### ISSUE TITLE
some command can't get any respon on freebsd 9.3 release

### ISSUE THREAD

**Issue by GanLuo96214** [PowerShell/Win32-OpenSSH#10]
it will print login announcement but cant use any command.

**Comment by jungle-boogie** [comment]
I'm able to login on a freebsd system from widows 7.

Check your sshd config on freebsd machine.

**Comment by GanLuo96214** [comment]
$ ls
ls
$ ls -la
ls -la
total 52
drwxr-xr-x  5 local_test  wheel  512 Aug 17 09:46 .
drwxr-xr-x  5 root        wheel  512 Apr  2  2015 ..
drwx------  3 local_test  wheel  512 Aug 17 09:46 .config
-rw-r--r--  1 local_test  wheel  967 Mar 30  2015 .cshrc
drwx------  3 local_test  wheel  512 Aug 10 09:07 .emacs.d
-rw-r--r--  1 local_test  wheel  251 Mar 30  2015 .login
-rw-r--r--  1 local_test  wheel  162 Mar 30  2015 .login_conf
-rw-------  1 local_test  wheel  378 Mar 30  2015 .mail_aliases
-rw-r--r--  1 local_test  wheel  335 Mar 30  2015 .mailrc
-rw-r--r--  1 local_test  wheel  747 Mar 30  2015 .profile
-rw-------  1 local_test  wheel  280 Mar 30  2015 .rhosts
-rw-r--r--  1 local_test  wheel  977 Mar 30  2015 .shrc
drwxr-xr-x  3 local_test  wheel  512 Aug  6 14:30 .subversion

**Comment by GanLuo96214** [comment]
just like this

**Comment by GanLuo96214** [comment]
sry my mistake
