### ISSUE TITLE
Easy installation

### ISSUE THREAD

**Issue by szepeviktor** [PowerShell/Win32-OpenSSH#100]
Would it be possible to write a Powershell script that downloads and installs the latest GitHub release?

**Comment by szepeviktor** [comment]
:disappointed: I speak no Powershell.

**Comment by h0rnman** [comment]
If the binary could be put into a static location that was updated every time a new build was done, it's pretty easy.  That said, I already have this script built, but I don't use GitHub enough to know how to submit it without cloning the entire repo.  Here is what I put together:
```powershell
function Install-OpenSSHWin() {

	function Get-UserAdminStatus() {
		return ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")
	}

	if (Get-UserAdminStatus) {

		$URL = "https://github.com/PowerShell/Win32-OpenSSH/releases/download/11_09_2015/OpenSSH-Win32.zip"

		Add-Type -Assembly System.IO.Compression.FileSystem

		Invoke-WebRequest -Uri $URL -OutFile "$env:temp\OpenSSH-Win32.zip"
		[System.IO.Compression.ZipFile]::ExtractToDirectory("$env:temp\OpenSSH-Win32.zip","$env:ProgramFiles")
		
		Invoke-Expression "netsh advfirewall firewall add rule name='SSH Port' dir=in action=allow protocol=TCP localport=22"

		Set-Location "$env:ProgramFiles\OpenSSH-Win32"
		& ".\ssh-keygen.exe " "-A"
		& ".\sshd.exe" "install"
		
		Set-Service -Name "SSHD" -Description "SSH Service for Windows" -StartupType Automatic
		Start-Service SSHD
	}

	else {
		Write-Host "This script must be run as an Administrator"
	}
}
Install-OpenSSHWin
```

I've only tested on my Win7x64 machine, but I tried to stick with things that would work under Powershell 3+.  I left out the part enabling key-based auth, but anyone doing that is going to likely do everything by hand anyway.

**Comment by szepeviktor** [comment]
Thank you very much.
Few things to make it better
- get latest release GitHub release ZIP: 32/64
- detect OS version: 32/64 bit (`$env:ProgramFiles"`)
- copy DLL
- detect errors

**Comment by szepeviktor** [comment]
@h0rnman You can use GitHub with your browser: edit/add/remove files, make commits, PR-s.

**Comment by manojampalam** [comment]
Thanks for the script @h0rnman. I'll work on getting a static link this weekend.

**Comment by bazzilic** [comment]
There's also a Chocolatey package in the repository, so you can use `cinst win32-openssh` and voila.

**Comment by DarwinJS** [comment]
In addition to the chocolatey package I wrote direct install scripts just like the op is asking for...

This is already done.  ( If you don't mind, having chocolatey automatically installed inline)

These run in an elevated powershell prompt and they will complete without any prompts:

Install w/ the server:

```
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {[bool]1};set-executionpolicy RemoteSigned -Force -EA 'SilentlyContinue';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/DarwinJS/ChocoPackages/master/win32-openssh/InstallChoco_and_win32-openssh_with_server.ps1'))
```

Without Server:

```
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {[bool]1};set-executionpolicy RemoteSigned -Force -EA 'SilentlyContinue';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/DarwinJS/ChocoPackages/master/win32-openssh/InstallChoco_and_win32-openssh.ps1'))
```

**Comment by maertendMSFT** [comment]
Check out the instructions here: https://github.com/PowerShell/Win32-OpenSSH/wiki/How-to-retrieve-links-to-latest-packages
Inside the zip there is a ps1 for the installation
