### ISSUE TITLE
Cant install ssh

### ISSUE THREAD

**Issue by shadhin16121996** [PowerShell/Win32-OpenSSH#1000]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**
Windows 10
**What is failing**
ssh files not instaling
**Expected output**
suppose to install
**Actual output**
not installing this always shows up
S C:\Program Files\OpenSSH> powershell -ExecutionPolicy Bypass -File install-sshd.ps1
The argument 'install-sshd.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
Windows PowerShell

**Comment by bagajjal** [comment]
You might not have sufficient permissions to install-sshd.ps1

**Comment by bagajjal** [comment]
Please reopen of required..
