### ISSUE TITLE
ssh-keygen.exe types DSA, ECDSA, RSA not supported

### ISSUE THREAD

**Issue by byronigoe** [PowerShell/Win32-OpenSSH#1001]
Please answer the following

**"OpenSSH for Windows" version**
Beta
 
**Client OperatingSystem**
Windows 10 Pro

**What is failing**
ssh-keygen lists various unusable encryption types in the help output:
usage: ssh-keygen [-q] [-b bits] [-t dsa | ecdsa | ed25519 | rsa]
                  [-N new_passphrase] [-C comment] [-f output_keyfile]
Try to use anything but ed25519 and it fails.

**Expected output**
Successful generation of a key pair.

**Actual output**
unknown key type dsa
unknown key type rsa
unknown key type ecdsa

**Comment by bagajjal** [comment]
Looks like you are using the windows inbox version of openssh.  If yes the this is expected.. The initial version has support for only ed25519.. 

You can try our github version that has latest and greatest version..

**Comment by bagajjal** [comment]
Reopen if required

**Comment by iamakulov** [comment]
Should I expect Windows to eventually update the inbox SSH version to match the GitHub one? If yes, do you know when this could be expected?

(I’m particularly interested in RSA support.)

**Comment by bagajjal** [comment]
Yes, it will be in our next release.. I guess the next release is in April..

**Comment by p0lar-bear** [comment]
I just downloaded and installed the 1.0.0.0 release as per the instructions, and `Get-Command` tells me that the `ssh-keygen` being used is the one in `C:\Program Files\OpenSSH\`, yet it's telling me that RSA isn't supported as above.

**Comment by bagajjal** [comment]
Are you sure you are using 1.0.0.0?

**Comment by p0lar-bear** [comment]
...Nope. I thought I was but I misread the output of Get-Command, it was using 0.0.18.0. Disregard.
