### ISSUE TITLE
Issue with Nano

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#1004]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
This is OpenSSH Beta installation via Windows Optional Features 
Output for ((Get-Item (Get-Command **ssh**).Source).VersionInfo.FileVersion)
0.0.18.0
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 Pro

**Client OperatingSystem**
Ubuntu 16.04.3 LTS 

**What is failing**
Cannot save new content to existing or new file using nano. However vi seems to work fine.
Pressing enter to save with same or new file name does not work or go back to the CLI.

Same issue was reported previously https://github.com/PowerShell/Win32-OpenSSH/issues/861?_pjax=%23js-repo-pjax-container

**Expected output**
The save file screen accepts the Enter key

**Actual output**
Bell sound plays in Windows instead

**Comment by bagajjal** [comment]
Please wait for the next windows update or use the latest github version..

**Comment by ghost** [comment]
Thanks for your reply, not much of a solution. I will go back to using Putty. Cheers

**Comment by DANIELG1952** [comment]
The issue with the enter key in nano can be bypassed. In the /etc folder there is the “nanorc” file in which we can remap some keys. At the end of the file I added 2 lines:
bind ^S savefile main
bind ^E enter all
When I edit a file with nano I can use ^S to save the file or ^O and ^E. And to use the enter function (break to new line) in the text I use ^E.

**Comment by DANIELG1952** [comment]
Another solution is to install the latest OPENSSH from 
http://www.mls-software.com/opensshd.html
OPENSSL by Microsoft is 7.5 and here we become 7.6.
This version has no problem with the keyboard at all.
