### ISSUE TITLE
Server port selecting does not work on scp.exe

### ISSUE THREAD

**Issue by ZURYB** [PowerShell/Win32-OpenSSH#1006]
Using "-P" on the command line for scp.exe to select the server port does not work. It attempts to connect to port 22.

**"OpenSSH for Windows" version**
scp.exe v0.0.24.0
 
**Client OperatingSystem**
Windows 7 x64 SP1 + security patches

**What is failing**
`scp -P 12345 -i x:\key\mykey.key user@1.2.3.4:/home/user/upload/* x:\download`

**Actual output**
`ssh: connect to host 1.2.3.4 port 22: Connection timed out`

**Comment by bagajjal** [comment]
@ZURYB - Thanks for reporting.. please wait for the next release (Jan-Mid).
Meanwhile, you can use the attached private scp binary.

[scp_nondef_port_fix.zip](https://github.com/PowerShell/Win32-OpenSSH/files/1599067/scp_nondef_port_fix.zip)

**Comment by mphilipps** [comment]
After running into this issue we worked around it by using -o "Port number".

**Comment by bingbing8** [comment]
this is fixed as part of https://github.com/PowerShell/openssh-portable/pull/258
