### ISSUE TITLE
New-NetFirewallRule on Win10

### ISSUE THREAD

**Issue by szepeviktor** [PowerShell/Win32-OpenSSH#101]
Could it be that Win10Pro has no `New-NetFirewallRule` Cmdlet?

**Comment by szepeviktor** [comment]
I've tried `Get-Command *firewall*`.

**Comment by h0rnman** [comment]
New-NetFirewallRule is for servers only.  If you're on a workstation, try:
```
netsh advfirewall firewall add rule name='SSH Port' dir=in action=allow protocol=TCP localport=22
```

**Comment by szepeviktor** [comment]
Thanks.
I'll put it into the Wiki.

**Comment by szepeviktor** [comment]
Added: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by martinpauly** [comment]
netsh advfirewall firewall add rule name='SSH Port' dir=in action=allow protocol=TCP localport=22
The blank in name is not accepted, the Wiki entry it is correct:
netsh advfirewall firewall add rule name=sshd dir=in action=allow protocol=TCP service=sshd
