### ISSUE TITLE
Is this project the same as the Windows "optional feature"?

### ISSUE THREAD

**Issue by FranklinYu** [PowerShell/Win32-OpenSSH#1012]
I found that in my Windows 10 there are optional features called OpenSSH Client (Beta) and OpenSSH Server (Beta). Is that the same as this project?

![optional-feature](https://user-images.githubusercontent.com/3153452/34831248-67ce4ad6-f6b4-11e7-87bd-5bf55dcfe529.PNG)

**Comment by bagajjal** [comment]
Yes

**Comment by FranklinYu** [comment]
Shall we mention it in Wiki? Or it is but I missed it?

**Comment by bagajjal** [comment]
Thanks, updated our wiki https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Status

**Comment by FranklinYu** [comment]
Is that one lagged behind? According to the blog, it only supports ED25519, so no RSA key.

**Comment by bagajjal** [comment]
Yes. GitHub will have latest binaries.
Windows will take its own schedule so it will always have a older version.
