### ISSUE TITLE
Username in ssh client

### ISSUE THREAD

**Issue by KarlM256** [PowerShell/Win32-OpenSSH#1013]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)` 0.0.24.0
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)` Windows 10 Pro (with Cygwin OpenSSH)

**Client OperatingSystem** Windows 10 Pro

**What is failing** Using client without ssh-agent

**Expected output** prompt for passphrase

**Actual output** failed to connect

So when I generate a key pair for a user alice on machine bob in a workgroup (not domain), the name shows up in the public key as alice@bob@BOB. This seems wrong, and should just be alice@bob or alice@BOB. By the way, the RSA key has a passphrase.

Then when I try "ssh fred" (without using the ssh-agent) it is not taking my key and falling back to password auth. But if I try " ssh -l alice bob" it prompts me for my passphrase and works fine.

Using the ssh client with without ssh-agent requires the passphrase every time but avoids the privilege escalation problem.

**Comment by manojampalam** [comment]
Agree that alice@bob@BOB is wrong. 

Otherwise, key based authentication should work without ssh-agent. Please share your client side traces (ssh -vvv)

**Comment by bagajjal** [comment]
Any update?

**Comment by manojampalam** [comment]
User name part should be fixed in the next release

**Comment by KarlM256** [comment]
Thanks
