### ISSUE TITLE
Using ssh client from Unison.

### ISSUE THREAD

**Issue by KarlM256** [PowerShell/Win32-OpenSSH#1014]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)` 0.0.24.0
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)` Windows 10 Pro

**Client OperatingSystem** Windows 10 Pro

**What is failing** invoking ssh from Unison

**Expected output** to work and invoke ssh to run a remote command.

**Actual output** 
Error in starting shell connection:
No such file or directory [create_process(ssh)]

Everything is in the PATH as expected. From the (non elevated) command line ssh -l alice bob "ls -l" works fine to a machine with Cygwin. Unison works fine with the Cygwin ssh (OpenSSH) client.

Thanks

**Comment by manojampalam** [comment]
Did you try setting the machine wide PATH to include ssh directory path?

**Comment by bagajjal** [comment]
Any update?

**Comment by gfb1** [comment]
Updates, anyone?
Windows to Linux ssh server. command line ssh works, but identical error when invoking ssh from Unison.

**Comment by bagajjal** [comment]
@gfb1 - Please share ssh logs (ssh -vvv user@ip) and sshd.logs (DEBUG3 enabled).

**Comment by gfb1** [comment]
![image](https://user-images.githubusercontent.com/37376662/37461577-2808e260-2825-11e8-8dc4-ebf374051e00.png)

all prior notations are repetitive....

**Comment by manojampalam** [comment]
debug3: failed to open file:/dev/tty error:3

This is normally not expected. Do you have DISPLAY and SSH_ASK_PASS variables set in your environment?

**Comment by gfb1** [comment]
No, I do not. I'll have to look up how to set them.  Thanks!

**Comment by manojampalam** [comment]
You should not have them set of you intend to type in your password manually

**Comment by bagajjal** [comment]
@gfb1 - Have a look at the sshd.log (With DEBUG3 enabled).

**Comment by Magneticdud** [comment]
the problem is that windows 10 ssh.exe can't be invoked by this app, as instead plink and cygwin ssh can be invoked. Example:

![immagine](https://user-images.githubusercontent.com/2940598/45189899-72954580-b23b-11e8-9c43-8086f5567853.png)

it's not a path problem, because it can't find it even if i force the full path via argument:

![immagine](https://user-images.githubusercontent.com/2940598/45189928-9193d780-b23b-11e8-844f-886e7aa79ae9.png)

**Comment by bagajjal** [comment]
@Magneticdud - can you try path in unix style (C:/windows/system32/OpenSSH/ssh.exe).
Look at the implementation of create_process().. It's a win32 API.

**Comment by Ede123** [comment]
I'm seeing the same issue in Unison 2.48.3.

Adding `C:/windows/system32/OpenSSH` to path and running Unison resulted in `No such file or directory [create_process(ssh)]`.

What worked however was copying "ssh.exe" to the Unison directory.

**Comment by maertendMSFT** [comment]
Looks like this is an issue in Unison with starting ssh.exe

**Comment by AntonKrug** [comment]
For the text variant of unison, you can invoke it with -sshcmd and provide custom path to the ssh binary. I think there should be way to change your unison profile to maybe have that by default (working from the GTK/GUI version too), however copying the openssh into the folder works too.

**Comment by Magneticdud** [comment]
I confirm that the latest version of unison works fine with the windows 10 openssh client, no more workarounds needed

**Comment by gfb1** [comment]
Thanks for your reply.
I just had to replace my laptop, so this was very timely!

guy

Sent from the road:
G.F. Barbato,  Ph.D.
