### ISSUE TITLE
Windows could not start the sshd service on Local Computer.

### ISSUE THREAD

**Issue by DFazeli** [PowerShell/Win32-OpenSSH#1015]
I have windows server 2016 ver 1607. downlaod latest ver ssh (0.0.24.0). then i installed. 
1 )
 ```
PS C:\Program Files\OpenSSH-Win64> .\install-sshd.ps1
[SC] SetServiceObjectSecurity SUCCESS
[SC] ChangeServiceConfig SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
sshd and ssh-agent services successfully installed
``` 
2 )
 ```
PS C:\Program Files\OpenSSH-Win64> .\ssh-keygen.exe -A
PS C:\Program Files\OpenSSH-Win64> ssh-keygen.exe genrate new host key : ....
```
3 ) start service sshd 

but I have an error 
```
---------------------------
Services
---------------------------
Windows could not start the sshd service on Local Computer.
Error 1067: The process terminated unexpectedly.
---------------------------
OK   
---------------------------
```
Please explain complete. how can I install sshd on win 2016 server? 
I want setup sftp server. 
Thanks a lot.

**Comment by bagajjal** [comment]
You missed to fix the host key permissions.
Please follow the install instructions here 
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by manojampalam** [comment]
Reopen if you still see this issue

**Comment by dfmuscat** [comment]
This is fine for install-win32 but what about the X64 version. All the blogs/comments are for 32bit. I do not hear anything from the contributors for X64 platform, Not sure if 64bit is being addressed

**Comment by bagajjal** [comment]
@dfmuscat - We support all the platforms (X86, X64, ARM-32, ARM-64).

**Comment by breakndenter** [comment]
It might not be related but i manage to start the service after exiting Openvpn and Plex  and stopping the respective services. I tried to replicate to see witch one after restart , uninstall etc but since that everything was smooth sailing and the pesky error never appeared on my machine again.

**Comment by s2zaman** [comment]
The 64bit version too is working now.
I suspect it is a permissions issue with 64bit version only.

Thanks @amakhno for [pointing it out](https://github.com/PowerShell/Win32-OpenSSH/issues/55#issuecomment-441172900).

The `FixHostFilePermissions.ps1` powershell script residing at `C:\Program Files\OpenSSH-Win64\FixHostFilePermissions.ps1` resolved the error `The OpenSSH SSH Server service terminated unexpectedly`.

The **sshd** service is now starting successfully.
Can be found in services with the **OpenSSH SSH Server** as display name.

**Comment by MBetters** [comment]
Please note on the [installation instructions page](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH) that the 64-bit version sometimes requires you to run `FixHostFilePermissions.ps1` in an elevated PowerShell before `net start sshd` works.
