### ISSUE TITLE
ssh-keygen "Too many arguments" when running in powershell

### ISSUE THREAD

**Issue by MartinSGill** [PowerShell/Win32-OpenSSH#1017]
Please answer the following

**"OpenSSH for Windows" version**
Built from source:

commit 1ad6c956ccbd4a48765b8fc537127f2b58b64e08 (HEAD -> L1-Prod, tag: 0.0.24.0, origin/L1-Prod, origin/HEAD)
 
**Server OperatingSystem**
N/A

**Client OperatingSystem**
Reproduced on:
- Win10 (1709, OS Build 16299.192)
- windowsservercore   1709

**What is failing**

ssh-keygen.exe -t dsa -N "" -f stuff

**Expected output**

A new key file

**Actual output**

"Too many arguments."

**Steps to Reproduce**

This issue only seems to happen if running in powershell, not if running in CMD.

For example: 

```
CMD> ssh-keygen.exe -t dsa -N "" -f stuff
Generating public/private dsa key pair.
Your identification has been saved in stuff.
Your public key has been saved in stuff.pub.
The key fingerprint is:
<redacted>
The key's randomart image is:
+---[DSA 1024]----+
|         .o.ooo. |
|         . ...o .|
|          .o.= o |
|       *  o+= +  |
|      * S o+o+ o |
|       o .  o=+..|
|        ..o.ooo..|
|        .=....o .|
|      .o..*oo*oEo|
+----[SHA256]-----+
```

```
PS> .\ssh-keygen.exe -t dsa -N "" -f stuff
Too many arguments.
usage: ssh-keygen [-q] [-b bits] [-t dsa | ecdsa | ed25519 | rsa]
                  [-N new_passphrase] [-C comment] [-f output_keyfile]
```

Reproduced in both PS 5.1 and PS-Core 6.0

**Comment by DarwinJS** [comment]
@MartinSGill - Like you, I think it would be best if this worked out of the box.

Here is a workaround that will at least make it work in PowerShell.

It uses the powershell "stop-parsing" operator `--%` described here: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing

```
ssh-keygen.exe --% -t dsa -N "" -f stuff
```
This also works and is more self-documenting:
```
start-process -nonewwindow ssh-keygen -argumentlist '-t dsa -N "" -f stuff'
```

**Comment by MartinSGill** [comment]
Well now that you've pointed it out... I can see the problem... it's the -f  alias for string.format.

I guess that's why PS has the --% operator.

Thanks for clearing that up. Still think it's a bug though... not sure if it's a Powershell or OpenSSH bug though...

**Comment by manojampalam** [comment]
This is by design (in Powershell). If you don't think so, please follow up with Powershell team/project.

**Comment by MartinSGill** [comment]
It would be convenient if an alias were provided, but I agree, it's by design, annoying as it is.

**Comment by himanshukumar4** [comment]
Too many arguments.
usage: ssh-keygen

this is as per design in powershell , got this error and resolved as mentioned ablve.

**Comment by Tar-M-0102** [comment]
It seems like you are encountering an error when running the ssh-keygen command. The error message suggests that there are too many arguments provided.

To generate an SSH key using the ssh-keygen command on Windows, follow these steps:

    Open the Command Prompt or PowerShell.
    Run the following command to generate an SSH key:

    ssh-keygen -t ed25519 -C "your@email.com"

    Make sure to replace "your@email.com" with your actual email address.
    It will prompt you to enter a file name to save the key. Press Enter to accept the default location (C:\Users\YourUsername\.ssh\id_ed25519) or specify a different location if desired.
    It will then prompt you to enter a passphrase. You can either enter a passphrase or leave it blank by pressing Enter. Note that using a passphrase adds an extra layer of security to your key.
    Once the key is generated, it will display a message confirming the location of the public and private key files.
