### ISSUE TITLE
Page Up/Down in vim doesn't work

### ISSUE THREAD

**Issue by jabdr** [PowerShell/Win32-OpenSSH#1018]
**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**
Setting TERM to xterm has no effect.

**"OpenSSH for Windows" version**
0.0.18.0
 
**Server OperatingSystem**
Ubuntu 16 LTS

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
Page Up and Page Down in vim on the server.

**Expected output**
Scroll up or down in the document that is opened with vim. 

btw: This does work if I am using the ssh client from ubuntu/wsl.

**Actual output**
It does nothing.

**Comment by bagajjal** [comment]
Please check this in the latest release

**Comment by jabdr** [comment]
It works with the latest release. I used the optionalfeature installation of Windows 10. I thought this would install the latest version. Sorry.
