### ISSUE TITLE
permission parent folder.

### ISSUE THREAD

**Issue by DFazeli** [PowerShell/Win32-OpenSSH#1019]
I install openssh and I can connect to ssh (terminal) and WinSCP with password and key.
How do I change the access so that the user can not access the parent folders?
for example, i have sftpuser, and log in with this user I don't want this user to be able to access parent folders.
thanks.

**Comment by bagajjal** [comment]
Windows OS doesn't provide the CHROOT functionality. In order to achieve this you need to use the windows security model. You can provide access to individual folders in combination with creating windows distribution list/groups

**Comment by DFazeli** [comment]
@bagajjal You may also be interested in how to set up access to Windows? Is there a training on this topic on YouTube or etc?
thanks a lot

**Comment by bagajjal** [comment]
No... Windows folder properties will allow you to provide the secured restricted access..

**Comment by DFazeli** [comment]
:) thanks @bagajjal . I solved it.

```
perm@WIN-SPKTE2V2UQN C:\Users\perm>cd ..                                                                                        
Access is denied.                                                                                                               
perm@WIN-SPKTE2V2UQN C:\Users\perm>                                                                                             
```
