### ISSUE TITLE
Support Zlib (DEFALTE) compression

### ISSUE THREAD

**Issue by agx** [PowerShell/Win32-OpenSSH#102]
```
ssh -v  -ocompression=yes witz
OpenSSH_7.1p2 Debian-2, OpenSSL 1.0.2f  28 Jan 2016
...
debug1: Next authentication method: password
Administrator@10.0.1.16's password: 
debug1: Enabling compression at level 6.
debug1: Authentication succeeded (password).
Authenticated to 10.0.1.16 ([10.0.1.16]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
packet_write_wait: Connection to 10.0.1.16: Broken pipe
```

Login succeeds with -ocompression=no (and the other WA mentioned on the web (ControlMaster no))

**Comment by manojampalam** [comment]
Compression in currently disabled. You can it in a private build by setting WIN32_ZLIB_NO to 0 on config.h. This requires building and linking againt Zlib binaries though.

**Comment by pvdhoef** [comment]
It appears that compression works now with Win32-OpenSSH-0.0.12.0.

See https://github.com/mitchellh/vagrant/issues/8076

Thanks a lot!

**Comment by manojampalam** [comment]
I don't think it does. Win32 port is built with compression disabled. The command line options is probably getting ignored.

**Comment by pvdhoef** [comment]
I see. I jumped to conclusions, apologies for the confusion. 
Anyway, I'm happy to be able to use `vagrant ssh` now without workarounds.

**Comment by maertendMSFT** [comment]
This is fixed in the latest release.
