### ISSUE TITLE
Are there any installation instructions yet?

### ISSUE THREAD

**Issue by ylluminate** [PowerShell/Win32-OpenSSH#1020]
I think many of us would like to use OpenSSH on Windows to provide a full system SSHD style service. It would be nice to use `sftp` and `ssh` to do Windows business with both `cmd.exe` and `bash`. 

Has anyone worked up some installation and usage instructions yet that facilitates this in the current state of the project?

**Comment by SourceryOne** [comment]
WinSCP provides a good installation instruction/tutorial here (to answer part of your question):
https://winscp.net/eng/docs/guide_windows_openssh_server

**Comment by bingbing8** [comment]
@ylluminate , please check out the [Install Instructions](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH)
