### ISSUE TITLE
Publickey authentication fails for domain accounts

### ISSUE THREAD

**Issue by Bruinbrum** [PowerShell/Win32-OpenSSH#1022]
For domain accounts public key authentication fails even though keys match.

The workaround is to connect using the domain, e.g.
ssh \<DOMAIN\>\\\<USER\>\@\<windows box\>

This needs to be clarified in the documentation - or some workaround allowing the windows box to identify the domain.

This is with OpenSSH for Windows 0.0.24.0

**Comment by Cambridgeport90** [comment]
Thanks for the clarification; I was wondering that. Haven’t yet enabled SSH on my servers, though I plan to use it soon in place of PSRemoting when possible.

**Comment by bagajjal** [comment]
Its already documented..
https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples
