### ISSUE TITLE
Please use semantic version numbers

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/Win32-OpenSSH#1026]
I don't understand how any software can go from a 0.0.24 to 1.0.0 and then still put in their release notes that it's a "preview" version.  You're sending mixed messages at best...

I'd like to ask that future versions follow something resembling [semver](https://semver.org/) ... properly marking pre-release versions in the version itself. A "pre-release"  that's "not production ready" being marked 1.0.0 --from a Microsoft team-- sends a dangerously confusing message.

**Comment by manojampalam** [comment]
Thank you for your feedback. We did a major version jump due to significant underlying changes in architecture, usage and troubleshooting scenarios - I've added Beta to release title, hoping to reduce the confusion a bit.

**Comment by NoMoreFood** [comment]
@manojampalam Since you guys are aligning to the OpenSSH versioning scheme, can't this be closed now?
