### ISSUE TITLE
WSL bash.exe as default ssh shell does not work

### ISSUE THREAD

**Issue by wlsfan** [PowerShell/Win32-OpenSSH#1028]
**"OpenSSH for Windows" version**
v1.0.0.0-Beta
 
**Server OperatingSystem**
Windows 10 Pro

winver -> Version 1709 (OS Build 16299.192)

**Client OperatingSystem**
Any

**What is failing**
According to the latest instructions, one can use WLS bash.exe as the default shell.

C:\Users\user>reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Openssh"

HKEY_LOCAL_MACHINE\SOFTWARE\Openssh
    DefaultShell    REG_SZ    c:\Windows\System32\bash.exe

**Expected output**
WLS bash.exe shell login

**Actual output**
cmd.exe shell login

**Comment by asterikx** [comment]
For me it does have an effect. Unfortunately the connecting client gets the error message ```Error: 0x80070005 Press any key to continue...```. Looks like it's a permission issue, but not sure what it is about. Holds for `bash.exe` as well as for `wsl.exe`.

@wlsfan Did you set the key for `HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH\Agent` by accident? Happened to me in the first place.

**Comment by wlsfan** [comment]
@asterikx I did not set the Agent key.

**Comment by bagajjal** [comment]
I have created the private [ssh-shellhost binary](https://github.com/PowerShell/Win32-OpenSSH/files/1537389/ssh-shellhost-DefaultShell-Issue.zip). Please use this binary (backup, replace existing ssh-shellhost.exe with my private ssh-shellhost.exe), it will show error message and the configured default shell..
1) Use "Get-DefaultShell" command display the default shell. Please note that this is a private command and not a powershell command.
2) Over the ssh client, just to make sure please issue "reg query "HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH" /v DefaultShell" command that shows the registry value.

Here is how it looks,
![image](https://user-images.githubusercontent.com/23668037/33692901-8f6deb2c-daa4-11e7-8361-d2d4699a8fa7.png)

**Comment by wlsfan** [comment]
I replaced the existing ssh-shellhost.exe with your private ssh-shellhost.exe and rebooted.

Note, the Get-DefaultShell was not included in the ssh-shellhost-DefaultShell-Issue.zip.
Also I did not see an error message.  I don't know if this matters but the ssh-shellhost.exe provided shows a File version: 0.0.23.0.  Here is the output of the client:

![image](https://user-images.githubusercontent.com/35668147/35365412-79990ee8-0142-11e8-8fc7-877733b91cde.png)

**Comment by bagajjal** [comment]
I tried on my side, it worked..
can you give a try one more time. After you do ssh, copy & paste "Get-DefaultShell" instead of typing.

**Comment by wlsfan** [comment]
I did a copy and paste with same result...

![image](https://user-images.githubusercontent.com/35668147/35366135-e3ce52a2-0145-11e8-98de-ea34727f644b.png)

**Comment by wlsfan** [comment]
I also tried it with the "" and with putty client.

![image](https://user-images.githubusercontent.com/35668147/35366286-a2cb390e-0146-11e8-838e-fe3ccbdbea17.png)

**Comment by bagajjal** [comment]
Are you sure you are using my private ssh-shellhost binary?

**Comment by wlsfan** [comment]
I am pretty sure.  Here is the listing:

![image](https://user-images.githubusercontent.com/35668147/35366505-e0717290-0147-11e8-9a58-9aefb583e2f2.png)

**Comment by bagajjal** [comment]
@wlsfan - It's my private binary. Not sure why its not working.
I have created another private binary, please try this.

1) Move existing ssh-shellhost.exe to ssh-shellhost_bkup.exe
2) Copy my **new** [private binary](https://github.com/PowerShell/Win32-OpenSSH/files/1669555/ssh-shellhost-default-shell-debug.zip) to your binary location (C:\program files\openssh). 
3) launch the ssh with no-pty session, "ssh -T user@ip"
4) It should dump the error code if it fails. 
Here is the snapshot,
![image](https://user-images.githubusercontent.com/23668037/35465895-49067838-02b4-11e8-9d77-2b00af12f762.png)
![image](https://user-images.githubusercontent.com/23668037/35465913-5e297fb2-02b4-11e8-897a-d85265db0731.png)

**Comment by wlsfan** [comment]
No error code on connect but when I issued the Get-DefaultShell I get the following message:

![image](https://user-images.githubusercontent.com/35668147/35468153-693d33bc-02e6-11e8-8311-3d34d620f86d.png)

**Comment by JadedDragoon** [comment]
Through my own troubleshooting, this appears to be a problem with Component Services permissions... at least on my system. I'm not certain this is the case... it could be coincidence, but I thought I'd share.

In my case there is an error in Event Viewer in `Windows Logs` > `System` about this. The source will be "DistributedCOM". It will look something like this:
![screenshot 2018-01-28 09 52 01](https://user-images.githubusercontent.com/1294429/35484130-49bb9aca-0411-11e8-916c-59c6188da606.png)
For me, this error appears in Event Viewer each time I try to connect remotely while bash.exe is set as my default shell.

The issue appears to be that this component (appid {E82567AE-2EA4-4DBC-BC68-8B0A0526D8D5} on my system) cannot be started by bash.exe. The error says it lacks local activation permission but when I check in `Component Services` > `DCOM Config` I see this:
![screenshot 2018-01-28 10 12 07](https://user-images.githubusercontent.com/1294429/35484296-c1593306-0413-11e8-90ca-f3d40422295e.png)
![screenshot 2018-01-28 10 10 13](https://user-images.githubusercontent.com/1294429/35484279-780d976e-0413-11e8-95d6-54a1770daf08.png)

**Comment by wlsfan** [comment]
I reinstalled Ubuntu on the server side and now when I ssh into the server with no-pty-session  I see the default configured shell however I see no prompt and my commands are just echoed back.  See below:

![image](https://user-images.githubusercontent.com/35668147/35484899-28e0451c-0425-11e8-9a95-9d3743eda67d.png)

When I ssh without the -T option I now receive the following error:

![image](https://user-images.githubusercontent.com/35668147/35484905-4f52776a-0425-11e8-896c-00d2e44ab4cb.png)

**Comment by wlsfan** [comment]
As JadedDragoon pointed out I also see the error message in the event viewer:

![image](https://user-images.githubusercontent.com/35668147/35484960-449bf0c0-0426-11e8-9d2b-70af0b1973f6.png)

**Comment by bagajjal** [comment]
@wlsfan  - WSL has fixed this error. 
Here is the WSL issue,
https://github.com/Microsoft/WSL/issues/2322

**Comment by bagajjal** [comment]
Also have a look at this,
https://github.com/PowerShell/Win32-OpenSSH/issues/289

**Comment by bagajjal** [comment]
Please reopen if required.
