### ISSUE TITLE
scp -3 fails

### ISSUE THREAD

**Issue by jps-aldridge** [PowerShell/Win32-OpenSSH#1029]
I executed

   scp -3 pi@sparepi.lan:a.txt pi@sparepi.lan:b.txt

I expected the file to be copied, but instead I got the message

   dup() in/out/err failed

scp client version: 0.0.18.0 
client operating system: Windows 10 Pro
server operating system: Raspbian GNU/Linux 9 (stretch)

**Comment by manojampalam** [comment]
Please try out the latest version. There were recent changes to dup() functionality. Reopen if needed.

**Comment by jps-aldridge** [comment]
I downloaded the most recent version (scp.exe has File version = 1.0.0.0, and Date modified = 19-Jan-18 23:41). It no longer gives a 'dup() in/out/err failed', but instead hangs indefinitely until I give a Ctrl-C.

I can copy the file in both directions via an explicit local temporary file without problem:

`D:\>d:\OpenSSH-Win64\scp.exe pi@sparepi.lan:a.txt .\temp.tmp`
`a.txt`
` `
`D:\>d:\OpenSSH-Win64\scp.exe .\temp.tmp pi@sparepi.lan:b.txt`
`temp.tmp`

but doing the equivalent in one step

`D:\>d:\OpenSSH-Win64\scp.exe -3 pi@sparepi.lan:a.txt pi@sparepi.lan:b.txt`

just hangs.

**Comment by lupo1977** [comment]
I found at least one bug in scp.c related to the command line argument -3. It may also be related to the issue here.
This bug is inside the OpenSSH core code, so I guess it will make no sense to raise a PR for this?

**Comment by manojampalam** [comment]
Right. Use https://www.openssh.com/report.html to report issues in core code
