### ISSUE TITLE
Separate the binary path, cfg and logs path.

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/Win32-OpenSSH#1030]
Separate the binaries, cfg, logs path.

binaries - We suggest %programfiles%
cfg - %programData%\ssh
logs - %programData%\ssh\logs

**Comment by DarwinJS** [comment]
A quick note about using ProgramData folders.  By default inheritance subfolders of ProgramData are only permissioned for CREATOR OWNER, SYSTEM and Administrators.

This means that the user who ran the install will be the only non Administrator to be able to see the files. 

In large organizations there are IT workers that do not have full administrator rights when working on systems.

For this reason, it could be helpful to grant Read to Authenticated Users to the ssh subfolder.

**Comment by bagajjal** [comment]
We are creating folders with explicit ACLs (system, administrator group - full control and authenticated users - read & execute)..this is part of install-sshd.ps1
