### ISSUE TITLE
Fail to start sshd service on Win10.16299.64

### ISSUE THREAD

**Issue by LoSealL** [PowerShell/Win32-OpenSSH#1031]
Please answer the following

**If it is a terminal issue then please go through wiki
I don't think so

**"OpenSSH for Windows" version**
`1.0.0.0 beta`
`OpenSSH_7.6p1, LibreSSL 2.5.3`
 
**Server OperatingSystem**
`Windows 10.0.16299.64`

**Client OperatingSystem**
None

**What is failing**
net start sshd

**Expected output**

**Actual output**
>sshd 服务正在启动 .
sshd 服务无法启动。
系统出错。
发生系统错误 1067。
进程意外终止。

>sshd service can't start.
system error.
error code 1067

**Comment by bagajjal** [comment]
please check
1)%programData%\ssh\sshd_config - exists
2)%programData%\ssh\<host_keys> - exists
3)run .\FixHostFilePermissions.ps1 -Confirm:$false.

If it didn't work then run the sshd.exe in debug mode and debug further.. please have a look at the release notes.

**Comment by manojampalam** [comment]
Check troubleshooting wiki and reopen with relevant logs.
