### ISSUE TITLE
[SSH-KeyGen] ed25519 saving key pair fails when supplying passphrase

### ISSUE THREAD

**Issue by Velocet** [PowerShell/Win32-OpenSSH#1037]
**"OpenSSH for Windows" version**
`0.0.18.0`

**Server OperatingSystem**
 `N/A`

**Client OperatingSystem**
`Windows 10 Enterprise 10.0.16299.98 `

**What is failing**
 `ssh-keygen `

**Expected output**
 ```
Generating public/private ed25519 key pair.
Enter file in which to save the key (C:\Users\Velocet/.ssh/id_ed25519):
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in C:\Users\Velocet/.ssh/id_ed25519.
Your public key has been saved in C:\Users\Velocet/.ssh/id_ed25519.pub.
The key fingerprint is:
SHA256:VV7Lu9LLUXx+uj2w4kwMJ/T88297y6KO8Jx0VqKn2fM Velocet@CUBE@Cube
The key's randomart image is:
+--[ED25519 256]--+
|            . .  |
|           o o . |
|         .. . o  |
|        ..o    o |
|        So = .. +|
|          * +o +.|
|       . o *.o* o|
|        = %o =+*+|
|         Bo*=E*BO|
+----[SHA256]-----+
```

**Actual output**
 ```
Generating public/private ed25519 key pair.
Enter file in which to save the key (C:\Users\Velocet/.ssh/id_ed25519):
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Saving key "C:\\Users\\Velocet/.ssh/id_ed25519" failed: invalid argument
```

**Comment by bagajjal** [comment]
can you try like this,
ssh-keygen -t ed25519 -Z aes128-ctr

**Comment by Velocet** [comment]
Works fine when supplying a passphrase.

```
Generating public/private ed25519 key pair.
Enter file in which to save the key (C:\Users\Velocet/.ssh/id_ed25519):
C:\Users\Velocet/.ssh/id_ed25519 already exists.
Overwrite (y/n)? y
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in C:\Users\Velocet/.ssh/id_ed25519.
Your public key has been saved in C:\Users\Velocet/.ssh/id_ed25519.pub.
The key fingerprint is:
SHA256:bZpbAz8FGAj+ScT0NZj24zCRN+SxRDQnBUr5sWKw59A Velocet@CUBE@Cube
The key's randomart image is:
+--[ED25519 256]--+
|    .+o.oO%oo    |
|   . .+oBB+B     |
|    . .=+=++     |
|     oo.E.=.     |
|      o=S=o..    |
|        .*..     |
|        o =      |
|         o o     |
|        .        |
+----[SHA256]-----+
```

**Comment by bagajjal** [comment]
Yes its because openssh installed through windows feature on demand doesn't support LibreSSL. FYI, this is fixed in upcoming releases.

**Comment by Velocet** [comment]
I got this from "[Using the OpenSSH Beta in Windows 10 Fall Creators Update and Windows Server 1709](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/)".

Thanks for the clarification.

**Comment by vvavrychuk** [comment]
@bagajjal, thanks for sharing command (ssh-keygen.exe -t ed25519 -Z aes128-ctr). It works for me.

> FYI, this is fixed in upcoming releases.

How to install this upcoming release where `ssh-keygen` works without additional arguments?

BTW. https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse installs version 0.0.1.0 and here https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement ssh-keygen works with empty passphrase. No idea how because for me it gives an error reported in this issue.
