### ISSUE TITLE
[ssh-add] "No such process" when using PowerShell

### ISSUE THREAD

**Issue by Velocet** [PowerShell/Win32-OpenSSH#1038]
**"OpenSSH for Windows" version**
`0.0.18.0`

**Server OperatingSystem**
 `N/A`

**Client OperatingSystem**
`Windows 10 Enterprise 10.0.16299.98 `

**What is failing**
 `ssh-add`

**Expected output**
```PowerShell
PS ~\.ssh> ssh-add id_ed25519
Identity added: id_ed25519 (Velocet@CUBE@Cube)
```

**Actual output**
```PowerShell
PS ~\.ssh> ssh-add id_ed25519
Error connecting to agent: No such process
```

The same command running under cmd.exe works fine:
```BatchFile
C:\Users\Velocet\.ssh>ssh-add id_ed25519
Identity added: id_ed25519 (Velocet@CUBE@Cube)
```

A workaround would be to use `Start-Process`:
```PowerShell
Start-Process -FilePath 'ssh-add' -ArgumentList 'C:\Users\Velocet\.ssh\id_ed25519'
```

**Comment by bingbing8** [comment]
@Velocet , in powershell prompt, if you launch a file in the current directory, it is like below:
```
PS ~\.ssh> .\ssh-add id_ed25519
```
This is by design by powershell to launch any file in powershell.

**Comment by Velocet** [comment]
`ssh-add` is an application (in `$env:windir\System32\OpenSSH`) not a file or cmdlet. Afaik PowerShell uses by default the current path, so `.\` isn't needed normally.

The problem is not related to a wrong path but a missing connection to the service (`ssh-agent`) when called in PowerShell. Strange error 🤔 

```PowerShell
PS ~\.ssh> ssh-add .\id_ed25519
Error connecting to agent: No such process

PS ~\.ssh> .\ssh-add id_ed25519
The term 'ssh-add' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ .\ssh-add id_ed25519
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\ssh-add:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by bagajjal** [comment]
Looks like ssh-agent is not running. From an elevated command prompt, do "net start ssh-agent".
From task manager check if ssh-agent process is running. Then issue ssh-add command.

**Comment by Velocet** [comment]
ssh-agent is running otherwise it wouldn't work when invoked in `cmd.exe`. This seems to be a PowerShell specific problem. I also restarted the service with no effect.

```PowerShell
PS ~\.ssh> Get-Service -Name 'ssh-agent'

Status   Name               DisplayName
------   ----               -----------
Running  ssh-agent          ssh-agent
```

**Comment by manojampalam** [comment]
Can you ensure you are invoking the same ssh-add in both the cases? I'm guessing you have multiple versions of ssh-add (from different sources), and the wrong one is getting invoked when you do it via Powershell.
Also, check if this environment variable is set in your PS environment - SSH_AUTH_SOCK

**Comment by Velocet** [comment]
I also thought about that in the first place and checked which binary gets called. I do have git installed which comes with it's own `ssh-add.exe` binary but this one throws an error if called explicitly in the command prompt. So it's impossible that another ssh-add binary is called.
`SSH_AUTH_SOCK` isn't present in PowerShell or command prompt.

cmd.exe
```BatchFile
C:\Users\Velocet>where ssh-add
C:\Windows\System32\OpenSSH\ssh-add.exe
```
```BatchFile
C:\Program Files\Git\usr\bin>ssh-add.exe
Could not open a connection to your authentication agent.

C:\Users\Velocet\.ssh>ssh-add.exe
Identity added: id_ed25519 (Velocet@CUBE@Cube)
```

PowerShell
```PowerShell
PS ~> Get-Command -Name 'ssh-add.exe'

CommandType Name        Version  Source
----------- ----        -------  ------
Application ssh-add.exe 0.0.18.0 C:\WINDOWS\System32\OpenSSH\ssh-add.exe
```

```PowerShell
PS C:\Program Files\Git\usr\bin> .\ssh-add.exe
Error connecting to agent: Connection refused

PS ~\.ssh> ssh-add
Error connecting to agent: No such process
```

**Comment by jbruett** [comment]
Seeing this same issue in v7.6.1.0p1-Beta.  I've uninstalled git for windows and posh-git (known conflicts), and installed openssh using the instructions in the repo (install-sshd.ps1 from 'c:\program files\openssh') and set both services to automatic and started them.  When I try and run ssh-add it fails with the following error:

```
add-ssh : The term 'add-ssh' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ add-ssh
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (add-ssh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
I have no env vars that are populating any ssh defaults that I'm aware of.

**Comment by maertendMSFT** [comment]
ssh-add from Git is not compatible with our release of OpenSSH.
