### ISSUE TITLE
Save passphrase to the Windows credential store

### ISSUE THREAD

**Issue by mrmckeb** [PowerShell/Win32-OpenSSH#104]
I'd like to be able to save my passphrase to my Windows credential store. I have Windows 10, a device with Windows Hello and I'm confident that for the purposes I'm using this for, I can securely save my passphrase (or only be asked for it once per session).

Is this something that's possible now? Or is it coming?

**Comment by manojampalam** [comment]
This is not possible now but is something we plan on doing as Windows alternative to passphrase management. Check back end of March.

**Comment by mrmckeb** [comment]
Great, thanks. Looking forward to seeing it in March (or beyond).

**Comment by mrmckeb** [comment]
Hi @manojampalam, I was just interested in an update to this - I saw in the release logs for the last preview that you're working on "right security model and user experience for Windows", and wondered if that was related to this piece of work?

**Comment by manojampalam** [comment]
ssh-agent for Windows now provides persistent storage for user's private keys. Checkout 5_15_2016 release for further details. The user keys are not only encrypted using data protection APIs but are also protected from malware attacks.

**Comment by mrmckeb** [comment]
Amazing, thanks @manojampalam!
