### ISSUE TITLE
OpenSSH server in Windows PE

### ISSUE THREAD

**Issue by effebi68** [PowerShell/Win32-OpenSSH#1040]
I would like to use OpenSSH server (with public key auth) in Windows PE. After creating an sshd user, the daemon itself runs, but no other machine can see it (I used an nmap ARP scan on the same network); ssh.exe on the same box (using the Ethernet IP) negotiates the connection.

What am I missing?

**Comment by effebi68** [comment]
The problem above was due to DaRT internal firewall; nevertheless, even disabling it I still can't login as SYSTEM.

That said: any plan to support OpenSSH server in WinPE / WinRE / DaRT environments? I am pretty sure we are not the only ones looking for it (in our case, as a fallback whenever a proper deployment environment fails).

**Comment by manojampalam** [comment]
Right now, logging in as SYSTEM is not supported. You'll need to create a user account explicitly (not sure if that's possible on WinPE) and use those credentials.

**Comment by effebi68** [comment]
I am pretty sure users can be created, because I did it myself to install
OpenSSH daemon; I do not know whether they can log in, but I'll try that
for sure: getting OpenSSH running would be a pretty good reward.

Thanks a lot; best regards
Federico Bianchi

2018-01-29 18:59 GMT+01:00 Manoj Ampalam <notifications@github.com>:

**Comment by NoMoreFood** [comment]
@effebi68 Recently became interested in this project and looking for ways I can contribute.  Is there any further action requested on this line of discussion?  I'm pretty sure that you could create a user in Windows PE by using net user <username> <password> /add.  Did you test this?

**Comment by JW0914** [comment]
Users can be created in WinPE, but not for login to WinPE. 

- Log in to WinPE occurs via the default administrator account, or, if utilizing a WinPE image configured for WinRE, as a specific user apart of the Administrators group.
