### ISSUE TITLE
A specified port value is not valid.

### ISSUE THREAD

**Issue by robertmylne** [PowerShell/Win32-OpenSSH#1042]
I am following the instructions on `https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH`

When I get to `step 5` I try to run this command `netsh advfirewall firewall add rule name=sshd dir=in action=allow protocol=TCP localport=sshd` because I am on Windows 10 and I get this in response `A specified port value is not valid`

Am I meant to specify the port `localport=22` the docs are unclear on this.

**Comment by bagajjal** [comment]
Yes, it's a typo.
I corrected it.
