### ISSUE TITLE
Differences according to authentication

### ISSUE THREAD

**Issue by alberaguilarfdez** [PowerShell/Win32-OpenSSH#1047]
Hi

I just installed v1.0.0.0-Beta on a Windows Server 2012 R2 Datacenter. On the server I have also installed cygwin to have bash and I have created several mount points towards an external filesystem.

From a client I am able to authenticate correctly to the server, using both username/password and through public/private key. But there is a difference ... if I authenticate using username/password I access the content of the mount points without problems. If I authenticate using public/private keys it gives me an access denied error.

From what I have been able to read this problem it seems that it has also happened with the server sshd of cygwin.

Can you help me?

Regards.

**Comment by manojampalam** [comment]
This should help https://github.com/PowerShell/Win32-OpenSSH/issues/518

**Comment by alberaguilarfdez** [comment]
Thanks manojampalam. I understand then that it is not possible.

I tried to solve the problem by starting the sshd service with another user than the Local System (thus making an impersonalization; it would be a domain user), but although the sshd service starts, authentication does not work. The error that leaves in the log is:

4516 2018-01-31 10:41:36.798 debug1: Bind to port 22 on ::.
4516 2018-01-31 10:41:36.798 Server listening on :: port 22.
4516 2018-01-31 10:41:36.799 debug1: Bind to port 22 on 0.0.0.0.
4516 2018-01-31 10:41:36.799 Server listening on 0.0.0.0 port 22.
4436 2018-01-31 10:41:56.108 debug1: inetd sockets after dupping: 3, 3
4436 2018-01-31 10:41:56.108 Connection from X.X.X.X port 63816 on X.X.X.X port 22
4436 2018-01-31 10:41:56.110 debug1: Client protocol version 2.0; client software version OpenSSH_5.1
4436 2018-01-31 10:41:56.110 debug1: match: OpenSSH_5.1 pat OpenSSH_5* compat 0x0c000000
4436 2018-01-31 10:41:56.110 debug1: Local version string SSH-2.0-OpenSSH_7.6
4436 2018-01-31 10:41:56.111 error: unable to generate token for user sshd
4436 2018-01-31 10:41:58.373 error: unable to generate token on 2nd attempt for user sshd
4436 2018-01-31 10:41:58.373 error: unable to get security token for user sshd
4436 2018-01-31 10:41:58.373 error: posix_spawn failed
4436 2018-01-31 10:41:58.374 error: ssh_msg_send: write
4436 2018-01-31 10:41:58.374 fatal: send_rexec_state: ssh_msg_send failed
4436 2018-01-31 10:41:58.374 debug1: do_cleanup

I have added the local user sshd in different local security policies (create a token object, replace a process level token) but I still cannot access it. Is the start of the sshd service supported with a domain user to be able to impersonate?

Regards.

**Comment by salamoun** [comment]
I have same problem.
I want connect to server that is inside domain. I want to connect with AD account.
When using password all is working fine. When using public key auth, then I end with broken pipe error NetUserGetInfo() with domainController:  failed with error: 5.
So I try to change sshd running as domain admin account, but then I end with error: unable to generate token for user sshd.

So, is it possible to use OpenSSH server, with pub key auth and domain account?

**Comment by manojampalam** [comment]
SSHD needs to run as system.

At this point, its not possible to automatically get the double hop privileges using key based authentication.

**Comment by github-cygwin** [comment]
> From a client I am able to authenticate correctly to the server, using both username/password and through public/private key. But there is a difference ... if I authenticate using username/password I access the content of the mount points without problems. If I authenticate using public/private keys it gives me an access denied error.
> 
> From what I have been able to read this problem it seems that it has also happened with the server sshd of cygwin.

No, that's not true.  In Cygwin you can use three different types of creating a user token for switching the user context.  One of them allows immediate access to network shares.

For details, see https://cygwin.com/cygwin-ug-net/ntsec.html#ntsec-setuid-overview


Corinna

**Comment by NoMoreFood** [comment]
Corinna, I continue to be amazed by some of brilliant hacking that Cygwin has done to be as feature rich as it is.   Curious...  does Method 3 continue to work after Credential Guard is activated?

**Comment by github-cygwin** [comment]
> Curious... does Method 3 continue to work after Credential Guard is activated?

I don't know.  I'm reading of Credential Guard for the first time.  I guess somebody will have to test it :wink:

Corinna
