### ISSUE TITLE
Chocolatey Package for 1.0.0.0 Ready - Lotsa Changes

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#1048]
The Chocolatey Package for 1.0.0.0 is ready.
There were a lot of changes.
Install, Upgrade (from 0.0.24.0) and Uninstall were tested.
Install/Uninstall was tested on Windows 7 PSH 2, Windows 10, Nano RTM (no updates)
https://chocolatey.org/packages/openssh/1.0.0.0
Chocolatey Moderation is not quite complete as of this posting.

**Comment by bingbing8** [comment]
@DarwinJS Great job! I tried the package 1.0.0.0 on win2k12R2, install, uninstall, upgrade, migration work fine!

**Comment by bingbing8** [comment]
@DarwinJS, really appreciate your hard work on updating the chocolatey script especially for the upgrade scenarios. I tested the openssh chocolatey package on win2k12R2 data center, install, uninstall, upgrade, migration of file system and single sign on registration, they all work fine.  Great work!

**Comment by manojampalam** [comment]
@DarwinJS Release notes has a wrong link (to previous version)
Product release notes: https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.24.0

**Comment by DarwinJS** [comment]
@bingbing8 - thanks for testing and glad to hear it is working well!

I just pushed a new version (1.0.0.20180131) that fixes the release notes link and does not automatically configure ssh-agent when sshd service is being installed (can still be installed with the correct switch).

**Comment by stevehipwell** [comment]
There is an [issue](https://github.com/DarwinJS/ChocoPackages/issues/58) with this release related to the registry path `HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH` which appears to be missing in the latest version.

**Comment by bagajjal** [comment]
Yeah it's a bug as the registry creation logic is in ssh-agent. Ssh-agent is an optional component to run... As a workaround just start and stop the ssh-agent service.

**Comment by DarwinJS** [comment]
Should be fixed in 1.0.0.20180201 which was just pushed.

**Comment by wigster** [comment]
Just installed 7.6.1 (first ssh install) on Win10.

Running Start-Service ssh-agent results in error cannot find any service with that name.

**Comment by bagajjal** [comment]
@wigster - Try running .\uninstall-sshd.ps1, .\install-sshd.ps1

**Comment by DarwinJS** [comment]
@wigster - if you mean with the chocolately package you need to do this:

`choco install -confirm openssh -params "'/SSHAgentFeature"'`

It will be started for you.

**Comment by wigster** [comment]
Thanks, that worked!
