### ISSUE TITLE
Build without cygwin

### ISSUE THREAD

**Issue by Ono-Sendai** [PowerShell/Win32-OpenSSH#105]
For something that is supposed to be a port to Windows, it's regrettable that the build process (as described here: https://github.com/PowerShell/Win32-OpenSSH/wiki/OpenSSH-64-bit-Build-and-Installation-Instructions) requires Cygwin.

It would be good if this could be built with Visual studio without having mingw or Cygwin.

**Comment by manojampalam** [comment]
We do have VS support (just that wiki needs to be updated). Install VS 2015 Community edition and launch Win32-OpenSSH.sln at \Win32-OpenSSH\contrib\win32\openssh 
Also, while you are at it, can you please update the wiki :) ?

**Comment by Ono-Sendai** [comment]
I get errors like this when trying to build with vs2015:

4>D:\programming\Win32-OpenSSH-latest\includes.h(181): fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory

Presumably some kind of configure script needs to be run?

**Comment by manojampalam** [comment]
OpenSSL needs to be built first (in VS or some other means that can generate needed static libs). 
http://p-nand-q.com/programming/windows/building_openssl_with_visual_studio_2013.html has relevant instructions.
Once the libs are generated, you may need to modify paths.targets file (Win32-OpenSSH\contrib\win32\openssh), to fix paths to OpenSSL SDK.

**Comment by manojampalam** [comment]
contrib/win32/openssh/OpenSSL-1.0.2d_build.cmd provided by @dkulwin has steps built on similar lines that generates static libraries.

**Comment by Ono-Sendai** [comment]
ok, got it building, thanks.

**Comment by manojampalam** [comment]
Cool. How did you end up building OpenSSL?

**Comment by Ono-Sendai** [comment]
Added some notes on the bottom of this wiki page: https://github.com/PowerShell/Win32-OpenSSH/wiki/OpenSSH-64-bit-Build-and-Installation-Instructions

**Comment by manojampalam** [comment]
Thanks for updating wiki.
