### ISSUE TITLE
Support for TERM=dumb

### ISSUE THREAD

**Issue by sakazuki** [PowerShell/Win32-OpenSSH#1057]
My terminal does not support colors or other special instructions. My $TERM is set to dumb, which indicates this. Could flow either provide a way to turn off color'd output, or respect the TERM setting?

It look like ssh-shellhost.exe problem ?

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
1.0.0.0
 
**Server OperatingSystem**
Windows Server 2012 R2 Standard

**Client OperatingSystem**
JSCH-0.1.45 (unfortunately, I have to use old version)

**What is failing**
My terminal does not support colors or other special instructions. My $TERM is set to dumb, which indicates this. Could flow either provide a way to turn off color'd output, or respect the TERM setting?

**Expected output**
No escape sequence chars. The pty settings (TERM=dumb ) affects their behavior

**Actual output**
Include escape sequence chars.  The pty settings (TERM=dumb) does not affect their behavior.

**Comment by manojampalam** [comment]
dump TERM  needs to be explicitly implemented in ssh-shellhost.exe (it only supports XTERM now). 

Unfortunately, your only option now is to not request a PTY
ssh -T user@target

and you'll end up with a way dumber terminal.

**Comment by sakazuki** [comment]
@manojampalam Thank you for your comment.

I want to try creating dumb support.
I think I should enhance ProcessIncomingKeys in shell-host.c to support dumb.

Could you give me advise to do it ?

**Comment by manojampalam** [comment]
This  may not be straightforward. First, you need to see how sshd gets to know that client has requested a "dumb" PTY. Then sshd needs to convey this to ssh-shellhost (perhaps using a cmdline parameter). This should invoke the logic you are planning to add in shell-host.c

**Comment by maertendMSFT** [comment]
On Win10, the Windows console is used.  We will not make any changes downlevel.
