### ISSUE TITLE
`ssh-keygen -c` truncates public key

### ISSUE THREAD

**Issue by Sniper296** [PowerShell/Win32-OpenSSH#1058]
**"OpenSSH for Windows" version**
0.0.18.0 from Optional Features
1.0.0.0 from GitHub
 
**Server OperatingSystem**
Windows 10 Home 1709 16299.125

**Client OperatingSystem**
N/A

**What is failing**
Changing a key's comment in `ssh-keygen` using `-c` truncates public key.

**Expected output**
`ssh-keygen -f test -t ed25519`
`ssh-keygen -c -f .\test`
```
-a----       02/02/2018     18:20            419 test
-a----       02/02/2018     18:20            105 test.pub
```

**Actual output**
`ssh-keygen -f test -t ed25519`
`ssh-keygen -c -f .\test`
```
-a----       02/02/2018     18:20            387 test
-a----       02/02/2018     18:20            0 test.pub
```

**Comment by manojampalam** [comment]
Thanks for the PR. Added comments that need to be addressed.

**Comment by lupo1977** [comment]
Should be ok now.

**Comment by manojampalam** [comment]
Added comments.

**Comment by lupo1977** [comment]
Now I only fixed the bug for windows and kept the old code intact.

**Comment by manojampalam** [comment]
Thanks @lupo1977 Merged your PR.
