### ISSUE TITLE
binaries lacking digital signatures

### ISSUE THREAD

**Issue by dwatley** [PowerShell/Win32-OpenSSH#1062]
**"OpenSSH for Windows" version**
v1.0.0.0-Beta
 
**Issue Description**
The OpenSSH for Windows binaries are currently lacking a digital signature. Are there plans to sign these binaries as part of the release process?

**Comment by bagajjal** [comment]
Right now it's still in beta.. Soon we will move to production ready. We will have binaries when we are production ready

**Comment by dwatley** [comment]
@bagajjal @joeyaiello - As I understand it from the recent [1803 blog post](https://blogs.msdn.microsoft.com/commandline/2018/03/07/windows10v1803/) that a portion of this SSH suite is being enabled by default. Enabling by default seems to imply "production ready" and will be a fully supported operating system feature. What are the implications for signing (in the OS build, and GitHub releases)?

**Comment by dwatley** [comment]
I see it's been [committed](https://github.com/PowerShell/openssh-portable/commit/f291d2438f11f376b3092bfad02f45915a5a152f) and [released](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.6.1.0p1-Beta). Would be handy if issues are referenced in PRs more generally.
