### ISSUE TITLE
TFS build SSH file copy fails with "read ECONNRESET" against sshd on Windows

### ISSUE THREAD

**Issue by StrikerTwo** [PowerShell/Win32-OpenSSH#1064]
**"OpenSSH for Windows" version**
 1.0.0.0 beta
 
**Server OperatingSystem**
Windows Server 2012 R2

**What is failing**
Task "Deploy: Copy Files Over SSH" in TFS Server 2018 Build 

**Expected output**
Build succeeds

**Actual output**
`2018-02-05T09:20:04.0161219Z Das Kopieren von 485 Dateien auf den Remotecomputer wurde abgeschlossen.
2018-02-05T09:20:04.0629880Z ##[error]Ausnahmefehler: read ECONNRESET`

**Comment by bagajjal** [comment]
please provide the server side logs sshd.log (with DEBUG3 enabled)

**Comment by StrikerTwo** [comment]
Looks good to me:
```
3812 2018-02-06 13:59:37.295 debug2: channel 0: window 1998761 sent adjust 98391
6204 2018-02-06 13:59:38.563 debug3: receive packet: type 1
6204 2018-02-06 13:59:38.563 Received disconnect from 87.138.XX.XX port 40448:11: 
6204 2018-02-06 13:59:38.563 Disconnected from 87.138.XX.XX port 40448
6204 2018-02-06 13:59:38.563 debug1: do_cleanup
6288 2018-02-06 13:59:38.563 debug3: mm_request_receive entering
6288 2018-02-06 13:59:38.563 debug1: do_cleanup
3812 2018-02-06 13:59:38.563 debug3: receive packet: type 1
3812 2018-02-06 13:59:38.563 Received disconnect from 87.138.XX.XX port 40449:11: 
3812 2018-02-06 13:59:38.563 Disconnected from 87.138.XX.XX port 40449
3812 2018-02-06 13:59:38.563 debug1: do_cleanup
7700 2018-02-06 13:59:38.579 debug3: mm_request_receive entering
7700 2018-02-06 13:59:38.579 debug1: do_cleanup
```
[sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/1699098/sshd.log)

**Comment by manojampalam** [comment]
We need to repro this to take it forward. Please add as much setup details as possible.

**Comment by StrikerTwo** [comment]
We have a TFS 2018 on Windows Server 2016 on-premise. The CI build has a task "Deploy: Copy Files Over SSH" that copies the build result to our public data centre server running Windows Server 2012 R2 on Hyper-V and the OpenSSH sshd.
The data centre server is protected by a Sophos UTM firewall that does simple NAT from a non-well-known port to TCP/22 on the server's internal IP.

If I copy the files manually with FileZilla to the same server, there is no error message.
Unfortunately I can't test the CI build against a different SSH server right now, because we only have the one.

**Comment by bagajjal** [comment]
@StrikerTwo - Since it works with FileZilla, try to compare the sshd.log and figure out the difference.
Also please make sure the binary folder has the **only** read access to "Authenticated Users".

**Comment by bagajjal** [comment]
This issue looks to be an issue with your configuration, environment.
I am closing this issue as it works with FileZilla.
