### ISSUE TITLE
[Regression] Match (user) Block No Longer Works in Version v1.0.0.0-Beta

### ISSUE THREAD

**Issue by jblank-uw** [PowerShell/Win32-OpenSSH#1065]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
1.0.0.0

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

Windows 10 Enterprise

**Client OperatingSystem**

Windows 10 Enterprise

**What is failing**

ForceCommand and Command option in authorized_keys no longer do anything in version  v1.0.0.0-Beta
Worked fine as of version 0.0.24.0

**Expected output**

**Actual output**

**Comment by manojampalam** [comment]
Just tried out ForceCommand and it seems to work. Add relevant details in sshd_config. 

What did you mean by "Command option in authorized_keys"

**Comment by jblank-uw** [comment]
My sshd_config contains

Match Group ssh_users
	ForceCommand      cmd /c set ssh

I also tried adding the Command option in my authorized_keys file

  command="whoami" ssh-rsa AAAAB3NzaC1yc2EAA...

Will gather some Debug traaces from each version.

Jim

**Comment by manojampalam** [comment]
Issue found. Looks like Match blocks have regressed in 1.0.0.0. Will issue a fix soon and add test cases.
