### ISSUE TITLE
version v1.0.0.0-Beta changes terminal background colors.

### ISSUE THREAD

**Issue by lejeczek** [PowerShell/Win32-OpenSSH#1066]
**"OpenSSH for Windows" version**
v1.0.0.0-Beta
 
**Server OperatingSystem**
v1.0.0.0-Beta

**Client OperatingSystem**
Centos 7

**What is failing**
SSH Win server that I got via "Add Features", version v0.0.24.0 did not one thing v1.0.0.0-Beta started doing, namely..
With v1.0.0.0-Beta(binary zip package) when sshed into Win server I get coloured(black) background except for blank/empty lines, where gnome-terminal-set background remains.
Eg, in my terminal background is blue, when I connect and exec dir that output background is painted black.

**Expected output**
SSH session to retain original background(all colours).
I assume it's something v1.0.0.0-Beta introduced and that it's not configurable(?)

**Actual output**

**Comment by manojampalam** [comment]
@bagajjal  is this expected?

**Comment by bagajjal** [comment]
@lejeczek - Did you configure default shell at the server side?
FYI, sshd will send the background color of the default shell it launched to the client.
If you didn't configure default shell in windows registry then cmd.exe (whose background is black) will be the default shell. 

what is the difference between v0.0.24.0 and v1.0.0.0.

**Comment by lejeczek** [comment]
Well, I did not, but I also did not configure "anything" in v0.0.24.0 where I'm on cmd.exe and there background is blue, as per my gnome-terminal.
I do pretty much the same, default vanilla openssh win install of v1.0.0.0-Beta , as per docs, and session behaves differently, I'll have black background(where output is not blank/empty line, those lines will be painted blue).
In both cases I do not (manually/purposefully) set default shell.

**Comment by bagajjal** [comment]
@lejeczek - Can you try my [private ssh-shellhost.exe](https://github.com/PowerShell/Win32-OpenSSH/files/1709034/ssh-shellhost-v1-background-issue.zip).

As part of V1.0.0.0, I have a [fix ](https://github.com/PowerShell/Win32-OpenSSH/issues/1005)related to coloring.

**Comment by lejeczek** [comment]
I will, how do I use ssh-shellhost ?
Reading "fix" - does it it mean it's fixed in git? If yes then could we have downloadable bins fixed as well?

**Comment by bagajjal** [comment]
Here are the steps, 

1) cd to your binary folder.
2) backup existing ssh-shellhost.exe (move ssh-shellhost.exe  ssh-shellhost.exe.bk)
3) copy my private binary to the binary folder.
4) Make an ssh connection.

The fix went in v1.0.0.0 is correct.

**Comment by lejeczek** [comment]
I exec: dir = colors retained, I exec "route print" = background changes to black.

**Comment by bagajjal** [comment]
The fix went in v1.0.0.0 is correct fix. This is expected behavior.
sshd process will send text with foreground, background color. If you don't specify any terminal, sshd will use cmd.exe as it's client. cmd.exe foreground, background colors will be sent to ssh client.

**Comment by bagajjal** [comment]
Reopen if you think it's a bug.
