### ISSUE TITLE
ssh with keys does not work for non-local users(?)

### ISSUE THREAD

**Issue by lejeczek** [PowerShell/Win32-OpenSSH#1067]
**"OpenSSH for Windows" version**
 v0.0.24.0 

**Server OperatingSystem**
v0.0.24.0 

**Client OperatingSystem**
Centos 7

**What is failing**
I cannot ssh to an account which is a domain account. Domain is NT-style and ssh server is Win10 Pro.
I put "?" as I'm new to Windows and I realize I might be missing something.
But I checked, just in case, permission of authrized_keys and these seem identical to what another(local) user's file has, which user can ssh with keys no problems.

**Expected output**
Just login.

**Actual output**
Still sshd asks for password.

regards.

**Comment by bagajjal** [comment]
Try logging like this,
ssh user@domain@host

If it didn't work then share sshd.log with DEBUG3 enabled and ssh log (ssh -vvv user@domain@host).

**Comment by lejeczek** [comment]
sshd.log:
..
8852 19:36:47:164 debug3: NetUserGetInfo() failed with error: 1722 for user: pe243 and domain: _biotec \n
8852 19:36:48:695 debug2: input_userauth_request: setting up authctxt for pe243@_biotec
8852 19:36:48:695 debug2: input_userauth_request: try method none
8852 19:36:48:695 Failed none for pe243@_biotec from 10.5.10.49 port 5390 ssh2
8852 19:36:48:695 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"
8852 19:36:48:695 debug3: send packet: type 51
8852 19:36:48:695 debug3: receive packet: type 50
8852 19:36:48:695 debug1: userauth-request for user pe243@_biotec service ssh-connection method publickey
8852 19:36:48:695 debug1: attempt 1 failures 0
8852 19:36:48:695 debug2: input_userauth_request: try method publickey
8852 19:36:48:695 debug1: userauth_pubkey: test whether pkalg/pkblob are acceptable for RSA SHA256:uMhpqoTLeyvAvLKbkiytTRGk8FSP6rfxgb1nhkg+L0Q
8852 19:36:48:695 debug1: trying public key file C:\\Users\\pe243\\.ssh/authorized_keys
8852 19:36:48:727 debug1: matching key found: file C:\\Users\\pe243\\.ssh/authorized_keys, line 1 RSA SHA256:uMhpqoTLeyvAvLKbkiytTRGk8FSP6rfxgb1nhkg+L0Q
8852 19:36:48:727 debug3: send packet: type 60
8852 19:36:48:727 debug2: userauth_pubkey: authenticated 0 pkalg rsa-sha2-512
8852 19:36:48:727 Postponed publickey for pe243@_biotec from 10.5.10.49 port 5390 ssh2
8852 19:36:48:727 debug3: receive packet: type 50
8852 19:36:48:727 debug1: userauth-request for user pe243@_biotec service ssh-connection method publickey
8852 19:36:48:727 debug1: attempt 2 failures 0
8852 19:36:48:727 debug2: input_userauth_request: try method publickey
8852 19:36:48:727 debug3: userauth_pubkey: have signature for RSA SHA256:uMhpqoTLeyvAvLKbkiytTRGk8FSP6rfxgb1nhkg+L0Q
8852 19:36:48:727 debug1: trying public key file C:\\Users\\pe243\\.ssh/authorized_keys
8852 19:36:48:727 debug1: matching key found: file C:\\Users\\pe243\\.ssh/authorized_keys, line 1 RSA SHA256:uMhpqoTLeyvAvLKbkiytTRGk8FSP6rfxgb1nhkg+L0Q
8852 19:36:48:862 debug2: userauth_pubkey: authenticated 0 pkalg rsa-sha2-512
8852 19:36:48:862 Failed publickey for pe243@_biotec from 10.5.10.49 port 5390 ssh2: RSA SHA256:uMhpqoTLeyvAvLKbkiytTRGk8FSP6rfxgb1nhkg+L0Q
8852 19:36:48:862 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"
8852 19:36:48:862 debug3: send packet: type 51
8852 19:36:48:863 debug3: receive packet: type 50
8852 19:36:48:863 debug1: userauth-request for user pe243@_biotec service ssh-connection method keyboard-interactive
8852 19:36:48:863 debug1: attempt 3 failures 1
8852 19:36:48:863 debug2: input_userauth_request: try method keyboard-interactive
8852 19:36:48:863 debug1: keyboard-interactive devs 
8852 19:36:48:863 debug1: auth2_challenge: user=pe243@_biotec devs=
8852 19:36:48:863 debug1: kbdint_alloc: devices ''
8852 19:36:48:863 debug2: auth2_challenge_start: devices 
8852 19:36:48:863 Failed keyboard-interactive for pe243@_biotec from 10.5.10.49 port 5390 ssh2
8852 19:36:48:863 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"
8852 19:36:48:863 debug3: send packet: type 51

ssh -vvv:

OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 60: Applying options for *
debug1: Executing proxy command: exec /usr/bin/sss_ssh_knownhostsproxy -p 22 10.5.10.53
debug1: permanently_drop_suid: 2501
debug1: identity file /home.sysops/appmgr/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home.sysops/appmgr/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home.sysops/appmgr/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home.sysops/appmgr/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home.sysops/appmgr/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home.sysops/appmgr/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home.sysops/appmgr/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home.sysops/appmgr/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6
debug1: match: OpenSSH_7.6 pat OpenSSH* compat 0x04000000
debug2: fd 6 setting O_NONBLOCK
debug2: fd 5 setting O_NONBLOCK
debug1: Authenticating to 10.5.10.53:22 as 'pe243@_biotec'
debug3: hostkeys_foreach: reading file "/home.sysops/appmgr/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home.sysops/appmgr/.ssh/known_hosts:23
debug3: load_hostkeys: loaded 1 keys from 10.5.10.53
debug3: hostkeys_foreach: reading file "/var/lib/sss/pubconf/known_hosts"
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: curve25519-sha256 need=64 dh_need=64
debug1: kex: curve25519-sha256 need=64 dh_need=64
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:/1wWphpxGHRWSP7SF/poo8DDYuIrt1dmL+TCWitQ4Oc
debug3: hostkeys_foreach: reading file "/home.sysops/appmgr/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home.sysops/appmgr/.ssh/known_hosts:23
debug3: load_hostkeys: loaded 1 keys from 10.5.10.53
debug3: hostkeys_foreach: reading file "/var/lib/sss/pubconf/known_hosts"
debug1: Host '10.5.10.53' is known and matches the ECDSA host key.
debug1: Found key in /home.sysops/appmgr/.ssh/known_hosts:23
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug2: key: /home.sysops/appmgr/.ssh/id_rsa (0x555efb5e2970)
debug2: key: /home.sysops/appmgr/.ssh/id_dsa ((nil))
debug2: key: /home.sysops/appmgr/.ssh/id_ecdsa ((nil))
debug2: key: /home.sysops/appmgr/.ssh/id_ed25519 ((nil))
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug3: start over, passed a different list publickey,password,keyboard-interactive
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home.sysops/appmgr/.ssh/id_rsa
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: pkalg rsa-sha2-512 blen 279
debug2: input_userauth_pk_ok: fp SHA256:uMhpqoTLeyvAvLKbkiytTRGk8FSP6rfxgb1nhkg+L0Q
debug3: sign_and_send_pubkey: RSA SHA256:uMhpqoTLeyvAvLKbkiytTRGk8FSP6rfxgb1nhkg+L0Q
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Trying private key: /home.sysops/appmgr/.ssh/id_dsa
debug3: no such identity: /home.sysops/appmgr/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /home.sysops/appmgr/.ssh/id_ecdsa
debug3: no such identity: /home.sysops/appmgr/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /home.sysops/appmgr/.ssh/id_ed25519
debug3: no such identity: /home.sysops/appmgr/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup keyboard-interactive
debug3: remaining preferred: password
debug3: authmethod_is_enabled keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug2: userauth_kbdint
debug3: send packet: type 50
debug2: we sent a keyboard-interactive packet, wait for reply
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug3: userauth_kbdint: disable: no info_req_seen
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: 
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
pe243@_biotec@10.5.10.53's password: 
debug3: send packet: type 50
debug2: we sent a password packet, wait for reply
--- here is prompt for password

many thanks.

**Comment by bagajjal** [comment]
@lejeczek - Can you try the latest version v1.0.0.0.

**Comment by lejeczek** [comment]
do you mean "beta" ?

**Comment by lejeczek** [comment]
It seems that even v1 beta needs sshd user to have (R) to authorized_keys of DOMAIN users even to prompt for a password. If such luck is absent sshd won't even connect, will instead fail: 

$ ssh "pe243"@10.5.10.52
packet_write_wait: Connection to UNKNOWN port 65535: Broken pipe

Still will not login password-less, will the problem continue to remain somewhere in file permissions?

**Comment by bagajjal** [comment]
@lejeczek - please share sshd.log (DEBUG3 enabled) and ssh -vvv user@ip

**Comment by lejeczek** [comment]
It seems that even v1 beta needs sshd user to have (R) to authorized_keys of DOMAIN users even to prompt for a password. If such permission is absent sshd won't even connect, will instead fail: 

$ ssh "pe243"@10.5.10.52
packet_write_wait: Connection to UNKNOWN port 65535: Broken pipe

Still will not login password-less, will the problem continue to remain somewhere in file permissions?
