### ISSUE TITLE
sftp can not change to different drives

### ISSUE THREAD

**Issue by tperrysov** [PowerShell/Win32-OpenSSH#107]
Trying all forms of cd c:\users, or /C/users, do not work.  I can not see any way of changing drive letters in this version of sftp.

**Comment by quamrulmina** [comment]
cd c:/users is the right form. Use forward slashes and colon after drive letter. cd c:\\users will also work - need two back slashes to get one backslash. Also drive letter support got added in the newer builds - make sure you are running the newer/recent builds.

**Comment by quamrulmina** [comment]
To use directories/files with spaces in their names, use "" around it. For example, cd "c:/Program Files"

**Comment by TehWardy** [comment]
Latest version (downloaded yesterday) doesn't seem to do this.
It's ok on C but doesn't appear to know anything about a D drive (that I happen to have).
Also will this support UNC paths / mapped network drives on the local machine?
I recall reading something about symlinks not showing up on another ticket.
