### ISSUE TITLE
Install OpenSSHUtils Module, signature invalid.

### ISSUE THREAD

**Issue by xiaohh2016** [PowerShell/Win32-OpenSSH#1070]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
0.0.18.0
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
CentOS7
**What is failing**
when I try to install opensshutils module, it reports an error. 
PackageManagement\Install-Package : 无法安装或更新模块“OpenSSHUtils”，因为文件“OpenSSHUtils.psd1”的验证码签名无效。

PackageMangaement\Install-package: Can not install or update module "OpenSSHUtils", because the signature of the file is invalid.

**Comment by JW0914** [comment]
You're using an extremely old version... please update to [1.0.0.0](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v1.0.0.0) (ensure you re-read the [install wiki](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH), as steps have changed).

**Comment by manojampalam** [comment]
@joeyaiello is this expected?

**Comment by bingbing8** [comment]
@xiaohh2016, can you try the latest release? We have both binary and script files digital signed.
