### ISSUE TITLE
Installer still sets the specific port number in the firewall

### ISSUE THREAD

**Issue by codearoo** [PowerShell/Win32-OpenSSH#1071]
The installer should create a firewall rule to the SSHD service or the EXE, not passing in the port used for the install. Now when the port number is changed in the sshd_config, it also has to get changed in the firewall config.
This was done via Chocolatey, using the parameters:
choco install -y openssh --params="/SSHServerFeature /SSHServerPort:12345"

And the firewall rule name ends up as:
SSHD Port OpenSSH (chocolatey package: openssh)

**Comment by DarwinJS** [comment]
The installer can be used to update the port - in which case it also updates the firewall rule.

I will consider changing it on the next version.
