### ISSUE TITLE
Latest Win10 updates (win is up to date as of Feb 12) made ssh fail to exec some command(?)

### ISSUE THREAD

**Issue by lejeczek** [PowerShell/Win32-OpenSSH#1072]
Hi,
I've installed some big "cumulative" updates (now I check and system says "is updated no updates" and my sshd has gone heywire!

**Client OperatingSystem**

**What is failing**

C:\Users\pawel>ssh-keygen
                                                                                                     
C:\Users\pawel>echo %errorlevel%
-1073741502
                                                                                                     
C:\Users\pawel>vim
                                                                                                     
C:\Users\pawel>echo %errorlevel%
-1073741502

C:\Users\pawel>powershell
                                                                                                     
C:\Users\pawel>echo %errorlevel%
-1073741502

**Expected output**

**Actual output**

**Comment by NoMoreFood** [comment]
@lejeczek What version of Win32-OpenSSH are you running? Did you try rolling back the updates?  If so, which specific update?  Is the behavior consistent?

The error -1073741502 translates to 0xC0000142 / STATUS_DLL_INIT_FAILED which is basically saying that DLLs failed to load for the child process.  

This could be a bug in OpenSSH, but see if anything mentioned here might correlate to your environment:

https://blogs.msdn.microsoft.com/winsdk/2015/06/03/what-is-up-with-the-application-failed-to-initialize-properly-0xc0000142-error/

**Comment by bagajjal** [comment]
Any update on this?
