### ISSUE TITLE
Adding a Get Response & Duplicate File (this is not an issue but an addition request)

### ISSUE THREAD

**Issue by XceSx6** [PowerShell/Win32-OpenSSH#1074]
Dear Developer,

For starters congratz on the good work and stable SFTP Framework !
After using it for about a Year now, it would be awesome to have the following available:
- A Get Response that can be called after calling any Function (like Upload or Download or Move, ..)
   Or having it returned as an object instead of the void
- A Duplicate File

Keep up the good work :)

**Comment by bagajjal** [comment]
@XceSx6 - We are in sync with openssh unix code. 
If you are requesting for new features then follow up with openssh folks https://www.openssh.com/report.html.

Our goal is to get integrated with openssh core code so we don't support adding new features.
