### ISSUE TITLE
No support for gcm ciphers in ssh client

### ISSUE THREAD

**Issue by dwatley** [PowerShell/Win32-OpenSSH#1075]
**"OpenSSH for Windows" version**
v1.0.0.0-Beta

```
C:\Program Files\OpenSSH>ssh -V
OpenSSH_7.6p1, LibreSSL 2.5.3

C:\Program Files\OpenSSH>ssh -Q cipher
3des-cbc
aes128-cbc
aes192-cbc
aes256-cbc
rijndael-cbc@lysator.liu.se
aes128-ctr
aes192-ctr
aes256-ctr
chacha20-poly1305@openssh.com
```

I discovered this due to my ssh config file having gcm ciphers in the cipher spec and getting an error message about a bad cipher spec during config parsing.
```
C:\Program Files\OpenSSH>ssh localhost
C:\\Users\\Dominic/.ssh/config line 8: Bad SSH2 cipher spec 'chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'.
```

Just wanted to document this wasn't available and requires someone to remove the gcm ciphers from their ssh config. Is there any particular reason for this? Git-SCM ssh client supports these ciphers:

```
C:\>ssh -V
OpenSSH_7.6p1, OpenSSL 1.0.2l  25 May 2017

C:\>ssh -Q cipher
3des-cbc
aes128-cbc
aes192-cbc
aes256-cbc
rijndael-cbc@lysator.liu.se
aes128-ctr
aes192-ctr
aes256-ctr
aes128-gcm@openssh.com
aes256-gcm@openssh.com
chacha20-poly1305@openssh.com
```

**Comment by manojampalam** [comment]
Looks like its a matter of enabling OPENSSL_HAVE_EVPGCM in config.h if LibreSSL does support this cipher.
