### ISSUE TITLE
Port Forwarding 

### ISSUE THREAD

**Issue by matthiasreisser** [PowerShell/Win32-OpenSSH#1076]
Please answer the following

**"OpenSSH for Windows" version**
v1.0.0.0-Beta
 
**Server OperatingSystem**
Windows 10 Education

**Client OperatingSystem**
MacOS X 10.13.2

**What is failing**
On my mac, I run.
`ssh -L 21000:localhost:21000 username@server_address`
On the Windows server, I am running the following, simple HTTP Server through python:
```
import SimpleHTTPServer
import SocketServer

# minimal web server.  serves files relative to the
# current directory.

PORT = 21000
HOST = "localhost"
Handler = SimpleHTTPServer.SimpleHTTPRequestHandler

httpd = SocketServer.TCPServer((HOST, PORT), Handler)

print "serving at port", PORT, "host", HOST
httpd.serve_forever()
``` 

**Expected output**
When navigating to localhost:21000 on my mac, I'd expect to the the content of the directory within which the python file lies. Alternatively, `wget localhost:21000` should download index.html

**Actual output**
The connection to the HTTP Server cannot be established:
```
wget localhost:21000
--2018-02-17 19:09:39--  http://localhost:21000/
Resolving localhost... ::1, 127.0.0.1
Connecting to localhost|::1|:21000... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

```
[Issue #288 ](https://github.com/PowerShell/Win32-OpenSSH/issues/288) might be very related. As a matter of fact, when running `sshd.exe -dd`, the logs show the following:

```
debug1: server_input_channel_open: ctype direct-tcpip rchan 3 win 2097152 max 32768
debug1: server_request_direct_tcpip: originator ::1 port 64170, target localhost port 21000
debug2: fd 9 setting O_NONBLOCK
debug1: getsockopt TCP_NODELAY: Invalid argument
debug1: connect_next: host localhost ([::1]:21000) in progress, fd=9
debug1: channel 1: new [direct-tcpip]
debug1: server_input_channel_open: confirm direct-tcpip
debug1: channel 1: connected to localhost port 21000
debug2: channel 1: read<=0 rfd 9 len 4294967295
debug2: channel 1: read failed
debug2: channel 1: close_read
debug2: channel 1: input open -> drain
debug2: channel 1: ibuf empty
debug2: channel 1: send eof
debug2: channel 1: input drain -> closed
debug2: channel 1: write failed
debug2: channel 1: close_write
debug2: channel 1: chan_shutdown_write: shutdown() failed for fd 9: The socket is not connected
debug2: channel 1: output open -> closed
debug2: channel 1: send close
debug2: channel 1: rcvd eof
debug2: channel 1: rcvd close
debug2: channel 1: is dead
debug2: channel 1: garbage collecting
debug1: channel 1: free: direct-tcpip, nchannels 2
```
As has been discussed in #288, this might have something to do with the usage of ipv6 as opposed to ipv4. 

Unfortunately, I have zero experience working with Windows, my knowledge of unix systems is more advanced. My knowledge of ssh is ok-ish, but I would not know how to force ipv4, for example. I have confirmed that my little HTTP server performs as expected and is reachable when running on a linux system. 

I would appreciate very much any help in getting this to run. 

Thx,
Mat

**Comment by JW0914** [comment]
Are you actually accessing `localhost`, or are you using that as a placeholder for a device hostname on your LAN?  If so, add a host entry to the windows host file mapping the local device's IP to it's hostname.localdomain.  If not, please disregard.

**Comment by matthiasreisser** [comment]
Hey @JW0914, thx for your fast response. I use the commands exactly as written (except for `username` and `server_address`), thus configuring my mac to forward any request to 'itself' on `localhost:21000` to `server_address:21000` instead.

**Comment by matthiasreisser** [comment]
In `C:\Program Files\OpenSSH\sshd_config`, I have enabled the line `AddressFamily inet` in order to enforce ipv4 usage. I still have the same message in the logs, however:
```
debug1: getsockopt TCP_NODELAY: Invalid argument
debug1: connect_next: host localhost ([::1]:21000) in progress, fd=9
```
which makes me suspicious if the sshd_config files is read at all. Is it in the right location for sshd to find it?

**Comment by JW0914** [comment]
The locations have changed in 1.0.0.0 (see [#7](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH), as location has changed to `%ProgramData%\ssh\sshd_config`), and the bug (#847) with not honoring the system wide [sshd_config](https://man.openbsd.org/sshd_config) was fixed.  

* You may also want to configure a user specific [ssh_config](https://man.openbsd.org/ssh_config) to be placed inside your user's .ssh directory.
   * Most options are cross compatible between the sshd_config and user specific `~\.ssh\config`, but some are not, so ensure you verify if copying and pasting from the sshd_config.
      * The user specific ssh_config must be named `config`, not _ssh_config_.

**Comment by matthiasreisser** [comment]
Ah, that explains it! This solved my problem, thank you very much!

**Comment by SummaCumWilly** [comment]
Sorry for necroposting, but what was it that solved this Mat? Was it the path to the sshd_config being in the new location or was it that you added a client config. I suspect it was just fixing the path on the server. It's just not clear in your answer what you did.
