### ISSUE TITLE
Bash failure after ssh into sshd host

### ISSUE THREAD

**Issue by Jocala** [PowerShell/Win32-OpenSSH#1077]
I  get the Error: 0x80070005 when I ssh into Windows 10 and run bash.

OpenSSH 7.6p1
v1.0.0.0-Beta
OpenSSH-Win64.zip

Surface Pro 3
winver 1709:16299.248

From a different thread: I did restart into safe mode and nuke the lxss\temp directory, no difference.

Occurs with all clients.

**Comment by bagajjal** [comment]
Duplicate of #289
Closing this as its a bash issue.

**Comment by Jocala** [comment]
Thanks, the link to #289 was very helpful.
