### ISSUE TITLE
Windows Filesystem Redirector is being used to load certain modules as if the SSH shell session is in 32 bit mode

### ISSUE THREAD

**Issue by CliffFoster** [PowerShell/Win32-OpenSSH#1079]
**"OpenSSH for Windows" version**
v1.0.0.0-Beta x64
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Windows 10 Pro (same system as server)

**What is failing**
Some third party commands seem to be using the Windows Filesystem Redirector to call 32 bit modules in 64 bit programs when called from a SSH session. Commands work fine locally in local command prompts, and the 32 bit versions of the commands work fine in the SSH session. The 64 bit commands seem to think they are executing in a 32 bit environment.

Unfortunately I've been unable to figure out a simple reproduction as this involves a complex FPGA build toolchain and some of the tools in it failing (if you tell the tools to run the 32 bit versions they run fine).

**Comment by DarwinJS** [comment]
Procmon reports the bitness of everything it monitors (architecture) - if you monitor an example it might show evidence for the problem.

**Comment by CliffFoster** [comment]
I dug through procmon's output this morning regarding the failing process and couldn't really find a difference between it failing in an SSH shell and a successful one in a normal command prompt shell beyond the fact that when the failing one tries to access ntdll.dll at some point the thread it is in immediately terminates and then the rest of the application terminates out after that. The return code is some large garbage negative number.

All of the architectures are 64 bit, and it seems to be loading the 64 bit dlls from System32 (when running the 32 bit tools it seems to be appropriately loading the ones from SysWOW64).

Very confused on what is going on.

**Comment by NoMoreFood** [comment]
This one may be tough to diagnose.

What's the "large negative number"?  Often those translate to unsigned numbers that happen to have the uppermost bit set thereby making it negative when cast to a signed number (i.e. ‭-2147479552‬ is 0x80001000).  

Also, in procmon, I'd recommending comparing the 'Environment' property in the parent process of the executable that fails versus one that works.  Filter on the 'Process Start' commands.
