### ISSUE TITLE
ssh-keygen -l -E md5 reports pub key file a "not a public keyfile"

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/Win32-OpenSSH#1080]
**"OpenSSH for Windows" version**
This is the client only - 0.0.18.0
 
**Server OperatingSystem**
N/A

**Client OperatingSystem**
Windows 10 Enterprise 16299.248
**What is failing**
This command reports my public key file "as not a public key file"
```
ssh-keygen -l -E md5 -f C:\Users\hillr\.ssh\id_rsa.pub
```

**Expected output**
I expect this output which is what WSL/Ubuntu gives me on the very same file:
```
7:42ms> ssh-keygen -l -E md5 -f /mnt/c/Users/hillr/.ssh/id_rsa.pub
2048 MD5:6e:7f:17:d3:40:78:e8:3f:91:d7:2a:f8:a0:cb:f2:2c hillr@ad.keysight.com (RSA)
```

**Actual output**
```
C:\\Users\\hillr\\.ssh\\id_rsa.pub is not a public key file.
```

BTW this command is in the instructions that VSTS/TFS gives out to verify your public key matches the hash that TFS has for your public key: https://www.visualstudio.com/team-services/support/help-troubleshoot-ssh-key-authentication-team-foundation-server/

**Comment by bagajjal** [comment]
I think you are using windows optional ssh feature from windows 10?
Windows optional ssh feature supports only ed25519 (doesn't support rsa, dsa, ecdsa).

Try the GitHub openssh version
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by rkeithhill** [comment]
Thanks for the info!  This is a Windows Insider build from last week (17101). I can't remember if I added this "option" or if it just comes with the newer Windows builds.  I suspect I probably added the option. Before I install from the GitHub project, I guess I'll need to remove the Windows feature/option first?

**Comment by bagajjal** [comment]
Yes remove the windows feature and install (.\uninstall-sshd.ps1;.\install-sshd.ps1) the sshd from openssh.

**Comment by bagajjal** [comment]
Reopen if required.
