### ISSUE TITLE
git bash as defaultshell

### ISSUE THREAD

**Issue by hentismith** [PowerShell/Win32-OpenSSH#1083]
**"OpenSSH for Windows" version**
OpenSSH_7.6p1, LibreSSL 2.5.3                                                                                                   

**Server OperatingSystem**
Microsoft Windows [Version 6.1.7601]                                                                                            

**Client OperatingSystem**
Linux

**What is failing**
Setting defaultshell to "c:\Program Files\Git\usr\bin\bash.exe" does not work

**Expected output**
Git bash shell

**Actual output**
No ssh connection. Screen blanks then back to Unix shell on client machine. 

Installing git with bash gives windows an easy bash environment. I can open a cmd in windows itself and run "c:\Program Files\Git\usr\bin\bash.exe" --login and get a bash shell to work in. 

Having this as ssh default shell would be amazing.

**Comment by hentismith** [comment]
As a side note, I set defaultshell to powershell and ssh from windows to windows I can then run the above defautlshell command and get a bash shell over ssh, but not from Unix terminal. 

Not sure if that helps or not.

**Comment by manojampalam** [comment]
@bagajjal is this expected?

**Comment by bagajjal** [comment]
@henti - We couldn't reproduce this issue. 
So we need your help,
1) Log on to windows machine that has sshd executable
2) Download [my private binary](https://github.com/PowerShell/Win32-OpenSSH/files/1787365/Default-shellissue.zip) to any test folder.
3) Unzip and execute the binary based on system type (X86, X64).
4) Paste the output.

**Comment by hentismith** [comment]
This is on windows 7 machine, which might be the reason. 

```jenkins@win7-image-base@WIN7-IMAGE-BASE C:\Users\jenkins\Desktop\Default-shellissue>ConsoleApplication2_X64.exe                 
RegOpenKeyExW (SOFTWARE\OpenSSH) failed:2                                                                                       
RegQueryValueExW (HKLM:SOFTWARE\OpenSSH\DefaultShell) failed:6                                                                  
Default shell:C:\Windows\system32\cmd.exe                                                                                       

press enter to EXIT!!                                                                                                           
```

Windows 10 seems to work fine.

**Comment by bagajjal** [comment]
@henti - I tried on my win7 machine, it worked perfectly.

Looking at the output you shared, 
"RegOpenKeyExW (SOFTWARE\OpenSSH) failed:2"  - [error 2 means file not found](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx).

Can you double check if you configured the Default shell at "HKLM:SOFTWARE\OpenSSH"

**Comment by hentismith** [comment]
Hi @bagajjal 

Ahh yes, I was using our azure build image which is still configured to use normal command. I'll have to build a new VM for testing. This will take some time. 

I'll do that in the next couple of days. 

H

**Comment by hentismith** [comment]
Hi @bagajjal 

I have no idea what I did wrong before, but this is working now. Thank you for being patient with me :) 

H
