### ISSUE TITLE
Keyboard problem with passwords on target machine

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#1084]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

I checked this document and it does not appear to discuss my problem. I did try with the environment variable TERM = 'xterm' but this had no effect. However I belive that the problem is in the keyboard support.

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
0.0.18.0
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Ubuntu 16.04.3 Server

**Client OperatingSystem**
Windows 10 Pro Version 1709.
Note that the Windows system has a Spanish language keyboard and is configured to use it.

**What is failing**
After logging into Linux using password authentication I run the following command which requires me to enter my password at the console:

`sudo ufw status
`
**Expected output**
The command runs.

**Actual output**
```
wobadmin@Throwawau:~$ sudo ufw status
[sudo] password for wobadmin:
Sorry, try again.
[sudo] password for wobadmin:
Sorry, try again.
[sudo] password for wobadmin:
sudo: 3 incorrect password attempts
wobadmin@Throwawau:~$
```

Note that any command using sudo will do.

I was using the character **#** in my password and I discovered if I changed the password to contain alphanumeric characters only, I was able to use sudo without problems. Note that on a Spanish language keyboard the **#** character can only be entered in combination with the AltGr key and is the third character on the **3** key.

Also note that I can type the **#** key on the command line without problem. It is only when entering a password that the problem occurs.

Apologies for the typo that caused the issue to appear prematurely.

**Comment by bagajjal** [comment]
could you please elaborate. Also provide the reproduction steps.

**Comment by bagajjal** [comment]
fixed as part of https://github.com/PowerShell/openssh-portable/pull/322
