### ISSUE TITLE
Bug: Directory Symbolic Links Not Navigable

### ISSUE THREAD

**Issue by NoMoreFood** [PowerShell/Win32-OpenSSH#1085]
Version: 1.0.0.0 (64-Bit)
Client Operating System: Windows 10 Pro

Regardless of target (different drive, same drive, network location), directory symbolic links are not navigable.  They show up as files and navigating to them produces the following error through WinSCP:

Permission denied.
Error code: 3
Error message from server: Permission denied

However, pointing to them as an initial directory does work properly.  Symbolic links to files work fine as well.  Please let me know if you need any additional information.  This looks great so far, and I look forward to having an quality SSH server on Windows that doesn't require the bloat of Cygwin.

**Comment by bagajjal** [comment]
@NoMoreFood - Thanks for filing a bug.

How do you point symbolic link as initial directory?
Also could you please provide the sshd.log (with DEBUG3 enabled) in both working and non-working scenarios.

**Comment by NoMoreFood** [comment]
The sshd logs were essentially identical.  Here are the sftp logs.

[sftp-good.log](https://github.com/PowerShell/Win32-OpenSSH/files/1765436/sftp-good.log)
[sftp-bad.log](https://github.com/PowerShell/Win32-OpenSSH/files/1765437/sftp-bad.log)

In my test setup, I have a normal, local hard drive directory V:\TestRoot with a symbolic link called V:\TestRoot\MySymLink that points to C:\.  The initial directory in WinSCP is specified as the 'Remote Directory' in the session settings.  Connecting to V:\TestRoot and using the 'Open Directory' button also works to browse to V:\TestRoot\MySymLink\.  Interestingly, WinSCP also has a session setting to 'Follow symbolic links to directories' but the setting seems to make no difference.  The fact the directory is showing up in the UI as a file is telling me the SFTP server probably isn't characterizing it properly.  I also received a similar error with another SFTP client.

If you can't reproduce it, I can tree compiling myself but I'm unfamiliar with the OpenSSH codebase so it might take me awhile to hunt it down.

**Comment by NoMoreFood** [comment]
Fixed it.  See https://github.com/PowerShell/Win32-OpenSSH/pull/1086

**Comment by NoMoreFood** [comment]
@bagajjal 

See pull request: https://github.com/PowerShell/Win32-OpenSSH/pull/1091

The "true" problem was much deeper than I thought.  It came down to inadequate implementations of lstat(), readlink(), and the missing mode in strmode() that I had previously found.  This may correct some other problems reported.

**Comment by NoMoreFood** [comment]
@bagajjal 

As requested, I pushed this to the other fork as pull request https://github.com/PowerShell/openssh-portable/pull/281.

**Comment by NoMoreFood** [comment]
@bagajjal Any chance to review my pull request?

**Comment by NoMoreFood** [comment]
This was addressed in my pull: https://github.com/PowerShell/openssh-portable/pull/281.  Closing.
