### ISSUE TITLE
ssh client on Windows7 fails "ssh_askpass: posix_spawn: No such file or directory"

### ISSUE THREAD

**Issue by llinyu** [PowerShell/Win32-OpenSSH#1088]
"OpenSSH for Windows" version
tested with versions v1.0.0.0-Beta

Client OperatingSystem
Windows 7 SP1 Professional

What is failing
On Windows 7, I can't connect to any ssh server using the ssh.exe client from this project. but putty works.
I have tried ssh.exe both in version v0.0.24.0 and v1.0.0.0-Beta without success.

I see the following:
https://github.com/PowerShell/Win32-OpenSSH/issues/966

but no environment "DISPLAY" variable on my Windows 7
DISPLAY=localhost:0.0

Expected output

> ssh.exe myname@192.168.10.101
myname@192.168.10.101's password:

Actual output

> ssh.exe myname@192.168.10.101
key_load_public: invalid format
ssh_askpass: posix_spawn: No such file or directory
Host key verification failed.

**Comment by bagajjal** [comment]
@llinyu  - Enable more debugs logs, sshd.log (with DEBUG3 enabled), ssh logs (ssh -vvv user@ip).
Please validate what's difference between putty and win32-openssh ssh.exe.

**Comment by llinyu** [comment]
I am terribly sorry. I made a mistake. 
My OS has a DISPLAY environment variable I didn’t figure it out, it is the same problem as #966.

**Comment by pavelkomarov** [comment]
I don't think @llinyu made a mistake. I'm trying to get X forwarding working (long story) [with the same setup described here](https://unix.stackexchange.com/questions/207365/x-flag-x11-forwarding-does-not-appear-to-work-in-windows), but it keeps failing with "ssh_askpass: posix_spawn: No such file or directory".

`ssh-askpass.exe` isn't a thing in your release, and it's unclear to me where `ssh_askpass` might live. It can be an environment variable, but why should I have to set it and what to? Clearly the code should never try to call something that doesn't exist, or it's looking for it in the wrong place. It's strange, because when my DISPLAY environment variable isn't set ssh asks for my password the normal way, and it's fine. Why shouldn't it always get my password that way? This remains a bug.

**Comment by nicksunyang** [comment]
Have you solved it?

**Comment by psz2036** [comment]
I seem to have found a workaround: create an object \dev\tty (in C:), e.g. with
  mkdir \dev
  echo x > \dev\tty
then Win10 ssh will prompt for password "normally".
With Xming I also seem to need "set DISPLAY=localhost:0" and to use "ssh -Y".

**Comment by cwg999** [comment]
For readability, issue was resolved from #966 

Option 1:
> As a workaround it seems that it is possible to create a directory C:\dev with an empty file called tty, so that the path \dev\tty can be opened.

Option 2: (Not recommended)
> DISPLAY=localhost:0.0 was set. Removing/Renaming this variable resolved the issue.

**Comment by psz2036** [comment]
Sorry but unsetting DISPLAY is not a solution: you do need DISPLAY for X11 windows
(e.g. with Xming, or morr directly for the ssh options -X or -Y to make sense).

**Comment by psz2036** [comment]
(Can someone re-open this, please... or tell me how to do?)

**Comment by psz2036** [comment]
Seems that the comment of cwg999 should have been about #966 (not 996).
There (in #966) the issue is "resolved": was a bug, now corrected in sources...
so it will eventually make its way into the binary shipped with Windows10. Until
then, use the \dev\tty workaround (that is mentioned in #966, and independently
re-discovered and mentioned above).

**Comment by cwg999** [comment]
You are correct, I fixed my comment.

**Comment by idanpa** [comment]
I see the same problem with:
Windows 10 18363.535
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
After unsetting DISPLAY problem fixed, but this is not a solution for me since I would like to use X11 forwarding.

**Comment by psz2036** [comment]
Did you try the workaround: create an object /dev/tty e.g. with
  mkdir \dev
  echo x > \dev\tty
(as per this issue #1088 or #966).

**Comment by idanpa** [comment]
mkdir \dev
echo x > \dev\tty

Fixed that issue, thanks

**Comment by xianwenchen** [comment]
I have the same problem on Cygwin64 on a freshly installed Windows 10 (installed today).

**Comment by riverar** [comment]
~~@bagajjal Please re-open this. And provide status on resolution.~~

**Comment by blakeduffey** [comment]
I continue to have X Forwarding fail (it works via PuTTY)

i've created C:\dev\tty per the recommended work around

xterm: Xt error: Can't open display:
xterm: DISPLAY is not set

**Comment by riverar** [comment]
@blakeduffey what's your client command line? Presume it's some form of ssh -X or -Y user@host? What's the host running? What version of sshd?

**Comment by blakeduffey** [comment]
./ssh -K blake@host.fqdn -Y

Ubuntu 16.04.4

**Comment by riverar** [comment]
@blakeduffey Can you provide the output of `ssh -vvv -K -Y blake@host.fqdn`? Feel free to redact any key data that may appear.

**Comment by riverar** [comment]
@maertendMSFT Did a fix for this land in a shipping version of Windows?

**Comment by DrPepperBianco** [comment]
Hey, I've had the same problem today. Got it fixed with the \dev\tty solution.

I still don't understand, why this is closed. Creating linux folders in Windows is not a real solution but only a workaround. This issue should not be tagged as closed!

I'm looking forward to a real solution.

**Comment by blakeduffey** [comment]
Creating files in the root of C: is a short term workaround - I'm also not sure why this ticket would be closed.

**Comment by riverar** [comment]
@maertendMSFT Ping.

**Comment by maertendMSFT** [comment]
This has been fixed in the latest release on GitHub.  The Windows FOD bits lag a bit behind.  Please try the latest release: https://github.com/PowerShell/Win32-OpenSSH/releases

**Comment by blakeduffey** [comment]
By 'latest release' you mean v8.1.0.0p1-Beta released in Dec 2019?  I feel like that is the version I was trying with when I posted in FEB...
