### ISSUE TITLE
sshd.exe is missing

### ISSUE THREAD

**Issue by LavenPy** [PowerShell/Win32-OpenSSH#1090]
Please answer the following

**Client OperatingSystem**
Windows 2012 R2

**What is failing**
Installation Script

**Expected output**
`sshd and ssh-agent services successfully installed`

**Actual output**
`"sshd.exe is not present in script path"`

**Explanation**
Hello,

I am not sure about this problem that I have.

I tried to install the 1.0.0.0 beta build. While doing so, the installation Script trough the error
` "sshd.exe is not present in script path"`

I've searched inside the build for this exe but couldn't find it.
Do i do something wrong, or is this exe really missing in that build?
Later I tried it again with the version 0.23.0 and had the same problem again.

In my thoughts, to solve the problem the sshd.exe should get included into the latest build.

If i did something wrong I'd be happy to provide more Information.

**Comment by LavenPy** [comment]
- Downloaded the wrong build, please donwload source from [here](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.6.0.0p1-Beta)

took me longer than it should. I Hope my stupidity can help someone else

**Comment by bluelightning13** [comment]
Thanks for this - I was sent to the wrong download page by a Git Tutorial on installing this. So I was getting the same error...
