### ISSUE TITLE
sshd needs ssh-agent to run?

### ISSUE THREAD

**Issue by rgl** [PowerShell/Win32-OpenSSH#1092]
the `sshd` service does not start without the `ssh-agent` service already running.

if this is expected, can you add a service dependency into `install-sshd.ps1`? e.g. add something like:

```
sc.exe config sshd depend= ssh-agent
```

**"OpenSSH for Windows" version**
 `7.6.0.0` (from https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.6.0.0p1-Beta)
 
**Server OperatingSystem**
 `Windows Server 2016 Standard`

**Comment by manojampalam** [comment]
The dependency was removed in the earlier release. sshd can start and work standalone without ssh-agent (unless you have your host keys registered with agent).

**Comment by rgl** [comment]
I didn't explicitly register them with the ssh-agent. Is that done by default? I'm installing at https://github.com/rgl/windows-2016-vagrant/blob/master/provision.ps1#L117 by just unzip, calling install-ssh, and generating the host key with ssh-keygen. Was that supposed to use the agent?

**Comment by manojampalam** [comment]
No, you don't need to register them with ssh-agent. Can you following troubleshooting link in wiki, try running sshd in debug mode

**Comment by Suncatcher** [comment]
So, if I got it right, ssh-agent is installed by default when installed [via optional features](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/), and not installed at all when installed from Github, isn't it?
ssh-agent is just a more secure way of key management?

**Comment by bagajjal** [comment]
@Suncatcher - Starting from v1.0.0.0, ssh-agent is an optional service. 

The "OpenSSH Server" installed from "Windows optional feature" is based on v0.0.18.0 and it runs the ssh-agent by default. In release v.0.0.18.0, ssh-agent is used for generating user token, key based authentication and also secure key management.

If you install from GitHub latest, ssh-agent will be added as a service but it will not be started.
In latest Github release (after v1.0.0.0), ssh-agent is used for secure key management.
