### ISSUE TITLE
Unable to start session from linux to windows, subsystem fails

### ISSUE THREAD

**Issue by simenmusaeus** [PowerShell/Win32-OpenSSH#1095]
Please answer the following

**"OpenSSH for Windows" version**
OpenSSH_7.6p1, LibreSSL 2.5.3

**Server OperatingSystem**
Windows Server 2016 Standard

**Client OperatingSystem**
Ubuntu Server 16.04

**What is failing**
Not able to start subsystem

```
New-PSSession : [192.168.101.12] The background process reported an error with the following message: The SSH client session has ended with error message: subsystem request failed on channel 0.
At line:1 char:12
+ $session = New-PSSession -HostName 192.168.101.12 -UserName Administr ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : 2100,PSSessionOpenFailed
```

Following troubleshooting instructions [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps)

```
debug1: server_input_channel_open: ctype session rchan 0 win 2097152 max 32768                                          
debug1: input_session_request                                                             
debug1: channel 0: new [server-session]                                                   
debug1: session_new: session 0                                                            
debug1: session_open: channel 0                                                                                         
debug1: session_open: session 0: link with channel 0                                                                    
debug1: server_input_channel_open: confirm session                                                                      
debug1: server_input_global_request: rtype no-more-sessions@openssh.com want_reply 0                                    
debug1: server_input_channel_req: channel 0 request subsystem reply 1                                                   
debug1: session_by_channel: session 0 channel 0                                                                         
debug1: session_input_channel_req: session 0 req subsystem                                                              
subsystem request for powershell by user administrator@win-m6nf9tic3h7 failed, subsystem not found                      
Connection closed by 192.168.101.9 port 54838                                                                           
debug1: channel 0: free: server-session, nchannels 1                                                                    
Close session: user administrator@win-m6nf9tic3h7 from 192.168.101.9 port 54838 id 0                                    
debug1: do_cleanup                                                                                                      
Transferred: sent 2580, received 2192 bytes                                                                             
Closing connection to 192.168.101.9 port 54838   
```

my `sshd_config`
```
# override default of no subsystems
Subsystem	sftp	sftp-server.exe
Subsystem	powershell C:/Program Files/PowerShell/6.0.1/pwsh.exe -sshs -NoLogo -NoProfile
```

**Comment by manojampalam** [comment]
Sorry, this does not make sense, your server is Ubuntu Server 16.04 and your sshd_config looks like it belongs to Windows.

**Comment by simenmusaeus** [comment]
Sorry, swapped the server and the client, corrected the original question: it's a windows server I'm attempting to access with an ubuntu client.

**Comment by mrvladis** [comment]
@simenmusaeus Your sshd_config is it in the correct location, e.g. %ProgramData%\ssh\ ?
I have had the same issue when tried to modify config within the folder that contain binaries.

**Comment by bagajjal** [comment]
Any update on this? I tried, it works.

**Comment by manojampalam** [comment]
Did you try putting quotes around your exe 
`Subsystem	powershell "C:/Program Files/PowerShell/6.0.1/pwsh.exe" -sshs -NoLogo -NoProfile`

**Comment by two70** [comment]
I am having issues with connecting as well, but mine deals with the SSH transport process abruptly terminating.

Double check that your PowerShell executable is where you are saying it is in the config file. In my case, Server 2012R2, it is located at `"C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"`. I was originally getting the same error as you until I changed the location.

**Comment by simenmusaeus** [comment]
@mrvladis Your right, you need to edit the `sshd_config` found in `%ProgramData%\ssh\` (`C:\ProgramData\ssh\`), it works for me now.

Would it be an idea to make this more explicit in the [setup instructions](https://github.com/PowerShell/PowerShell/blob/866b558771a20cca3daa47f300e830b31a24ee95/docs/new-features/remoting-over-ssh/README.md)? 

Being unexperienced with OpenSSH "_..at the location where you installed Win32 Open SSH_" sounds to me like `C:\Program Files\OpenSSH`, and not `C:\ProgramData\ssh\`.

**Comment by bagajjal** [comment]
@simenmusaeus  - I requested powershell team to update their setup instructions. Thanks.

**Comment by bagajjal** [comment]
@simenmusaeus - Please create a issue with powershell team.

**Comment by Mohit-Ak** [comment]
> Did you try putting quotes around your exe
> `Subsystem	powershell "C:/Program Files/PowerShell/6.0.1/pwsh.exe" -sshs -NoLogo -NoProfile`

Yes, But this leads to another error. Do you know the fix for the issue?

**Comment by Mohit-Ak** [comment]
> I am having issues with connecting as well, but mine deals with the SSH transport process abruptly terminating.
> 
> Double check that your PowerShell executable is where you are saying it is in the config file. In my case, Server 2012R2, it is located at `"C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"`. I was originally getting the same error as you until I changed the location.

Yes, But this leads to another error. Did you manage to fix the issue?
