### ISSUE TITLE
Cant transfer file via SCP from Ubuntu to Windows 10, while runing OpenSSH installed in Windows 10

### ISSUE THREAD

**Issue by alphaCTzo7G** [PowerShell/Win32-OpenSSH#1097]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
Windows 10 Enterprise Evaluation

**Client OperatingSystem**
I am running the latest Windows 10 (MSEDGE on Win10(x64) Stable (16.16299)) on
VirtualBox VM from here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

I have installed the OpenSSH server and client on the Windows 10 VM. SSH and
SCP generally works fine.

**What is failing**

If I try to move files from my ubuntu box to the Windows 10 VM
in a specific directory using say

scp ./vim.txt username@10.12.38.34:/C:/vim.txt

as per the new implemention of file paths in
https://github.com/PowerShell/Win32-OpenSSH/issues/48,

I cant transfer files to specific directory under "C:/" when using 

**Expected output**

I expect that when I do scp with the above command, it should move the file to C:/vim.txt.

**Actual output**
the files dont get transfered to "C:/vim.txt" in my Windows VM. Rather it gets
transfered to "C:/Program Files/OpenSSH/C?vim.txt"

Notice the question mark in "C?vim.txt". It appears that ssh-server or client
cant understand the ":", and thus just puts the file in the default folder.

Does the port of OpenSSH not understand that C:\ is a drive?

**Comment by manojampalam** [comment]
@bingbing8 @bagajjal is this expected to work?

**Comment by bingbing8** [comment]
I am looking

**Comment by bingbing8** [comment]
@manojampalam it is not expected. but i can't repro it.
@alphaCTzo7G, which version did you try? I tried to transfer file from Ubuntu client to Windows 10 with [v7.6.0.0p1-Beta](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.6.0.0p1-Beta), it transfer file to the right directory.
```
scp ./test111.txt newlogin@10.123.40.97:/c:/test111.txt
The authenticity of host '[10.123.40.97]:47002 ([10.123.40.97]:47002)' can't be established.
ECDSA key fingerprint is SHA256:4WYuX61hW8qypuzqG2EP/Sn5YWRy7UoS+GDGeDfRirw.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[10.123.40.97]:47002' (ECDSA) to the list of known hosts.
newlogin@10.123.40.97's password:
test111.txt                                   100%   18    10.7KB/s   00:00 
```
What error do you see? Can you check trace from both client and server side and paste here? Thanks!
To enable client trace, supply -vvv to scp command. On client trace, you will see something like 
debug1: Sending command: scp -v -t /C:/test111.txt
on server trace file (C:\ProgramData\ssh\logs\sshd.log), you will see something like:
2336 2018-03-12 13:55:39.193 debug1: Executing command: C:\\test\\OpenSSH-Win64\\scp -t /C:/test111.txt.

**Comment by alphaCTzo7G** [comment]
You are right. There are 2 versions  of OpenSSH shipped withe the VM. OpenSSH6.7 which is already installed by default. And there is openssh v7. I believe which can be installed as an add-on feature. I tried both.. but they didnt work. 

Today I installed OpenSSHv7.6. Its mostly working. SCP works just like standard scp now. `ssh` still has some problems with certain programs.
