### ISSUE TITLE
[Regression] v7.6.0.0p1-Beta broke certain domain logons

### ISSUE THREAD

**Issue by manojampalam** [PowerShell/Win32-OpenSSH#1098]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
v7.6.0.0
 
**Server OperatingSystem**
Windows 10 Enterprise

**Client OperatingSystem**
Windows 10 Enterprise

**What is failing**
Domain account logons may fail if FQDNN is used or the account does not have permissions to query AD

**Expected output**
It works

**Actual output**
Unable to login with debug logs showing failures with the following API call
`NetUserGetInfo() failed with error:  XXXXX`

**Comment by dwatley** [comment]
@manojampalam - Is this still on track for next release, and is the next release still targeted for this week? I haven't seen a PR come through yet.

**Comment by manojampalam** [comment]
Yes. It was fixed as part of https://github.com/PowerShell/openssh-portable/commit/2c559a2b6c498239a8082f83fbec8ead98842d6b

in file sshd.c

We have a couple of PRs in the pipeline.. Release should be out once they go through.

**Comment by dwatley** [comment]
Ah I missed it since the issue or change wasn't referenced in the commit notes. Thanks for the update, looking forward to testing.

**Comment by dwatley** [comment]
Confirming the latest release fixed this for me.
