### ISSUE TITLE
RSA keys in the repo

### ISSUE THREAD

**Issue by ktos** [PowerShell/Win32-OpenSSH#11]
I am not sure if any of files d2utmp*, like https://github.com/PowerShell/Win32-OpenSSH/blob/L1/d2utmpa09344, https://github.com/PowerShell/Win32-OpenSSH/blob/L1/d2utmpa09960 or https://github.com/PowerShell/Win32-OpenSSH/blob/L1/d2utmpa03344, https://github.com/PowerShell/Win32-OpenSSH/blob/L1/d2utmpa09348 should be in the code repository, as they are "private" keys.

You can purge them (https://help.github.com/articles/remove-sensitive-data/), but I think they may be treated as compromised at the moment.

**Comment by manojampalam** [comment]
Those were test keys, now deleted.
