### ISSUE TITLE
Not able to redirect output from ssh-agent

### ISSUE THREAD

**Issue by kadet1090** [PowerShell/Win32-OpenSSH#110]
It's impossible to redirect (or pipe) output from ssh-agent in powershell, it hangs and therefore there is no possibility to use any of automated scripts. 
![screenshot](https://dl.dropboxusercontent.com/u/60020102/ShareX/2016-02/2016-02-14_13-57-15-6e.png)

Any workaround?

**Comment by manojampalam** [comment]
Not any that I know. We are currently reviewing security around ssh-agent and the current implementation will likely change. will incorporate this feedback

**Comment by dahlbyk** [comment]
Does the pipe work if you redirect error to standard?

```
ssh-agent 2>&1 | Out-Clipboard
```

**Comment by dahlbyk** [comment]
Nevermind, just found this: https://github.com/PowerShell/Win32-OpenSSH/commit/fe136bc35276eeb8566264ccc0e6787343cb96cf.

> ssh-agent.exe and ssh-add.exe code updated and fixed to work in Windows.
> For convenience of users, ssh-agent.exe starts a cmd shell with the
> "SSH_AUTH_SOCK" and "SSH_AGENT_PID" environment variables set.
> ssh-add.exe can be run immediately from the cmd shell. 'ssh-add -L" and
> "ssh-add id_rsa"  and "ssh-add -d id_rsa" are 3 useful commands to list,
> add and delete keys from ssh-agent cache.

The `start cmd` is breaking anyone using this with posh-git, and I'm not sure there's any way for me to work around and kill the `cmd.exe` that's being spawned.

**Comment by manojampalam** [comment]
ssh-agent is reimplemented for Windows as a OS service. check out 5_15_2016  release details

**Comment by jkodroff** [comment]
@manojampalam Can you say when we can expect to see this in the Chocolatey package?  My Chocolatey shows win32-openssh 2016.05.30, but this bug is still being exhibited and I don't see ssh-agent as a service anywhere.
