### ISSUE TITLE
Possible Bug In Socket Code

### ISSUE THREAD

**Issue by NoMoreFood** [PowerShell/Win32-OpenSSH#1104]
It appears there could be a bug in socketio.c that is causing unit tests to fail and could cause crashes.  Upon inspection, it looks socketio_WSARecv() allocates an internal buffer (wsabuf.buf) with 70KB (INTERNAL_RECV_BUFFER_SIZE).  It stores this length in wsabuf.len.   However, wsabuf.len is blindly overwritten by a parameter to the socketio_WSARecv() called 'len' which could be greater than 70KB.  As a result WSARecv() will fail with WSAEFAULT since the length specified falls outside of the allocated buffer.  

I replaced the latter assignment of `wsabuf.len = len` with `wsabuf.len = min(len, wsabuf.len)` and that seemed to make the tests happier, although I'm not certain this is quite was intended here.

Link:

https://github.com/PowerShell/openssh-portable/blob/fb1342f7e07565ccee583078629db3687ec6d732/contrib/win32/win32compat/socketio.c#L197

**Client Operating System**
Windows 10 Enterprise

**What is failing**
Unit Tests / Socket

**Expected output**
Successful

**Actual output**
```
V:\Code\openssh-portable\contrib\win32\openssh\..\..\..\regress\unittests\win32compat\socket_tests.c:540 test #22 "select send and recv"
ASSERT_INT_EQ(errno, EAGAIN) failed:
       errno = 14
      EAGAIN = 11
```

**Comment by manojampalam** [comment]
You're right and the fix is accurate.

**Comment by NoMoreFood** [comment]
Are you going to take care of changing this or should I?

**Comment by manojampalam** [comment]
If its blocking you, go ahead and fix it, else I'll take care of it.

**Comment by NoMoreFood** [comment]
I also see another unit test that's failing (not one of mine) so I'll investigate that as well and put in changes for both (as necessary).

**Comment by manojampalam** [comment]
Which one?

**Comment by NoMoreFood** [comment]
I haven't look at it at a possible causes yet:

```
V:\Code\openssh-portable\contrib\win32\openssh\..\..\..\regress\unittests\win32compat\file_tests.c:126 test #25 "file io and fstat"
ASSERT_INT_EQ(st.st_mode & 0777, 0600) failed:
st.st_mode & 0777 = 391
        0600 = 384
```

**Comment by NoMoreFood** [comment]
Alright, just looked at that last one.  It appears that's just a problem with the test assuming what the default, inherited permissions are on the file system where the test is being run.

**Comment by NoMoreFood** [comment]
This was addressed with my pull: https://github.com/PowerShell/openssh-portable/pull/288.  Closing.
