### ISSUE TITLE
'Match Group' fails to match on member of either local or domain group

### ISSUE THREAD

**Issue by ebekker** [PowerShell/Win32-OpenSSH#1105]
**"OpenSSH for Windows" version**
`7.6.0.0` (installed via choco)
 
**Server OperatingSystem**
 `Windows Server 2016 Datacenter`

**Client OperatingSystem**
`Windows 10`

**What is failing**
Configured sshd_config with a `Match Group` clause referencing either a local group or an AD domain group, but neither works to match incoming users.

However, when I use a `Match User` clause to target a specific domain user using the notation `user@domain` where domain is the short name, the match clause works.

**Comment by bagajjal** [comment]
To debug further, enabled DEBUG3 logs in sshd.log.

**Comment by ebekker** [comment]
Thanks, should've tried that to start, but glad I filed the issue, I can document my findings here for benefit of others.

So here are the issues...

~~1. For starters, was getting the error:~~
```
NetUserGetInfo() failed with error: 2221 for user: XXXX and domain: (null)
```
~~Turns out that in order to test against a domain user's group memberships you have to use a domain qualified form of the username, so when you sign in, you have to use something like `domain\username`.~~ 

~~What's interesting is that when you don't qualify it with the domain, it doesn't satisfy the Match Group, *however* the authentication  still succeeds, so the main authentication piece is still resolving against the domain user account.  This could be a security issue, no?  A user who would otherwise be restricted `Match` configuration, would be able to bypass it.~~

This turned out to be a non-issue, see my comment below.

2. After I started signing in with domain-qualified username, I found that `Match` clause was still not matching against the group name which was specified in `group@domain` format.  Here it turns out, I specified the group name in mixed case to match how it's defined in AD (based on ADUC), but in the log it was clearly testing against the lowercased-form of the group names + domains.  So once I updated the `Match` clause to lowercase the group name, it started working.

**Comment by ebekker** [comment]
Turns out (1) above was incorrect on my part, I misinterpreted the log output.  It was strictly (2) issue, once the groups names were all lowercased in the `Match` everything works as expected.
