### ISSUE TITLE
Intermittent flashing when resizing console

### ISSUE THREAD

**Issue by musm** [PowerShell/Win32-OpenSSH#1109]
Installed from:  Add optional features
Build: Win 10 17115.1

![test4](https://user-images.githubusercontent.com/4319522/37609696-2a766566-2b74-11e8-8d84-38aa46a97d45.gif)

**Comment by bagajjal** [comment]
@musm - Due to a bug in conhost.exe (windows console executable), we don't support resizing. If you resize then we restore the window back.

**Comment by musm** [comment]
that's a pretty bad, any chance the conhost bug can be reported ?  Is there somewhere we can track progress on this.

**Comment by bagajjal** [comment]
I already filed a bug. Conhost team is working on it.
Unfortunately this bug can't be tracked outside of Microsoft.

**Comment by bagajjal** [comment]
I have listed the [known console issues](https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH) related to conhost.exe. 

Please file  new issue if it's not a known console issue.

**Comment by riverar** [comment]
Can you please provide the TFS # for reference? Thanks!

**Comment by bagajjal** [comment]
FYI, TFS ID - 15683949

**Comment by riverar** [comment]
It's also worth mentioning in some ncurses apps, like iftop, resizing completely hangs conhost and you have to kill it, as of 17134.

**Comment by musm** [comment]
Seems to be fixed?

**Comment by riverar** [comment]
Can confirm flashing and hanging (e.g. iftop) is gone in 17763
