### ISSUE TITLE
Add/set registry setting of default shell with powershell registry editor cmdlet. How to.

### ISSUE THREAD

**Issue by ivakyb** [PowerShell/Win32-OpenSSH#1111]
There is a nice topic [Install-Win32-OpenSSH].

I suggest to improve it with adding few lines about **setting registry entry DefaultShell with Powershell cmdlets**. Next command will set default shell *Git Bash*
```
PS> Set-ItemProperty HKLM:\SOFTWARE\OpenSSH -Name DefaultShell -Value "C:\devel\Git\bin\bash.exe"
```
In most cases arguments (cmd options) are not required. We may leave this value default (undefined). Or set with next command.
```
PS> Set-ItemProperty HKLM:\SOFTWARE\OpenSSH -Name DefaultShellCommandOption -Value "MY_ARGUMENTS"
```

### This is much more convenient then *regedit*

 [Install-Win32-OpenSSH]: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by DarwinJS** [comment]
There is something that does a little more than that in the universal installer: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/tools/Set-SSHDefaultShell.ps1

**Comment by bagajjal** [comment]
I updated the wiki.
