### ISSUE TITLE
beta 7.x.x.x with key auth breaks Exchange console

### ISSUE THREAD

**Issue by PretorianX** [PowerShell/Win32-OpenSSH#1115]
Hi guys, if login with password this sequence works, if with ssh key I receive an error:

 `Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

PS C:\scripts\new>
PS C:\scripts\new> add-pssnapin Microsoft.Exchange.Management.PowerShell.E2010
PS C:\scripts\new> Get-Mailbox
Get-Mailbox : Value cannot be null.
Parameter name: parameters
At line:1 char:12
+ Get-Mailbox <<<<
    + CategoryInfo          : NotSpecified: (:) [Get-Mailbox], ArgumentNullException
    + FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.Exchange.Management.RecipientTasks.GetMailbox`

How to reproduce: 
W2k8r2, Exchange 2010, powershell 2.0

1. Logon to powershell, or with DefaultShell or typing powershell
2. load "add-pssnapin Microsoft.Exchange.Management.PowerShell.E2010"
3. execute "Get-Mailbox"

**Comment by manojampalam** [comment]
See #518
