### ISSUE TITLE
couldn't stat remote file: Permission denied for mapped s: drive with public/private key

### ISSUE THREAD

**Issue by cstalker99** [PowerShell/Win32-OpenSSH#1116]
Scenario:  Connecting via SFTP from server1 (Linux server) to server2 (Windows server with sshd service).
S: drive is a mapped drive to another windows server.
All works fine when id/password validation is used.  The server-to-server connection succeeds and all mapped drives on sshcp001 (C:, F:, and S:) can be accessed.  See example for drive S: below.

infarcr@server1:/opt/informatica/pc_rcr > sftp ftpdds@server2
ftpdds@server2's password:
Connected to server2.
sftp> pwd
Remote working directory: /C:/Users/ftpdds
sftp> cd /S:/
sftp> cd General-Offices-GO/ftpxfr
sftp> pwd
Remote working directory: /S:/General-Offices-GO/ftpxfr
sftp> bye

When public/private key authentication is used, the server-to-server connection also succeeds.  However, a “Couldn’t stat remote file: Permission denied” error occurs when attempting to access the S: drive.  Accessing any other drive on the machine (C: or F: local to serverfor example) works fine.

infarcr@server1:/opt/informatica/pc_rcr > sftp -i ~/.ssh/ftpdds_server2 ftpdds@domainName@server2
Connected to server2.
sftp> pwd
Remote working directory: /C:/Users/ftpdds
sftp> cd /S:/
Couldn't stat remote file: Permission denied
sftp> bye

any suggest on how to fix this?

**Comment by cstalker99** [comment]
version v1.0.0.0-Beta of openssh installed on server2

**Comment by bagajjal** [comment]
see issue #518

**Comment by I1eoThe0ne** [comment]
**Work-Around** (since - unfortunately - logging in using key-files does not authenticate agains the AD)

**net use z: \\server\share /user:userName password**

**After the net use command the user is authenticated** - even against the AD and you can access network shares.
