### ISSUE TITLE
SFTP doesn't support hardlinks

### ISSUE THREAD

**Issue by manojampalam** [PowerShell/Win32-OpenSSH#1119]
Please answer the following

**"OpenSSH for Windows" version**
All up to v7.6.1.0
 
**Server OperatingSystem**
Any Windows OS

**Client OperatingSystem**
Any client

**What is failing**
SYMLINK command in SFTP session

**Expected output**
It works

**Actual output**
Fails with error

**Comment by NoMoreFood** [comment]
@manojampalam I know you make this for tracking.  The better characterization of 'What was failing' would be "ln command without '-s' specified".  In the SFTP server 'ln' routes to link() to create hardlinks.  That's what this more recent commit addresses.  'ln -s' routes to 'symlink()' which has already been released.

**Comment by manojampalam** [comment]
@NoMoreFood I was just trying out this on the latest source. See the following
`sftp> ls -lrt`
`-rw-******    1 -        -             408 May  2 22:06 a`
`sftp> ln a link`
`sftp> ls -lrt`
`-rw-******    1 -        -             408 May  2 22:06 link`
`-rw-******    1 -        -             408 May  2 22:06 a`

Looks like `link` is a copy of `a`. Is this expected?

**Comment by NoMoreFood** [comment]
Yes, although not a copy -- they are pointers to the same data on the file system.
