### ISSUE TITLE
Certificate Authentication doesn't work

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#1122]
I can't do certification authentication such as pubic/private key authentication.
Can you plz show me detail instructions for this?

**Comment by manojampalam** [comment]
https://github.com/PowerShell/Win32-OpenSSH/wiki/Certificate-Authentication

**Comment by ghost** [comment]
I can't do like that

**Comment by ghost** [comment]
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 35.187.224.170 [35.187.224.170] port 22.
debug1: Connection established.
debug1: identity file Desktop/aa type -1
debug1: identity file Desktop/aa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_7.6
debug1: match: OpenSSH_for_Windows_7.6 pat OpenSSH* compat 0x04000000
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-sha1-etm@openssh.com none
debug1: kex: client->server aes128-ctr hmac-sha1-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA 02:00:68:bc:a8:94:80:83:aa:b6:dc:90:7d:7b:bf:54
debug1: Host '35.187.224.170' is known and matches the ECDSA host key.
debug1: Found key in /home/pyephyoeaung/.ssh/known_hosts:11
debug1: ssh_ecdsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Trying private key: Desktop/aa
debug1: key_parse_private2: missing begin marker
debug1: read PEM private key done: type RSA
debug1: Authentications that can continue: publickey,keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug1: Authentications that can continue: publickey,keyboard-interactive
debug1: No more authentication methods to try.
Permission denied (publickey,keyboard-interactive).

**Comment by manojampalam** [comment]
Get server side traces

**Comment by pboard** [comment]
it could be the file ownership on the userprofile\ .ssh\authorized_keys file - If you enable server side debugging in the sshd_config file in ProgramData\ssh (DEBUG3 for the debug level), you should find the reason why it is failing. That was my issue when testing key authentication
