### ISSUE TITLE
Start openSSH with legacy key support

### ISSUE THREAD

**Issue by zack-snyder** [PowerShell/Win32-OpenSSH#1124]
My client seems to have an older openSSH version (unfortunately I cannot upgrade)
I cannot connect to openSSH server. SSH cannot negotiate
"OpenSSH for Windows" version
0.0.18.0

Server OperatingSystem
Windows 10 Pro

Added following in sshd_config
```
KexAlgorithms diffie-hellman-group1-sha1,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
Ciphers 3des-cbc,blowfish-cbc,aes128-cbc,aes128-ctr,aes256-ctr
```

What is failing
```
1716 18:01:04:153 Unable to negotiate with 192.168.115.188 port 56216: no matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
```
After adding the old key algorithms:
login failed:
starting sshd service

Expected output
start should work

**Comment by manojampalam** [comment]
Recommend, just downloading and trying out the new client (you don't need to install anything).

**Comment by bagajjal** [comment]
@zack-snyder - Looks like you are using windows optional feature. If yes then we support only ed25519.
Try using our github latest [release binaries](https://github.com/PowerShell/Win32-OpenSSH/releases)

**Comment by zack-snyder** [comment]
Please reopen, there was an error getting the version information correctly (I just previously downloaded OpenSSH via windows feature installer) then downloaded from github latest release.
```
C:\Program Files\OpenSSH>sshd.exe --version
unknown option -- -
OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
usage: sshd [-46DdeiqTt] [-C connection_spec] [-c host_cert_file]
            [-E log_file] [-f config_file] [-g login_grace_time]
            [-h host_key_file] [-o option] [-p port] [-u len]
```

**Comment by bagajjal** [comment]
@zack-snyder - The version number mentioned in the issue description is 0.0.18.0. If you are using the GitHub version then you shouldn't hit this issue. Please note that the sshd_config location has changed to %programdata%\ssh\ starting from v1.0.0.0. 

sshd.exe doesn't support "--version". FYI, [SSHD man page](https://www.freebsd.org/cgi/man.cgi?sshd(8))

Please try our [troubleshooting steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps). If you still hit the issue then share sshd.log(with DEBUG3 enabled), ssh log (ssh -vvv user@ip).
