### ISSUE TITLE
sshd.log is not created

### ISSUE THREAD

**Issue by zack-snyder** [PowerShell/Win32-OpenSSH#1125]
I installed openSSH now like described here:
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

However, I am missing the log file `sshd.log`

**"OpenSSH for Windows" version**
0.0.18.0
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Ubuntu 16.04 x64

**What is failing**
No login file is created.

**Expected output**
A valid file in: `C:\ProgramData\ssh\logs\sshd.log`

**Actual output**
Only a folder:
 `C:\ProgramData\ssh\logs\`

**Comment by zack-snyder** [comment]
Here my config file from : `C:\ProgramData\ssh\`
[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1884675/sshd_config.txt)

**Comment by manojampalam** [comment]
Please use the latest version. Things have changed quite a bit since 0.0.18.0. Reopen if you still see any issues.

**Comment by zack-snyder** [comment]
@manojampalam 
What do you mean with latest version? I have downloaded this version 4 day ago.
From here: https://github.com/PowerShell/Win32-OpenSSH/releases

**Comment by zack-snyder** [comment]
```
C:\Program Files\OpenSSH>sshd.exe --version
unknown option -- -
OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
```

**Comment by manojampalam** [comment]
Did you read the release notes ?

`Note:
New Logging facility added (ETW). Check out Logging Facilities for options to switch to file based logging.`
