### ISSUE TITLE
Permission denied (publickey,keyboard-interactive).

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#1126]
public key authentication doesn't work for me.
I added client public key to server's authorized key.
Can you plz  show me detail instruction?

**Comment by ghost** [comment]
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 35.187.224.170 [35.187.224.170] port 22.
debug1: Connection established.
debug1: identity file Desktop/aa type -1
debug1: identity file Desktop/aa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_7.6
debug1: match: OpenSSH_for_Windows_7.6 pat OpenSSH* compat 0x04000000
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-sha1-etm@openssh.com none
debug1: kex: client->server aes128-ctr hmac-sha1-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA 02:00:68:bc:a8:94:80:83:aa:b6:dc:90:7d:7b:bf:54
debug1: Host '35.187.224.170' is known and matches the ECDSA host key.
debug1: Found key in /home/pyephyoeaung/.ssh/known_hosts:11
debug1: ssh_ecdsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Trying private key: Desktop/aa
debug1: key_parse_private2: missing begin marker
debug1: read PEM private key done: type RSA
debug1: Authentications that can continue: publickey,keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug1: Authentications that can continue: publickey,keyboard-interactive
debug1: No more authentication methods to try.
Permission denied (publickey,keyboard-interactive).

**Comment by manojampalam** [comment]
see https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples. Reopen if you see any issues.

**Comment by petsuter** [comment]
I had the same problem. [This](https://stackoverflow.com/a/50502015/3679043) fixed it  for me:
> 4. Choose "Convert inherited permissions into explicit permissions on this object" when prompted;
> 5. (really, really important) Remove all permissions on file except for the `SYSTEM` and yourself. There must be exactly two permission entries on the file. Some guides suggest running the `Repair-AuthorizedKeyPermission $env:USERPROFILE\.ssh\authorized_keys` - this will try to add the `sshd` user to the permission list and it will break the authentication, so, don't do that, or at least do not agree on adding the `sshd` user). Both `SYSTEM` and yourself should have full control over the file.

**Comment by kenny1983** [comment]
@petsuter Nope, doesn't work for me. Running the latest Windows 10 x64 1903 on both client and server. Have setup keys and disabled password auth in C:\ProgramData\ssh\sshd_config. That should have been enough IMO, but no...then I came here from a Google search, saw your comment and thought "Ah-ha!". But guess what? Still no freaking dice!!

Hey Windows devs in charge of this "feature", how about you pull your thumbs out of your proverbial unsunny places, and implement this $#%&ing thing right?!?!?!?! I'll even do it for you if you like; I bet it'd take me 5 freaking minutes!!!!!!

Instead I've wasted 2 $#%&ing hours on this utter BS because of your gross ineptitude. When I could have just downloaded Putty and been done with it 1 hour and 55 minutes ago. Thanks a lot for the **great** feature!!!

**Comment by rwalle** [comment]
> I had the same problem. [This](https://stackoverflow.com/a/50502015/3679043) fixed it for me:
> 
> > 1. Choose "Convert inherited permissions into explicit permissions on this object" when prompted;
> > 2. (really, really important) Remove all permissions on file except for the `SYSTEM` and yourself. There must be exactly two permission entries on the file. Some guides suggest running the `Repair-AuthorizedKeyPermission $env:USERPROFILE\.ssh\authorized_keys` - this will try to add the `sshd` user to the permission list and it will break the authentication, so, don't do that, or at least do not agree on adding the `sshd` user). Both `SYSTEM` and yourself should have full control over the file.

For me, in addition to the permission issues, commenting out the last two lines, i.e. `Match Group administrators` fixed it. Wasted 2 hours on this. Microsoft really needs to improve their documentation.
