### ISSUE TITLE
Pubkey auth failure(appears to succeed?)

### ISSUE THREAD

**Issue by HSSupport** [PowerShell/Win32-OpenSSH#1127]
Please answer the following

**"OpenSSH for Windows" version**
7.6.0.0
 
**Server OperatingSystem**
Windows Server 2012 R2

**Client OperatingSystem**
Windows 10 64bit

**What is failing**
server appears to authenticate pubkey, then fails
**Expected output**
connection to term
**Actual output**
4288 2018-04-09 16:32:51.393 Connection from 192.168.99.X port 63721 on 192.168.99.X port 2358
4288 2018-04-09 16:32:51.394 debug1: Client protocol version 2.0; client software version PuTTY_Release_0.69
4288 2018-04-09 16:32:51.394 debug1: no match: PuTTY_Release_0.69
4288 2018-04-09 16:32:51.394 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.6
4288 2018-04-09 16:32:51.477 debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
4288 2018-04-09 16:32:51.477 debug1: SSH2_MSG_KEXINIT sent [preauth]
4288 2018-04-09 16:32:51.478 debug1: SSH2_MSG_KEXINIT received [preauth]
4288 2018-04-09 16:32:51.478 debug1: kex: algorithm: curve25519-sha256@libssh.org [preauth]
4288 2018-04-09 16:32:51.478 debug1: kex: host key algorithm: ssh-ed25519 [preauth]
4288 2018-04-09 16:32:51.478 debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha2-256 compression: none [preauth]
4288 2018-04-09 16:32:51.478 debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha2-256 compression: none [preauth]
4288 2018-04-09 16:32:51.478 debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
4288 2018-04-09 16:32:51.504 debug1: rekey after 4294967296 blocks [preauth]
4288 2018-04-09 16:32:51.504 debug1: SSH2_MSG_NEWKEYS sent [preauth]
4288 2018-04-09 16:32:51.504 debug1: expecting SSH2_MSG_NEWKEYS [preauth]
4288 2018-04-09 16:32:51.925 debug1: SSH2_MSG_NEWKEYS received [preauth]
4288 2018-04-09 16:32:51.925 debug1: rekey after 4294967296 blocks [preauth]
4288 2018-04-09 16:32:51.925 debug1: KEX done [preauth]
4288 2018-04-09 16:32:51.929 debug1: userauth-request for user DOMAIN.local\\\\administrator service ssh-connection method none [preauth]
4288 2018-04-09 16:32:51.929 debug1: attempt 0 failures 0 [preauth]
4288 2018-04-09 16:32:51.948 debug1: userauth-request for user DOMAIN.local\\\\administrator service ssh-connection method publickey [preauth]
4288 2018-04-09 16:32:51.948 debug1: attempt 1 failures 0 [preauth]
4288 2018-04-09 16:32:51.948 debug1: userauth_pubkey: test whether pkalg/pkblob are acceptable for RSA SHA256:cWRbox04tklEGYQNILhzS3nR1Mvk3GM4kgIsue8Z37E [preauth]
4288 2018-04-09 16:32:51.948 debug1: trying public key file C:\\Users\\administrator.DOMAIN\\.ssh/authorized_keys
4288 2018-04-09 16:32:51.948 debug1: matching key found: file C:\\Users\\administrator.DOMAIN\\.ssh/authorized_keys, line 1 RSA SHA256:cWRbox04tklEGYQNILhzS3nR1Mvk3GM4kgIsue8Z37E
4288 2018-04-09 16:32:51.948 Postponed publickey for blackadder.local\\\\administrator from 192.168.99.X port 63721 ssh2 [preauth]
4288 2018-04-09 16:32:55.508 debug1: userauth-request for user DOMAIN.local\\\\administrator service ssh-connection method publickey [preauth]
4288 2018-04-09 16:32:55.509 debug1: **attempt 2 failures 0 [preauth]**
4288 2018-04-09 16:32:55.509 debug1: trying public key file C:\\Users\\administrator.DOMAIN\\.ssh/authorized_keys
4288 2018-04-09 16:32:55.510 debug1: **matching key found**: file C:\\Users\\administrator.DOMAIN\\.ssh/authorized_keys, line 1 RSA SHA256:cWRbox04tklEGYQNILhzS3nR1Mvk3GM4kgIsue8Z37E
4288 2018-04-09 16:32:55.511 debug1: **monitor_child_preauth: DOMAIN.local\\administrator has been authenticated by privileged process**
4288 2018-04-09 16:32:55.514 debug1: monitor_read_log: child log fd closed
4680 2018-04-09 16:32:57.883 **Invalid user administrator@domain from 192.168.99.X port 63721**
4288 2018-04-09 16:32:57.938 debug1: do_cleanup

**Comment by manojampalam** [comment]
You are hitting this - https://github.com/PowerShell/Win32-OpenSSH/issues/1098

This is fixed in latest release. Try it out.
