### ISSUE TITLE
LogFacility in EventLog documentation is incorrect

### ISSUE THREAD

**Issue by dwatley** [PowerShell/Win32-OpenSSH#1128]
https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities

**LogFacility** isn't a recognized option from sshd. Should be **SyslogFacility**. Also, the **Debug** channel never seems to be registered even though DEBUG3 is enabled in the sshd_config.

**Comment by manojampalam** [comment]
Fixed and added instructions to see debug logs in Event Viewer.
