### ISSUE TITLE
v7.6.1.0p1-Beta Console Experience Problems

### ISSUE THREAD

**Issue by pldmgg** [PowerShell/Win32-OpenSSH#1129]
We start off like this in a CMD prompt...

    Microsoft Windows [Version 10.0.17133.1]
    (c) 2018 Microsoft Corporation. All rights reserved.

    C:\Users\pdadmin>set SSH_TERM_CONHOST_PARSER=0

    C:\Users\pdadmin>set SSH_TERM_CONHOST_PARSER
    SSH_TERM_CONHOST_PARSER=0

    C:\Users\pdadmin>

...Then we ssh...

    C:\Users\pdadmin>ssh zeroadmin@zero@win16zerows
    Windows PowerShell
    Copyright (C) 2016 Microsoft Corporation. All rights reserved.

    PS C:\Users\zeroadmin>

...Note that we have the Default Shell set as Windows PowerShell 5.1 on Win16ZeroWS. Next, we just try `$env:ComputerName` and it just start overwriting the beginning of our CMD prompt...

    $env:ComputerNameWIN16ZEROWS
    PS C:\Users\zeroadmin oration. All rights reserved.

    C:\Users\pdadmin>set SSH_TERM_CONHOST_PARSER=0

    C:\Users\pdadmin>set SSH_TERM_CONHOST_PARSER
    SSH_TERM_CONHOST_PARSER=0

    C:\Users\pdadmin>      

The same thing happens if I start from PowerShell (as opposed to CMD prompt).

The previous version (i.e. v7.6.0.0p1-Beta) did not have this problem...

**Comment by maertendMSFT** [comment]
Closing, please reopen if this repros on the latest build
