### ISSUE TITLE
Add testcase to validate link() functinoality.

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/Win32-OpenSSH#1132]
link() support is added as part of https://github.com/PowerShell/openssh-portable/pull/297.
We need to add testcase to validate link() functionality.

**Comment by NoMoreFood** [comment]
@bagajjal You want me to take care of this?

**Comment by bagajjal** [comment]
sure, if you have free cycles.

**Comment by NoMoreFood** [comment]
I put in a pull request for a unit test of link(): https://github.com/PowerShell/openssh-portable/pull/304
