### ISSUE TITLE
[xml] "Save" Method Does Not Work On Nano

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#1134]
I added the ETW registration code to the chocolatey package, but it errors out on Nano saying it cannot find an override for method "Save" with 1 argument.

I played around with other ways to update the file, but could not get it to work cleanly.

As a workaround I have forced on file based logging on Nano in the Chocoatey package.

**Comment by bingbing8** [comment]
@DarwinJS, what is the code for ETW registration? this line or something else?
```
wevtutil um `"$etwman`"
```

**Comment by DarwinJS** [comment]
Opps sorry @bingbing8  - it is this:

```
$xml.Save($etwman)
```
Right here: https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/openssh/install-sshd.ps1#L36

**Comment by bingbing8** [comment]
@DarwinJS, the failures are due to the fact that XMLDocument.Save does not take path as parameter in .NET 1.0.  will fix it.
