### ISSUE TITLE
Support for Remote Scripted Commands via SSH

### ISSUE THREAD

**Issue by pboard** [PowerShell/Win32-OpenSSH#1135]
Please answer the following

**"OpenSSH for Windows" version**
7.6.1
 
**Server OperatingSystem**
Windows Server 2012

**Client OperatingSystem**
Windows Server 2012

**What is failing**
OpenSSH is not executing remotely passed scripted commands. Using the Putty SSH client, the -m parameter, say with a file commands.txt to run, with Cygwin OpenSSH I can supply a list of commands to execute with the remote shell. MS OpenSSH implementation seems to be only executing the very first line of the script.

Both Bash and Windows shells via Cygwin SSH can process commands to be part of a scripted session.

**Expected output**
example - commands.txt passed as a parameter
echo %systemdrive% > runme.bat
echo CD\folder >> runme.bat
echo runmycommand.exe par1 parm2 >> runme.bat
echo blat result.txt -t user@email >> runme.bat
call runme.bat

**Actual output**
the runme.bat will have say "C:"
and the rest of the script never runs

**Comment by manojampalam** [comment]
Can you explain how you would use Cygwin's OpenSSH in this case? how ssh command line looks?

**Comment by pboard** [comment]
So for Cygwin SSH, individual users can have custom shells, defined in /etc/passwd (currently the MS version seems to only support one global shell - another issue). So we can have some users on a Unix Bash Shell, others on a Windows Command shell.

Many years ago, there was a custom shell named "switch.exe" that was part of a Cygwin SSH package named CopSSH. This would execute a script passed to the SSH connection (using the putty.exe SSH client -m parameter - to provide a text file with a list of commands to run - like a batch file really - I don't know if the default SSH opensource client has this function), provide a Windows CMD.exe session, and supported SFTP / SCP transfers. The built in bash shell provides the same basic services, with the ability to be passed a text file containing bash / sh commands to execute in a scripted fashion, and provides SFTP / SCP services as well).

Anyway, when we went to a 64bit Cygwin, the switch.exe tool didn't work, so I was able to write an equivalent function using a basic Shell Script. This works on both 64bit and 32bit Cygwin OpenSSH. We were able to just drop this in and replace the switch.exe with a shell script named switch.

It provides a Windows CMD.exe if no script is passed to the SSH client, if a script is passed, it redirects the script to a temporary file temp.bat and then executes it - it also tidies up escaping sequences (caused by Unix / SSH).

/bin/switch (shell script)
-----------------------
#!/bin/bash
if [ "$*" != "-c /bin/sftp-server" ]; then
if [ "$*" == "" ]; then
cmd.exe
else
echo "Executing Script"
commandstring=${*//\\\\\\/\\}
echo "${commandstring:3}" > temp.bat
cmd.exe /c temp.bat
del temp.bat
fi
exit 1
fi
exec /bin/sftp-server
-----------------------

Example script passed to the switch shell using the Putty SSH client, using -m "script.txt"
Due to behaviour of the old switch.exe and Cygwin, backslashes are encoded with three backslashes \\\, the comandstring in the shell script, converts it back for Windows execution to single slashes

example script.txt 
------------
echo %systemdrive%  > runme.bat
echo cd\\\path to patchaudit\\\patchcheck >> runme.bat
echo copy scripttorun.bat flagtorun.txt /Y >> runme.bat
echo patchaudit.bat %computername% clientid %systemdrive% >> runme.bat
cmd /c call runme.bat
------------
