### ISSUE TITLE
Installation on Server 2012 Essentials - service fails to start

### ISSUE THREAD

**Issue by HSSupport** [PowerShell/Win32-OpenSSH#1137]
Please answer the following

**"OpenSSH for Windows" version**
 7.6.1.0p1
 
**Server OperatingSystem**
Windows Server 2012 R2 Essentials

**What is failing**
installing SSHD - service fails to start

**Expected output**
service starts
**Actual output**
This was got from running via psexec as system,
___
c:\Program Files\OpenSSH-Win64>sshd.exe -dddd
debug2: load_server_config: filename __PROGRAMDATA__\\ssh/sshd_config
debug2: load_server_config: done config len = 175
debug2: parse_server_config: config __PROGRAMDATA__\\ssh/sshd_config len 175
debug3: __PROGRAMDATA__\\ssh/sshd_config:9 setting Port 2358
debug3: __PROGRAMDATA__\\ssh/sshd_config:24 setting LogLevel QUIET
debug3: __PROGRAMDATA__\\ssh/sshd_config:38 setting AuthorizedKeysFile .ssh/authorized_keys
debug3: __PROGRAMDATA__\\ssh/sshd_config:76 setting Subsystem sftp      sftp-server.exe
debug1: sshd version OpenSSH_for_Windows_7.6, LibreSSL 2.6.4
debug3: NetUserGetInfo() failed with error: 2221 for user: sshd and domain: (null)

debug3: NetUserGetInfo() with domainController: \\\\xxxserver.domain.local failed with error: 2221

Privilege separation user sshd does not exist
___

oddly this WILL install on Windows Server 2012 R2,  but not essentials.

thanks

**Comment by HSSupport** [comment]
i could just create a domain user "sshd" but i wouldn't be certain is was as secure as, say, getting the correct instructions on how to generate the account correctly.

**Comment by manojampalam** [comment]
this account gets created (if it does not already exist) as part of sshd service start up. 

Did you try 
`net start sshd`

If you do want to create it manually you can do
net user sshd <randompassword> /add

**Comment by HSSupport** [comment]
I have this issue on 3 2012 r2 essentials servers, but I got this from net user add sshd

c:\Program Files\OpenSSH-Win64>net user sshd /add
The password does not meet the password policy requirements. Check the minimum password length, password complexity and
password history requirements.

Which is... OK but I thought Service users had no password?

**Comment by bagajjal** [comment]
Did you try 
1) net stop sshd
2) net start sshd

**Comment by HSSupport** [comment]
Hi,

I did, here is the result
c:\Program Files\OpenSSH-Win64>Net start sshd
The sshd service is starting.
The sshd service could not be started.

A system error has occurred.

System error 1067 has occurred.

The process terminated unexpectedly.



Can a service user account have a password? What if the password expires?

Thanks

**Comment by bagajjal** [comment]
sshd service failed to start. To debug further try our [troubleshooting steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps).
after psexec, try .\sshd.exe -ddd

**Comment by HSSupport** [comment]
Hi

The result of that is in the first post :)

Thanks

**Comment by bagajjal** [comment]
My bad, I missed it.

During [sshd service start](https://github.com/PowerShell/openssh-portable/blob/41e4e893762d3859b23163f814a64aadfaa996b1/contrib/win32/win32compat/wmain_sshd.c#L127), we create "sshd" user. This is a mandatory step as the base unix code requires "sshd" user.

To debug further, please try this private [sshd binary](https://github.com/PowerShell/Win32-OpenSSH/files/1921308/sshd_sshd_user_creation_failure.zip). This binary contains the error log.

1) from cmd.exe, use psexec to login as SYSTEM (psexec  /s cmd)
2) run "whoami". It should show "nt authority\system"
3) make sure sshd user is not present.
4) run ".\sshd.exe -ddd". This should be my private binary so that it shows error log.

**Comment by HSSupport** [comment]
No worries, I'm grateful for the help!

c:\Program Files\OpenSSH-Win64>sshd.exe -dddd
debug2: load_server_config: filename __PROGRAMDATA__\\ssh/sshd_config
debug2: load_server_config: done config len = 175
debug2: parse_server_config: config __PROGRAMDATA__\\ssh/sshd_config len 175
debug3: __PROGRAMDATA__\\ssh/sshd_config:9 setting Port 2358
debug3: __PROGRAMDATA__\\ssh/sshd_config:24 setting LogLevel QUIET
debug3: __PROGRAMDATA__\\ssh/sshd_config:38 setting AuthorizedKeysFile .ssh/authorized_keys
debug3: __PROGRAMDATA__\\ssh/sshd_config:76 setting Subsystem sftp      sftp-server.exe
debug1: sshd version OpenSSH_for_Windows_7.7, LibreSSL 2.6.4
debug3: NetUserGetInfo() failed with error: 2221 for user: sshd and domain: (null)

debug3: NetUserGetInfo() with domainController: \\\\Xxxserver.Domain.local failed with error: 2221

Privilege separation user sshd does not exist


Same again, or was there a log I was looking for?
I don't mind if the answer is either a) make a sshd user with password or b) Disable the default essentials gpo password policy, rerun so user is created, and turn it back on. So long as the result is secure and not going to cause an issue when the password expires.
Thanks

**Comment by bagajjal** [comment]
Please retry this [updated private binary](https://github.com/PowerShell/Win32-OpenSSH/files/1921371/sshd-issue-create-sshd-user.zip).

Please try the same steps as above.
You will see two debug logs
1) starting the prerequisite setup
2) Failed to create user sshd, error: <error_number>

**Comment by HSSupport** [comment]
Hi,
Am I doing something wrong?

c:\Program Files\OpenSSH-Win64>sshd.exe -dddd
debug2: load_server_config: filename __PROGRAMDATA__\\ssh/sshd_config
debug2: load_server_config: done config len = 175
debug2: parse_server_config: config __PROGRAMDATA__\\ssh/sshd_config len 175
debug3: __PROGRAMDATA__\\ssh/sshd_config:9 setting Port 2358
debug3: __PROGRAMDATA__\\ssh/sshd_config:24 setting LogLevel QUIET
debug3: __PROGRAMDATA__\\ssh/sshd_config:38 setting AuthorizedKeysFile .ssh/authorized_keys
debug3: __PROGRAMDATA__\\ssh/sshd_config:76 setting Subsystem sftp      sftp-server.exe
debug1: sshd version OpenSSH_for_Windows_7.7, LibreSSL 2.6.4
debug3: NetUserGetInfo() failed with error: 2221 for user: sshd and domain: (null)

debug3: NetUserGetInfo() with domainController: \\\\Xxxserver.Domain.local failed with error: 2221

Privilege separation user sshd does not exist

c:\Program Files\OpenSSH-Win64>whoami
nt authority\system

**Comment by HSSupport** [comment]
And a check in ADUC shows no such user as sshd :)

**Comment by bagajjal** [comment]
Are you sure, you are using my private sshd binary?

**Comment by HSSupport** [comment]
Hi

Yep I deleted sshd.exe, copied your one over (got asked for permission to move it into the folder) and ran sshd.exe -ddd

Same answer again :( sorry

**Comment by bagajjal** [comment]
@HSSupport - My apologies. I expected printf() to write log to the command prompt but it didn't.

To overcome let's add the "sshd" user from an elevated command prompt.
`net user /add sshd P@ssword_1`

**Comment by HSSupport** [comment]
Adding the user with password allowed the service to start successfully! Which is great, thank you very much!

Is it secure to create the user in this fashion with a password, for running the sshd service?

**Comment by bagajjal** [comment]
if "sshd" user doesn't expect, sshd service creates "sshd" user with random password. So if we are doing manually then we should also use random password so that no one else can use these credentials to login. 

Now the problem is resolved, I would suggest to change the password to a random password.

FYI, sshd user is a non-admin user.

**Comment by HSSupport** [comment]
Hi,

I have changed the password to something very random, and have successfully uninstalled and installed ssh package and remote connected to it.
I suspect the random password generator you are using doesn't match up to the standard password policies for server 2012 essentials r2, perhaps complexity requirements?

Thank you for helping me resolve this issue. :)

**Comment by NoMoreFood** [comment]
@HSSupport Do you happen to know if you have a custom password filter installed on your systems?  The password generator used should meet most all the default criteria (>= 14, 3/4 character types, etc).

**Comment by HSSupport** [comment]
Hi

no just the windows 2012 R2 essentials defaults (once connected to office 365) which i think are 8 chars, 3 char types.

its odd, because im sure i have a server 2016 and a server 2012 r2 with the same GPO's enabled, but this installs just fine. But on every single one of the Server 2012 R2 Essentials servers, i have had to do net user /add sshd **COMPLEXPASS**.

i mean its only 3 servers but thats 100%.

unless joining the essentials server to office365 (using the essentials gui) causes this effect, i dont know what the difference could be.

thanks

**Comment by NoMoreFood** [comment]
@HSSupport If I provide you a modified sshd.exe binary that uses a different password creation algorithm, would you be willing to test it to see if it resolves your issue?

**Comment by NoMoreFood** [comment]
@HSSupport Bump.  Did you see my last post?

**Comment by wenkyzhang** [comment]
```
c:\OpenSSH-Win64>.\sshd.exe -ddd
debug2: load_server_config: filename __PROGRAMDATA__\\ssh/sshd_config
debug2: load_server_config: done config len = 212
debug2: parse_server_config: config __PROGRAMDATA__\\ssh/sshd_config len 212
debug3: __PROGRAMDATA__\\ssh/sshd_config:38 setting AuthorizedKeysFile .ssh/auth
orized_keys
debug3: __PROGRAMDATA__\\ssh/sshd_config:76 setting Subsystem sftp      C:\\Open
SSH-Win64\\sftp-server.exe
debug3: __PROGRAMDATA__\\ssh/sshd_config:77 setting Subsystem scp           C:\\
OpenSSH-Win64\\scp.exe
debug1: sshd version OpenSSH_for_Windows_7.7, LibreSSL 2.6.4
debug3: ReadFileEx() ERROR:38, io:0000009B94E60A20
debug3: read - no more data, io:0000009B94E60A20
debug3: ReadFileEx() ERROR:38, io:0000009B94E60A20
debug3: read - no more data, io:0000009B94E60A20
debug1: private host key #0: ssh-rsa SHA256:**********************************************
debug3: ReadFileEx() ERROR:38, io:0000009B94E7E830
debug3: read - no more data, io:0000009B94E7E830
debug3: ReadFileEx() ERROR:38, io:0000009B94E7E830
debug3: read - no more data, io:0000009B94E7E830
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:***********************************
debug3: ReadFileEx() ERROR:38, io:0000009B94E23660
debug3: read - no more data, io:0000009B94E23660
debug3: ReadFileEx() ERROR:38, io:0000009B94E23660
debug3: read - no more data, io:0000009B94E23660
debug1: private host key #2: ssh-ed25519 SHA256:*****************************************
debug1: rexec_argv[0]='.\\sshd.exe'
debug1: rexec_argv[1]='-ddd'
debug2: fd 3 setting O_NONBLOCK
debug3: sock_set_v6only: set socket 3 IPV6_V6ONLY
debug1: Bind to port 22 on ::.
Server listening on :: port 22.
debug2: fd 4 setting O_NONBLOCK
debug1: Bind to port 22 on 0.0.0.0.
Server listening on 0.0.0.0 port 22.
```

use putty connect, enter the user and password, i got this error
```
Network error: Software caused connection abort
```
Server log:
```
debug1: monitor_child_preauth: ecs-smart-0002\\administrator has been authentica
ted by privileged process
debug3: mm_get_keystate: Waiting for new keys
debug3: mm_request_receive_expect entering: type 26
debug3: mm_request_receive entering
debug3: mm_get_keystate: GOT new keys
debug3: mm_auth_password: user authenticated [preauth]
debug3: send packet: type 52 [preauth]
debug3: mm_request_send entering: type 26 [preauth]
debug3: mm_send_keystate: Finished sending state [preauth]
debug3: ReadFileEx() ERROR:109, io:0000009B94E7D740
debug3: read - no more data, io:0000009B94E7D740
debug1: monitor_read_log: child log fd closed
debug1: Not running as SYSTEM: skipping loading user profile
debug3: spawning "c:\\OpenSSH-Win64\\.\\sshd.exe" "-ddd" "-z"
CreateProcessAsUserW failed error:1314
fork of unprivileged child failed
debug1: do_cleanup
```

any help? thanks

**Comment by manojampalam** [comment]
You need to run sshd as SYSTEM (using psexec). see https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Comment by HSSupport** [comment]
hi @NoMoreFood, yes i have a system i can test this on if you pass me a modified installer :)
