### ISSUE TITLE
LsaSidNameMappingOperation_NonMappingError. any explanation?

### ISSUE THREAD

**Issue by LozBoz63** [PowerShell/Win32-OpenSSH#1138]
I'm trying an install on Windows 2012 R2 and I'm getting the following error on all connection attempts

3740 2018-04-17 19:38:32.085 debug1: inetd sockets after dupping: 3, 3
3740 2018-04-17 19:38:32.085 Connection from 26.96.111.250 port 54528 on 26.96.111.250 port 22
3740 2018-04-17 19:38:32.085 debug1: Client protocol version 2.0; client software version OpenSSH_for_Windows_7.6
3740 2018-04-17 19:38:32.085 debug1: match: OpenSSH_for_Windows_7.6 pat OpenSSH* compat 0x04000000
3740 2018-04-17 19:38:32.085 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.6
3740 2018-04-17 19:38:32.085 debug2: fd 3 setting O_NONBLOCK
3740 2018-04-17 19:38:32.085 error: LsaManageSidNameMapping failed with : LsaSidNameMappingOperation_NonMappingError \n
3740 2018-04-17 19:38:32.085 debug3: unable to generate sshd virtual token, falling back to s4u
3740 2018-04-17 19:38:32.085 error: unable to generate token for user sshd
3740 2018-04-17 19:38:34.418 error: unable to generate token on 2nd attempt for user sshd
3740 2018-04-17 19:38:34.418 error: unable to get security token for user sshd
3740 2018-04-17 19:38:34.418 fatal: privsep_preauth, fork of unprivileged child failed
3740 2018-04-17 19:38:34.418 debug1: do_cleanup

**Comment by bagajjal** [comment]
Does sshd service run as SYSTEM?
If yes, try our [troubleshooting steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps).

**Comment by LozBoz63** [comment]
I was following some old install instructions and was running under an sshd account
Switching to system resolved instantly.
Thanks for the mistake and sorry for not spotting my mistake
