### ISSUE TITLE
Cannot build using any of the build instructions

### ISSUE THREAD

**Issue by dwatley** [PowerShell/Win32-OpenSSH#1139]
**What is failing**
Unable to build from source using Visual Studio.
https://github.com/PowerShell/Win32-OpenSSH/wiki/Building-using-VS-2015
https://github.com/PowerShell/Win32-OpenSSH/wiki/Building-OpenSSH-for-Windows-(using-LibreSSL-crypto)

Basically I've downloaded the tagged source, loaded the Visual Studio solution, and it doesn't work out of the box using the instructions on the Wiki as a reference. FWIW the PowerShell instructions don't work either.

@manojampalam @bagajjal 

**Expected output**
Compiled binaries.

**Actual output**
Spam of this output in Visual Studio. Clearly there is a dependency missing that is not included nor instructed to procure.
```
10>c:\users\dwatley\src\openssh-portable-7.6.1.0\includes.h(168): fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory
```

I'm doing this to verify I can build OpenSSH from source, and potentially patch as necessary. What's the story here?

**Comment by bagajjal** [comment]
@dwatley - 
Did you try Start-OpenSSHBuild  command by importing OpenSSHBuildHelper.psm1 as mentioned [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Building-OpenSSH-for-Windows-(using-LibreSSL-crypto)).

FYI,  Start-OpenSSHBuild will download the LibreSSL from [latest release](https://github.com/PowerShell/LibreSSL/releases/tag/V2.6.4.1) and places the LibreSSL folder to this location $openssh-portable\contrib\win32\openssh. LibreSSL folder will contain two folders "bin", "sdk".

FYI, I have updated the wiki https://github.com/PowerShell/Win32-OpenSSH/wiki/Building-using-VS-2015

**Comment by dwatley** [comment]
I did, which wasn't working. Copying the folder from the zip directly to `$openssh-portable\contrib\win32\openssh` as you noted and I'm able to build directly from VS now.

Log of failure from running the cmdlet here.

```
PS C:\Users\dwatley\src\openssh-portable-7.6.1.0> Start-OpenSSHBuild -Configuration Release -NativeHostArch x64
Add-Content : Could not find a part of the path
'C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\contrib\win32\openssh\OpenSSHReleasex64.log'.
At C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\OpenSSHBuildHelper.psm1:24 char:9
+         Add-Content -Path $script:BuildLogFile -Value $Message
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\dwatle...HReleasex64.log:String) [Add-Content], DirectoryNotFo
   undException
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.AddContentCommand

Add-Content : Could not find a part of the path
'C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\contrib\win32\openssh\OpenSSHReleasex64.log'.
At C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\OpenSSHBuildHelper.psm1:24 char:9
+         Add-Content -Path $script:BuildLogFile -Value $Message
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\dwatle...HReleasex64.log:String) [Add-Content], DirectoryNotFo
   undException
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.AddContentCommand

out-file : Could not find a part of the path
'C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\contrib\win32\openssh\OpenSSHReleasex64.log'.
At C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\OpenSSHBuildHelper.psm1:165 char:9
+         Invoke-Expression ((new-object net.webclient).DownloadString( ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

Exception calling "SetEnvironmentVariable" with "3" argument(s): "Requested registry access is not allowed."
At C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\OpenSSHBuildHelper.psm1:204 char:9
+         [Environment]::SetEnvironmentVariable('Path', $newMachineEnvi ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SecurityException

Add-Content : Could not find a part of the path
'C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\contrib\win32\openssh\OpenSSHReleasex64.log'.
At C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\OpenSSHBuildHelper.psm1:24 char:9
+         Add-Content -Path $script:BuildLogFile -Value $Message
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\dwatle...HReleasex64.log:String) [Add-Content], DirectoryNotFo
   undException
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.AddContentCommand

Download, Copy LibreSSL
LibreSSL copied successfully
Starting Open SSH build; Build Log: C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\contrib\win32\openssh\OpenSSHReleasex64.log.
MSBUILD : error MSB1009: Project file does not exist.
Switch: C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\contrib\win32\openssh\Win32-OpenSSH.sln
Write-BuildMsg : Build failed for OpenSSH.
ExitCode: .
At C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\OpenSSHBuildHelper.psm1:576 char:9
+         Write-BuildMsg -AsError -ErrorAction Stop -Message "Build fai ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-BuildMsg

PS C:\Users\dwatley\src\openssh-portable-7.6.1.0>
```

**Comment by bagajjal** [comment]
1) Looks like the file (C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\contrib\win32\openssh\OpenSSHReleasex64.log') is not writable from the powershell window. May be you need to run powershell in elevated window?

Add-Content : Could not find a part of the path
'C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\contrib\win32\openssh\OpenSSHReleasex64.log'.
At C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\OpenSSHBuildHelper.psm1:24 char:9
+         Add-Content -Path $script:BuildLogFile -Value $Message
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\dwatle...HReleasex64.log:String) [Add-Content], DirectoryNotFo
   undException
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.AddContentCommand

2) Script fetches, copies the LibreSSL to desired location.

Download, Copy LibreSSL
LibreSSL copied successfully
Starting Open SSH build; Build Log: C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh\contrib\win32\openssh\OpenSSHReleasex64.log.

3) FYI, our CI system uses "Start-OpenSSHBuild" so I expect it to work always.

**Comment by dwatley** [comment]
Well the fact that `contrib\win32` is in the path twice seems off, which might be the source of the issue. Elevation doesn't really make sense because it's within the user profile in the user context.

**Comment by bagajjal** [comment]
Looks like you have ".git" folder in "C:\Users\dwatley\src\openssh-portable-7.6.1.0\contrib\win32\openssh".
The logic to determine the OpenSSHRoot is [here](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/openssh/OpenSSHCommonUtils.psm1#L13).
The build log path is determined like [this](https://github.com/PowerShell/openssh-portable/blob/41e4e893762d3859b23163f814a64aadfaa996b1/contrib/win32/openssh/OpenSSHBuildHelper.psm1#L644)

**Comment by dwatley** [comment]
I actually have no ".git" folder (hidden or otherwise) anywhere in that path. Is it possible the logic is blowing up a bit because I did not clone the repo (thus no git in the path), but downloaded the source [zip](https://github.com/PowerShell/openssh-portable/archive/v7.6.1.0.zip) from the releases page?

**Comment by NoMoreFood** [comment]
@dwatley Based on your other thread, it looks like you're now actively building.  Is this still an issue?

**Comment by dwatley** [comment]
I was able to build, but I believe I had to futz around with things beyond the instructions. I'll confirm from scratch.

**Comment by Jan-E** [comment]
> I was able to build, but I believe I had to futz around with things beyond the instructions. I'll confirm from scratch.

FWIW: I had the same troubles. The first step in the instructions did nothing at all. It exited within a second without any output.

`ipmo .\contrib\win32\openssh\OpenSSHBuildHelper.psm1 -Force`

I had to copy the latest LibreSSL manually to .\contrib\win32\openssh\LibreSSL before I could start building. What might be of interest: Cygwin is in my path and Chocolatey was already installed.

**Comment by manojampalam** [comment]
@bingbing8 can you please follow up ?

**Comment by bingbing8** [comment]
@Jan-E, @dwatley, please try the latest source from PowerShell/openssh-portable and let us know if the issue get fixed. Thanks!

**Comment by dwatley** [comment]
@bingbing8 - The instructions work from scratch for me now. Also noting I used VS2017.

**Comment by bingbing8** [comment]
Yes, itt should work for VS2017. I will close the issue. Please reopen if you see issues.
