### ISSUE TITLE
Nano Server support

### ISSUE THREAD

**Issue by alexpilotti** [PowerShell/Win32-OpenSSH#114]
The current codebase does not work on Nano Server, due to the following imports which are not available on Nano (with reverse forwarders) as of TP4:

sshd.exe:

USER32.dll
      OpenDesktopA
      OpenWindowStationA
      VkKeyScanA
      MapVirtualKeyA

ssh.exe, ssh-keygen, etc:

USER32.dll
     MapVirtualKeyA
     VkKeyScanA

**Comment by jdub** [comment]
The current release of Win32-OpenSSH + Nano Server Tech Preview 5 work together very well.

```
$ uname -a
Darwin slender.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

$ ssh gunpowder
Microsoft Windows [Version 10.0.14300]
(c) 2016 Microsoft Corporation. All rights reserved.

jdub@GUNPOWDER C:\windows>
```

**Comment by alexpilotti** [comment]
Closing this issue as it's fixed in TP5. Excellent stuff! :)
