### ISSUE TITLE
Text rendering corrupted in Putty

### ISSUE THREAD

**Issue by Cisien** [PowerShell/Win32-OpenSSH#1143]
Please answer the following

**"OpenSSH for Windows" version**
7.6.1.0
 
**Server OperatingSystem**
Windows Server Datacenter (2016 1709)

**Client OperatingSystem**
Windows 10 17652 
SSH Client: Putty 0.70

**What is failing**
Text rendering when the putty window is wider than default is incorrect when the line of text is wider than the default terminal width.
https://puu.sh/Ab8zo/ec03adf159.png
Additionally, the cursor position does not line up with the end of the line when long text is entered (copy/paste or typed)
https://puu.sh/Ab8BU/becac968b9.png

**Comment by electricduck** [comment]
Have you tried updating the SSH server? At the time of writing, the latest version is `7.6.1.0`. `0.0.18.0` was released on Aug 29, 2017.

**Comment by Cisien** [comment]
The version I am running is indeed 7.6.1.0. The ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion) command was using what was in my path, which was a previous install. The service is installed using the latest release, and is correctly referencing the sshd in program files.

```
PS C:\Program Files\OpenSSH> (Get-Item (Get-Command sshd).Source)


    Directory: C:\Program Files\OpenSSH


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/31/2018   3:06 AM         955592 sshd.exe


PS C:\Program Files\OpenSSH> ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
7.6.1.0
```
apologies for the confusion.
