### ISSUE TITLE
TEST_RESOURCES in unit test signal_tests.c is disabled. Need to investigate to the failures

### ISSUE THREAD

**Issue by bingbing8** [PowerShell/Win32-OpenSSH#1144]
Originally these lines was added by @NoMoreFood to detect resource leak after wait_for_multiple_objects. The before and after handle counts are randomly different on win2kr2 and win8. Below test code repro the behavior difference.
[TestCode.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1975791/TestCode.txt)

**Comment by bingbing8** [comment]
@NoMoreFood , the behavior on win2kr2 and win8 are by design. It is not a bug.  The extra handle is parallel loader thread. 
This explain why in our case:
1. 2 threads created and scheduled in different CPUs
2. Cpu 1 starts thread A
3. In the meantime Cpu 2 starts thread B
4. Cpu 1 acquires the loader lock. The wait is satisfied and the loader code continues its execution
5. In the meantime thread B in Cpu 2 tries to acquire the shared loader look, but finds a contention. So the NT kernel creates a non signalled Event and put the thread B in the waiting state. A new handle in the process is created.
6. When the loader code in Cpu 1 finish its initialization work, releases the loader lock (Critical section). The Critical section releasing code detects the old contention, and signals the event
7. Cpu 2 can now resume Thread B.
The Loader lock event is destroyed, only when the process is going to be terminated, by the loader code. So you have no clues how to predict if your process has or not a new handle in its table.
In Windows 10 you do not have this behaviour because the Critical section is implemented using another underlying synchronization primitive called WaitOnAddress.
As a general guideline, we can’t rely on the fact that the handle counter in the beginning of your code remains the same for the entire life of your process, even if you have closed all the handles. This is because the loader, and even any other components that run in the system, are not under your direct control.
Please let me know if you get the message and we can close on this issue.

**Comment by NoMoreFood** [comment]
@bingbing8  Yes, you can close the issue.  Thank you for the thorough write-up and the comparative analysis on why the behavior differs under Windows 10.  It would have taken me weeks muddling through assembly trying to figure that out.
