### ISSUE TITLE
ssh-agent.exe output nothing

### ISSUE THREAD

**Issue by locez** [PowerShell/Win32-OpenSSH#1145]
version :7.6.0
 Windows 10 Home 

Problem: ssh-agent.exe output nothing,and I want to use gpg-agent to read smarcard.
`SSH_AUTH_SOCK` has been set correct.

**Comment by manojampalam** [comment]
See #827

**Comment by nanonyme** [comment]
Just FWIW this is currently blocking being able to directly use Windows OpenSSH as part of Jenkins SSH agent integration https://issues.jenkins-ci.org/browse/JENKINS-51968 . It would be desirable not to need to install a secondary OpenSSH to the machine to achieve this use case.

**Comment by locez** [comment]
I finally use [https://github.com/vuori/weasel-pageant](https://github.com/vuori/weasel-pageant) to solve this case.It just need to install gpg4win and active the putty support.All can work fine in wsl.

**Comment by nanonyme** [comment]
Doesn't that also means you stopped using Win32-OpenSSH?

**Comment by locez** [comment]
Yes, the toolchains in wsl is more powerful.But actually, I am working in gentoo linux, which make everything is good.
