### ISSUE TITLE
OpenSSH ignores the HOME environment variable

### ISSUE THREAD

**Issue by archfrog** [PowerShell/Win32-OpenSSH#1146]
**"OpenSSH for Windows" version**: 7.6.0.0?  (got nothing from sshd, so ran it against ssh)

**Server OperatingSystem**: Irrelevant

**Client OperatingSystem**: Windows 10 Home (Version 10.0.17134.1)

**What is failing**
The `ssh` command does not use the `HOME` environment variable.  I am using an encrypted VeraCrypt container for all my keys and stuff, and other versions of OpenSSH (such as the Git version) work beautifully because they pick up `config` from `%HOME%\.ssh`, but the Microsoft OpenSSH ignores `HOME` altogther.

Please add support for the `HOME` environment variable so that MS OpenSSH works as a plugin instead of a new platform.

**Expected output**
That I can connect with my current setup based on the `HOME` environment variable.

**Actual output**
OpenSSH doesn't find my custom `config` file and therefore cannot connect to anything that uses keys.

**Comment by yanoryuichi** [comment]
Configuration files should not be stored in %USERPROFILE%\.ssh. It should be under %APPDATA%, or make it configurable with an environment variable %SSH_CONFIG_HOME% or something.

**Comment by archfrog** [comment]
I'm only asking to have it be storable under `%HOME%\.ssh` just like with all other OpenSSH implementations.  I'm not talking about `%USERPROFILE%` at all :-)

So far, I've resorted to using the OpenSSH implementation that is included in Git for Windows because it works well for me and supports configuration files in `%HOME%\.ssh` very well.

I was just hoping that I could some day use Microsoft's OpenSSH for Windows 10 like I use the Git one and the Linux ones.  But, alas, perhaps not.

**Comment by yanoryuichi** [comment]
In the first place, %HOME% and dot files are meaningless in Windows. Although OpenSSH specifies $HOME in UNIX, it's a bad design.

**Comment by archfrog** [comment]
Not if you regularly work on Linux platforms too.  You could also argue that the Linux subsystem is meaningless on Windows, yet some find it highly relevant and usable.  I'm only asking for a tiny change that will make it a seamless experience to use Win32-OpenSSH for us advanced users who regularly work in many different environments.

**Comment by archfrog** [comment]
I suppose if I could make a Windows symbolic link (junction, whatever?) to my regular config file, that would work too.  So you had `%APPDATA%\whatever\My Happy OpenSSH Configuration File.txt` was a symlink to %HOME%\.ssh\config, then it would work for me.  Would be tedious, but would work for me as my `%HOME%` never changes (it is a [VeraCrypt](https://www.veracrypt.fr/en/Home.html) container aka a virtual drive mounted from an encrypted file) :-)

**Comment by yanoryuichi** [comment]
I agree using ssh in WSL is a better way. In Windows 10 1803, I can make a symlink of $HOME/.ssh. Or using plink.exe of PuTTY is another way. The problem is a configuration directory of OpenSSH is not cofigurable.

**Comment by archfrog** [comment]
Yes, I interchangably use Putty and OpenSSH.  I tend to use OpenSSH for copying files because of the bulky Putty syntax (`putty -load Profile local-file.zip remote-server:/path/`) and Putty for actual SSH work because of the, IMHO, better console window (which I open with `start /max putty ...` to get a nice Unix-like terminal window :-)).

I didn't know that you can't configure the OpenSSH config directory.  And I guess you are ahead of me when it comes to what needs to be done on Windows.  So feel free to close this request; I'll try out the symlink method and see if I can't figure out a proper solution.

**Comment by yanoryuichi** [comment]
No, your request is useful. Actually I set a HOME environment variable in Windows like you do. I mean "CMD> setx HOME C:\Unix_Home".  A lot of commands are hard-coded with $HOME (=%USERPROFILE%). So, as you said, OpenSSH can pick %HOME% is good, but it's better if a configuration directory of OpenSSH is configurable, IMO.

**Comment by archfrog** [comment]
Okay, I see what you mean.  Perhaps a cascading design would make sense?  I.e. pick in this order:

1. `--config-file:PATH`.
2. `%APPDATA%\...`.
3. `%HOME%\.ssh\config`.
4. Give up locating the file and report an error.

Where `--config-file` is a new option to specify the directory that Win32-OpenSSH should use (better suggestions much wanted :-)).  

Or something like that.  I was just hoping to have `%HOME%` added somewhere in the cascade of lookups.  And this mostly for compatibility with other OpenSSH toolsets out there.  I really do love that OpenSSH is being officially supported on Windows, but there are some rough edges yet.

**Comment by maertendMSFT** [comment]
On Windows, the %userprofile% variable is used, there is not a %home%.  This could be created by a user.

**Comment by Holt59** [comment]
What's the reasoning behind this? The `%USERPROFILE%` cannot be changed, so if you have a custom `%HOME%` variable you simply cannot use the SSH client without having to pass the `-F` flag every time.

This creates different behavior depending on the tool you use, like `git` uses `%HOME%`, so if you have a custom `%HOME%`, you cannot use both `git` and `ssh` properly, and trying to create a hardlink between the two `.ssh` folder just does not work.

**Comment by yanoryuichi** [comment]
The problem is OpenSSH is hard-coded with $HOME/.ssh. It doesn't support XDG Base Directory. See this. https://wiki.archlinux.org/index.php/XDG_Base_Directory
It's same in Win32-OpenSSH. In my case, I don't use Win32-OpenSSH anymore and I'm happy with PuTTY now.

**Comment by darkn3rd** [comment]
I had a problem with an Windows image built for Vagrant that uses Win32-OpenSSH and it sets %HOME% to %USERPROFILE%.  The problem arises when I use provisioning scripts with Cygwin and MSYS2, where because HOME is set, their native scripts where they set HOME up are overriden, and their HOME points to USERPROFILE, not to their native HOME directories.  This is causing a lot of headaches.

**Comment by archfrog** [comment]
My solution today is to use DOSKEY macros for `ssh` and `scp` which explicitly use the -F option.  I uninstall Microsoft's OpenSSH and use the one from [Git for Windows](https://gitforwindows.org/) (so the DOSKEY macro are technically redundant as I also always set the `HOME` environment variable).

This works beautifully and you get many of the GNU command-line utilities as part of the deal.
