### ISSUE TITLE
New characters are changed to background color automatically in Vim

### ISSUE THREAD

**Issue by yf225** [PowerShell/Win32-OpenSSH#1147]
**"OpenSSH for Windows" version**
7.6.1.0
 
**Server OperatingSystem**
 Windows Server 2012 R2 Standard

**Client OperatingSystem**
macOS High Sierra 10.13.3

**What is failing**
1. `export TERM=xterm`, then connect to Windows server with SSH
2. Open vim (https://github.com/vim/vim-win32-installer/releases/tag/v8.0.1803) from either `cmd` or `powershell`
3. Press `i` to enter insert mode, type characters, characters are changed to background color immediately and the cursor is moving (if typing fast enough, can see characters changing from white color (normal color) to background color which then becomes invisible)
4. Save text to local file `a.txt`
5. Run `vim a.txt`
6. Now the content is visible and shown in white color
7. Press `i` to enter insert mode, type characters, all old and new characters are changed to background color again

Vim works fine when connected via Remote Desktop.

Using the new ssh-shellhost.exe from https://github.com/PowerShell/Win32-OpenSSH/issues/1066 didn't fix this issue.

**Comment by yf225** [comment]
Update: setting Vim to take less than half of the terminal window height fixes the issue (e.g. for a terminal window with 52 lines total, I need to do `:set lines=25` in Vim to make the new characters show up properly. I suspect that this is a rendering issue with OpenSSH.

**Comment by yf225** [comment]
The Cygwin SSH server and vim handle it much better. Highly recommend it if anyone is facing the same issue.

**Comment by maertendMSFT** [comment]
Try on server 2019
