### ISSUE TITLE
Limit OpenSSH only to SFTP doesn't work - ForceCommand internal-sftp

### ISSUE THREAD

**Issue by jirijanata** [PowerShell/Win32-OpenSSH#1148]
**"OpenSSH for Windows" version**
v7.6.1.0p1-Beta
 
**Server OperatingSystem**
Windows Server 2012 R2 Datacenter

**Client OperatingSystem**
Windows 8.1, WinSCP

**What is failing**
According to this article- https://www.digitalocean.com/community/tutorials/how-to-enable-sftp-without-shell-access-on-ubuntu-16-04 this command `ForceCommand internal-sftp` should dissallow SSH access and allows only SFTP. But it doesn't seems to work. It makes nothing.. I tried different commands and there is result:

**Working commands**
`ForceCommand cmd /c dir`

**Not working commands**
``ForceCommand internal-sftp``
`ForceCommand sftp`
`ForceCommand sftp-server.exe`

Have a nice day :)
OffTopic
Was anyone able to find workaround for not working chroot (Virtual Directories emulation etc.)?

**Comment by bagajjal** [comment]
If you specify "ForceCommand internal-sftp" in "%programdata%\ssh\sshd_config" file then it will only allow sftp connections.. When you try to do ssh/scp it will fail with error "error: This service allows sftp connections only" (in sshd.log / ETW log, depending on your configuration).

We have a [PR](https://github.com/PowerShell/openssh-portable/pull/308#issuecomment-387626846) inprogress for chroot support in SFTP.

I tried (allowing only SFTP connections) with the latest release binaries and it worked. If you run into any issues then follow our [troubleshooting steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps). 

If you still have issues then share your sshd_config, sshd.log (with DEBUG3 enabled).

**Comment by jirijanata** [comment]
Hi,

thank you very much for your answer. I'm attaching log and my config file. It looks, that ForceCommand is processing, but I'm still logged in and I'm not getting any deny message.
[sshd_testssh_domain.log](https://github.com/PowerShell/Win32-OpenSSH/files/1992680/sshd_testssh_domain.log)
[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1992707/sshd_config.txt)

Maybe some other bug (but I'll report it in another issue) - if I open ssh session just like TestSSH user (not TestSSH@doma.local), I'm able to log in, but no match is found in config file. This is just domain joined machine and there is no local TestSSH user. So there is maybe some bug in looking for domain/local users. 

Thank you for information about chroot :) it looks promising.

**Comment by bagajjal** [comment]
hmm looks like there is a bug.. change username to all lowercase in match block 
Match User testssh@doma.local
ForceCommand internal-sftp

**Comment by jirijanata** [comment]
Thank you very much for your prompt response. I tested few variants:

**Domain User**
Username: `openssh@doma.local`
Config file: `Match User openssh@doma.local`
Status: `BUG - user is able to use ssh.`

Username: `openssh`
Config file: `Match User openssh@doma`
Status: `OK- user is not able to use ssh, but sftp works. This domain format is not standard - usually is used format DOMAIN\user or user@domain.extension. I've now no test environment for domains like intern.redmond.microsoft.com - but it should be also somehow implemented.`

Username: `openssh`
Config file: `Match User openssh`
Status: `BUG - user is able to use ssh.`

Username: `DOMA\openssh`
Config file: `Match User DOMA\openssh`
Status: `BUG - user is able to use ssh.`
[sshd_backslash_format.log](https://github.com/PowerShell/Win32-OpenSSH/files/1994439/sshd_backslash_format.log)

**Local User**
Username: `test`
Config file: `Match User test`
Status: `OK - I'm not able to login to ssh, but sftp works. It doesn't matter, if I use in Putty username Test or test`

Username: `test`
Config file: `Match User Test`
Status: `BUG - user is able to use ssh.`

Thank you very much!

**Comment by manojampalam** [comment]
@jirijanata the confusion around domain name format will be fixed in the upcoming release. Going forward all domain identities should be of the form domain\name.

**Comment by manojampalam** [comment]
@jirijanata please look into https://github.com/PowerShell/Win32-OpenSSH/wiki/sshd_config for configuration rules 

Let us know if you see any issues

**Comment by jirijanata** [comment]
It works as expected. Thank you very much.

Can you edit **Not supported** commands in [wiki](https://github.com/PowerShell/Win32-OpenSSH/wiki/sshd_config) - there are still listed commands this commands, which works in 7.7.0.0p1 - `ChrootDirectory`, `DenyGroups`, `DenyUsers`.

**Comment by manojampalam** [comment]
Thanks. Fixed wiki.
