### ISSUE TITLE
Wrong command in wiki

### ISSUE THREAD

**Issue by jirijanata** [PowerShell/Win32-OpenSSH#1150]
In wiki is wrong command for logging:
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

There is 
`LogFacility LOCAL0`
but it should be
`SyslogFacility LOCAL0`

With LogFacility service won't start. Thank you for correction.

**Comment by bagajjal** [comment]
Thanks for reporting.. I have updated the wiki.
