### ISSUE TITLE
TTY PTY issue in older version of Windows 10

### ISSUE THREAD

**Issue by cbookg** [PowerShell/Win32-OpenSSH#1151]
I'm getting strange TTY behavior when connecting ssh to a linux server:  The first characters of a line are lost, and I don't get the prompt displayed until after another line break is sent.  But I've noticed that I only see this issue on version 1151 of Windows, where as with a newer version it works well.

I've gone through the wiki here:
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

And have two questions.
> Unfortunately, this rendering mode is only included with Windows 10
Does this actually mean a specific version of Windows 10, or is this expected to work on older versions.

> If you're not on Windows 10, you may have more luck using a third-party terminal emulator or console host like Cmder or ConEmu.
Are there instructions for having ssh use one of these?  Just running ssh from these various shells doesn't seem to result in any different behavior.  Ssh seems to use the default windows command shell regardless.

Versions:
"OpenSSH for Windows": 7.6.1.0
"Client OperatingSystem":  Windows 10 Enterprise
"Server Operating System": Ubuntu 16.04.4 LTS

**Comment by bagajjal** [comment]
Windows 10 conhost provides the support for parsing the ANSI buffer. [We determine](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/console.c#L118) this based on setting ENABLE_VIRTUAL_TERMINAL_PROCESSING  console mode. You can report console issues [here](https://github.com/Microsoft/console/issues/).

We don't support third-party terminal emulators. For Windows 10 below, we have custom ANSI parser that supports only VT100.
