### ISSUE TITLE
SSH_ASKPASS command not passed prompt message

### ISSUE THREAD

**Issue by xenoscopic** [PowerShell/Win32-OpenSSH#1152]
**"OpenSSH for Windows" version**
7.6.0.0
 
**Server OperatingSystem**
macOS (or any)

**Client OperatingSystem**
Windows 10

**What is failing**
The `msg` parameter provided to the `ssh_askpass` function is not forwarded to the command specified by `SSH_ASKPASS`.  This parameter specifies a prompt that should be forwarded as a command line argument to the `SSH_ASKPASS`-specified command.  The logic is correct in the `fork`-based version but not the `posix_spawn`-based version of the code.

**Expected output**
`%SSH_ASKPASS% <prompt>` being executed.

**Actual output**
`%SSH_ASKPASS%` being executed.

**Comment by manojampalam** [comment]
Thanks for catching this. Fix would be to just replace this

char* spawn_argv[2];
spawn_argv[0] = askpass;
spawn_argv[1] = NULL;

with this

char* spawn_argv[3];
spawn_argv[0] = askpass;
spawn_argv[1] = msg;
spawn_argv[2] = NULL;
