### ISSUE TITLE
Allow sshd to work unprivileged/uninstalled for regression testing

### ISSUE THREAD

**Issue by rtollert** [PowerShell/Win32-OpenSSH#1153]
Please answer the following

**"OpenSSH for Windows" version**
N/A
 
**Server OperatingSystem**
N/A

**Client OperatingSystem**
N/A

**What is failing**

Summary: sshd aborts on startup when run as a non-privileged user. While this is at least implicitly documented, it appears to be a major regression against upstream OpenSSH-Portable, which more or less explicitly fixed this use case in version 7.6. As a result, integrating sshd into regression/CI-style testing appears to be much more difficult on Windows than on Unix.

Details: I am writing an SFTP client implementation and would like to spin up an sshd instance for every run of its regression tests -- i.e., `make test` would run `sshd -d` before running each test. Ideally, this would not require any system privileges, particularly if only SFTP is to be exercised. And all of this is easy enough to implement in OpenSSH 7.6 on Linux. I simply define a custom sshd_config:
```
Port 22223
ListenAddress 127.0.0.1
ListenAddress ::1
HostKey test_host_ecdsa_key
AuthorizedKeysFile test_authorized_keys
UsePrivilegeSeparation no
Subsystem sftp /usr/lib/ssh/sftp-server -d sftp-root
```
and then run `sshd -dD -f test_sshd_config" -e`, as a user. I can then connect via `sftp sftp://localhost:22223` (after setting up keys appropriately) and everything just works. And insofar as, AFAIK, this is more or less how a lot of OpenSSH's regression tests work, I understand that this not only requires no privileges, it also requires no installation. And with a little bit of autodiscovery of open ports instead of hardcoding port 22223, this sort of thing could even be made to work re-entrantly.

(Note that this only started working again in OpenSSH 7.6 by explicitly allowing `UsePrivilegeSeparation no` when run as non-root, as documented in the release notes at https://www.openssh.com/txt/release-7.6 .)

I would like to run sshd in the same way on Windows. However, the current [Troubleshooting Steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps), and other release notes, make it clear that `sshd.exe -d` requires execution as the SYSTEM user. And the contents of OpenSSHTestHelper.psm1 seem to suggest that quite a bit of system-wide reconfiguration is needed to run the pester tests. If that sort of thing is always going to be necessary when running sshd for testing purposes, that would seems to make a simple, self-contained, unrestricted CI workflow -- where, e.g., sshd could be run directly from a Makefile by end developers, or run from multiple builds at once, etc. -- very hard to get working robustly.

I was unable to determine, from existing GitHub issues and design docs, whether or not this use case was considered. If it hasn't been, I would ask for it. To be clear, what I am specifically asking for is a way to run sshd as a nonprivileged user without any prior installation, for the primary purpose of regression/CI testing, when that testing does not require such privileges. If that means SFTP-only that's fine by me.

**Comment by manojampalam** [comment]
This will be added soon. There will be one restriction though - incoming connections will be restricted to the (nonprivileged) user that sshd would run as. No other user can be authenticated and allowed in. .

**Comment by rtollert** [comment]
Hooray! That is precisely what I was hoping for.
