### ISSUE TITLE
Mouse Events Support

### ISSUE THREAD

**Issue by colemickens** [PowerShell/Win32-OpenSSH#1158]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
7.6.1.0 

**Server OperatingSystem**
some random linux box

**Client OperatingSystem**
"Windows 10 Pro"

**What is failing**
mouse events in vim on remote host

**Expected output**
I can click around and move the cursor in vim, or scroll events will be interpreted by tmux.

**Actual output**
Nothing seems to happen with any mouse input.

I'm not sure if this is a Console/PTY/openssh issue, apologies. I'm not sure if this is expected to work or not. I've tried fiddling with various settings in cmd.exe: with/without quickedit enabled, etc.

**Comment by manojampalam** [comment]
This is not currently supported

**Comment by guilala** [comment]
+1 It's just a matter of mapping the mouse events to specific escape sequences, right? Something like ^[OA^[OA^[OA^[OA^[OB^[OB^[OB^[OB^[OB for the scroll wheel? Must be easy to accomplish, low hanging fruit. Would be very much appreciated by vim users!

**Comment by Trolldemorted** [comment]
I guess this explains why tmux' mouse mode doesn't work (?)

**Comment by maertendMSFT** [comment]
This should be supported in the latest release

**Comment by Trolldemorted** [comment]
@maertendMSFT the ssh client deployed to W10 2004 is still on version `OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5`. Can you estimate when this feature will be shipped?

**Comment by Luk164** [comment]
I just hit the same problem, wanted to use mc via ssh on another computer and mouse events did not work.

**Comment by paddywaan** [comment]
I've installed the latest v8.1 from the releases, as well as rebooted however have found that the issue of mouse interop still does not work correctly. I found my way here from: https://github.com/microsoft/terminal/issues/376 and am at a loss as to how to resolve mouse input for use inside of vim/htop/whatnot.

**Comment by Trolldemorted** [comment]
The recently released w10 version 20H2 (Build 19042.804) is still affected by this bug.

8.1.0.0 was released in 2019, do you have any updates for us @maertendMSFT ?

**Comment by mbs-c** [comment]
@Trolldemorted See #1693 for the update.

**Comment by Trolldemorted** [comment]
Thanks, it's good to know that it was intended to be included in 20H2.

**Comment by singular78** [comment]
When ssh to wsl on windows, the tmux in wsl can't get mouse event. 
OpenSSH_for_Windows_8.1p1

**Comment by Luk164** [comment]
Works for me after the last update. SSH into a linux allws me to use mouse as expected

**Comment by xspeed1989** [comment]
It doesn't work well on 8.6.0.0 when set mouse=on in vim

**Comment by Trolldemorted** [comment]
Same with tmux' mouse mode. I lost track of all these issues, is there an open one for the problems in TUI programs?

**Comment by andythedude** [comment]
running 20H2 and it doesn't work. this is the 21st century microsoft... CMON! Linux has had this for _decades_

**Comment by singular78** [comment]
> Works for me after the last update. SSH into a linux allws me to use mouse as expected

It doesn't work when ssh to wsl on windows

**Comment by Luk164** [comment]
@andythedude What is your setup? Mouse events have been working for me for the last few updates, both via pwsh and wsl. I am running pwsh 7.1.5 and WT 1.11.2921.0 (latest stable from windows store)

**Comment by singular78** [comment]
Thank you! It works after I upgrade win10 to win11.
I ssh to pwsh on Windows11 from the iTerm on MacOS, then I open wsl in pwsh.

**Comment by MANTENN** [comment]
> e events have been working for me for the last few updates, both via pwsh and wsl. I am running pwsh 7.1.5 and WT 1.11.2921.0 (latest stable from windows store)

Doesnt work when you SSH into a server; it works only on the WSL instance. Still a PTA to use.

**Comment by Luk164** [comment]
@MANTENN It DOES work for me, both via WSL and directly
![2021-11-25 17-45-48-cropped](https://user-images.githubusercontent.com/30559213/143479177-1b273413-98ac-4619-842d-d017e317a574.gif)

**Comment by MANTENN** [comment]
> @MANTENN It DOES work for me, both via WSL and directly ![2021-11-25 17-45-48-cropped](https://user-images.githubusercontent.com/30559213/143479177-1b273413-98ac-4619-842d-d017e317a574.gif)

Doesn't work with VIM

**Comment by francescoboc** [comment]
I am using OpenSSH_for_Windows_9.2p1, LibreSSL 3.7.2 on Win10 22H2, and I have no mouse support. Is it there anything I have to do to enable it?

**Comment by Git-Boy-Slim** [comment]
I would also be very interested in a solution for this. I am on the latest win 10 64bit with Open SSH v9.5.0.0p1-Beta. I can't get any working mouse mode, when I'm sshing into my windows machine. Using wsl locally on the latest Terminal preview recognizes my mouse, but I need ssh support. 

Another interesting observation:
When I used a different win 11 PC with a very close software setup I was able to use my mouse in nano and tmux over ssh. So there is something, but not for all windows version.

**Comment by Andrelopithecus** [comment]
> I would also be very interested in a solution for this. I am on the latest win 10 64bit with Open SSH v9.5.0.0p1-Beta. I can't get any working mouse mode, when I'm sshing into my windows machine. Using wsl locally on the latest Terminal preview recognizes my mouse, but I need ssh support.
> 
> Another interesting observation: When I used a different win 11 PC with a very close software setup I was able to use my mouse in nano and tmux over ssh. So there is something, but not for all windows version.

i ended up going a different route and grabbing alacritty terminal as it is OS agnostic.
