### ISSUE TITLE
PowerShell progress bars mangle SSH sessions

### ISSUE THREAD

**Issue by Jookia** [PowerShell/Win32-OpenSSH#1160]
Likely related to #938

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

Did this.

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`

7.6.1.0
I installed it using chocolatey

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

Windows 10 Home (17672.rs_prerelease.180511-1445)

**Client OperatingSystem**

Windows 10 Home (17672.rs_prerelease.180511-1445)
Linux OpenSSH_7.4p1, OpenSSL 1.0.2k  26 Jan 2017

**What is failing**

Get-Help prints a pretty progress bar while it searches for help.
Over SSH this progress bar mangles the output for some reason.
This applies when SSHing locally from an identical PowerShell or remotely via Linux.
Happens with sshd in debug mode.
Happens with SSH_TERM_CONHOST_PARSER=0.
Workaround is currently ssh -T..

**Expected output**
**Actual output**

![screenshot showing two instances of Get-Help](https://user-images.githubusercontent.com/185275/40308818-f4461310-5cf6-11e8-9082-2b0ef404633d.png)
Above is two instances of Get-Help running.
The one on the left is run through SSH to the same user.
The one on the right is run normally.

**Comment by manojampalam** [comment]
@bagajjal is this expected?

**Comment by dwatley** [comment]
Ping...

**Comment by bagajjal** [comment]
@dwatley - "Get-Help about_*" has no rendering issues over SSH. What was the exact command you are trying?

**Comment by Jookia** [comment]
'Get-Help which' was used in the screenshot above

**Comment by dwatley** [comment]
@bagajjal - As noted by @Jookia in the issue, this seems very much related to https://github.com/PowerShell/Win32-OpenSSH/issues/938. Depending on the SSH client, the console is managed unless `-T` is passed to disable pseudo-tty allocation.

**Comment by maertendMSFT** [comment]
This should now work in Win 10, we are not supporting this downlevel.
