### ISSUE TITLE
sshd virtual users logon rights

### ISSUE THREAD

**Issue by dwatley** [PowerShell/Win32-OpenSSH#1162]
**"OpenSSH for Windows" version**
openssh-portable latestw_all 236b04b3
 
**Server OperatingSystem**
Windows 10 Professional

**Client OperatingSystem**
Windows 10 Professional

**What is failing**
Seems most recent changes in dev broke logons due to the sshd user that is generated not having permissions. @manojampalam 

**Expected output**
Logon is processed as usual.

**Actual output**
Event Log Error
```
An account failed to log on.

Subject:
	Security ID:		SYSTEM
	Account Name:		DWATLEY-W$
	Account Domain:		CONTOSO
	Logon ID:		0x3E7

Logon Type:			2

Account For Which Logon Failed:
	Security ID:		NULL SID
	Account Name:		sshd_14724
	Account Domain:		VIRTUAL USERS

Failure Information:
	Failure Reason:		The user has not been granted the requested logon type at this machine.
	Status:			0xC000015B
	Sub Status:		0x0

Process Information:
	Caller Process ID:	0x3984
	Caller Process Name:	C:\Program Files\OpenSSH\sshd.exe
```

sshd debug log error
```
sshd: debug3: LogonUserExExW failed with 1385 \n
```

**Comment by NoMoreFood** [comment]
I think this is all done in the generate_sshd_virtual_token() which was outside of my changes.  Looks like that code has been doing an interactive logon for quite awhile...

**Comment by dwatley** [comment]
Yeah it was a more recent commit. I rolled back to my commit at https://github.com/PowerShell/openssh-portable/commit/936b89ac0d645aae059bcb7e376e14bc276d852a, rebuilt and things are working again.

Iterated through the latest commits building/testing until it breaks. The breaking commit is the latest commit: https://github.com/PowerShell/openssh-portable/commit/236b04b335997e96e424b82ed0dcc707931da9cb

**Comment by manojampalam** [comment]
Thanks for reporting this. The changes in that last commit looks unrelated. I believe the fix is to grant interactive logon privilege before doing a LogonUserExEx. I'm following up.

**Comment by manojampalam** [comment]
I understand why has showed up with the latest change. Previously, for unprivileged token generation, we had fall back logic in case virtual token generation fails (i.e to use sshd account token). This was masking the original issue and was removed in the last commit. 

@dwatley glad that you caught this early.

**Comment by dwatley** [comment]
@manojampalam Happy to help. I patched in your PR and it works for me.

**Comment by dwatley** [comment]
@manojampalam - eta on next release?

**Comment by bingbing8** [comment]
@dwatley, expect upcoming release this week
