### ISSUE TITLE
Reverse tunnel problems

### ISSUE THREAD

**Issue by gabest11** [PowerShell/Win32-OpenSSH#1163]
Server: Windows Server 2012 R2 Standard, OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
Client: OpenWRT 17.01.4, Dropbear SSH client v2017.75

I setup a reverse tunnel from a router running OpenWRT behind a 3G mobile connection. It works for a while, but the server randomly spawns multiple sshd child processes and it won't let me connect until I forcefully terminate the old ones. According to the log, it seems to reconnect every 10 minutes. 

The command I use on the client: (not sure about the monitoring port, or if it does anything)
`autossh -i /root/.ssh/id_dropbear -M 8022 -f -N -p 8022 -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3" -R *:9080:localhost:80 -R *:9022:localhost:22 Gabest@*********`

Three repeating segments from the log:
[log.txt](https://github.com/PowerShell/Win32-OpenSSH/files/2055445/log.txt)

**Comment by gabest11** [comment]
More info. Tested the server on a FreeBSD machine. Almost the same thing, just there are no stuck processes, because the ports are already in use. Also, there are no ServerAlive* options for dropbear (cut down, minimal implementation of ssh), this is probably why the idle connection is being dropped by a router along the path after 10 min. Setting ClientAlive* on the server seems to be a good solution on both platforms. FreeBSD just handles the problem nicer, without leaking zombie processes.

**Comment by manojampalam** [comment]
What release of OpenSSH_for_Windows_7.6p1 are you using? We had an issue with leaking processes in the initial version. Can you try the latest version?

**Comment by gabest11** [comment]
Looks to be alright with the latest version (7.7), but I bumped into another one.

In win32_usertoken_utils.c, TranslateName fails to convert domain\name to name@domain, because on the server ONLY "User logon name (pre-Windows 2000)" was filled in. As soon as I corrected it in the circled part, public key authentication started working again.

![untitled](https://user-images.githubusercontent.com/8768197/40809187-dc461f90-6529-11e8-8758-86d4b274abb9.jpg)

This was the logged error:

```
1368 2018-05-31 22:02:14.588 debug3: generate_s4u_user_token: Unable to discover upn for user 't': 1332
1368 2018-05-31 22:02:14.588 debug1: generate_s4u_user_token: LsaLogonUser() failed: -1073741726 SubStatus 0.
1368 2018-05-31 22:02:14.588 debug3: unable to generate token for user testenv\\gabest
1368 2018-05-31 22:02:16.932 debug3: generate_s4u_user_token: Unable to discover upn for user 't': 1332
1368 2018-05-31 22:02:16.932 debug1: generate_s4u_user_token: LsaLogonUser() failed: -1073741726 SubStatus 0.
1368 2018-05-31 22:02:16.932 error: unable to generate token on 2nd attempt for user testenv\\gabest
1368 2018-05-31 22:02:16.932 error: unable to get security token for user testenv\\gabest
1368 2018-05-31 22:02:16.932 fatal: fork of unprivileged child failed
1368 2018-05-31 22:02:16.932 debug1: do_cleanup
```

**Comment by gabest11** [comment]
It was my mistake, but the log file could be more helpful!

**Comment by gabest11** [comment]
All fine after a couple of days with 7.7.
