### ISSUE TITLE
installation instructions lacking critical information

### ISSUE THREAD

**Issue by jhiswin** [PowerShell/Win32-OpenSSH#1166]
sftp requires cmd.exe with /c set as shell

[Install Win32 OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH)

Still lists "Program Files" with https://github.com/PowerShell/Win32-OpenSSH/issues/1164
sftp and tunneling don't work out of the box.  Even with the registry patch setting shell to powershell, switching to internal-sftp.
chocolatey package doesn't work.

This should be listed somewhere.

**Comment by hugginsa** [comment]
@jhiswin - How did you switch to internal-sftp? My impression from the docs was that it required sftp-only configuration, but I still need ssh. Can you share part of your sshd_config?

**Comment by hugginsa** [comment]
The sftp and tunneling issue may relate to #1165

**Comment by jhiswin** [comment]
I've solved it myself, but this should be listed somewhere prominent.  Doesn't help that I can't access the wiki to add it myself.
