### ISSUE TITLE
Domain Users group is not found by AllowGroups (all others works fine)

### ISSUE THREAD

**Issue by jirijanata** [PowerShell/Win32-OpenSSH#1167]
**"OpenSSH for Windows" version**
v7.7.0.0p1-Beta
 
**Server OperatingSystem**
Windows Server 2012 R2 Datacenter

**Client OperatingSystem**
Windows 10, WinSCP

**What is failing**
I've user **testssh**. This user is domain user and is member of only one group **Domain Users**. If I put `AllowGroups "doma\domain users"` into the config, user is not able to log in. There is some problem with getting group **Domain Users** info from user account.

I tested following scenarios (+the one mentoined above):
1. User **testssh** is member of 2 Groups - **Domain Users** and **ssh**. 
- Config file -> `AllowGroups "doma\domain users"` -> **NOT able to log in**
- Config file -> `AllowGroups doma\ssh` -> **OK - user can log in**

2. I also tested group **Domain Admins**, and this group works without any problem.

3. Usually is **Domain Users** primary user group. I changed primary group to **ssh**, but everything remain the same.

**Expected output**
User is not able to log in.

**Actual output**
User should be able to log in.

Here are log files. Otherwise works this release very good. Chroot is working amazingly! Thanks
[sshd_log.txt](https://github.com/PowerShell/Win32-OpenSSH/files/2063335/sshd_log.txt)
[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/2063336/sshd_config.txt)

**Comment by manojampalam** [comment]
@nomorefood for any insight

**Comment by NoMoreFood** [comment]
@manojampalam @bagajjal You may remember my commentary on this topic in the pull request which I have copy/pasted below.

> Just wanted to note that the check (sub == SECURITY_BUILTIN_DOMAIN_RID) is to eliminate 'None' group from showing up (and causing the AppVeyor tests to fail that check for 0 group memberships). The 'None' group is a real principal that's added to every local account (sub-authority: '-513'). When the accounts is domain joined, this resolves to 'Domain Users'. You can actually assign permissions on the file system to 'None' and it's effectively the same as granting it to 'Authenticated Users'. It looks like the author of the 'whoami /groups' command actually tries to exclude this as well which has the side effect of making 'Domain Users' not show up on domain accounts (which it definitely should). The ‘Users’ BUILTIN group is also always added to the token regardless of the user being in the ‘Users’ group. Since these are all arguably real group principals that are used in group-based security checks, one could argue we should include them as well. If we choose to do this though, we’d have to eliminate the “no groups” tests from AppVeyor since there’s really no such thing as a real user with no group principals -- the only way that would happen is S4U fails or name lookup would fails with would be hard to trigger in an E2E test.

My preference is stop filtering out this SID altogether and eliminate the no group membership tests from AppVeyor.  

@jirijanata Were you just using 'Domain Users' for a simple test?  Is there a practical reason such a broad group would ever be used?

**Comment by manojampalam** [comment]
Yeah, hence added you. I don't see a difference between

AllowGroups "doma\domain users" 
and
AllowUsers "doma\\*"

Am I right?

And yes, if the tests are the only practical concern, we can as well get rid of this filtering.

**Comment by NoMoreFood** [comment]
Yes, that would pretty much accomplish the same intended effect.

I'll put in a pull request to remove that filtering and the corresponding tests.

**Comment by jirijanata** [comment]
Hi, thank you for quick reaction :) It was just test. I do not see any practical reason for using **Domain Users** group. I was just a little bit confused.. 

The information about not showing **Domain Users** group in `whoami /groups` command is also new for me.

If you can't easilly fix it (because of using `whoami /groups`) I suggest you to mention this behavior in Wiki :)

**Comment by NoMoreFood** [comment]
@manojampalam [Pull request](https://github.com/PowerShell/openssh-portable/pull/316) is in.  @jirijanata Should be addressed in the next version.

**Comment by jirijanata** [comment]
Awesome :) I'll test it with new release. Thank you very much.
