### ISSUE TITLE
Service restart doesn't terminate existing sessions

### ISSUE THREAD

**Issue by jirijanata** [PowerShell/Win32-OpenSSH#1168]
**"OpenSSH for Windows" version**
v7.7.0.0p1-Beta
 
**Server OperatingSystem**
Windows Server 2012 R2 Datacenter

**Client OperatingSystem**
Windows 10, Putty, WinSCP

**What is failing**
If I stop sshd service, all existing sessions are still running. Usually, if some service is restarted (for example Remote Desktop), all users are disconnected.

Before `netsh stop sshd` - sshd.exe is child process of services.exe (it's not visible on the picture)
![before_service_stop](https://user-images.githubusercontent.com/14040091/40871603-ed90891e-663e-11e8-852a-5d02b6662292.png)

After `netsh stop sshd` - process sshd.exe with PID 3632 is killed. But all child processes are running. sshd.exe is not child process of services.exe.
![after_service_stop](https://user-images.githubusercontent.com/14040091/40871629-348c5c94-663f-11e8-817d-f4ff18fab630.png)

If I kill sshd.exe with PID 1984, the session is still running. I need to kill sshd.exe with PID 3732 to terminate remote SSH session.
![after_kill_1984](https://user-images.githubusercontent.com/14040091/40871637-6a3f18fe-663f-11e8-9b60-2c200920a3b7.png)

**Expected output**
All SSH sessions are terminated and noone is able to login via SSH.

**Actual output**
All existing SSH sessions are working, but it's not possible to establish new session.

**Comment by manojampalam** [comment]
This is by design, similar to how it works on Unix.

**Comment by jirijanata** [comment]
Thank you for your quick reply. I thought that it's by design. I'm using mostly Windows based systems, so for me it was not expected behavior.

But from my point of view is easily understood, that cross-platform software should work same on all platforms.
