### ISSUE TITLE
Non-English (i.e. Cyrillic) characters cannot be input via console

### ISSUE THREAD

**Issue by dpokrovsky** [PowerShell/Win32-OpenSSH#1169]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**
Done
**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command **ssh**).Source).VersionInfo.FileVersion)`
 0.0.18.0
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Linux version 3.2.40 (root@build1) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #15284 SMP PREEMPT Sat May 19 04:14:18 CST 2018
OpenSSH_6.8p1-hpn14v6, OpenSSL 1.0.2n-fips  7 Dec 2017
**Client OperatingSystem**
Microsoft Windows [Version 10.0.16299.431]
**What is failing**
While trying to input non-English characters (i.e. Cyrillic) they are not echoed (and therefore being processed) properly in terminal. Put it simple: cannot input any non-English string.
Have tried _chcp 866_ and _chcp 65001_ for **cmd** session from which **ssh** was run.
Here is a server-side locale setting from ssh session:
LANG=ru_RU.utf8
LC_CTYPE="ru_RU.utf8"
LC_NUMERIC="ru_RU.utf8"
LC_TIME="ru_RU.utf8"
LC_COLLATE="ru_RU.utf8"
LC_MONETARY="ru_RU.utf8"
LC_MESSAGES="ru_RU.utf8"
LC_PAPER="ru_RU.utf8"
LC_NAME="ru_RU.utf8"
LC_ADDRESS="ru_RU.utf8"
LC_TELEPHONE="ru_RU.utf8"
LC_MEASUREMENT="ru_RU.utf8"
LC_IDENTIFICATION="ru_RU.utf8"
LC_ALL=ru_RU.utf8
At the same time there is no problem with displaying non-English characters in ssh session:
_$ ls ~/example/
пример_
The same thing (non-English input) works fine in _ssh_ from Ubuntu app (Linux Subsystem).
**Expected output**
_ls ~/example/пример/_
**Actual output**
for chcp 866:
_ls ~/example/үӠҨҬҥӠ/_
for chcp 65001:
_ls ~/example/ЀЀЀЀЀЀ/_

**Comment by bagajjal** [comment]
This is fixed. please check the latest release.
