### ISSUE TITLE
v7.7.0.0 - SFTP Connection closed on Windows Server 2008

### ISSUE THREAD

**Issue by Yorlereiyo** [PowerShell/Win32-OpenSSH#1170]
**"OpenSSH for Windows" version**
7.7.0.0
 
**Server OperatingSystem**
Windows Server 2008 R2 Standard

**Client OperatingSystem**
Tried on itself, Linux, WinSCP

**What is failing**
SFTP Connection closed
Downgrade to 1.0.0.0 can fix that

**Expected output**
SFTP connect successfully

**Actual output**
C:\Program Files\OpenSSH>sftp 127.0.0.1
The authenticity of host '127.0.0.1 (127.0.0.1)' can't be established.
ECDSA key fingerprint is SHA256:KY+E7EC/l8ZU1RQoTwgBfwF6/xIGYX7fdQiyrNeGRLM.
Are you sure you want to continue connecting (yes/no)?
Warning: Permanently added '127.0.0.1' (ECDSA) to the list of known hosts.
administrator@127.0.0.1's password:
Connection closed

**Comment by shitrus** [comment]
You are suffering from this issue #1164

**Comment by manojampalam** [comment]
Try v7.7.1.0
