### ISSUE TITLE
Signed LibreSSL utilities for Windows

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/Win32-OpenSSH#1173]
**"OpenSSH for Windows" version**

     7.6.0.0
 
**Server OperatingSystem**

    N/A

**Client OperatingSystem**

    Windows 10 Pro

**What is failing**

Currently the only options to install openssl (or a variant) on Windows are [random unsigned binaries](https://wiki.openssl.org/index.php/Binaries). I note OpenSSH is built using LibreSSL:

    OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4

It would be good to be able to get a signed build of LibreSSL for Windows for common command line libressl cases, eg inspecting keys and certificates. This would allow Windows users to get LibreSSL from a trusted source.

**Comment by manojampalam** [comment]
All binaries are MS signed from v7.6.1.0 onwards. Reopen if you see otherwise.

**Comment by mikemaccana** [comment]
@manojampalam are you sure there is a signed build of LibreSSL? I can't see any LibreSSL binaries  anywhere on my machine.

**Comment by mikemaccana** [comment]
PS = I'd reopen, as the binaries don't exist, but I don't have permission.

**Comment by manojampalam** [comment]
I see this for libcrypto.dll in 7.6.1.0 payload
![image](https://user-images.githubusercontent.com/14185020/40933373-1def0dee-67e6-11e8-9472-569a6268290c.png)

**Comment by mikemaccana** [comment]
Hi Manoj, I think you're not quite reading the request correctly, which is
for a libressl binary (typically called 'openssl.exe').

**Comment by manojampalam** [comment]
hmm. yes indeed. This is currently not in scope. Would you mind listing out both use cases and business cases on why they would be useful for a general OpenSSH setup.

**Comment by bagajjal** [comment]
Win32-OpenSSH requirement is to have a DLL (we named it as libcrypto.dll) instead of EXE (openssl.exe).

**Comment by mikemaccana** [comment]
It it possible to include an exe, which would allow us to use LibreSSL to inspect keys and certificates, change formats, etc? Currently we're limited to `certreq`, which can only do CSR, a small subset of the full LibreSSL binary.

**Comment by maertendMSFT** [comment]
We will be transitioning to OpenSSL in the near future.  Closing as this will be out of scope.
