### ISSUE TITLE
Executing service results in error 1297 even though the sshd user has correct security rights

### ISSUE THREAD

**Issue by NiQ1** [PowerShell/Win32-OpenSSH#1176]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
7.7.0.0 

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 Pro

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
Executing service results in error 1297 even though the sshd user has both the "log on as a service" and "replace a process level token" rights.
Note - if executing sshd directly from the command line as the sshd user (using "run as") then it works.

**Expected output**
C:\>net start sshd
The command completed successfully.

**Actual output**
C:\>net start sshd
System error 1297 has occurred.

A privilege that the service requires to function properly does not exist in the service account configuration.
You may use the Services Microsoft Management Console (MMC) snap-in (services.msc) and the Local Security Settings MMC snap-in (secpol.msc) to view the service configuration and the account configuration.

**Comment by manojampalam** [comment]
sshd service runs as SYSTEM, you don't need to and should not assign any privileges to "sshd" account - it is a low privilege account. 

Are you seeing this after running install-sshd.ps1 ?

**Comment by NiQ1** [comment]
sshd can't run as system, it explicitly checks for that and terminates... also the install script creates the "NT SERVICE\sshd" account specifically for the service.

**Comment by manojampalam** [comment]
This is simply not the case with 7.7.0.0. where in the installation script do you see that account being created?

**Comment by gayantd** [comment]
@manojampalam I do agree with @NiQ1 . I installed this and I have an account called "sshd". But I never assigned to any. I created own account in windows. SSHD service runs under SYSTEM account.
But when I check "logon as service" I could see sshd_port has been created numerous times. 
So I do believe sshd account is created when I install "install-sshd.ps1". Yet I don't know the purpose of that account.
@NiQ1 , sorry I didn't meant to HiJack your thread.

**Comment by manojampalam** [comment]
It's true that you'll end up with sshd (not ntservice/sshd) user account. It's not created as part of install-sshd, rather at service startup. This is being created at service startup to accommodate Unix code looking for sshd unprivileged account.

**Comment by maertendMSFT** [comment]
The latest version does not rely on sshd accounts, original issue is out of scope

**Comment by aragon5956** [comment]
i've the same problem even i execute `.\FixHostFilePermissions.ps1` and  `.\FixUserFilePermissions.ps1` :
 ```
PS C:\Program Files\OpenSSH> Restart-Service sshd
Restart-Service : Le service «sshd (sshd)» ne peut pas démarrer en raison de l'erreur suivante: Impossible de démarrer
le service sshd sur l'ordinateur '.'.
Au caractère Ligne:1 : 1
+ Restart-Service sshd
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Restart-Service]
   , ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.RestartServiceCommand

PS C:\Program Files\OpenSSH> .\FixHostFilePermissions.ps1
  [*] C:\ProgramData\ssh\sshd_config
      looks good

  [*] C:\ProgramData\ssh\ssh_host_ecdsa_key
      looks good

  [*] C:\ProgramData\ssh\ssh_host_ecdsa_key.pub
      looks good

  [*] C:\ProgramData\ssh\ssh_host_ed25519_key
      looks good

  [*] C:\ProgramData\ssh\ssh_host_ed25519_key.pub
      looks good

  [*] C:\ProgramData\ssh\ssh_host_rsa_key
      looks good

  [*] C:\ProgramData\ssh\ssh_host_rsa_key.pub
      looks good

   Done.

PS C:\Program Files\OpenSSH> .\FixUserFilePermissions.ps1
  [*] ~\.ssh\config
      looks good

  [*] C:\Users\alexa\.ssh\id_rsa
      looks good

  [*] C:\Users\alexa\.ssh\id_rsa.pub
      looks good

   Done.

PS C:\Program Files\OpenSSH> .\FixHostFilePermissions.ps1
  [*] C:\ProgramData\ssh\sshd_config

Current owner: 'ALEXANDREM\alexa'. 'AUTORITE NT\Système' should own 'C:\ProgramData\ssh\sshd_config'.
Shall I set the file owner?
[O] Oui  [T] Oui pour tout  [N] Non  [U] Non pour tout  [S] Suspendre  [?] Aide (la valeur par défaut est « O ») : T

Need to remove the inheritance before repair the rules.
Shall I remove the inheritance?
[O] Oui  [T] Oui pour tout  [N] Non  [U] Non pour tout  [S] Suspendre  [?] Aide (la valeur par défaut est « O ») : T
Inheritance is removed from 'C:\ProgramData\ssh\sshd_config'.

'BUILTIN\Utilisateurs' should not have access to 'C:\ProgramData\ssh\sshd_config'..
Shall I remove this access?
[O] Oui  [T] Oui pour tout  [N] Non  [U] Non pour tout  [S] Suspendre  [?] Aide (la valeur par défaut est « O ») : T
'BUILTIN\Utilisateurs' has no more access to 'C:\ProgramData\ssh\sshd_config'.
'NT SERVICE\sshd' has no more access to 'C:\ProgramData\ssh\sshd_config'.
      Repaired permissions

  [*] C:\ProgramData\ssh\ssh_host_ecdsa_key
      looks good

  [*] C:\ProgramData\ssh\ssh_host_ecdsa_key.pub
      looks good

  [*] C:\ProgramData\ssh\ssh_host_ed25519_key
      looks good

  [*] C:\ProgramData\ssh\ssh_host_ed25519_key.pub
      looks good

  [*] C:\ProgramData\ssh\ssh_host_rsa_key
      looks good

  [*] C:\ProgramData\ssh\ssh_host_rsa_key.pub
      looks good

   Done.

PS C:\Program Files\OpenSSH> ^C
PS C:\Program Files\OpenSSH> Restart-Service sshd
Restart-Service : Le service «sshd (sshd)» ne peut pas démarrer en raison de l'erreur suivante: Impossible de démarrer
le service sshd sur l'ordinateur '.'.
Au caractère Ligne:1 : 1
+ Restart-Service sshd
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Restart-Service]
   , ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.RestartServiceCommand
```
could you help me ?
my sshd version is  : 

```
PS C:\Program Files\OpenSSH> .\sshd.exe -d
debug1: sshd version OpenSSH_for_Windows_9.5, LibreSSL 3.8.2
debug1: private host key #0: ssh-rsa SHA256:ClEXD2C/iaTwtFDxUOPwcIrK8+CqXHlutDxXSgzIPTM
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:7qwfTYBphjkTNFm+wSF+LX9P9JKPMgu++qLcOKjd/FQ
debug1: private host key #2: ssh-ed25519 SHA256:T3TryzsUax+Lm1/tPpZtoH12STRWvMY/teFwy4HPa6o
debug1: rexec_argv[0]='C:\\Program Files\\OpenSSH\\sshd.exe'
debug1: rexec_argv[1]='-d'
debug1: Bind to port 22 on 0.0.0.0.
Server listening on 0.0.0.0 port 22.
```
my `ssh` directory in `ProgramData` is  belongs to the `administrator` user
![sshPrivilèges](https://github.com/user-attachments/assets/8947f799-fde5-486e-baac-45e89f7d2193)
![propriétaireDossierProgramDataSSH](https://github.com/user-attachments/assets/bf04bf80-939f-44f4-bf8e-f3310b144041)

could you help me ?
Regards
