### ISSUE TITLE
CTRL-C does not work

### ISSUE THREAD

**Issue by lufinkey** [PowerShell/Win32-OpenSSH#1182]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
v7.7.1.0p1-Beta
 
**Server OperatingSystem**
Windows 7

**Client OperatingSystem**
Linux

**What is failing**
Sending CTRL-C from the terminal during an SSH session does nothing

**Expected output**
CTRL-C should close the program running in the foreground

**Actual output**
CTRL-C does nothing

**Comment by FranklinYu** [comment]
This does work in my machine:

1. SSH to Linux.
2. Run `sleep 10`.
3. Before it wake up, hit CTRL + C.

I see that the program `sleep` terminated. Is this what you want?

**Comment by lufinkey** [comment]
It doesn't work when I SSH from Linux to Windows

**Comment by gayantd** [comment]
Did you add anything in registry at windows "DefaultShellCommandOption" ?

**Comment by lufinkey** [comment]
Where in the README does it say to do that, what path is that value at, and
what is the value?

**Comment by lufinkey** [comment]
The answer to your question is no, but was that something I was supposed to do?

**Comment by parkovski** [comment]
See #914; this is a chronic issue with every project that tries to act as a terminal on Windows. Unless somebody with source access to the console gives some guidance, I'm pretty sure it's unsolvable in the general case - I've spent hours digging through console disassembly and trying all sorts of methods with no success. In the future it'll be possible with actual PTYs (search `PseudoConsole` in kernel32 exports on latest insider build), but it sure would be nice if existing projects could do this now.

**Comment by manojampalam** [comment]
I see this working from Windows to Windows on a session with PTY. Did a ping and Ctrl+C aborted it. 
@bagajjal any clue why this would not work from Linux to Windows ? Does TERM value matter for Ctrl+C ?

**Comment by lufinkey** [comment]
I've been using whatever the default is, which I'm assuming is cmd.exe.
CTRL-C does work in regular cmd.exe though (not through an SSH connection)

**Comment by ronnicek** [comment]
Hm.. I have actually different problem. I am testing OpenSSH and I am connecting from Mac -> Windows -> Linux to see how OpenSSH works in Windows world :) but when I hit ctrl+c to terminate program running in Linux session (tail -f for example) it disconnect me from Linux machine directly.. any ideas?

One point.. when I connect from Windows to Linux then Ctrl + C is working well.. it could be some settings in iTerm2?

Looks also similar to #20

**Comment by maertendMSFT** [comment]
This should work in the latest release, please reopen if you still see this issue.
