### ISSUE TITLE
Issue with public key authentication

### ISSUE THREAD

**Issue by Maddog2050** [PowerShell/Win32-OpenSSH#1183]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
7.7.0.0
 
**Server OperatingSystem**
Windows Server 2016 Datacenter

**Client OperatingSystem**
Red Hat Enterprise Linux Server release 6.1 (Santiago)

**What is failing**
Key based authentication

**Expected output**
User connects to windows server

**Actual output**
Permission denied (publickey,keyboard-interactive).

I'm trying to run the OpenSSH service as 'NT AUTHORITY\Network Service' as the commands that I need to execute require network access. I've fixed security policy & file permissions, but when adding the service account  permissions to the authorized_keys I get the error below.

debug3: Bad permissions. Try removing permissions for user: S-1-5-20 on file C:\\Users\\MyUser\\.ssh/authorized_keys.
Authentication refused.

Is it possible to change this check so it checks for the SID that the sshd is running as rather than a fixed list of users.

**Comment by discentem** [comment]
@Maddog2050 Are you able to get to key base auth to work with other, normal system users? I'm running into this same issue with a normal user.

**Comment by bingbing8** [comment]
sshd service can run under SYSTEM as service or run in interactive mode (typically as admin), but not as network service.

**Comment by JW0914** [comment]
@Maddog2050 If this has been resolved, please close the issue =]
