### ISSUE TITLE
Errors in Windows Event Viewer

### ISSUE THREAD

**Issue by MrWolf-to** [PowerShell/Win32-OpenSSH#1184]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 7.7.1.0p1 Beta
**Server OperatingSystem**
Windows 7 64 bit and Windows 10 64 bit
ProductName).ProductName)`

**Client OperatingSystem**
Windows 7 64 bit and Windows 10 64 bit
**What is failing**
Errors in Windows Event Viewer
**Expected output**
-
**Actual output**
-

Hi, for latest versions, when I start sshd (net stars sshd), I see these errors in Window Event Viewer:

Event ID 2: sshd: error: Could not connect to agent "\\\\.\\pipe\\openssh-ssh-agent": No such file or directory

Event ID 2: sshd: error: Couldn't create pid file "c:\\program files\\openssh/./logs/sshd.pid": No such file or directory

I can connect to my server, though. I tried to add OpenSSH installation path to system PATH.

**Comment by manojampalam** [comment]
Check your service configuration (sshd_config). I guess you have specific entries for HostKeyAgent and PidFile

**Comment by MrWolf-to** [comment]
Hi, I can see these options my sshf_config:
hostkeyagent \\.\pipe\openssh-ssh-agent
PidFile ./logs/sshd.pid

I changed the second line to:
PidFile .\sshd.pid
as suggested here:
[https://github.com/PowerShell/Win32-OpenSSH/issues/493](url)
and it creates sshd.pid in the program folder.
If I tried to add the absolute path C:\ProgramData\ssh\logs, it gives me error:
sshd: error: Couldn't create pid file "C:\\\ProgramData\\\ssh\\\logs": Permission denied
it doesn't seem to handle backslash \\.

Doing this, the first error seems gone.
