### ISSUE TITLE
No sha256 hashes provided

### ISSUE THREAD

**Issue by discentem** [PowerShell/Win32-OpenSSH#1189]
Please provide sha256 hashes for these releases.

**Comment by manojampalam** [comment]
Binaries and utility scripts are already signed. Are you asking for something else ?

**Comment by discentem** [comment]
I guess signatures are sufficient. Many other software packages list the hashes of each new binary as well to verify downloads. ¯\\_(ツ)_/¯

**Comment by DarwinJS** [comment]
Sounds like you are talking about windows servicing.  If you consume openshh as an optional windows feature on win 10 / 2016 - you get all of that.
