### ISSUE TITLE
Connect fails from Secure Shell App for Google Chrome

### ISSUE THREAD

**Issue by cwegener** [PowerShell/Win32-OpenSSH#119]
Error message:
'buffer_get_ret: trying to get more bytes 1 than in buffer 0
buffer_get_char_ret: buffer_get_ret failed
buffer_get_char: buffer error'

Steps to reproduce:
1. Install Secure Shell for Google Chrome: https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo
2. Install latest binary release on Win2012R (tested with https://github.com/PowerShell/Win32-OpenSSH/releases/tag/latest based on f3c841824ed99e0ef9131cb3763c790da6030f94)
3. Connect from Secure Shell for Google Chrome using Username and Password.

**Comment by ghost** [comment]
This error happens when you have compression enabled. Disable compression and it will work just fine. I don't know Secure Shell but you will have to search in options or preferences, something like that....
