### ISSUE TITLE
Backspace sends ^H instead of ^? and is not recognized

### ISSUE THREAD

**Issue by rmcgowen** [PowerShell/Win32-OpenSSH#1190]
**"OpenSSH for Windows" version**
OpenSSH x64 7.7.1.0
 
**Server OperatingSystem**
Ubuntu 16.04

**Client OperatingSystem**
Windows 10 Home Version 10.0.17134 Build 17134

**What is failing**
When trying to use backspace in the command prompt while being asked for input in Linux, it sends ^H instead of ^? and does not delete a character.

**Expected output**
When hitting backspace it should delete a character. This is on a machine with Ubuntu.

**Actual output**
Incorrect backspace code being sent when asked for input.

**Comment by bagajjal** [comment]
@rmcgowen  - Please try this [private ssh.exe binary](https://github.com/PowerShell/Win32-OpenSSH/files/2112695/ssh_fix_backspace.zip)

**Comment by bagajjal** [comment]
Please try the private ssh.exe [ssh-fix-backspace.zip](https://github.com/PowerShell/Win32-OpenSSH/files/2112758/ssh-fix-backspace.zip)

**Comment by rmcgowen** [comment]
@bagajjal where is this from and what was the fix? It does indeed work. Thank you.

**Comment by bagajjal** [comment]
Here is the code fix, https://github.com/PowerShell/openssh-portable/pull/325/files

**Comment by rmcgowen** [comment]
I am going to leave this open since it is still an issue in this executable.

**Comment by bagajjal** [comment]
Sure, The fix will be part of next release. I will close this during that time.
