### ISSUE TITLE
Would it be possible to have packages signed by Microsoft? 

### ISSUE THREAD

**Issue by discentem** [PowerShell/Win32-OpenSSH#1191]
I'd like to be able to verify the certificate of the open-ssh releases. Is this possible? Does it mean the format would have to change from a .zip to a executable?

**Comment by bingbing8** [comment]
Starting v7.6.1.0p1-Beta, all the binaries and scripts in zip files are digital signed.

**Comment by discentem** [comment]
Acknowledged. Thanks @bingbing8!
