### ISSUE TITLE
How to activate sftp-server.log

### ISSUE THREAD

**Issue by Lnemirage** [PowerShell/Win32-OpenSSH#1193]
I tried to activate sftp logs as in the previous version but I didn't find sftp-server.log

sshd_config :
Subsystem	sftp	D:\Openssh\sftp-server.exe -l INFO

how to do it?

thanks

**Comment by manojampalam** [comment]
Did you check https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities ?

**Comment by thezim** [comment]
#834 might have some useful info.

**Comment by Lnemirage** [comment]
Now, I'm able to activate sftp logs on local file with :
sshd_config : Subsystem	sftp	sftp-server.exe -l INFO -f LOCAL0
and adding write permission to C:\ProgramData\ssh\logs for the connecting user 

but I'm still unable to have the sftp logs into windows event-viewer

**Comment by manojampalam** [comment]
are you hitting this https://github.com/PowerShell/Win32-OpenSSH/issues/1174

**Comment by Lnemirage** [comment]
thanks, I can see the sftp-logs into windows event viewver with this configuration :
sshd_config : 
     SyslogFacility AUTH
     Subsystem sftp sftp-server.exe -l INFO -f AUTH
and adding the connecting user to the local Administrator group

but I can't give Administrator permissions to this user permanently for security reason.

how to give the necessary permission to this user to use windows event viewver without adding it as Administrator group?

**Comment by manojampalam** [comment]
For now, I recommend turning on file based logging and give write permissions on sshd.log to your non-admin user.
