### ISSUE TITLE
Write failed: Broken pipe

### ISSUE THREAD

**Issue by Remeron** [PowerShell/Win32-OpenSSH#1194]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**
Not a terminal issue 

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 2012 server R2 
**Client OperatingSystem**
Unix Aix 7.1 
**What is failing**
Overview 
I need to connect from AIX to Windows via SSH and sftp. 
I installed SSH as per instructions and exchanged the public keys. 
When i connect from Windows to Aix using public key and or password there are no issues. 
When i connect from AIX to windows using password there are no issues but when i use the public key i get the broken pipe issue. 

I check the file permissions ran the below two commands and they came back good for everything. 
Powershell.exe -ExecutionPolicy Bypass -Command '. .\FixHostFilePermissions.ps1 -Confirm:$false'
Powershell.exe -ExecutionPolicy Bypass -Command '. .\FixUserFilePermissions.ps1 -Confirm:$false' 

when i do ssh -vvv user@destination_serve get the below error 
debug1: read PEM private key done: type RSA
debug1: Authentication succeeded (publickey).
Authenticated to destination_server([10.1.1.1]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
Write failed: Broken pipe

Also "C:\ProgramData\ssh\logs" has no log files. the folder is always empty. 

And i tried changing the below two items in C:\ProgramData\ssh\sshd_config still no luck. I did restart sshd after i changed the config. 
ClientAliveInterval 300
ClientAliveCountMax 30

Sorry if i had missed any information first time user. 

**Expected output**
should connect successfully 
**Actual output**
**Write failed: Broken pipe**

**Comment by bagajjal** [comment]
You need to fix the authorized_keys file permission..
Follow instructions here https://github.com/PowerShell/Win32-OpenSSH/wiki/OpenSSH-utility-scripts-to-fix-file-permissions.

If you still run into issues then follow https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps.

**Comment by Remeron** [comment]
Thanks for the quick response. 

I went through the first link and executed the steps on the Windows server. Got the below response. 

PS C:\program files\openssh> Powershell.exe -ExecutionPolicy Bypass -Command '. .\FixUserFilePermissions.ps1 -Confirm:$false'
  [*] C:\Users\sftpuser\.ssh\id_rsa
      looks good

  [*] C:\Users\sftpuser\.ssh\id_rsa.pub
      looks good
   Done.

PS C:\program files\openssh> Powershell.exe -ExecutionPolicy Bypass -Command '. .\FixHostFilePermissions.ps1 -Confirm:$false'
  [*] C:\ProgramData\ssh\sshd_config
      looks good

  [*] C:\ProgramData\ssh\ssh_host_dsa_key
      looks good

  [*] C:\ProgramData\ssh\ssh_host_dsa_key.pub
      looks good

  [*] C:\ProgramData\ssh\ssh_host_ecdsa_key
      looks good

  [*] C:\ProgramData\ssh\ssh_host_ecdsa_key.pub
      looks good

  [*] C:\ProgramData\ssh\ssh_host_ed25519_key
      looks good

  [*] C:\ProgramData\ssh\ssh_host_ed25519_key.pub
      looks good

  [*] C:\ProgramData\ssh\ssh_host_rsa_key
      looks good

  [*] C:\ProgramData\ssh\ssh_host_rsa_key.pub
      looks good

  [*] C:\Users\sftpuser\.ssh\authorized_keys
      looks good

   Done.

Went through the second link and psexec was detected as a threat in my system and removed it immediately but was able to get the log file working. This is the error i get in the sshd.log is below

2560 2018-06-20 18:17:44.596 debug1: trying public key file C:\\Users\\sftpuser\\.ssh/authorized_keys
2560 2018-06-20 18:17:44.596 debug1: matching key found: file C:\\Users\\sftpuser\\.ssh/authorized_keys, line 1 
2560 2018-06-20 18:17:44.596 debug3: mm_answer_keyallowed: key is allowed
2560 2018-06-20 18:17:44.596 debug3: mm_request_send entering: type 23
2560 2018-06-20 18:17:44.596 debug3: mm_key_allowed: waiting for MONITOR_ANS_KEYALLOWED [preauth]
2560 2018-06-20 18:17:44.596 debug3: mm_request_receive_expect entering: type 23 [preauth]
2560 2018-06-20 18:17:44.596 debug3: mm_request_receive entering [preauth]
2560 2018-06-20 18:17:44.596 debug3: send packet: type 60 [preauth]
2560 2018-06-20 18:17:44.596 debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa [preauth]
2560 2018-06-20 18:17:44.596 Postponed publickey for sftpuser from x.x.x.x port xxxxx ssh2 [preauth]
2560 2018-06-20 18:17:44.612 debug3: receive packet: type 50 [preauth]
2560 2018-06-20 18:17:44.612 debug1: userauth-request for user sftpuser service ssh-connection method publickey [preauth]
2560 2018-06-20 18:17:44.612 debug1: attempt 2 failures 0 [preauth]
2560 2018-06-20 18:17:44.612 debug2: input_userauth_request: try method publickey [preauth]
2560 2018-06-20 18:17:44.612 debug3: userauth_pubkey: have signature for RSA SHA256:zwP [preauth]
2560 2018-06-20 18:17:44.612 debug3: mm_key_allowed entering [preauth]
2560 2018-06-20 18:17:44.612 debug3: mm_request_send entering: type 22 [preauth]
2560 2018-06-20 18:17:44.612 debug3: mm_key_allowed: waiting for MONITOR_ANS_KEYALLOWED [preauth]
2560 2018-06-20 18:17:44.612 debug3: mm_request_receive_expect entering: type 23 [preauth]
2560 2018-06-20 18:17:44.612 debug3: mm_request_receive entering [preauth]
2560 2018-06-20 18:17:44.612 debug3: mm_request_receive entering
2560 2018-06-20 18:17:44.612 debug3: monitor_read: checking request 22
2560 2018-06-20 18:17:44.612 debug3: mm_answer_keyallowed entering
2560 2018-06-20 18:17:44.612 debug3: mm_answer_keyallowed: key_from_blob: 99999999999999
2560 2018-06-20 18:17:44.612 debug1: trying public key file C:\\Users\\sftpuser\\.ssh/authorized_keys
2560 2018-06-20 18:17:44.612 debug1: matching key found: file C:\\Users\\sftpuser\\.ssh/authorized_keys, line 1 RSA SHA256:zwPGhpk55m+VtRfumuP2iBVNIyGuPL6WQDZXZf5zr84
2560 2018-06-20 18:17:44.612 debug3: mm_answer_keyallowed: key is allowed
2560 2018-06-20 18:17:44.612 debug3: mm_request_send entering: type 23
2560 2018-06-20 18:17:44.612 debug3: mm_sshkey_verify entering [preauth]
2560 2018-06-20 18:17:44.612 debug3: mm_request_send entering: type 24 [preauth]
2560 2018-06-20 18:17:44.612 debug3: mm_sshkey_verify: waiting for MONITOR_ANS_KEYVERIFY [preauth]
2560 2018-06-20 18:17:44.612 debug3: mm_request_receive_expect entering: type 25 [preauth]
2560 2018-06-20 18:17:44.612 debug3: mm_request_receive entering [preauth]
2560 2018-06-20 18:17:44.612 debug3: mm_request_receive entering
2560 2018-06-20 18:17:44.612 debug3: monitor_read: checking request 24
2560 2018-06-20 18:17:44.612 debug3: mm_answer_keyverify: publickey gdgdsjshshshs signature verified
2560 2018-06-20 18:17:44.612 debug3: mm_request_send entering: type 25
2560 2018-06-20 18:17:44.612 Accepted publickey for sftpuser from x.x.x.x port xxxxx ssh2: RSA 
2560 2018-06-20 18:17:44.612 debug1: monitor_child_preauth: sftpuser has been authenticated by privileged process
2560 2018-06-20 18:17:44.612 debug3: mm_get_keystate: Waiting for new keys
2560 2018-06-20 18:17:44.612 debug3: mm_request_receive_expect entering: type 26
2560 2018-06-20 18:17:44.612 debug3: mm_request_receive entering
2560 2018-06-20 18:17:44.612 debug3: mm_get_keystate: GOT new keys
2560 2018-06-20 18:17:44.612 debug2: userauth_pubkey: authenticated 1 pkalg ssh-rsa [preauth]
2560 2018-06-20 18:17:44.612 debug3: send packet: type 52 [preauth]
2560 2018-06-20 18:17:44.612 debug3: mm_request_send entering: type 26 [preauth]
2560 2018-06-20 18:17:44.612 debug3: mm_send_keystate: Finished sending state [preauth]
2560 2018-06-20 18:17:44.612 debug1: monitor_read_log: child log fd closed
2560 2018-06-20 18:17:44.612 debug1: LsaLogonUser failed NTSTATUS: 1
**2560 2018-06-20 18:17:44.612 error: unable to generate token for user sftpuser
2560 2018-06-20 18:17:46.924 debug1: LsaLogonUser failed NTSTATUS: 1
2560 2018-06-20 18:17:46.924 error: unable to generate token on 2nd attempt for user sftpuser
2560 2018-06-20 18:17:46.924 error: unable to get security token for user sftpuser
2560 2018-06-20 18:17:46.924 fatal: fork of unprivileged child failed
2560 2018-06-20 18:17:46.924 debug1: do_cleanup**

**Comment by manojampalam** [comment]
What version of OpenSSH are you using? You didn't mention it earlier.

How did you create sftpuser account ? It looks like sshd was unable to generate token for this user using S4U logic. Does it work at all with any other account?

**Comment by bagajjal** [comment]
Now run the sshd as service (net start sshd).. It should allow you to login using key based authentication..

since you are not using psexec, It failed to generate token.. It's expected.

**Comment by Remeron** [comment]
this works 
ssh -vvv -i ~/.ssh/id_rsa -l sftpuser@ad servername 

this gave me broken pipe 
ssh -l sftpuser@ad servername 

So I guess I'm good with SSH 

now the same problem exist with sftp 
how to send the ad user name and identity via sftp? 
sorry if this questions sounds really stupid I'm not an extreme technical guy.

**Comment by bagajjal** [comment]
@Remeron - copy your identify file (id_rsa) to your user profile folder (c:\users\<usersname>\.ssh\) and make sure the permissions are good after copying.

Now you will be able to login using "ssh user@ip", "sftp user@ip".. This eliminates the need of passing "-i <identify_file>"...

**Comment by Remeron** [comment]
Thanks that resolves the issue. 

Two things that were done. 
1. Ad credentials were used with proper ad syntax for both SSH and SFTP
2. Key file was mapped to the correct location.
