### ISSUE TITLE
Unexpected prompt when $ in username

### ISSUE THREAD

**Issue by ichaoX** [PowerShell/Win32-OpenSSH#1198]
**"OpenSSH for Windows" version**
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.4

**Server OperatingSystem**
Windows 7 Ultimate

**Client OperatingSystem**
Any OS

**What is failing**
Unexpected prompt when $ in username or hostname

https://github.com/PowerShell/Win32-OpenSSH/blob/8dd7423e13ac0b88b3084ec95bc93ea09dec1fef/session.c#L916-L920

According to `prompt /?` , username and hostname should replace `$` to `$$`.

**Expected output**
`test$@host C:\Users\test$>`

**Actual output**
`test`

**Comment by NoMoreFood** [comment]
I'll take care of fixing this -- easy fix.

**Comment by manojampalam** [comment]
Thanks for taking care of this @NoMoreFood
