### ISSUE TITLE
Wiki Fix proposal: path issue when using scp

### ISSUE THREAD

**Issue by surli** [PowerShell/Win32-OpenSSH#1199]
I had an issue when using scp with a fresh install of OpenSSH using the instructions provided in the wiki: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

Actually, the problem was the path of the installation for OpenSSH: putting it in `C:\Program Files` might led to errors because of the space in the name.

So I propose to change the documentation to recommend installing it in `C:\OpenSSH`.

Description of the issue I encounter and my own fix is available there: https://stackoverflow.com/questions/50630804/scp-from-linux-to-windows-c-program-is-not-recognized-error/51042690#51042690

**Comment by bagajjal** [comment]
If there is a bug with spaces then it has to be fixed in code.
We still suggest C:\program files as it ACLs properly.

**Comment by surli** [comment]
Actually it has been referenced in #1164 and the latest release suggest as a workaround to install in `C:` (see: https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.7.0.0p1-Beta). So I don't really know if it's going to be fixed or not...

**Comment by bagajjal** [comment]
@surli - It's already fixed https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.7.1.0p1-Beta. Please let us know if you have any issues with latest release (7.7.1.0p1-Beta).

**Comment by surli** [comment]
I'm not sure to understand: how can it be fixed in https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.7.0.0p1-Beta if the page of the release itself talk about this regression? 

My comment was just about fixing the wiki to mention this regression.

**Comment by bagajjal** [comment]
I am referring to v7.7.1.0.p1-Beta. You are referring to old version v7.7.0.0p1-Beta.

**Comment by surli** [comment]
Oh! My bad! FYI the release https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.7.1.0p1-Beta is not tagged as the latest.

**Comment by manojampalam** [comment]
@surli yes. Do you know how to fix the "latest" tag? I always had GitHub do it automatically whenever a new release was pushed.

**Comment by surli** [comment]
Actually I'm not sure it's possible. Here it seems that this happens because you tag both version on the same commit. Maybe try editing latest release?
