### ISSUE TITLE
Launching PowerShell yields an inoperable console

### ISSUE THREAD

**Issue by tseward** [PowerShell/Win32-OpenSSH#12]
Entering the SSH session via PuTTy drops you at cmd as expected (Server 2012 R2 host). When you run 'PowerShell.exe', it launches within the session, but commands such as 'dir' fail to produce any output.

**Comment by manojampalam** [comment]
https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples

You'll need to launch powershell as "Powershell.exe -File -"

(you may need to "Enter" twice for some commands to return output. This is a known issue.)

**Comment by tseward** [comment]
Thanks, that worked.
