### ISSUE TITLE
support for powershell credentials

### ISSUE THREAD

**Issue by ebmarquez** [PowerShell/Win32-OpenSSH#120]
Does this project have PowerShell credentials on the roadmap.  This would make it easier to support ssh in scripts without having to watch for a password prompt.  Use get-credential to send a password to ssh in a secure method.

**Comment by discodance1** [comment]
powershell via openssh does not support popups / interactive session 
When connecting to a constrained end point via -credential, powershell over openssh hangs and event log shows this error:
Application popup: powershell.exe - System Warning : Unknown Hard Error

**Comment by maertendMSFT** [comment]
We recommend using [PowerShell Secret Management Module](https://devblogs.microsoft.com/powershell/secrets-management-development-release/)
