### ISSUE TITLE
Subsystem line specifies -NoLogo and -NoProfile but I see both upon connection via ssh

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/Win32-OpenSSH#1200]
**"OpenSSH for Windows" version**
 `7.6.1.0`
 
**Server OperatingSystem**
N/A

**Client OperatingSystem**
`Windows 10 Enterprise'

**What is failing**
The PC running sshd has this in the sshd_config file:
```
Subsystem       powershell      C:/Program Files/PowerShell/6-preview/pwsh.exe -sshs -NoLogo -NoProfile
```

**Expected output**
When I connect with SSH, I don't not expect to see the PowerShell logo nor do I expect to process the user's PowerShell profile on that machine. Yet it does both.

**Actual output**
This is from my test PC (also Windows 10 - Insiders):

![image](https://user-images.githubusercontent.com/5177512/42002970-75de662e-7a26-11e8-9903-348b50cb5634.png)

I can see the logo and in order and it is telling me it has processed profile scripts.  What gives?

**Comment by gayantd** [comment]
Where do you have below entry ? In client or server ?
Subsystem       powershell      C:/Program Files/PowerShell/6-preview/pwsh.exe -sshs -NoLogo -NoProfile

Did you add Powershell as your default shell in registry ? If yes, try removing that.

**Comment by rkeithhill** [comment]
It is on the server side - a Windows 10 1803 system with the Chocolatey pkg (openssh 7.6.1.1) installed.  I needed the release after the one that ships in 1803.  I didn't directly add anything to the registry but I did run the `install-sshd.ps1` script.  Did that put something in the registry? Also, what is the registry path I should be looking at?

**Comment by gayantd** [comment]
Here is the registry path:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH\DefaultShell
What is the value assigned to DefaultShell ?

**Comment by rkeithhill** [comment]
There is no regkey called `DefaultShell` at this path.  Only an `Agent` key.

**Comment by manojampalam** [comment]
Can you double check that your session process on your server does have the complete command line:
 C:/Program Files/PowerShell/6-preview/pwsh.exe -sshs -NoLogo -NoProfile


You can the command line on task manager (by selecting command line column)

**Comment by rkeithhill** [comment]
OK just now noticed that the "Logo" I get in this SSH session if for "Windows PowerShell" - see image in the original post above.  Hmm... How is Windows PowerShell getting executed here instead of PS Core.  

None of the pwsh.exe or powershell.exe process has any command-line parameters when I'm SSH'd into this system.
```
06-29 18:18:31 7> gps powershell,pwsh -ea 0 | % {Get-NtProcess $_.id} | % CommandLine
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
```
I'm only running one Windows PowerShell and that is the first entry above, the second one is running in session 0.  I suspect this is what is being run.  Indeed that is the case.  The $pid in the SSH session corresponds to this process:
```
SessionId                : 0
ProcessId                : 15608
ParentProcessId          : 16264
PebAddress               : 913153015808
ImageBaseAddress         : 140698001408000
ExitStatus               : 259
CommandLine              : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
FullPath                 : \Device\HarddiskVolume1\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
DepStatus                : NtApiDotNet.ProcessDepStatus
User                     : S-1-5-21-1876727327-1672651232-3010941439-28353
Mitigations              : NtApiDotNet.NtProcessMitigations
ExtendedFlags            : None
HasDebugPort             : False
HandleCount              : 629
BreakOnTermination       : False
DebugFlags               : 1
ExecuteFlags             : 13
IoPriority               : 2
Cookie                   : -663243975
OwnerProcessId           : 25433
WindowTitle              : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
WindowFlags              : 0
SubsystemType            : Win32
Wow64                    : False
Is64Bit                  : True
IsChildProcessRestricted : False
IsDeleting               : False
Protection               : NtApiDotNet.PsProtection
ImageInformation         : NtApiDotNet.SectionImageInformation
LUIDDeviceMapsEnabled    : True
GrantedAccess            : AllAccess
GrantedAccessMask        : 2097151
SecurityDescriptor       : O:BAG:DUD:(A;;0x1fffff;;;BA)(A;;0x1fffff;;;SY)(A;;0x121411;;;S-1-5-5-0-57399869)S:AI(ML;;NWN
                           R;;;HI)
Sddl                     : O:BAG:DUD:(A;;0x1fffff;;;BA)(A;;0x1fffff;;;SY)(A;;0x121411;;;S-1-5-5-0-57399869)S:AI(ML;;NWN
                           R;;;HI)
Handle                   : NtApiDotNet.SafeKernelObjectHandle
NtTypeName               : Process
NtType                   : Name = Process - Index = 7
Name                     : powershell.exe
CanSynchronize           : True
CreationTime             : 12/31/1600 5:00:00 PM
Inherit                  : False
ProtectFromClose         : False
Address                  : 0
```
This is the process tree that ProcExp shows:
![image](https://user-images.githubusercontent.com/5177512/42119513-1f12d712-7bca-11e8-9d72-586e98a360f3.png)

I do have the 7.6.1.0 version at that location:
```
06-29 18:26:24 11> gcm sshd

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     sshd.exe                                           7.6.1.0    C:\Program Files\OpenSSH\sshd.exe
```
The C:\ProgramData\ssh\sshd.pid file shows pid 5040 which corresponds the ProcExp info. But it is odd that the last entry in C:\ProgramData\ssh\logs\sshd.log is from several days ago even though I initiated a SSH session a few minutes ago.

Everything in my sshd_config file is commented out except these two lines:
```
Subsystem       sftp    sftp-server.exe
Subsystem       powershell      C:/Program Files/PowerShell/6-preview/pwsh.exe -sshs -NoLogo -NoProfile
```

**Comment by rkeithhill** [comment]
Oh wait a sec, there is a `DefaultShell` registry "value" under that reg key and it does point to powershell.exe - specifically `C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe`.  Sorry, I was looking for a reg key by that name.   

Where did that come from?  At one point, I had installed the `OpenSSH Client - Beta` Windows optional feature.  Did that create that reg val?  

If I remove that reg val and restart sshd, when I ssh into the box I now get a CMD prompt.  How come it is not using the subsystem (pwsh) specified in the sshd_config file?

**Comment by gayantd** [comment]
As I know you will set it only if runs below at Server:
New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force
page: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by rkeithhill** [comment]
@gayantd Thanks!!  I think I've figured out that the registry entries referred to by that Wiki dictate what shell is used when you `SSH` into the Windows box.  The sshd_config `subsystem` setting controls what version of PowerShell is used when you use PS Remoting over SSH to access the Windows box.


Now if I could just figure out if there's a way to specify parameters (ie -NoLogo) to the `DefaultShell` configured in the registry.  I'll poke around the Wiki but if anyone knows, I'm all ears.  :-)

**Comment by gayantd** [comment]
Great ! Good luck Keith !

**Comment by Goblenus** [comment]
@rkeithhill Hello :) There was a long time, but I have a question. Did you find a way how to specify "-NoLogo" parameter?

**Comment by rkeithhill** [comment]
@Goblenus Not yet.  😞

**Comment by Goblenus** [comment]
@rkeithhill ok... I did it this way:

Make a bat file and place it C:\1\1.bat
``` bat
@echo off
powershell.exe -nologo
``` 

Change `DefaultShell` to `C:\1\1.bat`

And you got PS with `-nologo` param :) But this is really bad way...
