### ISSUE TITLE
Unable to connect using Key from Windows 10 to Windows 2008 R2

### ISSUE THREAD

**Issue by gayantd** [PowerShell/Win32-OpenSSH#1201]
**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
Result : Get-Item : Cannot bind argument to parameter 'Path' because it is null.
 
**Server OperatingSystem**
 `Windows Server 2008 R2 Datacenter`

**Client OperatingSystem**
Windows 10 Enterprise

**What is failing**
Connection to server

I got below error in server side logs :
7820 2018-06-28 11:26:25.200 debug3: Failed to open file:C:\\Users\\irdtds\\.ssh/authorized_keys error:13
7820 2018-06-28 11:26:25.200 debug1: Could not open authorized keys 'C:\\Users\\irdtds\\.ssh/authorized_keys': Permission denied
7820 2018-06-28 11:26:25.200 debug3: mm_answer_keyallowed: publickey authentication test: ECDSA key is not allowed
7820 2018-06-28 11:26:25.200 Failed publickey for irdtds from 101.xx.xx.xx port 5xxxx ssh2: ECDSA SHA256:2gH+xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Expected output**
Successful login

**Actual output**
Unable to login
![image](https://user-images.githubusercontent.com/40220815/42016143-8653d4de-7afe-11e8-8245-2d37a5e89602.png)
![image](https://user-images.githubusercontent.com/40220815/42016304-30978530-7aff-11e8-800c-f57bced8a29d.png)

**Comment by bingbing8** [comment]
gayantd, can you check the ACL of C:\Users\irdtds\.ssh/authorized_key?  You can run ```FixHostFilePermissions.ps1``` on the server machine to fix the permissions on host.
Normally It should look like:
```
(Get-Acl C:\Users\irdtds\.ssh\authorized_keys).Access

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : NT AUTHORITY\SYSTEM
IsInherited       : True
InheritanceFlags  : None
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : BUILTIN\Administrators
IsInherited       : True
InheritanceFlags  : None
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : irdtds
IsInherited       : True
InheritanceFlags  : None
PropagationFlags  : None
```

**Comment by gayantd** [comment]
@bingbing8 , Thanks a lot for the reply. I do need to set this SFTP connection and have deadline. Appreciate your help.

Please find results :
PS C:\Users\Gayan.Dissanayake> (Get-Acl C:\Users\irdtds\.ssh\authorized_keys).Access

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : NT AUTHORITY\SYSTEM
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : BUILTIN\Administrators
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : IFINDDEVFS01\irdtds
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

Here is the result from FixHostFilePermissions.ps1. But it didn't check "C:\Users\irdtds\.ssh\authorized_keys" folder :(

![image](https://user-images.githubusercontent.com/40220815/42063282-fe57c0f4-7b84-11e8-8872-58adcff12036.png)

**Comment by bingbing8** [comment]
@gayantd, FixHostPermissions.ps1 only checks the authorized_keys under profile folders. If you don't see it check your file, which might means that location is not one of the profile folder.
![image](https://user-images.githubusercontent.com/12284203/42072356-e41a57ee-7b14-11e8-9ae9-d54bb75c4b21.png)

**Comment by bingbing8** [comment]
Also which version of openssh do you use?

**Comment by gayantd** [comment]
Hi @bingbing8 , I created authorized_keys folder instead of a file. #1180
So that issue resolved and I can login with ssh.exe.
But still sftp.exe failing with below error :

![image](https://user-images.githubusercontent.com/40220815/42072940-94495c1c-7bb7-11e8-8134-318a6e294c0c.png)

Got this with WinSCP : 
![image](https://user-images.githubusercontent.com/40220815/42073100-96253960-7bb8-11e8-91ab-ad7c00425418.png)

Server logs :  
5576 2018-06-29 06:06:32.228 debug1: Executing command: "C:\\Windows\\system32\\cmd.exe" /c C:\\Program Files\\OpenSSH-Win64\\sftp-server.exe
5576 2018-06-29 06:06:32.228 debug2: fd 4 setting TCP_NODELAY
5576 2018-06-29 06:06:32.228 debug3: fd 11 is O_NONBLOCK
5576 2018-06-29 06:06:32.228 debug3: fd 10 is O_NONBLOCK
5576 2018-06-29 06:06:32.228 debug3: fd 13 is O_NONBLOCK
5576 2018-06-29 06:06:32.228 debug3: send packet: type 99
5576 2018-06-29 06:06:32.228 debug3: ReadFileEx() ERROR:109, io:0000000000418750
5576 2018-06-29 06:06:32.228 debug2: channel 0: read<=0 rfd 11 len 0
5576 2018-06-29 06:06:32.228 debug2: channel 0: read failed
5576 2018-06-29 06:06:32.228 debug2: channel 0: close_read
5576 2018-06-29 06:06:32.228 debug2: channel 0: input open -> drain
5576 2018-06-29 06:06:32.228 debug2: channel 0: read 101 from efd 13
5576 2018-06-29 06:06:32.228 debug3: channel 0: discard efd
5576 2018-06-29 06:06:32.228 debug2: channel 0: ibuf empty
5576 2018-06-29 06:06:32.228 debug2: channel 0: send eof
5576 2018-06-29 06:06:32.228 debug3: send packet: type 96
5576 2018-06-29 06:06:32.228 debug2: channel 0: input drain -> closed
5576 2018-06-29 06:06:32.228 debug1: Received SIGCHLD.
5576 2018-06-29 06:06:32.228 debug1: session_by_pid: pid 7656
5576 2018-06-29 06:06:32.228 debug1: session_exit_message: session 0 channel 0 pid 7656
5576 2018-06-29 06:06:32.228 debug2: channel 0: request exit-status confirm 0
5576 2018-06-29 06:06:32.228 debug3: send packet: type 98
5576 2018-06-29 06:06:32.228 debug1: session_exit_message: release channel 0
5576 2018-06-29 06:06:32.228 debug2: channel 0: write failed
5576 2018-06-29 06:06:32.228 debug2: channel 0: close_write
5576 2018-06-29 06:06:32.228 debug2: channel 0: send eow
5576 2018-06-29 06:06:32.228 debug2: channel 0: output open -> closed
5576 2018-06-29 06:06:32.228 debug3: ReadFileEx() ERROR:109, io:0000000000456ED0
5576 2018-06-29 06:06:32.228 debug3: read - no more data, io:0000000000456ED0
5576 2018-06-29 06:06:32.228 debug2: channel 0: read 0 from efd 13
5576 2018-06-29 06:06:32.228 debug2: channel 0: closing read-efd 13
5576 2018-06-29 06:06:32.228 debug2: channel 0: send close
5576 2018-06-29 06:06:32.228 debug3: send packet: type 97
5576 2018-06-29 06:06:32.228 debug3: channel 0: will not send data after close
5576 2018-06-29 06:06:32.228 debug2: notify_done: reading
5576 2018-06-29 06:06:32.228 debug3: channel 0: will not send data after close
5576 2018-06-29 06:06:32.368 debug3: channel 0: will not send data after close
5576 2018-06-29 06:06:32.368 debug3: WSARecv - WSARecv() ERROR: io:000000000040CF40 10054
5576 2018-06-29 06:06:32.368 debug3: recv - from CB ERROR:108, io:000000000040CF40
5576 2018-06-29 06:06:32.368 Read error from remote host 101.98.84.53 port 54979: Unknown error
5576 2018-06-29 06:06:32.368 debug1: do_cleanup
4912 2018-06-29 06:06:32.384 debug3: mm_request_receive entering
4912 2018-06-29 06:06:32.384 debug1: do_cleanup

**Comment by bingbing8** [comment]
@bagajjal, I see this line. the path to sftp-server.exe is not quoted. I believe we fixed it, but not sure it is fixed in the 7.7.0.1.
5576 2018-06-29 06:06:32.228 debug1: Executing command: "C:\Windows\system32\cmd.exe" /c C:\Program Files\OpenSSH-Win64\sftp-server.exe

**Comment by bingbing8** [comment]
@gayantd, i believe your version of openssh is [7.7.0.0](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.7.0.0p1-Beta). version [7.7.1.0](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.7.1.0p1-Beta) has the fix for #1164

**Comment by gayantd** [comment]
@bingbing8 , Thanks for quick response 
I use version : OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.4

**Comment by bingbing8** [comment]
Please install version [7.7.1.0](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.7.1.0p1-Beta), or use the workaround mentioned in #1164

**Comment by gayantd** [comment]
I will try. But not sure if it is related with mine. Because I added below line to sshd_config at server.
Subsystem	sftp	"C:\Program Files\OpenSSH-Win64\sftp-server.exe"

And it picked from there.  logs:
1612 2018-06-29 09:50:07.560 debug1: Executing command: "C:\\Windows\\system32\\cmd.exe" /c C:\\Program Files\\OpenSSH-Win64\\sftp-server.exe

**Comment by bingbing8** [comment]
@gayantd, yes. It is related. The path to sftp-server.exe should be quoted. log should look like:
1612 2018-06-29 09:50:07.560 debug1: Executing command: "C:\Windows\system32\cmd.exe" /c "C:\Program Files\OpenSSH-Win64\sftp-server.exe"

workaround is to Install OpenSSH in a folder with no white space. Ex c:\openssh

**Comment by gayantd** [comment]
I will do right away. Should I uninstall and install services back or replace binary would enough ?

One extra question: Do I have to install OpenSSH in client machine ?

**Comment by bingbing8** [comment]
replacing binaries is enough.
Regarding openssh client, it depends which Windows 10 build you have. On latest release of windows build 1803, it already has built in openssh client installed. If you have older windows 10 build, you might need to either enable OpenSSH (Beta) optional feature for build 1709, or install openssh client from git hub (on older builds).

**Comment by gayantd** [comment]
I think I don't have any:
![image](https://user-images.githubusercontent.com/40220815/42074320-bffe3a6e-7bbf-11e8-888d-53f760f898a6.png)

But I was able to login using ssh.exe with using Binary extraction only. No SSHD or Agent service in my client machine. So do I have to install it for sftp.exe ? Which service should be running in my client ?
I don't want to save my Private key for SSO.
Thanks !

**Comment by bingbing8** [comment]
If you don't need to save private key for SSO,  you don't need to install ssh-agent service. sshd.exe is server only binary, you don't need it on client. Binary extraction for other files is enough.
Client binaries are: ssh.exe, scp.exe, sftp.exe, ssh-agent.exe, ssh-add.exe, ssh-keygen.exe, ssh-keyscan.exe, libcrypto.dll

**Comment by gayantd** [comment]
Gotcha. I replaced Binaries. But didn't work because sshd_config file had relative path specified. So update to default as below:
Subsystem	sftp	sftp-server.exe

Got logs:
7656 2018-06-29 10:49:44.780 debug1: Executing command: "c:\\windows\\system32\\cmd.exe" /c "C:\\Program Files\\OpenSSH-Win64\\sftp-server.exe"

Boom!!  I am in !!!
I highly appreciate your help and impressed with your knowledge.

One question : This give me access to all folders and files in server. But I don't want that. I want client has restricted access to only a folder. How can I do that ?

Thanks !

**Comment by bingbing8** [comment]
I believe ChrootDirectory in [sshd_confg](https://github.com/PowerShell/Win32-OpenSSH/wiki/sshd_config) is what you want.
Please follow [sshd_config](https://github.com/PowerShell/Win32-OpenSSH/wiki/sshd_config) to set it up.

**Comment by gayantd** [comment]
I just tried by specifying path. Nice ! It did work. I will explore more regarding permissions...etc
Thanks heaps !!
We can close this Yanbing. You are a Legend !!

**Comment by bagajjal** [comment]
@gayantd - fyi, ChrootDirectory restricts folder access only in sftp, scp. If you use ssh then folder restrictions will not apply. Windows OS doesn't have inbuilt ChrootDirectory implemention.
Incase of sftp, scp, our code first checks the folder restrictions (if ChrootDirectory is configured) before executing command using WIN32 APIs. Incase of ssh, each user character is fed directly to console so we don't have a way to restrict user to a folder.

**Comment by gayantd** [comment]
Thanks for that info ! It is valuable.  Because I have to pass details to third party to access our production servers. How can I enable only sftp then ? Is there a way to disable ssh and enable only sftp ?

**Comment by bagajjal** [comment]
1) Add these lines to c:\programdata\ssh\sshd_config 

Match User *
    ForceCommand internal-sftp
    ChrootDirectory  <restricted_directory>

2) Restart sshd (net stop sshd, net start sshd)

3) Validate both sftp, ssh.

**Comment by gayantd** [comment]
Awesome. I will try these on Monday and let you know guys.
Is there a space after "Match User" and asterisk ?

Best Regards
Gayan Dissanayake
(+64 221352218)

**Comment by bagajjal** [comment]
Yes.. configuration is same between UNIX, windows.

**Comment by gayantd** [comment]
@bagajjal yes I did check. 
Awesome ! It is working as expected. Cheers

**Comment by markm75** [comment]
Confused.. for win 2016, do i run / modify one of the above referenced ps1 scripts to secure a user to his home directory and not allow browsing outside of that location or is it more involved?

**Comment by bagajjal** [comment]
You don't need to run any ps1 scripts.
It's a configuration change.
1) Add these lines to c:\programdata\ssh\sshd_config
Match User *
   ForceCommand internal-sftp
   ChrootDirectory <restricted_directory>
2) Restart sshd (net stop sshd, net start sshd)
3) Validate both sftp, ssh.

**FYI, CHROOT only works for SFTP, SCP sessions but not for SSH.**
The above config restricts the user to a SFTP session and jails the user.

**Comment by markm75** [comment]
Thanks this might be what i'm looking for.. but by jails the user/restricts to a session, you mean restricts to one session? (should be fine)

What about a rare case where another user needs restricted but able to see the other users folders (i guess i'd just restrict them one level higher then right?)

Thanks for this, will give it a shot

**Comment by bagajjal** [comment]
In the above config, it applies to all users (as we specified *). 

But, you can use Match User / Match Group to restrict individual / group of users to different location.

If you are using a domain user then you need to specify like
    Match User short_domain_name\\user_name (Ex - Match User contoso\user, where FQDN is contoso.microsoft.com)

If you are using a workgroup / local user then you need to specify like
    Match User <username>

**Comment by markm75** [comment]
I tried to just add this to the default sshd_config in program data (at the very end of the file)

Match User *
ForceCommand internal-sftp
ChrootDirectory /D:/Data/FTProot/localuser/test/

But when i try one of my iis ftp logins it fails to login.. if i remove this code from sshd_config and retest, i can log in with no issue..

What might I be missing here?

Thanks

**Comment by manojampalam** [comment]
Remove / at ChrootDirectory and retry
    ChrootDirectory D:/Data/FTProot/localuser/test/

**Comment by markm75** [comment]
Thanks.. i made it further but it said no such file... however.. 
Changing to this:
D:\Data\FTProot\localuser\test\  (worked)

**Comment by markm75** [comment]
I also went ahead and did this per user locking them.. in one case we have a user that is locked to the root of these other ftp users home folders (so they can access them), but is there a way to not only do this but make the default starting path be one of those other folders (they can then drill backward and go into other folders as needed)..?

**Comment by manojampalam** [comment]
There is not. Chroot will be their starting directory.
