### ISSUE TITLE
vi on Linux turns console text blue

### ISSUE THREAD

**Issue by p0lar-bear** [PowerShell/Win32-OpenSSH#1203]
**"OpenSSH for Windows" version**
(Will fill in when I get home later, sorry! Leaving command here for reference)
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
CentOS 7.5.1804

**Client OperatingSystem**
Windows 10
(Will fill in with more complete info when I get home later, sorry! Leaving command here for reference)
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**What is failing**
When executing `vi` for a new file or seemingly at random on a fresh install of CentOS 7, the console text default color seems to be changed to blue, i.e. all text not colored by syntax highlighting in `vi` is blue, and any text the console generates henceforth which isn't preceded by an ANSI terminal code is blue. This state persists until the console window is closed.

This does not happen when the CentOS machine is used directly, e.g. via a Hyper-V connection window. Unsure if this occurs with other OS versions/distros, other `vi` versions, or other "flavors" of `vi` such as `vim`.

I am aware that the wiki explains the caveat that the client has outstanding issues with interactive applications such as `vi`, but I figured it couldn't hurt to point one specific one out that I didn't see an issue for before.

**Expected output**
Console to retain its default text color after `vi` is launched on the remote CentOS machine.

**Actual output**
![blue console text](https://i.stack.imgur.com/z1ivL.png)

**Comment by bagajjal** [comment]
Windows openssh client uses console support (conhost.exe) for parsing the incoming ANSI stream. Looks like the latest windows OS has fixed it. I verified this on windows Version 10.0.17134.112.

**Comment by soul4soul** [comment]
Out of the dozen or so times I have used vi this has happened once. What is very annoying is that the color change persists after exiting the ssh session. Ultimately I restarted the PS console.

**Client Info**
SSH Client 7.6.0.0
Window 10 Pro 1803 - 17134.345

**Server Info**
OpenSSH_7.7p1, OpenSSL 1.1.0h-fips  27 Mar 2018
`Fedora 28 4.16.3-301.fc28.x86_64 #1 SMP Mon Apr 23 21:59:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by bagajjal** [comment]
Please try the new windows 10 fall update (https://support.microsoft.com/en-us/help/4464619)

**Comment by bagajjal** [comment]
fyi, Just realized the windows 10 fall update is paused because of some known issues.
Please note that bunch of console rendering issues were resolved in the latest windows 10 fall updates.

**Comment by mcarden** [comment]
This remains an issue for me:

Edition: Windows 10 Enterprise
Version: 1803
Installed on: 4/04/2019
OS build: 17134.1550

**Comment by dmaziuk** [comment]
Still happening on W11 23H2 SSH'ing to RHEL9.
