### ISSUE TITLE
sshd cannot find the Git bash default shell

### ISSUE THREAD

**Issue by ksalman** [PowerShell/Win32-OpenSSH#1204]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
7.7.1.0
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 7 Enterprise

**Client OperatingSystem**
Debian 8

**What is failing**
I am trying to set my default shell to Git Bash which, I think, is the same as cygwin bash. I set the options as described here https://user-images.githubusercontent.com/23668037/32015013-9e644cee-b974-11e7-8375-bf3d50f596df.png

**Expected output**
I am able to login.

**Actual output**
I am not able to login. Here is my shell, with the -c option.  
![image](https://user-images.githubusercontent.com/1268871/42121556-fe7b2cfe-7be5-11e8-862b-3294e273fdb4.png)
I set the options as described here https://user-images.githubusercontent.com/23668037/32015013-9e644cee-b974-11e7-8375-bf3d50f596df.png

![image](https://user-images.githubusercontent.com/1268871/42121563-3b540ff6-7be6-11e8-8373-a500879dd2b3.png)

Running sshd in debug mode, it cannot find the shell specified in the registry.
![image](https://user-images.githubusercontent.com/1268871/42121573-68e49c4c-7be6-11e8-8181-ce36b1bb3056.png)

The shell exists and works fine on the local computer
![image](https://user-images.githubusercontent.com/1268871/42121591-cb0a018c-7be6-11e8-8340-659096732ae8.png)

**Comment by gayantd** [comment]
Did you notice your server registry DefaultShell value with double quotes ? Please try removing it. 
Cheers

**Comment by ksalman** [comment]
Ugh, I didn't realize that would be a problem. I added the double quotes because there's a space =). Evidently they are not needed. Thank you.
