### ISSUE TITLE
Failure installing OpenSSH native

### ISSUE THREAD

**Issue by angelog0** [PowerShell/Win32-OpenSSH#1205]
It seems I wrote the wrong mailing list: [#3340](https://github.com/Microsoft/WSL/issues/3340).

Thanks.

**Comment by gayantd** [comment]
Can you please explain the issue here ?

**Comment by angelog0** [comment]
Just trying @DarthSpock suggestion in [#3325](https://github.com/Microsoft/WSL/issues/3325), I tried to install the OpenSSH server native following one of the tutorials found on the WEB. For example this [tutorial1](https://winaero.com/blog/enable-openssh-server-windows-10) which also contains this reference [tutorial2](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709). Both refer to the beta version of OpenSSH sever but now (in April update) we know it is out of beta.

The problems arise when I try (for example, from [tutorial2](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709)) to start `ssh-agent` and/or generate `ssh-keygen`. 

Is there a tutorial for installation and usage of this OpenSSH server not in beta? If not, then you/someone should write it. 

This is the output from PS as administrator:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. Tutti i diritti sono riservati.

PS C:\WINDOWS\system32> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'


Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed

Name  : OpenSSH.Server~~~~0.0.1.0
State : Installed



PS C:\WINDOWS\system32> Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0


Path          :
Online        : True
RestartNeeded : False



PS C:\WINDOWS\system32> cd C:\Windows\System32\OpenSSH
PS C:\Windows\System32\OpenSSH> Start-Service ssh-agent
Start-Service : Impossibile avviare il servizio 'OpenSSH Authentication Agent (ssh-agent)' a causa del seguente
errore: Impossibile avviare il servizio ssh-agent sul computer '.'.
In riga:1 car:1
+ Start-Service ssh-agent
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

PS C:\Windows\System32\OpenSSH> .\ssh-keygen -A
C:\Windows\System32\OpenSSH\ssh-keygen.exe: generating new host keys: RSA Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_rsa_key.HXbwLr0RNp: No such file or directory
C:\Windows\System32\OpenSSH\ssh-keygen.exe: generating new host keys: DSA Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_dsa_key.q6HrKziqxp: No such file or directory
C:\Windows\System32\OpenSSH\ssh-keygen.exe: generating new host keys: ECDSA Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_ecdsa_key.nF7St2spR9: No such file or directory
C:\Windows\System32\OpenSSH\ssh-keygen.exe: generating new host keys: ED25519 Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_ed25519_key.x6irJqIWEH: No such file or directory
PS C:\Windows\System32\OpenSSH> dir


    Directory: C:\Windows\System32\OpenSSH


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/03/2018     19:20         343552 scp.exe
-a----       01/05/2018     01:16         355840 sftp-server.exe
-a----       10/03/2018     19:20         408064 sftp.exe
-a----       10/03/2018     19:20         531968 ssh-add.exe
-a----       10/03/2018     19:20         495616 ssh-agent.exe
-a----       10/03/2018     19:20         657920 ssh-keygen.exe
-a----       10/03/2018     19:20         594944 ssh-keyscan.exe
-a----       01/05/2018     01:16         154624 ssh-shellhost.exe
-a----       10/03/2018     19:20         894464 ssh.exe
-a----       20/05/2018     10:26         970240 sshd.exe
-a----       01/05/2018     01:16           2143 sshd_config_default


PS C:\Windows\System32\OpenSSH>
```

**Comment by manojampalam** [comment]
ssh-agent is disabled by default in April update. Can you explicitly enable it (you need to be an admin to do it)?

As for host keys, they should be automatically generated when starting sshd service.

**Comment by angelog0** [comment]
@manojampalam please, give a detailed recipe.. Obviously I am the administrator and can use PS or CMD... you should also update some [tutorial](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709)..

**Comment by manojampalam** [comment]
You could do the following to set ssh-agent back to "auto" on-demand start:
`sc.exe config sshd start= auto`

@JKeithB we need to do a blog for the OpenSSH in April update (similar to the one we did for Beta in [Fall update](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/)

**Comment by maertendMSFT** [comment]
Docs are available here: https://docs.microsoft.com/windows-server/administration/openssh/openssh_install_firstuse
