### ISSUE TITLE
building latest source on Windows.

### ISSUE THREAD

**Issue by tsd64** [PowerShell/Win32-OpenSSH#1207]
**"OpenSSH for Windows" version** : Win32-OpenSSH-7.7.0.0p1-Beta 
**Server OperatingSystem** : Windows 7sp1
***What is failing**
What openssl sdk is required to build the latest OpenSSH source?  There are too many unconditionally included headers to remove it, and if it was possible too many too many files unconditionally require it.

**Comment by manojampalam** [comment]
Did you see https://github.com/PowerShell/Win32-OpenSSH/wiki/Building-OpenSSH-for-Windows-(using-LibreSSL-crypto) ?
