### ISSUE TITLE
unbounded queue in shell-host-- may potentially use up the memory and crash the shell-host 

### ISSUE THREAD

**Issue by bingbing8** [PowerShell/Win32-OpenSSH#1208]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
7.7.1.0
 
**Server OperatingSystem**
Windows 10

**Client OperatingSystem**
Windows 10

**What is failing**
for each Windows Console event, ssh-shellhost allocated memory and insert it in an unbounded queue with function QueueEvent.

**Expected output**
bounded memory

**Actual output**
This may potentially use up the memory and crash the shell host

**Comment by maertendMSFT** [comment]
We have no plans to modify the shell host in the future.
