### ISSUE TITLE
Docker Windows documentation without relying on SSH installed with Git

### ISSUE THREAD

**Issue by jpierson** [PowerShell/Win32-OpenSSH#121]
Following through the Installation guide for [Docker on Windows](https://docs.docker.com/engine/installation/windows/) there is a step to create a test machine which fails when not running through the [Docker Quickstart Terminal](https://docs.docker.com/engine/installation/windows/#using-the-docker-quickstart-terminal) such as when using CMD or PowerShell without first ensuring that `c:\Program Files (x86)\Git\bin` is added to the `PATH` in order to reach `ssh.exe`. What would be nice is that if this tutorial could be followed without the dependency on ssh.exe installed along with Git.

Below is an example of the output I get when running the instructions to create the my-default machine in PowerShell without adding Git's copy of `ssh.exe` to my `PATH`.

```
PS docker-test> docker-machine create --driver virtualbox my-default
Running pre-create checks...
Creating machine...
(my-default) Copying C:\Users\jeff\.docker\machine\cache\boot2docker.iso to C:\Users\jeff\.docker\machine\machines\my-default\boot2docker.iso...
(my-default) Creating VirtualBox VM...
(my-default) Creating SSH key...
(my-default) Starting the VM...
(my-default) Check network to re-create if needed...
(my-default) Waiting for an IP...
Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

This issue is especially of concern because with having Win32-OpenSSH installed I had to deviate from the installation instructions for Docker because they advised _appending_ the `c:\Program Files (x86)\Git\bin` path meaning that the Win32-OpenSSH copy of ssh.exe is still resolved first due to or in which the paths are looked up. In order to get things to work I had to run the following command intsead which essentially overrides to use of Win32-OpenSSH with the git copy of ssh.exe.

``` PowerShell
$Env:Path = "c:\Program Files (x86)\Git\bin;${Env:Path}"
```

I could be completely off base but perhaps this and other similar tutorials that involve SSH could be good test cases or milestones for the the _Win32-OpenSSH_ project similar to how several open source projects on GitHub were used to prove the new Roslyn complier for C#.

**Comment by maertendMSFT** [comment]
This is an external issue for Docker, closing on our side
