### ISSUE TITLE
Backup my private keys

### ISSUE THREAD

**Issue by fabwu** [PowerShell/Win32-OpenSSH#1214]
[This blog post](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/) describes how to securely store a private key in the Windows security context with the `ssh-agent` command and then delete the corresponding private key from the disk.

I'm a bit afraid if my computer crashes that all my private keys are lost because I removed the key files. I currently backup my files with File History. Does the File History backup include the Windows security context respectively the private keys for my ssh connections?

(I apologize that this is not exactly an issue but I wasn't sure if I should ask this question on SO or here so just close this issue if it's in the wrong place)

**Comment by manojampalam** [comment]
Not sure what File History backup does, but unless it explicitly calls out, I don't believe it does any encryption of backup.

You could simply passphrase protect your private keys (and not delete them once registered with agent). 

@joeyaiello can you fix the blog post and recommend creating passphrase protected private keys in the first place ?

**Comment by Magneticdud** [comment]
File history is not a backup, it's more like a "safety net"

If your computer crashes, your private keys are still lost, as they're not backed up

> File History only backs up copies of files that are in the Documents, Music, Pictures, Videos, and Desktop folders and the OneDrive files available offline on your PC.

by default it doesn't does a backup of the private key

and if you backup the private keys with it... it's a plain copy, unencrypted. Anyone with access to your backup files **would have unlimited access to your server**. It's the digital equivalent of writing down a password on a post it on the monitor.

If you strongly need to backup the private key, you should use a secure way, like as an attachment to a KeePass entry (as it equals to a password)

Or... if lost, just recreate it and reauthorize the new one on the server.

**Comment by fabwu** [comment]
If I use a passphrase it's not a plaintext copy so you still need a password to access a server. Anyway, I used the method you proposed and backed up my private key in a password manager. I also removed my private key from my computer after I added it to ssh-agent.

**Comment by KalleOlaviNiemitalo** [comment]
[The current version of ssh-agent](https://github.com/PowerShell/openssh-portable/tree/v7.9.0.0/contrib/win32/win32compat/ssh-agent) stores private keys under the user's `HKEY_CURRENT_USER\SOFTWARE\OpenSSH\Agent\Keys`. It secures the keys in two ways:

- By giving `HKEY_CURRENT_USER\SOFTWARE\OpenSSH` an ACL that grants access only to SYSTEM and Administrators.
- By encrypting the key blob using [CryptProtectData](https://docs.microsoft.com/en-us/windows/desktop/api/dpapi/nf-dpapi-cryptprotectdata) while impersonating the user.

This encryption does not protect at all against the user who owns the keys, as they can just call CryptUnprotectData themselves, if they can read the Registry value and haven't lost their DPAPI master key.

**Comment by maertendMSFT** [comment]
The users should always backup their keys offline
