### ISSUE TITLE
Lock user to home ftp folder possible on windows server?

### ISSUE THREAD

**Issue by markm75** [PowerShell/Win32-OpenSSH#1215]
Been reading through on here, not seeing the final answer on this, but has anyone found a way to lock/restrict an sftp/openssh user to their home folder?

**Comment by bagajjal** [comment]
Go over this thread,
https://github.com/PowerShell/Win32-OpenSSH/issues/1201

**Comment by manojampalam** [comment]
https://github.com/PowerShell/Win32-OpenSSH/wiki/sshd_config#chrootdirectory
