### ISSUE TITLE
Login to Domain Controller fails with Pubkey Authentication

### ISSUE THREAD

**Issue by umemoni256** [PowerShell/Win32-OpenSSH#1216]
**"OpenSSH for Windows" version**
v7.7.1.0p1-Beta
 
**Server OperatingSystem**
Windows Server 2012 R2 Standard

**Client OperatingSystem**
CentOS 7

**What is failing**
Login fails.

**Expected output**
Successful login

**Actual output**
"Connection to 192.168.103.100 port 22: Broken pipe"

** Additional note **
Without the authorized_keys file in the user profile directory, login with password is possible.

[sshd-debug3.log](https://github.com/PowerShell/Win32-OpenSSH/files/2213988/sshd-debug3.log)
[ssh-vvv.log](https://github.com/PowerShell/Win32-OpenSSH/files/2213989/ssh-vvv.log)

**Comment by manojampalam** [comment]
@nomorefood is this the same issue in https://github.com/PowerShell/Win32-OpenSSH/issues/1213

**Comment by NoMoreFood** [comment]
@manojampalam Very possibly.  

@umemoni256 Does the account in question have a UPN explicitly defined on the account?

**Comment by umemoni256** [comment]
Even though I scrolled through the existing issues before opening this one, it seems I missed the #1213. It is indeed the same problem. After setting the UPN as suggested in #1213, everything works as expected.

Thanks!
