### ISSUE TITLE
Wiki instructions fail, GitHub requires TLS 1.2

### ISSUE THREAD

**Issue by jmillxyz** [PowerShell/Win32-OpenSSH#1217]
Operating System: Windows 2012 Server R2
PowerShell Version: 4.0

When running the commands in [this wiki article](https://github.com/PowerShell/Win32-OpenSSH/wiki/How-to-retrieve-links-to-latest-packages), I get the following: 

```
...
PS C:\Users\Administrator> $response=$request.GetResponse()
Exception calling "GetResponse" with "0" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At line:1 char:1
+ $response=$request.GetResponse()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

The reason is that [GitHub requires TLS 1.2](https://www.ssllabs.com/ssltest/analyze.html?d=github.com&s=192.30.253.112&hideResults=on).

Setting the TLS protocol to v1.2 by adding `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` to the beginning of that snippet resolves the error.

**Comment by manojampalam** [comment]
Thanks. Fixed it.
