### ISSUE TITLE
Support TabCompletion and ArrowKeys in default shell. Fix BackSpace issues.

### ISSUE THREAD

**Issue by keithzg** [PowerShell/Win32-OpenSSH#122]
**Host:** 
- Windows 10.0.10586 (Enterprise, 32-bit)
 - win32-openssh 2015.12.22 from Chocolatey (OpenSSH_7.1p1 Microsoft_Win32_port_with_VS Dec 22 2015, OpenSSL 1.0.2d 9 Jul 2015)

**Clients:** 
- *buntu 14.04 64-bit
 - OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6, OpenSSL 1.0.1f 6 Jan 2014
- *buntu 15.10 64-bit
 - OpenSSH_6.9p1 Ubuntu-2ubuntu0.1, OpenSSL 1.0.2d 9 Jul 2015 

With Yakuake, Konsole, and XTerm (tested on both *buntu 14.04 and 15.10), typing something in the prompt and then hitting backspace leaves the visible text unchanged, although it appears to have been received correctly on the host's end:

```
Autobuilds@MERCURY C:\>echo test1234
#pressed backspace 4 times, text appeared to remain the same, then hit enter
test
```
Using LXTerminal, it's nearly the same, but appends a visible 007F character for each backspace (not too surprising, since that's the character actually being sent).

Using PuTTY, backspace works entirely fine, which (combined with issue #57) made me suspect that I could fix this by changing what character code my backspace key sent, and so I went with 8 (ie. \b) and as long as I use that setting, Yakuake works fine.

Meanwhile, trying to edit my commands by navigating them with the arrow keys results in no movement of the cursor, and up/down fails to navigate through command history either. This makes for a rather barebones terminal experience! This is true in PuTTY as well, so I have no obvious clues as to how to fix it, if it's even possible.

Tab completion also fails to work, although I was mostly expecting that.

If this all is to be expected, Linux users should be informed visibly (either how to fix it entirely, or what known caveats exist compared to a 'normal' session even compared to a local cmd.exe instance), since it was quite a surprise to me! And judging from issue #57, OSX users will stumble in the same way---I'm creating this as a separate issue due to @voltagex's [comment](https://github.com/PowerShell/Win32-OpenSSH/issues/57#issuecomment-184580655) in #57 mentioning to a Linux user that their issue probably required a different case, but my specific gripes here seem much more close in character.

**Comment by voltagex** [comment]
Just a thought - you may be able to disable encryption completely via sshd
and have a look at what is sent across the wire in regards to backspace /
DEL.

One of the reasons for separate issues is the myriad of configurations and
add-ons in use. It'd be nice to reduce this down to a minimum test-case -
but maybe a Microsoft employee is best placed to do that.

**Comment by voltagex** [comment]
Also, do you get the same behaviour on Linux if you drop back to a command
line and use SSH that way? (ctrl-alt-f1, ctrl-alt-f7 to get back)

**Comment by keithzg** [comment]
> Also, do you get the same behaviour on Linux if you drop back to a command
line and use SSH that way? (ctrl-alt-f1, ctrl-alt-f7 to get back)

You mean a VT session? Yeah, I popped over to one and tested, exact same behaviour; backspace doesn't visibly (but does actually) work, arrow keys don't navigate at all, and tab autocompletion is MIA.

> Just a thought - you may be able to disable encryption completely via sshd
and have a look at what is sent across the wire in regards to backspace /
DEL.

Oh, well I mean I know that already, due to fiddling with settings in Yakuake/Konsole. By default it sends \x7f which, as aforementioned, does in fact delete input (considering that upon submit it acts accordingly), and if I change my terminal emulator settings to send \x08 (or \b in other words) it then works both practically _and_ visibly.

This isn't a _huge_ deal since I can switch profiles on a whim in my preferred terminal emulator and have the keyboard settings tied to such profiles, but it's a surprise and a stumbling block that should probably at least be documented, if not automatically worked around or fixed.

The lack of arrow keys for history and moving around command lines is a bigger problem, and tab autocompletion is also hard (but less difficult comparatively) to live without.

**Comment by cwegener** [comment]
:+1:

**Comment by manojampalam** [comment]
Thanks for the details. Arrow key processing is currently disabled in sshd, we were not able to get them to work as desired yet. Tab completion ins't supported yet. We plan on addressing terminal issues some time in May. Please continue to detail any workarounds you find in the mean time.

**Comment by jemiller0** [comment]
Arrow keys in vi don't appear to work either, or in less. It doesn't appear to really be usable at all. I'm using the latest zip file for Win64 that I downloaded yesterday. OpenSSH_7.1p1 Microsoft_Win32_port_with_VS May 30 2016, OpenSSL 1.0.2d 9 Jul 2015
Definitely not ready for prime time. I don't know how much of this is with SSH or with the console window. I'm running Windows 10 and was connecting to an Ubuntu server.

**Comment by dragon788** [comment]
Really hoping you guys can fix the arrow keys as I was really hoping to use this for my vagrant VMs, but I'm going to end up having to open Git bash or a cygwin terminal to perform my vagrant ssh commands until this is fixed.

**Comment by jemiller0** [comment]
On the plus side, maybe they will one day get it working. It's only about 25 or so years overdue. The Command Prompt shell window has needed an overhaul since forever. How Microsoft could have ignored this for so long is beyond me. I hope that it's improved further over the improvements they put into it in Windows 10.

**Comment by dragon788** [comment]
You can use `ctrl+p` and `ctrl+n` in lieu of the up and down arrows and `alt+b` and `alt+f` in lieu of the left and right arrows (jumps back/forward a word). These aren't ideal circumstances, but at least I'm learning more Emacs shortcuts (what most command lines default to) in case I ever have to use something other than the one true editor (Vim).

http://ss64.com/bash/syntax-keyboard.html

**Comment by dragon788** [comment]
Perhaps the new escape codes are to blame when running on Windows 10 like Microsoft really wants you to? https://github.com/rprichard/winpty/issues/82

**Comment by nigurr** [comment]
Is there any update on this issue? This is really annoying and one of the critical functionality

**Comment by EdoBarroso** [comment]
Still not working. I tried connecting into a RHEL and a Slackware host. Backspace works fine, but arrow navigation doesn't

**Comment by manojampalam** [comment]
ssh.exe only supports VT100 sessions. Ensure that your server side shell is configured to process VT100. Reopen if needed.

**Comment by lalomartins** [comment]
**EDIT:** ok, this was missing something along the lines of, “Please try out the Sep-End milestone release. Reopen if needed.” (copied from another bug)

Arrows now work, and escape. It would be nice if alt-something would send esc-something but that would be a separate issue.

**Comment by mikemaccana** [comment]
Thanks @lalomartins ! Also @manojampalam can confirm the new release fixes issues for me.

**Comment by alphaCTzo7G** [comment]
try mobassh.. it works much better compared to OpenSSH right now.. Command completion, colored prompts etc etc..

**Comment by jemiller0** [comment]
I think the latest version of Windows 10 fixes a lot of these kinds of issues. I've been using it with the SSH client that comes with Git and haven't noticed any problems. Before, you couldn't even run something like vi.
