### ISSUE TITLE
Unable to establish SFTP connection, SSH connection works from the same user/host

### ISSUE THREAD

**Issue by velocitystar** [PowerShell/Win32-OpenSSH#1220]
**"OpenSSH for Windows" version**
  - v7.7.1.0p1-Beta
 
**Server OperatingSystem**
   - Windows Server 2008 R2 Enterprise

**Client OperatingSystem**
   - Windows 7 Workstation

**What is failing**

Unable to establish SFTP connection using WinSCP nor SFTP command, SSH connection works fine from the same user/host.

**Expected output**

Connection established.

**Actual output**

##### DEBUG3 from SSHd
3036 2018-07-26 14:55:39.806 debug2: fd 3 setting O_NONBLOCK
3036 2018-07-26 14:55:39.806 debug3: sock_set_v6only: set socket 3 IPV6_V6ONLY
3036 2018-07-26 14:55:39.806 debug1: Bind to port 22 on ::.
3036 2018-07-26 14:55:39.806 Server listening on :: port 22.
3036 2018-07-26 14:55:39.806 debug2: fd 4 setting O_NONBLOCK
3036 2018-07-26 14:55:39.807 debug1: Bind to port 22 on 0.0.0.0.
3036 2018-07-26 14:55:39.807 Server listening on 0.0.0.0 port 22.
3036 2018-07-26 14:55:53.737 debug3: fd 5 is not O_NONBLOCK
3036 2018-07-26 14:55:53.740 debug3: spawning "C:\\SrvApps\\OpenSSH\\sshd.exe" "-R"
3036 2018-07-26 14:55:53.741 debug3: send_rexec_state: entering fd = 8 config len 190
3036 2018-07-26 14:55:53.741 debug3: ssh_msg_send: type 0
3036 2018-07-26 14:55:53.749 debug3: send_rexec_state: done
4268 2018-07-26 14:55:53.779 debug1: inetd sockets after dupping: 3, 3
4268 2018-07-26 14:55:53.779 Connection from 10.1.2.3 port 50530 on 30.141.36.111 port 22
4268 2018-07-26 14:55:53.779 debug1: Client protocol version 2.0; client software version WinSCP_release_5.11.2
4268 2018-07-26 14:55:53.779 debug1: no match: WinSCP_release_5.11.2
4268 2018-07-26 14:55:53.779 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
4268 2018-07-26 14:55:53.779 debug2: fd 3 setting O_NONBLOCK
4268 2018-07-26 14:55:53.813 debug3: spawning "C:\\SrvApps\\OpenSSH\\sshd.exe" "-y"
4268 2018-07-26 14:55:53.818 debug2: Network child is on pid 2580
4268 2018-07-26 14:55:53.818 debug3: send_rexec_state: entering fd = 6 config len 190
4268 2018-07-26 14:55:53.818 debug3: ssh_msg_send: type 0
4268 2018-07-26 14:55:53.818 debug3: send_rexec_state: done
4268 2018-07-26 14:55:53.818 debug3: ssh_msg_send: type 0
4268 2018-07-26 14:55:53.818 debug3: ssh_msg_send: type 0
4268 2018-07-26 14:55:53.818 debug3: preauth child monitor started
4268 2018-07-26 14:55:53.859 debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
4268 2018-07-26 14:55:53.859 debug3: send packet: type 20 [preauth]
4268 2018-07-26 14:55:53.859 debug1: SSH2_MSG_KEXINIT sent [preauth]
4268 2018-07-26 14:55:53.859 debug3: receive packet: type 20 [preauth]
4268 2018-07-26 14:55:53.859 debug1: SSH2_MSG_KEXINIT received [preauth]
4268 2018-07-26 14:55:53.859 debug2: local server KEXINIT proposal [preauth]
4268 2018-07-26 14:55:53.859 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1 [preauth]
4268 2018-07-26 14:55:53.859 debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
4268 2018-07-26 14:55:53.859 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
4268 2018-07-26 14:55:53.859 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
4268 2018-07-26 14:55:53.859 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
4268 2018-07-26 14:55:53.859 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
4268 2018-07-26 14:55:53.859 debug2: compression ctos: none [preauth]
4268 2018-07-26 14:55:53.859 debug2: compression stoc: none [preauth]
4268 2018-07-26 14:55:53.859 debug2: languages ctos:  [preauth]
4268 2018-07-26 14:55:53.859 debug2: languages stoc:  [preauth]
4268 2018-07-26 14:55:53.859 debug2: first_kex_follows 0  [preauth]
4268 2018-07-26 14:55:53.859 debug2: reserved 0  [preauth]
4268 2018-07-26 14:55:53.859 debug2: peer client KEXINIT proposal [preauth]
4268 2018-07-26 14:55:53.860 debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,rsa2048-sha256,rsa1024-sha1,diffie-hellman-group1-sha1 [preauth]
4268 2018-07-26 14:55:53.860 debug2: host key algorithms: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss [preauth]
4268 2018-07-26 14:55:53.860 debug2: ciphers ctos: aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-ctr,aes192-cbc,aes128-ctr,aes128-cbc,chacha20-poly1305@openssh.com,blowfish-ctr,blowfish-cbc,3des-ctr,3des-cbc,arcfour256,arcfour128 [preauth]
4268 2018-07-26 14:55:53.860 debug2: ciphers stoc: aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-ctr,aes192-cbc,aes128-ctr,aes128-cbc,chacha20-poly1305@openssh.com,blowfish-ctr,blowfish-cbc,3des-ctr,3des-cbc,arcfour256,arcfour128 [preauth]
4268 2018-07-26 14:55:53.860 debug2: MACs ctos: hmac-sha2-256,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-etm@openssh.com [preauth]
4268 2018-07-26 14:55:53.860 debug2: MACs stoc: hmac-sha2-256,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-etm@openssh.com [preauth]
4268 2018-07-26 14:55:53.860 debug2: compression ctos: none,zlib [preauth]
4268 2018-07-26 14:55:53.860 debug2: compression stoc: none,zlib [preauth]
4268 2018-07-26 14:55:53.860 debug2: languages ctos:  [preauth]
4268 2018-07-26 14:55:53.860 debug2: languages stoc:  [preauth]
4268 2018-07-26 14:55:53.860 debug2: first_kex_follows 0  [preauth]
4268 2018-07-26 14:55:53.860 debug2: reserved 0  [preauth]
4268 2018-07-26 14:55:53.860 debug1: kex: algorithm: curve25519-sha256@libssh.org [preauth]
4268 2018-07-26 14:55:53.860 debug1: kex: host key algorithm: ssh-ed25519 [preauth]
4268 2018-07-26 14:55:53.860 debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha2-256 compression: none [preauth]
4268 2018-07-26 14:55:53.860 debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha2-256 compression: none [preauth]
4268 2018-07-26 14:55:53.860 debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
4268 2018-07-26 14:55:53.910 debug3: receive packet: type 30 [preauth]
4268 2018-07-26 14:55:53.913 debug3: mm_key_sign entering [preauth]
4268 2018-07-26 14:55:53.913 debug3: mm_request_send entering: type 6 [preauth]
4268 2018-07-26 14:55:53.913 debug3: mm_request_receive entering
4268 2018-07-26 14:55:53.913 debug3: monitor_read: checking request 6
4268 2018-07-26 14:55:53.913 debug3: mm_answer_sign
4268 2018-07-26 14:55:53.915 debug3: mm_answer_sign: hostkey proof signature 008832E8(83)
4268 2018-07-26 14:55:53.915 debug3: mm_request_send entering: type 7
4268 2018-07-26 14:55:53.915 debug2: monitor_read: 6 used once, disabling now
4268 2018-07-26 14:55:53.915 debug3: mm_key_sign: waiting for MONITOR_ANS_SIGN [preauth]
4268 2018-07-26 14:55:53.915 debug3: mm_request_receive_expect entering: type 7 [preauth]
4268 2018-07-26 14:55:53.915 debug3: mm_request_receive entering [preauth]
4268 2018-07-26 14:55:53.915 debug3: send packet: type 31 [preauth]
4268 2018-07-26 14:55:53.915 debug3: send packet: type 21 [preauth]
4268 2018-07-26 14:55:53.915 debug2: set_newkeys: mode 1 [preauth]
4268 2018-07-26 14:55:53.915 debug1: rekey after 4294967296 blocks [preauth]
4268 2018-07-26 14:55:53.915 debug1: SSH2_MSG_NEWKEYS sent [preauth]
4268 2018-07-26 14:55:53.915 debug1: expecting SSH2_MSG_NEWKEYS [preauth]
4268 2018-07-26 14:55:54.357 debug3: receive packet: type 21 [preauth]
4268 2018-07-26 14:55:54.357 debug1: SSH2_MSG_NEWKEYS received [preauth]
4268 2018-07-26 14:55:54.357 debug2: set_newkeys: mode 0 [preauth]
4268 2018-07-26 14:55:54.357 debug1: rekey after 4294967296 blocks [preauth]
4268 2018-07-26 14:55:54.357 debug1: KEX done [preauth]
4268 2018-07-26 14:55:54.598 debug3: receive packet: type 5 [preauth]
4268 2018-07-26 14:55:54.598 debug3: send packet: type 6 [preauth]
4268 2018-07-26 14:55:54.657 debug3: receive packet: type 50 [preauth]
4268 2018-07-26 14:55:54.657 debug1: userauth-request for user testuser1 service ssh-connection method none [preauth]
4268 2018-07-26 14:55:54.657 debug1: attempt 0 failures 0 [preauth]
4268 2018-07-26 14:55:54.657 debug3: mm_getpwnamallow entering [preauth]
4268 2018-07-26 14:55:54.657 debug3: mm_request_send entering: type 8 [preauth]
4268 2018-07-26 14:55:54.657 debug3: mm_request_receive entering
4268 2018-07-26 14:55:54.657 debug3: monitor_read: checking request 8
4268 2018-07-26 14:55:54.657 debug3: mm_answer_pwnamallow
4268 2018-07-26 14:55:54.657 debug2: parse_server_config: config reprocess config len 190
4268 2018-07-26 14:55:54.659 debug3: mm_answer_pwnamallow: sending MONITOR_ANS_PWNAM: 1
4268 2018-07-26 14:55:54.659 debug3: mm_request_send entering: type 9
4268 2018-07-26 14:55:54.659 debug2: monitor_read: 8 used once, disabling now
4268 2018-07-26 14:55:54.659 debug3: mm_getpwnamallow: waiting for MONITOR_ANS_PWNAM [preauth]
4268 2018-07-26 14:55:54.659 debug3: mm_request_receive_expect entering: type 9 [preauth]
4268 2018-07-26 14:55:54.659 debug3: mm_request_receive entering [preauth]
4268 2018-07-26 14:55:54.659 debug2: input_userauth_request: setting up authctxt for testuser1 [preauth]
4268 2018-07-26 14:55:54.659 debug3: mm_inform_authserv entering [preauth]
4268 2018-07-26 14:55:54.659 debug3: mm_request_send entering: type 4 [preauth]
4268 2018-07-26 14:55:54.659 debug3: mm_request_receive entering
4268 2018-07-26 14:55:54.659 debug3: monitor_read: checking request 4
4268 2018-07-26 14:55:54.659 debug3: mm_answer_authserv: service=ssh-connection, style=
4268 2018-07-26 14:55:54.659 debug2: monitor_read: 4 used once, disabling now
4268 2018-07-26 14:55:54.659 debug2: input_userauth_request: try method none [preauth]
4268 2018-07-26 14:55:54.659 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
4268 2018-07-26 14:55:54.659 debug3: send packet: type 51 [preauth]
4268 2018-07-26 14:55:54.701 debug3: receive packet: type 50 [preauth]
4268 2018-07-26 14:55:54.701 debug1: userauth-request for user testuser1 service ssh-connection method keyboard-interactive [preauth]
4268 2018-07-26 14:55:54.701 debug1: attempt 1 failures 0 [preauth]
4268 2018-07-26 14:55:54.701 debug2: input_userauth_request: try method keyboard-interactive [preauth]
4268 2018-07-26 14:55:54.701 debug1: keyboard-interactive devs  [preauth]
4268 2018-07-26 14:55:54.701 debug1: auth2_challenge: user=testuser1 devs= [preauth]
4268 2018-07-26 14:55:54.701 debug1: kbdint_alloc: devices '' [preauth]
4268 2018-07-26 14:55:54.701 debug2: auth2_challenge_start: devices  [preauth]
4268 2018-07-26 14:55:54.701 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
4268 2018-07-26 14:55:54.701 debug3: send packet: type 51 [preauth]
4268 2018-07-26 14:55:54.759 debug3: receive packet: type 50 [preauth]
4268 2018-07-26 14:55:54.760 debug1: userauth-request for user testuser1 service ssh-connection method password [preauth]
4268 2018-07-26 14:55:54.760 debug1: attempt 2 failures 1 [preauth]
4268 2018-07-26 14:55:54.760 debug2: input_userauth_request: try method password [preauth]
4268 2018-07-26 14:55:54.760 debug3: mm_auth_password entering [preauth]
4268 2018-07-26 14:55:54.760 debug3: mm_request_send entering: type 12 [preauth]
4268 2018-07-26 14:55:54.760 debug3: mm_request_receive entering
4268 2018-07-26 14:55:54.760 debug3: monitor_read: checking request 12
4268 2018-07-26 14:55:54.761 debug3: mm_answer_authpassword: sending result 1
4268 2018-07-26 14:55:54.761 debug3: mm_request_send entering: type 13
4268 2018-07-26 14:55:54.762 Accepted password for testuser1 from 10.1.2.3 port 50530 ssh2
4268 2018-07-26 14:55:54.762 debug1: monitor_child_preauth: testuser1 has been authenticated by privileged process
4268 2018-07-26 14:55:54.762 debug3: mm_get_keystate: Waiting for new keys
4268 2018-07-26 14:55:54.762 debug3: mm_request_receive_expect entering: type 26
4268 2018-07-26 14:55:54.762 debug3: mm_request_receive entering
4268 2018-07-26 14:55:54.762 debug3: mm_get_keystate: GOT new keys
4268 2018-07-26 14:55:54.762 debug3: mm_auth_password: waiting for MONITOR_ANS_AUTHPASSWORD [preauth]
4268 2018-07-26 14:55:54.762 debug3: mm_request_receive_expect entering: type 13 [preauth]
4268 2018-07-26 14:55:54.762 debug3: mm_request_receive entering [preauth]
4268 2018-07-26 14:55:54.762 debug3: mm_auth_password: user authenticated [preauth]
4268 2018-07-26 14:55:54.762 debug3: send packet: type 52 [preauth]
4268 2018-07-26 14:55:54.762 debug3: mm_request_send entering: type 26 [preauth]
4268 2018-07-26 14:55:54.762 debug3: mm_send_keystate: Finished sending state [preauth]
4268 2018-07-26 14:55:54.763 debug1: monitor_read_log: child log fd closed
4268 2018-07-26 14:55:54.788 debug3: spawning "C:\\SrvApps\\OpenSSH\\sshd.exe" "-z"
4268 2018-07-26 14:55:54.790 User child is on pid 4804
4268 2018-07-26 14:55:54.790 debug3: send_rexec_state: entering fd = 5 config len 190
4268 2018-07-26 14:55:54.790 debug3: ssh_msg_send: type 0
4268 2018-07-26 14:55:54.790 debug3: send_rexec_state: done
4268 2018-07-26 14:55:54.790 debug3: ssh_msg_send: type 0
4268 2018-07-26 14:55:54.790 debug3: ssh_msg_send: type 0
4268 2018-07-26 14:55:54.790 debug3: ssh_msg_send: type 0
4804 2018-07-26 14:55:54.813 debug3: ssh_msg_recv entering
4804 2018-07-26 14:55:54.813 debug2: fd 4 setting O_NONBLOCK
4804 2018-07-26 14:55:54.813 debug2: parse_server_config: config reprocess config len 190
4804 2018-07-26 14:55:54.814 debug3: ssh_msg_recv entering
4804 2018-07-26 14:55:54.814 debug3: monitor_apply_keystate: packet_set_state
4804 2018-07-26 14:55:54.814 debug2: set_newkeys: mode 0
4804 2018-07-26 14:55:54.814 debug1: rekey after 4294967296 blocks
4804 2018-07-26 14:55:54.814 debug2: set_newkeys: mode 1
4804 2018-07-26 14:55:54.814 debug1: rekey after 4294967296 blocks
4804 2018-07-26 14:55:54.814 debug1: ssh_packet_set_postauth: called
4804 2018-07-26 14:55:54.814 debug3: ssh_packet_set_state: done
4804 2018-07-26 14:55:54.814 debug3: notify_hostkeys: key 0: ssh-rsa SHA256:buEc9o96ZMm/DEDsI98vuC9poH4M6W3dy4DOiwQ/SSg
4804 2018-07-26 14:55:54.814 debug3: notify_hostkeys: key 1: ecdsa-sha2-nistp256 SHA256:7QBvyuxdgC1jOw8zzE/wVPBugu8bUn8vpM/k25YD2WQ
4804 2018-07-26 14:55:54.814 debug3: notify_hostkeys: key 2: ssh-ed25519 SHA256:xu2mIdbm//fvG0N3/1cv850+CHBd4KvshsyGfFtRJTU
4804 2018-07-26 14:55:54.814 debug3: notify_hostkeys: sent 3 hostkeys
4804 2018-07-26 14:55:54.814 debug3: send packet: type 80
4804 2018-07-26 14:55:54.819 debug1: active: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
4804 2018-07-26 14:55:54.819 debug1: Entering interactive session for SSH2.
4804 2018-07-26 14:55:54.819 debug2: fd 7 setting O_NONBLOCK
4804 2018-07-26 14:55:54.819 debug2: fd 8 setting O_NONBLOCK
4804 2018-07-26 14:55:54.819 debug1: server_init_dispatch
4804 2018-07-26 14:55:54.819 debug3: receive packet: type 2
4804 2018-07-26 14:55:54.819 debug3: Received SSH2_MSG_IGNORE
4804 2018-07-26 14:55:54.819 debug3: receive packet: type 90
4804 2018-07-26 14:55:54.819 debug1: server_input_channel_open: ctype session rchan 256 win 2147483647 max 16384
4804 2018-07-26 14:55:54.819 debug1: input_session_request
4804 2018-07-26 14:55:54.819 debug1: channel 0: new [server-session]
4804 2018-07-26 14:55:54.819 debug2: session_new: allocate (allocated 0 max 10)
4804 2018-07-26 14:55:54.819 debug3: session_unused: session id 0 unused
4804 2018-07-26 14:55:54.819 debug1: session_new: session 0
4804 2018-07-26 14:55:54.819 debug1: session_open: channel 0
4804 2018-07-26 14:55:54.820 debug1: session_open: session 0: link with channel 0
4804 2018-07-26 14:55:54.820 debug1: server_input_channel_open: confirm session
4804 2018-07-26 14:55:54.820 debug3: send packet: type 91
4804 2018-07-26 14:55:55.108 debug3: receive packet: type 98
4804 2018-07-26 14:55:55.108 debug1: server_input_channel_req: channel 0 request simple@putty.projects.tartarus.org reply 0
4804 2018-07-26 14:55:55.108 debug1: session_by_channel: session 0 channel 0
4804 2018-07-26 14:55:55.108 debug1: session_input_channel_req: session 0 req simple@putty.projects.tartarus.org
4804 2018-07-26 14:55:55.348 debug3: receive packet: type 98
4804 2018-07-26 14:55:55.348 debug1: server_input_channel_req: channel 0 request subsystem reply 1
4804 2018-07-26 14:55:55.348 debug1: session_by_channel: session 0 channel 0
4804 2018-07-26 14:55:55.348 debug1: session_input_channel_req: session 0 req subsystem
4804 2018-07-26 14:55:55.348 debug2: subsystem request for sftp by user testuser1
4804 2018-07-26 14:55:55.348 debug1: subsystem: cannot stat sftp-server.exe: No such file or directory
4804 2018-07-26 14:55:55.348 debug1: subsystem: exec() sftp-server.exe
4804 2018-07-26 14:55:55.348 Starting session: subsystem 'sftp' for testuser1 from 10.1.2.3 port 50530 id 0
4804 2018-07-26 14:55:55.349 debug2: fd 9 setting O_NONBLOCK
4804 2018-07-26 14:55:55.349 debug2: fd 10 setting O_NONBLOCK
4804 2018-07-26 14:55:55.349 debug2: fd 11 setting O_NONBLOCK
4804 2018-07-26 14:55:55.349 debug2: fd 12 setting O_NONBLOCK
4804 2018-07-26 14:55:55.349 debug2: fd 13 setting O_NONBLOCK
4804 2018-07-26 14:55:55.349 debug2: fd 14 setting O_NONBLOCK
4804 2018-07-26 14:55:55.349 debug1: Executing command: "c:\\windows\\system32\\windowspowershell\\v1.0\\powershell.exe" /c sftp-server.exe
4804 2018-07-26 14:55:55.358 debug2: fd 4 setting TCP_NODELAY
4804 2018-07-26 14:55:55.358 debug3: fd 11 is O_NONBLOCK
4804 2018-07-26 14:55:55.358 debug3: fd 10 is O_NONBLOCK
4804 2018-07-26 14:55:55.358 debug3: fd 13 is O_NONBLOCK
4804 2018-07-26 14:55:55.358 debug3: send packet: type 99
4804 2018-07-26 14:55:55.924 debug2: channel 0: read 72 from efd 13
4804 2018-07-26 14:55:55.924 debug3: channel 0: discard efd
4804 2018-07-26 14:55:55.924 debug2: channel 0: read 290 from efd 13
4804 2018-07-26 14:55:55.924 debug3: channel 0: discard efd
4804 2018-07-26 14:55:55.924 debug2: channel 0: read 85 from efd 13
4804 2018-07-26 14:55:55.924 debug3: channel 0: discard efd
4804 2018-07-26 14:55:55.929 debug2: channel 0: read<=0 rfd 11 len 0
4804 2018-07-26 14:55:55.929 debug2: channel 0: read failed
4804 2018-07-26 14:55:55.929 debug2: channel 0: close_read
4804 2018-07-26 14:55:55.929 debug2: channel 0: input open -> drain
4804 2018-07-26 14:55:55.929 debug2: channel 0: ibuf empty
4804 2018-07-26 14:55:55.929 debug2: channel 0: send eof
4804 2018-07-26 14:55:55.930 debug3: send packet: type 96
4804 2018-07-26 14:55:55.930 debug2: channel 0: input drain -> closed
4804 2018-07-26 14:55:55.935 debug1: Received SIGCHLD.
4804 2018-07-26 14:55:55.935 debug1: session_by_pid: pid 3156
4804 2018-07-26 14:55:55.935 debug1: session_exit_message: session 0 channel 0 pid 3156
4804 2018-07-26 14:55:55.935 debug2: channel 0: request exit-status confirm 0
4804 2018-07-26 14:55:55.935 debug3: send packet: type 98
4804 2018-07-26 14:55:55.935 debug1: session_exit_message: release channel 0
4804 2018-07-26 14:55:55.935 debug2: channel 0: write failed
4804 2018-07-26 14:55:55.935 debug2: channel 0: close_write
4804 2018-07-26 14:55:55.935 debug2: channel 0: send eow
4804 2018-07-26 14:55:55.935 debug2: channel 0: output open -> closed
4804 2018-07-26 14:55:55.935 debug2: channel 0: read 0 from efd 13
4804 2018-07-26 14:55:55.935 debug2: channel 0: closing read-efd 13
4804 2018-07-26 14:55:55.935 debug2: channel 0: send close
4804 2018-07-26 14:55:55.935 debug3: send packet: type 97
4804 2018-07-26 14:55:55.935 debug3: channel 0: will not send data after close
4804 2018-07-26 14:55:55.935 debug2: notify_done: reading
4804 2018-07-26 14:55:55.935 debug3: channel 0: will not send data after close
4804 2018-07-26 14:55:55.977 debug3: receive packet: type 96
4804 2018-07-26 14:55:55.977 debug2: channel 0: rcvd eof
4804 2018-07-26 14:55:55.977 debug3: channel 0: will not send data after close
4804 2018-07-26 14:55:55.977 debug3: receive packet: type 97
4804 2018-07-26 14:55:55.977 debug2: channel 0: rcvd close
4804 2018-07-26 14:55:55.977 debug3: channel 0: will not send data after close
4804 2018-07-26 14:55:55.977 debug2: channel 0: is dead
4804 2018-07-26 14:55:55.977 debug2: channel 0: gc: notify user
4804 2018-07-26 14:55:55.977 debug1: session_by_channel: session 0 channel 0
4804 2018-07-26 14:55:55.977 debug1: session_close_by_channel: channel 0 child 0
4804 2018-07-26 14:55:55.977 Close session: user testuser1 from 10.1.2.3 port 50530 id 0
4804 2018-07-26 14:55:55.977 debug3: session_unused: session id 0 unused
4804 2018-07-26 14:55:55.977 debug2: channel 0: gc: user detached
4804 2018-07-26 14:55:55.977 debug2: channel 0: is dead
4804 2018-07-26 14:55:55.977 debug2: channel 0: garbage collecting
4804 2018-07-26 14:55:55.977 debug1: channel 0: free: server-session, nchannels 1
4804 2018-07-26 14:55:55.977 debug3: channel 0: status: The following connections are open:\r\n  #0 server-session (t4 r256 i3/0 o3/0 fd -1/-1 cc -1)\r\n
4804 2018-07-26 14:55:55.977 Connection closed by 10.1.2.3 port 50530
4804 2018-07-26 14:55:55.977 debug1: do_cleanup
4804 2018-07-26 14:55:55.977 Transferred: sent 2088, received 1792 bytes
4804 2018-07-26 14:55:55.977 Closing connection to 10.1.2.3 port 50530
4804 2018-07-26 14:55:55.977 debug3: mm_request_send entering: type 50
4268 2018-07-26 14:55:55.977 debug3: mm_request_receive entering
4268 2018-07-26 14:55:55.977 debug3: monitor_read: checking request 50
4268 2018-07-26 14:55:55.977 debug3: mm_answer_term: tearing down sessions

**Comment by ronelm2000** [comment]
I am able to replicate this error. It seems it happens when the default shell is changed to powershell. The key is this particular line:
```txt
debug1: Executing command: "c:\windows\system32\windowspowershell\v1.0\powershell.exe" /c sftp-server.exe
```

This should either indicate the exact path to sftp-server.exe or be something like ./sftp-server.exe

Current Workaround is to revert the Registry Entries to use powershell back to Command Prompt.

**Comment by bagajjal** [comment]
It's expected behavior.

See point 9,
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

![image](https://user-images.githubusercontent.com/23668037/45376154-f3da3880-b5ab-11e8-8cc6-0348da0a0e20.png)
