### ISSUE TITLE
cipher command access denied

### ISSUE THREAD

**Issue by hashCode1** [PowerShell/Win32-OpenSSH#1223]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 0.0.22.0
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows Server 2012 R2 Datacenter
**Client OperatingSystem**
Windows Server 2012 R2 Datacenter
**What is failing**
cipher /e /a C:\temp\test.txt

most write operation in C:\ are failing for admin user and domain users that are in admin group.
I set the sshd to logon as one of those users that is an admin

**Expected output**
file is encrypted 
**Actual output**
Encrypting files in C:\Temp\

test2.txt           [ERR]
test2.txt: Access is denied.

0 file(s) [or directorie(s)] within 1 directorie(s) were encrypted.

**Comment by bagajjal** [comment]
Please use the latest version and try again.

Are you executing (cipher /e /a C:\temp\test.txt) in an interactive ssh session?

**Comment by hashCode1** [comment]
Ok i will upgrade to the latest version.. 
and yes it is interactive ..  the user profile is loaded in the session and checked acl for the file user has full control

**Comment by hashCode1** [comment]
I have updated to the latest version and still cipher command doesnt work
PS C:\Users\hash> ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
7.7.1.0

**Comment by suyash-repo** [comment]
Found same issue with Windows 2k16. Any further updates on this?
```
PS C:\Users\Administrator> ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
7.9.0.0
PS C:\Users\Administrator> cipher /E qc

 Encrypting files in C:\Users\Administrator\

qc                  [ERR]
qc: Access is denied.

0 file(s) [or directorie(s)] within 1 directorie(s) were encrypted.

PS C:\Users\Administrator> ((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).
roductName)
Windows Server 2016 Standard
PS C:\Users\Administrator>
```

**Comment by NoMoreFood** [comment]
I've empirically confirmed this is related to https://github.com/PowerShell/Win32-OpenSSH/issues/1349.  Switching the logon type to interactive addresses the issue.

**Comment by maertendMSFT** [comment]
This repros with winrm based remoting, it appears that the cipher command does not work with a network logon token
