### ISSUE TITLE
SFTP, SSH unicode display issues.

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/Win32-OpenSSH#1225]
version - OpenSSHv7.7.2.0.

1) SSH NO-PTY Unicode issue
PS C:\Users\bagajjal\Desktop\OpenSSH_RS5_inbox> .\ssh.exe -T nonadmin@localhost "dir c:\users\nonadmin\client_test_dir_язык"
 Volume in drive C has no label.
 Volume Serial Number is F82C-1E41

 Directory of c:\users\nonadmin\client_test_dir_????

08/03/2018  05:46 PM    <DIR>          .
08/03/2018  05:46 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  26,905,329,664 bytes free
PS C:\Users\bagajjal\Desktop\OpenSSH_RS5_inbox>

2) SFTP Unicode issue
sftp> ls c:\test
/c:/test/client_test_dir_╤Å╨╖╤ï╨║   (But it should be **c:\test\client_test_dir_язык**)
sftp> cd c:\test\client_test_dir_язык
sftp> pwd
Remote working directory: /c:/test/client_test_dir_╤Å╨╖╤ï╨║

sftp> lcd c:\test\client_test_dir_язык
sftp> lpwd
Local working directory: c:\test\client_test_dir_╤Å╨╖╤ï╨║
sftp>

**Comment by FranklinYu** [comment]
Probably related to #1178.

**Comment by bagajjal** [comment]
@franklinyu - No.

Password reading ends up in readpassphrase().
SFTP Unicode output ends up in mprintf().

**Comment by NoMoreFood** [comment]
If interested, you can test with these binaries: https://github.com/NoMoreFood/openssh-portable/releases/tag/v7.9-merge-1

**Comment by manojampalam** [comment]
Did `chcp 65001` fix your issue ?
