### ISSUE TITLE
Non-ASCII character display issue

### ISSUE THREAD

**Issue by FranklinYu** [PowerShell/Win32-OpenSSH#1227]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
7.7.2.0
 
**Server OperatingSystem**
Ubuntu 16.04 (or any Linux with Bash 4.2 or later)

**Client OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 Enterprise Version 1803, build 17134.191

**What is failing**
```bash
echo -e '\u2620'
```

**Expected output**
[Skull and Crossbones (☠)](https://unicode-table.com/en/2620/).

**Actual output**
```text
Γÿá
```

### Note

1.  This happens only recently (less than half a year).
2.  @MathiasMagnus mention a similar issue in https://github.com/PowerShell/Win32-OpenSSH/issues/1178#issuecomment-411101981.

**Comment by bagajjal** [comment]
@franklinyu - Please provide the windows build number (on cmd.exe, issue "winver" command)

**Comment by FranklinYu** [comment]
@bagajjal Updated.

**Comment by bagajjal** [comment]
@MathiasMagnus  @franklinyu - I have fixed this issue (tested on windows version 1803 OS Build 17713.1002), please try this private binary [ssh_unicode_issue.zip](https://github.com/PowerShell/Win32-OpenSSH/files/2268037/ssh_unicode_issue.zip) and let me know if you see any issues.

**Comment by FranklinYu** [comment]
Works for me. @MathiasMagnus please confirm.

**Comment by MathiasMagnus** [comment]
Indeed, it works. Thanks for the hotfix!

**Comment by FranklinYu** [comment]
@bagajjal Shall we leave this issue open until next release? Not familiar with the workflow here.

**Comment by bagajjal** [comment]
Yes please. We will close it when the fix is merged.

**Comment by FranklinYu** [comment]
@bingbing8 Do we have a new release? Or is this already available in latest release?

**Comment by bingbing8** [comment]
@FranklinYu, the new release is coming in 2 business days

**Comment by FranklinYu** [comment]
Confirm that it works in [v7.9.0.0p1-Beta](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.9.0.0p1-Beta). Thanks!
