### ISSUE TITLE
Unable to install latest version of OpenSSH from Chocolatey site

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/Win32-OpenSSH#1228]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
```
PS [6] > ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
7.7.1.1
PS [8] >
```
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
```
PS [8] > ((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)
Windows 10 Pro
PS [10] >
```

**Client OperatingSystem**
```
PS [10] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.17735
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**What is failing**
This version won't install in PoweShell Core. Previous version work fine.  It's giving a Get-CimInstance error and won't complete installation.

**Expected output**
To complete installation without any failures.

**Actual output**
See error below:
```
PS C:\Program Files> choco install openssh
Chocolatey v0.10.8
Installing the following packages:
openssh
By installing you accept licenses for the packages.
Progress: Downloading openssh 7.7.2.1... 100%

openssh v7.7.2.1 [Approved]
openssh package files install completed. Performing other installation steps.
The package openssh wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): Y

ERROR: The 'Get-CIMInstance' command was found in the module 'CimCmdlets', but the module could not be loaded. For more information, run 'Import-Module CimCmdlets'.
The install of openssh was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\openssh\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - openssh (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\openssh\tools\chocolateyinstall.ps1'.
 See log for details.
PS C:\Program Files>
```
![openssh_err_01_2018-08-14_16-27-56](https://user-images.githubusercontent.com/19892435/44119588-aa1e5af2-9fe7-11e8-82fd-333566854dcb.jpg)

**Comment by DarwinJS** [comment]
I was about 99% sure of this already - but only by being told - so I wanted to test it.

The below screenshot shows that when I start a chocolatey package in PowerShell 6.0.4, the internal script is still processed by Windows PowerShell 5.x.

The first $psversiontable is the host that the package is being run from and the second is running in the context of the package.

![image](https://user-images.githubusercontent.com/11597190/44124003-f3160d52-9ff8-11e8-9bbe-ae9d72717930.png)

I would suggest that you check the configuration of Windows PowerShell.  Especially if you have installed any PowerShell Core compatibility tweaks.

Issues for the Chocolatey packages should be opened here: https://github.com/DarwinJS/ChocoPackages/issues

Thanks.

**Comment by MaximoTrinidad** [comment]
@DarwinJS ,

The thing is... I never use to have the problem of installing OPenSSh in PowerShell Core release.

![openssh_03_2018-02-28](https://user-images.githubusercontent.com/19892435/44158791-a12c6000-a083-11e8-8511-f5e102123a6d.jpg)

I'm trying to determine if is a PowerShell Core or an OpenSSH issue.

I've been trying to user Windows 10 Openssh feature but it not working.  Currently have a non-Windows Insider build (Version: 10.0.17134) with Win32-Openssh (version: 0.0.24.0) installed from Chocolatey and with PowerShell-Preview 4 working without any issues.

I know is an older version but is working.

Never had the issue with Get-CIMInstance!
:)

 I will resubmit the issue in the link provided.

Thanks,
Max
