### ISSUE TITLE
Unable to connect : Log says "RSA key is not allowed"

### ISSUE THREAD

**Issue by gayantd** [PowerShell/Win32-OpenSSH#1230]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
Windows Server 2008 R2 Datacenter

**Client OperatingSystem**
Linux

**What is failing**
Server logs

2468 2018-08-15 07:37:51.057 debug1: trying public key file C:\\Users\\xxxxx\\.ssh/authorized_keys
2468 2018-08-15 07:37:51.057 debug2: C:\\Users\\xxxxx\\.ssh/authorized_keys:1: check options: 'rsa-key-20160610 AAAAB3xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxh8DGmnreODdC7z3V4H/XOA3+L4ZBKgRIdOLFsteO5cDkGPQ875RXVhoXX5EH/IN1wJVLFdKNGi+DATH9kvISaNcw==\n'
2468 2018-08-15 07:37:51.057 debug2: C:\\Users\\irdtds\\.ssh/authorized_keys:1: advance: 'AAAAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxDGmnreODdC7z3V4H/XOA3+L4ZBKgRIdOLFsteO5cDkGPQ875RXVhoXX5EH/IN1wJVLFdKNGi+DATH9kvISaNcw==\n'
2468 2018-08-15 07:37:51.057 debug3: mm_answer_keyallowed: publickey authentication: RSA key is not allowed

**Comment by bagajjal** [comment]
I guess it's because of recent changes in base openssh 7.7.2.
authorized_keys file has rsa-key-20160610. Try changing rsa-key-20160610 to ssh-rsa.

Can you try the same keys on Linux machine that has openssh 7.7.2 installed.

**Comment by gayantd** [comment]
I tried by renaming rsa-key to ssh-rsa. But still same error.
I don't have Linux OS as my client is from outside. 

This is working fine for "ecdsa" key, but failed with RSA.

Config file following line is commented. Should I un-comment it ? what is the default value ?
#PubkeyAuthentication yes

**Comment by bagajjal** [comment]
Did you edit the authorized_keys file (replacing  rsa-key-20160610 to ssh-rsa)?
Also can you try to create and use the new rsa key?

sshd_config will have the default values as un-commented lines. so there is no need to update the sshd_config.

**Comment by gayantd** [comment]
yes tried by renaming rsa-key to ssh-rsa. But still same error.

Let me try with new rsa key.

**Comment by gayantd** [comment]
ah no. I just renamed "rsa-key-20160610" to "ssh-rsa-20160610".
Let me try to rename just "ssh-rsa" and try.

Thank you !

**Comment by gayantd** [comment]
Awesome, that did work !!!
@bagajjal , you helped me last time to exclude ssh and leave only for sftp by adding below lings config file.
Match User *
ForceCommand internal-sftp

But it doesn't work. When my Key is not authenticated, It asking for Password. When I provide password, I can login. I don't want to login with password. Only need to use by Key.
Is there a way to do it ?

**Comment by bagajjal** [comment]
To completely disable the password authentication,

1) Add below lines to %programdata%\ssh\sshd_config, 

ChallengeResponseAuthentication no
PasswordAuthentication no
UsePAM no

2) Now restart the sshd service
net stop sshd
net start sshd

3) Try password authentication. It should fail.

**Comment by gayantd** [comment]
Great ! That worked. Thank you!
