### ISSUE TITLE
"net stop sshd" failed with system error 109 (pipe has been ended)

### ISSUE THREAD

**Issue by yasu1013** [PowerShell/Win32-OpenSSH#1231]
**"OpenSSH for Windows" version**
0.0.21.0
 
**Server OperatingSystem**
Windows Server 2012 R2

**Client OperatingSystem**
N/A

**What is failing**
I added a task on task scheduler which stop sshd, rotation sshd.log, and start sshd again. This task runs everyday at "safety" (sshd is not used) time, but sometimes fails at stopping sshd.
The task stops sshd using "net stop" command, but failed with error messages below:
"system error 109"
"pipe has been ended"
However, sshd service has stopped successfully.

Has anyone experienced similar issue ? What are possible causes ?

**Comment by manojampalam** [comment]
You would see this, if sshd service process terminates before SCM is notified. 

Here are the underlying technical details. SSHD service is contolled via SCM. It has 2 primary threads, thread T1 is SCM control thread that dispatches service control instructions to SSHD. The other thread T2 is the one that is executing the main service loop. 
When you do net stop sshd, T1 issues a SIGINT that is processed by T2. We'll have to see if this SIGINT causes server_accept_loop to exit the process.

**Comment by yasu1013** [comment]
Thank you for very quick response. 
Just for confirmation, Is this issue caused by a bug in OpenSSH for Windows ?

**Comment by manojampalam** [comment]
Possibly.

**Comment by yasu1013** [comment]
Thank you. I wait for progress.

**Comment by yasu1013** [comment]
I am sorry, I forgot to tell an important thing:
"net stop" command sometimes fails. However, sshd service actually stops in that case. There is the event log that sshd service has stopped. 

updated at Aug 22: "a important thing" -> "an important thing" :)

**Comment by thezim** [comment]
@yasu1013 be aware that there might be an update you need - KB4345424. This was to fix an issue with a prior patch. While this series of updates references troubles with IIS we saw other 3rd party services being affected in our enterprise. Services getting stuck in a `Stopping` state. Just something worth trying if your still having an issue.

**Comment by yasu1013** [comment]
@thezim thank you for your comment. I will consider to apply KB4345424. I also would like to wait for the result of investigation in OpenSSH.

**Comment by maertendMSFT** [comment]
This may be resolved in the latest release, please reopen if it repros
