### ISSUE TITLE
StrictHostKeyChecking can not be disabled

### ISSUE THREAD

**Issue by kschwidder** [PowerShell/Win32-OpenSSH#1232]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`

7.7.2.0 (latest)
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

Windows Server 2012 R2

**Client OperatingSystem**

Windows 7

**What is failing**
We have established the SSH Server on Windows and want to update via Bamboo some directories.
Therefore SCP commands are used which hang since the sshd checks the authenticity of the host.
We have tried to set the StrictHostKeyChecking to no but it is not recognized for the windows release.
The prompt for yes/no still appears. 

**Expected output**

How enable StrictHostKeyChecking no in this Windows version ?

**Actual output**

The authenticity of host 'mdzhwweam01 (10.22.61.132)' can't be established.
ECDSA key fingerprint is SHA256:65ftQIDWX4G+FL5U4sPdjRjcsKAgOcJsjGO5diQf5UI.
Are you sure you want to continue connecting (yes/no)?

**Comment by bagajjal** [comment]
Add the below lines  to c:\users\\<user_name>\\.ssh\config (if file doesn't exist, just create it).

Host *
    StrictHostKeyChecking no

Now, fix the file (c:\users\\<user_name>\\.ssh\config) permissions so that no other user apart from administrators, system, current user has the read, write access..

If it didn't work then debug using
ssh -vvv user@ip

**Comment by beardedfool** [comment]
Having the same error having added those lines to config and checked permissions.
but not confident it's not a config error my end as this system is far from fresh.

That said, can I just check whether creating a ssh_config in C:\ProgramData\ssh should work? 
ssh -vvv seems to be suggesting it's read
debug1: Reading configuration data __PROGRAMDATA__\\ssh/ssh_config
but not sure if it's loaded correctly

Just wondering why there isn't one created by default? Am I in the wrong location?

WIn10 - 17134.228

**Comment by beardedfool** [comment]
OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
debug1: Reading configuration data C:\\Users\\XXXXX/.ssh/config
debug1: C:\\Users\\XXXXX/.ssh/config line 2: Applying options for *
debug1: Reading configuration data __PROGRAMDATA__\\ssh/ssh_config
debug2: resolving "192.168.21.5" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 192.168.21.5 [192.168.21.5] port 22.
debug1: Connection established.
debug1: identity file C:\\Users\\XXXXX/.ssh/id_rsa type 0
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_rsa-cert error:2
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_rsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\XXXXX/.ssh/id_rsa-cert type -1
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_dsa error:2
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_dsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\XXXXX/.ssh/id_dsa type -1
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_dsa-cert error:2
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_dsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\XXXXX/.ssh/id_dsa-cert type -1
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_ecdsa error:2
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_ecdsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\XXXXX/.ssh/id_ecdsa type -1
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_ecdsa-cert error:2
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_ecdsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\XXXXX/.ssh/id_ecdsa-cert type -1
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_ed25519 error:2
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_ed25519.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\XXXXX/.ssh/id_ed25519 type -1
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_ed25519-cert error:2
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/id_ed25519-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\XXXXX/.ssh/id_ed25519-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.6
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6p1 Ubuntu-4
debug1: match: OpenSSH_7.6p1 Ubuntu-4 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 192.168.21.5:22 as 'installer'
debug3: hostkeys_foreach: reading file "C:\\Users\\XXXXX/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file C:\\Users\\XXXXX/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from 192.168.21.5
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/known_hosts2 error:2
debug3: Failed to open file:C:\\ProgramData\\ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:\\ProgramData\\ssh/ssh_known_hosts2 error:2
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ssh-rsa XXXreplaced
debug3: hostkeys_foreach: reading file "C:\\Users\\XXXXX/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file C:\\Users\\XXXXX/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from 192.168.21.5
debug3: Failed to open file:C:\\Users\\XXXXX/.ssh/known_hosts2 error:2
debug3: Failed to open file:C:\\ProgramData\\ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:\\ProgramData\\ssh/ssh_known_hosts2 error:2
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:replaced.
Please contact your system administrator.
Add correct host key in C:\\Users\\XXXXX/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in C:\\Users\\XXXXX/.ssh/known_hosts:1
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug3: unable to connect to pipe \\\\.\\pipe\\openssh-ssh-agent, error: 2
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug2: key: C:\\Users\\XXXXX/.ssh/id_rsa (0000019E141DB4B0)
debug2: key: C:\\Users\\XXXXX/.ssh/id_dsa (0000000000000000)
debug2: key: C:\\Users\\XXXXX/.ssh/id_ecdsa (0000000000000000)
debug2: key: C:\\Users\\XXXXX/.ssh/id_ed25519 (0000000000000000)
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug3: start over, passed a different list publickey,password,keyboard-interactive
debug3: preferred publickey
debug3: authmethod_lookup publickey
debug3: remaining preferred:
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:+invg+1HNU5vPMp3Srtr0BqsvoMNXkSSCC7t0/f6FTw C:\\Users\\XXXXX/.ssh/id_rsa
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Trying private key: C:\\Users\\XXXXX/.ssh/id_dsa
debug3: GetFileAttributesExW with last error 2
debug3: no such identity: C:\\Users\\XXXXX/.ssh/id_dsa: No such file or directory
debug1: Trying private key: C:\\Users\\XXXXX/.ssh/id_ecdsa
debug3: GetFileAttributesExW with last error 2
debug3: no such identity: C:\\Users\\XXXXX/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: C:\\Users\\XXXXX/.ssh/id_ed25519
debug3: GetFileAttributesExW with last error 2
debug3: no such identity: C:\\Users\\XXXXX/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
installer@192.168.21.5: Permission denied (publickey,password,keyboard-interactive).

**Comment by bagajjal** [comment]
@beardedfool -
As per your ssh logs, the host key is already found in the known_hosts. So we are not hitting the original issue.

debug1: Authenticating to 192.168.21.5:22 as 'installer'
debug3: hostkeys_foreach: reading file "C:\Users\XXXXX/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file C:\Users\XXXXX/.ssh/known_hosts:1

**Next steps -** 
1) Backup, Remove the known hosts file (C:\Users\XXXXX/.ssh/known_hosts).
2) run ssh.exe user@ip
3) You should see the hostkey is automatically added to C:\Users\XXXXX/.ssh/known_hosts and also a warning msg on the console
c:\>ssh.exe XXXX@YYY
Warning: Permanently added 'XXXX' (ECDSA) to the list of known hosts.
XXXX@YYY's password:

**More on your questions,**

1) You config is read by the ssh client.
debug1: Reading configuration data C:\Users\XXXXX/.ssh/config
debug1: C:\Users\XXXXX/.ssh/config line 2: Applying options for *

2) You can specify the ssh config at 3 levels,
a) Command line option.
b) users config file (C:\users\xxxx/.ssh/config)
c) system wide config (%programdata%\ssh\ssh_config.

For each parameter, the first obtained value will be used. 
This behavior is inline with the [UNIX behavior](https://www.freebsd.org/cgi/man.cgi?query=ssh_config&sektion=5).

**Comment by beardedfool** [comment]
Thanks for the help and sorry both for confusing the original issue - long day. 

Much appreciated
