### ISSUE TITLE
sshd: Broken Pipe Failure () 

### ISSUE THREAD

**Issue by pm-babak** [PowerShell/Win32-OpenSSH#1233]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 7 Professional

**Client OperatingSystem**
Linux

**What is failing**
Client failed to connect to sshd (as Service) via public-key, sshd is windows 7 running on VMware Workstation 14, client is Linux
there are no problem when sshd running through terminal (not as service), and there is no problem with password authentication

**Expected output**

**Actual output**
sshd Log:
2964 2018-08-16 13:23:50.485 debug3: fd 5 is not O_NONBLOCK
2964 2018-08-16 13:23:50.485 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" "-R"
2964 2018-08-16 13:23:50.485 debug3: send_rexec_state: entering fd = 8 config len 233
2964 2018-08-16 13:23:50.485 debug3: ssh_msg_send: type 0
2964 2018-08-16 13:23:50.485 debug3: send_rexec_state: done
2404 2018-08-16 13:23:50.532 debug1: inetd sockets after dupping: 3, 3
2404 2018-08-16 13:23:50.532 Connection from 192.168.250.2 port 34690 on 192.168.250.3 port 22
2404 2018-08-16 13:23:50.548 debug1: Client protocol version 2.0; client software version OpenSSH_6.0
2404 2018-08-16 13:23:50.548 debug1: match: OpenSSH_6.0 pat OpenSSH* compat 0x04000000
2404 2018-08-16 13:23:50.548 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
2404 2018-08-16 13:23:50.548 debug2: fd 3 setting O_NONBLOCK
2404 2018-08-16 13:23:50.563 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" "-y"
2404 2018-08-16 13:23:50.563 debug2: Network child is on pid 2696
2404 2018-08-16 13:23:50.595 debug3: send_rexec_state: entering fd = 6 config len 233
2404 2018-08-16 13:23:50.595 debug3: ssh_msg_send: type 0
2404 2018-08-16 13:23:50.595 debug3: send_rexec_state: done
2404 2018-08-16 13:23:50.595 debug3: ssh_msg_send: type 0
2404 2018-08-16 13:23:50.595 debug3: ssh_msg_send: type 0
2404 2018-08-16 13:23:50.595 debug3: preauth child monitor started
2404 2018-08-16 13:23:50.610 debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
2404 2018-08-16 13:23:50.610 debug3: send packet: type 20 [preauth]
2404 2018-08-16 13:23:50.610 debug1: SSH2_MSG_KEXINIT sent [preauth]
2404 2018-08-16 13:23:50.641 debug3: receive packet: type 20 [preauth]
2404 2018-08-16 13:23:50.641 debug1: SSH2_MSG_KEXINIT received [preauth]
2404 2018-08-16 13:23:50.641 debug2: local server KEXINIT proposal [preauth]
2404 2018-08-16 13:23:50.641 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1 [preauth]
2404 2018-08-16 13:23:50.641 debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
2404 2018-08-16 13:23:50.641 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
2404 2018-08-16 13:23:50.641 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
2404 2018-08-16 13:23:50.641 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
2404 2018-08-16 13:23:50.641 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
2404 2018-08-16 13:23:50.641 debug2: compression ctos: none [preauth]
2404 2018-08-16 13:23:50.641 debug2: compression stoc: none [preauth]
2404 2018-08-16 13:23:50.641 debug2: languages ctos:  [preauth]
2404 2018-08-16 13:23:50.641 debug2: languages stoc:  [preauth]
2404 2018-08-16 13:23:50.641 debug2: first_kex_follows 0  [preauth]
2404 2018-08-16 13:23:50.641 debug2: reserved 0  [preauth]
2404 2018-08-16 13:23:50.641 debug2: peer client KEXINIT proposal [preauth]
2404 2018-08-16 13:23:50.641 debug2: KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 [preauth]
2404 2018-08-16 13:23:50.641 debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-rsa,ssh-dss [preauth]
2404 2018-08-16 13:23:50.641 debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se [preauth]
2404 2018-08-16 13:23:50.641 debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se [preauth]
2404 2018-08-16 13:23:50.641 debug2: MACs ctos: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96 [preauth]
2404 2018-08-16 13:23:50.641 debug2: MACs stoc: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96 [preauth]
2404 2018-08-16 13:23:50.641 debug2: compression ctos: none,zlib@openssh.com,zlib [preauth]
2404 2018-08-16 13:23:50.641 debug2: compression stoc: none,zlib@openssh.com,zlib [preauth]
2404 2018-08-16 13:23:50.641 debug2: languages ctos:  [preauth]
2404 2018-08-16 13:23:50.641 debug2: languages stoc:  [preauth]
2404 2018-08-16 13:23:50.641 debug2: first_kex_follows 0  [preauth]
2404 2018-08-16 13:23:50.641 debug2: reserved 0  [preauth]
2404 2018-08-16 13:23:50.641 debug1: kex: algorithm: ecdh-sha2-nistp256 [preauth]
2404 2018-08-16 13:23:50.641 debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
2404 2018-08-16 13:23:50.641 debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1 compression: none [preauth]
2404 2018-08-16 13:23:50.641 debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1 compression: none [preauth]
2404 2018-08-16 13:23:50.641 debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
2404 2018-08-16 13:23:50.829 debug3: receive packet: type 30 [preauth]
2404 2018-08-16 13:23:50.844 debug3: mm_key_sign entering [preauth]
2404 2018-08-16 13:23:50.844 debug3: mm_request_send entering: type 6 [preauth]
2404 2018-08-16 13:23:50.844 debug3: mm_request_receive entering
2404 2018-08-16 13:23:50.844 debug3: monitor_read: checking request 6
2404 2018-08-16 13:23:50.844 debug3: mm_answer_sign
2404 2018-08-16 13:23:50.844 debug3: mm_answer_sign: hostkey proof signature 0077A1C8(100)
2404 2018-08-16 13:23:50.844 debug3: mm_request_send entering: type 7
2404 2018-08-16 13:23:50.844 debug2: monitor_read: 6 used once, disabling now
2404 2018-08-16 13:23:50.844 debug3: mm_key_sign: waiting for MONITOR_ANS_SIGN [preauth]
2404 2018-08-16 13:23:50.844 debug3: mm_request_receive_expect entering: type 7 [preauth]
2404 2018-08-16 13:23:50.844 debug3: mm_request_receive entering [preauth]
2404 2018-08-16 13:23:50.844 debug3: send packet: type 31 [preauth]
2404 2018-08-16 13:23:50.844 debug3: send packet: type 21 [preauth]
2404 2018-08-16 13:23:50.844 debug2: set_newkeys: mode 1 [preauth]
2404 2018-08-16 13:23:50.844 debug1: rekey after 4294967296 blocks [preauth]
2404 2018-08-16 13:23:50.844 debug1: SSH2_MSG_NEWKEYS sent [preauth]
2404 2018-08-16 13:23:50.844 debug1: expecting SSH2_MSG_NEWKEYS [preauth]
2404 2018-08-16 13:23:50.891 debug3: receive packet: type 21 [preauth]
2404 2018-08-16 13:23:50.891 debug1: SSH2_MSG_NEWKEYS received [preauth]
2404 2018-08-16 13:23:50.891 debug2: set_newkeys: mode 0 [preauth]
2404 2018-08-16 13:23:50.891 debug1: rekey after 4294967296 blocks [preauth]
2404 2018-08-16 13:23:50.891 debug1: KEX done [preauth]
2404 2018-08-16 13:23:51.109 debug3: receive packet: type 5 [preauth]
2404 2018-08-16 13:23:51.109 debug3: send packet: type 6 [preauth]
2404 2018-08-16 13:23:51.125 debug3: receive packet: type 50 [preauth]
2404 2018-08-16 13:23:51.125 debug1: userauth-request for user fmc service ssh-connection method none [preauth]
2404 2018-08-16 13:23:51.141 debug1: attempt 0 failures 0 [preauth]
2404 2018-08-16 13:23:51.141 debug3: mm_getpwnamallow entering [preauth]
2404 2018-08-16 13:23:51.141 debug3: mm_request_send entering: type 8 [preauth]
2404 2018-08-16 13:23:51.141 debug3: mm_request_receive entering
2404 2018-08-16 13:23:51.141 debug3: monitor_read: checking request 8
2404 2018-08-16 13:23:51.141 debug3: mm_answer_pwnamallow
2404 2018-08-16 13:23:51.141 debug2: parse_server_config: config reprocess config len 233
2404 2018-08-16 13:23:51.141 debug3: mm_answer_pwnamallow: sending MONITOR_ANS_PWNAM: 1
2404 2018-08-16 13:23:51.141 debug3: mm_request_send entering: type 9
2404 2018-08-16 13:23:51.141 debug2: monitor_read: 8 used once, disabling now
2404 2018-08-16 13:23:51.141 debug3: mm_getpwnamallow: waiting for MONITOR_ANS_PWNAM [preauth]
2404 2018-08-16 13:23:51.141 debug3: mm_request_receive_expect entering: type 9 [preauth]
2404 2018-08-16 13:23:51.141 debug3: mm_request_receive entering [preauth]
2404 2018-08-16 13:23:51.141 debug2: input_userauth_request: setting up authctxt for fmc [preauth]
2404 2018-08-16 13:23:51.141 debug3: mm_inform_authserv entering [preauth]
2404 2018-08-16 13:23:51.141 debug3: mm_request_send entering: type 4 [preauth]
2404 2018-08-16 13:23:51.141 debug3: mm_request_receive entering
2404 2018-08-16 13:23:51.141 debug3: monitor_read: checking request 4
2404 2018-08-16 13:23:51.141 debug3: mm_answer_authserv: service=ssh-connection, style=
2404 2018-08-16 13:23:51.141 debug2: monitor_read: 4 used once, disabling now
2404 2018-08-16 13:23:51.141 debug2: input_userauth_request: try method none [preauth]
2404 2018-08-16 13:23:51.141 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
2404 2018-08-16 13:23:51.141 debug3: send packet: type 51 [preauth]
2404 2018-08-16 13:23:51.250 debug3: receive packet: type 50 [preauth]
2404 2018-08-16 13:23:51.250 debug1: userauth-request for user fmc service ssh-connection method publickey [preauth]
2404 2018-08-16 13:23:51.250 debug1: attempt 1 failures 0 [preauth]
2404 2018-08-16 13:23:51.250 debug2: input_userauth_request: try method publickey [preauth]
2404 2018-08-16 13:23:51.250 debug3: userauth_pubkey: have ssh-rsa signature for RSA SHA256:XwqMaF84YjO9f8yuCb6ee3LcrbnsGzUZRnYil48RB/s [preauth]
2404 2018-08-16 13:23:51.250 debug3: mm_key_allowed entering [preauth]
2404 2018-08-16 13:23:51.250 debug3: mm_request_send entering: type 22 [preauth]
2404 2018-08-16 13:23:51.250 debug3: mm_request_receive entering
2404 2018-08-16 13:23:51.250 debug3: monitor_read: checking request 22
2404 2018-08-16 13:23:51.250 debug3: mm_answer_keyallowed entering
2404 2018-08-16 13:23:51.250 debug3: mm_answer_keyallowed: key_from_blob: 00737350
2404 2018-08-16 13:23:51.250 debug1: trying public key file C:\\Users\\FMC\\.ssh/authorized_keys
2404 2018-08-16 13:23:51.250 debug2: C:\\Users\\FMC\\.ssh/authorized_keys:1: check options: 'GlobalHMI Public Key \n'
2404 2018-08-16 13:23:51.250 debug2: C:\\Users\\FMC\\.ssh/authorized_keys:1: advance: 'Public Key \n'
2404 2018-08-16 13:23:51.250 debug1: C:\\Users\\FMC\\.ssh/authorized_keys:3: matching key found: RSA SHA256:XwqMaF84YjO9f8yuCb6ee3LcrbnsGzUZRnYil48RB/s
2404 2018-08-16 13:23:51.250 debug1: C:\\Users\\FMC\\.ssh/authorized_keys:3: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
2404 2018-08-16 13:23:51.250 Accepted key RSA SHA256:XwqMaF84YjO9f8yuCb6ee3LcrbnsGzUZRnYil48RB/s found at C:\\Users\\FMC\\.ssh/authorized_keys:3
2404 2018-08-16 13:23:51.250 debug3: mm_answer_keyallowed: publickey authentication: RSA key is allowed
2404 2018-08-16 13:23:51.250 debug3: mm_request_send entering: type 23
2404 2018-08-16 13:23:51.250 debug3: mm_key_allowed: waiting for MONITOR_ANS_KEYALLOWED [preauth]
2404 2018-08-16 13:23:51.250 debug3: mm_request_receive_expect entering: type 23 [preauth]
2404 2018-08-16 13:23:51.250 debug3: mm_request_receive entering [preauth]
2404 2018-08-16 13:23:51.250 debug3: mm_sshkey_verify entering [preauth]
2404 2018-08-16 13:23:51.250 debug3: mm_request_send entering: type 24 [preauth]
2404 2018-08-16 13:23:51.250 debug3: mm_request_receive entering
2404 2018-08-16 13:23:51.250 debug3: monitor_read: checking request 24
2404 2018-08-16 13:23:51.250 debug3: mm_answer_keyverify: publickey 00737390 signature verified
2404 2018-08-16 13:23:51.250 debug1: auth_activate_options: setting new authentication options
2404 2018-08-16 13:23:51.250 debug3: mm_request_send entering: type 25
2404 2018-08-16 13:23:51.250 Accepted publickey for fmc from 192.168.250.2 port 34690 ssh2: RSA SHA256:XwqMaF84YjO9f8yuCb6ee3LcrbnsGzUZRnYil48RB/s
2404 2018-08-16 13:23:51.250 debug1: monitor_child_preauth: fmc has been authenticated by privileged process
2404 2018-08-16 13:23:51.250 debug3: mm_get_keystate: Waiting for new keys
2404 2018-08-16 13:23:51.250 debug3: mm_request_receive_expect entering: type 26
2404 2018-08-16 13:23:51.250 debug3: mm_request_receive entering
2404 2018-08-16 13:23:51.250 debug3: mm_get_keystate: GOT new keys
2404 2018-08-16 13:23:51.250 debug3: mm_sshkey_verify: waiting for MONITOR_ANS_KEYVERIFY [preauth]
2404 2018-08-16 13:23:51.250 debug3: mm_request_receive_expect entering: type 25 [preauth]
2404 2018-08-16 13:23:51.250 debug3: mm_request_receive entering [preauth]
2404 2018-08-16 13:23:51.250 debug1: auth_activate_options: setting new authentication options [preauth]
2404 2018-08-16 13:23:51.250 debug2: userauth_pubkey: authenticated 1 pkalg ssh-rsa [preauth]
2404 2018-08-16 13:23:51.250 debug3: send packet: type 52 [preauth]
2404 2018-08-16 13:23:51.250 debug3: mm_request_send entering: type 26 [preauth]
2404 2018-08-16 13:23:51.250 debug3: mm_send_keystate: Finished sending state [preauth]
2404 2018-08-16 13:23:51.250 debug1: monitor_read_log: child log fd closed
2404 2018-08-16 13:23:51.250 debug1: generate_s4u_user_token: LsaLogonUser() failed: -1073741811 SubStatus 0.
2404 2018-08-16 13:23:51.250 debug3: unable to generate token for user fmc
2404 2018-08-16 13:23:51.250 debug1: generate_s4u_user_token: LsaLogonUser() failed: -1073741811 SubStatus 0.
2404 2018-08-16 13:23:51.250 error: unable to generate token on 2nd attempt for user fmc
2404 2018-08-16 13:23:51.250 error: unable to get security token for user fmc
2404 2018-08-16 13:23:51.250 fatal: fork of unprivileged child failed
2404 2018-08-16 13:23:51.250 debug1: do_cleanup

client Debug output:
OpenSSH_6.0p1, OpenSSL 1.0.0j 10 May 2012
debug1: Reading configuration data /tmp/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: ssh_connect: needpriv 0
debug1: Connecting to 192.168.250.3 [192.168.250.3] port 22.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug3: Incorrect RSA1 identifier
debug3: Could not load "id_dsa" as a RSA1 public key
debug1: identity file id_dsa type -1
debug1: identity file id_dsa-cert type -1
debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_7.7
debug1: match: OpenSSH_for_Windows_7.7 pat OpenSSH*
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.0
debug2: fd 3 setting O_NONBLOCK
debug3: load_hostkeys: loading entries for host "192.168.250.3" from file "/tmp/.ssh/known_hosts"
debug3: load_hostkeys: found key type ECDSA in file /tmp/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-rsa,ssh-dss
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug2: kex_parse_kexinit: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
debug2: kex_parse_kexinit: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: kex_parse_kexinit: none
debug2: kex_parse_kexinit: none
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug2: mac_setup: found hmac-sha1
debug1: kex: server->client aes128-ctr hmac-sha1 none
debug2: mac_setup: found hmac-sha1
debug1: kex: client->server aes128-ctr hmac-sha1 none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA 55:23:8c:58:4e:99:0d:76:c1:e7:64:40:7e:e6:e4:98
debug3: load_hostkeys: loading entries for host "192.168.250.3" from file "/tmp/.ssh/known_hosts"
debug3: load_hostkeys: found key type ECDSA in file /tmp/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys
debug1: Host '192.168.250.3' is known and matches the ECDSA host key.
debug1: Found key in /tmp/.ssh/known_hosts:1
debug1: ssh_ecdsa_verify: signature correct
debug2: kex_derive_keys
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: id_dsa ((nil))
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug3: start over, passed a different list publickey,password,keyboard-interactive
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: id_dsa
debug1: read PEM private key done: type RSA
debug3: sign_and_send_pubkey: RSA b7:72:19:bc:7c:7f:9b:46:56:61:0a:d4:69:6f:b0:3e
debug2: we sent a publickey packet, wait for reply
debug1: Authentication succeeded (publickey).
Authenticated to 192.168.250.3 ([192.168.250.3]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
Write failed: Broken pipe

**Comment by bagajjal** [comment]
@babakNouri - 
Please try the new version of openssh [v7.7.2.0](https://github.com/PowerShell/openssh-portable/releases/tag/v7.7.2.0).
