### ISSUE TITLE
Can't add keys to ssh-agent, communication with agent failed

### ISSUE THREAD

**Issue by draftsteve** [PowerShell/Win32-OpenSSH#1234]
**"OpenSSH for Windows" version**
>(Get-Item (Get-Command ssh).Source).VersionInfo.FileVersion
7.6.0.0

Installed in c:\Windows\System32\OpenSSH in the 1803 Windows update. 

**Client OperatingSystem** 
Windows 10 Pro 1803

**What is failing**
ssh-add can't add keys to the ssh-agent. 

**Expected output**
The keys are accepted and listed when `ssh-add -l` is run. 

**Actual output**
> ssh-add .\.ssh\secret.pem
Could not add identity ".\.ssh\secret.pem": communication with agent failed

> ssh-add -l
error fetching identities: communication with agent failed

output from ssh-agent.log:
4688 2018-08-16 15:19:37.613 error: LookupAccountNameW on SSHD account failed with 1789
4688 2018-08-16 15:19:37.615 fatal: failed to retrieve client details
13372 2018-08-16 15:32:40.157 error: LookupAccountNameW on SSHD account failed with 1789
13372 2018-08-16 15:32:40.157 fatal: failed to retrieve client details
972 2018-08-16 15:42:25.752 error: LookupAccountNameW on SSHD account failed with 1789
972 2018-08-16 15:42:25.752 fatal: failed to retrieve client details
9088 2018-08-16 15:47:46.669 error: LookupAccountNameW on SSHD account failed with 1789
9088 2018-08-16 15:47:46.672 fatal: failed to retrieve client details

There  doesn't seem to be an sshd.exe in C:\Windows\System32\OpenSSH. I think I'm just missing a setting somewhere because I've gotten this working on other Windows machines of the same version with no issue.

**Comment by manojampalam** [comment]
see if this helps: https://github.com/PowerShell/Win32-OpenSSH/issues/1133

**Comment by draftsteve** [comment]
I read through this issue. 

I am using posh-git so I tried deleting the environment variables SSH_AGENT_PID and SSH_AUTH_SOCK but they don't exist. I'm guessing I'm using a newer version of posh-git?

Not loading posh-git doesn't seem to help either and the ssh-agent service starts fine.

**Comment by manojampalam** [comment]
That check in ssh-agent can be removed as sshd now runs as SYSTEM. We'll fix it. 

As a workaround to unblock you, could you create/install a dummy sshd service like this:
`sc.exe create sshd binPath=C:\Windows\System32\OpenSSH\ssh.exe`

**Comment by draftsteve** [comment]
I created the dummy sshd service as described.

ssh-add now works as expected. Thank you @manojampalam! This was driving me crazy.

**Comment by silradsi** [comment]
Hi there ! Having the same issue, I believe, on OpenSSH 7.7.2.1. Outputs are the same, though ssh-agent service is running (set on automatic). I do not have posh-git, git, or sshd.

The workaround worked, though. Need more info ?

**Comment by ajrock** [comment]
> That check in ssh-agent can be removed as sshd now runs as SYSTEM. We'll fix it.
> 
> As a workaround to unblock you, could you create/install a dummy sshd service like this:
> `sc.exe create sshd binPath=C:\Windows\System32\OpenSSH\ssh.exe`

Sorry to reanimate a dead thread, but just wanted to chime in that this solution works even for this failure in Oct 2019, thank you very much!

**Comment by LukeCarrier** [comment]
@manojampalam are you able to give an indication as to when this might ship? This ticket is closed but the need to create a dummy `sshd` service is still present even in Insiders builds.

`ssh-agent` was disabled, and even after enabling refused to work until I created the dummy `sshd` service, on upgrade to 19569.1000.

**Comment by ISkomorokh** [comment]
The workaround is still relevant in July 2020!

**Comment by bagajjal** [comment]
@ISkomorokh - The fix be part of next windows release which is available in fall timeframe this year.

**Comment by lbotinelly** [comment]
> The workaround is still relevant in July 2020!
...do you mean September 2020?

**Comment by SomethingWithPhp** [comment]
workaround still relevant... winver 20H2

**Comment by LukeCarrier** [comment]
I think this saga will _finally_ be closed by #1693. Good job Microsoft, it only took two years 🎉

**Comment by ittayd** [comment]
@LukeCarrier , I installed openssh via chocolatery, but still have this error. Why do you think it is solved by that release?

**Comment by thomassuckow** [comment]
You can also just install the OpenSSH server windows feature to mitigate this issue even if you never start the openssh server service.

**Comment by rbreaves** [comment]
Still relevant sadly and yes the workaround above does work, cs.exe wrapper. Feels like this should have been a pretty high priority awhile ago, but at least there's indication that the fix is coming.

**Comment by moaxcp** [comment]
Just ran into this and the workaround fixed it. Thanks!

**Comment by cconrad** [comment]
Still a good workaround in February 2021. Thank you

**Comment by valentinovamsi** [comment]
worked like a charm, thank you :)

**Comment by ferdinandosimonetti** [comment]
Windows 10 20H2 build 19042.746.
Last friday my SSH Agent worked like a charm.
Today, I had to install OpenSSH Server to get rid of the
`error fetching identities: communication with agent failed`

**Comment by dsisnero** [comment]
Still needed workaround

**Comment by yangruan** [comment]
> That check in ssh-agent can be removed as sshd now runs as SYSTEM. We'll fix it.
> 
> As a workaround to unblock you, could you create/install a dummy sshd service like this:
> `sc.exe create sshd binPath=C:\Windows\System32\OpenSSH\ssh.exe`

I had to run powershell as administrator to run this, but then I could ssh-add in any other powershell terminal.

**Comment by wcarson** [comment]
March 2021...workaround still needed and still works

**Comment by cima** [comment]
ssh-add used to work until last week, this week it needs the workaround. This issue needs to be reopened.

**Comment by LeszekKalibrate** [comment]
winver 20H2
Applied fix and Github is working now, but getting error in BASH cmd now:

```
$ git pull
CreateProcessW failed error:193
ssh_askpass: posix_spawn: Unknown error
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by jbanks9** [comment]
> That check in ssh-agent can be removed as sshd now runs as SYSTEM. We'll fix it.
> 
> As a workaround to unblock you, could you create/install a dummy sshd service like this: `sc.exe create sshd binPath=C:\Windows\System32\OpenSSH\ssh.exe`

HAY I know this is old, hope you are still around. When I tried using the work around with my local user path I got the error:

[SC] OpenSCManager FAILED 5: Access is denied. 

Do you know how I am able to fix this error?

**Comment by Spaxe** [comment]
Hi @jbanks9 you need to run PowerShell with Administrator privileges. It worked for me just now.

**Comment by SlinkySlonkyOlivia** [comment]
Sorry to revive this thread; but the workaround unfortunately did not work for me, despite running in admin priv...
It only told me the service already exists, and ssh-add -l still no worky.
