### ISSUE TITLE
User principal name lookup failed for user

### ISSUE THREAD

**Issue by AWSmith0216** [PowerShell/Win32-OpenSSH#1235]
**"OpenSSH for Windows" version**
 `7.7.2.0`
 
**Server OperatingSystem**
 `Windows Server 2016 Datacenter`

**Client OperatingSystem**
`RedHat Linux 7.2`

**What is failing**
Unable to successfully authenticate using key based authentication. Password authentication works. Running with debug level logging, on the server side the output is:

> 8000 2018-08-21 15:44:21.029 debug3: fd 5 is not O_NONBLOCK
> 8000 2018-08-21 15:44:21.029 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" "-R"
> 8000 2018-08-21 15:44:21.035 debug3: send_rexec_state: entering fd = 8 config len 188
> 8000 2018-08-21 15:44:21.035 debug3: ssh_msg_send: type 0
> 8000 2018-08-21 15:44:21.035 debug3: send_rexec_state: done
> 6456 2018-08-21 15:44:21.099 debug1: inetd sockets after dupping: 3, 3
> 6456 2018-08-21 15:44:21.099 Connection from 10.11.12.13 port 34314 on 10.13.12.11 port 22
> 6456 2018-08-21 15:44:21.099 debug1: Client protocol version 2.0; client software version OpenSSH_6.6.1
> 6456 2018-08-21 15:44:21.099 debug1: match: OpenSSH_6.6.1 pat OpenSSH_6.6.1* compat 0x04000000
> 6456 2018-08-21 15:44:21.099 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
> 6456 2018-08-21 15:44:21.099 debug2: fd 3 setting O_NONBLOCK
> 6456 2018-08-21 15:44:21.145 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" "-y"
> 6456 2018-08-21 15:44:21.151 debug2: Network child is on pid 7336
> 6456 2018-08-21 15:44:21.151 debug3: send_rexec_state: entering fd = 6 config len 188
> 6456 2018-08-21 15:44:21.151 debug3: ssh_msg_send: type 0
> 6456 2018-08-21 15:44:21.151 debug3: send_rexec_state: done
> 6456 2018-08-21 15:44:21.151 debug3: ssh_msg_send: type 0
> 6456 2018-08-21 15:44:21.151 debug3: ssh_msg_send: type 0
> 6456 2018-08-21 15:44:21.151 debug3: preauth child monitor started
> 6456 2018-08-21 15:44:21.178 debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
> 6456 2018-08-21 15:44:21.178 debug3: send packet: type 20 [preauth]
> 6456 2018-08-21 15:44:21.178 debug1: SSH2_MSG_KEXINIT sent [preauth]
> 6456 2018-08-21 15:44:21.178 debug3: receive packet: type 20 [preauth]
> 6456 2018-08-21 15:44:21.178 debug1: SSH2_MSG_KEXINIT received [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: local server KEXINIT proposal [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1 [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: compression ctos: none [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: compression stoc: none [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: languages ctos:  [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: languages stoc:  [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: first_kex_follows 0  [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: reserved 0  [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: peer client KEXINIT proposal [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-rsa,ssh-dss [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se [preauth]
> 6456 2018-08-21 15:44:21.178 debug2: MACs ctos: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96 [preauth]
> 6456 2018-08-21 15:44:21.179 debug2: MACs stoc: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96 [preauth]
> 6456 2018-08-21 15:44:21.179 debug2: compression ctos: none,zlib@openssh.com,zlib [preauth]
> 6456 2018-08-21 15:44:21.179 debug2: compression stoc: none,zlib@openssh.com,zlib [preauth]
> 6456 2018-08-21 15:44:21.179 debug2: languages ctos:  [preauth]
> 6456 2018-08-21 15:44:21.179 debug2: languages stoc:  [preauth]
> 6456 2018-08-21 15:44:21.179 debug2: first_kex_follows 0  [preauth]
> 6456 2018-08-21 15:44:21.179 debug2: reserved 0  [preauth]
> 6456 2018-08-21 15:44:21.179 debug1: kex: algorithm: curve25519-sha256@libssh.org [preauth]
> 6456 2018-08-21 15:44:21.179 debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
> 6456 2018-08-21 15:44:21.179 debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none [preauth]
> 6456 2018-08-21 15:44:21.179 debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none [preauth]
> 6456 2018-08-21 15:44:21.179 debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
> 6456 2018-08-21 15:44:21.183 debug3: receive packet: type 30 [preauth]
> 6456 2018-08-21 15:44:21.188 debug3: mm_key_sign entering [preauth]
> 6456 2018-08-21 15:44:21.188 debug3: mm_request_send entering: type 6 [preauth]
> 6456 2018-08-21 15:44:21.188 debug3: mm_key_sign: waiting for MONITOR_ANS_SIGN [preauth]
> 6456 2018-08-21 15:44:21.188 debug3: mm_request_receive_expect entering: type 7 [preauth]
> 6456 2018-08-21 15:44:21.188 debug3: mm_request_receive entering [preauth]
> 6456 2018-08-21 15:44:21.188 debug3: mm_request_receive entering
> 6456 2018-08-21 15:44:21.188 debug3: monitor_read: checking request 6
> 6456 2018-08-21 15:44:21.188 debug3: mm_answer_sign
> 6456 2018-08-21 15:44:21.190 debug3: mm_answer_sign: hostkey proof signature 00808B80(100)
> 6456 2018-08-21 15:44:21.190 debug3: mm_request_send entering: type 7
> 6456 2018-08-21 15:44:21.190 debug2: monitor_read: 6 used once, disabling now
> 6456 2018-08-21 15:44:21.190 debug3: send packet: type 31 [preauth]
> 6456 2018-08-21 15:44:21.190 debug3: send packet: type 21 [preauth]
> 6456 2018-08-21 15:44:21.190 debug2: set_newkeys: mode 1 [preauth]
> 6456 2018-08-21 15:44:21.190 debug1: rekey after 4294967296 blocks [preauth]
> 6456 2018-08-21 15:44:21.190 debug1: SSH2_MSG_NEWKEYS sent [preauth]
> 6456 2018-08-21 15:44:21.190 debug1: expecting SSH2_MSG_NEWKEYS [preauth]
> 6456 2018-08-21 15:44:21.195 debug3: receive packet: type 21 [preauth]
> 6456 2018-08-21 15:44:21.196 debug1: SSH2_MSG_NEWKEYS received [preauth]
> 6456 2018-08-21 15:44:21.196 debug2: set_newkeys: mode 0 [preauth]
> 6456 2018-08-21 15:44:21.196 debug1: rekey after 4294967296 blocks [preauth]
> 6456 2018-08-21 15:44:21.196 debug1: KEX done [preauth]
> 6456 2018-08-21 15:44:21.246 debug3: receive packet: type 5 [preauth]
> 6456 2018-08-21 15:44:21.247 debug3: send packet: type 6 [preauth]
> 6456 2018-08-21 15:44:21.247 debug3: receive packet: type 50 [preauth]
> 6456 2018-08-21 15:44:21.247 debug1: userauth-request for user username service ssh-connection method none [preauth]
> 6456 2018-08-21 15:44:21.247 debug1: attempt 0 failures 0 [preauth]
> 6456 2018-08-21 15:44:21.247 debug3: mm_getpwnamallow entering [preauth]
> 6456 2018-08-21 15:44:21.247 debug3: mm_request_send entering: type 8 [preauth]
> 6456 2018-08-21 15:44:21.247 debug3: mm_getpwnamallow: waiting for MONITOR_ANS_PWNAM [preauth]
> 6456 2018-08-21 15:44:21.247 debug3: mm_request_receive_expect entering: type 9 [preauth]
> 6456 2018-08-21 15:44:21.247 debug3: mm_request_receive entering [preauth]
> 6456 2018-08-21 15:44:21.247 debug3: mm_request_receive entering
> 6456 2018-08-21 15:44:21.247 debug3: monitor_read: checking request 8
> 6456 2018-08-21 15:44:21.247 debug3: mm_answer_pwnamallow
> 6456 2018-08-21 15:44:21.247 debug2: parse_server_config: config reprocess config len 188
> 6456 2018-08-21 15:44:21.249 debug3: mm_answer_pwnamallow: sending MONITOR_ANS_PWNAM: 1
> 6456 2018-08-21 15:44:21.249 debug3: mm_request_send entering: type 9
> 6456 2018-08-21 15:44:21.249 debug2: monitor_read: 8 used once, disabling now
> 6456 2018-08-21 15:44:21.249 debug2: input_userauth_request: setting up authctxt for username [preauth]
> 6456 2018-08-21 15:44:21.249 debug3: mm_inform_authserv entering [preauth]
> 6456 2018-08-21 15:44:21.249 debug3: mm_request_send entering: type 4 [preauth]
> 6456 2018-08-21 15:44:21.249 debug2: input_userauth_request: try method none [preauth]
> 6456 2018-08-21 15:44:21.249 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
> 6456 2018-08-21 15:44:21.249 debug3: send packet: type 51 [preauth]
> 6456 2018-08-21 15:44:21.249 debug3: mm_request_receive entering
> 6456 2018-08-21 15:44:21.249 debug3: monitor_read: checking request 4
> 6456 2018-08-21 15:44:21.249 debug3: mm_answer_authserv: service=ssh-connection, style=
> 6456 2018-08-21 15:44:21.249 debug2: monitor_read: 4 used once, disabling now
> 6456 2018-08-21 15:44:21.250 debug3: receive packet: type 50 [preauth]
> 6456 2018-08-21 15:44:21.250 debug1: userauth-request for user username service ssh-connection method publickey [preauth]
> 6456 2018-08-21 15:44:21.250 debug1: attempt 1 failures 0 [preauth]
> 6456 2018-08-21 15:44:21.250 debug2: input_userauth_request: try method publickey [preauth]
> 6456 2018-08-21 15:44:21.250 debug1: userauth_pubkey: test pkalg ssh-rsa pkblob RSA SHA256:LDszOqF3eFw91M3I0tims9NEkFIqUSVuA+Cg/DyUM70 [preauth]
> 6456 2018-08-21 15:44:21.250 debug3: mm_key_allowed entering [preauth]
> 6456 2018-08-21 15:44:21.250 debug3: mm_request_send entering: type 22 [preauth]
> 6456 2018-08-21 15:44:21.250 debug3: mm_key_allowed: waiting for MONITOR_ANS_KEYALLOWED [preauth]
> 6456 2018-08-21 15:44:21.250 debug3: mm_request_receive_expect entering: type 23 [preauth]
> 6456 2018-08-21 15:44:21.250 debug3: mm_request_receive entering [preauth]
> 6456 2018-08-21 15:44:21.250 debug3: mm_request_receive entering
> 6456 2018-08-21 15:44:21.250 debug3: monitor_read: checking request 22
> 6456 2018-08-21 15:44:21.250 debug3: mm_answer_keyallowed entering
> 6456 2018-08-21 15:44:21.250 debug3: mm_answer_keyallowed: key_from_blob: 00806B20
> 6456 2018-08-21 15:44:21.250 debug1: trying public key file C:\\Users\\username\\.ssh/authorized_keys
> 6456 2018-08-21 15:44:21.251 debug1: C:\\Users\\username\\.ssh/authorized_keys:1: matching key found: RSA SHA256:LDszOqF3eFw91M3I0tims9NEkFIqUSVuA+Cg/DyUM70
> 6456 2018-08-21 15:44:21.251 debug1: C:\\Users\\username\\.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
> 6456 2018-08-21 15:44:21.251 Accepted key RSA SHA256:LDszOqF3eFw91M3I0tims9NEkFIqUSVuA+Cg/DyUM70 found at C:\\Users\\username\\.ssh/authorized_keys:1
> 6456 2018-08-21 15:44:21.251 debug3: mm_answer_keyallowed: publickey authentication test: RSA key is allowed
> 6456 2018-08-21 15:44:21.251 debug3: mm_request_send entering: type 23
> 6456 2018-08-21 15:44:21.251 debug3: send packet: type 60 [preauth]
> 6456 2018-08-21 15:44:21.251 debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa [preauth]
> 6456 2018-08-21 15:44:21.251 Postponed publickey for username from 10.11.12.13 port 34314 ssh2 [preauth]
> 6456 2018-08-21 15:44:21.269 debug3: receive packet: type 50 [preauth]
> 6456 2018-08-21 15:44:21.270 debug1: userauth-request for user username service ssh-connection method publickey [preauth]
> 6456 2018-08-21 15:44:21.270 debug1: attempt 2 failures 0 [preauth]
> 6456 2018-08-21 15:44:21.270 debug2: input_userauth_request: try method publickey [preauth]
> 6456 2018-08-21 15:44:21.270 debug3: userauth_pubkey: have ssh-rsa signature for RSA SHA256:LDszOqF3eFw91M3I0tims9NEkFIqUSVuA+Cg/DyUM70 [preauth]
> 6456 2018-08-21 15:44:21.270 debug3: mm_key_allowed entering [preauth]
> 6456 2018-08-21 15:44:21.270 debug3: mm_request_send entering: type 22 [preauth]
> 6456 2018-08-21 15:44:21.270 debug3: mm_key_allowed: waiting for MONITOR_ANS_KEYALLOWED [preauth]
> 6456 2018-08-21 15:44:21.270 debug3: mm_request_receive_expect entering: type 23 [preauth]
> 6456 2018-08-21 15:44:21.270 debug3: mm_request_receive entering [preauth]
> 6456 2018-08-21 15:44:21.270 debug3: mm_request_receive entering
> 6456 2018-08-21 15:44:21.270 debug3: monitor_read: checking request 22
> 6456 2018-08-21 15:44:21.270 debug3: mm_answer_keyallowed entering
> 6456 2018-08-21 15:44:21.270 debug3: mm_answer_keyallowed: key_from_blob: 00806B20
> 6456 2018-08-21 15:44:21.270 debug1: trying public key file C:\\Users\\username\\.ssh/authorized_keys
> 6456 2018-08-21 15:44:21.271 debug1: C:\\Users\\username\\.ssh/authorized_keys:1: matching key found: RSA SHA256:LDszOqF3eFw91M3I0tims9NEkFIqUSVuA+Cg/DyUM70
> 6456 2018-08-21 15:44:21.271 debug1: C:\\Users\\username\\.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
> 6456 2018-08-21 15:44:21.271 Accepted key RSA SHA256:LDszOqF3eFw91M3I0tims9NEkFIqUSVuA+Cg/DyUM70 found at C:\\Users\\username\\.ssh/authorized_keys:1
> 6456 2018-08-21 15:44:21.271 debug3: mm_answer_keyallowed: publickey authentication: RSA key is allowed
> 6456 2018-08-21 15:44:21.271 debug3: mm_request_send entering: type 23
> 6456 2018-08-21 15:44:21.271 debug3: mm_sshkey_verify entering [preauth]
> 6456 2018-08-21 15:44:21.271 debug3: mm_request_send entering: type 24 [preauth]
> 6456 2018-08-21 15:44:21.271 debug3: mm_sshkey_verify: waiting for MONITOR_ANS_KEYVERIFY [preauth]
> 6456 2018-08-21 15:44:21.271 debug3: mm_request_receive_expect entering: type 25 [preauth]
> 6456 2018-08-21 15:44:21.271 debug3: mm_request_receive entering [preauth]
> 6456 2018-08-21 15:44:21.271 debug3: mm_request_receive entering
> 6456 2018-08-21 15:44:21.271 debug3: monitor_read: checking request 24
> 6456 2018-08-21 15:44:21.273 debug3: mm_answer_keyverify: publickey 00806520 signature verified
> 6456 2018-08-21 15:44:21.273 debug1: auth_activate_options: setting new authentication options
> 6456 2018-08-21 15:44:21.273 debug3: mm_request_send entering: type 25
> 6456 2018-08-21 15:44:21.273 Accepted publickey for username from 10.11.12.13 port 34314 ssh2: RSA SHA256:LDszOqF3eFw91M3I0tims9NEkFIqUSVuA+Cg/DyUM70
> 6456 2018-08-21 15:44:21.273 debug1: monitor_child_preauth: username has been authenticated by privileged process
> 6456 2018-08-21 15:44:21.273 debug3: mm_get_keystate: Waiting for new keys
> 6456 2018-08-21 15:44:21.273 debug3: mm_request_receive_expect entering: type 26
> 6456 2018-08-21 15:44:21.273 debug3: mm_request_receive entering
> 6456 2018-08-21 15:44:21.273 debug3: mm_get_keystate: GOT new keys
> 6456 2018-08-21 15:44:21.273 debug1: auth_activate_options: setting new authentication options [preauth]
> 6456 2018-08-21 15:44:21.273 debug2: userauth_pubkey: authenticated 1 pkalg ssh-rsa [preauth]
> 6456 2018-08-21 15:44:21.273 debug3: send packet: type 52 [preauth]
> 6456 2018-08-21 15:44:21.273 debug3: mm_request_send entering: type 26 [preauth]
> 6456 2018-08-21 15:44:21.273 debug3: mm_send_keystate: Finished sending state [preauth]
> 6456 2018-08-21 15:44:21.276 debug1: monitor_read_log: child log fd closed
> 6456 2018-08-21 15:44:21.313 error: lookup_principal_name: User principal name lookup failed for user 'domain\username' (explicit: 5, implicit: 5)
> 6456 2018-08-21 15:44:21.314 debug1: generate_s4u_user_token: LsaLogonUser() failed. User 'domain\username' Status: 0xC0000062 SubStatus 0.
> 6456 2018-08-21 15:44:21.314 debug3: get_user_token - unable to generate token for user domain\username
> 6456 2018-08-21 15:44:23.643 error: lookup_principal_name: User principal name lookup failed for user 'domain\username' (explicit: 5, implicit: 5)
> 6456 2018-08-21 15:44:23.644 debug1: generate_s4u_user_token: LsaLogonUser() failed. User 'domain\username' Status: 0xC0000062 SubStatus 0.
> 6456 2018-08-21 15:44:23.644 error: get_user_token - unable to generate token on 2nd attempt for user domain\username
> 6456 2018-08-21 15:44:23.644 error: unable to get security token for user domain\username
> 6456 2018-08-21 15:44:23.644 fatal: fork of unprivileged child failed
> 6456 2018-08-21 15:44:23.644 debug1: do_cleanup

From looking at similar tickets I checked a couple things. The user in question does have a UPN set in AD. I ran the FixUserFilePermissions.ps1 and FixHostFilePermissions.ps1 just to confirm things were right. One thing potentially unique in my situation is that the domain the machine is joined to is not the domain with the user -- it has a one-way trust to the domain where the user actually lives.

Let me know if there is any other information of value I can provide.

**Comment by manojampalam** [comment]
From 
```
6456 2018-08-21 15:44:23.643 error: lookup_principal_name: User principal name lookup failed for user 'domain\username' (explicit: 5, implicit: 5)
6456 2018-08-21 15:44:23.644 debug1: generate_s4u_user_token: LsaLogonUser() failed. User 'domain\username' Status: 0xC0000062 SubStatus 0.
6456 2018-08-21 15:44:23.644 error: get_user_token - unable to generate token on 2nd attempt for user domain\username
6456 2018-08-21 15:44:23.644 error: unable to get security token for user domain\username
```
0xC0000062: 
STATUS_INVALID_ACCOUNT_NAME    
The name provided is not a properly formed account name.

@nomorefood any clue what might be wrong?

**Comment by NoMoreFood** [comment]
@manojampalam The STATUS_INVALID_ACCOUNT_NAME is just a result of passing NetBiosDomainName\SamAccountName to the call.  The code does it in an a desperate attempt after not being able to discover the UPN.  The real errors are the '5's returned from the TranslateNameW function on the first line -- which is the standard error  code for access denied.  Unrelated - glad to see your posting again; was worried when I hadn't seen much activity ;-)   

@AWSmith0216 Any idea why a name lookup call might fail with access denied in your environment?  Any special permissions in Active Directory or specialized security settings?  Update: Just saw your comment.  The computer account running the service will need to have the ability to read into the Active Directory instance that contains the user.

**Comment by NoMoreFood** [comment]
@manojampalam This could be a complication with name lookup in the one-way trust scenario I didn't anticipate.  I will try to reproduce in a few days.  If you happen to have any veterans in the AD/programming arena that you can ask about name translation in one-way trust scenarios, this may be a good question for them.

**Comment by smx-smx** [comment]
I'm experiencing the same problem here. I have a one way trust scenario, and the name lookup fails with access denied because the domain server denies anonymous enumeration of usernames (`TranslateNameW` fails).
The lookup happens on connect, so the connection gets closed before the user has a chance to supply its password.
I verified i can login to the server succesfully with the normal Windows authentication (RDP, PSExec, etc). and the resulting sshd log matches with the one supplied by the OP.

**Comment by NoMoreFood** [comment]
@smx-smx Not sure there's ever going to be a solution for this.  Due to needing a consistent format to to support robust group/user matching in the OpenSSH configuration, we settled on NetBiosDomainName\SamAccountName.   I know it's a drastic configuration change, but you may want investigate a two-way trust using selective authentication and just open up login access to the domain controllers for the SSH server computer account.

**Comment by ghost** [comment]
@NoMoreFood I'm hitting this as well on latest windows SSH. User account is Microsoft's Azure AD joined machine, but machine is workgroup (not domain joined / remote). 

Is there any way to enable login of this sort of user, or do I need to create a local user to SSH in as instead?
