### ISSUE TITLE
OpenSSh file based logging doesn't work for non-admin logons by default

### ISSUE THREAD

**Issue by luckerby** [PowerShell/Win32-OpenSSH#1236]
**"OpenSSH for Windows" version**
7.7.2.0
 
**Server OperatingSystem**
 `Windows Server 2016 Standard`

**Client OperatingSystem**
Windows 10 Version 1803 (OS Build 17134.167)

**What is failing**
Doing a _git fetch remote master_, whereby the remote is an SSH endpoint hosted on an OpenSSH server doesn't result in any reference to the commands invoked in the sshd.log. Within the sshd.config file logging has been turned up to DEBUG3.

**Expected output**
I was expecting at least one entry for _git-upload-pack_ being invoked, however there was nothing.

**Actual output**
After the logon, there's nothing explicit about the commands issued, as seen below:
4132 2018-08-22 12:15:16.227 debug3: LsaLogonUser Succeeded (Impersonation: 1)
4132 2018-08-22 12:15:16.243 debug3: spawning "C:\\Program Files\\OpenSSH-Win64\\sshd.exe" "-z"
4132 2018-08-22 12:15:16.243 User child is on pid 7924
4132 2018-08-22 12:15:16.243 debug3: send_rexec_state: entering fd = 5 config len 188
4132 2018-08-22 12:15:16.243 debug3: ssh_msg_send: type 0
4132 2018-08-22 12:15:16.243 debug3: send_rexec_state: done
4132 2018-08-22 12:15:16.243 debug3: ssh_msg_send: type 0
4132 2018-08-22 12:15:16.243 debug3: ssh_msg_send: type 0
4132 2018-08-22 12:15:16.243 debug3: ssh_msg_send: type 0
4132 2018-08-22 12:15:16.243 debug3: ssh_msg_send: type 0
4132 2018-08-22 12:15:16.508 debug3: mm_request_receive entering
4132 2018-08-22 12:15:16.508 debug1: do_cleanup

**Comment by manojampalam** [comment]
You are probably using a non-admin account. By default, only admins can log in sshd.log. You should see the logs once you adjust ACLs to allow "Write" access by your "user".

**Comment by luckerby** [comment]
Indeed, I was using a regular user. Following a few tests to determine the minimal rights needed, I've went ahead and delegated permissions to Authenticated Users against the folder that holds sshd.log as below (in my scenario Bypass Traverse Checking is on for everyone, therefore no additional "Traverse Folder" permission was required). I used Authenticated Users in order to catch any activity invoked remotely, regardless of user.

![image](https://user-images.githubusercontent.com/31319583/44516124-e4fb1700-a6cc-11e8-886a-3e8527e478fd.png)

One security issue I'm seeing is for a user to be able to (maliciously) remove data from the log. This could be done directly through the SSH connection, however trying to append manually to the file results in a "The process cannot access the file ... because it is being used by another process", probably due to a lock set by the sshd service when it starts...

**Comment by manojampalam** [comment]
Actually not, you are perhaps not opening the file in "share" mode. The security issue unfortunately exists when you open up permissions on sshd.log. The changes in permissions are only advised for temporarily diagnosing issues with a specific non-admin user.

**Comment by luckerby** [comment]
You're right, I wasn't using the "share" mode to open the file. Once this was done, as seen below using a FileStream in Powershell (inspired by [this](https://stackoverflow.com/questions/513260/how-to-open-a-file-for-non-exclusive-write-access-using-net)) any user could modify sshd.log at will.

![image](https://user-images.githubusercontent.com/31319583/44982769-a2182980-af7f-11e8-9c50-4ec889a6d116.png)

The whole thing however raises an interesting dilemma - either disallow access to the logs, but have unknown commands running remotely on the system invoked by unknown users, or have logging enabled for a subset of users but risk having any of those corrupt the log file. Or is there a way to restrict the people that can connect in the first place ?

**Comment by manojampalam** [comment]
Yes ofcourse. Check out AllowUsers in sshd_config.

**Comment by luckerby** [comment]
Thanks, Manoj.

**Comment by manojampalam** [comment]
Keeping this open for tracking purpose.
