### ISSUE TITLE
Reinstallation not setting up OpenSSH correctly

### ISSUE THREAD

**Issue by erik-johnson-king** [PowerShell/Win32-OpenSSH#1239]
Please answer the following

**"OpenSSH for Windows" version**
7.6.0.0
 
**Server OperatingSystem**
Windows 10 Pro

**What is failing**
Reinstallation of OpenSSH on Windows 10 does not seem to create the sshd service upon uninstallation and installation (as it did the first time I installed it). Running "ssh-keygen -A" in C:\Windows\System32\OpenSSH does not create the expected ssh_host_ed25519_key file. Running sshd.exe manually gives "Privilege separation user sshd does not exist".

**Comment by bagajjal** [comment]
There is no need to run "ssh-keygen -A" as sshd will automatically create the host keys.
Note that the host keys are created in "%programdata%\ssh\" location.

Follow our [troubleshooting steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps) to debug more.
