### ISSUE TITLE
Support ssh-keyscan

### ISSUE THREAD

**Issue by daboul** [PowerShell/Win32-OpenSSH#124]
Hi.

I'm failing to use the ssh-keyscan command, it returns:

getaddrinfo x.x.x.x: Either the application has not called WSAStartup, or WSAStartup failed.

Looks like the Winsock is not properly initialized, any ideas?

Thanks,
David.

**Comment by tylerapplebaum** [comment]
+1

I would also like to request this.

**Comment by manojampalam** [comment]
We'll investigate and see if its a low hanging fruit to get it online. Investigation will be done my May-End but there isn't any guarantee if this can be supported by that milestone.
