### ISSUE TITLE
Service fails to start 

### ISSUE THREAD

**Issue by JukEboXAuDiO** [PowerShell/Win32-OpenSSH#1240]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
7.7.2.0p Beta
 
**Server OperatingSystem**
Windows Server 2016 x64

**Client OperatingSystem**
Windows Server 2016 x64

**What is failing**
Service is not starting.
**Expected output**
Service Started
**Actual output**
Windows could not start the OpenSSH SSH Server service on local computer

Error 1067: The process terminated unexpectedly.

OpenSSH in location C:\Program Files\OpenSSH\
Keys in c:\ProgramData\SSH

**Comment by JukEboXAuDiO** [comment]
Did the fix using .FixHostFilePermissions.ps1, uninstalled, & reinstalled and this fixed the issue.

**Comment by EdwinCloud101** [comment]
go to this video, at 2:00 to save time, to see the solution:
https://youtu.be/gUOEaZb0gW8
