### ISSUE TITLE
AllowGroups Not Honored for Groups Whose CN Contains Whitespace

### ISSUE THREAD

**Issue by luckerby** [PowerShell/Win32-OpenSSH#1242]
**"OpenSSH for Windows" version**
7.7.2.0
 
**Server OperatingSystem**
Windows Server 2016

**Client OperatingSystem**
Windows 10 (version 1803)

**What is failing**
I'm having OpenSSH configured for authenticating several users based on SSH keys. I'm now trying to limit the users that can connect to the server, regardless if they're providing explicitly their password. Specifying AllowGroups in sshd_config works as expected for CN@domain (where CN stands for the canonical name of the group (the attribute listed under Active Directory Users and Computers)). However I'm having trouble specifying a group whose CN contains whitespace (eg _All Admins_)

**Expected output**
Successful authentication

**Actual output**
User domain\\user from 1.1.1.1 not allowed because none of user's groups are listed in AllowGroups

**Comment by manojampalam** [comment]
Please check https://github.com/PowerShell/Win32-OpenSSH/wiki/sshd_config,

You should use domain\username format. Principal names with spaces should be enclosed in double quotes

**Comment by luckerby** [comment]
My mistake, I didn't pay attention when reading the doc initially. For the domain group I'm using, it's clearly stated that the format to be used is as below. It worked perfectly.

AllowGroups "contoso\ssh users"

**Comment by manojampalam** [comment]
Not really. I added the entry upon looking at your issue :). Thanks for raising it in the first place.
