### ISSUE TITLE
Issue with pwsh.exe 6.1.0-rc1 New-PSSession using SSH Key Auth

### ISSUE THREAD

**Issue by pldmgg** [PowerShell/Win32-OpenSSH#1244]
Same issue posted here since not sure if OpenSSH-Win64 or pwsh issue: https://github.com/PowerShell/PowerShell/issues/7709

In this test scenario, zerotesting5.zero.lab (192.168.2.13) is the localhost and zerowin16sshb.zero.lab (192.168.2.53) is the Remote Host.

Relevant info about both machines:

- Both are running Windows 2016 Standard
- Both have pwsh 6.1.0-rc1 (and ONLY pwsh 6.1.0-rc1) installed
- Both are running OpenSSH-Win64 7.7.2.0 (ssh-agent and sshd services are Running)
- Both have the following sshd_config: https://gist.github.com/pldmgg/73ef10856bed885ffcf1df4d11560d72

From zerotesting5.zero.lab (localhost) in pwsh.exe, do the following:

```powershell
# This fails:
New-PSSession -HostName zerowin16sshb -UserName zero\zeroadmin -KeyFilePath "C:\Users\zeroadmin\.ssh\zeroadmin_090418-cert.pub"

# This fails:
New-PSSession -HostName zerowin16sshb -UserName zero\zeroadmin -KeyFilePath "C:\Users\zeroadmin\.ssh\zeroadmin_090418"

# This works:
ssh zeroadmin@zero@zerowin16sshb

# This works:
ssh -o "IdentitiesOnly=true" -i "C:\Users\zeroadmin\.ssh\zeroadmin_090418" -i "C:\Users\zeroadmin\.ssh\zeroadmin_090418-cert.pub" zeroadmin@zero@zerowin16sshb

# This works:
ssh -o "IdentitiesOnly=true" -i "C:\Users\zeroadmin\.ssh\zeroadmin_090418" zeroadmin@zero@zerowin16sshb
```

For both of the `New-PSSession` failures above, the error message is as follows:

```powershell
New-PSSession : [zerowin16sshb] There is an error processing data from the background process. Error reported: PowerShell 6.1.0-rc.1.
At line:1 char:1
+ New-PSSession -HostName zerowin16sshb -UserName zero\zeroadmin -KeyFi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : 2102,PSSessionOpenFailed
```

For both of the `New-PSSession` attempts, output of `sshd.exe -ddd` on zerowin16sshb is the following:

https://gist.github.com/pldmgg/95fc0a364c201896646fac59957cfe79

Not sure if this is an OpenSSH-Win64 issue or a pwsh.exe issue, but since the straight ssh commands work and `New-PSSession` doesn't, I'm leaning towards pwsh.exe. But I'm also thinking that it could be something like ssh.exe not telling pwsh.exe's `New-PSSession` that it's done whatever it's doing...

**Comment by pldmgg** [comment]
More information on this...still not solved, but I've narrowed down the problem to the sshd Subsystem invocation of pwsh. Still not clear whether this is a pwsh.exe or OpenSSH-Win64 problem...

The `ForceCommand pwsh.exe -NoProfile` option in my original sshd_config concealed the fact that the "successful" ssh commands were NOT in fact using Subsystem to put me in a pwsh.exe session. Instead, logs indicate that sshd was...

```
Starting session: shell on windows-pty for zero\\zeroadmin from 192.168.2.13 port 50944 id 0
```

...and then immediately running the `ForceCommand` to put me in pwsh.exe. To clarify, what I **should** be seeing here is...

```
Starting session: subsystem 'powershell' for zero\\zeroadmin from 192.168.2.13 port 51060 id 0
```

...which is what I see when I run `New-PSSession`. (My updated sshd_config comments-out the `ForceCommand` option : https://gist.github.com/pldmgg/2850f834889fc430c08e3fd4e735c3e3)

Unfortunately commenting out `ForceCommand` did not make it so that my ssh commands used `Starting session: subsystem...` - they were/are still showing `Starting session: shell`, and I did NOT end up in pwsh.exe (but Public Certificate Authentication worked).

So the first problem is figuring out why Subsystem is NOT being used with straight ssh commands, and it IS being used (and failing for some unknown reason) by the pwsh.exe `*-PSSession` cmdlets.

Updated sshd logs can be found here:

1) SSHD_Results_New-PSSession_No_DefaultShell_In_Registry: https://gist.github.com/pldmgg/6cf1a2e1ca02ae540062222fc50bbb63

2) SSHD_Results_SSHExe_No_DefaultShell_In_Registry:
https://gist.github.com/pldmgg/3fa040a73ce6f83385dbc05acb96cf1a

**Comment by manojampalam** [comment]
Just tried out. It seems to work find with the following commandline options as detailed in 
https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-6

pwsh -sshs -NoLogo -NoProfile


It does hang with just 
   pwsh.exe -NoProfile 
From your logs, it seems that this is your subsystem commandline. 

Please follow up with Powershell team if this commandline is expected to work

**Comment by pldmgg** [comment]
@manojampalam Not sure what you were looking at, but I didn't just have `pwsh.exe -NoProfile`...Everywhere I look it has `-sshs -NoLogo -NoProfile` included. Can you point out where you see that?

Please see my updated information that I literally posted seconds before you closed this item.

And just to be clear...you tried Public Certificate Authentication?

**Comment by manojampalam** [comment]
From the following in your logs
```
debug1: subsystem: exec() C:/Program Files/Powershell/6-preview/pwsh.exe -sshs -NoLogo -NoProfile
Starting session: forced-command (config) 'pwsh.exe -NoProfile' for zero\\zeroadmin from 192.168.2.13 port 63276 id 0
debug1: Executing command: "c:\\windows\\system32\\cmd.exe" /c "pwsh.exe -NoProfile" with no pty
```

On double checking, it does look like your subsystem commadline is correct, but its getting overridden by your ForceCommand specification. IF you remove it, it should work fine. 

Otherwise, I advice you to go over sshd_config documentation to understand the intricacies between ForceCommand, Subsystem and (windows specific) [DefaultShell](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH)
https://man.openbsd.org/sshd_config
https://github.com/PowerShell/Win32-OpenSSH/wiki/sshd_config

**Comment by pldmgg** [comment]
@manojampalam I did remove `ForceCommand` in the latest info I posted immediately preceding when you closed this item. It's pretty clear that Subsystem is not being honored when I use straight ssh commands, and **is** being honored when I use New-PSSession (but then fails from some unknown reason...)

Please let me know your thoughts on this updated info when you get a chance.

And just want to make sure...you tried Public Certificate Authentication?

**Comment by manojampalam** [comment]
Subsystem is not meant for straight ssh commands.

You may invoke a subsystem using ssh.exe with -s flag but you wouldn't want to do that.  

The subsystem you added for PS remoting is meant to understand PSRP protocol stream.

If your requirement is to run your plain ssh commands in a PS shell, you should be dealing with "Default Shell". 

By "Public Certificate Authentication" did you mean ssh certificate authentication? If so, it should not have anything to do with PS or its subsystem. We have E2E test cases that validate cert auth and they all passed fine with this release. I recommend checking your cert auth scenario in a default setup first, and let us know if you see any issues?

**Comment by pldmgg** [comment]
@manojampalam Right now, my requirement is to use Public Cert Auth and Subsystem sshd_config such that both ssh.exe and Enter-PSSession put me in a pwsh session on the remote host.

So far, I have not been able to accomplish this for both ssh.exe and `*-PSSession` cmdlets. The only scenarios that led to me being in a pwsh.exe session on a remote host (where both client and server machines are Windows OSes) are as follows:

SCENARIO 1: 
Without `DefaultShell` entry in the registry, with `ForceCommand pwsh.exe -NoProfile`  in sshd_config, with `Subsystem powershell C:/symlinks/pwsh.exe -sshs -NoLogo -NoProfile` in sshd_config.

- The ssh commands in my original post place me in a pwsh.exe on the Remote Host (SUCCESS)
- `*-PSSession` cmdlets on the client side fail for some unknown reason (FAILURE)
- NOTE: Eventhough `Subsystem...` is active in sshd_config, it is not honored when using ssh.exe. It is honored when using the `*-PSSession` cmdlets.
- IMPORTANT NOTE: I've just confirmed that using `ForceCommand pwsh.exe -sshs -NoLogo -NoProfile` as you suggested causes ssh.exe to hang on the client side - so `ForceCommand pwsh.exe -NoProfile` is the only thing that works for me in this scenario, and only with ssh.exe commands (`*-PSSession` cmdlets still fail in the same way)

SCENARIO 2:
With `DefaultShell` entry in the registry of `C:/Program Files/Powershell/6-preview/pwsh.exe` without `ForceCommand` in sshd_config, with `Subsystem powershell C:/symlinks/pwsh.exe -sshs -NoLogo -NoProfile` in sshd_config.`

- The ssh commands in my original post place me in a pwsh.exe on the Remote Host (SUCCESS)
- `*-PSSession` cmdlets on the client side fail for some unknown reason (FAILURE)
- NOTE: Eventhough `Subsystem...` is active in sshd_config, it is not honored when using ssh.exe. It is honored when using the `*-PSSession` cmdlets.

***For every other permutation of these three configuration settings (`DefaultShell`, `ForceCommand`, `Subsystem`) :***

- Attempting to connect interactively via the ssh commands outlined in my original post have either -
1) Placed me in cmd.exe on the remote host
2) Prevented me from connecting altogether
3) Hung indefinitely

- Attempting to connect via the `*-PSSession` cmdlets has never been successful under any circumstances.

Can you please confirm that you've tried Public Certificate Authentication specifically? If not, can you please reopen?

EDIT: Yes SSH Cert Auth is what I mean by Pub Cert Auth, and I see that you already confirmed that (sorry I missed that bit). But I'm 99% sure that's not the issue given the fact that I can actually authenticate using an SSH Cert. The problem is that when I use SSH Cert Auth, I can't get ssh.exe to honor the Subsystem setting to put me in pwsh and the pwsh cmdlets on the client side don't seem to work at all when specifying `-KeyFilePath`).
