### ISSUE TITLE
SSH Between 2 Windows Machines Using pwsh.exe and OpenSSH-Win64 with SSH Cert Auth

### ISSUE THREAD

**Issue by pldmgg** [PowerShell/Win32-OpenSSH#1246]
# Goal:

Enter an interactive pwsh.exe session on a (Windows) Remote Host using SSH Public Cert Authentication using BOTH ssh.exe AND pwsh.exe `*-PSSession` cmdlets

# Requirements:

- SSH Client must be on a Windows OS
- SSHD Server must be on a Windows OS
- SSH Cert Authentication must be used
- The `Subsystem` sshd_config option must be used
- The `ForceCommand` sshd_config option must NOT be used
- Optionally specify `DefaultShell` as pwsh.exe under `HKLM:\SOFTWARE\OpenSSH` if necessary

# Environment

Relevant info about ssh client and sshd server machines:

- zerotesting5.zero.lab (192.168.2.13) is the localhost (client) and zerowin16sshb.zero.lab (192.168.2.53) is the Remote Host (server).
- Both are running Windows 2016 Standard
- Both have pwsh 6.1.0-rc1 (and ONLY pwsh 6.1.0-rc1) installed
- Both are running OpenSSH-Win64 7.7.2.0
- ssh-agent Service is running on both machines (`sshd -ddd` is run manually on the sshd server for each test in order to collect logs)
- Each machine's Signed Host Cert (`ssh-rsa-cert-v01@openssh.com AAAA... C:\ProgramData\ssh\ssh_host_rsa_key`) is loaded in the ssh-agent for both client and server (not sure if this is necessary)
- zero\zeroadmin's SSH Cert `ssh-rsa-cert-v01@openssh.com AAAA... C:\Users\zeroadmin\.ssh\zeroadmin_090618_114109` is loaded in the ssh-agent on the client
- Baseline sshd_config is as follows: https://gist.github.com/pldmgg/2850f834889fc430c08e3fd4e735c3e3

# What Works Beyond Any Doubt:

Testing so far proves that SSH Certificate Authentication is configured properly since I can consistently get to an interactive cmd.exe session on the Remote Host via any of the following commands:

```
ssh zeroadmin@zero@zerowin16sshb

ssh -o "IdentitiesOnly=true" -i "C:\Users\zeroadmin\.ssh\zeroadmin_090618" -i "C:\Users\zeroadmin\.ssh\zeroadmin_090618-cert.pub" zeroadmin@zero@zerowin16sshb

ssh -o "IdentitiesOnly=true" -i "C:\Users\zeroadmin\.ssh\zeroadmin_090618" zeroadmin@zero@zerowin16sshb
```

For completeness sake, `C:\Users\zeroadmin\.ssh\zeroadmin_090618-cert.pub` is in this format:

```
ssh-rsa-cert-v01@openssh.com AAAA...<truncated>...Bg==
```

# What Does Not Work:
- I have not been able to get any of the `*-PSSession` pwsh.exe cmdlets to work under any circumstances (using SSH Cert Auth).
- The above ssh.exe commands NEVER honor the sshd_config `Subsystem` setting. What I SHOULD see in sshd logs is the following...

```
Starting session: subsystem 'powershell' for zero\\zeroadmin from 192.168.2.13 port 51060 id 0
```

...What I always end up seeing is the following...

```
Starting session: shell on windows-pty for zero\\zeroadmin from 192.168.2.13 port 50944 id 0
```

Full sshd logs can be found under the relevant SCENARIO sections below.

Side Note: Using the pwshe.exe `*-PSSession` cmdlets DOES honor `Subsystem` (i.e., I see the desired `Starting session: subsystem ...` in sshd logs), however, they never actually create a PSSession.

# The Closest I Got to Satisfying Requirements:

### Config Info (these are the ONLY things that are changed from the above sshd_config between testing scenarios)

- `DefaultShell` Entry in Registry - NO
- `ForceCommand pwsh.exe -NoProfile` implemented in sshd_config - YES
- `Subsystem powershell C:/symlinks/pwsh.exe -sshs -NoLogo -NoProfile` implemented in sshd_config -YES
(NOTE: `C:/symlinks/pwsh.exe` is a symlink to `C:/Program Files/Powershell/6-preview/pwsh.exe`)

### Result

- The aforementioned ssh commands place me in pwsh.exe on the Remote Host (SUCCESS)
- `*-PSSession` cmdlets on the client side fail for some unknown reason (FAILURE)
- Additional Notes:
1) `Subsystem` is NOT honored when using ssh.exe. `Subsystem` IS honored when using the `*-PSSession` cmdlets.
2) Changing `ForceCommand pwsh.exe -NoProfile` to `ForceCommand pwsh.exe -sshs -NoLogo -NoProfile` causes ssh.exe to hang on the client side, but things look okay on the sshd side

LOGS:

1) SSHExe_No_DefaultShell_In_Registry: https://gist.github.com/pldmgg/3fa040a73ce6f83385dbc05acb96cf1a
2) New-PSSession_No_DefaultShell_In_Registry: https://gist.github.com/pldmgg/6cf1a2e1ca02ae540062222fc50bbb63

### Config Info (these are the ONLY things that are changed from the above sshd_config between testing scenarios)

- `DefaultShell` Entry in Registry of `C:/Program Files/Powershell/6-preview/pwsh.exe` - YES
- `ForceCommand` implemented in sshd_config - NO
- `Subsystem powershell C:/symlinks/pwsh.exe -sshs -NoLogo -NoProfile` implemented in sshd_config -YES
(NOTE: `C:/symlinks/pwsh.exe` is a symlink to `C:/Program Files/Powershell/6-preview/pwsh.exe`)

### Result

- The aforementioned ssh commands place me in pwsh.exe on the Remote Host (SUCCESS)
- `*-PSSession` cmdlets on the client side fail for some unknown reason (FAILURE)
- Additional Notes:
1) `Subsystem` is NOT honored when using ssh.exe. `Subsystem` IS honored when using the `*-PSSession` cmdlets.

LOGS:
I can post this as public gists, but long story short, the same problems mentioned in the "What Does Not Work" section above apply.

## ALL OTHER SCENARIOS:

Trying config settings other than those outlined in the above 2 Scenarios always resulted in one of the following outcomes:

- Placed me in cmd.exe on the Remote Host
- Prevented me from connecting altogether
- Hung indefinitely on either Client or SSHD side

Attempting to connect using SSH Cert Auth via the `*-PSSession` cmdlets (i.e. the `-HostName`, `-KeyFilePath`, and optionally the `-SSHTransport` parameters) has never been successful under any circumstances. Specifically I tried the following under all testing scenarios that I attempted...

```powershell
New-PSSession -HostName zerowin16sshb -UserName zero\zeroadmin -KeyFilePath "C:\Users\zeroadmin\.ssh\zeroadmin_090618-cert.pub"

New-PSSession -HostName zerowin16sshb -UserName zero\zeroadmin -KeyFilePath "C:\Users\zeroadmin\.ssh\zeroadmin_090618"

New-PSSession -HostName zerowin16sshb -UserName zeroadmin -KeyFilePath "C:\Users\zeroadmin\.ssh\zeroadmin_090618-cert.pub"

New-PSSession -HostName zerowin16sshb -UserName zeroadmin -KeyFilePath "C:\Users\zeroadmin\.ssh\zeroadmin_090618"

New-PSSession -HostName zerowin16sshb -UserName zero\zeroadmin -KeyFilePath "C:\Users\zeroadmin\.ssh\zeroadmin_090618-cert.pub" -SSHTransport

New-PSSession -HostName zerowin16sshb -UserName zero\zeroadmin -KeyFilePath "C:\Users\zeroadmin\.ssh\zeroadmin_090618" -SSHTransport

New-PSSession -HostName zerowin16sshb -UserName zeroadmin -KeyFilePath "C:\Users\zeroadmin\.ssh\zeroadmin_090618-cert.pub" -SSHTransport

New-PSSession -HostName zerowin16sshb -UserName zeroadmin -KeyFilePath "C:\Users\zeroadmin\.ssh\zeroadmin_090618" -SSHTransport
```

Thanks in advance for any help!

**Comment by pldmgg** [comment]
From /u/ainesophaur on reddit (https://www.reddit.com/r/PowerShell/comments/9doeqm/has_anyone_successfully_been_able_to_get_to_an/)

"There's a github issue about this and ultimately it was stated that authing by key pair will not grant you a kerberos session.. So you're then unable to do remote powershell using kerberos or negotiate auth. Your options are to either sign in with username and password via ssh (which will give you a kerberos ticket) or you have to use basic auth for remote powershell"

This actually makes a lot of sense to me...is that what's going on here?

**Comment by manojampalam** [comment]
Not convinced about Kerberos session theory. If key based auth works, cert auth should work as well. Are you saying key based auth doesn't work either ?

Otherwise, some technical background pertaining to your scenarios:
A subsystem process is invoked via the configured shell. something like this
defaultshell.exe -c subsystem_commandline

In your case, you should be seeing something like this in your server side logs (with both DefaultShell and subsystem configured using pwsh.exe)
```
debug1: Executing command: "c:\\ps6.1.0-rc.1\\pwsh.exe" -c "C:\\PS6.1.0-rc.1\\pwsh.exe -sshs -NoLogo -NoProfile" with no pty
```

On my end, I was NOT able to geting Enter-PSSession working with both DefaultShell and subsystem configured using pwsh.exe (while it works with DefaultShell set to cmd.exe).

So it looks to me that pwsh.exe as a default shell would not allow you to work with pwsh.exe as PSRP subsystem.

**Comment by pldmgg** [comment]
> Not convinced about Kerberos session theory. If key based auth works, cert auth should work as well. Are you saying key based auth doesn't work either ?

Cert and Key based auth works, but only with ssh.exe. I've never been able to get it to work with the `*-PSSession` cmdlets (**between Windows machines** ).

Using ssh.exe, I can get to an interactive pwsh.exe on the remote host by **EITHER**
- Using a `DefaultShell` registry value of `C:\symlinks\pwsh.exe`; **OR**
- By using `ForceCommand pwsh.exe -NoProfile` in sshd_config - in which case having **no** `DefaultShell` entry in the registry **or** having a `DefaultShell` entry with value `C:\Windows\system32\cmd.exe` works.

I understand how the subsystem is **supposed** to be invoked. But I think the biggest problem that I'm having on sshd when using ssh.exe is that I NEVER get to see `with no pty`. It ALWAYS uses `pty` and NEVER honors `Subsystem powershell C:/symlinks/pwsh.exe -sshs -NoLogo -NoProfile`. (This includes `DefaultShell` in registry with value pointing to `C:\Windows\system32\cmd.exe` or `C:\symlinks\pwsh.exe` or no `DefaultShell` entry at all, **as well as** any permutation of `ForceCommand` in sshd_config or not using it at all.)

In contrast, when I use the `*-PSSession` cmdlets I ALWAYS see `with no pty`.

So, Problem Number 1 that I'm encountering is that ssh.exe is not honoring Subsystem under any circumstances.

Problem Number 2 is that I can't get any of the `*-PSSession` cmdlets to work under any circumstances.

Regarding Problem Number 2, I wanted to try and recreate your success where you saif:
> it works with DefaultShell set to cmd.exe

To be overly cautious, I wiped out all of my ssh keys from my ssh-agent and my filesystem so that the `*-PSSession` cmdlets give me a password prompt. Here's what happened

## SCENARIO A:
- `DefaultShell` value of "C:\Windows\system32\cmd.exe" in registry - YES
- sshd_config here: https://gist.github.com/pldmgg/4fcdded3fb5d2cfa95d136c6b5fda6d6

On the client side I see this:

```powershell
PS C:\Users\zeroadmin> New-PSSession -HostName zerowin16sshb -UserName zero\zeroadmin
zeroadmin@zero@zerowin16sshb's password:
New-PSSession : [zerowin16sshb] The background process reported an error with the following message: The SSH client session has ended with error message: Connection reset by 192.168.2.53 port 22.
At line:1 char:1
+ New-PSSession -HostName zerowin16sshb -UserName zero\zeroadmin
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : 2100,PSSessionOpenFailed
``` 

On the sshd side, I see this:
https://gist.github.com/pldmgg/671be4e6f9dd9ffff198bbe4b555cc2d

##RESULT:
It accepts zero\zeroadmin's password, but then throws this stuff...

```
CreateProcessAsUserW failed error:1314
fork of unprivileged child failed
```

## SCENARIO B:
Same as SCENARIO A, but this time using ssh.exe from the client (as opposed to `*-PSSession` cmdlets).

##RESULT:
It accepts zero\zeroadmin's password, but then throws this stuff...

```
CreateProcessAsUserW failed error:1314
fork of unprivileged child failed
```

## SCENARIO C:
Same as SCENARIO B (i.e. using ssh.exe), but this time using the sshd service as opposed running `sshd -ddd` manually.

##RESULT:
It accepts zero\zeroadmin's password, and puts me in cmd.exe on the remote host.


-------

At this point, I'd just be happy if we could just solve Problem Number 1 - i.e. why Subsystem is never honored when I use ssh.exe. I have a hunch this is the root of all of these issues.

**Comment by pldmgg** [comment]
@manojampalam After doing more reading, I'm starting to think that `Subsystem` never being honored when using ssh.exe interactively is by design? Can you confirm?

Assuming I'm correct about the above, then the main problem I'm having is how sshd is handling the `*-PSSession` cmdlets.

(NOTE: I had to use `psexec64 -s sshd -ddd` in order to run sshd as System in order to get these logs):

### Using Password Auth

sshd Logs...
(Problems after line 260)
https://gist.github.com/pldmgg/2b675389975c19d27ea17cc7da14e52e


On the client side, it just hangs...
```powershell
PS C:\Users\zeroadmin> New-PSSession -HostName zerowin16sshb
zeroadmin@ZERO@zerowin16sshb's password:

# I need the Ctrl-C here, otherwise it just hangs indefinitely
```

### Using SSH (RSA) Cert Auth:

sshd Logs...
(Problems after line 304)
https://gist.github.com/pldmgg/c0172dfbd8a867b5f5c52ae159c14bbd

On the client side...
```powershell
PS C:\Users\zeroadmin> New-PSSession -HostName zerowin16sshb -UserName zero\zeroadmin -KeyFilePath "C:\Users\zeroadmin\.ssh\zeroadmin_090918_121751-cert.pub"

# I need the Ctrl-C here, otherwise it just hangs indefinitely
```

**Comment by manojampalam** [comment]
@pldmgg think about any ssh session as something that connects 2 pipes (in and out) on client to 2 pipes on a target process in server. When you open up a remote session, you end up specifying what the target process is. In some cases it is explicit (when you invoke an explicit command) and in some case its indirect (when you invoke a subsystem) and in some cases its implicit (when you invoke an interactive shell)

By default, when you do an interactive session, you are connecting your client terminal pipes to a "shell" on your server side. Here "shell" is your server side process. 

When you do sftp, you are connecting sftp.exe and sftp-server.exe via ssh. In this case, sftp-server.exe is configured as a subsystem.

When you open up an interactive session (ssh target), yes you'll never hit any subsystem (since you did not say so). If you do a (ssh -s subsystemname target), then you are telling your server to launch a subsystem process that is configured as "subystemname" subsystem. HTH.

I just tried out your scenario E2E (with subsystem and without DefaultShell), and I was able to get -PSSession commandlets working for CertificateAuthentication. From your logs, I can only guess that your remote session process (pwsh.exe -nologo ....) is hung for some reason, that I dont know. 

Relevant entries from sshd_config
```
Subsystem   powershell C:\PS6.1.0-rc.1\pwsh.exe -sshs -NoLogo -NoProfile
TrustedUserCAKeys __PROGRAMDATA__\ssh\ca_userkeys.pub
```

**Comment by pldmgg** [comment]
Okay...I guess one last question before I chalk this up to some issue completely unique to my environment:

Is this what you see in your sshd logs for your working E2E test?

```
debug1: Executing command: "c:\\windows\\system32\\cmd.exe" /c "C:\PS6.1.0-rc.1\pwsh.exe -sshs -NoLogo -NoProfile" with no pty
```

**Comment by manojampalam** [comment]
Right

```
debug1: subsystem: exec() C:\\PS6.1.0-rc.1\\pwsh.exe -sshs -NoLogo -NoProfile
Starting session: subsystem 'powershell' for redmond\\manojamp from ::1 port 57840 id 0
debug1: Executing command: "c:\\windows\\system32\\cmd.exe" /c "C:\\PS6.1.0-rc.1\\pwsh.exe -sshs -NoLogo -NoProfile" with no pty
```

![image](https://user-images.githubusercontent.com/14185020/45328311-4e25bb80-b510-11e8-975a-f289de2b2fd2.png)

**Comment by pldmgg** [comment]
@manojampalam Thanks for working with me on this!

Unfortunately, I still haven't had any success getting the `*-PSSession` cmdlets to work between two Windows 2016 Standard machines. I've tried fresh VMs, different domains, always with the result where pwsh on the client Win16 machine hangs and I need to Ctrl+C.

I'm certain that I've followed all of the aforementioned guidance (symlinks, permissions, etc), but still no dice.

I'm not going to close this issue because I really feel like someone should be able to recreate what's happening with my environment. But I understand if a contributor wants to close this issue without a solution if the issue can't be recreated.

**Comment by pldmgg** [comment]
HOLY CRAP I figured it out!

My mistake was that I was creating the symlink to pwsh.exe directly as opposed to its parent directory, i.e.

```powershell
New-Item -ItemType SymbolicLink -Path "C:\symlinks\pwsh.exe" -Target $(Get-Command pwsh).Source
```

When I made a symlink to pwsh.exe's parent directory (and updated the Subsystem path in sshd_config), the `*-PSSession` cmdlets started working:

```powershell
New-Item -ItemType SymbolicLink -Path "C:\pwshRoot" -Target $($(Get-Command pwsh).Source | Split-Path -Parent)
```

Now we're firing on all cylinders (password auth, key auth, ssh cert auth)

Thanks for your help @manojampalam !
