### ISSUE TITLE
Why is this OpenSSH here not in Windows 10 features but ...

### ISSUE THREAD

**Issue by lejeczek** [PowerShell/Win32-OpenSSH#1248]
...instead Windows users when add feature(s) get old version(s)?

Could these two not be synchronized somehow? Having the latest beta(and/or stable) in Win 10 features would make lives of so many people a lot easier!
many thanks, L.

**Comment by manojampalam** [comment]
@JKeithB need your help explaining OpenSSH on GitHub and OpenSSH on Windows. Please write up a wiki page as you suggested.

**Comment by ghost** [comment]
@lejeczek the short answer is not new - Windows has a release schedule that takes time to "bake". They have to massively retest when components change to avoid breaks caused between checkins from different teams. RS5 and beyond will include a stable version of what we build in Github, but not necessarily the most recent updates. 
Full support for Windows releases prior to RS5 has been discussed, but is not currently something we can manage broadly.
