### ISSUE TITLE
CTRL-C  is not working in ssd.exe

### ISSUE THREAD

**Issue by Ventusfahrer** [PowerShell/Win32-OpenSSH#125]
when ssd is invoked in powershell or cmd CTRL-C is not working.

standard Escape Sequence ~. is also not working

Hence I am not able to abort a session / connection.

**Comment by manojampalam** [comment]
use Ctrl+Pause/Break

**Comment by Ventusfahrer** [comment]
well, if you where lucky to find this key on your laptop or modern (media) keyboard it will work.

On my Microsoft Sculpt Comfort Keyboard it is CTRL-Scroll. 

We are all used to use CTRL-C in console based programs, Cygwin's ssh does also support CTRL-C and the ssh standard Escape-Sequences. 

Why to go for an extra handling in win32-openssh (which I have to find and remember)?

regards

Peter

**Comment by manojampalam** [comment]
This is a current work around. We're planning on fixing this in May.

**Comment by manojampalam** [comment]
Please test out the latest release. Reopen if needed.
