### ISSUE TITLE
Subsysstem definition and relative file specification

### ISSUE THREAD

**Issue by LozBoz63** [PowerShell/Win32-OpenSSH#1250]
In Version 7.6.1.0 the sshd_config file could have a line in

   Subsystemsftp	sftp-server.exe

effectively allowing relative file addressing for subsystem. parameter.

With 7.7.2.0 a full file specification is now required, this seems a retrograde step.

    Subsystem	sftp	C:\Windows\System32\OpenSSH\sftp-server.exe

**Comment by bagajjal** [comment]
We made a bunch of enhancements from v7.6.1.0 to v7.7.2.0.

If default shell is cmd.exe then we pick the sftp-server.exe, scp.exe from the sshd.exe directory.
If default shell is NOT cmd.exe then PATH should have the sshd.exe directory.

Look at point 9 in  https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH 

![image](https://user-images.githubusercontent.com/23668037/45454459-d8992700-b698-11e8-8336-b2942f871d65.png)

**Comment by LozBoz63** [comment]
Hi,

Thank you for your explanation and I can confirm we had set the default shell as powershell, I hadn't realized the full impact of what was discussed in point 9.

May I say, I believe the choice of whether you use cmd.exe or powerShell.exe and the consequential impacts on the default PATH seem counter intuitive to me.

If both cmd.exe and Powershell.exe were hard coded to locate files in the sshd.exe folder this would seem sensible as they are the two Windows Shells, only one is going to cause a lot of confusion and support calls in the longer term I recon.
