### ISSUE TITLE
Unauthorised read & list access to folders and files

### ISSUE THREAD

**Issue by LozBoz63** [PowerShell/Win32-OpenSSH#1251]
OpenSSH for Windows  version 7.7.2.0
Windows Server 2012 R2 Standard

We have an account call Kits-Service that is not a member of any Window group on a server (including Users). However when we connect to the SFTP server and are able to navigate around and copy files out from folder trees we should not have access to because the Kits-Service user is not the Creatoir Owner and neither is it mentioned of in any group in the ACL for the folder / file.

**Comment by manojampalam** [comment]
SSH remote session processes run under the context of the authenticated user (in your case Kits-Service). Regular Windows ACL based permissions apply. If you want to restrict Kits-Service to a specific directory you may use [ChRoot](https://github.com/PowerShell/Win32-OpenSSH/wiki/sshd_config#chrootdirectory)
