### ISSUE TITLE
MotD duplicated when called from PowerShell Core

### ISSUE THREAD

**Issue by FranklinYu** [PowerShell/Win32-OpenSSH#1253]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
7.7.2.0
 
**Server OperatingSystem**
Ubuntu 16.04.5 LTS (Note: this issue doesn't seem to affect Ubuntu 18.04. Very weird.)

**Client OperatingSystem**
Windows 10 Enterprise

**What is failing**
[MotD](https://en.wikipedia.org/wiki/Motd_(Unix)) is displayed twice when calling from PowerShell Core 6.1.0. No such issue in PowerShell 5.1 from Windows 10.

**Expected output**
Display MotD once when logging in.

**Actual output**
Display MotD twice when logging in.

**Comment by FranklinYu** [comment]
If I use a build introduced in PowerShell/openssh-portable#338 then PowerShell 5.1 is also affected. Shall this hold that PR back?

**Comment by bagajjal** [comment]
Are you sure it's win32-openssh ssh client issue?
Have you tried the other ssh clients (WSL, Putty)?

I didn't see this issue when I tried to login from win10 machine to Ubuntu 16.04.5 LTS

![image](https://user-images.githubusercontent.com/23668037/45909502-fceeb500-bdb6-11e8-9a6d-9442a8bef1b3.png)

**Comment by DHowett-MSFT** [comment]
I see this on roughly 80% of connections to _all servers_. It's probably a clientside buffer reuse issue, not a server issue.

**Comment by FranklinYu** [comment]
@bagajjal PuTTY and the SSH from Git Bash works with the same servers without issue. If you are not able to reproduce it, would you like a `Vagrantfile` showing the issue? I can try to come up with one.

There is some interesting issue with one of the servers. Part of MotD is duplicated. Not sure if this helps debugging.

**Comment by bagajjal** [comment]
@franklinyu - After multiple retries, I am able to repro the issue.
Will try to fix it for the next release.

**Comment by janorn** [comment]
Any updates?

**Comment by janorn** [comment]
I get a random nr of motd between 1-3.

**Comment by DHowett-MSFT** [comment]
This also happens when the alternate screen buffer is exited (like when vim is closed.)

**Comment by maertendMSFT** [comment]
Fixed via: https://github.com/PowerShell/openssh-portable/pull/426
