### ISSUE TITLE
ESC[m does not work in ssh.exe

### ISSUE THREAD

**Issue by DmitryDonetsky** [PowerShell/Win32-OpenSSH#1257]
**"OpenSSH for Windows" version**
7.7.2.0
 
**Server OperatingSystem**
Any

**Client OperatingSystem**
Windows 7 x64 russian

**What is failing**
`ESC[m` does not restore default color attributes, only `ESC[0m` does work.
Wiki says about this:
`If no codes are given, CSI m is treated as CSI 0 m (reset / normal).`
https://en.wikipedia.org/wiki/ANSI_escape_code
GNU Turbo Vision port, really sends `ESC[m` on my case, during application exit.

**Expected output**
![bug2](https://user-images.githubusercontent.com/43574636/46068386-b8319800-c181-11e8-9297-87dd1e0897f0.jpg)

**Actual output**
![bug2_2](https://user-images.githubusercontent.com/43574636/46068426-cb446800-c181-11e8-8787-b6be66489094.jpg)

**Comment by maertendMSFT** [comment]
Proper xTerm support is only on Win10+.
