### ISSUE TITLE
No moduli file in C:\ProgramData\ssh or anywhere else I can find.

### ISSUE THREAD

**Issue by binkleym** [PowerShell/Win32-OpenSSH#1261]
Please answer the following

"OpenSSH for Windows" version**
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5. (7.7.2.1)
 
**Server OperatingSystem**
Windows 10 Home 1809

**Client OperatingSystem**
Windows 10 Home 1809

**What is failing**
There is no moduli file in C:\ProgramData\ssh or anywhere else on the filesystem that I can find.   I would like to substitute my own generated moduli file for the default.

**Expected output**
PS C:\   dir c:\ProgramData\ssh\moduli

     Directory: C:\ProgramData\ssh

-a---  10/3/2018  10:47AM     50000 moduli

**Actual output**
PS C:\   dir c:\ProgramData\ssh\moduli

dir:  Cannot find path 'C:\ProgramData\ssh\moduli' because it does not exist.

**Comment by maertendMSFT** [comment]
This is fixed in the latest release.
