### ISSUE TITLE
psftp SSH2_MSG_UNIMPLEMENTED

### ISSUE THREAD

**Issue by sanderaiaots** [PowerShell/Win32-OpenSSH#1262]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
`OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.4
 
**Server OperatingSystem**
Version 6.2 (Build 9200)
Windows 2012 server

**Client OperatingSystem**
Version 6.2 (Build 9200)
Windows 2012 server

**What is failing**
sftp with putty is getting SSH2_MSG_UNIMPLEMENTED error

PUTTY output:
Looking up host "localhost"
Connecting to 127.0.0.1 port 22
Server version: SSH-2.0-OpenSSH_for_Windows_7.7
Using SSH protocol version 2
We claim version: SSH-2.0-PuTTY_Release_0.63
Doing Diffie-Hellman group exchange
Disconnected: Server protocol violation: unexpected SSH2_MSG_UNIMPLEMENTED packet
Fatal: Disconnected: Server protocol violation: unexpected SSH2_MSG_UNIMPLEMENTED packet

**Expected output**
login would work

**Actual output**
Fatal: Disconnected: Server protocol violation: unexpected SSH2_MSG_UNIMPLEMENTED packet

SSHD log wasn't available unfortunenlty

**Comment by manojampalam** [comment]
Please share sshd logs. It looks like your scenario is not supported in OpenSSH. Did you try with a Unix target ?

**Comment by thomasaarholt** [comment]
Edit: The below was with Putty version 0.63. Updated to 0.70, and now it connected without issue.

I can reproduce this. ssh from cmd works, but via Putty I get the same error as above. I tried setting Putty to log "All session output", but the error appears to take place before the log is even created.

Screenshot:
![image](https://user-images.githubusercontent.com/2721423/47362580-fe244200-d6d4-11e8-8a8b-7e56805c8c3b.png)

**Comment by bagajjal** [comment]
@thomasaarholt - Can you answer @manojampalam questions.

**Comment by thomasaarholt** [comment]
Basically: as per my edit, this works with the latest Putty. I recommend @sanderaiaots tries that before any further investigation is made.  This

**Comment by thomasaarholt** [comment]
I only tried windows -> windows. Putty did not supply logs.

**Comment by bagajjal** [comment]
Please share the sshd.log (serverside) to verify if its a genuine bug.
Refer to our (troubleshooting steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps).

Also please try same scenario targetting to Linux.
