### ISSUE TITLE
Win32-OpenSSH treats public key authentication as double-hop

### ISSUE THREAD

**Issue by tylerapplebaum** [PowerShell/Win32-OpenSSH#1264]
**"OpenSSH for Windows" version**
7.7.2.0
 
**Server OperatingSystem**
Windows Server 2016 Datacenter

**Client OperatingSystem**
Windows 10 Enterprise

**What is failing**
When using public key authentication to authenticate to a domain-joined server, Active Directory treats this login as a double hop. Meaning, I cannot do things like import and use the ActiveDirectory module.

Things work fine when I use the AD authentication mechanism like:

ssh.exe adminusername@domain.org@servername.domain.org

Treated as double hop with:

ssh.exe -i .\id_rsa adminusername@domain.org@servername.domain.org

**Comment by bagajjal** [comment]
Please have a look at this https://github.com/PowerShell/Win32-OpenSSH/issues/139
