### ISSUE TITLE
Disable creation of local sshd user

### ISSUE THREAD

**Issue by ShawnCrocker** [PowerShell/Win32-OpenSSH#1267]
Please answer the following

**"OpenSSH for Windows" version**
July 2018 version
 
**Server OperatingSystem**
Windows Server 2012 R2 Standard

**Client OperatingSystem**
N/A

**What is failing**
Nothing

**Expected output**
Local sshd account NOT ceated

**Actual output**
PS H:\> Get-LocalUser

Name       Enabled Description                                             
----       ------- -----------                                             
localadmin True    Built-in account for administering the computer/domain  
localguest False   Built-in account for guest access to the computer/domain
sshd       True

**Comment by manojampalam** [comment]
PR out to remove sshd account dependency. https://github.com/PowerShell/openssh-portable/pull/348

**Comment by ShawnCrocker** [comment]
Already noted and ready to fix
