### ISSUE TITLE
domain\username not working for ssh -l 

### ISSUE THREAD

**Issue by Ventusfahrer** [PowerShell/Win32-OpenSSH#127]
In Windows we know at least two different naming formats when specifying accounts

- User Principal Name     (username@domain)
- Down-Level Logon Name  (domain\username)

(see also: https://msdn.microsoft.com/de-de/library/windows/desktop/aa380525(v=vs.85).aspx)

If the user is specified in the  Down-Level Logon Name format, ssh is **not** working.
(unfortunately the second format is much more popular than the first one)

If this is by design please check the input parameter and write an appropriate error message.

If this is a bug...

**Comment by dwimsey** [comment]
Are you escaping the \ in the command line you're using (assuming you're doing it from the command line)?

ssh DOMAIN\user@host

won't work, but

ssh DOMAIN\\user@host

will, because the backslash is escaped so it actually gets passed to ssh properly.

I can confirm that both work.

**Comment by quamrulmina** [comment]
Use user@DOMAIN format. The following will work for Win32 ssh port.
ssh -l user@DOMAIN host
ssh user@DOMAIN@host

**Comment by quamrulmina** [comment]
To my knowledge, Win32 OpenSSH ported sshd and ssh currently has not implemented DOMAIN\user formats but DOMAIN\user format is implemented. So to provide domain name explicitly, use user@DOMAIN format .

**Comment by manojampalam** [comment]
dup #17 See that issue thread for updates

**Comment by quamrulmina** [comment]
sshd code fixed now so that domain\username format now works for password logon. username@domain form also works like before. The issue was in win32 sshd server and not in the ssh client. Note:Public key logon still is limited for a local account and will not work for a domain account.

**Comment by postgrep** [comment]
What if i want to connect to a Windows machine which is in not in a Domain but in a Workgroup and the user i want to login with is not the local account but the Microsoft account?

i tried quamrulmina's proposals and just used WORKGROUP instead of a domainname, but as expected this did not work.

**Comment by Lawands** [comment]
ssh user@DOMAIN@host This worked very well

**Comment by babin93** [comment]
> Note:Public key logon still is limited for a local account and will not work for a domain account

@quamrulmina is this still true ?

**Comment by bagajjal** [comment]
@babin93 - No. We support domain account as well.

**Comment by drorlupu** [comment]
@bagajjal  - For pubkey - We noticed it works for domain users only if we put the authorized_keys file in their local .ssh folder. If they (the domain user) are local administrators and we use %PROGRAMDATA%\ssh\administrators_authorized_keys and remove it from the .ssh folder in their home folder it does not work.
When we repeated the above and used a local user instead (which is in "administrators" group) and did the same (without configuration change) it did work.

**Comment by bagajjal** [comment]
refer to
https://github.com/PowerShell/Win32-OpenSSH/wiki/Setup-public-key-based-authentication-for-windows.

You need to fix permissions of  %PROGRAMDATA%\ssh\administrators_authorized_keys

**Comment by drorlupu** [comment]
We did that via the powershell script provided in the zip
Fix...Permissions, but still not good.

**Comment by bagajjal** [comment]
@drorlupu , please provide the ssh client logs (ssh.exe -vvv user@ip) and [sshd server logs](https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities) with DEBUG3 enabled.
