### ISSUE TITLE
Getting “System error 1067” when trying to start OpenSSH service

### ISSUE THREAD

**Issue by ParatrooperJoe** [PowerShell/Win32-OpenSSH#1272]
**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
(NOTE:  I downloaded and installed the following version:  **v7.7.2.0p1-Beta**)

I get the following error when I try to run the above command:

Get-Command " The term 'sshd' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:13
+ ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
+                 ~~~~~~~~~~~~~~~~
      +CategoryInfo              : ObjectNotFound: (sshd:String) [Get-Command], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.Powershell.Commands.GetCommandCommand

Get-Item : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:12em (Get-Command sshd).Source).VersionInfo.FileVersion)
+               ~~~~~~~~~~~~~~~~~~
       + CategoryInfo           : InvalidData:  (:) [Get-Item], ParameterBindingValidationException
       + FullyQualifiedErrorId : ParamterArgumentValidationErrorNullNotAllowed,Microsoft.Powershell.Commands.GetItemCommand

 
**Server OperatingSystem**
 Windows Server 2012 R2 Standard

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
Open SSH Service will not load

**Expected output**
Open SSh Service starts succesfully

**Actual output**
Windows Could not start the OpenSSH SSH Server service on Local Computer.

Error 1067: The process terminated unexpectedly.

I am logged in as a Domain Admin, just FYI...

**Comment by bagajjal** [comment]
1) Make sure binary location has the Write permissions to just to SYSTEM, Administrator groups. Authenticated users should and only have Read and Execute.

2) Make sure your binary location path is in system path environment variable.

3) check if you have libcrypto.dll file in the same folder as sshd.

4) If noting works then try the steps mentioned here https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Comment by ParatrooperJoe** [comment]
Thanks for the reply...

For Number 1.  As far as I can tell, it is set correctly, although the current User (A Domain Admin account) is the owner of the OpenSSH Folder.

2.  It is set correctly as well

3.  It is in the same folder as sshd

4.  I have tried following the steps there but I do not ever get any logs output into the log folder?

**Comment by ParatrooperJoe** [comment]
When attempting to follow the troubleshooting tips, this is what I get in the Powershell window:

`PS C:\OpenSSH> sshd.exe -d
debug1: sshd version OpenSSH_for_Windows_7.7, LibreSSL 2.6.4
debug1: private host key #0: ssh-rsa SHA256:y4NgLL/zahQOED8rPpr5zx6iJq+EGSE5pal6HCdcpfg
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:Acp2taSeXhSlUOdMO1FS0srlQNzPCH6mq8LQaFYqsqw
debug1: private host key #2: ssh-ed25519 SHA256:9ehJLIGDA/TewQ6qYqP7C3WKbzN053JkIS14aMaKD2s
debug1: rexec_argv[0]='C:\\OpenSSH\\sshd.exe'
debug1: rexec_argv[1]='-d'
debug1: Bind to port 22 on ::.
Server listening on :: port 22.
debug1: Bind to port 22 on 0.0.0.0.
Server listening on 0.0.0.0 port 22.
debug1: Server will not fork when running in debugging mode.
Connection from 172.20.15.10 port 52883 on 172.20.15.10 port 22
debug1: Client protocol version 2.0; client software version OpenSSH_for_Windows_7.7
debug1: match: OpenSSH_for_Windows_7.7 pat OpenSSH* compat 0x04000000
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
debug1: sshd version OpenSSH_for_Windows_7.7, LibreSSL 2.6.4
debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
debug1: SSH2_MSG_KEXINIT sent [preauth]
debug1: SSH2_MSG_KEXINIT received [preauth]
debug1: kex: algorithm: curve25519-sha256 [preauth]
debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
debug1: rekey after 134217728 blocks [preauth]
debug1: SSH2_MSG_NEWKEYS sent [preauth]
debug1: expecting SSH2_MSG_NEWKEYS [preauth]
debug1: SSH2_MSG_NEWKEYS received [preauth]
debug1: rekey after 134217728 blocks [preauth]
debug1: KEX done [preauth]
debug1: userauth-request for user hpaba\\\\sshadmin service ssh-connection method none [preauth]
debug1: attempt 0 failures 0 [preauth]
debug1: userauth-request for user hpaba\\\\sshadmin service ssh-connection method keyboard-interactive [preauth]
debug1: attempt 1 failures 0 [preauth]
debug1: keyboard-interactive devs  [preauth]
debug1: auth2_challenge: user=hpaba\\\\sshadmin devs= [preauth]
debug1: kbdint_alloc: devices '' [preauth]
debug1: userauth-request for user hpaba\\\\sshadmin service ssh-connection method password [preauth]
debug1: attempt 2 failures 1 [preauth]
Accepted password for hpaba\\sshadmin from 172.20.15.10 port 52883 ssh2
debug1: monitor_child_preauth: hpaba\\sshadmin has been authenticated by privileged process
debug1: monitor_read_log: child log fd closed
debug1: Not running as SYSTEM: skipping loading user profile
CreateProcessAsUserW failed error:1314
fork of unprivileged child failed
debug1: do_cleanup
PS C:\OpenSSH>`

**Comment by bagajjal** [comment]
When you are running in debug mode, you can login as the current windows log-in user only.
Looks like the current user (hpaba\\\\sshadmin) is not the windows log-in user on the sshd server machine.

By default it's ETW logging. https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities

As per logs, your sshd service should start. If you run into any issues then enable the file based logging mentioned in the above URL and provide the sshd.log, ssh client logs (ssh -vvv user@ip)

**Comment by ParatrooperJoe** [comment]
So that only confuses me even more.

I do not understand why this is so hard to get going?

Guess i am ging to just have to find a 3rd party tool to accomplish this.... SFTP setup should not cause this much trouble

**Comment by ParatrooperJoe** [comment]
also, How am I going to collect logs of errors if the service will not even start?

**Comment by bagajjal** [comment]
@highpointacademy - Not sure why sshd didn't start as service but it does start in debug mode.
The easiest way to install openssh is through chocolatey (https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/readme.md). Chocolatey will take care of all the manual steps mentioned in our installation instructions. 

Please make sure you delete the existing openssh before you try the chocolatey.

If you follow our installation instructions (https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH) then you shouldn't run into any issues.

**Comment by amarruedo** [comment]
I had this exact same issue, the server only would start on debug mode and fail with "System error 1067" when started from services desktop app.

In my case, the issue was in the ownership of host private key files. They must be owned only by SYSTEM account. [Here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-Win32-OpenSSH#host-private-key-files) you can find how to fix this.

**Comment by justdaven** [comment]
Thank you for this @amarruedo . This fixed the issue for me as well.

**Comment by andrero** [comment]
Yes!!, Thank you.

This worked for me, thank you amarruedo.
on Windows 2008R2 I used the GUI to clean up the security of the \programdata\ssh folder as a whole(affecting all files within), when I removed the "creator" user and was left with only System and Administrator.... and system as the owner.  The sshd service was then allowed to start!

**Comment by goodis0** [comment]
I am having this issue as well - have tried following your install steps along with all help tips here and cannot get it to work.  Keep getting the same 1067 Error what can i post here to help debug?

**Comment by smnishko** [comment]
Thank you for this @amarruedo ! That works for me as well

**Comment by aisakuRT** [comment]
In my case the issue was with host files created by `.\ssh-keygen.exe -A` command. And in order to fix it I used PS1 `.\FixHostFilePermissions.ps1` that comes with Release OpenSSH zip file

**Comment by isaku-dev** [comment]
@ParatrooperJoe 
In my case the issue was with host files created by .\ssh-keygen.exe -A command which should be owned by ''NT AUTHORITY\SYSTEM'. And in order to fix it I used PS1 .\FixHostFilePermissions.ps1 that comes with Release OpenSSH zip file

**Comment by JimLomas** [comment]
> @ParatrooperJoe
> In my case the issue was with host files created by .\ssh-keygen.exe -A command which should be owned by ''NT AUTHORITY\SYSTEM'. And in order to fix it I used PS1 .\FixHostFilePermissions.ps1 that comes with Release OpenSSH zip file

WANT YOUR BABIES 😄
