### ISSUE TITLE
Escape characters in output

### ISSUE THREAD

**Issue by Mudusu** [PowerShell/Win32-OpenSSH#1275]
I am getting special characters when connecting from linux to Windows openssh.

[2J[1;1H[0;39;24;27;37;40mWindows PowerShell                                                              
[2;1HCopyright (C) 2014 Microsoft Corporation. All rights reserved.                  

[4;1HPS C:\Users\Administrator>                                                      [4;4HC:\Users\Administrator>                                                      [4;26H>                                                      [4;28H[4;28H

Any help please?

**Comment by bagajjal** [comment]
What is your windows version?
Windows 10 and above supports only xterm. 
Prior releases of windows supports only VT100.

Set your TERM env variable accordingly.

**Comment by fang123322** [comment]
I also encountered this situation, Java programs connect SSH services, returning these characters caused a lot of trouble, how to cancel the return of these characters?
