### ISSUE TITLE
Is the Win10 Native Client using OpenSSH's FIPS libraries when Windows is in FIPS mode?

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#1276]
Sorry not sure where else to put this so putting as an issue.  A conversation came up recently about whether we could replace SecureCRT now that Win10 has included this but I can't find any documentation anywhere here or on the Microsoft site about what this means in an FIPS environment and OpenSSH can be compiled in either mode as can it's libraries.  My assumption here is the new SSH module is using OpenSSH's crypto library and not SCHANNEL hence setting Windows to FIPS mode would have no impact on that; can anybody confirm the FIPS status of this newly included client?

**Comment by NoMoreFood** [comment]
Currently it does not use the Windows cryptography libraries so the global Windows FIPS compliance flags will have no effect on it.  LibreSSL is used for cryptography which is not FIPS validated/certified and does not attempt to, as far as I know, do anything in controlling cryptographic operations.

However, you can certainly control the ciphers OpenSSH uses so you can make it it operate in a way that is compliant with the spirit of FIPS; my guess is the default configuration of OpenSSH is probably pretty close.   I doubt that OpenSSH on Windows will be FIPS validated/certified anytime soon.

**Comment by ebmarquez** [comment]
It's very sad that the Windows OpenSSH client is not going to be FIPS mode compliant.  I suppose I can default back to something that works like putty.  It really sucks that we can have SSH but not have it work in secure environments.

**Comment by maertendMSFT** [comment]
No, Win32-OpenSSH is not FIPS compliant.
In the near future we will be moving back to OpenSSL to be FIPS compliant.
