### ISSUE TITLE
Multiple simultaneous connection from different users

### ISSUE THREAD

**Issue by alitimer** [PowerShell/Win32-OpenSSH#1277]
Is there any configuration setup to make OpenSSH able to support multiple client connections at the same time from different users?
I have it up and running, however, once another user logs in, doesn't allow me to connect anymore and says: `Permission denied, please try again`. So, if I log in back again will work then.

**If it is a terminal issue**
NO

**"OpenSSH for Windows" version**
v7.7.2.0p1-Beta
 
**Server OperatingSystem**
Platform     ServicePack     Version             VersionString
 Win32NT                         10.0.17134.0      Microsoft Windows NT 10.0.17134.0

**Client OperatingSystem**
Platform     ServicePack        Version             VersionString
 Win32NT                             10.0.15063.0     Microsoft Windows NT 10.0.15063.0

**What is failing**
Simultaneous multiple connection from different users

**Expected output**
Stabilized connection.

**Actual output**
Permission denied, please try again.

**Comment by bagajjal** [comment]
OpenSSH supports multiple connections from different users.

Please look into the sshd.log (DEBUG3 enabled) to investigate further.
1) Have the below config in %programdata%\ssh\sshd_config file
SyslogFacility LOCAL0
LogLevel DEBUG3
2)restart sshd to pickup the latest changes in sshd_config.
3) run your scenario
4) investigate the sshd.log failure messages

**Comment by alitimer** [comment]
Thanks for the comment. From this part of the log
`Failed password for USERNAME from IP port PORT ssh2`
we could figure out that it fails since it refers to the server based database for authentication. I tried with local standard/admin windows account and works fine.

**Comment by manojampalam** [comment]
What does this mean?
"refers to server based database for authentication"

Can you explain how the above authentication works. It doesn't sound like regular Windows authentication

**Comment by alitimer** [comment]
Correct.
The authentication is through [pGina](http://pgina.org/) which sits on top of Windows authentication based on pGina custom setting for non-local users. So, authentication happens by sending query to the online database (LDAP). 
**Comment:** pGina makes profile for each non-local user but doesn't store their passwords on local machine as per custom setting. So if connection to LDAP fails, user won't be able to login.

What happens is that when the next user is logged in, I cannot connect through *ssh* because *ssh*  doesn't know pGina and asking directly from Windows. It fails: `Permission denied, please try again.`  since the user is not local; For local user there's no issue as Windows knows them.
Maybe there would be some config set up for ***pGina <-> openSSH*** interaction/integrity which I launched a [ticket ](https://github.com/pgina/pgina/issues/359) for that.

**Comment by manojampalam** [comment]
Ok. Thanks for the info. We've never validated via pGina. I don't know what the issue on your end it but I'm sharing some technical details that may help you take this further. 
 
OpenSSH calls LogonUser* Windows APIs to perform authentication. It doesn't have any configuration/flexibility to use into any other forms of authentication/API calls.

**Comment by alitimer** [comment]
Thanks for sharing that.

As a summary:
In special case of non-Windows authentication you have to be logged-in to be able to connect via ssh with the same account (getting favor of cache). 
Otherwise, you need local accounts to be able to login simultaneously via ssh with multiple users. openSSH talks to the Windows active directory for authentication.

**Comment by alitimer** [comment]
UPDATE:
It works if you try to login with [ssh key](https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples), not user's password querying by third party authentication from online database.
