### ISSUE TITLE
Binary release violates the 3–BSD licence by not providing it

### ISSUE THREAD

**Issue by yecril71pl** [PowerShell/Win32-OpenSSH#1278]
Please answer the following

**"OpenSSH for Windows" version**
7.6.0.1
 
**Client OperatingSystem**
Windows 10 Pro

**What is failing**
There is no LICENCE in OpenSSH-Win64.zip

**Expected output**
OpenSSH-Win64.zip\LICENCE.TXT

**Actual output**

**Comment by GitMensch** [comment]
This possibly also applies to the installed version under C:\Windows\System32\OpenSSH\ (which has no LICENSE in it).
I'd suggest to include https://github.com/PowerShell/openssh-portable/blob/latestw_all/LICENCE as is.
