### ISSUE TITLE
Binary 32-bit releases have non-working sshd.exe

### ISSUE THREAD

**Issue by Drugoy** [PowerShell/Win32-OpenSSH#1279]
I've tried v7.7.2.0p1-Beta, v7.7.2.0p1-Beta and v0.0.24.0 - none of these 3 contain a sshd.exe that would work on 32-bit windows 7: upon executing windows just barks that it's not a windows 32 executable file.

**Comment by bingbing8** [comment]
@Drugoy, Could you double check your machine is 32-bits machine? I validated the [OpenSSH-Win32.zip](https://github.com/PowerShell/Win32-OpenSSH/releases/download/v7.7.2.0p1-Beta/OpenSSH-Win32.zip) is 32 bits. I tested on 32-bits win8 machine

**Comment by NoMoreFood** [comment]
At least for Windows 10 64-bit, I was able to run the OpenSSH 32-bit just fine.  This is what I would expect (most 32-bit applications run perfectly fine on a 64-bit system if the SysWoW64 subsystem is installed).  I do not have a 32-bit Windows 7 machine to test on though.  The executable look fine to me.

**Comment by Drugoy** [comment]
@bingbing8 yes, it is 32-bit. Even if it wasn't - I'd be able to execute 32-bit binary anyways.
Maybe it is just incomatible with Windows 7.

**Comment by bingbing8** [comment]
@Drugoy, I tried [OpenSSH-Win32.zip](https://github.com/PowerShell/Win32-OpenSSH/releases/download/v7.7.2.0p1-Beta/OpenSSH-Win32.zip) on x86 win7 sp1 machine, the binaries work fine. Can you check if the package you downloaded are 32 bits?

**Comment by NoMoreFood** [comment]
It may also be worthwhile to temporarily disable your antivirus solution to see if the behavior changes or clearing the internet-downloaded flag that might be set on them (using an NTFS stream).  You can do that by right-clicking on all files, go to properties, and chose the option to 'unblock'.

**Comment by bingbing8** [comment]
@Drugoy, you can check if the package you downloaded is 32 bits or 64 bits by dumpbin.exe shipped with visual studio:
```
"c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\dumpbin.exe"
d:\test\sshdtest\sshd.exe /headers
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file d:\test\sshdtest\sshd.exe

PE signature found

File Type: EXECUTABLE IMAGE

FILE HEADER VALUES
             14C machine (x86)
               5 number of sections
        5B5A10C4 time date stamp Thu Jul 26 11:19:48 2018
               0 file pointer to symbol table
               0 number of symbols
              E0 size of optional header
             102 characteristics
                   Executable
                   32 bit word machine
...
```
