### ISSUE TITLE
Delete key sends an escape sequence

### ISSUE THREAD

**Issue by yecril71pl** [PowerShell/Win32-OpenSSH#1282]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 7.6.0.1
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**
Windows 10 Pro
**What is failing**
[ Ctrl [ V ] ] [ Delete ]
**Expected output**
^?
**Actual output**
^[[3~

**Comment by bagajjal** [comment]
@yecril71pl - You are using a very old version. Please test the new release (https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.7.2.0p1-Beta)

**Comment by yecril71pl** [comment]
The new release immediately quits.

**Comment by bagajjal** [comment]
Are you able to establish the ssh connection successfully?
Please elaborate your issue.

**Comment by yecril71pl** [comment]
There is noting to elaborate.  Your ssh client just quits without doing anything.  The bundled one works.

**Comment by manojampalam** [comment]
Without logs, there is not way to guess what's going on. Please refer to https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps and get us client and server side logs when you get a chance.

**Comment by yecril71pl** [comment]
C:\Users\krzzel\Documents\M>C:\Users\krzzel\Downloads\OpenSSH-Win64\OpenSSH-Win64\SSH -v \*.compute.amazonaws.com
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.4
debug1: Reading configuration data \*/.ssh/config
debug1: \*/.ssh/config line 2: Applying options for \*.compute.amazonaws.com
debug1: Connecting to \*.compute.amazonaws.com [34.\*] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file \*.pem type -1
debug1: key_load_public: No such file or directory
debug1: identity file \*.pem-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH\* compat 0x04000000
debug1: Authenticating to \*.compute.amazonaws.com:22 as 'ec2-user'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:\*
debug1: Host '\*.compute.amazonaws.com' is known and matches the ECDSA host key.
debug1: Found key in \*/.ssh/known_hosts:17
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic
debug1: Next authentication method: publickey
debug1: Trying private key: \*.pem
debug1: Authentication succeeded (publickey).
Authenticated to \*.compute.amazonaws.com ([34.*]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: console supports the ansi parsing
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
[ec2-user@\* ~]$ exit
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0

logout
debug1: channel 0: free: client-session, nchannels 1
Connection to \*.compute.amazonaws.com closed.
Transferred: sent 2620, received 3092 bytes, in 304.2 seconds
Bytes per second: sent 8.6, received 10.2
debug1: Exit status 0

**Comment by NoMoreFood** [comment]
@yecril71pl So... to confirm... using the newest version of the client and authenticating against an OpenSSH 7.4 server: you simply connect, immediately press delete, and the session disconnects?  What shell are you running on the remote server?

**Comment by yecril71pl** [comment]
The session disconnected because I told the shell to exit.

**Comment by bagajjal** [comment]
Please reopen if you still have this issue.
