### ISSUE TITLE
Scrolling issue when at end visible terminal

### ISSUE THREAD

**Issue by hoshsadiq** [PowerShell/Win32-OpenSSH#1283]
**"OpenSSH for Windows" version**
7.7.2.0
 
**Server OperatingSystem**
Windows Server 2016 Datacenter

**Client OperatingSystem**
MacOS

**What is failing**
Output overwrites current line when going past last line of the visible window. Everything works until we reach the last line of terminal. See screenshot. As you can see, I do `ls` twice, however, the second time the full output doesn't get displayed as it's at the bottom of the visible terminal and thus gets cut off.

Potentially same as #568.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/600045/47504457-3017de80-d864-11e8-8dd8-3226806262fd.png">

**Comment by aduzsardi** [comment]
I'm having similar issues 
Server OS: 
```powershell
PS C:\Users\Administrator> Get-CimInstance -ClassName Win32_OperatingSystem | fl *                                              


Status                                    : OK                                                                                  
Name                                      : Microsoft Hyper-V Server 2016|C:\Windows|\Device\Harddisk0\Partition4               
FreePhysicalMemory                        : 14953708                                                                            
FreeSpaceInPagingFiles                    : 2490368                                                                             
FreeVirtualMemory                         : 17543988                                                                            
Caption                                   : Microsoft Hyper-V Server 2016
```
Server SSH:
```
PS C:\ProgramData> choco install openssh /SSHServerFeature /SSHAgentFeature /OverWriteSSHDConf /SSHLogLever:VERBOSE --force
Chocolatey v0.10.11
Installing the following packages:
openssh;/SSHServerFeature;/SSHAgentFeature;/OverWriteSSHDConf;/SSHLogLever:VERBOSE
By installing you accept licenses for the packages.
openssh v7.7.2.1 already installed. Forcing reinstall of version '7.7.2.1'.
 Please use upgrade if you meant to upgrade to a new version.
Progress: Downloading openssh 7.7.2.1... 100%

openssh v7.7.2.1 (forced) [Approved]
openssh package files install completed. Performing other installation steps.
The package openssh wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): Y
```

Client OS: Ubuntu 18.04
Client SSH: OpenSSH 7.6p1


Screen is mangled when running a command that has a lot of output , while connect to the windows openssh server.

**Comment by danielparks** [comment]
I'm seeing this with Windows Server 2016 and 2012r2.

The first time a user logs in (before their profile directory is created) the terminal works normally. Every time after that, it displays only to the last line in the terminal, as described above.

Clients: openssh ?? on macOS 10.13,  OpenSSH_7.8p1 on macOS 10.14, and OpenSSH_6.7p1 on Debian 8.
Server: openssh 7.7.1.1 installed with chocolatey.

**Comment by asdr** [comment]
I have a similar issue here.

After a certain number of lines displayed correctly, the next lines won't be displayed until I run "cls" command, which clears all screen, then I can see the same number of lines again and it stops displaying again.

I make the connection from a Mac OS iterm2 terminal to a Windows Server 2016 through a Centos 7.7.

This is the output of "ssh -v 192.168.10.63"
**OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017**
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 58: Applying options for *
debug1: Connecting to 192.168.10.63 [192.168.10.63] port 22.
debug1: Connection established.
debug1: identity file /home/username/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
**debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_8.1**
**debug1: match: OpenSSH_for_Windows_8.1 pat OpenSSH* compat 0x04000000**
debug1: Authenticating to 192.168.10.63:22 as 'username'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: curve25519-sha256 need=64 dh_need=64
debug1: kex: curve25519-sha256 need=64 dh_need=64
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: XXXXXXXXXXXXXXX
debug1: Host '192.168.10.63' is known and matches the ECDSA host key.
debug1: Found key in /home/username/.ssh/known_hosts:2
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/username/.ssh/id_rsa
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Trying private key: /home/username/.ssh/id_dsa
debug1: Trying private key: /home/username/.ssh/id_ecdsa
debug1: Trying private key: /home/username/.ssh/id_ed25519
debug1: Next authentication method: keyboard-interactive
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: password
username@192.168.10.63's password:

**Comment by bagajjal** [comment]
@asdr - You are using old version. We made lot of improvements in terminal experience for windows 10, windows server 2019. For other OS we provide the basic terminal experience.

In any case you shouldn't be seeing this issue with the opensshV8.1.0.0.

**Comment by alberto-gglez** [comment]
Hi, I am having this issue on Windows 10 Pro 15063 using a recent install of OpenSSH v8.1.0.0p1-Beta (the last one in the repo).
Any solution to this problem? Thanks in advance

**Comment by aduzsardi** [comment]
I doubt this was ever resolved

**Comment by dschmidt** [comment]
(I think) I see the very same issue, but interestingly enough I only see this on one server but not on another.

Both run up-to-date Windows Server 1809, both have PowerShell Core 7.1 set as Default Shell, sshd version is in both cases `OpenSSH_8.3p1, OpenSSL 1.1.1h  22 Sep 2020`. 

Interestingly enough on the machine on which the output is broken ctrl+c doesn't work either.
On the one with working scrolling output, ctrl+c is working too. 

It does not seem to make a difference whether Powershell subsystem is enabled or not. I'm running out of ideas to check what's different on those two machines... 

If there is anything else I can do to help debug this, let me know.
