### ISSUE TITLE
Compilation Error when comping with OpenSSL 

### ISSUE THREAD

**Issue by meiry** [PowerShell/Win32-OpenSSH#1285]
using the guide : 
https://github.com/PowerShell/Win32-OpenSSH/wiki/OpenSSH-64-bit-Build-and-Installation-Instructions

when trying to compile the openssh with open ssl using VC 2017 andOpenSSL 64 bit which i downloaded from here :   https://slproweb.com/products/Win32OpenSSL.html
version : 
Win64 OpenSSL v1.1.0i

the file do exist in :   
C:\OpenSSL-Win64\include\openssl\ossl_typ.h

i did try compiling both static and dynamic same error

Please answer the following

**Client OperatingSystem**
windows 10 64 bit
**What is failing**
compilation to windows 64 bit using VC 2017 
**Expected output**

**Actual output**
```
1>cipher-ctr.c
1>d:\dev\my\v8\openssh-portable-latestw_all\cipher-ctr.c(129): error C2079: 'aes_ctr' uses undefined struct 'evp_cipher_st'
1>d:\dev\my\v8\openssh-portable-latestw_all\cipher-ctr.c(131): error C2027: use of undefined type 'evp_cipher_st'
1>d:\dev\my\v8\openssh-portable-latestw_all\cipher-ctr.c(132): error C2224: left of '.nid' must have struct/union type
1>d:\dev\my\v8\openssh-portable-latestw_all\cipher-ctr.c(133): error C2224: left of '.block_size' must have struct/union type
1>d:\dev\my\v8\openssh-portable-latestw_all\cipher-ctr.c(134): error C2224: left of '.iv_len' must have struct/union type
1>d:\dev\my\v8\openssh-portable-latestw_all\cipher-ctr.c(135): error C2224: left of '.key_len' must have struct/union type
1>d:\dev\my\v8\openssh-portable-latestw_all\cipher-ctr.c(136): error C2224: left of '.init' must have struct/union type
1>d:\dev\my\v8\openssh-portable-latestw_all\cipher-ctr.c(137): error C2224: left of '.cleanup' must have struct/union type
1>d:\dev\my\v8\openssh-portable-latestw_all\cipher-ctr.c(138): error C2224: left of '.do_cipher' must have struct/union type
1>d:\dev\my\v8\openssh-portable-latestw_all\cipher-ctr.c(140): error C2224: left of '.flags' must have struct/union type
1>Done building project "libssh.vcxproj" -- FAILED.
```

**Comment by bingbing8** [comment]
@meiry, please follow https://github.com/PowerShell/Win32-OpenSSH/wiki/Building-OpenSSH-for-Windows-(using-LibreSSL-crypto) to build openssh with libreSSL. The steps work for VS 2017 too.
The link you used needs to be cleaned up.

**Comment by meiry** [comment]
@bingbing8  
I know , im looking for openssl support as my app using openssl

**Comment by bingbing8** [comment]
@meiry, to compile with openssl, please still follow https://github.com/PowerShell/Win32-OpenSSH/wiki/Building-OpenSSH-for-Windows-(using-LibreSSL-crypto)
except one difference: you need to replace the content of folder of LibreSSL with openssl follow the same file structure.
