### ISSUE TITLE
Win32-OpenSSH isn't for Windows

### ISSUE THREAD

**Issue by tsd64** [PowerShell/Win32-OpenSSH#1286]
Please answer the following

**"OpenSSH for Windows" version**
 Win32-OpenSSH-7.7.2.0
 
**Server OperatingSystem**
Windows 10

**What is failing**
The last two beta releases is forcing Cygwin to be installed.  This was fixed in 0.0.24.0 and at one point of the Beta releases, but now this isn't even a Windows application.  

First, REALLY? You have to give a full pathname to execute a Windows app?

C:\ssh\bin>sshd -D
sshd re-exec requires execution with an absolute path

C:\ssh\bin>sshd.exe -D
sshd re-exec requires execution with an absolute path

Second, why would I need to set the config option if the sshd_config is in the same directory?

C:\ssh\bin>c:\ssh\bin\sshd.exe -D
__PROGRAMDATA__\ssh/sshd_config: No such file or directory

Plus, with all of this, I am unable to start sshd as a service.

When will this product be created for Windows?

**Comment by manojampalam** [comment]
sshd -d 
Note -d instead of -D.

Otherwise, when running sshd in non-debug mode, you are expected to specify the full path, this is a security requirement that's the same on Unix.

**Comment by tsd64** [comment]
When did that change?  The -d option was always debug mode?  Also, you still didn’t answer forcing to add options to that shouldn’t be needed.
