### ISSUE TITLE
Readme Installation instructions are not relevant to 7.7.2

### ISSUE THREAD

**Issue by pixelrebel** [PowerShell/Win32-OpenSSH#1288]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 7.7.2

**What is failing**
There is no powershell install script (install-sshd.ps1) as described in the ReadMe.

**Comment by Geogboe** [comment]
@pixelrebel are you absolutely sure you're downloading the latest release from here: https://github.com/PowerShell/Win32-OpenSSH/releases/download/v7.7.2.0p1-Beta/OpenSSH-Win64.zip

The file contents of that archive appear like this for me: 

![image](https://user-images.githubusercontent.com/3868453/48513756-a2a82880-e82a-11e8-8168-37e14d611fff.png)

I've also redownloaded it to confirm.

**Comment by pixelrebel** [comment]
Awe shucks!  You are correct. I must have downloaded from the upstream repo by mistake.  Thank you @Geogboe for taking the time to provide a thorough response (even though I am making a silly mistake).  I look forward to playing with this!
