### ISSUE TITLE
sshd fails to start in Windows Server 1803 with Containers

### ISSUE THREAD

**Issue by cperras** [PowerShell/Win32-OpenSSH#1289]
Please answer the following

I tried following these directions: https://www.thomasmaurer.ch/2018/06/install-openssh-server-on-windows-server/

Pretty much none of these steps worked 'out of the box' (eg: ssh-agent, sshd services were disabled by default). 

I managed to get ssh-agent running, but I cannot get sshd to run.

**"OpenSSH for Windows" version**
7.6.0.0
 
**Server OperatingSystem**
Windows Server Datacenter
(Windows Server 1803 with Containers)

**What is failing**
sshd

**Expected output**
sshd starts

**Actual output**
cannot find sshd.log (i see an empty ssh-agent.log file)
cannot find anything in Application logs
System logs contain, eg:

   1469 Nov 15 01:43  Error       Service Control M...   3221232506 The OpenSSH SSH Server service terminated unexpectedly.  It has done this 8 time(s).
   1468 Nov 15 01:43  Information Service Control M...   1073748860 The OpenSSH SSH Server service entered the running state.

i can find no other clues on what could be wrong.

**Comment by manojampalam** [comment]
Please follow steps here - https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps
