### ISSUE TITLE
7.9: cannot start pty session

### ISSUE THREAD

**Issue by DHowett-MSFT** [PowerShell/Win32-OpenSSH#1290]
Please answer the following

**"OpenSSH for Windows" version**
Latest build from openssh-portable.
 
**Server OperatingSystem**
18252

**Client OperatingSystem**
18252

**What is failing**
Any session that requires a TTY..

**Log**

```
13028 2018-11-15 13:11:52.781 Starting session: shell on windows-pty for redmond\\duhowett from 10.83.110.77 port 52286 id 0
13028 2018-11-15 13:11:52.781 debug2: fd 11 setting O_NONBLOCK
13028 2018-11-15 13:11:52.781 debug2: fd 12 setting O_NONBLOCK
13028 2018-11-15 13:11:52.781 debug2: fd 13 setting O_NONBLOCK
13028 2018-11-15 13:11:52.781 debug2: fd 14 setting O_NONBLOCK
13028 2018-11-15 13:11:52.781 debug2: fd 15 setting O_NONBLOCK
13028 2018-11-15 13:11:52.781 debug2: fd 16 setting O_NONBLOCK
13028 2018-11-15 13:11:52.782 debug3: shell: "c:\\windows\\system32\\windowspowershell\\v1.0\\powershell.exe"
13028 2018-11-15 13:11:52.782 debug3: shell_option: /c
13028 2018-11-15 13:11:52.782 debug3: This windows OS supports conpty
13028 2018-11-15 13:11:52.782 debug3: pty commandline: C:\\WINDOWS\\system32\\conhost.exe --headless --width 108 --height 45 --signal 0x1bc -- "c:\\windows\\system32\\windowspowershell\\v1.0\\powershell.exe"
13028 2018-11-15 13:11:52.815 error: cannot get process handle: 87
```

**Comment by DHowett-MSFT** [comment]
By "latest", I mean https://github.com/PowerShell/openssh-portable/commit/4666c11e0eec6b8f59ecc037089c054fa948bbbf

**Comment by DHowett-MSFT** [comment]
I believe the code at [win32_pty.c:158](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/win32_pty.c#L158) skips over the initialization of `pid` at line 183. Therefore, when we try to `OpenProcess(...pid…)` at [win32-doexec.c:378](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/w32-doexec.c#L378), it fails.

**Comment by manojampalam** [comment]
Thanks for catching this. @bingbing8 can you follow up ?

**Comment by manojampalam** [comment]
@bingbing8 can you follow up ?

**Comment by bingbing8** [comment]
I will fix it

**Comment by DHowett-MSFT** [comment]
The function in win32_pty.c is also leaking `cmd_w` because of the early return.

**Comment by bingbing8** [comment]
@DarwinJS yes, realized that. the fix will contains both
