### ISSUE TITLE
How determine if running SCP from my profile?

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/Win32-OpenSSH#1291]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `7.6.1.0`
 
**Server OperatingSystem**
 `Windows 10 Pro`

**Client OperatingSystem**
`Windows 10 Pro`

I'd like to prevent processing of my entire PowerShell profile (PowerShell is set to the default shell on my server OS).  Is there an env var or something I can look at in order to bail early in my profile processing?

**Comment by bingbing8** [comment]
you can supply "-NoProfile -c" as value of DefaultShellCommandOption

**Comment by NoMoreFood** [comment]
@rkeithhill You can also put this as the first line of your profile (which incidentally also makes SFTP work if OpenSSH is not in your system path):

`If ([Environment]::CommandLine -like '* -c "sftp-server.exe"') { Start-Process 'C:\Program Files\OpenSSH\sftp-server.exe' -NoNewWindow -Wait; [Environment]::Exit(0) }`

**Comment by rkeithhill** [comment]
@bingbing8 I could do that but then I'd lose my profile goodies (like PSRL customization) for an interactive SSH session to that machine.

@NoMoreFood Good idea.  I ended up going with this test at the beginning of my profile:
```
if ((Test-Path Env:\SSH_CLIENT) -and !(Test-Path Env:\SSH_TTY)) { return }
```
It would be nice if there was a corresponding `DefaultNonInteractiveShellCommandOption`  in the registry which I would set to `-NoProfile -c`.
