### ISSUE TITLE
sshd stops responding to handshakes and hangs the client

### ISSUE THREAD

**Issue by masaeedu** [PowerShell/Win32-OpenSSH#1293]
**"OpenSSH for Windows" version**
`7.7.2.0`
 
**Server OperatingSystem**
`Windows Server 2012 R2 Standard`

**Client OperatingSystem**
Arch Linux

**What is failing**
Running a simple command `hostname` command repeatedly freezes the SSH server after a few iterations:

```
while true; do { ssh -i ~/.ssh/test_machine_rsa Administrator@192.168.33.223 hostname }; done
```

**Details**
I was intermittently seeing hangs in a tool I'm working on that uses ssh to communicate with a Windows SSH server with win32-OpenSSH installed. After investigating various other parts of the system (IO streams, process parenting) I eventually realized it was sshd itself that was causing the hangs. I tried using wireshark to inspect the traffic and sure enough, the server is no longer responding to the client's handshake.

For a while the client and server interact well, but after a certain point SSHD simply stops responding to the client's handshake attempts. SSHD itself seems to be under the impression that it's waiting for a response to a key exchange message, eventually times out, and breaks the connection. The `ssh` client on the other end sits forever waiting for a response to its handshake, so from the perspective of whoever spawned it appears to be working very hard.

# Debugging info

## SSHD log

https://gist.github.com/masaeedu/9b5c630f9f9fe2a447363155ba9967e4

(relevant part is https://gist.github.com/masaeedu/9b5c630f9f9fe2a447363155ba9967e4#file-gistfile1-txt-L5323 and the part immediately preceding that)

## Wireshark screenshots

Normal iteration

![image](https://user-images.githubusercontent.com/3674056/48735336-19bc3300-ec16-11e8-8d8a-94e2d3e94194.png)

Final iteration

![image](https://user-images.githubusercontent.com/3674056/48735267-e9749480-ec15-11e8-8b3e-637b0b81bbe3.png)

## Client side output

![image](https://user-images.githubusercontent.com/3674056/48735837-753af080-ec17-11e8-8bfe-58dcdd111064.png)

**Comment by masaeedu** [comment]
Another interesting thing here is that it seems, like clockwork, to happen every 20th time (at least for this input). Maybe there's some kind of periodic thing happening in the background that triggers the bug.

**Comment by bingbing8** [comment]
@masaeedu, I am seeing similar behavior when test in appveyor. Investigating.

**Comment by masaeedu** [comment]
I can reproduce this 100% of the time in my environment (I have a VM snapshot), so if there's some additional information that can be collected using a modified build with additional logging, please let me know.

**Comment by bingbing8** [comment]
@masaeedu, I can't repro on win10. I will try to repro it on win2k12R2. Will let you know if more information is needed. Appreciate your help

**Comment by masaeedu** [comment]
Any luck with this @bingbing8? Happy to collect any additional data or repro information. This is currently blocking use of win32-OpenSSH and I'm currently having to port stuff to Cygwin SSH.

**Comment by bingbing8** [comment]
@masaeedu, unfortunately we did not have bandwidth to look into this. we will get back time once we get time.

**Comment by manojampalam** [comment]
@masaeedu can you do us a favor and get a dump of sshd service process. once you see it stop responding:
Follow these steps:
- Identify sshd process - TaskManager -> ServiceTab
![image](https://user-images.githubusercontent.com/14185020/49898943-301d6f00-fe0f-11e8-9ef0-d540bde4679c.png)
- Right click -> go to details
- Right click on sshd.exe process --> Create dump file

**Comment by NoMoreFood** [comment]
@masaeedu Any chance to create a dump? Also, if you insert a sleep to slow it down, does the behavior still happen "like clockwork"?

**Comment by masaeedu** [comment]
Sorry @NoMoreFood, @manojampalam, away on vacation at the moment and didn't have a chance to capture a dump. I'm going to set up the test environment and do this once I'm back at work.

**Comment by NoMoreFood** [comment]
@masaeedu I'd also be interested if you see any change in behavior when using the binaries I posted here: https://github.com/PowerShell/Win32-OpenSSH/issues/1301.

**Comment by masaeedu** [comment]
> Any chance to create a dump?

@NoMoreFood I've captured a dump file. Do you have an email I can send it to? It's too large to upload as an attachment here apparently.

One issue here is that I see several sshd processes in the details pane, although a few seconds after the hang occurs all but one disappear (the client just stays stuck forever though). I'm not sure which one I should be capturing a dump from, or, if I should be capturing them all, how to label them so they can be told apart.

> Also, if you insert a sleep to slow it down, does the behavior still happen "like clockwork"?

With a one second sleep I've still managed to reproduce it 3/3 times (so far).

> I'd also be interested if you see any change in behavior when using the binaries I posted here: #1301.

I tried out your binary and I can still see the hang occurring.

**Comment by masaeedu** [comment]
With a one second sleep I've still managed to reproduce it three times (so far).

**Comment by masaeedu** [comment]
@NoMoreFood The modified binaries don't fix the hang.

**Comment by manojampalam** [comment]
@masaeedu see instructions in https://github.com/PowerShell/Win32-OpenSSH/issues/1293#issuecomment-446745802 to find which sshd.exe process to dump.

**Comment by NoMoreFood** [comment]
@masaeedu Ok, thank you for testing my binaries.  After further analysis, most of the file I/O goes through a different set of calls so I don't think your issue is what I was thinking it could have been.  However, during my testing of rapid connections I did notice that I had to adjust the MaxStartups in sshd_config to a larger number (as shown below).  Since the one second sleep didn't change the behavior, I again doubt this is a problem for you unless your server is slow although it might be something you want to consider adjusting, in general.  

MaxSessions 512
MaxStartups 512

In addition to the sshd.exe dump, it might be valuable to capture one of the client sessions using ssh.exe -vvv to see if there's a particular part of the negotiation that's not responding.

**Comment by masaeedu** [comment]
@NoMoreFood The client logs and the wireshark dump shows that it always freezes when the client sends its version information to the server. On normal iterations the next thing that happens is the server responds with its own version information, but when the hang happens the server simply never responds.

I've uploaded the dump file here: http://do.masaeedu.com:8000/sshd.DMP

**Comment by masaeedu** [comment]
Regarding:

>  I did notice that I had to adjust the MaxStartups in sshd_config to a larger number (as shown below).

what happens if you don't adjust these values?

**Comment by NoMoreFood** [comment]
If you have many simultaneous connections, you need to adjust the value or the connection will not be processed.  A full description is provided here: https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Load_Balancing  I wasn't even aware of it until I saw the setting being processed when debugging the code.

**Comment by masaeedu** [comment]
After much more debugging I think there is something horribly wrong with our network, so I'm provisionally closing this issue and pursuing that avenue of investigation. If it turns out there is something wrong with ssh client/server I'll come back to this. Sorry for the (possibly) wild goose chase.

**Comment by manojampalam** [comment]
So it was working alright locally over loopback ?

**Comment by masaeedu** [comment]
@manojampalam Yes, it works fine if you ssh from the machine to itself. I was initially under the impression that the particular combination of client platform and version with the server was resulting in the issue (and so you wouldn't see it when attempting to ssh to loopback from Windows) but after testing with a variety of client platforms and versions (Windows with MSYS SSH, Cygwin SSH, Linux with OpenSSH 6.6 through 7.9) and finding the bug consistently, I'm fairly certain something on our network is eating packets.

**Comment by masaeedu** [comment]
Just following up to note that we have the smoking gun in our corporate firewall rules that was causing this issue. Sorry for the false alarm.

**Comment by masaeedu** [comment]
I will note though that it might be a bug in the SSH client in general (not specific to the Windows implementation) that it simply hangs instead of timing out if the server fails to respond with its version string.

I've tried adjusting various configuration options in my `~/.ssh/config` to try and get it to time out when the firewall breaks the connection like this, but without much success.
