### ISSUE TITLE
New-PSSession error "subsystem request failed on channel 0"

### ISSUE THREAD

**Issue by sunzcosmo** [PowerShell/Win32-OpenSSH#1296]
The problem keeps existing after I add the Subsystem, run 'sshd -T' shows that my config has already been loaded: 
```powershell
PS> sshd -T | select-string 'subsystem'

subsystem sftp sftp-server.exe
subsystem powershell c:\pwsh\pwsh.exe -sshs -NoLogo -NoProfile
```

The ssh cmd still can not figuring out the name 'powershell':
```powershell
PS> ssh root@10.90.183.191 -s powershell
Authorized users only. All activity may be monitored and reported.
Password:
subsystem request failed on channel 0
```

operation system:
```
PS>((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)
Windows 7 Professional
```

My openssh version is 
```
PS>((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
7.7.2.0
```
Powershell Version
```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by bingbing8** [comment]
@sunzcosmo , did you create symlink ```mklink /D c:\pwsh "C:\Program Files\PowerShell\6-preview"```?
following this [link](https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-6)

**Comment by sunzcosmo** [comment]
> @sunzcosmo , did you create symlink `mklink /D c:\pwsh "C:\Program Files\PowerShell\6"`?
> following this [link](https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-6)

I'm pretty sure I have already done it:
```powershell
PS C:\> C:\pwsh\pwsh.exe
PowerShell 6.1.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\>
```
yet the problem keeps reacurring:
```powershell
PS> New-PSSession -HostName 121.107.1.18 -UserName root
The authenticity of host '121.107.1.18 (121.107.1.18)' can't be established.
ECDSA key fingerprint is SHA256:+UhCwkkqDAdvuGCpW21uF2J6ToSizf0IuFJWYa4+tNw.
Are you sure you want to continue connecting (yes/no)?
Warning: Permanently added '121.107.1.18' (ECDSA) to the list of known hosts.
Password:
New-PSSession : [121.107.1.18] The background process reported an error with the following message: The SSH client session has end
ed with error message: subsystem request failed on channel 0.
At line:1 char:1
+ New-PSSession -HostName 121.107.1.18 -UserName root
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportExcept
ion
+ FullyQualifiedErrorId : 2100,PSSessionOpenFailed
```

**Comment by bingbing8** [comment]
@sunzcosmo, It works for me using latest binaries built from latest source. Could you follow the [Troubleshooting-Steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps) and post the sshd log?

**Comment by sunzcosmo** [comment]
> @sunzcosmo, It works for me using latest binaries built from latest source. Could you follow the [Troubleshooting-Steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps) and post the sshd log?

Just figured out why ... I was very careless when I read the document, and I forget to config the sshd_config on remote server. Really really sorry for wasting your time.

**Comment by Adikota** [comment]
Does this version of New-PSSession support a windows to Linux SSH connectivity?

**Comment by manojampalam** [comment]
@Adikota  Check out https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-6
