### ISSUE TITLE
don't rewrite sshd_config_default

### ISSUE THREAD

**Issue by brewagebear** [PowerShell/Win32-OpenSSH#1297]
**"OpenSSH for Windows" version**
 7.6.0.0

**Server OperatingSystem**
Windows10 Education

**Client OperatingSystem**
Windows10 Education

**What is failing**
I was changing the ports of the sshd config.
However, the file 'C:\Windows\System32\OpenSSH\sshd_config_default' is still outputting for permission issues.
I used the VScode program to open the file.
After removing the annotation from the 9th line #port 22, we changed it to port 10022.
I could see an error like the picture was printed.
It was also possible to change to Notepad.

Then, I came to know this page  and I read wiki page.
And there was a detailed description of how to change settings. 
I set it up through the appropriate method.
Modify the file %programdata%\ssh\sshd_config.
As a result of portscanning, we found that port 22 is still in use.

how to solve it?

**Actual output**
![sadas](https://user-images.githubusercontent.com/22961251/49087410-3b628d80-f29a-11e8-90c2-d7b3c869bca9.PNG)

**Comment by bingbing8** [comment]
after you update %programdata%\ssh\sshd_config, you need to restart the service to make your change take effect

**Comment by brewagebear** [comment]
> 
> 
> after you update %programdata%\ssh\sshd_config, you need to restart the service to make your change take effect

Thanks you so much :)
