### ISSUE TITLE
[Question] Is this identical to OpenSSH shipped with Windows 10/2019?

### ISSUE THREAD

**Issue by bugz8unny69** [PowerShell/Win32-OpenSSH#1299]
Hello everyone,

I am having a rather frustrating time installing OpenSSH server on Windows 2019 standard edition. I don't have the error message on hand but if I could install it manually, would be ideal. My question, is this the same release shipped with Windows 10/2019? There are some reference to Windows 10 in issues?

**EDIT:** I managed to install OpenSSH Server with Chocolatey.

**Comment by bingbing8** [comment]
@lhorace, short answer is no. Git hub release has latest feature and bug fix. Those latest change may be included in next windows release.

**Comment by bugz8unny69** [comment]
~~I meant, does the OpenSSH server shipped with Windows is derived from this repository? So to speak, issues encountered with OpenSSH, should be reported here?~~ Should issues be reported here and not the Microsoft forums?

**Comment by manojampalam** [comment]
If you are seeing issues with OpenSSH in-box in Windows, recommend posting in Microsoft forums so you get the attention via official support. You could also post it in here - but note that work on this repo is a community effort, with no SLAs on any issue resolutions.

**Comment by bugz8unny69** [comment]
That's fine, this is not a Production machine. Thanks for the info.
