### ISSUE TITLE
Replace with secure APIs

### ISSUE THREAD

**Issue by manojampalam** [PowerShell/Win32-OpenSSH#13]
Including but not limited to strcpy, strcat, sprintf

**Comment by bingbing8** [comment]
whenever applicable:
replace memcpy with memcpy_s
replace strlen with strnlen_s
replace vsnprintf with vsnprintf_s
replace snprintf with _snprintf_s
replace strcpy with strcpy_s
replace wcscpy with wcscpy_s
replace strcat with strcat_s
replace wcscat with wcscat_s
replace sprintf wtih sprintf_s
replace swprintf with swprintf_s
