### ISSUE TITLE
TCP Port Forwarding Failing

### ISSUE THREAD

**Issue by theonewolf** [PowerShell/Win32-OpenSSH#130]
After awhile, my TCP port forwarding appears flaky.  Handles appear to randomly become invalid like:

```log
unknown type for handle [744]
accept: The handle is invalid.

unknown type for handle [700]
accept: The handle is invalid.

unknown type for handle [684]
accept: The handle is invalid.

unknown type for handle [796]
accept: The handle is invalid.

unknown type for handle [688]
accept: The handle is invalid.
```

This is running the ssh client from the normal Windows (8.1) `cmd.exe` terminal.  I am using the 64-bit version of `ssh.exe` in the release (2015.12.22) hosted in the Chocolatey Gallery (but I didn't install, I unzipped and am directly using the `ssh.exe` executable).

**Comment by manojampalam** [comment]
We are working on #91 . Hopefully, this gets fixed.

**Comment by theonewolf** [comment]
You probably know this, but it's still an issue with your latest release, same behavior:

```bash
unknown type for handle [912]
accept: The handle is invalid.

unknown type for handle [816]
accept: The handle is invalid.

unknown type for handle [984]
accept: The handle is invalid.

unknown type for handle [900]
accept: The handle is invalid.
```

**Comment by manojampalam** [comment]
Try the latest release. It has a more reliable transport.

**Comment by manojampalam** [comment]
Should be fixed now.
