### ISSUE TITLE
Arrow Keys Do Not Work in Git vim When Connecting to Windows SSH Server

### ISSUE THREAD

**Issue by bliles** [PowerShell/Win32-OpenSSH#1300]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**
[check]

**"OpenSSH for Windows" version**
7.7.2.1
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
macOS 10.14.1

**What is failing**
Arrow keys do not work in git vim.

**Expected behavior**
Arrow keys work properly in vim.

Interestingly arrow keys work in the build of vim available here: https://www.vim.org/ when connecting to the Windows machine, but when git launches its version of vim, the arrow keys do not work. I've tried various vim settings like `set nocompatible` but there was no change.

My current workaround is to change git's default editor to the version available from https://www.vim.org.

**Comment by maertendMSFT** [comment]
This should work in the latest release.
