### ISSUE TITLE
Useful Information For Docs

### ISSUE THREAD

**Issue by cphillips83** [PowerShell/Win32-OpenSSH#1305]
I ran into a issue that was unexpected and I thought maybe it would be useful for others and perhaps added to the documents as a "gotcha".

When setting up sshd on a few machines, I couldn't get the public key auth to work on all of them and the output of `sshd -ddd` was clearly showing that it wasn't even looking in to the `C:\Users\<user>\.ssh` folder and was checking for `C:\Windows\.ssh` for a auth key. After awhile I realized that the permission fix powershell script also wasn't detecting this user and running:
```
Get-ChildItem "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList"
``` 

Was also not returning the user I just created and set as an admin account. The "gotcha" is that the profile doesn't exist until you first log in with that user and if the user folder already exists, windows will append some things to it like the host name.

What I ended up doing was:
- Follow the sshd install instructions
- Leave password auth on
- Log in to the server over sshd using the password
- Stop sshd, remove password auth access, create `C:\users\<user>\.ssh\authorized_keys` file
- Start sshd

On that note, if windows has already added suffixes to your user folder, you can enable password auth, log in and see the exact entry folder you are in to determine where you would want to create the .ssh folder (in case you don't want to delete the user and folders and start over).

**Comment by jborean93** [comment]
You can create a profile for a user account without having to log in as that user first. I've created a PowerShell cmdlet that does this for you

```
Function New-Profile {
    <#
    .SYNOPSIS
    Creates the profile for a user on the current host if one does not already exist.
    
    .PARAMETER Account
    [String] The string representation of an account to create the profile for. This is mutually exclusive to Account.
    
    .PARAMETER Identity
    [System.Security.Principal.IdentityReference] The IdentityReference object of an account to create the profile
    for. This is mutually exclusive to Account.

    .PARAMETER BaseName
    [String] Optionally define the base name for the profile directory to create.
    
    .EXAMPLE
    New-Profile -Account my-user
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true, ParameterSetName="string")]
        [String]$Account,
        [Parameter(Mandatory=$true, ParameterSetName="identity")]
        [System.Security.Principal.IdentityReference]$Identity,
        [Parameter()][String]$BaseName
    )

    Add-Type -Namespace PInvoke -Name Userenv -UsingNamespace System.Text -MemberDefinition @'
[DllImport("Userenv.dll", SetLastError = true, CharSet = CharSet.Unicode)]
public static extern int CreateProfile(
    [MarshalAs(UnmanagedType.LPWStr)] string pszUserSid,
    [MarshalAs(UnmanagedType.LPWStr)] string pszUserName,
    [Out, MarshalAs(UnmanagedType.LPWStr)] StringBuilder pszProfilePath,
    UInt32 cchProfilePath);
'@

    if ($PSCmdlet.ParameterSetName -eq "string") {
        $Identity = New-Object -TypeName System.Security.Principal.NTAccount -ArgumentList $Account
    }

    $account_sid = $Identity.Translate([System.Security.Principal.SecurityIdentifier])
    $account_name = $account_sid.Translate([System.Security.Principal.NTAccount])
    if (-not $BaseName) {
        $account_split = $account_name.Value.Split('\', 2)
        $BaseName = $account_split[-1]
    }

    $profile_path = Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\*" | `
        Where-Object { $_.PSChildName -eq $account_sid.Value }

    if ($null -ne $profile_path) {
        Write-Verbose -Message "The profile for $($account_name.Value) already exists"
        $profile_path = $profile_path.ProfileImagePath
    } else {
        if ($PSCmdlet.ShouldProcess($account_name.Value, "Create profile")) {
            # MAX_PATH is 260 chars
            $raw_path = New-Object -TypeName System.Text.StringBuilder -ArgumentList 260
            $res = [PInvoke.Userenv]::CreateProfile($account_sid.Value, $BaseName, $raw_path, $raw_path.Capacity)
            if ($res -ne 0) {
                $exp = [System.Runtime.InteropServices.Marshal]::GetExceptionForHR($res)
                Write-Error -Message "Failed to create user profile for $($account_name.Value): $($exp.Message)"
            } else {
                $profile_path = $raw_path.ToString()
            }
        }
    }

    return $profile_path
}
```

Unfortunately I couldn't find a .NET method to create the profile so had to resort to using PInvoke but it gets the job done. Feel free to use this cmdlet to create the profile fiel and then populate the .ssh directory without having to log that user on first.

**Comment by cphillips83** [comment]
@jborean93 That is awesome, this info should really make it to the wiki. I know its a result of how windows works and not really in scope of what OpenSSH is, but would be useful as a note that you could run in to this.

**Comment by jborean93** [comment]
Happy for people to take and use it as they wish. If people feel like it's a good addition to the wiki then that's fine with me. As with all code, make sure you test that it works before running in production.

**Comment by maertendMSFT** [comment]
We believe this is fixed in the latest release.
