### ISSUE TITLE
Win2008 command will not return

### ISSUE THREAD

**Issue by jeepMan79** [PowerShell/Win32-OpenSSH#1307]
hello,

Operating System = Windows 2008 r2
OpenSSH Default Shell = cmd

executing powershell command over SSH, response is not sent until the process is killed.
process example = cmd /c powershell.exe ipconfig

On Windows 2012, this work fine.  What is really strange is this was working in Windows 2008 for months and all of a sudden started happening on mulple machines.

Any ideas?

**Comment by NoMoreFood** [comment]
Try doing `powershell.exe -NonInteractive -NoProfile ipconfig` to see if the behavior changes.

**Comment by jeepMan79** [comment]
Tried that, no luck :(.  When running via putty, it prints the output to screen, and doesn't exit until I hit return.  I'm not sure which process is waiting, CMD or Powershell.exe.

**Comment by jeepMan79** [comment]
okay, so when I put "< NUL" at the end of the powershell command/script, it works fine.  not sure why.  only happens in windows 2008.

**Comment by reina-n** [comment]
I think parent sshd always crash on create connection on Win2008 32bit...
Ver: 7.7.2.0 code: 0xc0000005 offset: 0x00025ff8
Ver: 7.9.0.0 code: 0xc0000005 offset: 0x00028548
the offset between 7.7.2 and  7.9.0 was near.

**Comment by maertendMSFT** [comment]
Win Server 2008 r2 is no longer supported, only Win Server 2012 and higher are supported.
