### ISSUE TITLE
Wrong character set in SFTP

### ISSUE THREAD

**Issue by ilmaisin** [PowerShell/Win32-OpenSSH#131]
I noticed that the SFTP server does not translate the character set in file names to UTF-8. According to the [http://tools.ietf.org/html/draft-ietf-secsh-filexfer-13](specification) (page 14), UTF-8 is the preferred encoding.

Please support UTF-8 in SFTP in order to reduce unnecessary configuration steps on the client.

**Comment by dehy** [comment]
👍

**Comment by manojampalam** [comment]
SFTP now support Unicode file names
