### ISSUE TITLE
OpenSSH is doing its own VT input encoding, should be using ENABLE_VIRTUAL_TERMINAL_INPUT

### ISSUE THREAD

**Issue by DHowett-MSFT** [PowerShell/Win32-OpenSSH#1310]
All 800 lines of code [here](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/tncon.c#L129-L788) could be deleted and replaced with trusting the console to generate VT.
This works on all versions of Windows 10 since the RS1 using the `ENABLE_VIRTUAL_TERMINAL_INPUT` mode on the _input_ handle.

Switching to this will also resolve all outstanding issues regarding input like #1282.

Please use `ENABLE_VIRTUAL_TERMINAL_INPUT`.

**Comment by manojampalam** [comment]
@bingbing8 please take a look

**Comment by DHowett-MSFT** [comment]
This was fixed.

**Comment by bagajjal** [comment]
Fixed as part of https://github.com/PowerShell/openssh-portable/pull/412

**Comment by Trolldemorted** [comment]
When will this fix land on W10 PCs? Will it be in the upcoming april update?

**Comment by bagajjal** [comment]
It will be part of windows update coming this fall season.
