### ISSUE TITLE
Unable to log in as domain user with public key

### ISSUE THREAD

**Issue by kralikba** [PowerShell/Win32-OpenSSH#1311]
Please answer the following

**"OpenSSH for Windows" version**
7.7.2.0
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
Logging in with a public key. 

**Expected output**
Authentication succeeds  with a public key and I get a prompt on the client.

**Actual output**
Logging in with a password works fine. 
When logging in with a public key, ssh authentication seems to succeed but then something else fails.

On the client: `Connection reset by ...`

On the server, in the log, after setting debug to level 3:
(excerpt from [sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/2695086/sshd.log))
```
18368 2018-12-19 14:51:50.953 debug3: LsaLogonUser succeeded
18368 2018-12-19 14:51:51.004 debug3: spawning "C:\\WINDOWS\\System32\\OpenSSH\\sshd.exe" "-z"
18368 2018-12-19 14:51:51.008 debug3: send_rexec_state: entering fd = 5 config len 167
18368 2018-12-19 14:51:51.008 debug3: ssh_msg_send: type 0
18368 2018-12-19 14:51:51.008 debug3: send_rexec_state: done
18368 2018-12-19 14:51:51.008 debug3: ssh_msg_send: type 0
18368 2018-12-19 14:51:51.008 debug3: ssh_msg_send: type 0
18368 2018-12-19 14:51:51.008 debug3: ssh_msg_send: type 0
13380 2018-12-19 14:51:51.026 debug3: ssh_msg_recv entering
13380 2018-12-19 14:51:51.026 debug2: fd 4 setting O_NONBLOCK
13380 2018-12-19 14:51:51.026 debug2: parse_server_config: config reprocess config len 167
13380 2018-12-19 14:51:51.027 debug3: NetUserGetInfo() failed with error: 1722 for user: kralikba and domain: domainname \n
13380 2018-12-19 14:51:51.049 debug3: NetUserGetInfo() with domainController: \\\\DC failed with error: 5 \n
13380 2018-12-19 14:51:51.049 Invalid user kralikba@domainname from ::1 port 61490
18368 2018-12-19 14:51:52.585 debug3: mm_request_receive entering
18368 2018-12-19 14:51:52.585 debug1: do_cleanup

```

**Comment by NoMoreFood** [comment]
Are you sure the SSH server you're connecting to is running the latest version?  Version 7.7.2.0 doesn't have the function NetUserGetInfo() in it at all.

**Comment by kralikba** [comment]
You are right. I have wrongly assumed that overwriting the builtin sshd files would be a good idea; it seems that they have been reverted to the older version when I have not been looking. Apologies. (It does work with the latest binaries indeed.)
