### ISSUE TITLE
OpenSSHUtils module signature invalid

### ISSUE THREAD

**Issue by schwarzichet** [PowerShell/Win32-OpenSSH#1313]
Please answer the following

**"OpenSSH for Windows" version**
7.7.2.2
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
Install-Module -Force OpenSSHUtils -Scope AllUsers

**Expected output**
OpenSSHUtils is installed successfully

**Actual output**
```
PackageManagement\Install-Package : The module 'OpenSSHUtils' cannot be installed or updated because the authenticode
signature of the file 'OpenSSHUtils.psd1' is not valid.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.P
   ackageManagement.Cmdlets.InstallPackage
```
#1070 may be related

**Comment by xziya** [comment]
Any progress?

**Comment by manojampalam** [comment]
This module will be deprecated soon. To fix file permissions please follow https://github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-Win32-OpenSSH

**Comment by Hamled** [comment]
I'm not sure if the folks maintaining this repository have any relation to the team that works on the OpenSSH documentation at Microsoft.


But if that is the case, I would like to suggest that the documentation for key management be updated to not include instructions for installing the OpenSSHUtils module, as it has been deprecated.

Relevant page is here: https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement

**Comment by jamshid** [comment]
This is all so confusing because there is so much outdated information sprawling across the web. Can't Microsoft at least keep it's own site up to date? If this is outdated please put a link at the top to current instructions.
https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement
