### ISSUE TITLE
Custom subsystem console program cant read from the console (in)

### ISSUE THREAD

**Issue by KarloX2** [PowerShell/Win32-OpenSSH#1314]
**"OpenSSH for Windows" version**
7.6.0.1
 
**Server OperatingSystem**
Windows 10 Pro

I want to implement a custom subsystem for ssh. As a start, I created a simple console mode app with C#/.NET and registered the executeable in sshd_config like so:

`Subsystem	mytest	C:\path\to\myprogram.exe`

Then, when I establish a ssh session like so:

`ssh localhost -s mytest`

the program starts up. Initially the program write a hello message to the console (Console.WriteLine("Hello")) and this is displayed in the ssh window, so generally is seems to live.

However, I'm unable to read anything from the console in myprogram.exe. Neither Console.Read() not Console.ReadLine() would ever return anything on input on the client side. The program just blocks.

How can I resolve this? Any special settings to apply in/on myprogram.exe?

Note than when I declare `C:\Windows\System32\cmd.exe` as the binary of my subsystem that will work just fine, so generally it should be possible.

Thanks!

**Comment by manojampalam** [comment]
You'll need to read from stdin and not from Console.

**Comment by KarloX2** [comment]
Well, .NET Console.Read/Write methods claim to map to stdin /stdout if the input / output are redirected.

I also tried with Console.OpenStandardInput(), same result, read just blocks.

Does anybody like to repro this?

Thanks

**Comment by manojampalam** [comment]
OK. I'm not all familiar with .Net. When you do the following - is your app able to read "input"?
`echo input | C:\path\to\myprogram.exe`

**Comment by KarloX2** [comment]
Yes, `echo input | C:\path\to\myprogram.exe` works just fine.

Any idea what I could try next?

C# Source code is as simple as this:

```
            Console.WriteLine("Hello");

            while (true)
            {
                var k = Console.ReadLine();
                if (!string.IsNullOrEmpty(k))
                {
                    Console.WriteLine("R: " + k);
                    if (k == "quit") break;
                }
            }

            Console.WriteLine("Bye");

```
The "Hello" output is visible in the SSH client console. But no "R: …" echos and quit doesn't work either.

**Comment by manojampalam** [comment]
None that I could think of. How do you invoke your subsystem on your client?

**Comment by KarloX2** [comment]
I start the client like so:

`ssh localhost -s mytest`

and `mytest` is the name of the subsystem declared in sshd_config.

**Comment by manojampalam** [comment]
can you try with no TTY/PTY
`ssh -T localhost -s mytest`

**Comment by KarloX2** [comment]
I tried that, it doesn't make any difference.

However I think I found the cause of the problem now:

Under the hood, the .NET framework employs the internal __ConsoleStream class for accessing the console or the standard in/out respectively. Source code of .NET 4.7.2 is available [here](https://referencesource.microsoft.com/#mscorlib/system/io/__consolestream.cs).

At the very end of that class there is an external method  `WaitForAvailableConsoleInput` declared that is being called when it comes to read. I can't see the source code of that method implementation, but this seems where execution blocks. That _may_ have to do with the fact that the SSH client doesn't send the Windows style line termination sequence `<cr><lf>`, but only a `<lf>` like it is usual on Linux.

The bad thing is that it is perfectly possible to skip line mode (by a call to the `SetConsoleMode` API, so Read wouldn't wait for the like termination sequence), but that only works while using a real console. I can't find a way to do the same when the input is redirected (piped).

If the above it true, then I think this is a shortcoming of .NET and we should ask MS to add a feature to make WaitForAvailableConsoleInput trigger on `<lf>` AND also for a non-line mode when using pipes. Does anybody known where one can file such a feature request?

For the time being, the workaround seems to be to ignore the Console class (at least for reading) and to work with a FileStream on the native stdin handle.

**Comment by jborean93** [comment]
Completely out of the blue but this is something I've recently come across with trying to send data to Windows PowerShell over ssh. The problem is as mentioned above in the ` WaitForAvailableConsoleInput` in .NET Framework and it's not a problem with it expecting `\r\n` but rather an issue with pipe handles opened with `FILE_FLAG_OVERLAPPED` and how it waits for input. Because the SSH daemon creates the pipes it uses for stdio redirection with `FILE_FLAG_OVERLAPPED` the .NET applications calling `Console.ReadLine()` will hang indefinitely. For .NET Framework based applications the only workaround is to manually call [ReadFile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile) through PInvoke rather than going through .NET as it bypasses that function entirely. .NET 5+ is not susceptible to this problem as it no longer uses the ` WaitForAvailableConsoleInput` implementation.
