### ISSUE TITLE
Pageant as ssh-agent failing

### ISSUE THREAD

**Issue by aviadmini** [PowerShell/Win32-OpenSSH#1319]
Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
7.7.2.0
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 Home

**Client OperatingSystem**
Windows 10 Home

**What is failing**
Pageant as ssh agent fails (using https://github.com/benpye/wsl-ssh-pageant )
When running `ssh -T git@gitlab.com -vvv` having a valid (working key) in Pageant the output is following:
```
... more logs ...
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:cio8Lm+4b8Ofo9efq+6xf8/+Y5RPh/uemDQrFjXvoDg example@email.com
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: pkalg rsa-sha2-512 blen 277
debug2: input_userauth_pk_ok: fp SHA256:cio8Lm+4b8Ofo9efq+6xf8/+Y5RPh/uemDQrFjXvoDg
debug3: sign_and_send_pubkey: RSA SHA256:cio8Lm+4b8Ofo9efq+6xf8/+Y5RPh/uemDQrFjXvoDg
debug3: write - ERROR from cb:233, io:000001D4F56D60C0
sign_and_send_pubkey: signing failed: communication with agent failed
debug1: Trying private key: C:\\Users\\aviadmini/.ssh/id_rsa
debug3: no such identity: C:\\Users\\aviadmini/.ssh/id_rsa: No such file or directory
debug1: Trying private key: C:\\Users\\aviadmini/.ssh/id_dsa
debug3: no such identity: C:\\Users\\aviadmini/.ssh/id_dsa: No such file or directory
debug1: Trying private key: C:\\Users\\aviadmini/.ssh/id_ecdsa
debug3: no such identity: C:\\Users\\aviadmini/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: C:\\Users\\aviadmini/.ssh/id_ed25519
debug3: no such identity: C:\\Users\\aviadmini/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: C:\\Users\\aviadmini/.ssh/id_xmss
debug3: no such identity: C:\\Users\\aviadmini/.ssh/id_xmss: No such file or directory
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
git@gitlab.com: Permission denied (publickey).
```

Pageant is latest version
`SSH_AUTH_SOCK=\\.\pipe\ssh-pageant`

**Comment by manojampalam** [comment]
You'll need a pageant expert to see what's going on, on the agent side. Does it generate any logs to trouble shoot ?

Does this work ?
`ssh-add -l`

**Comment by NoMoreFood** [comment]
This will not work.  The way that PuTTY and WinSCP interact with Pageant is to locate the "Pageant" window and send messages using the Windows messaging subsystem.  The messages pass along a small structure to facilitate key exchange through a memory mapped file.  People have written various go-between translators for Cygwin's SSH implementation and Pageant which may work with this OpenSSH distribution but I wouldn't be optimistic.

**Comment by aviadmini** [comment]
The same one works with WSL through a unix socket

@manojampalam yes, `ssh-add -l` works and shows correct info

**Comment by NoMoreFood** [comment]
@aviadmini I apologize; I missed the part where you referenced to the fact you were _already_ using one of those custom go-between translators.  I feel like the issue is more appropriately posted in https://github.com/benpye/wsl-ssh-pageant which is looks like you already did.  I'll try to reproduce it myself this weekend, but I'm curious what the authors of that have to say.
