### ISSUE TITLE
chmod 600 on Windows?

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#132]
win32-OpenSSH is giving the error "Permission denied (publickey)" when I try to use an amazon pem.

What is the windows equivalent icacls command for chmod 600?  All I find on the net is work arounds by using other products - but I would like to use openssh.

**Comment by manojampalam** [comment]
Did you try it the UI way, Right-Click, properties, security....

**Comment by jhudsoncedaron** [comment]
Ugh! A good case for shipping a command-line tool for fixing private key files.

**Comment by Ventusfahrer** [comment]
...well the problem is that Windows is much more flexible in file system security than the common Unix implementations. chmod will never be enough for this job.

if you need to modify security settings per command line use calcs.exe or icacls.exe
...or in powershell Get-ACL/Set-ACL. search Google for examples.

If you need to investigate in file access related problems use procmon.exe (windows applicaton from www.sysinternals.com) on the desktop.

**Comment by Ventusfahrer** [comment]
... the most important thing is to find out which process (running under a specific account) tries to access which file. 
Depending where the file is located, it may have very special security settings mostly inherited by the parent directory. In some cases you are able to create a file but not to delete it...

Use procmon to find out what is happening

**Comment by DarwinJS** [comment]
This is me running ssh to access the local ssh key file.

I understand how to use those tools, but they will not help me understand what this linux ported software expects to see for Windows permissions to equate to chmod 600.

Seems by now someone would have made a PowerShell CMDLet "chmod" that handles it for me.

Does anyone know *exactly* what perms ssh.exe is looking for on the key file?

**Comment by jhudsoncedaron** [comment]
I think removing all access from the advanced view by unchecking inherit and deleting everything, then giving yourself full control does the needful.

**Comment by altaurog** [comment]
Does the win32 port actually check file and directory permissions?  It looks to me like it doesn't.  The functions `secure_filename` and `auth_secure_path` in [auth.c](https://github.com/PowerShell/Win32-OpenSSH/blob/ac42afd12228553afd48124a36484921efcffa10/auth.c#L555) both return 0 if compiled with `WIN32_FIXME`, which *is* defined in [win32_config.h](https://github.com/PowerShell/Win32-OpenSSH/blob/L1/win32_config.h#L1578).

**Comment by DarwinJS** [comment]
Not only that, but with the latest version I do not get the error - I must have misinterpreted the error.
Thanks.

**Comment by DreaJulca** [comment]
A PowerShell/CMD "chmod 600" equivalent would be a really convenient help if, just to pull a totally random and impersonal example out of the air, someone needed to give owner permissions of a private key to _NT AUTHORITY_ via PsExec while trying to use their desktop running Windows 10 Home as a personal server to give one or two fellow researchers access to to one's pre-existing GPU installation of TensorFlow.

Of course, it's possible that there is already a solution for this and I'm just not aware of it.

**Comment by jhudsoncedaron** [comment]
I guess I'm used to the unix world bug where ssh doesn't actually check the full ACL but only the classic permissions; hence DreaJulca's scenario wouldn't have broken it.

**Comment by goldstar611** [comment]
We have issues with adminstrators_authorized_keys as well but have found icacls to resolve inherited permissions with
```powershell
# Remove inheritance, copying existing permissions
icacls C:\ProgramData\ssh\administrators_authorized_keys /inheritance:d
# Remove Authenticated Users
icacls C:\ProgramData\ssh\administrators_authorized_keys /remove "Authenticated Users"
```
