### ISSUE TITLE
Authentication for IIS-user

### ISSUE THREAD

**Issue by suppenfilter** [PowerShell/Win32-OpenSSH#1321]
**"OpenSSH for Windows" version**
7.7.2.0
 
**Server OperatingSystem**
Windows Server 2012 R2

**Client OperatingSystem**
Windows 10/Windows Server 2016

**What is failing**
We want to transfer some files with OpenSSH running with an application in IIS (which starts the ssh-client in new process). A key based authentication should be done with a particular ssh user.
We now have a conflict with the permissions of the private key, since the IIS process runs under a different user than the this particular ssh user. Adding the IIS group to the permissions of the private key leads to the warning "UNPROTECTED PRIVATE KEY FILE" and the key is ignored.
Do you have a recommendation for the IIS-configuration and the permissions of the private key?

**Comment by manojampalam** [comment]
Your private key should only be accessible by your client (IIS process) and none else. 
What user context is your IIS process running as ?

**Comment by suppenfilter** [comment]
The IIS process will run with the account *ApplicationPoolIdentity*. I managed to make it work with when the IIS process runs with a custom account and limit the access rights of the private key to this account. But I did not yet manage to make it work with the *ApplicationPoolIdentity*.

**Comment by NoMoreFood** [comment]
@suppenfilter What happens when you assign the permissions and ownership of the file to APPPOOL\YourAppPoolName?

**Comment by ValZapod** [comment]
UNPROTECTED PRIVATE KEY FILE
