### ISSUE TITLE
Update Docs for ConPTY support

### ISSUE THREAD

**Issue by colemickens** [PowerShell/Win32-OpenSSH#1326]
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Can this page be updated to discuss the new TTY situation nwo that ConPTY is supported?

**Comment by mgkuhn** [comment]
The line “Windows OS does not have inbuilt support for a pseudoterminal.” clearly needs to be changed to “Windows versions before Windows 10 1809 did not have built-in support for a pseudoterminal. On more recent versions, OpenSSH 7.9 or newer can connect stdin/stdout of a command-line applications similar to how it does on POSIX systems.”
Anything else?

**Comment by bagajjal** [comment]
@colemickens , @mgkuhn - Thank you. I updated the [wiki](https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH)
