### ISSUE TITLE
Support PrintMotd

### ISSUE THREAD

**Issue by LinkPhoenix** [PowerShell/Win32-OpenSSH#1327]
**"OpenSSH for Windows" version**
 `v7.9.0.0p1-Beta`

**Client OperatingSystem**
Windows 10 Pro 1803

**What is failing**
I was able to integrate the BANNER option. So a banner before the connection but I did not find any hype about PrintMotd. The SSHD_Config documentation does not designate whether PrintMord is supported or not.
Namely that it does not specify whether or not Banner is an option, on this I can answer you Banner is supported, it should just indicate the PATH

I tried to see how to set up PrintMotd on Linux but I did not find anything that could, for example, force the Path to a file 'motd' with the banner

someone has already managed to put this in place on an OpenSSH on Windows or the option is simply not for the moment support.

Thank you for your help ;)

**Comment by manojampalam** [comment]
Its not supported yet. Updated https://github.com/PowerShell/Win32-OpenSSH/wiki/sshd_config

**Comment by DHowett-MSFT** [comment]
The title erroneously says `PrintMod` when it should say `PrintMotd`.

**Comment by manojampalam** [comment]
Thanks. Fixed.

**Comment by LinkPhoenix** [comment]
Thank you for the answer :)

and my mistake for the tittle.

Can not we add in the documentation that the BANNER option is supported?
