### ISSUE TITLE
Please document requirement for ed25519

### ISSUE THREAD

**Issue by directionless** [PowerShell/Win32-OpenSSH#1332]
**"OpenSSH for Windows" version**
7.6.0.0                                                                                                                         
 
**Server OperatingSystem**
Windows Server Datacenter                                                                                                       

**Client OperatingSystem**

OSX

**What is failing**

Using authorized_keys to connect to the server

**Expected output**

Connection to succeed

**Actual output**

Connection failed

This appear to be because sshd only supports ed25519 keys (as referenced in this [blog post](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/))

All the debugging information I was able to find was about permissions. But that was not the problem.

This should probably land on a wiki page somewhere

**Comment by kossmoboleat** [comment]
Is that really still the only kind of key that's supported? I've failed to get my rsa-sha2-512 key to work, maybe that's reason.

It's confusing that even the usage examples mention generating a rsa key instead: https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples

**Comment by kossmoboleat** [comment]
Actually I got it to work with my rsa key, so I don't think at least rsa keys are also supported currently.

I'm using this version `OpenSSH_for_Windows_7.9p1, LibreSSL 2.6.5`

**Comment by directionless** [comment]
Interesting that you got it to work. I've been assuming it's key type related (as opposed to permission) since everything started working when I swapped my key types.

**Comment by kossmoboleat** [comment]
For me it were actually permission issues for the `%PROGRAMDATA%/ssh/administrators authorized_keys` file. Back then I only found the issue by activating -ddd logging on the server side. 

The error messages and documentation could definitely be improved though.

**Comment by maertendMSFT** [comment]
This was a limitation early on, but no longer applies.
