### ISSUE TITLE
Could we have a "Releases" Tab on Github page for easy navigation? 

### ISSUE THREAD

**Issue by longtth** [PowerShell/Win32-OpenSSH#1335]
Not really an issue, but it relative to this repo so I post this, 
Could we have a `Release ` tab on this repo so we could navigate to download page easily?
Currently everytime a new release come I must open my bookmark to go to [download page](https://github.com/PowerShell/Win32-OpenSSH/releases)
![image](https://user-images.githubusercontent.com/1010849/52221876-c1233a80-28d4-11e9-886b-e4c7c676c27c.png)

**Comment by jborean93** [comment]
Not sure if you can add it to the top but you can still access it on the main landing page for the repo 
![image](https://user-images.githubusercontent.com/8462645/52236807-92788480-2913-11e9-8ba5-b373a1bb7f49.png)

**Comment by longtth** [comment]
@jborean93 sorry for my mistake, it's okay now. 
closed.
