### ISSUE TITLE
Suggestion: Provide object serialization where possible

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PowerShell/Win32-OpenSSH#134]
Hi!

One of the major benefits to PowerShell is that it is object-based.

It might be helpful to provide serialization and de-serialization if connections are both from and to PowerShell.

PowerShell remoting will do this for us as well, but I could see cases where SSH may be more appropriate in certain environments, where sticking to objects would be quite helpful.  I also realize we could do this on our own, but given PowerShell's task-based nature and some level of focus on IT admins, it would be valuable to abstract this out for us.

Cheers!

**Comment by maertendMSFT** [comment]
PowerShell 6+ supports remoting over SSH.
