### ISSUE TITLE
sshd_config "Match User" not matching domain user account

### ISSUE THREAD

**Issue by medavisjr** [PowerShell/Win32-OpenSSH#1341]
Running win32-openssh release 7.9.0.1
 
**Server OperatingSystem**
Windows Server 2016 Standard

**Client OperatingSystem**
Ubuntu 16.04

**What is failing**
The sshd server is joined to an Active Directory domain. I have a domain user that I want to match on and configure some parameters to jail the user to a certain directory. Log in is successful, but it appears from the logs that the user is not being matched, and therefore not being jailed to the desired directory.

This is the relevant configuration in my sshd_config:

```
Match User sqacorp\sftp-user
ForceCommand internal-sftp
ChrootDirectory e:\folder1
```

**Expected output**
Upon login, a 'pwd' command should show the session is in the e:\folder1 directory, and user is unable to change to a directory outside of that path.

**Actual output**
Upon login, user is in the C:\Users\sftp-user directory, and is able to navigate all over the filesystem.

Also, I see this in the log:

```
2056 2019-02-13 19:37:03.959 debug2: parse_server_config: config reprocess config len 254
2056 2019-02-13 19:37:03.959 debug3: checking match for 'User sqacorp\\sftp-user' user sftp-user host <redacted> addr <redacted> laddr <redacted> lport 22
2056 2019-02-13 19:37:03.959 debug3: match not found
2056 2019-02-13 19:37:03.959 debug3: NetUserGetInfo() failed with error: 2221 for user: sftp-user and domain: (null) \n
```

**Comment by NoMoreFood** [comment]
I do not believe you are running the latest version since NetUserGetInfo() appears no where in the 7.9 code.  Please double-check.

**Comment by medavisjr** [comment]
Well don't I feel silly. @NoMoreFood you were spot-on. Somehow, my installation playbook was pulling an older version of OpenSSH from August 2018 from my Chocolatey repository. I do have the public repo as a source for that, so I need to look into why my Artifactory instance isn't pulling the latest from the web when I request an upgrade.

After manually uploading the 7.9 code to my chocolatey repo and upgrading, everything is performing as expected.

Thank you!
