### ISSUE TITLE
SSHn failing to authenticate 

### ISSUE THREAD

**Issue by shaynecm-zz** [PowerShell/Win32-OpenSSH#1344]
SO I have installed open ssh through programmes and features and uninstalled/reinstalled to try and get this working. 

First issue is that when I have installed openSSH none of the ssh agent srvices are showing in the windows 10 services. 

I have then tried to install through github repo manually and I can use SSH in powershell core but I have no services cant start/restart. 

I can gen keys which I have and I have placed the Openssh in Programe Files\OpenSSH. 

I have cd to my local directory and under the .ssh file crated a key pair, I have loaded this into an azure vm and when I tried to SSH to it but comes up with the error: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

Where should the Keys be saved when they are generated so I can use them when I ssh?

I have tried being cd to the OpenSSH folder, the programe data folder/ssh folder and the .ssh folder crated in home but all fails. 

this just doesn't seem to work any more? 

if I create the ssh keys on a Linux machine they work fine. just really confused as this was working a few months back and I don't know if the recent update has killed this Open SSH .

I have rebuilt the windows 10 machine from scratch as well. 

I have tried to use the standard powershell and nothing. 

All from administrator too.

**Comment by manojampalam** [comment]
Lets take it step by step. What's the version of Windows you are using?

After you added SSH Server via Programs and Features - 
- did it succeed  in installing the server?
- `net start sshd` - did this work ?
