### ISSUE TITLE
scp to non existing directory hangs

### ISSUE THREAD

**Issue by matkaminski** [PowerShell/Win32-OpenSSH#1345]
**"OpenSSH for Windows" version**
7.9.0.0
 
**Server OperatingSystem**
Windows Server 2016 Datacenter

**Client OperatingSystem**
MacOs/Linux/Other

**What is failing**
I am using openssh server for windows version 7.9.0.0 on Windows Server 2016. I am using it for scp and it works if i am uploading files to existing directories. If i will specify target directory not existing on my Windows Server then scp command get stuck and hangs forever. 

Last lines in my client log:
debug1: Sending command: scp -v -t testdir/testfile
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
Sending file modes: C0644 0 testfile
...

Last lines in my server log:
8164 2019-02-21 10:18:37.834 debug3: LsaLogonUser Succeeded (Impersonation: 1)
8164 2019-02-21 10:18:37.850 debug3: spawning "C:\\Program Files\\OpenSSH-Win64\\sshd.exe" -z
8164 2019-02-21 10:18:37.865 User child is on pid 2056
8164 2019-02-21 10:18:37.865 debug3: send_rexec_state: entering fd = 5 config len 289
8164 2019-02-21 10:18:37.865 debug3: ssh_msg_send: type 0
8164 2019-02-21 10:18:37.865 debug3: send_rexec_state: done
8164 2019-02-21 10:18:37.865 debug3: ssh_msg_send: type 0
8164 2019-02-21 10:18:37.865 debug3: ssh_msg_send: type 0
8164 2019-02-21 10:18:37.865 debug3: ssh_msg_send: type 0
8164 2019-02-21 10:18:37.865 debug3: ssh_msg_send: type 0
8164 2019-02-21 10:18:37.865 debug3: ssh_msg_send: type 0

Do you know what might cause it?

**Comment by NoMoreFood** [comment]
Reproducible. Appears to be a server side issue since the native client works fine against another SSH server. I'll try to take a look at the code tonight.

**Comment by jborean93** [comment]
This is slightly related, it doesn't hang but it will error without any info when trying to scp a file that doesn't exist on the remote https://github.com/PowerShell/Win32-OpenSSH/issues/1284.

**Comment by NoMoreFood** [comment]
Pull request is in: https://github.com/PowerShell/openssh-portable/pull/376

**Comment by NoMoreFood** [comment]
If interested, you can test using these binaries: https://github.com/NoMoreFood/openssh-portable/releases/tag/v7.9-merge-1
