### ISSUE TITLE
Chrooting sometimes doesn't work

### ISSUE THREAD

**Issue by Alwaysin** [PowerShell/Win32-OpenSSH#1346]
**"OpenSSH for Windows" version**
v7.9.0.0p1-Beta
 
**Server OperatingSystem**
Windows Server 2016 Standard

**Client OperatingSystem**
WinSCP 5.13.7

**What is failing**
In my conf I chrooted a user:

```
Match User myuser
  ForceCommand internal-sftp
  ChrootDirectory C:\Users\myuser\SFTP
```

It woks fine but when launching several connections in a row with the same user, it sometimes doesn't work and instead put me in the root filesystem and I can go through all drives, folders and files!

**Expected output**
Always chrooting

**Actual output**
Not always chrooting, sometimes error message from WinSCP "cannot find <my directory>" and putting me in root fs.

**Comment by Alwaysin** [comment]
It looks like it may be due to the fact that the default lines:

```
Match Group administrators
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
```

were causing an error as my system is in french:

```
error: unable to resolve group administrators
```

By removing it, it looks like it is always chrooting now.

**Comment by manojampalam** [comment]
@Alwaysin, you said that it was randomly failing before. If the issue is due to "administrators", it should reproduce consistently. No?

**Comment by Alwaysin** [comment]
That's what I thought but it doesn't happen without those lines.
If I put them back, I sometimes am not chrooted.

There's probably another logic behind it. I'd be happy to provide you with any log or whatever you need (say a french virtual machine if you need it).

**Comment by NoMoreFood** [comment]
@Alwaysin Change your config to the following using the logging parameters on sftp-server and restart the service:

```
Match User myuser
  ForceCommand sftp-server.exe -f LOCAL0 -l DEBUG3
  ChrootDirectory C:\Users\myuser\SFTP
```
Attach the resulting sftp-server.log from C:\ProgramData\ssh\logs immediately after the problem occurs.

**Comment by Alwaysin** [comment]
I've changed my config to match yours, but it doesn't create a sftp-server.log!
Inside usual sshd.log I have the same error message about the group.

**Comment by manojampalam** [comment]
@Alwaysin  please see https://github.com/PowerShell/Win32-OpenSSH/issues/1236
