### ISSUE TITLE
Cannot run on Windows 2003 - error Not a Valid Win32 Application

### ISSUE THREAD

**Issue by darkblaze69** [PowerShell/Win32-OpenSSH#135]
Cannot run on Windows 2003 - error "Not a Valid Win32 Application"

**Comment by manojampalam** [comment]
Currently not supported. Will keep this request open but there is little chance this may get addressed this year.

**Comment by Ventusfahrer** [comment]
I would not handle it as a feature request.

1. Windows Server 2003 is out of support (also in security terms)
2. Code compiled with Microsoft Visual Studio 2013 or Microsoft Visual Studo 2015 is not supported on XP/2003 unless you use a compiler switch which side effects are not quite clear.

The time of Windows Server 2003/XP is over - I would no longer code for it...

Peter

**Comment by maertendMSFT** [comment]
Win32_OpenSSH is only supported on in support versions of Windows.
