### ISSUE TITLE
OpenSSH client is not able to forward a privileged port

### ISSUE THREAD

**Issue by mbulandra** [PowerShell/Win32-OpenSSH#1350]
**"OpenSSH for Windows" version**
7.7.2.1
 
**Server OperatingSystem**
Debian 9

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
When trying to forward a privileged port, it fails and an error message is diaplyed, no mater if cmd or powershell window is elevated or not. Adding -v for verbose output does not change anything.
```
> ssh -vvv -L 443:192.168.0.1:443 user@remotehost
Privileged ports can only be forwarded by root.
```

**Expected output**
When launching the same connection with Putty, it works:
```
> netstat -na | find ":443"
  TCP    127.0.0.1:443          0.0.0.0:0              LISTENING
```

**Actual output**
`Privileged ports can only be forwarded by root.`

**Comment by boeckwurst** [comment]
Please read the changes history and look at v1.0.0.0-Beta.

Did you try running ssh.exe as SYSTEM user?
See "You may use psexec -s cmd to open up cmd.exe running as SYSTEM."

**Comment by manojampalam** [comment]
Windows does not have privileges ports. Looks like you are seeing this due to Unix specific condition checks on the client side. 

As a work around, use a port over 1024.

**Comment by NoMoreFood** [comment]
That port check was removed in 7.8 [(commit)](https://github.com/openssh/openssh-portable/commit/73ddb25bae4c33a0db361ac13f2e3a60d7c6c4a5#diff-42833d59dac20f1a0417b3ada07e9bf6).  Please try upgrading to the 7.9.

**Comment by mbulandra** [comment]
Upgrading to v7.9.0.0p1-Beta solves the problem. Thank you!
