### ISSUE TITLE
OpenSSH Logging DateTime format

### ISSUE THREAD

**Issue by scuthber** [PowerShell/Win32-OpenSSH#1351]
Very silly question, but I cannot find the answer. I am running openssh 0.0.18.0 on Windows 2012 R2 and while most things are working fine, the sshd log doesn't have the date in it, only the time.

Here's an example:

3488 11:30:03:638 Accepted password for ##### from #.#.#.# port ##### ssh2
3488 11:30:03:794 Starting session: subsystem 'sftp' for ##### from #.#.#.# port ##### id 0
3488 11:30:04:841 Connection closed by #.#.#.# port #####
3488 11:30:04:841 Close session: user ##### from #.#.#.# port ##### id 0
3488 11:30:04:841 Transferred: sent 2872, received 2128 bytes
3488 11:30:04:841 Closing connection to #.#.#.# port 62063 

Is there any way I can get a date to be logged?

TIA, Steve

**Comment by NoMoreFood** [comment]
Can you try version 7.9?  My logs look to have a date.

**Comment by scuthber** [comment]
Thanks NoMoreFood. Tbh I fixed the issue in the end and have turned down the log level. I will bear your comment in mind if/when it goes wrong again!

**Comment by anusanraj** [comment]
@scuthber, I'm facing the same issue in sshd log file on Windows 2012R2 server. in sshd_config, log level is already commented out in our setting. Wondering how did you turned down the log level.
Thanks

**Comment by manojampalam** [comment]
See if this helps:
https://github.com/PowerShell/Win32-OpenSSH/wiki/sshd_config#syslogfacility
https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities
