### ISSUE TITLE
ConnectTimeout does not work as expected: if set it delays connection for the time specified

### ISSUE THREAD

**Issue by vashik** [PowerShell/Win32-OpenSSH#1352]
**"OpenSSH for Windows" version**
 7.7.2.2

**Server OperatingSystem**
 Debian Stretch

**Client OperatingSystem**
Windows 10 Enterprise

**What is failing**
If ConnectTimeout was set to anything except none ssh.exe tries to use poll() for non-blocking connection establishing, but fails and loops or waits for the amount of time specified in ConnectTimeout

**Expected output**
I expect ssh connection to take the same time as it takes with ConnectTimeout=none:

Measure-Command { ssh -o ConnectTimeout=none _linux-hostname_ date }
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 12
Ticks             : 10124291
TotalDays         : 1.17179293981481E-05
TotalHours        : 0.000281230305555556
TotalMinutes      : 0.0168738183333333
TotalSeconds      : 1.0124291
TotalMilliseconds : 1012.4291

**Actual output**
It spends amount of time specified in ConnectTimeout for establishing connection:

Measure-Command { ssh  -o ConnectTimeout=10 _linux-hostname_ date }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 10
Milliseconds      : 854
Ticks             : 108545539
TotalDays         : 0.00012563141087963
TotalHours        : 0.00301515386111111
TotalMinutes      : 0.180909231666667
TotalSeconds      : 10.8545539
TotalMilliseconds : 10854.5539

**Comment by NoMoreFood** [comment]
Can you verify this is an issue with 7.9?

**Comment by vashik** [comment]
It was reproducible with ssh.exe built from the default branch of https://github.com/PowerShell/openssh-portable so I believe it should be reproducible with 7.9
I will check later

**Comment by NoMoreFood** [comment]
Ignore.  I can reproduce this, but I have to use a remote host; localhost works fine.  Likely some sort of race condition.

**Comment by vashik** [comment]
Roger that. I can confirm it is not reproducible on localhost, that's why I put _linux_hostname_ in the command line

**Comment by NoMoreFood** [comment]
Well, this is not a classical race condition.  It appears that if the connection is very quick, there's a short-cut in the code that avoids poll().  Once in poll(), the appears the asynchronous processing is a bit buggy.  I'm looking into it, but I'm not as familiar with this part of the code.

**Comment by bcronje** [comment]
@roblourens I couldn't find find the Remote SSH source code repo, is it still closed for public review?

Just a small thank you, the whole remote development feature is such a great tool for us that does development across multiple hosts and operating systems. So my thanks and appreciation to you and everyone else involved in releasing this amazing extension.

**Comment by bcronje** [comment]
I ran into this bug manifested in the Remote SSH issue referenced above.

I found that the ssh client bundled with git on Windows does not have the bug:

```
"c:\Program Files\Git\usr\bin\ssh.exe" -V
OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
```
```
Measure-Command { & "c:\Program Files\Git\usr\bin\ssh.exe" -o ConnectTimeout=10 bcronje@10.1.10.130 date }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 468
Ticks             : 4681656
TotalDays         : 5.41858333333333E-06
TotalHours        : 0.000130046
TotalMinutes      : 0.00780276
TotalSeconds      : 0.4681656
TotalMilliseconds : 468.1656
```

**Comment by noskojan** [comment]
Hi, I am confirming this behavior on latest Windows 10 20H2 (all updates installed):

> ssh -V
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

Any expectations when this issue will be fixed, please?
Thank you

**Comment by bagajjal** [comment]
@noskojan - I don't see it with [OpenSSH v8.1](https://github.com/PowerShell/win32-openssh/releases). Can you please try.
I'm trying to login to azure VM 
![image](https://user-images.githubusercontent.com/23668037/111513126-b40ce280-870d-11eb-87ab-200e0ccd2fc6.png)

**Comment by rtollert** [comment]
@bagajjal This reproduces clearly for me in 8.1.0.0p1. I happen to be using an old Pentium 3 running Ubuntu as an ssh server. I haven't investigated yet whether it gets any better for faster targets. Lemme know what tracing you'd like.

**Comment by roblourens** [comment]
@bagajjal Try it with setting a number for that option. That is the bug, as I understand it. This also reproes for me in 8.1.

![image](https://user-images.githubusercontent.com/323878/119168528-d96fe280-ba15-11eb-80e4-b4f909a24c3d.png)

![image](https://user-images.githubusercontent.com/323878/119168622-f0163980-ba15-11eb-8585-64b142bf0bbe.png)

**Comment by spathiwa** [comment]
It reproduces easily for me too.  @bagajjal, your example above of it "not reproducing"  was using '-o connectTimeout=none'.  None does not cause an issue; if you use an actual number of seconds, e.g. connectTimeout=10, and connect to a remote host, it will wait the given number of seconds ALWAYS, instead of only if the remote host does not connect in that time.

**Comment by bagajjal** [comment]
@spathiwa, @rtollert , Please try the attached [ssh_v_8_6.zip](https://github.com/PowerShell/Win32-OpenSSH/files/6534821/ssh_v_8_6.zip)


![image](https://user-images.githubusercontent.com/23668037/119404129-3b3d8000-bc94-11eb-914c-8862ed7928e8.png)

**Comment by rtollert** [comment]
@bagajjal Sorry for the late response: the attached ssh_v_8.6.zip works great.
