### ISSUE TITLE
Custom server side logging

### ISSUE THREAD

**Issue by venky424** [PowerShell/Win32-OpenSSH#1353]
I have created sshd service on windows server 2012 and set syslogfacility as LOCAL0 . Then after thus change , logs are are getting created at C:\ProgramData\ssh\logs\. But I am looking for something which can create logs at our application drives instead of Operating system drives.

The version which I have is SSH-2.0-OpenSSH_for_Windows_7.7.

Below are from the config file.

SyslogFacility LOCAL0
LogLevel DEBUG3

Any insights will be very helpful.

**Comment by NoMoreFood** [comment]
At the moment, it appears this is hard coded.  I think the best you can hope for is to delete/rename the current logs folder and make a symbolic link (C:\ProgramData\ssh\logs -> real location) to point it to a new location.   See below.

```
NET STOP "OpenSSH SSH Server"
MKDIR V:\NewLogs
REN "%ProgramData%\ssh\Logs" OldLogs
MKLINK /D "%ProgramData%\ssh\Logs" V:\NewLogs
NET START "OpenSSH SSH Server"
```

**Comment by venky424** [comment]
Thank you @NoMoreFood  It worked... I have created symbolic link. Do you know any estimate when can we expect of setting customized logs location on windows open ssh ?

**Comment by NoMoreFood** [comment]
I'd be willing to put in a change to allow a registry override for LOCAL0 as that would be pretty easy, but I'd want probably want one of the maintainers to weigh in before I go to the trouble.  I've got quite a few PRs open and I'm loosing hope any of them will be merged.

**Comment by fatbigbright** [comment]
Hello there, this issue is also exactly what I need to know at this point. And I have another question: is there anyway to make the log file split into another new one by days?

**Comment by manojampalam** [comment]
@fatbigbright, recommend putting in a scheduled task that runs at 12am that moved contents from sshd.log to a file of your choice.

**Comment by manojampalam** [comment]
@venky424 symlink approach that @NoMoreFood suggested works well for redirecting logging to a different location. 
We would like to keep logging configuration within OpenSSH to a minimum.

**Comment by venky424** [comment]
@manojampalam  Would it be safe to redirect the logs to ProgramData on server? What would be the best option to retrieve the logs in case of crash or no admin permissions to create links on server ?

**Comment by manojampalam** [comment]
@venky424 logging by default is done in ProgramData/ssh/logs. So what did you mean by your first question?

OpenSSH by default logs into ETW. You can use EventViewer to see logs on a remote machine.

**Comment by maertendMSFT** [comment]
We don't recommend file based logging in production, as it can lead to heavy disc usage.
