### ISSUE TITLE
v7.9.0.0p1-Beta breaks with multiple groups

### ISSUE THREAD

**Issue by Enxer** [PowerShell/Win32-OpenSSH#1354]
**"OpenSSH for Windows" version**  7.9.0.0
**Server OperatingSystem** Windows 10 Enterprise
**Client OperatingSystem** Windows 10 Enterprise
**What is failing:** v7.9.0.0p1-Beta broke multiple Match conditions
**Expected output:** Authentication
**Actual output:** Repeated access denied

SSHD_config with multiple group matches:
[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/2957401/sshd_config.txt)

Output of trying to connect:
[debug3.txt](https://github.com/PowerShell/Win32-OpenSSH/files/2957399/debug3.txt)

The user in question is apart of the DOMAIN\\Helpdesk-local-admins group
If I downgrade the sshd binaries to v7.7.2.0p1-Beta it works without issue.

**Comment by NoMoreFood** [comment]
Seems to be reproducible.  Looking into it.

**Comment by NoMoreFood** [comment]
Pull request is in: https://github.com/PowerShell/openssh-portable/pull/380

@Enxer: Can you try the binaries posted here:

https://github.com/NoMoreFood/openssh-portable/releases/tag/v7.9-merge-2

**Comment by Enxer** [comment]
Hi Bryan,

I get the same results.
[sshd.log](https://github.com/PowerShell/openssh-portable/files/2969019/sshd.log)

My account: (Get-ADUser username –Properties MemberOf).MemberOf -match 'helpdesk'
CN=Helpdesk-local-admins,OU=Local Administrators,OU=Security Groups,OU=MyBusiness,DC=domain,DC=local

SSHD_Config:
[sshd_config.txt](https://github.com/PowerShell/openssh-portable/files/2969021/sshd_config.txt)

I am working with the 64 bit binaries if that matters.

**Comment by NoMoreFood** [comment]
Just to make sure, you replaced the server (sshd.exe) binaries with these and restarted the service?  Just weird that I was able to reproduce a similar behavior, find an exact cause, and it's different from the one you reported.

(Also can you delete your comment in the PR --- just don't want to somebody to respond to it over there)

**Comment by NoMoreFood** [comment]
The latest log makes it look like user (e.g., "nbentiznger") does not exist on the system.  Can you confirm it does?

**Comment by Enxer** [comment]
ah! - that's what I get for fat fingering my account name. I just re-tested and I got in. It is probably too late for me to be testing.
The correct name worked. Thanks Bryan I think we can close this out.

**Comment by NoMoreFood** [comment]
@Enxer Thanks for the update.  As I mentioned, can you please remove your comment from the pull request so we don't confused the efficacy of that change.  I'd say let's keep the issue open until this is officially released.  Thanks!
