### ISSUE TITLE
[sftp] can't rename files on exFAT file system

### ISSUE THREAD

**Issue by keuucy** [PowerShell/Win32-OpenSSH#1357]
**"OpenSSH for Windows" version**
v7.9.0.0p1-Beta
 
**Server OperatingSystem**
Windows 10

**Client OperatingSystem**

**What is failing**
can't rename files use sftp on exFAT file system (flash drive)
i can successfully rename using windows explorer and this error does not occur on NTFS file system.
WinSCP error message:

Permission denied.
Error code: 3
Error message from server: Permission denied

**Expected output**

**Actual output**

**Comment by NoMoreFood** [comment]
@keuucy Can you see if these binaries address your issue?

https://github.com/NoMoreFood/openssh-portable/releases/tag/v7.9-merge-3

**Comment by keuucy** [comment]
@NoMoreFood yes, this solved my problem, thank you!
