### ISSUE TITLE
MAC cipher umac-128-etm@openssh.com does not correctly work

### ISSUE THREAD

**Issue by alefranz** [PowerShell/Win32-OpenSSH#1359]
**"OpenSSH for Windows" version**
7.7.2.1
 
**Server OperatingSystem**
Ubuntu 18.04.2 LTS
OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017

**Client OperatingSystem**
Windows 10 Pro 17763

**What is failing**

the ssh client on windows negotiate with the server the MAC cipher `umac-128-etm@openssh.com` which is actually not supported or doesn't correctly work

if a different MAC cipher is specified explicitly the connection works fine
e.g. `-m hmac-sha2-256`

**Expected output**
successful login 

**Actual output**
Corrupted MAC on input.
ssh_dispatch_run_fatal: Connection to REDACTED port 22: message authentication code incorrect

```
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr
debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr
debug2: MACs ctos: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
debug2: MACs stoc: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: aes128-ctr MAC: umac-128-etm@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: umac-128-etm@openssh.com compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
```

**Comment by iguyking** [comment]
I have come across the same issue.  We have restricted the HMACs available to a much smaller subset.  If umac-128@openssh.com is used, the negotiation fails.   If I use others that are hmac-sha2-256 or hmac-sha2-512 it works correctly.

**Comment by iguyking** [comment]
Further testing.. umac-128-etm@openssh.com also triggers this issue.  Remote server is openssh-7.4p1-16.el7.x86_64 on CentOS as of May 21, 2019.  Removal of these MAC ciphers on the server side results in proper negotiation of MACs from the Win32 Openssh client.

**Comment by IanLee1521** [comment]
Also seeing this with :

Client: `OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5`
Server: `OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017`

Note, that if I try from a macOS client (`OpenSSH_7.9p1, LibreSSL 2.7.3`), it negotiates to the same MAC (`umac-128-etm@openssh.com` in this case) and succeeds. So definitely an issue on the Windows client side.

**Comment by IanLee1521** [comment]
I think an alternate approach / workaround to fixing this could be to simply change the MACs order that the client offers by default... Perhaps to something like what [Mozilla recommends](https://infosec.mozilla.org/guidelines/openssh.html#modern-openssh-67):

```
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
```

**Comment by jansohn** [comment]
Still a problem with `OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2`. Is anyone looking at this problem?

    > sftp.exe -vvv -i c:\Users\xyz\certificates\private_key.pem root@internal-server.emea.mycompany.com
    debug3: spawning "c:\\Users\\xyz\\Tools\\OpenSSH-Win64\\ssh.exe" "-oForwardX11 no" "-oForwardAgent no" "-oPermitLocalCommand no" "-oClearAllForwardings yes" -v -v -v -i c:\\Users\\xyz\\certificates\\private_key.pem -l root "-oProtocol 2" -s -- internal-server.emea.mycompany.com sftp
    OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
    debug3: Failed to open file:C:/Users/xyz/.ssh/config error:2
    debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
    debug2: resolving "internal-server.emea.mycompany.com" port 22
    debug2: ssh_connect_direct
    debug1: Connecting to internal-server.emea.mycompany.com [10.189.90.31] port 22.
    debug1: Connection established.
    debug3: Failed to open file:c:/Users/xyz/certificates/private_key.pem.pub error:2
    debug1: identity file c:\\Users\\xyz\\certificates\\private_key.pem type -1
    debug3: Failed to open file:c:/Users/xyz/certificates/private_key.pem-cert error:2
    debug3: Failed to open file:c:/Users/xyz/certificates/private_key.pem-cert.pub error:2
    debug1: identity file c:\\Users\\xyz\\certificates\\private_key.pem-cert type -1
    debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
    debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2
    debug1: match: OpenSSH_7.2 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
    debug2: fd 3 setting O_NONBLOCK
    debug1: Authenticating to internal-server.emea.mycompany.com:22 as 'root'
    debug3: hostkeys_foreach: reading file "C:\\Users\\xyz/.ssh/known_hosts"
    debug3: record_hostkey: found key type ECDSA in file C:\\Users\\xyz/.ssh/known_hosts:27
    debug3: load_hostkeys: loaded 1 keys from internal-server.emea.mycompany.com
    debug3: Failed to open file:C:/Users/xyz/.ssh/known_hosts2 error:2
    debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
    debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
    debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
    debug3: send packet: type 20
    debug1: SSH2_MSG_KEXINIT sent
    debug3: receive packet: type 20
    debug1: SSH2_MSG_KEXINIT received
    debug2: local client KEXINIT proposal
    debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
    debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
    debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
    debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
    debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
    debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
    debug2: compression ctos: none,zlib@openssh.com,zlib
    debug2: compression stoc: none,zlib@openssh.com,zlib
    debug2: languages ctos:
    debug2: languages stoc:
    debug2: first_kex_follows 0
    debug2: reserved 0
    debug2: peer server KEXINIT proposal
    debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
    debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
    debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr
    debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr
    debug2: MACs ctos: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
    debug2: MACs stoc: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
    debug2: compression ctos: none,zlib@openssh.com
    debug2: compression stoc: none,zlib@openssh.com
    debug2: languages ctos:
    debug2: languages stoc:
    debug2: first_kex_follows 0
    debug2: reserved 0
    debug1: kex: algorithm: curve25519-sha256@libssh.org
    debug1: kex: host key algorithm: ecdsa-sha2-nistp256
    debug1: kex: server->client cipher: aes128-ctr MAC: umac-128-etm@openssh.com compression: none
    debug1: kex: client->server cipher: aes128-ctr MAC: umac-128-etm@openssh.com compression: none
    debug3: send packet: type 30
    debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
    debug3: receive packet: type 31
    debug1: Server host key: ecdsa-sha2-nistp256 SHA256:7y59RZT3WwlxamXr8nwdWsin5iCwOcBWneFD/aVBn58
    debug3: hostkeys_foreach: reading file "C:\\Users\\xyz/.ssh/known_hosts"
    debug3: record_hostkey: found key type ECDSA in file C:\\Users\\xyz/.ssh/known_hosts:27
    debug3: load_hostkeys: loaded 1 keys from internal-server.emea.mycompany.com
    debug3: Failed to open file:C:/Users/xyz/.ssh/known_hosts2 error:2
    debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
    debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
    debug3: hostkeys_foreach: reading file "C:\\Users\\xyz/.ssh/known_hosts"
    debug3: record_hostkey: found key type ECDSA in file C:\\Users\\xyz/.ssh/known_hosts:27
    debug3: load_hostkeys: loaded 1 keys from 10.189.90.31
    debug3: Failed to open file:C:/Users/xyz/.ssh/known_hosts2 error:2
    debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
    debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
    debug1: Host 'internal-server.emea.mycompany.com' is known and matches the ECDSA host key.
    debug1: Found key in C:\\Users\\xyz/.ssh/known_hosts:27
    debug3: send packet: type 21
    debug2: set_newkeys: mode 1
    debug1: rekey out after 4294967296 blocks
    debug1: SSH2_MSG_NEWKEYS sent
    debug1: expecting SSH2_MSG_NEWKEYS
    debug3: receive packet: type 21
    debug1: SSH2_MSG_NEWKEYS received
    debug2: set_newkeys: mode 0
    debug1: rekey in after 4294967296 blocks
    debug3: unable to connect to pipe \\\\.\\pipe\\openssh-ssh-agent, error: 2
    debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
    debug1: Will attempt key: c:\\Users\\xyz\\certificates\\private_key.pem  explicit
    debug2: pubkey_prepare: done
    debug3: send packet: type 5
    Corrupted MAC on input.
    ssh_dispatch_run_fatal: Connection to 10.189.90.31 port 22: message authentication code incorrect
    Connection closed

Git for Windows binary which uses OpenSSL works, so I'm guessing it's a problem with LibreSSL?

    > C:\app\tools\Git\usr\bin\ssh -V
    OpenSSH_7.7p1, OpenSSL 1.0.2o  27 Mar 2018

**Comment by bagajjal** [comment]
Please raise an issue in https://github.com/libressl-portable/portable

**Comment by jansohn** [comment]
@bagajjal I'm trying to build the latest master to check if the problem still exists with LibreSSL 3.0.2. Unfortunately the build seems to always use LibreSSL 2.6.5? What am I doing wrong?

    PS D:\git\openssh-portable> git rev-parse HEAD
    8ab565c53f3619d6a1f5ac229e212cad8a52852c
    PS D:\git\openssh-portable> ipmo .\contrib\win32\openssh\OpenSSHBuildHelper.psm1 -Force
    PS D:\git\openssh-portable> Start-OpenSSHBuild -Configuration Release -NativeHostArch x64
    Starting Open SSH build; Build Log: D:\git\openssh-portable\contrib\win32\openssh\OpenSSHReleasex64.log.
    SSH build successful.
    .\bin\x64\Release\sftp.exe -vv -o "ciphers=aes128-ctr" -o "macs=umac-128-etm@openssh.com" user@hostname
    OpenSSH_for_Windows_8.1p1, LibreSSL 2.6.5
    [...]
    Corrupted MAC on input.
    ssh_dispatch_run_fatal: Connection to 192.168.1.123 port 22: message authentication code incorrect
    Connection closed

**Comment by bagajjal** [comment]
@jansohn - OpenSSH dynamically loads libcrypto.dll (Libressl DLL). It's pretty much possible that libcrypto.dll might be in different places.

**Comment by jansohn** [comment]
> 
> 
> @jansohn - OpenSSH dynamically loads libcrypto.dll (Libressl DLL). It's pretty much possible that libcrypto.dll might be in different places.

Thanks for pointing me in the right direction. The OpenSSH Client feature of Windows actually puts a `libcrypto.dll` in `C:\Windows\system32`...

I removed it with the following command:

    Get-WindowsCapability -Online | ? Name -like 'OpenSSH*Client*' | Remove-WindowsCapability -online

Unfortunately that DLL seems to be dynamically loaded (?) because I'm getting an error *The code execution cannot proceed because libcrypto.dll was not found. Reinstalling the program may fix the problem* when trying to execute ssh/sftp in `bin\x64\Release`.

After copying the `libcrypto.dll` to the binary folder it works as expected:

    PS D:\git\openssh-portable> .\bin\x64\Release\ssh -V
    OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
