### ISSUE TITLE
Implications of running ssh-agent as system

### ISSUE THREAD

**Issue by yan4321** [PowerShell/Win32-OpenSSH#1360]
**"OpenSSH for Windows" version**
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.4 (With PR362)
 
**Server OperatingSystem**
This issue is isolated to the client side only.

**Client OperatingSystem**
Windows 10

**What is failing**
We have a MFA authentication system for SSH. In order to SSH into remote servers users need to get ephemeral SSH user certificates. One of the auth factors is a physical possession of the Yubikey assigned to them. Upon successful authentication the user will get back a certificate backed by the private key stored in their Yubikey and signed by our internal HSMs.

We recently ported the client side components of that system for Windows and our port relies on the Win32-OpenSSH project (and hence PR362 was submitted).

Everything works well when the Yubikey is directly attached to the client machine, However, one of the usecases we have is a bit more complicated: we have a set of clients (Windows VMs) that are only accessible through remote desktop via Citrix VDI (due to our internal security policy). In this usecase the user will use his Laptop which has his Yubikey directly attached to, and will start a VDI session (using Citrix receiver) to the client VM. From there he will do the usual set of operations to authenticate himself and get a certificate. This should work because of the USB pass-through between the user's laptop and the client VM.

The interesting observation that we see, is that the USB pass-through works well when the process on the client VM runs as the user (not as system and without admin rights). For example, when we run pkcs11-tool or yubico-piv-tool on the client VM they perfectly recognize the Yubikey attached to the user's laptop on the other side of the session. However, it does not work when the process is running as system.
We have done the exact same experimentation using Microsoft Remote Desktop (Instead of Citrix VDI) and got the exact same results.

All of the above led us to wonder why does the ssh-agent of Win32-OpenSSH requires to be run as system. We noticed that there is a option to store host keys, and it makes sense that those will be stored in a system-wide registry location. However, for the user keys portion of the agent, is there any reason for it to be run as system? for reference the ssh agent in the OpenSSH-portable project runs as the user and does not require any root privileges. If there is no reason for that, doesn't it increase the attack surface?

**Expected output**
>ssh-add -s "C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll"
Enter passphrase for PKCS#11:
Card added: C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll

>ssh-add -l
2048 SHA256:KkS9W+Pj5FUgLwm3Msd0UjbF+d+pWC+nJmKHZp+adso C:/Program Files/OpenSC Project/OpenSC/pkcs11/opensc-pkcs11.dll (RSA)
2048 SHA256:XKjPsyo5z0eYDwnH3s3k6xIUAOBAqMa2HDgwCdf+PBE C:/Program Files/OpenSC Project/OpenSC/pkcs11/opensc-pkcs11.dll (RSA)

**Actual output**
>ssh-add -s "C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll"
Enter passphrase for PKCS#11:
Could not add card "C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll"

(Same results with Yubico's ykcs11.dll)
For the sake of experimentation we have built a version of ssh-agent that runs as the user (and only supports storing and using user SSH keys). using that version we get the expected output/behavior and the USB pass through works end-to-end.
From our experimentation, the root cause is that USB pass through would work (either when using Microsoft Remote Desktop or Citrix VDI) only when the process that is trying to access the USB device on the remote client is run as the user.

**Comment by WSLUser** [comment]
> OpenSSH_for_Windows_7.7p1

7.9 is out. I would upgrade first as a standard first step.

**Comment by maertendMSFT** [comment]
Please try this on the latest release.

**Comment by ckolumbus** [comment]
Problem still exists with the latest version of OpenSSH : OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2 on Win10 21H1 19043,1706

`ssh-add` fails:

```
pwsh❯ ssh-add -s "C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll"
Enter passphrase for PKCS#11:
Could not add card "C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll": communication with agent failed
```

but getting pub keys and logging in via ssh works:

```
pwsh❯ ssh -I "C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll" user@my.host.de
Enter PIN for 'xxx'
Linux my.host.de 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64
...
```

and `ssh-add -l` lists existing keys, so the agent is running correctly IMHO.
