### ISSUE TITLE
Create beta package of win32-openssh for beta testing

### ISSUE THREAD

**Issue by WSLUser** [PowerShell/Win32-OpenSSH#1361]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
7.9.0.0
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

N/A

**Client OperatingSystem**
Windows 7 Professional

**What is failing**

N/A
**Expected output**
N/A

**Actual output**
N/A

Due to various bugs and missing features I would request that a binary be built that includes pull requests that are known to work when tested. https://github.com/NoMoreFood/openssh-portable/releases/tag/v7.9-merge-2 already has individual binaries created per pull request. I would like to see an official bundled version that includes other pull requests that are known to work with existing code for beta testing. This binary would be used to release a preview via Chocolatey (via the openssh choco package with -pre).

**Comment by jborean93** [comment]
The releases here are already marked as beta and creating another release for work in between release doesn't make too much sense. They do have a guide on how to build your own release https://github.com/PowerShell/Win32-OpenSSH/wiki/Building-OpenSSH-for-Windows-(using-LibreSSL-crypto) which you can do and distribute at any time. I haven't actually followed the guide myself but if it doesn't work then it sounds like a docs issue.
