### ISSUE TITLE
What is the use of Authorizedkeyfile__PROGRAMDATA......?

### ISSUE THREAD

**Issue by agrawalsmart7** [PowerShell/Win32-OpenSSH#1368]
This is not an issue, but I really want to understand what is the exactly use of this.

When I tried to be ssh password less authentication, I can't get in through but when I comment that line I quickly logged in successfully I mean why? How does it works?

And why ssh comes into program data, I have a separate directory of OpenSSH but it doesn't use anymore.?

Please anyone give me your time to explain this. Would be a very great help.

Thanks.

**Comment by agrawalsmart7** [comment]
For clear:- The line I commented out is this

#AuthorizedKeysFile__PROGRADATA__/ssh/administrators_authorized_keys

**Comment by manojampalam** [comment]
#1324
