### ISSUE TITLE
Please Provide the Latest Release at a Versioned URL Immediately upon release (as well as at the "latest" URL)

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#137]
I am doing the chocolatey packaging for OpenSSH and have a request.

Is it possible for this project to provide the "current" release also at it's versioned URL? 

This way I can checksum the files downloaded from the site.

For instance, as of this writing 2_25_2016 is the "current version" and available at https://github.com/PowerShell/Win32-OpenSSH/releases/download/latest/OpenSSH-Win64.zip

However, unliked archived packages, this release is not also available at: https://github.com/PowerShell/Win32-OpenSSH/releases/download/02_25_2016/OpenSSH-Win64.zip

So if I do a check sum on a file I download from the current release for a package for 12_22_2015 - the package will break when you release a new version.

If when a new current version was made available, it was also available at it's versioned URL immediately - I could safely checksum the file against that URL even when new versions come out.

I hope that makes sense - but let me know if it does not.

**Comment by manojampalam** [comment]
Makes sense. Let me see if there is a way multi tag a single release in GitHub. If that's not possible, we may need to duplicate.

**Comment by manojampalam** [comment]
Looks like I've abusing GIT tags so far :). I've fixed it. From now on, this URL https://github.com/PowerShell/Win32-OpenSSH/releases/latest/
resolves to a link to the latest release. Ex
https://github.com/PowerShell/Win32-OpenSSH/releases/tag/2_25_2016
The actual payload is at
https://github.com/PowerShell/Win32-OpenSSH/releases/download/2_25_2016/OpenSSH-Win64.zip

So, it takes a bit of URL and string manipulation to get the download link but tags once created will remain static going forward. Hope this helps.

**Comment by manojampalam** [comment]
Latest download links can be obtained in Powershell as follows:

$url = 'https://github.com/PowerShell/Win32-OpenSSH/releases/latest/'
$request = [System.Net.WebRequest]::Create($url)
$request.AllowAutoRedirect=$false
$response=$request.GetResponse()
([String]$response.GetResponseHeader("Location")).Replace('tag','downloads') + '/OpenSSH-Win64.zip'
([String]$response.GetResponseHeader("Location")).Replace('tag','download') + '/OpenSSH-Win32.zip'

**Comment by manojampalam** [comment]
Above instructions added to wiki https://github.com/PowerShell/Win32-OpenSSH/wiki/How-to-retrieve-links-to-latest-packages

**Comment by manojampalam** [comment]
Leave a comment

**Comment by DarwinJS** [comment]
That just rocks - thanks for taking this seriously and for the super fast solution!
