### ISSUE TITLE
sshd fails while powershell is the default shell and the path and OpenSSH is inside a folder that contains space character

### ISSUE THREAD

**Issue by Pigwannafly** [PowerShell/Win32-OpenSSH#1370]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 7.7p1
 
**Server OperatingSystem**
Windows 10

**Client OperatingSystem**
 Debian GNU/Linux 9.4 (stretch)

**What is failing**
For a simple repro, on the server which is the windows machine, configure the default ssh shell in the windows registry, set Computer\HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH\DefaultShell to be the full path of powershell.exe. In addition, install OpenSSH for Windows under "C:\\Program Files" so that the full path of sftp-server.exe contains space character. On the server, run sshd with Forcecommand=internal-sftp and Subsystem=sftp=internal-sftp and then run sshfs on clinet machine.

The connection is not built successfully and in debug mode, I can see that the failing command is <\path\to\powershell.exe> -c <\path\to\sftp-server.exe>. The reason is that the path to sftp-server contains space characters. If OpenSSH is installed under another folder without space, everything works fine.

**Expected output**
The connection should be built successfully

**Actual output**
The connection fails to set up

**Comment by maertendMSFT** [comment]
This should be resolved, please try the latest release.
