### ISSUE TITLE
ssh cmd /c ver shows error: 'ver"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by StefanScherer** [PowerShell/Win32-OpenSSH#1373]
Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 7.7.2.2

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows Server 2019 Datacenter Evaluation

**Client OperatingSystem**
macOS 10.14.4

**What is failing**
Running the following command `cmd /c ver` through SSH does not work. 

**Expected output**
```
Microsoft Windows [Version 10.0.17763.437]                                      
```

**Actual output**
```
'ver"' is not recognized as an internal or external command,
operable program or batch file.
```

When I looked closer I saw a double quote `ver"`.

So I tried a little more:

```
$ ssh -p 2222 User03@localhost cmd /c ver
User03@localhost's password:
'ver"' is not recognized as an internal or external command,
operable program or batch file.
~                                                                               
$ ssh -p 2222 User03@localhost "cmd /c ver"
User03@localhost's password:
'ver"' is not recognized as an internal or external command,
operable program or batch file.
~                                                                               
$ ssh -p 2222 User03@localhost "cmd /c ver "
User03@localhost's password:

Microsoft Windows [Version 10.0.17763.437]
```

When I append a blank to my command then it works.

This command `cmd /c ver` is used by InSpec to recognize a Windows backend. I want to add SSH support for Windows in InSpec with https://github.com/inspec/train/pull/416 but struggle with that tiny difference. The original OpenSSH Windows port does not have this problem, only this native port seems to add quotes. I added a [workaround to call `ver` in my PR](https://github.com/inspec/train/pull/416/files#diff-c0c5840279f2347747dfb128d8a5f087R8) if `cmd /c ver` fails, but then we need two commands to detect Windows.
The detection is also used for WinRM connects, that's why `cmd /c ver` is used to start a cmd.exe from within the PowerShell session.

**Comment by StefanScherer** [comment]
I have also prepared a Windows Container image with a test user `User03` and `Passw0rd` to have a portable test environment to reproduce the problem.

```
$ docker run -d -p 2222:22 stefanscherer/openssh-windows
$ ssh -p 2222 User03@localhost cmd /c ver
User03@localhost's password:
'ver"' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by jborean93** [comment]
If you do `cmd.exe /c var` it should work as it starts the new executable cmd.exe. When debugging the command the process that is actually run is `C:\Windows\System32\cmd.exe /c "cmd /c ver"`. Command prompt has some weird rules around quoting and making sure you specify the extension seems to be enough to get around that.

You could also just do `ssh user@host ver` as the default shell is already cmd but that might be a bit inflexible as users can change their shell.

**Comment by StefanScherer** [comment]
Thanks @jborean93 I'll try that.

The `cmd /c ver` is needed as the InSpec/train module also supports WinRM and then lands in a PowerShell session. Therefore it has to start a cmd shell to finally run the ver command.

But `cmd.exe /c ver` should work for all scenarios there.

**Comment by StefanScherer** [comment]
Thanks @jborean93 for the tip. This really works and keeps the code more clean in InSpec train gem.
