### ISSUE TITLE
Typed input sometimes doubled in terminal

### ISSUE THREAD

**Issue by EricSL** [PowerShell/Win32-OpenSSH#1374]
Please answer the following

**"OpenSSH for Windows" version**
Tested on 7.7 and 7.9
 
**Server OperatingSystem**
Debian GNU/Linux 9.4

**Client OperatingSystem**
Windows 10

**What is failing**

Steps to reproduce:

1. Use a cmd shell that you have already been using which has a few screenfuls of text
2. ssh to a server
3. When you get a command prompt, scroll up by a few buffer heights so that your ssh session
is off screen.
4. Press "e"
5. Repeat step 3, typing a command like "echo x" one letter at a time while scrolled off screen.

**Expected output**

The command line should show that you typed "echo x" and then the server printed "x"

**Actual output**

Some letters you typed will be doubled in your console, for example "eechho   xx", but the server got the correct input and will print "x"

**Comment by maertendMSFT** [comment]
Please try the latest release.
