### ISSUE TITLE
How change dos command promt?

### ISSUE THREAD

**Issue by ilwsm** [PowerShell/Win32-OpenSSH#1379]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
7.7.2.1
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
linux

**What is failing**
dos command prompt

**Expected output**
c:\Users\Andrey
\>

**Actual output**
andrey@DESKTOP-blablabla c:\Users\Andrey>
![image](https://user-images.githubusercontent.com/2471892/57234873-50ea9900-702a-11e9-95e0-6770b6866cf9.png)

**Comment by arwinters** [comment]
You have to upgrade Win32-OpenSSH to version v7.9.0.0p1-Beta or above. Then add the following registry key HKLM:\SOFTWARE\OpenSSH\DefaultShell with value C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

The registry key type == string

**Comment by qtxo** [comment]
How to upgrade? I can only download source code:
https://github.com/PowerShell/openssh-portable/releases/tag/v7.9.0.0

**Comment by ilwsm** [comment]
And, why you advise me `powershell` instead `cmd`?

**Comment by arwinters** [comment]
That's right. Download the source and read the instructions (from this repository). Look in the directory contrib\win32. Use Visual Studio to compile the source, and use the PowerShell install script to install the new version on your Windows host.

**Comment by arwinters** [comment]
> And, why you advise me `powershell` instead `cmd`?

I interpreted the title of this issue to change the command prompt to PowerShell and posted the solution for that. I understand that you have a problem with getting cmd prompt.  In PowerShell you need to activate OpenSSH. Run this cmdlet with administrator privileges. And if you like to switch to PowerShell when accessing through ssh, you now know how to do that to :-) 

> Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

**Comment by ilwsm** [comment]
I want do that with default shell!
My question about default shell `cmd`.

**Comment by manojampalam** [comment]
do 
`set PROMPT=$P$G`
from within the remote session

**Comment by ilwsm** [comment]
Already, but problem is exist

**Comment by matsmcp** [comment]
The binary releases are at https://github.com/PowerShell/Win32-OpenSSH/releases.

They are NOT up to date though. It would be nice if we could get a new bin relase including the fixed ssh.exe

**Comment by manojampalam** [comment]
doing this from within the remote session worked for me. Please double check
`set PROMPT=$P$G`
