### ISSUE TITLE
204 GB sshd.log in 14 days (.5 GB/hour)

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#138]
Three days ago my primary SSD filled up when I could have sworn I had a ton of space.

Just now while creating the chocolatey installer for 2_25_2016 I see that this file is 204 GB.

This is after about 14 days of the service running.  So about 1/2 gig per hour.

I can't find a text editor capable of opening it.

I will zip it and keep it for while if anyone on the dev team wants a copy.

**Comment by quamrulmina** [comment]
reduce your logging level by commenting out LogLevel in sshd_config file. It is located in the directory where your sshd.exe is. Comment out (#LogLevel .. ) or have it as "LogLevel INFO" . Restart your win32 sshd to make the change effective.

**Comment by DarwinJS** [comment]
I have a completely default config file and logging is indeed commented.  

Does the log get lines from specific types of errors that ignore the LogLevel because they are more fundamental (like not finding a critical folder, etc)?

**Comment by jhudsoncedaron** [comment]
Go get a copy of tail.exe from unxutils and post the last 100 or so lines.

**Comment by DarwinJS** [comment]
Tried baretail.exe and it choked.

Good old Get-Content from powershell worked - it started from the start of the file which didn't matter because it is all this:


5920 11:02:05 067 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 067 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 067 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]
5920 11:02:05 068 fatal: WaitForMultipleObjects failed with error code [87]

**Comment by alexchandel** [comment]
This happened to me too on the 2016-02-25 build, even though I had LogLevel commented out. I had to uncomment it and change it to quiet.

**Comment by DarwinJS** [comment]
I just pushed version 2016.02.25.20150315 of the Chocolatey package.

If it find the default log setting of "#LogLevel INFO" (commented) it changes it to "LogLevel QUIET" - otherwise it leaves it alone.

**Comment by alexchandel** [comment]
@DarwinJS Actually this doesn't happen with the chocolatey package. Just when I installed it from the command line.

**Comment by DarwinJS** [comment]
@alexchandel - if you just retested you may already have gotten the *updated* chocolatey package which was approved this morning and now forces the log off - check your sshd_config to see if logging is set to QUIET.

Before I did the chocolatey package update, the chocolatey package did the nasty logging as well.

**Comment by alexchandel** [comment]
@DarwinJS I didn't just retest.

**Comment by ghost** [comment]
I just downloaded the latest build today from github and had same issue with logging using default settings. Logfile reached 15 GB just after a couple hours of use.

I apologize I didn't do too much investigation as my OS is on a 60GB SSD with my static storage on a separate drive. When it filled up my disk I went into nuke first ask questions later mode ;).

EDIT: Do not experience this issue in chocolatey release with default sshd_config value of LogLevel QUIET

**Comment by luanthom** [comment]
I also had this problem with vast number of entries in the log file filing the 200Gb in a few days. I also could not connect via SSH to the server. I changed to "LogLevel QUIET" and zero entries in the log but the server started working.

**Comment by manojampalam** [comment]
This should have gone away by now. Reopen if needed.
