### ISSUE TITLE
CD to other drive

### ISSUE THREAD

**Issue by dipiana** [PowerShell/Win32-OpenSSH#1384]
Hi,

I was trying hard to CD to a different drive (USB-stick) which is assigned to the letter F:
When I try "cd f:/" no error is shown, but I don't change directory. I am still in "C:\Users\username".

How can I change to F: ?

Thanks a lot!

**Comment by dipiana** [comment]
Found out it works if you only type "F:" (without "cd").

**Comment by puxu-msft** [comment]
It seems in `cmd.exe`, so you can also try `cd /d f:\`.
