### ISSUE TITLE
Java client sftp fails

### ISSUE THREAD

**Issue by shorbachuk** [PowerShell/Win32-OpenSSH#1386]
debug1: sshd version OpenSSH_for_Windows_7.9, LibreSSL 2.6.5
debug1: get_passwd: LookupAccountName() failed: 1332.
debug1: private host key #0: ssh-rsa SHA256:<REDACTED>
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:<REDACTED>
debug1: private host key #2: ssh-ed25519 SHA256:<REDACTED>
debug1: rexec_argv[0]='sshd.exe'
debug1: rexec_argv[1]='-d'
debug1: Bind to port 22 on ::.
Server listening on :: port 22.
debug1: Bind to port 22 on 0.0.0.0.
Server listening on 0.0.0.0 port 22.
debug1: Server will not fork when running in debugging mode.
Connection from 10.<REDACTED> port 51676 on 10.<REDACTED> port 22
debug1: Client protocol version 2.0; client software version SSHJ_0_13_0
debug1: no match: SSHJ_0_13_0
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.9
debug1: sshd version OpenSSH_for_Windows_7.9, LibreSSL 2.6.5
debug1: get_passwd: LookupAccountName() failed: 1332.
debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
debug1: SSH2_MSG_KEXINIT sent [preauth]
debug1: SSH2_MSG_KEXINIT received [preauth]
debug1: kex: algorithm: diffie-hellman-group14-sha1 [preauth]
debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1 compression: none [preauth]
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1 compression: none [preauth]
debug1: expecting SSH2_MSG_KEXDH_INIT [preauth]
debug1: rekey after 4294967296 blocks [preauth]
debug1: SSH2_MSG_NEWKEYS sent [preauth]
debug1: expecting SSH2_MSG_NEWKEYS [preauth]
debug1: SSH2_MSG_NEWKEYS received [preauth]
debug1: rekey after 4294967296 blocks [preauth]
debug1: KEX done [preauth]
debug1: userauth-request for user S<REDACTED>@<REDACTED>.com service ssh-connection method password [preauth]
debug1: attempt 0 failures 0 [preauth]
debug1: user <REDACTED>\\s<REDACTED> matched group list administrators at line 88
Accepted password for S<REDACTED>@<REDACTED>com from 10.<REDACTED> port 51676 ssh2
debug1: monitor_child_preauth: S<REDACTED>@<REDACTED>.com has been authenticated by privileged process
debug1: monitor_read_log: child log fd closed
User child is on pid 4680
debug1: sshd version OpenSSH_for_Windows_7.9, LibreSSL 2.6.5
debug1: get_passwd: LookupAccountName() failed: 1332.
debug1: user n matched group list administrators at line 88
Changed root directory to "E:\\"
debug1: rekey after 4294967296 blocks
debug1: rekey after 4294967296 blocks
debug1: ssh_packet_set_postauth: called
debug1: active: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Entering interactive session for SSH2.
debug1: server_init_dispatch
debug1: Received SSH2_MSG_UNIMPLEMENTED for 5
debug1: server_input_channel_open: ctype session rchan 0 win 2097152 max 32768
debug1: input_session_request
debug1: channel 0: new [server-session]
debug1: session_new: session 0
debug1: session_open: channel 0
debug1: session_open: session 0: link with channel 0
debug1: server_input_channel_open: confirm session
debug1: server_input_channel_req: channel 0 request subsystem reply 1
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req subsystem
debug1: subsystem: cannot stat sftp-server.exe: No such file or directory
debug1: subsystem: exec() sftp-server.exe
Starting session: subsystem 'sftp' for <REDACTED>\\s<REDACTED> from 10.<REDACTED>port 51676 id 0
debug1: session_by_channel: session 0 channel 0
debug1: session_close_by_channel: channel 0 child 8928
debug1: session_close_by_channel: channel 0: has child, ttyfd -1
debug1: Received SIGCHLD.
debug1: session_by_pid: pid 8928
debug1: session_exit_message: session 0 channel 0 pid 8928
debug1: session_exit_message: release channel 0
debug1: session_by_channel: session 0 channel 0
debug1: session_close_by_channel: channel 0 child 0
Close session: user <REDACTED>\\s<REDACTED>from 10.<REDACTED> port 51676 id 0
debug1: channel 0: free: server-session, nchannels 1
Received disconnect from 10.<REDACTED> port 51676:11:
Disconnected from 10.<REDACTED>port 51676
debug1: do_cleanup
debug1: do_cleanup
sshd.exe exited on <REDACTED> with error code 255.

**"OpenSSH for Windows" version**
7.9.0.0
 
**Server OperatingSystem**
Windows Server 2016 Standard

**Client OperatingSystem**
Unknown (Java Client)

**What is failing**
SFTP File transfer fails to complete

**Comment by manojampalam** [comment]
Please get SFTP server side traces using steps at 
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps
https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities
