### ISSUE TITLE
Enter-PSSession : The SSH client session has ended with error message: The SSH transport process has abruptly terminated causing this remote session to break.

### ISSUE THREAD

**Issue by eliassal** [PowerShell/Win32-OpenSSH#1388]
**"OpenSSH for Windows" version**
last version
 
**Server OperatingSystem**
win 2019
**Client OperatingSystem**
Centos 7
**What is failing**
Remote session from Centos to windows server
**Expected output**
I do 
 

> Enter-PSSession 192.168.20.70 -UserName salam@mydomnain

or

> Enter-PSSession 192.168.20.70 -SSHTransport

I get prompted to enter my password, a remote session to windows server to be opened
**Actual output**

On Centos I get
Enter-PSSession : The SSH client session has ended with error message: The SSH transport process has abruptly terminated causing this remote session to break.

on the server, in the event log I have the following 3 messages logged
3 - sshd: Disconnected from 192.168.20.12 port 41493
2 - sshd: Received disconnect from 192.168.20.12 port 41493:11: disconnected by user
1 - sshd: Accepted password for salam@mydomain from 192.168.20.12 port 41493 ssh2

**Comment by manojampalam** [comment]
Assuming you setup your server using steps at https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-6 ?

**Comment by eliassal** [comment]
Yes Sir

**Comment by manojampalam** [comment]
Please get debug traces from target. Follow steps at https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Comment by eliassal** [comment]
I did in thread #1387
https://github.com/PowerShell/Win32-OpenSSH/issues/1387
