### ISSUE TITLE
How to import existing pubkey to Windows Server

### ISSUE THREAD

**Issue by viggy96** [PowerShell/Win32-OpenSSH#1391]
I can't seem to import my ssh pubkey into Windows Server 2016 properly. I have tried putting it in C:\Users\USERNAME\\.ssh\authorized_keys, and %PROGRAMDATA%\ssh\administrators_authorized_keys, and neither location seems to work. 

Can you guys help?

**Comment by dwatley** [comment]
Is your config file enabled to use key files?

`PubkeyAuthentication yes`

You should attach debug logs if you can't get a connection going.

**Comment by manojampalam** [comment]
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps may help

**Comment by matsmcp** [comment]
Do you have the right permissions on the files. 
Openssh is sensitive about that and may reject a valid fileif the permissions are too relaxed

**Comment by manojampalam** [comment]
See if this helps:
https://github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-Win32-OpenSSH
