### ISSUE TITLE
ssh-keygen fails to convert ECDSA Base64 PEM Key to SSH Key

### ISSUE THREAD

**Issue by miketheitguy** [PowerShell/Win32-OpenSSH#1392]
**Troubleshooting steps**
1. Generate an ECDSA P384 Public/private X.509 Certificate Keypair
2. Use OpenSSL to export public key from public certificate.
3. Execute `ssh-keygen -vvv -i -f mypubkey.pem -m "PKCS8"`

**Terminal issue? please go through wiki**
Nope

**"OpenSSH for Windows" version**
7.9.0.0
 
**Client OperatingSystem**
Windows 10 18898

**What is failing**
Import/Dump of Base64 PEM to SSH Key formats.

**Expected output**
an SSH public key in STDOUT

**Actual output**
Nothing

**Notes**
Workaround is to use WSL version. Issue affects included version of OpenSSH with Windows 10; but I manually updated to the beta to see if it was resolved in this version.

May affect other key types as well, but for my purposes I'm using ECDSA keys.

**Comment by miketheitguy** [comment]
<img width="791" alt="annoying_bug" src="https://user-images.githubusercontent.com/8938349/58385713-73c4f900-7fa9-11e9-86e1-151daab90e1f.png">

**Comment by v5pham** [comment]
Reported the same issue (https://github.com/PowerShell/Win32-OpenSSH/issues/1400) which was a mistake on my part.

**Comment by manojampalam** [comment]
dup above.

**Comment by jgallucci32** [comment]
I can reproduce the issue and notice the following errors in Windows Event Viewer

**Event 1000, Application Error**
```
Faulting application name: ssh-keygen.exe, version: 7.7.2.1, time stamp: 0x5b60b79a
Faulting module name: libcrypto.dll, version: 2.6.5.1, time stamp: 0x5b6de5de
Exception code: 0xc0000409
Fault offset: 0x00000000000e5008
Faulting process id: 0x38a0
Faulting application start time: 0x01d680cb85bf9e1c
Faulting application path: C:\windows\System32\OpenSSH\ssh-keygen.exe
Faulting module path: C:\windows\SYSTEM32\libcrypto.dll
Report Id: 49e87e22-424b-4289-9cd6-94f4e36ce8a1
Faulting package full name: 
Faulting package-relative application ID: 
```
