### ISSUE TITLE
"critical stop" sound played when pressing backspace in empty line

### ISSUE THREAD

**Issue by vlschmidt** [PowerShell/Win32-OpenSSH#1394]
When connecting to a linux client, the "critical stop" sound is played when pressing backspace in terminal or when pressing tab with multiple options... this can get annoying really fast and I found no decent way to turn this "feature" off... Is this intended?

Please answer the following

**"OpenSSH for Windows" version**
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Ubuntu 18.04.2 LTS (GNU/Linux 4.9.140-tegra aarch64)

**Comment by DHowett-MSFT** [comment]
This is intended. The shell on the other end is emitting a "bell" indicator to indicate that you've done something wrong. SSH is sending that up to the terminal, and the terminal takes the "bell" indicator and produces a sound.

If you edit `/etc/inputrc` on the Linux server and add the following line, the "bell"ing will stop _for all ssh clients, everywhere_

```
set bell-style none
```

(more information [here](https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File-Syntax.html#Readline-Init-File-Syntax), in the _readline_ documentation).

**Comment by DHowett-MSFT** [comment]
You can also put that line in `~/.inputrc` if you do not have root access.

**Comment by vlschmidt** [comment]
@DHowett-MSFT Thanks for the response! You are correct, turning off the bell-style in the server fixes this issue for me. I thought it was the client due to the fact that working direclty on the machine did not produce the bell sounds.
