### ISSUE TITLE
Cannot login with SSH-KEY

### ISSUE THREAD

**Issue by bob-2165** [PowerShell/Win32-OpenSSH#1398]
v7.9.0.0p1
 
Windows 2012 R2

**Issue**
I am obtaining a key from Sucuri to paste inside the ~/.ssh/authorized_keys file. After doing this the Sucuri SFTP does not connect. The host name, FTP username, and Port are all correct. Any steps to try to ensure that I can connect via SSH-KEY? I am able to connect to the same user just through normal SFTP with user authentication in Windows.

**Expected output**
Connection through SSH-KEY.

**Actual output**
Cannot connect.

**Comment by Outek** [comment]
Most of the time, the problem are the wrong file permissions. Did you try to run FixHostFilePermissions and FixUserFilePermissions?

**Comment by manojampalam** [comment]
See if this helps:
https://github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-Win32-OpenSSH
