### ISSUE TITLE
sudo password in plain text

### ISSUE THREAD

**Issue by jungle-boogie** [PowerShell/Win32-OpenSSH#14]
Hello Microsoft,

I found it funny that you want to hide yes for this prompt:
`Are you sure you want to continue connecting (yes/no)? ***`

But it's definitely wrong to print the sudo password in plain text:
`sudo -v`
`sudo -v←[?2004l`
`Password:microsoft`

**Comment by dwimsey** [comment]
Sounds like your client isn't specifying TERM type properly or whatever sudo you're using is unaware of your term type and is behaving badly because of it.

**Comment by jungle-boogie** [comment]
Hi @dwimsey,

How would you suggest I check this?

Thanks!

**Comment by quamrulmina** [comment]
Fixed in upcoming release.

**Comment by manojampalam** [comment]
Fixed in the latest release.
