### ISSUE TITLE
"ChrootDirectory" not working using the 12_22_2015 release ?

### ISSUE THREAD

**Issue by mrizzi2** [PowerShell/Win32-OpenSSH#140]
Hello and good day,

I need to lock all users into the "C:\sftproot" directory using a chroot, so I have uncommented the configuration accordingly on the config file:

==================================================
ChrootDirectory C:\sftproot
==================================================

Have I missed a configuration step or is this a bug?

I am using the 12_22_2015 release.

Thank you and have a great day.

**Comment by nachfuellbar** [comment]
https://github.com/PowerShell/Win32-OpenSSH/issues/126
quamrulmina wrote:

> Chroot feature does not work in Windows. In Windows sftp server, home directories are set to the user's actual home directories ( like c:/users/username or c:/users/suername.domainname )

**Comment by ZakThePotter** [comment]
How I can lock user in specified Directory?

**Comment by mrPsycho** [comment]
especially if this directory on another drive

**Comment by mhaneef14** [comment]
I installed OPenSSH on windows 2012 R2 it works fine but dafault folder goes to user profile in C drive only.
I tried changing drive other than C but does not show other drives. any clue.
