### ISSUE TITLE
SFTP cannot save fetched file when local path contains non-latin character

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#1401]
**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 7.7.2.2

**Server OperatingSystem**
Ubuntu 18.04.2 LTS (Azure)

**Client OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 Enterprise 1904
`([environment]::OSVersion.Version)`

```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18362  0
```
**What is failing**
sftp cannot save downloaded file when path contains non-latin character (e.g. in user name part)

**Expected output**

**Actual output**
XXX and YYY are replacements for privacy.
Character `ł` is the problem. When local path is changed, file downloads without an issue.

``` cmd
PS C:\Users\XXXXłXXXXXXXX> cd ~
PS C:\Users\XXXXłXXXXXXXX> sftp srv3
Enter passphrase for key 'C:\Users\XXXXłXXXXXXXX/.ssh/srv3XXXX':
Connected to srv3.
sftp> get rmlist.txt
Fetching /home/YYYYYYYY/rmlist.txt to rmlist.txt
Couldn't open local file "rmlist.txt" for writing: No such file or directory
sftp> lcd f:\
sftp> get rmlist.txt
Fetching /home/YYYYYYYY/rmlist.txt to rmlist.txt
/home/YYYYYYYY/rmlist.txt                                                            100%   15KB 149.8KB/s   00:00     
sftp>
```

**Comment by NoMoreFood** [comment]
@manojampalam I know the cause of this.  I'll put in a PR to address unless you already have it handled.

**Comment by manojampalam** [comment]
@NoMoreFood not yet. Please do.
