### ISSUE TITLE
Domain authentication not working

### ISSUE THREAD

**Issue by nForcer** [PowerShell/Win32-OpenSSH#1402]
**"OpenSSH for Windows" version**
v7.9.0.0p1-Beta
 
**Server OperatingSystem**
Windows Server 2019

**Client OperatingSystem**
Windows 10

**What is failing**
Login with domain user fails every time. Error message: authentication failed. Local user works fine. The issue occurs with every domain user permitted to use the sftp server. 

Server Logfiles:
[sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/3276499/sshd.log)

Server config:
[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/3276423/sshd_config.txt)

**Comment by manojampalam** [comment]
@nomorefood as FYI
Looks like we have an issue along password authentication path for domain accounts. 

Also found following formatting issues that need to be addressed in logs :
- user \f matched group list....
- ....because user \f does not exist

@nForcer can you try using key based auth as a work around ?

**Comment by NoMoreFood** [comment]
@nForcer What username format are you using to login (van00.local\sftppull or van00\sftppull)?

**Comment by nForcer** [comment]
@manojampalam sadly key based auth is not an option right now. the customer only wants password auth at the moment.
But to localize the error i will try key based auth and will give you guys a report.

@NoMoreFood I did try both formats. Been even as crazy as trying van00.local\sftppull@van00.local or based on the microsoft articel sftppull?van00.local or sftppull@van00.local. Sadly nothing works.

**Comment by NoMoreFood** [comment]
@nForcer Actually I think this might be from the group matching bug I fixed.   Try the binaries here:

https://github.com/NoMoreFood/openssh-portable/releases/tag/v7.9-merge-3

**Comment by nForcer** [comment]
@NoMoreFood your binaries seem to work. I will test the whole thing with some users and will give you guys a feedback on next tuesday.

**Comment by nForcer** [comment]
@NoMoreFood everything works fine. Thank you guys for your support
