### ISSUE TITLE
SSHD crashes when GSSAPI auth is enabled

### ISSUE THREAD

**Issue by manojampalam** [PowerShell/Win32-OpenSSH#1405]
**"OpenSSH for Windows" version**
V7.9.0.0
 
**Server OperatingSystem**
Any

**Client OperatingSystem**
Any

**What is failing**
Configure server to use GSSAPI authentication. Logging in via a domain account works. But logging in using a workgroup account with client side configured to use GSSAPI auth results in a server side crash
Do either this
`ssh -K workgroupaccount@domain.joined.target.com`
or the following with GSSAPI enabled in client side ssh_config 
```
#in client config
GSSAPIAuthentication yes
#do this
ssh workgroupaccount@domain.joined.target.com
```

**Expected output**
remote session is opened using workgroup accounts

**Actual output**
client_loop: send disconnect: Connection reset

**Comment by manojampalam** [comment]
@nomorefood please take a look when you have a chance.

**Comment by NoMoreFood** [comment]
@manojampalam Will take a look.  Are you executing the SSH client whilst logged in under a domain account?  Just trying to understand the circumstances.

**Comment by manojampalam** [comment]
@NoMoreFood Yes. AFAIR, from traces, client is sending initial GSSAPI token of the logged in domain user, as it attempts to authenticate the workgroup account over GSSAPI.

**Comment by NoMoreFood** [comment]
@manojampalam Am able to reproduce.  Error is occurring when trying to cleanup the unusable credential handle.  Fix should be in shortly.

**Comment by mgkuhn** [comment]
issue can be closed?

**Comment by NoMoreFood** [comment]
Yes.
