### ISSUE TITLE
There is no longer a binary release for 7.9.0.0-Beta1 on github releases?

### ISSUE THREAD

**Issue by petemounce** [PowerShell/Win32-OpenSSH#1409]
Last week, I was able to download https://github.com/PowerShell/Win32-OpenSSH/releases/download/v7.9.0.0p1-Beta/OpenSSH-Win64.zip

When I tried moments ago, it 404s. Has it been removed?

I notice a new release, 8.0.0.0, has been added to https://github.com/PowerShell/Win32-OpenSSH 's README - that is not yet reflected on the github releases. 

Is a release in-flight right at the moment and I'm just concurrent with it? @manojampalam edited that file 40 minutes ago, so this seems likeliest?

If so - I'd like to still be able to download the 7.9.0.0p1-Beta distribution, please. That works fine for me and I'd rather upgrade to it smoothly than be blocked.

**Comment by manojampalam** [comment]
Working on pushing 8.0 out. 7.9 got mysteriously deleted in the process, I'm trying to figure out why. I've manged to salvage release notes. Trying to track down 7.9 build binaries. Please stay tuned.

**Comment by manojampalam** [comment]
Got 7.9 bits restored.

**Comment by petemounce** [comment]
Thank you!
