### ISSUE TITLE
Attempting to connect to same machine using ssh

### ISSUE THREAD

**Issue by Aamir-Raza** [PowerShell/Win32-OpenSSH#1410]
**"OpenSSH for Windows" version**
OpenSSH_7.9p1, OpenSSL 1.1.1a  20 Nov 2018

 **Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
So I'm not sure if I'm doing something that isn't possible here, trying to ssh into the same machine that I installed the OpenSSH server on. I see the OpenSSH Server in services and ensured it's running. Netstat shows port 22 is listening. I'm on an admin account on this PC, tried running ssh through Powershell and Git Bash but it always throws the Permission Denied error:

> $ ssh Aamir@localhost
> Aamir@localhost's password:
> Permission denied, please try again.
> Aamir@localhost's password:
> Permission denied, please try again.
> Aamir@localhost's password:
> Aamir@localhost: Permission denied (publickey,password,keyboard-interactive).

**Expected output**
Successfull sign-in

**Actual output**
Permission denied, please try again. :(

Any ideas where I went wrong? I'm entering the same password that I use for my Windows login (admin account)

**Comment by manojampalam** [comment]
`OpenSSH_7.9p1, OpenSSL 1.1.1`
Are you sure, you are using the right version of OpenSSH. The ones supported by this repo are never compiled with OpenSSL.

**Comment by Aamir-Raza** [comment]
> 
> 
> `OpenSSH_7.9p1, OpenSSL 1.1.1`
> Are you sure, you are using the right version of OpenSSH. The ones supported by this repo are never compiled with OpenSSL.

Yeah, the version in my post is straight from Git Bash (copied from terminal)

Git Bash: OpenSSH_7.9p1, OpenSSL 1.1.1a  20 Nov 2018
Powershell: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

Just to note, I've tried ssh to a domain I own and it works fine, it's just localhost that doesn't work. I can post the verbose log here if you like?

**Comment by manojampalam** [comment]
Sure. FYI, this version of OpenSSH is not from this project. 
`Git Bash: OpenSSH_7.9p1, OpenSSL 1.1.1a 20 Nov 2018`

**Comment by Aamir-Raza** [comment]
> 
> 
> Sure. FYI, this version of OpenSSH is not from this project.
> `Git Bash: OpenSSH_7.9p1, OpenSSL 1.1.1a 20 Nov 2018`

I hear you, I was just trying multiple terminals I guess. Here's a Powershell log:

```
PS C:\Users\Aamir> ssh -v localhost
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Connecting to localhost [::1] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\Aamir/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\Aamir/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\Aamir/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\Aamir/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\Aamir/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\Aamir/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\Aamir/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\Aamir/.ssh/id_ed25519-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\Aamir/.ssh/id_xmss type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\Aamir/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_7.7
debug1: match: OpenSSH_for_Windows_7.7 pat OpenSSH* compat 0x04000000
debug1: Authenticating to localhost:22 as 'aamir'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:edye8qInW+3FZbdM2I0xsHv1vDdCeT4ta6GhFZHjtKA
debug1: read_passphrase: can't open /dev/tty: No such file or directory
The authenticity of host 'localhost (::1)' can't be established.
ECDSA key fingerprint is SHA256:edye8qInW+3FZbdM2I0xsHv1vDdCeT4ta6GhFZHjtKA.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Trying private key: C:\\Users\\Aamir/.ssh/id_rsa
debug1: Trying private key: C:\\Users\\Aamir/.ssh/id_dsa
debug1: Trying private key: C:\\Users\\Aamir/.ssh/id_ecdsa
debug1: Trying private key: C:\\Users\\Aamir/.ssh/id_ed25519
debug1: Trying private key: C:\\Users\\Aamir/.ssh/id_xmss
debug1: Next authentication method: keyboard-interactive
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: password
debug1: read_passphrase: can't open /dev/tty: No such file or directory
aamir@localhost's password:
debug1: Authentications that can continue: publickey,password,keyboard-interactive
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: No such file or directory
aamir@localhost's password:
debug1: Authentications that can continue: publickey,password,keyboard-interactive
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: No such file or directory
aamir@localhost's password:
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: No more authentication methods to try.
aamir@localhost: Permission denied (publickey,password,keyboard-interactive).
```

edit: I can login from both terminals fine on another ssh server, it's just my machine where it doesn't work. I'm entering the same password as my login, which is the only account (admin) on this machine.

**Comment by Aamir-Raza** [comment]
Wondering if my issue is related to this at all:
https://github.com/PowerShell/Win32-OpenSSH/issues/1413

My Machine Name and Username are also the same.

**Comment by NoMoreFood** [comment]
@Aamir-Raza Very possibly.  Does changing your username or machine name resolve the issue?

**Comment by Aamir-Raza** [comment]
> 
> 
> @Aamir-Raza Very possibly. Does changing your username or machine name resolve the issue?

I was able to create a test account and _ssh test@localhost_ worked from the same machine and my phone! Later I changed the machine name and it solved everything!! 👍 

Looks like you cannot have the same machine name and username then. Ty for help 😃
