### ISSUE TITLE
Status of 7.9.0.0 p1 ?

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#1411]
Github is saying 7.9.0.0 p1 was just released - but I've had it packaged for quite a while.

Can you clarify if the compiled binaries have actually changed recently?

**Comment by pd93** [comment]
[v8.0.0.0 has been released](https://github.com/PowerShell/openssh-portable/releases/tag/v8.0.0.0), but there is no corresponding release in this repo - You'd have to compile the code yourself. As @DarwinJS says, v7.9.0.0 has been released for quite some time (Jan 19).

I'm still slightly puzzled as to why there are 2 repositories for tracking this project. It's all very confusing.

**Comment by manojampalam** [comment]
Please see https://github.com/PowerShell/Win32-OpenSSH/issues/1409

**Comment by pd93** [comment]
@manojampalam Thanks for the info. 

While we're discussing releases.. Would you mind sharing how these releases get merged into Windows 10 (if you know)?

- Do they just cut the latest Win32-OpenSSH for each major release of Windows? 
- Or is it updated via cumulative updates?
- Or something else?

Curious when v8.0.0.0 (with the ProxyJump fix) would get into an official Windows build without having to patch `ssh.exe` myself.

Thanks!

**Comment by DarwinJS** [comment]
I can't find binaries in the other repo?

I thought the MS release was going to support back to windows 7?  How do we get the v8.0.0.0 binaries for Windows ?

**Comment by manojampalam** [comment]
@DarwinJS I'm going to release v8.0.0.0 binaries later today. 

@pd93, the plan is to cut the latest, well tested version of Win32-OpenSSH for each major release/update of Windows. If all is well, you could expect 8.0 in [1909](https://en.wikipedia.org/wiki/Windows_10) update

**Comment by ValZapod** [comment]
@manojampalam Hey, I still have OpenSSH_for_Windows_7.7p1 in my 1909.
