### ISSUE TITLE
sshd rejecting all connections with or without rsa key with broken pipe error

### ISSUE THREAD

**Issue by bagness** [PowerShell/Win32-OpenSSH#1412]
**Troubleshooting steps**
I have tried ssh with and without RSA key and every time I get a broken pipe error.  I am running OpenSSH V7.90-Beta.  

Please answer the following

**"OpenSSH for Windows" version**
OpenSSH V7.9.0-Beta
 
**Server OperatingSystem**
Windows 2012 R2

**Client OperatingSystem**
MacOS X 10.14.5

**What is failing**
Any ssh or sftp attempt is failing with a Broken Pipe error

**Expected output**
Successful login with or without RSA key

**Actual output**
packet_write_wait: Connection to 10.0.0.1 port 22: Broken pipe

**Comment by manojampalam** [comment]
See https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps. 

Guessing you mostly likely have file permissions issue.
