### ISSUE TITLE
OPENSSH logs missing Date

### ISSUE THREAD

**Issue by anusanraj** [PowerShell/Win32-OpenSSH#1415]
On Windows 2012R2 server, OpenSSH log file(sshd.log) missing the date, instead it has an integer at the start of the line. See below a sample log collected today, 04.07.2019

5936 13:19:12 620 Accepted password for sappisftp from 10.200.178.116 port 20230 ssh2
6632 13:19:52 910 Accepted password for sappisftp from 10.200.180.78 port 39399 ssh2
18624 13:21:12 625 Accepted password for sappisftp from 10.200.178.116 port 56309 ssh2
20056 13:23:12 642 Accepted password for sappisftp from 10.200.178.116 port 49900 ssh2

Any idea how I can get the date... Appreciate your help, Thanks

**Comment by NoMoreFood** [comment]
Please try running the latest version provided on this repository.

**Comment by anusanraj** [comment]
> Please try running the latest version provided on this repository.

Thanks for your advice

**Comment by NoMoreFood** [comment]
@anusanraj Please close this issue if your problem was addressed satisfactorily.

**Comment by manojampalam** [comment]
Please reopen if needed.
