### ISSUE TITLE
"ssh -tt user@host command" won't run the command

### ISSUE THREAD

**Issue by vrokolos** [PowerShell/Win32-OpenSSH#1416]
The same thing works on a ubuntu host but on a windows host whenever I do that the screen gets cleared and I get thrown into the ssh shell as if no command was passed on the command line

"ssh user@host command" works fine but there's no input and no colors

**Comment by manojampalam** [comment]
Did this not work?
`ssh -t user@host command`

**Comment by vrokolos** [comment]
no. the command doesn't get executed

**Comment by maertendMSFT** [comment]
This is fixed in the latest release.
