### ISSUE TITLE
openssh can't keep the child processes running, once the parent process ends

### ISSUE THREAD

**Issue by sudhirraghuwanshi** [PowerShell/Win32-OpenSSH#1418]
Please answer the following

**"OpenSSH for Windows" version**
 8.0.0.0 beta
 
**Server OperatingSystem**
Windows Server 2012 Standard

**Client OperatingSystem**
SUSE Linux Enterprise Server 12

**What is failing**
command: 
ssh windows-host "perl.exe script123.pl"

I am calling multiple scripts inside script123.pl, which in turns creating a tree of child process under parent process. 
But the problem I am facing with OpenSSH is, when parent process gets completed, it terminates the session and kills the child processes along.

**Expected output**
The parent script(parent process) is calling other scripts in background, and it comes out without disturbing the child scripts (child processes). 
This is the expected behavior, it works with other SSH tools for windows, eg: SSH Tectia .

**Comment by manojampalam** [comment]
check this one - https://github.com/PowerShell/Win32-OpenSSH/issues/1032

**Comment by sudhirraghuwanshi** [comment]
@manojampalam  Thank you that helps.
Is it possible to have this built-in in OpenSSH package, because for me it is the matter of multiple servers where we run different script languages? 
The ssh-shellhost.exe mentioned in [#1032](https://github.com/PowerShell/Win32-OpenSSH/issues/1032) does not work with Openssh 8.0.0.0

Thanks in advance.
