### ISSUE TITLE
ssh to the server and  the domain account has been translated into domain\\user

### ISSUE THREAD

**Issue by ytreeca** [PowerShell/Win32-OpenSSH#1419]
Troubleshooting steps
I have tried ssh with and without RSA key and every time I get a broken pipe error. I am running OpenSSH V7.90-Beta.

Please answer the following

"OpenSSH for Windows" version
OpenSSH V7.9.0

Server OperatingSystem
Windows 2012 R2

Client OperatingSystem
Ubuntu 16.04

What is failing
Any ssh is failing with connection reset by peer

Expected output
Successful login with or without RSA key

Actual output
  When I try to ssh the windows server from the Unix server.  ssh -v user@domain@serverip.
I did run sshd.exe -d under system account on the windows server. The saw the error message after debug1: KEX done [preauth]
debug1: Can't match group at line 87 because user domain\\\user does not exist. The invalid user. 

 Why an extra slash was added into though?
I tried ssh -v domain\user@serverip, and the username was translated to domainuser. The slash was gone.  Has anyone experienced this problem? Any clue how to fix it?

Thanks in advance.

**Comment by mgkuhn** [comment]
You may want to read in `man bash` the section `QUOTING` to better understand what the backslash does in a POSIX shell and how to escape it, especially if any of the following lines surprise you:
```
$ echo \u
u
$ echo \\u
\u
$ echo '\u'
\u
$ echo "\\u"
\u
```
