### ISSUE TITLE
EXCEPTION: There was no endpoint listening at net.pipe://localhost

### ISSUE THREAD

**Issue by mattigot** [PowerShell/Win32-OpenSSH#1425]
**"OpenSSH for Windows" version**
7.7.2.1
 
**Server OperatingSystem**
 Windows 10 Enterprise LTSC 2019

**Client OperatingSystem**
indows 10 Enterprise

**What is failing**
Trying to run via ssh a application
This application has it's own service that communicates with net.pipe listener adapter service.

**Expected output**
Expected to be able to ssh into the machine and use the program

**Actual output**
I am able to ssh into the machine but Not able to run the program.

This is the error i get:
EXCEPTION: There was no endpoint listening at net.pipe://localhost/APSService that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
Type APS_Software /? for help.

Observations:
 * openssh works fine, since i am able to used different applications remotely via ssh (just not this one). 
* APSService service (the app service) is running with no issues.. (starts automatically)
* The application works locally with no issues. 
* net.pipe listener Adapter service is running (starts automatically)

**Comment by maertendMSFT** [comment]
Can you debug this application, it is not shown that this is an SSH issue.
