### ISSUE TITLE
Password auth does not work

### ISSUE THREAD

**Issue by andrfgs** [PowerShell/Win32-OpenSSH#1426]
When trying to contact a Windows computer with another Windows computer through ssh the password doesn't work. Both computers are registered in the same Microsoft account and therefore have the same username and password. 

The password that matches the microsoft account is refused on the client that attempts to contact the host. This is not a firewall problem either.

Whenever I try to input the correct microsoft account password the ssh client replies:

> Permission Denied, please try again

**Comment by maertendMSFT** [comment]
If you are still seeing this issue, please reopen.
Can you please provide the client side and server side logs?

**Comment by brunovieira97** [comment]
I have the same problem, can't even ssh to localhost on the server

**Comment by bagajjal** [comment]
Please follow the instructions below
https://github.com/PowerShell/Win32-OpenSSH/wiki/Setup-public-key-based-authentication-for-windows

**Comment by brunovieira97** [comment]
I did follow the instructions, and still was unable to set up OpenSSH Server on Windows 10. It asked for a password regardless of the key being provided.

I even removed all of SSH directories and the optional feature. After a reboot, reinstalling the server optional feature and setting all up, still no way for it to accept my client's public key.

**Comment by bagajjal** [comment]
@brunovieira97  - Please share ssh client logs (ssh -vvv user@ip) and ssh server logs with DEBUG3.
Note, we have an open issue that machine name, username should be different. This is not a recommended setting but some users tend to have same name for username and machine name.

By default, ssh server logging is ETW based. To change it to file based follow the below instructions,
1) Add below config to c:\programdata\ssh\sshd_config file
SyslogFacility LOCAL0
LogLevel DEBUG3
2) net stop sshd
3) net start sshd
4) ssh -vvv user@ip
