### ISSUE TITLE
ALT+Backspace sends ^? instead of ^H or ^[^? 

### ISSUE THREAD

**Issue by bao-qian** [PowerShell/Win32-OpenSSH#1428]
**"OpenSSH for Windows" version**
OpenSSH_for_Windows_8.0p1, LibreSSL 2.6.5

**Server OperatingSystem**
Ubuntu 18.04

**Client OperatingSystem**
Windows 10 Pro 1809 17763.615

**What is failing**

When trying to use ALT+backspace in the command prompt while being asked for input in Linux, it sends ^? instead of ^H or ^[^? and does not delete a word.

**Expected output**
When hitting ALT+backspace it should delete a word.
releated #1268 #1190 https://github.com/PowerShell/openssh-portable/pull/325

Here is the expected control character send from ssh bundled with git for windows.
git bundled ssh verion: openSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
```bash
ubuntu:~$ showkey -a
Press any keys - Ctrl-D will terminate this program
^[^?     27 0033 0x1b
        127 0177 0x7f
```
**Actual output**
A character is deleted instead of a whole word.
Here is the actual control character send from Win32-OpenSSH
```bash
ubuntu:~$ showkey -a

Press any keys - Ctrl-D will terminate this program

^?      127 0177 0x7f
```

**Comment by DHowett-MSFT** [comment]
This is also related to #1310.
