### ISSUE TITLE
Windows 1903 Upgrade Disables SSH Service

### ISSUE THREAD

**Issue by altano** [PowerShell/Win32-OpenSSH#1429]
**"OpenSSH for Windows" version**
ssh = 7.7.2.1
sshd = not installed 

**Client OperatingSystem**
Windows 10 1809 => 1903

**What is failing**
The Windows 1809=>1903 upgrade disables the `ssh-agent` service. The fix is simple, I just have to re-enable the service:
```
Get-Service | select -property name,starttype,status | Select-String ssh
Set-Service -Name ssh-agent -StartupType Automatic
Start-Service ssh-agent
Get-Service | select -property name,starttype,status | Select-String ssh
```

BUT I'm reporting this as a bug because:
1) Others might not be able to diagnose the issue as easily and this might be helpful and
2) I'm really frustrated with how hard it has been to maintain a semi-working OpenSSH setup on Windows using this package. It breaks on every Windows upgrade and the fix to #1263 made in January still isn't rolled out for some reason

**Comment by WSLUser** [comment]
> 7.7.2.1

Upgrade to 8.0. The problem is you changed versions with the upgrade. But the latest available won't be included with your OS until the next release. You're better off not enabling the feature but instead grabbing from the Github Release Page.  That still might not solve the disabling of the service issue but will eliminate a factor.

**Comment by anaisbetts** [comment]
This issue is super frustrating for people on Fast Ring, it's not just 1903, every Windows upgrade (and there are many of them!) re-disables the SSH Agent service. The effect of this bug is that every 2 weeks or so my SSH agent is broken and I'm prompted for passwords again.

**Comment by SteveL-MSFT** [comment]
@bagajjal / @manojampalam / @maertendMSFT we should consider this for our next release in Windows

**Comment by manojampalam** [comment]
@bingbing8, user overrides to service configuration is expected to be given preference during updates. Would you know why this is happening ?

**Comment by anaisbetts** [comment]
From a user perspective, I expected that I need to enable some Optional Feature that would ensure that ssh-agent is enabled, then it stays perma-enabled - or maybe like, it should be enabled automatically as part of enabling Developer Mode

**Comment by thinkjrs** [comment]
@altano thank you, worked perfectly for me 

> it should be enabled automatically as part of enabling Developer Mode

@anaisbetts @SteveL-MSFT I personally find this to be a fantastic default solution, when Developer Mode is on.

**Comment by bingbing8** [comment]
Looking into this issue. It needs to adjust some migration section of the manifest.

**Comment by bingbing8** [comment]
This migration will be available in next window release.

**Comment by maertendMSFT** [comment]
This next windows release will be available in the fall of 2020
