### ISSUE TITLE
 default port unable to change

### ISSUE THREAD

**Issue by troglobytor** [PowerShell/Win32-OpenSSH#1430]
Windows 8.1 
**"OpenSSH for Windows" version**
8.0

**What is failing**
I cannot seem to get it working on another port(52584). Testing with 
 scp  -P 52584  ~/advgui.txt mwindham@192.168.1.66:d:/scp/advgui.txt on 192.168.1.78.
Norton 360 firewall on or off.
**Expected output**
I edit C:\ProgramData\ssh\sshd_config, change startup parameters in services,
(always get it up on Port 22 when trying such, and scp works on port 22)
 and tried cmd with
C:\Program Files\OpenSSH>sshd.exe -p 52584  -d:
debug1: sshd version OpenSSH_for_Windows_8.0, LibreSSL 2.6.5 
debug1: rexec_argv[0]='sshd.exe'
debug1: rexec_argv[1]='-p'
debug1: rexec_argv[2]='52584'
debug1: rexec_argv[3]='-d'
debug1: Bind to port 52584 on ::.
Server listening on :: port 52584.
debug1: Bind to port 52584 on 0.0.0.0.
Server listening on 0.0.0.0 port 52584.
debug1: Server will not fork when running in debugging mode.
Connection from 192.168.1.78 port 49656 on 192.168.1.66 port 52584
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.0
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.
3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: sshd version OpenSSH_for_Windows_8.0, LibreSSL 2.6.5
debug1: get_passwd: LookupAccountName() failed: 1332.
debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp25
6,ssh-ed25519 [preauth]
debug1: SSH2_MSG_KEXINIT sent [preauth]
debug1: SSH2_MSG_KEXINIT received [preauth]
debug1: kex: algorithm: curve25519-sha256 [preauth]
debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit
> compression: none [preauth]
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit
> compression: none [preauth]
debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
debug1: rekey out after 134217728 blocks [preauth]
debug1: SSH2_MSG_NEWKEYS sent [preauth]
debug1: expecting SSH2_MSG_NEWKEYS [preauth]
debug1: SSH2_MSG_NEWKEYS received [preauth]
debug1: rekey in after 134217728 blocks [preauth]
debug1: KEX done [preauth]
debug1: userauth-request for user mwindham service ssh-connection method none [p
reauth]
debug1: attempt 0 failures 0 [preauth]
debug1: get_user_token - unable to generate user token for mwindham as i am not
running as system
ga_init, unable to resolve user mwindham
debug1: do_cleanup
debug1: Killing privsep child 1392
**Actual output**

**Comment by troglobytor** [comment]
If anyone knows easily where the port is set in the code, it would help me look/debug as I have built the latest for windows x64.(It took a bit to realize Expand-All was unavailable on W8.1)

**Comment by GjBrutello** [comment]
sshd_config_default or sshd_config in %programdata%

Port 52584 
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
-----------
or cmd start "" scp -P 52584 user@server

**Comment by troglobytor** [comment]
Does not work for me.

**Comment by GjBrutello** [comment]
don't forget add port to firewall rules and router port forwarding.

**Comment by troglobytor** [comment]
It would appear the port option in the Services gui is replaced by sshd_config, and maybe a firewalld port on reboot by runtime instead of permanent. Anyway, it works now with the firewalld port added permanently and a copied sshd_config from  a place I saved it. Anyway, it is fixed, working OK, please ignore.
