### ISSUE TITLE
Fixed FixHostFilePermissions.ps1 for administrators_authorized_keys

### ISSUE THREAD

**Issue by GjBrutello** [PowerShell/Win32-OpenSSH#1431]
**"OpenSSH for Windows" version**
Any
---------------------------------------
Who does not want to manually fix permissions every time after editing the file "administrators_authorized_keys" add this code to the file "FixHostFilePermissions.ps1". For example, between lines 43 - 52.
---------------------------------------
```
#check administrators_authorized_keys
$administratorsauthorizedkeysPath = join-path $env:ProgramData\ssh "administrators_authorized_keys"
if(Test-Path $administratorsauthorizedkeysPath -PathType Leaf)
{
    Repair-SshdConfigPermission -FilePath $administratorsauthorizedkeysPath @psBoundParameters
}
else
{
    Write-host "$administratorsauthorizedkeysPath does not exist"  -ForegroundColor Yellow
}

```

**Comment by cpesch** [comment]
I've stumbled across the same problem here. Please consider fixing this.
