### ISSUE TITLE
SSH can't connect with ssh-agent, but can connect when just using the `-i` option?

### ISSUE THREAD

**Issue by flatline-studios** [PowerShell/Win32-OpenSSH#1433]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 ```
((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
7.6.0.1
```

```
λ ssh -V
OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
``` 
**Server OperatingSystem**
Ubuntu 19.04

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
```
C:\Windows\System32\OpenSSH
λ ssh-add C:\Users\CLIENT-USERNAME\.ssh\tester
Enter passphrase for C:\Users\CLIENT-USERNAME\.ssh\tester:
Identity added: C:\Users\CLIENT-USERNAME\.ssh\tester (C:\Users\CLIENT-USERNAME\.ssh\tester)

C:\Windows\System32\OpenSSH
λ ssh-add -l
4096 SHA256:s3J+SE1DSy8eHmnXIY1U4F9qNDOoU/hC/FU/Tzt7oBw C:\Users\CLIENT-USERNAME\.ssh\tester (RSA)

C:\Windows\System32\OpenSSH
λ ssh SERVER-HOSTNAME -i C:\Users\CLIENT-USERNAME\.ssh\tester
REMOTE-USERNAME@SERVER-HOSTNAME: Permission denied (publickey).

C:\Windows\System32\OpenSSH
λ ssh-add -D
All identities removed.

C:\Windows\System32\OpenSSH
λ ssh-add -l
The agent has no identities.

C:\Windows\System32\OpenSSH
λ ssh SERVER-HOSTNAME -i C:\Users\CLIENT-USERNAME\.ssh\tester
Enter passphrase for key 'C:\Users\CLIENT-USERNAME\.ssh\tester':
Last login: Fri Aug 16 20:17:04 2019 from 1.2.3.4
REMOTE-USERNAME@SERVER-HOSTNAME:~$
```

**Expected output**
The line `ssh SERVER-HOSTNAME -i C:\Users\CLIENT-USERNAME\.ssh\tester` should connect just fine.

**Actual output**
See above.

**Comment by flatline-studios** [comment]
Adding to this, after some more research, I've found:

[https://unix.stackexchange.com/q/415216/244642](https://unix.stackexchange.com/q/415216/244642)
which leads to...
[https://bugzilla.mindrot.org/show_bug.cgi?id=2799](https://bugzilla.mindrot.org/show_bug.cgi?id=2799)

If that helps at all?

**Comment by GjBrutello** [comment]
cmd:.\OpenSSH
```
sc start ssh-agent
ssh-add C:\Users\CLIENT-USERNAME\.ssh\tester
```

**Comment by hjoelr** [comment]
@GjBrutello I'm guessing he already had the agent running because he could run successfully run `ssh-add <keyfile>` and `ssh-add -l`.

**Comment by bersbersbers** [comment]
Sounds a bit like #1263 to me.

**Comment by maertendMSFT** [comment]
This issue is fixed in the latest release.
