### ISSUE TITLE
Window 2008 Cannot Connect putty empty

### ISSUE THREAD

**Issue by domeneo** [PowerShell/Win32-OpenSSH#1435]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
Version 1,7.7.1,8 32bit
 
**Server OperatingSystem**
WIndow server 2018

**Client OperatingSystem**

**What is failing**
I trying putty localhost it can not connect.Putty is empty screen.

![2019-08-21_3-29-16](https://user-images.githubusercontent.com/24912028/63382514-116f6f00-c3c5-11e9-9159-cf7d1cc3f081.png)
![2019-08-21_3-22-10](https://user-images.githubusercontent.com/24912028/63382545-23e9a880-c3c5-11e9-953a-2c8e4433c225.png)
![2019-08-21_3-39-38](https://user-images.githubusercontent.com/24912028/63382675-5dbaaf00-c3c5-11e9-8058-f8d6582edfa7.png)

 but netstat port 22 is establish .
**Expected output**

**Actual output**

**Comment by maertendMSFT** [comment]
We no longer support Windows 2008.
i presume you server version, "Server 2018", is a typo
