### ISSUE TITLE
How can I stay connection after ssh followed by command

### ISSUE THREAD

**Issue by goldflower** [PowerShell/Win32-OpenSSH#1437]
**"OpenSSH for Windows" version**
OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
 
**Server OperatingSystem**
windows10 professional

**Client OperatingSystem**
Ubuntu18.04.3 LTS

**What is failing**
I want to connect to remote server and then use "cd" command to target work directory.

But there seems like no such option for staying connection after commands like below:

ssh abc@12.34.56.78 "cd /target/directory"

**Expected output**
Just like I typed these commands line by line and don't disconnect automatically.

**Actual output**
Only return the result of stdout from remote(if any) then disconnect.

I checked the wiki page but didn't find out such use case. : (

Thank you for any advance.

**Comment by mgkuhn** [comment]
That sounds more like a feature request for OpenSSH itself, rather than for the Windows port of it (which is what these issues are for). I'm not aware of any such ssh option on other operating systems.

You can try to work around it by sending a cd/pushd command followed by starting another shell, as in
```
$ ssh linux-server -t "cd /tmp && bash"
```

**Comment by mgkuhn** [comment]
Or to a Windows server from cmd.exe
```
C:\> ssh windows-server -t "pushd \Users&& cmd"
```
or from bash
```
$ ssh windows-server 'pushd \Users&& cmd'
```

**Comment by maertendMSFT** [comment]
You could use an interactive session to perform you actions.  Another option is to put everything in a script on the server and execute the script.
