### ISSUE TITLE
Update Windows SDK to latest if compatible

### ISSUE THREAD

**Issue by WSLUser** [PowerShell/Win32-OpenSSH#1439]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 8.0
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
**What is failing**
I tried to build the solution but VS2019 doesn't offer the Windows 8.1 SDK (nor should it). But I do have the latest Windows 10 SDK installed.
**Expected output**
I expect VS2019 to work seamlessly. The Windows 10 SDK notes state that win32 apps work for Windows 7 SP1 and newer. Therefore, unless there's some serious breakage somehow (even though if you retarget in VS, it works per https://stackoverflow.com/questions/43704734/how-to-fix-the-error-windows-sdk-version-8-1-was-not-found) we should use the newest.
**Actual output**
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
2>Done building project "libssh.vcxproj" -- FAILED.`

>

**Comment by WSLUser** [comment]
Made some changes to my branch under the UpdateWindowsSDK branch. I'm knocking out VS2019 support as well as it seems it's needed as the 8.1 SDK is not available in VS Community 2019 .

**Comment by maertendMSFT** [comment]
Can you try this in VS 2019?  The latest should work
