### ISSUE TITLE
openssh client won't connect (cygwin or linux openssh client works fine on my machine though)

### ISSUE THREAD

**Issue by ericcurtin** [PowerShell/Win32-OpenSSH#1441]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

Just try to ssh (using -vvv for debug info for you guys) to a RHEL7 system. This is the second laptop I've tried this ssh client on and failed to get it to work. Completely different laptop in a completely different network.

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command ssh).Source).VersionInfo.FileVersion)`

7.6.0.0 (windows ssh client)
 
**Server OperatingSystem**
RHEL7

**Client OperatingSystem**
Windows 10 Enterprise

**What is failing**
ssh client doesn't connect

**Expected output**
I get a bash prompt

**Actual output**
OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
debug1: Reading configuration data C:\\Users\\curtie2/.ssh/config
debug1: C:\\Users\\curtie2/.ssh/config line 1: Applying options for *
debug3: Failed to open file:C:\\ProgramData\\ssh/ssh_config error:2
debug3: w32_getpeername ERROR: not sock :3
debug3: w32_getpeername ERROR: not sock :3
debug1: getpeername failed: Not a socket
debug3: w32_getsockname ERROR: not sock :3
debug3: w32_getsockname ERROR: not sock :3
getsockname failed: Not a socket
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: ssh_packet_send_mux: type 90
debug1: Entering interactive session.
debug1: pledge: id
debug1: console supports the ansi parsing
debug2: client_check_window_change: changed

**Comment by maertendMSFT** [comment]
Are you using any 3rd party software that would replace or overlap with Windows sockets?

**Comment by ericcurtin** [comment]
Most likely no, but to be honest I can't remember 100% what machine this was since it was September 2019. I just use Cygwin or Linux version now, someday I might retry the Windows version.

**Comment by bagajjal** [comment]
Closing this for now.

**Comment by sh0rch** [comment]
> Closing this for now.

How did you resolve it?
