### ISSUE TITLE
Add Visual Studio 2019 tool chain to OpenSSHBuildHelper.psm1 and project files

### ISSUE THREAD

**Issue by WSLUser** [PowerShell/Win32-OpenSSH#1443]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 8.0
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
N/A
**Client OperatingSystem**
10
**What is failing**
Fails to build
**Expected output**
Build succeeds

**Comment by WSLUser** [comment]
Made some changes to my branch under the UpdateWindowsSDK branch. I'm knocking both out at once since it seems needed as the 8.1 SDK is not available in VS Community 2019 .

**Comment by maertendMSFT** [comment]
8.1 SDK is required for OpenSSH to work on Win 7.

**Comment by WSLUser** [comment]
I suggest dropping Win7 support instead then.
