### ISSUE TITLE
Persistent "ALL APPLICATION PACKAGES" security entry makes OpenSSH fail to consider .ssh

### ISSUE THREAD

**Issue by ShadowJonathan** [PowerShell/Win32-OpenSSH#1445]
**"OpenSSH for Windows" version**
7.7.2.1

**Client OperatingSystem**
Windows 10 Pro (`1903` from winver)

**What is failing**
`~/.ssh/config`  default permission check.

**Expected output**
No output, normal operation.

**Actual output**
`Bad owner or permissions on C:\\Users\\<user>/.ssh/config`

*Explanation:*
I've already tried `Repair-UserSshConfigPermission ~/.ssh/config`, this gave me repeatedly
```
'APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES' should not have access to '~/.ssh/config'..
```
`APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES` is a entry in any security tab under `C:\Users\<user>\`, it re-adds itself when removed.

According to microsoft, [this is by design](https://social.technet.microsoft.com/Forums/azure/en-US/e9b94c25-631b-4923-b318-b5a29704437b/file-and-folder-permission-problem-in-windows-10-v1809?forum=win10itprosecurity).

The issue is is that this makes OpenSSH fail fatally when checking `.ssh/*`, the security entry cant be removed, even when inheritance is toggled off.

**Comment by NoMoreFood** [comment]
I do not see this entry on my C:\Users or C:\Users\<userid> folder.  Do others?

**Comment by ShadowJonathan** [comment]
@NoMoreFood what windows version?

**Comment by manojampalam** [comment]
Need to follow up. Does deleting a folder and creating a new one solve your problem, i.e get rid of that ACL entry ?

**Comment by ShadowJonathan** [comment]
No, nor does removing it from the "top" folder where this occurs (user folder), because after a lengthy removal process, windows will just show that entry in every folder underneath the user one anyways.

Like I said, it's persistent, and it's by design, and it's causing openssh to ignore the folder

**Comment by NoMoreFood** [comment]
@ShadowJonathan I don't see this on my Windows 10 Enterprise or Windows 10 Professional installation.  It may be "by design" on certain directories, but I don't think it's the out-of-the-box behavior on Windows 10 for C:\Users.  Are you working in a domain environment?  Is it possible that there is a GPO pushing those permissions down periodically?

**Comment by ShadowJonathan** [comment]
I'm not in a domain environment, but i *am* using a Microsoft account.

**Comment by mashirozx** [comment]
The same issue on Windows 10 Home.

**Comment by maertendMSFT** [comment]
Won't fix, as this appears to be a localized issue.
