### ISSUE TITLE
"Failed publickey" VS "authorized_keys:1: matching key found"

### ISSUE THREAD

**Issue by RonanSaluden** [PowerShell/Win32-OpenSSH#1446]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 (LTSC1809)

**Client OperatingSystem**
Windows 10 (LTSC1809)

**What is failing**
When the server tries to match the sent key and the user's public key, it fails. However, when it compares it with the ones in the "authorized_keys" file, it finds a matching key. This "authorized_keys" contains one key only: the user's public key (see the "actual output").

**Expected output**
Accepted publickey for DS865...

**Actual output**
Failed publickey for DS865 from 127.0.0.1 port 56253 ssh2: RSA SHA256:R9Ww8HntxkgsboUkQvrBFte4ZAT4YrKahS90jHBqRvw
debug1: userauth-request for user DS865 service ssh-connection method publickey [preauth]
debug1: attempt 2 failures 1 [preauth]
debug1: userauth_pubkey: test pkalg rsa-sha2-512 pkblob RSA SHA256:2ex8rKVCS3XwvL8LV3I/e3btf2TMfnAb99pXyuBi06A [preauth]
debug1: trying public key file C:\\Users\\DS865\\.ssh/authorized_keys
debug1: C:\\Users\\DS865\\.ssh/authorized_keys:1: matching key found: RSA SHA256:2ex8rKVCS3XwvL8LV3I/e3btf2TMfnAb99pXyuBi06A

[sshClient_logs.txt](https://github.com/PowerShell/Win32-OpenSSH/files/3596553/sshClient_logs.txt)
[SSHD_logs.txt](https://github.com/PowerShell/Win32-OpenSSH/files/3596554/SSHD_logs.txt)

**Comment by manojampalam** [comment]
Don't find any issue. It looks like your client is sending 2 keys, first key gets rejected, second one gets accepted. Thumbprints for the 2 keys are clearly different. Check if you have ssh-agent running on client that might be feeding in an unwanted key.

**Comment by RonanSaluden** [comment]
Ok, thank you for you quick answer. I will look into it.

**Comment by RonanSaluden** [comment]
I still haven't found out why it seems that the client is sending 2 different keys. However, I've found that when I remove the key converted with Puttygen (using "Conversions"\"Export OpenSSH key") and replace it with a key generated with ssh-keygen.exe with the same passphrase, the SSH connection then works. Have you heard of such a wrong compatibility with this Puttygen tool?
