### ISSUE TITLE
Won't read USER/.ssh/authorized_keys if permissions include sshd service user, BUT Permission Denied error if permissions don't include the sshd service user

### ISSUE THREAD

**Issue by Charlweed** [PowerShell/Win32-OpenSSH#1450]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps
Assume the local system is LOCALWIN

1) Append user key to USER/.ssh/authorized_keys
2) Open command console as user "LOCALWIN\sshd", which is the user/owner for the sshd service.
In that console, start sshd -dddd, so you can see the debug logs in real time.
3) Set the permissions on USER/.ssh/authorized_keys to include read access for "LOCALWIN\sshd"
4) From a remote system, connect via ssh, attempting to use the key appended in step 1
5) Note that SSHD refuses to use the key, because the permissions are too open, logging that you need to remove access for the SID of the "LOCALWIN\sshd" user.
6) Remove read permissions for the "LOCALWIN\sshd" user, and repeat step "4"
7) Now note that the sshd service cannot access the  USER/.ssh/authorized_keys file, because permission is denied.

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH
No

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 Pro

**Client OperatingSystem**
Linux, MacOS

**What is failing**
This version of sshd is installed with the service running as a local user account, but the permissions checks are too strict to allow that user to read the files it needs to.
The result is that users cannot use their keys to connect, they must always use passwords.

**Expected output**
Last Login message

**Actual output**
Users's Password.

**Comment by affinityv** [comment]
If the user is in the administrators group, then the %programdata%\ssh\administrators_authorized_keys file is used **instead** of the user's own one.

You need to make sure that the **adminstrators_authorized_keys** file doesn't inherit rights for ordinary users to read it.  The administrators group works with full rights and ownership of the file, no other user or process needs to be given any access rights (not even system).

~~I think this should be a bug, the user's own authorized_keys should be used first if they have one, even if they belong to the administrators group.  If the user has no authorized key in their own file, then I think it should be fine to fall back to the administrators_authorized_keys file to look for further keys.~~

I've renamed the user's authorized_keys file to not_used--authorized_keys ... and I can still login with any of  the keys as stored in the administrators_authorized_keys file.

**Comment by affinityv** [comment]
This from sshd_config is the reason why the special authorized keys file is used to override the user's own file.

```
Match Group administrators
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
```

**Comment by maertendMSFT** [comment]
Administrator keys are located under `AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys`
