### ISSUE TITLE
Make OpenSSH build in VS2019

### ISSUE THREAD

**Issue by Charlweed** [PowerShell/Win32-OpenSSH#1451]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps
[The build instructions on the wiki](https://github.com/PowerShell/Win32-OpenSSH/wiki/Building-OpenSSH-for-Windows-(using-LibreSSL-crypto)) are out of date. The Start-OpenSSHBuild function fails immediately.
Note that VisualStudio 2015 is not readily available. Visual Studio is now "Visual Studio 2019"

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
commit 675e761d750e38a2951b01579f0670bc00e21fd3 (HEAD -> latestw_all
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**

**What is failing**
The command to VisualStudio 2019 fails.

**Expected output**
Build logs.

**Actual output**
Starting Open SSH build; Build Log: C:\Users\chymes\projects\3rd_party\openssh-portable\contrib\win32\openssh\OpenSSHDebugx64.log.                      Write-BuildMsg : Build failed for OpenSSH.
ExitCode: .                                                                                                                                             OpenSSHBuildHelper.psm1:627 char:9                                         +         Write-BuildMsg -AsError -ErrorAction Stop -Message "Build fai ...                                                                             +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                 + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException                                                                          + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-BuildMsg

**Comment by Charlweed** [comment]
Also, choco fails to install vcbuildtools when VS 2015 is installed
[chocolatey.log](https://github.com/PowerShell/Win32-OpenSSH/files/3678071/chocolatey.log)
The '/S' option in the choco installation package hides the display that "visualcppbuildtools_full.exe" aborts when VisualStudio 15 is already installed.

**Comment by manojampalam** [comment]
ref https://github.com/PowerShell/Win32-OpenSSH/issues/1439

**Comment by maertendMSFT** [comment]
Can you try this in VS 2019? The latest should work.  Please ensure win 8.1 SDK is installed.
