### ISSUE TITLE
Installation fails with -File parameter does not exist.

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#1453]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`

    7.7.2.3
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

    Windows 10 Home

**Client OperatingSystem**

Microsoft Windows [Version 10.0.18980.1]

**What is failing**
Step 4, of
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH
fails.

**Expected output**
Successful completion of the command 
    powershell.exe -ExecutionPolicy Bypass -File install-sshd.ps1

**Actual output**
    The argument 'install-sshd.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.

**Comment by WSLUser** [comment]
I don't get this issue. 2 things that may help: 1) Change to the 8.0 binaries. 2) Use Chocolatey instead. 

I also copied and pasted directly from the instructions and verified extra spaces weren't introduced. 

A possible reason for the failure: 

> Microsoft Windows [Version 10.0.18980.1]

This is an Insiders build. It's possible something changed that broke this. Are you using Windows Powershell or PS Core?

**Comment by manojampalam** [comment]
Did you try specifying the complete path for install-sshd.ps1 ?

**Comment by OnlineGBC** [comment]
i have the same problem installing it on a Windows 7 machine.  (Obviously, it is not needed on Windows 10).  The file itself is not found in the zip extract so there is no way to select a path:

Here is the Windows 7 version:
PS C:\Program Files\OpenSSH> [System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
6      1      7601   65536

The argument 'install-sshd.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as a argument to the -File parameter.

**Comment by maertendMSFT** [comment]
No repro
