### ISSUE TITLE
Non elevated powershell can't interact with key generated in elevated prompt

### ISSUE THREAD

**Issue by melink14** [PowerShell/Win32-OpenSSH#1454]
I recently set up OpenSSH on windows with ssh-agent to handle public key authentication when using SSH (mainly for connecting to my linux VPS and github).

As part of that, after seting up the services in an elevated prompt I also ran `ssh-keygen` and `ssh-add` as part of the general setup.

It worked when I tested it from that same prompt.

Later, I tried to ssh from a non elevated prompt and found that `ssh` would not use the key from my agent (though would use the file in my .ssh directory if passed via `-i` or the `Identity` line in ssh_config).

To debug, I ran various commands to check on ssh-agent status:

> `ssh-add -l`: error fetching identities: invalid format
> `ssh-add <path to key>`: Could not add identity "id_rsa_desk": invalid format
> `ssh-add -D`: Failed to remove all identities.

These all work as expected from elevated prompt, but as far as I know a generated key shouldn't have any user metadata in it. I checked the permissions in my key file and my user account has full permissions.

Is there something about generated a key with admin powershell that makes it not work from non elevated powershell ssh-agent?

Please answer the following

**"OpenSSH for Windows" version**
8.0.0.0
 
**Server OperatingSystem**
Ubuntu 16.04

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
`ssh-add -l`, `ssh-add <existing-key>`, `ssh <server>`

**Expected output**
1) should list keys.
2) Should add key to agent
3) Should connect to server using agent

**Actual output**
> `ssh-add -l`: error fetching identities: invalid format
> `ssh-add <path to key>`: Could not add identity "id_rsa_desk": invalid format
> `ssh-add -D`: Failed to remove all identities.

**Comment by melink14** [comment]
Since `ssh-add -l` fails even with no keys in my agent, maybe the cause is how the ssh-agent service is running?

It's running under SYSTEM, and Admin accounts have 'Full Control' while Users have Read & execute and Read.

**Comment by WSLUser** [comment]
> ssh-add <path to key>: Could not add identity "id_rsa_desk": invalid format

It's looking for `id_rsa`. I created a private/public key pair on my fedora box and scped it to Windows. Adding it worked just fine. where is "_desk" coming from? 

It has nothing to do with the service. As long as it's set to automatic and as local system, there should be no issues there if it's running.

**Comment by melink14** [comment]
> > ssh-add : Could not add identity "id_rsa_desk": invalid format
> 
> It's looking for `id_rsa`. I created a private/public key pair on my fedora box and scped it to Windows. Adding it worked just fine. where is "_desk" coming from?

There may be some confusion here, so let me explain.

1) `ssh-add` takes a path to a key and I'm providing a path to a key named id_rsa_desk. I use different names for different purposes. Clearly, the name of the key doens't matter if it works when I run powershell as an adminstrator. The key problem here is why ssh-agent works differently for adminstrator shell vs user shell.

2) You mentioned fedora, but to clarify, this is all a windows local problem. I generated the key on windows and then tried to add the key via windows. The problem may be that I generated the key from admin shell and thus for some reason it doesn't work from non-admin shell, though I don't know why that would be the case.

Especially, as I mentioned even if I remove all keys from ssh-agent, ssh-add still fails from non admin powershell.

> 
> It has nothing to do with the service. As long as it's set to automatic and as local system, there should be no issues there if it's running.

I agree, just adding extra information in case someone knows more than I do. Again, it works perfectly when running powershell as an administrator.

**Comment by manojampalam** [comment]
Can you 
- double check you using the same version of ssh utils in both the elevated and non elevated case?
- check ACLs on the key files (`icacls filename`)
- check if you talking to the same ssh-agent in both the cases (see if SSH_AUTH_SOCK if explicity set)?

**Comment by melink14** [comment]
I went to debug this again and now it works. not sure if a recent restart helped or an update or what (sorry to future people who come across this problem.)
