### ISSUE TITLE
SSH_AUTH_SOCK and SSH_AGENT_PID env vars not set from ssh-agent

### ISSUE THREAD

**Issue by jacobrillema** [PowerShell/Win32-OpenSSH#1455]
**"OpenSSH for Windows" version**
8.0.0.0 
 
**Client OperatingSystem**
Windows 10 Pro  

**What is failing*-
I am trying to connect GitKraken to my local ssh-agent.

**Expected output**
I can confirm my ssh-agent windows service is running with valid ssh keys loaded. 

**Actual output**

**Comment by manojampalam** [comment]
ssh-agent for Windows works on Named pipes. Does GitKraken have its own ssh client stack (or does it invoke openssh client) ? If former, it's most likely not compatible with Windows version of ssh-agent.
