### ISSUE TITLE
[Audits] Logging Logon attempts in Windows Event Logs

### ISSUE THREAD

**Issue by secdude** [PowerShell/Win32-OpenSSH#146]
Hi,
Question is: Is logging of failed logon attemps logged to windows eventlogs? So far I only found my successful logins but not my unsuccessful attempts. Would be beneficial for existing log management  integration.

Thanks & regards
secdude

**Comment by manojampalam** [comment]
Agree. Will consider this as part of security enhancements.

**Comment by maertendMSFT** [comment]
All sshd events are logged into the Windows event log.
https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities
