### ISSUE TITLE
Easiest way to contribute to Wiki?

### ISSUE THREAD

**Issue by billdinger** [PowerShell/Win32-OpenSSH#1460]
This is a question more than anything - the documentation around getting certificate based auth to work is out of date and could use some love. Spent a couple hours troubleshooting only to discover that the cert file for administrators required UTF-8 encoding for example among other tricks and tips that seem to only be contained inside the comments and issues here.

I want to contribute to update the wiki to encapuslate some of the things I found manually through perusing the issues here. Woudl it be acceptable to fork the repo, update wiki locally then put a PR in linking back to update wiki for maintenance? Or how would you prefer that get done in general?

Thanks!

**Comment by NoMoreFood** [comment]
I'm not the guy that'll end up merging it, but I would suspect that any robust contributions would be accepted.  And doing it in the way you described would be the way to go.

Also, I presume you mean public key authentication?

**Comment by billdinger** [comment]
Thanks @NoMoreFood , https://github.com/PowerShell/Win32-OpenSSH/pull/1465 we'll see if that works i'll go ahead and close this issue unless somethign changes =)
