### ISSUE TITLE
Keep long-running WSL processes alive after SSH disconnect

### ISSUE THREAD

**Issue by sskeirik** [PowerShell/Win32-OpenSSH#1464]
**"OpenSSH for Windows" version**
7.7.2.2
 
**Server OperatingSystem**
Win 10 Pro

**Client OperatingSystem**
Win 10 Pro

**What is failing**
I connect to server and am dropped into CMD shell. 
I run `wsl`.
Inside WSL, I run `tmux`.
I start a long-running process inside the tmux session.
I exit tmux.
I disconnect from the SSH session.
When I reconnect, the `tmux` process and all of its children are gone.

**Expected output**
The tmux process and its children should stay alive regardless if I am connected to server by SSH session.

**Actual output**
The tmux process dies sometime after disconnecting from the SSH session.

Related Issues (but these issues do not mention WSL processes):
#1418 #1032

**Comment by WSLUser** [comment]
Use `screen`. WSL should keep sessions open assuming there's a WSL window still open on the remote machine (or even local). Once all sessions are closed, it's by design in WSL to kill processes. Only configured background tasks should remain running if they are meant to continuously run.

**Comment by lfourquaux** [comment]
> Use `screen`. WSL should keep sessions open assuming there's a WSL window still open on the remote machine (or even local). Once all sessions are closed, it's by design in WSL to kill processes. Only configured background tasks should remain running if they are meant to continuously run.

`screen` and `tmux` do roughly the same thing, and @sskeirik is using `tmux`.  WSL is here mostly as a use case.  The issue is that all descendant processes are killed when the ssh connection closes, and preventing this is possible but far from easy.
