### ISSUE TITLE
Not able to work with Interactive commands without TTY

### ISSUE THREAD

**Issue by sureshkotapydev** [PowerShell/Win32-OpenSSH#1466]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `7.7.0.0`
 
**Server OperatingSystem**
 `Windows Server 2016 Standard Evaluation`

**Client OperatingSystem**
CentOS Linux release 7.6.1810 (Core)

**What is failing**
Interactive commands without TTY hangs indefinitely

**Expected output**
`ssh -T -vvv user@host "interactive-tool.exe"` should provide a interactive shell opened with "interactive-tool.exe" without any hang.

**Actual output**
`debug1: Sending command: interactive.exe
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0`

Waits here indefinitely

**Comment by maertendMSFT** [comment]
you need to provide the full path the the interactive-tool.exe
Please try the latest version
