### ISSUE TITLE
OpenSSH using wrong file separator in win10

### ISSUE THREAD

**Issue by coolshan008** [PowerShell/Win32-OpenSSH#1468]
I'm using OpenSSH in windows10 1903:
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

When I tried to log in to a linux server with an SSH private key,
> ssh %Username%@114.212.83.124

I got the following outputs:

>Could not create directory 'C:\\Users\\%MyAccountName%/.ssh'.
#@#%(#$# (unrelated outputs)
Failed to add the host to the list of known hosts (C:\\Users\\%MyAccountName%/.ssh/known_hosts).

The config directory is C:\\Users\\%MyAccountName%\\.ssh ,
where %MyAccountName% is a Chinese string.
I think Openssh is using the unix-style file separator **/** , which makes it fail to write files.
The ssh authorization failed and I have to enter the password frequently : (

**Comment by bagajjal** [comment]
No, it's just a display issue.
Internally we handle both windows and unix-style file paths.

It looks like ssh.exe under the current user context doesn't have permissions to create C:\Users\%MyAccountName%/.ssh

**Comment by firepond** [comment]
Meeting the same problem. And i'm wandering if it support Chinese characters and other utf characters.

**Comment by maertendMSFT** [comment]
Yes, both are supported.  Please try the latest version, if you still have issues then please open a new issue.

**Comment by ArthurChan2018** [comment]
@maertendMSFT @firepond 
Which version are you using?

I'm using the latest version(v9.5.0.0p1-Beta) but got the same error:
debug1: rekey in after 134217728 blocks
debug3: ssh_get_authentication_socket_path: path '\\\\.\\pipe\\openssh-ssh-agent'
debug3: unable to connect to pipe \\\\.\\pipe\\openssh-ssh-agent, error: 2
debug1: get_agent_identities: ssh_get_authentication_socket: No such file or directory
debug1: Will attempt key: C:\\Users\\\345\276\267\345\215\216/.ssh/id_rsa
debug1: Will attempt key: C:\\Users\\\345\276\267\345\215\216/.ssh/id_ecdsa
debug1: Will attempt key: C:\\Users\\\345\276\267\345\215\216/.ssh/id_ecdsa_sk
debug1: Will attempt key: C:\\Users\\\345\276\267\345\215\216/.ssh/id_ed25519
debug1: Will attempt key: C:\\Users\\\345\276\267\345\215\216/.ssh/id_ed25519_sk
debug1: Will attempt key: C:\\Users\\\345\276\267\345\215\216/.ssh/id_xmss
debug1: Will attempt key: C:\\Users\\\345\276\267\345\215\216/.ssh/id_dsa
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 7

**Comment by maertendMSFT** [comment]
@ArthurChan2018, can you open a new issue for this?  From the logging we dont see any character issues.  Please provide your server logs in the new issue.
