### ISSUE TITLE
file name contains non-english characters can't be handled in sftp client

### ISSUE THREAD

**Issue by imaxhung** [PowerShell/Win32-OpenSSH#1469]
for example, fail to display, transfer or create file named this way.
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.繁体&英文.ass success
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.繁体&英文.srt success
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.繁体.ass success
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.繁体.srt success
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.简体&英文.ass fail
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.简体&英文.srt fail
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.简体.ass fail
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.简体.srt fail
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.英文.srt success
I turned to use built-in openssh server, it also happen.
and I didn't find any rules why this happen.
Did I miss something？Testing other winPC had the same problem.
I had searched for a few days, found almost no relevant information about this.
by the way, FTP server is OK.
Can someone explain this? Thanks

**Comment by NoMoreFood** [comment]
What version are you running?  Pretty sure this was addressed in more recent versions.

**Comment by imaxhung** [comment]
Win10 Pro 1903 v18362
Win32-OpenSSH v8.0.0.0p1-Beta @NoMoreFood

**Comment by NoMoreFood** [comment]
So I was able to reproduce this issue with those specific characters, but only when the console font I had selected did not contain those glyphs.  Can you try changing your console font to see if they show up using any other fonts?

**Comment by imaxhung** [comment]
In a cmd dialog
-----------------------------
nothing changed, character set 936 (ANSI/OEM - 简体中文 GBK)
C:\Users\NAS\Downloads\Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG>dir /a
 驱动器 C 中的卷没有标签。
 卷的序列号是 2E6C-7F55

 C:\Users\NAS\Downloads\Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG 的目录

2019-09-26  16:38    <DIR>          .
2019-09-26  16:38    <DIR>          ..
2019-09-26  16:38           101,026 Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.简体&英文.ass
2019-09-26  16:38            53,964 Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.简体&英文.srt
2019-09-26  16:38            55,343 Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.简体.ass
2019-09-26  16:38            38,634 Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.简体.srt
2019-09-26  16:38           101,024 Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.繁体&英文.ass
2019-09-26  16:38            53,964 Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.繁体&英文.srt
2019-09-26  16:38            55,343 Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.繁体.ass
2019-09-26  16:38            38,634 Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.繁体.srt
2019-09-26  16:38            37,790 Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.英文.srt
               9 个文件        535,722 字节
               2 个目录 136,549,638,144 可用字节
------------normal-----------------
sftp> ls
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.绻佷綋&鑻辨枃.ass                                                         
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.绻佷綋&鑻辨枃.srt                                                         
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.绻佷綋.ass                                                                
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.绻佷綋.srt                                                                
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.鑻辨枃.srt                                                                
-----------------missing 4 files and Garbled character---------------
then run chcp 65001, turn character set to 65001 (UTF-8)
sftp> ls
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.繁体&英文.ass
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.繁体&英文.srt
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.繁体.ass
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.繁体.srt
Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.英文.srt
-----------------still missing 4 files and Garbled character back normal---------------

Am I right in this test? @NoMoreFood

**Comment by NoMoreFood** [comment]
Okay, let me look into the four missing files first.  That's definitely weird.

**Comment by NoMoreFood** [comment]
Weird.  I cannot reproduce the missing files behavior.  It's possible one of the special characters is being interpreted as some sort of control character and/or not outputting a new line.  Can you zero out the files and 7-zip them up?  I want to make sure GitHub is not garbling the characters itself.  

Also, can you try WinSCP and see if all files appear?

**Comment by imaxhung** [comment]
I use WinSCP very often. The result is the same.
Yes, very very weird. It seems related to how do filename organize those characters, not those characters itself. Especially contains some character like 体
example like Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.简体&英文.ass
just delete 简, stll missing
just delete 简体 or 体, it will appear.
example for creating a flie in a sftp client
named 简, success
named 简体, show garbled character 简�
named 简体简, success
named 简体简体, show garbled character 简体简�
... the last 体 will always garbled
example like Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.繁体&英文.ass
If I want to rename it, just rearrange four chinese chracters alone, most of the cases are failed.

sorry I don't get it for "zero out the files and 7-zip them up"
I just upload the source file I downloaded.
[[zmk.pw]Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.zip](https://github.com/PowerShell/Win32-OpenSSH/files/3670714/zmk.pw.Crawl.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.zip)

**Comment by imaxhung** [comment]
@NoMoreFood

**Comment by NoMoreFood** [comment]
@imaxhung I'll try to take a look later today or tomorrow.  What you provided is fine.  I tend to use 7-zip for my archiving and was worried that the files may have content in them that you may not want to send or I may not want to have (based on the name).

**Comment by imaxhung** [comment]
@NoMoreFood OK, take you time. All content is in the zip file. It's just some subtitle files. 
Thank you for your response.

**Comment by NoMoreFood** [comment]
Do you see something different from this when using WinSCP?  This is WinSCP with OpenSSH for Windows 8.0.

![image](https://user-images.githubusercontent.com/12881023/65951090-54cdec00-e40d-11e9-9cd6-8b65292c0e1b.png)

**Comment by imaxhung** [comment]
@NoMoreFood 
Only file address format is different.
![20191001180102](https://user-images.githubusercontent.com/13298913/65952959-8f6b6f00-e475-11e9-95f0-50af15f6b8e7.jpg)
![E5BF5778-A5B8-4881-A579-01F95F6B0DB0](https://user-images.githubusercontent.com/13298913/65953048-bcb81d00-e475-11e9-9387-5576d962428a.png)

**Comment by imaxhung** [comment]
I think it‘s a server-side problem under win10 platform(new installation a month ago), not a client problem.
Will it be caused by the impact of other software? @NoMoreFood

**Comment by imaxhung** [comment]
More test to prove that this should be a service-side problem.
Both places display all files normally in winscp.
![20191002100707](https://user-images.githubusercontent.com/13298913/66013351-71e1e800-e4fd-11e9-8610-05a2d678a230.jpg)

**Comment by NoMoreFood** [comment]
So you're probably right about the service-side aspect if WinSCP exhibits the issue.  I'm still trying to reproduce this from the same-named local directory.  Can you double check that you are running the newest version of the server as well (sshd.exe and sftp-server.exe)?

@manojampalam Unrelated to this issue but for your awareness, the 8.0 binaries have a reference to 7.9 in them:

![image](https://user-images.githubusercontent.com/12881023/66033903-37188980-e4d6-11e9-8f50-e5844dc59e13.png)

**Comment by imaxhung** [comment]
I'm running the newest version(downloaded from releases here). Even tested all releases. 
Start with the version v7.7.1.0p1-Beta, sshd can be started properly for me.

**Comment by imaxhung** [comment]
I've turned to use  freeSSHd. It works fine for me.
Thank you for your attention. @NoMoreFood 
![20191004141127](https://user-images.githubusercontent.com/13298913/66185287-7f3fd380-e6b1-11e9-9c33-495cd9871c36.png)

**Comment by manojampalam** [comment]
> So you're probably right about the service-side aspect if WinSCP exhibits the issue.  I'm still trying to reproduce this from the same-named local directory.  Can you double check that you are running the newest version of the server as well (sshd.exe and sftp-server.exe)?
> @manojampalam Unrelated to this issue but for your awareness, the 8.0 binaries have a reference to 7.9 in them:

Thanks @NoMoreFood. Fixed it post release.

**Comment by imaxhung** [comment]
Just tested v8.1.0.0p1-Beta
This closed issue had been solved since this release.
Thanks for your work. @NoMoreFood
