### ISSUE TITLE
ssh-keygen uses invalid path

### ISSUE THREAD

**Issue by cosmicvibe** [PowerShell/Win32-OpenSSH#147]
C:\Windows\system32>ssh-keygen -t rsa -b 4096
Generating public/private rsa key pair.
Enter file in which to save the key (C:\Users\wawer**/.ssh/id_rsa)**:

See bold. Path is not valid on Windows.

**Comment by quamrulmina** [comment]
Actually, Windows APIs/C/C++ runtime APIs allow mixing of slashes and the directory ".ssh" will be created if needed and the file id_rsa and id_rsa.pub will be created in that directory. So generating public/private key pair would actually succeed. But decoratively, the forward slashes can be converted to all back slashes in the code to make things look Windows oriented to the user for usability.

**Comment by manojampalam** [comment]
dup #156
