### ISSUE TITLE
sftp -b option including non ascii code  path cause error

### ISSUE THREAD

**Issue by Captain-K** [PowerShell/Win32-OpenSSH#1475]
**Troubleshooting steps**
open cmd
cd C:\Users\hoge
$ sftp -i foo.pem -b [full-path including non ascii code] fuga@xxx.xxx.xxx.xxx

*foo.pem is under C:\Users\hoge

**"OpenSSH for Windows" version**
v8.0.0.0p1-Beta

**What is failing**
No such file or directory (C:\\Users\\hoge\\343\203\206\343\202\271\343\203\210\\test.txt).

**Comment by NoMoreFood** [comment]
Can't seem to reproduce this.  Can you verify that sftp.exe is actually coming form the appropriate location?  It's not uncommon for other utilities to install it and put it in the path.

![image](https://user-images.githubusercontent.com/12881023/66116769-53cdc380-e5a1-11e9-9c05-121dc56ac92e.png)

**Comment by Captain-K** [comment]
thanx for replying

can you 'get' also as well as 'put' ?
`sftp> get △△△△.txt`

in my env, error occured
```
Couldn't open local file "△△△△.txt" for writing: No such file or directory
```

**Comment by maertendMSFT** [comment]
We cannot repro this issue.  Closing
