### ISSUE TITLE
Issues with SSH Configuration...

### ISSUE THREAD

**Issue by Comptech0174** [PowerShell/Win32-OpenSSH#1477]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

Troubleshooting steps have been followed, see output below

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

This is not a terminal issue, this is an SSH configuration issue... 

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`

7.7.2.2
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

Windows Server 2019 Datacenter

**Client OperatingSystem**

Windows 10 Enterprise 1903

**What is failing**

I'm attempting to configure an SSH to be an SFTP server only and create multiple Chrroot directory jails based on the active directory group membership of the user logging on.  I'm using the following configuration.  When I attempt to logon as a member of the Server_admins group I get access denied.  See attached logs for details... 

#Configure a subsystem.
Subsystems sftp	sftp-server.exe
#Set default ChrootDirectory
ChrootDirectory d:\sftproot
#Force local logging
SyslogFacility LOCAL0
#Set loglevel
LogLevel debug3
#Define parameters for HR users with SFTP access
Match Group mydomain\hr_sftp_access
       AllowGroups mydomain\hr_sftp_access
       ChrootDirectory e:\hrdatastorage
	   AllowTCPForwarding no
	   X11Forwarding no
	   ForceCommand internal-sftp
#Define parameters for HR users with SFTP access
Match Group mydomain\its_sftp_access
       AllowGroups mydomain\its_sftp_access
       ChrootDirectory f:\itsdatastorage
	   AllowTCPForwarding no
	   X11Forwarding no
	   ForceCommand internal-sftp
#Define Paramaeter to Server_Admins
Match Group mydomain\server_admins
       AllowGroups mydomain\server_admins
	   AllowTCPForwarding no
	   X11Forwarding no
	   ForceCommand internal-sftp

**Expected output**

Successful logon with users being placed into the correct Chroot jail based on their active directory group membership. 

**Actual output**

Access denied.  See log output below. 

3148 2019-10-10 14:26:34.837 debug2: fd 3 setting O_NONBLOCK
3148 2019-10-10 14:26:34.837 debug3: sock_set_v6only: set socket 3 IPV6_V6ONLY
3148 2019-10-10 14:26:34.837 debug1: Bind to port 22 on ::.
3148 2019-10-10 14:26:34.837 Server listening on :: port 22.
3148 2019-10-10 14:26:34.837 debug2: fd 4 setting O_NONBLOCK
3148 2019-10-10 14:26:34.837 debug1: Bind to port 22 on 0.0.0.0.
3148 2019-10-10 14:26:34.837 Server listening on 0.0.0.0 port 22.
3148 2019-10-10 14:26:58.612 debug3: fd 5 is not O_NONBLOCK
3148 2019-10-10 14:26:58.612 debug3: spawning "C:\\windows\\System32\\OpenSSH\\sshd.exe" "-R"
3148 2019-10-10 14:26:58.615 debug3: send_rexec_state: entering fd = 8 config len 549
3148 2019-10-10 14:26:58.615 debug3: ssh_msg_send: type 0
3148 2019-10-10 14:26:58.615 debug3: send_rexec_state: done
4556 2019-10-10 14:26:58.661 debug1: inetd sockets after dupping: 3, 3
4556 2019-10-10 14:26:58.661 Connection from 10.1.20.164 port 6560 on 10.42.4.11 port 22
4556 2019-10-10 14:26:58.661 debug1: Client protocol version 2.0; client software version OpenSSH_for_Windows_7.7
4556 2019-10-10 14:26:58.661 debug1: match: OpenSSH_for_Windows_7.7 pat OpenSSH* compat 0x04000000
4556 2019-10-10 14:26:58.661 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
4556 2019-10-10 14:26:58.661 debug2: fd 3 setting O_NONBLOCK
4556 2019-10-10 14:26:58.708 debug3: spawning "C:\\windows\\System32\\OpenSSH\\sshd.exe" "-y"
4556 2019-10-10 14:26:58.708 debug2: Network child is on pid 6460
4556 2019-10-10 14:26:58.708 debug3: send_rexec_state: entering fd = 6 config len 549
4556 2019-10-10 14:26:58.708 debug3: ssh_msg_send: type 0
4556 2019-10-10 14:26:58.708 debug3: send_rexec_state: done
4556 2019-10-10 14:26:58.708 debug3: ssh_msg_send: type 0
4556 2019-10-10 14:26:58.708 debug3: ssh_msg_send: type 0
4556 2019-10-10 14:26:58.708 debug3: preauth child monitor started
4556 2019-10-10 14:26:58.724 debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
4556 2019-10-10 14:26:58.724 debug3: send packet: type 20 [preauth]
4556 2019-10-10 14:26:58.724 debug1: SSH2_MSG_KEXINIT sent [preauth]
4556 2019-10-10 14:26:58.724 debug3: receive packet: type 20 [preauth]
4556 2019-10-10 14:26:58.724 debug1: SSH2_MSG_KEXINIT received [preauth]
4556 2019-10-10 14:26:58.724 debug2: local server KEXINIT proposal [preauth]
4556 2019-10-10 14:26:58.724 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1 [preauth]
4556 2019-10-10 14:26:58.724 debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
4556 2019-10-10 14:26:58.724 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
4556 2019-10-10 14:26:58.724 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
4556 2019-10-10 14:26:58.724 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
4556 2019-10-10 14:26:58.724 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
4556 2019-10-10 14:26:58.724 debug2: compression ctos: none [preauth]
4556 2019-10-10 14:26:58.724 debug2: compression stoc: none [preauth]
4556 2019-10-10 14:26:58.724 debug2: languages ctos:  [preauth]
4556 2019-10-10 14:26:58.724 debug2: languages stoc:  [preauth]
4556 2019-10-10 14:26:58.724 debug2: first_kex_follows 0  [preauth]
4556 2019-10-10 14:26:58.724 debug2: reserved 0  [preauth]
4556 2019-10-10 14:26:58.740 debug2: peer client KEXINIT proposal [preauth]
4556 2019-10-10 14:26:58.740 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c [preauth]
4556 2019-10-10 14:26:58.740 debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa [preauth]
4556 2019-10-10 14:26:58.740 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
4556 2019-10-10 14:26:58.740 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
4556 2019-10-10 14:26:58.740 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
4556 2019-10-10 14:26:58.740 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
4556 2019-10-10 14:26:58.740 debug2: compression ctos: none [preauth]
4556 2019-10-10 14:26:58.740 debug2: compression stoc: none [preauth]
4556 2019-10-10 14:26:58.740 debug2: languages ctos:  [preauth]
4556 2019-10-10 14:26:58.740 debug2: languages stoc:  [preauth]
4556 2019-10-10 14:26:58.740 debug2: first_kex_follows 0  [preauth]
4556 2019-10-10 14:26:58.740 debug2: reserved 0  [preauth]
4556 2019-10-10 14:26:58.740 debug1: kex: algorithm: curve25519-sha256 [preauth]
4556 2019-10-10 14:26:58.740 debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
4556 2019-10-10 14:26:58.740 debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
4556 2019-10-10 14:26:58.740 debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
4556 2019-10-10 14:26:58.740 debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
4556 2019-10-10 14:26:58.771 debug3: receive packet: type 30 [preauth]
4556 2019-10-10 14:26:58.771 debug3: mm_key_sign entering [preauth]
4556 2019-10-10 14:26:58.771 debug3: mm_request_send entering: type 6 [preauth]
4556 2019-10-10 14:26:58.771 debug3: mm_key_sign: waiting for MONITOR_ANS_SIGN [preauth]
4556 2019-10-10 14:26:58.771 debug3: mm_request_receive_expect entering: type 7 [preauth]
4556 2019-10-10 14:26:58.771 debug3: mm_request_receive entering [preauth]
4556 2019-10-10 14:26:58.771 debug3: mm_request_receive entering
4556 2019-10-10 14:26:58.771 debug3: monitor_read: checking request 6
4556 2019-10-10 14:26:58.771 debug3: mm_answer_sign
4556 2019-10-10 14:26:58.786 debug3: mm_answer_sign: hostkey proof signature 000002740CD85F40(100)
4556 2019-10-10 14:26:58.786 debug3: mm_request_send entering: type 7
4556 2019-10-10 14:26:58.786 debug2: monitor_read: 6 used once, disabling now
4556 2019-10-10 14:26:58.786 debug3: send packet: type 31 [preauth]
4556 2019-10-10 14:26:58.786 debug3: send packet: type 21 [preauth]
4556 2019-10-10 14:26:58.786 debug2: set_newkeys: mode 1 [preauth]
4556 2019-10-10 14:26:58.786 debug1: rekey after 134217728 blocks [preauth]
4556 2019-10-10 14:26:58.786 debug1: SSH2_MSG_NEWKEYS sent [preauth]
4556 2019-10-10 14:26:58.786 debug1: expecting SSH2_MSG_NEWKEYS [preauth]
4556 2019-10-10 14:26:58.786 debug3: send packet: type 7 [preauth]
4556 2019-10-10 14:26:58.833 debug3: receive packet: type 21 [preauth]
4556 2019-10-10 14:26:58.833 debug1: SSH2_MSG_NEWKEYS received [preauth]
4556 2019-10-10 14:26:58.833 debug2: set_newkeys: mode 0 [preauth]
4556 2019-10-10 14:26:58.833 debug1: rekey after 134217728 blocks [preauth]
4556 2019-10-10 14:26:58.833 debug1: KEX done [preauth]
4556 2019-10-10 14:26:58.912 debug3: receive packet: type 5 [preauth]
4556 2019-10-10 14:26:58.912 debug3: send packet: type 6 [preauth]
4556 2019-10-10 14:26:58.958 debug3: receive packet: type 50 [preauth]
4556 2019-10-10 14:26:58.958 debug1: userauth-request for user mydomain\\\\my.user service ssh-connection method none [preauth]
4556 2019-10-10 14:26:58.958 debug1: attempt 0 failures 0 [preauth]
4556 2019-10-10 14:26:58.958 debug3: mm_getpwnamallow entering [preauth]
4556 2019-10-10 14:26:58.958 debug3: mm_request_send entering: type 8 [preauth]
4556 2019-10-10 14:26:58.958 debug3: mm_getpwnamallow: waiting for MONITOR_ANS_PWNAM [preauth]
4556 2019-10-10 14:26:58.958 debug3: mm_request_receive_expect entering: type 9 [preauth]
4556 2019-10-10 14:26:58.958 debug3: mm_request_receive entering [preauth]
4556 2019-10-10 14:26:58.958 debug3: mm_request_receive entering
4556 2019-10-10 14:26:58.958 debug3: monitor_read: checking request 8
4556 2019-10-10 14:26:58.958 debug3: mm_answer_pwnamallow
4556 2019-10-10 14:26:58.958 debug2: parse_server_config: config reprocess config len 549
4556 2019-10-10 14:26:58.958 debug3: checking match for 'Group mydomain\\hr_sftp_access' user mydomain\\my.user host 10.1.20.164 addr 10.1.20.164 laddr 10.42.4.11 lport 22
4556 2019-10-10 14:26:59.396 debug3: lookup_principal_name: Successfully discovered explicit principal name: 'mydomain\\my.user'=>'my.user@mydomainindustries.com'
4556 2019-10-10 14:26:59.474 debug3: LsaLogonUser Succeeded (Impersonation: 0)
4556 2019-10-10 14:26:59.474 debug1: user l does not match group list mydomain\\hr_sftp_access at line 10
4556 2019-10-10 14:26:59.474 debug3: match not found
4556 2019-10-10 14:26:59.474 debug3: checking match for 'Group mydomain\\its_sftp_access' user l host 10.1.20.164 addr 10.1.20.164 laddr 10.42.4.11 lport 22
4556 2019-10-10 14:26:59.630 debug1: get_passwd: LookupAccountName() failed: 1332.
4556 2019-10-10 14:26:59.630 debug1: Can't match group at line 17 because user l does not exist
4556 2019-10-10 14:26:59.630 debug3: match not found
4556 2019-10-10 14:26:59.630 debug3: checking match for 'Group mydomain\\server_admins' user l host 10.1.20.164 addr 10.1.20.164 laddr 10.42.4.11 lport 22
4556 2019-10-10 14:26:59.646 debug1: get_passwd: LookupAccountName() failed: 1332.
4556 2019-10-10 14:26:59.646 debug1: Can't match group at line 24 because user l does not exist
4556 2019-10-10 14:26:59.646 debug3: match not found
4556 2019-10-10 14:26:59.646 debug3: mm_answer_pwnamallow: sending MONITOR_ANS_PWNAM: 0
4556 2019-10-10 14:26:59.646 debug3: mm_request_send entering: type 9
4556 2019-10-10 14:26:59.646 debug2: monitor_read: 8 used once, disabling now
4556 2019-10-10 14:26:59.646 debug3: mm_inform_authserv entering [preauth]
4556 2019-10-10 14:26:59.646 debug3: mm_request_send entering: type 4 [preauth]
4556 2019-10-10 14:26:59.646 debug2: input_userauth_request: try method none [preauth]
4556 2019-10-10 14:26:59.646 debug3: mm_request_receive entering
4556 2019-10-10 14:26:59.646 debug3: monitor_read: checking request 4
4556 2019-10-10 14:26:59.646 debug3: mm_answer_authserv: service=ssh-connection, style=
4556 2019-10-10 14:26:59.646 debug2: monitor_read: 4 used once, disabling now
4556 2019-10-10 14:26:59.646 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
4556 2019-10-10 14:26:59.646 debug3: send packet: type 51 [preauth]
4556 2019-10-10 14:26:59.693 debug3: receive packet: type 50 [preauth]
4556 2019-10-10 14:26:59.693 debug1: userauth-request for user mydomain\\\\my.user service ssh-connection method keyboard-interactive [preauth]
4556 2019-10-10 14:26:59.693 debug1: attempt 1 failures 0 [preauth]
4556 2019-10-10 14:26:59.693 debug2: input_userauth_request: try method keyboard-interactive [preauth]
4556 2019-10-10 14:26:59.693 debug1: keyboard-interactive devs  [preauth]
4556 2019-10-10 14:26:59.693 debug1: auth2_challenge: user=mydomain\\\\my.user devs= [preauth]
4556 2019-10-10 14:26:59.693 debug1: kbdint_alloc: devices '' [preauth]
4556 2019-10-10 14:26:59.693 debug2: auth2_challenge_start: devices  [preauth]
4556 2019-10-10 14:26:59.693 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
4556 2019-10-10 14:26:59.693 debug3: send packet: type 51 [preauth]
4556 2019-10-10 14:27:04.403 debug3: receive packet: type 50 [preauth]
4556 2019-10-10 14:27:04.403 debug1: userauth-request for user mydomain\\\\my.user service ssh-connection method password [preauth]
4556 2019-10-10 14:27:04.403 debug1: attempt 2 failures 1 [preauth]
4556 2019-10-10 14:27:04.403 debug2: input_userauth_request: try method password [preauth]
4556 2019-10-10 14:27:04.403 debug3: mm_auth_password entering [preauth]
4556 2019-10-10 14:27:04.403 debug3: mm_request_send entering: type 12 [preauth]
4556 2019-10-10 14:27:04.403 debug3: mm_auth_password: waiting for MONITOR_ANS_AUTHPASSWORD [preauth]
4556 2019-10-10 14:27:04.403 debug3: mm_request_receive_expect entering: type 13 [preauth]
4556 2019-10-10 14:27:04.403 debug3: mm_request_receive entering [preauth]
4556 2019-10-10 14:27:04.403 debug3: mm_request_receive entering
4556 2019-10-10 14:27:04.403 debug3: monitor_read: checking request 12
4556 2019-10-10 14:27:04.403 debug1: Windows authentication failed for user: NOUSER domain: . error: 1326
4556 2019-10-10 14:27:04.403 debug3: mm_answer_authpassword: sending result 0
4556 2019-10-10 14:27:04.403 debug3: mm_request_send entering: type 13
4556 2019-10-10 14:27:04.403 Failed password for invalid user mydomain\\my.user from 10.1.20.164 port 6560 ssh2
4556 2019-10-10 14:27:04.403 debug3: mm_auth_password: user not authenticated [preauth]
4556 2019-10-10 14:27:04.403 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
4556 2019-10-10 14:27:04.403 debug3: send packet: type 51 [preauth]

**Comment by NoMoreFood** [comment]
Please try latest version.  There was a bug with group matching using multiple groups in that version.
