### ISSUE TITLE
Works one way but not the other

### ISSUE THREAD

**Issue by CaptainRon47** [PowerShell/Win32-OpenSSH#1478]
I am trying to connect without entering password from a Linux based Rpi to a Win 7 system.  I have loaded OpenSSH-Win32 on the windows machine and I have SSh on the RPI.  I generated key files on the rpi and can transfer them to the Win-7 system using SCP.  I have set the file permissions on the Win-7 system using "ICACLS" commands.  

I can run ssh in a command prompt window (on Win7) and get a command prompt on the RPI without entering a password.  However I cannot go the other way (which is what I really want to do).  in the debug output it says "we sent a publickey packet. wait for reply" but then says "trying private key:..." and eventually drops to password method.

I am really scratching my head; but I am not sure it is finding the public key files on the Win-7 system as they are in C:/users/bxxxx/.ssh/ directory.  If I try to use a config file to explicitly set the  Identityfile it comes back as no such file or directory?

Can anyone help ?

thanks,
Ron

**Comment by CaptainRon47** [comment]
from the debug output I could see it was not finding "__ProgramData__"/ssh/administrators_authorized_keys.
 I had previously copied both the private and public key files (from the rpi) into C:/ProgramData/ssh and renamed them as the host keys, then ran ssh-add.exe. So I then changed the config file to line:
       AuthorizedKeysFile C:/ProgramData/ssh/administrators_authorized_keys
now I get
6368 2019-10-10 20:53:07.961 debug1: trying public key file:/ProgramData/ssh/administrators_authorized_keys
6368 2019-10-10 20:53:07.961 Authentication refused.

I don't know if this is progress or NOT?

**Comment by CaptainRon47** [comment]
the attached files are debug output for an attempt to ssh from the RPI to a Win7 PC.  the _v file is the verbose output on the rpi during the failed attempt, while the other file is the debug output in the Win7 log file.

[rpi_to_win7_fail.txt](https://github.com/PowerShell/Win32-OpenSSH/files/3720136/rpi_to_win7_fail.txt)

[rpi_to_win7_fail_v.txt](https://github.com/PowerShell/Win32-OpenSSH/files/3720139/rpi_to_win7_fail_v.txt)

Can anyone tell why the authentication failed?

thanks,
Ron

**Comment by NoMoreFood** [comment]
Try taking these lines out of C:\ProgramData\ssh\sshd_config and restart the service.  And then just make sure your public key string is in C:\Users\userid\.ssh\authorized_keys

```
Match Group administrators
AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
```

**Comment by CaptainRon47** [comment]
Thanks,
I have modified the sshd_config file on the Win7 machine from the defaults as follows:
SyslogFacility LOCAL0
LogLevel DEBUG2
StrictModes no
RSAAuthentication yes
the line you suggested is already commented out.

What I find in the sshd_log file is this:
57304 2019-10-13 20:57:45.098 debug1: userauth-request for user rons service ssh-connection method publickey [preauth]
57304 2019-10-13 20:57:45.098 debug1: attempt 1 failures 0 [preauth]
57304 2019-10-13 20:57:45.098 debug2: input_userauth_request: try method publickey [preauth]
57304 2019-10-13 20:57:45.098 debug2: userauth_pubkey: valid user rons querying public key ssh-rsa 
57304 2019-10-13 20:57:45.099 debug1: userauth_pubkey: test pkalg ssh-rsa pkblob RSA SHA256:JOmd5OXHD7IUCeK6AM0novX2nJx97jYZrWru57pJCyk [preauth]
57304 2019-10-13 20:57:45.099 debug1: trying public key file C:\\Users\\RonS\\.ssh/authorized_keys
57304 2019-10-13 20:57:45.099 debug1: Could not open authorized keys 'C:\\Users\\RonS\\.ssh/authorized_keys': Permission denied
57304 2019-10-13 20:57:45.100 debug1: trying public key file C:\\Users\\RonS\\.ssh/authorized_keys2
57304 2019-10-13 20:57:45.100 debug1: Could not open authorized keys 'C:\\Users\\RonS\\.ssh/authorized_keys2': No such file or directory
57304 2019-10-13 20:57:45.100 Failed publickey for rons from 192.168.0.128 port 59614 ssh2: RSA SHA256:JOmd5OXHD7IUCeK6AM0novX2nJx97jYZrWru57pJCyk
57304 2019-10-13 20:57:45.101 debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa [preauth]
57304 2019-10-13 20:57:45.106 debug1: userauth-request for user rons service ssh-connection method keyboard-interactive [preauth]
57304 2019-10-13 20:57:45.106 debug1: attempt 2 failures 1 [preauth]
57304 2019-10-13 20:57:45.106 debug2: input_userauth_request: try method keyboard-interactive [preauth]

I had used icacls to remove all permissions in the .ssh directory except for those of the main user 
(which is also how I am trying to access the Win7 machine thru).  The remaining permissions in that directory are as follows:
authorized_keys RonLaptop\RonS:(F)
authorized_keys RonLaptop\RonS:(F)

However the permissions on that directory (C:/users/rons/.ssh are
C:/users/rons/.ssh RonLaptop\RonS:(OI)(CI)(F)

I don't know how to remove the object (OI) and class (CI) permissions and I am not sure if that is the issue.
Originally I had created a separate user (from rons) to try as the ssh user, but that was not working so I went back to using my main login user.  I may try creating a new user just for ssh again, now that I have made some progress.  

please let me know if you have any questions or needed input to help resolve my issue.

thanks,
Ron

**Comment by CaptainRon47** [comment]
Ok, Never mind - I believe I have it working.  I had to add Administrators full permissions to both the directory and the file (authorized users) and now the RPI can SSh into the Win 7 machine.

thanks for your input.
