### ISSUE TITLE
ssh-keygen uses invalid path

### ISSUE THREAD

**Issue by ppdac** [PowerShell/Win32-OpenSSH#148]
C:\Windows\system32>ssh-keygen -t rsa -b 4096
Generating public/private rsa key pair.
Enter file in which to save the key **(C:\Users\wawer/.ssh/id_rsa)**:

See bold. Path is not valid on Windows.

I installed via Chocolately.

**Comment by quamrulmina** [comment]
Actually, Windows APIs/C/C++ runtime APIs allow mixing of slashes and the directory ".ssh" will be created if needed and the file id_rsa and id_rsa.pub will be created in that directory. So generating public/private key pair would actually succeed. But decoratively, the forward slashes can be converted to all back slashes in the code to make things look Windows oriented to the user for usability.

**Comment by cosmicvibe** [comment]
The path is simply not created:

> C:\Windows\system32>ssh-keygen -t rsa -b 4096
> Generating public/private rsa key pair.
> Enter file in which to save the key (C:\Users\wawer/.ssh/id_rsa): tets
> Enter passphrase (empty for no passphrase):
> 
> C:\Windows\system32>cd C:\Users\wawer/.ssh/
> The system cannot find the path specified.

**Comment by Morten242** [comment]
> Enter file in which to save the key (C:\Users\wawer/.ssh/id_rsa):

This is a prompt to _change_ the location of the file (I always found it confusing too..). The standard path is listed inside the parenthesis (ie. ``C:\Users\wawer/.ssh/id_rsa``). When you wrote 'tets' and pressed enter it instead ended up being saved directly to the working directory with the name you gave it (ie. ``C:\windows\system32\tets``).

Pressing enter when that prompt appears will make it save to that particular path.

**Comment by cosmicvibe** [comment]
Thank you Morten, I see how it works now.

**Comment by bagajjal** [comment]
Verified this on the latest build and it seems to work fine.. 
Please reopen if you still have issues..

E:\test>del c:\Users\test_user\.ssh\id_rsa*

E:\test>.\ssh-keygen.exe -t rsa
Generating public/private rsa key pair.
Enter file in which to save the key (c:\Users\test_user/.ssh/id_rsa):
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in c:\Users\test_user/.ssh/id_rsa.
Your public key has been saved in c:\Users\test_user/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:dCmftA5xBsPKhX34/KmAr2Hbb4e+dsHEa5OO17LLsU0 test_user@REDMOND@testuser-d
The key's randomart image is:
+---[RSA 2048]----+
|       +o.       |
|      . =o..     |
|     . o++*.     |
|      o. Oooo    |
|       .S ++ +   |
|      . .o  X    |
|      o. ..*.+E  |
|     . +. *.*=.  |
|      o..=+==+.  |
+----[SHA256]-----+

E:\test>dir c:\Users\test_user\.ssh\id_rsa*
 Volume in drive C is Windows
 Volume Serial Number is 9C8B-C608

 Directory of c:\Users\test_user\.ssh

07/07/2017  04:05 PM             1,679 id_rsa
07/07/2017  04:05 PM               406 id_rsa.pub
               2 File(s)          2,085 bytes
               0 Dir(s)  223,633,211,392 bytes free

E:\test>
