### ISSUE TITLE
Right-click pasting into active SSH-Session strips away certain symbols

### ISSUE THREAD

**Issue by arminlinzbauer** [PowerShell/Win32-OpenSSH#1483]
Please answer the following

**"OpenSSH for Windows" version**
7.7.2.2

**Client OperatingSystem**
Windows 10 Pro 1903, OS Build 18362.418

**What is failing**
Right-click pasting into active SSH-Session strips section symbol (§) and probably others, too.
I noticed this odd behavior when I couldn't log into mysql with the password I right-click-pasted into the password-prompt. CMD and PowerShell themselves handle it correctly. Also I was able to log into mysql using a PuTTY-SSH-Session. Right-click-pasting works there, too.

It is possible, to manually add the stripped symbols back in if the keyboard layout offers the symbol (the section symbol is available with e.g. a standard German keyboard layout).

**Expected output**
not applicable

**Actual output**
not applicable

**Comment by FiZiX** [comment]
I can confirm. I'm having the same issue.

**Comment by maertendMSFT** [comment]
Can you try this on the latest version, please open a new issue if you still see this.
