### ISSUE TITLE
Can't load ssh key via "-i" argument

### ISSUE THREAD

**Issue by Deliay** [PowerShell/Win32-OpenSSH#1488]
**"OpenSSH for Windows" version**
`7.7.2.2`
 
**Server OperatingSystem**
`Ubuntu 18.04`

**Client OperatingSystem**
 `Windows 10 Pro`

**What is failing**
Load ssh-key

**Actual output**
Key exist and it have right permission setting
![image](https://user-images.githubusercontent.com/5661435/67791463-6d83fd00-fab2-11e9-9800-e7e2e4cf0fca.png)

Connect and pass identity file via `-i (id_file_path)` argument, but verbose information show the key not exist
![image](https://user-images.githubusercontent.com/5661435/67791192-ff3f3a80-fab1-11e9-9383-515b760696a5.png)

**Comment by bagajjal** [comment]
@Deliay - Is it a symbolic link? Can you try this in cmd.exe/powershell.

**Comment by Deliay** [comment]
![image](https://user-images.githubusercontent.com/5661435/68069310-6fdba500-fd99-11e9-8452-0be4b9d8e2bd.png)

@bagajjal - It seem not a symbolic link. Try in cmd.exe and powershell still reproduce same error.

**Comment by Deliay** [comment]
![image](https://user-images.githubusercontent.com/5661435/68069417-dca36f00-fd9a-11e9-8d76-ff46814fc77b.png)

My script defined a shorthand command to connect to server, it working in the past few month. But it get error recently.

**Comment by maertendMSFT** [comment]
Can you try the newest version?  Please open a new issue if this persists.
