### ISSUE TITLE
install-sshlsa.ps1 is not digitally signed

### ISSUE THREAD

**Issue by carrillo455** [PowerShell/Win32-OpenSSH#149]
I got this error running this command on Windows Server 2012 (Admin mode):

powershell.exe .\install-sshlsa.ps1

Error: "about_Execution_Policies"..

Need help, please :(

**Comment by carrillo455** [comment]
+ CategoryInfo          : SecurityError: (:) [], PSSecurityException
 + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by Ventusfahrer** [comment]
as suggested: just execute 

Get-Help about_Execution_Policy.

for details.

This will end up in on of the following comands:

1. in an elevated powershell: Set-ExecutionPolicy unrestricted
2. start the script as follows:    powershell.exe -executionpolicy unrestricted ./install-sshlsa.ps1

**Comment by DarwinJS** [comment]
Do **NOT** set your execution policy to 'unrestricted'  It is much better to set it to RemoteSigned which will work for any unsigned scripts that reside on the local machine.

**Comment by carrillo455** [comment]
thanks @Ventusfahrer! I tried as in 2, it worked.

Yes @DarwinJS, I executed the unrestricted only for this command to avoid changing the variable.
Salutes +1

**Comment by DarwinJS** [comment]
@carrillo455 - If you followed the code in this thread it would do it permanently.  The only way to do it temporarily is start CMD and then execute "powershell -executionpolicy unrestricted" - then it is per-process.  Set-ExecutionPolicy CMDLet always makes a permanent change.

**Comment by carrillo455** [comment]
Yes, got it @DarwinJS  I only did point number 2 from Ventusfahrer answer, thanks!!

**Comment by manojampalam** [comment]
We'll have an official installation package later.
