### ISSUE TITLE
sshd lets users with expired passwords log in with SSH keys

### ISSUE THREAD

**Issue by ChrisITpro** [PowerShell/Win32-OpenSSH#1495]
**"OpenSSH for Windows" version**
Latest (8.0.0.0) from https://github.com/PowerShell/Win32-OpenSSH/releases
 
**Server OperatingSystem**
Tried only Windows 2008R2 and 2012R2

**Client OperatingSystem**
Tried only Windows 10, with PuTTY-CAC 0.73 SSH client

**What is failing**
It's more a security issue than a failure in my opinion. If a Windows user has its password expired but still has its SSH key in the authorized_keys file, the user can still log in and nothing forces them to change their password immediately.

**Expected output**
I would expect the same behaviour than when connecting to a Linux sshd server: so whether you log in with a password or an SSH key, the server checks your account and forces you to change your password if it is expired.

**Actual output**
If a Windows user has its password expired but still has its SSH key in the authorized_keys file, the user can still log in and nothing forces them to change their password immediately. The user with expired password can basically do whatever they want through the command line.
I noticed the opposite issue exists when logging in with password: access is simply denied if your password is expired (already reported in https://github.com/PowerShell/Win32-OpenSSH/issues/748).

**Comment by mgkuhn** [comment]
On Linux, that will most likely be done by a PAM module, e.g. read `man pam_unix`, and not by `sshd`. So I am not convinced this is (or should be) an sshd issue.

Perhaps the best solution for you is to disable public-key authentication, enable GSSAPIAuthentication instead, and then the kinit (or equivalent) on your client should fail if the user's Active Directory password has expired. No unexpired password, no Kerberos ticket, no login.

I wouldn't expect sshd to worry about expired passwords if the authentication method you have chosen does not even involve a password.

**Comment by maertendMSFT** [comment]
Please see the above response.  The key based auth is different from password based auth.  As long as the key is valid on the machine, the user will be able to get access.  Please check if the same behavior is present on Linux.

**Comment by arsphl** [comment]
It is not a bug effectively. It is possible not to have an automatic login when using a public key.

AuthenticationMethods "publickey,password" 

That asks to have both mechanism checked. It is more secure. If you use public keys for automation you can authorize only specific users to have only public key.
