### ISSUE TITLE
Enter-PSSession Error processing data from the background process

### ISSUE THREAD

**Issue by JasonFossen** [PowerShell/Win32-OpenSSH#1498]
**SYMPTOMS**
After successfully configuring OpenSSH as a server on Windows, confirming that access with ssh.exe or putty.exe works as expected, when connecting with pwsh's Enter-PSSession or Invoke-Command, it fails with an error message: "There is an error processing data from the background process. Error reported: ..."  When you delete, rename or move your PowerShell profile script(s) at that OpenSSH server, the error message disappears and pwsh remoting works as expected.

**CAUSE**
You have 1) a profile script at the OpenSSH server, 2) that profile script prints or displays output when run, and 3) you have changed the default OpenSSH server's command shell from CMD to either Windows PowerShell or PowerShell Core.  The output of the profile script is disrupting the launch of pwsh as an OpenSSH "subsystem" despite the fact that the sshd_config file is correctly configured with the "..\pwsh.exe -sshs -nologo -noprofile" line. 

**REPRODUCE**
Install PowerShell Core 7 preview 5 on a Windows Server 2019 system.

Delete, rename or move all PowerShell profile scripts on that server.

Install the OpenSSH 8.0.beta sshd.exe service from GitHub on that Windows Server into $env:ProgramFiles\OpenSSH as recommended, and configure the "Subsystem" line in it's sshd_config file (https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-6).  

Confirm that the OpenSSH server is working with both ssh.exe and pwsh's "Enter-PSSession -HostName _server_."

Change the OpenSSH default command shell to either powershell.exe or pwsh.exe (https://github.com/PowerShell/Win32-OpenSSH/wiki/DefaultShell).

Confirm with ssh.exe and "Enter-PSSession -HostName _server_" that OpenSSH is still accessible and that ssh.exe gets the new default shell as expected (powershell.exe or pwsh.exe, not CMD).

Add a profile script for powershell.exe or pwsh.exe, whichever one you want, and add a command to that script which produces output, e.g., a line like "XXXXXXX".

Confirm with ssh.exe that OpenSSH is still accessible and that the profile script runs as expected, e.g., it prints "XXXXXXX."

Attempt to connect with pwsh's "Enter-PSSession -HostName _server_" as before.  Note that it now fails with an error message:  "There is an error processing data from the background process. Error reported:  XXXXXXX."

Comment out the line from the profile script which produces the output.  Add other commands to the profile script which do not produce output, e.g., create a function.  Attempt to connect again with pwsh's "Enter-PSSession -HostName _server_" and note that it succeeds.  

Uncomment the line from the profile script which produces the output and causes pwsh's Enter-PSSession to fail.

Change the default OpenSSH command shell back to CMD again.

Attempt to connect again with pwsh's "Enter-PSSession -HostName _server_" and note that it succeeds.  

**NOTES**
Set the default OpenSSH command shell back to CMD.  Use Process Explorer or a similar tool to watch the sshd.exe service as a pwsh client connects with "Enter-PSSession -HostName _server_".  The parent sshd.exe spawns a child sshd.exe, which runs "cmd.exe /c" to launch "pwsh.exe -sshs -nologo -noprofile".  It works.  

But when 1) the default OpenSSH shell is changed to either powershell.exe or pwsh.exe and 2) there is a profile script that produces output, then the parent sshd.exe runs either "powershell.exe -c" or "pwsh.exe -c" (whichever you chose) in order to launch "pwsh.exe -sshs -nologo -noprofile".  The profile script of powershell.exe/pwsh.exe is disrupting the launch of the last pwsh.exe in the chain of process launches.  

The "-c" argument to powershell.exe/pwsh.exe seems to be hard-coded into sshd.exe.  Following the above instructions for changing the default OpenSSH command shell, if you configure the DefaultShellCommandOption registry value, this value appears to be ignored by sshd.exe when launching pwsh as a subsystem.  (See https://github.com/PowerShell/Win32-OpenSSH/wiki/DefaultShell.)  Setting the DefaultShellCommandOption value to something like "-noprofile -command" does not work.

This issue has not been tested on a Linux SSH server.

This issue has not been tested on any earlier versions of pwsh or OpenSSH for Windows.

**EXPECTED BEHAVIOR**
When the default OpenSSH command shell is changed from CMD to either powershell.exe or pwsh.exe on a Windows server, and the SSH user has a profile script on that server, then that profile script should not be run when the user connects with "Enter-PSSession -HostName _server_" using pwsh.  

**MITIGATION**
Either 1) change the default OpenSSH command shell back to CMD on the target server, or 2) edit your profile script on the server so that it produces no output when it runs.  The profile script can create functions, change the Prompt function, change colors, etc., just so long as it produces no output which confuses sshd.exe.

**Comment by veleek** [comment]
Just wanted to bump this as still being the case on the most recent builds of Windows.  

I've worked around this by adding a block to the top of my profile that checks for the existence of `$env:SSH_CONNECTION` which is set when connecting with SSH.  Longer term solution is to add some magic to prevent output but that's probably a bit harder.

```powershell
if($env:SSH_CONNECTION)
{
  return
}
```

If necessary, I can manually load the profile afterwards (using an additional helpful function) and everything works peachy.

**Comment by veleek** [comment]
Just reading through the [documentation for `Write-Host`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-host?view=powershell-6) to figure out some options for this, and while it's not possible with `Write-Host` as of PS 5.0 `Write-Host` is a wrapper for `Write-Information` which supports the `$InformationPreference` variable (similar to `$ErrorPreference` and `$WarningPreference`.

Replacing your calls to `Write-Host` with `Write-Information` and then toggling `$InformationPreference` based on the `SSH_CONNECTION` variable could effectively accomplish this.  You'd have to be very careful though because that won't help with stuff which is implicitly written or stuff using `Out-Host`, but at least it's a start.

**Comment by smaug9** [comment]
Bumptity bump bump.
Getting this same error from linux pwsh 7 to win pwsh 7 over ssh.
I'll attempt to add the default cmd.exe back to the default shell to see if that works.


```
PS /etc> $Error[0].exception.tostring()
System.Management.Automation.Remoting.PSRemotingTransportException: There is an error processing data from the background process. Error reported: VERBOSE: Populating RepositorySourceLocation property for module .
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.Open()
   at System.Management.Automation.Runspaces.RunspacePool.Open()
   at System.Management.Automation.RemoteRunspace.Open()
   at Microsoft.PowerShell.Commands.EnterPSSessionCommand.GetRunspaceForSSHSession()
   at Microsoft.PowerShell.Commands.EnterPSSessionCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
PS /etc>
```

**Comment by berbology** [comment]
Just spent 2 days fighting this exact issue, going Win10 -> Win10
I've used the workaround @veleek kindly provided above but is this on anyone's radar yet?
Current tutorials around setting up the newly 1.0 Windows Terminal with Powershell 7 Remoting lead to this error for anyone, like myself, with a $PROFILE that outputs text.

**Comment by bagajjal** [comment]
This issue should go to https://github.com/PowerShell/powershell

**Comment by bagajjal** [comment]
Please raise a new issue in https://github.com/PowerShell/powershell repo.
