### ISSUE TITLE
sshd.exe hanging to start up

### ISSUE THREAD

**Issue by ericlc** [PowerShell/Win32-OpenSSH#1501]
Please answer the following

**"OpenSSH for Windows" version**
 `7.9.0.0`
 
**Server OperatingSystem**
 `Windows Server 2012 R2 Standard`

**Client OperatingSystem**
`Red Hat Enterprise Linux Server release 7.5 (Maipo)`

**What is failing**
sshd.exe is not starting correctly. It takes a long time to open port 22. The host belongs to a Windows domain.

I started in debug mode, and noticed that it takes a long time to log this line:
**debug1: get_passwd: LookupAccountName() failed: 1788.**

Full log:

debug2: load_server_config: filename __PROGRAMDATA__\\ssh/sshd_config
debug2: load_server_config: done config len = 291
debug2: parse_server_config: config __PROGRAMDATA__\\ssh/sshd_config len 291
debug3: __PROGRAMDATA__\\ssh/sshd_config:25 setting SyslogFacility LOCAL0
debug3: __PROGRAMDATA__\\ssh/sshd_config:26 setting LogLevel DEBUG3
debug3: __PROGRAMDATA__\\ssh/sshd_config:40 setting AuthorizedKeysFile .ssh/authorized_keys
debug3: __PROGRAMDATA__\\ssh/sshd_config:81 setting Subsystem sftp      sftp-server.exe
debug3: checking syntax for 'Match Group administrators'
debug1: sshd version OpenSSH_for_Windows_7.9, LibreSSL 2.6.5
debug1: get_passwd: LookupAccountName() failed: 1788.

Meanwhile, I checked the sshd process in task manager and its in a wait chain, waiting process lsass.exe

![image](https://user-images.githubusercontent.com/24657349/68790239-af21b580-0625-11ea-970a-01907c5435fb.png)

**Expected output**

Startup correctly without hanging.

How to debug this call LookupAccountName()?

**Actual output**

**Comment by NoMoreFood** [comment]
1788 (0x6FC) = ERROR_TRUSTED_DOMAIN_FAILURE = The trust relationship between the primary domain and the trusted domain failed.  

Does the computer account running the sshd service have the ability to read Active Directory information for the specified user?

**Comment by ericlc** [comment]
Which user do you mean? The error is in service startup and there is no user trying to connect yet. The service is starting with SYSTEM user.

> to read Active Directory information for the specified user?

How to check that? I can log in with domain users in this computer without any problems.

Thanks for your help.

**Comment by maertendMSFT** [comment]
LookupAccountName() has failed for the local administrators group.  This issue is specific for your network configuration.  Closing as it has been a while since it was opened.
