### ISSUE TITLE
Why does sshd service need to be run by LocalSystem?

### ISSUE THREAD

**Issue by ChrisITpro** [PowerShell/Win32-OpenSSH#1502]
**"OpenSSH for Windows" version**
Latest (https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.0.0.0p1-Beta)
 
**Server OperatingSystem**
Windows Server 2016

**Client OperatingSystem**
N./A

**What is failing**
SSHD service when trying to run it as another (less privileged) account.

**Expected output**
SSHD service running fine with other account.

**Actual output**
Error 1297 when trying to start the service.

Hello,

For security reasons, it is generally recommended that Windows services do not run as LocalSystem, especially where LocalSystem's privileges aren't needed.
Even Microsoft recommends against it:
https://docs.microsoft.com/en-us/windows/win32/ad/the-localsystem-account
https://docs.microsoft.com/en-us/windows/win32/services/localsystem-account

So I wanted to understand why LocalSystem is being used in the latest OpenSSH version for Windows, instead of a lower-privileged account.
Are there any security measures / safeguards to prevent any compromise to the SSHD service from destroying the host Windows system for example? (should that ever happen)

Thank you.

**Comment by bagajjal** [comment]
SSHD daemon runs as a system process. All it does is create a new SSHD process for the incoming connection. The new SSHD process will be running under the user context.

This is same as the Unix OpenSSH implementation.

**Comment by ChrisITpro** [comment]
Thanks, this answers my question. No need to worry then.
