### ISSUE TITLE
windows default install should not be under system32

### ISSUE THREAD

**Issue by amoldeshpande** [PowerShell/Win32-OpenSSH#1504]
**Troubleshooting steps**
Enable OpenSSH client from Windows 10 "manage optional features"

use any 32-bit ls.exe (e.g., from altlasian sourcetree and it's git_local tree)

try to  execute "ls c:/windows/system32/openssh"

It will fail because of the Filesystem Redirector sending it to SysWow64

Please answer the following

**"OpenSSH for Windows" version**
irrelevant
 
**Server OperatingSystem**
N/A

**Client OperatingSystem**
Windows 10 1903

**What is failing**
Any 32-bit app that wants to look at this directory.
**Expected output**

**Actual output**
N/A

**Comment by gunnarhaslinger** [comment]
- sshd.exe is a 64bit executable
- It is installed as a Service (sshd), as a result of this, Location C:\Windows\system32\openssh looks conforming from my perspective

A 32bit process doesn't "see" C:\Windows\System32\OpenSSH because of the Folder-Redirection, this is true, but:
- everything works as designed
- why is there a need to use a 32bit "ls.exe" Command for listing C:\Windows\System32?
- If a 32bit process needs to read something in C:\Windows\System32 it can use the virtual Path C:\Windows\SysNative\OpenSSH

**Comment by gunnarhaslinger** [comment]
Suggestion: If you really need 32bit Processes to see the Contents of C:\Windows\System32\OpenSSH and cannot use C:\Windows\SysNative\OpenSSH (for reasons I don't know) you could make a junction-Point C:\Windows\SysWOW64\OpenSSH pointing to C:\Windows\System32\OpenSSH

**Comment by amoldeshpande** [comment]
I don't need 32-bit processes to list system32. I need access to Microsoft's ssh client apps from any process on the system. Putting them in a redirected system32 makes that janky.

There are many apps (like Unix shells) which are 32-bit by default. These shells work by tracking executables in the path instead of randomly executing whatever the user typed in and let God sort it out.

I am aware I can get ssh clients from elsewhere. I would rather get it from a probably-blessed-by-Microsoft location than some random version compiled by someone an unknown number of years ago.

**Comment by gunnarhaslinger** [comment]
Then configuring "c:\Windows\SysNative\OpenSSH\ssh.exe" as your SSH-Client for 32bit-Parent-Processes should be a suitable solution.
In case you need it in the Path "set PATH=%PATH%;C:\Windows\SysNative\OpenSSH" works.

**Comment by maertendMSFT** [comment]
If a 32-bit application is looking to use openssh, then create a symlink under C:/windows/systemnative
