### ISSUE TITLE
Some characters (symbols & non-BMP characters including emoji & minor Kanji) are not passed to Linux host

### ISSUE THREAD

**Issue by tats-u** [PowerShell/Win32-OpenSSH#1505]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
8.0.0.0

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

Ubuntu 18.04
CentOS 7

**Client OperatingSystem**

Windows 10 Pro

**What is failing**

Strings containing the following characters don't properly passed to remote servers.

- `×`(U+00D7)
- `¥`(U+00A5)
- `©`(U+00A9)
- `½`(U+00BD)
- `・`(U+30FB)
- `”`(U+201D)
- `’`(U+2019)
- `→`(U+2192)
- `↔`(U+2194)
- `♯`(U+266F)
- some other symbols similar to above
- `𠮷`(U+20BB7; sometimes used for names instead of U+5409)
- `𠮟`(U+20B9F; equals to U+53F1)
- non-BMP emojis

1. Launch a text editor like Vim in a remote server and get it ready to be input.
2. Copy and paste, or type using IME such a string to a SSH session.

**Expected output**

All characters of input string.

**Actual output**

These characters are lost.  they seem not to be passed to servers. (`松屋・すき家・𠮷野家`→`松屋すき家野家`)
The rest characters are properly displayed.

**Note**

OpenSSH in WSL and NeoVim in local Windows session don't cause this problem.

**Comment by maertendMSFT** [comment]
This should work in the latest release, 8.1.  Please open a new issue if you are still experiencing issues
