### ISSUE TITLE
"Bad passphrase" error on ssh-add 

### ISSUE THREAD

**Issue by stuartleeks** [PowerShell/Win32-OpenSSH#1506]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`: 7.7.2.3
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)` : Windows 10 Enterprise

**Client OperatingSystem**
Windows 10 Enterprise

**What is failing**
I have shared SSH keys across an Unbuntu and a Windows 10 machine and recently added passphrases to my keys. I am using these keys to access git repositories so want to add the keys to the ssh-agent to avoid re-entering the passphrase. The keys are working fine in Ubuntu but on Windows when I run `ssh-add` to add the key I get  `Bad passphrase, try again`. I have the passphrase copied to the clipboard and am pasting it in to avoid typing errors. Additionally, if I perform a git command and it prompts for the passphrase, pasting it is successful.

Any suggestions for debugging this would be appreciated :-)

**Expected output**
`Bad passphrase, try again`

**Actual output**
Key should be added

**Comment by githubERIK** [comment]
@stuartleeks , I too tried pasting my ssh password to PowerShell and saw the bad passphrase error.
Eventually, it turned out that the way _how_ pasting is done matters. Once you see `Enter passphrase for ...`, then do a right click and push Enter.

---

```
PS C:\Users\user\Documents> ssh-add C:\Users\user\.ssh\personal
Enter passphrase for C:\Users\user\.ssh\personal:
```

Do a right click and push Enter. Do _not_ hit `Ctrl+V`.

```
Identity added: C:\Users\user\.ssh\personal (user@Users-Windows)
```

**Comment by maertendMSFT** [comment]
This should work in the latest release, 8.1.  Please open a new issue if you are still experiencing issues
