### ISSUE TITLE
shell request failed on channel 0

### ISSUE THREAD

**Issue by SoulHucKer** [PowerShell/Win32-OpenSSH#1508]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
v8.0.0.0p1-Beta
**Server OperatingSystem**
Windows Server 2019 Standard
**Client OperatingSystem**
Windows 10 Enterprise
**What is failing**
When I enter the password through SSH and enter, I fail to log in successfully, and the following string is returned
“shell request failed on channel 0”
**Expected output**
login success
**Actual output**
shell request failed on channel 0

**Comment by maertendMSFT** [comment]
This should work in the latest release, 8.1.  Please open a new issue if you are still experiencing issues
