### ISSUE TITLE
The OpenSSH Authentication Agent service (ssh-agent) has its startup type changed to disabled on windows upgrade

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#1509]
**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
7.7.2.3 

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 Enterprise

**What is failing**
When I update to a new build of windows (which I do fairly frequently for self hosting), the startup type of the ssh-agent service gets set to Disabled. This is regardless of what its startup type was before the upgrade. I use this service to manage my ssh keys for connecting to git servers, so I need it to always be running in order for me to work. It's getting very annoying that I keep having to go into the services management UI and re-enable this service every time I get a new build.

See also https://microsoft.visualstudio.com/OS/_workitems/edit/19782498

**Comment by maertendMSFT** [comment]
This has been fixed, it should be updated in the next large Windows update, likely during the fall timeframe.
