### ISSUE TITLE
Intermittent SIGCHLD command failures on Windows 2012 R2

### ISSUE THREAD

**Issue by paulewog** [PowerShell/Win32-OpenSSH#151]
I am really excited about the possibility of using OpenSSH.  When I was testing it on 2008 R2, it seemed to be working really well.

But, on Windows 2012, I am getting intermittent - more often than not, actually - failures.  The log ends up looking like this:

```
1228 11:03:34 337 Starting session: command for Administrator from 9.80.197.145 port 54342
1228 11:03:34 337 debug1: allocating new sfd, sfd [4] fd [5] handle [468] type [2]
1228 11:03:34 337 debug1: allocating new sfd, sfd [5] fd [6] handle [472] type [2]
1228 11:03:34 353 debug1: allocating new sfd, sfd [6] fd [7] handle [476] type [2]
1228 11:03:34 353 debug1: allocating new sfd, sfd [7] fd [8] handle [480] type [2]
1228 11:03:34 353 debug1: allocating new sfd, sfd [8] fd [9] handle [484] type [2]
1228 11:03:34 353 debug1: allocating new sfd, sfd [9] fd [10] handle [488] type [2]
1228 11:03:34 353 debug1: Using token from LogonUser()...
1228 11:03:34 353 debug1: -> GetHomeDirFromToken()...
1228 11:03:34 353 debug1: <- GetHomeDirFromToken()...
1228 11:03:34 353 debug1: Executing command: cmd /c echo hi
1228 11:03:34 353 debug1: Received SIGCHLD.
1228 11:03:34 353 debug1: session_by_pid: pid 524
1228 11:03:34 353 debug1: session_exit_message: session 0 channel 0 pid 524
1228 11:03:34 353 debug1: session_exit_message: release channel 0
1228 11:03:34 353 debug1: read from socket sfd [9] failed with error code [10054]
1228 11:03:34 353 debug1: read from socket sfd [3] failed with error code [10035]
1228 11:03:34 353 debug1: read from socket sfd [7] failed with error code [10054]
1228 11:03:34 524 Connection closed by 9.80.197.145
```

Sometimes it works.  It also seems to work almost all the time with commands like _ipconfig /all_ ... as long as you don't do something bad like _ipconfig asdf_

Any ideas?  Some setup thing that I did wrong? :)

**Comment by paulewog** [comment]
Also, the RC of the local ssh command appears to be unaffected.  If it was non-zero or some specific code that I could check for, we could just keep retrying until it worked, that would be a [hacky] workaround... :)

**Comment by paulewog** [comment]
Reg command stuff:

```
the working one:
2960 12:44:42 724 debug1: Executing command: reg query "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters" /v "NV Domain"
2960 12:44:42 739 debug1: read from socket sfd [7] failed with error code [10054]
2960 12:44:42 739 debug1: read from socket sfd [9] failed with error code [10054]
2960 12:44:42 739 debug1: Received SIGCHLD.
2960 12:44:42 739 debug1: session_by_pid: pid 524
2960 12:44:42 739 debug1: session_exit_message: session 0 channel 0 pid 524
2960 12:44:42 739 debug1: session_exit_message: release channel 0
2960 12:44:42 739 debug1: read from socket sfd [3] failed with error code [10035]
2960 12:44:42 911 Connection closed by 9.80.197.145 

12:48:23 PM: and the failing one:
904 12:44:47 583 debug1: Executing command: reg query "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters" /v "NV Domain"
904 12:44:47 599 debug1: Received SIGCHLD.
904 12:44:47 599 debug1: session_by_pid: pid 524
904 12:44:47 599 debug1: session_exit_message: session 0 channel 0 pid 524
904 12:44:47 599 debug1: session_exit_message: release channel 0
904 12:44:47 599 debug1: read from socket sfd [9] failed with error code [10054]
904 12:44:47 599 debug1: read from socket sfd [3] failed with error code [10035]
904 12:44:47 599 debug1: read from socket sfd [7] failed with error code [10054] 
```

**Comment by paulewog** [comment]
Some more information... if I prepend cmd /c to the reg query command, it works every time.  So there seems to be something about running without cmd /c ... at least on 2012, not sure about 2008, like I said.  Haven't tested that yet.

**Comment by paulewog** [comment]
Even on 2012, some commands - builtin shell commands, perhaps?  That is what failed this time - still fail when prefixed with cmd /c

... but cmd /c cmd /c dir C:\ now works every time, too.

I don't know if this is just random or not... if I drop it to one cmd /c, it fails.  Adding two cmd /c prefixes and it works.

**Comment by quamrulmina** [comment]
It seems the output sockets are being closed prematurely before all program output has gone out. This will be fixed in a future update. Only one "cmd /c" is needed when one is running a shell command giving the command in the ssh invocation ass follows.
ssh user@machine cmd /c set        -- will succeed and show all env vars of cmd shell
ssh user@machine set                    -- will fail as "set" is a cmd command and cmd is not specified
ssh user@machine ipconfig            --- will succeed as "ipconfig" is an external program

**Comment by paulewog** [comment]
Is it possible that having both cmd calls somehow makes the output get sent before the socket closes? It seems very strange that it seems to work. :)

**Comment by manojampalam** [comment]
Can you try out the latest version?

**Comment by paulewog** [comment]
Will try it out this week. :)

**Comment by paulewog** [comment]
Hello,

I'm encountering a different problem now.  When I try to install on Windows 2012 R2 and run sshd.exe, I get errors such as:

key_load_private: insufficient buffer space
Could not load host key: ssh_host_rsa_key

... for all the SSH keys.  I generated them using ssh-keygen -A

**Comment by Snegohod** [comment]
The same error on Windows Server 2012 R2 in the new release (3_19_2016). Previous release(2_25_2016) works fine.

> [Build Mar 19 2016 22:36:41]
> key_load_private: insufficient buffer space
> Could not load host key: ssh_host_rsa_key
> key_load_private: insufficient buffer space
> Could not load host key: ssh_host_dsa_key
> key_load_private: insufficient buffer space
> Could not load host key: ssh_host_ecdsa_key
> key_load_private: insufficient buffer space
> Could not load host key: ssh_host_ed25519_key
> Disabling protocol version 2. Could not load host key
> sshd: no hostkeys available -- exiting.

**Comment by manojampalam** [comment]
Thanks for testing it out. I can see the same issue on 2012 R2. Will fix it and issue an update tomorrow.

**Comment by manojampalam** [comment]
Try it out with 1.1 versions I just uploaded

**Comment by paulewog** [comment]
Cool, will try it out on a few versions tomorrow morning.

**Comment by Snegohod** [comment]
Tested OpenSHH-Win64-1.1 on 2012 R2 and 2008 R2. Works great

**Comment by paulewog** [comment]
I've also tested on 2008 R2 and 2012 R2 and both seem to be working.  Thanks! :+1:
