### ISSUE TITLE
Realpath resolves to "\" instead of "/" when "remote directory" is left empty in the ftp client.

### ISSUE THREAD

**Issue by jjverschoor** [PowerShell/Win32-OpenSSH#1512]
**"OpenSSH for Windows" version**
8.1.0.0

**Server OperatingSystem**
Windows Server 2012 R2 Standard

**Client OperatingSystem**
windows 10 1909

**What is failing**
Upon first connect, realpath resolves to "\\" rather than "/", if...

- "remote directory" is not hardcoded to "/" in the ftp client, and..
-  there is no caching of the remote directory structure. 

**Expected output**
Realpath "/" upon first connect.

**Actual output**
realpath resolves to "\\", which ultimately leads to a broken path and directory listing failures.

Problem starts in sftp-server.c where on lines 1169+ you can find that void process_realpath has been updated to call "sftp_realpath", rather than the old "realpath". 

***************start code****************
process_realpath(u_int32_t id)
{
	char resolvedname[PATH_MAX];
	char *path;
	int r;

	if ((r = sshbuf_get_cstring(iqueue, &path, NULL)) != 0)
		fatal("%s: buffer error: %s", __func__, ssh_err(r));

	if (path[0] == '\0') {
		free(path);
		path = xstrdup(".");
	}
	debug3("request %u: realpath", id);
	verbose("realpath \"%s\"", path);
	if (sftp_realpath(path, resolvedname) == NULL) {

***************end code****************

However, sftp_realpath.c omits some error checking, that was included in realpath.c, like "#if !defined(HAVE_REALPATH) || defined(BROKEN_REALPATH), etc." (Also getcwd.c misses "*--bpt = '/';" on line 118), both of which lead likely to this error of REALPATH resolving to "/".

So..

- either the error-checking needs to be reintroduced in sftp_realpath.c etc., 
- or you just change the "sftp_realpath"-reference to the old "realpath" again. 

In either case the problem is resolved.

So, ftp client log (WinSCP) reads like the below when referencing sftp_realpath.c:

. 2019-11-28 15:14:05.316 Getting current directory name.
. 2019-11-28 15:14:05.316 Getting real path for '.'
> 2019-11-28 15:14:05.316 Type: SSH_FXP_REALPATH, Size: 10, Number: 37648
> 2019-11-28 15:14:05.316 10,00,00,93,10,00,00,00,01,2E,
. 2019-11-28 15:14:05.316 Sent 14 bytes
. 2019-11-28 15:14:05.316 There are 0 bytes remaining in the send buffer
. 2019-11-28 15:14:05.316 Looking for network events
. 2019-11-28 15:14:05.316 Timeout waiting for network events
. 2019-11-28 15:14:05.316 Waiting for another 4 bytes
. 2019-11-28 15:14:05.316 Looking for incoming data
. 2019-11-28 15:14:05.316 Looking for network events
. 2019-11-28 15:14:05.316 Detected network event
. 2019-11-28 15:14:05.316 Enumerating network events for socket 1596
. 2019-11-28 15:14:05.316 Enumerated 1 network events making 1 cumulative events for socket 1596
. 2019-11-28 15:14:05.316 Handling network read event on socket 1596 with error 0
. 2019-11-28 15:14:05.316 Received 27 bytes (0)
. 2019-11-28 15:14:05.316 Read 4 bytes (23 pending)
. 2019-11-28 15:14:05.316 Read 23 bytes (0 pending)
< 2019-11-28 15:14:05.316 Type: SSH_FXP_NAME, Size: 23, Number: 37648
< 2019-11-28 15:14:05.316 68,00,00,93,10,00,00,00,01,00,00,00,01,5C,00,00,00,01,5C,00,00,00,00,
. 2019-11-28 15:14:05.316 Real path is '\\'
. 2019-11-28 15:14:05.372 Listing directory "\\".

Whilst the ftp client log (WinSCP) reads like the below when referencing realpath.c:

. 2019-11-28 21:53:18.896 Getting current directory name.
. 2019-11-28 21:53:18.896 Getting real path for '.'
> 2019-11-28 21:53:18.896 Type: SSH_FXP_REALPATH, Size: 10, Number: 16
> 2019-11-28 21:53:18.896 10,00,00,00,10,00,00,00,01,2E,
. 2019-11-28 21:53:18.896 Sent 14 bytes
. 2019-11-28 21:53:18.896 There are 0 bytes remaining in the send buffer
. 2019-11-28 21:53:18.896 Looking for network events
. 2019-11-28 21:53:18.896 Timeout waiting for network events
. 2019-11-28 21:53:18.896 Waiting for another 4 bytes
. 2019-11-28 21:53:18.896 Looking for incoming data
. 2019-11-28 21:53:18.896 Looking for network events
. 2019-11-28 21:53:18.896 Detected network event
. 2019-11-28 21:53:18.896 Enumerating network events for socket 2020
. 2019-11-28 21:53:18.897 Enumerated 1 network events making 1 cumulative events for socket 2020
. 2019-11-28 21:53:18.897 Handling network read event on socket 2020 with error 0
. 2019-11-28 21:53:18.897 Received 27 bytes (0)
. 2019-11-28 21:53:18.897 Read 4 bytes (23 pending)
. 2019-11-28 21:53:18.897 Read 23 bytes (0 pending)
< 2019-11-28 21:53:18.897 Type: SSH_FXP_NAME, Size: 23, Number: 16
< 2019-11-28 21:53:18.897 68,00,00,00,10,00,00,00,01,00,00,00,01,2F,00,00,00,01,2F,00,00,00,00,
. 2019-11-28 21:53:18.897 Real path is '/'
. 2019-11-28 21:53:18.946 Listing directory "/".

**Comment by bagajjal** [comment]
@jjverschoor  - Thanks for reporting.
I have already fixed it, the PR (https://github.com/PowerShell/openssh-portable/pull/410) is pending.

**Comment by jjverschoor** [comment]
awesome, thanks so much
