### ISSUE TITLE
SFTP does not correctly support reparse-points

### ISSUE THREAD

**Issue by jamercee** [PowerShell/Win32-OpenSSH#1520]
OpenSSH for Windows 10 (Build 1809) does not correctly support NTFS reparse points. SFTP reports reparse points as regular directories, but they do not support recursion. Attempts to `cd `into these directories reports an error (typically Bad message).

For example, use WinSCP, and try to list the directory contents of `C:\Users\myuser\AppData\Local\Application Data`, will return the error:

```
Bad message (badly formatted packet or protocol incompatibility)
Error code: 5
Error message from server: Bad message
```

A similar result can be retrieved from the python module [paramiko](https://www.paramiko.org/)

```
import paramiko
t = paramiko.Transport(('127.0.0.1', 22))
t.connect(username='myuser', password='mypassword')
sftp = paramiko.SFTPClient.from_transport(t)
sftp.listdir('/Users/myuser/AppData/Local/Application Data')

```
**OSError: Bad message**

OpenSSH should include the symlink attribute to stat, rather than just report it as a simple directory giving a client the option to then skip recursion.

**Comment by ghost** [comment]
( back ref. https://github.com/MicrosoftDocs/windowsserverdocs/issues/3619 )

**Comment by NoMoreFood** [comment]
I’m not sure what version ships with 1809.  Symlink support has been in for
awhile.  Can you try the latest?

**Comment by jamercee** [comment]
Tests are run against a fresh install of OpenSSH from 2 days ago using the instructions at https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse

Powershell reports

```
PS> Get-WindowsCapability -Online | ? Name -like 'OpenSSH.Server*'

Name  : OpenSSH.Server~~~~0.0.1.0
State : Installed
```

sshd reports:

```
C:\> sshd -v
unknown option -- v
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
usage: sshd [-46DdeiqTt] [-C connection_spec] [-c host_cert_file]
            [-E log_file] [-f config_file] [-g login_grace_time]
            [-h host_key_file] [-o option] [-p port] [-u len]
```

Is this the latest version with symlink support?

FYI, we tested this against Windows 10-Pro, 64-bit (not sure if that's relevant).

**Comment by NoMoreFood** [comment]
Yeah, the version here should support them: https://github.com/PowerShell/Win32-OpenSSH/releases
