### ISSUE TITLE
Non-interactive command output is polluted with empty lines and escape sequences

### ISSUE THREAD

**Issue by mkpankov** [PowerShell/Win32-OpenSSH#1528]
**"OpenSSH for Windows" version**
7.7.2.2
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**

CentOS 7

**What is failing**

Output is littered with empty lines and escape sequences

```
[vagrant@adm ~]$ export TERM=xterm
[vagrant@adm ~]$ /usr/bin/ssh  _@10.0.2.2 -p 22 -o PubkeyAuthentication=no -t "dir" > /tmp/test
_@10.0.2.2's password:
Connection to 10.0.2.2 closed.
[vagrant@adm ~]$ less /tmp/test
```

**Expected output**
```
 Том в устройстве C не имеет метки.
 Серийный номер тома: 606B-DD98

 Содержимое папки C:\Users\_

15.12.2019  18:17    <DIR>          .
15.12.2019  18:17    <DIR>          ..
12.12.2019  12:29    <DIR>          .amethyst
11.11.2019  15:06    <DIR>          .cargo
18.08.2019  15:14    <DIR>          .cisco
11.11.2019  15:20    <DIR>          .config
12.12.2019  09:43               355 .gitconfig
13.07.2019  21:11    <DIR>          .oracle_jre_usage
03.10.2019  10:36    <DIR>          .Origin
16.12.2019  13:12    <DIR>          .pylint.d
03.10.2019  10:36    <DIR>          .QtWebEngineProcess
28.09.2019  23:08    <DIR>          .rustup
02.12.2019  09:53    <DIR>          .ssh
18.12.2019  12:07    <DIR>          .vagrant.d
18.12.2019  10:51    <DIR>          .VirtualBox
11.11.2019  11:56    <DIR>          .vscode
14.12.2019  17:04    <DIR>          3D Objects
13.07.2019  22:24    <DIR>          ansel
14.12.2019  17:04    <DIR>          Contacts
14.12.2019  17:04    <DIR>          Desktop
16.12.2019  12:28    <DIR>          Documents
14.12.2019  17:04    <DIR>          Downloads
17.12.2019  22:55    <DIR>          Favorites
13.07.2019  22:00    <DIR>          Intel
14.12.2019  17:04    <DIR>          Links
14.12.2019  17:04    <DIR>          Music
28.11.2019  17:47    <DIR>          OneDrive
16.12.2019  10:34    <DIR>          Pictures
14.12.2019  17:04    <DIR>          Saved Games
14.12.2019  17:04    <DIR>          Searches
14.12.2019  17:04    <DIR>          Videos
12.12.2019  13:13    <DIR>          VirtualBox VMs
               1 файлов            355 байт
              31 папок  14 773 170 176 байт свободно
```
**Actual output**

```
ESC[2JESC[?25lESC[mESC[H

<myriad of empty lines>
ESC[HESC]0;c:\windows\system32\cmd.exe^GESC[?25hESC[?25l Том в устройстве C не имеет метки.ESC[20XESC[20C
 Серийный номер тома: 606B-DD98ESC[24XESC[24C
ESC[55XESC[55C
 Содержимое папки C:\Users\_ESC[27XESC[27C
ESC[55XESC[55C
15.12.2019  18:17    <DIR>          .ESC[18XESC[18C
15.12.2019  18:17    <DIR>          ..ESC[17XESC[17C
12.12.2019  12:29    <DIR>          .amethystESC[10XESC[10C
11.11.2019  15:06    <DIR>          .cargoESC[13XESC[13C
18.08.2019  15:14    <DIR>          .ciscoESC[13XESC[13C
11.11.2019  15:20    <DIR>          .configESC[12XESC[12C
12.12.2019  09:43               355 .gitconfigESC[9XESC[9C
13.07.2019  21:11    <DIR>          .oracle_jre_usage
03.10.2019  10:36    <DIR>          .OriginESC[12XESC[12C
16.12.2019  13:12    <DIR>          .pylint.dESC[10XESC[10C
03.10.2019  10:36    <DIR>          .QtWebEngineProcess
28.09.2019  23:08    <DIR>          .rustupESC[12XESC[12C
02.12.2019  09:53    <DIR>          .sshESC[15XESC[15C
18.12.2019  12:07    <DIR>          .vagrant.dESC[9XESC[9C
18.12.2019  10:51    <DIR>          .VirtualBox
11.11.2019  11:56    <DIR>          .vscodeESC[12XESC[12C
14.12.2019  17:04    <DIR>          3D ObjectsESC[9XESC[9C
13.07.2019  22:24    <DIR>          anselESC[14XESC[14C
14.12.2019  17:04    <DIR>          ContactsESC[11XESC[11C
14.12.2019  17:04    <DIR>          DesktopESC[12XESC[12C
16.12.2019  12:28    <DIR>          DocumentsESC[10XESC[10C
14.12.2019  17:04    <DIR>          DownloadsESC[10XESC[10C
17.12.2019  22:55    <DIR>          FavoritesESC[10XESC[10C
13.07.2019  22:00    <DIR>          IntelESC[14XESC[14C
14.12.2019  17:04    <DIR>          LinksESC[14XESC[14C
14.12.2019  17:04    <DIR>          MusicESC[14XESC[14C
28.11.2019  17:47    <DIR>          OneDriveESC[11XESC[11C
16.12.2019  10:34    <DIR>          PicturesESC[11XESC[11C
14.12.2019  17:04    <DIR>          Saved Games
14.12.2019  17:04    <DIR>          SearchesESC[11XESC[11C
14.12.2019  17:04    <DIR>          VideosESC[13XESC[13C
12.12.2019  13:13    <DIR>          VirtualBox VMs
               1 файлов            355 байтESC[12XESC[12C
              31 папок  14 772 064 256 байт свободно
ESC[?25h
```

**Comment by DHowett-MSFT** [comment]
`-t` explicitly requests the allocation of a terminal, which the server uses to determine that the output will be going to a terminal. If you do not want a terminal to be allocated, drop the `-t` flag from your SSH invocation.

**Comment by mkpankov** [comment]
That's not what happens when connecting to a Linux OpenSSH server though.

There, even with `-t`, output doesn't have escapes when it shouldn't:

```
PS C:\Users\_\Documents\GitHub\Vagrantfiles> ssh -t adm "ls -la" > file
Connection to 127.0.0.1 closed.
PS C:\Users\_\Documents\GitHub\Vagrantfiles> cat file
total 36
drwx------. 6 vagrant vagrant   203 Dec 17 08:17 .
drwxr-xr-x. 3 root    root       21 Jun  1  2019 ..
-rw-------  1 vagrant vagrant 12944 Dec 24 09:04 .bash_history
-rw-r--r--. 1 vagrant vagrant    18 Oct 30  2018 .bash_logout
-rw-r--r--. 1 vagrant vagrant   193 Oct 30  2018 .bash_profile
-rw-r--r--. 1 vagrant vagrant   231 Oct 30  2018 .bashrc
-rw-r--r--  1 root    root        0 Nov 27 07:13 blockdevice_zfs.log
drwx------  3 vagrant vagrant    18 Nov 27 07:52 .config
-rw-------  1 vagrant vagrant    42 Dec 17 08:17 .lesshst
drwxrw----  3 vagrant vagrant    19 Dec 16 10:28 .pki
drwx------. 2 vagrant vagrant    48 Dec 16 07:53 .ssh
-rw-------  1 vagrant vagrant  3789 Dec 17 07:55 .viminfo
drwxrwxr-x  5 vagrant vagrant   100 Dec 16 10:28 .vscode-server
```

When using `ls -la` interactively, names of some folders are colored.

Then, `-t` is used by a program that wants to interact with remote shell. Interaction is via parsing prompt and sending commands, which breaks when output has unexpected escapes in it. Without `-t`, interaction won't be possible.

**Comment by mgkuhn** [comment]
First of all you need to upgrade to a newer OpenSSH and/or Windows version to enjoy ConPTY support. This means v7.9.0 or newer and Windows 10 1809 or newer. Before [ConPTY](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/), programs such as sshd couldn't see the stdout of any program and had to screen-scrape the text window.

**Comment by mkpankov** [comment]
@mgkuhn how would I do that, if I installed it as a Windows component?

My current Windows version is 18363, OpenSSH is still 7.7.

**Comment by mgkuhn** [comment]
I think you will find that installing a [current Github release](https://github.com/PowerShell/Win32-OpenSSH/releases) will be a huge improvement compared to 7.7 (just unzip into Program Files). I have no idea why Windows is still installing such an outdated version as a component, which causes people to raise many issues here that have been fixed in the Github releases over a year ago.

**Comment by mkpankov** [comment]
@mgkuhn thanks, I updated.

It didn't help with the issue at all, though.

**Comment by mgkuhn** [comment]
And you are sure you are actually talking to the new version sshd, i.e. "ssh -v host" really says " remote software version OpenSSH_7.9" or newer, and you haven't still accidentally the older 7.7 sshd running somewhere?
Full sshd installation instructions:
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by mkpankov** [comment]
Yes.

I actually needed to make a new service manually since I installed to user directory instead of Program files, and start that new service. I also checked the version with ssh itself.

**Comment by mgkuhn** [comment]
The underlying problem is probably that `cmd.exe` (and it's built-in command `dir`) is still a 30-year old application that uses ConsoleAPI to write into a VGA character matrix, rather than just outputting plaintext to a terminal emulator, and therefore `cmd.exe` does ConsoleAPI things such as clearing the screen and overwriting the rest of the line with space characters, and if you specify ssh option `-t` you are asking sshd to give you all that ancient ConsoleAPI cursor-control behavior. I suspect the ultimate solution is to rewrite `cmd.exe` to talk to a VT100 terminal in a way that doesn't require many ESC sequences (like a Unix shell does, now that Windows does have proper VT100 terminal emulation) rather than to a VGA text-mode character memory buffer. Windows is not Unix.

**Comment by maertendMSFT** [comment]
Please try this with the latest release, and make sure Windows is updated.
