### ISSUE TITLE
Update policy in Windows 10 / Windows Server

### ISSUE THREAD

**Issue by chrgraefe** [PowerShell/Win32-OpenSSH#1529]
We install OpenSSH.Server as a WindowsCapability.

Is this package (OpenSSH.Server~~~~0.0.1.0) updated within a release or only when the OS is upgraded?

**Comment by Stanzilla** [comment]
I was told on Twitter before that it is only updated on OS upgrades.

**Comment by gunnarhaslinger** [comment]
Not sure if you are asking about Feature-Updates of OpenSSH or Security/Quality-Updates.
I asked a similar question to yours - maybe this answers your question too. See [https://github.com/PowerShell/Win32-OpenSSH/issues/1500](https://github.com/PowerShell/Win32-OpenSSH/issues/1500)

**Comment by chrgraefe** [comment]
Thanks Gunnar/Danke Gunnar
