### ISSUE TITLE
When processing the command parameter, stderr output results in Packet Integrity Error

### ISSUE THREAD

**Issue by AndrewDeanMS** [PowerShell/Win32-OpenSSH#1530]
**"OpenSSH for Windows" version**
7.6.0.0
 
**Server OperatingSystem**
WIndows 10 Enterprise (ARM64)

**Client OperatingSystem**
Windows 10 Enterprise (x64)

**What is failing**
Given this program (RepeatErr):
```
#include <iostream>

int main(int argc, char** argv)
{
  for (int i = 1; i < argc; ++i)
  {
    std::cout << argv[i] << std::endl;
    std::cerr << argv[i] << std::endl;
  }
  return 0;
}
```

Invoke it this way (ssh running on windows, x64. sshd running on windows, ARM64):
```ssh -l <user> <ipAddress> "c:\Path\To\RepeatErr.exe 1 2 3"```

**Expected output**
```
1
2
3
1
2
3
```

**Actual output**
```
1
Packet integrity error (4 bytes remaining) at C:\\OpenSSH\\contrib\\win32\\openssh\\..\\..\\..\\channels.c:2916
Disconnecting <ipAddress> port 22: Packet integrity error.
```

**Notes**
I have tried this scenario where ssh is running on Windows x64 and sshd is running on Ubuntu x64 (WSL), and I received the expected output.

**Comment by bagajjal** [comment]
@AndrewDeanMS  - Please try the latest version 8.0.0.1

**Comment by AndrewDeanMS** [comment]
Tried the latest version, and this issue has been resolved.
