### ISSUE TITLE
Install-Module -Force OpenSSHUtils -Scope AllUsers

### ISSUE THREAD

**Issue by viponedream** [PowerShell/Win32-OpenSSH#1531]
WHEN I INSTALL by the course: https://docs.microsoft.com/zh-cn/windows-server/administration/openssh/openssh_keymanagement

Install-Module -Force OpenSSHUtils -Scope AllUsers

it says:

PackageManagement\Install-Package : 无法安装或更新模块“OpenSSHUtils”，因为文件“OpenSSHUtils.psd1”的验证码签名无效。
所在位置 C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 字符: 21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package]，E
    xception
    + FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.P
   ackageManagement.Cmdlets.InstallPackage

**Comment by maertendMSFT** [comment]
OpenSSHUtils is no longer required.  Remove that from the command.
