### ISSUE TITLE
ProxyCommand fails with same config as WSL

### ISSUE THREAD

**Issue by ahmadalli** [PowerShell/Win32-OpenSSH#1533]
**"OpenSSH for Windows" version**
7.7.2.1
 
**Server OperatingSystem**
Centos 6

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
ProxyCommand works fine on WSL (ubuntu 18.04) with the same server while it fails on windows

**Expected output**
established ssh connection

**Actual output**

```
channel 0: open failed: administratively prohibited: open failed
stdio forwarding failed
ssh_exchange_identification: Connection closed by remote host
```

**Configs**

on wsl:

```
Host jump
   HostName jupmer.io
   User root

Host *.jump
  User root
  ProxyCommand ssh jump -W %h:%p

Host dest.jump
  HostName 192.168.10.10
```

on windows:

```
Host jump
   HostName jupmer.io
   User root

Host *.jump
  User root
  ProxyCommand ssh.exe jump -W %h:%p

Host dest.jump
  HostName 192.168.10.10
```

**Comment by Domain** [comment]
You must specify the full path of ssh.exe, or update to new version, such as v8.1.

**Comment by ahmadalli** [comment]
@Domain I've tried full address too. also how can I update to new version?

**Comment by ahmadalli** [comment]
I've tried full address and it worked
