### ISSUE TITLE
posix-rename@openssh.com is not atomic

### ISSUE THREAD

**Issue by rtollert** [PowerShell/Win32-OpenSSH#1534]
[Presently](https://github.com/PowerShell/openssh-portable/blob/v8.1.0.0/contrib/win32/win32compat/misc.c#L735), `w32_rename()` is implemented by a `_wunlink()` or `_wrmdir()` (if necessary) followed by `_wrename`. This is a problem, because it breaks POSIX's atomicity requirements on `rename()`. More specifically, 
- `posix-rename@openssh.com` [is explicitly defined](https://github.com/PowerShell/openssh-portable/blob/v8.1.0.0/PROTOCOL#L380) to do precisely what is specified by POSIX `rename()`.
- The implementation of `posix-rename@openssh.com` [just calls `rename()`](https://github.com/PowerShell/openssh-portable/blob/v8.1.0.0/sftp-server.c#L1317) ([which is aliased to `w32_rename()`](https://github.com/PowerShell/openssh-portable/blob/v8.1.0.0/contrib/win32/win32compat/inc/stdio.h#L21))
- [POSIX rename is explicitly atomic](https://pubs.opengroup.org/onlinepubs/009695399/functions/rename.html#tag_03_608_08).

[The internets informs me](https://stackoverflow.com/a/2368286) that [`ReplaceFile()`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-replacefilew) might make fixing this not-quite-impossible, although y'all may know better than I do (or they do).

**Comment by NoMoreFood** [comment]
Does this have any known or theoretical consequence for the execution of OpenSSH, specifically?

**Comment by rtollert** [comment]
AFAIK: Yes, if connecting to sftp, and attempting to use posix-rename@openssh.com to effect rename-to-overwrite.

**Comment by DHowett-MSFT** [comment]
Recommend implementation using `MoveFileExW` with flag `MOVEFILE_REPLACE_EXISTING`. If moving across volumes, `MOVEFILE_COPY_ALLOWED` will be required as well.

**Comment by DHowett-MSFT** [comment]
Ah, I missed the callout to `ReplaceFile`. That is also an excellent choice.

**Comment by mgkuhn** [comment]
@NoMoreFood Users of [SSHFS](https://en.wikipedia.org/wiki/SSHFS) may expect proper POSIX file-system semantics, and being able to atomically replace one file with another is immensely valuable, for example when updating a web site consisting of static HTML files (to make sure site readers do not see a missing or half-written file during the replacement). Also, several editors and version-control systems depend on the atomic replacement semantics of a POSIX rename to deal gracefully with failure situations such as full disks, so implementing this properly may help to avoid a lot of race conditions there as well.

**Comment by mgkuhn** [comment]
@rtollert: following the merge of PowerShell/openssh-portable#438 can you close this issue?

**Comment by rtollert** [comment]
Yup! Apologies for the delay.
