### ISSUE TITLE
sftp-server advertises fstatvfs@openssh.com even though it is not supported

### ISSUE THREAD

**Issue by rtollert** [PowerShell/Win32-OpenSSH#1535]
[fstatvfs is not (currently) implemented](https://github.com/PowerShell/openssh-portable/blob/2c2ac97333f33bdb39dc875d4ef0c7b7fdb8e323/contrib/win32/win32compat/misc.c#L1185) on win32, but [it's still advertised in SSH_FXP_INIT](https://github.com/PowerShell/openssh-portable/blob/2c2ac97333f33bdb39dc875d4ef0c7b7fdb8e323/sftp-server.c#L666). I'd be OK with simply not advertising this as a supported extension.

**Comment by bagajjal** [comment]
@rtollert - Thanks for reporting. This will be fixed in next release.

**Comment by WSLUser** [comment]
I'd prefer it to be implemented over ignoring it if possible. The more openssh features we have on Windows, the better.
