### ISSUE TITLE
How can I use the latest cipher suites in openssh for windows

### ISSUE THREAD

**Issue by Acenl12** [PowerShell/Win32-OpenSSH#1536]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps
#Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
#MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
#KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1

in sshd_config
How can I use the latest cipher suites in openssh for windows

**Server OperatingSystem**
Windows Server 2019

**Comment by bagajjal** [comment]
https://www.freebsd.org/cgi/man.cgi?sshd_config(5)

Use "Ciphers" in the sshd_config.

**Comment by Acenl12** [comment]
That's what I did, didn't work

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bagajjal** [comment]
once you change the sshd_config, you need to restart the sshd service (net stop sshd; net start sshd). 
If you still have problem then share you sshd_config and sshd.log with DEBUG3 enabled.

**Comment by Acenl12** [comment]
Did a, restart

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bagajjal** [comment]
So, are you still facing the issue? 
Please provide the full details.

**Comment by bagajjal** [comment]
Also provide the ssh client log (ssh -vvv user@ip)

**Comment by Acenl12** [comment]
When I put in these ciphers, the sshd service won't even start:
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1

This is my sshd_config
# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

Port 22
AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

HostKey __PROGRAMDATA__/ssh/ssh_host_rsa_key
HostKey __PROGRAMDATA__/ssh/ssh_host_dsa_key
HostKey __PROGRAMDATA__/ssh/ssh_host_ecdsa_key
HostKey __PROGRAMDATA__/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
StrictModes no
#MaxAuthTries 6
#MaxSessions 10

PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile .ssh/authorized_keys

#AuthorizedPrincipalsFile none

# For this to work you will also need host keys in %programData%/ssh/ssh_known_hosts
HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
PasswordAuthentication no
PermitEmptyPasswords no

# GSSAPI options
#GSSAPIAuthentication no

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#PermitUserEnvironment no
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# override default of no subsystems
Subsystem sftp sftp-server.exe

# Example of overriding settings on a per-user basis
#Match User anoncvs
# AllowTcpForwarding no
# PermitTTY no
# ForceCommand cvs server

Match Group administrators
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys

AllowGroups administrators

Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1

________________________________
Van: bagajjal <notifications@github.com>
Verzonden: vrijdag 10 januari 2020 19:09
Aan: PowerShell/Win32-OpenSSH <Win32-OpenSSH@noreply.github.com>
CC: guidovbrakel <guido.vanbrakel@outlook.com>; Author <author@noreply.github.com>
Onderwerp: Re: [PowerShell/Win32-OpenSSH] Make OpenSSH for Windows (#1536)


https://www.freebsd.org/cgi/man.cgi?sshd_config(5)

Use "Ciphers" in the sshd_config.

**Comment by Acenl12** [comment]
ssh -vvvv shows this
C:\Users\Administrator>ssh -vvvv localhost
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug3: Failed to open file:C:/Users/Administrator/.ssh/config error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolving "localhost" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to localhost [::1] port 22.
debug3: finish_connect - ERROR: async io completed with error: 10061, io:000001635C26FC80
debug1: connect to address ::1 port 22: Connection refused
debug1: Connecting to localhost [127.0.0.1] port 22.
debug3: finish_connect - ERROR: async io completed with error: 10061, io:000001635C26FC80
debug1: connect to address 127.0.0.1 port 22: Connection refused
ssh: connect to host localhost port 22: Connection refused

________________________________
Van: Guido van Brakel <guido.vanbrakel@outlook.com>
Verzonden: maandag 13 januari 2020 09:31
Aan: PowerShell/Win32-OpenSSH <Win32-OpenSSH@noreply.github.com>; PowerShell/Win32-OpenSSH <reply@reply.github.com>
CC: Author <author@noreply.github.com>
Onderwerp: Re: [PowerShell/Win32-OpenSSH] Make OpenSSH for Windows (#1536)

When I put in these ciphers, the sshd service won't even start:
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1

This is my sshd_config
# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

Port 22
AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

HostKey __PROGRAMDATA__/ssh/ssh_host_rsa_key
HostKey __PROGRAMDATA__/ssh/ssh_host_dsa_key
HostKey __PROGRAMDATA__/ssh/ssh_host_ecdsa_key
HostKey __PROGRAMDATA__/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
StrictModes no
#MaxAuthTries 6
#MaxSessions 10

PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile .ssh/authorized_keys

#AuthorizedPrincipalsFile none

# For this to work you will also need host keys in %programData%/ssh/ssh_known_hosts
HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
PasswordAuthentication no
PermitEmptyPasswords no

# GSSAPI options
#GSSAPIAuthentication no

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#PermitUserEnvironment no
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# override default of no subsystems
Subsystem sftp sftp-server.exe

# Example of overriding settings on a per-user basis
#Match User anoncvs
# AllowTcpForwarding no
# PermitTTY no
# ForceCommand cvs server

Match Group administrators
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys

AllowGroups administrators

Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1

________________________________
Van: bagajjal <notifications@github.com>
Verzonden: vrijdag 10 januari 2020 19:09
Aan: PowerShell/Win32-OpenSSH <Win32-OpenSSH@noreply.github.com>
CC: guidovbrakel <guido.vanbrakel@outlook.com>; Author <author@noreply.github.com>
Onderwerp: Re: [PowerShell/Win32-OpenSSH] Make OpenSSH for Windows (#1536)


https://www.freebsd.org/cgi/man.cgi?sshd_config(5)

Use "Ciphers" in the sshd_config.

**Comment by WSLUser** [comment]
I'd hate to be the bearer of bad news but that sshd config also doesn't work on Linux. I had attempted to harden one of our CentOS hosts ssh config and summarily broke access to it (I will note I did not add the chacha as the version of CentOS I'm running doesn't support it) (fortunately had a snapshot taken just before the change). So it's most likely an upstream issue. 

That said, if we can get it resolved on Windows, we could take that patch and push it upstream so everyone can benefit.

**Comment by Acenl12** [comment]
It does work on Ubuntu, we have it on 2000 Ubuntu servers

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Acenl12** [comment]
Is there any update on this, I really would like to be able to use the latest cipher suites in OpenSSH for Windows.

**Comment by EwertonJordao** [comment]
I have the same issue. I try to set Cipher for compatibility with IBM mainframe my client not be able to connect on SFTP

```
# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

HostKey __PROGRAMDATA__/ssh/ssh_host_rsa_key
# HostKey __PROGRAMDATA__/ssh/ssh_host_dsa_key
# HostKey __PROGRAMDATA__/ssh/ssh_host_ecdsa_key
HostKey __PROGRAMDATA__/ssh/ssh_host_ed25519_key


# Ciphers and keying
# RekeyLimit default none
# Restrict key exchange, cipher, and MAC algorithms, as per sshaudit.com
# hardening guide
Ciphers aes128-ctr, aes192-ctr, aes256-ctr, twofish192-ctr, twofish256-ctr
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
```

If I restart sshd service I receive an error :
![image](https://user-images.githubusercontent.com/12378570/98301734-07ba3300-1f9a-11eb-81b5-2368b1e0cb74.png)

![image](https://user-images.githubusercontent.com/12378570/98301810-21f41100-1f9a-11eb-9852-5c6a62451330.png)

**Comment by Adam1986** [comment]
Has a resolution ever been found for this? Got the same issue as detailed above.

**Comment by bagajjal** [comment]
@Adam1986  - What is failing for you? Please open a new issue if it's supported by upstream openssh but not by win32-openssh.

@guidovbrakel - ripemd160 is removed by upstream openssh. Here is the [code commit](https://github.com/openssh/openssh-portable/commit/7bdb2eeb1d3c26acdc409bd94532eefa252e440b).

@EwertonJordao - Upstream openssh doesn't support ciphers "twofish192-ctr, twofish256-ctr".
![image](https://user-images.githubusercontent.com/23668037/114625071-8eb8b900-9c66-11eb-8938-182a54192f7b.png)
