### ISSUE TITLE
Show server name when connecting

### ISSUE THREAD

**Issue by Acenl12** [PowerShell/Win32-OpenSSH#1537]
How can I show the server name when connecting to an machine with OpenSSH for Windows in the terminal?

**Comment by mgkuhn** [comment]
Does typing `hostname` not solve your problem? [Other options exists ...](https://www.windows-commandline.com/find-computer-name-from-command-line/)
This doesn't sound like an ssh-related question, more like a command-shell related one.

**Comment by mgkuhn** [comment]
Try e.g. `ssh machine.contoso.com "hostname&&cmd"`

**Comment by Acenl12** [comment]
I already found another solution, making powershell the default shell and then changing the powershell profile.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mgkuhn** [comment]
Could you please close this issue if you have found a solution?
