### ISSUE TITLE
Setting Powershell as the default shell through the registry causes Powershell to be run as Administrator

### ISSUE THREAD

**Issue by DwightGappa** [PowerShell/Win32-OpenSSH#1539]
Please answer the following

**"OpenSSH for Windows" version**
7.7.2.2
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
When connecting to target Windows 10 Pro through SSH that has Powershell set as the default shell by setting the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH\DefaultShell" to the value "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"(https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration#configuring-the-default-shell-for-openssh-in-windows) starts Powershell as an Administrator. 

It displays "Administrator: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" when connecting from through the Windows 10 command window (CMD.EXE and Powershell.exe).

Confirmed that the SSH Powershell shell has admin rights with the following command.

([Security.Principal.WindowsPrincipal] `
>>   [Security.Principal.WindowsIdentity]::GetCurrent() `
>> ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

The breaks with the expected start context as a normal user then elevate to administrator i.e. sudo on bash

**Expected output**
([Security.Principal.WindowsPrincipal] `
>>   [Security.Principal.WindowsIdentity]::GetCurrent() `
>> ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
False

**Actual output**
([Security.Principal.WindowsPrincipal] `
>>   [Security.Principal.WindowsIdentity]::GetCurrent() `
>> ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
True

**Comment by DwightGappa** [comment]
Any shell set as default will run as Administrator rights. Just verified that the normal cmd.exe run as Administrator through OpenSSH

**Comment by maertendMSFT** [comment]
Default network logon sessions will be elevated session.  If you are an admin, it will be elevated session.  If you are connecting as a non-admin user, you will not have admin privileges.
