### ISSUE TITLE
Can't log in with public key--bad diagnostic "bad owner on .ssh/authorized_keys"

### ISSUE THREAD

**Issue by jhudsoncedaron** [PowerShell/Win32-OpenSSH#1542]
**"OpenSSH for Windows" version** 7.7.2.2
 
**Server OperatingSystem** Server Core: Microsoft Windows [Version 10.0.18362.592]

**Client OperatingSystem** Windows 10 and Debian

**What is failing** Can't log in with public keys

debug3: mm_answer_keyallowed entering
debug3: mm_answer_keyallowed: key_from_blob: 000001622C55A280
debug1: trying public key file C:\\Users\\InterfaceVM01\\.ssh/authorized_keys
debug3: Bad owner on C:/Users/InterfaceVM01/.ssh/authorized_keys
Authentication refused.
debug3: mm_answer_keyallowed: publickey authentication test: RSA key is not allowed
Failed publickey for interfacevm01\\interfacevm01 from 12.139.157.2 port 42754 ssh2: RSA SHA256:8O+NS/1wEgwLypJlsoV8j7rFxwlSl61kn+SVjuQFP+0
debug3: mm_request_send entering: type 23
debug2: userauth_pubkey: authenticated 0 pkalg rsa-sha2-512 [preauth]
debug3: userauth_finish: failure partial=0 next methods="publickey" [preauth]
debug3: send packet: type 51 [preauth]
Connection closed by authenticating user interfacevm01\\\\interfacevm01 12.139.157.2 port 42754 [preauth]

The problem is "Bad owner on C:/Users/InterfaceVM01/.ssh/authorized_keys" So what's the problem? The diagnostic is just wrong:

C:\Users\InterfaceVM01\.ssh>powershell GET-ACL authorized_keys "|" select Owner

Owner
-----
InterfaceVM01\InterfaceVM01

(yes the username is the same as the hostname)

icacls:

C:\Users\InterfaceVM01\.ssh>icacls authorized_keys
authorized_keys NT AUTHORITY\SYSTEM:(F)
                NT AUTHORITY\SYSTEM:(I)(F)
                BUILTIN\Administrators:(I)(F)
                InterfaceVM01\InterfaceVM01:(I)(F)

Successfully processed 1 files; Failed processing 0 files

**Comment by bagajjal** [comment]
@jhudsoncedaron - Please use V8.1.0.0. It should be fixed.

**Comment by jhudsoncedaron** [comment]
@bagajjal : I'll be back tomorrow. Got upgrade instructions. Currently sshd installed by dism.

**Comment by jhudsoncedaron** [comment]
Ok so I unpacked the zip file to C:\OpenSSH-Win64-8.1.0p1-Beta, changed the service binary paths in regedit to match, changed the sftp-subsystem line in C:\ProgramData\ssh to match, and tried it.

Results:

Can log in interactively while running `ssh -dddd` on the server, but if I try via the ssh service I get stuck at 

debug1: Authentication succeeded (publickey).
Authenticated to interface01.<redacted>
debug1: channel 0: new [client-session]
debug2: channel 0: send session
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session
debug1: pledge: network
<<long pause>>
packet_write_wait: Connection to <redacted> port <redacted>: Broken Pipe

Trying to log in with psftp doesn't work at all. If I try it with `sshd -dddd` I get:

Server listening on 0.0.0.0 port 5022.
debug3: fd 5 is not O_NONBLOCK
debug1: Server will not fork when running in debugging mode.
debug3: send_rexec_state: entering fd = 8 config len 312
debug3: ssh_msg_send: type 0
debug3: send_rexec_state: done
Connection from 12.139.157.2 port 62012 on 10.1.10.7 port <redacted>
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
kex_exchange_identification: banner line contains invalid characters

The psftp client is working and can connect to Linux servers.

I guessed that maybe I had not done enough of the repointing and so ran `install-sshd.ps` from C:\OpenSSH-Win64-8.1.0p1-Beta. No change.

I think the beta is just busted.

**Comment by WSLUser** [comment]
What you should of done is stop the sshd service. Then delete the Openssh-Win32 directory. Replace it with a fresh extract. Open PS and run the install script. Then run the user and file permission scripts. Lastly start the sshd service. This should work as long as they are all run in elevated mode.

**Comment by bagajjal** [comment]
Please make sure the ssh binary folder has read and execute permissions to "Users" local account on the machine and all the child items will inherit this.

**Comment by jhudsoncedaron** [comment]
I'm not going to continue to pursue this. I only waited a day before disabling the builtin copy and deploying Cygwin's copy and moving the server into production.

Since it probably is fixed and the next dism-series release will not see the bug, I'm punching close now.
