### ISSUE TITLE
Why is there no separate installation script for ssh-agent?

### ISSUE THREAD

**Issue by jmyreen** [PowerShell/Win32-OpenSSH#1547]
**"OpenSSH for Windows" version**
 8.1.0.0p1 Beta

**Client OperatingSystem**
Windows 10 Enterprise

I downloaded OpenSSH 8.1.0.0 from Github and couldn't find information on how to install ssh-agent. After much searching I realized that the `install-sshd.ps1` script contains hidden in it the commands to also install `ssh-agent` as a service (`New-Service -Name ssh-agent...`)

`ssh-agent` is (mainly) a helper program for the SSH client. It makes no sense to me that you would have to install the SSH server to just install `ssh-agent`.

**Comment by GjBrutello** [comment]
lol, just write: sc config ssh-agent start= auto
or before install add  $agentDesc -StartupType Automatic  to install-sshd.ps1

**Comment by jmyreen** [comment]
@GjBrutello lol, you can't start or change the state of a service that is not installed.

To your second suggestion: my request was for a separate installation script for ssh-agent. Ssh-agent is usually used on the client side. I don't want to install sshd on my laptop, but ssh-agent is very useful.

**Comment by maertendMSFT** [comment]
Majority of users required the agent and the service.  If you do not need one, then after installing modify the installation script.
