### ISSUE TITLE
How do we contribute?

### ISSUE THREAD

**Issue by riverar** [PowerShell/Win32-OpenSSH#1549]
I'm trying to find the active codebase to pull down, compile, and contribute. But I'm stuck in a maze of non-standard branch names and a loop of repository links. For example this repository links to https://github.com/powershell/Win32-OpenSSH, which links back to this one. `L1` and `master` seem outdated. Should we refer to the forked `latestw_all`?

This is a huge mess.

cc: @jeffwilcox

**Comment by NoMoreFood** [comment]
In terms of the actual code (not the documentation), use latestw_all in https://github.com/powershell/openssh-portable.  That what I've used for all my pull requests.  

Possible it's a huge mess but then again possible you (and I) just don't understand the history there.
