### ISSUE TITLE
sftp always logs with the level DEBUG3

### ISSUE THREAD

**Issue by wl2776** [PowerShell/Win32-OpenSSH#155]
SFTP subsystem creates file sftp-server.log and uses DEBUG3 log level regardless of settings in sshd_config

**Comment by wl2776** [comment]
This code sets it: https://github.com/PowerShell/Win32-OpenSSH/blob/L1/sftp-server.c#L2040

**Comment by manojampalam** [comment]
Thanks for finding this. If this is the case, with the new update, you'll observe that the log bloats pretty quickly (transport Debug3 are very verbose). Please keep deleting it often. I'll work on a fix and try to get an update next week.

**Comment by manojampalam** [comment]
Fixed in latest release
