### ISSUE TITLE
Very Slow DNS Lookups

### ISSUE THREAD

**Issue by bin** [PowerShell/Win32-OpenSSH#1553]
**"OpenSSH for Windows" version**
 8.1.0.0
 
**Server OperatingSystem**
Alpine Linux 3.11, Ubuntu 18.04.4 LTS

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
DNS Lookups for hostnames are very slow (15-20 seconds).  IP addresses have no such issue, and running with `-vvv` shows that it is stalling on the address resolution step.  The same hostname resolves fine in other applications.  Cloudflare is the DNS provider for the client system and administers the nameservers for the domain.  I've tested this with two such domains, one that resolves through a CNAME record to a LAN IPv4 and another that resolves through an A record to a public IPv4.  Both have the same issue.  I am using RSA private key authentication with a password-protected keyfile, and have checked permissions on all key files and config files.  I have tried with and without ssh-agent.  I've tried connecting with putty and it had no issues resolving the domains in a timely manner.  Nslookup resolved them quickly, too.  There's no IPv6 involved, and I made sure it wasn't attempting a v6 lookup by passing -4.  No change to behavior.  It's also of note that while hanging at domain resolution, control-C doesn't abort the program as I'd expect, but just hangs.  Other inputs (e.g. newlines) don't get processed either; they'll show up in a burst as soon as resolution finishes.  I have to manually kill the program to stop it during this step.

**Expected output**
The supplied domain should resolve at a speed typical of DNS queries (a fraction of a second).  

**Actual output**
Domains take 15-20 seconds to resolve.

**Comment by NoMoreFood** [comment]
OpenSSH does not do custom DNS lookups or searches -- it defers to the operating system using standard functions.  You likely have some systemic issue with your environment that needs to be addressed.

**Comment by SR-Lut3t1um** [comment]
@bin I had the same problem but later realized I setup a IPv6 address in my DNS but not on my server.
Maybe you have a similar problem, like the openssh server is not listening on IPv6. I guess this is caused by the client who tries IPv4 after v6 fails.
