### ISSUE TITLE
Change of Port 22 to another port does not work

### ISSUE THREAD

**Issue by hornyd** [PowerShell/Win32-OpenSSH#1555]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 v8.1.0.0p1-Beta 

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 Pro

**Client OperatingSystem**

**What is failing**
Changing port 22 in the sshd.config file included

**Expected output**
new port to be listened

**Actual output**
Still port 22

I have placed the current version into folder and run the install script and also disable the firwall as prelimary test.
I like to have another port than 22 because the PC is behind linux system already using port 22 so the users can make the difference
Changeing in the config port 22, restart the service or the PC, still port 22 is listened.

**Comment by hornyd** [comment]
Do the sshd_config_default how must it be and how to call it?

**Comment by bagajjal** [comment]
You need to modify $env:ProgramData\ssh\sshd_config file. Don't modify sshd_config_default.
Any changes to sshd_config requires the sshd restart (net stop sshd; net start sshd).

**Comment by hornyd** [comment]
Ah ok, thank you for the quick reply. Will try

**Comment by bagajjal** [comment]
Closing the issue as we didn't hear back. Let me know if you still have an issue.
