### ISSUE TITLE
ssh-keygen uses incorrect slash

### ISSUE THREAD

**Issue by welnanick** [PowerShell/Win32-OpenSSH#156]
I know this is nothing major, but I noticed it and thought I'd bring it up just in case. When using ssh-keygen to generate an ssh key it uses the wrong slashes in part of the address to the file I want to save it in:

```
C:\Users\nwelna\Documents>ssh-keygen -t rsa -b 4096 -C "*my email*"

Generating public/private rsa key pair.
Enter file in which to save the key (C:\Users\nwelna/.ssh/id_rsa):
```

As you can see, the first two slashes are correct ( \ ) when the second two are incorrect ( / ). I'm running this through cmd.exe.

It doesn't break anything, it was just an inconsistency I saw.

**Comment by benkevan** [comment]
This is duplicated.. it obviously works and you can cd to the directly as you'd expect. This would just need to be cleaned up in pathnames.h if it were decided to "look" like typical Windows slashes.

**Comment by manojampalam** [comment]
dup #469

**Comment by manojampalam** [comment]
Leave a comment
