### ISSUE TITLE
Not Able to Run "ssh" Command from PowerShell (works fine from command prompt)

### ISSUE THREAD

**Issue by iandonnelly** [PowerShell/Win32-OpenSSH#1566]
**"OpenSSH for Windows" version**
OpenSSH_for_Windows_7.7p1,
 
**Server OperatingSystem**
CentOS

**Client OperatingSystem**
Windows 10 Home ARM (on Surface Pro X)

**What is failing**
Running the ssh command from powershell. It works from command prompt. Even C:\Windows\System32\OpenSSH\ssh.exe fails

**Steps Taken**
I tried removing OpenSSH and then enabling it again (through Settings->Addd&Remove as well as the powershell command)
I tried a reboot
I also tried a full reset of my PC then enabling OpenSSH (same behavior)

**Expected output**
ssh.exe should run

**Actual output**
```
> ssh
ssh : The term 'ssh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
```
```
> C:\Windows\System32\OpenSSH\ssh.exe
C:\Windows\System32\OpenSSH\ssh.exe : The term 'C:\Windows\System32\OpenSSH\ssh.exe' is not recognized as the name of
a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,        verify that the path is correct and try again.
```

**Comment by DHowett-MSFT** [comment]
This is because PowerShell on ARM64 is actually the x86 powershell, so it is subject to system file redirection.

Try `c:\windows\sysnative\openssh\ssh.exe`. I know it looks like the sysnative folder doesn’t exist in explorer or CMD, but it will work from powershell.

It would be better for you to move to PowerShel Core, as it has a native ARM64 version.

**Comment by iandonnelly** [comment]
@DHowett-MSFT I will try that later today. Is it possible to setup PowerShell Core to be the default terminal for VS Code? That's where I really need ssh to be working.

Also any possibility of documenting this on the [Installation of OpenSSH for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse) page. I see a note on the [WSL2 ](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#troubleshooting) page.

If it works on PowerShell Core should I close this or is it still a valid issue?

**Comment by WSLUser** [comment]
PS 5.1 is not being worked on so yes this issue can technically be closed. PS7 should be able to satisfy most of your itches if not all including ssh.

**Comment by iandonnelly** [comment]
@WSLUser @DHowett-MSFT 
Installing powershell core on Windows ARM builds isn't well documented but since this works from wsl and cmd.exe I'm fine closing this. Still think it should be documented in the Installation of OpenSSH for Windows page.

**Comment by davide-rota** [comment]
> @WSLUser @DHowett-MSFT
> Installing powershell core on Windows ARM builds isn't well documented but since this works from wsl and cmd.exe I'm fine closing this. Still think it should be documented in the Installation of OpenSSH for Windows page.

Agree, Powershell Core (ARM) is well hidden (only zip package, dotnet tool will install x86 32bit even on ARM systems). Including "c:\windows\sysnative\openssh" in the path when installing openssh on Win10 ARM might be a better option.

**Comment by DHowett-MSFT** [comment]
Minor complication there, unfortunately. `sysnative` is actually an _invalid_ path for anything running outside of emulation. It's really strange. :smile:

**Comment by WSLUser** [comment]
Perhaps you could file an internal bug for them to fix that. `sysnative` should work in either case. Or documentation should show why exactly they can't allow use of `sysnative` on ARM.

**Comment by DHowett-MSFT** [comment]
This will probably never be fixed, but it _is_ documented [here](https://docs.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector).

> Note that 64-bit applications cannot use the Sysnative alias as it is a virtual directory not a real one.
