### ISSUE TITLE
Question about Admin Access over SSh

### ISSUE THREAD

**Issue by jasonkuehl** [PowerShell/Win32-OpenSSH#157]
In linux I’m able to use a sudo command to execute commands that need higher privileges. How can I do this in windows? I’m able to login with my local user but I'm unable to gain access to the administrator account.

**Comment by vors** [comment]
This may work

```
runas.exe /savecred /user:administrator <command>
```

From
http://stackoverflow.com/questions/8249705/how-to-run-an-application-as-run-as-administrator-from-the-command-prompt

Note that you need to replace `administrator` by the real administrator name on the machine.

**Comment by jasonkuehl** [comment]
Yep, that hit the nail on the head. Thank you.

**Comment by manojampalam** [comment]
With the latest version from 3_19, the remote session should be admin-capable. You may need to flip this bit though - https://support.microsoft.com/en-us/kb/942817

**Comment by manojampalam** [comment]
Feel free to reopen if needed.
