### ISSUE TITLE
ssh running under local system account does not use ssh-agent

### ISSUE THREAD

**Issue by kurtbeil01** [PowerShell/Win32-OpenSSH#1570]
**"OpenSSH for Windows" version**
 Win64-OpenSSH 8.1.0.0
 
**Server OperatingSystem**
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 4

**Client OperatingSystem**
Windows Server 2016 Standard

**What is failing**
Need to run ssh as scheduled job and therfore used NT AUTHORITY\SYSTEM account.

Therefore we created the keys with ssh-keygen on client side. Public key was installed on server. Private key was added to ssh-agent using ssh-add command. After that we removed private/public vom .ssh folder.

Checked everything from cmd command prompt with local user and admin user. Everthing was working like expected. ssh connected to server and executed commands without asking for password or key files. So it's using the keys stored in ssh-agent.

**Expected output**
Here the debug output from the command using admin user. All user, ip, key data were removed!

As you can see at the debug1: Will attempt key section, there are currently two key in ssh-agent available, which will be used. You can also see some lines after that, that the second key (yyyyyyyyyyyyyyyyyyyyyyyy) was accepted by the server. So the ls -l command was executed.

ssh -vvv <user>@xx.xx.xx.xx ls -l
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
debug3: Failed to open file:C:/Users/<user>/.ssh/config error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolve_canonicalize: hostname xx.xx.xx.xx is address
debug2: ssh_connect_direct
debug1: Connecting to xx.xx.xx.xx [xx.xx.xx.xx] port 22.
debug1: Connection established.
debug3: Failed to open file:C:/Users/<user>/.ssh/id_rsa error:2
debug3: Failed to open file:C:/Users/<user>/.ssh/id_rsa.pub error:2
debug1: identity file C:\\Users\\<user>/.ssh/id_rsa type -1
debug3: Failed to open file:C:/Users/<user>/.ssh/id_rsa-cert error:2
debug3: Failed to open file:C:/Users/<user>/.ssh/id_rsa-cert.pub error:2
debug1: identity file C:\\Users\\<user>/.ssh/id_rsa-cert type -1
debug3: Failed to open file:C:/Users/<user>/.ssh/id_dsa error:2
debug3: Failed to open file:C:/Users/<user>/.ssh/id_dsa.pub error:2
debug1: identity file C:\\Users\\<user>/.ssh/id_dsa type -1
debug3: Failed to open file:C:/Users/<user>/.ssh/id_dsa-cert error:2
debug3: Failed to open file:C:/Users/<user>/.ssh/id_dsa-cert.pub error:2
debug1: identity file C:\\Users\\<user>/.ssh/id_dsa-cert type -1
debug3: Failed to open file:C:/Users/<user>/.ssh/id_ecdsa error:2
debug3: Failed to open file:C:/Users/<user>/.ssh/id_ecdsa.pub error:2
debug1: identity file C:\\Users\\<user>/.ssh/id_ecdsa type -1
debug3: Failed to open file:C:/Users/<user>/.ssh/id_ecdsa-cert error:2
debug3: Failed to open file:C:/Users/<user>/.ssh/id_ecdsa-cert.pub error:2
debug1: identity file C:\\Users\\<user>/.ssh/id_ecdsa-cert type -1
debug3: Failed to open file:C:/Users/<user>/.ssh/id_ed25519 error:2
debug3: Failed to open file:C:/Users/<user>/.ssh/id_ed25519.pub error:2
debug1: identity file C:\\Users\\<user>/.ssh/id_ed25519 type -1
debug3: Failed to open file:C:/Users/<user>/.ssh/id_ed25519-cert error:2
debug3: Failed to open file:C:/Users/<user>/.ssh/id_ed25519-cert.pub error:2
debug1: identity file C:\\Users\\<user>/.ssh/id_ed25519-cert type -1
debug3: Failed to open file:C:/Users/<user>/.ssh/id_xmss error:2
debug3: Failed to open file:C:/Users/<user>/.ssh/id_xmss.pub error:2
debug1: identity file C:\\Users\\<user>/.ssh/id_xmss type -1
debug3: Failed to open file:C:/Users/<user>/.ssh/id_xmss-cert error:2
debug3: Failed to open file:C:/Users/<user>/.ssh/id_xmss-cert.pub error:2
debug1: identity file C:\\Users\\<user>/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
debug1: Remote protocol version 2.0, remote software version DCX_SSH_19.09.01
debug1: no match: DCX_SSH_19.09.01
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to xx.xx.xx.xx:22 as '<user>'
debug3: hostkeys_foreach: reading file "C:\\Users\\<user>/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file C:\\Users\\<user>/.ssh/known_hosts:2
debug3: load_hostkeys: loaded 1 keys from xx.xx.xx.xx
debug3: Failed to open file:C:/Users/<user>/.ssh/known_hosts2 error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug3: order_hostkeyalgs: prefer hostkeyalgs: rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ssh-rsa SHA256:qx6lFrmArxOJx3sHZejClYSE1uytjgj56jPxNNGb6eQ
debug3: hostkeys_foreach: reading file "C:\\Users\\<user>/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file C:\\Users\\<user>/.ssh/known_hosts:2
debug3: load_hostkeys: loaded 1 keys from xx.xx.xx.xx
debug3: Failed to open file:C:/Users/<user>/.ssh/known_hosts2 error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug1: Host 'xx.xx.xx.xx' is known and matches the RSA host key.
debug1: Found key in C:\\Users\\<user>/.ssh/known_hosts:2
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: <domain>\\<user>@<servername> RSA SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx agent
debug1: Will attempt key: <user> <user>@email.com RSA SHA256:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy agent
debug1: Will attempt key: C:\\Users\\<user>/.ssh/id_rsa
debug1: Will attempt key: C:\\Users\\<user>/.ssh/id_dsa
debug1: Will attempt key: C:\\Users\\<user>/.ssh/id_ecdsa
debug1: Will attempt key: C:\\Users\\<user>/.ssh/id_ed25519
debug1: Will attempt key: C:\\Users\\<user>/.ssh/id_xmss
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering public key: emea\\<user>@<servername> RSA SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx agent
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey
debug1: Offering public key: <user> <user>@email.com RSA SHA256:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy agent
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: <user> <user>@email.com RSA SHA256:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy agent
debug3: sign_and_send_pubkey: RSA SHA256:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
debug3: sign_and_send_pubkey: signing using rsa-sha2-512
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
Authenticated to xx.xx.xx.xx ([xx.xx.xx.xx]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Entering interactive session.
debug1: pledge: network
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: receive packet: type 4
debug1: Remote: /home/<user>/.ssh/authorized_keys:4: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug3: receive packet: type 4
debug1: Remote: /home/<user>/.ssh/authorized_keys:4: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 3 setting TCP_NODELAY
debug2: client_session2_setup: id 0
debug1: Sending command: ls -l
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug3: receive packet: type 96
debug2: channel 0: rcvd eof
debug2: channel 0: output open -> drain
debug3: receive packet: type 98
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug3: receive packet: type 98
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug2: channel 0: rcvd eow
debug2: channel 0: chan_shutdown_read (i0 o1 sock -1 wfd 4 efd 6 [write])
debug2: channel 0: input open -> closed
debug3: receive packet: type 97
debug2: channel 0: rcvd close
debug3: channel 0: will not send data after close
total 4
drwxr-xr-x 2 <user> users 4096 Mar 13 07:27 bin
debug3: channel 0: will not send data after close
debug2: channel 0: obuf empty
debug2: channel 0: chan_shutdown_write (i3 o1 sock -1 wfd 5 efd 6 [write])
debug2: channel 0: output drain -> closed
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
ype 97

**Actual output**
Now we tried exactly the same from sytem account. we use the command "psexec64 -s -i cmd.exe" to open a command line interface as system and run "ssh -vvv <user>@xx.xx.xx.xx ls -l"
This time we get an Permission denied (publickey) error.

Reason seem to be that this time no ssh-agent is used. Only key files from folder C:\\windows\\system32\\config\\systemprofile/.ssh/ are considered. But as already explained, we have removed all key files because they are available through ssh-agent.

So for me it looks like ssh running as system does not query ssh-agent at all. Very strange because the ssh-agent service  uses the same account.

Is there something wrong in my thinking or is this just a bug
Or is there any other way, which I don't know, to get ssh to use ssh-agent.

*****************************************************************
As workaround we tried to use a id_rsa key file, which we installed in folder C:\\windows\\system32\\config\\systemprofile/.ssh/ 

Now we got an unprotected private key file warning which prevent ssh from using it. This could be fixed and we we got it working.

But of course thats not the solution that we want. We want to remove all key files and keep them in a save place after they are are added to ssh-agent.

******************************************************************
Debug output runnig ssh with system account

OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/config error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolve_canonicalize: hostname xx.xx.xx.xx is address
debug2: ssh_connect_direct
debug1: Connecting to xx.xx.xx.xx [xx.xx.xx.xx] port 22.
debug1: Connection established.
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_rsa error:2
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_rsa.pub error:2
debug1: identity file C:\\windows\\system32\\config\\systemprofile/.ssh/id_rsa type -1
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_rsa-cert error:2
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_rsa-cert.pub error:2
debug1: identity file C:\\windows\\system32\\config\\systemprofile/.ssh/id_rsa-cert type -1
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_dsa error:2
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_dsa.pub error:2
debug1: identity file C:\\windows\\system32\\config\\systemprofile/.ssh/id_dsa type -1
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_dsa-cert error:2
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_dsa-cert.pub error:2
debug1: identity file C:\\windows\\system32\\config\\systemprofile/.ssh/id_dsa-cert type -1
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_ecdsa error:2
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_ecdsa.pub error:2
debug1: identity file C:\\windows\\system32\\config\\systemprofile/.ssh/id_ecdsa type -1
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_ecdsa-cert error:2
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_ecdsa-cert.pub error:2
debug1: identity file C:\\windows\\system32\\config\\systemprofile/.ssh/id_ecdsa-cert type -1
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_ed25519 error:2
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_ed25519.pub error:2
debug1: identity file C:\\windows\\system32\\config\\systemprofile/.ssh/id_ed25519 type -1
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_ed25519-cert error:2
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_ed25519-cert.pub error:2
debug1: identity file C:\\windows\\system32\\config\\systemprofile/.ssh/id_ed25519-cert type -1
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_xmss error:2
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_xmss.pub error:2
debug1: identity file C:\\windows\\system32\\config\\systemprofile/.ssh/id_xmss type -1
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_xmss-cert error:2
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/id_xmss-cert.pub error:2
debug1: identity file C:\\windows\\system32\\config\\systemprofile/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
debug1: Remote protocol version 2.0, remote software version DCX_SSH_19.09.01
debug1: no match: DCX_SSH_19.09.01
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to xx.xx.xx.xx:22 as '<user>'
debug3: hostkeys_foreach: reading file "C:\\windows\\system32\\config\\systemprofile/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file C:\\windows\\system32\\config\\systemprofile/.ssh/known_hosts:2
debug3: load_hostkeys: loaded 1 keys from xx.xx.xx.xx
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/known_hosts2 error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug3: order_hostkeyalgs: prefer hostkeyalgs: rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ssh-rsa SHA256:qx6lFrmArxOJx3sHZejClYSE1uytjgj56jPxNNGb6eQ
debug3: hostkeys_foreach: reading file "C:\\windows\\system32\\config\\systemprofile/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file C:\\windows\\system32\\config\\systemprofile/.ssh/known_hosts:2
debug3: load_hostkeys: loaded 1 keys from xx.xx.xx.xx
debug3: Failed to open file:C:/windows/system32/config/systemprofile/.ssh/known_hosts2 error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug1: Host 'xx.xx.xx.xx' is known and matches the RSA host key.
debug1: Found key in C:\\windows\\system32\\config\\systemprofile/.ssh/known_hosts:2
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: C:\\windows\\system32\\config\\systemprofile/.ssh/id_rsa 
debug1: Will attempt key: C:\\windows\\system32\\config\\systemprofile/.ssh/id_dsa 
debug1: Will attempt key: C:\\windows\\system32\\config\\systemprofile/.ssh/id_ecdsa 
debug1: Will attempt key: C:\\windows\\system32\\config\\systemprofile/.ssh/id_ed25519 
debug1: Will attempt key: C:\\windows\\system32\\config\\systemprofile/.ssh/id_xmss 
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: C:\\windows\\system32\\config\\systemprofile/.ssh/id_rsa
debug3: no such identity: C:\\windows\\system32\\config\\systemprofile/.ssh/id_rsa: No such file or directory
debug1: Trying private key: C:\\windows\\system32\\config\\systemprofile/.ssh/id_dsa
debug3: no such identity: C:\\windows\\system32\\config\\systemprofile/.ssh/id_dsa: No such file or directory
debug1: Trying private key: C:\\windows\\system32\\config\\systemprofile/.ssh/id_ecdsa
debug3: no such identity: C:\\windows\\system32\\config\\systemprofile/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: C:\\windows\\system32\\config\\systemprofile/.ssh/id_ed25519
debug3: no such identity: C:\\windows\\system32\\config\\systemprofile/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: C:\\windows\\system32\\config\\systemprofile/.ssh/id_xmss
debug3: no such identity: C:\\windows\\system32\\config\\systemprofile/.ssh/id_xmss: No such file or directory
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
<user>@xx.xx.xx.xx: Permission denied (publickey).

**Comment by kurtbeil01** [comment]
Finally could solve this issue by myself.

Needed to add the private key once more with ssh-add. But this ssh-add was running as system account. After that ssh running under system acount could find the key. So it's really the way it's supposed to be.

What irritated me was that there was no information about ssh-agent access in the debug output. So at first I thought ssh-agen wasn't being acessed at all.

**Comment by beerisgood** [comment]
> 
> 
> Finally could solve this issue by myself.
> 
> Needed to add the private key once more with ssh-add. But this ssh-add was running as system account. After that ssh running under system acount could find the key. So it's really the way it's supposed to be.
> 
> What irritated me was that there was no information about ssh-agent access in the debug output. So at first I thought ssh-agen wasn't being acessed at all.

with system rights? Sounds like a security problem
