### ISSUE TITLE
Why are those UNIX-dedicated code blocks working correctly?

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#1572]
First of all, I want to state it clearly.

I'm not building or installing the Windows port of OpenSSH, I'm just researching, so nothing wrong encountered. I just want to ask some questions about the code (or maybe VS as well) and expect that someone could tell me what I want to know.

**"OpenSSH for Windows" version**

The last commit of the current **latestw_all** branch. (f4498b7c5bd132ec16499c94650fc3689d59a226)
 

**Server OperatingSystem**

Not related with the question.

**Client OperatingSystem**

Not related with the question.

**What is failing**

Nothing.

**Expected output**

Nothing.

**Actual output**

Nothing

---------------

**And here is my question**

After several hours of code reading in  `PowerShell/openssh-portable` project, I found that most of UNIX-dedicated code blocks are stay unchanged, not even the "include" statements.

For example, in includes.h and many other .c files, we have a lot of `#include <sys/socket.h>` statements there without an `#ifdef #endif` block to surround it. This normally means that the compiler will definitely look for `<sys/socket.h>` when you compile the code, but on Windows, there is no such header file named as `<sys/socket.h>`, not even in MinGW. (And of course, there is lots more code like this that should never supposed to exist in a program runs on Windows).

And according to the vcxproj files in contrib/win32/openssh directory, (If I didn't get wrong with it) most of those UNIX-dedicated code blocks are still get compiled and survived.

So, what actually happened during the compilation to make these code blocks work?

----------------

**Apologies**

And sorry for such a time-wasting question, but I really need someone to help me to understand this, I just failed to reveal all these mysterious mechanisms of Windows development.

**Comment by bagajjal** [comment]
![image](https://user-images.githubusercontent.com/23668037/77141147-25518100-6a39-11ea-81c7-e5e25ce76244.png)
