### ISSUE TITLE
Is User LocalPath other than default Path supported for authorized_keys file? 

### ISSUE THREAD

**Issue by NealWalters** [PowerShell/Win32-OpenSSH#1574]
**"OpenSSH for Windows" version**
7.9p1 for Windows 
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**
Win 2012/R2

**What is failing**
To get public key certificate to work, we had to put it in c:\users\testuser\.ssh.\authorized_keys. 
However, when the user was created, we set the "Home Folder - Local Path" to e:\Integration\SFTP\TestUser. 

When we put the .ssh/authorized_keysin the e:\Integratoin\SFTP\TestUser directory, we got the error: " Failed to open file:C:/Windows/.ssh/authorized_keys error:2", which seem quite misleading. 

When the user sends a file, it is stored in the e:\Integration\SFTP\TestUser as desired.  So the Local path seems to work for the upload/download of files, but not for the .ssh.\authorized_keys.

**Expected output**
If the local path for the user is defined as e:\Integration\SFTP\TestUser. then I wouldn't expect any error when putting the .ssh\authorized_keys there. 

(Also posted here: https://superuser.com/questions/1534321/why-does-openssh-try-to-open-c-windows-ssh-authorized-keys-instead-of-user-dir).

**Comment by WSLUser** [comment]
Doing this is already something not done in Linux. It is intended for the user profile .ssh to be used. You can specify any path for sending and receiving files but authorized keys much be directly under C:\User\username\ .ssh\ This is by-design behavior and imo should not be changed. It is not secure to place authorized keys somewhere other than the user home folder anyways. It may be inconvenient but if there's multiple users that need that file then simply use an administrator account to copy it to each of the profiles. Your solution is to change "Home Folder - Local Path" to C:\Users\testuser.

**Comment by WSLUser** [comment]
Also update your SSH to 8.1. There are some changes that should help in regards to the authorized keys. See https://github.com/PowerShell/openssh-portable/pull/409 for example.
