### ISSUE TITLE
sftp channel failing

### ISSUE THREAD

**Issue by jjlauer** [PowerShell/Win32-OpenSSH#158]
Hi,

I am using the Java JSCH library to connect. SSH sessions work and I can execute commands, but when I try to open up an "sftp" channel, the connection dies.  The log output is here: http://pastebin.com/qZpx6Xdr

Looks like a profile error is occurring at the end?

**Comment by manojampalam** [comment]
Try the latest release and reopen if needed

**Comment by Gondee** [comment]
So this is resolved with the latest release? 

Edit: Updated the OpenSSH executables, and still getting this error: 
`com.jcraft.jsch.JSchException: java.io.IOException: channel is broken`
