### ISSUE TITLE
Some character does not displayed normally.

### ISSUE THREAD

**Issue by wldhg** [PowerShell/Win32-OpenSSH#1580]
**"OpenSSH for Windows" version**
`8.1.0.0`
 
**Server OperatingSystem**
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**Client OperatingSystem**
Windows 10 (2004; build 19041.172)

**What is failing**
Failes to update console lines, display some characters.
That bug-like icon seems `0x0e` ASCII 15 code.

**Expected output**
1. XShell
![image](https://user-images.githubusercontent.com/22350783/78511916-61c40180-77db-11ea-9f16-4ae044d37eaf.png)

2. VS Code Remote ssh
![image](https://user-images.githubusercontent.com/22350783/78511896-4527c980-77db-11ea-84ac-485d36f29074.png)

**Actual output**
1. Windows cmd
![image](https://user-images.githubusercontent.com/22350783/78511854-c599fa80-77da-11ea-8f64-4283c624d8f0.png)

2. VS code integrated shell
![image](https://user-images.githubusercontent.com/22350783/78511835-a56a3b80-77da-11ea-865a-f1be45a49bc6.png)

**Comment by bagajjal** [comment]
@wldh-g  - Do you see this with plain ssh interactive session?
What is your setting to get non-english characters for "date" command?

To repro issue in simple,  in an interactive session copy&paste the characters that you think are not rendered properly.

**Comment by wldhg** [comment]
![image](https://user-images.githubusercontent.com/22350783/80115573-e24a7680-85bf-11ea-80b8-7d30dec2560a.png)
It is okay with `bash` session.
but the problem is occurred when I enter `fish` shell, even without any powerline feature.

**Comment by maertendMSFT** [comment]
@DHowett can you take a look at this?

**Comment by DHowett** [comment]
We usually see this one when tmux is running. There are two special characters, "shift out" (0x0E) and "shift in" (0x0F) that tmux likes to print to the screen when certain character encodings are in use. We have not been able to determine how to make tmux stop.

Newer versions of the windows console (**and Terminal**) support these characters and treat them properly. If you want a workaround for this issue, you can use (and should be using) Windows Terminal. Especially on Windows 20.04

**Comment by wldhg** [comment]
**Environment**

![image](https://user-images.githubusercontent.com/22350783/91439650-4fd91d00-e8a8-11ea-85aa-e0eef007beea.png)

**Output**
1. Windows Terminal + PS \
  ![image](https://user-images.githubusercontent.com/22350783/91439447-ed801c80-e8a7-11ea-84e4-03f6b993a15d.png)
2. Windows Terminal + CMD \
  ![image](https://user-images.githubusercontent.com/22350783/91439736-7434f980-e8a8-11ea-9200-63317f008e06.png)

It's clear. Thank you for your deep inspection, @DHowett !
