### ISSUE TITLE
Question about Log File Size

### ISSUE THREAD

**Issue by NealWalters** [PowerShell/Win32-OpenSSH#1584]
"OpenSSH for Windows" version
7.9p1 for Windows

Server OperatingSystem
Win 2012/R2

Question: 
My log file got up to 500 MB.  Are there any built-in parameters to keep it to a size, or to break to a new file each day?  Or would I have to create my own scripts to stop the service, rename the log, then start the service?

**Comment by bagajjal** [comment]
It's answered here,
https://github.com/PowerShell/Win32-OpenSSH/issues/935
