### ISSUE TITLE
sshd yields a barely functional/broken terminal

### ISSUE THREAD

**Issue by alexchandel** [PowerShell/Win32-OpenSSH#159]
After installing the SSHD Win64 server and rebooting the machine, ssh'ing to the machine yields an extremely poorly behaved terminal. Backspace doesn't work, nor does output coloring, nor do the arrow keys.

I've tested this on 64-bit Windows 2012 R2 and Windows 7 Pro, connecting from OS X's ssh client.

In the Windows 7 case, all of these features worked before restarting the machine after installing, but stopped working after I restarted it.

**Comment by alexchandel** [comment]
In fact after this happens, `powershell.exe` no longer works. No output appears in the terminal, nor do any typed characters, until I type "exit" and press enter.

**Comment by manojampalam** [comment]
Its understood that the terminal experience is very primitive at this stage. The implementation for interactive shell in the current version is a stop gap solution, expect a better terminal by end of May.

**Comment by alexchandel** [comment]
@manojampalam that's not entirely the issue I'm having here though.

The issue is that **initially** there is a terminal experience when one ssh's to a Windows machine, however annoying (e.g. no scrollback): it has ~~arrow keys and terminal history~~ backspace and coloring. But after **rebooting** with Windows SSHD server, the ~~terminal experience goes away~~ backspace key breaks entirely, and the terminal is not even VT100.

**Comment by manojampalam** [comment]
Arrow keys have been disabled on sshd side for a while now. Not sure how they ended up working for you. Anyway, as I said, please bear with these limitations for now.

**Comment by alexchandel** [comment]
@manojampalam I'm really curious how it ended up working. It was a ~~fully functional~~ terminal, with colorized output, ~~arrow keys (both left/right and up/down), home/end,~~ backspace, and scrollback modification (though that was annoying). Is there a flag that enables this?

**Comment by alexchandel** [comment]
@manojampalam 

Update: this is a limitation issue. I was wrong, the arrow keys never worked. However, when I install SSHD from the 2016-02-25 release with LSA, the **backspace key** originally works for clients. But when I restart, it breaks forever. Also, if I install SSHD from the Chocolatey package (with `-params '"/SSHServerFeature /KeyBasedAuthenticationFeature"'`), the backspace key never works to begin with.

**Comment by alexchandel** [comment]
@manojampalam  This has regressed even further in 4_5_2016. In 3_19_2016, while the screen wasn't updated to reflect it, pressing the backspace key would remove characters from the buffer. In 4_5_2016, not even this happens anymore.

**Comment by manojampalam** [comment]
Yes, please bear with this experience for now. We are working on getting the experience right.

**Comment by alexchandel** [comment]
Related: #122

**Comment by alexchandel** [comment]
I notice the 2016_05_15 release provides (marginal) sshd terminal experience improvements when connected from a 2016_05_15 win32 ssh client.

However, it's still bad from other ssh clients. In particular for the Arch & OSX ssh clients connected to the Win32 sshd, in addition to not removing characters from the buffer and not removing them from the screen, the backspace key now adds some nonprintable character to the buffer that tends to corrupt most commands.

Is this still slated for improvement?

**Comment by rayhayes** [comment]
Yes. I'm working on it now. I'll make a point to test from at least OSX.

**Comment by alexchandel** [comment]
Hopefully this will make it into a June release.

**Comment by dragon788** [comment]
I'd also like to report that escape character sequences behave horribly. I did an `npm install` inside a vagrant ssh session using win32-openSSH as the client and it was pretty rough, lots of control characters littering the screen as npm uses them to color the dots or stars of its progress meters.

**Comment by anotherjarvi** [comment]
Yep, also having issues using up arrow/down arrow for history

**Comment by dragon788** [comment]
Does ctrl+ P and ctrl+ N work with sshd or do you have to use the Windows previous history key of F7?

**Comment by lalomartins** [comment]
**EDIT:** ok, this was missing something along the lines of, “Please try out the Sep-End milestone release. Reopen if needed.” (copied from another bug)

Arrows now work, and escape. It would be nice if alt-something would send esc-something but that would be a separate issue.
