### ISSUE TITLE
PermitListen not limiting port forwarding.

### ISSUE THREAD

**Issue by Ma-XX-oN** [PowerShell/Win32-OpenSSH#1590]
**"OpenSSH for Windows" version**
The `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)` command didn't work in PowerShell.
```
PS C:\Program Files\OpenSSH-Win64> ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
Get-Command : The term 'sshd' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:13
+ ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (sshd:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

Get-Item : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:12
+ ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
+            ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Item], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetItemComm
   and

PS C:\Program Files\OpenSSH-Win64>
```
Giving an invalid switch though gave the following:
```
PS C:\Program Files\OpenSSH-Win64> ./sshd --version
unknown option -- -
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
usage: sshd [-46DdeiqTt] [-C connection_spec] [-c host_cert_file]
            [-E log_file] [-f config_file] [-g login_grace_time]
            [-h host_key_file] [-o option] [-p port] [-u len]
```

**Server OperatingSystem**
```
PS C:\Program Files\OpenSSH-Win64> ((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name Produc
tName).ProductName)
Windows 8.1
```

**Client OperatingSystem**
```
PS C:\> ((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)
Windows 10 Pro
```

**What is failing**
Can't limit port being passed to.

**The setup**
1. Have `nc` (netcat) installed on the system being tested.
2. At beginning of a default `ssh_config` file:
   ```
   PermitTTY no
   MaxSessions 1
   AllowUsers debug
   PermitListen 4023
   ```
3. Restart `sshd`.
4. Server terminal 1
    ```
   $ nc -6l 4024
   ```
**Expected output**

Client terminal 1
```
$ ssh -N -L localhost:5022:localhost:4024 debug@server.lan -p 7778
debug@server.lan's password:
```

Client terminal 2
```
$ nc -v localhost 5022
Connection to localhost 5022 port [tcp/*] succeeded!

$
```
Since the only permitted port to forward to is 4023 as stated in the `ssh_config` file and *not* 4024 as requested in the `ssh` command above, either:

`ssh` command should fail
- optimal, as the bind should be considered invalid and is closest to what should be causing an error or

`nc` should drop connection
- suboptimal but ok, as the `nc` client shouldn't be able to connect to `nc` listener.

**Actual output**
Client terminal 2
```
$ nc -v localhost 5022
Connection to localhost 5022 port [tcp/*] succeeded!
```
and typing in either Client's terminal 2 or Server's terminal 1 will show up in the other terminal after pressing Enter.  server.lan can be either another computer or the same as the client.lan.

**Comment by riverar** [comment]
Hey @Ma-XX-oN, the sshd docs describe `PermitListen` as such (emphasis mine):
> **Limit remote port forwarding with the ssh(1) -R option** such that it may only listen on the specified host (optional) and port. IPv6 addresses can be specified by enclosing the address in square brackets. Multiple permitlisten options may be applied separated by commas. Hostnames may include wildcards as described in the PATTERNS section in ssh_config(5). A port specification of * matches any port. Note that the setting of GatewayPorts may further restrict listen addresses. Note that ssh(1) will send a hostname of “localhost” if a listen host was not specified when the forwarding was requested, and that this name is treated differently to the explicit localhost addresses “127.0.0.1” and “::1”.

And from ssh docs, regarding `-R`:
> Specifies that connections to the given TCP port or Unix socket on the remote (server) host are to be forwarded to the local side.

So is your scenario set up correctly here? Not seeing `-R` usage in your repro steps.

**Comment by Ma-XX-oN** [comment]
Hi @riverar,

Thanks for the response.  Not sure why I thought it was PermitListen.  Must be PermitOpen then.  Though I thought that I tried that also.  I'll try it again.
