### ISSUE TITLE
Rendering issues when connecting from Linux Mint terminal

### ISSUE THREAD

**Issue by veljkomilj** [PowerShell/Win32-OpenSSH#1591]
**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
Windows Server 2016 Datacenter

**What is failing**
Rendering is broken when ssh-ing from Linux Mint terminal to windows 2016 running openssh server. I can only get the first 45 lines displayed properly.  Once 45th line is reached the last line starts being overwritten. Please take a look into output that I am getting.

**Expected output**
`Microsoft Windows [Version 10.0.14393]                                                                                          
(c) 2016 Microsoft Corporation. All rights reserved.                                                                            

redmond\veljkom@SP-BEAST C:\Users\veljkom>dir                                                                                   
 Volume in drive C is Windows                                                                                                   
 Volume Serial Number is BA52-656C                                                                                              

 Directory of C:\Users\veljkom                                                                                                  

04/22/2020  12:36 PM    <DIR>          .                                                                                        
04/22/2020  12:36 PM    <DIR>          ..                                                                                       
03/24/2017  08:25 PM    <DIR>          .config                                                                                  
01/19/2017  04:04 PM    <DIR>          .dnx                                                                                     
03/12/2020  12:52 PM    <DIR>          .dotnet                                                                                  
03/22/2019  01:03 PM    <DIR>          .matplotlib                                                                              
01/27/2017  12:05 PM    <DIR>          .nuget                                                                                   
03/15/2020  12:52 AM    <DIR>          .pylint.d                                                                                
03/16/2020  09:34 PM                 7 .python_history                                                                          
04/22/2020  12:37 PM    <DIR>          .ssh                                                                                     
04/16/2020  04:37 PM             1,866 .viminfo                                                                                 
02/21/2020  05:11 PM    <DIR>          .vscode                                                                                  
02/21/2020  12:35 PM    <DIR>          Contacts                                                                                 
03/02/2020  05:16 PM    <DIR>          Desktop                                                                                  
03/12/2020  12:10 PM    <DIR>          Documents                                                                                
04/22/2020  11:55 AM    <DIR>          Downloads                                                                                
02/21/2020  12:35 PM    <DIR>          Favorites                                                                                
02/21/2020  12:35 PM    <DIR>          Links                                                                                    
02/21/2020  12:35 PM    <DIR>          Music                                                                                    
02/21/2020  12:35 PM    <DIR>          Pictures                                                                                 
02/21/2020  12:35 PM    <DIR>          Saved Games                                                                              
02/21/2020  12:35 PM    <DIR>          Searches                                                                                 
03/12/2020  12:11 PM    <DIR>          source                                                                                   
02/21/2020  12:35 PM    <DIR>          Videos                                                                                   
               2 File(s)          1,873 bytes                                                                                   
              22 Dir(s)  77,615,083,520 bytes free                                                                              

redmond\veljkom@SP-BEAST C:\Users\veljkom>dir                                                                                   
 Volume in drive C is Windows                                                                                                   
 Volume Serial Number is BA52-656C                                                                                              

 Directory of C:\Users\veljkom                                                                                                  

04/22/2020  12:36 PM    <DIR>          .                                                                                        
04/22/2020  12:36 PM    <DIR>          ..                                                                                       
03/24/2017  08:25 PM    <DIR>          .config                                                                                  
01/19/2017  04:04 PM    <DIR>          .dnx                                                                                     
03/12/2020  12:52 PM    <DIR>          .dotnet                                                                                  
03/22/2019  01:03 PM    <DIR>          .matplotlib                                                                              
01/27/2017  12:05 PM    <DIR>          .nuget                                                                                   
03/15/2020  12:52 AM    <DIR>          .pylint.d                                                                                
03/16/2020  09:34 PM                 7 .python_history                                                                          
04/22/2020  12:37 PM    <DIR>          .ssh                                                                                     
04/16/2020  04:37 PM             1,866 .viminfo                                                                                 
02/21/2020  05:11 PM    <DIR>          .vscode                                                                                  
02/21/2020  12:35 PM    <DIR>          Contacts                                                                                 
03/02/2020  05:16 PM    <DIR>          Desktop                                                                                  
03/12/2020  12:10 PM    <DIR>          Documents                                                                                
04/22/2020  11:55 AM    <DIR>          Downloads                                                                                
02/21/2020  12:35 PM    <DIR>          Favorites                                                                                
02/21/2020  12:35 PM    <DIR>          Links                                                                                    
02/21/2020  12:35 PM    <DIR>          Music                                                                                    
02/21/2020  12:35 PM    <DIR>          Pictures                                                                                 
02/21/2020  12:35 PM    <DIR>          Saved Games                                                                              
02/21/2020  12:35 PM    <DIR>          Searches                                                                                 
03/12/2020  12:11 PM    <DIR>          source                                                                                   
02/21/2020  12:35 PM    <DIR>          Videos                                                                                   
               2 File(s)          1,873 bytes                                                                                   
              22 Dir(s)  77,615,083,520 bytes free                                                                                                   `
**Actual output**
Microsoft Windows [Version 10.0.14393]                                                                                          
(c) 2016 Microsoft Corporation. All rights reserved.                                                                            

redmond\veljkom@SP-BEAST C:\Users\veljkom>dir                                                                                   
 Volume in drive C is Windows                                                                                                   
 Volume Serial Number is BA52-656C                                                                                              

 Directory of C:\Users\veljkom                                                                                                  

04/22/2020  12:36 PM    <DIR>          .                                                                                        
04/22/2020  12:36 PM    <DIR>          ..                                                                                       
03/24/2017  08:25 PM    <DIR>          .config                                                                                  
01/19/2017  04:04 PM    <DIR>          .dnx                                                                                     
03/12/2020  12:52 PM    <DIR>          .dotnet                                                                                  
03/22/2019  01:03 PM    <DIR>          .matplotlib                                                                              
01/27/2017  12:05 PM    <DIR>          .nuget                                                                                   
03/15/2020  12:52 AM    <DIR>          .pylint.d                                                                                
03/16/2020  09:34 PM                 7 .python_history                                                                          
04/22/2020  12:37 PM    <DIR>          .ssh                                                                                     
04/16/2020  04:37 PM             1,866 .viminfo                                                                                 
02/21/2020  05:11 PM    <DIR>          .vscode                                                                                  
02/21/2020  12:35 PM    <DIR>          Contacts                                                                                 
03/02/2020  05:16 PM    <DIR>          Desktop                                                                                  
03/12/2020  12:10 PM    <DIR>          Documents                                                                                
04/22/2020  11:55 AM    <DIR>          Downloads                                                                                
02/21/2020  12:35 PM    <DIR>          Favorites                                                                                
02/21/2020  12:35 PM    <DIR>          Links                                                                                    
02/21/2020  12:35 PM    <DIR>          Music                                                                                    
02/21/2020  12:35 PM    <DIR>          Pictures                                                                                 
02/21/2020  12:35 PM    <DIR>          Saved Games                                                                              
02/21/2020  12:35 PM    <DIR>          Searches                                                                                 
03/12/2020  12:11 PM    <DIR>          source                                                                                   
02/21/2020  12:35 PM    <DIR>          Videos                                                                                   
               2 File(s)          1,873 bytes                                                                                   
              22 Dir(s)  77,615,083,520 bytes free                                                                              

redmond\veljkom@SP-BEAST C:\Users\veljkom>dir                                                                                   
 Volume in drive C is Windows                                                                                                   
 Volume Serial Number is BA52-656C                                                                                              

 Directory of C:\Users\veljkom                                                                                                  

04/22/2020  12:36 PM    <DIR>          .                                                                                        
04/22/2020  12:36 PM    <DIR>          ..                                                                                       
redmond\veljkom@SP-BEAST C:\Users\veljkom>

**Comment by bagajjal** [comment]
Possible duplicate of https://github.com/PowerShell/Win32-OpenSSH/issues/1556.
Please test with private binary given in #1556 and confirm.

**Comment by veljkomilj** [comment]
I have confirmed that the private binary is fixing the problem. You can close this as duplicate of 1556.
