### ISSUE TITLE
Can I reconnect to session after dissconnecting

### ISSUE THREAD

**Issue by veljkomilj** [PowerShell/Win32-OpenSSH#1592]
**"OpenSSH for Windows" version**
8.1.0.0
 
**Server OperatingSystem**
 `Windows Server 2016 Datacenter`

**Client OperatingSystem**
Linux Mint 19

**What is failing**
I want to start process on server and disconnect. Then I should be able to reconnect to a same session. On linux server I would do this with tmux / screen. 

Is there a way to accomplish the same on windows?

**Comment by bagajjal** [comment]
Unfortunately there is no such utility (like screen) on windows.

However there is a workaround if you want to run long running process even after ssh session is closed. see https://github.com/PowerShell/Win32-OpenSSH/issues/1032
