### ISSUE TITLE
Question Account Permissions

### ISSUE THREAD

**Issue by gamethis** [PowerShell/Win32-OpenSSH#1594]
I have a question from a secpolicy point of view.
What permissions must an account have to access system via ssh?
ie... SeRemoteInteractiveLogonRight
reference for rights https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-rights-assignment

I have not found this in documentation.

thanks

**Comment by bagajjal** [comment]
Over SSH, If you are an admin then you can execute "psexec -s cmd" to switch to system account.

![image](https://user-images.githubusercontent.com/23668037/80414711-4b631000-8886-11ea-83e8-4abc3daa5982.png)

**Comment by gamethis** [comment]
thanks for the response... but not quite what I was looking at...

So if I set up my security policy to allow my user ssh... I need to know which type of auth they need.  ie network, remote interactive.... etc...

**Comment by gamethis** [comment]
Found the Answer Login Type is 3 Network Login
