### ISSUE TITLE
Installer assumes that sshd will only be installed on computers configured in English

### ISSUE THREAD

**Issue by pjt33** [PowerShell/Win32-OpenSSH#1596]
**"OpenSSH for Windows" version**
7.7.2.2 installed following section "*Installing OpenSSH from the Settings UI on Windows Server 2019 or Windows 10 1809*" of https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Windows 10 Enterprise

**What is failing**
Public key authentication.

**Expected output**
Successful authentication.

**Actual output**
Client (shell output):

    Permission denied (publickey,keyboard-interactive).

Server (via Event Viewer):

	<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
		<System>
			<Provider Name="OpenSSH" Guid="{c4b57d35-0636-4bc3-a262-370f249f9802}" />
			<EventID>2</EventID>
			<Version>0</Version>
			<Level>2</Level>
			<Task>0</Task>
			<Opcode>0</Opcode>
			<Keywords>0x8000000000000000</Keywords>
			<TimeCreated SystemTime="2020-04-29T09:19:20.159780200Z" />
			<EventRecordID>6</EventRecordID>
			<Correlation />
			<Execution ProcessID="11500" ThreadID="6588" />
			<Channel>OpenSSH/Admin</Channel>
			<Computer>EVEN-PC</Computer>
			<Security UserID="S-1-5-18" />
		</System>
		<EventData>
			<Data Name="process">sshd</Data>
			<Data Name="payload">error: unable to resolve group administrators</Data>
		</EventData>
	</Event>

## Diagnosis and proposed fix

The problem (clued in by issue  #1346) is that the server is was installed in Spanish, and so the group is called `administradores`.

Proposed fix: the installer should look up the local name of the S-1-5-32-544 group and substitute that into `sshd_config`.

**Comment by maertendMSFT** [comment]
Please try the latest release, 8.1

**Comment by michaeladm** [comment]
To use localization, you need to change the encoding of file C:\ProgramData\ssh\sshd_config to UTF8. This can be done for example in FAR Manager -> EDIT -> SIFT+F2 (Save as) -> Select "UTF8" codepage. And in the "Match Group" parameters, use only lowercase letters. Example:

Match Group администраторы
   AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys

**Comment by alexhass** [comment]
I'm running a English 2019 DC machine in an old AD that was German in past and the issue persist. It is not resolved in latest version that is installed on my system via optional components. How can this errors removed?

I see hundreds of errors

`sshd: error: unable to resolve group administrators`

**Comment by bagajjal** [comment]
@alexhass - What is the SSH server version? please share the sshd.log (DEBUG3 enabled). Please refer to the [wiki](https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities) for file based sshd.log.

**Comment by alexhass** [comment]
The version Microsoft released officially with Windows 2019. It says "OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5". If this is the wrong version - can MS publish a newer version that comes via Windows Update, please?

**Comment by alexhass** [comment]
Is it the correct fix to change C:\ProgramData\ssh\sshd_config to German word "Administratoren"?

```
#Match Group administrators
Match Group Administratoren
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
```

**Comment by bagajjal** [comment]
@alexhass - V7.7 shipped into windows server 2019 doesn't have this fix. 
V8.1 shipped into windows server 2022 has the fix.

Unfortunately, we can't fix it in windows server 2019 as it's not a security issue.

**Comment by alexhass** [comment]
How about fixing bugs in 2019? This is a bug and it is new to me that only security issues are getting fixed during a product live cycle. I‘m sure an update will also fix many other bugs people have found. So it is useful to provide an update during a 10 years live cycle.

**Comment by bagajjal** [comment]
@SteveL-MSFT , @maertendMSFT about fixing it in Windows server 2019
