### ISSUE TITLE
Authorization problem with RSA keys

### ISSUE THREAD

**Issue by Lime13** [PowerShell/Win32-OpenSSH#1598]
Hi, on the Windows 7 server OpenSSH works and users connect using a password everything is fine but the question arose about how to connect using RSA SSH2 keys. But I ran into a problem that the server does not want to authorize using keys. What might be the problem and how to solve it?
sshd.log
5796 15:41:36 920 debug1: socket:300, io:000000000045B900, fd:4 
5796 15:41:36 920 debug1: pipe - read end: handle:00000000000000F0, io:0000000000467F50, fd:5
5796 15:41:36 920 debug1: pipe - write end: handle:00000000000000F8, io:0000000000485780, fd:6
5796 15:41:36 998 debug1: close - io:000000000045B900, type:1, fd:4, table_index:4
5796 15:41:36 998 debug1: close - io:0000000000467F50, type:2, fd:5, table_index:5
5796 15:41:36 998 debug1: Register child 0000000000000110 pid 4600, 0 zombies of 0
5796 15:41:36 998 debug1: Forked child 4600.
5796 15:41:36 998 debug1: close - io:0000000000485780, type:2, fd:6, table_index:6
5796 15:41:36 998 debug1: w32_close ERROR: bad fd: 4
4600 15:41:37 139 Connection from 192.168.10.1 port 4063 on 192.168.10.2 port 22
4600 15:41:37 139 debug1: Client protocol version 2.0; client software version PuTTY_Release_0.60
4600 15:41:37 139 debug1: match: PuTTY_Release_0.60 pat PuTTY_Local:*,PuTTY-Release-0.5*,PuTTY_Release_0.5*,PuTTY_Release_0.60*,PuTTY_Release_0.61*,PuTTY_Release_0.62*,PuTTY_Release_0.63*,PuTTY_Release_0.64* compat 0x00004000
4600 15:41:37 139 debug1: Enabling compatibility mode for protocol 2.0
4600 15:41:37 139 debug1: Local version string SSH-2.0-OpenSSH_7.1p1 Microsoft_Win32_port_with_VS
4600 15:41:37 139 error: Unable to get agent socket: agent not present
4600 15:41:37 139 debug1: list_hostkey_types: ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
4600 15:41:37 139 debug1: SSH2_MSG_KEXINIT sent
4600 15:41:37 139 debug1: SSH2_MSG_KEXINIT received
4600 15:41:37 139 debug1: kex: algorithm: diffie-hellman-group14-sha1
4600 15:41:37 139 debug1: kex: host key algorithm: ssh-rsa
4600 15:41:37 139 debug1: kex: client->server cipher: aes256-cbc MAC: hmac-sha1 compression: none
4600 15:41:37 139 debug1: kex: server->client cipher: aes256-cbc MAC: hmac-sha1 compression: none
4600 15:41:37 139 debug1: expecting SSH2_MSG_KEXDH_INIT
4600 15:41:37 232 debug1: SSH2_MSG_NEWKEYS sent
4600 15:41:37 232 debug1: expecting SSH2_MSG_NEWKEYS
4600 15:41:37 326 debug1: SSH2_MSG_NEWKEYS received
4600 15:41:37 326 debug1: KEX done
4600 15:41:37 326 debug1: userauth-request for user user1 service ssh-connection method none
4600 15:41:37 326 debug1: attempt 0 failures 0
4600 15:41:37 326 Failed none for user1 from 192.168.10.1 port 4063 ssh2
4600 15:41:37 326 debug1: userauth-request for user user1 service ssh-connection method publickey
4600 15:41:37 326 debug1: attempt 1 failures 0
4600 15:41:37 326 debug1: test whether pkalg/pkblob are acceptable
4600 15:41:37 326 Postponed publickey for user1 from 192.168.10.1 port 4063 ssh2
4600 15:41:38 012 debug1: userauth-request for user user1 service ssh-connection method publickey
4600 15:41:38 012 debug1: attempt 2 failures 0
4600 15:41:38 012 debug1: cannot connect to auth agent
4600 15:41:38 012 Failed publickey for user1 from 192.168.10.1 port 4063 ssh2: RSA SHA256:OtunAipE0pEhQPLy4qtRhrIkw0GO1MoiH0ROx6yiztI
4600 15:41:38 012 debug1: userauth-request for user user1 service ssh-connection method keyboard-interactive
4600 15:41:38 012 debug1: attempt 3 failures 1
4600 15:41:38 012 debug1: keyboard-interactive devs 
4600 15:41:38 012 debug1: auth2_challenge: user=user1 devs=
4600 15:41:38 012 debug1: kbdint_alloc: devices ''
4600 15:41:38 012 Failed keyboard-interactive for user1 from 192.168.10.1 port 4063 ssh2
4600 15:41:48 308 debug1: userauth-request for user user1 service ssh-connection method password
4600 15:41:48 308 debug1: attempt 4 failures 2
4600 15:41:48 308 Accepted password for user1 from 192.168.10.1 port 4063 ssh2
4600 15:41:48 308 debug1: Entering interactive session for SSH2.
4600 15:41:48 308 debug1: pipe - read end: handle:0000000000000108, io:0000000000241AB0, fd:4
4600 15:41:48 308 debug1: pipe - write end: handle:000000000000010C, io:00000000002CCD10, fd:5
4600 15:41:48 308 debug1: server_init_dispatch_20
4600 15:41:48 308 debug1: server_input_channel_open: ctype session rchan 256 win 16384 max 16384
4600 15:41:48 308 debug1: input_session_request
4600 15:41:48 308 debug1: channel 0: new [server-session]
4600 15:41:48 308 debug1: session_new: session 0
4600 15:41:48 308 debug1: session_open: channel 0
4600 15:41:48 308 debug1: session_open: session 0: link with channel 0
4600 15:41:48 308 debug1: server_input_channel_open: confirm session
4600 15:41:48 418 debug1: server_input_channel_req: channel 0 request pty-req reply 1
4600 15:41:48 418 debug1: session_by_channel: session 0 channel 0
4600 15:41:48 418 debug1: session_input_channel_req: session 0 req pty-req
4600 15:41:48 418 debug1: Allocating pty.
4600 15:41:48 418 debug1: session_pty_req: session 0 alloc console
4600 15:41:48 418 debug1: Ignoring unsupported tty mode opcode 3 (0x3)
4600 15:41:48 418 debug1: server_input_channel_req: channel 0 request shell reply 1
4600 15:41:48 418 debug1: session_by_channel: session 0 channel 0
4600 15:41:48 418 debug1: session_input_channel_req: session 0 req shell
4600 15:41:48 418 Starting session: shell on console for user1 from 192.168.10.1 port 4063
4600 15:41:48 418 debug1: pipe - read end: handle:0000000000000110, io:00000000002CC250, fd:6
4600 15:41:48 418 debug1: pipe - write end: handle:0000000000000114, io:00000000002C7360, fd:7
4600 15:41:48 418 debug1: pipe - read end: handle:0000000000000118, io:0000000000290830, fd:8
4600 15:41:48 418 debug1: pipe - write end: handle:000000000000011C, io:00000000002908E0, fd:9
4600 15:41:48 418 debug1: pipe - read end: handle:0000000000000120, io:00000000002CF840, fd:10
4600 15:41:48 418 debug1: pipe - write end: handle:0000000000000124, io:00000000002CF8F0, fd:11
4600 15:41:48 418 debug1: <- GetHomeDirFromToken()...
4600 15:41:48 418 debug1: Executing command: ssh-shellhost.exe
4600 15:41:48 511 debug1: Register child 0000000000000130 pid 2960, 0 zombies of 0
4600 15:41:48 511 debug1: close - io:00000000002CC250, type:2, fd:6, table_index:6
4600 15:41:48 511 debug1: close - io:00000000002908E0, type:2, fd:9, table_index:9
4600 15:41:48 511 debug1: close - io:00000000002CF8F0, type:2, fd:11, table_index:11
4600 15:41:51 085 debug1: close - io:0000000000290830, type:2, fd:8, table_index:8
4600 15:41:51 085 debug1: close - io:00000000002CF840, type:2, fd:10, table_index:10
4600 15:41:51 085 debug1: zombie'ing child at index 0, 0 zombies of 1
4600 15:41:51 085 debug1: raise sig:3
4600 15:41:51 085 debug1: process_queued_signals: WARNING - A signal has interrupted and was processed
4600 15:41:51 085 debug1: Received SIGCHLD.
4600 15:41:51 085 debug1: Unregister child at index 0, 1 zombies of 1
4600 15:41:51 085 debug1: session_by_pid: pid 2960
4600 15:41:51 085 debug1: session_exit_message: session 0 channel 0 pid 2960
4600 15:41:51 085 debug1: session_exit_message: release channel 0
4600 15:41:51 085 debug1: close - io:00000000002C7360, type:2, fd:7, table_index:7
4600 15:41:51 085 debug1: Sending exit signal to child process [pid = 2960]...
4600 15:41:51 085 debug1: session_pty_cleanup: session 0 release console
4600 15:41:51 085 debug1: session_by_channel: session 0 channel 0
4600 15:41:51 085 debug1: session_close_by_channel: channel 0 child 0
4600 15:41:51 085 debug1: session_close: session 0 pid 0
4600 15:41:51 085 debug1: channel 0: free: server-session, nchannels 1
4600 15:41:51 085 Connection closed by 192.168.10.1
4600 15:41:51 085 debug1: raise sig:1
5796 15:41:51 085 debug1: zombie'ing child at index 0, 0 zombies of 1
5796 15:41:51 085 debug1: raise sig:3
5796 15:41:51 085 debug1: Unregister child at index 0, 1 zombies of 1
5796 15:41:51 085 debug1: process_queued_signals: WARNING - A signal has interrupted and was processed

**Comment by bagajjal** [comment]
Please share DEBUG3 sshd.log and client side logs (ssh -vvv user@ip).

It also matters how you are generating the keys. I would suggest you create new keys using 
ssh-keygen.exe -t rsa -f id-rsa

**Comment by Lime13** [comment]
Unfortunately now there is no way to make debag3.  The keys were made using puttygen a private key on the client and public on the server.

**Comment by Lime13** [comment]
[sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/4585968/sshd.log)

**Comment by Lime13** [comment]
I attached a log with DEBUG 3. How to make a log from the client I do not know as the ssh client is not on it. I'm using putty to connect.

**Comment by bagajjal** [comment]
@Lime13  - You are not using this repo binaries.

Log from your sshd.log
2404 12:32:19 218 debug1: Local version string SSH-2.0-OpenSSH_7.1p1 Microsoft_Win32_port_with_VS

We never have [version 7.1](https://github.com/PowerShell/Win32-OpenSSH/releases)
