### ISSUE TITLE
Powershell accepts input on the daemons prompt, not the clients

### ISSUE THREAD

**Issue by ariscop** [PowerShell/Win32-OpenSSH#16]
https://youtu.be/dVPuI8HrE00

Launching powershell directly (ssh localhost powershell) has the same behavior

**Comment by quamrulmina** [comment]
Known limit now - cmd.exe shell runs but Powershell does not. Our win32 port of sshd server does not provide a console as input in pty/tty mode and powershell seems to need a console input to run in interactive mode. Notice cmd.exe shell does not have this need and so runs fine.

**Comment by quamrulmina** [comment]
"powershell -File -" invocation will make it work now as it is a known issue of powershell.

**Comment by quamrulmina** [comment]
Invoke as follows to make it work:
ssh user@domain@hostname powershell -File -

From a cmd.exe remote shell:
ssh user@domain@hostname
c:> powershell -File -

**Comment by MichaelPie** [comment]
@quamrulmina This didn't work for me. When I enter powershell -File - I just receive "powershell -File" twice as output, but PowerShell commands still don't work. Only cmd.exe shell works.

**Comment by quamrulmina** [comment]
In the upcoming release it has been fixed and "ssh user@domain@hostname powershell -File -" will work. But it will work even better if you launch powershell after getting to the interactive shell, cmd.exe, in this case so that pty support like echo characters are available:
ssh user@domain@hostname
c:> powershell -File -

**Comment by manojampalam** [comment]
Fixed in latest release.

**Comment by mikemaccana** [comment]
Why is this closed? There's a workaround (`powershell -File -`) but obviously input should be set correctly by default.

**Comment by ariscop** [comment]
This bug was fixed, powershell's io is sent over ssh instead of using the sshd's console
On the latest release powershell is still broken, but it's a different bug

**Comment by mikemaccana** [comment]
Thanks @ariscop!
