### ISSUE TITLE
Why does Win32-OpenSSH "print" every screen refresh like a dot matrix printer ?

### ISSUE THREAD

**Issue by prynhart** [PowerShell/Win32-OpenSSH#1601]
Firstly, I *love* being able to SSH into Windows boxes (long time *nix admin here) - so thank you for this project.  But I've always been curious as to why every character seems to be painted or printed to the screen (including spaces).

Here's an example video showing two VMs - the top running Windows Server 2016 and the bottom FreeBSD:

https://youtu.be/HXPLlFZ90mM

On the Windows box I'm running one of the cmdlets from  https://superuser.com/questions/176624/linux-top-command-for-windows-powershell (to give a pseudo 'top')  compared to standard top on the FreeBSD box.

Notice how the Windows box "draws" everything (including spaces) whereas the *nix box appears to refresh / update without looking like a dot matrix printer "printing lines".

Note that it's not this particular cmdlet that does this - I can see something similar with any output (e.g. Get-ChildItem -Recuse will do it).

Both VMs are on the same ESX host - so it's not the case of one machine having a much slower hosting environment.  I've also changed my default shell to powershell.exe - so it's not a case of this session being 'wrapped' inside a cmd.exe (in case this would make a difference).

Thanks in Advance,

Patrick Rynhart

**Comment by bagajjal** [comment]
On latest windows (win10+ / windows server 2019), openssh uses console pty support. It has the same experience as the unix.

On prior windows releases, we have only basic support.
