### ISSUE TITLE
Release Clarification

### ISSUE THREAD

**Issue by gamethis** [PowerShell/Win32-OpenSSH#1604]
https://github.com/PowerShell/Win32-OpenSSH/issues/137
we have a latest tag for releases here
but can we get it for https://github.com/PowerShell/openssh-portable/releases/

or is https://github.com/PowerShell/openssh-portable/releases/tag/v8.1.0.0
the same as https://github.com/PowerShell/Win32-OpenSSH/releases/latest/

my concern is having a latest stable vs latest development version.
the code for latest shown here https://github.com/PowerShell/Win32-OpenSSH/wiki/How-to-retrieve-links-to-latest-packages

shows latest dev version not latest stable version.

thanks

**Comment by bagajjal** [comment]
@gamethis - We track our binaries and issues at https://github.com/PowerShell/Win32-OpenSSH and code at  https://github.com/PowerShell/openssh-portable. There are historical reason why we ended up like this.  We don't have stable and development versions.

**Comment by gamethis** [comment]
@bagajjal thanks for the info, to clarify... I am asking that the latest version in https://github.com/PowerShell/openssh-portable is the same as latest version here https://github.com/PowerShell/Win32-OpenSSH.
I ask as one is marked beta and the other is not.  if they are not the same then I am asking for the latest to be tagged in the both repos.

**Comment by bagajjal** [comment]
@gamethis - The latest version in both the repos are same although one has "P1-Beta" in the release name.

Win32-openssh repo is used for bug tracking and Microsoft compiled binary releases.
openssh-portable is used for source code and PR requests.

Going forward, I will use the same tag in both repos to avoid confusion.
