### ISSUE TITLE
GSSAPI Kerberos Windows -> Linux: "sspi delegation was requested but not fulfilled"

### ISSUE THREAD

**Issue by bpfoley45** [PowerShell/Win32-OpenSSH#1606]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
8.1.0.0
 
**Server OperatingSystem**
Fedora 32, OpenSSH_8.2p1, OpenSSL 1.1.1g - 
- domain joined with sssd

**Client OperatingSystem**
Windows 10 Enterprise
- domain joined

**What is failing**
From my windows domain joined machine I can authenticate to the linux machine via kerberos but do not get a ticket on the machine itself. Looking in the logs I see:

```
debug1: Delegating credentials
debug1: sspi delegation was requested but not fulfilled
debug1: Authentication succeeded (gssapi-with-mic).
```

so while Kerberos logon works, delegation does not and I end up with a remote shell and no Kerberos tickets. In my ssh_config I have:

```
	GSSAPIAuthentication yes
	GSSAPIDelegateCredentials yes
```

I have found that:

- Windows to Windows Kerberos delegation works
- Windows to Linux does not
- Linux to Windows delegation works

I had though it to be my linux configuration but was able to use Kerberos delegation from a domain joined macOS client just fine. All tests performed with the same user account in AD.

On the Windows machine I am indeed getting a kerberos ticket for host/linux.mydomain.com (which is why my auth is most likely working). Just unsure why I cannot delegate credentials and get a ticket from windows --> linux

**Expected output**
klist in remote session outputs a ticket

**Actual output**
klist in remote session has no tickets

**Comment by bagajjal** [comment]
@NoMoreFood - Could you please take a look at this one. You are our kerberos expert :)

**Comment by NoMoreFood** [comment]
@bpfoley45 What kind of Kerberos delegation are you attempting to use?

**Comment by bpfoley45** [comment]
> @bpfoley45 What kind of Kerberos delegation are you attempting to use?

That is the interesting part; I am not configuring any Delegation within the linux AD computer object or my user account. To add to this; this is within an AD forest with computers in the root domain and user accounts in the child making anything other than Resource Based Constrained Delegation a no-go. I was about to go this route until I began testing with other clients/OSes.

When I connect from from Windows -> Windows with `ssh -K` I auth and klist shows:

```
domain\myuser@WINDOWSHOST C:\Users\myuser>klist

Current LogonId is 0:0x414150ec

Cached Tickets: (1)

#0>     Client: myuser @ DOMAIN.FQDN
        Server: host/windowshost.fqdn @ DOMAIN.FQDN
        KerbTicket Encryption Type: AES-256-CTS-HMAC-SHA1-96
        Ticket Flags 0x40a10000 -> forwardable renewable pre_authent name_canonicalize
        Start Time: 5/12/2020 8:30:58 (local)
        End Time:   5/12/2020 18:30:58 (local)
        Renew Time: 0
        Session Key Type: AES-256-CTS-HMAC-SHA1-96
        Cache Flags: 0x8 -> ASC
        Kdc Called:
```

On the client host I see:

```
Current LogonId is 0:0x4ef883

Cached Tickets: (3)

#2>     Client: myuser @ DOMAIN.FQDN
        Server: host/windowshost.fqdn @ DOMAIN.FQDN
        KerbTicket Encryption Type: AES-256-CTS-HMAC-SHA1-96
        Ticket Flags 0x40a10000 -> forwardable renewable pre_authent name_canonicalize
        Start Time: 5/12/2020 8:30:58 (local)
        End Time:   5/12/2020 18:30:58 (local)
        Renew Time: 5/12/2020 18:30:58 (local)
        Session Key Type: AES-256-CTS-HMAC-SHA1-96
        Cache Flags: 0x40 -> FAST
        Kdc Called: kdc.DOMAIN.FQDN
```

I can replicate this from macOS -> Windows, macOS -> Linux; just unsure why it doesn't work from Windows -> Linux. I am attempting to see if this is an issue with SSSD/OpenSSH/PAM on the linux side but with the other scenarios working I am not 100% convinced they are the culprits. 

I really want to avoid having to kinit after doing a passwordless auth via SSH to Linux.

**Comment by NoMoreFood** [comment]
Can you see if you have the Windows->Linux issue with PuTTY with GSSAPI?  That's had a few more years of runtime so if you don't have the issue there, I can do a Wireshark trace and see if the token being issued is different for some reason.

**Comment by bpfoley45** [comment]
Yes the problem exists within PUTTY with GSSAPI as well. I though perhaps it could be credential guard causing issues, but it does indeed work Windows -> Windows with that enabled. I also created some test VMs to ensure that I was bypassing that as well as any possible Group Policy settings for our environment.

I have been able to get it to work Windows -> Linux by enabling "Trust this computer for delegation to any service (Kerberos only)" on the Linux computer object. This gets immediate delegation:

```
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Next authentication method: gssapi-with-mic
debug1: Delegating credentials
debug1: Delegating credentials
debug1: Authentication succeeded (gssapi-with-mic).
```

And deselecting that option (after purging tickets on my windows client) goes back to same delegation not fulfilled issue. 

The unconstrained delegation is not an ideal workaround; I have also looked at potential cross domain issues by creating test users in same domain as the linux computer without success.

**Comment by NoMoreFood** [comment]
Well, the good news based on those finding is that everything is probably working as designed in OpenSSH / PuTTY.

But yeah, getting delegation to work on the domain side can sometimes be a challenge.  If unconstrained delegation works when enabled on the Linux box, you may want to triple-check that Credential Guard is actually running on your Windows box (if you want it to be).  Unconstrained delegation works by passing the entire TGT which should be prevented on the source system if Credential Guard is enabled.  Credential Guard has many prerequisites so it's not uncommon for folks to have it "enabled" in Group Policy but not actually "Running" (which can be viewed under System Information).

Have you tried setting up resource based constrained delegation between the Linux computer objects when coming from Windows?  Not sure all Linux Kerberos implementations will support it though.

**Comment by bpfoley45** [comment]
I am not so sure Credential Guard is at fault here, as I can get a ticket via SSH to another Windows host both by Putty and Win32_OpenSSH.

I also created standalone virtual machines joined to the domain and blocking inheritance. Also to remove any doubts I created 2 new users: one in the same root domain as the linux machine and another in the child domain where we keep all other user accounts, group membership is only Domain Users.

I have tried using resource based constrained delegation and placing the windows machine into the PrincipalsAllowedToDelegateToAccount attribute of the Linux machine, but this does not work.

In fact, looking closer at the debug output of Windows -> WIndows I still see:

```
debug1: Authentications that can continue: publickey,gssapi-with-mic,keyboard-interactive
debug1: Next authentication method: gssapi-with-mic
debug1: Delegating credentials
debug1: sspi delegation was requested but not fulfilled
debug1: Delegating credentials
debug1: sspi delegation was requested but not fulfilled
debug1: Authentication succeeded (gssapi-with-mic).
```

but I end up with a `host/windowsserver.fqdn` ticket upon login that has the same timestamp as the client machine with the following: `Ticket Flags 0x40a10000 -> forwardable renewable pre_authent name_canonicalize`

I _think_ I may be going outside the scope of OpenSSH here and maybe walking into an underlying Windows Kerberos layer issue. My reasoning is that the same tickets I receive from the domain on a linux machine or macOS machine delegate just fine via SSH **and** I can delegate OK to another windows machine. There is something going on between windows and non-windows that I need some more understanding or tools to debug further.

**Comment by AJDurant** [comment]
You might need to check things on the AD side to allow delegation on the Linux computer object:
![image](https://user-images.githubusercontent.com/763880/85849427-d6875600-b7a2-11ea-8929-325f208ca182.png)
setting this on the computer object for the Linux server you want to connect to should allow both PuTTY and OpenSSH for Windows to delegate.

You can set the above with powershell:
```powershell
Set-ADComputer -Clear:msDS-AllowedToDelegateTo -Identity:"SERVER_CN" -Server:"DOMAIN_CONTROLLER"
Set-ADAccountControl -Identity:"SERVER_CN" -TrustedForDelegation:$true -TrustedToAuthForDelegation:$false
```

This should probably be limited to the services you need rather than allowing everything, depending on your use case.

**Comment by mgkuhn** [comment]
@bpfoley45: the SSPI client library does check in the `userAccountControl` attribute of the LDAP entry for the computer to which you want to delegate a ticket if that delegation is permitted (e.g., is the bit `TRUSTED_FOR_DELEGATION(524288)` set there, as shown in the GUI screenshot by @AJDurant above). MIT Kerberos (as used on Linux, macOS, and PuTTY with GSSAPI) on the other hand does **not** ask Active Directory for whether the destination computer is trusted for delegation, because (unlike SSPI) MIT Kerberos does not speak LDAP, and reads `/etc/krb5.conf` instead for its policy decisions. Therefore, I suspect @AJDurant's advice may fix your problem. Please confirm.

Whenever SSPI and GSSAPI behave differently in PuTTY, it has been my experience that SSPI didn't like what it saw in Active Directory's LDAP data (encryption types not permitted in `msDS-SupportedEncryptionTypes`, delegation not permitted in `userAccountControl`, cross-domain trust not configured correctly, etc.), whereas GSSAPI simply didn't look.

Yes, the fact that the “Trust this computer for delegation” check is implemented decentrally in the client, and not in the KDC, surprised me too, because that seems counter-intuitive from a security perspective: if the client has been compromised, the adversary can bypass that check there. All this shows us is that the constraints on delegating tickets that Microsoft has tried to add to its SSPI implementation of Kerberos are probably not as big a huge security improvement as they might seem: they can be ignored in the client, and _are_ in fact ignored by MIT Kerberos for Windows.

**Comment by bartecargo** [comment]
Is it possible that someone could summarise how Windows -> Linux SSO should be configured in the documentation page?

* [Login using Kerberos Authentication](https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples#login-using-kerberos-authentication)

I've set up my Linux server according to that documentation, which does add gssapi to the list of authentications:

```
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Next authentication method: gssapi-with-mic
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Next authentication method: publickey
```

However, I still can't a seamless login experience using `ssh -K host.domain`. When I enter my domain password at the ssh password prompt, I am able to log in. I've also tried enabling "Trust this computer for delegation to any service (Kerberos only)" for the Linux machine in AD and purging local tickets with `klist purge`, but this didn't make any difference for me. 

I'm running `OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3`.

How can I diagnose the problem further?

**Comment by mgkuhn** [comment]
@bpfoley45 Was your original delegation problem solved? If so, can you please close this issue?
@bartecargo Please open a new issue for your new problem, and I'll try to answer there, Otherwise discussions of different people's issues get intertwined here. (This issue is about *delegation* not working for @bpfoley45 's particular setup.)

**Comment by bpfoley45** [comment]
@mgkuhn Yes, your explanation in regards to how GSSAPI behaves on different platforms mirrors my hands on experience. By granting Kerberos delegation, the problem is resolved.
