### ISSUE TITLE
Unable to use public key authentication with sshd

### ISSUE THREAD

**Issue by edwardsp** [PowerShell/Win32-OpenSSH#1608]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 7.7.2.1
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows Server 2019 Datacenter
**Client OperatingSystem**
CentOS 7.7
**What is failing**
Public key authentication is not working.  I am using a new install and using the az cli to invoke the following:
```
param($sshkey)

Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

Start-Service sshd
# OPTIONAL but recommended:
Set-Service -Name sshd -StartupType 'Automatic'
# Confirm the Firewall rule is configured. It should be created automatically by setup. 
Get-NetFirewallRule -Name *ssh*
# There should be a firewall rule named "OpenSSH-Server-In-TCP", which should be enabled
# If the firewall does not exist, create one
New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22

# set default shell to powershell
New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force

cd C:\ProgramData\ssh
echo $sshkey > administrators_authorized_keys
icacls administrators_authorized_keys /inheritance:r
icacls administrators_authorized_keys /grant SYSTEM:`(F`)
icacls administrators_authorized_keys /grant BUILTIN\Administrators:`(F`)
```

**Expected output**
From the CentOS VM I should be able to log in without typing my password.
**Actual output**
Password is always requested

**Comment by billdinger** [comment]
Can you spit out the debug logs? [how to do so here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities)

Looking at what you posted it _looks_ fine.

**Comment by edwardsp** [comment]
I have resolved this issue.  The problem occurs where I write `administrators_authorized_keys`.  The script initially posted writes in unicode.  The following works correctly:

    echo $sshkey | Set-Content -LiteralPath administrators_authorized_keys -Encoding Default
