### ISSUE TITLE
ssh-keygen -N does not allow empty password

### ISSUE THREAD

**Issue by babin93** [PowerShell/Win32-OpenSSH#1609]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
7.7.2.2
 
**Server OperatingSystem**
Does not apply

**Client OperatingSystem**
Windows

**What is failing**
When I do
 `ssh-keygen -q -t rsa -f C:/tmp/id_rsa -N ''` 
or 
`ssh-keygen -q -t rsa -f C:/tmp/id_rsa -N ""`
or
`ssh-keygen -q -t rsa -f C:/tmp/id_rsa -N`

I get an error.

I want to automate key generation, therefore, the workarround of not using the -N option and leaving the password field empty when prompted does not really work for me.

**Expected output**
No output, Like when I run the same command in WSL

**Actual output**
`option requires an argument -- N`

**Comment by bagajjal** [comment]
You should use -P.

In a powershell window try this,
.\ssh-keygen.exe -t rsa -f id_rsa_1 -P `"`"

**Comment by babin93** [comment]
@bagajjal, I actually get the same error message with your command

`option requires an argument --P`

**Comment by babin93** [comment]
@bagajjal Could the issue be reopened ? This solution does not fix my problem.

**Comment by babin93** [comment]
@bagajjal, could we reopen this issue. The proposed fix does not work for me.

**Comment by bagajjal** [comment]
@babin93 - Didn't realize the quotes are messed up..  Try the below command in a powershell window


![image](https://user-images.githubusercontent.com/23668037/83821384-1b780b00-a683-11ea-93aa-383ed6da8b15.png)
