### ISSUE TITLE
run python pywinauto GUI automation script with win-openssh in windows 2012R2

### ISSUE THREAD

**Issue by wuwentao** [PowerShell/Win32-OpenSSH#1610]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 
`OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2`

**Server OperatingSystem**

`Windows Server 2012 R2 Standard`

in fact, we need to support all Windows 10/Windows 2016/Windows 2019, also include old windows 7 and windows 2008 R2 for GUI automation testing purpose.

**Client OperatingSystem**
`Ubuntu 16.04 LTS`
or Ubuntu18.04 LTS/20.04 LTS/CentOS 7/CentOS 8 
OS will using ssh client or `python paramiko` ssh client lib to access `windows openssh` service and run `pywinauto GUI script` .

**What is failing**
openssh can't run pywinauto GUI script

**Expected output**
openssh can execute python script with administrator permission and start GUI or get windows dialog

**Actual output**

the same command line can be execute in `cmd.exe` or `powershell.exe` after remote desktop to windows.
or using a user-define Perl script with (`IO::Socket::INET/IO::Select`) to execute the same command (add to startup with a simple perl script, not running as service)

but openssh can't work with the same command line script, it maybe GUI permission issue or openssh service permission issue.

```
user@ubuntu16:~/public_html/rli539$ ssh Administrator@win2012r2-vm02.xxx.net
Administrator@win2012r2-vm02.xxx.net's password:
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

administrator@WIN2012R2-VM02 C:\Users\Administrator>python --version
Python 3.7.4

administrator@WIN2012R2-VM02 C:\Users\Administrator>py c:/scripts/gui/gui.py
check IMS Admin GUI window running status
IMS Admin exe is : imsAdmin.exe
IMS Admin path is :C:\Program Files (x86)\xxx Management Service\bin\imsAdmin.exe
IMS Admin pid is :5480
IMS Admin process already running, will reconnect to it
Traceback (most recent call last):
  File "c:/scripts/gui/gui.py", line 60, in <module>
    gui = ims.ims()
  File "c:/scripts/gui/gui.py", line 61, in __init__
    self._run_ims(pid=pid)
  File "c:/scripts/gui/gui.py", line 90, in _run_jims
    self.dialog_close()
  File "c:/scripts/gui/gui.py", line 165, in dialog_close
    self.dialog_get()
  File "c:/scripts/gui/gui.py", line 141, in dialog_get
    self.dlg = self.app.top_window()
  File "C:\Python\Python37\lib\site-packages\pywinauto\application.py", line 1156, in top_window
    raise RuntimeError("No windows for that process could be found")
RuntimeError: No windows for that process could be found

administrator@WIN2012R2-VM02 C:\Users\Administrator>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Administrator\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=WIN2012R2-VM02
ComSpec=C:\Windows\system32\cmd.exe
DEFLOGDIR=C:\ProgramData\McAfee\Endpoint Security\Logs
FP_NO_HOST_CHECK=NO
HOME=C:\Users\Administrator
HOMEDRIVE=C:
HOMEPATH=\Users\Administrator
LOCALAPPDATA=C:\Users\Administrator\AppData\Local
LOGNAME=administrator
NUMBER_OF_PROCESSORS=4
OS=Windows_NT
Path=C:\Program Files\OpenSSH;C:\Python\Python37\Scripts\;C:\Python\Python37\;C:\Windows\system32;C:\Windows;C:\Windows\System32
Connection to win2012r2-vm02.xxx.net closed.t
```

**Comment by bagajjal** [comment]
@wuwentao - You can't run GUI applications over SSH.  This is expected behavior.

**Comment by wuwentao** [comment]
@bagajjal 
really thank you very much for your quickly response, I have some question:

1. why we can't run GUI appliation over SSH?  sorry, I'm newbie about it , and didn't found these info in Wiki document (maybe I missed it, I'm not sure)

2. Is there any good solution to run GUI application from linux to windows via command line python script ?
in fact, we have a perl script can do it, just want to confirm with openssh or more tools?

Thanks

**Comment by bagajjal** [comment]
Windows GUI applications are different from Linux X11 applications.
X11 separates the rendering and reacting to the key board or mouse events.
You can launch X11 applications like (xedit, xclock) over SSH by connecting to linux SSHD service.
Rending will be done on the client side which requires X servers running on client machine.. The X server will send the key board, mouse events to X client running on the ssh server. X client will dictate how to render on the ssh client side.

There is no way to launch windows GUI applications. You need to automate your scenario. Powershell is a great automation tool as it's the core windows management language and it's cross platform. You can run same powershell scripts/modules on linux/mac.

**Comment by techchrism** [comment]
I was able to get GUI applications running outside of session 0 by using PsExec and the `-i` option.
My command looks like this: `.\PsExec.exe -accepteula \\{computer} -u {username} -p {password} -i 1 {command}`
Another possible option is https://stackoverflow.com/questions/25726172/launch-process-from-session-0-isolation but I have not tried this on Windows 10.
I'm still looking for a simple alternative to PsExec that doesn't involve typing the password each time or storing it in a script.
