### ISSUE TITLE
New-PSSession long connect and return null

### ISSUE THREAD

**Issue by Timka654** [PowerShell/Win32-OpenSSH#1612]
OpenSSH Client:
0.0.1.0
Client OS:
Windows 10 (1909)
Server OS:
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-101-generic x86_64)
PowerShell:
7.0.1 (on client and server too)
Problem:
Cannot open ssh session on New-PSSession -HostName $sshAddress -UserName $sshUser command, long time try connect and return null without messages, ssh use private/public key sign

Long time i'm publish project with .ps script, but today i'm have this problem, before have the problem i'm 
- install
LLVM
Python 3.83
Python 2.75
- uninstall
Python 3.80
Ubuntu 18.04 (WSL) - not executed any
- update
PowerShell 7.0.0 to 7.0.1
Visual Studio Build Tools 2017 to latest

What I've already try
- return llvm and python to back... no effect
- reinstall OpenSSH Client + Server... no effect
- try to connect another project host... have problem too
- try connect to host who not have powershell... have message
New-PSSession: [194.87.103.100] The background process reported an error with the following message: The SSH client session has ended with error message: subsystem request failed on channel 0.
- try connect from PowerShell with ssh root@<ip> command... every ok, but i'm cannot use this on my script
- open ssh auth.log on server... have messages
May 24 00:04:52 appfoxCRM sshd[3398]: pam_unix(sshd:session): session opened for user root by (uid=0)
May 24 00:04:53 appfoxCRM sshd[3398]: Received disconnect from <ip> port <port>:11: disconnected by user
May 24 00:04:53 appfoxCRM sshd[3398]: Disconnected from user root <ip> port <port>
May 24 00:04:53 appfoxCRM sshd[3398]: pam_unix(sshd:session): session closed for user root

next i'm trying
- try scenario from VM as client
- install PowerShell 7.0.0

I'm not have another variants, hope this help, but maybe who have solution at now

**Comment by Timka654** [comment]
- try scenario from VM as client.. have problem too

**Comment by bagajjal** [comment]
@Timka654  - If the plain ssh (ssh user@ip) works fine then you need to raise the bug against powershell repo (https://github.com/PowerShell/powershell)
