### ISSUE TITLE
Permission denied (publickey,keyboard-interactive)

### ISSUE THREAD

**Issue by yianzhongguo** [PowerShell/Win32-OpenSSH#1614]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
8.1.0.0
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 Pro
**Client OperatingSystem**
CentOS Linux release 7.6.1810 (Core)
**What is failing**
I want to connect to my windows 10 pro computer using the following command on my linux server. 
       ssh yian_T@222.200.163.203 -p 22
I installed OpenSSH in my windows 10 pro computer. My windows 10 pro computer is in a wireless area network environment and I set it as a port 22. 

My sshd_config is set as follows:

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey __PROGRAMDATA__/ssh/ssh_host_rsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_dsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ecdsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
#LogLevel INFO
SyslogFacility LOCAL0
LogLevel DEBUG3

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes no
#MaxAuthTries 6
#MaxSessions 10

PubkeyAuthentication yes
# RSAAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile	C:/Users/yian.YIAN_T/.ssh/authorized_keys

#AuthorizedPrincipalsFile none

# For this to work you will also need host keys in %programData%/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
PasswordAuthentication no
PermitEmptyPasswords no

# GSSAPI options
#GSSAPIAuthentication no

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#PermitUserEnvironment no
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# override default of no subsystems
Subsystem	sftp	sftp-server.exe

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	AllowTcpForwarding no
#	PermitTTY no
#	ForceCommand cvs server

#Match Group administrators
#       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys

**Expected output**

**Actual output**
Permission denied (publickey,keyboard-interactive)

**The content of sshd.log is as follows:** 
26600 2020-06-01 17:09:07.252 debug2: fd 3 setting O_NONBLOCK
26600 2020-06-01 17:09:07.252 debug3: sock_set_v6only: set socket 3 IPV6_V6ONLY
26600 2020-06-01 17:09:07.252 debug1: Bind to port 22 on ::.
26600 2020-06-01 17:09:07.252 Server listening on :: port 22.
26600 2020-06-01 17:09:07.252 debug2: fd 4 setting O_NONBLOCK
26600 2020-06-01 17:09:07.252 debug1: Bind to port 22 on 0.0.0.0.
26600 2020-06-01 17:09:07.252 Server listening on 0.0.0.0 port 22.
26600 2020-06-01 17:10:25.630 debug3: fd 5 is not O_NONBLOCK
26600 2020-06-01 17:10:25.632 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" -R
26600 2020-06-01 17:10:25.634 debug3: send_rexec_state: entering fd = 8 config len 304
26600 2020-06-01 17:10:25.634 debug3: ssh_msg_send: type 0
26600 2020-06-01 17:10:25.635 debug3: send_rexec_state: done
9584 2020-06-01 17:10:25.656 debug1: inetd sockets after dupping: 4, 4
9584 2020-06-01 17:10:25.656 Connection from 222.200.179.21 port 37254 on 192.168.1.110 port 22
9584 2020-06-01 17:10:25.656 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
9584 2020-06-01 17:10:25.656 debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1
9584 2020-06-01 17:10:25.656 debug1: match: OpenSSH_6.6.1 pat OpenSSH_6.6.1* compat 0x04000002
9584 2020-06-01 17:10:25.656 debug2: fd 4 setting O_NONBLOCK
9584 2020-06-01 17:10:25.666 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" -y
9584 2020-06-01 17:10:25.668 debug2: Network child is on pid 27348
9584 2020-06-01 17:10:25.668 debug3: send_rexec_state: entering fd = 6 config len 304
9584 2020-06-01 17:10:25.668 debug3: ssh_msg_send: type 0
9584 2020-06-01 17:10:25.668 debug3: send_rexec_state: done
9584 2020-06-01 17:10:25.668 debug3: ssh_msg_send: type 0
9584 2020-06-01 17:10:25.668 debug3: ssh_msg_send: type 0
9584 2020-06-01 17:10:25.668 debug3: preauth child monitor started
9584 2020-06-01 17:10:25.686 debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-ed25519 [preauth]
9584 2020-06-01 17:10:25.686 debug3: send packet: type 20 [preauth]
9584 2020-06-01 17:10:25.686 debug1: SSH2_MSG_KEXINIT sent [preauth]
9584 2020-06-01 17:10:25.686 debug3: receive packet: type 20 [preauth]
9584 2020-06-01 17:10:25.686 debug1: SSH2_MSG_KEXINIT received [preauth]
9584 2020-06-01 17:10:25.686 debug2: local server KEXINIT proposal [preauth]
9584 2020-06-01 17:10:25.686 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1 [preauth]
9584 2020-06-01 17:10:25.686 debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-ed25519 [preauth]
9584 2020-06-01 17:10:25.686 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
9584 2020-06-01 17:10:25.686 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
9584 2020-06-01 17:10:25.686 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
9584 2020-06-01 17:10:25.686 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
9584 2020-06-01 17:10:25.686 debug2: compression ctos: none,zlib@openssh.com [preauth]
9584 2020-06-01 17:10:25.686 debug2: compression stoc: none,zlib@openssh.com [preauth]
9584 2020-06-01 17:10:25.686 debug2: languages ctos:  [preauth]
9584 2020-06-01 17:10:25.686 debug2: languages stoc:  [preauth]
9584 2020-06-01 17:10:25.686 debug2: first_kex_follows 0  [preauth]
9584 2020-06-01 17:10:25.686 debug2: reserved 0  [preauth]
9584 2020-06-01 17:10:25.686 debug2: peer client KEXINIT proposal [preauth]
9584 2020-06-01 17:10:25.686 debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 [preauth]
9584 2020-06-01 17:10:25.686 debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss [preauth]
9584 2020-06-01 17:10:25.686 debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se [preauth]
9584 2020-06-01 17:10:25.686 debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se [preauth]
9584 2020-06-01 17:10:25.686 debug2: MACs ctos: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96 [preauth]
9584 2020-06-01 17:10:25.686 debug2: MACs stoc: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96 [preauth]
9584 2020-06-01 17:10:25.686 debug2: compression ctos: none,zlib@openssh.com,zlib [preauth]
9584 2020-06-01 17:10:25.686 debug2: compression stoc: none,zlib@openssh.com,zlib [preauth]
9584 2020-06-01 17:10:25.686 debug2: languages ctos:  [preauth]
9584 2020-06-01 17:10:25.686 debug2: languages stoc:  [preauth]
9584 2020-06-01 17:10:25.686 debug2: first_kex_follows 0  [preauth]
9584 2020-06-01 17:10:25.686 debug2: reserved 0  [preauth]
9584 2020-06-01 17:10:25.686 debug1: kex: algorithm: curve25519-sha256@libssh.org [preauth]
9584 2020-06-01 17:10:25.686 debug1: kex: host key algorithm: ssh-ed25519 [preauth]
9584 2020-06-01 17:10:25.686 debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none [preauth]
9584 2020-06-01 17:10:25.686 debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none [preauth]
9584 2020-06-01 17:10:25.686 debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
9584 2020-06-01 17:10:25.697 debug3: receive packet: type 30 [preauth]
9584 2020-06-01 17:10:25.701 debug3: mm_sshkey_sign entering [preauth]
9584 2020-06-01 17:10:25.701 debug3: mm_request_send entering: type 6 [preauth]
9584 2020-06-01 17:10:25.701 debug3: mm_sshkey_sign: waiting for MONITOR_ANS_SIGN [preauth]
9584 2020-06-01 17:10:25.701 debug3: mm_request_receive_expect entering: type 7 [preauth]
9584 2020-06-01 17:10:25.701 debug3: mm_request_receive entering [preauth]
9584 2020-06-01 17:10:25.701 debug3: mm_request_receive entering
9584 2020-06-01 17:10:25.701 debug3: monitor_read: checking request 6
9584 2020-06-01 17:10:25.701 debug3: mm_answer_sign
9584 2020-06-01 17:10:25.702 debug3: mm_answer_sign: KEX signature 0000020AF7248D50(83)
9584 2020-06-01 17:10:25.702 debug3: mm_request_send entering: type 7
9584 2020-06-01 17:10:25.702 debug2: monitor_read: 6 used once, disabling now
9584 2020-06-01 17:10:25.702 debug3: send packet: type 31 [preauth]
9584 2020-06-01 17:10:25.703 debug3: send packet: type 21 [preauth]
9584 2020-06-01 17:10:25.703 debug2: set_newkeys: mode 1 [preauth]
9584 2020-06-01 17:10:25.703 debug1: rekey out after 4294967296 blocks [preauth]
9584 2020-06-01 17:10:25.703 debug1: SSH2_MSG_NEWKEYS sent [preauth]
9584 2020-06-01 17:10:25.703 debug1: expecting SSH2_MSG_NEWKEYS [preauth]
9584 2020-06-01 17:10:25.730 debug3: receive packet: type 21 [preauth]
9584 2020-06-01 17:10:25.730 debug1: SSH2_MSG_NEWKEYS received [preauth]
9584 2020-06-01 17:10:25.730 debug2: set_newkeys: mode 0 [preauth]
9584 2020-06-01 17:10:25.730 debug1: rekey in after 4294967296 blocks [preauth]
9584 2020-06-01 17:10:25.730 debug1: KEX done [preauth]
9584 2020-06-01 17:10:25.790 debug3: receive packet: type 5 [preauth]
9584 2020-06-01 17:10:25.790 debug3: send packet: type 6 [preauth]
9584 2020-06-01 17:10:25.797 debug3: receive packet: type 50 [preauth]
9584 2020-06-01 17:10:25.797 debug1: userauth-request for user yian_T service ssh-connection method none [preauth]
9584 2020-06-01 17:10:25.797 debug1: attempt 0 failures 0 [preauth]
9584 2020-06-01 17:10:25.797 debug3: mm_getpwnamallow entering [preauth]
9584 2020-06-01 17:10:25.797 debug3: mm_request_send entering: type 8 [preauth]
9584 2020-06-01 17:10:25.797 debug3: mm_getpwnamallow: waiting for MONITOR_ANS_PWNAM [preauth]
9584 2020-06-01 17:10:25.797 debug3: mm_request_receive_expect entering: type 9 [preauth]
9584 2020-06-01 17:10:25.797 debug3: mm_request_receive entering [preauth]
9584 2020-06-01 17:10:25.797 debug3: mm_request_receive entering
9584 2020-06-01 17:10:25.797 debug3: monitor_read: checking request 8
9584 2020-06-01 17:10:25.797 debug3: mm_answer_pwnamallow
9584 2020-06-01 17:10:25.797 debug3: get_passwd: Invalid account type: 3.
9584 2020-06-01 17:10:25.797 debug2: parse_server_config: config reprocess config len 304
9584 2020-06-01 17:10:25.797 Invalid user yian_T from 222.200.179.21 port 37254
9584 2020-06-01 17:10:25.797 debug3: mm_answer_pwnamallow: sending MONITOR_ANS_PWNAM: 0
9584 2020-06-01 17:10:25.797 debug3: mm_request_send entering: type 9
9584 2020-06-01 17:10:25.798 debug2: monitor_read: 8 used once, disabling now
9584 2020-06-01 17:10:25.798 debug3: mm_inform_authserv entering [preauth]
9584 2020-06-01 17:10:25.798 debug3: mm_request_send entering: type 4 [preauth]
9584 2020-06-01 17:10:25.798 debug2: input_userauth_request: try method none [preauth]
9584 2020-06-01 17:10:25.798 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
9584 2020-06-01 17:10:25.798 debug3: ensure_minimum_time_since: elapsed 0.919ms, delaying 6.613ms (requested 7.532ms) [preauth]
9584 2020-06-01 17:10:25.798 debug3: mm_request_receive entering
9584 2020-06-01 17:10:25.798 debug3: monitor_read: checking request 4
9584 2020-06-01 17:10:25.798 debug3: mm_answer_authserv: service=ssh-connection, style=
9584 2020-06-01 17:10:25.798 debug2: monitor_read: 4 used once, disabling now
9584 2020-06-01 17:10:25.805 debug3: userauth_finish: failure partial=0 next methods="publickey,keyboard-interactive" [preauth]
9584 2020-06-01 17:10:25.805 debug3: send packet: type 51 [preauth]
9584 2020-06-01 17:10:25.810 debug3: receive packet: type 50 [preauth]
9584 2020-06-01 17:10:25.810 debug1: userauth-request for user yian_T service ssh-connection method publickey [preauth]
9584 2020-06-01 17:10:25.810 debug1: attempt 1 failures 0 [preauth]
9584 2020-06-01 17:10:25.810 debug2: input_userauth_request: try method publickey [preauth]
9584 2020-06-01 17:10:25.810 debug2: userauth_pubkey: invalid user yian_T querying public key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDESHoKEMuhxDoZsoakp5Sz3szXyti/hMaIwafYMrT2TkNnq0E4gJb3e+eVDcoAZjO1WSCm6y/EGA7tVUD8/CWyjJWEvgJgamAlsJpuiYFFh6lvicrATRyLvLf1qRWr5fo4tUr+YdVUs//4v+/qjJmuMvzB2KEq+JNMW7dGn2TCM0QWyXcXKdllitJjMZsVVBUhX5N8+OI4uiXL6K1zH+EOhZ0Bg+tfovn2+XolhaYIGAqPIdpg+s0HfjKCM+HK5le83gjSyr+qjWo9x3KLXWzKd8ZkBpwnASRAaNAFBYzNYtzAyXjod9g/7BDSL5RyLPeWeToSt8ZteyooZsGhBlgh [preauth]
9584 2020-06-01 17:10:25.810 debug1: userauth_pubkey: test pkalg ssh-rsa pkblob RSA SHA256:VRhM5dYyCvm9FK9VgEwkJcjVJ2XXoLjt3FZ7va0fXM4 [preauth]
9584 2020-06-01 17:10:25.810 debug2: userauth_pubkey: disabled because of invalid user [preauth]
9584 2020-06-01 17:10:25.810 debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa [preauth]
9584 2020-06-01 17:10:25.810 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
9584 2020-06-01 17:10:25.810 debug3: ensure_minimum_time_since: elapsed 0.000ms, delaying 7.532ms (requested 7.532ms) [preauth]
9584 2020-06-01 17:10:25.818 debug3: userauth_finish: failure partial=0 next methods="publickey,keyboard-interactive" [preauth]
9584 2020-06-01 17:10:25.818 debug3: send packet: type 51 [preauth]
9584 2020-06-01 17:10:25.826 debug3: receive packet: type 50 [preauth]
9584 2020-06-01 17:10:25.826 debug1: userauth-request for user yian_T service ssh-connection method keyboard-interactive [preauth]
9584 2020-06-01 17:10:25.826 debug1: attempt 2 failures 1 [preauth]
9584 2020-06-01 17:10:25.826 debug2: input_userauth_request: try method keyboard-interactive [preauth]
9584 2020-06-01 17:10:25.826 debug1: keyboard-interactive devs  [preauth]
9584 2020-06-01 17:10:25.826 debug1: auth2_challenge: user=yian_T devs= [preauth]
9584 2020-06-01 17:10:25.826 debug1: kbdint_alloc: devices '' [preauth]
9584 2020-06-01 17:10:25.826 debug2: auth2_challenge_start: devices  [preauth]
9584 2020-06-01 17:10:25.826 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
9584 2020-06-01 17:10:25.826 debug3: ensure_minimum_time_since: elapsed 0.000ms, delaying 7.532ms (requested 7.532ms) [preauth]
9584 2020-06-01 17:10:25.834 debug3: userauth_finish: failure partial=0 next methods="publickey,keyboard-interactive" [preauth]
9584 2020-06-01 17:10:25.834 debug3: send packet: type 51 [preauth]
9584 2020-06-01 17:10:25.859 Connection closed by invalid user yian_T 222.200.179.21 port 37254 [preauth]
9584 2020-06-01 17:10:25.859 debug1: do_cleanup [preauth]
9584 2020-06-01 17:10:25.861 debug3: mm_request_receive entering
9584 2020-06-01 17:10:25.861 debug1: do_cleanup
9584 2020-06-01 17:10:25.861 debug1: Killing privsep child 27348

**Comment by bagajjal** [comment]
@yianzhongguo - Looks like the username and the machine name are same (yian_T).. There is a known bug that can cause this issue. For now, you can create a different user whose name doesn't match with the machine name.

**Comment by yianzhongguo** [comment]
@bagajjal Thank you very much! I'll try your suggestion as soon as possible.

**Comment by yianzhongguo** [comment]
@bagajjal I've tried it as you said and I succeed. You are professional and the the reason really is that the name of my account is the same as the name of my computer. Thanks again!
