### ISSUE TITLE
No log for file transfer

### ISSUE THREAD

**Issue by daniel-shukuya** [PowerShell/Win32-OpenSSH#1615]
Please answer the following

**"OpenSSH for Windows" version**
8.1.0.0
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
My sshd.log doesn't log transfer files.

**Expected output**
File transfer log in sshd.log file.

**Actual output**
The log file always displays:
2220 2020-06-01 13:18:05.371 Server listening on :: port 22.
2220 2020-06-01 13:18:05.371 Server listening on 0.0.0.0 port 22.
668 2020-06-01 13:18:11.746 Accepted password for sftp from 127.0.0.1 port 49920 ssh2
4468 2020-06-01 13:18:18.111 Accepted password for sftp from 127.0.0.1 port 49921 ssh2

Hi!

My sshd.log doesn't log file transfer.

I tested all combinations of sshd_config:
SyslogFacility LOCAL0, and AUTH(event viewer)
LogLevel INFO, DEBUG, VERBOSE (etc)

and no log lines for file transfer.

I also tried in Windows Server 2016 and Windows 10 v18363.
Also tried 64bit (v8.1.0.0p1-Beta) and 32bit installation.
Also tried install by powershell and manually.

Thanks!

**Comment by bagajjal** [comment]
Please note any changes to sshd_config file should require a sshd service restart (net stop sshd; net start sshd).

If you are expecting the sftp server logs then it will be a different file (sftp-server.log). You need to have the below configuration in sshd_config file ($env:programdata\ssh\sshd_config).

Subsystem	sftp	sftp-server.exe -f LOCAL0 -l DEBUG3

**Comment by daniel-shukuya** [comment]
> Please note any changes to sshd_config file should require a sshd service restart (net stop sshd; net start sshd).
> 
> If you are expecting the sftp server logs then it will be a different file (sftp-server.log). You need to have the below configuration in sshd_config file ($env:programdata\ssh\sshd_config).
> 
> Subsystem sftp sftp-server.exe -f LOCAL0 -l DEBUG3

Yes, I always restart the "Open SSH Server".

I also try the line that you suggest "Subsystem sftp sftp-server.exe -f LOCAL0 -l DEBUG3". But in this case doesn't even log the file in "C:\ProgramData\ssh\logs"

So weird.

Here is my actual sshd_config:

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey __PROGRAMDATA__/ssh/ssh_host_rsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_dsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ecdsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
SyslogFacility LOCAL0
LogLevel DEBUG3

# Authentication:
AllowUsers sftp

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile	.ssh/authorized_keys

#AuthorizedPrincipalsFile none

# For this to work you will also need host keys in %programData%/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication yes
#PermitEmptyPasswords no

# GSSAPI options
#GSSAPIAuthentication no

#AllowAgentForwarding yes
AllowTcpForwarding no
GatewayPorts no
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#PermitUserEnvironment no
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# override default of no subsystems
Subsystem	sftp	sftp-server.exe -f LOCAL0 -l DEBUG3

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	AllowTcpForwarding no
#	PermitTTY no
#	ForceCommand cvs server

Match Group administrators
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys

I attached the log file in DEBUG3 mode and no record for transfer files.

[sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/4712520/sshd.log)

**Comment by bagajjal** [comment]
@invol2ver - Is your sftp connection successful? Are you able to transfer files? 
Looking at the last few lines of sshd.log file shows you don't have DEBUG3 enabled.. 

2752 2020-06-01 13:43:55.885 Server listening on :: port 22.
2752 2020-06-01 13:43:55.885 Server listening on 0.0.0.0 port 22.
976 2020-06-01 13:44:02.679 Accepted password for sftp from 127.0.0.1 port 50157 ssh2
7328 2020-06-01 13:44:07.903 Accepted password for sftp from 127.0.0.1 port 50158 ssh2

**Comment by daniel-shukuya** [comment]
> @invol2ver - Is your sftp connection successful? Are you able to transfer files?
> Looking at the last few lines of sshd.log file shows you don't have DEBUG3 enabled..
> 
> 2752 2020-06-01 13:43:55.885 Server listening on :: port 22.
> 2752 2020-06-01 13:43:55.885 Server listening on 0.0.0.0 port 22.
> 976 2020-06-01 13:44:02.679 Accepted password for sftp from 127.0.0.1 port 50157 ssh2
> 7328 2020-06-01 13:44:07.903 Accepted password for sftp from 127.0.0.1 port 50158 ssh2

Yes, im able to transfer files without any problem! Im using filezilla.

Sorry, the lines that you mention are in LogLevel INFO mode.
The previous attached log file is in DEBUG3 mode. (https://github.com/PowerShell/Win32-OpenSSH/files/4712520/sshd.log)


I attach here a printscreen of filezilla upload:
![filezilla upload](https://user-images.githubusercontent.com/3927216/83437445-29752400-a416-11ea-8f9a-7a17d81c89ee.jpg)

**Comment by daniel-shukuya** [comment]
> Please note any changes to sshd_config file should require a sshd service restart (net stop sshd; net start sshd).
> 
> If you are expecting the sftp server logs then it will be a different file (sftp-server.log). You need to have the below configuration in sshd_config file ($env:programdata\ssh\sshd_config).
> 
> Subsystem sftp sftp-server.exe -f LOCAL0 -l DEBUG3

@bagajjal finally i got it!

It was necessary to add the local sftp user as administrator for writting the sftp-server.log!

it's ok for an external user to be an administrator of the pc? Is there any way to avoid this?

**Comment by bagajjal** [comment]
@invol2ver - We don't recommend using file based logging in a production environment.
You should use the ETW based logging in production environment which doesn't have this problem.

File based logging is useful for easy debugging and we suggest to avoid in production. 
It's a known issue that non-admin users can't write the logs to the sftp-server.log/sshd.log.

**Comment by daniel-shukuya** [comment]
> @invol2ver - We don't recommend using file based logging in a production environment.
> You should use the ETW based logging in production environment which doesn't have this problem.
> 
> File based logging is useful for easy debugging and we suggest to avoid in production.
> It's a known issue that non-admin users can't write the logs to the sftp-server.log/sshd.log.

Thanks @bagajjal ! But...

If I remove the local user from the group of Administrators and change the line "Subsystem sftp sftp-server.exe -f AUTH -l INFO" there is NO record of file transfers in ETW. Only get this line in ETW "sshd: Accepted password for sftp from 127.0.0.1 port 51924 ssh2".

Then add the local user back to the administrators group and now i finally have file transfer logs in ETW. How can I prevent the local user from being an Administrator?

**Comment by bagajjal** [comment]
@invol2ver - Event viewer has 3 channels (Admin, Debug, Operational). Admin channel is restricted for administrators on the machine, non-admin users can't write to this channel. Non-admin users can write to Debug, Operational channels. For testing purpose, set the log level as DEBUG3 and check these channels.

Incase if you are fine with file based logged then you can add the non-admin user to have write permissions to $env:programdata\ssh\logs\sftp-server.log.

**Comment by daniel-shukuya** [comment]
@bagajjal Perfectly understood.

For me is better login in ETW. But still have the problem with Local User and the Administrator Group.

Here is my test:

Scenario 1 (login to sftp and transfer file):
sshd_config: Subsystem sftp sftp-server.exe -f AUTH -l INFO
**local user is NOT Administrator**
EWT: only get this 2 lines in Operational:
- sshd: Server listening on 0.0.0.0 port 22.
- sshd: Accepted password for sftp from 127.0.0.1 port 52052 ssh2

Scenario 2 (login to sftp and transfer file):
sshd_config: Subsystem sftp sftp-server.exe -f AUTH -l INFO
**local user is Administrator**
EWT: Operational tree:
- finally i get the file transfer line log: "sftp-server: open "/C:/Users/sftp/Downloads/filezilla upload.jpg" flags WRITE,CREATE,TRUNCATE mode 0666"

I'm missing some configuration?

Thanks for the patience!

**Comment by bagajjal** [comment]
@invol2ver  - This issue is specific to non-admin users whether we use ETW (or) File based logging. This is a known bug.

Subsystem sftp sftp-server.exe -f AUTH -l DEBUG3

I would suggest enabling DEBUG3 for sftp-server.log which should capture the files upload/downloaded in the DEBUG channel. Having DEBUG3 for sftp-server.log shouldn't cause too many traces. Please check if this covers your scenario.

**Comment by bagajjal** [comment]
@invol2ver  - Here is the existing bug 
https://github.com/PowerShell/Win32-OpenSSH/issues/1174

**Comment by daniel-shukuya** [comment]
Thanks @bagajjal !
it was driving me crazy!

I will analyze another alternatives because DEBUG3 mode it seems doesn't record file deletion.

**Comment by daniel-shukuya** [comment]
It is planned to solve this Issue?

**Comment by bagajjal** [comment]
@invol2ver - This is a backlog item. This is not prioritized at this time.

**Comment by Algvaldivia** [comment]
> @bagajjal Perfectly understood.
> 
> For me is better login in ETW. But still have the problem with Local User and the Administrator Group.
> 
> Here is my test:
> 
> Scenario 1 (login to sftp and transfer file): sshd_config: Subsystem sftp sftp-server.exe -f AUTH -l INFO **local user is NOT Administrator** EWT: only get this 2 lines in Operational:
> 
> * sshd: Server listening on 0.0.0.0 port 22.
> * sshd: Accepted password for sftp from 127.0.0.1 port 52052 ssh2
> 
> Scenario 2 (login to sftp and transfer file): sshd_config: Subsystem sftp sftp-server.exe -f AUTH -l INFO **local user is Administrator** EWT: Operational tree:
> 
> * finally i get the file transfer line log: "sftp-server: open "/C:/Users/sftp/Downloads/filezilla upload.jpg" flags WRITE,CREATE,TRUNCATE mode 0666"
> 
> I'm missing some configuration?
> 
> Thanks for the patience!

Hi, Daniel,
I so everything above about logging, I have the same issues and much more.
As I see you have more results.
One question, on the install, not any ftpuser is created, you mention it, that user is created manually by you??? How is declared or enrolled this user on SSH configuration?

I will appreciate your answers,
Thanks!

**Comment by Algvaldivia** [comment]
> It is planned to solve this Issue?

Hi, Daniel,
I so everything above about logging, I have the same issues and much more.
As I see you have more results.
One question, on the install, not any ftpuser is created, you mention it, that user is created manually by you??? How is declared or enrolled this user on SSH configuration?

I will appreciate your answers,
Thanks!

**Comment by daniel-shukuya** [comment]
I remember that I had created a Local Active Directory User.
I would like to help you, but im no longer in this project. Sorry!

**Comment by bagajjal** [comment]
The fix is part of V8.6 release

PowerShell/openssh-portable#513

**Comment by Algvaldivia** [comment]
> I remember that I had created a Local Active Directory User.
> I would like to help you, but im no longer in this project. Sorry!

Thanks @daniel-shukuya

**Comment by Algvaldivia** [comment]
> The fix is part of V8.6 release
> 
> PowerShell/openssh-portable#513

Well, I going to test it!
Thanks
