### ISSUE TITLE
ssh.exe exits with code 255 (crash?) after a long running session 

### ISSUE THREAD

**Issue by tigerinus** [PowerShell/Win32-OpenSSH#1616]
Please answer the following

**"OpenSSH for Windows" version**
```
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
```

**Server OperatingSystem**
```
Debian 10 (Buster) 
OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019
```

**Client OperatingSystem**
```
Windows 10 20H1
```

**What is failing**

I always keep a long run SSH session to my remote DEV machine with tmux running. I used to do it using SSH from WSL (Debian 10 Buster). I recently switched to use SSH for Win32 (not the one comes Windows Optional Features, but downloaded directly from Releases from this repo). 

Then I noticed that everytime I left it running for couple of hours, then come back, and try to interact with it (hit a key or click a mouse - yes mouse event is enabled), SSH.exe would exit right away with code 255:

![image](https://user-images.githubusercontent.com/7172560/83475365-cb514b00-a4c0-11ea-9e2f-773a28bb631f.png)

Luckily I got TMUX running, so I can always attach back to the work with nothing lost.

**Expected output**
It should not exit all of sudden.

**Actual output**
It exits all of sudden - feels like a crash but I don't see a dump in WER.

**Comment by bagajjal** [comment]
@tigerinus - I couldn't reproduce on my side. Can you open a fresh window and do ssh -vvv user@ip and leave the session till it disconnects on it's own? We also need server side logs with DEBUG3 enabled for the same session.

**Comment by tigerinus** [comment]
> @tigerinus - I couldn't reproduce on my side. Can you open a fresh window and do ssh -vvv user@ip and leave the session till it disconnects on it's own? We also need server side logs with DEBUG3 enabled for the same session.

I don't want to enable DEBUG level tracing on sshd since it's shared with many other devs in the team.

However I did capture some client side logs, although it's a bit hard to read:

![image](https://user-images.githubusercontent.com/7172560/83625913-41d87080-a5c7-11ea-88dc-ecf167dd898f.png)

--
EDIT: I'm working from home today. I realized the log message I shared above could be due to VPN disconnection.

I will collect client side logs again once I get to office.

**Comment by tigerinus** [comment]
![image](https://user-images.githubusercontent.com/7172560/83873304-26f03280-a766-11ea-92a9-4e81856bb1d4.png)

I repro'ed this in office. Please take a look.

If I use ssh under WSL, this would never happen.

**Comment by bagajjal** [comment]
Error 10054  means  An existing connection was forcibly closed by the remote host.
Looks like the server is closing the connection. Do you have TCPKeepAlive configured?
It's difficult to debug without server side logs

**Comment by tigerinus** [comment]
> Error 10054 means An existing connection was forcibly closed by the remote host.
> Looks like the server is closing the connection. Do you have TCPKeepAlive configured?
> It's difficult to debug without server side logs

I have `TCPKeepAlive yes` set at the server side long time ago. That's fine. I will switch to WSL ssh for now. Thanks.
