### ISSUE TITLE
gssapi-with-mic is failing from windows

### ISSUE THREAD

**Issue by cderemble** [PowerShell/Win32-OpenSSH#1618]
**"OpenSSH for Windows" version**
OpenSSH_8.2p1, OpenSSL 1.1.1f  31 Mar 2020
 
**Server OperatingSystem**
CentOS Linux release 7.5.1804 (Core)

**Client OperatingSystem**
Windows Server 2016 Standard

**What is failing**
The gssapi-with-mic is failing when connecting from a windows machine to a Linux server.
This works from the same machine to the same server using putty.

**Expected output**
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug3: start over, passed a different list publickey,gssapi-keyex,gssapi-with-mic,password
debug3: preferred gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup gssapi-with-mic
debug3: remaining preferred: publickey,keyboard-interactive,password
debug3: authmethod_is_enabled gssapi-with-mic
debug1: Next authentication method: gssapi-with-mic
debug3: send packet: type 50
debug2: we sent a gssapi-with-mic packet, wait for reply
debug3: receive packet: type 60
debug1: Delegating credentials
debug1: sspi delegation was requested but not fulfilled
debug3: send packet: type 61
debug3: receive packet: type 61
debug1: Delegating credentials
debug1: sspi delegation was requested but not fulfilled
debug3: send packet: type 66
debug3: receive packet: type 52
debug1: Authentication succeeded (gssapi-with-mic).

**Actual output**
debug1: Authentications that can continue: publickey,gssapi-with-mic,password,keyboard-interactive
debug3: start over, passed a different list publickey,gssapi-with-mic,password,keyboard-interactive
debug3: preferred gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup gssapi-with-mic
debug3: remaining preferred: publickey,keyboard-interactive,password
debug3: authmethod_is_enabled gssapi-with-mic
debug1: Next authentication method: gssapi-with-mic
debug1:  Miscellaneous failure (see text)
unknown mech-code 2 for mech 1 3 6 1 4 1 311 2 2 10

debug1:  Miscellaneous failure (see text)
get-principal lstat(/tmp/krb5cc_1190891)

debug2: we did not send a packet, disable method
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey

**Comment by bagajjal** [comment]
@cderemble - You are definitely not using our OpenSSH binaries. We don't have V8.2 yet and also we use LibreSSL instead of OpenSSL.

https://github.com/PowerShell/Win32-OpenSSH/releases
