### ISSUE TITLE
Ok to mention chocolatey package in Wiki Install Page?

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#162]
Is it ok to mention that the chocolatey package handles install, upgrade and uninstall on this page: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH ?

I can do a pull request against that Wiki page if you are pushed for time.

**Comment by manojampalam** [comment]
Absolutely. Please do a pull request.

**Comment by DarwinJS** [comment]
Ok - I have the markdown ready.  I replicated the wiki repo, but from what I can tell there is no way for me to sent a pull request against my changes.

Should I send the markdown to someone?

Thanks.

**Comment by manojampalam** [comment]
Apologies for the delay. This thread was off my radar as it was closed. Can you add it the repo and send me a pull request? I'll extract out its contents and add it to wiki.
