### ISSUE TITLE
Unable to start ssh-agent after updating to Windows 10 May 2020 Update

### ISSUE THREAD

**Issue by dstaley** [PowerShell/Win32-OpenSSH#1625]
**"OpenSSH for Windows" version**
 `8.1.0.0`

**Client Operating System**
`Windows 10 Pro`

**What is failing**
In an elevated PowerShell prompt:
```
Start-Service ssh-agent
```

**Expected output**
`ssh-agent` starts

**Actual output**
```
PS C:\WINDOWS\system32> Start-Service ssh-agent
Start-Service : Service 'OpenSSH Authentication Agent (ssh-agent)' cannot be started due to the following error:
Cannot start service ssh-agent on computer '.'.
At line:1 char:1
+ Start-Service ssh-agent
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
```

**Comment by dstaley** [comment]
Running the uninstall script followed by the install script seems to have cleared things up. I guess something got overwritten during the update, so it needed to be corrected by re-installing.

**Comment by bagajjal** [comment]
Closing the issue as it's working. Will keep an eye if others report this issue.

**Comment by j143** [comment]
One possible reason is: `Startup Type` is to `Disabled`, try changing to `automatic` or `manual` .

**Snippet:** (In the `services` dialog)
![image](https://user-images.githubusercontent.com/53068787/96333833-d7156680-1089-11eb-9fad-7ae1dc130a5e.png)

**Comment by StefanDumont** [comment]
Thx @j143! Had the same problem and that did the trick!

**Comment by pkmz** [comment]
I tried this and I solved the problem too.

**Comment by YarialisGuzman** [comment]
> One possible reason is: `Startup Type` is to `Disabled`, try changing to `automatic` or `manual` .
> 
> **Snippet:** (In the `services` dialog) ![image](https://user-images.githubusercontent.com/53068787/96333833-d7156680-1089-11eb-9fad-7ae1dc130a5e.png)

YUP! And to find that on your windows machine type up "Services" and click on that.

**Comment by MalikTaylor** [comment]
@j143 This helped me solve the issue, thank you very much

**Comment by dennisvang** [comment]
or, in powershell (as admin) run  `get-service ssh-agent | set-service -startuptype manual`
