### ISSUE TITLE
Can`t Login With SSH Keys(v8.1.0.0)

### ISSUE THREAD

**Issue by wei-z-git** [PowerShell/Win32-OpenSSH#1630]
**"OpenSSH for Windows" version**
v8.1.0.0
 
**Server OperatingSystem**
Windows 10 Education

**Client OperatingSystem**
Windows 10 Education

**What is failing**
I hava followed the steps of **[Login With SSH Keys]**
1.  ssh-keygen -t rsa -f id_rsa
2.  copy the id_rsa.pub to %systemdrive%\Users\<user>\.ssh\authorized_keys, 
(https://github.com/PowerShell/Win32-OpenSSH/wiki/OpenSSH-utility-scripts-to-fix-file-permissions)

but it still not works, and need to input the password when I use {ssh -v -i .\id_rsa ftpuser@127.0.0.1}

maybe someplace I did`t deploy correct...
SSHserver and SSHclient are in the same Server

> PS C:\Program Files\OpenSSH> **ssh -v -i .\id_rsa ftpuser@127.0.0.1**
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 22.
debug1: Connection established.
debug1: identity file .\\id_rsa type 0
debug1: key_load_public: No such file or directory
debug1: identity file .\\id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_7.7
debug1: match: OpenSSH_for_Windows_7.7 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 127.0.0.1:22 as 'ftpuser'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:oitWUb+oa604JBWIB/KDGgiQQQIHidRGtp8RC4gWrF8
debug1: Host '127.0.0.1' is known and matches the ECDSA host key.
debug1: Found key in C:\\Users\\Administrator/.ssh/known_hosts:2
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
_debug1: Offering public key: RSA SHA256:TCYBsDM9z78gLxcR1EjmVKjk2xtRn91q7AV/jv7rk3A .\\id_rsa_
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: password
debug1: read_passphrase: can't open /dev/tty: No such file or directory
**ftpuser@127.0.0.1's password:**

**Expected output**
don`t need to input password

**Actual output**
need to input password

**Comment by bagajjal** [comment]
@Weway-git - If you are using admin users then default sshd_config expects the public keys in %programdata%\ssh\administrators_authorized_keys file (without any extension).
Please note that the file encoding should be UTF8.

**Comment by wei-z-git** [comment]
@bagajjal -
Thank you for your reply，
I use "ftpuser" which belongs to  administrators(picture 1) 

> ![image](https://user-images.githubusercontent.com/32572815/86198354-090dc600-bb8a-11ea-9b4b-9a43134e03ed.png)

but... maybe it  still not work, here is my steps:
1.Generate a key pair on the client
>  PS C:\Program Files\OpenSSH> ssh-keygen -t rsa -f id_rsa
> Generating public/private rsa key pair.
> Enter passphrase (empty for no passphrase):
> Enter same passphrase again:
> Your identification has been saved in id_rsa.
> Your public key has been saved in id_rsa.pub.
> The key fingerprint is:
> SHA256:vmrVIU0XeXWX99YaydA5ljm5+AojUxpEVQhuQB6WNxY administrator@SK-20200616RLMZ
> The key's randomart image is:
> +---[RSA 2048]----+
> |     .=oE+.oo+ *=|
> |     o.+= o + @.+|
> |      .+o+ . * =+|
> |       .o + . = +|
> |        S* . . + |
> |       .= +   o  |
> |       ..o o .   |
> |      .  .  .    |
> |     ....        |
> +----[SHA256]-----+
> PS C:\Program Files\OpenSSH>

2. put the id_rsa.pub into C:\ProgramData\ssh\ and rename it , "administrators_authorized_keys"（UTF-8）
![image](https://user-images.githubusercontent.com/32572815/86198753-ec25c280-bb8a-11ea-87af-a6faf3df92c3.png)

3.then "net stop sshd"&"net start sshd"
4,but it still need to input the password...

> PS C:\Program Files\OpenSSH> ssh -v -i .\id_rsa ftpuser@127.0.0.1
> OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
> debug1: Connecting to 127.0.0.1 [127.0.0.1] port 22.
> debug1: Connection established.
> debug1: identity file .\\id_rsa type 0
> debug1: key_load_public: No such file or directory
> debug1: identity file .\\id_rsa-cert type -1
> debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
> debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_7.7
> debug1: match: OpenSSH_for_Windows_7.7 pat OpenSSH* compat 0x04000000
> debug1: Authenticating to 127.0.0.1:22 as 'ftpuser'
> debug1: SSH2_MSG_KEXINIT sent
> debug1: SSH2_MSG_KEXINIT received
> debug1: kex: algorithm: curve25519-sha256
> debug1: kex: host key algorithm: ecdsa-sha2-nistp256
> debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
> debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:oitWUb+oa604JBWIB/KDGgiQQQIHidRGtp8RC4gWrF8
> debug1: Host '127.0.0.1' is known and matches the ECDSA host key.
> debug1: Found key in C:\\Users\\Administrator/.ssh/known_hosts:2
> debug1: rekey after 134217728 blocks
> debug1: SSH2_MSG_NEWKEYS sent
> debug1: expecting SSH2_MSG_NEWKEYS
> debug1: SSH2_MSG_NEWKEYS received
> debug1: rekey after 134217728 blocks
> debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
> debug1: SSH2_MSG_EXT_INFO received
> debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
> debug1: SSH2_MSG_SERVICE_ACCEPT received
> debug1: Authentications that can continue: publickey,password,keyboard-interactive
> debug1: Next authentication method: publickey
> debug1: Offering public key: RSA SHA256:TCYBsDM9z78gLxcR1EjmVKjk2xtRn91q7AV/jv7rk3A .\\id_rsa
> debug1: Authentications that can continue: publickey,password,keyboard-interactive
> debug1: Next authentication method: keyboard-interactive
> debug1: Authentications that can continue: publickey,password,keyboard-interactive
> debug1: Next authentication method: password
> debug1: read_passphrase: can't open /dev/tty: No such file or directory
> ftpuser@127.0.0.1's password:
>

**Comment by bagajjal** [comment]
In a powershell window, run  the below command to get ACLs
`` get-acl $env:ProgramData\ssh\sshd_config | ft -w``

Please make sure only system, administrators group has access to %programdata%\ssh\administrators_authorized_keys.

If this doesn't work, look at server side logs. Refer to [wiki](https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities).

Please note any changes to sshd_config requires restart of sshd service  (net stop sshd; net start sshd).

**Comment by wei-z-git** [comment]
@bagajjal 

It seems that only system and administrators have

> PS C:\Windows\system32> get-acl $env:ProgramData\ssh\sshd_config | ft -w
>     目录: C:\ProgramData\ssh
> 
> 
> Path        Owner                  Access
> ----        -----                  ------
> sshd_config BUILTIN\Administrators NT AUTHORITY\SYSTEM Allow  FullControl
>                                    BUILTIN\Administrators Allow  FullControl
>                                    SK-20200616RLMZ\Administrator Allow  FullControl

 ...Now I know that  the publickey is uncorrect...   but I retry the publickey , it`s still Failed "Failed publickey for ftpuser"
and operational log is :   

> 级别	日期和时间	来源	事件 ID	任务类别
> 信息	2020/7/2 9:55:34	OpenSSH	4	无	sshd: Connection reset by authenticating user ftpuser 127.0.0.1 port 52880 [preauth]
> 信息	2020/7/2 9:55:32	OpenSSH	4	无	sshd: Connection from 127.0.0.1 port 52880 on 127.0.0.1 port 22
> **信息	2020/7/2 9:52:38	OpenSSH	4	无	sshd: Failed publickey for ftpuser from ::1 port 52871 ssh2: RSA SHA256:vmrVIU0XeXWX99YaydA5ljm5+AojUxpEVQhuQB6WNxY**
> 信息	2020/7/2 9:52:38	OpenSSH	4	无	sshd: Authentication refused.
> 信息	2020/7/2 9:52:38	OpenSSH	4	无	sshd: Connection from ::1 port 52871 on ::1 port 22
> 信息	2020/7/2 9:52:29	OpenSSH	4	无	sshd: Server listening on 0.0.0.0 port 22.
> 信息	2020/7/2 9:52:29	OpenSSH	4	无	sshd: Server listening on :: port 22.
> 信息	2020/7/2 9:52:13	OpenSSH	4	无	sshd: Connection reset by authenticating user ftpuser ::1 port 52870 [preauth]
> 信息	2020/7/2 9:52:12	OpenSSH	4	无	sshd: Authentication refused.
> 信息	2020/7/2 9:52:10	OpenSSH	4	无	sshd: Connection reset by authenticating user ftpuser ::1 port 52865 [preauth]
> 信息	2020/7/2 9:50:56	OpenSSH	4	无	sshd: Authentication refused.
> 信息	2020/7/2 9:50:54	OpenSSH	4	无	sshd: Connection reset by authenticating user ftpuser ::1 port 52861 [preauth]
> 信息	2020/7/2 9:49:59	OpenSSH	4	无	sshd: Authentication refused.
> 信息	2020/7/2 9:46:37	OpenSSH	4	无	sshd: Connection reset by authenticating user ftpuser 127.0.0.1 port 52617 [preauth]
> 信息	2020/7/2 9:45:04	OpenSSH	4	无	sshd: Authentication refused.

and the DEBUG log :    maybe the route isn`t right， too？

>>  Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: trying public key file C:\\Users\\ftpuser\\.ssh/authorized_keys**

> 级别	日期和时间	来源	事件 ID	任务类别
> 信息	2020/7/2 9:50:36		0	无	
> Debug	2020/7/2 9:52:29	OpenSSH	6	无	sshd: debug1: Bind to port 22 on ::.
> Debug	2020/7/2 9:52:29	OpenSSH	6	无	sshd: debug1: Bind to port 22 on 0.0.0.0.
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: inetd sockets after dupping: 3, 3
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: Client protocol version 2.0; client software version OpenSSH_for_Windows_7.7
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: match: OpenSSH_for_Windows_7.7 pat OpenSSH* compat 0x04000000
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: SSH2_MSG_KEXINIT sent [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: SSH2_MSG_KEXINIT received [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: kex: algorithm: curve25519-sha256 [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: rekey after 134217728 blocks [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: SSH2_MSG_NEWKEYS sent [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: expecting SSH2_MSG_NEWKEYS [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: SSH2_MSG_NEWKEYS received [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: rekey after 134217728 blocks [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: KEX done [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: userauth-request for user ftpuser service ssh-connection method none [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: attempt 0 failures 0 [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: userauth-request for user ftpuser service ssh-connection method publickey [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: attempt 1 failures 0 [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: userauth_pubkey: test pkalg rsa-sha2-512 pkblob RSA SHA256:vmrVIU0XeXWX99YaydA5ljm5+AojUxpEVQhuQB6WNxY [preauth]
**> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: trying public key file C:\\Users\\ftpuser\\.ssh/authorized_keys**
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: userauth-request for user ftpuser service ssh-connection method keyboard-interactive [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: attempt 2 failures 1 [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: keyboard-interactive devs  [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: auth2_challenge: user=ftpuser devs= [preauth]
> Debug	2020/7/2 9:52:38	OpenSSH	6	无	sshd: debug1: kbdint_alloc: devices '' [preauth]
>

**Comment by feelingfrance** [comment]
you need run the code in powershell,
$acl = Get-Acl C:\ProgramData\ssh\administrators_authorized_keys
$acl.SetAccessRuleProtection($true, $false)
$administratorsRule = New-Object system.security.accesscontrol.filesystemaccessrule("Administrators","FullControl","Allow")
$systemRule = New-Object system.security.accesscontrol.filesystemaccessrule("SYSTEM","FullControl","Allow")
$acl.SetAccessRule($administratorsRule)
$acl.SetAccessRule($systemRule)
$acl | Set-Acl

**Comment by bagajjal** [comment]
You mentioned ftpuser is an admin on this machine but looks like ftpuser is not an administrator..

 Debug 2020/7/2 9:52:38 OpenSSH 6 无 sshd: debug1: trying public key file C:\Users\ftpuser\.ssh/authorized_keys

Place your public keys in C:\Users\ftpuser\.ssh/authorized_keys.

**Comment by wei-z-git** [comment]
@bagajjal 
I had put public keys in “C:\Users\ftpuser\.ssh/authorized_keys” before，but publickey is still not allowed by sshd server
![image](https://user-images.githubusercontent.com/32572815/86452551-0c05e380-bd4f-11ea-904b-eb560c2d8244.png)

Operational logs:
> 级别	日期和时间	来源	事件 ID	任务类别
> **_信息	2020/7/3 16:57:28	OpenSSH	4	无	sshd: Failed publickey for ftpuser from 127.0.0.1 port 51012 ssh2: RSA SHA256:PJxwscWEOUWQGdUIS3S45M6uRvsKnajjEYRB/X8mJBE_**
> **_信息	2020/7/3 16:57:28	OpenSSH	4	无	sshd: Authentication refused._**
> 信息	2020/7/3 16:57:28	OpenSSH	4	无	sshd: Connection from 127.0.0.1 port 51012 on 127.0.0.1 port 22
> 信息	2020/7/3 16:56:23	OpenSSH	4	无	sshd: Connection reset by authenticating user ftpuser 127.0.0.1 port 50936 [preauth]
> 信息	2020/7/3 16:55:11	OpenSSH	4	无	sshd: Connection from 127.0.0.1 port 50936 on 127.0.0.1 port 22

DEBUG:

> 级别	日期和时间	来源	事件 ID	任务类别
> 信息	2020/7/3 16:56:35		0	无	
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: inetd sockets after dupping: 3, 3
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: Client protocol version 2.0; client software version OpenSSH_for_Windows_7.7
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: match: OpenSSH_for_Windows_7.7 pat OpenSSH* compat 0x04000000
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: SSH2_MSG_KEXINIT sent [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: SSH2_MSG_KEXINIT received [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: kex: algorithm: curve25519-sha256 [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: rekey after 134217728 blocks [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: SSH2_MSG_NEWKEYS sent [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: expecting SSH2_MSG_NEWKEYS [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: SSH2_MSG_NEWKEYS received [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: rekey after 134217728 blocks [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: KEX done [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: userauth-request for user ftpuser service ssh-connection method none [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: attempt 0 failures 0 [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: userauth-request for user ftpuser service ssh-connection method publickey [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: attempt 1 failures 0 [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: userauth_pubkey: test pkalg rsa-sha2-512 pkblob RSA SHA256:PJxwscWEOUWQGdUIS3S45M6uRvsKnajjEYRB/X8mJBE [preauth]
> **Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: trying public key file C:\\Users\\ftpuser\\.ssh/authorized_keys**
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: userauth-request for user ftpuser service ssh-connection method keyboard-interactive [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: attempt 2 failures 1 [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: keyboard-interactive devs  [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: auth2_challenge: user=ftpuser devs= [preauth]
> Debug	2020/7/3 16:57:28	OpenSSH	6	无	sshd: debug1: kbdint_alloc: devices '' [preauth]


Is there any possible that the route of the sshd_config isn`t right... 
maybe "C:\\Users\\ftpuser\\.ssh/authorized_keys" should be "C:\\Users\\ftpuser\\.ssh\\authorized_keys"

**Comment by wei-z-git** [comment]
Final solution:

Maybe the reason is  "%programdata%\ssh\administrators_authorized_keys" or "C:\Users\ftpuser\.ssh\authorized_keys" didn`t hava enough access 


（1）when the ftpuser belongs to administrators
![image](https://user-images.githubusercontent.com/32572815/87615998-9a626800-c746-11ea-9eb7-d80015807f77.png)
   the  "SYSTEM", "ftpuser" should has total access to "%programdata%\ssh\administrators_authorized_keys" 
![image](https://user-images.githubusercontent.com/32572815/87615939-730b9b00-c746-11ea-89c3-9d13217993b8.png)

（2）when ftpuser doesn't belong to administrators
 the "ftpuser" should has total access to "C:\Users\ftpuser\.ssh\authorized_keys" 
![image](https://user-images.githubusercontent.com/32572815/87616467-ad296c80-c747-11ea-944d-9c4d06927c67.png)


Thanks to bagajjal and  feelingfrance!

**Comment by AxelHu** [comment]
This post fixes my issue too, thanks a lot!

**Comment by wei-z-git** [comment]
Notice that the group "Authenticated Users " should also be removed from the file(administrator-authorized-keys), when sshuser belongs to administrators

**Comment by sgrayban** [comment]
@feelingfrance Your tip...

> $acl = Get-Acl C:\ProgramData\ssh\administrators_authorized_keys
> $acl.SetAccessRuleProtection($true, $false)
> $administratorsRule = New-Object system.security.accesscontrol.filesystemaccessrule("Administrators","FullControl","Allow")
> $systemRule = New-Object system.security.accesscontrol.filesystemaccessrule("SYSTEM","FullControl","Allow")
> $acl.SetAccessRule($administratorsRule)
> $acl.SetAccessRule($systemRule)
> $acl | Set-Acl

Work perfectly!
Thank you so much

**Comment by yocoyang** [comment]
I have been troubled by this issue for a long time, this saved me a lot of time.
