### ISSUE TITLE
SSH to VM Linux only works after SSH from VM to Windows

### ISSUE THREAD

**Issue by ElvaRivle** [PowerShell/Win32-OpenSSH#1634]
**"OpenSSH for Windows" version**
8.1.0.0
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Debian 10.4 running on VMWare with bridged connection with static IP

**What is failing**
Can SSH to Debian **ONLY AFTER** SSH-ing from Debian to Windows. Only after that does *timed out* dissapear on Windows (visible in **actual output**). I made all possible combinations of Firewall setup both on Win and Deb but problem persists.

**Expected output**
Ability to SSH to Debian immediately:
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
debug1: Reading configuration data C:\\Users\\elvir/.ssh/config
debug1: C:\\Users\\elvir/.ssh/config line 1: Applying options for 192.168.0.201
debug1: Connecting to 192.168.0.201 [192.168.0.201] port 22.
debug1: connect to address 192.168.0.201 port 22: Connection timed out
ssh: connect to host 192.168.0.201 port 22: Connection timed out
PS C:\Users\elvir> ssh elva@192.168.0.201 -v
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
debug1: Reading configuration data C:\\Users\\elvir/.ssh/config
debug1: C:\\Users\\elvir/.ssh/config line 1: Applying options for 192.168.0.201
debug1: Connecting to 192.168.0.201 [192.168.0.201] port 22.
debug1: Connection established.
debug1: identity file C:\\Users\\elvir/.ssh/id_rsa type 0
debug1: identity file C:\\Users\\elvir/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\elvir/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\elvir/.ssh/id_dsa-cert type -1
debug1: identity file C:\\Users\\elvir/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\elvir/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\elvir/.ssh/id_ed25519 type -1
debug1: identity file C:\\Users\\elvir/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\elvir/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\elvir/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.9p1 Debian-10+deb10u2
debug1: match: OpenSSH_7.9p1 Debian-10+deb10u2 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.0.201:22 as 'elva'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:[host_key]
debug1: Host '192.168.0.201' is known and matches the ECDSA host key.
debug1: Found key in C:\\Users\\elvir/.ssh/known_hosts:1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: Will attempt key: C:\\Users\\elvir/.ssh/id_rsa RSA SHA256:[preauth]
debug1: Will attempt key: C:\\Users\\elvir/.ssh/id_dsa
debug1: Will attempt key: C:\\Users\\elvir/.ssh/id_ecdsa
debug1: Will attempt key: C:\\Users\\elvir/.ssh/id_ed25519
debug1: Will attempt key: C:\\Users\\elvir/.ssh/id_xmss
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: C:\\Users\\elvir/.ssh/id_rsa RSA SHA256:[preauth]
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: C:\\Users\\elvir/.ssh/id_dsa
debug1: Trying private key: C:\\Users\\elvir/.ssh/id_ecdsa
debug1: Trying private key: C:\\Users\\elvir/.ssh/id_ed25519
debug1: Trying private key: C:\\Users\\elvir/.ssh/id_xmss
debug1: Next authentication method: password
debug1: read_passphrase: can't open /dev/tty: No such file or directory
elva@192.168.0.201's password:

**Actual output**
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
debug1: Reading configuration data C:\\Users\\elvir/.ssh/config
debug1: C:\\Users\\elvir/.ssh/config line 1: Applying options for 192.168.0.201
debug1: Connecting to 192.168.0.201 [192.168.0.201] port 22.
debug1: connect to address 192.168.0.201 port 22: Connection timed out
ssh: connect to host 192.168.0.201 port 22: Connection timed out

**Comment by ElvaRivle** [comment]
What is even more fascinating, disabling Inbound rule in Windows firewall I get *timed out* on Debian when SSH-ing to Windows (expected). But **even after that** I get ability to SSH from Windows to Debian without any more *timed out*

**Comment by bagajjal** [comment]
@ElvaRivle - I don't think it's SSH issue. To confirm, please try your scenario with putty ssh client.

**Comment by ElvaRivle** [comment]
@bagajjal Putty works, so as two VMs SSH-ing into one another on my network. 

Edit: My bad, it actually doesn't. I forgot to restart VM. I'll try SSH from my phone and if that doesn't work than I'm closing this

**Comment by ElvaRivle** [comment]
Termux works, Putty client on Android works (2 apps tested)... after all those connections, again trying from Windows gets timed out, even Putty

**Comment by bagajjal** [comment]
@ElvaRivle - Please try different SSH client like putty from the same windows machine. 
I am guessing, it's related to some network configuration.

**Comment by ElvaRivle** [comment]
@bagajjal Excuse me, could have sworn I wrote it. Putty from same Windows machine doesn't work

**Comment by bagajjal** [comment]
@ElvaRivle - Given putty doesn't work confirms the fact that it's something to do with your network configuration.
I'm closing this issue as it's not related to SSH.

**Comment by ElvaRivle** [comment]
For future readers, fixed this by: 

- disabling SELinux
- using keys instead of password
- manually disabled then enabled VMWare bridge feature from Network and Sharing
- *upped* my network interface (ens33) on VM

First two didn't fix directly, but they *maybe* helped last two things to work, I don't know. All I know is that last 2 things definitely helped.
