### ISSUE TITLE
Prevent showing directory contents in SFTP

### ISSUE THREAD

**Issue by dbarros** [PowerShell/Win32-OpenSSH#1637]
Please answer the following

**"OpenSSH for Windows" version**
 `8.0.0.0`
 
**Server OperatingSystem**
 `Windows Server 2016 Datacenter`

**Client OperatingSystem**
  `macOS 10.15.5`

**What is failing**

Nothing is failing. I would like to know how to configure SFTP so that when someone logs in, the directory contents are not visible. i.e. if the user enters `dir`, then any files/directories which are in that directory, are not listed.

**Comment by bagajjal** [comment]
@dbarros - There is no way hide the directory contents. If you want to restrict the user to a specific directory then you should use CHROOT.
