### ISSUE TITLE
Question: Executing commands immediately?

### ISSUE THREAD

**Issue by JohannesTK** [PowerShell/Win32-OpenSSH#164]
Should it be possible to execute commands immediately with Win32-OpenSSH?

I.e.:
`ssh user@desktop dir` and it lists the directories and files. 

I can do it from Windows -> Linux and it works fine but the other way around Linux -> Windows gives me broken pipe. 

Is the functionality still not there yet there or should it work?

**Comment by manojampalam** [comment]
Its a known issue. SSHD executes the cmd directly, instead of processing it in a shell. i.e, it is trying to run dir.exe rather than "cmd.exe /c dir". This will be fixed as part of refactoring effort by end of May.

**Comment by manojampalam** [comment]
do "cmd.exe /c dir" instead of "dir"
