### ISSUE TITLE
Why is Windows 10 20H1 still shipping with OpenSSH 7.7p1?

### ISSUE THREAD

**Issue by mgkuhn** [PowerShell/Win32-OpenSSH#1646]
When on Windows 10 20H1 (10.0.19041.388) I follow the instructions at

  https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse

to install the OpenSSH version built as a feature into the latest Windows 10 release, I still get
```
C:\>ssh -V
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```

That is an ancient version (from 2018) that still lacks the game-changing improvements that have happened since, in particular
* GSSAPI/Kerberos authentication (since 7.9)
* PTY support via conpty (since 7.9)

Each new Windows 10 release, I am disappointed that it still ships with OpenSSH for Windows 7.7 as an optional feature. As a result, I have to instruct colleagues to manually download and install the GitHub version, rather than simply add the one that came with their OS distribution. While I myself am perfectly confident with unzipping the latest versions from GitHub and adjusting PATH etc., some of my colleagues may not be, therefore, in the interest of easier collaboration via Active Directory (GSSAPI/Kerberos) based authentication, I am very interested in more recent versions becoming a standard Windows 10 feature.

What is holding back releasing the excellent newer versions of OpenSSH for Windows as a Windows 10 optional feature?

When do you expect the version that comes as a feature with Windows to be at least 7.9p1 or newer?

How is the version “0.0.1.0” displayed at

```
PS C:\> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'


Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed

Name  : OpenSSH.Server~~~~0.0.1.0
State : Installed
```

releated to the version tags used on GitHub?

**Comment by bagajjal** [comment]
@mgkuhn - The next windows release during this fall season will have the new github version v8.1 shipped in windows.

**Comment by bagajjal** [comment]
The next windows update will be available on 10/20/2020.

**Comment by jcotton42** [comment]
Are there any plans to accelerate the release cycle of the bundled SSH past the 6 months for a Windows release?

**Comment by bagajjal** [comment]
@jcotton42 - Unfortunately not. We are tied with the windows release cycle.

**Comment by TurnOffNOD** [comment]
> 
> 
> @mgkuhn - The next windows release during this fall season will have the new github version v8.1 shipped in windows.

Hi,  the upstream OpenSSH has already released version 8.3, could you please ship ssh version 8.3p with next windows update?
Or we take release frequency into consideration, plan to ship future version 8.4?

**Comment by mgkuhn** [comment]
@TurnOffNOD wrote:
> Or we take release frequency into consideration, plan to ship future version 8.4?

“Version ten is really where we want to be at”, to quote [Stefan Karpinsky](https://en.wikipedia.org/wiki/Stefan_Karpinski) (after being nagged when [Julia](https://julialang.org/) 1.0 will finally be released).

Let them first ship in Windows the very important (Kerberos! ConPTY!) and well-tested features of OpenSSH 7.9, 8.0 and 8.1 that we already have, rather than asking for features of future releases that do not even exist yet.

Are you confident that there is anything particularly interesting coming in OpenSSH 8.4 that you are desperately waiting for?

(OpenSSH 8.2 added support for communicating with FIDO2 USB/Bluetooth devices as a major new feature, and porting that to Windows may still require non-trivial effort. That may not be realistic in the few weeks left until the next Windows release.)

**Comment by TurnOffNOD** [comment]
> 
> 
> @TurnOffNOD wrote:
> 
> > Or we take release frequency into consideration, plan to ship future version 8.4?
> 
> “Version ten is really where we want to be at”, to quote [Stefan Karpinsky](https://en.wikipedia.org/wiki/Stefan_Karpinski) (after being nagged when [Julia](https://julialang.org/) 1.0 will finally be released).
> 
> Let them first ship in Windows the very important (Kerberos! ConPTY!) and well-tested features of OpenSSH 7.9, 8.0 and 8.1 that we already have, rather than asking for features of future releases that do not even exist yet.

That's right. If we think one more step, there will be a test when we choose version 8.1 to be shipped, but there will also be a test if we choose the latest released version 8.3 to be shipped. There will always a test anyway, why not choose a newer version?

> 
> Are you confident that there is anything particularly interesting coming in OpenSSH 8.4 that you are desperately waiting for?

No, that's totally a guess, based on my observation on frequency of released version.
> 
> (OpenSSH 8.2 added support for communicating with FIDO2 USB/Bluetooth devices as a major new feature, and porting that to Windows may still require non-trivial effort. That may not be realistic in the few weeks left until the next Windows release.)

Does it mean next Windows release is around the corner, in September?

**Comment by mgkuhn** [comment]
> Does it mean next Windows release is around the corner, in September?

I wish github would not allow email replies to issues. This would force respondents to reply via the issue web page, where they would see the full discussion and could discover that their question was already answered in an earlier reply (here on 30 Jul).

**Comment by mgkuhn** [comment]
@bagajjal I just upgraded a PC from Windows 10 2004 to Windows 10 20H2: But in `cmd.exe` I still get an ancient ssh version:
```
C:\> ver

Microsoft Windows [Version 10.0.19042.572]

C:\> ssh -V
OpenSSH_for_Window_7.7p1, LibreSSL 2.6.5

```

Likewise, in Powershell, I still get
```
PS C:\> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'


Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed

Name  : OpenSSH.Server~~~~0.0.1.0
State : Installed
```
as before.

I had *very* much hoped that Windows 20H2 would include an upgrade to `OpenSSH_for_Windows_8.1` or newer.

What happened? (Please reopen this issue and update the title to 20H2)

**Comment by maertendMSFT** [comment]
Hi folks, please see https://github.com/PowerShell/Win32-OpenSSH/issues/1693 for information regarding updates into Windows

**Comment by psztoch** [comment]
And how not to install Linux afterwards?
You try and convince programmers to work on Windows and only have problems afterwards.
