### ISSUE TITLE
Windows 10 OpenSSH client doesn't support Compression

### ISSUE THREAD

**Issue by okudayukiko** [PowerShell/Win32-OpenSSH#1647]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
Windows optional features
C:\Users\User name>`ssh -V`
`OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5`

**Server OperatingSystem**
user name@debian:~$ `ssh -V`
`OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d 10 Sep 2019`

**Client OperatingSystem**
Windows 10 1909 x86-64

**What is failing**
1. Windows 10 `ssh` Doesn't support compression.
Use `ssh -Cv username@hostname` in Windows 10:
`debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none`
`debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none`
Use `ssh -Cv username@hostname` in Debian 10:
`debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com`
`debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com`
2. Windows 10 `ssh` doesn't support `ssh -Q help` and `ssh -Q sig`, but Debian 10 `ssh` support them.
C:\Users\User name>`ssh -Q help`
`Unsupported query "help"`
C:\Users\User name>`ssh -Q sig`
`Unsupported query "sig"`
3. Windows 10 `ssh` Doesn't support TUN tunneling even if we add a TAP-Windows adapter and we renamed this Network Connection (in Control Panel) to "2". It's useful for VPN.
C:\Users\User name>`ssh -w 2:2 username@hostname`
`Tunnel interfaces are not supported on this platform`
`Tunnel device open failed.`
`Could not request tunnel forwarding.`
4. `C:\Windows\system32\libcrypto.dll` has no digital signature.

**Expected output**

**Actual output**

**Comment by NoMoreFood** [comment]
Please try the latest release: 

https://github.com/PowerShell/Win32-OpenSSH/releases
