### ISSUE TITLE
Feature request - Relocate logs on file system

### ISSUE THREAD

**Issue by cobaltjacket** [PowerShell/Win32-OpenSSH#1648]
I need to be able to relocate the logs to another location (say the D: drive.) This is for a use case where the C: drive is essentially re-imaged between each boot. On Unix variants of OpenSSH, we would accomplish this by modifying the SyslogFacility parameter, but how can we do something like this on Windows?

**Comment by bagajjal** [comment]
@cobaltjacket - On windows, the default logging is the ETW based. 
File based logging is a way to easily debug the issues.
We don't recommend file based logging in production as it can cause disk overflow.

**Comment by bagajjal** [comment]
Incase, if you want to use file based logging then you should write your own script to truncate / copy the sshd.log file.
