### ISSUE TITLE
Setting sshd_config and ssh_config options via Active Directory

### ISSUE THREAD

**Issue by mgkuhn** [PowerShell/Win32-OpenSSH#1650]
At present, administrators who want to enable SSH Kerberos authentication or delegation for users and computers in their domain have to place the line
```
GSSAPIAuthentication yes
```
into `C:\ProgramData\ssh\sshd_config` and similarly also
```
GSSAPIAuthentication yes
GSSAPIDelegation yes
```
into `C:\ProgramData\ssh\ssh_config` on _each individual machine_. That can become a bit tedious to manage.

Is there some way to push out such (and similar) changes to the global ssh/sshd configuration options in a more centralized way, similar to an [Active Directory Group Policy](https://en.wikipedia.org/wiki/Group_Policy)?

If not, what would be a good way to add such a feature?

For example, could OpenSSH for Windows be modified to check not only `C:\ProgramData\ssh\` but also config files placed somewhere under the `\\MYDOMAIN.COM\SYSVOL` or `\\MYDOMAIN.COM\NETLOGON\` shares that are already SMB mounted from the domain controller by domain-joined Windows computers?

Is there some existing Group Policy or other API or mechanism that would be suitable for distributing SSH config settings (ideally even in a computer or user specific way)?

**Comment by NoMoreFood** [comment]
You could use [Group Policy preferences](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn789188(v=ws.11)) to distribute / overwrite the sshd_config file from a centralized location.

You can further enhance that by using [Item Level Targeting](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn789189(v=ws.11)) to only distribute the file on systems where the feature is actually installed.
