### ISSUE TITLE
Hi, does Win32-OpenSSH v8.1.0.0p1-Beta link against libressl version 2.9.2.1

### ISSUE THREAD

**Issue by TurnOffNOD** [PowerShell/Win32-OpenSSH#1655]
Please answer the following

**"OpenSSH for Windows" version**
8.1.0.0
 

**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Win 10 Pro 2004.

**What is failing**
I upgraded OpenSSH from shipped 7.7p1 to latest v8.1.0.0p1-Beta. On release webpage https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.1.0.0p1-Beta , it says version 8.1.0.0p1-Beta has upgraded LibreSSL to version 2.9.2.1.

However, when I ssh -V to check, it say LibreSSL 2.6.5:
![image](https://user-images.githubusercontent.com/2140029/90960300-411eee80-e4d3-11ea-8e2d-c3edf3f4eb88.png)

Is this a bug? Or have I missed something when upgraded?

**Expected output**
LibreSSL 2.9.2

**Actual output**
LibreSSL 2.6.5

**Comment by bagajjal** [comment]
LibreSSL is loaded in runtime. It's possible that you haven't overriden the libcrypto.dll at c:\windows\system32 folder.

**Comment by TurnOffNOD** [comment]
> 
> 
> LibreSSL is loaded in runtime. It's possible that you haven't overriden the libcrypto.dll at c:\windows\system32 folder.

Right, I thought the install script would update this dll automatically, so I didn't pay attention to it. After I update the dll manually, the problem has been solved.
