### ISSUE TITLE
SSH Agent from OpenSSH 7.7 on Windows 10 (2004) cannot authenticate with Ubuntu 20.04 host

### ISSUE THREAD

**Issue by shawly** [PowerShell/Win32-OpenSSH#1659]
**"OpenSSH for Windows" version**
7.7.2.1 (added through command `Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0`)
Can be reproduced with [OpenSSH portable v7.7.2.0p1](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.7.2.0p1-Beta)-Beta as well as v7.6.
 
**Server OperatingSystem**
Windows 10 Pro (2004)

**Client OperatingSystem**
Ubuntu 20.04

**What is failing**
Cannot authenticate via SSH Agent.

**Expected output**
Successful authentication.

**Actual output**

**SSH Client logs**

This is the ssh clients verbose log when connecting to the Ubuntu 20.04 host:
https://pastebin.com/qM7nrKTP

And this is how it looks like when I connect to a Ubuntu 18.04 host:
https://pastebin.com/MKwzAgBf

This is how it looks like when I turn off the SSH agent and use the private key from my .ssh folder:
https://pastebin.com/KnbFibmG

**SSH Server logs**

Server side auth log when trying to authenticate with the SSH Agent which fails
https://pastebin.com/au5hV0Cv

Server side auth log when trying to authenticate with the local stored privae key which succeeds
https://pastebin.com/tfTCGLKH

**Workarounds**

Either disable SSH Agent service and use local private key from .ssh folder or use OpenSSH portable 8.1 from releases which works fine too. Using OpenSSH agent from 7.6 with Ubuntu 18 as client works as well, so this issue seems to be related to the Windows builds of OpenSSH.
I also tried the SSH Agent from [OpenSSH portable v7.9](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.9.0.0p1-Beta) which works perfectly fine as well.

**Solution**

Upgrade OpenSSH version in Windows Features to a newer stable version.

**Comment by lixin9311** [comment]
I can confirm the same issue.

**Workarounds:**
Just use ed25519 instead.

**Comment by mgkuhn** [comment]
Issue can probably be closed now as fixed: the “OpenSSH version in Windows Features” is now 8.1, as of this week (install KB5003173 via Windows Update on the Semi-Annual Channel).

**Comment by bagajjal** [comment]
Thanks @mgkuhn
