### ISSUE TITLE
Hang / crash when powershell is executed from cmd via ssh (Windows 10 Pro)

### ISSUE THREAD

**Issue by mesmariusz** [PowerShell/Win32-OpenSSH#166]
Dears

I have on my remote Win 10 SSH installed follow instruction below:

https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

Connection to cmd works perfectly but after powershell is executed (from cmd) then connection looks like below (no commands can be executed - looks like no response from remote cmd). 

http://filmy.elektroda.net/58_1458919094.mp4

Is this a bug? Please give me some hints / or please support me somehow. 

Thank you and best regards.
Mariusz

**Comment by nachfuellbar** [comment]
https://github.com/PowerShell/Win32-OpenSSH/issues/159

like @manojampalam said in this issue, you can expect a better working solution end of May

**Comment by manojampalam** [comment]
Try the following:
Powershell -File -

That's telling Powershell to redirect its IO streams through std IO.

**Comment by manojampalam** [comment]
This is explained in https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples

**Comment by mesmariusz** [comment]
Thank you. Now it works: http://filmy.elektroda.net/48_1458924598.mp4

Only one question mark: why 'new line' (enter) works so oddly ?

**Comment by manojampalam** [comment]
the 'new line' should work better with the latest version. I put in a work around for now.

**Comment by C-Duv** [comment]
I had issues when execution PowerShell scripts from a .bat script that I started via a SSH session.
I've stepped onto this GH issue but in my case I wanted to run PowerShell scripts, not PowerShell interactive console.

## Steps:
1. I open an SSH session to a Windows 7 workstation
2. I type the following command: `C:\foobar\install.bat`
3. `install.bat` script hangs in the middle of it's execution

## Files

`install.bat`:

``` Batch
@echo off
echo Starting
cmd.exe /C powershell.exe -File "file1.ps1"
echo Done with file1
cmd.exe /C powershell.exe -File "file2.ps1"
echo Done with file2
```

`file1.ps1`:

``` Batch
Write-Host "EOF file1"
```

`file2.ps1`:

``` Batch
Write-Host "EOF file2"
```

Script would only print:

```
install.bat
           Starting
EOF file1
         _
```

And hangs. I had to press [Enter] for the `file2.ps1` to run:

```
install.bat
           Starting
EOF file1

Done with file1
EOF file2
         _
```

And once more for the `install.bat` to end:

```
install.bat
           Starting
EOF file1

Done with file1
EOF file2

Done with file2
```

In my real use case, the stuff the `file1.ps1` was doing (calling external binaries) made the "[Enter]-trick" not working (I had to kill the Powershell process).

## My solution:

Use the `-InputFormat None` powershell.exe's option:

`install.bat`:

``` Batch
@echo off
echo Starting
cmd.exe /C powershell.exe -InputFormat None -File "file1.ps1"
echo Done with file1
cmd.exe /C powershell.exe -InputFormat None -File "file2.ps1"
echo Done with file2
```

Outputs:

```
install.bat
           Starting
EOF file1
         Done with file1
EOF file2
         Done with file2
```

Let's hope this help someone.
