### ISSUE TITLE
OpenSSH powershell command permissions

### ISSUE THREAD

**Issue by kanan-m** [PowerShell/Win32-OpenSSH#1662]
**"OpenSSH for Windows" version**
`7.7.2.2`
 
**Server OperatingSystem**
 `Windows Server 2019 Datacenter`

**Client OperatingSystem**
`Windows 10 Enterprise`

**What is failing**
Server is in domain1, account is in domain2. Between domains there is two-way trust. I connect to server through my domain2 account. I can connect. I am an ordinary user (not admin). When I execute through ssh `Get-Service` command I got `Get-Service : Cannot open Service Control Manager on computer '.'. This operation might require other privileges.`. If I log in to server, and execute through powershell then I can get result (all services). 

1) If I give admin privileges to my account, in that case I can get powershell result via ssh too.
2) if I type `Get-Service servicename` (which I have permissions through group policy), can get result.

I need that I can manage my windows services via ssh. By the way, I gave full access to specialized services which I need to manage. net start/stop servicename also not working.

**Expected output**

**Actual output**

**Comment by jborean93** [comment]
The is probably down to the fact that SCManager is set to only allow Admins and Interactive users the ability to enumerate services. If you run `sc.exe sdshow scmanager` it will output the SDDL of SCManager, you can use the following script to parse that SDDL to a more human friendly format

```powershell
# https://docs.microsoft.com/en-us/windows/win32/services/service-security-and-access-rights
Add-Type -TypeDefinition @'
using System;

namespace SCManager
{
    [Flags]
    public enum AccessMask
    {
        SC_MANAGER_CONNECT = 0x0001,
        SC_MANAGER_CREATE_SERVICE = 0x0002,
        SC_MANAGER_ENUMERATE_SERVICE = 0x0004,
        SC_MANAGER_LOCK = 0x0008,
        SC_MANAGER_QUERY_LOCK_STATUS = 0x0010,
        SC_MANAGER_MODIFY_BOOT_CONFIG = 0x0020,
        STANDARD_RIGHTS_REQUIRED = 0xF0000,
        STANDARD_RIGHTS_READ = 0x20000,
        STANDARD_RIGHTS_WRITE = 0x20000,
        STANDARD_RIGHTS_EXECUTE = 0x20000,
        SC_MANAGER_ALL_ACCESS = STANDARD_RIGHTS_REQUIRED |
            SC_MANAGER_CONNECT |
            SC_MANAGER_CREATE_SERVICE |
            SC_MANAGER_ENUMERATE_SERVICE |
            SC_MANAGER_LOCK |
            SC_MANAGER_QUERY_LOCK_STATUS |
            SC_MANAGER_MODIFY_BOOT_CONFIG,
        GENERIC_READ = STANDARD_RIGHTS_READ |
            SC_MANAGER_ENUMERATE_SERVICE |
            SC_MANAGER_QUERY_LOCK_STATUS,
        GENERIC_WRITE = STANDARD_RIGHTS_WRITE |
            SC_MANAGER_CREATE_SERVICE |
            SC_MANAGER_MODIFY_BOOT_CONFIG,
        GENERIC_EXECUTE = STANDARD_RIGHTS_EXECUTE |
            SC_MANAGER_CONNECT |
            SC_MANAGER_LOCK,
        GENERIC_ALL = SC_MANAGER_ALL_ACCESS,
    }
}
'@

$sddl = ((sc.exe sdshow scmanager) -join "").Trim()
$sd = ConvertFrom-SddlString -Sddl $sddl
$sd.RawDescriptor.DiscretionaryAcl | ForEach-Object {
    $sid = $_.SecurityIdentifier
    try {
        $account = $sid.Translate([Security.Principal.NTAccount])
    } catch [Security.Principal.IdentityNotMappedException] {
        $account = $sid
    }
    [PSCustomObject]@{
        Account = $account
        Access = [SCManager.AccessMask]$_.AccessMask
        AccessMask = '0x{0:X8}' -f $_.AccessMask
        AceType = $_.AceType
    }
} | Format-List
```

On my host I get the following in the output

```
Account    : NT AUTHORITY\INTERACTIVE
Access     : SC_MANAGER_CONNECT, GENERIC_READ
AccessMask : 0x00020015
AceType    : AccessAllowed

Account    : NT AUTHORITY\SERVICE
Access     : SC_MANAGER_CONNECT, GENERIC_READ
AccessMask : 0x00020015
AceType    : AccessAllowed

Account    : NT AUTHORITY\Authenticated Users
Access     : SC_MANAGER_CONNECT
AccessMask : 0x00000001
AceType    : AccessAllowed

Account    : NT AUTHORITY\SYSTEM
Access     : SC_MANAGER_CONNECT, SC_MANAGER_MODIFY_BOOT_CONFIG, GENERIC_READ
AccessMask : 0x00020035
AceType    : AccessAllowed

Account    : BUILTIN\Administrators
Access     : GENERIC_ALL
AccessMask : 0x000F003F
AceType    : AccessAllowed

Account    : APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES
Access     : SC_MANAGER_CONNECT
AccessMask : 0x00000001
AceType    : AccessAllowed

Account    : S-1-15-3-1024-528118966-3876874398-709513571-1907873084-3598227634-3698730060-278077788-3990600205
Access     : SC_MANAGER_CONNECT
AccessMask : 0x00000001
AceType    : AccessAllowed
```

I can see that `BUILTIN\Administrators` effective have full control and can do what they can which explains why an admin works all the time. There is also `NT AUTHORITY\Authenticated Users` which allows me to connect to SCManager but that's it, it is unable to enumerate the services or do anything really which is why `Get-Service` fails with the permission error. The reason why you are able to call `Get-Service` on a normal PowerShell window outside of SSH is because of the `NT AUTHORITY\INTERACTIVE` ACE that allows those members the `GENERIC_READ` right allowing that group to enumerate the services. The `NT AUTHORITY\INTERACTIVE` group is added to your access token for interactive logons but SSH is a Network logon so that group is no longer present.

To see this in action, run `whoami.exe /groups` through an SSH connection and on a normal interactive logon and see the differences. To solve this problem you effectively need to grant the same access mask (`0x00020015`) to the user you are running that. This can be done through a group it is a member of or even through `NT AUTHORITY\NETWORK` to allow network logons the same access rights as an interactive logon. You can use `sc.exe` to set your new SDDL like so:

```powershell
# Change this to the user/group you wish to add the right for
$sid = [Security.Principal.NTAccount]::new('NT AUTHORITY', 'NETWORK').Translate(
    [Security.Principal.SecurityIdentifier])

$sddl = ((sc.exe sdshow scmanager) -join "").Trim()
$sd = ConvertFrom-SddlString -Sddl $sddl
$sd.RawDescriptor.DiscretionaryAcl.AddAccess(
    [Security.AccessControl.AccessControlType]::Allow,
    $sid,
    0x00020015,  # SC_MANAGER_CONNECT | GENERIC_READ
    [Security.AccessControl.InheritanceFlags]::None,
    [Security.AccessControl.PropagationFlags]::None
)
$newSddl = $sd.RawDescriptor.GetSDDLForm('All')

Write-Host "Changing SDDL From:`n$sddl`nTo:`n$newSddl"
sc.exe sdset scmanager $newSddl
```

**Comment by kanan-m** [comment]
@jborean93 Great thanks for your detailed answer. I've changed user/group and could give permission to. Now I can execute and get result for both `Get-Service` and `net start/stop`

Let me ask one more question. What is about with other powershell commands which I need. For example:  `Get-NetTCPConnection`.
Below is result when I execute command
`Get-EventLog : Cannot open log Application on machine .. Windows has not provided an error code.`
`Get-NetTCPConnection : Cannot connect to CIM server. Access denied`

**Comment by jborean93** [comment]
The event logs and WMI/CIM have the same problem where it’s set to allow Interactive users and admins but a network logon for a standard user is neither of them. You need to edit the SD for both of them to allow access, otherwise you need to change the logon of the current thread to an interactive logon using script like https://gist.github.com/jborean93/3c148df03545023c671ddefb2d2b5ffc. Bare in mind that script will work for things that run in the same process but calling other executables will not. It also means you need to pass in the credentials manually which is not ideal.

**Comment by kanan-m** [comment]
@jborean93 Thanks again for your support. I found your answer in [issue-1636](https://github.com/PowerShell/Win32-OpenSSH/issues/1636). I've changed the script a bit to suitable for me as below:
```
using namespace System.Security.AccessControl
using namespace System.Security.Principal

$READ = 1
$WRITE = 2
$CLEAR = 4

$sid = [Security.Principal.NTAccount]::new('XYZ', 'SREngineers').Translate([Security.Principal.SecurityIdentifier])

# Get the existing SDDL
[xml]$logConfig = wevtutil.exe get-log Application /format:XML
$existingSDDL = $logConfig.channel.channelAccess
$sd = [RawSecurityDescriptor]::new($existingSDDL)

# Add read permissions to Group
$allUsersAce = [CommonAce]::new(
    [AceFlags]::None,
    [AceQualifier]::AccessAllowed,
    ($READ),
    $sid,
    $false,
    $null
)
$sd.DiscretionaryAcl.InsertAce($sd.DiscretionaryAcl.Count, $allUsersAce)

# Get the new SDDL and set the even log config
$newSDDL = $sd.GetSddlForm([AccessControlSections]::All)
&wevtutil.exe @('set-log', 'Application', "/ca:$newSDDL")
```

Now I can execute `Get-EventLog` and get result. As I understand for (almost) every command which I want to execute on SSH, needs to be edit SD. OK, but how can I easily find which which *.exe stands for dedicated powershell command? For example: for `Get-Service` it was `sc.exe`, for `Get-EventLog` it was `wevtutil.exe`. What about for `Get-NetTCPConnection` and so on?

**Comment by jborean93** [comment]
> OK, but how can I easily find which which *.exe stands for dedicated powershell command?

There's no easy way, it's just something you learn over time or fine your Googling skills. Usually I search for like

> How to set security descriptor for x

> What about for Get-NetTCPConnection and so on?

The error you got in your comment tells you the underlying protocol that this cmdlet uses

> Get-NetTCPConnection : Cannot connect to CIM server. Access denied

This is saying that it's trying to connect to a CIM server which is just another acronym for WMI. Once again it's the same problems as SCManager and the Event Log where a standard user typically only gets access by the fact that it's an INTERACTIVE when you are logging in locally. To configure the SD for WMI you can either do so interactively with `wmimgmt.msc`. The security is set on the namespace of the WMI class and `Get-NetTCPConnection` is just a wrapper of [MSFT_NetTCPConnection](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/nettcpipprov/msft-nettcpconnection). This means you need to adjust the namespace `Root\StandardCimv2` to give your user/group permissions. I've never had to adjust these settings so I could be wrong about the location, I would search online to see what others recommend for granting access to a WMI namesapce.

**Comment by kanan-m** [comment]
@jborean93 so thanks to you for your support. I found a script on internet and customize as my needs
```
$Namespace = 'StandardCimv2'

$sid = [Security.Principal.NTAccount]::new('XYZ', 'SREngineers').Translate([Security.Principal.SecurityIdentifier])

$WMISDDL = "A;;CCWP;;;$Sid" 
$WMISDDLPartialMatch = "A;\w*;\w+;;;$Sid"

$security = Get-WmiObject -Namespace root\$Namespace -Class __SystemSecurity
$binarySD = @($null)
$result = $security.PsBase.InvokeMethod('GetSD',$binarySD)
$converter = New-Object system.management.ManagementClass Win32_SecurityDescriptorHelper
$CurrentWMISDDL = $converter.BinarySDToSDDL($binarySD[0])

    if ($CurrentWMISDDL.SDDL -match $WMISDDLPartialMatch) {
        $NewWMISDDL = $CurrentWMISDDL.SDDL -replace $WMISDDLPartialMatch, $WMISDDL
    }
    else {
        $NewWMISDDL = $CurrentWMISDDL.SDDL += '(' + $WMISDDL + ')'
    }

$WMIbinarySD = $converter.SDDLToBinarySD($NewWMISDDL)
$WMIconvertedPermissions = ,$WMIbinarySD.BinarySD

$result = $security.PsBase.InvokeMethod('SetSD',$WMIconvertedPermissions)
```
