### ISSUE TITLE
ftp failed but ssh is successful after starting server in local

### ISSUE THREAD

**Issue by echosys** [PowerShell/Win32-OpenSSH#1664]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 7.7.2.3
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 Home
**Client OperatingSystem**
Windows 10 Home
**What is failing**
after starting the server according to this guide, https://winscp.net/eng/docs/guide_windows_openssh_server#win10 
I am able to `ssh username@192.168.11.22` or `ssh username@localhost` to the local server from powershell and `dir` is able to list the information 
Volume in drive C is Windows
 Volume Serial Number is 14EA-F233
 Directory of C:\Users\username
all files are present in the directory listing 

But in browser ftp://localhost/ keep on asking for password and username without any error message, correct input is given, 

In powershell, an error is give when given `ftp localhost`

Connected to DESKTOP-1MKLHSDF.
220 Microsoft FTP Service
200 OPTS UTF8 command successful - UTF8 encoding now ON.
User (DESKTOP-1MKLHSDF:(none)): username
331 Password required
Password:
530-User cannot log in, home directory inaccessible.
 Win32 error:   Access is denied.
 Error details: Authorization rules denied the access.
530 End
Login failed.

The correct password and username is given for ssh and ftp, ssh is able to login but ftp failed, it seems the home directory is not accessible to ftp user but for ssh user is accessible 

**Expected output**
in browser ftp://localhost/ should return error message 

The correct password and username is given for ssh and ftp, ssh is able to login but ftp failed, the home directory should be accessible to ftp user as well

**Actual output**
The correct password and username is given for ssh and ftp, ssh is able to login but ftp failed, it seems the home directory is not accessible to ftp user but for ssh user is accessible

**Comment by jborean93** [comment]
FTP has nothing to do with SSH. You might be thinking of SFTP which uses the `sftp` binary and operates over SSH just like `ssh.exe`.

**Comment by bagajjal** [comment]
@echosys - As @jborean93  mentioned, FTP has nothing to do with SSH.
