### ISSUE TITLE
Can't setup passwordless ssh with public key authentication

### ISSUE THREAD

**Issue by hafizhmakmur** [PowerShell/Win32-OpenSSH#1670]
**Troubleshooting steps**
I have tried to setup a public key authentication SSH mostly following [this guide](https://www.concurrency.com/blog/may-2019/key-based-authentication-for-openssh-on-windows) but in the end I'm still asked for password while using the same guide in other machine I can do it flawlessly. So far I tried to ssh my own computer but of course it's the same when I try to ssh from other machine.

The output of `icacls C:\ProgramData\ssh\adminstrators_authorized_keys` is
```
.\administrators_authorized_keys NT AUTHORITY\SYSTEM:(F)
                                 BUILTIN\Administrators:(F)

Successfully processed 1 files; Failed processing 0 files
```

[Server Log](https://github.com/PowerShell/Win32-OpenSSH/files/5302640/sshd.log)

[Client Log](https://github.com/PowerShell/Win32-OpenSSH/files/5302662/ClientLog.txt)

**"OpenSSH for Windows" version**
7.7.2.3
 
**Server OperatingSystem**
WIndows 10 Pro

**Client OperatingSystem**
Windows 10 Pro, exact same computer

**What is failing**
Can't login to SSH with pubkey

**Expected output**
Login SSH without password prompt

**Actual output**
SSH still prompt for password.

**Comment by bagajjal** [comment]
@hafizhmakmur - Follow the instructions [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Setup-public-key-based-authentication-for-windows).

The adminstrators_authorized_keys should be in c:\programdata\ssh. You have in c:\programdata

**Comment by hafizhmakmur** [comment]
@bagajjal  I'll see the instruction. Btw I mistype. My adminstrators_authorized_keys is already in c:\programdata\ssh ,  not in c:\programdata . Apologies.

**Comment by sasilik** [comment]
Seems that you don't have AllowUsers specified in C:\ProgramData\ssh\sshd_config

**Comment by hafizhmakmur** [comment]
@sasilik  AllowUsers? what should I set it to? I don't see that option in sshd_config

**Comment by sasilik** [comment]
Add at the end of the file - AllowUsers yourusename
Documentation is https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration

**Comment by bagajjal** [comment]
@hafizhmakmur - I think you have your machine name, username are same. Please change one of them then things will start working.
fyi, there is a known bug for this.

**Comment by hafizhmakmur** [comment]
@sasilik I have tried adding AllowUsers makmur and AllowUsers makmur@127.0.0.1 and AllowUsers makmur\makmur but so far the log looks like it still haven't changed.

**Comment by hafizhmakmur** [comment]
@bagajjal Really? That may be the answer! Any info about the known bug? I'll try changing the names.

**Comment by sasilik** [comment]
Shouldn't the authorized_keys file be in the folder youruserfolder\\.ssh\ ?

**Comment by hafizhmakmur** [comment]
> 
> 
> @hafizhmakmur - I think you have your machine name, username are same. Please change one of them then things will start working.
> fyi, there is a known bug for this.

Thank you very much @bagajjal ! It works!!
