### ISSUE TITLE
Chroot not working on OpenSSH v8.1.0.0p1-Beta

### ISSUE THREAD

**Issue by VGzsysadm** [PowerShell/Win32-OpenSSH#1671]
My config:

Subsystem sftp sftp-server.exe
ForceCommand internal-sftp
Match Group sftpgroup
         ChrootDirectory C:\sftp_root\

I tested also with

Match User myuser
         ChrootDirectory C:\sftp_root\myuser

The user has the correct rights inside the folder but when i log in using programs like filezilla or winscp through SFTP connection, the directory opened is %userprofile% ( C:\users\myuser\ ) not C:\sftp_root\myuser

Apparently this functionality was added since v7.0.xx

OpenSSH v8.1.0.0p1-Beta
Windows Server 2016 Standard 10.0 Build 14393

**Comment by eabase** [comment]
It's not recommended to use `Subsystem sftp <own server>`, instead use the internal using: `Subsystem sftp internal-sftp`.
Lacking and obscure documentation, and crappy default sshd_config settings, is the reason this is not very clear.
