### ISSUE TITLE
Where is the documention of the `-sshs` pwsh (or Subsystem?) command line switch?

### ISSUE THREAD

**Issue by eabase** [PowerShell/Win32-OpenSSH#1672]
All over MS and internet there is numerous examples of using the **`-sshs`** command option in the `sshd_config` file, like this: 
```powershell
Subsystem	powershell	c:/progra~1/powershell/7/pwsh.exe -sshs -NoLogo
```

However, I cannot find anything at all about what this does (or supposed to do).
Can someone please document this somewhere and point me to it?

**Comment by sdwheeler** [comment]
The `-sshs` parameter of `pwsh` is only used for running PowerShell as an SSH subsystem. It is not intended or supported for any other use.

This is documented in https://docs.microsoft.com/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core#set-up-on-a-windows-computer.

**Comment by eabase** [comment]
@bagajjal 

^^^ *That* link is not documentation, it says absolutely nothing about the function of that command switch. So why did you close this?

**Comment by bagajjal** [comment]
@eabase -  If the issued is not resolved then please open a new issue in [powershell repo](https://github.com/PowerShell/PowerShell).
It's not related to OpenSSH.
