### ISSUE TITLE
Connection to remote host is closed when CTRL+C pressed.

### ISSUE THREAD

**Issue by eugenov** [PowerShell/Win32-OpenSSH#1675]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 8.1.0.0
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 Home Single Language
**Client OperatingSystem**
CentOS7.4
**What is failing**
SSH session, started in Windows Terminal or Powershell terminal is closed when CTRL+C pressed
**Expected output**
stop executing "top" utility on remote client
**Actual output**
Connection to host closed.

As follows:
...
 8453 root      20   0       0      0      0 S   2.9  0.0 130:07.53 ptlrpcd_00_01 <-- last rows of top output
 8454 root      20   0       0      0      0 S   2.9  0.0 200:51.85 ptlrpcd_00_02 <-- last rows of top output
 8455 root      20   0       0      0      0 S   2.9  0.0 130:16.53 ptlrpcd_00_03 <-- last rows of top output
debug1: channel 0: free: client-session, nchannels 1
Connection to host closed.
Transferred: sent 2556, received 11896 bytes, in 8.7 seconds
Bytes per second: sent 293.8, received 1367.5
debug1: Exit status -1
PS C:\Users\gene>

**Comment by eugenov** [comment]
Seams like forced "-t" option

**Comment by eabase** [comment]
What happens when you open a new subshell and do the same? Still log you out from session, or just the shell?

**Comment by eugenov** [comment]
> 
> 
> What happens when you open a new subshell and do the same? Still log you out from session, or just the shell?

Yes, still terminating session. Maybe it's because i am the owner of ssh.exe, so ctrl+c stops ssh as any other process in local shell? I updated openssh from 7.7 to 8.1 manual way.

**Comment by eugenov** [comment]
Installed Insider Prevew 20231 over May 2020 - still the same. SSH is completely unusable at this moment

**Comment by eugenov** [comment]
I don't know why, but this issue is directly connected with environement DISPLAY setting. There is no such bugs when I remove DISPLAY from windows environement variables...

**Comment by eugenov** [comment]
Found it! This behaviour is caused by "XAuthLocation", defined in SSH ~/.ssh/config file.

**Comment by eabase** [comment]
@eugenov 
> Found it! This behaviour is caused by "XAuthLocation", defined in SSH ~/.ssh/config file.

Great. So what is the correct vs wrong setting?

**Comment by eugenov** [comment]
XAuthLocation is just a path to executable. If one adds it to host description, one has problems. No XAuthLocation - no problems.
