### ISSUE TITLE
Stopping SSHD server doesn't kill already established connections

### ISSUE THREAD

**Issue by eabase** [PowerShell/Win32-OpenSSH#1681]
I would say this is a rather serious security issue, as "*pulling the plug*" doesn't kill all `sshd` processes.

**What is failing**

Killing SSHD with `net stop sshd`, does not kill already established SSH sessions 
You can check with `pslist64.exe | sls "sshd"`. 

**Expected output**

none

**Actual output**

Two sshd processes (for one opened connection):
```
sshd 
sshd
```

**Comment by rtollert** [comment]
This is upstream behavior, and quite explicit — it allows you to administer an sshd install while ssh'd in. If this project's goal is (in general) to be fully merged upstream, I don't expect this behavior to ever change.

**Comment by eabase** [comment]
@rtollert 
> This is upstream behavior, and quite explicit — it allows you to administer an sshd install while ssh'd in. If this project's goal is (in general) to be fully merged upstream, I don't expect this behavior to ever change.

Hi Richard, 
I'm not really sure what you are saying here. Surely if I stop the sshd service on any other OS, it stops. So the issue is not so much about there being 2 sshd processes, but that you explicitly request the service to be stopped, and it isn't. 

So since there is no info output after the attempted stop, this also constitute a serious security issue. Imagine, you setup a test server with password "123" and then stop it and think it's stopped, just to find your machine hacked a few hours later.

**Comment by mwtrigg** [comment]
> I'm not really sure what you are saying here. Surely if I stop the sshd service on any other OS, it stops. So the issue is not so much about there being 2 sshd processes, but that you explicitly request the service to be stopped, and it isn't.

If you stop the sshd service on another OS, the service stops.  If you stop the sshd service on a windows host, the service stops.  It does not kill active ssh sessions.

> So since there is no info output after the attempted stop, this also constitute a serious security issue. Imagine, you setup a test server with password "123" and then stop it and think it's stopped, just to find your machine hacked a few hours later.

I'm not following you.  The sshd service is stopped; therefore subsequent ssh connections fail to connect; but your existing session remains.

This is quite easily demonstrated on windows and non-windows OSes.

**Comment by bagajjal** [comment]
As others were saying this is expected behavior.

"net stop sshd" - Stop the sshd service. No new connections are established. All the old connections are retained.
This is inline with upstream sshd.

**Comment by eabase** [comment]
> 
> 
> As others were saying this is expected behavior.
> 
> "net stop sshd" - Stop the sshd service. No new connections are established. All the old connections are retained.
> This is inline with upstream sshd.

There must be some miscommunication then, because if you look in OP, the SSH *daemon* (here windows service) is still running as seen by the presence of the 2 `sshd` entries. Am I missing something?

**Comment by rtollert** [comment]
@eabase Not at all. You are simply highlighting that
- There is a clear contradiction between the nominal behavior of (virtually all) Windows services, and OpenSSH's explicitly documented behavior; and
- Of the two behaviors, Win32-OpenSSH is choosing to follow *OpenSSH* behavior, not *Windows* behavior. This is, at minimum, a totally internally consistent position to take.

**Comment by rtollert** [comment]
As a useful comparison point: the exact same behavior distinction actually exists on Linux today, with systemd, and the exact same decision was made. By default, when you stop a service in systemd, it kills off all of its spawned processes too (`KillMode=control-group`). But for sshd, at least on my Arch machine, it only kills the service itself (`KillMode=process`).

To be fair, this decision makes a *lot* more sense when you can meaningfully administer a system, up to and including OS upgrades and partial system failures, through ssh. But I'm not entirely certain that Win32-OpenSSH was precisely designed with that workflow in mind, particularly with respect to credentials.

**Comment by eabase** [comment]
@rtollert 
Thanks Richard for the clear explanation.
