### ISSUE TITLE
Invoked .\install-sshd.ps1 and rebooted but there is no sshd Service in Services.msc

### ISSUE THREAD

**Issue by cspencer893** [PowerShell/Win32-OpenSSH#1682]
**Troubleshooting steps**

a. Get latest https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

b. Extract OpenSSH-Win64 folder to 'C:\Program Files\'

c. Create new sysvar Path 'C:\Program Files\OpenSSH-Win64'
d. Enabled scripts Set-ExecutionPolicy RemoteSigned

e. Run 'C:\Program Files\OpenSSH-Win64\install-sshd.ps1'
----> Output was:
[SC] SetServiceObjectSecurity SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
sshd and ssh-agent services successfully installed

f. Disabled scripts Set-ExecutionPolicy Restricted

g. Run 'C:\Program Files\OpenSSH-Win64\ssh-keygen.exe -A'

h. Run services.msc

i. SSHD is supposed to be there but it isn't.

**"OpenSSH for Windows" version**

8.1.0.0
 
**Server OperatingSystem**

Windows 10 Pro

**Client OperatingSystem**

Win 10 Pro

**What is failing**
SSHD is supposed to be shown in Services.msc but it isn't.

**Expected output**
I expect to see sshd services and be able to interact with it

**Actual output**

Nothing

**Comment by jborean93** [comment]
The `Services.msc` GUI does not show the actual service name in the GUI by default but rather the display name. In this case the default display name is `OpenSSH SSH Server`.

![image](https://user-images.githubusercontent.com/8462645/95645450-74105680-0b02-11eb-9139-eece35dc3aa4.png)

You can open up that service in the GUI to get the service name:

![image](https://user-images.githubusercontent.com/8462645/95645463-aa4dd600-0b02-11eb-9e85-b12b2a946dcb.png)

With PowerShell you can easily get both names:

```powershell
PS C:\Windows\system32> Get-Service sshd

Status   Name               DisplayName
------   ----               -----------
Running  sshd               OpenSSH SSH Server
```
