### ISSUE TITLE
DefaultShell DefaultShellCommandOption ignored

### ISSUE THREAD

**Issue by sommella** [PowerShell/Win32-OpenSSH#1688]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`

7.7.2.2
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

Windows Server 2019 Datacenter

**Client OperatingSystem**

**What is failing**

Following this: https://github.com/PowerShell/Win32-OpenSSH/wiki/DefaultShell I have configured:

 New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force
 New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShellCommandOption -Value "-nologo" -PropertyType String -Force

But after SSH Poweshell is still showing the Logo

**Expected output**

PS C:\Users\Administrator>

**Actual output**

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator>

**Comment by jborean93** [comment]
Check out https://github.com/PowerShell/Win32-OpenSSH/issues/1677. The `DefaultShellCommandOption` isn't used for interactive ssh sessions. It is used if you do `ssh username@hostname my_command` but there is a bug where the options are ignored if it is 15 characters or more.

**Comment by sommella** [comment]
Hi,
Thanks for reply.

I need to have interactive shell with a custom MOTD, for this purpose I
have configured the $default script with some write-host.
I would like to also disable the powershell logo (usually done via -
nologo).
There is a way to achieve this with ssh on windows?
Thanks & Regards

**Comment by jborean93** [comment]
Yes, read that issue I linked to, especially the last comment where I talked about using a bat file for the `DefaultShell` option.

**Comment by sommella** [comment]
Thanks!
