### ISSUE TITLE
ssh always prompts for passphrase

### ISSUE THREAD

**Issue by weavage** [PowerShell/Win32-OpenSSH#1692]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
8.1.0.0
 
**Server OperatingSystem**
N/A

**Client OperatingSystem**
Windows 10 Enterprise

**What is failing**
Even when running ssh-agent and adding proper keys, ssh always prompts for the key passphrase

**Expected output**
Terminal prompt on remote box

**Actual output**
debug1: read_passphrase: can't open /dev/tty: No such file or directory
Enter passphrase for key 'C:\Users\myuser/.ssh/id_ed25519':

**Comment by mgkuhn** [comment]
You need to describe your problem in a way that readers here can reproduce, i.e. show the actual command lines that you used, or an equivalent batch file, to set up `ssh-agent` and load a key into it with `ssh-add`, as described at https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement

**Comment by mgkuhn** [comment]
What happened when you ran `ssh-add C:\Users\myuser\.ssh\id_ed25519` and then just `ssh-add`?

**Comment by weavage** [comment]
Hopefully this will provide more detail.

I made sure ssh-agent was running.
``` 
PS C:\Users\myuser> Get-Service ssh-agent

Status   Name               DisplayName
------   ----               -----------
Running  ssh-agent          OpenSSH Authentication Agent
```

I clear the agent of any existing keys.
```
PS C:\Users\myuser> ssh-add -D
All identities removed.
```

No keys loaded.
```
PS C:\Users\myuser> ssh-add -l
The agent has no identities.
```

Now add my key. I ran both as you listed, but they should be equivalent. We're using Vault signed SSH keys, hopefully that doesn't affect things. I have tried the same Vault signed key using git-bash SSH and it works fine there.
```
PS C:\Users\myuser> ssh-add C:\Users\myuser\.ssh\id_ed25519
Enter passphrase for C:\Users\myuser\.ssh\id_ed25519:
Identity added: C:\Users\myuser\.ssh\id_ed25519 (myuser@company.com Vault SSH)
Certificate added: C:\Users\myuser\.ssh\id_ed25519-cert.pub (vault-linux-ssh)
PS C:\Users\myuser> ssh-add
Enter passphrase for C:\Users\myuser/.ssh/id_ed25519:
Identity added: C:\Users\myuser/.ssh/id_ed25519 (myuser@company.com Vault SSH)
Certificate added: C:\Users\myuser/.ssh/id_ed25519-cert.pub (vault-linux-ssh)
```

Show keys are loaded.
```
PS C:\Users\myuser> ssh-add -l
256 SHA256:el6bw7evjtT7v0XQq830yCI72gqdA5PjLfRRErmCC7o myuser@company.com Vault SSH (ED25519-CERT)
```

Now I try to ssh to a server.
```
PS C:\Users\myuser> ssh myuser@myserver.org
******************************************************************
* Systems require authorization; unauthorized access is illegal. *
******************************************************************

Enter passphrase for key 'C:\Users\myuser/.ssh/id_ed25519':
```

I can add some verbose output, but it gets very chatty obviously. Here's an excerpt of the debug output where it appears to try the public key.
```
...
debug1: Authentications that can continue: publickey,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering public key: C:\\Users\\myuser/.ssh/id_ed25519 ED25519-CERT SHA256:el6bw7evjtT7v0XQq830yCI72gqdA5PjLfRRErmCC7o agent
debug1: Server accepts key: C:\\Users\\myuser/.ssh/id_ed25519 ED25519-CERT SHA256:el6bw7evjtT7v0XQq830yCI72gqdA5PjLfRRErmCC7o agent
debug1: read_passphrase: can't open /dev/tty: No such file or directory
Enter passphrase for key 'C:\Users\myuser/.ssh/id_ed25519':
```

If I go ahead and enter the passphrase, it lets me into the server. Everything seems fine, so I can not for the life of me determine if this is some security policy getting in the way or a config issue or what. Open to any and all help somebody can provide. Thanks!

**Comment by yumiki** [comment]
I have the same issue with windows 10 Family. (Openssh 7.7.2.1)

The thing is that I have a key named "ssh2-rsa-openssh.priv" because I have several key for several purpose. I add this key in the ssh config file and everything is fine with pagent about that. But with Openssh I still get the prompt ask for the passphrase even if I'm able to see it by typing ssh-add -l

```
C:\Users\MyUs> ssh-add -l
2048 SHA256:gn6************************************ C:\Users\MyUs\.ssh\ssh2-rsa-openssh.priv (RSA)
```

EDIT:
Solve by upgrading OpenSSH to version 8.0.0.0

**Comment by mgkuhn** [comment]
Just an idea: are you confident that your running ssh-agent is really version 8.1 and not the old 7.7 version that still comes with the latest Windows 10? Perhaps uninstall the OpenSSH version that comes with Windows 10 as an additional featre, to avoid version mixups.

Other's have reported problems with using ssh-agent 7.7: #1659

**Comment by OnikenX** [comment]
@weavage Its probably a problem with permissions, see this link for more info:
https://adamtheautomator.com/openssh-windows/#Configuring_Public_Key_Authentication

**Comment by mgkuhn** [comment]
Is this issue now fixed following the upgrade of the OpenSSH version in Windows Features to 8.1 this week? (Install KB5003173 via Windows Update on the Semi-Annual Channel.)

**Comment by bagajjal** [comment]
Thanks @mgkuhn.

**Comment by weavage** [comment]
Newer versions seem to have fixed this issue (and introduced new ones). Feel free to close.
