### ISSUE TITLE
Domain accounts do not works with key based authentication

### ISSUE THREAD

**Issue by barry-luijten** [PowerShell/Win32-OpenSSH#17]
I'm getting these messages on the server (using debug mode) when trying to log in using public key authentication. I have tried both rsa as dsa keys. Both are placed in .ssh\authorized_keys in my profile directory. Password auth is working.
Should this entry in sshd_config be in Windows format? "AuthorizedKeysFile	.ssh/authorized_keys"

**Comment by manojampalam** [comment]
I've tried it without modifying that entry and it worked fine. What's the OS on server?

**Comment by allegorythm** [comment]
I too have the same error after setting DEBUG logging. Is domain user key exchange supported?  Forgive me if it is unsupported, it is not 100 % clear in the documentation.
Here are the details, hope it helps.  
connection from RHEL 6.5  -> Windows 2008 R2 SP1  (also tested on Windows 2012 SP1 with same results)
/home/opensshtestid/.ssh/id_rsa  has been generated on RHEL linux box and same related pubkey transferred to windows server to the locations below:
c:\users\localid\ .ssh\authorized_keys    (this is the test local admin account)
c:\users\domainid\ .ssh\authorized_keys  (this is a test domain account. This account is a member of local admin group on the windows server)

testing results:

local id test (key exchange works fine)

[opensshtestid@10.193.42.224] ssh localid@10.192.44.41   
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
localid@10.192.44.41 C:\Users\localid>

log snippet
4732 12:18:36 719 Connection from 10.193.42.224 port 43087 on 10.192.44.41 port 22
4732 12:18:36 721 debug1: Client protocol version 2.0; client software version OpenSSH_5.3
4732 12:18:36 721 debug1: match: OpenSSH_5.3 pat OpenSSH_5* compat 0x0c000000
4732 12:18:36 721 debug1: Enabling compatibility mode for protocol 2.0
4732 12:18:36 721 debug1: Local version string SSH-2.0-OpenSSH_7.1
4732 12:18:36 721 debug1: list_hostkey_types: ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
4732 12:18:36 721 debug1: SSH2_MSG_KEXINIT sent
4732 12:18:36 722 debug1: SSH2_MSG_KEXINIT received
4732 12:18:36 722 debug1: kex: client->server aes128-ctr hmac-sha1 none
4732 12:18:36 722 debug1: kex: server->client aes128-ctr hmac-sha1 none
4732 12:18:36 722 debug1: expecting SSH2_MSG_KEX_DH_GEX_REQUEST
4732 12:18:36 920 debug1: SSH2_MSG_KEX_DH_GEX_REQUEST received
4732 12:18:36 920 WARNING: /moduli does not exist, using fixed modulus
4732 12:18:36 921 debug1: SSH2_MSG_KEX_DH_GEX_GROUP sent
4732 12:18:36 967 debug1: expecting SSH2_MSG_KEX_DH_GEX_INIT
4732 12:18:37 081 debug1: SSH2_MSG_NEWKEYS sent
4732 12:18:37 081 debug1: expecting SSH2_MSG_NEWKEYS
4732 12:18:37 095 debug1: SSH2_MSG_NEWKEYS received
4732 12:18:37 095 debug1: KEX done
4732 12:18:37 291 debug1: userauth-request for user localid service ssh-connection method none
4732 12:18:37 292 debug1: attempt 0 failures 0
4732 12:18:37 293 Failed none for localid from 10.193.42.224 port 43087 ssh2
4732 12:18:37 294 debug1: userauth-request for user localid service ssh-connection method publickey
4732 12:18:37 294 debug1: attempt 1 failures 0
4732 12:18:37 294 debug1: test whether pkalg/pkblob are acceptable
4732 12:18:37 294 Postponed publickey for localid from 10.193.42.224 port 43087 ssh2
4732 12:18:37 302 debug1: userauth-request for user localid service ssh-connection method publickey
4732 12:18:37 302 debug1: attempt 2 failures 0
4732 12:18:37 303 debug1: -> LsaLogon()...
4732 12:18:37 303 debug1: Checking args...
4732 12:18:37 303 debug1: Setting up LSA Strings...
4732 12:18:37 304 debug1: LsaRegisterLogonProcess()...
4732 12:18:37 305 debug1: Retrieving Authentification Package ID...
4732 12:18:37 305 debug1: Allocating LsaAuth struct...
4732 12:18:37 305 debug1: Setting up TOKEN_SOURCE...
4732 12:18:37 305 debug1: Login attemp...
4732 12:18:51 673 debug1: login status: 0...
4732 12:18:51 673 debug1: homedir = [C:\Users\localid]
4732 12:18:51 673 debug1: Duplicating token...
4732 12:18:51 674 debug1: LsaLogon : OK.
4732 12:18:51 675 debug1: <- LsaLogon()...
4732 12:18:51 675 debug1: Using LSA HomeDirW.
4732 12:18:51 675 debug1: trying public key file C
4732 12:18:51 676 debug1: allocating new sfd, sfd [4] fd [5] handle [416] type [1]
4732 12:18:51 676 debug1: matching key found: file C, line 1 RSA SHA256:dYjWtR/46CZA9ivk4XAD1YHgesINXbN3jrPgfoOkvKY
4732 12:18:51 677 Accepted publickey for localid from 10.193.42.224 port 43087 ssh2: RSA SHA256:dYjWtR/46CZA9ivk4XAD1YHgesINXbN3jrPgfoOkvKY
4732 12:18:51 677 debug1: Entering interactive session for SSH2.
4732 12:18:51 677 debug1: server_init_dispatch_20
4732 12:18:51 678 debug1: server_input_channel_open: ctype session rchan 0 win 1048576 max 16384
4732 12:18:51 678 debug1: input_session_request
4732 12:18:51 678 debug1: channel 0: new [server-session]
4732 12:18:51 679 debug1: session_new: session 0
4732 12:18:51 679 debug1: session_open: channel 0
4732 12:18:51 679 debug1: session_open: session 0: link with channel 0
4732 12:18:51 679 debug1: server_input_channel_open: confirm session
4732 12:18:51 679 debug1: server_input_global_request: rtype no-more-sessions@openssh.com want_reply 0
4732 12:18:51 681 debug1: server_input_channel_req: channel 0 request pty-req reply 1
4732 12:18:51 681 debug1: session_by_channel: session 0 channel 0
4732 12:18:51 681 debug1: session_input_channel_req: session 0 req pty-req
4732 12:18:51 681 debug1: Allocating pty.
4732 12:18:51 681 debug1: session_pty_req: session 0 alloc console
etc...

domain id test (key exhange not working, authentication is ok).  As I mentioned, the same authorized key file is used as in previous test.
[opensshtestid@10.193.42.224]  ssh -l domainid@domain 10.192.44.41
opensshtestid@domain@10.192.44.41's password:                                                                                 Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

after domain password is entered manually, authentication is successful as shown above


4268 12:29:24 732 Connection from 10.193.42.224 port 43112 on 10.192.44.41 port 22
4268 12:29:24 734 debug1: Client protocol version 2.0; client software version OpenSSH_5.3
4268 12:29:24 734 debug1: match: OpenSSH_5.3 pat OpenSSH_5* compat 0x0c000000
4268 12:29:24 734 debug1: Enabling compatibility mode for protocol 2.0
4268 12:29:24 734 debug1: Local version string SSH-2.0-OpenSSH_7.1
4268 12:29:24 734 debug1: list_hostkey_types: ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
4268 12:29:24 734 debug1: SSH2_MSG_KEXINIT sent
4268 12:29:24 736 debug1: SSH2_MSG_KEXINIT received
4268 12:29:24 736 debug1: kex: client->server aes128-ctr hmac-sha1 none
4268 12:29:24 736 debug1: kex: server->client aes128-ctr hmac-sha1 none
4268 12:29:24 736 debug1: expecting SSH2_MSG_KEX_DH_GEX_REQUEST
4268 12:29:24 935 debug1: SSH2_MSG_KEX_DH_GEX_REQUEST received
4268 12:29:24 935 WARNING: /moduli does not exist, using fixed modulus
4268 12:29:24 935 debug1: SSH2_MSG_KEX_DH_GEX_GROUP sent
4268 12:29:24 960 debug1: expecting SSH2_MSG_KEX_DH_GEX_INIT
4268 12:29:25 055 debug1: SSH2_MSG_NEWKEYS sent
4268 12:29:25 055 debug1: expecting SSH2_MSG_NEWKEYS
4268 12:29:25 069 debug1: SSH2_MSG_NEWKEYS received
4268 12:29:25 069 debug1: KEX done
4268 12:29:25 276 debug1: userauth-request for user opensshtestid@domain service ssh-connection method none
4268 12:29:25 276 debug1: attempt 0 failures 0
4268 12:29:25 277 Failed none for opensshtestid@domain from 10.193.42.224 port 43112 ssh2
4268 12:29:25 278 debug1: userauth-request for user opensshtestid@domain service ssh-connection method publickey
4268 12:29:25 278 debug1: attempt 1 failures 0
4268 12:29:25 278 debug1: test whether pkalg/pkblob are acceptable
4268 12:29:25 279 Postponed publickey for opensshtestid@domain from 10.193.42.224 port 43112 ssh2
4268 12:29:25 286 debug1: userauth-request for user opensshtestid@domain service ssh-connection method publickey
4268 12:29:25 286 debug1: attempt 2 failures 0
4268 12:29:25 288 debug1: -> LsaLogon()...
4268 12:29:25 288 debug1: Checking args...
4268 12:29:25 288 debug1: Setting up LSA Strings...
4268 12:29:25 289 debug1: LsaRegisterLogonProcess()...
4268 12:29:25 290 debug1: Retrieving Authentification Package ID...
4268 12:29:25 290 debug1: Allocating LsaAuth struct...
4268 12:29:25 290 debug1: Setting up TOKEN_SOURCE...
4268 12:29:25 290 debug1: Login attemp...
4268 12:29:25 673 debug1: SSH-LSA authorization failed. (err = 0, ntStat = c000006d).
4268 12:29:25 674 debug1: <- LsaLogon()...
4268 12:29:25 675 Failed publickey for opensshtestid@domain from 10.193.42.224 port 43112 ssh2: RSA SHA256:dYjWtR/46CZA9ivk4XAD1YHgesINXbN3jrPgfoOkvKY
4268 12:29:25 676 debug1: userauth-request for user opensshtestid@domain service ssh-connection method keyboard-interactive
4268 12:29:25 676 debug1: attempt 3 failures 1
4268 12:29:25 676 debug1: keyboard-interactive devs 
4268 12:29:25 676 debug1: auth2_challenge: user=opensshtestid@domain devs=
4268 12:29:25 677 debug1: kbdint_alloc: devices ''
4268 12:29:25 677 Failed keyboard-interactive for opensshtestid@domain from 10.193.42.224 port 43112 ssh2
4268 12:29:44 954 debug1: userauth-request for user opensshtestid@domain service ssh-connection method password
4268 12:29:44 954 debug1: attempt 4 failures 2
4268 12:29:45 077 Accepted password for opensshtestid@domain from 10.193.42.224 port 43112 ssh2
4268 12:29:45 078 debug1: Entering interactive session for SSH2.
4268 12:29:45 078 debug1: server_init_dispatch_20
4268 12:29:45 080 debug1: server_input_channel_open: ctype session rchan 0 win 1048576 max 16384
4268 12:29:45 080 debug1: input_session_request
4268 12:29:45 080 debug1: channel 0: new [server-session]
4268 12:29:45 080 debug1: session_new: session 0
4268 12:29:45 080 debug1: session_open: channel 0
4268 12:29:45 080 debug1: session_open: session 0: link with channel 0
4268 12:29:45 080 debug1: server_input_channel_open: confirm session
4268 12:29:45 080 debug1: server_input_global_request: rtype no-more-sessions@openssh.com want_reply 0
4268 12:29:45 121 debug1: server_input_channel_req: channel 0 request pty-req reply 1
4268 12:29:45 122 debug1: session_by_channel: session 0 channel 0
4268 12:29:45 122 debug1: session_input_channel_req: session 0 req pty-req
4268 12:29:45 122 debug1: Allocating pty.
4268 12:29:45 122 debug1: session_pty_req: session 0 alloc console

**Comment by monsoft** [comment]
I have this same issue with key authentication.

**Comment by ercmcd** [comment]
I too am receiving this error. Anyone else able to figure this out?

**Comment by wese33** [comment]
Any solutions yet?

**Comment by manojampalam** [comment]
We are still evaluating security implications of mapping domain accounts with keys that are not associated with AD. This may bypass AD security model. In Windows world, relevant scenarios are implemented by "AD issued user certificates".

**Comment by jhudsoncedaron** [comment]
I consider this ability essential to a Windows port of ssh; we intend to use this for massive cross-domain automation. As you know, automation with a simple scripting language must use publickey auth because it can't contain an expect-loop for password and unless you've hacked the client it won't prompt anyway.

To avoid bypassing AD security model; check that the user is not disabled. You're probably going to have to disallow access to network resources, like the scheduled task switch "Do not save password. The task will only have access to local resources." But we can always get a network resource by calling ssh again.

**Comment by manojampalam** [comment]
Support for domain accounts is added in latest release 5_15_2016
