### ISSUE TITLE
Cannot login with domain account using alternative UPN suffix

### ISSUE THREAD

**Issue by scottmckenzie** [PowerShell/Win32-OpenSSH#170]
With the latest release (3_19_2016 1.1) I am not able to login with my domain user account that uses an alternative UPN suffix.  This was working with the previous release.

As a workaround I am able to login with the default UPN suffix for our domain even though that is not the UPN suffix that my user account uses.

**Comment by manojampalam** [comment]
Please detail the exact format of user names being used. Try if it works on the latest release. Reopen if needed
