### ISSUE TITLE
Add to documentation for ssh server login using public key auth to an admin user. 

### ISSUE THREAD

**Issue by codero7** [PowerShell/Win32-OpenSSH#1701]
As a Unix user, it was tough to figure out the problem with public key authentication noted here: [https://superuser.com/questions/1538449/unable-to-use-publickey-authentication-on-win32-open-ssh-server](https://superuser.com/questions/1538449/unable-to-use-publickey-authentication-on-win32-open-ssh-server)
This [page ](https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples) makes no note that it is not enough to just add the public key to .ssh/authorized_keys but in the case we are dealing with an administrator user we need to also add it to C:\ProgramData\ssh\administrators_authorized_keys and also edit the permissions afterwards (So only SYSTEM and Administrators have Permission). The page is misleading and since most internet guides are unix based then this can become very confusing as we only see a failure in public key during login from the client side and no indication that administrators_authorized_keys is actually essential for ssh to any administrator user.

Alternatively, another page could also be added to explain administrators_authorized_keys file and its importance.

**Comment by bagajjal** [comment]
It's documented [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Setup-public-key-based-authentication-for-windows).  Please let me know if this doesn't work.
