### ISSUE TITLE
openssh client bugged on windows with user folder including Chinese-charactor

### ISSUE THREAD

**Issue by Asxcvbn** [PowerShell/Win32-OpenSSH#1704]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
> (Get-Item (Get-Command ssh).Source).VersionInfo.FileVersion
7.7.2.1
i didn't installed sshd. just ssh in windows10 `Manage optional features'.
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Err, should i say linux?  CentOS7, and other ssh clients can connect to this server.
**Client OperatingSystem**
> ((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)
Windows 10 Pro
**What is failing**

for example, someone's username is "用户" and thus his user folder is “C:\Users\用户”， and he might run ssh.exe on his cmd or powershell to remote: user@remote. basic usage like ssh user@remote works, yet one cant use "-i" option to use a identity file, with error like "cannot create directory C:\\Users\\\312\21\234\132\423\152/.ssh" (here the \xxxx nums are just to show the case). and with config files and valid identity key files you are still prompted to input password for the site.
and ssh-keygen cant just save key to home folder/.ssh.

here
at %HOME, we run 
```cmd
ssh -vvv -i .ssh\id_ed25519 username@example.com
```
**Expected output**
we may expect to login example.com with username and identify file .ssh\id_ed25519
(this identity file exists)
**Actual output**
please note that for privacy reasons, username, host, ip and \xxxnums are just for showing the cast, not what is running here, thus \xxx nums may not corrospond to the local username here "用户", and example.com and ip address here will not match. 

C:\Users\用户>ssh -vvv -i .ssh\id_ed25519 llux@example.com
Warning: Identity file .ssh\id_ed25519 not accessible: No such file or directory.
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolving "example.com" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to example.com [212.132.3.193] port 22.
debug1: Connection established.
Could not create directory 'C:\\Users\\\312\21\234\132\423\152/.ssh'.

debug1: key_load_public: Invalid argument
debug1: identity file C:\\Users\\\312\21\234\132\423\152/.ssh/id_rsa type -1

debug1: key_load_public: Invalid argument
debug1: identity file C:\\Users\\\312\21\234\132\423\152/.ssh/id_rsa-cert type -1

debug1: key_load_public: Invalid argument
debug1: identity file C:\\Users\\\312\21\234\132\423\152/.ssh/id_dsa type -1

debug1: key_load_public: Invalid argument
debug1: identity file C:\\Users\\\312\21\234\132\423\152/.ssh/id_dsa-cert type -1

debug1: key_load_public: Invalid argument
debug1: identity file C:\\Users\\\312\21\234\132\423\152/.ssh/id_ecdsa type -1

debug1: key_load_public: Invalid argument
debug1: identity file C:\\Users\\\312\21\234\132\423\152/.ssh/id_ecdsa-cert type -1

debug1: key_load_public: Invalid argument
debug1: identity file C:\\Users\\\312\21\234\132\423\152/.ssh/id_ed25519 type -1

debug1: key_load_public: Invalid argument
debug1: identity file C:\\Users\\\312\21\234\132\423\152/.ssh/id_ed25519-cert type -1

debug1: key_load_public: Invalid argument
debug1: identity file C:\\Users\\\312\21\234\132\423\152/.ssh/id_xmss type -1

debug1: key_load_public: Invalid argument
debug1: identity file C:\\Users\\\312\21\234\132\423\152/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to example.com:22 as 'llux'

debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:Cgv5E5AQRTKK8N3Pr2bWEw2/kh1/puiLPjCBbH70Bv0

debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2

debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug3: failed to open file:C:/dev/tty error:3
debug1: read_passphrase: can't open /dev/tty: No such file or directory
The authenticity of host 'example.com (212.132.3.193)' can't be established.
ECDSA key fingerprint is SHA256:Cgv5E5AQRTKK8N3Pr2bWEw2/kh1/puiLPjCBbH70Bv0.
Are you sure you want to continue connecting (yes/no)?

**Comment by mgkuhn** [comment]
Considering the number of Unicode issues fixed between versions 7.7 and 8.1: can you reproduce this issue with the current release 8.1?

**Comment by Asxcvbn** [comment]
> 
> 
> Considering the number of Unicode issues fixed between versions 7.7 and 8.1: can you reproduce this issue with the current release 8.1?

the new version 8.1 appeares to have fixed this issue, note that the key files created in 7.7 with username included Chinese charactors looks buggy, and cannot work. i have to re gen the keys using openssh 8.1. 

now a problem arises:  windows is still shipped with old version(7.7p1) of openssh... even till 20h2 19042.685, the latest non insider version i got. i can manually update my openssh, but not everyone may do this

**Comment by mgkuhn** [comment]
The issue of Windows 10 20H2 accidentally still having been shipped with the rather old and comparatively buggy v7.7 of OpenSSH for Windows is already being tracked at #1693. So you can close this issue now if the problem you reported originally is already fixed in v8.1.

**Comment by Asxcvbn** [comment]
> 
> 
> The issue of Windows 10 20H2 accidentally still having been shipped with the rather old and comparatively buggy v7.7 of OpenSSH for Windows is already being tracked at #1693. So you can close this issue now if the problem you reported originally is already fixed in v8.1.

got. thanks
