### ISSUE TITLE
Is it possible not to show the host name in the command prompt?

### ISSUE THREAD

**Issue by xeriax** [PowerShell/Win32-OpenSSH#1708]
Hi there,
is it possible to remove/hide the host name  shown in the command prompt?

**Comment by mgkuhn** [comment]
Your prompt is controlled by an environment variable.

If your shell is `cmd.exe`, try
```
set PROMPT=$P$G
```
You can also try to add the line
```
PROMPT=$P$G
```
to your `%USERPROFILE%\.ssh\environment` file. You will have to enable `PermitUserEnvironment` in your sshd configuration.

There is also the possibility to use `SendEnv MYVAR` on the server side and `AcceptEnv MYVAR`.

**Comment by xeriax** [comment]
@mgkuhn 
Thank you very much, this works.

😄
