### ISSUE TITLE
Ability to chose elevation at connection time

### ISSUE THREAD

**Issue by mwisnicki** [PowerShell/Win32-OpenSSH#1713]
**"OpenSSH for Windows" version**
7.7.2.3
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
Right now admin users are always elevated. ~~It is possible to change it globally with registry setting.~~ (It would be nice if that was the case).
Additionally admin users `authorized_keys` are ignored and instead `__PROGRAMDATA__/ssh/administrators_authorized_keys` is being used as per default `sshd_config`.

**Expected output**
I would like ability to chose whether to elevate on connection time.
I could see it done with some modifiers on user name, e.g. `ssh marcin@UAC@localhost` or maybe via magical SetEnv property.
In case no elevation is requested, authorized_keys should be read from home directory.

**Comment by bagajjal** [comment]
This is by design.

All admin user network connections are elevated. If this is a problem then use non-admin users.
