### ISSUE TITLE
Provide credentials to SSH connections for automation

### ISSUE THREAD

**Issue by 0byt3** [PowerShell/Win32-OpenSSH#1714]
Is there a way I can automate SSH connections without public key authentication.

Say I want to connect to a bunch of computers to set up public key authentication, because it isn't set up yet and I want to do this over SSH. I would be in a position where I need to use a password, but I am not finding a way or a tool to do this by using a credential file or something like that.

Is there a tool like "expect" on Linux that would work?

In WindowsPowershell (Powershell 3-5.1), I could use PoSH-SSH, however PoSH-SSH is not supported in Powershell Core.
In Linux I would use sshpass .

**Comment by bagajjal** [comment]
You can use SSHASKPASS 
1.	Download the [sample utility](https://github.com/PowerShell/openssh-portable/raw/latestw_all/regress/pesterTests/utilities/askpass_util/askpass_util.exe) which will echo the password from an environment variable. 
Let’s say "e:\ssh\askpass_util.exe" is path on your machine.
2. set environment value
       $env:DISPLAY=1
       $env:SSH_ASKPASS="e:\ssh\askpass_util.exe"
       $env:ASKPASS_PASSWORD="password"
3. Now try ssh
       ssh testuser@myTest1

**Comment by 0byt3** [comment]
Just realized that I never thanked you for this. How rude of me.

Thank you so much, this has helped me a lot!

**Comment by matsmcp** [comment]
Thanks for writing this. 
It solved a major issue here
