### ISSUE TITLE
Instead of Russian letters, the numbers in sftp-server. log are shown

### ISSUE THREAD

**Issue by Okorokov** [PowerShell/Win32-OpenSSH#1718]
Hi. 
In the sftp-server. log file, the path to the file and the name of the file, instead of Russian letters, numbers
Example:
4408 2020-12-01 16:40:09.995 opendir "/C:/Users/Obt/\320\234\320\276\320\270 \320\264\320\276\320\272\321\203\320\274\320\265\320\275\321\202\321\213/\320\234\320\276\320\270 \321\200\320\270\321\201\321\203\320\275\320\272\320\270"
4408 2020-12-01 16:40:11.665 closedir "/C:/Users/Obt/\320\234\320\276\320\270 \320\264\320\276\320\272\321\203\320\274\320\265\320\275\321\202\321\213/\320\234\320\276\320\270 \321\200\320\270\321\201\321\203\320\275\320\272\320\270"

What is the problem?
sshd_config
Subsystem	sftp	sftp-server.exe -l INFO -f LOCAL0

**Comment by Okorokov** [comment]
что не кто с такой проблемой не встречался?

**Comment by bagajjal** [comment]
@Okorokov - Please try this with OpenSSH v8.1

**Comment by vthiebaut10** [comment]
@Okorokov  - Please try this private [sftp-server binary](https://github.com/PowerShell/Win32-OpenSSH/files/6361470/sftp-server.zip), and let us knows if it fixes your issue.
Please follow these steps:

cd to openssh bin folder.
take backup of sftp-server.exe
copy the private sftp-server binary to bin folder.
start sftp connection
try your scenario.

Let us knows if that solves your issue.
