### ISSUE TITLE
SFTP File Size Limit(cannot transfer any files larger than 2.9GB) 

### ISSUE THREAD

**Issue by spagetthicoder** [PowerShell/Win32-OpenSSH#172]
I'm using Win32-OpenSSH as an SFTP Server but it looks like there is a file size limit for viewing(on the server side), uploading and downloading files. Is this intentional? I have a file with size of 2.9GB which I cannot upload or download. I can't even view any "large" files located on the server using FileZilla or WinSCP clients. When I try to upload the file the progress bar gets to about 70% and the following error occurs:
**_Bad message (badly formatted packet or protocol incompatibility). Error code: 5 Error message from server: Bad message_**

In addition when the same file is split into 2 or more smaller in size files it can be transferred and viewed without a problem.

**Comment by manojampalam** [comment]
I've tried it on my end and was able to transfer files upto 10 GB. Try the latest version/
