### ISSUE TITLE
Question - when will version 8.1 be part of Windows as an add-on?

### ISSUE THREAD

**Issue by danizen** [PowerShell/Win32-OpenSSH#1721]
This is only a question, and not an issue with the software.  I conducted an evaluation because our Cloud architect installed v8.1.0.0p1-Beta, and our ATO for our cloud requires PIV login.  It would be a good idea to use Microsoft OpenSSH, but only when the Windows add-on has support for PIV login.

Can you provide some general expectations (which are non-binding)?

I tried it both as a downloadable ZIP and as an add-on installation because I have a more complicated development environment than most which features using SSH Agent.

**Comment by bagajjal** [comment]
I think you are talking about changes in this PR (https://github.com/PowerShell/openssh-portable/pull/3620)?

**Comment by dekiesel** [comment]
> https://github.com/PowerShell/openssh-portable/pull/3620

Is it possible you meant https://github.com/PowerShell/openssh-portable/pull/362
?

**Comment by bagajjal** [comment]
@dekiesel - Yes. Thanks for correcting the typo.

**Comment by danizen** [comment]
No, that is not exactly what I mean't, and in fact I may be confused about the role of this repository.  Is this an official Microsoft repository?  Is it the upstream of the Windows OpenSSH-client and server optional features?

It was my impression that both of these were true.

**Comment by bagajjal** [comment]
Yes. It's an official Microsoft repository. It's shipped as Github release and also as windows inbox optional features (client and server optional features).

**Comment by mgkuhn** [comment]
The issue title sounds like a duplicate of #1693.

**Comment by danizen** [comment]
Closing as duplicate of #1693.

**Comment by danizen** [comment]
And thank you all :)
