### ISSUE TITLE
SSH_ASKPASS_REQUIRED not respected

### ISSUE THREAD

**Issue by runapp** [PowerShell/Win32-OpenSSH#1726]
**"OpenSSH for Windows" version**
8.1.0.0

**Client OperatingSystem**
Windows 10 Enterprise LTSC 2019

**What is failing**
`ssh` still tries to call `ssh_askpass` even if `SSH_ASKPASS_REQUIRED` is set to `never`.

**Expected output**
[`SSH_ASKPASS_REQUIRE` allows further control over the use of an askpass program. If this variable is set to `never` then ssh will never attempt to use one.](https://man.openbsd.org/ssh.1#SSH_ASKPASS_REQUIRE)

**Actual output**
```
PS C:\Users\runapp> echo $env:SSH_ASKPASS
PS C:\Users\runapp> echo $env:SSH_ASKPASS_REQUIRE
never
PS C:\Users\runapp> $env:DISPLAY='localhost:0.0'
PS C:\Users\runapp> ssh root@127.0.0.1
CreateProcessW failed error:2
ssh_askpass: posix_spawnp: No such file or directory
Host key verification failed.
```

**Comment by bagajjal** [comment]
[SSH_ASKPASS_REQUIRE](https://github.com/openssh/openssh-portable/commit/aaa8b609a7b332be836cd9a3b782422254972777#diff-2e506269754a88672db257abd79b4cf6ed187ecad809e5fa86e7f843eca20756)  is introduced in OpenSSH V8.4. Current Windows latest version is V8.1.
I'm working on upgrading to V8.4.

**Comment by runapp** [comment]
Got it. I'll try to use a dummy `ssh_askpass.exe` instead, temporarily.
