### ISSUE TITLE
client_loop send disconnect

### ISSUE THREAD

**Issue by altjx** [PowerShell/Win32-OpenSSH#1728]
I'm using Windows Server 2016 Datacenter and I'm just having some issues with very basic functionality. I just downloaded the latest release (v8.1.0.0p1-Beta) and just having issues even getting the ssh server to work properly.

I have started the ssh server using the following syntax from cygwin:

```
/cygdrive/d/Users/myuser/Documents/OpenSSH-Win64/OpenSSH-Win64/sshd.exe -f C:/programData/ssh/sshd_config
```

The `sshd_config` file is basically a copy of the `sshd_config_default` file except `PermitRootLogin` is set to `yes`

Every time I try to initiate an SSH connection to myself, it just drops with the following error:

```
client_loop: send disconnect: Connection reset by peer
```

I tried initiating this with `-vv` to enable verbose logging, and this is what it looks like:

```
debug2: we did not send a packet, disable method
debug1: Next authentication method: keyboard-interactive
debug2: userauth_kbdint
debug2: we sent a keyboard-interactive packet, wait for reply
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug2: we did not send a packet, disable method
debug1: Next authentication method: password
myuser@localhost's password:
debug2: we sent a password packet, wait for reply
debug1: Authentication succeeded (password).
Authenticated to localhost ([::1]:22).
debug1: channel 0: new [client-session]
debug2: channel 0: send open
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
client_loop: send disconnect: Connection reset by peer
```

Any help would be greatly appreciated.

**Comment by bagajjal** [comment]
Try installing sshd as service. Follow instructions [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH).

Please follow the troubleshooting steps listed [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps)

**Comment by altjx** [comment]
I've visited those manuals. I finally got SSH to start using the service, but now I can't connect to it and nothing in the article helps. I've tried enabling logging on both the client and the server. The server doesn't report any logs and the client doesn't really provide anything that's useful:

```
$ ssh root@localhost -o PubKeyAuthentication=no -vvv
OpenSSH_8.4p1, OpenSSL 1.1.1f  31 Mar 2020
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/sbutler49/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/sbutler49/.ssh/known_hosts2'
debug2: resolving "localhost" port 22
debug2: ssh_connect_direct
debug1: Connecting to localhost [::1] port 22.
debug1: Connection established.
debug1: identity file /home/sbutler49/.ssh/id_rsa type -1
debug1: identity file /home/sbutler49/.ssh/id_rsa-cert type -1
debug1: identity file /home/sbutler49/.ssh/id_dsa type -1
debug1: identity file /home/sbutler49/.ssh/id_dsa-cert type -1
debug1: identity file /home/sbutler49/.ssh/id_ecdsa type -1
debug1: identity file /home/sbutler49/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/sbutler49/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/sbutler49/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/sbutler49/.ssh/id_ed25519 type -1
debug1: identity file /home/sbutler49/.ssh/id_ed25519-cert type -1
debug1: identity file /home/sbutler49/.ssh/id_ed25519_sk type -1
debug1: identity file /home/sbutler49/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/sbutler49/.ssh/id_xmss type -1
debug1: identity file /home/sbutler49/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.4
kex_exchange_identification: read: Connection reset by peer
Connection reset by ::1 port 22

```

**Comment by bagajjal** [comment]
https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities

By default server writes the logs to ETW. You can configure sshd service to write to a log file..
1) Add these lines to c:\programdata\ssh\sshd_config file.
SyslogFacility LOCAL0
LogLevel DEBUG3

2) restart sshd service
net stop sshd
net start sshd

3) connect to ssh service
ssh -vvv user@ip

**Comment by bagajjal** [comment]
Please reopen with logs, if you still have issues.
