### ISSUE TITLE
5952 2021-01-24 17:42:24.399 Connection from 127.0.0.1 port 53430 on 127.0.0.1 port 22 5952 2021-01-24 17:42:24.399 error: kex_exchange_identification: write: Connection reset

### ISSUE THREAD

**Issue by Oz691** [PowerShell/Win32-OpenSSH#1729]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
v8.1.0.0p1-Beta
 
**Server OperatingSystem**
windows server 2016

**Client OperatingSystem**

**What is failing**
after completing all the steps provided, when i try to connect to the server using SFTP, it gives the following error in the log file 
**Expected output**
should able to log me in the folder

**Actual output**
it does not connect, 

Log File:
5952 2021-01-24 17:42:24.399 Connection from 127.0.0.1 port 53430 on 127.0.0.1 port 22
5952 2021-01-24 17:42:24.399 error: kex_exchange_identification: write: Connection reset

**Comment by bagajjal** [comment]
@usman1158  - Please share the ssh client logs (ssh -vvv user@ip) and sshd server logs with DEBUG3.

**Comment by bagajjal** [comment]
Reopen with logs if you still have issues.
