### ISSUE TITLE
Invalid Argument

### ISSUE THREAD

**Issue by paulewog** [PowerShell/Win32-OpenSSH#173]
I'm getting an "invalid argument" on one of my test machines.  It never gets to the SSH prompt.  Client side logs:

```
$ ssh -v Administrator@sjx64z9r cmd /c echo hi
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: Connecting to sjx64z9r [REDACTED] port 22.
debug1: Connection established.
debug1: identity file /Users/paul/.ssh/id_rsa type 1
debug1: identity file /Users/paul/.ssh/id_rsa-cert type -1
debug1: identity file /Users/paul/.ssh/id_dsa type -1
debug1: identity file /Users/paul/.ssh/id_dsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.2

debug1: Remote protocol version 2.0, remote software version OpenSSH_7.1p1 Microsoft_Win32_port_with_VS
debug1: match: OpenSSH_7.1p1 Microsoft_Win32_port_with_VS pat OpenSSH*
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-sha1-etm@openssh.com none
debug1: kex: client->server aes128-ctr hmac-sha1-etm@openssh.com none
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(1024<2048<8192) sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_GROUP
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_REPLY
Read from socket failed: Connection reset by peer
```

Server side:

```
2116 22:19:18 578 debug1: allocating new sfd, sfd [3] fd [4] handle [356] type [2]
2116 22:19:18 578 Connection from 9.80.228.49 port 59648 on 9.30.121.53 port 22
2116 22:19:18 578 debug1: Client protocol version 2.0; client software version OpenSSH_6.2
2116 22:19:18 578 debug1: match: OpenSSH_6.2 pat OpenSSH* compat 0x04000000
2116 22:19:18 578 debug1: Enabling compatibility mode for protocol 2.0
2116 22:19:18 578 debug1: Local version string SSH-2.0-OpenSSH_7.1p1 Microsoft_Win32_port_with_VS
2116 22:19:18 578 debug1: list_hostkey_types: ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
2116 22:19:18 578 debug1: SSH2_MSG_KEXINIT sent
2116 22:19:18 765 debug1: SSH2_MSG_KEXINIT received
2116 22:19:18 765 debug1: kex: algorithm: diffie-hellman-group-exchange-sha256
2116 22:19:18 765 debug1: kex: host key algorithm: ssh-rsa
2116 22:19:18 765 debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none
2116 22:19:18 765 debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none
2116 22:19:18 765 debug1: expecting SSH2_MSG_KEX_DH_GEX_REQUEST
2116 22:19:19 125 debug1: SSH2_MSG_KEX_DH_GEX_REQUEST received
2116 22:19:19 125 WARNING: /moduli does not exist, using fixed modulus
2116 22:19:19 125 debug1: SSH2_MSG_KEX_DH_GEX_GROUP sent
2116 22:19:19 125 debug1: expecting SSH2_MSG_KEX_DH_GEX_INIT
2116 22:19:19 328 fatal: ssh_dispatch_run_fatal: Connection to 9.80.228.49: invalid argument
2116 22:19:19 328 debug1: do_cleanup
```

**Comment by paulewog** [comment]
The server works when you use the Windows client.  The only major difference I can see is the key algorithm, one being the Diffie-Hellman Group Exchange (shows up when I use my Mac's SSH client) and one being the elliptical curve thingy (this is used when I try using the Windows ssh client).

This is the original March release (not 1.1) and on Windows 2008 R2.

It fails trying to connect to it from both Mac and Linux clients.

**Comment by fjaenal** [comment]
I am having a similar problem using the jcraft.jsch java library. In my case the sshd (On a windows 2008 r2) shows the following error:
7124 09:28:39 672 Connection from 10.73.24.24 port 63331 on 10.73.28.31 port 22200
7124 09:28:39 672 debug1: Client protocol version 2.0; client software version JSCH-0.1.53
7124 09:28:39 672 debug1: no match: JSCH-0.1.53
7124 09:28:39 672 debug1: Enabling compatibility mode for protocol 2.0
7124 09:28:39 672 debug1: Local version string SSH-2.0-OpenSSH_7.1p1 Microsoft_Win32_port_with_VS
7124 09:28:39 672 debug1: list_hostkey_types: ssh-rsa,ecdsa-sha2-nistp256
7124 09:28:39 672 debug1: SSH2_MSG_KEXINIT sent
7124 09:28:39 726 debug1: SSH2_MSG_KEXINIT received
7124 09:28:39 726 debug1: kex: algorithm: ecdh-sha2-nistp256
7124 09:28:39 726 debug1: kex: host key algorithm: ssh-rsa
7124 09:28:39 726 debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1 compression: none
7124 09:28:39 727 debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1 compression: none
7124 09:28:39 727 debug1: expecting SSH2_MSG_KEX_ECDH_INIT
7124 09:28:39 746 fatal: ssh_dispatch_run_fatal: Connection to 10.73.24.24: invalid argument
7124 09:28:39 746 debug1: do_cleanup

The java code it just do (com.jcraft.jsch.Session):
`           Hashtable<String, String> config = new Hashtable<String, String>();
            config.put("StrictHostKeyChecking", "no");
            config.put("cipher.s2c", UnixRemoteExecutionManager.sshCiphers);
            config.put("cipher.c2s", UnixRemoteExecutionManager.sshCiphers);

```
        session = jsch.getSession(user, getHost(), getPort());
        session.setPassword(password);
        session.setConfig(config);
        session.setTimeout(remoteXManager.getConnectionProperties().connectionTimeoutSecs*1000); // SESSION_TIMEOUT
        session.setUserInfo(new PasswordKeyboardInteractive(getHost(),
                password));
```

session.connect();`

The UnixRemoteExecutionManager.sshCiphers list are:
"_aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc,blowfish-cbc,aes128-ctr,aes192-ctr,aes256-ctr,3des-ctr,arcfour,arcfour128,arcfour256_"

I have been trying to check how the connection is build but no luck yet. Also the connection works perfectly from a windows cmd.

**Environment**:
- Server side: Windows 2008 r2
- Client side: Windows 7 64 bits
- Powershell Windows SSH version: 4/5/2016

**Comment by manojampalam** [comment]
Can you try the latest release and reopen if needed?

**Comment by dmitrybezer** [comment]
I'm using the 5_15_2016 release and the problem is still here. I'm unable to connect from a mac. And the key exchange algorithm doesn't seem to be the issue here because even if I force ssh clients on mac and windows to use the same algorithm  (using this option -oKexAlgorithms=diffie-hellman-group-exchange-sha256) connection from windows works fine while mac client fails with exactly the same message log as @paulewog  provided.

**Comment by paulewog** [comment]
@manojampalam - sorry for the delay in response.  Unfortunately, I'm no longer at the job where I was using this... :/
