### ISSUE TITLE
Only allowing Domain Auth Users to login if part of the local admins group

### ISSUE THREAD

**Issue by steskalja** [PowerShell/Win32-OpenSSH#1730]
Attached are the sshd_config and the sshd log

**"OpenSSH for Windows" version**
8.1.0.0
 
**Server OperatingSystem**
Windows Server 2016 Datacenter

**Client OperatingSystem**
Windows 10 Enterprise
[sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/5875920/sshd.log)

[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/5875923/sshd_config.txt)
[sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/5875924/sshd.log)

**What is failing**
Cannot login domain user if they are not a part of the local admin group on the server

Client debug output:
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug3: Failed to open file:C:/Users/212670239/.ssh/config error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolve_canonicalize: hostname 10.121.22.20 is address
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 10.121.22.20 [10.121.22.20] port 22.
debug3: finish_connect - ERROR: async io completed with error: 10061, io:0000020528D4E0E0
debug1: connect to address 10.121.22.20 port 22: Connection refused
ssh: connect to host 10.121.22.20 port 22: Connection refused
PS C:\Users\212670239> ssh -vvv logon\de670239hp@10.121.22.20
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug3: Failed to open file:C:/Users/212670239/.ssh/config error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolve_canonicalize: hostname 10.121.22.20 is address
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 10.121.22.20 [10.121.22.20] port 22.
debug1: Connection established.
debug3: Failed to open file:C:/Users/212670239/.ssh/id_rsa error:2
debug3: Failed to open file:C:/Users/212670239/.ssh/id_rsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\212670239/.ssh/id_rsa type -1
debug3: Failed to open file:C:/Users/212670239/.ssh/id_rsa-cert error:2
debug3: Failed to open file:C:/Users/212670239/.ssh/id_rsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\212670239/.ssh/id_rsa-cert type -1
debug3: Failed to open file:C:/Users/212670239/.ssh/id_dsa error:2
debug3: Failed to open file:C:/Users/212670239/.ssh/id_dsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\212670239/.ssh/id_dsa type -1
debug3: Failed to open file:C:/Users/212670239/.ssh/id_dsa-cert error:2
debug3: Failed to open file:C:/Users/212670239/.ssh/id_dsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\212670239/.ssh/id_dsa-cert type -1
debug3: Failed to open file:C:/Users/212670239/.ssh/id_ecdsa error:2
debug3: Failed to open file:C:/Users/212670239/.ssh/id_ecdsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\212670239/.ssh/id_ecdsa type -1
debug3: Failed to open file:C:/Users/212670239/.ssh/id_ecdsa-cert error:2
debug3: Failed to open file:C:/Users/212670239/.ssh/id_ecdsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\212670239/.ssh/id_ecdsa-cert type -1
debug3: Failed to open file:C:/Users/212670239/.ssh/id_ed25519 error:2
debug3: Failed to open file:C:/Users/212670239/.ssh/id_ed25519.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\212670239/.ssh/id_ed25519 type -1
debug3: Failed to open file:C:/Users/212670239/.ssh/id_ed25519-cert error:2
debug3: Failed to open file:C:/Users/212670239/.ssh/id_ed25519-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\212670239/.ssh/id_ed25519-cert type -1
debug3: Failed to open file:C:/Users/212670239/.ssh/id_xmss error:2
debug3: Failed to open file:C:/Users/212670239/.ssh/id_xmss.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\212670239/.ssh/id_xmss type -1
debug3: Failed to open file:C:/Users/212670239/.ssh/id_xmss-cert error:2
debug3: Failed to open file:C:/Users/212670239/.ssh/id_xmss-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\212670239/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_8.1
debug1: match: OpenSSH_for_Windows_8.1 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 10.121.22.20:22 as 'logon\\de670239hp'
debug3: hostkeys_foreach: reading file "C:\\Users\\212670239/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file C:\\Users\\212670239/.ssh/known_hosts:2
debug3: load_hostkeys: loaded 1 keys from 10.121.22.20
debug3: Failed to open file:C:/Users/212670239/.ssh/known_hosts2 error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:P5HWvxWjNxgC1xe9WSBCqxaiWEczjY1m4uscbCGk0Sw
debug3: hostkeys_foreach: reading file "C:\\Users\\212670239/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file C:\\Users\\212670239/.ssh/known_hosts:2
debug3: load_hostkeys: loaded 1 keys from 10.121.22.20
debug3: Failed to open file:C:/Users/212670239/.ssh/known_hosts2 error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug1: Host '10.121.22.20' is known and matches the ECDSA host key.
debug1: Found key in C:\\Users\\212670239/.ssh/known_hosts:2
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug3: unable to connect to pipe \\\\.\\pipe\\openssh-ssh-agent, error: 2
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug2: key: C:\\Users\\212670239/.ssh/id_rsa (0000000000000000)
debug2: key: C:\\Users\\212670239/.ssh/id_dsa (0000000000000000)
debug2: key: C:\\Users\\212670239/.ssh/id_ecdsa (0000000000000000)
debug2: key: C:\\Users\\212670239/.ssh/id_ed25519 (0000000000000000)
debug2: key: C:\\Users\\212670239/.ssh/id_xmss (0000000000000000)
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: recv - from CB ERROR:10054, io:000002D3132200E0
Connection reset by 10.121.22.20 port 22

**Comment by bagajjal** [comment]
This is specific to your environment. Please debug yourself.

Looking at the sshd.log, error 0xc000015b (STATUS_LOGON_TYPE_NOT_GRANTED) - A user has requested a type of logon (e.g., interactive or network) that has not been granted. An administrator has control over who may logon interactively and through the network.

4768 2021-01-26 20:24:15.203 debug3: lookup_principal_name: Successfully discovered explicit principal name: 'logon\\de670239hp'=>'de670239hp@logon.ds.ge.com'
4768 2021-01-26 20:24:15.311 debug1: generate_s4u_user_token: LsaLogonUser() failed. User 'logon\\de670239hp' Status: 0xC000015B SubStatus 0.
4768 2021-01-26 20:24:15.311 debug3: get_user_token - unable to generate token for user logon\\de670239hp

**Comment by steskalja** [comment]
Doh! I missed that policy. If you want any groups or users outside of admins to access the box through ssh you need to add them to Access this computer from the network under user rights assignments. Thank you for pointing out my error!
