### ISSUE TITLE
Server refused to start a shell/command - shell request failed on channel 0

### ISSUE THREAD

**Issue by Rittmeister39** [PowerShell/Win32-OpenSSH#1733]
**"OpenSSH for Windows" version**
v8.1.0.0p1-Beta
**Server OperatingSystem**
Win10 2004 AME (ameliorated)
**Client OperatingSystem**
Win10 Pro 2004
**What is failing**
ssh connection does not get a shell
**Expected output**
receiving a shell and successful login
**Actual output**
no shell, disconnected

I installed OpenSSH on a freshly installed Win10 2004 ISO (Ameliorated Edition).
Connecting with sftp works, including file transfers.
Connecting with either putty 0.74 or from a Win10 commandline (ssh -l user 192.168.0.101) fails with this error:
Putty: Server refused to start a shell/command
cmd: shell request failed on channel 0
---
How I installed it:
DL and put all the files into c:\ProgramFile\OpenSSH
elevated Powershell:
C:\> New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
C:\> powershell.exe -ExecutionPolicy Bypass -File install-sshd.ps1
C:\> net start sshd
C:\> Set-Service sshd - StartupType Automatic

The only thing I changed in the default sshd_config is SyslogFacility LOCAL0 and LogLevel DEBUG3.
That was all, connecting failed with this installation already, so I tried this additional step to make sure the System knows which shell I want.

New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force
 New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShellCommandOption -Value "/c" -PropertyType String -Force

Unfortunately, this didn't fix the issue.

Here is the log (I set it to LOCAL0 and DEBUG3)

6344 2021-01-30 20:28:56.428 debug2: fd 3 setting O_NONBLOCK
6344 2021-01-30 20:28:56.428 debug3: sock_set_v6only: set socket 3 IPV6_V6ONLY
6344 2021-01-30 20:28:56.428 debug1: Bind to port 22 on ::.
6344 2021-01-30 20:28:56.428 Server listening on :: port 22.
6344 2021-01-30 20:28:56.428 debug2: fd 4 setting O_NONBLOCK
6344 2021-01-30 20:28:56.428 debug1: Bind to port 22 on 0.0.0.0.
6344 2021-01-30 20:28:56.428 Server listening on 0.0.0.0 port 22.
6344 2021-01-30 20:29:54.163 debug3: fd 5 is not O_NONBLOCK
6344 2021-01-30 20:29:54.163 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" -R
6344 2021-01-30 20:29:54.163 debug3: send_rexec_state: entering fd = 8 config len 311
6344 2021-01-30 20:29:54.163 debug3: ssh_msg_send: type 0
6344 2021-01-30 20:29:54.163 debug3: send_rexec_state: done
6624 2021-01-30 20:29:54.195 debug1: inetd sockets after dupping: 4, 4
6624 2021-01-30 20:29:54.195 Connection from ::1 port 49779 on ::1 port 22
6624 2021-01-30 20:29:54.195 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
6624 2021-01-30 20:29:54.195 debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_7.7
6624 2021-01-30 20:29:54.195 debug1: match: OpenSSH_for_Windows_7.7 pat OpenSSH* compat 0x04000000
6624 2021-01-30 20:29:54.195 debug2: fd 4 setting O_NONBLOCK
6624 2021-01-30 20:29:54.210 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" -y
6624 2021-01-30 20:29:54.210 debug2: Network child is on pid 6644
6624 2021-01-30 20:29:54.210 debug3: send_rexec_state: entering fd = 6 config len 311
6624 2021-01-30 20:29:54.210 debug3: ssh_msg_send: type 0
6624 2021-01-30 20:29:54.210 debug3: send_rexec_state: done
6624 2021-01-30 20:29:54.210 debug3: ssh_msg_send: type 0
6624 2021-01-30 20:29:54.210 debug3: ssh_msg_send: type 0
6624 2021-01-30 20:29:54.210 debug3: preauth child monitor started
6624 2021-01-30 20:29:54.226 debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
6624 2021-01-30 20:29:54.226 debug3: send packet: type 20 [preauth]
6624 2021-01-30 20:29:54.226 debug1: SSH2_MSG_KEXINIT sent [preauth]
6624 2021-01-30 20:29:54.226 debug3: receive packet: type 20 [preauth]
6624 2021-01-30 20:29:54.226 debug1: SSH2_MSG_KEXINIT received [preauth]
6624 2021-01-30 20:29:54.226 debug2: local server KEXINIT proposal [preauth]
6624 2021-01-30 20:29:54.226 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1 [preauth]
6624 2021-01-30 20:29:54.226 debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
6624 2021-01-30 20:29:54.226 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
6624 2021-01-30 20:29:54.226 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
6624 2021-01-30 20:29:54.226 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
6624 2021-01-30 20:29:54.226 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
6624 2021-01-30 20:29:54.226 debug2: compression ctos: none,zlib@openssh.com [preauth]
6624 2021-01-30 20:29:54.226 debug2: compression stoc: none,zlib@openssh.com [preauth]
6624 2021-01-30 20:29:54.226 debug2: languages ctos:  [preauth]
6624 2021-01-30 20:29:54.226 debug2: languages stoc:  [preauth]
6624 2021-01-30 20:29:54.226 debug2: first_kex_follows 0  [preauth]
6624 2021-01-30 20:29:54.226 debug2: reserved 0  [preauth]
6624 2021-01-30 20:29:54.226 debug2: peer client KEXINIT proposal [preauth]
6624 2021-01-30 20:29:54.226 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c [preauth]
6624 2021-01-30 20:29:54.226 debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa [preauth]
6624 2021-01-30 20:29:54.226 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
6624 2021-01-30 20:29:54.226 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
6624 2021-01-30 20:29:54.226 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
6624 2021-01-30 20:29:54.226 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
6624 2021-01-30 20:29:54.226 debug2: compression ctos: none [preauth]
6624 2021-01-30 20:29:54.226 debug2: compression stoc: none [preauth]
6624 2021-01-30 20:29:54.226 debug2: languages ctos:  [preauth]
6624 2021-01-30 20:29:54.226 debug2: languages stoc:  [preauth]
6624 2021-01-30 20:29:54.226 debug2: first_kex_follows 0  [preauth]
6624 2021-01-30 20:29:54.226 debug2: reserved 0  [preauth]
6624 2021-01-30 20:29:54.226 debug1: kex: algorithm: curve25519-sha256 [preauth]
6624 2021-01-30 20:29:54.226 debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
6624 2021-01-30 20:29:54.226 debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
6624 2021-01-30 20:29:54.226 debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
6624 2021-01-30 20:29:54.226 debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
6624 2021-01-30 20:29:54.226 debug3: receive packet: type 30 [preauth]
6624 2021-01-30 20:29:54.241 debug3: mm_sshkey_sign entering [preauth]
6624 2021-01-30 20:29:54.241 debug3: mm_request_send entering: type 6 [preauth]
6624 2021-01-30 20:29:54.241 debug3: mm_sshkey_sign: waiting for MONITOR_ANS_SIGN [preauth]
6624 2021-01-30 20:29:54.241 debug3: mm_request_receive_expect entering: type 7 [preauth]
6624 2021-01-30 20:29:54.241 debug3: mm_request_receive entering [preauth]
6624 2021-01-30 20:29:54.241 debug3: mm_request_receive entering
6624 2021-01-30 20:29:54.241 debug3: monitor_read: checking request 6
6624 2021-01-30 20:29:54.241 debug3: mm_answer_sign
6624 2021-01-30 20:29:54.241 debug3: mm_answer_sign: KEX signature 031D92E0(101)
6624 2021-01-30 20:29:54.241 debug3: mm_request_send entering: type 7
6624 2021-01-30 20:29:54.241 debug2: monitor_read: 6 used once, disabling now
6624 2021-01-30 20:29:54.241 debug3: send packet: type 31 [preauth]
6624 2021-01-30 20:29:54.241 debug3: send packet: type 21 [preauth]
6624 2021-01-30 20:29:54.241 debug2: set_newkeys: mode 1 [preauth]
6624 2021-01-30 20:29:54.241 debug1: rekey out after 134217728 blocks [preauth]
6624 2021-01-30 20:29:54.241 debug1: SSH2_MSG_NEWKEYS sent [preauth]
6624 2021-01-30 20:29:54.241 debug1: Sending SSH2_MSG_EXT_INFO [preauth]
6624 2021-01-30 20:29:54.241 debug3: send packet: type 7 [preauth]
6624 2021-01-30 20:29:54.241 debug1: expecting SSH2_MSG_NEWKEYS [preauth]
6624 2021-01-30 20:29:54.257 debug3: receive packet: type 21 [preauth]
6624 2021-01-30 20:29:54.257 debug1: SSH2_MSG_NEWKEYS received [preauth]
6624 2021-01-30 20:29:54.257 debug2: set_newkeys: mode 0 [preauth]
6624 2021-01-30 20:29:54.257 debug1: rekey in after 134217728 blocks [preauth]
6624 2021-01-30 20:29:54.257 debug1: KEX done [preauth]
6624 2021-01-30 20:29:54.257 debug3: receive packet: type 5 [preauth]
6624 2021-01-30 20:29:54.257 debug3: send packet: type 6 [preauth]
6624 2021-01-30 20:29:54.257 debug3: receive packet: type 50 [preauth]
6624 2021-01-30 20:29:54.257 debug1: userauth-request for user user service ssh-connection method none [preauth]
6624 2021-01-30 20:29:54.257 debug1: attempt 0 failures 0 [preauth]
6624 2021-01-30 20:29:54.257 debug3: mm_getpwnamallow entering [preauth]
6624 2021-01-30 20:29:54.257 debug3: mm_request_send entering: type 8 [preauth]
6624 2021-01-30 20:29:54.257 debug3: mm_getpwnamallow: waiting for MONITOR_ANS_PWNAM [preauth]
6624 2021-01-30 20:29:54.257 debug3: mm_request_receive_expect entering: type 9 [preauth]
6624 2021-01-30 20:29:54.257 debug3: mm_request_receive entering [preauth]
6624 2021-01-30 20:29:54.257 debug3: mm_request_receive entering
6624 2021-01-30 20:29:54.257 debug3: monitor_read: checking request 8
6624 2021-01-30 20:29:54.257 debug3: mm_answer_pwnamallow
6624 2021-01-30 20:29:54.257 debug2: parse_server_config: config reprocess config len 311
6624 2021-01-30 20:29:54.257 debug3: checking match for 'Group administrators' user user host ::1 addr ::1 laddr ::1 lport 22
6624 2021-01-30 20:29:54.257 debug3: LsaLogonUser Succeeded (Impersonation: 0)
6624 2021-01-30 20:29:54.257 debug1: user user matched group list administrators at line 90
6624 2021-01-30 20:29:54.257 debug3: match found
6624 2021-01-30 20:29:54.257 debug3: reprocess config:91 setting AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
6624 2021-01-30 20:29:54.257 debug3: mm_answer_pwnamallow: sending MONITOR_ANS_PWNAM: 1
6624 2021-01-30 20:29:54.257 debug3: mm_request_send entering: type 9
6624 2021-01-30 20:29:54.257 debug2: monitor_read: 8 used once, disabling now
6624 2021-01-30 20:29:54.257 debug2: input_userauth_request: setting up authctxt for user [preauth]
6624 2021-01-30 20:29:54.257 debug3: mm_inform_authserv entering [preauth]
6624 2021-01-30 20:29:54.257 debug3: mm_request_send entering: type 4 [preauth]
6624 2021-01-30 20:29:54.257 debug2: input_userauth_request: try method none [preauth]
6624 2021-01-30 20:29:54.257 debug3: mm_request_receive entering
6624 2021-01-30 20:29:54.257 debug3: monitor_read: checking request 4
6624 2021-01-30 20:29:54.257 debug3: mm_answer_authserv: service=ssh-connection, style=
6624 2021-01-30 20:29:54.257 debug2: monitor_read: 4 used once, disabling now
6624 2021-01-30 20:29:54.257 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
6624 2021-01-30 20:29:54.257 debug3: ensure_minimum_time_since: elapsed 0.000ms, delaying 7.194ms (requested 7.194ms) [preauth]
6624 2021-01-30 20:29:54.279 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
6624 2021-01-30 20:29:54.279 debug3: send packet: type 51 [preauth]
6624 2021-01-30 20:29:54.279 debug3: receive packet: type 50 [preauth]
6624 2021-01-30 20:29:54.279 debug1: userauth-request for user user service ssh-connection method keyboard-interactive [preauth]
6624 2021-01-30 20:29:54.279 debug1: attempt 1 failures 0 [preauth]
6624 2021-01-30 20:29:54.279 debug2: input_userauth_request: try method keyboard-interactive [preauth]
6624 2021-01-30 20:29:54.279 debug1: keyboard-interactive devs  [preauth]
6624 2021-01-30 20:29:54.279 debug1: auth2_challenge: user=user devs= [preauth]
6624 2021-01-30 20:29:54.279 debug1: kbdint_alloc: devices '' [preauth]
6624 2021-01-30 20:29:54.279 debug2: auth2_challenge_start: devices  [preauth]
6624 2021-01-30 20:29:54.279 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
6624 2021-01-30 20:29:54.279 debug3: ensure_minimum_time_since: elapsed 0.000ms, delaying 7.194ms (requested 7.194ms) [preauth]
6624 2021-01-30 20:29:54.295 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
6624 2021-01-30 20:29:54.295 debug3: send packet: type 51 [preauth]
6624 2021-01-30 20:29:59.135 debug3: receive packet: type 50 [preauth]
6624 2021-01-30 20:29:59.135 debug1: userauth-request for user user service ssh-connection method password [preauth]
6624 2021-01-30 20:29:59.135 debug1: attempt 2 failures 1 [preauth]
6624 2021-01-30 20:29:59.135 debug2: input_userauth_request: try method password [preauth]
6624 2021-01-30 20:29:59.135 debug3: mm_auth_password entering [preauth]
6624 2021-01-30 20:29:59.135 debug3: mm_request_send entering: type 12 [preauth]
6624 2021-01-30 20:29:59.135 debug3: mm_auth_password: waiting for MONITOR_ANS_AUTHPASSWORD [preauth]
6624 2021-01-30 20:29:59.135 debug3: mm_request_receive_expect entering: type 13 [preauth]
6624 2021-01-30 20:29:59.135 debug3: mm_request_receive entering [preauth]
6624 2021-01-30 20:29:59.135 debug3: mm_request_receive entering
6624 2021-01-30 20:29:59.135 debug3: monitor_read: checking request 12
6624 2021-01-30 20:29:59.141 debug3: mm_answer_authpassword: sending result 1
6624 2021-01-30 20:29:59.141 debug3: mm_request_send entering: type 13
6624 2021-01-30 20:29:59.141 Accepted password for user from ::1 port 49779 ssh2
6624 2021-01-30 20:29:59.141 debug1: monitor_child_preauth: user has been authenticated by privileged process
6624 2021-01-30 20:29:59.141 debug3: mm_get_keystate: Waiting for new keys
6624 2021-01-30 20:29:59.141 debug3: mm_request_receive_expect entering: type 26
6624 2021-01-30 20:29:59.141 debug3: mm_request_receive entering
6624 2021-01-30 20:29:59.157 debug3: mm_get_keystate: GOT new keys
6624 2021-01-30 20:29:59.157 debug3: mm_auth_password: user authenticated [preauth]
6624 2021-01-30 20:29:59.157 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
6624 2021-01-30 20:29:59.157 debug3: ensure_minimum_time_since: elapsed 6.558ms, delaying 0.636ms (requested 7.194ms) [preauth]
6624 2021-01-30 20:29:59.157 debug3: send packet: type 52 [preauth]
6624 2021-01-30 20:29:59.157 debug3: mm_request_send entering: type 26 [preauth]
6624 2021-01-30 20:29:59.157 debug3: mm_send_keystate: Finished sending state [preauth]
6624 2021-01-30 20:29:59.157 debug1: monitor_read_log: child log fd closed
6624 2021-01-30 20:29:59.157 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" -z
6624 2021-01-30 20:29:59.157 User child is on pid 6696
6624 2021-01-30 20:29:59.157 debug3: send_rexec_state: entering fd = 5 config len 311
6624 2021-01-30 20:29:59.157 debug3: ssh_msg_send: type 0
6624 2021-01-30 20:29:59.157 debug3: send_rexec_state: done
6624 2021-01-30 20:29:59.157 debug3: ssh_msg_send: type 0
6624 2021-01-30 20:29:59.157 debug3: ssh_msg_send: type 0
6624 2021-01-30 20:29:59.157 debug3: ssh_msg_send: type 0
6624 2021-01-30 20:29:59.157 debug3: ssh_msg_send: type 0
6624 2021-01-30 20:29:59.157 debug3: ssh_msg_send: type 0
6696 2021-01-30 20:29:59.173 debug3: recv_idexch_state: entering fd = 3
6696 2021-01-30 20:29:59.173 debug3: ssh_msg_recv entering
6696 2021-01-30 20:29:59.173 debug3: recv_idexch_state: done
6696 2021-01-30 20:29:59.173 debug2: fd 4 setting O_NONBLOCK
6696 2021-01-30 20:29:59.173 debug3: recv_autxctx_state: entering fd = 3
6696 2021-01-30 20:29:59.173 debug3: ssh_msg_recv entering
6696 2021-01-30 20:29:59.173 debug3: recv_autxctx_state: done
6696 2021-01-30 20:29:59.173 debug2: parse_server_config: config reprocess config len 311
6696 2021-01-30 20:29:59.173 debug3: checking match for 'Group administrators' user user host ::1 addr ::1 laddr ::1 lport 22
6696 2021-01-30 20:29:59.173 debug3: get_user_token - i am running as user, returning process token
6696 2021-01-30 20:29:59.173 debug1: user user matched group list administrators at line 90
6696 2021-01-30 20:29:59.173 debug3: match found
6696 2021-01-30 20:29:59.173 debug3: reprocess config:91 setting AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
6696 2021-01-30 20:29:59.173 debug3: monitor_recv_keystate: entering 
6696 2021-01-30 20:29:59.173 debug3: ssh_msg_recv entering
6696 2021-01-30 20:29:59.173 debug3: monitor_recv_keystate: done
6696 2021-01-30 20:29:59.173 debug3: monitor_apply_keystate: packet_set_state
6696 2021-01-30 20:29:59.173 debug2: set_newkeys: mode 0
6696 2021-01-30 20:29:59.173 debug1: rekey in after 134217728 blocks
6696 2021-01-30 20:29:59.173 debug2: set_newkeys: mode 1
6696 2021-01-30 20:29:59.173 debug1: rekey out after 134217728 blocks
6696 2021-01-30 20:29:59.173 debug1: ssh_packet_set_postauth: called
6696 2021-01-30 20:29:59.173 debug3: ssh_packet_set_state: done
6696 2021-01-30 20:29:59.173 debug3: monitor_recv_authopt: entering 
6696 2021-01-30 20:29:59.173 debug3: ssh_msg_recv entering
6696 2021-01-30 20:29:59.173 debug3: monitor_recv_authopt: done
6696 2021-01-30 20:29:59.173 debug3: notify_hostkeys: key 0: ssh-rsa SHA256:pG67ED+8LVxt2BxfStcA03ytOq+OaBAmteahzssLhpg
6696 2021-01-30 20:29:59.173 debug3: notify_hostkeys: key 1: ecdsa-sha2-nistp256 SHA256:mSpAApCHag06839Mejm/1KmF39sjTUTUAFWzs8RKFcM
6696 2021-01-30 20:29:59.173 debug3: notify_hostkeys: key 2: ssh-ed25519 SHA256:mbf/87eDJnhwpbBWmLYm7f+WwAZAP/qeI0PavBzAlI8
6696 2021-01-30 20:29:59.173 debug3: notify_hostkeys: sent 3 hostkeys
6696 2021-01-30 20:29:59.173 debug3: send packet: type 80
6696 2021-01-30 20:29:59.173 debug1: active: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
6696 2021-01-30 20:29:59.173 debug1: Entering interactive session for SSH2.
6696 2021-01-30 20:29:59.173 debug2: fd 7 setting O_NONBLOCK
6696 2021-01-30 20:29:59.173 debug2: fd 8 setting O_NONBLOCK
6696 2021-01-30 20:29:59.173 debug1: server_init_dispatch
6696 2021-01-30 20:29:59.173 debug3: receive packet: type 90
6696 2021-01-30 20:29:59.173 debug1: server_input_channel_open: ctype session rchan 0 win 1048576 max 16384
6696 2021-01-30 20:29:59.173 debug1: input_session_request
6696 2021-01-30 20:29:59.173 debug1: channel 0: new [server-session]
6696 2021-01-30 20:29:59.173 debug2: session_new: allocate (allocated 0 max 10)
6696 2021-01-30 20:29:59.173 debug3: session_unused: session id 0 unused
6696 2021-01-30 20:29:59.173 debug1: session_new: session 0
6696 2021-01-30 20:29:59.173 debug1: session_open: channel 0
6696 2021-01-30 20:29:59.173 debug1: session_open: session 0: link with channel 0
6696 2021-01-30 20:29:59.173 debug1: server_input_channel_open: confirm session
6696 2021-01-30 20:29:59.173 debug3: send packet: type 91
6696 2021-01-30 20:29:59.173 debug3: receive packet: type 80
6696 2021-01-30 20:29:59.173 debug1: server_input_global_request: rtype no-more-sessions@openssh.com want_reply 0
6696 2021-01-30 20:29:59.188 debug3: receive packet: type 98
6696 2021-01-30 20:29:59.188 debug1: server_input_channel_req: channel 0 request pty-req reply 1
6696 2021-01-30 20:29:59.188 debug1: session_by_channel: session 0 channel 0
6696 2021-01-30 20:29:59.188 debug1: session_input_channel_req: session 0 req pty-req
6696 2021-01-30 20:29:59.188 debug1: Allocating pty.
6696 2021-01-30 20:29:59.188 debug3: fd 9 is not O_NONBLOCK
6696 2021-01-30 20:29:59.188 debug3: fd 10 is not O_NONBLOCK
6696 2021-01-30 20:29:59.188 debug1: session_pty_req: session 0 alloc windows-pty
6696 2021-01-30 20:29:59.188 debug3: send packet: type 99
6696 2021-01-30 20:29:59.188 debug3: receive packet: type 98
6696 2021-01-30 20:29:59.188 debug1: server_input_channel_req: channel 0 request shell reply 1
6696 2021-01-30 20:29:59.188 debug1: session_by_channel: session 0 channel 0
6696 2021-01-30 20:29:59.188 debug1: session_input_channel_req: session 0 req shell
6696 2021-01-30 20:29:59.188 Starting session: shell on windows-pty for user from ::1 port 49779 id 0
6696 2021-01-30 20:29:59.188 debug2: fd 11 setting O_NONBLOCK
6696 2021-01-30 20:29:59.188 debug2: fd 12 setting O_NONBLOCK
6696 2021-01-30 20:29:59.188 debug2: fd 13 setting O_NONBLOCK
6696 2021-01-30 20:29:59.188 debug2: fd 14 setting O_NONBLOCK
6696 2021-01-30 20:29:59.188 debug2: fd 15 setting O_NONBLOCK
6696 2021-01-30 20:29:59.188 debug2: fd 16 setting O_NONBLOCK
6696 2021-01-30 20:29:59.188 debug3: shell: "c:\\windows\\system32\\windowspowershell\\v1.0\\powershell.exe"
6696 2021-01-30 20:29:59.188 debug3: shell_option: /c
6696 2021-01-30 20:29:59.188 debug3: This windows OS supports conpty
6696 2021-01-30 20:29:59.188 debug3: pty commandline: C:\\Windows\\system32\\conhost.exe --headless --width 120 --height 50 --signal 0x218 -- "c:\\windows\\system32\\windowspowershell\\v1.0\\powershell.exe"
6696 2021-01-30 20:29:59.188 debug1: exec_command_with_pty - failed to execute C:\\Windows\\system32\\conhost.exe --headless --width 120 --height 50 --signal 0x218 -- "c:\\windows\\system32\\windowspowershell\\v1.0\\powershell.exe", error:2
6696 2021-01-30 20:29:59.188 debug3: send packet: type 100
6696 2021-01-30 20:29:59.188 debug3: recv - from CB ERROR:10054, io:030F1E40
6696 2021-01-30 20:29:59.188 Read error from remote host ::1 port 49779: Connection reset
6696 2021-01-30 20:29:59.188 debug1: do_cleanup
6624 2021-01-30 20:29:59.188 debug3: mm_request_receive entering
6624 2021-01-30 20:29:59.188 debug1: do_cleanup

Can somebody please tell me what is wrong? :)

**Comment by SamB** [comment]
@Rittmeister39 Well, it looks awfully similar to #1339; the workaround there was to use the 64-bit version of the server.

**Comment by Rittmeister39** [comment]
> 
> 
> @Rittmeister39 Well, it looks awfully similar to #1339; the workaround there was to use the 64-bit version of the server.

oh! that is embarassing. I downloaded the 32 bit version and thought there's no other. Thank you very much, I will try to uninstall 32bit and test 64, and report back if that solved it.

**Comment by Rittmeister39** [comment]
Thank you very much again!
I stopped the service, uninstalled it with the script, removed the 32-bit version, put the 64-bit version there, installed it, and now SSH gets a shell and works.
epic! ps. sorry for my newb mistake. I didn't look good enough to see the 64bit version download.

**Comment by bagajjal** [comment]
Duplicate https://github.com/PowerShell/Win32-OpenSSH/issues/1339
