### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#1736]
deleted

**Comment by bagajjal** [comment]
@uservictor - This is a rare scenario. The fix will be part of next OpenSSH release (v8.5) planned for this month.
Please validate if the attached private ssh.exe binary solves your problem.

[ssh-prevent-duplicate-msg.zip](https://github.com/PowerShell/Win32-OpenSSH/files/6080551/ssh-prevent-duplicate-msg.zip)

**Comment by bagajjal** [comment]
Here is the PR.
https://github.com/PowerShell/openssh-portable/pull/426

**Comment by uservictor** [comment]
Thank you, i will try and report.

**Comment by uservictor** [comment]
@bagajjal Today I run the new version that you providet me, the double "motd" posting is fixed (run ssh.exe 12 times) thank you for that.
But the second problem is still there _"While exit text editor nano (for example, in other cases it happens too) i got double post of connected hostname"_ always as I exit "nano" page with Ctrl +X iI get double post of hostname.

![Screenshot (2)](https://user-images.githubusercontent.com/56163305/110017734-d45c9a80-7d26-11eb-9645-36c7bc45a1c5.png)

Have a nice day

**Comment by bagajjal** [comment]
@uservictor - I don't see the "double hostname" after exiting nano. My winver version is "[Version 10.0.19042.985]".
