### ISSUE TITLE
What dependencies are needed to build openssh on Windows?

### ISSUE THREAD

**Issue by chardch** [PowerShell/Win32-OpenSSH#1739]
What are all the dependencies we need to install in order to build this on Windows?

**Comment by bagajjal** [comment]
If you are using visual studio then it automatically gets all the dependencies (Libressl, ZLIB). Open Win32-OpenSSH.sln(https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/openssh/Win32-OpenSSH.sln) in Visual studio and build.
