### ISSUE TITLE
Ubuntu on Windows

### ISSUE THREAD

**Issue by sonnyp** [PowerShell/Win32-OpenSSH#174]
Does the Ubuntu user space on Windows announcement https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/ means the end of Win32-OpenSSH in favor of using Ubuntu's openssh binary?

Probbly not as it won't bring OpenSSH + PowerShell but just to make sure

**Comment by manojampalam** [comment]
Not really. Ubuntu runs in an isolated sub system and cannot be used to manage its host Windows OS. As I see, ssh in Ubuntu user space complements Win32-OpenSSH as it provides a window (ssh client on Ubuntu connected to sshd on Windows) to interact with host OS.
