### ISSUE TITLE
Runas does not work as expected under SSH

### ISSUE THREAD

**Issue by matsmcp** [PowerShell/Win32-OpenSSH#1740]
**"OpenSSH for Windows" version**
8.1
 
**Server OperatingSystem**
 Server 2019

**Client OperatingSystem**
Server 2019

**What is failing**
1. log on to a system as a user over SSH (cmd as shell)
2. atempt to start a cmd as administratior with runas /user:administrator CMD

**Expected output**
A cmd shell running as administrator

**Actual output**
The shell doesn't start or starts and dies directly. 

For us this is a security issue since using SSH as a member of administrators is a bad practice. However, since we can't elevate locally (since runas doesn't work) our users has to have admin rights on their SSH accounts.

It would be a lot better to do SSH as user and then elevate to an account with higher rights or even the administrator account since it's password can be handled through laps so it would be fairly strong and gets changed by laps.

**Comment by bagajjal** [comment]
You can do nested ssh connections.
The first ssh connection with non-admin user. When you want administrator permissions then ssh with administrator user inside the existing ssh connection.

`runas /user` relies on the shell (meaning Windows Explorer, not console) to elevate which requires a winstation.  As a remote user, this won’t be possible until Windows supports real `sudo`.

**Comment by matsmcp** [comment]
That is an interesting workaround and it seems rather easy to - thank you. 

I did try with a Match user Administrator Address 127.0.0.1 and that seems to solve the issue until a real sudo will be available

Edit: Match Group Administrators Address 127.0.0.1 is a better way of doing it allow for other admin accounts as well
