### ISSUE TITLE
KEX Exchange

### ISSUE THREAD

**Issue by stborisov** [PowerShell/Win32-OpenSSH#1744]
Hello,  i have open ssh server running on win2012r2.
Version of sshd 8.1.0.0
Can I Enable diffie-hellman-group1-sha1[preauth] ?
Error:
sshd: Unable to negotiate with "client ip" port 46552: no matching key exchange method found. Their offer: diffie-hellman-group1-sha1 [preauth]

**Comment by bagajjal** [comment]
"diffie-hellman-group1-sha1" is not  a default supported Kex algorithm.

However, you can achieve this by following these steps,
1) Add the below config to $env:Programdata\ssh\sshd_config file

KexAlgorithms +diffie-hellman-group1-sha1

2) restart sshd server
net stop sshd
net start sshd

3) ssh connection.
ssh -vvv user@ip

**Comment by stborisov** [comment]
Thank you!
