### ISSUE TITLE
No permission to run icacls.exe through ssh, using powershell

### ISSUE THREAD

**Issue by roblourens** [PowerShell/Win32-OpenSSH#1752]
From https://github.com/microsoft/vscode-remote-release/issues/4524

This is a strange issue. Two users are reporting that if they log in locally and run this command in powershell: `icacls.exe testfile.txt` then it runs successfully. But if they run the same command through SSH with powershell, it fails: `echo icacls.exe testfile.txt | ssh [host] powershell` with this output:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\rswhite> icacls.exe testfile.txt /reset
processed file: testfile.txt
Successfully processed 1 files; Failed processing 0 files
Program 'icacls.exe' failed to run: Win32 internal error "Access is denied" 0x5 occurred while reading the console
output buffer. Contact Microsoft Customer Support Services.At line:1 char:1
+ icacls.exe testfile.txt /reset
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ icacls.exe testfile.txt /reset
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

I have no idea what that error implies.

Here is a good place to start in the issue: https://github.com/microsoft/vscode-remote-release/issues/4524#issuecomment-784821162

Full logs from the sshd server: https://github.com/microsoft/vscode-remote-release/issues/4524#issuecomment-794750474

The server version is `OpenSSH_for_Windows_7.7`

**Comment by bagajjal** [comment]
@RyanSW - Confirmed using OpenSSH v8.1 resolved the problem.

I tried to repro using the windows inbuild openssh 7.7 but I couldn't repro.
![image](https://user-images.githubusercontent.com/23668037/110710459-c12c4d80-81b2-11eb-9fcb-290fdd630546.png)

**Comment by bagajjal** [comment]
I'm closing this issue as it works with OpenSSH v8.1.  Thanks @RyanSW
