### ISSUE TITLE
Cursor position in text editors

### ISSUE THREAD

**Issue by asheroto** [PowerShell/Win32-OpenSSH#1758]
**What are client, server operating systems?**
Client: Putty or PowerShell w/ssh.exe
OS: Server 2019

**What version of OpenSSH are you using?**
OpenSSH_for_Windows_8.0p1, LibreSSL 2.6.5

Using OpenSSH for Windows, if I remote into a server and try to edit a test file such as by typing

`nano readme.txt`

I can edit it fine, but the cursor position is not visible when I move with the arrow keys.

If I type the above command from Windows PowerShell (not using ssh), it works fine, showing the cursor position. Using PowerShell + the native ssh.exe client it hides the position or when connecting remotely to my listening port.

**Comment by bagajjal** [comment]
@asheroto - ssh server is running on windows server 2019? From where did you install the nano executable for windows?
I tried https://sourceforge.net/projects/nano-for-windows/files/latest/download but it didn't work over ssh.

nano command works well over ssh when connected to linux VM.

**Comment by asheroto** [comment]
Hi,

Indeed, it works fine on Linux machines, but not on Windows.

I installed Nano via Chocolatey, which cites its source from [here](https://www.nano-editor.org/).  Following the links, I believe it comes from [here](https://www.nano-editor.org/dist/win32-support/).  Note, the version is 2.5.3, which is old, from 2017.  Even an alternate version from SourceForge is the same version.  I guess to be sure it was Nano I would need to compile the Windows version from source.

If you believe this to be related to the text editor itself, rather than OpenSSH, I completely understand, just let me know.  Being that it works in Windows CMD/PowerShell without using SSH like just typing "nano" at the command prompt rather than remoting-in via SSH, I assumed it was an SSH issue, that's why my first stop was here 😁.

**Comment by vthiebaut10** [comment]
SSH uses conpty to launch the applications. Involving the console team to take a look at it: @Dhowett, can you please look at this issue?

**Comment by DHowett** [comment]
Thanks for looping me in! This looks like https://github.com/microsoft/terminal/issues/3202, which I just verified has been fixed in newer versions of ConPTY (tested on Windows 21xxx and Windows Terminal, which bundles an up-to-date version of conhost for its own use)

**Comment by bagajjal** [comment]
Thanks @DHowett.
I'm closing this as fixed.

**Comment by asheroto** [comment]
@DHowett , thanks for the info, am I correct it understanding that this will be fixed after the appropriate upcoming Windows updates are installed?
