### ISSUE TITLE
Wrong error message when keys dont have right permissions set: insufficient buffer space

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#176]
which is followed by "Permission denied (publickey)"

I am using an AWS pem with the 3/19/2016 release of open ssh.

This error comes after saying yes to the thumbprint prompt.

Windows 2012 client under PowerShell or CMD.exe => against Amazon Linux.

AWS connectivity verified via ping and the fact I can accept the fingerprint.

**Comment by DarwinJS** [comment]
Figured out the permission denied was due to my error.  Is the "insufficient buffer space" response relevant to a logon error?  Not sure whether to close this or if that message is still a problem in itself.

**Comment by DarwinJS** [comment]
In #132 that I asked a while back, I think we already determined that OpenSSH for windows is not actually checking the permissions on the key file.

So you might want this bug to be called "Wrong error message on some authentication errors using PEM file "insufficient buffer space"

Maybe that's what you meant - the .pem based keys do not have sufficient permissions to logon?

**Comment by bagajjal** [comment]
Verified in the recent release, not seeing this issue.
But when there are no read permissions to open a file then we are showing file not found instead of access denied. Fixed this issue.
