### ISSUE TITLE
Openssh  Chroot Directory

### ISSUE THREAD

**Issue by sunil77-i** [PowerShell/Win32-OpenSSH#1760]
HI,

I have scenario I have bunch of local users all using the sftp service, I want to set them a root folder I can achieve it by using ChrootDirectory Command.

I have folder structure like below on the D drive

D:\SFTP\User1

Folder1
Folder2

I have set the ChrootDirectory Command to **ChrootDirectory D:\SFTP\User1** the I can able to view Folder1 and Folder2 respectively but I wanted to see the User1 folder as a home directory for User1 so I tried setting ChrootDirectory D:\SFTP\ like this then I am able to see the User2 folder which I dont want to see.

My Requirement is to when a User1 login using Filezilla or winscp he should be able to see the User1 folder first then inside that Folder1 and Folder2 listed respectively.

My Requirement is as below.
![file](https://user-images.githubusercontent.com/79965477/113001807-c9aeed00-918e-11eb-89ee-2fa7c3ebf738.PNG)

When I apply ChrootDirectory D:\SFTP\ im seeing the below result which i dont want.

![image](https://user-images.githubusercontent.com/79965477/113002307-45109e80-918f-11eb-97a3-74012faa2440.png)

Please give me some suggestions please

Thanks

Sunil

**Comment by bagajjal** [comment]
@sunil77-i - You can have achieve this by creating D:\SFTP\User1\User1 and setting the chroot to  D:\SFTP\User1.
