### ISSUE TITLE
Document system requirements for the OpenSSH package

### ISSUE THREAD

**Issue by mburr-precor** [PowerShell/Win32-OpenSSH#1763]
I couldn't find any sort of documentation about the minimum system requirements in the readme, the wiki, the installation instructions or anywhere.

At the very least it would be nice to say what the minimum version of Windows this package will run on .

For the record, I have it running on a Win7 SP1 machine that is using some old tools that are license-locked to that machine (so upgrading to Win10 is an effort we are putting off as long as humanly possible).  The OpenSSH package is running fine, but maybe that's just luck or we haven't used a feature that is broken on the old Windows version?

**Comment by bagajjal** [comment]
Please refer to https://github.com/PowerShell/Win32-OpenSSH/wiki.

We support win7 and above.

**Comment by bagajjal** [comment]
I updated the https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by mburr-precor** [comment]
Thanks for letting me know that Win7 is supported and updating the wiki!
