### ISSUE TITLE
Connection reset by IP port 22

### ISSUE THREAD

**Issue by Dukro** [PowerShell/Win32-OpenSSH#1764]
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
debug1: Connecting to 192.168.0.109 [192.168.0.109] port 22.
debug1: Connection established.
debug1: identity file C:\\Users\\Dukro/.ssh/id_rsa type 0
debug1: identity file C:\\Users\\Dukro/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\Dukro/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\Dukro/.ssh/id_dsa-cert type -1
debug1: identity file C:\\Users\\Dukro/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\Dukro/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\Dukro/.ssh/id_ed25519 type -1
debug1: identity file C:\\Users\\Dukro/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\Dukro/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\Dukro/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_8.1
debug1: match: OpenSSH_for_Windows_8.1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.0.109:22 as 'Administrators'
debug1: SSH2_MSG_KEXINIT sent
Connection reset by 192.168.0.109 port 22

**Comment by bagajjal** [comment]
It's pretty much possible that the openssh bin folder is not accessible to "authenticated users".
please provide read&execute permissions to "authenticated users".

C:\Users\Administrator> get-acl C:\users\Administrator\Desktop\openssh-v8.1.0.0\ | fl *


PSPath                  : Microsoft.PowerShell.Core\FileSystem::C:\users\Administrator\Desktop\openssh-v8.1.0.0\
PSParentPath            : Microsoft.PowerShell.Core\FileSystem::C:\users\Administrator\Desktop
PSChildName             : Debug
PSDrive                 : C
PSProvider              : Microsoft.PowerShell.Core\FileSystem
CentralAccessPolicyId   :
CentralAccessPolicyName :
Path                    : Microsoft.PowerShell.Core\FileSystem::C:\users\Administrator\Desktop\openssh-v8.1.0.0\
Owner                   : BUILTIN\Administrators
Group                   : BALU\None
Access                  : {System.Security.AccessControl.FileSystemAccessRule, System.Security.AccessControl.FileSystemAccessRule,
                          System.Security.AccessControl.FileSystemAccessRule, System.Security.AccessControl.FileSystemAccessRule}
Sddl                    : O:BAG:S-1-5-21-580595344-4019799737-150087938-513D:PAI(A;OICI;0x1200a9;;;AU)(A;OICI;FA;;;SY)(A;OICI;FA;;;BA)(A;OICI;FA;;;LA)
AccessToString          : NT AUTHORITY\Authenticated Users Allow  ReadAndExecute, Synchronize
                          NT AUTHORITY\SYSTEM Allow  FullControl
                          BUILTIN\Administrators Allow  FullControl
AuditToString           :
AccessRightType         : System.Security.AccessControl.FileSystemRights
AccessRuleType          : System.Security.AccessControl.FileSystemAccessRule
AuditRuleType           : System.Security.AccessControl.FileSystemAuditRule
AreAccessRulesProtected : True
AreAuditRulesProtected  : False
AreAccessRulesCanonical : True
AreAuditRulesCanonical  : True



C:\Users\Administrator>
