### ISSUE TITLE
Start-Service: Cannot find any service with service name 'sshd'.

### ISSUE THREAD

**Issue by Dukro** [PowerShell/Win32-OpenSSH#1765]
PS C:\Users\Administrator> sudo Start-Service sshd
Start-Service: Cannot find any service with service name 'sshd'.

**Comment by bagajjal** [comment]
@Dukro - windows doesn't have sudo.
Did you run install-sshd.ps1 which registers sshd, ssh-agent as services.

Please follow the [installation steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH)

**Comment by HNazmul-X** [comment]
I am also getting same error.  Can't understand what should I do.

**Comment by tgauth** [comment]
If you have followed the installation steps mentioned above, and are still facing an issue, please open a new issue with repro steps and any logging/error messages so we are better able to assist you.

**Comment by HNazmul-X** [comment]
@tgauth  thank you for your reply. 
when I run Set-Service command it showed me error. said failed to start ssh-agent. But when I run ssh-agent.exe. fortunately it run.
