### ISSUE TITLE
Cannot log in with a local user.

### ISSUE THREAD

**Issue by infelicitas** [PowerShell/Win32-OpenSSH#1766]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
`((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)` 
"The term 'sshd' is not recognized as the name of a cmdlet, function, script file, or operable program."
But it's 8.1.0.0

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows Server 2019 Standard

**Client OperatingSystem**
Windows 10 Enterprise, SSH 7.7.2.1

**What is failing**
Cannot login with a local user and password. 
Local user and ssh-key works. 
Domain user works, this is a domain-joined computer.

I cannot figure out what is going wrong with password authentication. I've tried from both windows clients and linux clients with no luck. Would like some guidance.

**Expected output**
PS whatever-on-remote-machine>

**Actual output**
Permission denied, please try again.

SSH logfile, DEBUG3.

**4992 2021-04-06 16:29:11.884 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" -R
4992 2021-04-06 16:29:11.889 debug3: send_rexec_state: entering fd = 8 config len 226
4992 2021-04-06 16:29:11.889 debug3: ssh_msg_send: type 0
4992 2021-04-06 16:29:11.909 debug3: send_rexec_state: done
6152 2021-04-06 16:29:11.929 debug1: inetd sockets after dupping: 4, 4
6152 2021-04-06 16:29:11.929 Connection from <removed-ip> port 8967 on <removed-ip> port 22
6152 2021-04-06 16:29:11.929 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
6152 2021-04-06 16:29:11.929 debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_7.7
6152 2021-04-06 16:29:11.929 debug1: match: OpenSSH_for_Windows_7.7 pat OpenSSH* compat 0x04000000
6152 2021-04-06 16:29:11.929 debug2: fd 4 setting O_NONBLOCK
6152 2021-04-06 16:29:11.959 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" -y
6152 2021-04-06 16:29:11.959 debug2: Network child is on pid 6184
6152 2021-04-06 16:29:11.964 debug3: send_rexec_state: entering fd = 6 config len 226
6152 2021-04-06 16:29:11.964 debug3: ssh_msg_send: type 0
6152 2021-04-06 16:29:11.984 debug3: send_rexec_state: done
6152 2021-04-06 16:29:11.984 debug3: ssh_msg_send: type 0
6152 2021-04-06 16:29:11.989 debug3: ssh_msg_send: type 0
6152 2021-04-06 16:29:11.989 debug3: preauth child monitor started
6152 2021-04-06 16:29:11.989 debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
6152 2021-04-06 16:29:11.989 debug3: send packet: type 20 [preauth]
6152 2021-04-06 16:29:11.989 debug1: SSH2_MSG_KEXINIT sent [preauth]
6152 2021-04-06 16:29:11.989 debug3: receive packet: type 20 [preauth]
6152 2021-04-06 16:29:11.989 debug1: SSH2_MSG_KEXINIT received [preauth]
6152 2021-04-06 16:29:11.989 debug2: local server KEXINIT proposal [preauth]
6152 2021-04-06 16:29:11.989 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1 [preauth]
6152 2021-04-06 16:29:11.989 debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
6152 2021-04-06 16:29:11.989 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
6152 2021-04-06 16:29:11.989 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
6152 2021-04-06 16:29:11.989 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
6152 2021-04-06 16:29:11.989 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
6152 2021-04-06 16:29:11.989 debug2: compression ctos: none,zlib@openssh.com [preauth]
6152 2021-04-06 16:29:11.989 debug2: compression stoc: none,zlib@openssh.com [preauth]
6152 2021-04-06 16:29:11.989 debug2: languages ctos:  [preauth]
6152 2021-04-06 16:29:11.989 debug2: languages stoc:  [preauth]
6152 2021-04-06 16:29:11.989 debug2: first_kex_follows 0  [preauth]
6152 2021-04-06 16:29:11.989 debug2: reserved 0  [preauth]
6152 2021-04-06 16:29:11.989 debug2: peer client KEXINIT proposal [preauth]
6152 2021-04-06 16:29:11.989 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c [preauth]
6152 2021-04-06 16:29:11.989 debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa [preauth]
6152 2021-04-06 16:29:11.989 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
6152 2021-04-06 16:29:11.989 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
6152 2021-04-06 16:29:11.989 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
6152 2021-04-06 16:29:11.989 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
6152 2021-04-06 16:29:11.989 debug2: compression ctos: none [preauth]
6152 2021-04-06 16:29:11.989 debug2: compression stoc: none [preauth]
6152 2021-04-06 16:29:11.989 debug2: languages ctos:  [preauth]
6152 2021-04-06 16:29:11.989 debug2: languages stoc:  [preauth]
6152 2021-04-06 16:29:11.989 debug2: first_kex_follows 0  [preauth]
6152 2021-04-06 16:29:11.989 debug2: reserved 0  [preauth]
6152 2021-04-06 16:29:11.989 debug1: kex: algorithm: curve25519-sha256 [preauth]
6152 2021-04-06 16:29:11.989 debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
6152 2021-04-06 16:29:11.989 debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
6152 2021-04-06 16:29:11.989 debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
6152 2021-04-06 16:29:11.989 debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
6152 2021-04-06 16:29:11.999 debug3: receive packet: type 30 [preauth]
6152 2021-04-06 16:29:11.999 debug3: mm_sshkey_sign entering [preauth]
6152 2021-04-06 16:29:11.999 debug3: mm_request_send entering: type 6 [preauth]
6152 2021-04-06 16:29:11.999 debug3: mm_sshkey_sign: waiting for MONITOR_ANS_SIGN [preauth]
6152 2021-04-06 16:29:11.999 debug3: mm_request_receive_expect entering: type 7 [preauth]
6152 2021-04-06 16:29:11.999 debug3: mm_request_receive entering [preauth]
6152 2021-04-06 16:29:11.999 debug3: mm_request_receive entering
6152 2021-04-06 16:29:11.999 debug3: monitor_read: checking request 6
6152 2021-04-06 16:29:11.999 debug3: mm_answer_sign
6152 2021-04-06 16:29:12.004 debug3: mm_answer_sign: KEX signature 0000017974050EC0(100)
6152 2021-04-06 16:29:12.004 debug3: mm_request_send entering: type 7
6152 2021-04-06 16:29:12.004 debug2: monitor_read: 6 used once, disabling now
6152 2021-04-06 16:29:12.004 debug3: send packet: type 31 [preauth]
6152 2021-04-06 16:29:12.004 debug3: send packet: type 21 [preauth]
6152 2021-04-06 16:29:12.004 debug2: set_newkeys: mode 1 [preauth]
6152 2021-04-06 16:29:12.004 debug1: rekey out after 134217728 blocks [preauth]
6152 2021-04-06 16:29:12.004 debug1: SSH2_MSG_NEWKEYS sent [preauth]
6152 2021-04-06 16:29:12.004 debug1: Sending SSH2_MSG_EXT_INFO [preauth]
6152 2021-04-06 16:29:12.004 debug3: send packet: type 7 [preauth]
6152 2021-04-06 16:29:12.004 debug1: expecting SSH2_MSG_NEWKEYS [preauth]
6152 2021-04-06 16:29:12.019 debug3: receive packet: type 21 [preauth]
6152 2021-04-06 16:29:12.019 debug1: SSH2_MSG_NEWKEYS received [preauth]
6152 2021-04-06 16:29:12.019 debug2: set_newkeys: mode 0 [preauth]
6152 2021-04-06 16:29:12.019 debug1: rekey in after 134217728 blocks [preauth]
6152 2021-04-06 16:29:12.019 debug1: KEX done [preauth]
6152 2021-04-06 16:29:12.034 debug3: receive packet: type 5 [preauth]
6152 2021-04-06 16:29:12.034 debug3: send packet: type 6 [preauth]
6152 2021-04-06 16:29:12.034 debug3: receive packet: type 50 [preauth]
6152 2021-04-06 16:29:12.034 debug1: userauth-request for user ads-lok-backup service ssh-connection method none [preauth]
6152 2021-04-06 16:29:12.034 debug1: attempt 0 failures 0 [preauth]
6152 2021-04-06 16:29:12.034 debug3: mm_getpwnamallow entering [preauth]
6152 2021-04-06 16:29:12.034 debug3: mm_request_send entering: type 8 [preauth]
6152 2021-04-06 16:29:12.034 debug3: mm_getpwnamallow: waiting for MONITOR_ANS_PWNAM [preauth]
6152 2021-04-06 16:29:12.034 debug3: mm_request_receive_expect entering: type 9 [preauth]
6152 2021-04-06 16:29:12.034 debug3: mm_request_receive entering [preauth]
6152 2021-04-06 16:29:12.034 debug3: mm_request_receive entering
6152 2021-04-06 16:29:12.034 debug3: monitor_read: checking request 8
6152 2021-04-06 16:29:12.034 debug3: mm_answer_pwnamallow
6152 2021-04-06 16:29:12.034 debug2: parse_server_config: config reprocess config len 226
6152 2021-04-06 16:29:12.039 debug3: LsaLogonUser Succeeded (Impersonation: 0)
6152 2021-04-06 16:29:12.039 debug3: mm_answer_pwnamallow: sending MONITOR_ANS_PWNAM: 1
6152 2021-04-06 16:29:12.039 debug3: mm_request_send entering: type 9
6152 2021-04-06 16:29:12.039 debug2: monitor_read: 8 used once, disabling now
6152 2021-04-06 16:29:12.039 debug2: input_userauth_request: setting up authctxt for ads-lok-backup [preauth]
6152 2021-04-06 16:29:12.039 debug3: mm_inform_authserv entering [preauth]
6152 2021-04-06 16:29:12.039 debug3: mm_request_send entering: type 4 [preauth]
6152 2021-04-06 16:29:12.039 debug2: input_userauth_request: try method none [preauth]
6152 2021-04-06 16:29:12.039 debug3: mm_request_receive entering
6152 2021-04-06 16:29:12.039 debug3: monitor_read: checking request 4
6152 2021-04-06 16:29:12.039 debug3: mm_answer_authserv: service=ssh-connection, style=
6152 2021-04-06 16:29:12.039 debug2: monitor_read: 4 used once, disabling now
6152 2021-04-06 16:29:12.039 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
6152 2021-04-06 16:29:12.039 debug3: ensure_minimum_time_since: elapsed 4.990ms, delaying 0.920ms (requested 5.911ms) [preauth]
6152 2021-04-06 16:29:12.044 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
6152 2021-04-06 16:29:12.044 debug3: send packet: type 51 [preauth]
6152 2021-04-06 16:29:12.049 debug3: receive packet: type 50 [preauth]
6152 2021-04-06 16:29:12.049 debug1: userauth-request for user ads-lok-backup service ssh-connection method keyboard-interactive [preauth]
6152 2021-04-06 16:29:12.049 debug1: attempt 1 failures 0 [preauth]
6152 2021-04-06 16:29:12.049 debug2: input_userauth_request: try method keyboard-interactive [preauth]
6152 2021-04-06 16:29:12.049 debug1: keyboard-interactive devs  [preauth]
6152 2021-04-06 16:29:12.049 debug1: auth2_challenge: user=ads-lok-backup devs= [preauth]
6152 2021-04-06 16:29:12.049 debug1: kbdint_alloc: devices '' [preauth]
6152 2021-04-06 16:29:12.049 debug2: auth2_challenge_start: devices  [preauth]
6152 2021-04-06 16:29:12.049 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
6152 2021-04-06 16:29:12.049 debug3: ensure_minimum_time_since: elapsed 0.000ms, delaying 5.911ms (requested 5.911ms) [preauth]
6152 2021-04-06 16:29:12.059 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
6152 2021-04-06 16:29:12.059 debug3: send packet: type 51 [preauth]
6152 2021-04-06 16:29:35.933 debug3: receive packet: type 50 [preauth]
6152 2021-04-06 16:29:35.933 debug1: userauth-request for user ads-lok-backup service ssh-connection method password [preauth]
6152 2021-04-06 16:29:35.938 debug1: attempt 2 failures 1 [preauth]
6152 2021-04-06 16:29:35.948 debug2: input_userauth_request: try method password [preauth]
6152 2021-04-06 16:29:35.948 debug3: mm_auth_password entering [preauth]
6152 2021-04-06 16:29:35.948 debug3: mm_request_send entering: type 12 [preauth]
6152 2021-04-06 16:29:35.948 debug3: mm_request_receive entering
6152 2021-04-06 16:29:35.948 debug3: monitor_read: checking request 12
6152 2021-04-06 16:29:35.948 debug1: Windows authentication failed for user: ads-lok-backup domain: . error: 1326
6152 2021-04-06 16:29:35.948 debug3: mm_answer_authpassword: sending result 0
6152 2021-04-06 16:29:35.948 debug3: mm_request_send entering: type 13
6152 2021-04-06 16:29:35.948 Failed password for ads-lok-backup from <removed-ip> port 8967 ssh2
6152 2021-04-06 16:29:35.948 debug3: mm_auth_password: waiting for MONITOR_ANS_AUTHPASSWORD [preauth]
6152 2021-04-06 16:29:35.948 debug3: mm_request_receive_expect entering: type 13 [preauth]
6152 2021-04-06 16:29:35.948 debug3: mm_request_receive entering [preauth]
6152 2021-04-06 16:29:35.948 debug3: mm_auth_password: user not authenticated [preauth]
6152 2021-04-06 16:29:35.948 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
6152 2021-04-06 16:29:35.948 debug3: ensure_minimum_time_since: elapsed 15.015ms, delaying 8.627ms (requested 5.911ms) [preauth]
6152 2021-04-06 16:29:35.961 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
6152 2021-04-06 16:29:35.961 debug3: send packet: type 51 [preauth]
6152 2021-04-06 16:29:45.465 debug3: receive packet: type 50 [preauth]
6152 2021-04-06 16:29:45.465 debug1: userauth-request for user ads-lok-backup service ssh-connection method password [preauth]
6152 2021-04-06 16:29:45.465 debug1: attempt 3 failures 2 [preauth]
6152 2021-04-06 16:29:45.465 debug2: input_userauth_request: try method password [preauth]
6152 2021-04-06 16:29:45.465 debug3: mm_auth_password entering [preauth]
6152 2021-04-06 16:29:45.465 debug3: mm_request_send entering: type 12 [preauth]
6152 2021-04-06 16:29:45.465 debug3: mm_request_receive entering
6152 2021-04-06 16:29:45.465 debug3: monitor_read: checking request 12
6152 2021-04-06 16:29:45.465 debug1: Windows authentication failed for user: ads-lok-backup domain: . error: 1326
6152 2021-04-06 16:29:45.465 debug3: mm_answer_authpassword: sending result 0
6152 2021-04-06 16:29:45.465 debug3: mm_request_send entering: type 13
6152 2021-04-06 16:29:45.465 Failed password for ads-lok-backup from <removed-ip> port 8967 ssh2
6152 2021-04-06 16:29:45.465 debug3: mm_auth_password: waiting for MONITOR_ANS_AUTHPASSWORD [preauth]
6152 2021-04-06 16:29:45.465 debug3: mm_request_receive_expect entering: type 13 [preauth]
6152 2021-04-06 16:29:45.465 debug3: mm_request_receive entering [preauth]
6152 2021-04-06 16:29:45.465 debug3: mm_auth_password: user not authenticated [preauth]
6152 2021-04-06 16:29:45.465 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
6152 2021-04-06 16:29:45.465 debug3: ensure_minimum_time_since: elapsed 0.000ms, delaying 5.911ms (requested 5.911ms) [preauth]
6152 2021-04-06 16:29:45.475 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
6152 2021-04-06 16:29:45.475 debug3: send packet: type 51 [preauth]
6152 2021-04-06 16:29:46.733 debug3: recv - from CB ERROR:10054, io:00000238D6DAA210 [preauth]
6152 2021-04-06 16:29:46.733 Connection reset by authenticating user ads-lok-backup <removed-ip> port 8967 [preauth]
6152 2021-04-06 16:29:46.733 debug1: do_cleanup [preauth]
6152 2021-04-06 16:29:46.738 debug3: mm_request_receive entering
6152 2021-04-06 16:29:46.738 debug1: do_cleanup
6152 2021-04-06 16:29:46.738 debug1: Killing privsep child 6184*

Windows security log states: Error 4625, An account failed to log on.
Logon type: 8
Security ID: NULL SID
Account name: ads-lok-backup
Account domain: <local server name>
Failure reason: Unknown username or bad password.

**Comment by bagajjal** [comment]
@infelicitas - 
Looking at the sshd logs, error 1326 corresponds to "The user name or password is incorrect."
6152 2021-04-06 16:29:45.465 debug1: Windows authentication failed for user: ads-lok-backup domain: . error: 1326

do you have same name as machine name and user name? If yes then please change one of those.
does "net user" on powershell/cmd shows the local user?
Can you first type the password in a notepad, copy and paste to make sure the ssh client is taking the right password.
if this didn't work then change the password of local user and try one more time.

**Comment by infelicitas** [comment]
_No, the machine name is different. 

Net user shows the user info, account active, password required._

I was starting to wonder about the password now. I had been both typing and copy/paste:ing the password before, on multiple machines. I could do standard log in to windows. But now set the password to something super-simple, and it works over ssh! 
I guess there are some symbols or locale in the original password that get mis-encoded over an ssh connection. But coming up with an new password is easy.

**Comment by infelicitas** [comment]
Was using some form of invalid characters in password string. Tested OK with simple password.
