### ISSUE TITLE
Missing builds for aarch64

### ISSUE THREAD

**Issue by adiantek** [PowerShell/Win32-OpenSSH#1774]
https://github.com/PowerShell/Win32-OpenSSH/releases/
There are builds only for x64_86 and x86. I've Windows with aarch64. Where could I find the latest version for aarch64? The latest version on Windows 10 has bugged ProxyJump and it's already compiled into aarch64.

**Comment by bagajjal** [comment]
We don't have ARM32, ARM64 builds for our github releases. There is no ask from community so far.
Having said that April windows update on 4/22 will have OpenSSH v8.1 for windows 10.
