### ISSUE TITLE
what's the hackery behind Medium IL elevating to High IL within same window ?

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#1775]
**"OpenSSH for Windows" version**
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.4
 
**Server OperatingSystem**
Windows 10 Pro - 10.0.19042.928

**Client OperatingSystem**
Windows 10 Pro - 10.0.19042.928

**What is failing**

win32 apps generally create a sperate window for running a process with High IL with UAC.

successfully  sshing to `ssh adminUser@anyLocalIP` elevates standard users medium IL shell to High IL within the same window without spawning a separate High IL window without UAC.

**AFAIK, it's only possible to elevate a medium IL process to HIgh IL by manually a system IL process replacing the medium IL process's access Token.**

**(1.) Doesn't it go against windows process security model?
(2.) what's sort of hackery is used here?**

**Comment by bagajjal** [comment]
@ecovio1 - I didn't get your acronyms High IL, medium IL. But I think I get your question.
When you ssh to a windows ssh server (locally or remotely), the ssh server will create a shell (in the background) in the elevated mode for admin users only.
ssh client (locally or remotely) will send the command to the ssh server which executes the command in elevated mode.

It looks like we elevate the client shell (ssh client shell)  but it's not. Once you exit the client shell then you will be back to the non-elevated shell.

Does this answer your question?

**Comment by ghost** [comment]
By IL, I was referring to [Mandatory Integrity Level](https://docs.microsoft.com/en-us/windows/win32/secauthz/mandatory-integrity-control).

Yes, thanks. that answers my question fully.
