### ISSUE TITLE
Event ID 2 in Event log

### ISSUE THREAD

**Issue by jakfrost84** [PowerShell/Win32-OpenSSH#1776]
I am getting an error in the even log. Is this of concern? Everything appears to be working properly. 

Event ID: 2
sshd: error: kex_exchange_identification: read: Connection reset
sshd: error: kex_exchange_identification: read: Connection aborted

**Comment by bagajjal** [comment]
Please provide full sshd.log. Refer to https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities#file-based-logging

**Comment by jakfrost84** [comment]
2532 2021-04-20 13:12:30.907 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" -R
2532 2021-04-20 13:12:30.909 debug3: send_rexec_state: entering fd = 8 config len 531
2532 2021-04-20 13:12:30.909 debug3: ssh_msg_send: type 0
2532 2021-04-20 13:12:30.918 debug3: send_rexec_state: done
3832 2021-04-20 13:12:30.934 debug1: inetd sockets after dupping: 4, 4
3832 2021-04-20 13:12:30.934 Connection from 127.0.0.1 port 51311 on 127.0.0.1 port 22
3832 2021-04-20 13:12:30.935 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
3832 2021-04-20 13:12:30.935 debug3: WSARecv - WSARecv() ERROR: io:000000166FBB9670 10053
3832 2021-04-20 13:12:30.935 error: kex_exchange_identification: read: Connection aborted

**Comment by jakfrost84** [comment]
3296 2021-04-20 13:20:53.285 debug1: inetd sockets after dupping: 4, 4
3296 2021-04-20 13:20:53.285 Connection from 127.0.0.1 port 51375 on 127.0.0.1 port 22
3296 2021-04-20 13:20:53.285 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
3296 2021-04-20 13:20:53.286 debug3: WSARecv - WSARecv() ERROR: io:00000084D22A9670 10053
3296 2021-04-20 13:20:53.286 error: kex_exchange_identification: read: Connection aborted
2532 2021-04-20 13:21:55.748 debug3: fd 5 is not O_NONBLOCK
2532 2021-04-20 13:21:55.749 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" -R
2532 2021-04-20 13:21:55.750 debug3: send_rexec_state: entering fd = 8 config len 531
2532 2021-04-20 13:21:55.750 debug3: ssh_msg_send: type 0
2532 2021-04-20 13:21:55.760 debug3: send_rexec_state: done
4928 2021-04-20 13:21:55.776 debug1: inetd sockets after dupping: 4, 4
4928 2021-04-20 13:21:55.776 Connection from 127.0.0.1 port 51384 on 127.0.0.1 port 22
4928 2021-04-20 13:21:55.777 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
4928 2021-04-20 13:21:55.778 debug3: recv - from CB(2) ERROR:108, io:000000E31EAA9670
4928 2021-04-20 13:21:55.778 error: kex_exchange_identification: read: Connection reset

**Comment by bagajjal** [comment]
Looks like the connection is closed by client. To debug further we need client side logs (.\ssh.exe -vvv user@ip) , server side logs for the same ssh connection.

**Comment by jakfrost84** [comment]
Since the client in this case is the local host what user would I use? In the logs I see OpenSSH/admin related to the error.  I have no issues connecting with the allowed users in the config.  I just noticed this error happened ~every minute.

**Comment by bagajjal** [comment]
Ideally you shouldn't see this error. In order to debug the error, we need ssh client (ssh -vvv user@ip) and sshd.log (with debug3 enabled).

If you are not experiencing any ssh connection issues then we can't debug this issue as you can't collect required logs.
I suggest you try to repro, collect logs both on client and server. If not then close the issue.
