### ISSUE TITLE
Server Refused the Connection

### ISSUE THREAD

**Issue by sunil77-i** [PowerShell/Win32-OpenSSH#1778]
Hi All,

I have installed the latest Version of OpenSSH win-64, And Configured everything properly.

The connection was working fine for more than 2 weeks after all of a sudden getting the below error.
![image](https://user-images.githubusercontent.com/79965477/115578555-062fbd80-a2e3-11eb-9342-97d2ec2bf36f.png)

Please help me to get rid of this issue.

Thanks,

Sunil

**Comment by bagajjal** [comment]
Please follow steps [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps) to debug.

**Comment by bagajjal** [comment]
Closing this based on #1779 as you mention it works after sshd service restart.

**Comment by sunil77-i** [comment]
@bagajjal Hi,

I have tried the steps mentioned in the here section and found the below logs,

![image](https://user-images.githubusercontent.com/79965477/115824049-fd470500-a424-11eb-86ec-837a4921c182.png)

Thanks,

Sunil

**Comment by sunil77-i** [comment]
Hi @bagajjal ,

May I get any update please.

Thanks,
Sunil

**Comment by bagajjal** [comment]
@sunil77-i  - I don't see any error in the screenshot you share..  There is no incoming connection as per logs. You should see the below logs when there is a new incoming ssh connection,

debug1: Server will not fork when running in debugging mode.
debug3: send_rexec_state: entering fd = 8 config len 291
debug3: ssh_msg_send: type 0
debug3: send_rexec_state: done
Connection from ::1 port 50519 on ::1 port 22

To assist you better, please share your scenario, ssh client logs (ssh -vvv user@ip), ssh server logs.

**Comment by sunil77-i** [comment]
@bagajjal Hi,

I ran the command sftp -vvv user@host and I found the below logs,

![image](https://user-images.githubusercontent.com/79965477/115984027-80519200-a5c2-11eb-9867-ff88416a82e1.png)

Thanks,
Sunil

**Comment by sunil77-i** [comment]
@bagajjal Any update?

Thanks,

Sunil

**Comment by bagajjal** [comment]
@sunil77-i - Are you running ssh client in the same machine or from different machine? Did you have the firewall setting enabled to accept incoming traffic on port 22?

**Comment by sunil77-i** [comment]
@bagajjal I am running ssh client on the same machine.
Yes I have firewall with port 22 and it is enabled.

Thanks,
Sunil

**Comment by bagajjal** [comment]
@sunil77-i - Please run sshd as service. Provide full [ssh server side](https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities), client side logs (ssh -vvv user@ip) for the same connection.
I still don't understand why ssh client can't establish a connection when sshd service listens on port 22.

**Comment by bagajjal** [comment]
Make sure there are no processes other than sshd server running on port 22.

**Comment by sunil77-i** [comment]
@bagajjal I tried running the sshd as service, but there is no logs has been generated while attempting to connect to ssh server.
please let me know if I missed something.

Yes I confirmed no other processes are running on port 22.

Thanks,
Sunil

**Comment by bagajjal** [comment]
@sunil77-i  - By default sshd logging is ETW based. I gave a link in my previous comment on how you can enable file based logging. please follow the steps to enable file based logging.

![image](https://user-images.githubusercontent.com/23668037/116127098-493fb700-a67c-11eb-90d2-02afb77bbce9.png)
