### ISSUE TITLE
Can only SSH into Windows computer under debug mode

### ISSUE THREAD

**Issue by Tyrubias** [PowerShell/Win32-OpenSSH#1781]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `7.7.2.3`
 
**Server OperatingSystem**
 `Windows 10 Education`

**Client OperatingSystem**
`macOS 11.2.3 20D91 arm64`

**What is failing**
I can't SSH into my Windows computer from my macOS computer when running `sshd` as a service under `SYSTEM`. However, running `sshd.exe -d` (debug mode). I'm using public key based authentication and have added my macOS computer's public key to my home folder's `.ssh\authorized_keys` file.

**Expected output**
I can SSH into my Windows computer.

**Actual output**
`Permission denied (publickey,keyboard-interactive).`

**Comment by bagajjal** [comment]
@Tyrubias - please follow instructions [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Setup-public-key-based-authentication-for-windows) to setup key based authentication.

fyi, when you run sshd in debug mode, it works only for the user who is running sshd in debug mode.

**Comment by Tyrubias** [comment]
@bagajjal I tried the instructions and it produced the same results, even on a fresh install of Windows.

**Comment by bagajjal** [comment]
What is the output of "whoami /user" on cmd.exe. If the SID starts with "S-1-12-" then it's AAD user and windows OS doesn't have support to create s4u token for AAD users i.e., you can't SSH log in with AAD credentials.

Else, share the ssh client logs (ssh -vvv user@ip) and [sshd server side logs](https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities).

**Comment by Tyrubias** [comment]
@bagajjal Thank you so much for the help. I discovered that I was running as an AAD user because I was running Windows 10 Education and I switched away.
