### ISSUE TITLE
This error  'No supported authentication methods available ( server sent : publickey, keyboard-interactive) ' has been trigged for the creation of new users.

### ISSUE THREAD

**Issue by Vetrikumar74-cloud** [PowerShell/Win32-OpenSSH#1782]
Error Message : This error  'No supported authentication methods available ( server sent : publickey, keyboard-interactive) ' has been trigged for the creation of new users.

But old users still able to access

Any ideas?

**Comment by mgkuhn** [comment]
Full client (`ssh -v`) and [server log files](https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities) attached here might help.
Do your new users all have an [`authorized_keys` file set up](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement) correctly?

**Comment by Vetrikumar74-cloud** [comment]
Hi Mgkuhn,

Will give a shot on this.

**Comment by bagajjal** [comment]
@Vetrikumar74-cloud - Also provide ssh_config (if you have any), sshd_config

**Comment by bagajjal** [comment]
If you are still facing this issue, please reopen with the requested information.
