### ISSUE TITLE
OpenSSH Service won't start when using Ciphers within sshd_config file

### ISSUE THREAD

**Issue by Adam1986** [PowerShell/Win32-OpenSSH#1788]
**"OpenSSH for Windows" version**
8.1.0.0
 
**Server OperatingSystem**
Windows Server 2019

**Client OperatingSystem**
Cisco Unified Communications Solutions Appliance

We're utilising OpenSSH on Windows to store backups of some Cisco Systems in our workplace.  One of these systems will not connect to the OpenSSH server, the OpenSSH Server logs show the following:

`Unable to negotiate with 192.168.142.142 port 51747: no matching cipher found. Their offer: aes128-cbc,none,3des-cbc,blowfish-cbc [preauth]`

If I add any of these Ciphers into the sshd_config file within C:\ProgramData\ssh the service will no longer start with the simple error of:

`The OpenSSH SSH Server service terminated unexpectedly.`

Nothing gets written into any log files.

How do I get around this issue to be able to get this Cisco Device to be able to connect to the OpenSSH Server using specific Ciphers?

This seems to be similar to this issue logged here: https://github.com/PowerShell/Win32-OpenSSH/issues/1536

Thanks

**Comment by bagajjal** [comment]
@Adam1986 - It would help what ciphers you are trying to add to c:\programdata\ssh\sshd_config.
fyi, blowfish-cbc, none are not supported ciphers.

If you have the below line in sshd_config then you are good.
 Ciphers aes128-cbc,3des-cbc

Please make sure, sshd service is restarted to take sshd_config changes to take in affect.

If you still have problem the start sshd.exe in debug mode (.\sshd.exe -ddd).

**Comment by Adam1986** [comment]
Pleased to say this has fixed it - I was placing the Ciphers on a new line underneath the Match Group and when starting sshd.exe -ddd it was making it clear that was the issue.  So placed that block of configuration elsewhere and now the service starts fine and the device connects and uploads backups with no error.

**Comment by mohaa8844** [comment]
@Adam1986  Thanks 
With -ddd option I found out that the my issue was just the location of the config (it was after some matching config )

**Comment by jmferreirab** [comment]
@Adam1986 suggestion to put the Ciphers line before the Match Group setting also helped me

![image](https://github.com/PowerShell/Win32-OpenSSH/assets/29668777/840dc755-1497-4054-9f9b-24a8e7d9e4e1)

However, the service also seems to fail to start if logging was enabled and the %programdata%/ssh/logs folder exists:

```
# Logging
SyslogFacility LOCAL0
LogLevel DEBUG3
```

Deleting the logs folder before restarting the server fixes this. This is partially hinted at in the troubleshooting docs: https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps
