### ISSUE TITLE
Proposed Updates to Install Instructions for Chocolatey

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#179]
I discussed this with someone on the Win32-OpenSSH team, but can't find the thread now.

Github does not allow forking and PRs for wikis like it does for code - so I couldn't get these updates to you in that way.

Here is the markdown I propose for the bottom of [https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH]

Feel free to edit it as you see fit.
## Automated Install and Upgrade Using Chocolatey

The Chocolatey package is maintained to do all the above install items.  The package is also engineered to use 'Choco upgrade win32-openssh' to update to the latest release.
Be sure to look over the installation instructions on Chocolatey as the package takes special switches to install, upgrade and uninstall the sshd service and a special switch to completely clean up server keys on an uninstall.
## Chocolatey Package Testing and Features

Generally the Chocolatey package is tested for upgrade from the previous release, forced install on top of itself (fix a broken install) and clean uninstall.
For upgrade and forced install scenarios the Chocolatey package leaves existing server keys and config files in place - it requires a special switch to remove these during uninstall.
## Differences Between Chocolatey Package and Install Instructions Above

These differences are mainly due to assuming you are deploying this automatically to a set of servers - not just playing on one.
1. Sets sshd service to start automatically and starts it.
2. Opens sshd port in windows firewall for sshd service (and removes it's firewall rules on uninstall)
3. Does not call install/uninstall helper scripts - but uses it's own code. (this allowed the chocolatey package not to exhibit lsa integration problems in early releases)
4. Works around known problem when possible - for example, currently it detects if logging is commented out per the default configuration and forces it off as the default results in logging half a GB per hour on **some systems**
5. Gives next steps advice - for instance if you install the sshd server to use key based authentication the package _does not start the sshd service_ and advises that you need to reboot to fully enact key based authentication.
## Chocolatey Package Usage Scenarios

Here is the package page: [https://chocolatey.org/packages/win32-openssh]

Here are the individual steps (or use the oneliners below to do all steps):
1. Install Chocolate Package Manager using one of the command lines on the Chocolatey.org home page [https://chocolatey.org]
2. Install SSH client tools without sshd server (one line): `choco install win32-openssh -confirm`
3. Install SSH client tools AND sshd server (one line): `choco install win32-openssh -params '"/SSHServerFeature /KeyBasedAuthenticationFeature"' -confirm`
4. Upgrade SSH client tools without sshd server (one line): `choco upgrade win32-openssh -confirm`
5. Upgrade SSH client tools AND sshd server (one line): `choco upgrade win32-openssh -params '"/SSHServerFeature"' -confirm`
6. Uninstall SSH client tools (including server if present): `choco upgrade win32-openssh -params '"/SSHServerFeature"' -confirm`
7. Uninstall SSH client tools, including server if present and remove all generated config including server keys: `choco upgrade win32-openssh -params '"/SSHServerFeature /DeleteConfigAndServerKeys"' -confirm`
## Oneliner To Install Chocolatey and Win32-OpenSSH All At Once

If you would like to install Chocolatey and OpenSSH in one go, drop this oneliner into an elevated PowerShell Prompt:
`[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {[bool]1};set-executionpolicy RemoteSigned -Force -EA 'SilentlyContinue';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/DarwinJS/ChocoPackages/master/win32-openssh/InstallChoco_and_win32-openssh.ps1'))`

To do the same thing, but also install the server, use:
`[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {[bool]1};set-executionpolicy RemoteSigned -Force -EA 'SilentlyContinue';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/DarwinJS/ChocoPackages/master/win32-openssh/InstallChoco_and_win32-openssh_with_server.ps1'))`

**Comment by manojampalam** [comment]
Added @ https://github.com/PowerShell/Win32-OpenSSH/wiki/Win32-OpenSSH-Automated-Install-and-Upgrade-using-Chocolatey 

and put in a link on the very first step of install instructions

**Comment by manojampalam** [comment]
Also, the latest installation steps include using ntrights.exe (picked up from 2003 resource tool kit and packaged in zip) to adjust privilege assignments. I'm looking for a non-ntrights alternative.
