### ISSUE TITLE
System Error 1067 has occurred

### ISSUE THREAD

**Issue by at20210511** [PowerShell/Win32-OpenSSH#1793]
**Info**
Win32-OpenSSH Version: v8.1.0.0p1-Beta
Server Operating System: Windows Server 2016 (1607)

**What is failing**
after running install-sshd.ps1, the OpenSSH Service crash with error 1067 when try to start (net start sshd).
ssh-keygen.exe -A and running FixHostFilePermissions.ps1 did not solve the issue.

**Comment by bagajjal** [comment]
1067 means "process aborted". It's hard to tell what's causing sshd service to abort.
Follow the below steps and provide the logs
1) open a cmd.exe 
2) cd <openssh_bin_folder>
3) run ".\sshd.exe -ddd"

**Comment by at20210511** [comment]
debug2:load_server_config: filename __programdata__\\ssh/sshd_config
debug3:Failed to open file:c:/programdata/sshd_config error:2
__programdata__\ssh/sshd_config: no such file or drectory

**Comment by bagajjal** [comment]
Looks like you haven't run the install-sshd.ps1. please follow instructions [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH)

**Comment by at20210511** [comment]
I have run the install-sshd.ps1.
.\install-sshd.ps1
[SC] SetServiceObjectSecurity SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
sshd and sshd-agent services successfully installed.

Still the same issue:
debug2:load_server_config: filename programdata\ssh/sshd_config
debug3:Failed to open file:c:/programdata/sshd_config error:2
programdata\ssh/sshd_config: no such file or drectory

**Comment by bagajjal** [comment]
@at20210511 , After installing. You need to start the sshd service.
Please follow all the [steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH)
