### ISSUE TITLE
cant login running 4_5_2016 or OpenSSH-Win64-1.1.zip on windows 8.1

### ISSUE THREAD

**Issue by janwilmans** [PowerShell/Win32-OpenSSH#180]
Logging in with local user 'jan' works ok, the logging shows this:

5008 09:41:54 934 error: getsockname failed: The system detected an invalid pointer address in attempting to use a pointer argument in a call.

5008 09:41:56 777 error: getsockname failed: The system detected an invalid pointer address in attempting to use a pointer argument in a call.

-- connect using putty with user 'jan' 
5008 09:41:59 141 Accepted password for jan from :: port 50913 ssh2
5008 09:41:59 141 error: getsockname failed: The system detected an invalid pointer address in attempting to use a pointer argument in a call.
5008 09:41:59 141 error: getsockname failed: The system detected an invalid pointer address in attempting to use a pointer argument in a call.
-- user 'jan' in now logged in

-- connect using putty with user 'wortel' 

8732 09:43:37 895 error: getsockname failed: The system detected an invalid pointer address in attempting to use a pointer argument in a call.

8732 09:43:39 895 error: getsockname failed: The system detected an invalid pointer address in attempting to use a pointer argument in a call.

8732 09:43:42 053 Accepted password for wortel from :: port 50916 ssh2
8732 09:43:42 063 error: getsockname failed: The system detected an invalid pointer address in attempting to use a pointer argument in a call.

8732 09:43:42 063 error: getsockname failed: The system detected an invalid pointer address in attempting to use a pointer argument in a call.

6500 09:38:34 337 Accepted password for wortel from :: port 50860 ssh2
6500 09:38:34 347 error: getsockname failed: The system detected an invalid pointer address in attempting to use a pointer argument in a call.
-- putty reports

**Comment by janwilmans** [comment]
sorry the mess in the previous comment, I can seem to edit it anymore.
in case of user 'jan' to works fine.
in case of user 'wortel' the logging in the sshd.log is exactly the same, but the client connection is lost immediately after login.

C:\temp\OpenSSH-Win32>ssh localhost -l wortel
wortel@localhost's password:
packet_write_wait: Connection to ::1: Unknown error

C:\temp\OpenSSH-Win32>

**Comment by manojampalam** [comment]
See if https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting%20Steps can help. Reopen if needed
