### ISSUE TITLE
System Error 1067 has occurred

### ISSUE THREAD

**Issue by at20210511** [PowerShell/Win32-OpenSSH#1801]
Info
Win32-OpenSSH Version: v8.1.0.0p1-Beta
Server Operating System: Windows Server 2016 (1607)

What is failing
after running install-sshd.ps1, the OpenSSH Service crash with error 1067 when try to start (net start sshd).
ssh-keygen.exe -A and running FixHostFilePermissions.ps1 did not solve the issue.

I have run the install-sshd.ps1.
.\install-sshd.ps1
[SC] SetServiceObjectSecurity SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
sshd and sshd-agent services successfully installed.

Still the same issue:
debug2:load_server_config: filename programdata\ssh/sshd_config
debug3:Failed to open file:c:/programdata/sshd_config error:2
programdata\ssh/sshd_config: no such file or drectory

**Comment by bagajjal** [comment]
Duplicate of https://github.com/PowerShell/Win32-OpenSSH/issues/1793
