### ISSUE TITLE
Permission denied (publickey,keyboard-interactive).

### ISSUE THREAD

**Issue by aescolastico** [PowerShell/Win32-OpenSSH#1802]
Problem: PubKey auth is not working on Win10 v18363.1440, OpenSSH.Server~~~~0.0.1.0

Permissions and config file are configured as documented
![Screen Shot 2021-05-20 at 8 42 45 PM](https://user-images.githubusercontent.com/30540257/119066351-9843e800-b9ad-11eb-886d-58ec871d87a4.png)

Both ssh-agent and sshd services were restarted after config and permission changes

**Comment by bagajjal** [comment]
@aescolastico  - It looks like you are trying AAD user which is not currently supported. 

https://github.com/PowerShell/Win32-OpenSSH/issues/1787

**Comment by aescolastico** [comment]
Quite right. I created a normal account and that worked. Thanks!
