### ISSUE TITLE
Permission denied (publickey) error.

### ISSUE THREAD

**Issue by mushlih-almubarak** [PowerShell/Win32-OpenSSH#1807]
I always get "Permission denied (publickey) error."
Is it because I wrote the passphrase wrong? Or for what?
If the passphrase is wrong, how do I delete the passphrase?

That error appears after I run the command: "ssh@username -p portNumber" (without " ") on powershell as administrator, then it asks for passphrase up to 3 times, then the error appears

**Comment by bagajjal** [comment]
@mushlih-almubarak - 
* What are your client and server OS?
* What win32-openssh version are you using/
* Share client side logs (ssh -vvv user@ip) and [server side logs](https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities).

**Comment by mushlih-almubarak** [comment]
Solved
