### ISSUE TITLE
Typo in Release Note https://github.com/PowerShell/Win32-OpenSSH/tree/V8.6.0.0p1-Beta

### ISSUE THREAD

**Issue by affinityv** [PowerShell/Win32-OpenSSH#1812]
The notes say:
`Allow athorizedKeysCommand to work with the System user. Thanks to @bkatyl, @NoMoreFood.`

athorizedKeysCommand should obviously be authorizedKeysCommand or AuthorizedKeysCommand

**Comment by bagajjal** [comment]
fixed. Thank you.
