### ISSUE TITLE
Issues with ~/.ssh/config

### ISSUE THREAD

**Issue by blakeduffey** [PowerShell/Win32-OpenSSH#1814]
I'm trying to configure this version of ssh to support ScaleFT (from Okta)

When i configure the config file per the Okta instructions

`Match exec "C:\Program Files (x86)\ScaleFT\bin\sft.exe resolve -q %h"
    ProxyCommand "C:\Program Files (x86)\ScaleFT\bin\sft.exe" proxycommand %h
    UserKnownHostsFile C:\Users\m29296\AppData\Local\ScaleFT\proxycommand_known_hosts`

I get this error when running ssh

`C:\\Users\\bd/.ssh/config: line 1: Bad configuration option: \377\376m

C:\\Users\\bd/.ssh/config: terminating, 1 bad configuration options`

Any thoughts appreciated

**Comment by bagajjal** [comment]
Please share the full ssh config

**Comment by blakeduffey** [comment]
Thank you for your response - that is the entire config file.

**Comment by mgkuhn** [comment]
Can you please attach your `.ssh/config` file to your reply by dragging and dropping it into the github comment window? We need to see the entire file byte-for-byte, as it appears to contain non-ASCII characters that you can't quote by pasting them into the comment box. Please *attach* the file instead.

**Comment by blakeduffey** [comment]
I appreciate the follow-up.  You were right, there were 'invisible' non-ASCII characters in the file - Okta support was able to help me.  I wasn't able to see them in VSCode (but trusty vi to the rescue)

Thanks so much
