### ISSUE TITLE
SFTP Transfer randomly stops with error `forced close`

### ISSUE THREAD

**Issue by amudhanp** [PowerShell/Win32-OpenSSH#1815]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows server 2016

**Client OperatingSystem**
Renci.SshNet.SshClient.0.0.1

**What is failing**
When doing file transfer randomly getting this error in client transfer.
"An existing connection was forcibly closed" 

Below are the Debug logs.

sftp.log
2440 2021-06-17 13:31:13.530 debug1: request 19061: write "/somefolder/somefile" (handle 0) off 623710689 len 32739
2440 2021-06-17 13:31:13.530 debug3: request 19061: sent status 0
2440 2021-06-17 13:31:13.530 sent status Success
2440 2021-06-17 13:31:13.661 debug1: read eof
2440 2021-06-17 13:31:13.661 forced close "/somefolder/somefile" bytes read 0 written 623743428
2440 2021-06-17 13:31:13.661 session closed for local user sftpuser from [some.ip]
4396 2021-06-17 13:59:51.700 session opened for local user sftpuser from [some.ip]
4396 2021-06-17 13:59:51.732 received client version 3
4396 2021-06-17 13:59:51.847 debug3: request 1: realpath
4396 2021-06-17 13:59:51.847 realpath "."

SSHD.log
5548 2021-06-17 13:31:13.016 debug2: channel 0: window 1966080 sent adjust 131072
5548 2021-06-17 13:31:13.131 debug2: channel 0: window 1966080 sent adjust 131072
5548 2021-06-17 13:31:13.331 debug2: channel 0: window 1966080 sent adjust 131072
5548 2021-06-17 13:31:13.430 debug2: channel 0: window 1966080 sent adjust 131072
5548 2021-06-17 13:31:13.530 debug2: channel 0: window 1966080 sent adjust 131072
5548 2021-06-17 13:31:13.661 debug3: recv - from CB ERROR:10054, io:000001C0E40930F0
5548 2021-06-17 13:31:13.661 Read error from remote host some.ip port 61576: Connection reset
5548 2021-06-17 13:31:13.661 debug1: do_cleanup
5640 2021-06-17 13:31:13.661 debug3: mm_request_receive entering
5640 2021-06-17 13:31:13.661 debug1: do_cleanup
1744 2021-06-17 13:59:49.606 debug3: fd 5 is not O_NONBLOCK
1744 2021-06-17 13:59:49.606 debug3: spawning "C:\\Program Files\\OpenSSH\\sshd.exe" -R
1744 2021-06-17 13:59:49.606 debug3: send_rexec_state: entering fd = 8 config len 496
1744 2021-06-17 13:59:49.606 debug3: ssh_msg_send: type 0
1744 2021-06-17 13:59:49.606 debug3: send_rexec_state: done

**Expected output**

**Actual output**

**Comment by bagajjal** [comment]
Looking at the logs, sftp client is doing a force close. Please followup with Renci.SshNet.SshClient.0.0.1 team.

2440 2021-06-17 13:31:13.661 debug1: read eof
2440 2021-06-17 13:31:13.661 forced close "/somefolder/somefile" bytes read 0 written 623743428

**Comment by amudhanp** [comment]
I am reopening this issue because I tried using with FileZilla sftp client but still same issue but some additional error messages.
Just wanted to know more info about the error msg.

**SFTP.log**
8268 2021-06-28 05:28:32.779 debug3: request 267: sent status 0
8268 2021-06-28 05:28:32.779 sent status Success
8268 2021-06-28 05:28:32.795 debug1: request 286: write "/somefoleder/somefile" (handle 0) off 11681792 len 16384
8268 2021-06-28 05:28:32.795 debug3: request 286: sent status 0
8268 2021-06-28 05:28:32.795 sent status Success
8268 2021-06-28 05:28:32.795 debug3: write ERROR from cb(2):232, io:0000015FFAAEE670
8268 2021-06-28 05:28:32.795 error: write: Unknown error
8268 2021-06-28 05:28:32.795 forced close "/somefoleder/somefile" bytes read 0 written 11698176
8268 2021-06-28 05:28:32.795 session closed for local user sftpuser from [1.1.1.1]
9844 2021-06-28 05:28:43.668 debug3: request 256: realpath
9844 2021-06-28 05:28:43.668 realpath "/somefoleder/."
9844 2021-06-28 05:28:43.668 debug1: request 256: sent names count 1


12712 2021-06-28 04:32:55.977 debug3: request 55: sent status 0
12712 2021-06-28 04:32:55.977 sent status Success
8608 2021-06-28 04:32:56.076 debug1: read eof
8608 2021-06-28 04:32:56.076 forced close "/somefoleder/somefile" bytes read 0 written 57522423
8608 2021-06-28 04:32:56.076 session closed for local user sftpuser from [1.1.1.1]
12712 2021-06-28 04:32:56.176 debug1: request 56: write "/somefoleder/somefile" (handle 0) off 1505994 len 32739
12712 2021-06-28 04:32:56.176 debug3: request 56: sent status 0

**sshd.log**
11436 2021-06-28 04:32:55.762 debug2: channel 0: window 1966080 sent adjust 131072
932 2021-06-28 04:32:56.076 debug3: recv - from CB ERROR:10060, io:000001E3FF4BFFE0
932 2021-06-28 04:32:56.076 Read error from remote host 1.1.1.1 port 49938: Connection timed out
932 2021-06-28 04:32:56.076 debug1: do_cleanup
13200 2021-06-28 04:32:56.076 debug3: mm_request_receive entering
13200 2021-06-28 04:32:56.076 debug1: do_cleanup
11436 2021-06-28 04:32:56.176 debug2: channel 0: window 1966080 sent adjust 131072

Filezilla reports " FATAL ERROR" : Remote side unexpectedly closed network connection.
