### ISSUE TITLE
Compiling in Visual C++ 2008, as C++ code

### ISSUE THREAD

**Issue by MaxTheBenax** [PowerShell/Win32-OpenSSH#1819]
Hello,

I need to compile the sftp client and server for a Windows CE platform requiring Visual C++ 2008, compiled as C++ code.

I included stdafx.x to the *.c files, for example I modified xmss_wots.c as follow  
#include "stdafx.h"
#include "includes.h"
...

I get compile errors like the following:
xmss_wots.c
c:\users\me\documents\visual studio 2008\projects\OpenSSH\OpenSSH\includes.h(19) : fatal error C1083: Cannot open include file: 'config.h': No such file or directory

Is it possible to compile openssh-portable with Visual C++ 2008, as C++ code, please?

Thank you for your answer.

**Comment by MaxTheBenax** [comment]
Hello Bagajjal,

Thank you for your answer.
I am using an embedded system running with Windows CE.
The system required to compile applications using a third party library written in C++ and compiled with Visual C++ 2008. 

Thank you again for your answer,

**Comment by bagajjal** [comment]
Ok, Good luck. We build using VS2015+.
