### ISSUE TITLE
ssh + cat - broken pipe

### ISSUE THREAD

**Issue by fptstl** [PowerShell/Win32-OpenSSH#182]
Hi,

I am usually doing on a Linux system:
cat file1 | ssh user@server "cat > file2"

However, it is not working from a Linux server to the windows server running Win32-OpenSSH
I have tried:
cat /home/usr01/filea | ssh usr01@server "cmd /c type > c:\Users\usr01\Documents\filea.txt"

without success.

Suggestions?

Thanks.

Florin

**Comment by fptstl** [comment]
!bump!

**Comment by manojampalam** [comment]
AFIAK, there's isn't cat-like tool for Windows that can mimic this over SSH.
