### ISSUE TITLE
Server refused to start a shell/command on occasion

### ISSUE THREAD

**Issue by najoco** [PowerShell/Win32-OpenSSH#1820]
**"OpenSSH for Windows" version**
V8.6.0.0p1-Beta
 
**Server OperatingSystem**
Windows Server 2019 Datacenter at Azure

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
Upon occasion, I receive the error of Server refused to start a shell/command. Upon retrying connection it may connect or fail a few more times. It appears to only be an issue when not RDP'd into the server. I am not able to pinpoint a pattern.

It is impacting all users.

---------------------------
Error
---------------------------
Server refused to start a shell/command
---------------------------
Authentication log (see session log for details):
Using username "testabc456789ftp".

Authentication failed.
---------------------------
OK   Reconnect   Help   
---------------------------

[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/6718178/sshd_config.txt)
[sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/6718180/sshd.log)
[winscp.log](https://github.com/PowerShell/Win32-OpenSSH/files/6718181/winscp.log)

**Comment by bagajjal** [comment]
@najoco - Attached sshd.log is missing sshd logs from the authenticated sshd process.  Authenticated sshd process will launch the scp / sftp processes. To capture the authenticated sshd process logs, you need provide write access to the user "testabc456789ftp" to write to c:\ProgramData\ssh\logs\sshd.log. 

![image](https://user-images.githubusercontent.com/23668037/123472801-7ccf8c80-d5ac-11eb-9264-4c2dcef3a550.png)

**Comment by najoco** [comment]
In this session:

testabc456789ftp connection completed
test_fc9c6d34_ftp connection failed


[sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/6718311/sshd.log)

**Comment by bagajjal** [comment]
Are you doing scp / sftp? From logs, I see sshd authenticated process establishing sftp connection.


6012 2021-06-25 14:02:43.795 debug3: spawn_argv[0]: "c:\\windows\\system32\\cmd.exe" /c "sftp-server.exe"
6012 2021-06-25 14:02:43.795 debug3: spawning "c:\\windows\\system32\\cmd.exe" /c "sftp-server.exe" as subprocess
6012 2021-06-25 14:02:43.842 error: CreateProcessW failed error:5
6012 2021-06-25 14:02:43.842 error: posix_spawn: eother

**Comment by najoco** [comment]
I am attempting to connect just to sftp. In this test I am using the WINSCP client.  My config was included in my original post. Sorry I am new at OpenSSH

**Comment by najoco** [comment]
What has me confused the most is that the issue is intermittent. One moment the login works for an account and fails for another. a moment later it will be vice versa and later on no accounts will have issue.

**Comment by bagajjal** [comment]
Are you by any chance, using x86 win32-openssh binaries on x64 machines?

**Comment by najoco** [comment]
OpenSSH-Win64.zip. 
I originally installed from Server 19 feature and downloaded and overwrote EXEs from https://github.com/PowerShell/Win32-OpenSSH/releases/

**Comment by bagajjal** [comment]
What happens if you use the default sshd_config? please note any changes to sshd_config requires a restart to sshd process (net stop sshd; net start sshd).

If this also has a problem, then I will delete OpenSSH server optional feature, delete all the openssh releated binaries. Install it in a new location (ex- c:\program files\openssh\)

**Comment by najoco** [comment]
Done and same issue is occurring. 

Any known issues with using this on Azure servers?

**Comment by najoco** [comment]
I have decided to move the openssh server to a different server with less tasks/services running on it. I still see this error once in a while, but not close to the amount as with the prior server. Thank you for your assistance.
