### ISSUE TITLE
Set bash.exe as a user shell

### ISSUE THREAD

**Issue by Alexhha** [PowerShell/Win32-OpenSSH#183]
Hello, is it possible to specify bash.exe as a user shell? For e.g. I can use bash.exe with Bitvise ssh server

```
resin@dc1 MINGW32 ~
$ id
uid=1049689(resin) gid=1049089 groups=1049089

resin@dc1 MINGW32 ~
$ echo $SHELL
/usr/bin/bash
```

**Comment by manojampalam** [comment]
OpenSSH for Windows will not include a bash implementation on server side. You need to rely on third party bash for Win32.

**Comment by yakimant** [comment]
@manojampalam, how to run 3rd party bash as a default shell?

**Comment by gamma** [comment]
I tried using the ForceCommand, which works for my case, but then it has problems with the sftp subsystem using the same command instead of the specified subsystem command ...
