### ISSUE TITLE
run the SSH/SFTP server without installing the service, only running it via the command line

### ISSUE THREAD

**Issue by insinfo** [PowerShell/Win32-OpenSSH#1834]
How to run the SSH/SFTP server without installing the service, only running it via the command line

![image](https://user-images.githubusercontent.com/12227024/131256708-e5ec5c4b-5e41-4f35-9f0e-664bc3b6e6b8.png)

**"OpenSSH for Windows" version**
7.6.0.0
 
**Server OperatingSystem**
Windows 10 Pro
![image](https://user-images.githubusercontent.com/12227024/131256590-3acb448d-11d0-4a3c-9abc-873d84e83d65.png)

**Comment by bagajjal** [comment]
You can run sshd service in debug mode "sshd.exe -ddd" but this only authenticates the current user.
Is there a reason why you don't want to run as a service?

**Comment by insinfo** [comment]
I want to start SSH/SFTP from my application, I'm developing a server backup application via SFTP and I want my application to start SSH/SFTP only when copying files.

**Comment by bagajjal** [comment]
@insinfo - SSHD and SFTPserver should run as a service to accept all incoming users. If sshd server runs as a on demand application then it only accepts the incoming user under which the sshd application is started. 
This is out of scope of our project. You can try starting the sshd in the debug mode.
