### ISSUE TITLE
ssh-shellhost.exe not translating mouse events

### ISSUE THREAD

**Issue by willcassella** [PowerShell/Win32-OpenSSH#1835]
I noticed that when logging into a windows machine via SSH, mouse events are not passed through to child processes. This issue can be narrowed down to ssh-shellhost.exe not translating VT100 mouse events to Windows Console I/O mouse events.

Steps to reproduce:
1) Open a shell that speaks VT100 on stdout (such as WSL bash)
2) Launch a subprocess through ssh-shellhost: `ssh-shellhost.exe -c powershell` or `ssh-shellhost.exe -c wsl`
3) Attempt to use the mouse in any terminal application (Win32 or WSL) that supports it (such as neovim with `:set mouse=a`)

Steps to reproduce on Windows SSH server:
1) ssh into a windows machine (ie: `ssh localhost`)
2) Attempt to use the mouse in any terminal application (Win32 or WSL) that supports it (such as neovim with `:set mouse=a`)

I may have gotten some of the VT100<->Win32 Console IO directionality or terminology mixed up, but either way this doesn't seem to be working.

**Comment by willcassella** [comment]
Ok gotcha. Even without invoking `ssh-shellhost` though, I'm still hitting the issue where mouse events aren't received by terminal apps when ssh'ing to a Windows host (such as in the `ssh localhost` example, or ssh'ing from a Linux or macOS client). I'm running the latest Windows 10 version Windows Update will give me, using the OpenSSH server provided by the settings app (8.1.0.1). 

Edition	Windows 10 Pro
Version	21H1
Installed on	‎10/‎12/‎2020
OS build	19043.1202
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by bagajjal** [comment]
It's working for me. 
I did ssh from windows machine (windows 10) to ubuntu VM. After SSH, I did vi to a file and set the ":set mouse=a". If process the mouse events i.e., I can scroll up / down.

**Comment by willcassella** [comment]
Use terminal mouse with Windows as the client (ie, running through ssh.exe) works fine for me as well. The issue I'm hitting is when Windows is the **host** (ie, running **sshd.exe**).

**Comment by bagajjal** [comment]
@DHowett - could you please have a look at it. This seems to be in the console.

**Comment by DHowett** [comment]
Sorry, I am not clear on how you are avoiding `ssh-shellhost`. What version is the OS running `sshd`, and how are you bypassing `ssh-shellhost`?

**Comment by willcassella** [comment]
I'm running the version I posted above (19043.1202). To clarify, by 'without invoking `ssh-shellhost`' I just meant not invoking it directly as in the first example (just doing whatver `sshd` decides to do by default).

**Comment by willcassella** [comment]
I just updated my computer to Windows 11 (version 21H2, build 22000.124, sshd version 8.1.0.1) and this no longer appears to be an issue.

**Comment by bagajjal** [comment]
Thanks for the update. closing the issue.
