### ISSUE TITLE
Fix*FilePermissions.ps1 appear to have been drop from the release

### ISSUE THREAD

**Issue by joshudson** [PowerShell/Win32-OpenSSH#1836]
**Troubleshooting steps**

https://github.com/PowerShell/Win32-OpenSSH/wiki/OpenSSH-utility-scripts-to-fix-file-permissions

but they're not there.

````
C:\>dir fix*.ps1 /s

File Not Found

C:\>dir opensshutils.ps?1 /s

File Not Found

C:\>
````

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`: 8.1.0.1
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`: Windows Server 2022 Datacenter

**Client OperatingSystem**: NA

**What is failing**

FixUserFilePermissions.ps1 .ssh

**Expected output**

(no output expected)

**Actual output**

````
PS C:\Users\CedaronAdmin> fixuserfilepermissions.ps1 .ssh
fixuserfilepermissions.ps1 : The term 'fixuserfilepermissions.ps1' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ fixuserfilepermissions.ps1 .ssh
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (fixuserfilepermissions.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
````

**Comment by bagajjal** [comment]
This utility is shipped as part of the github release.
https://github.com/PowerShell/Win32-OpenSSH/releases/download/V8.6.0.0p1-Beta/OpenSSH-Win64.zip
