### ISSUE TITLE
Windows 11 machine has 8.1.0.1 (which doesn't exist as a tag in this repo?)

### ISSUE THREAD

**Issue by colemickens** [PowerShell/Win32-OpenSSH#1837]
I feel like I've always been confused about how OpenSSH is tagged/released for Windows. I assume that has to do with how Windows is shipped, etc.

However, I do sort of expect to be able to find corresponding tags/source for the OpenSSH builds that I find coming pre-installed in Windows, even in beta releases.

I'm on winver `Win11 Pro 21H2 OS Build 22000.184` and I have version `8.1.0.1` in `C:\Windows\system32\OpenSSH` right now, and as mentioned, don't see a tag for that release in this repo.

Can the release/ship process be documented? Can we get tags or source drops that correspond to builds that are shipping to users via Windows builds?

Actually... to further the confusion, this repo has a readme saying that releases are done in `openssh-portable`, but yet the verified releases still seem to be being done here?

**Comment by panekj** [comment]
https://github.com/PowerShell/Win32-OpenSSH/issues/1693#issuecomment-793320270

> Windows binaries have a different tag from the Github release tag for the below reasons,
> 
> 1. We maintain a different repo internally for servicing. Any security bugs will be fixed in the internal repo and will go through windows update. Once the windows update is rolled out, the security fixes will be part of our next GitHub release.
> 2. We first release on Github to seek feedback from the community. We wait for at least a couple of months before we take the Github release to windows. This may contain minor changes like any regressions, security bugs. In most cases, the code commit is the same for windows release, Github releases. Just that the release tags are different.
>       Having different tags between windows and GitHub helps us to better understand, reproduce the bug from the specific repo branch.


> Actually... to further the confusion, this repo has a readme saying that releases are done in `openssh-portable`, but yet the verified releases still seem to be being done here?

It says that development is done in `openssh-portable`.

**Comment by bagajjal** [comment]
Thanks @panekj for referring the right comment.
Closing this as it's already addressed

**Comment by colemickens** [comment]
Yes, thanks all! I appreciate the detailed answer.

**Comment by ecki** [comment]
I can see why you have different Repos and tags, but I don’t see why you not eventually push all released tags to the public Repo with a unique tag which allows people to see the code which is active on their machines
