### ISSUE TITLE
SSHD (8.6.0.0) Domain joined Windows Server 2019 "invalid user"

### ISSUE THREAD

**Issue by Stormrice** [PowerShell/Win32-OpenSSH#1838]
**"OpenSSH Server for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
8.6.0.0 Win64

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows Server 2019 Standard

**"OpenSSH Client for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
8.1.0.1

**Client OperatingSystem**
Windows 10 Pro

**Client SSH Commands**
`sftp -i .\.ssh\****_ed25519_ssh_key_windows sftp@192.168.1.12`
`sftp -i .\.ssh\****_ed25519_ssh_key_windows sftp@192.168.1.22`

**What is failing**
I have one SSH **non**-domain joined client (that I name external client).
I have one Active Directory server running Windows server 2019 Standard on a VirtualBox virtual machine (192.168.1.32).
I have 2 SSHD **domain** joined physical servers running Windows Server 2019 Standard (with official licenses):
1. srv12 = 192.168.1.12 (I cannot connect)
2. srv22 = 192.168.1.22 (I can connect)

The Windows servers (AD + 2 SSHD) are being rebooted every day, as they are in testing mode, not in production mode yet.

I try to connect from my external client to the local **sftp** account on each SSHD servers.
1. SFTP account SID on srv12 = S-1-5-21-2****
2. SFTP account SID on srv22 = S-1-5-21-1****

Despite having the same **sshd_config** configuration, I can connect to only one of the SSHD servers (srv22), but not the other (srv12).

From the logs, I understand that Windows fail to recognize my user **sftp** because it prefixes it with srv12\ (the name of the computer).
So, instead of trying to connect the **sftp** user, it tries to connect srv12\sftp, which is not allowed in the sshd_config.

**Sometimes, after I manually restart OpenSSH service on srv12, I can connect until I restart it again, in that case, the system does not prefixes the account name with srv12\.**

**If I add srv12\sftp in the AllowUser parameter of sshd_config, I have the **lsalogon() token** error.**

**If I add srv22\sftp to the AllowUser parameter of sshd_config of the srv22 server, it fails to recognize the user, without triggering the lsalogon() token error.**

**I can add that srv12 was the AD Domain Controller before I created the virtual machine. So I have installed and configured the ADDC role on srv12, before uninstalled it to deploy the DC on the VM. Maybe the DC role has broken the accounts.**

**Expected output**
Connecting to both SSHD.

**Actual output**
Can only connect reliably to srv22.

**Log files**
[external_client_to_srv12_fail.txt](https://github.com/PowerShell/Win32-OpenSSH/files/7163814/external_client_to_srv12_fail.txt)
[external_client_to_srv12_success.txt](https://github.com/PowerShell/Win32-OpenSSH/files/7163815/external_client_to_srv12_success.txt)
[external_client_to_srv22_success.txt](https://github.com/PowerShell/Win32-OpenSSH/files/7163816/external_client_to_srv22_success.txt)
[srv12_fail.txt](https://github.com/PowerShell/Win32-OpenSSH/files/7163817/srv12_fail.txt)
[srv12_success.txt](https://github.com/PowerShell/Win32-OpenSSH/files/7163818/srv12_success.txt)
[srv22_success.txt](https://github.com/PowerShell/Win32-OpenSSH/files/7163819/srv22_success.txt)

**Configuration files**
[sshd_config_srv12.txt](https://github.com/PowerShell/Win32-OpenSSH/files/7163821/sshd_config_srv12.txt)
[sshd_config_srv22.txt](https://github.com/PowerShell/Win32-OpenSSH/files/7163822/sshd_config_srv22.txt)

Thank you for your time :)

**Comment by mgkuhn** [comment]
Wild guess: is it possible that you have ended up with (some memory of) two users called “sftp”, e.g. one local user, and one in the domain, and therefore something thinks it has to prefix the NetBIOS name before the username to disambiguate between the two users?

**Comment by Stormrice** [comment]
Thanks mgkuhn !

I don't know how to check if there are any remains of information that are causing this account misinterpretation.

However, my servers have now joined the production domain, and the error seems to have disappeared.

I tested with a non-domain joined computer and the SFTP connection works for both servers.
