### ISSUE TITLE
This same issue is occurring for me my port 22 stays open and my new port 5901 stays closed

### ISSUE THREAD

**Issue by Infonesii** [PowerShell/Win32-OpenSSH#1839]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**

**What is failing**

**Expected output**

**Actual output**

**Comment by mgkuhn** [comment]
“The same issue” as what? Please describe in detail the steps that someone needs to go through to reproduce your problem. How exactly did you attempt to specify the port number? Copy and paste or attach the exact command lines and/or config file used here. Give exact versions of the operating system and OpenSSH that you used (there are lots!).
