### ISSUE TITLE
Setting up passwordless Kerberos auth from Windows ssh client to Windows ssh server

### ISSUE THREAD

**Issue by mike3085** [PowerShell/Win32-OpenSSH#1843]
**"OpenSSH for Windows" version**
8.1.0.1
 
**Server OperatingSystem**
Windows 10 Pro, 2012 R2, 2016, 2019

**Client OperatingSystem**
Windows 10 Pro

Hello, currently in our environment we use publickey with Active Directory user accounts for authentication. The ssh clients and servers are both Windows based. I am looking at switching to Kerberos, GSSAPI, or NTLM for Active Directory authentication that is passwordless to move away from publickey auth but am a little stuck on where to start. Thank you.

**Comment by mgkuhn** [comment]
If both client and server are already joined to the same Active Directory domain, and both have OpenSSH 8.1 or newer running, I don't think anything else is needed than to add the line
```
GSSAPIAuthentication yes
```
to `%programdata%\ssh\sshd_config` on the server (and restart sshd so it rereads the file). (Note that *Windows Server 2019* and earlier don't ship with OpenSSH 8.1, so you'll have to install it from [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH) instead.)

On the client, either use option `ssh -K` or likewise add `GSSAPIAuthentication yes` and possibly also `GSSAPIDelegation yes` to your `ssh_config` (if you expect to be able to access other servers from the destination server; you may have to [trust the destination server](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/appv-v4/how-to-configure-the-server-to-be-trusted-for-delegation) for that in Active Directory if you want tickets delegated).

Check with `ssh -K -v` what is happening, if something doesn't work, and attach the output here.

**Comment by mike3085** [comment]
Thanks @mgkuhn that worked perfectly.
