### ISSUE TITLE
From my local macOS machine how to remotely execute a PowerShell Script present on my local machine when the scripts requires arguments?

### ISSUE THREAD

**Issue by umapriyadarsi** [PowerShell/Win32-OpenSSH#1844]
**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
On the remote Windows machine the OpenSSH version is 8.6.0.0
<img width="590" alt="image" src="https://user-images.githubusercontent.com/3054787/135722422-9303d1da-a525-4301-8084-e2f0847064ad.png">
 
**Server OperatingSystem**
I am running macOS Big Sur 11.6 on M1 Macbook.

**Client OperatingSystem**
The client is running Windows 10 Pro.

**What is failing**
I have written a PowerShell Script which expects receiving argument values. This .ps1 script is present on my Mac(local machine). I am trying to execute it remotely on the Windows Machine. I am able to execute scripts which do not execute any arguments, or alternatively write the script in string and input the placeholder argument values with bash variables. However, what I am unable to do is send over the script along with arguments for remote execution. Any help would be appreciated.

**Expected output**
olo
HELO
BYE
lol

**Actual output**
<img width="979" alt="image" src="https://user-images.githubusercontent.com/3054787/135724204-172e3455-0871-420c-9832-a0cba4de8ce6.png">

olo

lol

**Comment by mgkuhn** [comment]
It seems you are sending the entire content of the file `test.ps1` to your server inside the ssh command line, where each line of this file will be executed as soon as it is parsed. You are then appending to the end of that ssh command line the value of your two arguments, which do not contain valid Powershell instructions, hence the error message. By the time Powershell received your two argument values, it has already finished executing all lines in your script.

There are several ways in which you can do what you want:

a) You could first copy your `test.ps1` script to a place where your server can read it, and then you send as the ssh commandline the path with the location of that script, such that Powershell loads and executes the script file. You can either user `scp` to copy the file over, or, if you have a file server, you can copy the script file to a share that both your client and your server can access. If you then call that script via its pathname on the server (i.e., without `($cat ...)`) then you can append your arguments as you had intended, and the arguments will be passed on to the script.

b) You could also prefix the content of your script with variable assignments, e.g. something along the lines of
```
ssh Admin@10.51.79.127 $(echo argtwo='$ARG_TWO') $(cat ...)
```
But generally, I think a) is a much cleaner and more standard solution. I would consider b) a bit of a _hack_.

**Comment by umapriyadarsi** [comment]
Thanks @mgkuhn . I went with this approach rather:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/3054787/135954323-65f96adc-acc9-4178-a221-c4ef9ea85e5b.png">

I think we can close this issue with this, and am doing the same.
