### ISSUE TITLE
SSH permission denied : Invalid User requesting public key Error

### ISSUE THREAD

**Issue by sapienza88** [PowerShell/Win32-OpenSSH#1848]
I am trying to connect via `ssh` to a machine. I set everything as described here on both machines : `http://woshub.com/using-ssh-key-based-authentication-on-windows/` and i get 

> permission denied public key

 Error then on the server (the distant machine) i get this log :

    4480 2021-10-18 09:48:24.620 debug3: checking match for 'Group administrators' user VM1 host *.*.*.220 addr *.*.*.220 laddr *.*.*.221 lport 22
    4480 2021-10-18 09:48:24.620 debug3: lookup_sid: local user name is same as machine name
    4480 2021-10-18 09:48:24.620 debug1: get_passwd: lookup_sid() failed: 1332.
    4480 2021-10-18 09:48:24.620 debug1: Can't match group at line 90 because user VM1 does not exist
    4480 2021-10-18 09:48:24.620 debug3: match not found
    4480 2021-10-18 09:48:24.620 Invalid user VM1 from *.*.*.220 port 62542
    4480 2021-10-18 09:48:24.620 debug3: mm_answer_pwnamallow: sending MONITOR_ANS_PWNAM: 0
    4480 2021-10-18 09:48:24.620 debug3: mm_request_send: entering, type 9
    4480 2021-10-18 09:48:24.620 debug2: monitor_read: 8 used once, disabling now
    4480 2021-10-18 09:48:24.620 debug3: mm_inform_authserv: entering [preauth]
    4480 2021-10-18 09:48:24.620 debug3: mm_request_send: entering, type 4 [preauth]
    4480 2021-10-18 09:48:24.620 debug2: input_userauth_request: try method none [preauth]
    4480 2021-10-18 09:48:24.620 debug3: mm_request_receive: entering
    4480 2021-10-18 09:48:24.620 debug3: monitor_read: checking request 4
    4480 2021-10-18 09:48:24.620 debug3: mm_answer_authserv: service=ssh-connection, style=
    4480 2021-10-18 09:48:24.620 debug2: monitor_read: 4 used once, disabling now
    4480 2021-10-18 09:48:24.620 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
    4480 2021-10-18 09:48:24.620 debug3: ensure_minimum_time_since: elapsed 0.000ms, delaying 6.939ms (requested 6.939ms) [preauth]
    4480 2021-10-18 09:48:24.636 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
    4480 2021-10-18 09:48:24.636 debug3: send packet: type 51 [preauth]
    4480 2021-10-18 09:48:24.636 debug3: receive packet: type 50 [preauth]
    4480 2021-10-18 09:48:24.636 debug1: userauth-request for user VM1 service ssh-connection method publickey [preauth]
    4480 2021-10-18 09:48:24.636 debug1: attempt 1 failures 0 [preauth]
    4480 2021-10-18 09:48:24.636 debug2: input_userauth_request: try method publickey [preauth]
    4480 2021-10-18 09:48:24.636 debug2: userauth_pubkey: invalid user VM1 querying public key rsa-sha2-512 AAAAB3NzaC1ycNW+Vtf+SwP/zwg2M2Y1XocnRQu/zdhzBjnPfDKM/PRV4GTb1gsL7cJs/a/jW/QvIDxM4dtMe11t5O8jKc9TUQo509U9BQ8ulCUGe8tAuP+3WKKOzTuVhSeGy6IWfk7Z3OXJaEEL0GKaUpHJY+8MtukImmJ2w0UwknhYu7aP4U4AoqlBNR0gv/HynUoROB7fzgFQkUX6c6fBZ3UgCFCTl7QxmjMnNPsQbBedN00lm4lqVjQCvQY4VCI27ZHpYTz1Rdvm7CXBVatZ6n/irVsHNvDuULQcv63 [preauth]
    4480 2021-10-18 09:48:24.636 debug1: userauth_pubkey: test pkalg rsa-sha2-512 pkblob RSA SHA256:53qr1ydq/iMCtOIpHteK5c [preauth]
    4480 2021-10-18 09:48:24.636 debug2: userauth_pubkey: disabled because of invalid user [preauth]
    4480 2021-10-18 09:48:24.636 debug2: userauth_pubkey: authenticated 0 pkalg rsa-sha2-512 [preauth]
    4480 2021-10-18 09:48:24.636 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
    4480 2021-10-18 09:48:24.636 debug3: ensure_minimum_time_since: elapsed 0.000ms, delaying 6.939ms (requested 6.939ms) [preauth]
    4480 2021-10-18 09:48:24.652 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
    4480 2021-10-18 09:48:24.652 debug3: send packet: type 51 [preauth]
    4480 2021-10-18 09:48:24.652 debug3: receive packet: type 50 [preauth]
    4480 2021-10-18 09:48:24.652 debug1: userauth-request for user VM1 service ssh-connection method keyboard-interactive [preauth]
    4480 2021-10-18 09:48:24.652 debug1: attempt 2 failures 1 [preauth]
    4480 2021-10-18 09:48:24.652 debug2: input_userauth_request: try method keyboard-interactive [preauth]
    4480 2021-10-18 09:48:24.652 debug1: keyboard-interactive devs  [preauth]
    4480 2021-10-18 09:48:24.652 debug1: auth2_challenge: user=VM1 devs= [preauth]
    4480 2021-10-18 09:48:24.652 debug1: kbdint_alloc: devices '' [preauth]
    4480 2021-10-18 09:48:24.652 debug2: auth2_challenge_start: devices  [preauth]
    4480 2021-10-18 09:48:24.652 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
    4480 2021-10-18 09:48:24.652 debug3: ensure_minimum_time_since: elapsed 0.000ms, delaying 6.939ms (requested 6.939ms) [preauth]
    4480 2021-10-18 09:48:24.667 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
    4480 2021-10-18 09:48:24.667 debug3: send packet: type 51 [preauth]
    4480 2021-10-18 09:48:31.296 debug3: receive packet: type 50 [preauth]
    4480 2021-10-18 09:48:31.296 debug1: userauth-request for user VM1 service ssh-connection method password [preauth]
    4480 2021-10-18 09:48:31.296 debug1: attempt 3 failures 2 [preauth]
    4480 2021-10-18 09:48:31.296 debug2: input_userauth_request: try method password [preauth]
    4480 2021-10-18 09:48:31.296 debug3: mm_auth_password: entering [preauth]
    4480 2021-10-18 09:48:31.296 debug3: mm_request_send: entering, type 12 [preauth]
    4480 2021-10-18 09:48:31.296 debug3: mm_auth_password: waiting for MONITOR_ANS_AUTHPASSWORD [preauth]
    4480 2021-10-18 09:48:31.296 debug3: mm_request_receive_expect: entering, type 13 [preauth]
    4480 2021-10-18 09:48:31.296 debug3: mm_request_receive: entering [preauth]
    4480 2021-10-18 09:48:31.296 debug3: mm_request_receive: entering
    4480 2021-10-18 09:48:31.296 debug3: monitor_read: checking request 12
    4480 2021-10-18 09:48:31.296 debug1: Windows authentication failed for user: NOUSER domain: . error: 1326
    4480 2021-10-18 09:48:31.296 debug3: mm_answer_authpassword: sending result 0
    4480 2021-10-18 09:48:31.296 debug3: mm_answer_authpassword: sending result 0
    4480 2021-10-18 09:48:31.296 debug3: mm_request_send: entering, type 13
    4480 2021-10-18 09:48:31.296 Failed password for invalid user VM1 from *.*.*.220 port 62542 ssh2
    4480 2021-10-18 09:48:31.296 debug3: mm_auth_password: user not authenticated [preauth]
    4480 2021-10-18 09:48:31.296 debug3: user_specific_delay: user specific delay 0.000ms [preauth]
    4480 2021-10-18 09:48:31.296 debug3: ensure_minimum_time_since: elapsed 0.000ms, delaying 6.939ms (requested 6.939ms) [preauth]
    4480 2021-10-18 09:48:31.311 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
    4480 2021-10-18 09:48:31.311 debug3: send packet: type 51 [preauth]
    4480 2021-10-18 09:50:24.572 fatal: Timeout before authentication for *.*.*.220 port 62542

Could someone help understand how to fix this ?

**Comment by mgkuhn** [comment]
`user VM1 does not exist` sounds like a strong clue

Do the user `VM1` and the file `C:\Users\VM1\.ssh\authorized_keys` really exist on the server, and what are the permissions of the latter?

**Comment by sapienza88** [comment]
Yes VM1 and the file are there

**Comment by bagajjal** [comment]
Might be related to https://github.com/PowerShell/Win32-OpenSSH/issues/1787.
