### ISSUE TITLE
terminal not working using sshd

### ISSUE THREAD

**Issue by covici** [PowerShell/Win32-OpenSSH#187]
I was trying to ssh into my windows box using the sshd I installed from this repository.  The terminal type is Linux and neither backspace nor arrow keys work once I have logged in.

**Comment by alexchandel** [comment]
I can confirm the same from OSX's terminal.

The arrow keys are disabled for some reason, but the loss of backspace is a **regression**. In 3_19_2016, while the screen wasn't updated to reflect it, pressing the backspace key would remove characters from the buffer. In 4_5_2016, not even this happens anymore.

**Comment by alexchandel** [comment]
Is is a possible dupe of #159.

**Comment by manojampalam** [comment]
dup #122
