### ISSUE TITLE
Add DefaultShellOptions registry key for session shell options.

### ISSUE THREAD

**Issue by rkitover** [PowerShell/Win32-OpenSSH#1871]
**"OpenSSH for Windows" version**
8.0.0.0
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Windows 10 Pro

It would be nice to support passing options to the shell executable for sessions and not just commands.

I use PowerShell and I would like to be able to start sessions with `-NoLogo`.

**Comment by mgkuhn** [comment]
Have you considered using the `command="..."` attribute in `authorized_keys` to achieve this? You can override there the commend-line used to start the shell, individually for each public key.

(Otherwise, I can't think of any existing field in the SSH2 protocol that could be used to implement your feature request.)

**Comment by rkitover** [comment]
This would disable my ability to execute arbitrary commands using:

```powershell
ssh <host> <command>
```

, when I just want to change the options for starting a login shell.

As you can see here:

https://github.com/PowerShell/Win32-OpenSSH/wiki/DefaultShell

this is configured through the registry keys `DefaultShell`, `DefaultShellCommandOption` and `DefaultShellEscapeArguments` so I don't see any issue with adding another registry key for options to `DefaultShell` or perhaps allowing `DefaultShell` to be a full command with arguments instead of just an executable.

**Comment by bagajjal** [comment]
Please refer to https://github.com/PowerShell/Win32-OpenSSH/issues/1800. It's part of V8.6

**Comment by rkitover** [comment]
Awesome, thank you.
