### ISSUE TITLE
SSH Breaks Control-C When Interrupted

### ISSUE THREAD

**Issue by xobs** [PowerShell/Win32-OpenSSH#1874]
**Background**
When `ssh` is interrupted it does something that breaks Control-C for the console. For example, if a user presses Control-C to abort password entry, or to interrupt connecting to a server with an unfamiliar SSH key, then Control-C will not work with subsequent programs.

A common example is `ping -t`, which will become unkillable in this case.

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command ssh).Source).VersionInfo.FileVersion)`: 8.1.0.1
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`: Windows 10 Pro

**Client OperatingSystem**
 Any

**What is failing**
 If Control-C is pressed during an SSH session, then it will never work again. For example, `ping -t` will not be able to be interrupted.

**Expected output**
 SSH should not break Control-C
```
[18:33:37] ~> ping -t 1.1.1.1

Pinging 1.1.1.1 with 32 bytes of data:
Reply from 1.1.1.1: bytes=32 time=2ms TTL=59

Ping statistics for 1.1.1.1:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 2ms, Maximum = 2ms, Average = 2ms
Control-C
[18:36:47] ~>
```

**Actual output**
 SSH breaks Control-C
```
[18:36:47] ~> ssh user@10.0.237.4
The authenticity of host '10.0.237.4 (10.0.237.4)' can't be established.
ECDSA key fingerprint is SHA256:/XZLbehLeTwk7imZenonphXQJlA+6LSVqDYhGuKJPow.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
[18:37:10] ~># Control-C was pressed above
[18:37:13] ~> ping -t 1.1.1.1

Pinging 1.1.1.1 with 32 bytes of data:
Reply from 1.1.1.1: bytes=32 time=2ms TTL=59
Reply from 1.1.1.1: bytes=32 time=2ms TTL=59
Reply from 1.1.1.1: bytes=32 time=2ms TTL=59
# Note: the above command cannot be terminated, and will continue until the window is closed
```

This was reported in https://github.com/microsoft/terminal/issues/6001 but does not appear to have been reported here.

**Comment by bagajjal** [comment]
@xobs I couldn't repro this. Which terminal are you using cmd.exe / powershell.exe / WSL? I see you only mentioned server operating system (which is not useful for this scenario). We need the client operating system where you are performing these operations.

**Comment by xobs** [comment]
I'm using Windows 21H2 (OS Build 22000.376) with either PowerShell 7.2.1 or PowerShell 5.1.22000.282 and Windows Terminal 1.11.3471.0.

I can't reproduce it using `cmd.exe` when using Windows Terminal, and I'm unable to powershell with anything other than Windows Terminal at this point.

**Comment by bagajjal** [comment]
@xobs - Let's skip the use of windows terminal to launch the cmd.exe / powershell.exe for a moment. 

Are you seeing this behavior on a pure cmd.exe / powershell.exe terminal?

**Comment by xobs** [comment]
On one of my machines, running `powershell.exe` launches Windows Terminal.

On another machine (Windows 21H2 OS Build 19044.1415), cmd.exe works fine but powershell.exe fails:
![image](https://user-images.githubusercontent.com/238325/148872616-923f4bea-2baa-4818-b730-6efa66c0aa2d.png)

**Comment by phil-blain** [comment]
At first glance this looks like a duplicate of #1699, no ?

**Comment by xobs** [comment]
It does appear to be a duplicate. I've added a link to the Windows Terminal issue, and I'll close this one. Thanks for finding that!
