### ISSUE TITLE
RFD: opening GUI apps on local machine?

### ISSUE THREAD

**Issue by rkitover** [PowerShell/Win32-OpenSSH#1879]
**"OpenSSH for Windows" version**
 8.0.0.0

**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Windows 10 Pro

I am using `ssh localhost` and `ssh localhost <command>` as a handy sudo replacement in PowerShell because Windows ssh gives you elevated access.

This works relatively well for some things, with some minor annoyances like #1870 .

Here is my `$profile` function btw:

```powershell
function sudo {
    ssh localhost "sl $(pwd); $($args -join " ")"
}
```

Another thing that does not work is opening GUI apps. I remember vaguely that Windows used to have some feature where services could "interact with the desktop" that may no longer exist, etc..

Does anyone have any ideas about this? Is this possible at all?

**Comment by bagajjal** [comment]
You can't run the GUI applications over the SSH. 
Refer to https://github.com/PowerShell/Win32-OpenSSH/issues/1610

**Comment by rkitover** [comment]
I'm asking about something different though, I do not expect GUI applications to run over ssh on another system.

I am connecting to the same machine via localhost, and if the ssh service has some kind of desktop interaction token it should be possible for it to open GUI applications on the desktop on the same machine.

**Comment by bagajjal** [comment]
@rkitover - SSH sever process run in session 0. The processes in session 0 can't launch GUI applications.
