### ISSUE TITLE
Using filezilla and cyberduck to access windows server 2019 with openssh SFTP with key file  

### ISSUE THREAD

**Issue by seed2eve** [PowerShell/Win32-OpenSSH#1883]
Hello,

I wish to authenticate by using key file, ( by using filezilla or cyberduck, to select the private key), thus, in the sshd_config, I  required to set 

pubkeyauthentication yes

and also 

PasswordAuthentication yes 

The result is, user can authenticate it. it can authenticated by password  or by  key file.  

 But, if I "comment" #PasswordAuthentication yes , it wont get authenticate by just using key file. 

My First objective is to only allow key file to authenticate through filezilla or cyberduck ftp client. 
- to be exact, i wish to allow key file, then filezilla will prompt me a passphase i set at private key. 

Second objective, is by using key file and also password to authenticate together. For this, i checked from wiki, it require to set authenticationmethods " publickey,password" but i had tried and is not working. 

Hope that experts can advise on this. i'm new at this.

**Comment by bagajjal** [comment]
It shouldn't happen. Please provide the sshd server logs 

https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities

**Comment by seed2eve** [comment]
SSHD: Accepted password for charlie from 10.81.234.7 port 63160 ssh2 <---from log
authenticate through password but not key. 
 
pubkeyauthentication yes  , but i had comment out the PasswordAuthentication yes  <--from sshd_config, i had restart services when make changes. 

by right it should failed when i use password, am i right?

**Comment by seed2eve** [comment]
sshd: Connection closed by authentcating user alfred x.x.x.x port 64843[preauth] 
filezilla error: show server refused our key
public key i had put at c:\sftproot\user\.ssh  [inside is authorized_
pubkeyauthentication yes
 
comment out #PasswordAuthentication yes 

i dont understand this line, 
Match Group administrators 
    authorizedkeysfile_Programdata_/ssh/administrators_authorized_keys

should i place another public key here?

**Comment by bagajjal** [comment]
@seed2eve , 
You need to have "PasswordAuthentication no" in your sshd_config. The default value of PasswordAuthentication is "Yes". When you comment out, it will take the default value which is "Yes".

https://man.openbsd.org/sshd_config

The default sshd_config looks for the administrator users, authorized_keys file in $env:programdata\ssh\administrators_authorized_keys file. This is added to overcome a security issue.
