### ISSUE TITLE
OpenSSH Win32 port falling behind releases

### ISSUE THREAD

**Issue by user8446** [PowerShell/Win32-OpenSSH#1891]
Hello,

The Win32 port version is currently at v8.6 which is now two releases behind OpenSSH which is currently at v8.8. There are plenty of bugfixes and issues resolved: https://www.openssh.com/releasenotes.html

It appears maintaining this has stalled?

**Comment by bagajjal** [comment]
@user8446 - We are planning to do a Github release next month, Feb 2022. Working on few fixes from our side.

**Comment by user8446** [comment]
So great to hear!
Thank you very much for maintaining this!
