### ISSUE TITLE
sshd/sftp-server log rotation/delete

### ISSUE THREAD

**Issue by zvekan** [PowerShell/Win32-OpenSSH#1893]
I would ask/suggest to add sshd.log and sftp-server.log option to rotate logs on hourly,daily,weeky,monthly basis.
Also to add option to delete logs older then X days.

For now I have created little script and just run task daily

$DateFormat = "{0:yyyy-MM-dd-HH-mm-ss}" -f [DateTime]::Now
$sshdLOG = "sshd-" + $DateFormat + ".log"
$sftpLOG = "sftp-server-" + $DateFormat + ".log"

Copy-Item -Path C:\ProgramData\ssh\logs\sshd.log -Destination C:\ProgramData\ssh\logs\$sshdLOG
Copy-Item -Path C:\ProgramData\ssh\logs\sftp-server.log -Destination C:\ProgramData\ssh\logs\$sftpLOG

$null | Set-Content C:\ProgramData\ssh\logs\sshd.log
$null | Set-Content C:\ProgramData\ssh\logs\sftp-server.log

Get-ChildItem -recurse C:\ProgramData\ssh\logs -Filter sshd-*.log | Where-Object {$_.CreationTime -lt (Get-Date).AddDays(-30)} | remove-item
Get-ChildItem -recurse C:\ProgramData\ssh\logs -Filter sftp-server-*.log | Where-Object {$_.CreationTime -lt (Get-Date).AddDays(-30)} | remove-item

**Comment by bagajjal** [comment]
@zvekan  - ETW logging is our default logging. we suggest file based logging only for debugging.
We can't support this request for non-default behavior.
