### ISSUE TITLE
SCP -r fails to correctly copy with directory structures deeper than 8 levels

### ISSUE THREAD

**Issue by jameymorris** [PowerShell/Win32-OpenSSH#1897]
**"OpenSSH for Windows" version**
8.1.0.0
(8.6 also tested)
 
**Server OperatingSystem**
Windows 10 Enterprise

**Client OperatingSystem**
Windows 10 Enterprise

**What is failing**
SCP fails with a recursive copy with a directory structure greater than eight folders deep. Directories up to the 8th directory are created in the destination, but no directories deeper than the 8th directory are created. No files are copied at all.

C:\test\copy_test has a nested file structure:
`copy_test\test_file_0.txt`
`copy_test\level_1\test_file_1.txt`
`copy_test\level_1\level_2\test_file_2.txt`
`...`
`copy_test\level_1\level_2\level_3\level_4\level_5\level_6\level_7\level_8\test_file_8.txt`

Test command:
`scp -r C:\test\copy_test <computername>:C:\test\copy_test2`

This test succeeds with 7.9 and 8.0. It fails with 8.1 and 8.6. If I remove the directory level_8, the tests succeed in all versions.

**Expected output**
C:\test\copy_test2 contains an identical structure and test files.

**Actual output**
C:\test\copy_test2 contains no files and the directory structure stops at level_7.

**Comment by bagajjal** [comment]
@jameymorris  - can you check if it's working on *nix machines. AFAIK, we don't have any windows specific changes in this area.

**Comment by jameymorris** [comment]
Yes, I checked this on CentOS 7 with OpenSSH 7.4 and 8.1 and there was no issue there. The entire directory structure and files copied successfully.

**Comment by bagajjal** [comment]
@jameymorris, we are fixing this issue in our next release (Probably by end of Feb 2022).
Thanks for reporting the issue.
