### ISSUE TITLE
A CMD window pops up every time an SSH or SCP or SFTP connection is made

### ISSUE THREAD

**Issue by jintianxiayu** [PowerShell/Win32-OpenSSH#1898]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3`
 
**Server OperatingSystem**
 `win10 64`

**Client OperatingSystem**
 `win10 64`

**What is failing**
A CMD window pops up every time an SCP or SFTP connection is made

**Expected output**
No cmd window pops up;

**Actual output**
A cmd window pops up;

**Comment by jintianxiayu** [comment]
bye, switch to apache sshd

**Comment by bagajjal** [comment]
@jintianxiayu , This is a major issue, if it happens. We can't repro this issue. No one has informed this issue so far. 
Is the issue happening on the client machine or server machine?

**Comment by jintianxiayu** [comment]
> 
@bagajjal 
server machine;

the cmd window exists until data transform is over

**Comment by bagajjal** [comment]
@jintianxiayu , I'm not sure how it's possible as we create new processes in session 0 for which you can't see any windows.

**Comment by NoMoreFood** [comment]
@jintianxiayu Are you running the server in debug mode when you see this?

**Comment by sane4ektopz** [comment]
I can confirm. Latest version, 10.0.0.0p2-Preview. I'm running sshd.exe directly, "portable way", not as a service. Tried it as a user and as admin. SSH works fine.
With "Subsystem sftp internal-sftp" SFTP does not work at all, MobaXTerm shows empty SFTP browser, WinSCP says "Cannot initialize SFTP protocol. Is the host running a SFTP server?"
With "Subsystem sftp C:\path\to\sftp-server.exe" both of these clients work, but on the host side a blank cmd.exe window appears until the session is closed. Also every time SFTP client downloads or uploads files another blank window appears.
I think it shouldn't be like that.

**Comment by sane4ektopz** [comment]
@bagajjal

**Comment by tgauth** [comment]
> I'm running sshd.exe directly, "portable way", not as a service. Tried it as a user and as admin.

What do you mean by "portable way"? It sounds like you are running the ssh server in debug mode.

**Comment by sane4ektopz** [comment]
> in debug mode.

I don't know if it's a debug mode. My steps are:
- download OpenSSH-Win64.zip
- extract it somewhere like "C:\Users\User\Desktop\ssh\"
- configure sshd_config
- with powershell cd to that directory
- run .\sshd.exe -f .\sshd_config

Is that debug mode? I also tried to start it with Task Scheduler but no, problem is the same.

**Comment by tgauth** [comment]
> Is that debug mode? I also tried to start it with Task Scheduler but no, problem is the same.

Yes, it is. Here are the instructions for using the install script within OpenSSH-Win64.zip to setup the service: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by sane4ektopz** [comment]
> Yes, it is. Here are the instructions for using the install script within OpenSSH-Win64.zip to setup the service: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

Yea, I know about it. But in my case that's not what I need basically because of a lack of admin rights on my machine. So it turns out this weird behavior is normal behavior. Okay then, thank you!
