### ISSUE TITLE
SSH'ed into Ubuntu machine on Azure got "TERM environment variable not set" 

### ISSUE THREAD

**Issue by shanselman** [PowerShell/Win32-OpenSSH#19]
SSH'ed into Ubuntu machine on Azure got "TERM environment variable not set" when running top.

This works fine, of course, with other SSH clients. TERM is set to dumb right now. I exported TERM to xterm and it worked a little, but I can't ctrl-c out of top or htop, and htop has considerable visual corruption.

**Comment by jungle-boogie** [comment]
What's `sudo -v` do for you? It prints my password in plain text with xterm and/or dumb term.

**Comment by quamrulmina** [comment]
Fxied in new upcoming release. ssh.exe client now is much more function rick and should work better. The client has ANSI/Vt220 support and sets TERM to vt220. sudo showing password is also fixed as ssh client does not do local echo which it was to do before showing everything typed.

**Comment by shanselman** [comment]
Looking forward to it!

On Thu, Oct 29, 2015 at 3:33 PM, quamrulmina <notifications@github.com>
wrote:

> Fxied in new upcoming release. ssh.exe client now is much more function
> rick and should work better. The client has ANSI/Vt220 support and sets
> TERM to vt220. sudo showing password is also fixed as ssh client does not
> do local echo which it was to do before showing everything typed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerShell/Win32-OpenSSH/issues/19#issuecomment-152346457>
> .
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by manojampalam** [comment]
Try the latest release.
