### ISSUE TITLE
CHROOT for Windows - Restrict SFTP to specific folder does not work

### ISSUE THREAD

**Issue by dodyg** [PowerShell/Win32-OpenSSH#190]
When I logged in using user xxx, it allows access to the C: of the server. 

(Windows 2008 R2 Update 1 - 64 bit) - I am using release 4_5_2016

```
Match User xxx
    ChrootDirectory C/Web/xxx
    # Disable tunneling, authentication agent, TCP and X11 forwarding.
    PermitTunnel no
    AllowAgentForwarding no
    AllowTcpForwarding no
    X11Forwarding no
```

**Comment by jski** [comment]
Confirmed broken functionality.  Impossible as of now to restrict users to any specific folders in this release.  Product unusable as a result.

Have tried setting ChrootDirectory in application config as above, and also most methods of Windows redirection in user profiles.

**Comment by whereisaaron** [comment]
One way would to be to create a user with limited file system permissions... except unfortunately Windows ships with the 'Authenticated Users' group added to the 'Users' group, making it impossible to create a user with limited file system permissions (less than 'Users' has). You can remove 'Authenticated Users' from the 'Users' group, but since no one, including Microsoft, tests that way, it is unknowable how many things would break or subtly misbehave. But if you are building a fresh Windows instance, this could be one approach to try.

**Comment by manojampalam** [comment]
#140

**Comment by ZakThePotter** [comment]
So, how I can lock user in specified Directory?

**Comment by whereisaaron** [comment]
It seems like #140 and #190 have been closed without adding the missing path restriction feature.  An actual chroot jail if not required (or possible it seems), only the ability to restrict a sftp user's sftp transactions to a specific folder. Other Windows sftp servers simulate the path restriction within the sftp server. OpenSSH sftp module could be patched the same way.

Push it to some way-future milestone, but this is a core sftp feature that should be on the road map.

**Comment by manojampalam** [comment]
Adding this to backlog list.

**Comment by RobC-CTL** [comment]
Just wondering if there is any progress on this issue? Thanks

**Comment by manojampalam** [comment]
Not yet and this is still not in radar. chroot for Windows is a non-trivial feature and its kind of complicated to make it fool proof (since Windows natively doesn't provide this option).

**Comment by RobC-CTL** [comment]
Thanks for the update

**Comment by thomasmcneill** [comment]
I am only looking to changeroot for SFTP.  I do not think this would be a trivial problem for that particular application.

**Comment by whereisaaron** [comment]
Hi @manojampalam thanks for your work on OpenSSH, it is great to see.

I think we (users) understand than a 'real' chroot for ssh is in the too hard basket, since there is no OS support. However we are just looking for a simulated chroot that contains sftp users to a folder (by manipulation/validation of the file paths or a folder mount perhaps). Check out the Microsoft IIS FTP Server and the Bisvise SSH Server for Windows an implementations of folder isolation for sftp/FTP users. 

Maybe you could implement this with Windows folder mounts? Mount the target chroot folder as a no-drive-letter volume, and the restrict the sftp user to that volume?

For an sftp server this is pretty core functionality, and the reason we can't use the OpenSSH port right now for sftp.

**Comment by manojampalam** [comment]
@whereisaaron totally understand the limitation and thanks for the potential design options. Again, since chroot is not supported by Windows natively, it would require some effort to ensure a secure alternative. For ex. how to block indirect access to "outside" files through links.

**Comment by PrestonTaylor** [comment]
To be quite honest I'm not really sure what anyone could use OpenSSH on windows for outside of personal use without this feature. It's kind of a must have unfortunately. Even a half baked solution would be more secure than just leaving a deceiving config option that doesn't function.

**Comment by manojampalam** [comment]
#292 for other additional feedback.

**Comment by archiker** [comment]
Can't agree more - though limiting user access to specific directory is a luxury, the limitation to drive, eg., only to a non-system drive (eg., D:\) or mapped drive (eg., F:\ or G:\) would be much safer. 

Opening R/W to system drive is risky to any user.

**Comment by manojampalam** [comment]
FYI, we have changes in pipeline to support SFTP with chroot
https://github.com/PowerShell/openssh-portable/pull/308

**Comment by swills1** [comment]
Anyone get this working? Doesn't seem to be fixed.

```
Match User test
    ChrootDirectory C/test
    # Disable tunneling, authentication agent, TCP and X11 forwarding.
    PermitTunnel no
    AllowAgentForwarding no
    AllowTcpForwarding no
    X11Forwarding no
```

**Comment by swills1** [comment]
So this is fixed?

**Comment by manojampalam** [comment]
Yes, just tried this with v7.7.0.0, it works

Match User test
    ChrootDirectory c:\temp
    # Disable tunneling, authentication agent, TCP and X11 forwarding.
    PermitTunnel no
    AllowAgentForwarding no
    AllowTcpForwarding no
    X11Forwarding no

See https://github.com/PowerShell/Win32-OpenSSH/wiki/sshd_config for Windows specific rules

**Comment by proskilly** [comment]
I tried putting   ChrootDirectory c:\sshTest    into sshd_config  but when I log in with FileZilla i'm at /C:/Users/Administrator

Is there something I need to do to get it to read the latest config file, also I only had file sshd_config_default,   are you supposed to rename (or copy) that to sshd_config, I assume it ignore sshd_config_default, it's just there as a template/starting point?

**Comment by Diaskhan** [comment]
@manojampalam  could U describe all process.
And all enviroment that u setup !

On win10 64 with v7.7.2.0p1-Beta 64 bit

it shows this with (ChrootDirectory c/temp)
C:\WINDOWS\system32>sftp acer@localhost
acer@localhost's password:
Connection reset by ::1 port 22
Connection closed

or this with (ChrootDirectory c:\temp)

C:\WINDOWS\system32>sftp acer@localhost
acer@localhost's password:
Connection closed

**Comment by bagajjal** [comment]
@Diaskhan -
Please share you sshd_config, sshd.log (With Debug3 enabled) and sftp logs (sftp -vvv user@ip)

**Comment by Diaskhan** [comment]
```
# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey __PROGRAMDATA__/ssh/ssh_host_rsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_dsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ecdsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile	.ssh/authorized_keys

#AuthorizedPrincipalsFile none

# For this to work you will also need host keys in %programData%/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
PasswordAuthentication yes
#PermitEmptyPasswords no

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#PermitUserEnvironment no
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# override default of no subsystems
Subsystem	sftp	sftp-server.exe

# Example of overriding settings on a per-user basis

Match User acer
ChrootDirectory c:\temp
# Disable tunneling, authentication agent, TCP and X11 forwarding.
PermitTunnel no
AllowAgentForwarding no
AllowTcpForwarding no
X11Forwarding no

```

**Comment by Diaskhan** [comment]
and event logs
```
sshd: Accepted password for acer from ::1 port 50246 ssh2
sshd: User child is on pid 2140
sshd: Changed root directory to "c:\\temp"
sshd: Starting session: subsystem 'sftp' for acer from ::1 port 50246 id 0
sshd: Close session: user acer from ::1 port 50246 id 0
sshd: Read error from remote host ::1 port 50246: Unknown error
```

**Comment by Diaskhan** [comment]
thanks gues no help is needed.

Just install budu server
https://www.sftp.net/servers

**Comment by marcosmateom** [comment]
Hello, Just wondering if there is any progress on this issue? Thanks

**Comment by marcosmateom** [comment]
Just wondering if there is any progress on this issue? Thanks

**Comment by mika-n** [comment]
This works with OpenSSH-win64 8.1.x version, but you need to set following sshd_config options (by default in %PROGRAMDATA%\SSH\ folder location in Windows platform):

```
ForceCommand internal-sftp
Subsystem  sftp   sftp-server.exe -d "D:\MyDataRoot\"
ChrootDirectory D:\MyDataRoot

PermitTunnel no
AllowAgentForwarding no
AllowTcpForwarding no
X11Forwarding no
AllowUsers sftpuser
```
The key trick is to use ForceCommand, Subsystem with -d option and ChrootDirectory option. Other options are just additional "security tweaks" to limit exposed surface area. 

Of course in this example the SFTP login users (here only sftpuser named local computer user is allowed) should have read+write Windows permissions in D:\MyDataRoot folder. It should not have permissions in anywhere with sensitive data (especially should NOT have write permissions in SSH configuration and application folder).

If you want to use different SFTP root folders per user name then you can do it by using Match User configurations.

```
ForceCommand internal-sftp
Subsystem  sftp   sftp-server.exe -d "D:\MyDataRoot\"

Match User johndoe
ChrootDirectory D:\MyDataRoot\JohnDoe

Match User marydoe
ChrootDirectory D:\MyDataRoot\MaryDoe

PermitTunnel no
AllowAgentForwarding no
AllowTcpForwarding no
X11Forwarding no
AllowUsers johndoe marydoe
```

**Comment by Digiover** [comment]
@mika-n what if every user has his own "MyDataRoot" folder? Is there an equivalent for `msIIS-FTPRoot`, because that would be nice!

**Comment by mika-n** [comment]
> @mika-n what if every user has his own "MyDataRoot" folder? Is there an equivalent for `msIIS-FTPRoot`, because that would be nice!

OpenSSH config file has a "Match user <userNameGoesHere>" entry for defining user specific customizations. I think it can be used with ChrootDirectory command also. See the following post for an example.
https://github.com/PowerShell/Win32-OpenSSH/issues/190#issuecomment-391883883

It would be nice to have something like `"ChrootDirectory c:\MyDataRoot\%username%"` type of syntax to set the root directory "dynamically" based on username but I think OpenSSH cannot do it like this. However, matchUser config entry should work.

**Comment by adictn** [comment]
@mika-n 
I've struggled with this for the last 7 days.
Thank you!

I've tried a lot with many types of path syntaxes but ChrootDirectory was simply not working at all.
So, what I did and worked was just what you said:
```
ForceCommand internal-sftp
Match User username
ChrootDirectory f:\somefolder
```

I hope everyone finds this.

**Comment by anoale** [comment]
@mika-n 
Thanks dude. I suffered all evening and now I conquered it.
I completely cleared the config file C:\ProgramData\ssh\sshd_config and only pasted the following lines:

    ForceCommand internal-sftp
    Subsystem  sftp   sftp-server.exe -d "C:\SFTP\"
    ChrootDirectory C:\SFTP

    PermitTunnel no
    AllowAgentForwarding no
    AllowTcpForwarding no
    X11Forwarding no
    AllowGroups sftpusers


Now it works as I need it:
 - only SFTP (ssh access denied) for local windows group.

**Comment by mogan2055847** [comment]
ForceCommand internal-sftp
Match User username
ChrootDirectory f:\somefolder
===============================
this one works perfectly.

**Comment by strollo** [comment]
In my case was the position of lines:

It was required to have `Subsystem sftp	sftp-server.exe`  before the `Match User` rule like this


```
Subsystem	sftp	sftp-server.exe
Match User imagiclesftp
	ChrootDirectory "....."
```

**Comment by tvikram1258** [comment]
can we use symbolic links share folders. does it support in SFTP

**Comment by bitcjacobsen** [comment]
> This works with OpenSSH-win64 8.1.x version, but you need to set following sshd_config options (by default in %PROGRAMDATA%\SSH\ folder location in Windows platform):
> 
> ```
> ForceCommand internal-sftp
> Subsystem  sftp   sftp-server.exe -d "D:\MyDataRoot\"
> ChrootDirectory D:\MyDataRoot
> 
> PermitTunnel no
> AllowAgentForwarding no
> AllowTcpForwarding no
> X11Forwarding no
> AllowUsers sftpuser
> ```
> 
> The key trick is to use ForceCommand, Subsystem with -d option and ChrootDirectory option. Other options are just additional "security tweaks" to limit exposed surface area.
> 
> Of course in this example the SFTP login users (here only sftpuser named local computer user is allowed) should have read+write Windows permissions in D:\MyDataRoot folder. It should not have permissions in anywhere with sensitive data (especially should NOT have write permissions in SSH configuration and application folder).
> 
> If you want to use different SFTP root folders per user name then you can do it by using Match User configurations.
> 
> ```
> ForceCommand internal-sftp
> Subsystem  sftp   sftp-server.exe -d "D:\MyDataRoot\"
> 
> Match User johndoe
> ChrootDirectory D:\MyDataRoot\JohnDoe
> 
> Match User marydoe
> ChrootDirectory D:\MyDataRoot\MaryDoe
> 
> PermitTunnel no
> AllowAgentForwarding no
> AllowTcpForwarding no
> X11Forwarding no
> AllowUsers johndoe marydoe
> ```

I've tried using this. Here is my rules: 
```
ForceCommand internal-sftp

# no default banner path
#Banner none

# override default of no subsystems
Subsystem	sftp	sftp-server.exe	-d "D:\DataDir\"
ChrootDirectory D:\DataDir

PermitTunnel no 
AllowAgentForwarding no 
AllowTcpForwarding no
X11Forwarding no 
AllowUsers bridgehead

```
Filezilla gives: FATAL ERROR: Network error: Software caused connection abort
If I try to SFTP from an ubuntu box I get: client_loop: send disconnect: Broken pipe

If I comment out the chroot and -d parts I can SFTP in just fine. I'm using OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5 installed through optional features. Anyone else having this issue?

**Comment by Algvaldivia** [comment]
```
Hi everyone,
There is a "real" explained and not confusing way to grant access to only a specific folder for each specific user.
Can anyone show an example of a real a detailed configuration to do this, or it is impossible.
- Not One folder vs Many users. One folder, one user.

My configuration (fails at all) but I want to share it, expecting for someone who can show what's wrong? What we need to know to get that kind of restriction, that everybody wants but the most of us can't..

- For the sample I have 3 users and a group, named SFTP_Users, all the three users belong to this group.
- The main SFTP root folder is at C:\SFTP
- Each user have a child-folder inside : C:\SFTP\<username>
- Each user only has access to their folder
- But I do not want to show the content of the root folder, I want to show and provide access for each users to their folder (inside only)

The Open SSH Server main binaries files reside at : C:\Program Files\OpenSSH-Win64
The configuration file resides at : C:\ProgramData\ssh
The configuration settings that I added at the end of sshd_config is:
=======================================================
`# Forcing SFTP functionality, needed for ChrootDirectory parameter below
ChrootDirectory C:\SFTP\

# override default of no subsystems
Subsystem	sftp	internal-sftp

# allow to connect to OpenSSH only for users in this domain group
AllowGroups sftp_users

# enable password authentication (SSH keys cannot be used)
AuthenticationMethods password 

Match user ftpuser1
       ChrootDirectory C:\SFTP\ftpuser1

Match user ftpuser2
       ChrootDirectory C:\SFTP\ftpuser2

Match user ftpuser3
       ChrootDirectory C:\SFTP\ftpuser3

Match user ftpuser4
       ChrootDirectory C:\SFTP\ftpuser4

ForceCommand internal-sftp 
PermitTunnel no
AllowAgentForwarding no
AllowTcpForwarding no
X11Forwarding no
GatewayPorts no
PermitTTY no`

==================== END OF THE FILE =========================

My configuration do not return any good behavior or results, I'm tired to seek ideas across all of the threads and to make changes without any evolution or results.

If someone who really have a similar situation and his configuration is working as expected and consider sharing it with us, 
Please, are welcome.

Thanks.
```

**Comment by mika-n** [comment]
@Algvaldivia Try these settings and in this order and make sure you have created local Windows accounts named ftpuser1/ftpuser2/ftpuser3/ftpuser4. And optionally you can tweak folder level permissions in Windows folder settings per user to make sure those local accounts don't have read-write permission anywhere they don't need it:

# Forcing SFTP functionality, needed for ChrootDirectory parameter below

ForceCommand internal-sftp
Subsystem  sftp   sftp-server.exe -d "C:\SFTP\"

Match user ftpuser1
       ChrootDirectory C:\SFTP\ftpuser1

Match user ftpuser2
       ChrootDirectory C:\SFTP\ftpuser2

Match user ftpuser3
       ChrootDirectory C:\SFTP\ftpuser3

Match user ftpuser4
       ChrootDirectory C:\SFTP\ftpuser4

AuthenticationMethods password 
AllowUsers ftpuser1 ftpuser2 ftpuser3 ftpuser4

PermitTunnel no
AllowAgentForwarding no
AllowTcpForwarding no
X11Forwarding no
GatewayPorts no
PermitTTY no

**Comment by Algvaldivia** [comment]
@mika-n 
Thanks for your answer.

I will try with your instructions, comments later. 😁

**Comment by Algvaldivia** [comment]
@mika-n
That's the behavior after the changes:
![image](https://user-images.githubusercontent.com/53494547/140586463-c094f7fd-31ae-404a-9403-4d3e4d0c296c.png
![Returns-Listing-C-Users](https://user-images.githubusercontent.com/53494547/140586572-f0a50dc5-d4da-4614-a863-16257e75d9b6.png))
More than that ftpuser1 also has access to all drive C:..

So, I did this change:
Put a: ChrootDirectory C:\SFTP\ before than ForceCommand internal-sftp...

ChrootDirectory C:\SFTP\
ForceCommand internal-sftp
Subsystem sftp sftp-server.exe -d "C:\SFTP"

Now,
FileZilla just list directory folder \SFTP\ and their content..
![Returns-Listing-C-Users-2](https://user-images.githubusercontent.com/53494547/140587282-59c099ba-2612-48b0-abde-8634274138dc.png)

But, still not the desire state,
It should only list the content inside of \SFTP\ftpuser1...not around else...
Although ftpuser1 only have access to the ftpuser1 folder, can not enter to the other, the command 'ChrootDirectory C:\SFTP\ftpuser1' have not effect.

**Comment by mika-n** [comment]
Maybe trying something like this:

Match user ftpuser1
ChrootDirectory C:\SFTP\ftpuser4
ForceCommand internal-sftp

Match user ftpuser2
ChrootDirectory C:\SFTP\ftpuser2
ForceCommand internal-sftp

And make sure you have the latest OpenSSH for Windows version because some older releases don't support user-specific chrooting.

**Comment by Algvaldivia** [comment]
Hi, @mika-n 
I did..but still:
Status:	Retrieving directory listing...
Status:	Listing directory /
Status:	Directory listing of "/" successful

|  And make sure you have the latest OpenSSH for Windows version because some older releases don't support 
| user-specific chrooting.
Using SSH-2.0-OpenSSH_for_Windows_8.6

![OpenSSH-versioning](https://user-images.githubusercontent.com/53494547/140613650-8ce79b11-1ee6-429d-8084-89a0ccd0812c.png)

The SFTP Root Folder permission are:
![SFTP_RootFolder_Permissions](https://user-images.githubusercontent.com/53494547/140613719-6efb0d96-0d04-4479-beef-5812c9f2c334.png)
If I deny the List folder permission to the SFTP_Users group then no-body can access their folders:

And one of the ftpuser's are:
![FTPUser1_Permission_Folder](https://user-images.githubusercontent.com/53494547/140613797-af316f14-d44e-4ede-8627-f6203d52dad2.png)

**Comment by dagronslayer** [comment]
I am writing to confirm Algvaldivia's experience, with one exception:

The first 'Match User' statement in my sshd_config works. IE, the ChrootDirectory works. All the subsequent entries will ignore ChrootDirectory and use C:\Users\<Username>

I can actually change the order in sshd_config and the first statement is always the only one that works.

**Comment by dagronslayer** [comment]
After more testing, the problem is worse than noted above. 50% it gives me a chroot home, 50% of the time it gives me a C:\Users\ home
If I delete the C:\Users directory, it creates a new one.
![Screen Shot 2021-11-23 at 9 47 37 AM](https://user-images.githubusercontent.com/74074460/143069264-8c8b2813-f0d5-47c1-b216-c543109ac571.png)

**Comment by Algvaldivia** [comment]
> After more testing, the problem is worse than noted above. 50% it gives me a chroot home, 50% of the time it gives me a C:\Users\ home
> If I delete the C:\Users directory, it creates a new one.
> ![Screen Shot 2021-11-23 at 9 47 37 AM](https://user-images.githubusercontent.com/74074460/143069264-8c8b2813-f0d5-47c1-b216-c543109ac571.png)
> 
> 

That's the behavior... unpredictable.
Windows, even on PowerShell have New-Drive function to enclose and jail a folder, I do not know if that function is available for OpenSSH's code & language.

I'm trying other SSH SFTP like n'software and they did the folder jail but do not fit the expectations as Open SSH, so I hope this feature will be available as soon as possible. Come on guys!

**Comment by elHec** [comment]
If the OpenSSH server its installed with the domain controller role, you must put Domain\User on the match section:

Match user Domain\ftpuser4
ChrootDirectory C:\SFTP\ftpuser4

This work fine for me and all users on my domain controller.

The OpenSSH that I have installed is v8.1.0.0p1-Beta

**Comment by 0x8j0rn4r80r93** [comment]
> If the OpenSSH server its installed with the domain controller role, you must put Domain\User on the match section:
> 
> Match user Domain\ftpuser4 ChrootDirectory C:\SFTP\ftpuser4
> 
> This work fine for me and all users on my domain controller.
> 
> The OpenSSH that I have installed is v8.1.0.0p1-Beta

This worked for me. Great! Thanks @elHec!

**Comment by i3v** [comment]
Just to sum up [1](https://github.com/PowerShell/Win32-OpenSSH/issues/190#issuecomment-868458061) and [2](https://github.com/PowerShell/Win32-OpenSSH/issues/190#issuecomment-240599911), here's what eventually worked for me:
```
Subsystem	sftp	internal-sftp   # must be before first "Match"

Match User someuser
    AuthorizedKeysFile __PROGRAMDATA__/ssh/some_authorized_key
    ChrootDirectory "C:\Users\someuser\somefolder"   # only works  for sftp
    ForceCommand internal-sftp
    PermitTunnel no
    AllowAgentForwarding no
    AllowTcpForwarding no
    X11Forwarding no
    GatewayPorts no
```
