### ISSUE TITLE
SFTP with windows 2019 - keybased authentication + different user different cert

### ISSUE THREAD

**Issue by seed2eve** [PowerShell/Win32-OpenSSH#1901]
Hi, 

im following this youtube video to configure my SFTP with openssh( windows server 2019) 

I had created multiple users, I tend to have 1 user having own certificate.  is that possible? 

2. I able to load userA with private key and able to connect, then I load same private key with userB, it cant connect. it said server refuse the keys. I had copied the .ssh\authorized_keys from userA to userB. which part i had done wrong?  (this is just to testing, my ultimate goal is to each user have own certificate, might be plan to key the private key via puttygen)

**Comment by bagajjal** [comment]
This should help
https://github.com/PowerShell/Win32-OpenSSH/wiki/Setup-public-key-based-authentication-for-windows
