### ISSUE TITLE
ForceCommand internal-sftp setting does not provide logging records

### ISSUE THREAD

**Issue by nedubarr** [PowerShell/Win32-OpenSSH#1903]
**"OpenSSH for Windows" version**
_sshd version OpenSSH_for_Windows_7.7, LibreSSL 2.6.5__
 
**Server OperatingSystem**
_Windows Server 2019_ 

**What is failing**

As per https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities

We require the following settings to enable local sftp logs:

**Subsystem	sftp	sftp-server.exe -f LOCAL0 -l DEBUG3**

Which works fine, however... when required to allow sftp substyem connections only (no SSH/SCP/etc) we require the ForceCommand:

**ForceCommand internal-sftp**

Once this is done, we lose the ability to log sftp events.

**Comment by bagajjal** [comment]
The below config should work.
ForceCommand internal-sftp -f LOCAL0 -l DEBUG3
