### ISSUE TITLE
ssh.exe local port forwarding limited to 32 connections

### ISSUE THREAD

**Issue by scottmckenzie** [PowerShell/Win32-OpenSSH#191]
I have an ssh server which I am using to tunnel connections to remote servers.  In my .ssh\config file I have lots (>32) of LocalForward directives for this server like so:
`LocalForward 127.0.0.1:13389 remoteserver.localnet:3389`

When my config file contains more than 32 LocalForward directives I can no longer connect to my jumphost.  I receive the error `select: Overlapped I/O operation is in progress.`.  If I limit the LocalForward directives to 32 then I can successfully connect.

This seems to have been introduced in release 3_19_2016 which I believe included new I/O code.  Release 2_25_2016 allows me to connect to my jumphost with more than 32 local port forwardings.

**Comment by manojampalam** [comment]
This is due to a internal enforced limit. This can be upped a bit more but making it boundless requires a multi threaded solution that I would like to avoid. 
A work around would be to make a copy of ssh.exe and ssh_config in a separate directory, split LocalForward directives between ssh_configs and run separate instances of ssh.exe

**Comment by jhudsoncedaron** [comment]
@manojampalam Ah yes you ran into an inherent design flaw in Windows. It's not the first you will hit.

Knowing the flaws involved when I attempted to plan a port, I'm surprised that MS didn't just decide to fix the Windows problems first. Problem #1: Can't wait for thousands of handles per thread. Problem #2: Can't create anything like a PTY so a console app that wants to change TTY settings does not signal the server end and so it doesn't pass down the network pipe. Problem #3: Trying UTF-8 on the console explodes, but essentially all ssh links are either UTF-8 Text or binary and ssh can't tell the difference.

**Comment by nkrepo** [comment]
I am using "OpenSSH for Windows" version 0.0.22.0 at
Microsoft Windows 10 Pro 64-bit 10.0.16299 (Fall Creators Update)

@manojampalam 
The number of local ports that can be forwarded is limited to 16 instead of 32.
When I try to forward more than 16 local ports I get the following error:
"select: Not enough space"

**Comment by manojampalam** [comment]
@nkrepo there were no changes in the limit. Can you share your repro steps?

**Comment by nkrepo** [comment]
@manojampalam
I used a simple PowerShell script that called ssh.exe and specified  more than 16 local port forwards like the following.
```
ssh -L 3301:192.168.0.1:1123 `  
       ... `
      -L 3317:192.168.0.17:1123 `
      user@userdomain.com
```

**Comment by manojampalam** [comment]
Thanks. Looks like its an issue in core code. If you enable ssh client side traces you'll see the following pattern. For every alternate port, two sockets are somehow getting allocated. Looking into this further...

	channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 57001.
debug2: fd 6 setting O_NONBLOCK
debug3: fd 6 is O_NONBLOCK

debug1: channel 1: new [port listener]
debug1: Local connections to LOCALHOST:57002 forwarded to remote address 127.0.0.1:47002
debug3: channel_setup_fwd_listener_tcpip: type 2 wildcard 0 addr NULL
debug3: sock_set_v6only: set socket 7 IPV6_V6ONLY
debug1: Local forwarding listening on ::1 port 57002.
debug2: fd 7 setting O_NONBLOCK
debug3: fd 7 is O_NONBLOCK

debug1: channel 2: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 57002.
debug2: fd 8 setting O_NONBLOCK
debug3: fd 8 is O_NONBLOCK

debug1: channel 3: new [port listener]
debug1: Local connections to LOCALHOST:57003 forwarded to remote address 127.0.0.1:47002
debug3: channel_setup_fwd_listener_tcpip: type 2 wildcard 0 addr NULL
debug3: sock_set_v6only: set socket 9 IPV6_V6ONLY
debug1: Local forwarding listening on ::1 port 57003.
debug2: fd 9 setting O_NONBLOCK
debug3: fd 9 is O_NONBLOCK

debug1: channel 4: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 57003.
debug2: fd 10 setting O_NONBLOCK
debug3: fd 10 is O_NONBLOCK

debug1: channel 5: new [port listener]
debug1: Local connections to LOCALHOST:57004 forwarded to remote address 127.0.0.1:47002
debug3: channel_setup_fwd_listener_tcpip: type 2 wildcard 0 addr NULL
debug3: sock_set_v6only: set socket 11 IPV6_V6ONLY
debug1: Local forwarding listening on ::1 port 57004.
debug2: fd 11 setting O_NONBLOCK
debug3: fd 11 is O_NONBLOCK

debug1: channel 6: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 57004.
debug2: fd 12 setting O_NONBLOCK
debug3: fd 12 is O_NONBLOCK

debug1: channel 7: new [port listener]
debug1: Local connections to LOCALHOST:57005 forwarded to remote address 127.0.0.1:47002
debug3: channel_setup_fwd_listener_tcpip: type 2 wildcard 0 addr NULL
debug3: sock_set_v6only: set socket 13 IPV6_V6ONLY
debug1: Local forwarding listening on ::1 port 57005.
debug2: fd 13 setting O_NONBLOCK
debug3: fd 13 is O_NONBLOCK

**Comment by manojampalam** [comment]
Try with -4 parameter. My guess is you are ending up listening on IPv6 address too for each forwarded port. That will double the number of sockets you are listening on.

**Comment by nkrepo** [comment]
@manojampalam you are correct it was binding to both IPv4 and IPv6 address now it works up to 32 local port forwards. I had disabled IPv6 for the physical network adapter but not system-wide, therefore the `Loopback Pseudo-Interface` still has an IPv6 address.

```
Get-NetIPAddress -ifIndex 1

IPAddress         : ::1
InterfaceIndex    : 1
InterfaceAlias    : Loopback Pseudo-Interface 1
AddressFamily     : IPv6
...
PolicyStore       : ActiveStore

IPAddress         : 127.0.0.1
InterfaceIndex    : 1
InterfaceAlias    : Loopback Pseudo-Interface 1
AddressFamily     : IPv4
...
PolicyStore       : ActiveStore
```
