### ISSUE TITLE
Kill idle sessions

### ISSUE THREAD

**Issue by serk89** [PowerShell/Win32-OpenSSH#1910]
If a user forgets to disconnect the SSH session, we can see the traffic on the server until the user initiates the disconnect when they remember or after their computer is rebooted.
Is there a way to disconnect the user or kill the sessions from the server side, if user is idle or if the session is over 60 minutes for example.
I am running v8.6 on Server 2019

**Comment by mgkuhn** [comment]
Automatic session timeouts are a feature provided by some shells. For example in `bash` you can set the variable `TMOUT` to the number of seconds after which the shell prompt will time out and exit the shell, thereby also closing an idle SSH session:
```
$ TMOUT=5 bash
$ timed out waiting for input: auto-logout
```
In case CMD.EXE and PowerShell don't have anything equivalent, perhaps that might be worth adding there?

**Comment by mgkuhn** [comment]
If you want to terminate a session on the server in case the other side has switched off their computer, have a look at the sshd_config options `TCPKeepAlive`, `ClientAliveCountMax` and `ClientAliveInterval`, which negotiate that TCP must regularly send packets even if the user isn't typing anything, and if those packets don't arrive, then the TCP session is closed after a while.

**Comment by serk89** [comment]
TCPKeepAlive, ClientAliveCountMax and ClientAliveInterval are all set already. I agree would be good to get some sort of feature added.

**Comment by bagajjal** [comment]
TCPKeepAlive is on by default.

If you are looking for a feature in the terminal, then it will be out of scope for SSH.

**Comment by gcastellana** [comment]
I'm having the same problem with version 9.5.
TCPKeepAlive, ClientAliveCountMax and ClientAliveInterval are all configured but have no effect on idle connections
