### ISSUE TITLE
'scp.exe' lost connection V8.9.0.0p1-Beta

### ISSUE THREAD

**Issue by wannvmi** [PowerShell/Win32-OpenSSH#1912]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

'scp.exe' ²»ˇŚ²¿»󎢲¿ļ®£¬Ҳ²»ˇ¿ʔ̐еĳ͐ 
»󆺴¦mτ¼þ¡£
lost connection

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH
scp error 

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**

**What is failing**

**Expected output**

**Actual output**

**Comment by bagajjal** [comment]
@wannvmi - Please ensure the system PATH environment variable has the Win32-OpenSSH installation folder path.

**Comment by bagajjal** [comment]
@wannvmi , Feel free to reopen the issue if you are still having issue.
