### ISSUE TITLE
SSH-Agent installed through MSI is missing required privileges

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/Win32-OpenSSH#1914]
This problem is specific to MSI installation only.

**Problem statement**
If you install the V8.9 through MSI then ssh-agent doesn't have all the required privileges. This effects the FIDO / PKCS11 scenarios because the ssh-agent fails to create ssh-sk-helper.exe / ssh-pkcs11-helper.exe. 

**Work around**  
Please use zip payload for installation instead of MSI package.

**Code snippets**
Install-sshd.ps1 has the required privileges. Code [here](https://github.com/PowerShell/openssh-portable/blob/bd0d488a3c4bca55626909d81ac766f2aa278791/contrib/win32/openssh/install-sshd.ps1#L101).

MSI is missing the required privileges. Code [here](https://github.com/PowerShell/openssh-portable/blob/bd0d488a3c4bca55626909d81ac766f2aa278791/contrib/win32/install/shared.wxs#L66)

**Comment by ghost** [comment]
@bagajjal This fix only seems to be present in the 32-bit MSI.  Running the 64-bit installer results in the same error.

**Comment by crrodriguez** [comment]
have the same issue as @shareefj , win64 msi does not set proper privileges and the agent is unable to work.. which command exactly should I use to fix it ?

**Comment by tgauth** [comment]
can run the following in a command prompt or PowerShell: 
`sc.exe privs ssh-agent SeAssignPrimaryTokenPrivilege/SeTcbPrivilege/SeBackupPrivilege/SeRestorePrivilege/SeImpersonatePrivilege`
