### ISSUE TITLE
Provide a way to confirm the fix folder permissions for programdata\ssh installation prompt to allow for a silent installation

### ISSUE THREAD

**Issue by rgl** [PowerShell/Win32-OpenSSH#1916]
After https://github.com/PowerShell/openssh-portable/pull/549, `install-ssh.ps1` now prompts the user to confirm the fix the programdata\ssh folder permissions but that does not allow for a silent installation.

Please provide a way to call `install-sshd.ps1` with a `-Confirm:$false` parameter, just like we can do with `FixHostFilePermissions.ps1 -Confirm:$false`.

**Comment by rgl** [comment]
I've just tried the new version, but `install-sshd.ps1 -Confirm:$false` is not working:

```console
PS C:\Program Files\OpenSSH> .\install-sshd.ps1 -Confirm:$false
C:\Program Files\OpenSSH\install-sshd.ps1 : Cannot bind parameter because parameter 'confirm' is specified more than once. To provide multiple values to parameters that can accept multiple values, use the array
syntax. For example, "-parameter value1,value2,value3".
At line:1 char:1
+ .\install-sshd.ps1 -Confirm:$false
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [install-sshd.ps1], ParameterBindingException
    + FullyQualifiedErrorId : ParameterAlreadyBound,install-sshd.ps1


PS C:\Program Files\OpenSSH> .\sshd.exe --version
unknown option -- -
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3
usage: sshd [-46DdeiqTt] [-C connection_spec] [-c host_cert_file]
            [-E log_file] [-f config_file] [-g login_grace_time]
            [-h host_key_file] [-o option] [-p port] [-u len]

```

Can you please re-open this issue?

**Comment by bagajjal** [comment]
@rgl  - I think you are trying on the windows powershell. Can you try it on powershell 7+

**Comment by rgl** [comment]
I can, but older Windows versions (e.g. Windows 2019) do not ship PowerShell 7 out-of-the-box. So I would say these scripts should target Windows PowerShell 5.1.

**Comment by rgl** [comment]
@bagajjal, I confirm that it works correctly with PowerShell 7.2.2.

**Comment by bagajjal** [comment]
Thanks @rgl. We will fix this for windows PowerShell.

**Comment by max06** [comment]
I just spent half a day searching for whatever broke our unattended windows (2019) image builds... :(

Any ETA for a fix? Should I pin our scripts to the previous version or is this a matter of hours?

**Comment by rgl** [comment]
@max06 IMHO, if you are sad after something breaks, always pin your dependencies. And upgrade at your own pace, when you can afford the time.

**Comment by max06** [comment]
> @max06 IMHO, if you are sad after something breaks, always pin your dependencies.

You're right. Full ack.
But we're building windows server images here to be used by customers on a regular schedule, Those should contain the latest releases, including security fixes. I have no issues with failing builds, it's fine if a shortterm bug blocks us for some days. This is just a bad timing because I'm currently rebuilding our CI pipeline...

**Comment by dhs-rec** [comment]
Any idea about when this will be released?

**Comment by tgauth** [comment]
> Any idea about when this will be released?

This was released with v8.9.1.0p1-Beta - https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.9.1.0p1-Beta

**Comment by dhs-rec** [comment]
@tgauth, no, it wasn't. This issue was reopened after that release.

**Comment by tgauth** [comment]
Ah, yes - sorry about that, the issue was reopened to fix for Windows PowerShell. I don't know the date for the next release yet.
