### ISSUE TITLE
MSI : system path (x86)

### ISSUE THREAD

**Issue by kyrios123** [PowerShell/Win32-OpenSSH#1919]
Small correction needed on the Install [Win32 OpenSSH Using MSI](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI) wiki page.

If the 32-bit version is installed the command to update the system path in point 2 should be 
`setx /M PATH $($Env:PATH + ';' + ${Env:ProgramFiles(x86)} + '\OpenSSH')`

**Comment by tgauth** [comment]
Done - thanks for catching this!
