### ISSUE TITLE
Vista support?

### ISSUE THREAD

**Issue by guy3145** [PowerShell/Win32-OpenSSH#192]
Hi
im using Windows Vista, i installed OpenSSH according to instructions.
when im trying to connect using putty via ssh im getting the following error:
"network error: software caused connection abort"
in other OS i dont have that issue: wi2012r2, win2008r2, win7, win8

does this program support windows vista?
Thanks for helping
Guy

**Comment by manojampalam** [comment]
Sorry, we haven't tested it on Vista.
