### ISSUE TITLE
missing SSH_ORIGINAL_COMMAND on Server 2016

### ISSUE THREAD

**Issue by dada216** [PowerShell/Win32-OpenSSH#1926]
**"OpenSSH for Windows" version**
 OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3
 
**Server OperatingSystem**
 Windows Server 2016 Datacenter

**Client OperatingSystem**
RedHat Linux 8.5

**What is failing**
executing a remote command via ssh does not passes the actual argument given to ssh to the client

content of administrators_authorized_keys:
command="powershell.exe -File C:\ansible\nagios\launcer.ps1" ssh-rsa AAAAB3Nza...

invocation from linux:
ssh -i /var/spool/nagios/.ssh/id_rsa administrator@alphatrading.local@hostname resourcecheck.ps1

content of launcher.ps1
C:\ansible\nagios\%SSH_ORIGINAL_COMMAND%

**Expected output**
output from script resourcecheck.ps1

**Actual output**
```
C:\ansible\nagios\%SSH_ORIGINAL_COMMAND% : The term 'C:\ansible\nagios\%SSH_ORIGINAL_COMMAND%' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the  spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\ansible\nagios\launcer.ps1:1 char:1
+ C:\ansible\nagios\%SSH_ORIGINAL_COMMAND%
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ansible\nagios\%SSH_ORIGINAL_COMMAND%:String) [ 
   ], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

directly restricting the command parameter to the script resourcecheck.ps1 results in correct execution and stdout return.

**Comment by bagajjal** [comment]
Given it's a powershell script, you might need to refer the environment variable using $env:SSH_ORIGINAL_COMMAND

**Comment by dada216** [comment]
thanks, that was it, how silly of me.
