### ISSUE TITLE
Exit codes relayed to remote client do not change based on program exit status

### ISSUE THREAD

**Issue by dada216** [PowerShell/Win32-OpenSSH#1933]
**"OpenSSH for Windows" version**
OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3
 
**Server OperatingSystem**
 `Windows Server 2012 R2 Standard`

**Client OperatingSystem**
Red Hat Enterprise Linux release 8.5 (Ootpa)

**What is failing**
executing any command remotely from linux on windows via ssh has a return code of 1, regardless of the actual return code of the program.

```
[root@linuxhost libexec]# ssh administrator@domain.local@windowshost "hostname"; echo $?
windowshost
1
[root@linuxhost libexec]# ssh administrator@domain.local@windowshost "hostname1"; echo $?
hostname1 : Termine 'hostname1' non riconosciuto come nome di cmdlet, funzione, programma eseguibile o file script. 
Controllare l'ortografia del nome o verificare che il percorso sia incluso e corretto, quindi riprovare.
In riga:1 car:1
+ hostname1
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (hostname1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
1

```
**Expected output**

return code should have been 0 when calling hostname and 1 when calling hostname1
on a windows server 2019 with the same exact opensshversion the return code is always 0, regardless of the actual return code from the program being called.

**Comment by bagajjal** [comment]
I don't see this behavior from ubutnu18 to windows 11 machine.

![image](https://user-images.githubusercontent.com/23668037/163604121-e25a1d5f-847f-4c88-b9f5-696fe96647cb.png)

**Comment by mgkuhn** [comment]
Can't reproduce either:

From Linux to Linux:
```
$ ssh ubuntu-server exit 0 ; echo $?
0
$ ssh ubuntu-server exit 1 ; echo $?
1
$ ssh ubuntu-server exit 255 ; echo $?
255
$ ssh ubuntu-server exit_ ; echo $?
bash: exit_: command not found
127
```

From Linux to Windows 10 21H2 (Powershell, OpenSSH 8.1p1):
```
$ ssh windows-server exit 0 ; echo $?
0
$ ssh windows-server exit 1 ; echo $?
1
$ ssh windows-server exit 255 ; echo $?
255
$ ssh windows-server exit_ ; echo $?
exit_ : The term 'exit_' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path 
is correct and try again.
At line:1 char:1
+ exit_
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (exit_:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
1
$ ssh windows-server hostname ; echo $?
WINDOWS-SERVER
0
```
