### ISSUE TITLE
MSI Not Installing Any Feature (Client or Server) When Using the REMOVE Property on Initial Install

### ISSUE THREAD

**Issue by bmkaiser** [PowerShell/Win32-OpenSSH#1936]
### **Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

- Steps are being performed from a prompt that is being run as Admin on a computer that doesn't already have OpenSSH for Windows installed
- MSI verbose log file can be viewed here: [OpenSSH for Windows MSI Install Logs](https://gist.githubusercontent.com/bmkaiser/4354d76d59207f26f861e40809080847/raw/8a6bdf16f0475882a5a96eb71cb6dffffe88d659/openssh-8910.log)
- Following this documentation (see below for current documentation screenshot): [Install Win32 OpenSSH Using MSI](../wiki/Install-Win32-OpenSSH-Using-MSI)

![image](https://user-images.githubusercontent.com/5446414/165330201-c1207f20-5de0-497b-8794-6564d2b30a12.png)

#### Scenario 1: Run the MSI with the `REMOVE` Property

- **Results**: The install exits with an exit code of `0` and no features are installed
- **Command**: `msiexec.exe /i OpenSSH-x64-v8.9.1.0.msi REMOVE=Server`

#### Scenario 2: Run the MSI with no Arguments

- **Results**: It installs both the ssh-agent and sshd services successfully
- **Command**: `msiexec.exe /i OpenSSH-x64-v8.9.1.0.msi`

#### Scenario 3: Run the MSI after Scenario 2 with the `REMOVE` Property

- **Results**: It successfully removes the specified feature
- **Command**: `msiexec.exe /i OpenSSH-x64-v8.9.1.0.msi REMOVE=Server`

### Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`

8.9.1.0
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3

**Client OperatingSystem**

Windows 10 Enterprise 21H2 (10.0.19044.1645)

**What is failing**

Installation

**Expected output**

When running the MSI for initial installation with the `REMOVE` property, I would expect it to install successfully with only the feature that is not specified to be removed.

**Actual output**

MSI doesn't install any feature if the `REMOVE` property is used during initial installation.

**Comment by stevenwdv** [comment]
I had the same problem, but I realized the idea is probably that you should first run the command without any parameters to install client *and* server, and then run one of the REMOVE commands if you want just one.

I have no idea why the wiki doesn't just mention that you can do this in one simple command, just picking one msi feature:
```shell
msiexec /i openssh.msi ADDLOCAL=Client
```
or:
```shell
msiexec /i openssh.msi ADDLOCAL=Server
```

Maybe the wiki should be updated to this?

**Comment by bmkaiser** [comment]
I agree this is a documentation issue rather than a functional one now that you've pointed out that `ADDLOCAL` is probably what's intended. I too was having to run the installer twice because I wasn't aware of `ADDLOCAL`.

Perhaps the wiki should instead say something like this:

## 1. Run MSI Installer
The MSI must be run in any command prompt (cmd.exe & pwsh.exe both work), as it does not yet have a UI (coming soon).  
The MSI will install OpenSSH to the `ProgramFiles\OpenSSH` folder.  
The commands to run, are as follows:
* To install both the SSH Client & the SSH Server (default behavior)  
`msiexec /i <path to openssh.msi>`
* To install only the SSH Client  
`msiexec /i <path to openssh.msi> ADDLOCAL=Client`
* To install only the SSH Server  
`msiexec /i <path to openssh.msi> ADDLOCAL=Server`
* To uninstall only the SSH Client
`msiexec /i <path to openssh.msi> REMOVE=Client`
* To uninstall only the SSH Server
`msiexec /i <path to openssh.msi> REMOVE=Server`

###  Examples:
* Installing SSH Client & openssh.msi is in the working directory:  
`msiexec /i openssh.msi ADDLOCAL=Client`
* Installing SSH Server & openssh.msi is in C:\users\public\downloads\:  
`msiexec /i C:\users\public\downloads\openssh.msi ADDLOCAL=Server`
* Uninstalling SSH Client & openssh.msi is in the working directory:  
`msiexec /i openssh.msi REMOVE=Client`

**Comment by tgauth** [comment]
Thanks @bmkaiser & @stevenwdv - added these changes to the [wiki](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI).
