### ISSUE TITLE
Update system path instructions break stuff

### ISSUE THREAD

**Issue by stevenwdv** [PowerShell/Win32-OpenSSH#1937]
The instructions on [the wiki](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI#2-update-system-path-required-for-scp-and-sftp) to update the path for MSI install break a couple of things.

First, they append the user's Path to the machine Path, which is definitely not what you want.

Second, this command truncates the Path to 1024 characters, which broke stuff for me. Fortunately I could recover the rest from another still running process using Process Hacker.

I propose a solution using the dedicated PowerShell command: https://stackoverflow.com/a/2571200

**Comment by tgauth** [comment]
Thanks @stevenwdv - changes made to the [wiki](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI#2-update-system-path-required-for-scp-and-sftp).
