### ISSUE TITLE
SSH Cipher Negotiation Fails with libssh2.1.7.0

### ISSUE THREAD

**Issue by johnbuonassisi** [PowerShell/Win32-OpenSSH#194]
Installed Win32-OpenSSH on Windows 2008-R2 Server and attempted to upload a file using libssh2.1.7.0. The SSH connection fails because the server and client cannot decide on an appropriate cipher. Both client and server support aes256-cbc, aes192-cbc, and aes128-cbc, so why does the cipher negotiation fail?

sshd.log reports:
5512 14:20:30 909 fatal: Unable to negotiate with XXX.XX.XXX.XXX: no matching cipher found. Their offer: **aes256-cbc,aes192-cbc,aes128-cbc**,arcfour128,arcfour,3des-cbc

Win32-OpenSSH supported ciphers:
.\ssh.exe -Q cipher
aes128-ctr
aes192-ctr
aes256-ctr
**aes128-cbc
aes192-cbc
aes256-cbc**
chacha20-poly1305@openssh.com

**Comment by arif-pragmasys** [comment]
aes*-cbc ciphers are on in ssh.exe, but not in sshd.exe(the server) by default. You can turn them on by adding the following line in your sshd_config file:
![capture](https://cloud.githubusercontent.com/assets/14184782/21364306/e0febbfa-c6b5-11e6-836a-5e222a256735.PNG)

Server should pick up the new config without a restart.

**Comment by manojampalam** [comment]
Reopen if needed
