### ISSUE TITLE
256colors2.pl crashes ssh.exe

### ISSUE THREAD

**Issue by Daniel15** [PowerShell/Win32-OpenSSH#195]
Version: 2016.04.05 (installed via Chocolatey: https://chocolatey.org/packages/win32-openssh)
Script: https://conemu.github.io/256colors2.pl (or just google "256colors2.pl") - It's a script designed to test if 256 color mode is working.

Result if I run it on a remote server via ssh.exe:
![](http://ss.dan.cx/2016/04/chrome_25-22.00.03.png)

Verbose logs don't seem to contain anything particularly interesting.

Exception (sorry I don't have debug symbols):

```
Unhandled exception at 0x00007FF7097EC8F4 in ssh.exe: Stack cookie instrumentation code detected a stack-based buffer overrun.
```

Expected result:
![](http://ss.dan.cx/2016/04/ConEmu_25-21.06.50.png)

**Comment by bagajjal** [comment]
This is working fine and there are no exceptions now.
