### ISSUE TITLE
scp.exe not in $env:path when using 8.9.0.1-msi

### ISSUE THREAD

**Issue by linderd** [PowerShell/Win32-OpenSSH#1952]
**"OpenSSH for Windows" version**
8.9.1.0
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Ubuntu 20.04

**What is failing**
When i try to use scp to or from the windows machine I get an error, that scp.exe can not be found. e.g.: `scp file.txt windows-machine:`

**Expected output**
*file get's transferred*

**Actual output**
error: scp.exe not found

**Workarund**
- add a directory containing scp.exe to $env:path
- go back to 8.6.0.0

**Comment by tgauth** [comment]
Thanks @linderd, this limitation of the MSI is documented [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI) in step 2.

**Comment by linderd** [comment]
thanks @tgauth, I did not see that.

**Comment by SneakyPayload** [comment]
@tgauth I was also banging my head on the desk with this problem. Thanks.
