### ISSUE TITLE
PermitTTY no

### ISSUE THREAD

**Issue by claudioezz** [PowerShell/Win32-OpenSSH#1953]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 8.9.1.0
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows Server 2019 Standard
**Client OperatingSystem**
Windows Server 2019 Standard
**What is failing**
from original configuration i have modified only PermitTTY directive from yes to no
**Expected output**
block interactive access /client_loop: send disconnect: Connection reset by peer
**Actual output**
Interactive session

Adding command cmd or powershell to connection string, I'm able to doing an SSH interactive session with the target server
example :

ssh [user]@[machine] cmd
ssh [user]@[machine] powershell

**Comment by tgauth** [comment]
@claudioezz, did you restart sshd after you modified the configuration?

**Comment by claudioezz** [comment]
yes,


Il mer 15 giu 2022, 19:05 Tess Gauthier ***@***.***> ha
scritto:

**Comment by mike-brearton-dtl** [comment]
I also was able to get a command line, with permitTTY=no
If the client specifies **ssh -T** the command line is available.
If I do not specify -T, the command line is not permitted... as configured and expected.

**Comment by claudioezz** [comment]
Ok, thanks.

Il gio 11 ago 2022, 06:13 mike-brearton-dtl ***@***.***> ha
scritto:

**Comment by vthiebaut10** [comment]
Fix will be in the next release (v9.1) coming up soon.
