### ISSUE TITLE
ForwardAgent not working with ProxyJump

### ISSUE THREAD

**Issue by MatejVitek** [PowerShell/Win32-OpenSSH#1958]
**"OpenSSH for Windows" version**
8.1.0.1

**Server OperatingSystem**
Ubuntu 22.04 LTS

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
I'm trying to connect via SSH to a remote server using a `ProxyJump` in between, then pull/push some git repository changes to/from the remote host, using the SSH agent from my local PC (I don't have any SSH keys or a running SSH agent on the remote server).

`.ssh/config`:

	Host JumpHost
		HostName ip.ip.ip.ip
		User username
		ForwardAgent yes

	Host Target
		HostName 192.168.100.101
		User user
		ProxyJump JumpHost
		ForwardAgent yes

Doing this in Powershell results in a Permission denied error. However, doing the same thing in a WSL shell (running Ubuntu) with its own SSH implementation works without issues.

I've also tried the same from my home PC, also running Windows 10 Pro and also get the same issue (working in WSL but not in Powershell).

Additionally, if I try a different remote with the same `ProxyJump`, it still fails in Powershell, however if I connect to `JumpHost` itself (i.e. without using a `ProxyJump` directive), this setup works fine in both Powershell and WSL and I can use git as expected.

**Expected output**
This is what I get in a WSL shell:

	user@PC:~$ ssh Target
	user@Target:~$ ssh-add -L
	ssh-ed25519 AAAAC3NzaC1lZDI1NTE5BASDIGdmx21Jrea+X7XlvQnC49d+M59SXi/Elia0Sm9yJ5NF User-PC
	user@Target:~$ cd Repo
	user@Target:~/Repo$ git pull
	Already up to date.

**Actual output**
This is what I get with the same commands in Powershell.

	user@PC:~$ ssh Target
	user@Target:~$ ssh-add -L
	ssh-ed25519 AAAAC3NzaC1lZDI1NTE5BASDIGdmx21Jrea+X7XlvQnC49d+M59SXi/Elia0Sm9yJ5NF User-PC
	user@Target:~$ cd Repo
	user@Target:~/Repo$ git pull
	git@bitbucket.org: Permission denied (publickey).
	fatal: Could not read from remote repository.

	Please make sure you have the correct access rights
	and the repository exists.

Additional log from `ssh -vvv` from remote (instead of `git pull`):

	user@Target:~$ssh -vvv git@bitbucket.org
	OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022
	debug1: Reading configuration data /home/user/.ssh/config
	debug1: /home/user/.ssh/config line 74: Applying options for *
	debug1: Reading configuration data /etc/ssh/ssh_config
	debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
	debug1: /etc/ssh/ssh_config line 21: Applying options for *
	debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/user/.ssh/known_hosts'
	debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/user/.ssh/known_hosts2'
	debug2: resolving "bitbucket.org" port 22
	debug3: resolve_host: lookup bitbucket.org:22
	debug3: ssh_connect_direct: entering
	debug1: Connecting to bitbucket.org [104.192.141.1] port 22.
	debug3: set_sock_tos: set socket 3 IP_TOS 0x10
	debug1: Connection established.
	debug1: identity file /home/user/.ssh/id_rsa type -1
	debug1: identity file /home/user/.ssh/id_rsa-cert type -1
	debug1: identity file /home/user/.ssh/id_ecdsa type -1
	debug1: identity file /home/user/.ssh/id_ecdsa-cert type -1
	debug1: identity file /home/user/.ssh/id_ecdsa_sk type -1
	debug1: identity file /home/user/.ssh/id_ecdsa_sk-cert type -1
	debug1: identity file /home/user/.ssh/id_ed25519 type -1
	debug1: identity file /home/user/.ssh/id_ed25519-cert type -1
	debug1: identity file /home/user/.ssh/id_ed25519_sk type -1
	debug1: identity file /home/user/.ssh/id_ed25519_sk-cert type -1
	debug1: identity file /home/user/.ssh/id_xmss type -1
	debug1: identity file /home/user/.ssh/id_xmss-cert type -1
	debug1: identity file /home/user/.ssh/id_dsa type -1
	debug1: identity file /home/user/.ssh/id_dsa-cert type -1
	debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
	debug1: Remote protocol version 2.0, remote software version conker_cad0b366a2 2ca47060d73e
	debug1: compat_banner: no match: conker_cad0b366a2 2ca47060d73e
	debug2: fd 3 setting O_NONBLOCK
	debug1: Authenticating to bitbucket.org:22 as 'git'
	debug3: record_hostkey: found key type RSA in file /home/user/.ssh/known_hosts:1
	debug3: load_hostkeys_file: loaded 1 keys from bitbucket.org
	debug1: load_hostkeys: fopen /home/user/.ssh/known_hosts2: No such file or directory
	debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
	debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
	debug3: order_hostkeyalgs: prefer hostkeyalgs: rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256
	debug3: send packet: type 20
	debug1: SSH2_MSG_KEXINIT sent
	debug3: receive packet: type 20
	debug1: SSH2_MSG_KEXINIT received
	debug2: local client KEXINIT proposal
	debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
	debug2: host key algorithms: rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com
	debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
	debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
	debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
	debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
	debug2: compression ctos: none,zlib@openssh.com,zlib
	debug2: compression stoc: none,zlib@openssh.com,zlib
	debug2: languages ctos: 
	debug2: languages stoc: 
	debug2: first_kex_follows 0 
	debug2: reserved 0 
	debug2: peer server KEXINIT proposal
	debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,ext-info-s
	debug2: host key algorithms: ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss
	debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,chacha20-poly1305@openssh.com
	debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,chacha20-poly1305@openssh.com
	debug2: MACs ctos: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96
	debug2: MACs stoc: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96
	debug2: compression ctos: none
	debug2: compression stoc: none
	debug2: languages ctos: 
	debug2: languages stoc: 
	debug2: first_kex_follows 0 
	debug2: reserved 0 
	debug1: kex: algorithm: curve25519-sha256@libssh.org
	debug1: kex: host key algorithm: rsa-sha2-512
	debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
	debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
	debug3: send packet: type 30
	debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
	debug3: receive packet: type 31
	debug1: SSH2_MSG_KEX_ECDH_REPLY received
	debug1: Server host key: ssh-rsa SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A
	debug3: record_hostkey: found key type RSA in file /home/user/.ssh/known_hosts:1
	debug3: load_hostkeys_file: loaded 1 keys from bitbucket.org
	debug1: load_hostkeys: fopen /home/user/.ssh/known_hosts2: No such file or directory
	debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
	debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
	debug1: Host 'bitbucket.org' is known and matches the RSA host key.
	debug1: Found key in /home/user/.ssh/known_hosts:1
	debug3: send packet: type 21
	debug2: ssh_set_newkeys: mode 1
	debug1: rekey out after 134217728 blocks
	debug1: SSH2_MSG_NEWKEYS sent
	debug1: expecting SSH2_MSG_NEWKEYS
	debug3: receive packet: type 21
	debug1: SSH2_MSG_NEWKEYS received
	debug2: ssh_set_newkeys: mode 0
	debug1: rekey in after 134217728 blocks
	debug2: get_agent_identities: ssh_agent_bind_hostkey: communication with agent failed
	debug1: get_agent_identities: ssh_fetch_identitylist: communication with agent failed
	debug1: Will attempt key: /home/user/.ssh/id_rsa 
	debug1: Will attempt key: /home/user/.ssh/id_ecdsa 
	debug1: Will attempt key: /home/user/.ssh/id_ecdsa_sk 
	debug1: Will attempt key: /home/user/.ssh/id_ed25519 
	debug1: Will attempt key: /home/user/.ssh/id_ed25519_sk 
	debug1: Will attempt key: /home/user/.ssh/id_xmss 
	debug1: Will attempt key: /home/user/.ssh/id_dsa 
	debug2: pubkey_prepare: done
	debug3: send packet: type 5
	debug3: receive packet: type 7
	debug1: SSH2_MSG_EXT_INFO received
	debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-rsa,ssh-dss-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com>
	debug3: receive packet: type 6
	debug2: service_accept: ssh-userauth
	debug1: SSH2_MSG_SERVICE_ACCEPT received
	debug3: send packet: type 50
	debug3: receive packet: type 51
	debug1: Authentications that can continue: publickey
	debug3: start over, passed a different list publickey
	debug3: preferred gssapi-with-mic,publickey,keyboard-interactive,password
	debug3: authmethod_lookup publickey
	debug3: remaining preferred: keyboard-interactive,password
	debug3: authmethod_is_enabled publickey
	debug1: Next authentication method: publickey
	debug1: Trying private key: /home/user/.ssh/id_rsa
	debug3: no such identity: /home/user/.ssh/id_rsa: No such file or directory
	debug1: Trying private key: /home/user/.ssh/id_ecdsa
	debug3: no such identity: /home/user/.ssh/id_ecdsa: No such file or directory
	debug1: Trying private key: /home/user/.ssh/id_ecdsa_sk
	debug3: no such identity: /home/user/.ssh/id_ecdsa_sk: No such file or directory
	debug1: Trying private key: /home/user/.ssh/id_ed25519
	debug3: no such identity: /home/user/.ssh/id_ed25519: No such file or directory
	debug1: Trying private key: /home/user/.ssh/id_ed25519_sk
	debug3: no such identity: /home/user/.ssh/id_ed25519_sk: No such file or directory
	debug1: Trying private key: /home/user/.ssh/id_xmss
	debug3: no such identity: /home/user/.ssh/id_xmss: No such file or directory
	debug1: Trying private key: /home/user/.ssh/id_dsa
	debug3: no such identity: /home/user/.ssh/id_dsa: No such file or directory
	debug2: we did not send a packet, disable method
	debug1: No more authentication methods to try.
	git@bitbucket.org: Permission denied (publickey).

**Comment by dogbertai** [comment]
```
debug2: get_agent_identities: ssh_agent_bind_hostkey: communication with agent failed
debug1: get_agent_identities: ssh_fetch_identitylist: communication with agent failed
```

ssh-agent in OpenSSH For Windows 8.1 is incompatible with OpenSSH (proper) 8.9.

Try installing the latest OpenSSH For Windows https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI

**Comment by MatejVitek** [comment]
Thanks, this seems to have resolved the issue.
