### ISSUE TITLE
ssh.exe colors support

### ISSUE THREAD

**Issue by shanoor** [PowerShell/Win32-OpenSSH#196]
I tried to log in a CoreOS machine and the welcome uses fancy colors that mess with Powershell:

![coreos](https://cloud.githubusercontent.com/assets/17402800/14808320/6bfde8ac-0b95-11e6-9e68-0cba70c291d5.PNG)

I'm using the latest version of Win32-OpenSSH downloaded from the _releases_ folder, **version 4_5_2016**.

**Comment by manojampalam** [comment]
Please try out the milestone release. Reopen if needed.
