### ISSUE TITLE
Change instruction for setting environment variables

### ISSUE THREAD

**Issue by JMyklebust** [PowerShell/Win32-OpenSSH#1960]
Hi,

This may be a nitpick but the instruction for updating path needs to be modified.
Using ``$env:path`` will take the combination of both user and sytem paths.
This can cause issues if we are only modifiying the system enviroment variables.
Use ``[Environment]::GetEnvironmentVariable("Path","Machine")`` to retrieve path variable from the system/machine store only.

So the line in:
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI#2-update-system-path-required-for-scp-and-sftp

So the command should be modified like this:
```Powershell
[Environment]::SetEnvironmentVariable("Path", [Environment]::GetEnvironmentVariable("Path","Machine") + ';' + ${Env:ProgramFiles} + '\OpenSSH', "Machine")
```

**Comment by tgauth** [comment]
Thanks for pointing this out @JMyklebust - it has been [updated](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI)

**Comment by JMyklebust** [comment]
Not sure it will be noticed, but adding it here for reference (no reason to raise another issue for it).
After playing around with things i realized that current suggested method of adding to the environment variables will also expand any strings in the environment.

If this is undesirable we can do this in a more complex (but maybe cleaner) way.
````PowerShell
# Get path environment variables without expanding them
# We also split at the delimiter to give an array, and cast as a list for simpler editing
$regKey = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey('SYSTEM\CurrentControlSet\Control\Session Manager\Environment', $true)
$path = [system.collections.generic.list[string]]($regKey.GetValue('Path', $null, "DoNotExpandEnvironmentNames") -split ";")

# Side note: Defining search Predicates for collections in PowerShell
# With named parameters
# {param ($item) $item  -match "SSH"}
# As args from pipeline
# {$args[0] -match "SSH"}

# Clean up any empty lines from list (just a bit of sanity)
[void]$path.RemoveAll({ [string]::IsNullOrWhiteSpace($args[0]) })

# More complex logic can be done, but in most cases you really only want to have the path to OpenSSH in program files and in the Windows directory
# Clear out all OpenSSH entries from the list
[void]$path.RemoveAll({ $args[0] -match "OpenSSH" })
# After removing all OpenSSH entries we insert the one we want at the start of the list, and Windows default one (just in case) at the end of the list
$path.Insert(0, '%PROGRAMFILES%\OpenSSH')
$path.Add('%WINDIR%\System32\OpenSSH')

# Finally update registry value
$regKey.SetValue("Path", ($path -join ";"), "ExpandString")
````

This way will also make sure that you are overriding the build in OpenSSH version with the newer installed version.
In the simplified version you can also do the "override" by adding the new path to the front of the existing content instead of at the end.
````PowerShell
[Environment]::SetEnvironmentVariable("Path", (${Env:ProgramFiles} + '\OpenSSH' + ';') + [Environment]::GetEnvironmentVariable("Path","Machine") , "Machine")
````
