### ISSUE TITLE
MSI Installer not updating system path during installation of OpenSSH

### ISSUE THREAD

**Issue by upyesp** [PowerShell/Win32-OpenSSH#1965]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

There is now a winget installer for OpenSSH, excellent, thanks to all involved.

When installing the winget package `Microsoft.OpenSSH`, the environment variable, system path, is not updated.  

### Expected behavior

```console
Typically winget installations include the step to update the system path. My experience of other app, including Microsoft apps, installed via winget is that the system path is updated as part of the installation.
```

### Actual behavior

```console
The system path remains unaltered after the winget installation of OpenSSH.
```

### Error details

```console
ssh -V does not return the version installed as SSH cannot be found.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

8.9.1.0

**Comment by tgauth** [comment]
Yes - this is due to a limitation of the MSI that is documented [here]( https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI)

I think we can leave this open but maybe rename to capture that is due to the MSI, rather than WinGet

**Comment by upyesp** [comment]
Thanks for looking into this.  So, the winget package is a wrapper of the MSI installer, didn't know that. 

I've renamed the issue from winget to MSI installer.

It would certainly be an improvement to the user experience if the MSI installer, and therefore the winget package, updated the system path in include the folder for OpenSSH.

**Comment by jmairboeck** [comment]
This also causes SFTP to not work. After adding the installation directory to the PATH manually, SFTP works.
