### ISSUE TITLE
winget package id  Microsoft.OpenSSH installs a beta version, the package id should reflect this

### ISSUE THREAD

**Issue by upyesp** [PowerShell/Win32-OpenSSH#1966]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

When using `winget search openssh`, 1 result is returned,  Microsoft.OpenSSH.

This winget package appears to install the same version as the current MSI installer, as `ssh -V` returns the same version information for winget as the MSI installer.  Version, 8.9p1.

The GitHub release page identifies this as being a beta version.

The winget installer id, Microsoft.OpenSSH, does not reflect to the user that this package is not a production/stable release. The package id is misleading.  

### Expected behavior

```console
winget package id Microsoft.OpenSSH should be reserved for a stable version of OpenSSH.

A different package id should be used to identify beta versions, for example Microsoft.OpenSSH.beta
```

### Actual behavior

```console
`ssh -V` returns
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3

This is the same version information returned as the OpenSSH version installed by the MSI installer.  The NSI installer is identified on the GitHub release page as being a beta version, see https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.9.1.0p1-Beta
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

8.9p1

**Comment by tgauth** [comment]
We can update the version tag to 8.9.1.0p1-Beta under Microsoft.OpenSSH to distinguish between production & beta releases

**Comment by upyesp** [comment]
Hi, 

Updating the version tag to 8.9.1.0p1-Beta would make it clearer.

However, thinking about the general use of winget, with other apps, the convention seems to be that none-production versions indicate this as a suffix in the id of the winget package.  For example, these Microsoft winget packages:

Microsoft.PowerShell.Preview
Microsoft.WindowsTerminal.Preview
Microsoft.VisualStudioCode.Insiders

These exist, in addition to the following:

Microsoft.PowerShell
Microsoft.WindowsTerminal
Microsoft.VisualStudioCode

So I think user expectations would be that Microsoft.OpenSSH is for the latest stable release?  

From a different perspective... a benefit of winget is that people/organisations produce PowerShell scripts to automate the installation of apps.   Also to update apps to their latest version.  If a single id of Microsoft.OpenSSH is used for both stable and beta releases, then such automated scripts could inadvertently result in over-writing a stable release of OpenSSH with a newer, but beta, release.

If possible, having 2 winget ids, with 1 for stable and another for beta/preview, would be preferable.

**Comment by tgauth** [comment]
v8.9.1.0 is now available on WinGet under Microsoft.OpenSSH.Beta
