### ISSUE TITLE
ssh-client: browsing bash history via cursor-up/down doesn't work

### ISSUE THREAD

**Issue by GitMensch** [PowerShell/Win32-OpenSSH#197]
Client: OpenSSH-Win64 ssh 16/04/05
Server: sshd on SLES
User Shell Server: bash
User Shell Client: tested both cmd.exe and powershell.exe

I can browse the history when I connect to the server via PuTTY, but not when I connect via OpenSSH-Win64 ssh.

Is this a common problem?
Is there something I can do to fix/workaround this issue on my local setup?

**Comment by strahinjanis** [comment]
It's not only about the cursors keys, even ESC doesn't work, this makes a native shells (powershell/cmd) pretty useless even SSHd is runnin.

**Comment by manojampalam** [comment]
#122
