### ISSUE TITLE
ProxyCommand Token Replacement doesn't work with SCP.exe (OpenSSH V8.6.0.0 and later)

### ISSUE THREAD

**Issue by seanyen** [PowerShell/Win32-OpenSSH#1972]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

1. Install the latest version of OpenSSH.
2. Run scp like: `scp -v -o ProxyCommand="c:\foo\bar.exe %h %p" ...`
3. Check the scp verbose logs to see how it is going to execute the ProxyCommand.

### Expected behavior

```console
Expect the `%h` and `%p` to be replaced with the hostname and port respectively.
```

### Actual behavior

```console
They are replaced by some random content strings.

This seems to be a regression. The ProxyCommand works fine in V8.1.0.0.

BTW, just some observation, if I am doing the random % tokens like scp -o ProxyCommand="C:\foo\bar.exe %s %d %c" ...

Then the SCP will compose something similar to what `printf` behaves. (For example, "C:\foo\bar.exe (null) -1883202610 \357\277\275".)

It could be a clue what's wrong there.
```

### Environment data

```PowerShell
None
```

### Version

V8.9.1.0, V8.9.0.0, V8.6.0.0

**Comment by tgauth** [comment]
Thanks for raising this issue! Just a note - I think the affected versions are V8.9.1.0 & V8.9.0.0. I am not able to repro with V8.6.0.0.
