### ISSUE TITLE
Support MINGW based build

### ISSUE THREAD

**Issue by fjaenal** [PowerShell/Win32-OpenSSH#198]
I am getting an issue when building with win32_build, the error comes when start to make the "openbsd-compat". (Out of all instructions the error happens on make) Looks I am missing something to install.

The error is:
(cd openbsd-compat && make)
make[1]: Entering directory '/cygdrive/c/views/opt/Win32-OpenSSH-3_19_2016/openbsd-compat'
i686-w64-mingw32-gcc -g -O2 -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fn
o-builtin-memset -I/cygdrive/c/views/opt/Win32-OpenSSH-3_19_2016/contrib/win32/win32compat/includes -I/cygdrive/c/views/opt/Win32-OpenSSH-3_19_2016/openbsd-comp
at -I/cygdrive/c/views/opt/Win32-OpenSSH-3_19_2016/contrib/win32/win32compat/includes -I/cygdrive/c/views/opt/Win32-OpenSSH-3_19_2016/libkrb -I/usr/local  -I. -
I.. -I. -I./.. -I/cygdrive/c/views/opt/Win32-OpenSSH-3_19_2016/../openssl-1.0.2d/include  -DHAVE_CONFIG_H -c arc4random.c
In file included from /usr/i686-w64-mingw32/sys-root/mingw/include/sys/types.h:81:0,
                 from ../includes.h:31,
                 from arc4random.c:27:
/usr/i686-w64-mingw32/sys-root/mingw/include/_mingw_off_t.h:24:17: error: conflicting types for ‘off_t’
 typedef off64_t off_t;
                 ^
In file included from ../includes.h:28:0,
                 from arc4random.c:27:
/cygdrive/c/views/opt/Win32-OpenSSH-3_19_2016/contrib/win32/win32compat/includes/sys/compat-types.h:10:14: note: previous declaration of ‘off_t’ was here
 typedef long off_t;
              ^
In file included from arc4random.c:27:0:
../includes.h:33:41: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h> /\* For CMSG_\* */

Also the sys/socket.h error puzzle me. Should we be using winsock2.h instead? At least when the arch is Windows 32

This happens with the 5/4/2016 and with the 19/3/2016 versions.
The openssl library used is: openssl-1.0.2d
The zLib version is: zlib-1.2.8
hosts: host=i686-win64-mingw32
build: build=i686-win64-mingw32

My operating system is a Windows 7 64 bits.
Cygwin is the latest 32 bits install.

Is there something missing in the documentation for installing it?

Thanks a lot Francisco

**Comment by fjaenal** [comment]
i think I know what is happening, in the version that is the 4_5_2016.zip with the source code has only this includes (contrib/win32/win32compat/includes/sys/):

$ ls -ltr contrib/win32/win32compat/includes/sys/
total 5
-rwxrwx---+ 1 Administrators Domain Users 126 Apr  5 22:12 un.h
-rwxrwx---+ 1 Administrators Domain Users 435 Apr  5 22:12 uio.h
-rwxrwx---+ 1 Administrators Domain Users 137 Apr  5 22:12 resource.h
-rwxrwx---+ 1 Administrators Domain Users 257 Apr  5 22:12 param.h
-rwxrwx---+ 1 Administrators Domain Users 131 Apr  5 22:12 ioctl.h

However in the actual master it also has the socket.h include.

**Comment by fjaenal** [comment]
However still giving the _mingw_off_t.h:24:17: error: conflicting types for ‘off_t’. And also several warnings.

**Comment by manojampalam** [comment]
mingw build is currently broken. Can you use the VS option instead?

**Comment by maertendMSFT** [comment]
Wont fix
There is not a large customer ask, we will happy review a community PR.
