### ISSUE TITLE
BANNER option not working

### ISSUE THREAD

**Issue by jberry** [PowerShell/Win32-OpenSSH#1980]
When setting up this openssh-portable on Windows Server, the included "sshd_config" config file shows the BANNER option.  However trying to actually display a Banner does not seem to be working.

Is there any special compile or config that needs to happen to enable that feature, or is it just a non-supported option currently for Windows running openssh server?

**Comment by vthiebaut10** [comment]
Hi @jberry, if you correctly update the value of the Banner property in the sshd_config file restart sshd in the server, then the banner should be displayed before authentication when connecting to the server. 
I can't repro your error on Windows Server 2019. Can you share more information? What version of OpenSSH are you using? What version of Windows Server?

**Comment by jberry** [comment]
We opened a ticket against Microsoft on this; it appears the win32 openssh server expects a banner file inside C:\windows\system32, but no where is that mentioned in configs or docs that we found.

**Comment by vthiebaut10** [comment]
@jberry I don't see that behavior when testing on Windows Server 2019 with OpenSSH 8.9. I tried placing the banner file on different directories, and it always gets displayed correctly. Why do you say it expects a banner file inside C:\windows\system32? Was that by trial and error? Can you confirm the version of OpenSSH that you are using?

**Comment by maertendMSFT** [comment]
@jberry, can you provide more info here?

Otherwise we will need to close this issue as a "no repro"

**Comment by jberry** [comment]
Go ahead and just close it, we dealt with this months ago via a MS ticket and I don't have any test environments left to reproduce it anymore
