### ISSUE TITLE
Fish shell garbled text

### ISSUE THREAD

**Issue by howdoicomputer** [PowerShell/Win32-OpenSSH#199]
I have `fish` running on a remote server and I get garbled text:

```

 * Documentation:  https://help.ubuntu.com/

12 packages can be updated.
0 updates are security updates.


Last login: Thu Apr 28 15:10:01 2016 from 192.168.1.174
erWelcome to fish, the friendly interactive shell
Type help for instructions on how to use fish                                                                                                                                                                                                ls
esktop/
         ocuments/  Downloads/  Music/  Pictures/  Public/  Templates/  Videos/
/tlerΓÅÄ
Γ₧£  ~
```

FYI.

**Comment by dragon788** [comment]
This may be related to the fact that it isn't interpreting escape sequences correctly. If you disable colors do you get less issues/corruption?

**Comment by bagajjal** [comment]
Please test with the latest release. 
For more information go through https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

If you still have issues, then please raise a new issue
