### ISSUE TITLE
certificate authentication failing with sshd: error: Certificate does not contain an authorized principal

### ISSUE THREAD

**Issue by leocoolmitra** [PowerShell/Win32-OpenSSH#1991]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

I am trying to setup certifiate authentication in my test lab and after setting it up when i try to SSH i get this error
sshd: error: Certificate does not contain an authorized principal

I have signed my user certificate with principal user1@contoso.local and in my authorized_principles file under programdata\ssh i have contoso.local\user1.
I have also tried using user1@contoso.local and user but still the same error.

### Expected behavior

```console
should let me ssh in from client to server without password
```

### Actual behavior

```console
fails with error.
```

### Error details

```console
sshd: error: Certificate does not contain an authorized principal
```

### Environment data

```PowerShell
server win 2022 = OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
client windows 10 OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
```

### Version

OpenSSH_for_Windows_8.1p1

**Comment by tgauth** [comment]
Please see https://github.com/PowerShell/Win32-OpenSSH/issues/1055#issuecomment-362470985
