### ISSUE TITLE
Inconsistent (wrong?) resolving of shell-escaping compared to "standard" OpenSSH when using withing standard Windows cmd line

### ISSUE THREAD

**Issue by robsan00** [PowerShell/Win32-OpenSSH#1992]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

The resolving of shell-escaping seems to be different compared to when using "standard" OpenSSH. I have ran into this because some automation code I wrote worked on a machine with MinGW installed, that had "OpenSSH_8.5p1, OpenSSL 1.1.1k  25 Mar 2021" in the path, while on another Windows machine, where the standard Windows OpenSSH path variable had higher priority it did not work.

What I started with: I used the Python module "shlex" to get a properly shell-escaped command:
```python
from shlex import quote
print(quote(f"/bin/sh -c {quote('ls -la')}"))

'/bin/sh -c '"'"'ls -la'"'"''
```
When I use this shell command with the standard OpenSSH it works fine, however with e.g. "OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.2" it does not.

Remark: this only is true when calling ssh.exe within cmd.exe, using it in a PowerShell does not show this problem.

I am not sure if this is an issue (I mean for me in my concrete case it is, but maybe expecting that a POSIX shell escape works fine within a Windows cmd.exe is a wrong expectation by me), but the inconsistency between the different OpenSSH versions is at the very least curious.

### Expected behavior

```console
ssh <user>@<ip> '/bin/sh -c '"'"'ls -la'"'"''
should work

Standard OpenSSH resolves this as

debug1: Sending command: /bin/sh -c 'ls -la'
```

### Actual behavior

```console
"OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.2" resolves the command as

debug1: Sending command: '/bin/sh -c '''ls -la''''
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.2

**Comment by PaulHigin** [comment]
Resolving this as external behavior of cmd.exe.  Workaround is to use PowerShell or cmd.exe specific escaping.

**Comment by mgkuhn** [comment]
The command-line syntax of `cmd.exe` and a POSIX shell could hardly be more different. For starters, the escape character is `^` and not `\`, and the way `"` and `\` are parsed is very different. The best documentation of the `cmd.exe` syntax that I know of is [this Stackoverflow post](https://stackoverflow.com/a/4095133).

Also, unlike the POSIX shell, `cmd.exe` does not parse the command-line arguments into `argv[]`. It it instead hands over the entire command line to the process, which has to do its own command-line parsing. This is usually done by the language run-time used, not by the application software. You should therefore also look into [how Microsoft C parses a command-line into argv[]](https://learn.microsoft.com/en-us/cpp/c-language/parsing-c-command-line-arguments?view=msvc-170). Again, this is *very* different from how a POSIX shell does it, especially regarding `"` and `\`.

SSH doesn't really do any escaping of command lines. SSH simply receives `argv[]` from the C run-time, joins arguments with spaces if there are more than one, and then passes a single string as the entire command-line to the shell at the other end, which then may start parsing it into its constituent parts.

**Comment by mgkuhn** [comment]
By the way, in case you want to see how shell escaping for `cmd.exe` needs to be done properly, have a look at [this implementation](https://github.com/JuliaLang/julia/blob/532125d51d23f22c3fd117fe8a37c158fe16ac62/base/shell.jl#L314) in the run-time environment of the Julia programming language, which does it correctly. It is surprisingly complicated, and took me quite a while to figure out!

**Comment by mgkuhn** [comment]
Your Python example implemented in [Julia](https://julialang.org/) would be
```julia
julia> print(Base.shell_escape_wincmd(
  Base.escape_microsoft_c_args(
    "ssh", "linux.cl.cam.ac.uk", "/bin/sh -c $(Base.shell_escape_posixly(Base.shell_escape_posixly("ls",  "-la")))")
))
ssh linux.cl.cam.ac.uk "/bin/sh -c 'ls -la'"
```
which works fine in cmd.exe as
```
C:\Users\mgkuhn>ssh linux.cl.cam.ac.uk "/bin/sh -c 'ls -la'"
total 648276                                                             
drwxr-x--x 236 mgk25 mgk25            73728 Oct 27 11:29 .               
drwxr-xr-x   3 root  root                 0 Oct 27 11:34 ..              
[...]
```
but which is really not very interesting, as your `ls -la` command doesn't contain any `cmd.exe` metacharacters.

Try something with meta characters, such as echoing `^"^`:
```julia
julia> print(Base.shell_escape_wincmd(
  Base.escape_microsoft_c_args(
    "ssh", "linux.cl.cam.ac.uk", "/bin/sh -c $(Base.shell_escape_posixly(Base.shell_escape_posixly("echo",  "^\"^")))")
))
ssh linux.cl.cam.ac.uk "/bin/sh -c 'echo '\''^\"^^'\'''^"
```
which also works fine:
```
C:\Users\mgkuhn>ssh linux.cl.cam.ac.uk "/bin/sh -c 'echo '\''^\"^^'\'''^"
^"^
```
