### ISSUE TITLE
Regression of 1545

### ISSUE THREAD

**Issue by roblourens** [PowerShell/Win32-OpenSSH#1993]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

In https://github.com/PowerShell/Win32-OpenSSH/issues/1545, an issue was fixed with piping into ssh without a command, eg

```
$ echo "echo test" | ssh -T win64bot3
client_loop: send disconnect: Broken pipe
```

Downstream issue: https://github.com/microsoft/vscode-remote-release/issues/7272#issuecomment-1282862510

I verified this as fixed in the 8.6 beta. In the issue above, it seems like the official 8.6 release actually has this issue. I haven't verified that myself. But I can verify it with the 8.9 beta from the releases page.

### Expected behavior

```console
It should echo "test"
```

### Actual behavior

```console
Now it fails with `client_loop: send disconnect: Broken pipe`
```

### Environment data

```PowerShell
PS C:\Users\roblou> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
```


### Version

8.9.1.0-beta

### Visuals

_No response_

**Comment by PaulHigin** [comment]
I cannot repro this in the latest builds.  But in addition, I feel the repro steps above are incorrect.  As pointed out in the original issue (https://github.com/PowerShell/Win32-OpenSSH/issues/1545#issuecomment-581044530), you need to specify the command on the server that accepts the piped input.

```powershell
echo "test" | ssh win64bot3 pwsh
PS C:\ > "test"
test
```

**Comment by roblourens** [comment]
What does "latest builds" mean, what version exactly?

The original issue was about how it should work without specifying the command. Specifying the command is a workaround. This is an important scenario for vscode's Remote-SSH extension.

**Comment by PaulHigin** [comment]
I was testing v8.9 and v9.1, but I see that the original fix went in v8.6 and it worked there.  So this does look like a regression.

**Comment by vthiebaut10** [comment]
Regression will be fixed on the next release (v9.1).

**Comment by roblourens** [comment]
Thank you!

**Comment by roblourens** [comment]
Do you know what the timeline is like for 9.1 reaching users via Windows Update?

**Comment by PaulHigin** [comment]
This was fixed with this PR (null ptr check): https://github.com/PowerShell/openssh-portable/pull/616

**Comment by roblourens** [comment]
Thanks, but do you know when it will reach Windows users?

**Comment by vthiebaut10** [comment]
@roblourens It takes a number of months to ship the newer versions of OpenSSH to Windows. But you can get the beta version from the [Releases](https://github.com/PowerShell/Win32-OpenSSH/releases) page in this repo once we release it and install it using the instructions from our [Wiki](https://github.com/PowerShell/Win32-OpenSSH/wiki).

**Comment by roblourens** [comment]
I understand that it takes a number of months- the last time I reported a bug in this project, it took over a year. So I'm wondering whether you have a sense of what the timeline for the next release is like or is it to early to know?

**Comment by maertendMSFT** [comment]
Unfortunately, we cannot comment on Windows release timelines.  Our latest beta bits will always ship on GitHub and our in-box version be included in a Windows release at a later date.
