### ISSUE TITLE
ctrl+c exits client instead of being sent to server

### ISSUE THREAD

**Issue by godefroi** [PowerShell/Win32-OpenSSH#20]
While ctrl+c does not exit the client while it's prompting for a password upon connection (#5), once the connection is complete, ctrl+c is processed by the client (terminating it) instead of being sent to the server. This behavior is not consistent with the other SSH clients I've used on Windows (such as the Cygwin one).

**Comment by manojampalam** [comment]
We are fixing this issue in the upcoming release (in ~3 weeks).

**Comment by quamrulmina** [comment]
Fixed in upcoming release

**Comment by manojampalam** [comment]
Fixed in latest release
