### ISSUE TITLE
scp error " Bad packet size 0"

### ISSUE THREAD

**Issue by Otxandio** [PowerShell/Win32-OpenSSH#200]
Good afternoon,

I've been suffering a annoying problem when I try to copy any file via scp from Linux to Windows. Output always is:

/usr/bin/dbclient: Connection to Administrador@192.x.x.xxx:22 exited: Bad packet size 0
lost connection

I don't have problems connecting via SSH or copying files vis sftp. I do need to use scp for scripting purposes. 

Thanks in advance.

**Comment by ragnars-stuff** [comment]
Did you check if scp.exe is in you OpenSSH folder on windows?

scp was not in the build I was using, so I had to use sftp instead.

**Comment by Otxandio** [comment]
You're right, scp.exe isn't in the OpenSSH folder. I tried adding the file from another build and it didn't work.

I keep using sftp instead, just as you.

**Comment by manojampalam** [comment]
#106
