### ISSUE TITLE
sftp / scp regression from 8.6.0.0 to 8.9.1.0

### ISSUE THREAD

**Issue by maertendMSFT** [PowerShell/Win32-OpenSSH#2006]
### Discussed in https://github.com/PowerShell/Win32-OpenSSH/discussions/1997

<div type='discussions-op-text'>

<sup>Originally posted by **tdesaules** November 16, 2022</sup>
Hi guys ! 

I just move my openssh server version from 8.6.0.0 to 8.9.1.0
I can't see any issue on "pure" ssh usage but I get a "lost connection" from the client with an "unknow error" when I try to use scp or sftp

I didn't see an issue about, just to confirm before create one with more debug info.

I did the test from a Windows 10 client with the same openssh version.
The server is a Windows Server 2016 (1607 buid 14393.5356) 
I use a custom port (10022) and use ssh keys to authenticate.

have a nice day</div>

**Comment by tgauth** [comment]
In 8.9.1.0, the SYSTEM Path needs to be updated to include OpenSSH for SCP/SFTP usage, see https://github.com/PowerShell/Win32-OpenSSH/issues/1922#issuecomment-1082108871

(Starting with 9.1, the install will take care of this so it is no longer a manual step)

If that doesn't work, please provide the debug logs

**Comment by maertendMSFT** [comment]
@tdesaules, can you provide your logs or test the suggestion above?
