### ISSUE TITLE
cannot run sftp on version V8.9.1.0 on windows server 2012

### ISSUE THREAD

**Issue by maertendMSFT** [PowerShell/Win32-OpenSSH#2007]
### Discussed in https://github.com/PowerShell/Win32-OpenSSH/discussions/2001

<div type='discussions-op-text'>

<sup>Originally posted by **bogdan-atl** November 28, 2022</sup>
For some reason, the connection itself breaks, without error.,identical problem on windows 7

sftp -P 2200 -i id_ecdsa_sk_yubikey4 bogdan@192.168.0.93
Enter passphrase for key 'id_ecdsa_sk_yubikey4': 
Confirm user presence for key ECDSA-SK SHA256:x5swo2zbVQCcG6bcгc42VevBrrjjDgIBQK/eSravAkU
User presence confirmed
Connection closed.  
Connection closed</div>

**Comment by tgauth** [comment]
In 8.9.1.0, the SYSTEM Path needs to be updated to include OpenSSH for SCP/SFTP usage, see https://github.com/PowerShell/Win32-OpenSSH/issues/1922#issuecomment-1082108871

(Starting with 9.1, the install will take care of this so it is no longer a manual step)

If that doesn't work, please provide the debug logs

**Comment by maertendMSFT** [comment]
Closing as a duplicate of: https://github.com/PowerShell/Win32-OpenSSH/issues/2006
