### ISSUE TITLE
MSI for beta doesn't install ssh-agent

### ISSUE THREAD

**Issue by hut8** [PowerShell/Win32-OpenSSH#2014]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

First I followed the directions here on Windows 11 and got the SSH client working: https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=gui -- that package contains an SSH-Agent Windows service:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/363720/200651677-32cd17ba-2b05-4cb6-8366-c12e3e93edbd.png">

I ran into a bug in the SSH client (having to do with `Ctrl+Space`) that is fixed in the beta. I removed the OpenSSH "optional features" in the control panel, which (as I expected) also removed the SSH Agent. 

Then, I installed the beta using the MSI as per these instructions: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI#1-run-msi-installer

This installs the OpenSSH Server service, but doesn't install the Agent service. There is still an ssh-agent.exe that's in the right directory (`C:\Program Files\OpenSSH`), but no windows service gets installed. I looked through OpenSSHUtils.psm1 to try to find if there's something there. How do I add the agent service in the beta? I'm reporting this as a bug primarily because it's nowhere in the documentation (that I can find), and also perhaps there's something amiss with the MSI builder where it fails to do the service installer step for the agent (although it does install the server component).

It's very confusing that the development (and hopefully issues) happen here but the Wiki and releases are at https://github.com/powershell/Win32-OpenSSH -- that one has 270+ open issues. Should I be filing issues here?

### Expected behavior

```console
The agent service should be installed, just like the server service. Or at least there should be some documentation about how to do this.
```

### Actual behavior

```console
No agent service is installed in the beta.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3

**Comment by tgauth** [comment]
Yes, sorry it's confusing. Win32-OpenSSH is a legacy repo where we maintain issues/releases, although the active development is here in OpenSSH-Portable.

I'm not able to repro the ssh-agent service not being created via MSI install.

As a workaround, you can use the PowerShell cmdlet New-Service:
`New-Service ssh-agent`
when prompted, provide the path to ssh-agent.exe: 
`C:\Program Files\OpenSSH\ssh-agent.exe`

Otherwise, can you try rerunning the MSI with logging, as documented in https://learn.microsoft.com/en-us/windows/win32/msi/standard-installer-command-line-options: `/L* "<logname>.log"`

**Comment by hut8** [comment]
Wow, thanks for such a quick response. https://github.com/PowerShell/Win32-OpenSSH/issues/1914 is likely related since I'm using 64-bit. I'll update in a bit.

**Comment by floh96** [comment]
@tgauth i had the same problem when i upgraded openssh via winget I then uninstalled it and installed it via the pwsh script and it worked.
