### ISSUE TITLE
No echo when responding to unknown host or changed host key prompt

### ISSUE THREAD

**Issue by j18ter** [PowerShell/Win32-OpenSSH#202]
The "README.win32" file contains this entry: "Disabled stdin echo while reading password on Windows". It seems that the echo is being suppressed too early, and as a result it is already engaged when the user is prompted to confirm that an unknown host, or changed host key is acceptable.

This was observed with version 4_5_2016.

**Comment by bagajjal** [comment]
duplicate of #692
