### ISSUE TITLE
"1312, CredRead" while running "poetry add" through OpenSSH Server

### ISSUE THREAD

**Issue by hello8693** [PowerShell/Win32-OpenSSH#2022]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

> Excuse me for my poor English. I'm a Chinese.

Win11 x64 21H2 in Parallels Desktop 17

I use VSCode Remote to connect to my VM and copy my codes to it. I got this error when running `poetry add PySide2`.

```cmd
PS C:\Users\Hello8693\Project> poetry add PySide2

(1312, 'CredRead', '指定的登录会话不存在。可能已被终止。')
```

### Expected behavior

```console
I don't know that because this is the first time I use poetry.
```

### Actual behavior

```console
PS C:\Users\Hello8693\Project> poetry add PySide2

(1312, 'CredRead', '指定的登录会话不存在。可能已被终止。')
```

### Error details

```console
Oh...It seems that my powershell doesn't have a Get-Error...


Get-Error : 无法将“Get-Error”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写
，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ Get-Error
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-Error:String) [], CommandNotFoundException      
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

**Comment by maertendMSFT** [comment]
This does not appear to be an issue with Win32-OpenSSH.  Can you ask this on the VS Code remoting GitHub issues page? https://github.com/microsoft/vscode-remote-release/issues

Please reopen and provide SSH logs if you believe this to be an issue with WIn32-OpenSSH.
