### ISSUE TITLE
OpenSSH on Windows, Logs not showing file transfers or deletes and such

### ISSUE THREAD

**Issue by myrwjms** [PowerShell/Win32-OpenSSH#2026]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Hello, Ive seen a couple posts about this and that it was solved in version 8.6, we are on v9.0.0pa-beta but having same issue.

We are using sftp with open ssh, but i cant seem to get the logs to show things like who opened a file, deleted a file and so on.  
I can see things like who logged in and disconnected.  
In previous posts the issue seemed to be a rights issue.  Ive given the user administrative rights to try that out but no go, and rights to the local log file.
Ive tried with both an AD user and a local user.
Also tried using the local0 logfile and event viewer.

Feel like im just missing a setting somewhere.  
Ive tried setting the logging level to all levels, ive had it on INFO, Verbose and Debug3, cant see anything related to file deletes or uploads.  
Debug3 shows allot, but seems to be related to all SSH connection stuff, makes sense.

Ive seen in previous posts that when using the local0 logfile, that the logfile should be sftp-server.log, i dont have that, i just have the ssh.log file showing up,  So im wondering if im missing a setting to turn that on?

 my sshd_config is below

For this line
Subsystem	sftp	sftp-server.exe -d E:\SftpRoot -l INFO -f LOCAL0

Ive tried -l INFO, -l VERBOSE and -l DEBUG3
Ive restarted the OpenSSH service everytime ive made a change.  

thanks for any help.  

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey __PROGRAMDATA__/ssh/ssh_host_rsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_dsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ecdsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
SyslogFacility LOCAL0
LogLevel VERBOSE

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile	.ssh/authorized_keys

#AuthorizedPrincipalsFile none

# For this to work you will also need host keys in %programData%/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication yes
#PermitEmptyPasswords no

# GSSAPI options
#GSSAPIAuthentication no

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#PermitUserEnvironment no
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# override default of no subsystems
Subsystem	sftp	sftp-server.exe -d E:\SftpRoot -l VERBOSE -f LOCAL0

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	AllowTcpForwarding no
#	PermitTTY no
#	ForceCommand cvs server

ForceCommand internal-sftp

Match User ftptest
	ChrootDirectory "E:\SftpRoot\ftptest"

Match Group administrators
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys

### Expected behavior

```console
To see who is uploading and deleting files in log files
```

### Actual behavior

```console
Not seeing uploading and deleting files in log files or event viewer
```

### Environment data

```PowerShell
Windows 2019 Server
```

### Version

v9.1..0.0p1-Beta

**Comment by tgauth** [comment]
Since `ForceCommand internal-sftp` is set, the logging settings need to be added there.
Can you please try: `ForceCommand internal-sftp -l VERBOSE -f LOCAL0`

**Comment by myrwjms** [comment]
That did the trick, thank you so much:)
Will test some more but so far looks to be working for both the Local0 logfile and the Event Viewer if i switch it to AUTH

Thanks Again
