### ISSUE TITLE
Windows 11 OpenSSH 8.6p1, LibreSSL 3.4.3 ssh commands with HERE doc failing.

### ISSUE THREAD

**Issue by priyankabhosale** [PowerShell/Win32-OpenSSH#2039]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Remote SSH commands with [HERE Doc](https://tldp.org/LDP/abs/html/here-docs.html) are failing to execute on Windows 11 (22H2 OS Build 22621.1250) with OpenSSh Version 8.6P1 (OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3).

I have another Windows 11 machine with Openssh 8.1P1 where remote ssh commands with HERE are working fine.

Sample SSH commands with HERE DOC-

```
ssh user@$MACHINE << EOF

 if exist ${GIT_WORKSPACE}  rmdir /q /s ${GIT_WORKSPACE}
 
 del /q /s /f "C:\Users\user\AppData\Local\temp\*" > NUL

 mkdir ${GIT_WORKSPACE}

 cd ${GIT_WORKSPACE}

 git checkout $BRANCH

 mkdir ${VIRTUAL_ENV_WORKSPACE}
 exit
EOF
```

### Expected behavior

```console
Interactive SSH commands with HERE doc or multiple commands separated newline shall work with OpenSSH 8.6p1
```

### Actual behavior

```console
SSH connection gets timed out
```

### Error details

```console
Pseudo-terminal will not be allocated because stdin is not a terminal.
client_loop: send disconnect: Broken pipe
```

### Environment data

```PowerShell
Windows 11 OpenSSh Version 8.6P1 (OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3).
```

### Version

8.6

**Comment by maertendMSFT** [comment]
@priyankabhosale, can you try this with the latest release?

**Comment by priyankabhosale** [comment]
Hi @maertendMSFT,
Tried with latest release- OpenSSH_for_Windows_9.2p1  i.e. https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v9.2.0.0p1-Beta and it did work.

Thank you.
