### ISSUE TITLE
sftp won't log into OS X machine

### ISSUE THREAD

**Issue by ChaseFlorell** [PowerShell/Win32-OpenSSH#204]
when I am in Terminal on my Mac, I can connect to `sftp localhost` without issue.
My firewall is off, so it should accept remote connections as well.

When I try to connect using sftp from the latest release here, I get the following output

> fork: The system cannot find the file specified.

![snap22](https://cloud.githubusercontent.com/assets/471626/15221312/3653b3c2-1828-11e6-9aba-769976f38ecd.png)

I'm trying to find information on what this error is, but am coming up empty handed. What is this exactly?

_note: the very top of the screenshot is my exiting an SSH connection. SSH allows me to login just fine._

**Comment by fg-fg** [comment]
Did you solve this issue
