### ISSUE TITLE
ssh-add -c fails with communication with agent failed

### ISSUE THREAD

**Issue by Daniel-Nashed** [PowerShell/Win32-OpenSSH#2042]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

I am trying to add keys to the SSH agent, with the confirmation option `-c`.
The same functionality works on Linux.

Here is the exact error message:

```
ssh-add -c my_ed_key
Could not add identity "my_ed_key": communication with agent failed
```
Also other applications can't use this functionality with the current ssh-agent on Windows

It works when not using `c `

```
ssh-add  my_ed_key
Identity added: my_ed_key (user@mymachine)
```

### Expected behavior

```console
Expected behavior would be that the key can be added and the agent would ask for permission if the key is used.
```

### Actual behavior

```console
ssh-add -c my_ed_key
Could not add identity "my_ed_key": communication with agent failed
```

### Error details

```console
ssh-add -c my_ed_key
Could not add identity "my_ed_key": communication with agent failed
```

### Environment data

```PowerShell
OpenSSH_for_Windows_9.2p1, LibreSSL 3.6.1
```

### Version

OpenSSH_for_Windows_9.2p1, LibreSSL 3.6.1

**Comment by vthiebaut10** [comment]
Confirmation relies on ssh-askpass, and Windows doesn't have an ssh-askpass equivalent; therefore, the -c parameter for ssh-add is not supported for Windows.
