### ISSUE TITLE
Typo in build instructions

### ISSUE THREAD

**Issue by JeffreyJHerr** [PowerShell/Win32-OpenSSH#2044]
### Summary of the new feature / enhancement

In the build instructions located at https://github.com/PowerShell/Win32-OpenSSH/wiki/Building-OpenSSH-for-Windows-(using-LibreSSL-crypto) under sections referencing the Windows SDK the text reads as 10.0.17663.0 in the bullet point, in the sub bullet and in the referenced image it is 10.0.17763.0, this happens again under the Retarget Projects bullet point, text is 10.0.17663.0 but the image is 10.0.17763.0

**Comment by tgauth** [comment]
Thanks for catching this! Wiki page has been updated.
