### ISSUE TITLE
Running a batch of commands through ssh

### ISSUE THREAD

**Issue by timcerl** [PowerShell/Win32-OpenSSH#205]
I am very much a tyro when it comes to SSH.
I am trying to use this to configure network switches.  Working interactively works fine.  I can connect with password to the network switch, and that leaves me at the switch's CLI prompt.  But what I want to do is to be able to script commands to be executed by the switch.  Are there instructions on how to do something simple list this in a script?
Log into the switch
Pass one or more commands
test the return code to see if there was an error with the passed commands.
log off the switch.

Thanks.

**Comment by manojampalam** [comment]
you can execute a single command by doing 
ssh ..... [command]

**Comment by timcerl** [comment]
How?
The first SSH command logs me into the switch.  At that point my PowerShell window is connected to the switch's CLI.  Anything I enter will be processed by the CLI, so if I enter 'ssh  [command]' it will be read by the CLI.
Is there a way to establish a session to the switch without ending up at the switch's CLI prompt so that I can continue entering commands?  That is what I have not been able to figure out.

**Comment by timcerl** [comment]
Sorry.  I meant to ask if there is a way to operate this like a PSSession.

**Comment by manojampalam** [comment]
At this point, no. You'll have to run each command individually in a separate session. i.e you need to run ssh ... [command] repeatedly. ssh.exe can automatically authenticate if configured to use key based authentication. 

At a later point, when Win32 OpenSSH supports "multiplexing master process", you can create a session once (perhaps in a background process), and route each of your commands through the created connection.

**Comment by timcerl** [comment]
Okay.  That makes sense.  I'll look at the documentation to figure out the key auth.
Thanks!
