### ISSUE TITLE
Service Start on Windows Server 2012 R2 x64

### ISSUE THREAD

**Issue by wayneworkman** [PowerShell/Win32-OpenSSH#206]
I've followed the write-up in the wiki for installing OpenSSH, however when I try to start the service using Powershell the command hangs forever. If I navigate through the GUI to Services and right click and pick "Start" it says:

"Error 1067: The process terminated unexpectedly."

**Comment by manojampalam** [comment]
Typically happens when either
- sshd_config does not exist
- host keys are not in place
  Try these troubleshooting steps
  https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting%20Steps
