### ISSUE TITLE
Bad permission. Try removing permissions for user: NT AUTHORITY\\Authenticated Users (S-15-11)

### ISSUE THREAD

**Issue by ericchansen** [PowerShell/Win32-OpenSSH#2061]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Fresh Windows 11.

Created a ~/.ssh/config with the following content.

```
Include E:\repos\shared-ssh-config\*.conf
```

### Expected behavior

I would hope that this should just work out of the box.

### Actual behavior

```console
Bad permissions. Try removing permissions for user: NT AUTHORITY\\Authenticated Users (S-1-5-11) on file E:/repos/shared-ssh-config/shared.conf.
Bad owner or permissions on E:/repos/shared-ssh-config/shared.conf.
```

### Environment data

```PowerShell
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.1037
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1037
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

PSVersion                      5.1.22621.1037

**Comment by vthiebaut10** [comment]
@ericchansen "Authorized Users" shouldn't have permission to Write or Modify the shared file. In that case, Authenticated users may have Read and Execute permissions, and only Administrators should have Write and Modify permissions.
Please let me know if this resolves your problem.

**Comment by vthiebaut10** [comment]
Closing this issue since we got no response if the issue is fixed. Feel free to reopen if you need further assistance.

**Comment by anjanesh** [comment]
What's the solution ?

**Comment by vthiebaut10** [comment]
The solution is to remove bad permissions from the target file. Try removing permission from "Authenticated Users". If the problem persists even though the permissions have been fixed, then a more detailed investigation will be needed to identify the problem.

**Comment by anjanesh** [comment]
I managed to get this to work in WSL via sudo.
(I converted the ppk to pem)
