### ISSUE TITLE
winget should allow per-user install (and not require admin)

### ISSUE THREAD

**Issue by tgauth** [PowerShell/Win32-OpenSSH#2067]
### Discussed in https://github.com/PowerShell/Win32-OpenSSH/discussions/2066

<div type='discussions-op-text'>

<sup>Originally posted by **blakeduffey** May  5, 2023</sup>
winget install --id Microsoft.OpenSSH.Beta

should install on a per user basis (this would allow install without admin rights)</div>

**Comment by tgauth** [comment]
@blakeduffey - to clarify, would this be to install the ssh client via WinGet on a per-user basis? 

The ssh server requires admin rights to complete its set-up

**Comment by blakeduffey** [comment]
@tgauth - thanks for pointing this out.  Honestly it didn't occur that winget was installing the server component :)

In a corporate environment where users don't have local admin, being able to install software without local admin is very useful.  My goal here is to give the users the OpenSSH client without engaging the service desk.

Last time I checked the version of OpenSSH native/pre-installed was perpetually out of date.

Thanks much

**Comment by tgauth** [comment]
In that case, would downloading the [zip](https://github.com/PowerShell/Win32-OpenSSH/releases/download/v9.2.2.0p1-Beta/OpenSSH-Win64.zip) that is published with each release be sufficient workaround?

**Comment by blakeduffey** [comment]
Thanks for the feedback.  Currently that's what I'm doing:

```
msiexec /a https://github.com/PowerShell/Win32-OpenSSH/releases/download/v9.2.2.0p1-Beta/OpenSSH-Win64-v9.2.2.0.msi /qb TARGETDIR="$env:LOCALAPPDATA\Programs\OpenSSH"
 
[Environment]::SetEnvironmentVariable("PATH", $Env:PATH + ";$env:LOCALAPPDATA\Programs\OpenSSH\program files\openssh", [EnvironmentVariableTarget]::User)
```

It works well enough (if a bit kludgey)

Ideally winget would have some kind of switch to install just the client piece (and not require admin) - but I realize that may be a lot of work for a minimal return.  :)

We have (pretty universally) moved away from using PuTTY in favor of openssh (tabs in Windows Terminal, Visual Code remote development integration, etc).

Thanks for listening.
