### ISSUE TITLE
Get-CimInstance fails with "Access Denied" when run over a ssh connection

### ISSUE THREAD

**Issue by sba923** [PowerShell/Win32-OpenSSH#2077]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

When run in a local (or RDP) session, `Get-CimInstance` works without elevation:

![image](https://github.com/PowerShell/Win32-OpenSSH/assets/12860484/27bf6c82-87ba-4a95-92fe-aa29687f9549)

When run using the exact same (non-admin) account, but over a ssh connection, `Get-CimInstance` fails with "Access Denied":

![image](https://github.com/PowerShell/Win32-OpenSSH/assets/12860484/8dadd67f-19f2-43cd-b889-7e7ad9b38c1c)

### Expected behavior

```console
`Get-CimInstance` should work fine over a ssh connection, without granting elevation permission to the account (otherwise remote ssh clients would be granted undesired rights to the target non-admin account).
```

### Actual behavior

```console
`Get-CimInstance` fails with "Access Denied"
```

### Environment data

```PowerShell
(target machine)

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
 
Target system is: Microsoft Windows Server 2019 Datacenter 10.0.17763,
```

### Version

9.1.0.0

**Comment by tgauth** [comment]
We're able to repro this with OpenSSH 9.2 also - will investigate further

**Comment by vthiebaut10** [comment]
This limitation appears to be by design. The root cause seems to be that by default remote connections are not allowed to query WMI. In this github thread there are some workarounds for this:
https://github.com/microsoft/vscode-remote-release/issues/2648#issuecomment-1293832539

You can find further documentation here: https://learn.microsoft.com/en-us/windows/win32/wmisdk/connecting-to-wmi-on-a-remote-computer?source=recommendations

**Comment by NoMoreFood** [comment]
See https://github.com/PowerShell/Win32-OpenSSH/issues/1349 for root cause.
