### ISSUE TITLE
sshd.log ERROR was happened, and i can't use publickey to connected

### ISSUE THREAD

**Issue by g1im2** [PowerShell/Win32-OpenSSH#208]
when i create sshd service and restart my PC, "sshd.log" become biger and biger which take one minutes. and i use wiki's method to install sshd and put the publickey in .ssh, another computer  provide the publickey to me, it can't connect my computer, i don't kown why, but , at this time, i found file with "sshd.log" was strange. and i check with powershell command "get-service sshd", it was running status.

my os: windows 7 64bit

install step:
1. use administrator install .\install_sshd.ps
2. copy ssh-lsa.all to C:\Windows\System32
3. use regedit to modify reg, add values with "ssh-lsa" into "Authentication Packages"
4. into install folder and user powershell command run "ssh-keygen.exe -A"
5. create a folder which rename ".ssh" in /users/users_name/ and put the publickey which was anthoer computer provide me.
6. closed firewall(all firewall)
7. restart my PC and start service sshd

win32-Openssh-version: last-version with 4_5 for 64bit
download from github's release

some error was happened:
1. some logs which appear in sshd.log, last one was repeat forever if i don't stop service with sshd
like this
1892 20:05:56 367 Server listening on :: port 22.
1892 20:05:56 367 Server listening on 0.0.0.0 port 22.
1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。

1892 20:05:56 367 error: accept: 操作成功完成。
1. i use another computer which provide publickey, it can't connect to install win32-openssh service's PC.(another computer use UBuntu OS and installed openssh)
2. if i running sshd service, my cpu usage like 50 percents and computer become slower

**Comment by DarwinJS** [comment]
If you use the chocolatey package it explicitly sets the logging to quiet which seems to fix this for most people.

If you already have chocolatey installed you can do "choco install win32-openssh"

If you don't have chocolatey (or don't know what it is) the following strings can be dropped directly into an elevated powershell prompt to install it and install the package all at once:

[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {[bool]1};set-executionpolicy RemoteSigned -Force -EA 'SilentlyContinue';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/DarwinJS/ChocoPackages/master/win32-openssh/InstallChoco_and_win32-openssh.ps1'))

OR for the server:

[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {[bool]1};set-executionpolicy RemoteSigned -Force -EA 'SilentlyContinue';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/DarwinJS/ChocoPackages/master/win32-openssh/InstallChoco_and_win32-openssh_with_server.ps1'))

**Comment by g1im2** [comment]
@DarwinJS thanks for your answer, Choco installer just set log silent, but it can't solve my problem, the cpu usage was still high, about 50 percent, and I still can't use public key to connect it. I don't know why, and I found the choco installer do same thing like me if I install by manual, all steps was according by wiki. If you can help me, and give me some analysis method to find this problem, I will be very grateful to you, thanks

**Comment by botfarmer** [comment]
Try with another port, e.g. 2222

**Comment by manojampalam** [comment]
Check if these steps help https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting%20Steps
