### ISSUE TITLE
Sshd service crashes on start when i append line at the end of sshd_config

### ISSUE THREAD

**Issue by kotenok2000** [PowerShell/Win32-OpenSSH#2081]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Append "Compression yes" at the end of C:\ProgramData\ssh\sshd_config
Run net stop sshd
run net start sshd
It doesn't start

### Expected behavior

```console
It parses sshd_config successfully
```

### Actual behavior

```console
It crashes on start
```

### Error details

```console
C:\Users\frolo>net start sshd
The OpenSSH SSH Server service is starting.
The OpenSSH SSH Server service could not be started.

A system error has occurred.

System error 1067 has occurred.

The process terminated unexpectedly.
```

### Environment data

```PowerShell
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

### Visuals

Bad sshd config 
[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/11752092/sshd_config.txt)
Good sshd config
[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/11752098/sshd_config.txt)

**Comment by matsmcp** [comment]
The Issue is that you are trying to add compression under a match rule. Compression is not allowed under a match rule.

If you move your compression line so that it appears before the match line it should work

something like 

```
.......
# override default of no subsystems
Subsystem	sftp	sftp-server.exe

#Enable compression
Compression yes

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	AllowTcpForwarding no
#	PermitTTY no
#	ForceCommand cvs server

Match Group administrators
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys



```
Tested on 9.2p1

**Comment by tgauth** [comment]
In addition, to validate changes to sshd_config - run `sshd -T` 
This will look for sshd_config in C:\ProgramData\ssh\ - can also optionally specify a different path with `-f`
If the config file is valid, it should return the configuration state, otherwise it will point to the invalid configuration lines
