### ISSUE TITLE
Linux can be updated remotely. Windows cannot. It should.

### ISSUE THREAD

**Issue by doctorpangloss** [PowerShell/Win32-OpenSSH#2083]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

I ought to be able to update my Windows installation from an OpenSSH session the same way I update anything else, like my Linux servers.

 1. Run the following script:
```
Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
Install-Module -Name PSWindowsUpdate -Force
Get-WindowsUpdate -MicrosoftUpdate -AcceptAll -Install -IgnoreReboot
```
2. Observe the following error:
```
Get-WindowsUpdate : Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
At line:1 char:1
+ Get-WindowsUpdate -MicrosoftUpdate -AcceptAll -Install -IgnoreReboot
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsUpdate], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,PSWindowsUpdate.GetWindowsUpdate
```
 
3. Use the following workaround to install Windows Updates. It will cause your machine to reboot in the middle of automations; it doesn't block until updates are installed; it doesn't provide feedback if it fails.

```
Enable-WURemoting
Invoke-WuJob -Script { ipmo PSWindowsUpdate; Install-WindowsUpdate -AcceptAll -AutoReboot | Out-File "C:/Windows/PSWindowsUpdate.log"} -RunNow -Confirm:$false -Verbose -ErrorAction Ignore
```

### Expected behavior

```console
(Windows updates are installed)
```

### Actual behavior

```console
PS> Get-WindowsUpdate -MicrosoftUpdate -AcceptAll -Install -IgnoreReboot
...
Get-WindowsUpdate : Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
At line:1 char:1
+ Get-WindowsUpdate -MicrosoftUpdate -AcceptAll -Install -IgnoreReboot
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsUpdate], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,PSWindowsUpdate.GetWindowsUpdate
```

### Environment data

```PowerShell
$PSVersionTable

Name                           Value                                                                            
----                           -----                                                                            
PSVersion                      5.1.20348.1366                                                                   
PSEdition                      Desktop                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                          
BuildVersion                   10.0.20348.1366                                                                  
CLRVersion                     4.0.30319.42000                                                                  
WSManStackVersion              3.0                                                                              
PSRemotingProtocolVersion      2.3                                                                              
SerializationVersion           1.1.0.1
```

### Version

OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

**Comment by matsmcp** [comment]
Have you tried the same thing over WinRM?
Both WinRM and SSH runs in another Security context (Network Login) vs Console or RDP (Interactive User) and that has caused Issues before

**Comment by doctorpangloss** [comment]
> Both WinRM and SSH runs in another Security context (Network Login) vs Console or RDP (Interactive User) and that has caused Issues before

Is there a way to run sshd in a security context that permits Windows Update? Or is there a way to allow Windows Update to run in sshd's security context?

I understand Windows is a complex piece of software. There will be an instinct to "find" the "right person" for this issue. I would look up, not horizontally, because the issue is the result of a design flaw. 

The flaw is:

> Here's something Linux can do that Windows cannot: Linux can get updated remotely, Windows cannot.

That seems like a big deal to me. I wouldn't muddy it with the specifics of `sshd` or `WinRM` since it doesn't really matter.

**Comment by matsmcp** [comment]
The reason for the Question is that if it doesn't work with WINRM either when there is nothing the OpenSSH project can do to fix it on their own. There are a number of issues that relates to interactive/network logon and I can only hope that maybe @maertendMSFT has channels to report them internally (for example you cant write to the eventlog as a user in an SSH or winrm session due to the ACL that says admin or interactive user)

**Comment by doctorpangloss** [comment]
>  I can only hope that maybe @maertendMSFT has channels to report them internally.

@maertendMSFT This is not meant to be cranky. I am not sure what is going on with Microsoft with closing real issues on GitHub, this has been going on for at least since 2021. Unless there is a snippet that shows how to update Windows using the command line remotely, this issue isn't resolved.

I understand you don't decide the metrics here. The fastest route to zero is to disable the Issues tabs. I will stop reporting issues, and sophisticated Windows users can check out like they had in the past.

**Comment by maertendMSFT** [comment]
This is not an issue with Win32-OpenSSH, hence the issue needs to be closed on this repo. I understand the frustration here, but this is not the correct channel for this type of issue to be tracked. If you are looking for a contact in Windows for this issue, the best option would be to file a case with Microsoft/Windows support.

Normally, we would link another issue when closing if we are able to share it from another open-source repo, in this case I am unable to share this information as it is not a public repo and I am limited on what I can share on communications in Windows.

**Comment by vthiebaut10** [comment]
@doctorpangloss There are some Windows Update Agent COM APIs that are restricted for users using "NETWORK" Logon (see [here](https://learn.microsoft.com/en-us/windows/win32/wua_sdk/using-wua-from-a-remote-computer)), and that's why you aren't able to update Windows remotely. Those restrictions are not a bug in Win32-OpenSSH and are defined by design. I've seen different workarounds online, but I don't personally know what is the best one for your situation. I will update this thread if I can find a good workaround.

**Comment by doctorpangloss** [comment]
> I understand the frustration here

I understand your frustration too. 

>  I will update this thread if I can find a good workaround.

Thank you.

> Those restrictions are not a bug in Win32-OpenSSH and are defined by design...

I appreciate your support. I am trying to use Windows in an innovative way.

**Comment by mgkuhn** [comment]
The Bitvise SSH server allows configuration of the logon type between "network" and "interactive". Does using that solve your problem? https://bitvise.com/ssh-server-guide-logon-type

**Comment by mgkuhn** [comment]
The Bitvise SSH server allows configuration of the logon type between "network" and "interactive". Does using that solve your problem? https://bitvise.com/ssh-server-guide-logon-type
