### ISSUE TITLE
ssh and sftp sessions are no longer directed to user profile directory in 5_15_2016 release

### ISSUE THREAD

**Issue by manojampalam** [PowerShell/Win32-OpenSSH#209]
Logging in using the latest version will result in user's default directory set to %WINDIR%. This should instead be user's documents or profile directory.

**Comment by DTurkmen** [comment]
Is user's "Home Folder" taken into consideration (as set in user Properties)? Which build can I use to direct user to their home folders?

**Comment by TehWardy** [comment]
I have also been trying to set the "ChrootDirectory" setting to anything other than none in the config file but this doesn't seem to work either.
Is this the same bug or should I raise a new one?

**Comment by rgl** [comment]
here its working fine with v0.0.5.0. can you guys try that version?

**Comment by TehWardy** [comment]
Are you kidding me?
This took so long to sort out we got a third party to manage a server for us.

but thanks for fixing it at least, maybe someone else can benefit from it

**Comment by rgl** [comment]
why should I be kidding you? I didn't fix anything, I was trying the latest version and noticed that this particular issue seemed to be solved.

**Comment by manojampalam** [comment]
This was fixed a while back.
