### ISSUE TITLE
AllowGroups does not work for domain groups

### ISSUE THREAD

**Issue by TippyLion28** [PowerShell/Win32-OpenSSH#2094]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

I'm trying to allow ONLY members of a domain group to login over SSH. The following just lets anyone login:

`AllowGroups domain-shortname\groupname`

Trying to combine this with a Deny statement just blocks everyone out

### Expected behavior

```console
Specifying only AllowGroups means that only members of that group can login
```

### Actual behavior

```console
Allows everyone in
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.17763.3770
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.3770
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

v9.2.2.0p1-Beta

**Comment by maertendMSFT** [comment]
Can you provide the SSHD config file?

**Comment by TippyLion28** [comment]
I fixed this eventually. I had my AllowGroups statement at the bottom of my sshd config which was underneath a match statement. Indentation was throwing me off; it seems to be completely ignored.

**Comment by tgauth** [comment]
> I fixed this eventually. I had my AllowGroups statement at the bottom of my sshd config which was underneath a match statement. Indentation was throwing me off; it seems to be completely ignored.

Ah, thanks for explaining! To clarify - it wasn't being ignored, it was being interpreted as part of the Match block. The AllowGroups keyword would only be applied when the criteria of the Match statement is met like any other keyword within the Match block.

**Comment by TippyLion28** [comment]
This is what was throwing me - my AllowGroups statement was not indented like the rest of the match block. Yet it was being interpreted as if it was. Anyway, I moved my AllowGroups statement upwards in the config and it works now :)
