### ISSUE TITLE
Load key invalid format when run as admin

### ISSUE THREAD

**Issue by rickdgray-dc** [PowerShell/Win32-OpenSSH#2099]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

When running any git commands as admin, my public key is "invalid." When running as my local user, it works correctly.

The same repo and public key are used in both cases; the public key location's full path has been hardcoded in case of any ambiguity with `~/.ssh` as different users.

I currently have [this](https://developer.1password.com/docs/ssh/agent/advanced#use-multiple-github-accounts) setup with 1password, but I don't believe it to be the cause.

### Expected behavior

```console
I expect the public key to be read correctly in either case.

Correct behavior as local (successful fetch and nothing to update so no info returned):
![image](https://github.com/PowerShell/openssh-portable/assets/124840104/a00cfdfa-ecd5-45e9-b4a1-988a08579d27)
```

### Actual behavior

```console
Error as admin (unable to make fetch request as key is considered invalid):
![image](https://github.com/PowerShell/openssh-portable/assets/124840104/38fed06a-451b-4587-b85f-0c9a4594fe67)
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

PS 7.3.4, OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

**Comment by tgauth** [comment]
@rickdgray-dc - I'm not sure this is specific to Win32-OpenSSH but to clarify, are there are separate public keys for the local user and the admin user?

**Comment by rickdgray-dc** [comment]
Hey Tess, I can't really explain it but after a couple weeks or so it seemed to resolve itself. Perhaps an update to terminal or 1password was released. To answer your question, there are not separate keys for local and admin. Regardless, I'll close this issue for now and reopen it if the issue arises again. Thanks, for helping.
