### ISSUE TITLE
Unable to issue commands after connecting to a server running Tectia 6.3.6

### ISSUE THREAD

**Issue by tmichealson** [PowerShell/Win32-OpenSSH#21]
after connecting any command issued is simply echoed and the session freezes.

**Comment by quamrulmina** [comment]
New ssh client in upcoming release is more feature complete and the problem is likely fixed.

**Comment by manojampalam** [comment]
Try out the latest release.

**Comment by tmichealson** [comment]
Similar results.  There is no echo of the issued command, but the session freezes after any command is issued (i.e. “dir”, or ”cd c:\”  so not complex stuff)

I have verified that I can connect and issue commands to the same server using PUTTY, or the Linux SSH client.

SFTP seems to work though.

**Comment by manojampalam** [comment]
Ok. We'll follow up.

**Comment by quamrulmina** [comment]
Fixed the problem. Our ssh client will now work with all versions of Tectia ssh servers.
