### ISSUE TITLE
on windows7 64bit, cmd.exe /c $ntrights can't read "c:\Program files"

### ISSUE THREAD

**Issue by g1im2** [PowerShell/Win32-OpenSSH#210]
if i install by wiki, some error would be happened, like "can't read c:\Program Files dirctory", because it contains blank in path name.

i read install_sshd.ps1 and found the command line like this.
line 7 $ntrights = Join-Path $scriptdir "ntrights.exe -u `"NT SERVICE\SSHD`" +r SeAssignPrimaryTokenPrivilege"
line 30 cmd.exe /c $ntrights

put the install dirctory on no contains blank path name, it will be ok

**Comment by manojampalam** [comment]
Thanks. I've fixed it.
