### ISSUE TITLE
Install Instructions show "net start ssh-agent" but

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#211]
but I do not see anything anywhere in the instructions that configures ssh-agent.exe as a service.

This is the first bullet under Step 5 (as of this writing) here: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by manojampalam** [comment]
this is taken care of by install-sshd.ps1. Updated wiki.
