### ISSUE TITLE
SSH_ASKPASS is ignored by ssh.exe on Windows 11, but not on Windows 10

### ISSUE THREAD

**Issue by Maddimax** [PowerShell/Win32-OpenSSH#2115]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

* Set SSH_ASKPASS to your askpass program of choice
* CreateProcess("C:\Windows\System32\OpenSSH\ssh.exe")

> This works on Windows 10 where ssh.exe -V = "OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2"
> but not on Windows 11 where ssh.exe -V = "OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3"

### Expected behavior

```console
askpass program should be started when password is needed
```

### Actual behavior

```console
askpass program is not started
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

**Comment by Robert-xiaoqiang** [comment]
`SSH_ASKPASS` environment variable works well for me with the same Windows11 and "**OpenSSH_for_Windows_8.6p1**" as you after I configure the environment variable `SSH_ASKPASS_REQUIRE`.
Specifically, I didn't try this variable with Windows 10 and "**OpenSSH_for_Windows_8.1p1**", but I knew about the `SSH_ASKPASS` behaviors on Linux from "man ssh" as:

> If ssh does not have  a  terminal associated with it but `DISPLAY` and `SSH_ASKPASS` are set, it will execute the program  specified  by  `SSH_ASKPASS` and open an X11 window to read the passphrase.

Furthermore, **OpenSSH 8.4+** provides variable `SSH_ASKPASS_REQUIRE` to use `SSH_ASKPASS` program more flexibly. More details are in this discussion [https://unix.stackexchange.com/questions/272506/can-i-get-ssh-to-use-an-askpass-program-even-if-it-was-run-from-a-terminal](https://unix.stackexchange.com/questions/272506/can-i-get-ssh-to-use-an-askpass-program-even-if-it-was-run-from-a-terminal).
Therefore, you can try to set the environment variable SSH_ASKPASS_REQUIRE to `force` and see whether it still doesn't work.

**Comment by Maddimax** [comment]
Thanks a lot for that info, it works!
