### ISSUE TITLE
ssh.exe does not exit on its own when host closes connection

### ISSUE THREAD

**Issue by davedesro** [PowerShell/Win32-OpenSSH#212]
Hi, when this command is called in PowerShell

```
ssh.exe user@example.com "ls -al; exit"
```

.. the `ssh.exe` process does not exit on its own.  Either another process needs to kill it or a user needs to hit <enter>.

This makes automation using `ssh.exe` very difficult.

Is there a way the powershell `ssh.exe` can exit on its own when the server kills the connection, similar to Linux openssh ssh?

thanks!
- Dave

**Comment by manojampalam** [comment]
What OS are you seeing this?

**Comment by davedesro** [comment]
64-bit Windows 7.. pretty old, but I'm stuck with this constraint. :-\

**Comment by davedesro** [comment]
Hi @manojampalam, this is still an issue for me. Do you expect this to be closed by next week's milestone?  Thanks!

**Comment by manojampalam** [comment]
Sorry, did not get a chance to look into this yet.

**Comment by manojampalam** [comment]
Looks like this is working now. Just tried from a Windows 7 box to Ubuntu target.
