### ISSUE TITLE
Creating a user for Win32-OpenSSH.

### ISSUE THREAD

**Issue by paolosezart** [PowerShell/Win32-OpenSSH#2123]
### Summary of the new feature / enhancement

I would like to be able to create a user for OpenSSH not from among Windows users. I think there should be such an undocumented possibility. I read the instructions very carefully, but I didn't find such an opportunity.

**Comment by maertendMSFT** [comment]
What is the use case for this scenario?

In our view this feature request is out of scope of this project unless there is a scenario we are missing.

**Comment by zhw2101024** [comment]
> What is the use case for this scenario?
> 
> In our view this feature request is out of scope of this project unless there is a scenario we are missing.

I guess the author want a user just used for tasks with OpenSSH, but not shown on login screen.
I once thought about this too, maybe can be achieved by creating hidden users.
