### ISSUE TITLE
DefaultShellCommandOption has an unreasonably small size limit

### ISSUE THREAD

**Issue by samhocevar** [PowerShell/Win32-OpenSSH#2125]
### Summary of the new feature / enhancement

The `DefaultShellCommandOption` registry key has a size limit of 15 characters. This seems unreasonably small especially since `DefaultShellArguments` has a much larger limit and its contents are not used for a non-interactive shell, so a lot of what is in there has to be duplicated.

For instance, if I wanted to configure OpenSSH to use MSYS2 without creating a helper script, this is what my registry keys would look like:

```
DefaultShell                 C:\msys64\msys2_shell.cmd
DefaultShellArguments        -defterm -mingw64 -no-start -shell zsh
DefaultShellCommandOption    -defterm -mingw64 -no-start -shell zsh -c
DefaultShellEscapeArguments  0
```

### Proposed technical implementation details (optional)

[This PR](https://github.com/PowerShell/openssh-portable/pull/683) increases the limit to the same value as `DefaultShellArguments`, which is currently `PATH_MAX / 2 - 1`.

**Comment by tgauth** [comment]
closing - available in 9.4 release
