### ISSUE TITLE
Release 5_15_2016 install-sshd.ps1 error

### ISSUE THREAD

**Issue by scottmckenzie** [PowerShell/Win32-OpenSSH#213]
When running install-sshd.ps1 from 5_15_2016 I received the following output:

```
[SC] SetServiceObjectSecurity SUCCESS
[SC] ChangeServiceConfig SUCCESS
'C:\Program' is not recognized as an internal or external command,operable program or batch file.
sshd and ssh-agent services successfully installed
```

I have fixed this like so:
1. Change line 7 to read:
`$ntrights = Join-Path $scriptdir "ntrights.exe"`
2. Change line 30 to read:
`& $ntrights -u "NT SERVICE\SSHD" +r SeAssignPrimaryTokenPrivilege`

I cloned the repo so I could patch install-sshd.ps1 and submit a pull request but it is not present in the repo.

**Comment by manojampalam** [comment]
This is fixed in the updated paylaod
