### ISSUE TITLE
UserKnownHostsFile Token Replacement doesn't work (OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2)

### ISSUE THREAD

**Issue by zWingz** [PowerShell/Win32-OpenSSH#2134]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

setup the config
```
Host my-host
HostName 127.0.0.1
IdentityFile %d\.ssh\id_ed25519
UserKnownHostsFile %d\.ssh\known_hosts
```

### Expected behavior

```console
connect to server succeed
```

### Actual behavior

```console
faile to get the known host from `%d\.ssh\known_hosts`
```

### Error details

```console
debug3: Failed to open file:C:/Users/%d/.ssh/known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug3: Failed to open file:C:/Users/%d/.ssh/known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug3: failed to open file:C:/dev/tty error:3
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

### Visuals

![image](https://github.com/PowerShell/Win32-OpenSSH/assets/13031838/ef965d6e-b520-4f94-a2f1-980875ae3238)

**Comment by maertendMSFT** [comment]
@zWingz can you give us more details on the file permissions that you have over the impacted directories? Is `%d` a shortcut or the actual name?  I am not familiar with it being a shortcut.

**Comment by zWingz** [comment]
@maertendMSFT 
https://man7.org/linux/man-pages/man5/ssh_config.5.html#tokens
<img width="809" alt="image" src="https://github.com/PowerShell/Win32-OpenSSH/assets/13031838/c0cce0e6-5fa9-42ca-83f2-40dfc7f3931c">
<img width="714" alt="image" src="https://github.com/PowerShell/Win32-OpenSSH/assets/13031838/8f676551-0eb8-4dc6-be44-63c3d1cdc017">


`%d` is a tokens for `ssh-config`

**Comment by zWingz** [comment]
`UserKnownHostFile %d/.ssh/known_hosts` works on MacOS and `OpenSSH_8.8p1, OpenSSL 1.1.1l  24 Aug 2021` for windows

**Comment by zWingz** [comment]
also work on the window


Name                           Value
----                           -----
PSVersion                      5.1.14393.5582
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.5582
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by vthiebaut10** [comment]
@zWingz does it work with the most recent version of OpenSSH? It works for me with OpenSSH 9.2.2 (but fails on 8.1)

**Comment by zWingz** [comment]
@vthiebaut10 Sorry, I don't know does it works on other version

**Comment by vthiebaut10** [comment]
I tested on version 8.1 and 9.2, and it seems that the issue was fixed on some previous version. Can you update your client to version 9.2?

**Comment by zWingz** [comment]
Sure. I can upgrade my ssh client..But I want to find a shortcut that represents the HOME directory

**Comment by vthiebaut10** [comment]
%d should work for the user's home directory. There just seem to be a bug in older versions that don't format the path correctly.

**Comment by zWingz** [comment]
@vthiebaut10 thx
