### ISSUE TITLE
git+ssh+gpg4win get_agent_identities: ssh_agent_bind_hostkey: invalid format every other command

### ISSUE THREAD

**Issue by andrewpmartinez** [PowerShell/Win32-OpenSSH#2141]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

1) Install latest release: v9.2.2.0p1-Beta
2) Install gp4win (gpg 2.4.3, libcrypto 1.10.2)
3) Use a Yubikey for private key storage, and verify access via `gpg --card-status`
4) Configure gpgagent in %APPDATA%/Roaming/gnupg/gpg-agent.conf with:
```
default-cache-ttl 7200
max-cache-ttl 14400

default-cache-ttl-ssh 7200 
max-cache-ttl-ssh 14400

enable-win32-openssh-support
```
5) Set env variable SSH_AUTHS_SOCK to `\\.\\pipe\\openssh-ssh-agent`
6) Register public key with github
7) Attempt to connect to github: `ssh git@github.com` or with debug logging `ssh git@github.com -vvv` or use git commands (e.g. `git pull`)
8) Note every other attempt works

Step 7 can be git actions as well (i.e. `git pull`). However, it is easier to see the SSH logs using SSH.

### Expected behavior

```console
Should work on on every SSH connection/git command.
```

### Actual behavior

```console
Alternates between working and not working.
```

### Error details

```console
Powershell didn't return an error but the debug messages from SSH returns the last two lines on connections that fail:


debug2: ssh_set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug2: ssh_set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug2: get_agent_identities: ssh_agent_bind_hostkey: invalid format
debug1: get_agent_identities: ssh_fetch_identitylist: agent contains no identities
```

On success, the logs look like:

```
debug2: ssh_set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug2: ssh_set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug2: get_agent_identities: ssh_agent_bind_hostkey: agent refused operation
debug1: get_agent_identities: agent returned 2 keys
debug1: Will attempt key: cardno:12_587_012 RSA SHA256:74kWPLly2zBhmgypjzuzvNQqYAXCvDjN2Q94JjNxO/I agent
debug1: Will attempt key: cardno:12_587_012 RSA SHA256:74kWPLly2zBhmgypjzuzvNQqYAXCvDjN2Q94JjNxO/I agent
```
```


### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.13
PSEdition                      Core
GitCommitId                    7.2.13
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Version

v9.2.2.0p1-Beta

### Visuals

[git.fail.zip](https://github.com/PowerShell/Win32-OpenSSH/files/12597731/git.fail.zip)

**Comment by andrewpmartinez** [comment]
As an aside, I was using gpg+ssh+git using a bridge for a very long time, and to worked flawlessly. Once `gpg` released support for the SSH_AUTH_SOCK named pipe, I switched to that, which worked great for a long time.

**Comment by maertendMSFT** [comment]
@andrewpmartinez, when did this stop working?  Was there an update where this stopped working or was it random? Do you also have ssh-agent running at the same time? can you provide more details or docs on gpgagent setup steps?

**Comment by andrewpmartinez** [comment]
Seems like the SSH Agent was running and I assume was fighting to read/write to the named pipe. I assume when I upgraded the SSH Agent service was installed and marked for automatic start. I have disabled it now. GPG Agent is now they only process handling the named pipe and seems to work just fine.
