### ISSUE TITLE
Problem "rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]" still

### ISSUE THREAD

**Issue by Juddd** [PowerShell/Win32-OpenSSH#2145]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

After install the latest v9.2.2.0p1-Beta, I run:
rsync -a -e "D:\soft\OpenSSH-Win64\ssh -p 22"  bindir/ yode@12.12.12.57:/home/myname/testrsync
I still get this information:

### Expected behavior

```console
I hope it  copy my `bindir/` to my serve
```

### Actual behavior

```console
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(231) [Receiver=3.2.7]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(231) [sender=3.2.7]
```

### Error details

```console
I note this is a solved problem [here](https://github.com/PowerShell/Win32-OpenSSH/issues/2012#issuecomment-1593753897). But it clearly exists. Note that rsync on my server is fine, because I have no problem running the same code in wsl2
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

v9.2.2.0p1-Beta

**Comment by maertendMSFT** [comment]
rsync is out of scope for this project, so this is unsupported by us.

Though you can try this!
https://github.com/PowerShell/Win32-OpenSSH/issues/1266#issuecomment-1239095766
There are other workarounds described in the thread as well.
