### ISSUE TITLE
Path over 260 characters when using the chocolatey one-liner install

### ISSUE THREAD

**Issue by lancel66** [PowerShell/Win32-OpenSSH#215]
Path too long error preventing the choco/openssh one-liner from completing successfully in Powershell:

hashes match.
 Extracting C:\Users\vagrant\AppData\Local\Temp\chocolatey\win32-openssh\2016.04.05\win32-opensshInstall.zip to C:\Program Files...
 Get-ChildItem : The specified path, file name, or both are too long. The fully 
 qualified file name must be less than 260 characters, and the directory name mu
 st be less than 248 characters.
 At C:\ProgramData\chocolatey\helpers\functions\Write-FileUpdateLog.ps1:25 char:
 23
- ... $originalContents = Get-ChildItem -Recurse $locationToMonitor | Selec ...
-                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ReadError: (C:\Program File...bad-free-extras:St 
    ring) [Get-ChildItem], PathTooLongException
  - FullyQualifiedErrorId : DirIOError,Microsoft.PowerShell.Commands.GetChildItemCommand

**Comment by DarwinJS** [comment]
Please try the most recent package version (2016.05.30 still in chocolatey moderation as of this writing) as it no longer embeds the .zip file.

Please report chocolatey packaging issues to: https://github.com/DarwinJS/ChocoPackages/issues

Thanks.

**Comment by Kamila3565** [comment]
I am getting this same issue and its very difficult to solve this problem without any third party app, i guess the best thing to do is to use a third party app like Long Path Tool. Just download it and use it to solve this issue. I hope this would help.

**Comment by maertendMSFT** [comment]
This looks to be specific to chocolatey
