### ISSUE TITLE
when sftp ls /.  , it list /c:/  using sftp-server

### ISSUE THREAD

**Issue by tick-guo** [PowerShell/Win32-OpenSSH#2150]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

1. connect to sftp-server from cmd 
2. run cmd   
`ls /.   `

### Expected behavior

```console
just list 
ls /
c:
d:
e:
```

### Actual behavior

```console
listed /c:/ files
```

### Environment data

```PowerShell
not involved
```

### Version

OpenSSH_for_Windows_9.2p1, LibreSSL 3.7.2

### Visuals

![微信截图_20230923133146](https://github.com/PowerShell/Win32-OpenSSH/assets/39718787/966587dd-0dcf-4d2f-a8cd-840ddf8793e1)

**Comment by tgauth** [comment]
I agree that `ls /.` over sftp prints the contents of the system drive directory. 
In a PowerShell session on the same machine (no sftp), `ls /.` also prints the contents of the system drive directory, so I think this is the expected behavior. 
Let me know if I am misunderstanding the issue.

**Comment by tick-guo** [comment]
> I agree that `ls /.` over sftp prints the contents of the system drive directory. In a PowerShell session on the same machine (no sftp), `ls /.` also prints the contents of the system drive directory, so I think this is the expected behavior. Let me know if I am misunderstanding the issue.

thinks reply.
l hava the reasons,
1. in a powershell ,cd /. will  return  current driver root , not always c:
, but sftp will display c: anyway.
2. in sftp dir style , / means root and . means current , so  /. should goto  /
3. some sftp gui client   always try /. to display  root dir . and  l can not  see my files  in other drivers  anyway , that is just my  face  problem.
