### ISSUE TITLE
What are "sshd_{digits}" users seen in a brute-force attack ?

### ISSUE THREAD

**Issue by rpdeo** [PowerShell/Win32-OpenSSH#2157]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Scenario: 

Windows server 2016  with Win32 OpenSSH 7.x

Port open to internet, we observe what looks like a SSHD brute-force attempt.

Hundreds of 4625 events (failure) with NOUSER as client username.

We are finding 4624 events (success) with client username that look like "sshd_<number>"

There are no local user accounts with such usernames.

How are these 4624 events generated ?

What is leading to authentication success ?

Any guidance would be appreciated.

Perhaps the risks need to be documented somewhere.

### Expected behavior

```console
sshd_<number> should also be failure events.
```

### Actual behavior

```console
authentication success for sshd_<number> events.
```

### Environment data

```PowerShell
Windows Server 2016
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```

### Version

OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

**Comment by rpdeo** [comment]
We are finding that these are "Virtual Accounts" (not sure how they are configured)

sample 4624 event details are below:

An account was successfully logged on. Subject: Security ID: S-1-5-18 Account Name: SFTP-SVR$ Account Domain: CONTOSO Logon ID: 0x3E7 Logon Information: **Logon Type: 5** Restricted Admin Mode: - Virtual Account: Yes Elevated Token: Yes Impersonation Level: Impersonation New Logon: Security ID: S-1-5-111-REDACTED-REDACTED-REDACTED-REDACTED-REDACTED-**2660** Account Name: **sshd_2660** Account Domain: **VIRTUAL USERS** Logon ID: 0x20B9DE66E Linked Logon ID: 0x0 Network Account Name: - Network Account Domain: - Logon GUID: {00000000-0000-0000-0000-000000000000} Process Information: Process ID: 0xa64 Process Name: C:\Windows\System32\OpenSSH\sshd.exe Network Information: Workstation Name: - Source Network Address: - Source Port: - Detailed Authentication Information: Logon Process: Advapi Authentication Package: Negotiate Transited Services: - Package Name (NTLM only): - Key Length: 0

Apologies for the blob above newlines were lost when copying and redacting it.

**Comment by vthiebaut10** [comment]
@rpdeo - during an attempt to start a connection, sshd spawns a temporary process that runs in the context of a temporary virtual account named something like "sshd_XXXX" that handles pre-authentication tasks. After attempting to authenticate, that process is terminated, and if authentication was successful sshd then spawns a new sshd process running in the user context. 
The temporary virtual accounts are created as part of the authentication process, but that doesn't guarantee authentication will be successful.

Let us know if this answers your question, or if you need additional info

**Comment by rpdeo** [comment]
@vthiebaut10 , thank you for the explanation. 

This does help, we were concerned where the virtual accounts are showing up in logs. 

I suspected the pre-auth/privilege separation feature in sshd but was not sure. 

Can you point me to the source file where this is implemented ?

You can close issue after that with a documentation request.

**Comment by tgauth** [comment]
The call comes from the `sshd main` function: https://github.com/PowerShell/openssh-portable/blob/latestw_all/sshd.c#L2574
The `server_accept_loop` is defined here: https://github.com/PowerShell/openssh-portable/blob/latestw_all/sshd.c#L1526

**Comment by rpdeo** [comment]
@tgauth thanks, found the implementation here: https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/win32_usertoken_utils.c#L568
