### ISSUE TITLE
wrong message when connection refused

### ISSUE THREAD

**Issue by calphool** [PowerShell/Win32-OpenSSH#216]
When there's no host listening, you get this for your error message:

ssh: connect to host {whatever} port 22: The operation completed successfully.

Should be:

ssh: connect to host {whatever} port 22: Connection refused

**Comment by welnanick** [comment]
Just as some more reference, in the latest release, it now says:

`ssh: connect to host *host* port 22: No error`

Just thought I'd chime in since the message changed.

**Comment by arif-pragmasys** [comment]
When no host listening, the current version prints:
ssh: connect to host xxxxx port 22: Unknown error

It has the correct error no (107, which is ECONNREFUSED), but unable to get a valid string message for that posix error using strerror(), hence the 'Unknon error' message. Looks like the strerror() api is handling Posix errors upto number 43 correctly, beyond that printing 'Unkown error'
![capture](https://cloud.githubusercontent.com/assets/14184782/21369366/3db383b0-c6cc-11e6-9e48-eea1f1ae8c9d.PNG)
