### ISSUE TITLE
Does the latest version support reverse connections?

### ISSUE THREAD

**Issue by worm001** [PowerShell/Win32-OpenSSH#2163]
### Summary of the new feature / enhancement

As the question requires, there is a Windows system on the intranet with the latest version of "OpenSSH Win64 v9.4.0.0. msi" installed. How can I set it to log in and access the resources of the intranet machine on a machine with a public network?

**Comment by maertendMSFT** [comment]
Are you looking to implement reverse tunnelling?  If so, that is already supported.
Can you give use more details on the scenario? Which machine has internet access, the client or the server?
Starting in 9.2, the firewall rule is set to only allow private networks by default. This may need to be updated if you did not make this change explicitly.

**Comment by worm001** [comment]
Windows host 'A' on a private network with 'OpenSSH Win64 v9.4.0.0msi' installed
”It is a server that can access the internet! The specific public IP address of host "B" is the client. The previous method was to use FRP for internal network proxy. May I ask how I can set it up so that FRP is no longer needed.

**Comment by tgauth** [comment]
Ok, this sounds like reverse tunneling - host 'B' is accessible via public IP, so host 'A' can connect to host 'B' then a loopback connection will allow traffic from host 'A' to host 'B'

If my understanding of the desired scenario is correct, here's some instructions on setting up reverse tunneling: https://www.howtogeek.com/428413/what-is-reverse-ssh-tunneling-and-how-to-use-it/
