### ISSUE TITLE
Installation Instructions Ordering May Need Correcting?

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#217]
Just trying to follow the installation instructions to build the chocolatey package.

**Step 5**, bullet 1 says **"net start ssh-agent"**

However, it seems that ssh-agent service is not configured until **Step 7**, bullet 4 which is **"powershell.exe .\install-sshd.ps1"**

I believe the ssh-agent installation is in the .\install-sshd.ps1.

Could you please clarify or reorder the steps on that page?

Thanks much.

**Comment by manojampalam** [comment]
done
