### ISSUE TITLE
ssh-keygen certificate creation fails due to bad permissions when the CA file is on a Dev Drive

### ISSUE THREAD

**Issue by anthonyvdotbe** [PowerShell/Win32-OpenSSH#2176]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

* generate a keypair
* create a certificate with `ssh-keygen -s ca_key id_ed25519.pub`, where `ca_key` is on a [Dev Drive](https://learn.microsoft.com/en-us/windows/dev-drive/)

### Expected behavior

```console
certificate creation succeeds (as it does when I copy `ca_key` outside the Dev Drive and run the same command again)
```

### Actual behavior

```console
Bad permissions. Try removing permissions for user: NT AUTHORITY\\Authenticated Users (S-1-5-11) on file C:/Users/antho/DevDrive/ssh/ca_key.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'ca_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "ca_key": bad permissions
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

**Comment by maertendMSFT** [comment]
At face value this appears to be an issue with the permissions associated with the file. This type of issue can occur outside of the Dev Drive as well when multiple people have access to the file. Can you check what permissions you have on the file and ensure that only `Users/antho` has permissions on the folder? It looks like `Authenticated Users` has permissions as well. `Administrator` and `system` access are ok.

**Comment by anthonyvdotbe** [comment]
Indeed, the file's permissions are too liberal. It also has:

```
Authenticated Users / Allow / Modify / Parent Object
Users (mypc\Users) / Allow / Read & execute / Parent Object
```

Since my Dev Drive is within my `$HOME`, I expected the files within the Dev Drive would transparently inherit the permissions from the Dev Drive's parent folder.
