### ISSUE TITLE
failed to initialize w32posix wrapper

### ISSUE THREAD

**Issue by fengxx** [PowerShell/Win32-OpenSSH#2181]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

very weird behavior, 
1) win+R, type `ssh hostname` can not reproduce
2) win+R, type cmd, then type `ssh hostname`, throws error `failed to initialize w32posix wrapper`
3) win+R, type cmd, then type cmd.exe in cmd to spawn a new process, then type `ssh hostname` in the new cmd,  there is no error
4) win+R, type powershell, then type `ssh hostname` in powershell, throws error `failed to initialize w32posix wrapper`
5) open [ConEmu ](https://conemu.github.io/), type ssh, can not reproduce

System has enough memory, and tried cmd.exe with small history buffer such as 50, still no luck

no idea what triggered [the error in w32posix_initialize](https://github.com/PowerShell/openssh-portable/blob/cb23f0d9c0f4d40edbc2863419dcff40ebd5e0a6/contrib/win32/win32compat/w32fd.c#L226-L237)

### Expected behavior

```console
ssh can connect to remote host
```

### Actual behavior

```console
`failed to initialize w32posix wrapper` and hangs
```

### Error details

```console
failed to initialize w32posix wrapper
```

### Environment data

```PowerShell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.22621.2419
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2419
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

OpenSSH_for_Windows_9.4p1, LibreSSL 3.7.3

**Comment by fengxx** [comment]
It seesm there was a conflict with WindowsTerminal, removed WindowsTerminal  and resintalled from Microsoft Store, everything is back to normal. feel free to close if it is not a bug

**Comment by abhivarma007** [comment]
I had the same issue, when tried on VS Code worked perfectly fine.
