### ISSUE TITLE
Something screwed up in auth2-pubkey.c, inside expand_authorized_keys()

### ISSUE THREAD

**Issue by calphool** [PowerShell/Win32-OpenSSH#219]
I've been trying to get RSA key exchange SSO working, but I believe I've run into a bug in auth2-pubkey.c in expand_authorized_keys().

I put the public key in the c:\Users\{myuserid}\.ssh\authorized_keys folder as id_rsa.pub, and when I fire up sshd.exe with -D -d -d -d I get this:

```
debug1: attempt 2 failures 0
debug2: input_userauth_request: try method publickey
debug3: gethomedir: pUserName [{myuserid}]
debug3: gethomedir: username [{myuserid}]
debug3: gethomedir: getenv
debug3: gethomedir: userprofile [C:\Users\{myuserid}]
debug3: GetHomeDir: homedir [C:\Users\{myuserid}]
debug1: trying public key file C
debug1: Could not open authorized keys 'C': Access is denied.
debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa

```

It looks like something in expand_authorized_keys() is screwing up the path of the key because it thinks there's something wrong with having a colon in a path name, and it's just using the "C" of my "C:\Users\{myuserid}"... since this code is a port from Linux, that's not altogether surprising I suppose.

I don't have a build environment set up (installed from choco), or I'd dig a bit deeper myself, but this is what seems to be happening.

**Comment by calphool** [comment]
I went and got the tip revision 5_16_2016 and the messages are different, but I'm still not able to get key based SSO working... clearly there's something I'm supposed to be doing with ssh-agent, but it's not obvious how to get it working.

**Comment by manojampalam** [comment]
debug1: Could not open authorized keys 'C': Access is denied.

This is an artifact of passing UTF-16 strings through SSH code. This will be fixed in the next month or so.
But otherwise, your issue is "Access is denied". Apparently, the user your sshd is running as does not have access to authorized_keys

**Comment by calphool** [comment]
I'm now on the 5_16_2016 version, I'm seeing this in the agent logs:

```
6400 17:09:17 965 agent_start pid:6400, dbg:0, child:0, pipe:0
6400 17:10:12 779 client pid 7048 connected on \\.\pipe\ssh-keyagent
6400 17:10:12 782 debug1: spawned child 6640 to process 3
6640 17:10:12 796 agent_start pid:6640, dbg:0, child:1, pipe:364
6640 17:10:12 796 debug1: connection io 000000CCD4DAF370 #bytes:0 state:0
6400 17:10:12 887 client pid 7048 connected on \\.\pipe\ssh-authagent
6400 17:10:12 889 debug1: spawned child 3376 to process 3
3376 17:10:12 904 agent_start pid:3376, dbg:0, child:1, pipe:372
3376 17:10:12 904 debug1: connection io 000000CE4820F370 #bytes:0 state:0
3376 17:10:12 905 debug1: connection io 000000CE4820F370 #bytes:4 state:1
3376 17:10:12 905 debug1: connection io 000000CE4820F370 #bytes:966 state:2
3376 17:10:12 905 debug1: client type: 3
3376 17:10:12 906 debug1: unable to generate user token
3376 17:10:12 906 debug1: connection 000000CE4820F370 clean up
3376 17:10:12 906 debug1: iocp error: 6 on 0000000000000000 
6640 17:12:12 710 debug1: iocp error: 109 on 000000CCD4DAF370 
6640 17:12:12 710 debug1: connection 000000CCD4DAF370 clean up
6640 17:12:12 710 debug1: iocp error: 6 on 0000000000000000 
```

Still not able to get the SSO stuff working... I'm guessing "unable to generate user token" is meaningful in some way, but not sure how.

**Comment by manojampalam** [comment]
Is this domain or local user? How are you issuing the ssh.exe cmdline?

**Comment by calphool** [comment]
Domain.  The server is Windows 2012 r2, fresh install, no local accounts.  I've tried both:

ssh -v {myuser}@{mydomain}@{myserver}

and

ssh -v {myuser}@{myserver}

...with this latter one being an attempt to use the RSA key pair...  Neither one seems to work.

Based on what you're saying, I wonder if I should revert back to the previous build (the one in choco), and then diagnose why sshd wasn't able to access the public key I had stored... it looks like maybe I was closer than I thought.

**Comment by calphool** [comment]
I reverted back to the choco install version, but I'm getting the 

`debug1: Could not open authorized keys 'C': Access is denied.`

thing again.

I don't understand why anything wouldn't have access.  I've run sshd under an administrator console on the command line, and I'm attempting to use the key for the user I'm actually signed onto the server as.

Could somebody create a video of setting up a SSO via rsa keys, starting with nothing installed anywhere?  Or has nobody got this working yet?

**Comment by calphool** [comment]
Okay... I figured out why I was getting "Access is denied".  I _thought_ that the authorized_keys was a _directory_, but it appears that perhaps it's a file that you're supposed to paste the public keys into?

I got rid of the c:\Users{myuser}.ssh\authorized_keys _directory_, replaced it with a file of the same name, and then pasted my client generated public key in there, and started sshd back up on the command line in interactive mode.

Now when I attempt to connect with ssh -v {myuser}@{thesshservername}, the sshd process dies on the server.  When I run it as a service, I get an entirely different behavior (the c0000041 error shows up in the logs again).

**Comment by manojampalam** [comment]
On the latest release, Key-auth has been tested and validate to work in both domain and work group scenarios and for both local and domain accounts. (only local accounts were working previously).
I recommend installing the latest release and retrying again. 
Otherwise, have you been installing ssh-lsa.dll (and rebooting) in your attempts so far?

I will, as you recommended, create a training video over the weekend, on how to setup SSO via keys.

**Comment by calphool** [comment]
Yes, I've been keeping that DLL in sync with the release (in C:\windows\system32).  I had to rename it in order to get rid of the previous version because something held it exclusively.  Renamed it, rebooted, deleted the old renamed file, put the new one in place, and rebooted  again.

**Comment by calphool** [comment]
I did get it all working with a local account and a shared key, but I'm trying to use a domain account with keys (with the 4/5/2016) build.  It looks like I need to upgrade to the tip revision and try again.  The keys aren't managed the same way though, right?  You have to use ssh-agent and ssh-add, correct?

**Comment by manojampalam** [comment]
Yes. ssh-agent is supported in the latest version. (ITs not mandatory to store keys in ssh-agent, however).

What was the issue before that was preventing key auth with local accounts?

**Comment by calphool** [comment]
I didn't start out doing local accounts.  I started out with the intent of using domain accounts.  I didn't try to use a local account until later.

**Comment by manojampalam** [comment]
Reopen if needed
