### ISSUE TITLE
Discussion on Cybersecurity Risks: Issue with Unshielded Versions in OpenSSH for Windows

### ISSUE THREAD

**Issue by a31515034** [PowerShell/Win32-OpenSSH#2190]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

During the process of conducting a host vulnerability scan, an unshielded version risk in OpenSSH has been reported. I attempted to modify the configuration file as follows:

Banner none
VersionAddendum none
VersionAddendum no
VersionAddendum OpenSSH for_Windows_x.x

@tgauth
However, the version number remains visible despite these changes. I seek assistance on how to effectively shield the version number from being disclosed.

 "Please refer to this issue: 'Hardcoded banner allows an attacker to quickly identify vulnerable machines' discussion (currently without any answers)."

### Expected behavior

```console
To hide the version number display.
```

### Actual behavior

```console
OpenSSH for_Windows_9.5
```

### Environment data

```PowerShell
Name                           Value                                                                                                                                                                                                
----                           -----                                                                                                                                                                                                
PSVersion                      5.1.17763.5202                                                                                                                                                                                       
PSEdition                      Desktop                                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                              
BuildVersion                   10.0.17763.5202                                                                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                  
SerializationVersion           1.1.0.1
```

### Version

OpenSSH for_Windows_9.5

**Comment by maertendMSFT** [comment]
This applies to the whole of OpenSSH, no just Win32-OpenSSH.  This is not something that we are likely to modify, as this will create unnecessary inconsistency with the parent OpenSSH project.  If this is a change you would like to see, please create an issue on the OpenSSH repo.

Additionally, a bad actor could obtain the versioning of SSH via the `ssh -V` command for the client and obtain the sshd version via the debug logs.  Either way, the ssh version information is available.

Finally, the banner parameter is for reading from a file, that is not where the versioning information is coming from. Are you seeing the version information after login or the debug logs?

**Comment by mgkuhn** [comment]
@a31515034 Since Microsoft don't reveal the actual patch level in any of the version strings sent to an unauthenticated user, there is actually not much useful vulnerability information that the attacker could gain from that string.

```
$ ssh -vn foo@example.com
[...]
debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_8.1
debug1: match: OpenSSH_for_Windows_8.1 pat OpenSSH* compat 0x04000000
[...]
```

For example, that version string `OpenSSH_for_Windows_8.1` has been the same on Windows 10 since the *2021-05 Cumulative Update*, even though a number of patches had been quietly applied since.

**Comment by a31515034** [comment]
Thank you for the responses, maertendMSFT and mgkuhn. The main issue I'm facing is related to a host security scanning tool, where the scan report has flagged a risk regarding "SSH Server Type and Version Information." Specifically, the scan has explicitly detected the version information for OpenSSH for Windows, leading to the identification of a potential risk.

I am currently researching possible solutions. If there are any recommended methods to conceal this version information in the future, please provide corresponding suggestions. Thank you.

**Comment by mgkuhn** [comment]
Sounds more like a problem with that particular scanning tool. There are other tools available to check if a Windows machine is up-to-date, e.g. `wmic qfe list` should show you when each security update was installed on a node.
