### ISSUE TITLE
Is ~/.ssh/config supported?

### ISSUE THREAD

**Issue by cmonty14** [PowerShell/Win32-OpenSSH#2192]
### Prerequisites

- [X] Write a descriptive title.
- [ ] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

After creating SSH keypair for public key authentication successfully I wonder if I can user a SSH configuration file _~/.ssh/config_?
Please note that I'm not talking about SSH Server configuration file _sshd_conf_.

This SSH configuration file could have this content:
```
Host remote-server
    HostName remote-server
    User d038783
    IdentityFile C:\Users\Name\.ssh\id_ed25519
    IdentitiesOnly yes
    ForwardAgent no
    PreferredAuthentications publickey
    ControlPath C:\Users\Name\.ssh\cm-%r@%h:%p
    ControlMaster auto
    ControlPersist 10m
```
If SSH configuration file _~/.ssh/config_ is supported, are there any restrictions regarding [SSH options](https://man.openbsd.org/ssh.1#o)?
And what is the correct syntax when using a path? `/` or `\`?

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

**Comment by matsmcp** [comment]
c:\users\username\.ssh\config is supported.
you can add Host aliases in it. 
I don't know if all values/options are supported.

**Comment by cmonty14** [comment]
This issue is solved.

I created file C:\user\username\.ssh\config with this content:
```
Host *
    ServerAliveInterval 180
    ServerAliveCountMax 3
    ForwardAgent no
    RemoteForward /run/user/2038783/gnupg/S.gpg-agent ~/AppData/Local/gnupg/d.o35wa9tdt49rzsbu/S.gpg-agent.extra
```

You'll notice the forward-slash `/` in line `RemoteForward` that works for the path `~/AppData/Local/gnupg/d.o35wa9tdt49rzsbu/S.gpg-agent.extra` on Windows client.
