### ISSUE TITLE
Per-User default shell?

### ISSUE THREAD

**Issue by maertendMSFT** [PowerShell/Win32-OpenSSH#2198]
### Discussed in https://github.com/PowerShell/Win32-OpenSSH/discussions/2191

<div type='discussions-op-text'>

<sup>Originally posted by **Khitiara** January 13, 2024</sup>
Id like to set a per-user default shell as i have powershell installed from the windows store on the computer i am SSH-ing into and would like to set that as the default shell for just my user - i see the docs for the main default shell option but this seems to be a whole-machine option rather than per-user</div>

**Comment by matsmcp** [comment]
I have the same kind of request in #1741

**Comment by maertendMSFT** [comment]
closing as a dupe
