### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by dmitrybezer** [PowerShell/Win32-OpenSSH#220]
Related to #173 

I'm using the 5_15_2016 release and the problem is still here. I'm unable to connect from a mac. And the key exchange algorithm doesn't seem to be the issue here because even if I force ssh clients on mac and windows to use the same algorithm (using this option -oKexAlgorithms=diffie-hellman-group-exchange-sha256) connection from windows works fine while mac client fails with exactly the same message log as @paulewog provided.

**Comment by manojampalam** [comment]
Please try out latest release and reopen if needed.
