### ISSUE TITLE
Establishing key-based authentication

### ISSUE THREAD

**Issue by timcerl** [PowerShell/Win32-OpenSSH#221]
Are there instructions for establishing a key-based authentication session?
I want to be able to establish a connection to a network switch.  I have the IP address, username, and password, but that connects me to the CLI.  I want to remain in a PowerShell window/script so I can execute commands against the network switch, for example:
ssh configure terminal
ssh feature lacp
ssh feature udld
ssh feature vpc
ssh spanning-tree port type network default
And so on.  But I don't know how to establish the key-based authentication to allow this. I looked around in the issues and the wiki and did not find any guidance that helped me.
Thanks for the guidance.

**Comment by calphool** [comment]
Good luck with this.... been fighting it for 3 days now.  It _seems_ that it's possible based on what I've read in the installation instructions, but I'll be damned if I can get it working.... starting to feel really stupid.  It would be nice once somebody figures this out if they could post a youtube video of the entire process.

**Comment by timcerl** [comment]
Glad to know I have company!  Sounds like it would make sense for someone to document it in the wiki.

**Comment by manojampalam** [comment]
Did you not find key-auth examples in here - https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples?

**Comment by timcerl** [comment]
I am talking about going from a Windows client to a Linux switch.  The instructions in the wiki shows:
3.Copy  id_rsa.pub  (client's public key) to corresponding user's directory on ssh HOST ◦as  %systemdrive%\users\user.ssh\authorized_keys 
I am pretty sure that Linux does not understand systemdrive%\users\user.ssh\authorized_keys as a place for storing keys.

**Comment by manojampalam** [comment]
Refer https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/s2-ssh-configuration-keypairs.html

**Comment by jemiller0** [comment]
This works for me for ssh.exe. However, it doesn't work for scp. I think there's a bug because I have it working fine from another Linux box and like I said, it works fine for ssh.exe.

**Comment by jemiller0** [comment]
Never mind, I just realized that there is no scp included with this distribution. I was picking up scp.exe from an installation of Git that I have. Seems odd that this distribution doesn't include scp.
