### ISSUE TITLE
OpenSSH ssh ignores contents of .config file in User

### ISSUE THREAD

**Issue by Dyl777** [PowerShell/Win32-OpenSSH#2215]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Any time a create another user and use that user as the server, and try to ssh from root, ssh doesn't work until you use ssh-add, creating a config file in the root or administrator user and adding the necessary info in this case 
![IMG_20240308_091502_117](https://github.com/PowerShell/Win32-OpenSSH/assets/117218643/2d078de7-8c99-4e9f-9c39-5919a468c571)
And starting ssh-agent doesn't work until I use ssh-add (which am supposing it is not supposed to be the case because starting ssh-agent and adding to the config file should be enough) which am supposing ssh-add just adds the key to the known_hosts file (atleast in my case). Upon using ssh -vvv servername@...., even after reading my config file in Users\Username\.ssh\ , it still tries to read the default ssh_config in ProgramData which is not yet even created although sshd_config already exists and is created. Whenever I try to create ssh_config in PROGRAM_DATA by myself and add (https://github.com/PowerShell/Win32-OpenSSH/assets/117218643/2d078de7-8c99-4e9f-9c39-5919a468c571) it shows "bad permissions for the ssh_config". It always shows 
![IMG_20240308_093151_177](https://github.com/PowerShell/Win32-OpenSSH/assets/117218643/32550344-6697-44dc-8be0-aef38fabb755)
(By the way why doesn't the ssh_config file already exist by default given the hassles to create it) IT NEVER SHOWS THAT IT IS LOADING THE IdentityFile in the config file even though it reads the config file (I messed around with the config file adding gibberish to the IdentityFile location it didn't even say "IdentityFile file directory not found despite reading the config file", it goes directly to read all the other keys in the PROGRAM_DATA ssh directory and the ones it expects to be in Users\Username\.ssh\ directory but never loads the one in the IdentityFile location (I suppose ssh -i <keydirectory> servername@... works but I don't want to be entering the location of my keys Everytime I want to ssh in the server) it also loads the keys in .known_hosts in the Users\Username\.ssh directory which is the only reason ssh-add works. Eventually all the keys fail and it asks for a password (Note: I have already added the public key to the servername authorized_keys. Here is a look at my sshd_config file in the PROGRAM_DATA DIRECTORY 
![IMG_20240308_095132_193](https://github.com/PowerShell/Win32-OpenSSH/assets/117218643/3d67a0d4-1ce9-4869-8f3b-f8856ef89b24)
![IMG_20240308_095143_703](https://github.com/PowerShell/Win32-OpenSSH/assets/117218643/1991a5bb-6444-470b-b9d5-ecede9408464)

### Expected behavior

```console
Why does ssh ignore the contents config file in Users\Username\.ssh so hard, even adding other things such as PubKeyAuthentication true,... or any other such configuration in the config file including the IdentityFile is ignored
```

### Actual behavior

```console
Only ssh-add and ssh -i work when you are trying to ssh from the already existing administrator user (usually has the name of the computer it was bought in may case is named ASUS). In even more complex scenarios where you create the servername User and create another user to and try to setup that user to connect to servername, ssh-add starts to asks for a paraphrase (and I don't really use paraphrases in creating my keys) even if the folder containing the keys are chown to that user and chmod 700/600 to that user
```

### Error details

```console
Error details are in the description
```

### Environment data

```PowerShell
This is Windows 10 64-bit system
Using OpenSSH Win64
```

### Version

Using OpenSSH Win64

### Visuals

The visuals are in the description

**Comment by maertendMSFT** [comment]
In your first image, in the config file, you define the host as `Host gitbenchuser1@DESKTOP-DK6PJG9`.  In the ssh config file, you cannot have the username you would like to connect as in the Host section.  If you are trying to connect as gitbenchuser1, then replace it under the `User` field and remove ASUS.  If you are trying to connect as ASUS, then just remove gitbenchuser1 from the `Host` line.

```
Host DESKTOP-DK6PJG9
    User gitbenchuser1
    IdentityFile ...
```

**Comment by Dyl777** [comment]
Ok. So what goes in the HostName

**Comment by tgauth** [comment]
> Ok. So what goes in the HostName

Since `DESKTOP-DK6PJG9` is the same as the `Host` field, it is not needed.

**Comment by Dyl777** [comment]
Ok. That solves the config file reading. Thks alot.
