### ISSUE TITLE
Command Prompt Font Fallbacks To Vector If Default Was Raster

### ISSUE THREAD

**Issue by NurudinImsirovic** [PowerShell/Win32-OpenSSH#2216]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

1. Download the [cozette.fon.zip](https://github.com/PowerShell/Win32-OpenSSH/files/14542472/cozette.fon.zip) font and install it.
2. Set the font 
![image](https://github.com/PowerShell/Win32-OpenSSH/assets/102489121/2dcf322b-896e-416c-93a4-d8f478ea16ba)
3. Open a new Command Prompt window and simply run `ssh`

My assumption is that this has to do with the [SetConsoleMode](https://learn.microsoft.com/en-us/windows/console/setconsolemode) function

### Expected behavior

```console
Font should not have changed from the raster.
```

### Actual behavior

```console
Font fallbacks to TrueType (vector) alternative.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.2364
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2364
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

### Visuals

https://github.com/PowerShell/Win32-OpenSSH/assets/102489121/0f059354-7725-4da3-95e8-4b1d1d64e0fe

**Comment by maertendMSFT** [comment]
Do you see this error when using the latest version?

**Comment by NurudinImsirovic** [comment]
@maertendMSFT My apology, it turns out that the problem is related with the font itself - I'm still in the process of debugging the font format as it was generated using my tool. Closing the issue.
