### ISSUE TITLE
Change README.md, add a reference to the latest stable for Windows

### ISSUE THREAD

**Issue by upyesp** [PowerShell/Win32-OpenSSH#2219]
### Summary of the new feature / enhancement

Hi, the README for this Windows SSH repo says this with regard to the latest stable release:

> Stable Releases
> Stable release tarballs are available from a number of [download mirrors](https://www.openssh.com/portable.html#downloads). We recommend the use of a stable release for most users. Please read the [release notes](https://www.openssh.com/releasenotes.html) for details of recent changes and potential incompatibilities.

The resources linked to above do not appear to include downloads for Windows installers.

The release page for this repo has downloads for the beta versions.  I can't find a link to install the latest stable  for Windows.  

### Proposed technical implementation details (optional)

Please update the README paragraph to include a link to an installer for the latest stable release for Windows.  Perhaps the latest stable is only released via Windows updates?  If so, please make that explicit in the README.

Thanks :)

**Comment by tgauth** [comment]
The README refers to upstream's (OpenSSH-Portable) releases. 
As far as stable Win32-OpenSSH releases, please refer to https://github.com/PowerShell/Win32-OpenSSH/discussions/2136.

**Comment by upyesp** [comment]
Thanks for the link to the issue.  Looks like I duplicated a prior issue/question with my question, apologies for that.

The info re stable is kinda hidden away just now, in the reply to that issue.  Something would normally be in the README?

Anyways, thanks to everyone in the OPENSSH team.
