### ISSUE TITLE
Bad Configuration file default path for SFTP / SCP.

### ISSUE THREAD

**Issue by FossPrime** [PowerShell/Win32-OpenSSH#222]
The problem is that the wiki instructions ask you to put the program in `C:\Program Files\OpenSSH-Win64` but the default config points to a non existing `/win32openssh/bin/sftp-server.exe` making matters worse, `scp.exe` does not in fact come with the default distributed package. Program Files is probably the right place... but I can't see in the code how this misconfiguration comes about.
# Original Symptoms for reference

sftp broken pipe, couldn't read packet, connection reset by peer 
Running the latest ecdsa supporting build of OpenSSH on Windows Server 2012 R2.

```
sftp Administrator@10.0.1.202
packet_write_wait: Connection to 10.0.1.202: Broken pipe
Couldn't read packet: Connection reset by peer
```

![screenshot from 2016-05-19 12-07-18](https://cloud.githubusercontent.com/assets/876076/15400830/03146a68-1dbb-11e6-993e-de85892863cd.png)

Sidenote: Backspace doesn't work when logged in via SSH, unsure what shell runs on the windows side.

heres my sshd_config

```
# $OpenBSD: sshd_config,v 1.84 2011/05/23 03:30:07 djm Exp $

Subsystem   sftp    /win32openssh/bin/sftp-server.exe
Subsystem   scp /win32openssh/bin/scp.exe

```

**Comment by RayFoss** [comment]
The problem is that the wiki instructions ask you to put the program in `C:\Program Files\OpenSSH-Win64` but the default config points to a non existing `/win32openssh/bin/sftp-server.exe` making matters worse, `scp.exe` does not in fact come with the default distributed package.

**Comment by charabaruk** [comment]
@RayFoss if you change the path for `Subsystem sftp` to the sftp-server.exe in the installation directory, SFTP works fine. However, you're right that the path should be correctly configured in the out-of-box sshd_config file.

As for SCP I believe that there have been issues with porting it that have lead to it being _removed_ for the last few releases until they can fix it up.

**Comment by manojampalam** [comment]
Feedback taken. Will fix it in next release.

**Comment by fjaenal** [comment]
Is scp going to be back?

**Comment by charabaruk** [comment]
@fjaenal I would assume SCP will return before the integration milestone is hit, but it needs to work again first. Until then, it's a good thing that it isn't included in the packaged builds.

**Comment by manojampalam** [comment]
Right.
