### ISSUE TITLE
Add SSH server compression support

### ISSUE THREAD

**Issue by sima945** [PowerShell/Win32-OpenSSH#2224]
### Summary of the new feature / enhancement

It looks like SSH server compression is not supported, will this be added at some point?

https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration#configuration-arguments

### Proposed technical implementation details (optional)

Add SSH server compression option and allow it to be configured

**Comment by tgauth** [comment]
@Forum1877621 thanks for opening an issue - it looks like our documentation on this is out of date!

ZLib is used for compression within Win32-OpenSSH since v8.1. 

When initiating a connection via the ssh client, add `-C` to turn on compression.

**Comment by sima945** [comment]
I'll close this, it looks like the docs were updated
