### ISSUE TITLE
Error "BN_is_negative not found in DLL" when calling ssh after moving exe

### ISSUE THREAD

**Issue by trallnag** [PowerShell/Win32-OpenSSH#2228]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Install `OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2`.

I have installed it using WinGet from the package `Microsoft.OpenSSH.Beta`.

Copy `C:\Program Files\OpenSSH\ssh.exe` to `$HOME`.

Run `$HOME\ssh.exe -V` in PowerShell. Observe error.

### Expected behavior

```console
> C:\Users\tim\ssh.exe -V
OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2
```

### Actual behavior

```console
> C:\Users\tim\ssh.exe -V
Window pop ups with error message

> echo $LASTEXITCODE
-1073741511
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2

### Visuals

<img width="310" alt="Screenshot 2024-04-28 191308" src="https://github.com/PowerShell/Win32-OpenSSH/assets/24834206/05ac2c00-8dbd-44cd-a3a6-de9744f0a1e0">

**Comment by tgauth** [comment]
Try moving `libcrypto.dll` to the same folder as `ssh.exe`. It seems like it's picking up an older version of `libcrypto.dll` in the `$env:PATH`. See https://github.com/PowerShell/Win32-OpenSSH/issues/2052 for a similar issue.

**Comment by trallnag** [comment]
This indeed resolves the issue. Thanks for the hint.
