### ISSUE TITLE
Running ssh-agent.exe should start ssh-agent service

### ISSUE THREAD

**Issue by theaquamarine** [PowerShell/Win32-OpenSSH#224]
Running `ssh-agent.exe` starting the ssh-agent service would make integrating with existing scripts that use ssh-agent much easier, as at the moment they have to work out whether the program is Win32-OpenSSH's version and start the service instead.

`ssh-agent.exe -k` stopping the service would also be nice, but less important since the admin requirement means it'll have to be handled specially in many situations anyway.

**Comment by nigurr** [comment]
+1 vote. this should be default behavior.

if I pass any flag with ssh-agent, it simply crashes.
