### ISSUE TITLE
Do not require restarting when installing sshd with key-based authentication

### ISSUE THREAD

**Issue by alexchandel** [PowerShell/Win32-OpenSSH#225]
This is a massive papercut, and should **not** be necessary. In many cases, it's extremely inconvenient to restart an entire server just to fix sshd.

SSHD should be immediately runnable after installing, and it shouldn't consume 100% CPU before restarting like it currently does.

**Comment by manojampalam** [comment]
Restart is mandatory to register ssh-lsa.dll - (required to generate local user tokens without needing password). 
Unless there is a need to reinstall this dll, restart will not be necessary

**Comment by DarwinJS** [comment]
As a follow up - the Chocolatey package advises a restart because the same code is used for initial installs and upgrades - as all chocolatey packages do.  I build packages for the end target of an "upgrade install" because it is the harder case scenario to get right.

But if upon your own experimentation you do not need a restart in your scenario - you can, of course, go ahead without one.

**Comment by alexchandel** [comment]
@DarwinJS But Win32-OpenSSH literally requires a restart when installed with key-based authentication. It uses 100% CPU if you don't restart.

**Comment by DarwinJS** [comment]
OK - good to know - I based the behavior on the installation guide text that was available when I did the very first version.

**Comment by alexchandel** [comment]
If it's still present in the next release, I'll rename this to "sshd uses 100% CPU until restart when installed with key-based authentication from chocolatey package". I can't test it now, because the chocolatey seems to hang forever at psexec when I try to update to "2016.05.15".

If the 100% cpu usage isn't an issue, shouldn't key-based authentication be installed by default without `/KeyBasedAuthenticationFeature`?

**Comment by alexchandel** [comment]
@DarwinJS On upgrade, the chocolatey package should check whether ssh-lsa.dll has been changed during the upgrade, and restart sshd immediately if the DLL is the same as before and doesn't need to be re-registered.
