### ISSUE TITLE
User permission error

### ISSUE THREAD

**Issue by zxc9527** [PowerShell/Win32-OpenSSH#2256]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

I added a non-administrator user, test, and gave it read-only access to the sftp root directory, but it could still read and write from the root directory

Folder Permission:
![QQMail_1721635259416](https://github.com/user-attachments/assets/47b9ca22-e985-4235-b397-0c526bf6ab2e)

Config:
![QQMail_1721635261998](https://github.com/user-attachments/assets/c87e066f-6086-49b3-afea-b8a7d8ea140f)

Sftp client:
![QQMail_1721635264905](https://github.com/user-attachments/assets/e519c387-094c-4da8-8808-35d3cb893e9a)

### Expected behavior

```console
The specified user has only read permission on the specified path
```

### Actual behavior

```console
The specified user can read and write the read-only path
```

### Environment data

```PowerShell
PS C:\Program Files\OpenSSH> $PSVersionTable

 

Name                           Value

----                           -----

PSVersion                      5.1.17763.5458

PSEdition                      Desktop

PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}

BuildVersion                   ‪10.0.17763.5458‬

CLRVersion                     ‪4.0.30319.42000‬

WSManStackVersion              3.0

PSRemotingProtocolVersion      2.3

SerializationVersion           1.1.0.1
```

### Version

OpenSSH v9.5.0.0p1

**Comment by NoMoreFood** [comment]
What are the permissions for 'Users'?  The permissions are going to be the cumulative permissions of those assigned to 'test' + 'Users'.

**Comment by zxc9527** [comment]
> What are the permissions for 'Users'? The permissions are going to be the cumulative permissions of those assigned to 'test' + 'Users'.

Same permissions as test

**Comment by tgauth** [comment]
Can you verify that the `test` user only has read permissions to the folder outside of an SSH connection?

**Comment by NoMoreFood** [comment]
@zxc9527 You will have to remove 'Users' from any files under that directory.

**Comment by zxc9527** [comment]
> Can  verify that the `test` user only has read permissions to the folder outside of an SSH connection?

I have tested that other folders in D:\ path can also read and write

Thi


> Can you verify that the `test` user only has read permissions to the folder outside of an SSH connection?

**Comment by zxc9527** [comment]
> Can you verify that the `test` user only has read permissions to the folder outside of an SSH connection?

I have tested that other folders in D:\ path can also read and write

D:\ permission:
![QQMail_1721697002286](https://github.com/user-attachments/assets/de53303c-bd50-461f-b93a-d89657bedbfa)

**Comment by zxc9527** [comment]
> @zxc9527 You will have to remove 'Users' from any files under that directory.

It worked, thank you very much for your help
