### ISSUE TITLE
Install all builds to a subfolder with the same name

### ISSUE THREAD

**Issue by alexchandel** [PowerShell/Win32-OpenSSH#226]
The 64-bit version should not be installed to `/Program Files/OpenSSH-Win64` if the 32-bit version is installed to `/Program Files (x86)/OpenSSH-Win32`. This is a pointless difference that exists with virtually no other software package, nor even any other distribution of SSH. It only serves to add a layer of confusion for users. All architectures should be recommended to be installed to a subfolder of the same name, be it `OpenSSH-Win32` or just `OpenSSH`.

**Comment by manojampalam** [comment]
Feedback taken. I'll update wiki on next release.

**Comment by DarwinJS** [comment]
FYI - The Chocolatey package will also be updated on next release.

**Comment by DarwinJS** [comment]
Hoping you can pick another Program Files folder before release: https://github.com/PowerShell/Win32-OpenSSH/issues/256
