### ISSUE TITLE
winget install option for client only install

### ISSUE THREAD

**Issue by johnburnett** [PowerShell/Win32-OpenSSH#2270]
### Summary of the new feature / enhancement

I'd like to install the openssh client via winget, but not have the sshd service enabled.  I can work around this by running:
```powershell
Set-Service -Name sshd -StartupType 'Manual'
Stop-Service sshd
```
...but ideally there would be a way to prevent this in the first place.  And in the meantime, I'd recommend the above bit of powershell gets added to https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH to help others with the same request.

**Comment by tgauth** [comment]
you should be able to use [WinGet's](https://learn.microsoft.com/en-us/windows/package-manager/winget/install) `--override` parameter to pass: `ADDLOCAL=Client`

**Comment by johnburnett** [comment]
Ah great, thank you.  Where’s that documented?

**Comment by tgauth** [comment]
winget is using the MSI: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI.
I'll call that out explicitly in https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH.

**Comment by johnburnett** [comment]
Sounds great, thanks!
