### ISSUE TITLE
> ### Prerequisites

### ISSUE THREAD

**Issue by OAIUR** [PowerShell/Win32-OpenSSH#2272]
> ### Prerequisites
> * [x]  Write a descriptive title.
> * [x]  Make sure you are able to repro it on the latest version
> * [x]  Search the existing issues.
> 
> ### Steps to reproduce
> If I Output to a consolegridview, I would expect the column header to be above the columns itself. Currently they seem to be two space to the right? Get-process | out-consolegridview
> 
> ### Expected behavior
> ```
> Be in line with the column
> ```
> 
> ### Actual behavior
> ```
> Two position more to the right
> ```
> 
> ### Error details
> _No response_
> 
> ### Environment data
> ```powershell
> Name                           Value
> ----                           -----
> PSVersion                      7.2.6
> PSEdition                      Core
> GitCommitId                    7.2.6
> OS                             Linux 5.15.56-v8+ #1575 SMP PREEMPT Fri Jul 22 20:31:26 BST 2022
> Platform                       Unix
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0
> ```
> 
> ### Version
> 0.7.2
> 
> ### Visuals
> ![358CC30E-BEAE-4D1F-8939-F9666F734ED4](https://user-images.githubusercontent.com/65505278/186497318-6d674334-7e90-4496-bbcb-bf60d0568e3a.jpeg)

[]()

_Originally posted by @OAIUR in https://github.com/PowerShell/.github/issues/5#issuecomment-2347024115_

**Comment by maertendMSFT** [comment]
This is not a SSH issue.  I see an issue created in another PowerShell repo.  Closing this issue.
