### ISSUE TITLE
Understanding question - will there be updates after 9.5.0.0 or not?

### ISSUE THREAD

**Issue by Saxomania** [PowerShell/Win32-OpenSSH#2277]
### Summary of the new feature / enhancement

May i dont have a clue but will updates offered here after version 9.5.0.0? If not how could i get them?

### Proposed technical implementation details (optional)

check above please

**Comment by maertendMSFT** [comment]
yes, but we do not track every upstream release.  We evaluate if the changes made upstream have impact in the Windows environment and make a decision based off that information.  There will be future releases.
