### ISSUE TITLE
ripemd160 HMAC support

### ISSUE THREAD

**Issue by krz101** [PowerShell/Win32-OpenSSH#2289]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

When using ssh command I am getting error "no matching MAC found. Their offer: hmac-ripemd160, hmac-sha1".

In older version 8.1 I did not have this issue with the same ssh command.

### Expected behavior

```console
Expected ssh command to create tunnel connection with no errors
```

### Actual behavior

```console
"no matching MAC found. Their offer: hmac-ripemd160, hmac-sha1"
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.5007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.5007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

9.5

**Comment by maertendMSFT** [comment]
This is a result of a change that was made upstream in OpenSSH 7.6: https://www.[openssh.com/txt/release-7.6](https://www.openssh.com/txt/release-7.6)

Did you have it explicitly added after 7.6 was released? 

We also removed SHA1 in release 9.5, so you may have just been relying on SHA1.  Once that was removed and pushed out, then you were no longer supported by default.

**Comment by krz101** [comment]
Thanks for the clarification. Looks like I can specify the option -o MACS=hmac-sha1 and it works.

**Comment by krz101** [comment]
Closing this since the issue was the removal of sha1 from defaults. One can specify to use that MAC in the command options or the .ssh config file.
