### ISSUE TITLE
SFTP put text file overwrite bug

### ISSUE THREAD

**Issue by gr9** [PowerShell/Win32-OpenSSH#229]
openssh version: 5_15_2016 (x64)
OS Version: Windows Server 2012 datacenter edition (azure)
SFTP Clients Tested: FileZilla (OS X), sftp OS X, WinSCP (windows 10)
Logs: nothing pertinent in sshd_logs or windows event viewer

When overwriting a text file (and possibly binary?) using any of these clients or client OS's, if the new text file is shorter (less characters/lines) than the file to be overwritten - then the difference in file length will be appended to the new file from the old file.

Steps to reproduce: 

1)create a file called test.txt with the following contents:
one
\
two three
four
five.

2)Upload said file to the server using any of the client's listed above.  If you log into the server using RDP & open the file directly on the server - you should see it uploads correctly.

3) Edit the text file by reducing the number of lines/characters to the following:
on
two th
four
five.

4) Upload the file again to the server - making sure to confirm the overwrite
5) Log directly into the server again using RDP and open the file again using a text editor directly on the server & review contents of the overwritten file; you should see the following instead of what was entered in step 3 (note the extra 'five.' appended on a new line):
on
two th
four
five.
five.

**Comment by gr9** [comment]
FYI - I also noticed this in the march 2016 version of openssh; but installed the latest just now to verify its still happening.

**Comment by manojampalam** [comment]
Can you try out latest release?

**Comment by gr9** [comment]
Beautiful - confirmed fix; thank you kindly!
