### ISSUE TITLE
v9.8 doesn't log connects, disconnects, and failed attempts

### ISSUE THREAD

**Issue by user8446** [PowerShell/Win32-OpenSSH#2292]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

After upgrading to v9.8, the ssh longs no longer shows connections, disconnects, and failed attempts. This is a security issue as admins are now blind to ssh activity. Only server listening is logged:

`4400 2024-10-17 10:53:56.221 Server listening on 0.0.0.0 port #####.`

### Expected behavior

```console
Connects and disconnects should be logged.
```

### Actual behavior

```console
Connects and disconnects are not logged.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

9.8

**Comment by tgauth** [comment]
Are you referring to file-based logging or event viewer? For file-based logging in v9.8, connection info should be in `sshd-session.log`

**Comment by user8446** [comment]
Ok I see now, sessions are now broken out into `sshd-session.log` and not combined with `sshd.log` anymore. Thank you for pointing that out!
