### ISSUE TITLE
OpenSSH-Win32 doesn't work properly with config file

### ISSUE THREAD

**Issue by Peilun0912** [PowerShell/Win32-OpenSSH#23]
After creating C:\Users\username\\.ssh\config, no matter what contents are inside, the `ssh` command always show:

```
fstat C:\Users\<username>/.ssh/config: 操作順利完成。
```

**Comment by mikepruett3** [comment]
Same issue. If I rename the config file, it works. Support for config files would be appreciated.

**Comment by scottdware** [comment]
If you rename it to `ssh_config` and place it under C:\Users\<username> then it will work, I've found.

**Comment by cydhaselton** [comment]
Is that true for the sshd_config file as well?

**Comment by scottdware** [comment]
For the `sshd_config` file I have that in the root directory with all the rest of the binaries (i.e. `C:\OpenSSH` for me).

**Comment by Peilun0912** [comment]
Since `C:\Users\<username>\ssh_config` works, I'm closing this issue. Thanks for help!

**Comment by kpaleniu** [comment]
I would not consider this issue resolved, even if there is a workaround. In my opinion, the correct fix for this would be to either

* fix reading the user-defined config file from standard location, i.e. `~/.ssh/config`, or
* introduce a more Windows-ish pattern, for example storing the configuration in appdata.

**Comment by kpaleniu** [comment]
Also, one other thing to note. Renaming the folder `.ssh` to `_ssh` also works.
