### ISSUE TITLE
LOCALAPPDATA, TEMP, TMP and other profile related env variables missing in ssh session

### ISSUE THREAD

**Issue by jake-at-work** [PowerShell/Win32-OpenSSH#230]
With 5/30/2016 release the follow environment variables are not set:

`LOCALAPPDATA=C:\Users\Administrator\AppData\Local`
`TEMP=C:\Users\ADMINI~1\AppData\Local\Temp\2`
`TMP=C:\Users\ADMINI~1\AppData\Local\Temp\2`

Executing powershell results in the following error:

`The shell cannot be started. A failure occurred during initialization:
Illegal characters in path.`

**Comment by manojampalam** [comment]
Yes. Still working on "how to securely load user profile". Set them explicitly as a workaround for the time being.

**Comment by YuqingZhao-zz** [comment]
Manoj, when will this issue be fixed? I'm working on a tool relying on %TMP% variable.

**Comment by manojampalam** [comment]
ETA - 7/22

**Comment by discodance1** [comment]
What is the work around for this? I have set the TMP,TEMP,LOCALAPPDATA env variables but launching powershell.exe via cmd on openssh still gives me "illegal characters in path error".

**Comment by manojampalam** [comment]
This was fixed a while back. Reopen if needed.
