### ISSUE TITLE
Ssh-agent crashed when querying via ssh-add -L (2016-5-15)

### ISSUE THREAD

**Issue by dragon788** [PowerShell/Win32-OpenSSH#231]
I installed Win32-OpenSSH via chocolatey. I then opened a new regular user Powershell terminal and tried to use ssh-agent, it silently failed. I attempted to launch it to get usage with /? and -? and it crashed with a "not responding" error. I then opened a new Administrator Powershell terminal to start ssh-agent, it started, but as soon as I queried it with ssh-add -L it crashed.

Elevated session where I started the agent

```
PS C:\windows\system32> ssh-agent.exe
agent_start pid:9904, dbg:1, child:0, pipe:0
client pid 19016 connected on \\.\pipe\ssh-keyagent
debug1: connection io 000000B331A03F90 #bytes:0 state:0
debug1: connection io 000000B331A03F90 #bytes:4 state:1
debug1: connection io 000000B331A03F90 #bytes:1 state:2
debug1: connection 000000B331A03F90 clean up
debug1: iocp error: 6 on 0000000000000000
```

Normal session where I was attempting to access the agent

```
PS C:\Users\User> ssh-agent.exe
agent_start pid:18804, dbg:1, child:0, pipe:0
cannot create agent root reg key, ERROR:5
PS C:\Users\User> ssh
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-L address] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port]
           [-Q cipher | cipher-auth | mac | kex | key]
           [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
PS C:\Users\User> ssh-add -L
error fetching identities for protocol 2: communication with agent failed
The agent has no identities.
```

In the Administrator session after it crashed

```
PS C:\windows\system32> ssh-add -L
Could not open a connection to your authentication agent.
```

**Comment by manojampalam** [comment]
you are supposed to start ssh-agent as a service. 
net start ssh-agent

See release notes

**Comment by dragon788** [comment]
I was trying to query it from PowerShell's Get-Service but it was reporting it didn't exist.

**Comment by DarwinJS** [comment]
@manojampalam - if it is running properly as a service they would also run psexec.exe to get into system account context first?  Like we have to do to run ssh-add.exe during install right?

**Comment by dragon788** [comment]
Do you guys maintain the Chocolatey install or not? It doesn't appear to have installed the services, and when I was looking at the install documentation it mentioned running sshd, I don't need sshd as I simply want to use the OpenSSH client/agent functionality. Is this supported and is there a "client only" install document?

**Comment by DarwinJS** [comment]
I maintain the Chocolatey package, but I am not on the Win32-OpenSSH team.

If you run the chocolatey package with no parameters you get a client only install.  You'll still see the service .exes in the folder because the zip has everything in it - but they are not configured.

Are you saying you'd like to use the shh-agent to cache keys for a client install then?

**Comment by dragon788** [comment]
@DarwinJS That explains the behavior I was seeing, I could find it in the PATH but the service wasn't registered.

Yes I would be very interested in using ssh-agent and ssh-add with the client without having the sshd server service running. This would allow me to use `vagrant ssh` as a command without having to install cygwin or Git Bash just to connect to my various virtual machines.

Having ssh-agent without having the sshd service might also be more secure for machines of developers or regular end users that don't want/need to remotely access their own machines. The agent service is hardly something that would be a likely attack vector on Windows, but its also much less exposed than having another service running on an open port.

**Comment by dragon788** [comment]
@DarwinJS Just tried a `vagrant ssh` and it is working without having a working ssh-agent, but that is probably because in this case Vagrant is handling the key exchange/user credentials. I'd be happy to help test if you have any "beta" packages with the new functionality as I can see myself using this a lot more in my new position doing DevOps for Windows.
