### ISSUE TITLE
Linux can be updated remotely. Windows cannot. It should. (Reopens #2083)

### ISSUE THREAD

**Issue by doctorpangloss** [PowerShell/Win32-OpenSSH#2310]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Revisiting this issue because I think there's a chance you will take a look at it again.

I ought to be able to update my Windows installation from an OpenSSH session the same way I update anything else, like my Linux servers.

 1. Run the following script:
```
Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
Install-Module -Name PSWindowsUpdate -Force
Get-WindowsUpdate -MicrosoftUpdate -AcceptAll -Install -IgnoreReboot
```
2. Observe the following error:
```
Get-WindowsUpdate : Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
At line:1 char:1
+ Get-WindowsUpdate -MicrosoftUpdate -AcceptAll -Install -IgnoreReboot
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsUpdate], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,PSWindowsUpdate.GetWindowsUpdate
```
 
3. There is no workaround to install Windows Updates.

This earlier workaround, authored by the community, has always failed:

```
Enable-WURemoting
Invoke-WuJob -Script { ipmo PSWindowsUpdate; Install-WindowsUpdate -AcceptAll -AutoReboot | Out-File "C:/Windows/PSWindowsUpdate.log"} -RunNow -Confirm:$false -Verbose -ErrorAction Ignore
```

### Expected behavior

```console
(Windows updates are installed)
```

### Actual behavior

```console
PS> Get-WindowsUpdate -MicrosoftUpdate -AcceptAll -Install -IgnoreReboot
...
Get-WindowsUpdate : Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
At line:1 char:1
+ Get-WindowsUpdate -MicrosoftUpdate -AcceptAll -Install -IgnoreReboot
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsUpdate], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,PSWindowsUpdate.GetWindowsUpdate
```

### Environment data

```PowerShell
$PSVersionTable

Name                           Value                                                                            
----                           -----                                                                            
PSVersion                      5.1.20348.1366                                                                   
PSEdition                      Desktop                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                          
BuildVersion                   10.0.20348.1366                                                                  
CLRVersion                     4.0.30319.42000                                                                  
WSManStackVersion              3.0                                                                              
PSRemotingProtocolVersion      2.3                                                                              
SerializationVersion           1.1.0.1
```

### Version

OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

**Comment by StevenBucher98** [comment]
Thanks for bringing this back up to our attention! Have you tried submitting an issue with the module owners https://github.com/mgajda83/PSWindowsUpdate/issues ? From what we gathered there does not seem to be any changes to the APIs so this comment still seems to stand, https://github.com/PowerShell/Win32-OpenSSH/issues/2083#issuecomment-1658905172. We can investigate a little further but suggest reaching out to the module owner to see if you can get more insight on work arounds or fixes within that module.

**Comment by doctorpangloss** [comment]
well listen I'm not stupid and I'm not trying to be annoying, I hear you on the "This Behavior is by Design" brainrot, I really appreciate your attention on the matter. But maybe one way to formulate the bug is that `Get-WindowsUpdate : Access is denied` is wrong: I am logged in as someone with privileges to do a Windows Update, so I should be able to do a Windows Update. Or help me innovate a formulation of this bug to get this issue addressed? I think it would add a ton of value to OpenSSH for Windows if it could be used to update Windows.

**Comment by mgkuhn** [comment]
The Bitvise SSH server allows configuration of the logon type between "network" and "interactive". Does using that solve your problem? https://bitvise.com/ssh-server-guide-logon-type
