### ISSUE TITLE
Register ssh-lsa.dll without restarting

### ISSUE THREAD

**Issue by alexchandel** [PowerShell/Win32-OpenSSH#233]
The installer needs to find a way to register ssh-lsa.dll/load at install time, so a logout/restart isn't required. Restarting, even if it's only once, is a papercut, and shouldn't be necessary. This is a tracking issue for suggestions and progress towards implementing them.

**Comment by manojampalam** [comment]
dup #225.

**Comment by DarwinJS** [comment]
FYI the latest choco package checks the file size and only upgrades if it has changed.

I also requested that the dev team start using versioning in the binaries so it is even easier to tell when things have changed.
