### ISSUE TITLE
Please start versioning all binaries (and a complete set of binary headers)

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#235]
For instance, ssh-lsa.dll appears to have no data in the fileversioninfo and version is set to 0.0.0.0.

This is making it difficult to create the chocolatey installer and detect file changes.

It will also be difficult to create any other type of installer that intelligently updates files only if needed.

**Comment by manojampalam** [comment]
Changes checked in L1-Prod. Releases going forward will have binaries versioned.

**Comment by DarwinJS** [comment]
Would it be possible to review all the binary file headers and update them with appropriate values?  For instance, this would be a great way to know that this is the version built by Microsoft PowerShell Team by looking at headers.
