### ISSUE TITLE
ssh from a mac or linux clients

### ISSUE THREAD

**Issue by rickmoua** [PowerShell/Win32-OpenSSH#236]
I have loaded the latest openssh-win64 on a windows 2012 R2.  From the client Mac/Linux, I doesn't seem to take the password.  

MacBook-Pro: $ ssh jsmith@server1
jsmith@server1's password: 
Permission denied, please try again.
jsmith@server1's password: 
Just wondering why this standardized method don't work with openssh-win64

However, the below worked.
MacBook-Pro: $ ssh jsmith@store@server1
where domain name is "store". This is different than the standard way.  Is there a plan to make it work like in the standardized way?

**Comment by manojampalam** [comment]
if jsmith is a domain user, you need to user the -l option. See wiki for usage examples.
