### ISSUE TITLE
Windows Symbolic Links to folders don't show up

### ISSUE THREAD

**Issue by luanthom** [PowerShell/Win32-OpenSSH#238]
Windows symlinks (soft links) to folders on the SFTP server do not show up in a directory list in a SFTP client.

Tested with Bitvise SFTP and Centos 6 SFTP clients against Win32-OpenSSH  5-30-2016.

**Comment by bagajjal** [comment]
Please check the latest release.
I have validated with Bitvise SFTP client and it is showing soft links.
