### ISSUE TITLE
permision denied(public key)

### ISSUE THREAD

**Issue by tomekirov** [PowerShell/Win32-OpenSSH#239]
Anyone help me with this agent log file error configured on Windows Server 2012 R2:

3904 16:23:34 318 agent_start pid:3904, dbg:0, child:0, pipe:0
3904 16:25:36 752 client pid 12792 connected on \.\pipe\ssh-keyagent
3904 16:25:36 754 debug1: spawned child 8920 to process 3
8920 16:25:36 762 agent_start pid:8920, dbg:0, child:1, pipe:384
8920 16:25:36 762 debug1: connection io 000000F9C713EBE0 #bytes:0 state:0
3904 16:25:37 437 client pid 12792 connected on \.\pipe\ssh-authagent
3904 16:25:37 438 debug1: spawned child 12576 to process 3
12576 16:25:37 447 agent_start pid:12576, dbg:0, child:1, pipe:392
12576 16:25:37 447 debug1: connection io 000000481D01EBE0 #bytes:0 state:0
12576 16:25:37 447 debug1: connection io 000000481D01EBE0 #bytes:4 state:1
12576 16:25:37 447 debug1: connection io 000000481D01EBE0 #bytes:978 state:2
12576 16:25:37 448 debug1: client type: 3
12576 16:25:37 448 debug1: unable to generate user token
12576 16:25:37 448 debug1: connection 000000481D01EBE0 clean up
12576 16:25:37 448 debug1: iocp error: 6 on 0000000000000000 

8920 16:25:37 523 debug1: iocp error: 109 on 000000F9C713EBE0 

8920 16:25:37 523 debug1: connection 000000F9C713EBE0 clean up
8920 16:25:37 523 debug1: iocp error: 6 on 0000000000000000 

Also i run the commands : powershell.exe .\install-sshlsa.ps1
ntrights.exe -u +r SeAssignPrimaryTokenPrivilege

**Comment by manojampalam** [comment]
Still facing this issue? Are you using local user account? If so can you make sure ssh-lsa is installed ? Reopen if needed.
