### ISSUE TITLE
Tab autocompletion blank in cmd

### ISSUE THREAD

**Issue by robotdad** [PowerShell/Win32-OpenSSH#24]
When running ssh in cmd tab autocompletion works but does not display characters. It does in Powershell.

**Comment by manojampalam** [comment]
This is due to a limitation in how I/O is directed through cmd.exe on server side. We'll try to address this while moving the default shell to PowerShell.

**Comment by skullkiller** [comment]
tab completion also doesn't work properly in powershell. The command get tab completed, but we can see it in the screen)

**Comment by robotdad** [comment]
This looks like it is working in the current build for powershell and cmd

**Comment by manojampalam** [comment]
Did not expect this to work :) What client are you using?

**Comment by cydhaselton** [comment]
I'm using the latest build and don't have tab completion in cmd or powershell, FYI.
Also, using different SSH clients result in widely different results with display and output.

**Comment by manojampalam** [comment]
Expected. Tab completion wouldn't work yet. Share details on the different SSH clients and the different results you are seeing.

**Comment by cydhaselton** [comment]
Good to know.
For right now I'll focus on ConnectBot display/output results...it's the easiest to use with SSHD so far.
