### ISSUE TITLE
sshd service terminates after a brief period of time

### ISSUE THREAD

**Issue by gr9** [PowerShell/Win32-OpenSSH#241]
ServerOS: MS Server 2012 r2 Datacenter edition (azure)
SSH/SFTP Client: N/A

After upgrading to the latest build (thanks!) to fix my previous issue - it seems now that the sshd service stops after a short while; maybe an hour or so.  So far all I have found are these logs from sshd.txt:

```
504 18:41:24 112 Server listening on :: port 22.
504 18:41:24 112 Server listening on 0.0.0.0 port 22.
3652 18:44:00 255 Accepted password for Reece Griffin from 184.69.145.158 port 56081 ssh2
3520 18:44:06 986 Accepted password for Reece Griffin from 184.69.145.158 port 56082 ssh2
3392 18:45:21 238 Accepted password for Reece Griffin from 184.69.145.158 port 56091 ssh2
792 18:45:27 919 Accepted password for Reece Griffin from 184.69.145.158 port 56092 ssh2
504 18:47:21 175 Received signal 8; terminating.
1716 18:47:45 075 Server listening on :: port 22.
1716 18:47:45 075 Server listening on 0.0.0.0 port 22.
3004 18:50:37 620 Accepted password for Reece Griffin from 184.69.145.158 port 56115 ssh2
1784 18:50:44 475 Accepted password for Reece Griffin from 184.69.145.158 port 56116 ssh2
3272 18:51:39 453 Accepted password for Reece Griffin from 184.69.145.158 port 56121 ssh2
3304 18:51:45 981 Accepted password for Reece Griffin from 184.69.145.158 port 56122 ssh2
3376 18:53:15 297 WARNING: ./moduli does not exist, using fixed modulus
3376 18:53:41 389 Accepted password for Reece Griffin from 184.69.145.158 port 56200 ssh2
3752 18:53:53 792 WARNING: ./moduli does not exist, using fixed modulus
3752 18:53:55 496 Accepted password for Reece Griffin from 184.69.145.158 port 56210 ssh2
3264 21:27:05 747 Server listening on :: port 22.
3264 21:27:05 747 Server listening on 0.0.0.0 port 22.
2536 21:27:43 641 Accepted password for Reece Griffin from 184.69.145.158 port 57671 ssh2
4092 21:27:59 963 Accepted password for Reece Griffin from 184.69.145.158 port 57672 ssh2
4040 21:29:25 700 Accepted password for Reece Griffin from 184.69.145.158 port 57676 ssh2
```

the ssh-agent service continues to be in the 'Running' state; its sshd that requires period manual restarting for me.  Please let me know if there is any further diagnosis I can provdie.

**Comment by gr9** [comment]
as a workaround in the mean time I've just set the properties for the service to automatically restart the service in case of failure.

**Comment by manojampalam** [comment]
Can you check event viewer on why the service has stopped (in System log) ?

If its reported that the service terminated abruptly, it most likely crashed. I'll ensure to upload symbols for subsequent releases. We'll have to attach a debugger (https://msdn.microsoft.com/en-us/library/windows/hardware/ff551063(v=vs.85).aspx) and get a crash a dump.

**Comment by areiter** [comment]
I think I have the same problem.
sshd frequently stops working with the following error message.

```
Faulting application name: sshd.exe, version: 0.0.0.0, time stamp: 0x574c7019
Faulting module name: KERNELBASE.dll, version: 10.0.10586.494, time stamp: 0x5775e4c5
Exception code: 0x80000003
Fault offset: 0x00000000000c2d52
Faulting process ID: 0x650
Faulting application start time: 0x01d1df1c47c91d4f
Faulting application path: C:\Program Files\OpenSSH-Win64\sshd.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report ID: d7dd10a0-688c-477f-9558-6fd989bb7a3a
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by JD10NN3** [comment]
same error here

**Comment by yukisekisan** [comment]
Same error here.

OS: Windows Server 2012 R2 64x

The time of exception is random

**Comment by nathannoble** [comment]
Same error

**Comment by mzagar** [comment]
Same error here:

Faulting application name: sshd.exe, version: 0.0.1.0, time stamp: 0x57ef503e
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18292, time stamp: 0x56fcb50a
Exception code: 0x80000003
Fault offset: 0x00000000000de2d2
Faulting process id: 0x654
Faulting application start time: 0x01d220631d40f9a1
Faulting application path: C:\Program Files\OpenSSH\sshd.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 7d416b8d-8c56-11e6-80d7-00155d1e6600
Faulting package full name: 
Faulting package-relative application ID:

**Comment by soidamientrung** [comment]
Same error:
Faulting application name: sshd.exe, version: 0.0.0.0, time stamp: 0x574c7019
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18264, time stamp: 0x56e1bd71
Exception code: 0x80000003
Fault offset: 0x00000000000de0e2
Faulting process id: 0xf8c
Faulting application start time: 0x01d229af75fd5810
Faulting application path: C:\openssh\sshd.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 05315aff-95e0-11e6-80cb-005056b264b5
Faulting package full name: 
Faulting package-relative application ID:

**Comment by swaminathanvetri** [comment]
Facing the same error with the below logs from event viewer!
Faulting application name: sshd.exe, version: 0.0.0.0, time stamp: 0x574c7019
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18007, time stamp: 0x55c4c341
Exception code: 0x80000003
Fault offset: 0x00000000000ddfd2
Faulting process id: 0x1e6c
Faulting application start time: 0x01d22b5d069df58b
Faulting application path: C:\OpenSSH\sshd.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 34d79087-9832-11e6-80f6-005056b6e5fc
Faulting package full name: 
Faulting package-relative application ID: 

OS: Windows Server 2012 R2 64x

Any workaround or resolution for this issue ?

**Comment by gr9** [comment]
As for workaround - you can change the settings in the services control panel (Control Panel->System->Administrative Tools->Services;  Right click sshd->Properties.  In the Recovery tab; set first, second and all subsequent failures to restart the service after a minute.  This makes the service mostly usable - however still not ideal; my guess is that I get approx 95% sshd uptime this way.  You have to wait for it to recover a couple of times a day.

**Comment by wrigler** [comment]
Hello, facing also the same error (Windows 2012R2 fully updated):
Faulting application name: sshd.exe, version: 0.0.2.0, time stamp: 0x580c37e9
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18340, time stamp: 0x57366075
Exception code: 0x80000003
Fault offset: 0x00000000000de2d2
Faulting process id: 0xb00
Faulting application start time: 0x01d235c915682458
Faulting application path: C:\OpenSSH-Win\sshd.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 64c0bc79-a1be-11e6-80f1-005056010ace
Faulting package full name: 
Faulting package-relative application ID:

**Comment by rgl** [comment]
have you guys tried with the [latest version v0.0.5.0](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.5.0)?

**Comment by friism** [comment]
With 0.0.3.0 I started setting `sc.exe failure sshd reset= 86400 actions= restart/500` - that worked around the instability.

I'm running 0.0.5.0 with the restart setting above, but haven'g tested whether it's stable without.

**Comment by rgl** [comment]
can you see if the service has been restarting due to error?

**Comment by friism** [comment]
@rgl yeah, I think it is:

```
Get-EventLog -Log "Application" -Source "Application Error" -Message "*sshd.exe*" | Format-List


Index              : 649
EntryType          : Error
InstanceId         : 1000
Message            : Faulting application name: sshd.exe, version: 0.0.5.0, time stamp: 0x585626f5
                     Faulting module name: KERNELBASE.dll, version: 10.0.14393.321, time stamp: 0x57f4c4f0
                     Exception code: 0x80000003
                     Fault offset: 0x00000000000c6142
                     Faulting process id: 0x1298
                     Faulting application start time: 0x01d2602a146e0964
                     Faulting application path: C:\OpenSSH-Win64\sshd.exe
                     Faulting module path: C:\Windows\System32\KERNELBASE.dll
                     Report Id: d577f0de-2efd-4053-a96a-f6b5205cabb2
                     Faulting package full name:
                     Faulting package-relative application ID:
Category           : Application Crashing Events
CategoryNumber     : 100
ReplacementStrings : {sshd.exe, 0.0.5.0, 585626f5, KERNELBASE.dll...}
Source             : Application Error
TimeGenerated      : 12/27/2016 10:19:22 AM
TimeWritten        : 12/27/2016 10:19:22 AM
UserName           :

Index              : 648
EntryType          : Error
InstanceId         : 1000
Message            : Faulting application name: sshd.exe, version: 0.0.5.0, time stamp: 0x585626f5
                     Faulting module name: KERNELBASE.dll, version: 10.0.14393.321, time stamp: 0x57f4c4f0
                     Exception code: 0x80000003
                     Fault offset: 0x00000000000c6142
                     Faulting process id: 0x15a0
                     Faulting application start time: 0x01d26029e7c65781
                     Faulting application path: C:\OpenSSH-Win64\sshd.exe
                     Faulting module path: C:\Windows\System32\KERNELBASE.dll
                     Report Id: 265eaed9-1a65-45dd-aa88-c16fd8e64db5
                     Faulting package full name:
                     Faulting package-relative application ID:
Category           : Application Crashing Events
CategoryNumber     : 100
ReplacementStrings : {sshd.exe, 0.0.5.0, 585626f5, KERNELBASE.dll...}
Source             : Application Error
TimeGenerated      : 12/27/2016 10:14:58 AM
TimeWritten        : 12/27/2016 10:14:58 AM
UserName           :
```

**Comment by rgl** [comment]
ouch :-(

**Comment by carcus88** [comment]
Getting the same exception code 0x80000003 at random times when the ssh server is just sitting idle.

**Comment by manojampalam** [comment]
Can you please update to the latest version and get a crash dump if possible?

**Comment by friism** [comment]
@manojampalam how does one collect that?

**Comment by gd197** [comment]
Same exception code when multiple connection from client
Please look at my comment on #193
It might be linked

**Comment by carcus88** [comment]
@manojampalam I was using 0.0.4.0 and updated to 0.0.6.0 and still get the crashes. I can easily re-produce  the crash in a matter of minutes by spawning multiple SFTP sessions that upload and chdir on a lot of files (500+). I used the MS debug diagnostics tool to capture this crash dump.
[Crash rule for all instances of sshd.exe.zip](https://github.com/PowerShell/Win32-OpenSSH/files/702603/Crash.rule.for.all.instances.of.sshd.exe.zip)

Its worth noting that I have SSHD listening on two ports (22 and 222) for two different IP addresses. I am uploading to the second port during these tests (222). After the crash the service auto-restarts and I can still connect to port 22 but not port 222 until I manually restart the service.

**Comment by manojampalam** [comment]
Thanks. Let me try and re-produce.

**Comment by manojampalam** [comment]
Fix is at https://github.com/PowerShell/openssh-portable/pull/55. Will be available in Jan Mid drop.

**Comment by carcus88** [comment]
Initial tests are promising, I am no longer able to get sshd.exe to crash when uploading multiple files during multiple sessions. Thanks @manojampalam !

**Comment by gd197** [comment]
yep, no more crash on my side.
unfortunately this led now to issue 481.

**Comment by manojampalam** [comment]
#481 should  fixed in Jan-End drop

**Comment by gd197** [comment]
Thanks a lot for your great job @manojampalam !

**Comment by jashuang99** [comment]
hi all,
I'm new to using openssh.  we have 0.0.5.0 installed, but are currently experiencing the error described above.  Looks like the fix is in place.  Could someone guide me through how to apply the fix to the server?
much appreciated.

**Comment by bagajjal** [comment]
@jashuang99 - You are using very old version (0.0.5.0). Lot has changed. Upgrade to latest release https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by jashuang99** [comment]
@bagajjal , Thanks.  I've actually tried to upgrade to 0.0.24.0 on our test server, but wasn't able to find a detailed upgrade guide, and the newly installed version wouldn't even run.  so I've reverted it back to 0.0.5.0.  here's what I did for upgrade:
- backed up the current version
- uninstall the current version
- install the new version
- copy the config file back
does that look correct?

**Comment by bagajjal** [comment]
The latest release is [v1.0.0.0](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v1.0.0.0).
We have listed the required steps here,
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

Also have a look at the release notes,
https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v1.0.0.0

After all these, if you still fail to start the sshd.exe then run ".\sshd.exe -ddd" from an elevated cmd.exe.

**Comment by jashuang99** [comment]
@bagajjal Thanks for the information.  I've successfully upgraded it to version 1.0.  sshd.exe is started and running.  however, when I try to connect to the server from the client (using winscp), I get a timeout error.  Nothing was recorded in the log.  any suggestions to resolve this?  TIA.
