### ISSUE TITLE
SSH_ORIGINAL_COMMAND is not set when command is overridden

### ISSUE THREAD

**Issue by hach-que** [PowerShell/Win32-OpenSSH#243]
I need to intercept the commands being run by the client because the commands are assuming a UNIX shell.

I tried both `ForceCommand` (as part of sshd_config) and `command=` (as part of authorized_keys) and while they launch the process, they don't provide the original command at all.  It's supposed to be in `SSH_ORIGINAL_COMMAND`.

**Comment by hach-que** [comment]
I'm pretty sure this Win32-specific code near here:

https://github.com/PowerShell/Win32-OpenSSH/blob/946ed7d29761cfe239f1b80f08920b88f2236f42/session.c#L759

Needs something similar to:

https://github.com/PowerShell/Win32-OpenSSH/blob/946ed7d29761cfe239f1b80f08920b88f2236f42/session.c#L1751

Probably:

```
if (original_command)
    SetEnvironmentVariable("SSH_ORIGINAL_COMMAND", original_command);
```

**Comment by manojampalam** [comment]
Thanks for the suggestion. I've included it and it will be available in the next release (in a couple of days)
