### ISSUE TITLE
Running unknown command closes the connection / exits the agent process

### ISSUE THREAD

**Issue by solmersa** [PowerShell/Win32-OpenSSH#245]
On a Linux server running an unknown command (ie. ls3) thru ssh returns an error, in OpenSSH for Windows instead it aborts / closes the connection.  It should return an error too, so the client continue connected and could diagnose the trouble.  The latter is the sshd standard Linux behavior.
This is related to #61 and #60 .

**Comment by manojampalam** [comment]
Cannot repro this using Win32 client and deamon. Can you add more specific details ?

**Comment by solmersa** [comment]
This happens when using a SSH client like:
oSSh as SshNet::SshClient
THIS.oSSh = SshNet::SshClient(this.Host,THIS.nPort,this.User,this.Password)
- next line closes connection, you can check that in the server the child process
- is exited.  If you change host for a Linux host, only an error is returned, the connection
- remains valid / open

THIS.oSSh.RunCommand("dir')
- Yes I know that if you enclosed that by "command /c dir", it will work, but when failing should keep the connection open.  In the Openssh source code in fact there is an exit() instruction, so it ends the child process.

**Comment by manojampalam** [comment]
Please try the latest release and reopen if you still see this issue.
