### ISSUE TITLE
Ability to run BASH as the default shell

### ISSUE THREAD

**Issue by morgango** [PowerShell/Win32-OpenSSH#246]
I would like to be able to SSH to my Windows 10 box and run the new bash shell.  When I run this command, I get Error: 0x80070005.  From what I can gather, this is because the CMD shell is invoked with "legacy mode" on.  See [this issue](https://github.com/Microsoft/BashOnWindows/issues/110) for more details.

I would love to be able to log in and use the SSH shell by default, but would settle for being able to run the bash shell within the cmd shell as my first command.

BTW, this is very cool stuff indeed.  This is turning my gaming PC into a server I can use for development at work, and really augments my MacBook nicely.  Well done.

**Comment by manojampalam** [comment]
Thanks for the feedback. We'll consider it as part of Terminal improvement exercise we are going through.

**Comment by bagajjal** [comment]
IS this supported in the openssh unix flavor? If yes then please let us know the steps.
If not then we are not supporting this requirement.

Please reopen with required information.

**Comment by smokeintheshell** [comment]
@bagajjal From my experimentation it seems like currently the best method to achieve what you want is to the openssh-server from aptitude. I have yet to achieve getting this to run as a service or from boot, but there are many ways to get it to launch the daemon at user log in. From the linux openssh you can launch cmd.exe and a limited functioning powershell window.
Hope this helps

**Comment by bagajjal** [comment]
Please refer to this.
https://github.com/PowerShell/Win32-OpenSSH/issues/800

WSL bash can't be launched from ssh, 
https://github.com/PowerShell/Win32-OpenSSH/issues/289
