### ISSUE TITLE
`Bad address` error message printed in the ssh session when using tunneling

### ISSUE THREAD

**Issue by knocte** [PowerShell/Win32-OpenSSH#248]
Tunneling via `LocalForward` directives in your .ssh config file seems to work fine, however, if you check if the port is open via PowerShell's command `Test-NetConnection -Port 6379 -ComputerName localhost -InformationLevel Detailed`, you get a `bad address` message printed on the SSH session.

At first I thought this meant that tunneling wasn't actually working (and in fact, at times after doing this, the connection would hang, and I would need to restart the sshd server), but it's a red herring. If I just test my app that uses the port (instead of checking if the port is open via PowerShell), it works.

It would be great to fix this error message though.

**Comment by manojampalam** [comment]
Tried on the latest release and I see this no more. Reopen if you still see it.
