### ISSUE TITLE
Multiple sshd.exe processes created

### ISSUE THREAD

**Issue by fjaenal** [PowerShell/Win32-OpenSSH#249]
SSH implementation: 30/05/2016 (32 bits)
Server Operating System: Windows 2008 r2 64bits
Client Operating System: Windows 7 64 bits
Sftp client: java client using jcraft.

Client Code:
`if (! m_session.isConnected()) {
                establishSession(host, port, userName, password);
            }
            m_channel = m_session.openChannel("sftp");
            m_channel.connect();
            ChannelSftp c = (ChannelSftp) m_channel;`

Where m_session is com.jcraft.jsch.Session
Where m_channelis com.jcraft.jsch.Channel

Each time a channel is open it looks like a new sshd.exe process is created:
sshd.exe                      8440 Services                   0      5,960 K
sshd.exe                     13068 Services                   0      6,120 K
sshd.exe                     11804 Services                   0      5,948 K
sshd.exe                      9332 Services                   0      6,012 K
sshd.exe                     12024 Services                   0      6,184 K
sshd.exe                      4324 Services                   0      6,076 K
sshd.exe                     10088 Services                   0      6,176 K
sshd.exe                      8324 Services                   0      6,008 K
sshd.exe                      6668 Services                   0      5,960 K
sshd.exe                     10440 Services                   0      6,132 K
sshd.exe                      5916 Services                   0      6,028 K
sshd.exe                      9996 Services                   0      6,040 K
sshd.exe                      8356 Services                   0      6,004 K
sshd.exe                     10412 Services                   0      5,976 K
sshd.exe                      8092 Services                   0      6,148 K

And also in the netstat. Even if I close the channel the connection remains. How is that the services creates a process per connection? Is it working as intended?

I will try to reproduce this with more information.

Francisco

**Comment by fjaenal** [comment]
I have found that the processes are created each time I open an sftp connection. However, I think it creates a parent process (sshd.exe) and an underlying process for the sftp-server. When a disconnected is invoke the process killed by SIGCHLD is the sftp-server and the sshd.exe parent process is not always killed:

In another test I have this in the log
10536 12:20:57 972 debug1: Received SIGCHLD.
10536 12:20:57 973 debug3: waitpid - pid:-1, options:1
10536 12:20:57 973 debug1: Unregister child at index 0, 1 zombies of 1
10536 12:20:57 973 debug1: session_by_pid: pid 11732

But in the list of open sshd.exe none has that pid, that is why I think the sshd.exe is the parent process.

@manojampalam More Info.
Each time an sshd.exe  process is created it tried to save the id in the pid file, but because its in use it fails. This may also affect when trying to kill it:
9284 10:59:59 829 Accepted password for Administrator from 10.73.78.42 port 53319 ssh2
3692 11:00:21 028 error: Couldn't create pid file "c:\Windows\Temp\sshd.pid": Permission denied

**Comment by manojampalam** [comment]
Haven't gone through your complete report yet, but here are the design details -
sshd.exe server process spawns sshd.exe worker process for each incoming connection. This worker process will spawn a subsystem process (sftp-server.exe, ssh-shellhost.exe, etc) based on the invoked session. 
You'll similarly see a bunch of ssh-agent.exe processes. This is all expected and is designed such that we'll have the flexibility to reboot sshd (to consume config changes for ex) without interrupting existing connections/sessions. 

If what you see does not make sense based on these details, reopen please.

**Comment by fjaenal** [comment]
Just wanted to comment that even after disconnected and disconnection signal is sent (SIGCHLD) the worker process remains, not always, for quite a lot of time (can be hours). Maybe is it a Windows process   management issue.

Again thanks for the answer !!!!!
