### ISSUE TITLE
[QUESTION] SSH_MSG_DISCONNECT: 2 Too many authentication failures [SOLVED]

### ISSUE THREAD

**Issue by fjaenal** [PowerShell/Win32-OpenSSH#254]
Trying to connect to the server. I am getting:
"**Connection failed. SSH_MSG_DISCONNECT: 2 Too many authentication failures**"

The server logs are:
5816 16:06:08 238 Failed none for invalid user Administrator from 10.73.78.42 port 51735 ssh2
5816 16:06:08 239 Failed keyboard-interactive for invalid user Administrator from 10.73.78.42 port 51735 ssh2
5816 16:06:08 243 Failed password for invalid user Administrator from 10.73.78.42 port 51735 ssh2
5816 16:06:08 245 Failed password for invalid user Administrator from 10.73.78.42 port 51735 ssh2
5816 16:06:08 247 Failed password for invalid user Administrator from 10.73.78.42 port 51735 ssh2
5816 16:06:08 249 Failed password for invalid user Administrator from 10.73.78.42 port 51735 ssh2
5816 16:06:08 251 Failed password for invalid user Administrator from 10.73.78.42 port 51735 ssh2
5816 16:06:08 251 error: maximum authentication attempts exceeded for invalid user Administrator from 10.73.78.42 port 51735 ssh2

On the other hand this happens independently on which method I use (ssh console, jsch java program, putty, etc ...)

I have resterted the sshd server, reinstall it, restart the client, and anything I came through with no luck. Any idea???

**Comment by manojampalam** [comment]
Try it with one other user accounts. I'm guessing there is an issue with Administrator account itself (if password is valid)

**Comment by fjaenal** [comment]
Problem it was I was missing the shell-host executable in the directory. Thanks for the tips and the fast answer.
Keep the Great Job !
