### ISSUE TITLE
RemoteForward does not work

### ISSUE THREAD

**Issue by laughterk** [PowerShell/Win32-OpenSSH#259]
After connected to server, sshd.exe do listen at the specified port, but there're some problems:
1. sshd.exe only listens at 127.0.0.1 even if "*" is specified in "RemoteForward"
2. the connection is closed immediately after connected to the tcp port (ex.: using telnet)

**Comment by arif-pragmasys** [comment]
regarding issue no. 1, can you please share little bit more how are you using the RemoteForward config. Are you setting them in ssh_config?

issue no. 2 might be related to https://github.com/PowerShell/Win32-OpenSSH/issues/454

**Comment by laughterk** [comment]
> regarding issue no. 1, can you please share little bit more how are you using the RemoteForward config. Are you setting them in ssh_config?

Yes, I used RemoteForward in ~/.ssh/config: RemoteForward. Seems to work fine on v0.0.3.0.

> issue no. 2 might be related to #454

Tested here, the same error is reported on v0.0.3.0.

**Comment by manojampalam** [comment]
Reopen if needed. We have automated test case for remote forwarding and it seems to work
