### ISSUE TITLE
Ctrl+C terminate ssh client.

### ISSUE THREAD

**Issue by mfilippov** [PowerShell/Win32-OpenSSH#26]
When I press Ctrl+C for terminate command in ssh session ssh client was terminated.

**Comment by yuribank** [comment]
I noticed the same thing. It seems the client is intercepting SIGINT in a way that it should not.

**Comment by diogocp** [comment]
Duplicate of #20.

**Comment by manojampalam** [comment]
See above for duplicate issue link.
