### ISSUE TITLE
SFTP Issue

### ISSUE THREAD

**Issue by aress31** [PowerShell/Win32-OpenSSH#260]
Hi,

When I try to connect to a remote machine using SFTP, I keep getting this error message:
`fork: No such file or directory`
The SFTP server is properly configured. 
Any suggestion?

Best,
Alexandre

**Comment by librehat** [comment]
I encountered exactly the same issue. Win64 on windows 7. :(

**Comment by aress31** [comment]
Well, I found out that when launched directly from the openSSH directory (using the absolute path) the executable works just fine. Whereas, when adding the OpenSSH to the environement path and then invoking the sftp.exe executable from poweshell/cmd, we get this dodgy error message. 
`fork: No such file or directory`
Anyone got a workaround?

**Comment by manojampalam** [comment]
I'll fix this in next release

**Comment by manojampalam** [comment]
Reopen if you still see this issue
