### ISSUE TITLE
SFTP Autocomplete

### ISSUE THREAD

**Issue by aress31** [PowerShell/Win32-OpenSSH#261]
Would it be possible to implement command line automcplete using the tab key on an sftp session?

**Comment by manojampalam** [comment]
Does sftp autocomplete work in the Unix version of OpenSSH?

**Comment by bagajjal** [comment]
auto complete functionality is provided by the terminals (like cygwin) and not by the sftp.
sftp protocol doesn't deal with auto complete. please use terminals that support the auto complete (like cygwin).

**Comment by justinhelgerson** [comment]
@bagajjal Would this be something the PowerShell team would consider as a feature?  Assuming the end goal of the project is to have SSH and SFTP available by default in Windows, I think auto-completion is a must-have for the UX.

**Comment by gang929** [comment]
Win32-OpenSSH's SFTP can be build with libedit?  Maybe it support auto-completion feature.
