### ISSUE TITLE
SCP server does not work

### ISSUE THREAD

**Issue by grepwood** [PowerShell/Win32-OpenSSH#263]
When trying to connect with WinSCP to a server running this version of sshd, I don't get any response whatsoever. The firewall is open and the sshd is listening. When I try to ssh into the server, I get:

```
OpenSSH_6.7p1-hpn14v5, OpenSSL 1.0.1m 19 Mar 2015
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to REDACTED [REDACTED] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /home/mdec/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/mdec/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/mdec/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/mdec/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/mdec/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/mdec/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/mdec/.ssh/id_ed25519 type 4
debug1: key_load_public: No such file or directory
debug1: identity file /home/mdec/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.7p1-hpn14v5
debug1: ssh_exchange_identification: 220 Microsoft FTP Service


debug1: ssh_exchange_identification: 500 'SSH-2.0-OpenSSH_6.7p1-hpn14v5 ': command not understood.
```

Someone help please? :(

**Comment by Gondee** [comment]
Have you found any more information on the issue?

**Comment by grepwood** [comment]
@Gondee Where does PowerShell OpenSSH normally store logs? I've set LogFacility to AUTH.

**Comment by Gondee** [comment]
@grepwood Powershell I'm not sure. If you switch AUTH to debug, you will see the .log files in the directory where OpenSSH is installed. Here is the log when my pipe breaks
`12848 11:52:52 877 client pid 4480 connected on \\.\pipe\ssh-keyagent
12848 11:52:52 878 debug1: spawned child 6976 to process 3
6976 11:52:52 890 agent_start pid:6976, dbg:0, child:1, pipe:344
6976 11:52:52 891 debug1: connection io 000000000044EC40 #bytes:0 state:0
6976 11:52:52 891 debug1: connection 000000000044EC40 clean up
6976 11:52:52 891 debug1: iocp error: 6 on 0000000000000000`

**Comment by grepwood** [comment]
Nevermind, this is due to a mistake in server configuration. There was previously IIS 7.5 FTPS configured to run on that port alongside of a separate IIS 7.5 FTP instance. OpenSSH SFTP works nicely.
