### ISSUE TITLE
Turn on compression cause incomplete message error on OS X 10.11

### ISSUE THREAD

**Issue by laughterk** [PowerShell/Win32-OpenSSH#266]
When I'm connecting from OS X to windows with compression enabled, I get
"incomplete message" error as below:

$ ssh -o compression=yes hostname
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data ...
debug1: ...: Applying options for ...
debug1: ...: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to ... port 22.
debug1: Connection established.
debug1: identity file ... type 1
debug1: key_load_public: No such file or directory
debug1: identity file ... type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.1p1 Microsoft_Win32_port_with_VS
debug1: match: OpenSSH_7.1p1 Microsoft_Win32_port_with_VS pat OpenSSH\* compat 0x04000000
debug1: Authenticating to ... as '...'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> zlib@openssh.com
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> zlib@openssh.com
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:doiaHIOGR8ALC8Eg2BspPNtYfHOrvTNlc5v9u1LujV8
debug1: Host '...' is known and matches the ECDSA host key.
debug1: Found key in ...:6
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: ...
debug1: Server accepts key: pkalg ssh-rsa blen 535
debug1: Enabling compression at level 6.
debug1: Authentication succeeded (publickey).
Authenticated to ...
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
ssh_dispatch_run_fatal: Connection to ...: incomplete message

**Comment by elestedt** [comment]
Confirmed on windows client as well. Disabling compression allows the connection to complete.

**Comment by NiQ1** [comment]
Confirmed on *NIX clients as well -
  [~] # ssh -C Administrator@192.168.0.5
  The authenticity of host '192.168.0.5 (192.168.0.5)' can't be established.
  ECDSA key fingerprint is SHA256:****REMOVED****.
  Are you sure you want to continue connecting (yes/no)? yes
  Warning: Permanently added '192.168.0.5' (ECDSA) to the list of known hosts.
  Administrator@192.168.0.5's password:
  ssh_dispatch_run_fatal: Connection to 192.168.0.5 port 22: incomplete message

**Comment by bingbing8** [comment]
This should be fixed by now. Try latest release and reopen if needed.
