### ISSUE TITLE
sftp command line remote commands ignored

### ISSUE THREAD

**Issue by eperede** [PowerShell/Win32-OpenSSH#267]
Dear Developers,

we'd need to execute sftp command similar to Linux/Unix in Windows. There is one feature which does not work yet, the command line remote commands like
sftp.exe user@server ls
I'd expect the same result like in Linux that the remote directory is listed...

The same thing works perfectly with ssh.exe.
ssh.exe user@server ls
It produces the same result like in Linux/Unix.
Therefore I pressume that the issue could be easily and quickly solved which would allow us to use the same scripts in Windows like in Linux.
Platform: Windows 7
Openssh 30. 05. 2016, version Win64
Environment: cmd & Powershell

Thanks a lot in advance for the fix!

**Comment by manojampalam** [comment]
As per https://linux.die.net/man/1/sftp, there isn't a command option for SFTP. Are you sure this works in the Unix version? If not this would be a request for OpenSSH (not Windows specific).

**Comment by bagajjal** [comment]
sftp protocol doesn't take commands as arguments. this is the same behavior on linux and windows version of openssh code.
