### ISSUE TITLE
JSCH SFTP cannot connect "Broken Channel Error"

### ISSUE THREAD

**Issue by Gondee** [PowerShell/Win32-OpenSSH#268]
I looked through some of the other posts about this error but nothing has resolved the issue. I am attempting to connect to the latest version (5_30_2016) of OpenSSH using JSCH. I am just testing with the sample SFTP code provided by the JSCH website. 

Program Reports: 
`com.jcraft.jsch.JSchException: java.io.IOException: channel is broken`
OpenSSH Error log: 
`6700 12:07:53 736 agent_start pid:6700, dbg:0, child:0, pipe:0
6700 13:29:54 112 client pid 7784 connected on \.\pipe\ssh-keyagent
6700 13:29:54 114 debug1: spawned child 2024 to process 3
2024 13:29:54 124 agent_start pid:2024, dbg:0, child:1, pipe:344
2024 13:29:54 124 debug1: connection io 000000000012EC40 #bytes:0 state:0
2024 13:29:54 124 debug1: connection 000000000012EC40 clean up
2024 13:29:54 124 debug1: iocp error: 6 on 0000000000000000 

6700 13:30:08 630 shutdown
6700 13:30:08 630 debug1: shutting down
11232 13:30:09 847 agent_start pid:11232, dbg:0, child:0, pipe:0`

Also is there a reason I don't have a sshd.log? Any ideas on where to look next?

**Comment by Gondee** [comment]
Testing from Linux yields Broken Pipe Error. sftp error log doesnt fill either.

**Comment by manojampalam** [comment]
Ensure server side sftp subsystem is enabled and pointing to the right exe. 
Set LogLevel to DEBUG to have sshd.log generated. 
Reopen with logs if needed

**Comment by Gondee** [comment]
@manojampalam please excuse my inexperience with this. Can you point me in the right direction as to how to enable the SFTP server subsystem?
