### ISSUE TITLE
Strange output formatting when ssh'ing into server

### ISSUE THREAD

**Issue by JohRest** [PowerShell/Win32-OpenSSH#27]
Hi,

I've just tested the release code... Login went smoothly, but when I type "ll" for a Long Directory listing, I get something like this:
JoLuServer.selfhost.me> dir
dir
drwx------    6 root     root          4096 Oct  5 14:01 [1;34m.[0m
drwxr-xr-x   26 root     root          4096 Oct 26 07:31 [1;34m..[0m
-rw-------    1 root     root            16 Jul  2 07:33 [0;0m.esd_auth[0m
drwx------    2 root     root          4096 Sep  8 07:31 [1;34m.gnupg[0m
drwxr-xr-x    3 root     root          4096 Oct  5 14:01 [1;34m.local[0m
-rw-r--r--    1 root     root           364 Mar 12  2015 [0;0m.profile[0m
drwx------    2 root     root          4096 Oct 26 07:32 [1;34m.pulse[0m
-rw-------    1 root     root           256 Jul  2 07:33 [0;0m.pulse-cookie[0m
drwxr-xr-x    2 root     root          4096 May 19  2014 [1;34m.ssh[0m

which looks like some kind of encoding issue...

**Comment by manojampalam** [comment]
We are working on improving terminal support. This should be fixed in the next release (~3 weeks from now).

**Comment by manojampalam** [comment]
Try the latest release.
