### ISSUE TITLE
NanoServer 2016TP5 Issue

### ISSUE THREAD

**Issue by stolaf** [PowerShell/Win32-OpenSSH#272]
I try to install OpenSSH-Win64 on NanoServer TP5 manually. 
Chocolatey not work on Nano for me.

install-sshd.ps1 not work:
 _Program 'ntrights.exe' failed to run: The subsystem needed to support the image type is not present.
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed__

OK: Win32 SubSystem not exist on Nano

i change to: 
Import-Module "$toolsdir\PoshPrivilege"
Add-Privilege 'NT SERVICE\SSHD' SeServiceLogonRight
_Unable to find type [Privileges].
    + CategoryInfo          : InvalidOperation: (Privileges:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound_

NTRights.ps1 also not work on Nano (Win32Exception not exist on Nano) and
# cmd.exe /c "`"$TargetFolder\ntrights.exe`" -u `"NT SERVICE\SSHD`" +r SeAssignPrimaryTokenPrivilege"

Any replacement for this?

What else can I do so that SSH on a Nano works?

**Comment by manojampalam** [comment]
see #234
