### ISSUE TITLE
Fix Dates in Roadmap

### ISSUE THREAD

**Issue by KaliszAd** [PowerShell/Win32-OpenSSH#273]
https://github.com/PowerShell/Win32-OpenSSH/wiki/Win32-OpenSSH-RoadMap#rough-timeline-on-when-the-key-tasks-would-be-accomplished there should be 2016 instead of 2015 probably.

Because there isn't much activity, consider postponing those deadlines again. Or write an announcement about the state of the project

**Comment by manojampalam** [comment]
Thanks. Fixed the dates. We are picking up speed on this project and should have activity back again.
