### ISSUE TITLE
Windows could not start the sshd service on Local Computer

### ISSUE THREAD

**Issue by davecramer** [PowerShell/Win32-OpenSSH#274]
The system cannot find the file specified.

Path to executable is C:\Program Files\OpenSSH\sshd.exe

**Comment by welnanick** [comment]
Is "C:\Program Files\OpenSSH\" in your PATH variable?

**Comment by davecramer** [comment]
No, it's not thanks for the reply

Dave Cramer

**Comment by manojampalam** [comment]
reopen if needed

**Comment by alilland** [comment]
Mine is indeed in PATH, and I still have this error, I have also tried re installing

**Comment by bagajjal** [comment]
@aronlmin - Try our [troubleshooting steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps). 
After psexec as system, run ".\sshd.exe -ddd"
