### ISSUE TITLE
cannot launch powershell shell when sshing from linux to a windows server.

### ISSUE THREAD

**Issue by discodance1** [PowerShell/Win32-OpenSSH#275]
I am trying to ssh from linux to windows server. I am not able to launch powershell. It complains: 

The shell cannot be started. A failure occurred during initialization:
Illegal characters in path.

I have verified that for a user CLIENTNAME, LOCALAPPDATA, TEMP, TMP, USERDNSDOMAIN, LOGONSERVER are not set when ssh'ing but even after manually setting the above env variables via a bat script. powershell invocation is not successful.

**Comment by discodance1** [comment]
This is mostly with openssh 64 bit version. I was able to get into powershell console via openssh 32 bit but have other problems with it as interactive session with power shell hangs via openssh.

**Comment by outofcoffee** [comment]
@discodance1 have you tried with:

```
powershell -File -
```

This works for me.

**Comment by manojampalam** [comment]
reopen if needed
