### ISSUE TITLE
Bug: I'm getting unreadable chars

### ISSUE THREAD

**Issue by Drugoy** [PowerShell/Win32-OpenSSH#276]
I tried connecting from Debian 8.5 x64 (En locale) to Windows 7 SP1 x64 (Ru locale) and I am getting unreadable symbols instead of Cyrillic text.
This is how the prompt looks for me right after the connection:
<img src="https://i.imgur.com/FnqWAAo.png">
I tried `chcp 65001` to change codepage to UTF-8, but the text at left from my server's hostname is still in unreadable chars:
<img src="https://i.imgur.com/VGmFJCC.png">

Also, even when echoed - Cyrillic chars are unreadable:
<img src="https://i.imgur.com/xIqWwNB.png">

**Comment by manojampalam** [comment]
Please validate and reopen if needed

**Comment by Drugoy** [comment]
I don't see the commit that's supposed to fix the issue.

**Comment by Drugoy** [comment]
I've found the commit and I've tried the new version (v.0.0.3.0): you managed to fix something yet broke something else:
The prompt:
<img src="https://i.imgur.com/0ml5KoD.png">
The prompt after entering a wrong passphrase first (shouldn't prompts always be the same? isn't the difference a sign of a bug?):
<img src="https://i.imgur.com/OiKc9EP.png">
After `chcp 65001`:
<img src="https://i.imgur.com/MbT6kLn.png">
`echo "привет"` after `chcp 65001`:
<img src="https://i.imgur.com/7Qtn0pc.png">
`echo "привет"` without `chcp 65001`:
<img src="https://i.imgur.com/A4Sa8kV.png">

I wish I could reopen this issue, but I don't have enough rights.

**Comment by Drugoy** [comment]
@manojampalam @rayhayes hello.

**Comment by manojampalam** [comment]
@bagajjal  is this expected?

**Comment by bagajjal** [comment]
@Drugoy - Please try the latest version.

**Comment by Drugoy** [comment]
@bagajjal - Please share the link to the binary of the latest version.

**Comment by bagajjal** [comment]
Follow this https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by Drugoy** [comment]
Thanks, the issue is fixed!
