### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by derhoeppi** [PowerShell/Win32-OpenSSH#278]
Hi,
i'm getting an error connecting my Win 2012R2 Server -> Access denied. User Folder exist, Services are running and host firewall is open.
I activated the debug log in sshd_config but i get no informational facts to work on the problem. Any other here with that problem.

I execute the ntrights command like #227 but it doesn't solve the Problem.

**Comment by derhoeppi** [comment]
I think it's a username issue. I get a Connection from an unix host like user@domain@host. But the same from an Windows host with putty is not running.

**Comment by SteveL-MSFT** [comment]
Does it work if you use: ssh -l user@domain host?

**Comment by manojampalam** [comment]
reopen if needed
