### ISSUE TITLE
Could not start SFTP

### ISSUE THREAD

**Issue by derhoeppi** [PowerShell/Win32-OpenSSH#279]
If a Client connect to my OpenSSH Server sftp does not start. The Client could be logged in but after a while i get the error: Read timeout.

With WinSCP i get another error: Authentication failed.

SFTP Server is enabled by Default after running install-sshd.ps1. The path uses / instead of . Is it possible to use "" oder '' in path entries?

**Comment by manojampalam** [comment]
Reopen if you still see this issue with latest release.
