### ISSUE TITLE
SFTP Connection

### ISSUE THREAD

**Issue by derhoeppi** [PowerShell/Win32-OpenSSH#280]
On my Windows 10 Workstation i can not connect to sftp Server. With DEBUG3 Level i get the message

> 9092 20:15:28 954 debug3: Home path before CreateProcessAsUser [C:\Users\Dirk]
> 9092 20:15:28 954 debug1: Executing command: C:\Program Files\OpenSSH\sftp-server.exe
> 9092 20:15:28 954 debug1: ERROR. Cannot create process as new user (2).

in sshd.log. WinSCP as Client return the error "Authentication error"

**Comment by manojampalam** [comment]
Reopen if you still see this issue in latest release.
