### ISSUE TITLE
SSH command : No response, I must push "Enter-Key" for keeping ssh-command.

### ISSUE THREAD

**Issue by tono13jp** [PowerShell/Win32-OpenSSH#281]
[Issue Summary]
SSH command : No response, I must push "Enter-Key" for keeping ssh-command.

[Client version]
SSH Client is latest build of Windows SSH.

C:\Program Files\OpenSSH-Win64>VER
Microsoft Windows [Version 6.3.9600]
C:\Program Files\OpenSSH-Win64>ssh -V
OpenSSH_7.1p1 Microsoft_Win32_port_with_VS May 30 2016, OpenSSL 1.0.2d 9 Jul 2015
C:\Program Files\OpenSSH-Win64>

[Server version]
SSH Client is latest build of Windows SSH.

C:\Program Files\OpenSSH-Win64>VER
Microsoft Windows [Version 6.3.9600]
C:\Program Files\OpenSSH-Win64>ssh -V
OpenSSH_7.1p1 Microsoft_Win32_port_with_VS May 30 2016, OpenSSL 1.0.2d 9 Jul 2015
C:\Program Files\OpenSSH-Win64>

[Behavior]
Repro steps is below.

C:\Users\infraadm>echo %time% & ssh miadmin@171.88.44.163 hostname
18:21:06.00

Then I have pushed "Enter-Key".

C:\Users\infraadm>echo %time% & ssh miadmin@171.88.44.163 hostname
18:21:06.00
cbkvk163

[Expected behavior]
C:\Users\infraadm>echo %time% & ssh miadmin@171.88.44.163 hostname
18:21:06.00
cbkvk163

[P.S.]
DEBUG3 set to SSH server and no longer reproduce.

C:\Program Files\OpenSSH-Win64>type sshd_config | findstr /i loglevel
# LogLevel INFO

LogLevel DEBUG3

**Comment by Gondee** [comment]
I am having this issue as well. Interestingly, of my Open SSH Win32 Nodes, 32 bit ones dont have this issue. I have temporarily remedied this by including `[Environment]::Exit(1)` at the end of all powershell commands

**Comment by tono13jp** [comment]
Thank you for your response, but I can't repair this issue yet.
I write more information that is SSH-Client's debug mode -vvv, it seems to have stopped here.

debug1: close - io:000000A55AFF3EE0, type:2, fd:4, table_index:4
debug2: termio_close - pio:000000A55AFF3EE0
debug3: TermRead thread, io:000000A55AFF3EE0

**Comment by manojampalam** [comment]
Please try out the milestone release. Reopen if needed.
