### ISSUE TITLE
Is there a documentation of ssh_config.

### ISSUE THREAD

**Issue by tono13jp** [PowerShell/Win32-OpenSSH#284]
[Issue Summary]
I found “ssh_config” file in Win32-OpenSSH.
But there are no manual of “ssh_config”.

I would like to check the manual of “ssh_config”
You may think Win32-OpenSSH ssh_config can be used just like the manual link below OpenSSH?
http://man.openbsd.org/ssh_config

Or when it is officially released, documentation will be released?

**Comment by derhoeppi** [comment]
I want to follow this topic. I need them to add some cipher suites!

**Comment by SteveL-MSFT** [comment]
Should be the same documentation as ssh_config is just part of OpenSSH (independent of our port)
