### ISSUE TITLE
cannot create agent root reg key, ERROR:5

### ISSUE THREAD

**Issue by kentcb** [PowerShell/Win32-OpenSSH#285]
Surface Book running Windows 10.

A couple of days ago, I began getting this output when starting a new Powershell session:

```
agent_start pid:8336, dbg:1, child:0, pipe:0
cannot create agent root reg key, ERROR:5
Could not open a connection to your authentication agent.
Loading personal and system profiles took 1500ms.
```

I don't know exactly when this started, but it seemed to coincide with an installation of posh-git, which makes no sense to me. At the time, I hadn't installed Win10 anniversary edition yet.

I tried re-installing via:

```
choco install win32-openssh --force
```

The reinstall worked for a while, then started failing with the above again. This time it _was_ after the anniversary edition installation.

I just tried reinstalling again, but this time it seems to have had no positive effect.

Any idea how to rectify this?

**Comment by mikemaccana** [comment]
I manually updated to the May 30 build and am now receiving the same ERROR:5 error, though my agent seems to be working:

```
agent_start pid:2724, dbg:1, child:0, pipe:0
cannot create agent root reg key, ERROR:5
Identity added: C:\Users\mike/.ssh/id_rsa (C:\Users\mike/.ssh/id_rsa)
```

**Comment by manojampalam** [comment]
Looks like something (Posh-GIT) is trying to start its version of ssh-agent process but picked up Win32-OpenSSH's version - these 2 version work in different ways. Try removing Win32-OpenSSH bin path from your %PATH% (reopen if needed)

**Comment by mikemaccana** [comment]
Thanks @manojampalam that fixed it. Specifically, I disabled posh-git since I don't find it provides much value.
