### ISSUE TITLE
Broken pipe and lost connection when trying to use scp

### ISSUE THREAD

**Issue by hbjastad** [PowerShell/Win32-OpenSSH#286]
Looks like the same as #47 
(ssh works, scp doesn't)
(user/domain/host have been anonymized)
## 

$ ssh -p 8022 user@domain@host
user@domain@host's password:
Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.

user@domain@host C:\Users\user>exit
exit
    Connection to host closed.

$ scp -P 8022 test.txt user@domain@host:
user@domain@host's password:
packet_write_wait: Connection to 10.179.32.163: Broken pipe
lost connection

**Comment by manojampalam** [comment]
Dup #295
