### ISSUE TITLE
NT SERVICE\SSHD user needs SeServiceLogonRight

### ISSUE THREAD

**Issue by richard-browne** [PowerShell/Win32-OpenSSH#290]
I just installed OpenSSH following the guide in the wiki. The sshd service didn't start because SeServiceLogonRight is missing. I had to run 'ntrights.exe -u "NT SERVICE\SSHD" +r SeServiceLogonRight'. Should this line be added to install-sshd.ps1?

**Comment by DarwinJS** [comment]
I just pushed version 2016.05.30.20160807 which is still in moderation.

It uses a new approach to the NT rights that should have high compatibility and was tested on Nano as well.

There is also a new switch /UseNTRights - that can be used if you find the new method does not work.

**Comment by manojampalam** [comment]
All virtual service accounts should have this right enabled by default. Try again on a different on a different box and reopen if needed

**Comment by DarwinJS** [comment]
@manojampalam - I agree that is what is _supposed_ to happen, but my experience on Nano was that I had to grant SeServiceLogonRight for Nano.  Nano was the only place I saw it.  I was getting a permission denied until I added that.

**Comment by manojampalam** [comment]
Thanks Darwin. I'll check out behavior on Nano.

**Comment by DarwinJS** [comment]
Would love to know if I am wrong and/or if it is a Nano only issue - I could limit that change to just Nano if that is all that is affected.

**Comment by richard-browne** [comment]
It's not just a Nano issue. I am on Windows 7 (Enterprise). Domain joined. Perhaps it's something to do with our group policy.

**Comment by DarwinJS** [comment]
@manojampalam - were you able to determine if this permission must be explicitly granted for Nano?  I have seen some other issues reported that imply the permission must be explicit for nano => https://github.com/PowerShell/Win32-OpenSSH/issues/378
