### ISSUE TITLE
There is no Digital Signature on release .exe file 

### ISSUE THREAD

**Issue by semi-automatique** [PowerShell/Win32-OpenSSH#291]
I think a Digital Signature on each .exe file of a release would be a good thing. Ideally from Microsoft or at least a Digital Signature from the person who make a release.  For example, each file of SysinternalsSuite have the Microsoft signature.

**Comment by SteveL-MSFT** [comment]
We definitely need it for when we declare a release ready for production.

**Comment by bingbing8** [comment]
Production ready releases will have signed payload
