### ISSUE TITLE
Cipher Suites

### ISSUE THREAD

**Issue by derhoeppi** [PowerShell/Win32-OpenSSH#293]
Which cipher suites are allowed?
I asked because my brocade san switches are not able to connect to the ssh server. The error message is "write failed - broken pipe". Therefore i change the sshd.config file with the params TCPKeepAlive yes, ClientAliveInterval 600 and ClientAliveCountMax 20.

The result is the same - no connection. If i want to define cipher suites in sshd.config - the sshd Service won't start.

**Comment by manojampalam** [comment]
See cipher.c

#ifdef WITH_OPENSSL
    { "none",   SSH_CIPHER_NONE, 8, 0, 0, 0, 0, 0, EVP_enc_null },
    { "3des-cbc",   SSH_CIPHER_SSH2, 8, 24, 0, 0, 0, 1, EVP_des_ede3_cbc },
    { "blowfish-cbc",
            SSH_CIPHER_SSH2, 8, 16, 0, 0, 0, 1, EVP_bf_cbc },
    { "cast128-cbc",
            SSH_CIPHER_SSH2, 8, 16, 0, 0, 0, 1, EVP_cast5_cbc },
    { "arcfour",    SSH_CIPHER_SSH2, 8, 16, 0, 0, 0, 0, EVP_rc4 },
    { "arcfour128", SSH_CIPHER_SSH2, 8, 16, 0, 0, 1536, 0, EVP_rc4 },
    { "arcfour256", SSH_CIPHER_SSH2, 8, 32, 0, 0, 1536, 0, EVP_rc4 },
    { "aes128-cbc", SSH_CIPHER_SSH2, 16, 16, 0, 0, 0, 1, EVP_aes_128_cbc },
    { "aes192-cbc", SSH_CIPHER_SSH2, 16, 24, 0, 0, 0, 1, EVP_aes_192_cbc },
    { "aes256-cbc", SSH_CIPHER_SSH2, 16, 32, 0, 0, 0, 1, EVP_aes_256_cbc },
    { "rijndael-cbc@lysator.liu.se",
            SSH_CIPHER_SSH2, 16, 32, 0, 0, 0, 1, EVP_aes_256_cbc },
    { "aes128-ctr", SSH_CIPHER_SSH2, 16, 16, 0, 0, 0, 0, EVP_aes_128_ctr },
    { "aes192-ctr", SSH_CIPHER_SSH2, 16, 24, 0, 0, 0, 0, EVP_aes_192_ctr },
    { "aes256-ctr", SSH_CIPHER_SSH2, 16, 32, 0, 0, 0, 0, EVP_aes_256_ctr },

# ifdef OPENSSL_HAVE_EVPGCM

```
{ "aes128-gcm@openssh.com",
        SSH_CIPHER_SSH2, 16, 16, 12, 16, 0, 0, EVP_aes_128_gcm },
{ "aes256-gcm@openssh.com",
        SSH_CIPHER_SSH2, 16, 32, 12, 16, 0, 0, EVP_aes_256_gcm },
```

# endif /\* OPENSSL_HAVE_EVPGCM */
