### ISSUE TITLE
scp not working

### ISSUE THREAD

**Issue by kquainta** [PowerShell/Win32-OpenSSH#295]
Similar to #286 regarding #47 
I installed release 5_15_2016
ssh works but not scp
## 

pi@raspberrypi3:~ $ ssh Kevin@192.168.1.100
Kevin@192.168.1.100's password:
Microsoft Windows [Version 10.0.10586](c) 2015 Microsoft Corporation. All rights reserved.

pi@raspberrypi3:~ $ scp myfile Kevin@192.168.1.100:myfile
Kevin@192.168.1.100's password:
Write failed: Broken pipe
lost connection

**Comment by railsmith** [comment]
I am also facing the same issue. Any workaround?

**Comment by SteveL-MSFT** [comment]
This is a known issue and being worked on

**Comment by manojampalam** [comment]
dup #106
