### ISSUE TITLE
Unable to see currently logged on users.

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#296]
As an administrator, I would like to see who's currently logged on to the SSH server, including the IP address and Port details. (In our case, important because of SSH Reverse Tunnels.)

In Linux, one could do something like `ps auxwww | grep sshd:`
Under Windows, all sshd processes seem to be running under the sshd context, rendering it impossible to detect currently logged on users. I've tried get-process, pslist, tasklist etc. to no avail.

**Comment by manojampalam** [comment]
Very valid ask. 
We need to come up with something new and different for Windows. A potential option is to implement a query endpoint on each ssh-agent processes (each sshd has an associated ssh-agent process) .

**Comment by maertendMSFT** [comment]
This issue is fixed in the most recent release.
