### ISSUE TITLE
Unable to configure LDAP Authentication.

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#297]
Since OpenLDAP relies on PAM to do any 'external' authentication, I am unable to configure the SSHd to use LDAP for authentication. The LDAP server could be an OpenLDAP server, or perhaps Active Directory. (In my case, it's OpenLDAP on Windows.)

This LDAP Authentication will most likely be turned into a feature request, but it's an important one.

**Comment by mrPsycho** [comment]
+1.
would be very usefull to get it working. for example to use it with proxy servers to implement MFA.

**Comment by maertendMSFT** [comment]
This is not applicable in Windows, try using Kerberos auth instead.
