### ISSUE TITLE
Configure script error in Cygwin reference environment.

### ISSUE THREAD

**Issue by dajrob** [PowerShell/Win32-OpenSSH#30]
I am able to successfully build dkulwin's November 5th commit (65fb8f4...)

I have not been able to build arif-pragmasys's commit from later that day (71cca6e...), nor can I build any subsequent commit.

I currently get the following error when I run OpenSSH's ./configure script:
./configure: line 6068: syntax error near unexpected token `-Wl,-z,relro'
./configure: line 6068: `       OSSH_CHECK_LDFLAG_LINK(-Wl,-z,relro)'

Additional Info:
I am using the reference versions defined in this wiki's build guide. https://github.com/PowerShell/Win32-OpenSSH/wiki/OpenSSH-32-bit-Build-and-Installation-Instructions

I built my reference installation using the Cygwin time machine, 32-bit, circa 2013-11-12. See the following links for more info.
http://www.fruitbat.org/Cygwin/index.html
ftp://www.fruitbat.org/pub/cygwin/circa/index.html
ftp://www.fruitbat.org/pub/cygwin/circa/2013/11/12/103606/
ftp://www.fruitbat.org/pub/cygwin/circa/2013/11/12/103606/index.html

I have also attached my build script. (Rename from .txt -> .sh before running in Cygwin)
Note: The script assumes the existence of a root build directory named "C:\Builds\PowerShell-Win32-OpenSSH", you will need to modify the script as needed for your environment.

[Build32and64.txt](https://github.com/PowerShell/Win32-OpenSSH/files/31167/Build32and64.txt)

**Comment by givenera** [comment]
The build instruction has been changed lately, since we are trying to keep the same source base compatible both in win32 and Linux. Please run 
./win32_build  
after syncing the latest. That should take care of everything. The 32 bit build instruction document has been updated.
Thanks

**Comment by arif-pragmasys** [comment]
The build instruction has been changed lately, since we are trying to keep the same source base compatible both in win32 and Linux. Please run 
./win32_build

after syncing the latest. That should take care of everything. The 32 bit build instruction document has been updated.
Thanks

**Comment by dajrob** [comment]
I can confirm my builds are working again since incorporating the new ./win32_build command. I will close this issue. Thank you for your response, and for all your hard work on this project.

**Comment by arif-pragmasys** [comment]
Glad to hear its working for you!
