### ISSUE TITLE
Pasting into remote sessions gives question marks around '-' and '|' symbols

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/Win32-OpenSSH#300]
I have some text on the clipboard:

If I paste it into a local app or a local terminal, it is:

```
sudo journalctl -u myapp | grep restart
```

 If I paste it into a remote session using ssh, the text is:

```
sudo journalctl ?-u certsimple  ?grep restart
```

**Comment by manojampalam** [comment]
Please validate and reopen if needed
