### ISSUE TITLE
Chocolatey package:  Could not public key login with local windows user until I edited the registry for ssh-lea

### ISSUE THREAD

**Issue by darenyong** [PowerShell/Win32-OpenSSH#302]
Hi,

Just to help out anyone else who may run into this when installing ssh with the chocolatey package.

I created a local user on a windows box and could only get password login working, until I modified the registry.

Open RegEdit, select this key:
HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Lsa/Authentication Packages

Add the following new line with this text:
ssh-lsa

Then the public key auth worked for the windows local user.  This regedit is not necessary for a domain user.

I found this out by reading this:

https://github.com/PowerShell/Win32-OpenSSH/wiki/OpenSSH-64-bit-Build-and-Installation-Instructions

**Comment by SteveL-MSFT** [comment]
Good tip, I would suggest informing the owner of the Chocolatey package to have them address this: https://chocolatey.org/packages/win32-openssh

**Comment by DarwinJS** [comment]
This should be working now in the latest release (still in moderation).  You can try it with:

`choco install -y win32-openssh -params='/SSHServerFeature'`
