### ISSUE TITLE
tun interface

### ISSUE THREAD

**Issue by jean-marc** [PowerShell/Win32-OpenSSH#304]
Hello,

Is there any plan to support tun interfaces to allow IP tunnels?
I am using the latest win32-OpenSSH:
C:>ssh -V
OpenSSH_7.1p1 Microsoft_Win32_port_with_VS May 30 2016, OpenSSL 1.0.2d 9 Jul 2015

This is the error I get when setting up the tunnel from a Windows client to a Linux server:
C:>ssh -w0:0 root@192.168.3.1
Tunnel interfaces are not supported on this platform
Tunnel device open failed.
Could not request tunnel forwarding.

I have tested the tunnel from Linux client and it works fine.

Many thanks,

jm

**Comment by manojampalam** [comment]
TCP Port forwarding is supported (is that what you are referring to ?). Make sure server side configuration is set to allow it.

**Comment by jean-marc** [comment]
Hello,
I was referring to the setup described here: http://joeykelly.net/rants/vpn_using_ssh.txt

Thanks

**Comment by manojampalam** [comment]
Ah. VPN tunneling is not yet supported on Windows. It requires some interfacing work with VPN drivers on Windows last time I checked. This is listed in "not in scope" features here - https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Scope

**Comment by hugodu21** [comment]
so sad :(
