### ISSUE TITLE
unable to login after execute Ctrl+C

### ISSUE THREAD

**Issue by KotaroKashima** [PowerShell/Win32-OpenSSH#305]
[Summary]
 Once I execute Ctrl+C, I cannot login to server by ssh never.

[Environment]
OS Version: WindowsServer2012R2 
OpenSSH：OpenSSH_7.1p1 Microsoft_Win32_port_with_VS May 30 2016, OpenSSL 1.0.2d 9 Jul 2015

[How to reproduce the issue]
1. login to server by ssh.
   PS C:\Users\Administrator> C:\OpenSSH-Win32\ssh.exe test01@192.168.0.1
   test01@192.168.0.1's password:  [Enter password]
   Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.
   test01@host01 C:\Windows>
2. exeute Ctrl+C. Nothing happened.
   test01@host01 C:\Windows>
3. logout by command 'exit'
   test01@host01 C:\Windows>exit
   exit
   Connection to 192.168.0.1 closed.
   PS C:\Users\Administrator> 
4. login to server agent, but cannot login.
   PS C:\Users\Administrator> C:\OpenSSH-Win32\ssh.exe test01@192.168.0.1

The input of the password is not displayed, and it's not responding.

[Recovery]
Restart sshd service.

**Comment by KotaroKashima** [comment]
I tried to  investigate about this issue with Process Explorer.
https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx

This result is as follows.

a) The thread about sechost.dll is killed when I execute Ctrl+C.
b) I cannot login when the thread is killed.
c) I cannot login when I suspend the thread manually. 
![sshd](https://cloud.githubusercontent.com/assets/22027557/18357229/185a938e-762b-11e6-8e7d-85f2dc2bcf34.jpg)

**Comment by manojampalam** [comment]
Please try out the milestone release. Reopen if needed.
