### ISSUE TITLE
TIP: Do not attempt to use Local System as the SSHD log on user. Otherwise cannot create process as new user (sshd.log) or broken pipe (client side) errors will occur.

### ISSUE THREAD

**Issue by darenyong** [PowerShell/Win32-OpenSSH#306]
The 'Local System' account does not have the SeAssignPrimaryTokenPrivilege right.

This will cause SSHD to fail when it tries to Create a Process as User.

Instead, make sure you have local user account created to run the sshd service and assign all the correct privileges.

**Comment by manojampalam** [comment]
You can configure privilege that need to be assigned to a particular service process. 
Take a look at this service for ex: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinRM
Registry value: RequiredPrivileges
