### ISSUE TITLE
Support PKCS providers in Windows

### ISSUE THREAD

**Issue by sdalessandro** [PowerShell/Win32-OpenSSH#307]
Getting the following error trying to use OpenSC to generate a key for my YK4...

PS C:\Users\Sandro\Documents\Yubi_Stuff> ssh-keygen.exe -D opensc-pksc11.dll -e
no pkcs11 support

I have a fresh install of both OpenSSH-Win32 and OpenSC-0.15.0-win32. Not sure where the issue is that's throwing this error. Any help is much appreciated!

**Comment by manojampalam** [comment]
Yes. PKCS providers are not in scope yet. https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Scope

**Comment by omniproc** [comment]
I'd like to see PKCS11 as well. As we're moving away from traditional passwords this would be a great deal.

**Comment by RichardScothern** [comment]
Just adding an interest in this feature too.

@manojampalam do you have a hard requirement for this repo being merged into the official openSSH before accepting pull requests for out of scope features?  Thanks!

**Comment by manojampalam** [comment]
@RichardScothern, not at all. We can take any changes that are well tested and don't contribute to any major deviations in core source code layout .

**Comment by lars18th** [comment]
Hi,

You ca use this solution:

- Install the PuTTY-Pageant-CAC from @NoMoreFood : https://github.com/NoMoreFood/putty-cac/releases
- Use the WSL-SSH-Pageant tool to link the Pageant-CAC to the OpenSSH Client AUTH : https://github.com/benpye/wsl-ssh-pageant/releases (download the GUI version).
- Set your environment with `SETX SSH_AUTH_SOCK \\.\pipe\ssh-pageant`.
- Then start the PuTTY-Pageant-CAC and launch the WSL-SSH-Pageant with `wsl-ssh-pageant-amd64-gui.exe --systray --winssh ssh-pageant`.

After that all of yours certificates in PKCS11 loaded in Pageant will be available for your Win32-OpenSSH SSH Client.
And this works too for PuTTY keys and CAPI certificates.

Regards.

**Comment by omniproc** [comment]
@lars18th I'm currently using the CAC port of PuTTY and yes, your suggested method to use it's pageant component would allow PKCS11 use. However: this seems like a workaround. Native PKCS11 support in Windows and W31-OpenSSH would be a great thing.

**Comment by lars18th** [comment]
> @lars18th I'm currently using the CAC port of PuTTY and yes, your suggested method to use it's pageant component would allow PKCS11 use. However: this seems like a workaround. Native PKCS11 support in Windows and W31-OpenSSH would be a great thing.

Hi @m451 ,

I feel _native_ support will never be. Why? Because Win32-OpenSSH has his own Agent Manager. And the Microsoft people prefers to use it. Then, if you like to use the PuTTY's Agent Pageant (de facto standard in Windows), then you only require to use a PROXY. And this piece it's the **WSL-SSH-Pageant**. This new tool is quite simple and works well. You don't need more... except that the original Pageant lacks PKCS11 support (and others). But @NoMoreFood did a good job adding support to the Pageant.

So from my point of view, this it's the best solution. Besides, I'm a PuTTY Pageant fan. :smile: 
Regards.

**Comment by miketheitguy** [comment]
Just throwing my hat in the ring for support for this :)

**Comment by keliansb** [comment]
> Hi,
> 
> You ca use this solution:
> 
> * Install the PuTTY-Pageant-CAC from @NoMoreFood : https://github.com/NoMoreFood/putty-cac/releases
> * Use the WSL-SSH-Pageant tool to link the Pageant-CAC to the OpenSSH Client AUTH : https://github.com/benpye/wsl-ssh-pageant/releases (download the GUI version).
> * Set your environment with `SETX SSH_AUTH_SOCK \\.\pipe\ssh-pageant`.
> * Then start the PuTTY-Pageant-CAC and launch the WSL-SSH-Pageant with `wsl-ssh-pageant-amd64-gui.exe --systray --winssh ssh-pageant`.
> 
> After that all of yours certificates in PKCS11 loaded in Pageant will be available for your Win32-OpenSSH SSH Client.
> And this works too for PuTTY keys and CAPI certificates.
> 
> Regards.

Thank you for your solution, it works like a charm! Do you know if the same thing is possible to do but with PuTTY instead of the Win32-OpenSSH client? I'm currently using mRemoteNG which doesn't support it currently...

**Comment by lars18th** [comment]
> Thank you for your solution, it works like a charm! Do you know if the same thing is possible to do but with PuTTY instead of the Win32-OpenSSH client? I'm currently using mRemoteNG which doesn't support it currently...

Sure! If you use the original PuTTY (or any other fork... I like the KiTTY), then you only need to run the PuTTY-Pageant-CAC and select in your session configuration "Connection-->SSH-->Auth-->Authenticate methods" and check the option **Attempt authentication using Pageant**.

Regards.

**Comment by manojampalam** [comment]
Relevant changes 
-  https://github.com/PowerShell/openssh-portable/commit/44ba5483cdd10a4d9c00979d05100986188fdd19
- https://github.com/PowerShell/openssh-portable/commit/3449eb21529664e48ae366539692dd64a742da34

**Comment by omniproc** [comment]
@manojampalam any usage instructions?

**Comment by NoMoreFood** [comment]
@m451 There's nothing unique about the Windows implementation other than you point to a .dll file instead of a .so file.  The `-I` flag can be used to specify the library.
