### ISSUE TITLE
PublicKey Authentication issue

### ISSUE THREAD

**Issue by 0byt3** [PowerShell/Win32-OpenSSH#308]
I have an issue with the public key authentication. I created the authorized_keys file in linux `cat /root/.ssh/id_dsa.pub > /mnt/share/Users/Administrator.DOMAIN/.ssh/authorized_keys` to make sure it's ASCII..

sshd log says ssh-agent didn't validate the key, but nothing in ssh-agent log says anything that I understand that would be the issue. Any help would be much appreciated.

Here's the log file for sshd:
`1452 22:08:43 353 debug1: socket:300, io:000000498C3AAC20, fd:3 
1452 22:08:43 353 debug1: Bind to port 22 on ::.
1452 22:08:43 353 Server listening on :: port 22.
1452 22:08:43 353 debug1: socket:348, io:000000498C3A9680, fd:4 
1452 22:08:43 353 debug1: Bind to port 22 on 0.0.0.0.
1452 22:08:43 353 Server listening on 0.0.0.0 port 22.
1452 22:08:47 213 debug1: socket:360, io:000000498C38F810, fd:5 
1452 22:08:47 213 debug1: pipe - read end: handle:000000000000016C, io:000000498C38F8C0, fd:6
1452 22:08:47 213 debug1: pipe - write end: handle:0000000000000170, io:000000498C38F970, fd:7
1452 22:08:47 213 debug1: close - io:000000498C38F810, type:1, fd:5, table_index:5
1452 22:08:47 213 debug1: w32_close ERROR: bad fd: -1
1452 22:08:47 213 debug1: Register child 0000000000000178 pid 1828, 0 zombies of 0
1452 22:08:47 213 debug1: Forked child 1828.
1452 22:08:47 213 debug1: close - io:000000498C38F970, type:2, fd:7, table_index:7
1452 22:08:47 213 debug1: w32_close ERROR: bad fd: 5
1828 22:08:47 259 Connection from 192.168.1.11 port 41266 on 192.168.1.15 port 22
1828 22:08:47 259 debug1: Client protocol version 2.0; client software version OpenSSH_5.9p1 Debian-5ubuntu1
1828 22:08:47 259 debug1: match: OpenSSH_5.9p1 Debian-5ubuntu1 pat OpenSSH_5* compat 0x0c000000
1828 22:08:47 259 debug1: Enabling compatibility mode for protocol 2.0
1828 22:08:47 259 debug1: Local version string SSH-2.0-OpenSSH_7.1p1 Microsoft_Win32_port_with_VS
1828 22:08:47 259 debug1: list_hostkey_types: ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
1828 22:08:47 259 debug1: SSH2_MSG_KEXINIT sent
1828 22:08:47 259 debug1: SSH2_MSG_KEXINIT received
1828 22:08:47 259 debug1: kex: algorithm: ecdh-sha2-nistp256
1828 22:08:47 259 debug1: kex: host key algorithm: ecdsa-sha2-nistp256
1828 22:08:47 259 debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1 compression: none
1828 22:08:47 259 debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1 compression: none
1828 22:08:47 259 debug1: expecting SSH2_MSG_KEX_ECDH_INIT
1828 22:08:47 322 debug1: SSH2_MSG_NEWKEYS sent
1828 22:08:47 322 debug1: expecting SSH2_MSG_NEWKEYS
1828 22:08:47 322 debug1: SSH2_MSG_NEWKEYS received
1828 22:08:47 322 debug1: KEX done
1828 22:08:47 384 debug1: userauth-request for user administrator@CCS service ssh-connection method none
1828 22:08:47 384 debug1: attempt 0 failures 0
1828 22:08:47 384 Failed none for administrator@CCS from 192.168.1.11 port 41266 ssh2
1828 22:08:47 384 debug1: userauth-request for user administrator@CCS service ssh-connection method publickey
1828 22:08:47 384 debug1: attempt 1 failures 0
1828 22:08:47 384 debug1: test whether pkalg/pkblob are acceptable
1828 22:08:47 384 Postponed publickey for administrator@CCS from 192.168.1.11 port 41266 ssh2
1828 22:08:47 384 debug1: userauth-request for user administrator@CCS service ssh-connection method publickey
1828 22:08:47 384 debug1: attempt 2 failures 0
1828 22:08:47 400 debug1: auth agent did not authorize client administrator@CCS
1828 22:08:47 400 debug1: close - io:0000002086930860, type:2, fd:5, table_index:5
1828 22:08:47 400 Failed publickey for administrator@CCS from 192.168.1.11 port 41266 ssh2: DSA SHA256:wrtmIpkU2Y2Yud1jza8np3aaGxA9Zlc2szgm7Z5YMOk
1828 22:08:47 400 debug1: userauth-request for user administrator@CCS service ssh-connection method keyboard-interactive
1828 22:08:47 400 debug1: attempt 3 failures 1
1828 22:08:47 400 debug1: keyboard-interactive devs 
1828 22:08:47 400 debug1: auth2_challenge: user=administrator@CCS devs=
1828 22:08:47 400 debug1: kbdint_alloc: devices ''
1828 22:08:47 400 Failed keyboard-interactive for administrator@CCS from 192.168.1.11 port 41266 ssh2
1828 22:08:49 931 debug1: userauth-request for user administrator@CCS service ssh-connection method password
1828 22:08:49 931 debug1: attempt 4 failures 2
1828 22:08:49 962 Accepted password for administrator from 192.168.1.11 port 41266 ssh2
1828 22:08:49 962 debug1: Entering interactive session for SSH2.
1828 22:08:49 962 debug1: pipe - read end: handle:0000000000000148, io:0000002086986190, fd:5
1828 22:08:49 962 debug1: pipe - write end: handle:000000000000014C, io:0000002086930860, fd:6
1828 22:08:49 962 debug1: server_init_dispatch_20
1828 22:08:49 962 debug1: server_input_channel_open: ctype session rchan 0 win 1048576 max 16384
1828 22:08:49 962 debug1: input_session_request
1828 22:08:49 962 debug1: channel 0: new [server-session]
1828 22:08:49 962 debug1: session_new: session 0
1828 22:08:49 962 debug1: session_open: channel 0
1828 22:08:49 962 debug1: session_open: session 0: link with channel 0
1828 22:08:49 962 debug1: server_input_channel_open: confirm session
1828 22:08:49 962 debug1: server_input_global_request: rtype no-more-sessions@openssh.com want_reply 0
1828 22:08:50 212 debug1: server_input_channel_req: channel 0 request pty-req reply 1
1828 22:08:50 212 debug1: session_by_channel: session 0 channel 0
1828 22:08:50 212 debug1: session_input_channel_req: session 0 req pty-req
1828 22:08:50 212 debug1: Allocating pty.
1828 22:08:50 212 debug1: session_pty_req: session 0 alloc console
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 1 (0x1)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 2 (0x2)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 3 (0x3)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 4 (0x4)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 5 (0x5)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 6 (0x6)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 7 (0x7)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 8 (0x8)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 9 (0x9)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 10 (0xa)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 12 (0xc)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 13 (0xd)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 14 (0xe)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 18 (0x12)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 30 (0x1e)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 31 (0x1f)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 32 (0x20)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 33 (0x21)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 34 (0x22)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 35 (0x23)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 36 (0x24)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 37 (0x25)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 38 (0x26)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 39 (0x27)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 40 (0x28)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 41 (0x29)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 50 (0x32)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 51 (0x33)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 52 (0x34)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 53 (0x35)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 54 (0x36)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 55 (0x37)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 56 (0x38)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 57 (0x39)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 58 (0x3a)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 59 (0x3b)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 60 (0x3c)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 61 (0x3d)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 62 (0x3e)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 70 (0x46)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 71 (0x47)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 72 (0x48)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 73 (0x49)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 74 (0x4a)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 75 (0x4b)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 90 (0x5a)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 91 (0x5b)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 92 (0x5c)
1828 22:08:50 212 debug1: Ignoring unsupported tty mode opcode 93 (0x5d)
1828 22:08:50 212 debug1: server_input_channel_req: channel 0 request env reply 0
1828 22:08:50 212 debug1: session_by_channel: session 0 channel 0
1828 22:08:50 212 debug1: session_input_channel_req: session 0 req env
1828 22:08:50 212 debug1: server_input_channel_req: channel 0 request shell reply 1
1828 22:08:50 212 debug1: session_by_channel: session 0 channel 0
1828 22:08:50 212 debug1: session_input_channel_req: session 0 req shell
1828 22:08:50 212 Starting session: shell on console for administrator@CCS from 192.168.1.11 port 41266
1828 22:08:50 212 debug1: pipe - read end: handle:0000000000000150, io:000000208698ADC0, fd:7
1828 22:08:50 212 debug1: pipe - write end: handle:0000000000000154, io:000000208698AE70, fd:8
1828 22:08:50 212 debug1: pipe - read end: handle:0000000000000158, io:00000020869863B0, fd:9
1828 22:08:50 212 debug1: pipe - write end: handle:000000000000015C, io:0000002086986460, fd:10
1828 22:08:50 212 debug1: pipe - read end: handle:0000000000000160, io:0000002086986510, fd:11
1828 22:08:50 212 debug1: pipe - write end: handle:0000000000000174, io:000000208698F0C0, fd:12
1828 22:08:50 212 debug1: <- GetHomeDirFromToken()...
1828 22:08:50 212 debug1: Executing command: ssh-shellhost.exe
1828 22:08:50 212 debug1: Register child 0000000000000180 pid 1424, 0 zombies of 0
1828 22:08:50 212 debug1: close - io:000000208698ADC0, type:2, fd:7, table_index:7
1828 22:08:50 212 debug1: close - io:0000002086986460, type:2, fd:10, table_index:10
1828 22:08:50 212 debug1: close - io:000000208698F0C0, type:2, fd:12, table_index:12
1828 22:08:52 447 debug1: close - io:00000020869863B0, type:2, fd:9, table_index:9
1828 22:08:52 447 debug1: close - io:0000002086986510, type:2, fd:11, table_index:11
1828 22:08:52 447 debug1: zombie'ing child at index 0, 0 zombies of 1
1828 22:08:52 447 debug1: raise sig:3
1828 22:08:52 447 debug1: process_queued_signals: WARNING - A signal has interrupted and was processed
1828 22:08:52 447 debug1: Received SIGCHLD.
1828 22:08:52 447 debug1: Unregister child at index 0, 1 zombies of 1
1828 22:08:52 447 debug1: session_by_pid: pid 1424
1828 22:08:52 447 debug1: session_exit_message: session 0 channel 0 pid 1424
1828 22:08:52 447 debug1: session_exit_message: release channel 0
1828 22:08:52 447 debug1: close - io:000000208698AE70, type:2, fd:8, table_index:8
1828 22:08:52 447 debug1: Sending exit signal to child process [pid = 1424]...
1828 22:08:52 447 debug1: session_pty_cleanup: session 0 release console
1828 22:08:52 447 debug1: session_by_channel: session 0 channel 0
1828 22:08:52 447 debug1: session_close_by_channel: channel 0 child 0
1828 22:08:52 447 debug1: session_close: session 0 pid 0
1828 22:08:52 447 debug1: channel 0: free: server-session, nchannels 1
1828 22:08:52 447 Received disconnect from 192.168.1.11: 11: disconnected by user
1828 22:08:52 447 Disconnected from 192.168.1.11
1828 22:08:52 447 debug1: do_cleanup
1452 22:08:52 447 debug1: close - io:000000498C38F8C0, type:2, fd:6, table_index:6
1452 22:08:52 447 debug1: zombie'ing child at index 0, 0 zombies of 1
1452 22:08:52 447 debug1: raise sig:3
1452 22:08:52 447 debug1: Unregister child at index 0, 1 zombies of 1
1452 22:08:52 447 debug1: process_queued_signals: WARNING - A signal has interrupted and was processed
`

ssh-agent log file:
`1632 22:08:40 322 agent_start pid:1632, dbg:0, child:0, pipe:0
1632 22:08:47 259 client pid 1828 connected on \.\pipe\ssh-keyagent
1632 22:08:47 259 debug1: spawned child 1208 to process 3
1208 22:08:47 259 agent_start pid:1208, dbg:0, child:1, pipe:364
1208 22:08:47 259 debug1: connection io 000000A6BFDBD850 #bytes:0 state:0
1632 22:08:47 384 client pid 1828 connected on \.\pipe\ssh-authagent
1632 22:08:47 384 debug1: spawned child 1472 to process 3
1472 22:08:47 384 agent_start pid:1472, dbg:0, child:1, pipe:372
1472 22:08:47 384 debug1: connection io 000000D993B8D850 #bytes:0 state:0
1472 22:08:47 384 debug1: connection io 000000D993B8D850 #bytes:4 state:1
1472 22:08:47 384 debug1: connection io 000000D993B8D850 #bytes:1078 state:2
1472 22:08:47 384 debug1: client type: 3
1472 22:08:47 400 debug1: unable to generate user token
1472 22:08:47 400 debug1: connection 000000D993B8D850 clean up
1472 22:08:47 400 debug1: iocp error: 6 on 0000000000000000 

1208 22:08:52 447 debug1: iocp error: 109 on 000000A6BFDBD850 

1208 22:08:52 447 debug1: connection 000000A6BFDBD850 clean up
1208 22:08:52 447 debug1: iocp error: 6 on 0000000000000000 
`

**Comment by manojampalam** [comment]
Reworded subject to highlight the issue. 

I'm assuming you are using Windows local accounts (as opposed to domain accounts). Try the following:
- ensure that ssh-lsa.dll is installed (not needed for domain accounts). 
- try creating a pub key file in Windows and compare it with the one copied from Unix. See if CR, LFs make a difference.

**Comment by 0byt3** [comment]
I am using domain accounts. I'm sure I have LSA installed. I can think of one thing that might be an issue. I started using an updated version, but I couldn't update the ssh-lsa.dll, but it tells me it's opened by a process, so I hoped it wouldn't be an issue, because otherwise I have to find out what that process is... I did stop and uninstall the previous ssh install, except the LSA which failed with that error.

**Comment by 0byt3** [comment]
Is there something I'm missing as far as the configuration goes? Or is this an actual bug?

**Comment by 0byt3** [comment]
I created the authorized_keys using a redirect to a text file to make sure it's ASCII then coped that file over to the C:\Users\Administrator\.ssh directory.

**Comment by 0byt3** [comment]
I tried two things: I used powershell to create a text file of authorized_keys using ' "<output from id_dsa.pub>" | Out-File -Encoding ascii -FilePath C:\Users\Aadministrator.ssh\authorized_keys '.
The other was create the file on the linux server the copy it to the directory on the windows server: 'cat /root/.ssh/id_dsa.pub > authorized_keys '.

**Comment by 0byt3** [comment]
I tried using the local administrator account and it worked. The domain administrator account doesn't work. I am hoping that might mean something to someone.

**Comment by 0byt3** [comment]
I think this is an issue with my server rather than with OpenSSH. I set up the service on a new server and it worked fine. I was also able to run psexec -i -s cmd.exe with a domain admin account, whereas I can't on my current server. I can only run that command as a local admin, but on the new server I set up I was able to run it. The new server was a full server 2012 R2 install joined to Microsoft AD. The not working server is Server 2012R2 Core joined to Samba4 AD.

The psexec error I get is the following:
Error deriving session key:
The requested operation cannot be completed. The computer must be trusted for delegation and the current user account must be configured to allow delegation.

**Comment by mohag** [comment]
With the Chocolatey package, it seems like it is at least necessary to run "C:\Program Files\OpenSSH-Win64\install-sshlsa.ps1" (It copies the DLL and adds some registry entries) and reboot the server before public key auth works, (I could not get it to work without a reboot)

**Comment by carcus88** [comment]
On server 2012 I can confirm public key auth works when using the chocolatey package when running that command. @mohag

**Comment by 0byt3** [comment]
I installed it on a DC and it seems to work on there.

**Comment by DarwinJS** [comment]
@mohag - the server must be rebooted for public key auth (for the new DLL to be loaded as an authentication library) and the chocolatey package notes this in a warning at the end of the package. 

It seems many are missing the Chocolatey package warning and then concluding they still need to run install-sshlsa.ps1 - but it seems to me that's when they finally try rebooting.

**Comment by 0byt3** [comment]
Since I have it working on the DC and don't need it on the other server I'm closing the issue.
