### ISSUE TITLE
After vim use, screen becomes black instead of blue

### ISSUE THREAD

**Issue by HLFH** [PowerShell/Win32-OpenSSH#31]
Hi,

After vim use, screen becomes black instead of blue. And I'm hearing a strange noise when I use `:` when I'm beginning to type `:q!`.

![blackinsteadofblue](https://cloud.githubusercontent.com/assets/2359059/11090133/b71b1f34-886f-11e5-878d-258e0a30ea31.PNG)

Thanks in advance,
HLFH

**Comment by quamrulmina** [comment]
Fixed. ssh client will now restore previous color when a session has ended. Tested with vim to now work.

**Comment by HLFH** [comment]
@quamrulmina Thanks!
