### ISSUE TITLE
SSH_FXP_OPEN with SSH_FXF_APPEND flag is rejected as "bad message"

### ISSUE THREAD

**Issue by drieseng** [PowerShell/Win32-OpenSSH#310]
As project lead for **SSH.NET**, I found that (MS) **OpenSSH** does not support the **SSH_FXF_APPEND** flag.
I learned this while looking into [this](https://github.com/sshnet/SSH.NET/issues/83) issue.

When attempting to open a file with that flag, the SFTP subsystem responds with a **SSH_FXP_STATUS** message with status code **SSH_FX_BAD_MESSAGE**.

I'm using version 5_30_2016 (Win64).

Let me know if you need more info.

**Comment by manojampalam** [comment]
Please try release from https://github.com/PowerShell/Win32-OpenSSH/milestone/4 and reopen if you still see this.
