### ISSUE TITLE
SFTP subsystem does not log 

### ISSUE THREAD

**Issue by drieseng** [PowerShell/Win32-OpenSSH#311]
While looking into issue #310, I was hoping to find logging of the **SFTP** subsystem.
However, the **sftp-server.log** remained at zero size.
How can I configure/enable logging for the SFTP subsystem.

More specifically, I tried configuring the **SFTP** subsystem with **DEBUG3** level in **sshd_config**:

``` txt
Subsystem   sftp    D:/development/MS-OpenSSH-Win64/sftp-server.exe  -f AUTH -l DEBUG3
```

**Comment by manojampalam** [comment]
Looks like looging code is disabled for Windows. sftp-server.c line 2018. Can you try enabling it and see if it works?

**Comment by drieseng** [comment]
I haven't yet built from source. I'll try to find time for this.

**Comment by manojampalam** [comment]
If you login as admin, you should see sftp-server.log under logs folder
