### ISSUE TITLE
File name mapping suggestion

### ISSUE THREAD

**Issue by lfourquaux** [PowerShell/Win32-OpenSSH#312]
This is a suggestion regarding mapping file names between Unix/utf-8 and Windows/utf-16 .

Unix file names are byte strings, with / as separator, no other special character, and are usually (nowadays) utf-8 encoded Unicode strings.

Windows file names are strings of 16 bits values, use \ or / as separator, have a few other prohibited or special characters (?*:"|<>), and are almost always utf-16 encoded Unicode strings.

A sensible mapping should preserve Unicode strings (i.e. map utf-8 to utf-16 and back) and handle as gracefully as possible other values (non-Unicode) and special characters.

Proposed Windows to Unix mapping:
- 16 bits values that are not Unicode surrogates, \, or private use characters, are mapped to the same Unicode character in utf-8 representation
- \ is mapped to /
- a well formed pair of Unicode surrogates is mapped to the corresponding Unicode character in utf-8 representation
- Unicode surrogate characters that are not part of a well formed surrogate pair is mapped to the utf-8 representation of this isolated surrogate character (warning: this is invalid utf-8, corresponding to invalid utf-16 in the input)
- Unicode characters in the private use area corresponding to (\?_:"|<>) shifted by 0xf000 (see the reverse mapping below) are mapped to (\?_:"|<>), other characters in the private use area are mapped to their utf-8 representation.

Proposed Unix to Windows mapping:
- / is mapped to \ (widened to 16 bits)
- special characters (\?*:"|<>) are mapped to the Unicode private use area by adding 0xf000 to their byte value (yielding a 16-bit value)
- valid utf-8 byte sequences are mapped to the corresponding utf-16 representation
- utf-8 byte sequences corresponding to the Unicode surrogate range are mapped to isolated utf-16 surrogates
- bytes that are not part of a valid utf-8 byte sequence are simply widened to 16 bits.

Combined together, these mappings have the following properties:
- Windows -> Unix -> Windows preserve all paths faithfully, except for converting / to \
- Unix -> Windows -> Unix preserve valid utf-8 paths except for a few Unicode characters in the private use area
- the mapping never fails
- raw byte sequences on the Unix side are mostly interpreted as iso-8859-1 (but not mapped back to the same bytes).

Credits: the idea of using the private use area to represent special characters is taken from Cygwin; it is also used by other Posix-to-Windows emulation layers. The file name mapping algorithm used by Cygwin has a few more refinements (using the private use area for leading and trailing spaces and dots) that might be worth considering for Win32-OpenSSH.

This proposal does not address the issue of mapping the root (drive letters C: or UNC \machine\share) since there is a wide range of practices from one emulation layer to the other.

**Comment by manojampalam** [comment]
Thanks for thinking this through. This helps with Unicode work in pipeline.

**Comment by manojampalam** [comment]
Here's how the Unicode is supported in Windows version of OpenSSH in scp and sftp
- All input from console is read as UTF-16, converted to UTF-8, "\" converted to "/" and fed through OpenSSH core code
- OpenSSH core code is still intact and operates on Unix style file paths
- Output on console is still in Unix style. Since this involves some refactoring of core code, we'll work on this later.

Otherwise, there is nothing in specific done to handle special charactors. Let us know if you have any concerns
