### ISSUE TITLE
Wiki reference to PsExec leads to a 404 page

### ISSUE THREAD

**Issue by mihaipopescu** [PowerShell/Win32-OpenSSH#313]
In Section 6 of the installation manual https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH:

>   download psexec from [here](https://technet.microsoft.com/en-us/sysinternals/psexec.aspx)

Apparently the link has been changed to https://technet.microsoft.com/en-us/sysinternals/pxexec.aspx instead.

**Comment by manojampalam** [comment]
Thanks. Fixed.
