### ISSUE TITLE
ssh from Nano does not work

### ISSUE THREAD

**Issue by rob-scheepens** [PowerShell/Win32-OpenSSH#317]
When trying to ssh from a Nano Server machine to a Linux machine, I'm getting:

```
[10.60.5.178]: PS C:\Program Files\OpenSSH-Win64> .\ssh.exe nutanix@10.60.4.51
.\ssh.exe : Pseudo-terminal will not be allocated because stdin is not a terminal.
```

Trying -t and -T does not help:

```
[10.60.5.178]: PS C:\Program Files\OpenSSH-Win64> .\ssh.exe -t nutanix@10.60.4.51
.\ssh.exe : Pseudo-terminal will not be allocated because stdin is not a terminal.

```

-T just does nothing, eventually I stopped it using Ctrl+C:

```
[10.60.5.178]: PS C:\Program Files\OpenSSH-Win64> .\ssh.exe -T nutanix@10.60.4.51
The remote pipeline has been stopped.
```

Note: I'm getting similar behavior when from CentOS I SSH into a Windows Server 2016 and then from there connect to another machine:

```
host:10.60.4.51:~$ ssh administrator@10.60.5.177
FIPS mode initialized
administrator@10.60.5.177's password:
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

administrator@RSHV3060G4-3 C:\Users\Administrator>ssh administrator@10.60.5.178
ssh administrator@10.60.5.178
                             Pseudo-terminal will not be allocated because stdin is not a terminal.
Host key verification failed.
```

**Comment by DarwinJS** [comment]
Did you manually install?

**Comment by rob-scheepens** [comment]
I installed using instructions from https://github.com/PowerShell/Win32-OpenSSH/issues/234#issuecomment-246081634.

**Comment by manojampalam** [comment]
I see what's going on. The remote session process within Nano is not associated with a Console. Remote Powershell Protocol has its own TTY protocol that is not connected to ssh.exe.

This is a Windows specific issue that needs some thinking. We may need to come up with a custom host for Powershell that will behave like a pseudo terminal for ssh.exe.

**Comment by ghost** [comment]
When I attempt to spawn an instance of ssh.exe under my application in order to execute commands on a server, I receive the error described here. On a linux machine, I would have had the option to use the `-T` option, but it is not available on this version of OpenSSH for some reason.

**Comment by manojampalam** [comment]
-T option now works with ssh.exe. Please test out your scenarios with the latest release and reopen if the issue still persists.
