### ISSUE TITLE
After sudo use, bad character

### ISSUE THREAD

**Issue by HLFH** [PowerShell/Win32-OpenSSH#32]
Hi,

After I'm using `sudo -s` or `sudo -i`, I get a bad character  `hlfh┬á`.

![badcharacteraftersudouse](https://cloud.githubusercontent.com/assets/2359059/11090209/4f98d954-8870-11e5-97ad-0963e5c223c2.PNG)

Thanks in advance,
HLFH

**Comment by HLFH** [comment]
![powerssh](https://cloud.githubusercontent.com/assets/2359059/12007030/befe78ae-abf1-11e5-852e-f79ea6360f97.PNG)

@quamrulmina @manojampalam Could you support UTF-8? I believe it's related to UTF-8 support.

**Comment by quamrulmina** [comment]
commands like "sudo -s" and "sudo -I" now works using our ssh client . Tested with our latest ssh client from powershell as shown in the issue.

**Comment by HLFH** [comment]
No real UTF-8 support apparently and it does not seem that you support the last ciphers. I can't try the last version because I improved too much the SSH security and it only works with openssh client provided by Cygwin...and directly by GNU/Linux.
