### ISSUE TITLE
If possible do not use the fourth part of the version number

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#331]
This is a low priority request.
NuGet uses Semantic versioning with four positions.
Chocolatey NuGet uses a "convention" of using the fourth version position to "fixup/patch" packaging while still being able to maintain direct correlation with the software version number for what is being packaged.

For instance, if the software version 0.0.3.0 had to have it's chocolatey packaging fixed up twice, the three chocolatey versions would look something like this:

0.0.3.0 #same version number as a new release of app
0.0.3.20160821 #fix to packages on 2016-08-21, underlying app is still 0.0.3
0.0.3.20160909 #fix to packages on 2016-09-09, underlying app is still 0.0.3

If the fourth position is used by the software, then the above scheme still has to be used in order to publish new, immutable versions on chocolatey.org, but the correlation to the underlying software is then less clear.

I know there are a lot of priorities beyond packaging that go into a versioning scheme, but thought I would ask in case it's not a hard adjustment to make.

**Comment by manojampalam** [comment]
Sure. We can follow the same convention. I'll have the next package versioned 0.0.1.X.

**Comment by DarwinJS** [comment]
Awesome!

If we're on the same page you will always leave the fourth position to be a zero right?

**Comment by manojampalam** [comment]
Yes. 0 for all planned releases and date for any quick fix releases.

**Comment by DarwinJS** [comment]
I am trying to indicate that the fourth position would need to be reserved _exclusively_ for packaging only fixups if it was to be useful to me in the way I am requesting.

So I need to be able to re-release packing multiple times with the exact same version of the binaries for fixups.  If that part of the version number is used by the binaries for any reason, then I end up obfuscating the real underllying version whenever I have to override it just for the package.

I understand this might not be something you are not willing to entertain doing - just trying to explain that for packaging fixups to not create confusion about the actual binaries version contained in the package - it needs that last version segment on the binaries to always be "0" (unused by the binaries basically).

**Comment by DarwinJS** [comment]
Just an FYI that another method I can use for chocolatey "package fixes" is to append two numbers to the last version position.

I've actually had to do this with the current release so you will see that for 0.0.0.9 of the binaries, the chocolatey package version is 0.0.0.901.

Obviously there is a possibility of slight confusion that the binaries have a version of 0.0.0.901 - but at least there is a way forward if you do not wish to leave the fourth version position untouched for packaging.

**Comment by manojampalam** [comment]
Sorry for the delay. I can stick with your proposal. I'll leave out the last position for packaging.
