### ISSUE TITLE
Installation under Windows 10

### ISSUE THREAD

**Issue by marco-vaz** [PowerShell/Win32-OpenSSH#332]
Hi all,

Add so many issues trying to install, that i've tried to automate it. Here is my powershell contribution to install having in mind the installation wiki found on "https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH".

[install-OpenSSH-Win32.txt](https://github.com/PowerShell/Win32-OpenSSH/files/485111/install-OpenSSH-Win32.txt)

Cheers

**Comment by DarwinJS** [comment]
@marco-vaz - Nice work!

You should know that the Chocolatey package is also able to be used offline without chocolatey, without WOW64.

More information is here: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/readme.md#complete-offline-install-wout-chocolatey-nor-wow64-nor-powershell-5

**Comment by manojampalam** [comment]
Thanks @marco-vaz. I'll put your script in repo and add a pointer in wiki. I'll make the privates keys to system32 and wow64 parts opt-in.

**Comment by manojampalam** [comment]
Added link to wiki. 
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by Bravecold** [comment]
Thanks @marco-vaz I'm wondering about the arguments that require the function.- it's a great job, but please insert some documentation about, Synopsis and how to use please.

**Comment by robetus** [comment]
The installation has been updated but the auto install script has not. Can anyone tell me how to insert  these two steps into the attached script?:

```
powershell -ExecutionPolicy Bypass -File install-sshd.ps1
```
and
```
.\FixHostFilePermissions.ps1 -Confirm:$false
```
[mod-install-OpenSSH-Win32.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1216290/mod-install-OpenSSH-Win32.txt)
