### ISSUE TITLE
Public Key Login failure

### ISSUE THREAD

**Issue by K-B-C** [PowerShell/Win32-OpenSSH#335]
Under version v.0.0.0.9 of OpenSSH-Win64 public key login only functions if the package is installed under: C:\Program Files\OpenSSH-Win64.

Installing under: C:\Program Files\OpenSSH functions, but without the public key login feature.

**Comment by manojampalam** [comment]
I have tried installing in custom paths and it works fine. Make sure you run "installsshd.ps1" from the newer location. Also update sshd_config  and fix subsystem paths.

**Comment by manojampalam** [comment]
Reopen if needed
