### ISSUE TITLE
Please update all chocolatey package references from id "win32-openssh" to "openssh"

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#336]
This change was necessary to accommodate going "down" in version number from 2016.05.30 to 0.0.0.9.

This page has a lot of references to the old package id: https://github.com/PowerShell/Win32-OpenSSH/wiki/Win32-OpenSSH-Automated-Install-and-Upgrade-using-Chocolatey which is now obsoleted.

Links can now to go https://chocolatey.org/packages/win32-openssh

Also much of the information in the document is probably superceded (e.g. Nano support, offline support) by this document: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/readme.md

**Comment by manojampalam** [comment]
https://chocolatey.org/packages/win32-openssh shows a DEPRECATED tag. Is there an updated link?

**Comment by DarwinJS** [comment]
Yes.
https://chocolatey.org/packages/openssh

**Comment by manojampalam** [comment]
done
