### ISSUE TITLE
-E log_file option always returns "Couldn't open logfile"

### ISSUE THREAD

**Issue by allisterb** [PowerShell/Win32-OpenSSH#338]
I'm using the latest release: v0.0.0.9. Any file name or path used for the -E option returns "Couldn't open logfile filename: Invalid argument". I tried using single file names, relative and absolute paths but nothing works.

Steps to reproduce: run any ssh command line with the -E option and a file name:
ssh -E foo.log -l myuser myhost

**Comment by manojampalam** [comment]
dup #526
