### ISSUE TITLE
powershell cannot be started "The patth is not of legal form"

### ISSUE THREAD

**Issue by discodance1** [PowerShell/Win32-OpenSSH#339]
I have installed 64 bit win32-openssh on my windows 2012 server R2 standard edition.
I was able to install the ssh agent and ssh daemon. I am able to ssh into this windows server from my ubuntu server but cannot launch powershell.

powershell -File -
                  The shell cannot be started. A failure occurred during initialization:
The path is not of a legal form.

Am i doing something wrong?

**Comment by discodance1** [comment]
I have installed the latest available version on win32-openssh 64 bit version.

**Comment by SteveL-MSFT** [comment]
which version of PowerShell?

**Comment by discodance1** [comment]
> $PSVersionTable.PSVersion

Major  Minor  Build  Revision

---

5      0      10586  117

**Comment by SteveL-MSFT** [comment]
Can you install WMF5.1 (https://www.microsoft.com/en-us/download/details.aspx?id=53347) and try with that?  I believe we made some changes to PowerShell to specifically support SSH

**Comment by discodance1** [comment]
with WMF5.1, i am now able to launch powershell console. 

Thanks for the quick response.

**Comment by SteveL-MSFT** [comment]
I'm resolving and closing this as Fixed as we made specific changes in 5.1 to address this, but won't be providing a hotfix for 5.0
