### ISSUE TITLE
Issue with starting powershell console on win 2008 R2 standard

### ISSUE THREAD

**Issue by discodance1** [PowerShell/Win32-OpenSSH#343]
I have installed the latest version on win32-openssh 64 bit on win 2008 R2 standard. I am able to ssh to this windows server from my ubuntu box but when i try to open a powershell console using 

> powershell -File -   or powershell.exe , the command prompt reverts back to cmd

 $$$>powershell.exe
powershell.exe
              Windows PowerShell 
Copyright (C) 2016 Microsoft Corporation. All rights reserved.
## user@ C:\Users\$$$j>

$$$$$>powershell -File -
powershell -File -
## user@ C:\Users\$$$j>

I have installed wfm 5.1 on this server which seems to have fixed similar issue on windows server 2012.

Major  Minor  Build  Revision

---

5      1      14394  1000

**Comment by discodance1** [comment]
I am seeing this in the event log:

Application: powershell.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Illegal characters in path.
Stack:
   at System.Environment.FailFast(System.String)
   at System.Management.Automation.WindowsErrorReporting.FailFast(System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[])
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)

**Comment by discodance1** [comment]
Any help on this is highly appreciated.

**Comment by discodance1** [comment]
does only win32-openssh 32 bit work on win2008 R2 sp1 ? (along with .net 4.6 and wmf 5.1). Even with these installations. powershell console sometimes launches with powershell, sometimes with powershell.exe/ powershell.exe -File -. 

I don`t see a consistent behavior.  
Can you let me know the installation steps for 2008 R2 sp1, which version of win32-openssh works and the dependencies ?

**Comment by SteveL-MSFT** [comment]
We had to make changes in PowerShell 5.1 to work correctly via SSH.  Try installing WMF5.1 Preview from here: https://www.microsoft.com/en-us/download/details.aspx?id=53347

**Comment by discodance1** [comment]
I have already installed WMF 5.1. Launching powershell is not consistent (with powershell.exe -File -) with win32 openssh 32 bit. From time to time i get error:
" The given path's format is not supported."

**Comment by SteveL-MSFT** [comment]
Sorry missed the part about 5.1.  We'll investigate this.

**Comment by manojampalam** [comment]
Please try out the milestone release. Reopen if needed.
