### ISSUE TITLE
LsaRegisterLogonProcess Failed

### ISSUE THREAD

**Issue by discodance1** [PowerShell/Win32-OpenSSH#346]
I am trying to use public key authentication from my linux server to windows. I have ensure that the ssh-lsa.dll exists under c:\windows\system32\ and the user's public key is copied to 
c:\Users\user.ssh\authorized_keys.

From my linux server i am running this command:

ssh -i <private_key> user@fqdn_of_windows host

in sshd.exe log i see this error: 
debug1: LsaRegisterLogonProcess failed
debug1: unable to generate token for user

**Comment by discodance1** [comment]
I have also verified that the nt service sshd user has "Replace primary token rights" on the local machine.

ntrights.exe -u "NT SERVICE\SSHD" +r SeAssignPrimaryTokenPrivilege.

**Comment by discodance1** [comment]
This is the sshd log

This is the sshd.log

debug2: input_userauth_request: try method publickey  
debug3: w32_write fd:4  
debug2: write - io:00000065D2BEDA60  
debug3: wait() on 0 events and 0 childres  
debug2: WriteCB - pio:00000065D2BEDA60, pending_state:1, error:0, transferred:4 of remaining: 4  
debug2: write - reporting 4 bytes written, io:00000065D2BEDA60  
debug3: w32_write fd:4  
debug2: write - io:00000065D2BEDA60  
debug3: wait() on 0 events and 0 childres  
debug2: WriteCB - pio:00000065D2BEDA60, pending_state:1, error:0, transferred:978 of remaining: 978  
debug2: write - reporting 978 bytes written, io:00000065D2BEDA60  
debug3: w32_read fd:4  
debug3: read - io:00000065D2BEDA60 remaining:0  
debug2: ReadFileEx io:00000065D2BEDA60  
debug3: wait() on 0 events and 0 childres  
debug2: ReadCB pio:00000065D2BEDA60, pending_state:1, error:109, received:0  
debug2: read - (2) no more data, io:00000065D2BEDA60  
debug1: auth agent did not authorize client <USER>  
debug3: w32_close fd:4  
debug1: close - io:00000065D2BEDA60, type:2, fd:4, table_index:4  
debug2: fileclose - pio:00000065D2BEDA60  
debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa  
Failed publickey for <USER> from 2620:0:10c1:1056:: port 39101 ssh2: RSA SHA256:lXw1wLkgAWuJGECJpaqN8He/iABPz  
aUJttgzXaY  
debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"  
debug3: w32_write fd:5  
debug2: send - io:00000065D2BF5D00  
debug2: send - WSASend() returned 0, APC scheduled io:00000065D2BF5D00  
debug2: WSASendCB - io:00000065D2BF5D00, pending_state:1, error:0, sent:76 of remaining:76  
debug3: w32_select fd:5  
debug3: Total in fds:1

**Comment by discodance1** [comment]
This a domain account.

**Comment by manojampalam** [comment]
Are you sure you are using the latest version? sshd should not be calling LsaRegisterLogonProcess as it now runs in low privileged mode.

**Comment by discodance1** [comment]
On the latest versions i haven't seen this issue. closing it.
