### ISSUE TITLE
ssh session hang on Nano RTM

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#347]
Configuration:
ssh 0.0.1.0 installed on Windows 10 Anniversary logging into sshd 0.0.1.0 running on Nano RTM.

After entering credentials, screen goes blank, blinking cursor in upper left - nothing more happens.

On Nano I can use netstat to see that a connection occurred.

The same testing (same client and server) with version 0.0.9.0 worked fine.

Nano RTM is a freshly reset VM each time.

Windows 10 has Bash installed - but it was also that way for the 0.0.9.0 testing a few days ago.

**Comment by manojampalam** [comment]
Yes. The server side changes do not work on Nano yet. Made a note of it in release notes.

**Comment by jdub** [comment]
The note wasn't quite clear enough (at least to me): "The server side changes do not work" suggests improvements or updates in this version do not work, rather than sshd not providing a working ssh service. 😄

**Comment by bingbing8** [comment]
You need to do the following to get a remote cmd session on nano (since Nano does not support PTY)
ssh.exe user@target cmd.exe
