### ISSUE TITLE
Nano: ssh output appears on console instead of in Remote PowerShell session

### ISSUE THREAD

**Issue by rob-scheepens** [PowerShell/Win32-OpenSSH#349]
After creating a Nano image with OpenSSH included (using -SetupCompleteCommand @("cd c:\openssh\tools","powershell .\barebonesinstaller.ps1 -SSHServerFeature"), it seems an overlay (terminal) window is created on the Nano console. Using Alt+TAB it is possible to switch back to the Nano logon prompt. However, ssh output is redirected to that window, making it appear that for example an scp command is hung, while it is actually waiting for user input on the console.

This command appears stuck:
![scp_command_appears_hung](https://cloud.githubusercontent.com/assets/15910576/19035174/3346dc8e-8968-11e6-8870-7d7b074d01e2.png)
...but it's actually awaiting user input here:
![output_on_nano_console](https://cloud.githubusercontent.com/assets/15910576/19035173/33458f14-8968-11e6-8bbb-bf2aacadaa86.png)

**Comment by manojampalam** [comment]
Known issue. PTY on server side does not work on nano yet. I assume you are using an older build.

**Comment by rob-scheepens** [comment]
@manojampalam, Nano build is 14393.rs1_release.160715-1616, OpenSSH is 0.0.1.0 (https://chocolatey.org/api/v2/package/openssh/0.0.1.0). Should the behavior be different on for example 14393.0.160911-2111.RS1_Refresh?

**Comment by rob-scheepens** [comment]
@manojampalam : after upgrading to 0.0.1.0 I seem to be running into https://github.com/PowerShell/Win32-OpenSSH/issues/347 on Nano. Any ETA on when this will be addressed?

**Comment by manojampalam** [comment]
@rayhayes  is looking into it. dup #347
