### ISSUE TITLE
$host.ui.RawUI.ReadKey - VirtualKeyCode Returns Zero

### ISSUE THREAD

**Issue by Fitzroy87** [PowerShell/Win32-OpenSSH#351]
Source computer: Windows 7 Pro SP1
Target computer: Windows 7 Pro SP1
- Enter the command: `$key = $host.ui.RawUI.ReadKey("NoEcho,IncludeKeyDown")`
- Press a key
- Enter the command: `$key.virtualkeycode`

Letter keys return a virtualkeycode of zero. Whereas arrow keys return the expected value.

Why is this?

**Comment by bingbing8** [comment]
Did you mean to open this in Powershell issue list? If not please clarify and reopen.

**Comment by Fitzroy87** [comment]
@bingbing8 The problem described occurs when connecting from a machine using the Win32-OpenSSH client to a machine running the Win32-OpenSSH server and then launching PowerShell (on the target machine).

I don't think I have authority to reopen, so please can you do so.
