### ISSUE TITLE
Unicode - Windows 7

### ISSUE THREAD

**Issue by Fitzroy87** [PowerShell/Win32-OpenSSH#352]
Running the following within a local powershell console on Windows 7 results in a right arrow character and left arrow character:
`26..27|%{[char]$_}`
`→`
`←`

However when run from within an SSH session, the characters are not rendered as expected:
`Æ`
`É`

My (limited) understanding is that conhost does support a subset of unicode characters. 

Does SSH suppress all unicode support under Windows 7?

**Comment by rayhayes** [comment]
It was an issue with the way the console was handling the output. Should be fixed in next release.
