### ISSUE TITLE
given public key is not mapped to user USER@DOMAIN (profile:(null))

### ISSUE THREAD

**Issue by discodance1** [PowerShell/Win32-OpenSSH#353]
I am trying to log in as a roll account which has not logged into the windows server i am trying to ssh.

This is the error in ssh_agent log:
given public key is not mapped to user user@domain (profile:(null)). I have copied user's public key under C:\Users\user.ssh\authroized_keys

environment="sshuser=USER@DOMAIN" from="IP ADDRESS RANGE" ssh-rsa-naldnangsgksbksb USER@DOMAIN

**Comment by discodance1** [comment]
SSHD log:

w32_read fd:4
2556 23:18:51 545 debug3: read - io:0064A368 remaining:0
2556 23:18:51 545 debug2: ReadFileEx io:0064A368
2556 23:18:51 561 debug3: wait() on 0 events and 0 childres
2556 23:18:51 607 debug2: ReadCB pio:0064A368, pending_state:1, error:109, received:0
2556 23:18:51 607 debug2: read - (2) no more data, io:0064A368
2556 23:18:51 607 debug1: auth agent did not authorize client USER@DOMAIN
2556 23:18:51 607 debug3: w32_close fd:4
2556 23:18:51 607 debug1: close - io:0064A368, type:2, fd:4, table_index:4
2556 23:18:51 607 debug2: fileclose - pio:0064A368
2556 23:18:51 607 debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa
2556 23:18:51 607 Failed publickey for USER@DOMAIN from 2620:0:10c1:1056:: port 49775 ssh2: RSA SHA256:lXw1wLkgAWuJ8unSaHe/iABPzaUJttgzXaY
2556 23:18:51 607 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"
2556 23:18:51 607 debug3: w32_write fd:3

**Comment by discodance1** [comment]
I am sshing from a linux server to this windows server using:

ssh -i <private key> -l user@domain host

**Comment by discodance1** [comment]
Any pointers to check are really appreciated.

**Comment by manojampalam** [comment]
I assume you meant C:\Users\user.ssh\authroized_keys ("\" after "user")
Otherwise 
profile:(null)) 
that seems to be the problem. 

ssh-agent couldn't lookup profile path for this user. What is a "roll account" ?

**Comment by discodance1** [comment]
Looks like we need the user profile created before the user tries to ssh in. I was able to resolve the issue after the user profile was created on the windows server i was trying to ssh in.
