### ISSUE TITLE
scp.exe: "./ssh.exe could not be started"

### ISSUE THREAD

**Issue by tocklime** [PowerShell/Win32-OpenSSH#354]
I've installed v0.0.1.0 from chocolatey (choco install openssh).

When I run:

```
PS C:\>scp test example.com:test
./ssh.exe could not be started
```

but

```
PS C:\> cd 'C:\Program Files\OpenSSH-Win64'
PS C:\Program Files\OpenSSH-Win64> scp test example.com:test
sssh: connect to host example.com port 22: No error
lost connection
```

i.e., it is finding ssh.exe when run from the same directory as ssh.exe, but not otherwise. ssh.exe is on the path.

I expected scp.exe to work when I'm in any directory, but it only works when I'm in the Program Files\OpenSSH-Win64 directory.

**Comment by tocklime** [comment]
Nevermind, My Path included cygwin before C:\Program Files\OpenSSH-Win64, so I guess scp.exe was finding the wrong version of ssh.exe and choking. I've reordered the path and it's happy now.

**Comment by DarwinJS** [comment]
Did you restart your shell to re-read the PATH environment variable?  

It would be nice if it was immediately usable in the same shell, eh?  Could I bother you to submit a feature request to have the package set the current process path as well: https://github.com/darwinjs/chocopackages

**Comment by tocklime** [comment]
@DarwinJS I did restart the shell. Rebooted too, in frustration. I'll add a feature request.

**Comment by DarwinJS** [comment]
Well that would be  bug report then - it should add to the path - please include details about your OS.

**Comment by tocklime** [comment]
No, it did edit the Path variable fine (stuck the OpenSSH-Win64 directory on the end. I'm going to reopen this too, because I was wrong above - even editing the path, I'm still getting ssh.exe could not be started. I was accidentally running cygwin's scp.exe above, when I thought it was working.

The machine I'm having trouble on is Windows Web Server 2008 R2. It's 64 bit. This is the path (I moved the OpenSSH-Win64 directory up to the front, but it didn't fix anything)

```
PS C:\Users\Administrator> $env:Path
%SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\Program Files\OpenSSH-Win64;C:\ProgramData\Oracle\Java\javapath;C:\Win
dows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Fi
les\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Fi
les\TortoiseHg\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windo
ws\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;
```

**Comment by tocklime** [comment]
I found out powershell's equivalent of `which`:

```
PS C:\Users\Administrator> get-command ssh |Format-Table Path, Name

Path                                                        Name
----                                                        ----
C:\Program Files\OpenSSH-Win64\ssh.exe                      ssh.exe


PS C:\Users\Administrator> get-command scp |Format-Table Path, Name

Path                                                        Name
----                                                        ----
C:\Program Files\OpenSSH-Win64\scp.exe                      scp.exe


PS C:\Users\Administrator> scp test example.com:test
./ssh.exe could not be started
```

**Comment by tocklime** [comment]
I've just installed it on my desktop (also via chocolatey), and am getting very similar results.

**Comment by DarwinJS** [comment]
I believe it is your use of "./"  On my system straight "ssh" works WHEN I AM NOT in the SSH folder.  The .\ works if I am in the folder where ssh is.  

Using .\ or ./ when I am not in the folder fails.

**Comment by tocklime** [comment]
yes, ssh.exe always works for me too. it's scp that doesn't.

**Comment by tocklime** [comment]
~~Looking at the code:~~
~~https://github.com/PowerShell/Win32-OpenSSH/blob/L1-Prod/scp.c#L915~~

~~I'm unfamiliar with the code base, but it looks like scp.exe's call to ssh.exe is not passing in the environment (3rd argument to `start_process_io` is `NULL`) - perhaps that's why?~~

(I think it inherits env from parent)

Not discounting the 'my machine is set up weird' scenario, just thought I'd look at the code and that seemed odd. Does scp.exe work for you, @DarwinJS?

**Comment by DarwinJS** [comment]
Try scp with no command to see whether you get the help.  For me scp is working the same way - displays the help in the exact same scenario as ssh.

There might be a problem with SCP in your configuration - but it woud not seem to have anything to do with the path.

**Comment by tocklime** [comment]
scp with no command gives me the help, whether I'm in the OpenSSH-Win64 directory or not. scp actually trying to copy a file works if i'm in the directory, but not otherwise. I get the exact same behaviour on the machine I'm remoted into and my desktop.

``` powershell
PS C:\Program Files\OpenSSH-Win64> scp
usage: scp [-12346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
           [-l limit] [-o ssh_option] [-P port] [-S program]
           [[user@]host1:]file1 ... [[user@]host2:]file2
PS C:\Program Files\OpenSSH-Win64> scp a example:b
ssh.exe: Could not resolve hostname example: No such host is known.
lost connection
PS C:\Program Files\OpenSSH-Win64> cd ..
PS C:\Program Files> scp
usage: scp [-12346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
           [-l limit] [-o ssh_option] [-P port] [-S program]
           [[user@]host1:]file1 ... [[user@]host2:]file2
PS C:\Program Files> scp a example:b
./ssh.exe could not be started
```

**Comment by tocklime** [comment]
It looks like something in the code is defining `ssh_program` to be `./ssh.exe` (though I can't see where), with the `./`  which means windows doens't check the path. `sftp.exe` has a very similar problem: (I remembered about -v):

``` powershell
PS C:\Program Files> sftp
usage: C:\Program Files\OpenSSH-Win64\sftp.exe [-1246aCfpqrv] [-B buffer_size] [-b batchfile] [-c cipher]
          [-D sftp_server_path] [-F ssh_config] [-i identity_file] [-l limit]
          [-o ssh_option] [-P port] [-R num_requests] [-S program]
          [-s subsystem | sftp_server] host
       C:\Program Files\OpenSSH-Win64\sftp.exe [user@]host[:file ...]
       C:\Program Files\OpenSSH-Win64\sftp.exe [user@]host[:dir[/]]
       C:\Program Files\OpenSSH-Win64\sftp.exe -b batchfile [user@]host
PS C:\Program Files> sftp -v a example:b
debug1: pipe - read end: handle:00000000000000A4, io:00000000003F8990, fd:3
debug1: pipe - write end: handle:00000000000000A8, io:00000000003F8A40, fd:4
debug1: pipe - read end: handle:00000000000000AC, io:00000000003F8AF0, fd:5
debug1: pipe - write end: handle:00000000000000B0, io:00000000003F8BA0, fd:6
debug1: Executing ssh client: "./ssh.exe -oForwardX11=no -oForwardAgent=no -oPermitLocalCommand=no -oClearAllForwardings
=yes -v -oProtocol=2 -s -- a sftp"...

fork: No such file or directory
PS C:\Program Files> cd .\OpenSSH-Win64
PS C:\Program Files\OpenSSH-Win64> sftp -v a example:b
debug1: pipe - read end: handle:00000000000000A4, io:00000000003E8990, fd:3
debug1: pipe - write end: handle:00000000000000A8, io:00000000003E8A40, fd:4
debug1: pipe - read end: handle:00000000000000AC, io:00000000003E8AF0, fd:5
debug1: pipe - write end: handle:00000000000000B0, io:00000000003E8BA0, fd:6
debug1: Executing ssh client: "./ssh.exe -oForwardX11=no -oForwardAgent=no -oPermitLocalCommand=no -oClearAllForwardings
=yes -v -oProtocol=2 -s -- a sftp"...

debug1: Register child 00000000000000B8 pid 4536, 0 zombies of 0
debug1: close - io:00000000003E8AF0, type:2, fd:5, table_index:5
debug1: close - io:00000000003E8A40, type:2, fd:4, table_index:4
OpenSSH_7.1p1 Microsoft_Win32_port_with_VS, OpenSSL 1.0.2d 9 Jul 2015
debug1: Reading configuration data C:\Users\Administrator/.ssh/config
ssh.exe: Could not resolve hostname a: No such host is known.
Connection closed
```

**Comment by tocklime** [comment]
looks like `_PATH_SSH_PROGRAM` is set to `./ssh.exe` here: https://github.com/PowerShell/Win32-OpenSSH/blob/69be768f2eada42792ccf9d23819a84f29e4b877/contrib/win32/openssh/config.h.vs#L1728

Which leaves me wondering how this works for anyone.

**Comment by manojampalam** [comment]
Thanks for investigating. Looks like scp.exe is always being used from within the installation directory.

**Comment by bluekeys** [comment]
To confirm, scp works for me only if I run it from C:\Program Files\OpenSSH-Win64

**Comment by mikemaccana** [comment]
I'm getting the exact same as what @bluekeys mentioned - I have to cd into C:\Program Files\OpenSSH-Win64 to be able to run `scp`

**Comment by shiatsumat** [comment]
I got the same experience as @bluekeys and @mikemaccana (although PATH is correctly set), but I found that by adding a command line option "-S C:\Progra~1\OpenSSH-Win64\ssh.exe" it works. I'm not sure what it means.

**Comment by manojampalam** [comment]
This was fixed a while back. Try out the latest release and reopen if you still see it

**Comment by bluekeys** [comment]
@Kinokkory, @mikemaccana, @manojampalam, @kobeyu

This is now working for me. I upgraded to the latest version 0.0.4.0 using choco 

`choco update openssh` (in an administrator terminal)

Thanks for the update.
