### ISSUE TITLE
Logs Not Updated

### ISSUE THREAD

**Issue by laurinkeithdavis** [PowerShell/Win32-OpenSSH#358]
Trying to debug an SFTP issue. Removed Win32-OpenSSH completely. Installed via Chocolatey. Configured LogLevel to DEBUG3. I've searched my entire system and I have sftp-server.log files in C:\Program Files\OpenSSH-Win64 and in the %USERPROFILE% folder of the user that I'm trying to login as, but none of these are being updated (empty files).

**Comment by laurinkeithdavis** [comment]
Ok, so I had to add NT SERVICE\SSHD to Administrators and now this file is being updated:

C:\Program Files\OpenSSH-Win64\sshd.log

But this file, while locked open by the process and the modification date is changing, is still 0 bytes

C:\Program Files\OpenSSH-Win64\sftp-server.log

**Comment by SteveL-MSFT** [comment]
You don't need to add "NT SERVICE\SSHD", just need to give write permission to that folder to that service account.

**Comment by manojampalam** [comment]
Installation script should now put the rights ACLs on "logs" folder.
