### ISSUE TITLE
SSH client emits "blank" error after accepting a new trusted host

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/Win32-OpenSSH#359]
This was causing a PowerShell SSH connection to error out after the user accepted a new trusted host.  The reason of the PowerShell transport error was because the SSH client emitted an error with a blank error message after emitting the expected warning:

``` powershell
The authenticity of host 'computer' can't be established.
ECDSA key fingerprint is SHA256:AeRUkqd3vJjZDNI07Do4BBpmutic4UR35bKw3FBV6a4.
Are you sure you want to continue connecting (yes/no)?
Warning: Permanently added 'computer' to the list of known hosts.

# "Blank" error message received here causing connection termination
```

PowerShell SSH remoting treats all SSH client errors as terminating errors and so terminates the connection with this blank error.  This only happens with Win32-OpenSSH, I don't see this behavior on Linux Ubuntu, so this appears to be a Win32 implementation only behavior.

I can fix this in PowerShell SSH remoting by ignoring "blank" error messages but this also looks like a bug in Win32-OpenSSH.

**Comment by arif-pragmasys** [comment]
Is this still happening with latest?

**Comment by bingbing8** [comment]
Reopen if you still see it.
