### ISSUE TITLE
Need MSI install package for Win32-OpenSSH

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/Win32-OpenSSH#360]
Win32-OpenSSH should have MSI install packages available similar to SSH packages for other Linux distros like Ubuntu and OSX.  This would automate the process of downloading and configuring OpenSSH on Windows.  I don't know if there should be separate packages for client and server but now that PowerShell supports SSH based remoting it would be nice to have an automated way to install SSH so that a new PowerShell 'Enable-SSHRemoting' cmdlet can install SSH to a target platform as needed.

**Comment by megamorf** [comment]
Duplicate of #350. Please close.

**Comment by PaulHigin** [comment]
Closing as this is a duplicate of #350
