### ISSUE TITLE
Terminal issues in v0.0.1.0

### ISSUE THREAD

**Issue by dermeister0** [PowerShell/Win32-OpenSSH#362]
**Midnight Commander**

Functional keys (F1 - F12) do not work.
Cursor position is changed several times for each arrow key press.
Many wrong characters are displayed on screen.
Window size is broken after entering a lot of characters to command line.
Large terminal size is not supported.

![2016-10-10_1757](https://cloud.githubusercontent.com/assets/4054844/19233980/238f753e-8f13-11e6-8d00-ce00ef42a3a6.png)
![2016-10-10_1801](https://cloud.githubusercontent.com/assets/4054844/19234068/889e7876-8f13-11e6-9df6-654fde1e3b4d.png)
![2016-10-10_1803](https://cloud.githubusercontent.com/assets/4054844/19234143/ec1bde0c-8f13-11e6-86dd-bcee7c8bc110.png)

**Comment by dermeister0** [comment]
**Far Manager**

Nothing works.

![2016-10-10_1804](https://cloud.githubusercontent.com/assets/4054844/19234195/3ca3c4b6-8f14-11e6-8360-0cfb812ed05f.png)

**Comment by dermeister0** [comment]
**Nano**

Cursor keys do not work.

![2016-10-10_1809](https://cloud.githubusercontent.com/assets/4054844/19234266/aa8e3fe2-8f14-11e6-9efb-1dde2e6de9cd.png)

**Comment by manojampalam** [comment]
Please check milestone release and reopen if needed.
