### ISSUE TITLE
sshd does not forward output of command

### ISSUE THREAD

**Issue by jake-at-work** [PowerShell/Win32-OpenSSH#365]
Try

```
$ ssh user@windows powershell
```

exits immediately without output

Say you have a executable that does long running work, cmake in my case

```
$ ssh user@windows cmd /c make --build .
```

there is no output but cmake is running as seen in the task manager, the session exits when cmake completes.

Forcing a tty with `-t` has similar behavior except that the session does not exit when command completes.

Output is seen if you shell rather than command.

```
$ ssh user@windows
user@windows C:\Users\usr> cmake --build .
....
lots of cmake output
....
user@windows C:\Users\usr>
```

CMake outputs as expected.

Or the powershell example:

```
$ ssh user@windows
user@windows C:\Users\usr> powershell
PS C:\Users\usr>
```

Powershell outputs as expected.

**Comment by SteveL-MSFT** [comment]
What version of powershell and openssh?

**Comment by mikedld** [comment]
I have the same issue. Just installed Win32-OpenSSH (so, v0.0.1.0), not sure how to check powershell version but it's the one bundled with Windows 10 with all the updates installed.

In addition to the above, I've noticed this:

```
C:\Users\mikedld>powershell

C:\Users\mikedld>echo %errorlevel%
-1073741502
```

Getting same errorlevel value when trying to run e.g. Far Manager or cl.

Here `-1073741502` is `0xc0000142` which appears to be "The application failed to initialize properly".

**Comment by SteveL-MSFT** [comment]
alpha.10 broke something @PaulHigin

**Comment by jake-at-work** [comment]
Power shell is meant as just an example of and executable that fails to get output. We are using poweshell 5.

Effectively it's anything that is sent in as a command in non-interactive mode that does not get output. If you run the same commands in interactive mode they work just fine.

**Comment by jake-at-work** [comment]
SSH 0.0.1.0

**Comment by xenoscopic** [comment]
Have you tried invoking the command with sshd in debug mode?  I had the same problem with the latest release, but for some reason things seem to work when the server is in debug mode (although you can only run a single command at that point).  Perhaps there is something in the forking (or equivalent) that sshd does that is killing things?

**Comment by mikedld** [comment]
Okay, I fixed the issue. It appears that Windows 10 now includes two new services: "SSH Server Proxy" and "SSH Server Broker", both described as "Part of Microsoft SSH Server for Windows". When I thought I was connecting to OpenSSH I was in fact connecting to this built-in SSH service. I noticed that sshd service wasn't running, so I stopped those built-in services and then started sshd. Far Manager still isn't usable (some drawing and keys handling issues), but at least I'm seeing output of other commands just fine.

**Comment by DarwinJS** [comment]
Those services are part of Windows 10 "Developer Mode" - usually enabled to have access to Anniversary Edition's "Windows Subsystem for Linux" / Bash shell.  

When using the chocolatey package it should detect this condition and refuses to install unless you disable those services or use a custom port for Win32-OpenSSH.

More here #318

**Comment by manojampalam** [comment]
Issue understood and it needs certain fixes in shell hosting logic on server side. Its around server not respecting the (-t) PTY request flag. 
I'll try it get it fixed in Oct-End milestone.
