### ISSUE TITLE
ssh connection command similar to linux ?

### ISSUE THREAD

**Issue by discodance1** [PowerShell/Win32-OpenSSH#366]
Instead of using ssh -i private_key -l user@domain host can we make this call similar to linux 
which is ssh -i private_key user@host in some way ?

**Comment by SteveL-MSFT** [comment]
you can use 'ssh -i key user@host' for local users, domain users will require using '-l user@domain'.  This is as expected.

**Comment by manojampalam** [comment]
You can also do 
ssh -i private_key user@domain@host
