### ISSUE TITLE
Logging, permissions on log files and security issues

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#367]
I believe on Windows, SSH logs should go to the machine state data location %ProgramData% ?

This would ensure that:
- The logs are writable without giving the EXE write permissions to it's own binary folder
- Logs are not uac virtualized on Client OSes when writing back to Program files with non-admin
- administrators don't give end user accounts permissions to write to this folder, thereby undoing it's built-in malware protection design.

Even on non-windows it would be wise for ssh to be applying these same principles.  Some linux software is good about separating state data from binary locations - but many linux softwares are not.
Fyi should prevent issues like #358

**Comment by manojampalam** [comment]
Valid points. I pefer the deamon and agent logs to be in the same (binary) location. I would like to keep open the idea to potentially support multiple sxs versions of SSH (including different versions of Win32 OpenSSH). We can create a logs folder with appropriate permissions to solve the security issues.

**Comment by manojampalam** [comment]
Since https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.5.0
Logging is done in %bin%\logs folder where %bin% is installation directory. logs directory is ACLed to be writable only by admin and sshd accounts.
