### ISSUE TITLE
Support shortcuts on cmd

### ISSUE THREAD

**Issue by nachfuellbar** [PowerShell/Win32-OpenSSH#37]
Hello,

in a ssh session in powershell i can use shortcuts  like "ctrl + a" and "ctrl + e"
with ssh in cmd i can't use this shortcuts

thanks

**Comment by jungle-boogie** [comment]
What's the current behavior when you use `ctrl + a`?

**Comment by nachfuellbar** [comment]
I got `^A` at the end of the line
I tried this multiple times now and it's seems like this work most of the time
Only sometimes i can't use this shortcuts; On powershell this works every time for me (except for blanking of the input)

**Comment by nachfuellbar** [comment]
Only happend on cmd's which i used over a longer time (hours to days; with multiple commands including telnet)
Can't reproduce this at the moment
