### ISSUE TITLE
Chocolatey package link in docs

### ISSUE THREAD

**Issue by jwhipp** [PowerShell/Win32-OpenSSH#371]
Link in docks is to the only depreciated package, should be this:

https://chocolatey.org/packages/openssh

**Comment by robolivable** [comment]
Just out of curiosity, are the dates on the Disqus comments on that page accurate? Seems strange that there are four year old comments when the oldest package version is only about a month old...

**Comment by DarwinJS** [comment]
Hello, I am the Chocolatey packager for OpenSSH and can explain that oddity.

On chocolatey the package id "openssh" was used some time back for a package that never went public (never got out of moderation).

The simple way to gain the id for the package was to make me a moderator of the existing ID - hence the old, non-relevant stuff hanging off it.

I will check if a cleanup is possible - but yes, the official chocolatey package id for this openssh project is "openssh".

**Comment by manojampalam** [comment]
Reopen if needed
