### ISSUE TITLE
sftp client does not work

### ISSUE THREAD

**Issue by eperede** [PowerShell/Win32-OpenSSH#374]
Hello,

we'd like to use the sftp client. The openssh-win64 has been unpacked to "c:\program files\openssh" directory on Windows 7 64 bit. After doing the installation and path setup, we get the following error whenever we try to run the program from a location NOT c:\program files\openssh .

_D:\Users\u55XXXX>sftp -v iak@10.11.12.13
debug1: pipe - read end: handle:00000000000000A4, io:0000000000380300, fd:3
debug1: pipe - write end: handle:00000000000000A8, io:00000000003803B0, fd:4
debug1: pipe - read end: handle:00000000000000AC, io:0000000000380460, fd:5
debug1: pipe - write end: handle:00000000000000B0, io:0000000000382530, fd:6
debug1: Executing ssh client: "./ssh.exe -oForwardX11=no -oForwardAgent=no -oPer
mitLocalCommand=no -oClearAllForwardings=yes -v -l iak -oProtocol=2 -s -- 10.11.
12.13 sftp"...

fork: No such file or directory_

If we run the command from c:\program files\openssh then it works.

I agree that we could have used the directory c:\program files\openssh-win64 however I think it's nowhere explicitely forbidden to change the directory name.

**Comment by eperede** [comment]
I was still trying some more things and wanted to share:
ssh.exe works fine. 
D:\Users\u55XXXX>ssh ciri1.sap.XXX.XXX.XXX
Authorized uses only. All activity may be monitored and reported.
u55XXXX@ciri1.sap.XXX.XXX.XXX's password:

scp.exe fails as well if you do not enter the directory where it's installed. 
D:\Users\u55XXXX>scp iak@ciri1.sap.XXX.XXX.XXX:test.txt c:\
./ssh.exe could not be started
D:\Users\u55XXXX>

If you enter the directory of openssh then scp works as well.
The whole story happens with v0.0.1.0 .

**Comment by manojampalam** [comment]
This will be fixed in Oct--Mid milestone

**Comment by manojampalam** [comment]
Try https://github.com/PowerShell/Win32-OpenSSH/milestone/4 and reopen if you see still see it
