### ISSUE TITLE
Emacs doesn't render characters properly and infinitely scrolls when terminal goes to full screen.

### ISSUE THREAD

**Issue by g-mips** [PowerShell/Win32-OpenSSH#376]
So I am running on a Windows 10 Home Edition with Anniversary Update and using ssh to ssh into my Raspberry Pi 2 Model B.

I tried opening emacs and some of the characters were being rendered incorrectly. As well, the moment I went into full screen, the text began to scroll and became tabbed like stairs.

![opensshbug](https://cloud.githubusercontent.com/assets/7365623/19573553/f9c15232-96c3-11e6-856c-ad46a0634467.gif)

**Comment by manojampalam** [comment]
can you open bash on your target (or any shell that supports VT100)? I have seen issues with vi on CSH but it works fine in BASH.

**Comment by manojampalam** [comment]
Reopen if needed
