### ISSUE TITLE
Latest release v0.0.1.0 does not allow to change Windows drive 

### ISSUE THREAD

**Issue by cristeab** [PowerShell/Win32-OpenSSH#377]
Hi

I have installed latest release, but when logging with winscp from a different machine only C: drive is visible (there is an E: drive). Also, I have tried to use git to clone a repository found on E: drive with the same result. Is this a known problem or is there a workaround for it ?

thanks
Bogdan

**Comment by cristeab** [comment]
Also, symbolic links are not followed (not sure if this is a completely different issue)

**Comment by cristeab** [comment]
I have forgot to mention, all binaries are installed on drive E:, but still only C: is visible

**Comment by cristeab** [comment]
The git clone command does not seem to work even when I move the repository on C: drive

**Comment by manojampalam** [comment]
Try latest release and reopen if needed
