### ISSUE TITLE
Nano server: publickey authentication failure

### ISSUE THREAD

**Issue by mikhirev** [PowerShell/Win32-OpenSSH#378]
I'm trying to get sshd working in docker container based on Nano server. My dockerfile is:

```
FROM microsoft/nanoserver

ARG SSH_VERSION=v0.0.1.0

RUN powershell  -command \
    $ErrorActionPreference = 'Stop'; \
    $VerbosePreference = 'Continue'; \
    iwr -usebasicparsing "https://github.com/PowerShell/Win32-OpenSSH/releases/download/$env:SSH_VERSION/OpenSSH-Win64.zip" -outfile openssh-win64.zip; \
    expand-archive openssh-win64.zip -destinationpath '/program files'; \
    rm openssh-win64.zip; \
    rni '/program files/openssh-win64' openssh; \
    cd '/program files/openssh'; \
    powershell -executionpolicy bypass -file install-sshd.ps1; \
    ./ssh-keygen -A; \
    powershell -executionpolicy bypass -file install-sshlsa.ps1; \
    set-service ssh-agent -startuptype automatic

ADD authorized_keys /users/administrator/.ssh/authorized_keys

WORKDIR /program files/openssh
CMD ./sshd -ddd
EXPOSE 22
```

I'm unable to login into container using public key. The `authorized_keys` file is a copy of one that I use on host system, I can `ssh localhost` successfully. The relevant part of `sshd` output inside the container is following:

```
debug1: userauth-request for user Administrator service ssh-connection method publickey
debug1: attempt 1 failures 0
debug2: input_userauth_request: try method publickey
debug1: test whether pkalg/pkblob are acceptable
debug3: w32_write fd:5
debug2: send - io:0000019153C9AF80
debug2: send - WSASend() returned 0, APC scheduled io:0000019153C9AF80
debug2: WSASendCB - io:0000019153C9AF80, pending_state:1, error:0, sent:324 of remaining:324
debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa
Postponed publickey for Administrator from 172.22.224.1 port 49794 ssh2
debug3: w32_select fd:5
debug3: Total in fds:1
debug2: on_select - io:0000019153C9AF80 type:1 rd:1
debug3: WSARecv - pio: 0000019153C9AF80
debug2: WSARecv - WSARecv() returned 0, io:0000019153C9AF80
debug3: wait() on 0 events and 0 childres
debug2: WSARecvCompletionCB - io:0000019153C9AF80, pending_state:1, flags:0, error:0, received:644
debug3: select - returning 1
debug3: w32_read fd:5
debug3: recv - io:0000019153C9AF80
debug2: recv - returning 644 bytes from prior completed IO, remaining:0, io:0000019153C9AF80
debug1: userauth-request for user Administrator service ssh-connection method publickey
debug1: attempt 2 failures 0
debug2: input_userauth_request: try method publickey
debug3: w32_write fd:4
debug2: write - io:0000019153C9AAD0
debug3: wait() on 0 events and 0 childres
debug2: WriteCB - pio:0000019153C9AAD0, pending_state:1, error:0, transferred:4 of remaining: 4
debug2: write - reporting 4 bytes written, io:0000019153C9AAD0
debug3: w32_write fd:4
debug2: write - io:0000019153C9AAD0
debug3: wait() on 0 events and 0 childres
debug2: WriteCB - pio:0000019153C9AAD0, pending_state:1, error:0, transferred:978 of remaining: 978
debug2: write - reporting 978 bytes written, io:0000019153C9AAD0
debug3: w32_read fd:4
debug3: read - io:0000019153C9AAD0 remaining:0
debug2: ReadFileEx io:0000019153C9AAD0
debug3: wait() on 0 events and 0 childres
debug2: ReadCB pio:0000019153C9AAD0, pending_state:1, error:109, received:0
debug2: read - (2) no more data, io:0000019153C9AAD0
debug1: auth agent did not authorize client Administrator
debug3: w32_close fd:4
debug1: close - io:0000019153C9AAD0, type:2, fd:4, table_index:4
debug2: fileclose - pio:0000019153C9AAD0
debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa
```

BTW I'm unable to start `sshd` as service in such container:

```
PS C:\program files\openssh> start-service sshd
start-service sshd
start-service : Service 'sshd (sshd)' cannot be started due to the following
error: Cannot start service sshd on computer '.'.
At line:1 char:1
+ start-service sshd
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceControl
   ler:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Comman
   ds.StartServiceCommand
```

I also tried using versions 0.0.0.9 and 5_30_2016 with the same result.

P. S. I'm not familiar with windows and powershell, so if you need more info, please describe how to obtain it in details.

**Comment by DarwinJS** [comment]
I have found that on Nano you must grant the special privileges for LogonAsAService (even though this technically should not be necessary) and I receive the same error you did when that is not done.

Here is a dockerfile I have been playing with that calls the same install script from the chocolatey package - it seems to install fine - including granting the appropriate privileges - but I have not had a chance to completely test the end result.

https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/Dockerfile

**Comment by DarwinJS** [comment]
Your "start-service sshd" command above does not look like it is a remoted prompt into a Nano machine?

**Comment by mikhirev** [comment]
> Your "start-service sshd" command above does not look like it is a remoted prompt into a Nano machine?

It is `docker run -i mytestimage powershell`. I also tried to enable sshd service similar to ssh-agent in dockerfile, but it does not start anyway.

**Comment by DarwinJS** [comment]
Yes - I believe the docker file I referenced will get you around the service not starting as it grants it appropriate permissions.

**Comment by mikhirev** [comment]
> Yes - I believe the docker file I referenced will get you around the service not starting as it grants it appropriate permissions.

Yes, you are right. Unfortunatly this does not solve the main problem — I still can't login. There's also wrong path to `sftp-server.exe` in `sshd_config`.

I figured out that default user inside containers is not `Administrator` but `ContainerAdministrator`, so I put `authorized_keys` into `/users/containeradministrator/.ssh` and tried running `ssh ContainerAdministrator@<container IP>`. I also tried `ssh 'User Manager\ContainerAdministrator@<container IP>'`. Anyway I get a password prompt.

**Comment by manojampalam** [comment]
Are you still seeing this issue?

**Comment by erik-am** [comment]
@mikhirev I'm facing the same issue. In my container I ran `sshd -d` and increased the log level to find the following log information:

```
debug1: userauth-request for user ContainerAdministrator service ssh-connection method none
debug1: attempt 0 failures 0
debug1: NetUserGetInfo() failed with error: 2221 for user: ContainerAdministrator and domain: (null)

DsGetDcNameW() failed with error: 1355

Invalid user ContainerAdministrator from 10.3.52.61 port 3192
Failed none for invalid user ContainerAdministrator from 10.3.52.61 port 3192 ssh2
debug1: userauth-request for user ContainerAdministrator service ssh-connection method publickey
debug1: attempt 1 failures 0
Failed publickey for invalid user ContainerAdministrator from 10.3.52.61 port 3192 ssh2
```

So it cannot find user ContainerAdministrator. 😞  (Same happens when I try to login as `User Manager\ContainerAdministrator`.)

@DarwinJS I tried to do `./AddAccountToLogonAsAService.ps1 ContainerAdministrator` but it says "Account already in Logon as a Service", so that's not the issue.

**Comment by erik-am** [comment]
The error `DsGetDcNameW() failed with error: 1355` leads me to believe that it's looking for the Domain Controller... though we're dealing with a local user, not a domain user!

**Comment by manojampalam** [comment]
As mentioned in #553 domain lookup is done if the local lookup fails. 
AFAIK, ContainerAdministrator is a special virtual account (and we don't support virtual account logons yet over network).

You can create a new (Windows) user account on your container and use it for ssh remote access.

**Comment by erik-am** [comment]
@manojampalam You're right. What I tried now is to use the "Administrator" account in the Docker container, which is not virtual. I copied the public key to `C:\Users\Administrator\.ssh\authorized_keys`.

I no longer get the domain error, so the user account is found correctly!
I also ran `./AddAccountToLogonAsAService.ps1 Administrator`

Unfortunately I get this error
```
debug1: auth agent did not authorize client Administrator
Failed publickey for Administrator from 10.3.52.61 port 3785 ssh2: RSA SHA256:1KmF/C0iiQIVaYELt5PXJsXBs/mUgYjSm+KK2p4ugrE
```
I'm a bit clueless how to continue troubleshooting. @manojampalam Any suggestions?

(I don't know how to get the logging of the ssh-agent. It's started in the background as a service by the Chocolatey package.)

**Comment by manojampalam** [comment]
ssh-agent logs should be in ssh-agent.log under logs folder where you have your ssh binaries installed. 
It should have a reason why auth failed.

**Comment by erik-am** [comment]
@manojampalam Somehow I don't have a logs folder in `C:\Program Files\OpenSSH-Win64`

**Comment by manojampalam** [comment]
Go ahead and create one. See if it works.

**Comment by erik-am** [comment]
@manojampalam Thanks, creating the `logs` folder manually did the trick. Now I have the following log entries in ssh-agent.log:

```
7724 09:08:26 839 client pid 4348 connected
7724 09:08:26 843 debug1: spawned worker 8116 for agent client pid 4348
8116 09:08:26 880 agent_start pid:8116, dbg:0, child:1, pipe:480
8116 09:08:26 881 debug3: connection io 0000021E9DD7AA60 #bytes:0 state:0
8116 09:08:26 881 debug1: connection 0000021E9DD7AA60 clean up
8116 09:08:26 881 debug1: iocp error: 6 on 0000000000000000 \n
```

What does it mean? I would expect something related to Lsa in the logs, but it's not there.

EDIT: Sometimes I also get "debug1: unable to generate token for user Administrator"

**Comment by DarwinJS** [comment]
@manojampalam - seems odd to place logging data in a subfolder of the binaries folder (on Windows).  Has there been any discussion of making the default more windows compliant?  Like c:\programdata\ssh\logs or something similar?

**Comment by erik-am** [comment]
Did someone else get it working to have a Windows Docker Container and to try to login using pub key authentication? I try to login as the Administrator, but it keeps failing.

I'm in an urgency to get this working, so _anything_ I can do to debug or to give more information, please let me know.

FYI this is the Dockerfile:

```Dockerfile
FROM microsoft/windowsservercore

# Install chocolatey
RUN @powershell -NoProfile -ExecutionPolicy unrestricted -Command "$env:chocolateyUseWindowsCompression = 'false'; (iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))) >$null 2>&1" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin

COPY yourkey.pub C:/Users/Administrator/.ssh/authorized_keys

RUN choco install openssh -y --version 0.0.9.20170308 -params '"/SSHServerFeature"'

# Optional for customized sshd_config:
#COPY sshd_config C:/sshd_config
#RUN copy /Y C:\sshd_config "C:\Program Files\OpenSSH-Win64\sshd_config"

# I copied AddAccountToLogonAsAService.ps1 from the chocolatey package
COPY AddAccountToLogonAsAService.ps1 AddAccountToLogonAsAService.ps1
RUN powershell ./AddAccountToLogonAsAService.ps1 Administrator

EXPOSE 22/tcp

RUN mkdir "C:\Program Files\OpenSSH-Win64\logs"
```

**Comment by DarwinJS** [comment]
Consider using the Dockerfile I published with the package source.

FYI - it has not been tested recently and I don't have time at the moment and understand you are in a hurry.

https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/Dockerfile

**Comment by manojampalam** [comment]
@DarwinJS, we eventually want to move to Windows ETW logging. For now, we are keeping all logging in the same folder to have the flexibility of hosting multiple versions of OpenSSH on the same box.

**Comment by manojampalam** [comment]
@erik-am I'm trying out a docker container now.

**Comment by manojampalam** [comment]
@erik-am Can you make sure you have ssh-lsa.dll installed?
Try this out
del %windir%\system32\ssh-lsa.dll

It should say ACCESS DENIED (as that dll should be loaded by lsass.exe). 
If you dont' see this, they you don't have it installed. To install, run install-sshlsa.ps1 from the release payload (and restart).

**Comment by erik-am** [comment]
@manojampalam Interesting! Indeed I do not get the Access Denied.
It looks like install-sshlsa.ps1 does get called when the Chocolatey package is installed and baked into the image, but maybe if the container is started, LSA is not loaded correctly.
I'll try to run install-sshlsa.ps1 again from a running container... At least we're a step closer. 😃

**Comment by erik-am** [comment]
@manojampalam Meanwhile I verified that `ssh-lsa` is correctly appended to `SYSTEM\CurrentControlSet\Control\Lsa`. I can still delete ssh-lsa.dll which makes it seem that adding `ssh-lsa` to the registry is not enough to load the dll in a Docker environment.

Is there some way we can force the authentication packages to reload in Windows?

**Comment by manojampalam** [comment]
Sorry, lost track of this issue. A machine reboot is needed to load any new registered auth packages

**Comment by erik-am** [comment]
@manojampalam Kind of difficult with a Docker container. 😋 Doing a `docker stop` and `docker start` unfortunately doesn't seem to trigger the same behaviour.

**Comment by manojampalam** [comment]
ssh-lsa.dll has been deprecated and a reboot is no longer required for OpenSSH setup. Try out the latest release.
