### ISSUE TITLE
Issue executing powershell -File filename as non admin

### ISSUE THREAD

**Issue by discodance1** [PowerShell/Win32-OpenSSH#379]
Having issues executing powershell -File filename as non admin user on server using win32-openssh. This successfully works when the user is added to admin user group and also when invoked locally as the same user.
I have verified the powershell execution policy. 

This is the error i get:
powershell.exe -File <filename>
AuthorizationManager check failed.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by manojampalam** [comment]
You may launch powershell directly now. i.e without -File -

**Comment by discodance1** [comment]
I can launch powershell. The problem i am facing is as a non admin user i cam not able to execute powershell scripts

PS C:\> .\test.ps1
.\test.ps1 : AuthorizationManager check failed.
At line:1 char:1
+ .\test.ps1
+ ~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by discodance1** [comment]
This is only happening when i am connected to the windows server where i want to run the powershell script via openssh.

When i login to the server as the non admin user i am able to execute the same powershell script without any issue.

**Comment by manojampalam** [comment]
dup #419
