### ISSUE TITLE
man page views

### ISSUE THREAD

**Issue by jungle-boogie** [PowerShell/Win32-OpenSSH#38]
Hello,

Is anyone else having problems viewing man pages with just `man ls` for example?

I see:

    jungle@host[18:06] ~ % man ls
    --More--(byte 2508)

No contents of the manual entry actually appear for the desired page.

My normal shell is zsh but I have also changed to sh with the same results.

Thanks!

**Comment by nachfuellbar** [comment]
No problem with my setup
Used cmd and powershell to connect to SLES11 Server with OpenSSH 5.1 and bash+sh as shells

**Comment by jungle-boogie** [comment]
Hi @nachfuellbar,

What windows ssh client version are you using? I'm using the one from this month: 11_09_2015

    % ssh -V
    OpenSSH_7.1p1, OpenSSL 1.0.1p-freebsd 9 Jul 2015


Thanks!

**Comment by nachfuellbar** [comment]
@jungle-boogie i'm using the same binary download
no source build version

**Comment by jungle-boogie** [comment]
Hi @nachfuellbar,

I cleaned up my `.zshrc` and it works now. I had a duplicate path in my file:
`PROMPT="[%n@%m %~]%# "`.

Interestingly this only showed up with powershell SSH.
