### ISSUE TITLE
Documentation On Setting Up Users for SSH

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#381]
Some special procedures for pushing keys are mentioned here: https://github.com/PowerShell/Win32-OpenSSH/issues/341

Since this procedure requires use of a password the first time, I am assuming a windows user must be created.

It will be easy, especially for Nano, for people to assume they can simply create a folder with the user's name and drop the keys in. (yep, I tried that ;)

However, if a proper userid creation is done, followed by a logon and Windows profile creation, Windows may create a new profile folder for that user because it finds the folder name with the user id is taken.

It is unclear is SSH searches the registry to find user => home directory mapping or if it will assume <Userprofileroot>\userid (which would not be what windows thinks if the above scenario happens.

It would be great to have a guide on how to setup users - with special attention to systems where the only reason to setup a user is for SSH access.

It would be great if this guide included powershell code for user creation since that's the only way to create a full on windows user on core and Nano.

**Comment by friism** [comment]
@DarwinJS I just encountered this problem too. Is there any way to activate a user so that you don't have to login with password first, but can start using publickey auth right off the bat?

**Comment by DarwinJS** [comment]
@friism - I have not actually tested any of my conjecture in the first post of this issue.

I was hoping for a statement from the Dev team (@manojampalam) on this ticket as to what SSH expects when the first (and possibly only) reason someone is creating a user is so they can use SSH.

I do know that proper user creation creates many of the necessary objects, but that the user profile folder creation does not happen until the first windows logon.

I also don't know if the very first user logon is via SSH - does SSH trigger the normal user profile creation - or do something else.

**Comment by friism** [comment]
@DarwinJS I got it mostly working, except for the first password to login: https://github.com/friism/ec2-windows-packer-ssh

**Comment by manojampalam** [comment]
related to #478

**Comment by friism** [comment]
I have fully password-less SSH working on EC2 now: https://github.com/friism/ec2-windows-packer-ssh

**Comment by maertendMSFT** [comment]
OpenSSH works the same as any other user creation in Windows.  If more info is needed, please submit a issue on the docs page: https://docs.microsoft.com/windows-server/administration/openssh/openssh_overview
