### ISSUE TITLE
Release v0.0.2.0: High CPU consumption by ssh.exe in open SSH session 

### ISSUE THREAD

**Issue by pseudovector** [PowerShell/Win32-OpenSSH#385]
Hi,
After I upgraded my win32-openssh to v0.0.2.0, the ssh.exe and the conhost.exe comsume a lot of (about 10% each) CPU cycles constantly during open SSH sessions to my android devices and my windows PC (running win32-openssh server).
This happens every time.

![capture](https://cloud.githubusercontent.com/assets/15955186/19712065/43be919e-9b6d-11e6-81ed-1ef4267b7e9e.PNG)

**Comment by pseudovector** [comment]
Anybody experienced the same issue?

**Comment by manojampalam** [comment]
Yes, current console read code does a busy loop for reading console input. This is the reason behind CPU  usage. @rayhayes is looking into better options.

**Comment by hashhar** [comment]
I have the same issue but with sshd.exe. I start it as a service and it constantly uses 30% of CPU.

**Comment by manojampalam** [comment]
@hashhar please reopen a new issue if you still see the issue with sshd.exe

**Comment by hashhar** [comment]
@manojampalam Both the issues are now fixed. It seems to have a CPU spike when the service is just started and just before connecting, but that seems consistent with what I've seen with openssh on linux. Thanks.
