### ISSUE TITLE
Release v0.0.2.0: Can not scroll back to see previous console output

### ISSUE THREAD

**Issue by pseudovector** [PowerShell/Win32-OpenSSH#386]
Can not scroll back to see previous console output after v0.0.1.0.

Happens in either powershell and cmd.

![capture](https://cloud.githubusercontent.com/assets/15955186/19712397/fd7b7082-9b6f-11e6-97e9-d1c0891da5ae.PNG)

**Comment by manojampalam** [comment]
Console reset is needed to maintain it in sync with server side PTY. 

You don't see this happen if a TTY/PTY is not requested. i.e when you do this.
ssh user@target cmd.exe

**Comment by bagajjal** [comment]
This is fixed if you are using the windows 10.
For more information please go through https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH
