### ISSUE TITLE
When you connect with an IPv6 address, it is displayed bad address to sshd.log.

### ISSUE THREAD

**Issue by x9f5yjkq** [PowerShell/Win32-OpenSSH#391]
When you connect with IPv6 address, you will see a bad address to sshd.log.

Also, if you set the AllowUsers user @ IPv6 address in sshd_config, it does not function properly.

IPv6 addresses or would not support?

**Comment by bagajjal** [comment]
Closing this as it is working in the latest release.

**Comment by bagajjal** [comment]
In the latest release, IPV6 and allow users are working fine..

**Comment by x9f5yjkq** [comment]
Hello.
It surely operates normally in the IPv6 environment.
However, in sshd.log, the source IPv6 address is not displayed properly.

Example: sshd.log
5464 10:18:47 463 error: getsockname failed: Bad address
5464 10:18:47 463 Connection from 2001:df0:266:108:: port 50786 on UNKNOWN port 0


The IPv6 address of the connection source is as follows.
2001:df0:266:108:0:dddd:c60:f8d5

However, sshd.log shows only 2001: df 0: 266: 108 ::.
Moreover, an error "error: getsockname failed: Bad address" has also occurred.

**Comment by joeyaiello** [comment]
I'm hitting the same thing in sshd.log (both the `Bad address` error and the malformed/incomplete IPv6 address). 

Note the connection works just fine.

**Comment by x9f5yjkq** [comment]
Thank you.
I understand that IPv6 can be connected with the current version, and it is already in operation.
I'd like you to output the full IPv6 address to sshd.log, so I am waiting for program modification.

**Comment by bagajjal** [comment]
Its fixed, please check the latest release..

Here is the sshd.log message,
36464 17:46:20:474 Connection from 2001:4898:e0:69:c567:fecb:2093:798f port 62742 on 2001:4898:e0:69:95ce:cc02:bbad:38bd port 22

**Comment by x9f5yjkq** [comment]
Hi.

Thanks for reply.
I could confirm it too.
