### ISSUE TITLE
Cannot initialize session when enable ForceCommand attribute in sshd_config

### ISSUE THREAD

**Issue by huytrann** [PowerShell/Win32-OpenSSH#392]
When I enable ForceCommand attribute in sshd_config to run a simple bat file and login the server with putty, the session can't be initialized. However the bat file still executed.

ForceCommand C:/test.bat

Inside test.bat, I just put a simple command mkdir C:\testfolder

Best regards,

**Comment by manojampalam** [comment]
Needs to be investigated why force command isn't working. ForceCommand is picked up in do_exec in session.c

**Comment by arif-pragmasys** [comment]
Does your script test.bat have only 1 line in it? try putting cmd.exe at the last line of the script.
Explanations: 
Looking more into the documentation, the default behavior of ForceCommand is to execute the script given as argument, then close the session. Tested it in Linux open-ssh. So if you want to let the user continue after the script is executed, a shell has to be launched in the script file itself, with something like this:
$SHELL -l

People use this feature to add additional layers of security where the script will verify some info before giving the user a shell. Please see here for more detail: http://dant.net.ru/calomel/openssh.html

On windows, I used cmd.exe in the script and it gave me a shell after executing the script content. Here is my sample script:

mkdir C:\testfolder
cmd.exe

**Comment by huytrann** [comment]
what is the shell it give you, Windows CMD or OpenSSH?

The script was still executed but after that no openssh session given to me.

**Comment by megamorf** [comment]
@huytrann He means that you need to add either cmd or powershell at the end of your bat file to have a shell session after the script has finished. The SSH session will simply be closed after executing the script if you don't invoke your Windows shell of choice at the end.

**Comment by manojampalam** [comment]
Reopen if needed.
