### ISSUE TITLE
ssh.exe quits immediately after startup with no output

### ISSUE THREAD

**Issue by jkodroff** [PowerShell/Win32-OpenSSH#394]
When I run ssh.exe, it quits immediately upon startup with no error message.

- I installed using the Chocolatey package.
- I'm running Windows 8.1 Pro.
- It's broken in both PowerShell and cmd and displays error text in neither shell.

Here's the output:
```
C:\Users\jkodroff> ssh
C:\Users\jkodroff> which ssh
C:\Program Files\OpenSSH-Win64\ssh.EXE
C:\Users\jkodroff> ssh
C:\Users\jkodroff> $lastexitcode
1
C:\Users\jkodroff>
```

Please let me know if there's any additional info I can provide.

**Comment by JamieRRobillardSr** [comment]
you need to specify the name of the server you want to connect to.

**Comment by joeyaiello** [comment]
@JamieRRobillardSr yeah, but expected output is still:

```
C:\WINDOWS\system32> ssh
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-L address] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port]
           [-Q cipher | cipher-auth | mac | kex | key]
           [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
```

**Comment by manojampalam** [comment]
@joeyaiello were you able to repro it on your end?

**Comment by jkodroff** [comment]
Also, a message indicating which argument is missing or invalid would be helpful (but I understand if that's not possible b/c of compatibility with the *nix version of OpenSSH).

**Comment by arif-pragmasys** [comment]
Is this still happening with latest?

**Comment by manojampalam** [comment]
Doesn't reproduce on the latest version (0.0.6.0)
