### ISSUE TITLE
Wild card does not work.

### ISSUE THREAD

**Issue by x9f5yjkq** [PowerShell/Win32-OpenSSH#398]
mget did not work command, the mput command.
You will not be able to send and receive multiple files with wildcards?

[Example]
-------------------------------------------------
sftp> lls
2016/11/07  18:16    <DIR>          .
2016/11/07  18:16    <DIR>          ..
2016/10/24  18:18                23 ftp_file1.txt
2016/10/24  18:18                23 ftp_file2.txt
2016/10/24  18:18                23 ftp_file3.txt

sftp> mput ftp*
Match pattern not implemented on Win32.
File "ftp*" not found.

sftp> put ftp*
Match pattern not implemented on Win32.
File "ftp*" not found.
-------------------------------------------------

**Comment by bagajjal** [comment]
Thanks for opening an issue. This is a known issue. We will plan and fix this is coming releases.

**Comment by manojampalam** [comment]
Fixed in milestone release
