### ISSUE TITLE
Error running setup-ssh-lsa.cmd

### ISSUE THREAD

**Issue by markagarcia** [PowerShell/Win32-OpenSSH#40]
I have a systems running Windows 2012 R2. When i try to run "setup-ssh-lsa.cmd" I received an error about the script not being able to find a file. I was able to fix this by running "copy "C:\Program Files\OpenSSH-Win32\x64\ssh-lsa.dll" "C:\Windows\system32\"". I know that this is a hack, but what the hell, it worked. I checked and the Reg key was created, so, all should be good. Well, not so much. When i try to start ssh outside the directory where the binary is, it get an error, when i change into the directory i get a different error, finally if i call it using what i call "Linux style", it works. Example below: 

PS C:\> ssh
ssh : The term 'ssh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.
At line:1 char:1
+ ssh
+ ~~~
    + CategoryInfo          : ObjectNotFound: (ssh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\> cd 'C:\Program Files\OpenSSH-Win32'
PS C:\Program Files\OpenSSH-Win32> ssh
ssh : The term 'ssh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.
At line:1 char:1
+ ssh
+ ~~~
    + CategoryInfo          : ObjectNotFound: (ssh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Suggestion [3,General]: The command ssh was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If yo
u trust this command, instead type ".\ssh". See "get-help about_Command_Precedence" for more details.

PS C:\Program Files\OpenSSH-Win32> .\ssh.exe
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-L address] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port]
           [-Q cipher | cipher-auth | mac | kex | key]
           [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]

I was able to install and get the expected behavior on my Windows 2008 R2 box. Is this a Windows 2012 issue? It is almost as if the .DLL is not registering the path of the application correctly.

**Comment by nachfuellbar** [comment]
Hello @markagarcia 
did you add "C:\Program Files\OpenSSH-Win32" to your PATH enviroment?
Without this your powershell ( won't find the executables (because it doesn't know where to search)

**Comment by markagarcia** [comment]
So i added it to the path to my system variable and it worked. 

However, when i installed this on my Windows 2008 R2 machine i did not (manually) add the path but it still worked. This may just be how 2012 R2 handles things a bit differently that Windows 2008 R2 and if that is the case great, i now know.

Thanks for the help.

**Comment by nachfuellbar** [comment]
I think ssh executables will placed in C:\Windows\system32 (on 32 Bit systems) or C:\Windows\SysWOW64 when they create a installer
If so adding directories to Path enviroment will be unnecessary

Anyways i'm glad i could help

**Comment by quamrulmina** [comment]
Future installer will add a path to Path environment variable where all ssh binaries are located.
