### ISSUE TITLE
sshd dynamic port forwarding doesn't work

### ISSUE THREAD

**Issue by ekos2001** [PowerShell/Win32-OpenSSH#401]
Does dynamic port forwarding implemented in sshd?

**Comment by zyrill** [comment]
Yes, you can use dynamic port forwarding. I've tried it and it works, running on Win Server 2012 R2.

**Comment by ekos2001** [comment]
It doesn't work for me for some reasons
Here is my setup:
sshd started on Windows 10, firewall is disabled
ssh started on different Windows 10 PC with following command line: 
ssh -D 1080 user@host
Firefox set up to use socks5 proxy localhost:1080
When I try to use firefox, following appears in ssh console:
getsockname failed: Bad address
channel 2: open failed: unknown channel type:

If I connect to another ssh server with the similar command line, everything is working. ssh still sending to console "getsockname failed: Bad address" but not "channel 2: open failed: unknown channel type:"

Also I tried to enable LogLevel DEBUG3 in sshd_config, but can't see any messages related to this
What is the best way to diagnose it?

Thanks

**Comment by ekos2001** [comment]
Any ideas?

**Comment by ekos2001** [comment]
@zyrill, what is your full setup? socks port, browser?

**Comment by maertendMSFT** [comment]
@ekos2001 please let us know if this is still an issue.
