### ISSUE TITLE
"unable to open service handle"

### ISSUE THREAD

**Issue by pheebcodes** [PowerShell/Win32-OpenSSH#403]
On starting Powershell (with standard user and admin) I'm getting the following printed out.

```
unable to open service handle
Could not open a connection to your authentication agent.
```

Windows 10
Chocolatey v0.10.3
OpenSSH_7.1p1 Microsoft_Win32_port_with_VS Nov  6 2016, OpenSSL 1.0.2d 9 Jul 2015

**Comment by pheebcodes** [comment]
D'oh. Easy fix. Removed `posh-git` from my `Documents\WindowsPowerShell\Modules` folder.

**Comment by brizzock** [comment]
>choco uninstall poshgit -y 

this fixed my problem too. i closed/opened console and reinstalled poshgit and no more problems. i still don't understand the problem but THANK YOU. i would have probably blown away my whole dev workstation if that had persisted.
