### ISSUE TITLE
v0.0.3.0  scp fails

### ISSUE THREAD

**Issue by dougransom** [PowerShell/Win32-OpenSSH#404]
c:\Program Files\OpenSSH>.\scp.exe install-sshd.ps1 blue
'cp' is not recognized as an internal or external command,
operable program or batch file.

**Comment by bingbing8** [comment]
This issue is duplicate with issue 340 when copy files locally on windows, it trying to find the path of cp while we should use copy command.

**Comment by bingbing8** [comment]
not duplicate but fix in the same PR

**Comment by bingbing8** [comment]
This is fixed in the latest release
