### ISSUE TITLE
ssh-agent: unable to open service handle

### ISSUE THREAD

**Issue by jkodroff** [PowerShell/Win32-OpenSSH#406]
When I run ssh-agent, I get the following output:

```
unable to open service handle
```

Some debugging info:

- Windows 8.1
- Installed via the Chcolatey package (0.3.0)

Please let me know if there's additional steps to take.

**Comment by manojampalam** [comment]
Did you install sshd and ssh-agent services? See https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by jkodroff** [comment]
I don't understand why sshd would need to be installed as a service if I'm only making outgoing connections.

Also, assuming that there's no need for command line output compatibility, it would be helpful to have a hint for this in the ssh-agent output.

**Comment by manojampalam** [comment]
ssh-agent is implemented as an OS service in Windows. Its needed both on client and server side.
