### ISSUE TITLE
sftp-server path in sshd_config

### ISSUE THREAD

**Issue by frostius** [PowerShell/Win32-OpenSSH#407]
If installation is to a path other than default, the sftp-server path in the sshd_config is incorrect.  At minimum, the install guide should be updated to reflect this

**Comment by DarwinJS** [comment]
@mfrost66 - I am interested in the scenario where you need to install outside of the defaults - because if you install outside of Program files - especially on desktop OSes - you lose a lot of built-in malware protections.

**Comment by frostius** [comment]
many laptops have very small primary SSDs.  3rd party tools can easily
consume this space, so I install most apps to a separate drive as a matter
course

hard-coding paths is wrong for so many reasons its difficult for me to
imagine any reasonable justification

**Comment by DarwinJS** [comment]
Well I can't speak for the dev team - but this is a pre-release software that does not have an installer supported by the team yet.  So defaulting files in the zip to the location advised in the installation documentation means it just works out of the box for anyone who wishes to use the default configuration.

I'm sure once they get a full blown installer that allows choosing the install folder, it will update any other locations that need to point to the install folder using the logic built into the installer.

**Comment by frostius** [comment]
No doubt - its going to be awesome!  Imagine even how much more awesomer it
would be if the marketing dept would add a 2nd intern!  Open source ALL THE
WAY BABY!!!!

**Comment by manojampalam** [comment]
see https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.2.0
relative sub-system paths. Relative Sub-system executables can now be picked up from installation root. Ex the following in sshd_config would work for sftp: 
◦SFTP sftp-server.exe //sftp-server.exe will be picked up from sshd.exe installation path

**Comment by manojampalam** [comment]
sshd_config in latest payload is modified to reflect this change
SFTP sftp-server.exe
