### ISSUE TITLE
Scp destination path is screwed.

### ISSUE THREAD

**Issue by codersam** [PowerShell/Win32-OpenSSH#410]
I'm trying to upload files from [Bamboo's](https://www.atlassian.com/software/bamboo) [SCP task](https://confluence.atlassian.com/bamboo/using-the-scp-task-in-bamboo-305759795.html) to Windows Server 2012 R2 Standard Edition (run in Amazon t2.micro instance).

**But files get saved under wrong names.**

_For example:_
I configure Bamboo's SCP task to upload file  `api.war` into folder `deploy` as a user  `buser@my-server.com` (via public key put into authorized_keys).
Which I **expect** to find later on the server at the path `C:\Users\buser\deploy\api.war`
But **instead** I find it at the following path: `C:\Users\buser\'deploy'`

So it seems that it handles the single quotes in the destination path parameter the wrong way.

Kind regards,
Alex

P.S. I used https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.3.0
OpenSSH-Win64.zip

**Comment by tbxy09** [comment]
I got the path issue too while I try to upload the file to git server using git push command, always return a path with the quotes in its error message
 #400

**Comment by bingbing8** [comment]
this issue is not repro on the latest build. please try it again on next release and reopen it if it still repros.

**Comment by dangrussell** [comment]
I was able to create a work-around for this by first creating a folder on the Windows side that literally has the single-quotes already in it, In your case, making a folder named `'deploy'` in `C:\Users\buser\`
