### ISSUE TITLE
ncurses madness

### ISSUE THREAD

**Issue by zachross90210** [PowerShell/Win32-OpenSSH#411]
![017298039a7526e9426b101d9114ec14](https://cloud.githubusercontent.com/assets/2589828/20465882/93664a9a-af70-11e6-8621-1a1080dfe620.gif)

**Comment by fpqc** [comment]
@zadjii-msft I assume you're keeping in contact with the powershell openssh team?  This is like your bread and butter!

**Comment by fpqc** [comment]
Also, to get even this far, I had to export TERM=xterm on my remote shell.

**Comment by zadjii-msft** [comment]
I can't say I've seen anything like this before, or really have any experience with the ssh.exe project.

Someone want to give me some more context?

**Comment by fpqc** [comment]
@zadjii-msft This is logging into a remote linux box with Win32-openssh (still present in 0.0.4.0).  If you then try to run `htop`, it cannot detect your TERM environment.  If you then forcibly `export TERM=xterm`, and try to run `htop`, you get this crazy mess. 

I think the openssh guys need to discuss enabling vt emulation or come up with a Windows-conhost terminfo file.  Either way, it's definitely something that needs to involve the console team, I think.

**Comment by bagajjal** [comment]
This is fixed for the windows 10 users (by using windows 10 conhost support).
please go through the wiki for more information,
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH
