### ISSUE TITLE
Following unittests fail/crash on Windows

### ISSUE THREAD

**Issue by manojampalam** [PowerShell/Win32-OpenSSH#412]
The following tests are enabled, but some part of the tests are disabled with WIN32_FIXME and need to fix
##unittest-hostkeys.exe
### regress/unittests/hostkeys/test_iterate.c
1. line 66
		ASSERT_SIZE_T_LT(ctx->i, ctx->nexpected);
### regress/unittests/sshkey/test_file.c
1. All tests about "parse XXX from new-format w/ passphrase"
2. All tests "parse Ed25519 XXXX"
### regress/unittests/sshkey/test_fuzz.c
1. All tests about "fuzz Ed25519 XXXX"
### regress/unittests/sshkey/test_sshkey.c
1. All tests about "ED25519"
### regress/unittests/utf8/tests.c
1. SetLocale does not take urf8 in the argument
2. Following tests are failing:
  	one("esc", "\033x", -2, -2, -2, "\\033x");
  	one("inv_badbyte", "\377x", -2, -2, -2, "\\377x");
  	one("inv_nocont", "\341x", -2, -2, -2, "\\341x");
  	one("inv_nolead", "a\200b", -2, -2, -2, "a\\200b");
   	one("sz_esc", "123456789012\033", -2, -2, 16, "123456789012"); 
  	one("double_fit", "a\343\201\201", 3, 3, 4, "a\343\201\201");
  	one("double_spc", "a\343\201\201", 4, 3, 4, "a\343\201\201");

**Comment by bingbing8** [comment]
All tests are fixed except those in utf8.
