### ISSUE TITLE
Invalid ECDSA key length for valid key length

### ISSUE THREAD

**Issue by prashcr** [PowerShell/Win32-OpenSSH#413]
I'm not sure what's wrong here...
  
```
λ ssh-keygen -t ecdsa -b 521
Invalid ECDSA key length - valid lengths are 256, 384 or 521 bits
```

**Comment by arif-pragmasys** [comment]
Since win32 openssh is not compiled/linked with nistP521 feature, current build does not support 521 bit ecdsa keys. The error message has been modified based on whether nistP521 is supported.

**Comment by prashcr** [comment]
If the error message has been modified, it'd be great if someone could link the commit and then this issue can be closed.
