### ISSUE TITLE
SSH_AUTH_SOCK to GPG4Win's gpg-agent not recognized

### ISSUE THREAD

**Issue by wsargent** [PowerShell/Win32-OpenSSH#415]
I installed openssh 0.3.0 though chocolatey on Windows 10 Home.

I installed GPG4Win 2.3.3 and started a gpg-agent.

I open up a Windows Command prompt and added the following

```
set SSH_AUTH_SOCK="C:\Users\wsargent\AppData\Roaming\gnupg\S.gpg-agent.ssh" 
```

But the openssh client did not recognize it:

```
ssh-add -L
Could not open a connection to your authentication agent.
```

More details in the gist: https://gist.github.com/wsargent/072319c2100ac0aea4305d6f6eeacc08#using-gpg-agent-instead-of-ssh-agent

**Comment by manojampalam** [comment]
Due to security considerations, ssh-agent works a bit differently in Windows. Please see "Privilege Separation and Security model in Windows" in https://github.com/PowerShell/Win32-OpenSSH/wiki/About%20Win32%20OpenSSH%20and%20Design%20Details
