### ISSUE TITLE
unable to execute powershell scripts as non admin

### ISSUE THREAD

**Issue by discodance1** [PowerShell/Win32-OpenSSH#419]
PS C:\> .\test.ps1
.\test.ps1 : AuthorizationManager check failed.
At line:1 char:1
+ .\test.ps1
+ ~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

This works when i run the command directly using powershell -Command get-command

**Comment by discodance1** [comment]
This is only happening when i am connected to the windows server where i want to run the powershell script via openssh.

When i login to the server as the non admin user i am able to execute the same powershell script without any issue.

**Comment by discodance1** [comment]
Any help or pointers ?

**Comment by discodance1** [comment]
doing more tshooting with procmon:
I see that when running powershell script as non admin user i get ACCESS DENIED on this registry key:
hklm\software\microsoft\WBEM\CIMOM

**Comment by discodance1** [comment]
Any help looks like it is trying to run this command as non admin:

C:\Program Files\OpenSSH\ssh-shellhost.exe -nopty powershell.exe -File C:\test.ps1. Does ssh-shellhost.exe only works as admin user?

**Comment by discodance1** [comment]
also when i try to run the above command manually in cmd i don't see any output in cmd.

**Comment by manojampalam** [comment]
Thanks for the details. Here's what I can iner:
Remote ssh sessions are network logons. The specific resource hklm\software\microsoft\WBEM\CIMOM might be blocking access to network non-admins. If so you'll need to adjust ACLs on the resource.

**Comment by discodance1** [comment]
I am still seeing the issue, even though i have provided this non admin acl access to this registry. Looks like hklm\software\microsoft\wbem\cimom is related to logging. I have provided acl access for the non admin to this resource and i no longer get ACCESS DENIED in the proc mon logs but running powershell scripts is still blocked over ssh as a non admin.

1. I have verified that this non admin account has file level acls on that file.
2. non admin is able to execute the powershell script when logged in on that server.
3. when the non admin is added to the administrators group, over ssh it is able to execute powershell scripts.
4. Powershell execution policy is set to remote signed for the local machine.

Is there anything else you think i should check?

**Comment by fpqc** [comment]
@manojampalam The problem is that right now Windows lacks anything like `sudo` on Linux.  So any user with admin credentials will have all actions performed with the full privileges rather than the limited ones performed before doing UAC.  I mentioned this on Twitter on the announcement of 0.0.4.0.

The console team says they're looking at implementing a Windows version of sudo.  You should keep in contact with their PM, since they are reworking a lot of this stuff.

**Comment by manojampalam** [comment]
@discodance1 is the issue specific to your test script, or is it that your non-admin is unable to execute any script?

@fpqc agree with your obsevations and will check with console team. But otherwise, the implementation of ssh for Windows is consistent with security model of other Windows services. You get remote logons (with full admin privileges).

**Comment by discodance1** [comment]
@manojampalam issue is that a non admin account is not able to execute any powershell script when connected via win32-openssh.

**Comment by PaulHigin** [comment]
@discodance1 I have not been able to repro this.  Take a closer look at the error record you get.  It should contain an Exception property which should have an InnerException property.  The InnerException will likely provide more detailed information on the error.

**Comment by discodance1** [comment]
@PaulHigin I am sshing from linux server to windows server. Below is the exception i get:

PS C:> .\test.ps1
.\test.ps1 : AuthorizationManager check failed.
At line:1 char:1

.\test.ps1
  + CategoryInfo          : SecurityError: (:) [], PSSecurityException
  + FullyQualifiedErrorId : UnauthorizedAccess

test.ps1 only has one command in it - Get-Command. I can verify that this non admin has access to run this command as this command executes successfully when i run "powershell.exe -Command Get-Command' as the same non admin. Non admin account has acl access to the file 'test.ps1'. How can i tshoot this more ?

**Comment by PaulHigin** [comment]
To examine the error more closely I do the following:
```powershell
PS /> $err = $error[0]                               # Save the most recent error
PS /> $err.Exception                                 # See the exception message
PS /> $err.Exception.GetType()                 # See the exception type
PS /> $err.Exception.InnerException         # See the inner exception (this usually has more info if available)
PS /> $err.Exception.InnerException.InnerException  # Sometimes there are three levels



```

**Comment by discodance1** [comment]
Thanks this is what i get:

PS C:\> $err
.\test.ps1 : AuthorizationManager check failed.
At line:1 char:1
+ .\test.ps1
+ ~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\> $err.Exception
AuthorizationManager check failed.
PS C:\> $err.Exception.GetType()

IsPublic IsSerial Name                                     BaseType                                                                                  
-------- -------- ----                                     --------                                                                                  
True     True     PSSecurityException                      System.Management.Automation.RuntimeException                                             


PS C:\> $err.Exception.InnerException
Access denied

**Comment by megamorf** [comment]
@discodance1 please wrap the command output in 3 backticks like this:

    ```
    your code
    ```

**Comment by PaulHigin** [comment]
It looks like test.ps1 is in a non-accessible location given your credentials.  Try putting test.ps1 in an accessible location like $home.  This works for me:
```powershell
PS C:\> '1..10 | % { "Output $_" }' > $home\test.ps1
PS C:\> & "$home\test.ps1"
Output 1
Output 2
...
```

**Comment by discodance1** [comment]
I have placed the file under the non-admin's user profile C:\Users\<user>\Documents\test.ps1. Also under properties-->security i have made sure the non admin user has full control over test.ps1

```
PS C:\Users\<user>\Documents> & "C:\Users\<user>\Documents\test.ps1"   
& : AuthorizationManager check failed.
At line:1 char:3
+ & "C:\Users\<user>\Documents\test.ps1"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by PaulHigin** [comment]
Did you copy test.ps1 from a remote location?  If so then PowerShell will not run it if ExecutionPolicy is set to "RemoteSigned".  You can either sign it or use Unblock-File on it to indicate that it is trusted.

**Comment by discodance1** [comment]
This file was created locally on the server.

**Comment by PaulHigin** [comment]
In that case I don't know.  I can't repro it.  I can run SSH from Linux (Ubuntu 14) to Windows 10 having latest Win32Open-SSH, using a local non-Admin account, run PowerShell, and create and run scripts in my $home directory.

**Comment by fpqc** [comment]
@PaulHigin By the way, when I connect to the Win32-opensshd on Windows (with Windows Subsystem for Linux's bash.exe and then sshing to localhost) and open powershell, the backspace key, delete key, and arrow keys are broken

![2016-12-08](https://cloud.githubusercontent.com/assets/6083371/21026124/476d027c-bd59-11e6-83cd-e87ebabfd06b.png)
![2016-12-08 1](https://cloud.githubusercontent.com/assets/6083371/21026123/476c898c-bd59-11e6-8eee-40f1c9eaa21f.png)

Does the same thing happen from your Ubuntu box?

Also, is it possible this is because my locale and language settings are set up to UTF-8?

**Comment by PaulHigin** [comment]
@fpqc - Yes I see the same thing.  Please open an issue.

**Comment by discodance1** [comment]
k, i have hit a dead end with this issue with no leads on how to go forward. I have also created a case with microsoft to see if my server has special settings which is preventing execution of powershell script as a non admin but they came back saying they wont support this issue since this is win32-openssh specific.

**Comment by PaulHigin** [comment]
Unfortunately I am not able to repro the problem so cannot investigate it.  You can try clearly summarizing your repro conditions so that someone is able to reproduce the problem.  But I have not been able to see the behavior you describe.

**Comment by freegnu** [comment]
disable write permissions for any user except for admin
pwershell thinks the file is inseure as a user can alter the script to do whatever they want and then you would run it not realizing the script had been changed

**Comment by maertendMSFT** [comment]
We cannot repro this issue, closing.  Please comment if you can repro
