### ISSUE TITLE
Server refused public-key signature despite accepting key!

### ISSUE THREAD

**Issue by juergenr** [PowerShell/Win32-OpenSSH#420]
I followed exactly the instruction from
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH
(ommiting the optional point 6)

Then I generated a keypair with ssh-keygen.exe -t rsa -f id_rsa
Added the public key to the authorized_keys file
Converted the private key to ppk format via Putty Key Generator
Tried Putty and Winscp with Private key file - getting the above error message (in title).

(I used different Windows and Win64-OpenSSH version - no one works)

Has somebody got it to work?
Any help would be highly appreciated!

**Comment by rogue-admin** [comment]
Curious, as we're having the same issue... is the account you're trying to login as a domain account?

**Comment by fpqc** [comment]
If you're trying to login to a domain account, you probably also are required to sign the public key with a trusted domain certificate.

**Comment by juergenr** [comment]
No, its a local account testet on several VMs (with Windows 2012 and Windows 10).
A step-by-step tutorial with every single step would be very nice (including putty/winscp with public key access).

**Comment by fpqc** [comment]
@juergenr Hmmmm.  Are you on Windows 10?

**Comment by juergenr** [comment]
Yes, the client is winscp/putty/ssh on Windows 10.

**Comment by fpqc** [comment]
@juergenr Change the port of sshd to 2222 (in sshd_config), then restart the sshd service with `sc restart sshd`.  Windows 10 has a built in openssh server (maybe it's only active when you're in developer mode?) that will prevent binding port 22.

**Comment by juergenr** [comment]
When I stopped the sshd service on Windows 2012 nothing is listening on port 22 (netstat -a)

**Comment by fpqc** [comment]
@juergenr Oh, the server is on Windows Server 2012.  I thought it was on your local machine.

**Comment by juergenr** [comment]
I've tried all combinations without success

**Comment by manojampalam** [comment]
Server side Logs would help. https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting%20Steps

**Comment by arif-pragmasys** [comment]
Just tried latest ssh Server both on Win10 and Win 2012 server R2 and connected using putty client. RSA key login worked for me. The following instructions to convert openssh key (generated with ssh-keygen) to ppk worked for me.
https://kb.site5.com/shell-access-ssh/how-to-convert-ssh-keys-to-ppk-format/

**Comment by arif-pragmasys** [comment]
WInSCP also seemed to work with the same PPK file against Win32 OpenSSH server.

**Comment by manojampalam** [comment]
Reopen if needed

**Comment by stephenconnolly1** [comment]
Just lost an hour on this one !!
For a domain account, and using putty, you must use the full domain\user@host format when passing in the PVK. for some reason when using password based auth, the server is able to resolve the user domain automatically.

**Comment by stephenconnolly1** [comment]
Also check the account hasn't been locked as that can cause  the same error message.

**Comment by rustyx** [comment]
For a **domain account** you must use the format **DOMAIN\username**. Your key does not have to be signed.
