### ISSUE TITLE
Command execution exit-status is always 0

### ISSUE THREAD

**Issue by JmFixit** [PowerShell/Win32-OpenSSH#421]
Reproducible on 0.0.2.0 to Version 0.0.4.0

When command is executed exit code should be within the exit-status response however starting from 0.0.2.0 to 0.0.4.0 its always 0.
**How to reproduce:**
ssh -v Administrator@WIN_HOST "EXIT 66"
or
ssh -v Administrator@WIN_HOST "cmd.exe /C EXIT 66"
**Expected result:**
Correct 66 ssh command exit status should be reported.
**Actual result:**
0 is reported

ssh log from version 0.0.4.0 when such command is executed:
.........
debug1: client_input_channel_req: channel 0 rtype **exit-status reply 0**
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 3592, received 5248 bytes, in 0.1 seconds
Bytes per second: sent 53405.6, received 78026.9
**debug1: Exit status 0**
.........

Correctly working ssh server on linux log:
ssh -v root@localhost "exit 66"
....
ebug1: Sending command: exit 66
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 1960, received 2096 bytes, in 0.0 seconds
Bytes per second: sent 211484.8, received 226159.2
**debug1: Exit status 66**
...

Note: exit status works correctly on version 0.0.1.0

**Comment by arif-pragmasys** [comment]
When we execute a command like following:
ssh -v -T test1@server "cmd /c exit 2"
on the server side , the following is executed
......\ssh-shellhost.exe -nopty cmd /c exit 2

sshd server is returning the exit code of  'ssh-shellhost.exe' which always happens to be 0. 
We should look into ssh-shellhost.exe so that is propagates the correct exit code of the executed command.

**Comment by rgl** [comment]
any news on this? for doing any kind of remote automation this is essential to have working.

**Comment by manojampalam** [comment]
Fixed in https://github.com/PowerShell/openssh-portable/pull/43. Will be available in next drop.
