### ISSUE TITLE
SFTP directory listing does not use "d" for directories

### ISSUE THREAD

**Issue by martinprikryl** [PowerShell/Win32-OpenSSH#423]
Release v0.0.4.0.

    psftp> ls /C:
    Listing directory /C:/
    -rwxrwxrwx    1          0            8192 Jul  2  2015 Boot
    -r-xr-xr-x    1          0            4096 Sep  9 13:58 Documents and Settings
    -r-xr-xr-x    1          0           24576 Nov 21 15:24 Program Files
    -r-xr-xr-x    1          0           65536 Nov 30 14:48 Program Files (x86)

The very first character should be `d` instead of `-` for directories. With SFTP version 3 (the only supported by OpenSSH), this is the only indication GUI SFTP clients (WinSCP, FileZilla, etc.) can use to distinguish files from folders.

Without the `d` the directories will be presented as files to user, making the GUI SFTP clients unusable:

![listing](https://cloud.githubusercontent.com/assets/1632297/20788664/022f1026-b7b2-11e6-9650-c2b0c8f719a7.png)

---

Interestingly the release v0.0.3.0 had exactly opposite bug. All entries (even files) had `d`.

Release v0.0.2.0 was behaving correctly.

**Comment by bagajjal** [comment]
Thanks for opening an issue. We have identified this issue. It will be fixed in next release.

**Comment by manojampalam** [comment]
Fixed in milestone release
