### ISSUE TITLE
rm <filepattern*> exits the SFTP process

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/Win32-OpenSSH#424]
sftp> dir 1*
 Volume in drive E is abc
 Volume Serial Number is xxxx-yyyy

 Directory of E:\test

12/02/2016  04:27 PM         7,532,544 1.pdb
               1 File(s)      7,532,544 bytes
               0 Dir(s)  164,862,545,920 bytes free
sftp> rm 1*
Match pattern not implemented on Win32.
E:\sftp\test>

**Comment by manojampalam** [comment]
Fixed in milestone release
