### ISSUE TITLE
Service has stopped after some error

### ISSUE THREAD

**Issue by zaufi** [PowerShell/Win32-OpenSSH#426]
I'm trying to control a Vagrant box with Windows 10 and latest OpenSSH inside. Unfortunately, `vagrant` is [not ready for that](https://github.com/mitchellh/vagrant/issues/8080), but for some reason `sshd.exe` being started as a service, has stopped unexpectedly after that actions (mentioned in a referenced bug report).

**Comment by manojampalam** [comment]
Did you check https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting%20Steps ?

**Comment by zaufi** [comment]
@manojampalam, yes I did. I've added `DEBUG` as a log level, but the fault happens when `sshd` is a service, and the host just goes up (by `vagrant up`). Unfortunately there is no `sshd.log` file in the `sshd.exe` directory :(

**Comment by bingbing8** [comment]
Can you please try out the latest version?
If it still doesn't work, can you check if sshd works in debug mode?

In an elevated admin console - sshd.exe -d 
as detailed in wiki

**Comment by manojampalam** [comment]
Reopen if needed.
