### ISSUE TITLE
SSH server fails with public key authentication for local user 

### ISSUE THREAD

**Issue by mochtu** [PowerShell/Win32-OpenSSH#429]
I'm trying to connect from macOS to a Windows Server 2012 R2 with OpenSSH running in version 0.0.4.

I get the following issue from `ssh-agent.txt` when the client is trying to authenticate with a RSA public key. Of course the authorized_keys file exists. It works fine with password authentication.

> agent_start pid:584, dbg:0, child:1, pipe:416
debug2: client type: 3
debug1: process agent request type 100
debug1: trying public key file C:\Users\Administrator/.ssh\authorized_keys
debug1: given public key is not mapped to user Administrator (profile:C:\Users\Administrator)
debug1: iocp error: 109 on 0000007597451290

**Comment by TyrionLanister** [comment]
I'm not able to  connect localhost in windows using public key authentication with latest win32 sshd release.  It also failed with last  release of v0.0.3.0. So it may not be bug at all 
Can any one help with me with issue. There are no other installation of sshd in cygwin.

Logs from sshd.log for command **ssh localhost**

> 8580 06:34:35 514 error: getsockname failed: Bad address
> 8580 06:34:35 723 Postponed publickey for DESKTOP-IQQAVUN\user from :: port 50861 ssh2
> 8580 06:34:35 740 Failed publickey for DESKTOP-IQQAVUN\user from :: port 50861 ssh2: RSA SHA256:mBonigwRKYfjifS4mpr9IHen2GO604peNTE0UFCU0TY


**I didnt type the password so failures from keyboard failures are genuine.**

> 8580 06:34:35 741 Failed keyboard-interactive for DESKTOP-IQQAVUN\user from :: port 50861 ssh2
> 8580 06:34:37 104 Failed password for DESKTOP-IQQAVUN\user from :: port 50861 ssh2
> 8580 06:34:37 104 error: maximum authentication attempts exceeded for DESKTOP-IQQAVUN\user from :: port 50861 ssh2
> 8580 06:34:37 104 Disconnecting: Too many authentication failures

**Comment by TyrionLanister** [comment]
ssh **user@localhost** works for me  with public key authentication but why I cant just  
ssh localhost.
I see that with ssh localhost, the sshd server  sees "**DESKTOP-IQQAVUN/user**" as different account than "**user**"
It's not able to sense hostname of my computer.
so it mistakenly accepts username from ssh localhost command as  "**DESKTOP-IQQAVUN/user**".

If you see at above log for failed  authentication 

> 8580 06:34:37 104 Failed password for **DESKTOP-IQQAVUN\user** from :: port 50861 ssh2

 & log for successfull attempt 

> Accepted publickey for **user** from :: port 50568 ssh2



Can anyone explain it to me @quamrulmina @michaeltlombardi  @manojampalam @arif-pragmasys

How is it possible to add "hostname" into the config file so that ssh localhost works

**Comment by arif-pragmasys** [comment]
@TyrionLanister, it is possible that you might have 2 account by the name 'user', one is local and another is domain account. When you try 'ssh localhost' then the current logged in user is picked up, which is 'DESKTOP-IQQAVUN/user'. But when you try 'ssh user@localhost', you are forcing to ssh to use the local version of the 'user' account. The way current code resolves name is if domain is not mentioned it looks into the local user list.

The way we currently resolving domain user name is having some issue. We use win32 api NetUserGetInfo() to get the sid of the user. But currently this is returning ERROR_ACCESS_DENIED. There could be several reason for that:
1. The name server is not setup properly.
2. We are not using the api properly.
3. 'NT SERVICE\sshd', the user which the sshd service runs as does not have the necessary privileges to call NetUserGetInfo() api.
We are looking into it.

**Comment by mochtu** [comment]
Thanks for hijacking this thread @TyrionLanister. I think you should have opened your own issue…

**Comment by msnelling** [comment]
@mochtu I'm also having issues with public key authentication. Have you made any progress?

**Comment by mochtu** [comment]
@msnelling Not at all. Password authentication is fine, public key fails and the only debug output related to it is the one printed in my initial post. I'm using cygwin and openssh in the meantime, which works as expected with an rsa key.

**Comment by arif-pragmasys** [comment]
For local users, login with password and see what home directory you land on. Make sure you put the .ssh directory and related key files in that directory. Please give this a try if you have not already.

**Comment by msnelling** [comment]
@arif-pragmasys yes I've done this without success.

**Comment by manojampalam** [comment]
@mochtu I'm looking at this issue now. Can you try out the latest version?
Can you check if key based auth works from the same box (over loopback)?
If it does, can you generate DEBUG3 level traces and compare the success Vs failed logs?
If it doesn't, please attach ssh-agent DEBUG3 logs.

**Comment by DarwinJS** [comment]
If you used the chocolatey package to do this install, then the lack of public key auth was likely the fault of the chocolatey package - it was not properly copying the ssh-lsa.dll on new installs.

It is fixed in version 0.0.9.20170308, which as of this moment is still in moderation.  It can be pulled before moderation is complete by specifying the version on your chocolately install or upgrade command line.

**Comment by mochtu** [comment]
@DarwinJS Thank you, it is fixed now for me.
