### ISSUE TITLE
SSHD: the output of some command is empty

### ISSUE THREAD

**Issue by khattori** [PowerShell/Win32-OpenSSH#43]
For instance, the following command
```
$ ssh someuser@somehost cmd.exe /C dir
```
outputs emty result.

The debug log of SSHD:
```
debug1: Executing command: cmd.exe /C dir
debug1: Received SIGCHLD.
debug1: session_by_pid: pid 464
debug1: session_exit_message: session 0 channel 0 pid 464
debug1: session_exit_message: release channel 0
debug1: read from socket sfd [9] failed with error code [10054]
debug1: read from socket sfd [3] failed with error code [10035]
debug1: read from socket sfd [7] failed with error code [10054]
debug1: session_by_channel: session 0 channel 0
debug1: session_close_by_channel: channel 0 child 0
debug1: session_close: session 0 pid 0
debug1: channel 0: free: server-session, nchannels 1
WaitForSingleObject in thread [0] failed with error code [298]
```

**Comment by quamrulmina** [comment]
Please try it with the latest release. "ssh someuser@somehost cmd.exe /C dir" should not produce the directory output of the user's home directory.

**Comment by quamrulmina** [comment]
New releases have fixed the issues. Windows cmd shell commands are to be run using cmd /c command format but other external commands can be run directly without cmd. E.g. all these will work:
ssh someuser@somehost cmd /C dir
ssh someuser@somehost cmd /C set
ssh someuser@somehost hostname
ssh someuser@somehost myprogram.exe
