### ISSUE TITLE
Missing characters in fullscreen console applications like vim

### ISSUE THREAD

**Issue by alexchandel** [PowerShell/Win32-OpenSSH#431]
When connecting to a Windows SSH server, with vim-tux (v8.0.0117) installed on the Windows machine, editing a file with vim that has syntax highlighting results in many random characters not getting displayed. For example, given a file `test.pl` with contents,

```perl
use strict;
use warnings;
```

connecting to the Windows server and immediately running `vim test.pl` results in the semicolons not getting displayed. Attempting to highlight the terminal screen confirms there are actually no semicolons there.

It's not limited to semicolons; testing with other source files has various other characters disappearing, including braces and double-quotes.

Tested with the macOS SSH client.

**EDIT:** still present on latest version, v0.0.4.0

**Comment by bagajjal** [comment]
Please test with the latest release.
For more information go through https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

**Comment by alexchandel** [comment]
Just tested in 0.0.14, this is only partially fixed.

The initial paint is now better, but any changes to the screen quickly corrupt the screen and create missing lines.

For example, in vim, scrolling down or beginning to type causes almost every colored line to disappear or shift position, or move in the wrong direction. I end up with duplicate lines, wrongly placed lines, and 90% missing lines. And occasionally colored lines are missing to begin with.

**Comment by bagajjal** [comment]
Is your ssh client running on windows 10 OS? If not then the console is not good for vim...
If you are using windows 10 OS then set the TERM to xterm before doing ssh.

**Comment by alexchandel** [comment]
My SSH client is macOS (& I've tried it with other unix SSH clients), so the problem is with the windows SSH server.

The vim display is rapidly corrupted when anything changes.

**Comment by biao-w** [comment]
@bagajjal I am experiencing the same issue @alexchandel mentioned above. Basically VIM is unusable from a Mac->Win10 (1803) ssh session. 

I did 'export TERM=xterm' before ssh. Default shell is powershell.
VIM version is: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 23 2017 19:48:19) 

Perhaps you or someone can re- open this issue?

**Comment by alexchandel** [comment]
@bagajjal Please reopen this. I just tested with Win32-OpenSSH 7.7.2.1 and this issue still exists. I tested with and without TERM=xterm, and with multiple terminal emulators. Something is still broken in your code.

**Comment by bagajjal** [comment]
@alexchandel - Are you trying the same scenario (Mac ssh client -> Windows ssh server)?

**Comment by maertendMSFT** [comment]
This is supported in the latest Win 10 and above releases.
