### ISSUE TITLE
Pasting from clipboard to ssh session on any non-windows client fails

### ISSUE THREAD

**Issue by alexchandel** [PowerShell/Win32-OpenSSH#432]
When connected to a Windows ssh server from macOS, in the Terminal app using the macOS ssh client, pasting either with "Cmd+V" or by choosing "Paste" from the "Edit" menu fails, and appears to only paste the first character of the clipboard in.

This extends to all forms of pasting, including dragging a file into the Terminal window to paste its path (which results in a lone `/` getting pasted).

**Comment by trodemaster** [comment]
I'm also seeing this issue on a fresh install of openssh with macOS 10.12.2 . I have tried changing the terminal type to vt100 and still seeing the issue.

**Comment by Azq2** [comment]
Same issue on gnome terminal (ubuntu 14.04) :(

**Comment by tomrittervg** [comment]
I also experience this with a few additions:
 - If I open zsh  =from cmd or powershell after SSH-ing, I experience the problem
 - If I run powershell, then a docker container, and paste into the docker container I get the entire value of the clipboard... except _some_ of the characters get replaced with '?' similar to #300

**Comment by bagajjal** [comment]
Please check in the latest release.. this should be fixed, if not please reopen..
