### ISSUE TITLE
Connecting to win32-sshd powershell from a terminal emulator breaks powershell

### ISSUE THREAD

**Issue by fpqc** [PowerShell/Win32-OpenSSH#434]
When I connect to the Win32-opensshd on Windows (with Windows Subsystem for Linux's bash.exe and then sshing to localhost) and open powershell, the backspace key, delete key, and arrow keys are broken:

![2016-12-08](https://cloud.githubusercontent.com/assets/6083371/21026124/476d027c-bd59-11e6-83cd-e87ebabfd06b.png)
![2016-12-08 1](https://cloud.githubusercontent.com/assets/6083371/21026123/476c898c-bd59-11e6-8eee-40f1c9eaa21f.png)

So I tested it with other terminal emulators (for example: gnome-terminal (TERM=xterm-256color), PuTTY (TERM=putty), a Linux VM's console TTY (TERM=linux)).  

The reason this is broken, in reality, is that Powershell for Windows cannot understand the different kinds of terminfo associated with different terminal emulators.  Incidentally, the Linux and Mac ports of Powershell (6-alpha) are able to understand and decode the control codes of different terminals using the libterminfo project (part of the ncurses project), which is licensed under the MIT/X license (and therefore can be integrated into Microsoft software (opensource or proprietary) as the license is highly permissive).  

I think the answer is to backport this "terminfo-awareness" back to the Windows version of powershell.  This awareness of terminfo should make it so Windows powershell will work properly in a Win32-opensshd session.

@PaulHigin Pinging you (you told me to make a new issue).

Reference:
[Official ncurses/terminfo FAQ](http://invisible-island.net/ncurses/)

**Comment by bagajjal** [comment]
Please test with the latest release.
For more information go through https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

If you still have issues, please open a new issue.

**Comment by fpqc** [comment]
Hey, just wondering how you ended up solving it. I just tested and it seems to work now! (at least when using an xterm-compatible terminal emulator.  I haven't tested in st or rxvt-unicode yet, wondering if you think they will work?

**Comment by bagajjal** [comment]
windows 10 console provides the capability to decode the xterm sequences. so we pass the raw buffer received from the ssh server to the windows console directly.

For more information go through https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

**Comment by fpqc** [comment]
@bagajjal This is the server-side question, and I'm connecting from a Linux machine,and it's working fine in st, xterm, and gnome-terminal.  I haven't tried rxvt yet.  

Edit: Works in rxvt too!
