### ISSUE TITLE
SSH connection restrictions

### ISSUE THREAD

**Issue by iviikel** [PowerShell/Win32-OpenSSH#436]
This is more of a question than an issue...
Is there a way to configure only a single AD user account or group to be able to connect to the server via SSH?
We want to setup a Machine/Service account in Active Directory that will be able to connect to the server via SSH and all other connection requests refused.
With the default configuration I find that I can connect using an AD account that has no privileges to the server (admin or RDP) and modify content.

**Comment by manojampalam** [comment]
Try AllowUsers in sshd_config https://linux.die.net/man/5/sshd_config

**Comment by gd197** [comment]
I'm using the AllowUsers in AD context for only one account and this is working well on my side
