### ISSUE TITLE
ssh from a linux to windows

### ISSUE THREAD

**Issue by rickmoua** [PowerShell/Win32-OpenSSH#44]
Tried ssh from a linux (ubuntu) to the windows server that has the openssh-win32 running, found that it only works if I specify the local admin user of that machine, but not working if specify a domain user. On the windows client, both local user and domain user works.

**Comment by quamrulmina** [comment]
domain users should work with password login. Specify in user@domain@hostname format. E.g. john@windowsdomain@mymachine should work. Public key login now works with local account only but will be fixed in a future release to work with windows domain account also.

**Comment by rickmoua** [comment]
Great that worked. thx
