### ISSUE TITLE
Terminal issues in v0.0.4.0

### ISSUE THREAD

**Issue by dermeister0** [PowerShell/Win32-OpenSSH#440]
Some issues are fixed in #362.

Remaining issues:

**Midnight Commander**
Large terminal size is not supported.

![2016-12-14_1218](https://cloud.githubusercontent.com/assets/4054844/21171517/1a93eb58-c1ff-11e6-9a63-1961e04224d8.png)

**Comment by dermeister0** [comment]
**Far Manager**
Nothing works.

![2016-12-14_1213](https://cloud.githubusercontent.com/assets/4054844/21171579/832ff832-c1ff-11e6-85a7-dbb7aed00d5d.png)

**Comment by bagajjal** [comment]
Please explain what do you mean by "Far Manager Nothing works?"

**Comment by dermeister0** [comment]
I recorded videos.

See how Far Manager works in freeSSHd:
https://www.screencast.com/t/epouO79I

That's how it looks in Win32-OpenSSH v0.0.4:
https://www.screencast.com/t/5s77aSTWAGTm

The same in Win32-OpenSSH v0.0.7:
https://www.screencast.com/t/fVdyzYKf

**Comment by dermeister0** [comment]
I installed Win32-OpenSSH v7.7.1.0p1-Beta to server.

Far Manager is not displayed correctly in OpenSSH client (Windows 10 1803).

![2018-07-19_183001](https://user-images.githubusercontent.com/4054844/42939935-cb2865dc-8b81-11e8-8e81-c0b0ff46ac6f.png)

Similar bugs in Putty.

**Comment by bagajjal** [comment]
Sorry for the long wait to fix this issue. It will be fixed as part of the next windows release.
FYI, We are leveraging the work from console team so have to wait for the next windows release.

**Comment by bagajjal** [comment]
Please try the new windows 10 fall update (https://support.microsoft.com/en-us/help/4464619)

**Comment by bagajjal** [comment]
fyi, Just realized the windows 10 fall update is paused because of some known issues.
Please note that bunch of console rendering issues were resolved in the latest windows 10 fall updates.

**Comment by maertendMSFT** [comment]
Closing per @bagajjal's response.
