### ISSUE TITLE
Error on Upload

### ISSUE THREAD

**Issue by uiucgrad** [PowerShell/Win32-OpenSSH#442]
I am able to login to the server using windows authentication but when I try to upload a files using WinSCP the transfer appears to complete but immediately after it is done I get an error that says: "Connection has been unexpectedly closed. Server sent command exit status 255."

Correspondingly the sftp-server.log that says "4560 14:01:19 110 fatal: process_setstat: buffer error: incomplete message"

I then have to reconnect to the server.  Any idea what may be causing this?

**Comment by manojampalam** [comment]
Windows auth is not supported yet. You probably meant user/pw (or Basic authentication).

**Comment by bagajjal** [comment]
Verified uploading huge file of 7 GB and it worked fine. If the issue mentioned is different then please provide the step by step procedure so that we can reproduce and fix it.
