### ISSUE TITLE
[v0.0.5.0] sshd.log is not output

### ISSUE THREAD

**Issue by x9f5yjkq** [PowerShell/Win32-OpenSSH#443]
Hello.
After upgrading to v.0.0.5.0, sshd.log is not output.

**Comment by manojampalam** [comment]
check in "logs" folder

**Comment by x9f5yjkq** [comment]
Thank you.
But there is no logs folder anywhere.

In the "C: \ Windows \ Logs" folder
Will sshd.log be created under?

I searched for sshd.log on the server, but there was not it.

**Comment by x9f5yjkq** [comment]
I created the "logs" folder manually in the root folder and it was output.

**Comment by manojampalam** [comment]
install-sshd.ps1 should have created it and set the right permissions. No?

**Comment by x9f5yjkq** [comment]
Hello. Thank you for your reply.

I ran the install-sshd.ps1, but the logs folder was not created.

---------------------------------------------------------------------------
PS C:\Windows\system32> d:

PS D:\> cd .\OpenSSH-Win64

PS D:\OpenSSH-Win64> .\install-sshd.ps1
[SC] SetServiceObjectSecurity SUCCESS
[SC] ChangeServiceConfig SUCCESS
 Granting SeAssignPrimaryTokenPrivilege to NT SERVICE\SSHD   ... successful
sshd and ssh-agent services successfully installed

PS D:\OpenSSH-Win64> dir logs
Get-ChildItem : パス 'D:\OpenSSH-Win64\logs' が存在しないため検出できません。
発生場所 行:1 文字:4
+ dir <<<<  logs
    + CategoryInfo          : ObjectNotFound: (D:\OpenSSH-Win64\logs:String) [Get-ChildItem]、ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

PS D:\OpenSSH-Win64>
---------------------------------------------------------------------------

**Comment by manojampalam** [comment]
can you dump contents of install-sshd.ps1?

**Comment by x9f5yjkq** [comment]
Hello. Thank you for your reply.
I'm sorry, I used an old script.
Please close this case.
