### ISSUE TITLE
When is the major release scheduled?

### ISSUE THREAD

**Issue by tak08** [PowerShell/Win32-OpenSSH#445]
Hello. The [RoadMap](https://github.com/PowerShell/Win32-OpenSSH/wiki/Win32-OpenSSH-RoadMap) has not been revised since this October. Could you answer when the major release scheduled and update [RoadMap](https://github.com/PowerShell/Win32-OpenSSH/wiki/Win32-OpenSSH-RoadMap)?

**Comment by manojampalam** [comment]
"RoadMap" link is now obsolete. Please follow https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Status

Our first goal is to integrate back in OpenSSH main repo. We have just started on this and will update the above link on progress as we move forward.

**Comment by DarwinJS** [comment]
@manojampalam - can you elaborate how the Windows releases will work once the code is merged to that repo?  Will that repo contain the windows zip files in their releases?

**Comment by r2690698** [comment]
Yeh , any updates ?

**Comment by manojampalam** [comment]
@DarwinJS I dont think OpenSSH ever hosted binaries for any platform. Windows will be no exception. I should otherwise have an update on - how the official bits will eventually be distributed - by Mid Jan.

**Comment by DarwinJS** [comment]
Ok - so this github repo will continue to be the place to get the compile bits then?

**Comment by seanpoulter** [comment]
I've been keeping an eye on this for quite a while and am excited by the work. It's come up a few times talking to folks about the project -- any guess-estimates when this'll be "production" ready? Thanks!

**Comment by bagajjal** [comment]
We still don't have the time frame  for the production ready code.
We shipped openssh as feature on demand in Windows 10 fall creators update.
We will update the status in #688.

**Comment by seanpoulter** [comment]
Thanks @bagajjal.
