### ISSUE TITLE
ssh no loner working with v 0.0.5.0

### ISSUE THREAD

**Issue by discodance1** [PowerShell/Win32-OpenSSH#447]
ssh -l user@domain hostname 
results in ssh_exchange_identification: Connection closed by remote host

**Comment by manojampalam** [comment]
Please share client and server logs.

**Comment by mathieu68468** [comment]
I have the same issue, the server's logs indicate:

6320 19:17:31 597 debug1: Bind to port 22 on ::.
6320 19:17:31 597 Server listening on :: port 22.
6320 19:17:31 597 debug1: socket:364, io:00000000003E8E60, fd:4 
6320 19:17:31 597 debug1: Bind to port 22 on 0.0.0.0.
6320 19:17:31 597 Server listening on 0.0.0.0 port 22.
6320 19:17:50 875 debug1: socket:376, io:00000000003CDC00, fd:5 
6320 19:17:50 875 debug1: pipe - r-h:380,io:00000000003CDCB0,fd:6  w-h:384,io:00000000003CDD60,fd:7
6320 19:17:50 875 debug1: spawning C:\\Program Files\\OpenSSH\\"C:\\Program Files\\OpenSSH\\sshd.exe"
6320 19:17:50 876 debug1: close - io:00000000003CDC00, type:1, fd:5, table_index:5
6320 19:17:50 876 error: fork: No such file or directory
6320 19:17:50 876 debug1: close - io:00000000003CDD60, type:2, fd:7, table_index:7
6320 19:17:50 877 debug1: ReadFileEx() ERROR:109, io:00000000003CDCB0
6320 19:17:50 877 debug1: close - io:00000000003CDCB0, type:2, fd:6, table_index:6
6320 19:18:50 130 debug1: Native Ctrl+C handler, CtrlType 0
6320 19:18:50 130 debug1: raise sig:0

Sshd is installed on "C:\Program Files\OpenSSH"

**Comment by manojampalam** [comment]
dup #450 
Please check workaround in that issue
