### ISSUE TITLE
I want to start the sshd service with a Windows user account other than "NT SERVICE \ SSHD".

### ISSUE THREAD

**Issue by x9f5yjkq** [PowerShell/Win32-OpenSSH#448]
please tell me.
If you start the service with a user account (eg Administrator) other than "NT SERVICE \ SSHD" or "Local System" sshd service, you can not connect SFTP from the client.
Is it a specification?

----------------------------------------------------------
> sftp user1@Computer
Permission denied (publickey,keyboard-interactive).
Connection closed
----------------------------------------------------------

**Comment by manojampalam** [comment]
You may start sshd directly on command line as any user (Just make sure the user has this privilege - SeAssignPrimaryTokenPrivilege)

**Comment by x9f5yjkq** [comment]
Thank you!
It worked fine.
Close please.
