### ISSUE TITLE
Autocompletion and Character in a ssh session from a linux client to a windows machine

### ISSUE THREAD

**Issue by Pascalao** [PowerShell/Win32-OpenSSH#45]
Hi,

I use a linux client to connect with a windows machine.
--> ssh -l user@domain host
i am connected now with the windows machine.
After there i have a problem. 
If I type a backspace i get unknown characters and if i use the tabulator then i get freespaces and not the autocompletion. How i can fix that? Or can you fix that?

Best regards

**Comment by quamrulmina** [comment]
--For backspace to work from a Linux client, you need to set erase character in the shell your are using "stty erase ^?" command in the shell or your profile. "stty -a" shows all the current setting of the shell terminal. Our sshd server (actually windows shells like cmd ) expects "control h" as the backspace/erase character and not DEL.
--Tab autocompletion will not work in sshd sessions with windows shell (cmd or powershell) and it is a  limitation of the current design.

**Comment by quamrulmina** [comment]
backspace works if the linux/ssh client is set properly. Tab auto-completion not working in sshd sessions with windows shell is a current design limitation.

**Comment by QueenRiver** [comment]
When I type "stty erase ^?"  after I login from a linux/ssh client, I get this message:
stty erase ^?
stty: 'standard input': Inappropriate ioctl for device

Then how to set it up in the profile. Where?
