### ISSUE TITLE
Remote port forwarding not working

### ISSUE THREAD

**Issue by arif-pragmasys** [PowerShell/Win32-OpenSSH#454]
host1 executes:
ssh -R 9001:host1:22 user@host2

host2 executes: 
ssh -p 9001 user@localhost

error in host1: WARNING: Server requests forwarding for unknown listen_port 0
error in host2: ssh_exchange_identification: read: Unknown error

Similar command works for openssh in linux.

**Comment by arif-pragmasys** [comment]
Tried similar command in 3 machine scenario, where forwarding is initiated from M2 to facilitate M1(has user u1) connecting to M3(has user u3).

M2 excutes: ssh -R 9001:M3:22 u1@M1
M1 Excutes: ssh -p 9001 u3@localhost

Getting simliar error.
![untitled](https://cloud.githubusercontent.com/assets/14184782/21412308/ed7cd57e-c7b4-11e6-9033-66c1dc7186b8.png)

**Comment by drodsou** [comment]
Hi arif-pragmasys,

I am assuming all your hosts are Windows.

Could it be a firewall problem?. Be aware that _localhost_ is "my computer seen from the outside", like _0.0.0.0_, affected by firewall rules, while _127.0.0.1_ is "my computer seen from the inside", not affected by firewall rules. So maybe this should work in your first scenario:

_Ihost2 executes:
ssh -p 9001 user@127.0.0.1_

Or you can check  if port 9001 is open in "incoming rules" in the Windows firewall/advanced in Host2, as Win32-OpenSSH installation instructions here on Github only open port 22 by default -also you can shut off all the firewall for a moment and test the tunnels again to verify

Regards

**Comment by manojampalam** [comment]
dup #259

**Comment by djmaze** [comment]
Similar problem here. While local port forwarding (`-L`) works, remote port forwarding (`-R`) does not. I tried with different servers. 

When trying to curl a forwarded http port on the remote machine, curl just outputs:

```
curl: (52) Empty reply from server
```

Here is the verbose output from the ssh client when trying to access the port remotely:

```
debug1: client_input_channel_open: ctype forwarded-tcpip rchan 3 win 2097152 max 32768
debug1: client_request_forwarded_tcpip: listen localhost port 2019, originator 127.0.0.1 port 55096
debug1: getsockopt TCP_NODELAY: Invalid argument
debug1: connect_next: host localhost ([::1]:2019) in progress, fd=7
debug1: channel 1: new [127.0.0.1]
debug1: confirm forwarded-tcpip
debug1: channel 1: connected to localhost port 2019
debug1: channel 1: free: 127.0.0.1, nchannels 2
```

As a workaround, PuTTy is working flawlessly with remote port forwarding on the same machine. So it does not seem to be a firewall problem.
