### ISSUE TITLE
Backspace key delete whole word

### ISSUE THREAD

**Issue by zaufi** [PowerShell/Win32-OpenSSH#458]
Connecting to Windows 10 box w/ Win32-OpenSSH 0.0.4.0 inside I have a strange keyboard behaviour: the backspace key delete a whole word instead of just one last symbol. This is pretty annoying bug causing to retype everything from begin :(

I tried w/ `TERM=xterm`

**Comment by megamorf** [comment]
0.0.5.0 is the latest version.

**Comment by manojampalam** [comment]
@zaufi what is your ssh client? and what are its "term" settings?

**Comment by zaufi** [comment]
openssh-7.4_p1
my default `TERM` is `konsole-256color`, also I tried `xterm` for sure

**Comment by bagajjal** [comment]
issue is identified.. for time being use "Ctrl + H" for backspace..
