### ISSUE TITLE
error: getsockname failed: Filename too long

### ISSUE THREAD

**Issue by Janareddy** [PowerShell/Win32-OpenSSH#459]
Hi All,

I have installed OpenSSH in my windows server 2012 R2. I am getting the errors like this in the log file : 

**error: getsockname failed: Filename too long
error: setsockopt SO_KEEPALIVE: Filename too long**

Did any one face this kind of issue? If so, Could you please help me to clear this issue.

I have googled the error, but could not find proper solution.

Thanks in advance,
Jana

**Comment by bingbing8** [comment]
When do you get this error? when running a command? or during installation? @Janareddy

**Comment by gsoing** [comment]
Hello,

I have the same error when i try to log in with a ssh client.
On the client side i've got connection reset by peer and on the server log i have : 8196 10:03:42 088 error: setsockopt SO_KEEPALIVE: Filename too long

But if i launch sshd with -d option it works.

Regards
--
Guillaume

**Comment by Janareddy** [comment]
@bingbing8  Hi, I have installed successfully. But I am unable to connect using sftp (using filezilla). When I check the log I saw that error. Thanks!

**Comment by manojampalam** [comment]
@Janareddy can you repeat you steps with included sftp client and attach logs?

**Comment by manojampalam** [comment]
Reopen with logs.

**Comment by frederik12345** [comment]
Some people often view Long path tool as spam and not working but I already use it many times and it always work . I have the same problem and only Long path tool helped me. So I would suggest to use it .
