### ISSUE TITLE
ssh.exe fails if ~/.ssh/config exists

### ISSUE THREAD

**Issue by nikatjef** [PowerShell/Win32-OpenSSH#46]
Greetings,

  First, thank you for doing this port.

  If you have a config file in your .ssh directory, ssh.exe will fail with the following message;
    fstat C:\Users\foo/.ssh/config: The operation completed successfully.

  To ensure that the problem was not caused by the contents of my config file I tried it with an empty file which failed with the above output, a mininal version that just contained my user name definition which also failed with the same output, and my normal config using the -F (config file option) which worked correctly.

  I am using the 11_09_2015 build on a 32bit Windows 10 Home tablet with all of the latest patches.

**Comment by nachfuellbar** [comment]
https://github.com/PowerShell/Win32-OpenSSH/issues/23

**Comment by manojampalam** [comment]
Duplicate of #23
