### ISSUE TITLE
AllowGroups does not work

### ISSUE THREAD

**Issue by leyshon** [PowerShell/Win32-OpenSSH#463]
I'm trying to configure AllowGroups to restrict access to only those who are a member of a group. Currently I'm doing this with a local group and it simply doesn't work. I've set it to ```AllowGroups ssh``` and I can login regardless of whether I am a member of this group or not. Expected behavior should be that if you are not a member of this group you are denied login.  DenyGroups similarly blanket blocks all groups.

**Comment by manojampalam** [comment]
This is due to ga_* routines that are not yet implemented for Windows. (openssh-portable\contrib\win32\win32compat\no-ops.c)
