### ISSUE TITLE
global known_hosts is not honored

### ISSUE THREAD

**Issue by ryudice** [PowerShell/Win32-OpenSSH#466]
Is there a global known_hosts file?

**Comment by manojampalam** [comment]
You can have ssh_known_hosts and ssh_known_hosts2 in the directory where ssh.exe resides. But currently there is a restriction that these files will be picked up only when ssh.exe is run from its bin directory. 

i.e if ssh.exe is installed in c:\openssh then you need to do the following:
cd c:\openssh
ssh.exe ....

**Comment by manojampalam** [comment]
A fix for this issue would involve changes to OpenSSH core code, so plan on doing it after the initial integration back into OpenSSH main repo. Currently, the location of these files default to the following in pathnames.h

#define _PATH_SSH_SYSTEM_HOSTFILE	        SSHDIR "/ssh_known_hosts"
#define _PATH_SSH_SYSTEM_HOSTFILE2	SSHDIR "/ssh_known_hosts2"

SSHDIR is currently defined as "." in config.h.vs

A potential way to fix this involves supporting a way to specify module path using a escape sequence (similar to '%d' (local user's home directory), '%u' (local user name)). 
i.e say %z refers to module path and SSHDIR defaults to %z

**Comment by manojampalam** [comment]
This is now supported with 1.0.0.0 release. Place it under %PROGRAMDATA%\ssh
