### ISSUE TITLE
SFTP rename failed

### ISSUE THREAD

**Issue by gregmich29** [PowerShell/Win32-OpenSSH#467]
Sftp server in running on windows 10 (Win32-openSSH 0.0.5.0), on Linux Ubuntu a SSHFS client is used. The sftp rename command failed systematically if the destination file exists ( operation not permitted).
In my opinion, on the sftp sever, the support of the extension posix-rename@openssh.com does not work properly. In fact the handler "process_extended_posix_rename" call a method "rename" mapped on the windows method _wrename. This method is not compatible with the posix implementation, if the destination file exists the method failed.

**Comment by bagajjal** [comment]
Thanks for reporting the bug. The issue is fixed and will be available in the January-Mid milestone.
