### ISSUE TITLE
Windows - SFTP long listing (ls -l) output issues

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/Win32-OpenSSH#468]
1) On windows, long listing (ls -l) output doesn't have the username, group name
-*********    1 -        -           52052 Dec 21 09:56 ntuser.pol
2) The permissions (rwx) are not matching.

From sftp code:-
sftp> cd c:
sftp> ls -lrt
drwxrwxrwx    1 -        -               0 Oct 30  2015 PerfLogs
drwxrwxrwx    1 -        -               0 Nov  3  2015 inetpub
-r--r--r--    1 -        -               0 May  4  2016 OS

From Cygwin:-
bagajjal@balu-d /cygdrive/c
$ ls -lrt
total 36788960
drwxrwx---+ 1 SYSTEM                      SYSTEM                                0 Oct 30  2015 PerfLogs
drwxrwx---+ 1 SYSTEM                      SYSTEM                                0 Nov  3  2015 inetpub
-r-xr-x---+ 1 SYSTEM                      SYSTEM                                0 May  4  2016 OS

**Comment by bingbing8** [comment]
Consider output of user names with accounts that dont exist anymore.
Create user
Create a file owned by that user
Delete user
