### ISSUE TITLE
Write failed: Broken pipe

### ISSUE THREAD

**Issue by flyklmwl** [PowerShell/Win32-OpenSSH#47]
[wind@JaxPC .ssh]$ ssh administrator@192.168.2.151

Microsoft Windows [°æ±¾ 6.1.7601]
°æÈ¨ËùÓÐ (c) 2009 Microsoft Corporation¡£±£ÁôËùÓÐÈ¨Àû¡£

administrator@MHK-229 C:\Users\Administrator>exit
Connection to 192.168.2.151 closed.
[wind@JaxPC .ssh]$ scp a.txt administrator@192.168.2.151:a.txt
Write failed: Broken pipe
lost connection
[wind@JaxPC .ssh]$

How can I solve this problem?
thanks

**Comment by manojampalam** [comment]
Current release does not support scp.

**Comment by thezim** [comment]
Is there an estimation on when this will be supported?

**Comment by manojampalam** [comment]
Year end.

**Comment by pzingg** [comment]
Also getting this error with sftp from a Mac OS X box:

sftp username@host
username@host's password:
Write failed: Broken pipe
Connection closed

According to some docs you can use Match User/Group in the sshd_config file and chroot the target scp directory, but how do you satisfy this requirement on a Windows server:

sudo chown root:root C:\Users\username

Is there any location that I can use (or sshd_config setup) that will work with sftp?

**Comment by quamrulmina** [comment]
scp client and server both now works in Windows. Please report any scp or sftp problems creating new issues ticket. Thanks.
