### ISSUE TITLE
Issue with scp.exe and backslashes in username on Linux host

### ISSUE THREAD

**Issue by Etharin** [PowerShell/Win32-OpenSSH#471]
Hi,

When I'm copying from Linux to Linux I can use the following and it works fine:
scp install.ps1 domain\\\username@hostname:install.ps1

However using scp.exe causes issues when the \ is included in the user name:
PS E:\OpenSSH-Win64 (1)\OpenSSH-Win64> .\scp install-sshd.ps1 domain\\\username@hostname:install.ps1
The filename, directory name, or volume label syntax is incorrect.
        0 file(s) copied.

I've tried single backslash, single quoting and double quoting around the destination.
Am I missing something or are backslashes not allowed in the scp.exe username?
The same username works on the same host using ssh.exe.

**Comment by manojampalam** [comment]
Fixed in https://github.com/PowerShell/openssh-portable/commit/654c18f96023b7d580d6048b84417cad66199645

**Comment by Etharin** [comment]
Awesome, thanks for fixing so fast.
