### ISSUE TITLE
command=" authorized_keys not enforced?

### ISSUE THREAD

**Issue by andynz2017** [PowerShell/Win32-OpenSSH#473]
Authentication using publickey to workstation user account (non domain user).
Syntax Used:
command="C:\folder location\application folder\binary" ssh-rsa KEY HERE rmteuser@rmtehost
Authentication over SSH successful even though command not specified on the client side, and enforced in authorized_keys file server side. Shell access acquired where it should be restricted if command not specified?

Unsure if this is an issue with how I have defined the command statement in the authorized_keys file or whether this is an underlying bug. Please advise, may just be me being a muppet.

**Comment by manojampalam** [comment]
This is not supported in Windows yet. 

Did you not see this log message in sshd.log or ssh-agent.log ?
AuthorizedPrincipalsCommand and AuthorizedKeysCommand are not supported in Windows yet

If not, let me know.

**Comment by andynz2017** [comment]
Thanks for the quick response.

Using DEBUG3, no messages associated with AuthorizedPrinciplesCommand or AuthorizedKeysCommand noted.

**Comment by manojampalam** [comment]
Just tried adding these in sshd_config
AuthorizedKeysCommand /c:\windows\system32\cmd.exe
AuthorizedKeysCommandUser admin

and saw this line in ssh-agent.log
10992 23:37:26 859 AuthorizedPrincipalsCommand and AuthorizedKeysCommand are not supported in Windows yet

**Comment by andynz2017** [comment]
This would explain why I didn’t see the error in ssh-agent.log. I didn’t have those commands explicitly defined in my sshd_config configuration. 

Is there estimated time frames on when this feature may become available?
