### ISSUE TITLE
In powershell, scp followed by ssh is outputting weird characters

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/Win32-OpenSSH#482]
1) ssh
2) issue dir
3) exit ssh
4) now do scp
5) you will see weird characters  "0KB/s   --:-- ETAIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIII"

**Comment by bingbing8** [comment]
does not repro. Please reopen when you can repro it.

**Comment by david-chaves** [comment]
Hi, I'm having the same issue, this is the following commands running inside a powershell script:
```powershell
# Let's declare some variable to use throught the script file
$remote_host="rampup-bastion"
$ansible_folder = "ansible"
$remote_folder="{0}:{1}/{2}" -f $remote_host ,"/home/ec2-user", $ansible_folder

# Before we can copy files, we need to create some folders
ssh $remote_host "mkdir -p $ansible_folder"
ssh $remote_host "mkdir -p $ansible_folder/inventories"
ssh $remote_host "mkdir -p $ansible_folder/roles"

# First, we are going to copy the file responsible for installing ansible
scp .\ansible.sh $remote_folder
```
The host it's defined inside my `%HOMEPATH%\.ssh\config` using the ssh agent to connect trough. What the script does it's copy the files to a AWS RedHat Instance.

**Comment by manojampalam** [comment]
@bingbing8 can you please take a look?

**Comment by david-chaves** [comment]
I as doing some more testing and discovered that calling `Write-Output` solves the issue, no idea what it does in background.

**Comment by bingbing8** [comment]
@david-chaves, I still can't repro.  Are you able to repro it on [latest release](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.6.1.0p1-Beta)?
