### ISSUE TITLE
Windows OpenSSH reply problem by Linux cron ssh.

### ISSUE THREAD

**Issue by olhonia** [PowerShell/Win32-OpenSSH#484]
Hello Everyone.
Im japanese. and sorry about my bad english...

im builded ssh server to Windows 7(RSA Public Key enabled).
after, i tryd SSH Command by Linux(command is ssh -i rsa_key user01@192.168.2.1 dir).
this command is replyd.
but, this command into crontab then, not return any reply.  ｡・ﾟ・(ﾉД`)・ﾟ・｡
Am i making mistake?
Do you know about someone's?

Work environment:
    Windows 7 Professional (192.168.2.1/24)
    LINUX [CentOS6.6] (192.168.2.5/24)

**Comment by bagajjal** [comment]
ssh -i rsa_key user01@192.168.2.1 dir -> This will output to your console..

When you add this to crontab, where will the output be written?

Try redirecting the output of ssh to a file and check the content of that file, if you plan to have it in the crontab.

Please let us know if this solves your problem.

**Comment by olhonia** [comment]
@bagajjal
Thanks for comments.
I already tryed it.

ssh -i rsa_key user01@192.168.2.1 dir -> Output_test.txt

if dont use crontab (Type command line) then,  its successfuly written to [Output_test.txt].
and can see Windows directory construction.
```
   -bash-4.1$ cat Output_test.txt
    h      Cu C ?{
                  [        x
                            ﾍ OS ?ｷ
    {
     [ V
        A
         ?ﾍ B824-25D8 ?ｷ        <-   Garbled characters because encoding is different
    C:\Users\user01 ?fB                 Windows: shift-jis     LINUX:UTF-8
                              Ng


   2016/12/22  09:39    <DIR>          .
   2016/12/22  09:39    <DIR>          ..
   2017/01/06  08:44    <DIR>          .ssh
   2016/09/10  11:29    <DIR>          Contacts
   2017/01/06  17:00    <DIR>          Desktop
   2016/09/13  11:04    <DIR>          Documents
   2016/09/20  18:14    <DIR>          Downloads
```

but, if add to crontab then, not written anything.
```
   -bash-4.1$ crontab -l
   LANG=ja_JP.UTF-8
   SHELL=/bin/bash
   PATH=/sbin:/bin:/usr/sbin:/usr/bin
   MAILTO=user01
   HOME=/home/user01
     14 13 *  *  * sh ./test.sh

   -bash-4.1$ ls -ltr
   -rw-r--r-- 1 user01 user01         0  1月 24 13:14 2017 Output_test.txt

   -bash-4.1$ cat Output_test.txt
   -bash-4.1$


```
timestamp has been updated.

**Comment by ikrel** [comment]
the issue can be easily reproduced by using nohup , the -vvv logs read failed as opposed to interactive success. Google gives some linux-on-linux reports of similar behaviour which are solved by -t -t.
however using -t with windows openssh hangs the client, and then leads to 100% cpu utilization on the server. 
in_debug.sh] debug2: channel 0: read<=0 rfd 4 len 0
[23:50:09]	[win_debug.sh] debug2: channel 0: read failed
[23:50:09]	[win_debug.sh] debug2: channel 0: close_read
[23:50:09]	[win_debug.sh] debug2: channel 0: input open -> drain
[23:50:09]	[win_debug.sh] debug2: channel 0: ibuf empty
[23:50:09]	[win_debug.sh] debug2: channel 0: send eof
[23:50:09]	[win_debug.sh] debug2: channel 0: input drain -> closed

**Comment by siddolo** [comment]
@olhonia, @ikrel 
try:
script -q -c "ssh -i .ssh/id_rsa user01@192.168.2.1 whoami"

Keep in mind that "dir" is not a binary, so you have to execute "cmd /c dir"

**Comment by bagajjal** [comment]
This is fixed by now, please test in the recent release (0.0.16.0)..  
Reopen if you have any issues.

**Comment by geoffreywiseman** [comment]
This has been driving me nuts for several days now. Finally I found this issue. 👍
