### ISSUE TITLE
Returning exit code 4 to ssh client

### ISSUE THREAD

**Issue by mjessome** [PowerShell/Win32-OpenSSH#485]
I have just upgraded to v0.0.7.0 from v0.0.5.0 and noticed that my ssh client is always exiting with status code 4, even on successful exit. This was not an issue with v0.0.5.0.
Both a manual install as well as an install through chocolatey have been tried.
I am using ssh keys for login, username `WORKGROUP\marc.jessome` is specified in .ssh/config. Client is running OSX with 

```
$ ssh windows
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

WORKGROUP\marc.jessome@windows C:\Users\marc.jessome>exit
Connection to windows closed.

$ echo $?
4
```

**Comment by mjessome** [comment]
Seems to be OK on v0.0.6.0

**Comment by bagajjal** [comment]
please share the debug3 logs for the ssh-agent and sshd

**Comment by gd197** [comment]
any chance to have a fix for January-End milestone ?

**Comment by manojampalam** [comment]
Looking into this

**Comment by manojampalam** [comment]
Thanks for reporting this. This will be fixed in Jan-End release.
