### ISSUE TITLE
Unknown error at packet_write_wait  and operation failed on Release build when verbose option is not enabled.

### ISSUE THREAD

**Issue by bingbing8** [PowerShell/Win32-OpenSSH#486]
scp pester test, some tests failed randomly on release build when -v is not specified. 
packet_write_wait: Connection to fe80::c521:2d89:3d17:361e%18 port 22: Unknown error
Please see dump cab at \\\scratch2\scratch\yawang\OpenSSH

**Comment by manojampalam** [comment]
We haven't seen this recently
