### ISSUE TITLE
Unknown error at ssh_dispatch_run_fatal

### ISSUE THREAD

**Issue by bingbing8** [PowerShell/Win32-OpenSSH#487]
Run the folowing with single signon setup
start cmd.exe /c powershell "1..100 | foreach {.\ssh.exe -i .\id_rsa localadmin@127.0.0.1 hostname}"
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 22: Unknown error

**Comment by manojampalam** [comment]
We haven't seen this recently.
