### ISSUE TITLE
regedit changes made the display not working

### ISSUE THREAD

**Issue by tranbadu** [PowerShell/Win32-OpenSSH#489]
I am having the same issue as madhavanks26. The display is not working since I made the regedit change. Not even in safe mode it comes on. Is there a fix for this?

Here is the change I made.

reg add HKLM\System\CurrentControlSet\Control\Lsa /v "Authentication Packages" /t REG_MULTI_SZ /d msv1_0\0ssh-lsa -f

Thanks,
tranbadu

**Comment by manojampalam** [comment]
Sorry to hear this. I don't know why this change would break the OS. I'll check and see if there is a way to revert it.

**Comment by tranbadu** [comment]
I was able to fix it by using the last known good configuration on Windows 7. I still wanted to get OpenSSH to work on a Windows 7 machine with key authentication. Do you have any success doing it?

**Comment by manojampalam** [comment]
Use manual steps as mentioned in https://github.com/PowerShell/Win32-OpenSSH/issues/189
