### ISSUE TITLE
0.0.7.0 broke packer builds

### ISSUE THREAD

**Issue by friism** [PowerShell/Win32-OpenSSH#491]
I'm using openssh and packer with SSH to build windows AWS AMIs. This worked up to and including 0.0.6.0, but stopped working with 0.0.7.0. I'm guessing because of the scp-related changes.

Here's my code: https://github.com/friism/ec2-windows-packer-ssh/blob/master/docker-ci/docker-ci.json

I think the way packer uses scp is a little special, and I haven't produced a simpler repo.

**Comment by friism** [comment]
I'm pondering if this is the cause: https://github.com/PowerShell/openssh-portable/commit/654c18f96023b7d580d6048b84417cad66199645

**Comment by friism** [comment]
This is the error:

```
2017/01/22 09:20:39 packer.exe: 2017/01/22 09:20:39 opening new ssh session
2017/01/22 09:20:39 packer.exe: 2017/01/22 09:20:39 Starting remote scp process:  scp -vt C:/
2017/01/22 09:20:39 packer.exe: 2017/01/22 09:20:39 Started SCP session, beginning transfers...
2017/01/22 09:20:39 packer.exe: 2017/01/22 09:20:39 Copying input data into temporary file so we can read the length
2017/01/22 09:20:39 packer.exe: 2017/01/22 09:20:39 [DEBUG] scp: Uploading button-down.ps1: perms=C0644 size=1219
2017/01/22 09:20:39 packer.exe: 2017/01/22 09:20:39 SCP session complete, closing stdin pipe.
2017/01/22 09:20:39 packer.exe: 2017/01/22 09:20:39 Waiting for SSH session to complete.
2017/01/22 09:20:39 packer.exe: 2017/01/22 09:20:39 non-zero exit status: 4
2017/01/22 09:20:39 packer.exe: 2017/01/22 09:20:39 Retryable error: Error uploading script: Process exited with status 4
2017/01/22 09:20:41 packer.exe: 2017/01/22 09:20:41 [INFO] 1219 bytes written for 'uploadData'
```

I get it when configuring packer to use sftp too. Interactive ssh prompt works fine

**Comment by manojampalam** [comment]
This is due to #485. Fix is in and will be available in Jan end drop.

**Comment by friism** [comment]
Awesome, thanks @manojampalam
