### ISSUE TITLE
The sshd server is stoped when run a script at the same time

### ISSUE THREAD

**Issue by Jingli1985** [PowerShell/Win32-OpenSSH#492]
I write a Powershell script that is stored on Hyper-V 2012 Server, however, I also write a shell script to run this script remotely , I start two shell terminal to run this script at the same time, the sshd server is stopped automatically when script is over

the log is like below 

> 5708 11:30:00 108 debug1: Executing command: C:\RHEL-6.9-20161110.2-x86_64-GEN1\LISA\WS2012R2\lisa\bin\OpenSSH-Win64\ssh-shellhost.exe -nopty powershell        /test.ps1
5708 11:30:00 108 debug1: Register child 00000000000001E0 pid 5276, 0 zombies of 0
5708 11:30:00 108 debug1: close - io:0000004E641B72B0, type:2, fd:7, table_index:7
5708 11:30:00 108 debug1: close - io:0000004E641D0AE0, type:2, fd:10, table_index:10
5708 11:30:00 108 debug1: close - io:0000004E641D0C40, type:2, fd:12, table_index:12
39768 11:32:41 741 debug1: close - io:00000088314064B0, type:2, fd:9, table_index:9
39768 11:32:41 741 debug1: close - io:000000883141C2F0, type:2, fd:11, table_index:11
39768 11:32:41 741 debug1: zombie'ing child at index 0, 0 zombies of 1
39768 11:32:41 741 debug1: raise sig:3
39768 11:32:41 741 debug1: process_queued_signals: WARNING - A signal has interrupted and was processed
39768 11:32:41 741 debug1: Received SIGCHLD.
39768 11:32:41 741 debug1: Unregister child at index 0, 1 zombies of 1
39768 11:32:41 741 debug1: session_by_pid: pid 45384
39768 11:32:41 741 debug1: session_exit_message: session 0 channel 0 pid 45384
39768 11:32:41 741 debug1: session_exit_message: release channel 0
39768 11:32:41 741 debug1: close - io:00000088314054F0, type:2, fd:8, table_index:8
39768 11:32:42 008 debug1: session_by_channel: session 0 channel 0
39768 11:32:42 008 debug1: session_close_by_channel: channel 0 child 0
39768 11:32:42 008 Close session: user vdcadmin from 10.8.174.117 port 44040 id 0
39768 11:32:42 008 debug1: channel 0: free: server-session, nchannels 1
39768 11:32:42 008 Received disconnect from 10.8.174.117 port 44040:11: disconnected by user
39768 11:32:42 008 Disconnected from 10.8.174.117 port 44040
39768 11:32:42 008 debug1: do_cleanup
29948 11:32:42 008 debug1: close - io:000000FC650A76D0, type:2, fd:6, table_index:6
29948 11:32:42 008 debug1: zombie'ing child at index 0, 0 zombies of 2
29948 11:32:42 008 debug1: raise sig:3
29948 11:32:42 008 debug1: process_queued_signals: WARNING - A signal has interrupted and was processed
5708 11:33:01 518 debug1: close - io:0000004E641D0A30, type:2, fd:9, table_index:9
5708 11:33:01 518 debug1: close - io:0000004E641D0B90, type:2, fd:11, table_index:11
5708 11:33:01 518 debug1: zombie'ing child at index 0, 0 zombies of 1
5708 11:33:01 518 debug1: raise sig:3
5708 11:33:01 518 debug1: process_queued_signals: WARNING - A signal has interrupted and was processed
5708 11:33:01 518 debug1: Received SIGCHLD.
5708 11:33:01 518 debug1: Unregister child at index 0, 1 zombies of 1
5708 11:33:01 518 debug1: session_by_pid: pid 5276
5708 11:33:01 518 debug1: session_exit_message: session 0 channel 0 pid 5276
5708 11:33:01 518 debug1: session_exit_message: release channel 0
5708 11:33:01 518 debug1: close - io:0000004E641B6B40, type:2, fd:8, table_index:8
5708 11:33:01 783 debug1: session_by_channel: session 0 channel 0
5708 11:33:01 783 debug1: session_close_by_channel: channel 0 child 0
5708 11:33:01 783 Close session: user vdcadmin from 10.8.174.117 port 44046 id 0
5708 11:33:01 783 debug1: channel 0: free: server-session, nchannels 1
5708 11:33:01 783 Received disconnect from 10.8.174.117 port 44046:11: disconnected by user
5708 11:33:01 783 Disconnected from 10.8.174.117 port 44046
5708 11:33:01 783 debug1: do_cleanup
29948 11:33:01 783 debug1: zombie'ing child at index 0, 1 zombies of 2
29948 11:33:01 783 debug1: raise sig:3
29948 11:33:01 783 debug1: Unregister child at index 0, 2 zombies of 2
17836 10:45:07 805 debug1: socket:388, io:0000003BF2F2F880, fd:3

the code is in server is like below:
`####################################################
#
#this script is used to test Open Win64 SSH server
#
###################################################

$array = @("test1", "test2", "test3")
for ($i=0; $i -lt $array.length; $i++) {
    $array[$i]
    for ($j=0; $j -lt 20; $j++) {
        write-output "hello"
        start-sleep -s 3
    }
}`

the shell is like below:

`#!/bin/bash
#
# nssh
#
# Simple script to execute remote command via ssh on servers listed in $SERVERLIST variable
# Can also transfer files vi scp on servers listed in $SERVERLIST variable
#
###################################

usage() {
	echo -e "\nnormal usage:"
	echo "$0 run \"remote-command\" (e.g. $0 run \"uname -a\")"
	echo "$0 cp \"file-to-transfer\" [target-folder|file] (e.g. $0 cp /etc/hosts /etc)"
	echo -e "\ncustom server list usage: (default is nssh-hostnames.txt in the current directory)"
	echo "e.g. SERVERLIST=/home/norbert/hostlist.txt $0 run \"remote-command\""
	echo "     SERVERLIST=/home/norbert/hostlist.txt $0 cp \"file-to-transfer\" [target-folder|file]"
	echo -e "\nwhere SERVERLIST is path to a text file with a list of servers separated by space or new line.\n"
	echo "custom user usage: (default is the user)"
	echo "e.g. SSHUSER=root $0 run \"remote-command\""
	echo -e "     SSHUSER=root $0 cp \"file-to-transfer\" [target-folder|file]\n"
	echo -e "./nssh.sh '/RHEL-6.9-20170111.0-i386-GEN1/LISA/WS2012R2/lisa/" "/RHEL-6.9-20170111.0-i386-GEN1/\t/i386-2016-GEN1/\tRHEL-6.9-20170111.0-i386-GEN1\t2016'     "
	exit
}

function do_command()
{
	sleep 3s
	case "$1" in
	run)
		echo "--------$cmd_run--------"
		cmd_run="$2\t$3"
		for i in $(cat $SERVERLIST); do
			echo "==> Running \"$2\" on $i"
		expect -c "
			spawn ssh -X -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l ${SSHUSER} ${i} "$cmd_run"
			expect {
			    \"*assword\" {set timeout 6000; send \"${PASSWD}\n\";}
			    \"yes/no\" {send \"yes\n\"; exp_continue;}
			}
	       
		expect eof"
		done
		;;
	cp)
		[ ! -f "$2" ] && echo "error: file \"$2\" not found" && exit
		[ -z "$3" ] && TARGETLOCATION='~' || TARGETLOCATION=$3
		for i in $(cat $SERVERLIST); do
			echo "==> Transferring \"$2\" to ${i}:${TARGETLOCATION}"
			#if [ -z "$SSHUSER" ]; then scp -p "$2" ${i}:$TARGETLOCATION; else scp -p "$2" ${SSHUSER}@${i}:/$TARGETLOCATION; fi
			#scp -p LISA.tar vdcadmin@10.73.72.130:/RHEL-6.10-20170111.0-x86_64-GEN1
			expect -c "
				spawn scp -p "$2" ${SSHUSER}@${i}:/$TARGETLOCATION 
				expect {
				    \"*assword\" {set timeout 6000; send \"${PASSWD}\n\";}
				    \"yes/no\" {send \"yes\n\"; exp_continue;}
				}
		       
			expect eof"
		done
		;;
	rcp)
		[ ! -d "$3" ] && echo "error: file \"$3\" not found" && exit
		[ -z "$2" ] && TARGETLOCATION='~' || TARGETLOCATION=$2
		for i in $(cat $SERVERLIST); do
			echo "==> Transferring ${i}:${TARGETLOCATION} to \"$2\" "
			#if [ -z "$SSHUSER" ]; then scp -p "$2" ${i}:$TARGETLOCATION; else scp -p "$2" ${SSHUSER}@${i}:/$TARGETLOCATION; fi
			#scp -p LISA.tar vdcadmin@10.73.72.130:/RHEL-6.10-20170111.0-x86_64-GEN1
			expect -c "
				spawn scp -p ${SSHUSER}@${i}:$TARGETLOCATION "$3" 
				expect {
				    \"*assword\" {set timeout 6000; send \"${PASSWD}\n\";}
				    \"yes/no\" {send \"yes\n\"; exp_continue;}
				}
		       
			expect eof"
		done
		;;

	*) usage;;
	esac
}
###############################################
#
# main()
#
##############################################

SSHUSER=$user
PASSWD=$password
do_command run $test_cmd`

**Comment by manojampalam** [comment]
I don't see any hint of sshd service getting stopped. In the traces you attached, the sshd worker process is getting terminated after the script execution, which is expected,

5708 11:33:01 783 Disconnected from 10.8.174.117 port 44046
 5708 11:33:01 783 debug1: do_cleanup

The main service with pid 29948 is still intact:
 29948 11:33:01 783 debug1: zombie'ing child at index 0, 1 zombies of 2

**Comment by maertendMSFT** [comment]
Closing unless there is more information
