### ISSUE TITLE
none of the client executables accept "Ctrl+c" and "backspace" while feeding a password

### ISSUE THREAD

**Issue by manojampalam** [PowerShell/Win32-OpenSSH#5]
Issue observed with ssh.exe (while feeding password) and ssh-keygen.exe (while feeding paraphrase)

Ex.
C:\openssh>ssh-keygen.exe -t rsa -f id_rsa
Generating public/private rsa key pair.
Enter passphrase (empty for no passphrase): **************

When asked to enter passphrase, try Ctrl+C or backspace

**Comment by EZTEQ** [comment]
There shouldn't be any "*" when entering a password.

**Comment by quamrulmina** [comment]
Fixed it and checked in the code. Great suggestions – Linux/Unix openssh works the same way – no “*” feedback in password or passphrase.
Thanks. Quamrul Mina.

**Comment by quamrulmina** [comment]
Fixed in L1 branch. Control-c is now sent to the sshd server and will not terminate ssh.exe client itself. To terminate or abandon client, type Control-break. Backspace also now works when typing password.

**Comment by manojampalam** [comment]
The latest release should have this fixed.
