### ISSUE TITLE
Logging is not writing the unicode characters

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/Win32-OpenSSH#502]
Example
23464 11:05:21 419 debug1: request 32: readdir "/E:/client_test_dir_\321\217\320\267\321\213\320\272/" (handle 0)

**Comment by remittor** [comment]
See this place: https://github.com/PowerShell/openssh-portable/blob/5ad8a2c3580ce0bfcf1f81c11b7641235dfcdfea/log.c#L447

**Comment by manojampalam** [comment]
This is due to mprintf related changes in OpenSSh main repo. These got recently ported and this issue should be fixed in March-End release.
