### ISSUE TITLE
Exit status code disruption

### ISSUE THREAD

**Issue by djferguson** [PowerShell/Win32-OpenSSH#503]
We are using openssh in conjunction with Bamboo/Ant to run remote bat scripts.  While testing out v0.0.7.0 we started getting a new ant error.

Our bat scripts are set with an "exit 0" and that has worked without issue.  Now with the 0.0.7.0 version we get an ant error. 

/var/bamboo/build/deploybuild.xml:43: The following error occurred while executing this line:
/var/bamboo/build/deploybuild.xml:63: Remote command failed with exit status 4

Line 43 in our ant script is a macro to line 63 that runs sshexec.

**Comment by manojampalam** [comment]
dup #485
