### ISSUE TITLE
"sshd.exe" can't execute child process (bugged function: spawn_child)

### ISSUE THREAD

**Issue by remittor** [PowerShell/Win32-OpenSSH#504]
If run main process as `C:\OpenSSH>"sshd.exe"↲` (look for quotes) then child process **sshd.exe** can't executed.
If main module have name with space (like `sshd v74.exe`) then child process **sshd v74.exe** can't executed.

Fix: https://github.com/PowerShell/openssh-portable/pull/59

**Comment by manojampalam** [comment]
Thanks @remittor for finding the issue and providing the fix. I'll have it available in Feb end drop.

**Comment by manojampalam** [comment]
Logic around spawn_child has been modified a bit and this should work from March-End release

**Comment by remittor** [comment]
Not fixed!
Proof: https://github.com/PowerShell/openssh-portable/pull/117
