### ISSUE TITLE
rsa key based auth verification failure with some ssh clients

### ISSUE THREAD

**Issue by gd197** [PowerShell/Win32-OpenSSH#507]
I have some issues regarding the new V0.0.8.0 release
Using rsa key based auth
failure with a sun ssh client (was working before in V0.0.7.0) : 
bash-3.00$ ssh -V
Sun_SSH_1.1.3, SSH protocols 1.5/2.0, OpenSSL 0x0090704f

agent.log on W7 openssh-win64 server:

1600 10:50:19 175 client pid 2672 connected
1600 10:50:19 177 debug1: spawned worker 4388 for agent client pid 2672 
4388 10:50:19 218 agent_start pid:4388, dbg:0, child:1, pipe:360
4388 10:50:19 218 debug3: connection io 0000000000434860 #bytes:0 state:0
4388 10:50:24 597 debug3: connection io 0000000000434860 #bytes:4 state:1
4388 10:50:24 597 debug3: connection io 0000000000434860 #bytes:398 state:2
4388 10:50:24 599 debug2: client type: 3
4388 10:50:24 599 debug1: process agent request type 100
4388 10:50:24 618 debug3: LsaLogonUser succeeded
4388 10:50:24 619 debug1: trying public key file C:\\Users\\xxx/.ssh/authorized_keys
4388 10:50:24 619 debug1: matching key found: file C:\\Users\\xxx/.ssh/authorized_keys, line 1 RSA SHA256:uGlMPy/f4OjHyq5n+7Mpxuba6r7m49bUAWHH0CEuejo
4388 10:50:24 620 error: key_verify: invalid argument
4388 10:50:24 620 debug1: signature verification failed
4388 10:50:24 620 debug3: connection io 0000000000434860 #bytes:5 state:3
4388 10:50:28 519 debug1: iocp error: 109 on 0000000000434860 \n
4388 10:50:28 519 debug1: connection 0000000000434860 clean up
4388 10:50:28 519 debug1: iocp error: 6 on 0000000000000000 \n

same test, same openssh server with another client (cygwin) wich works well
 ➤ ssh -V
OpenSSH_6.2p2, OpenSSL 1.0.1g 7 Apr 2014

agent.log on W7 openssh-win64 server:

1600 11:38:56 076 client pid 4356 connected
1600 11:38:56 078 debug1: spawned worker 5344 for agent client pid 4356 
5344 11:38:56 123 agent_start pid:5344, dbg:0, child:1, pipe:360
5344 11:38:56 123 debug3: connection io 0000000000264860 #bytes:0 state:0
5344 11:38:59 428 debug3: connection io 0000000000264860 #bytes:4 state:1
5344 11:38:59 428 debug3: connection io 0000000000264860 #bytes:978 state:2
5344 11:38:59 430 debug2: client type: 3
5344 11:38:59 430 debug1: process agent request type 100
5344 11:38:59 438 debug3: LsaLogonUser succeeded
5344 11:38:59 439 debug1: trying public key file C:\\Users\\xxx/.ssh/authorized_keys
5344 11:38:59 440 debug1: matching key found: file C:\\Users\\xxx/.ssh/authorized_keys, line 3 RSA SHA256:mcsaimK2DGHFHAExYjaWFUfk8T8JIMGy3XuufIEuLPE
5344 11:38:59 528 debug3: connection io 0000000000264860 #bytes:8 state:3
5344 11:39:02 938 debug1: iocp error: 109 on 0000000000264860 \n
5344 11:39:02 938 debug1: connection 0000000000264860 clean up
5344 11:39:02 939 debug1: iocp error: 6 on 0000000000000000 \n

trying to generate new key-pairs does not help
Might be linked with #481 ?
Also note that using the same key (which fail under Sun) with a linux client is working well also

Hope this helps

**Comment by gd197** [comment]
misuse on my side, please don't take into account

**Comment by friism** [comment]
@gd197 did you find the problem? I'm having the same problem: I can log in using git-bash OpenSSH client, but the Go-lang client in Packer fails with similar stuff in the log.

**Comment by gd197** [comment]
Hello,
Seem it was a badly secured private rsa key on my sun cient (wrong permission)
After correcting and reloading the session the auth went well
