### ISSUE TITLE
Terminal gets garbled with long output

### ISSUE THREAD

**Issue by MrBatschner** [PowerShell/Win32-OpenSSH#508]
**Host:** Windows Server 2016 x64 with OpenSSH Build 0.0.8.0 (probably happening on other Windows Versions too, but untested)
**Client:** any Windows with PuTTY or Linux with xterm

When logging in to a Windows Server 2016 host with ssh through sshd and executing a command that produces very long output, the output gets garbled up after some time.

Steps to reproduce: log in through SSH and execute a simple "dir /s C:\\". After some time, the output becomes incomplete, or even stops (with the cursor doing a silly dance on just one line).

**Comment by mikemaccana** [comment]
I didn't experience this behavior with previous releases but after moving to `0.0.9.0` from, IIRC, `0.0.7.0` I am. Here's an `npm install` running on a Linux host:

![screenshot_10](https://cloud.githubusercontent.com/assets/172594/23263390/0311296e-f9d6-11e6-8400-e14c6c8582f5.png)

**Comment by bagajjal** [comment]
Please test with the latest release.

**Comment by mikemaccana** [comment]
@bagajjal Behaviour no longer occurs with the recent 0.0.10.0 release 👍

**Comment by bagajjal** [comment]
Thank you.
