### ISSUE TITLE
Failed silent interaction 

### ISSUE THREAD

**Issue by olegdunkan** [PowerShell/Win32-OpenSSH#509]
Check it out golang/go#18901
I have used v 0.0.8 (32 and 64 bits)

**Comment by olegdunkan** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx

WSAECONNRESET
10054
Connection reset by peer.
An existing connection was forcibly closed by the remote host. This normally results if the peer application on the remote host is suddenly stopped, the host is rebooted, the host or remote network interface is disabled, or the remote host uses a hard close (see setsockopt for more information on the SO_LINGER option on the remote socket). This error may also result if a connection was broken due to keep-alive activity detecting a failure while one or more operations are in progress. Operations that were in progress fail with WSAENETRESET. Subsequent operations fail with WSAECONNRESET.

````
4148 22:13:43 458 debug2: WSARecvCompletionCB - io:0000003B1EE87B30, pending_state:1, flags:0, error:10054, received:0
4148 22:13:43 458 debug3: select - returning 1
4148 22:13:43 458 debug3: sigprocmask() how:517928372
4148 22:13:43 458 debug3: sigprocmask() how:517928380
4148 22:13:43 458 debug3: w32_read fd:3
4148 22:13:43 458 debug3: recv - io:0000003B1EE87B30
4148 22:13:43 458 debug1: recv - from CB ERROR:10054, io:0000003B1EE87B30
````

**Comment by manojampalam** [comment]
Happens if the other side exist abruptly. Need client and server side logs to understand what's causing this. https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Comment by manojampalam** [comment]
Reopen with logs attached.
