### ISSUE TITLE
Access via ssh/sftp from ubuntu

### ISSUE THREAD

**Issue by jobe451** [PowerShell/Win32-OpenSSH#51]
Things that I got to work:
- access windows directory via sftp from WinSCP
- access windows machine from ubuntu via SSH and run windows commands like dir.

What I don't get to work though:
1) form ubuntu machine (I tried a fuew endings)
```bash
rsync srcfile user@windows8.host:c:/
```

2) Open from Nautilius the Windows remote directory by using "sftp://user@windows8.host"

**Comment by quamrulmina** [comment]
1) rsync is not bundled in Windows or is in our ssh package. Hence your rsync command does not work.
2) scp client and server and sftp client and servers are now available in our package and have been improved with various fixes related to file and directory accesses. ubuntu sftp and scp works with our sftp server and scp server. Please try ubuntu Nautilius with your remote directory access and it should work now.

**Comment by quamrulmina** [comment]
We tested it to work from ubuntu gui Nautilus client using "sftp://username@windowshost" format . So will close the issue.
