### ISSUE TITLE
build problem with contrib\win32\win32compat\inc\crtheaders.h

### ISSUE THREAD

**Issue by ngugc** [PowerShell/Win32-OpenSSH#516]
contrib\win32\win32compat\inc\crtheaders.h is not regenerated if it exists.
And it's not removed when cleaning the whole solution.

This will cause build problems if the content is changed by new commits.

**Comment by manojampalam** [comment]
Tried adding the following to "config" project file but it does not seem to work. 

  \<Target Name="BeforeClean">
    \<Delete Files="$(OpenSSH-Src-Path)contrib\win32\win32compat\inc\crtheaders.h" />
 \</Target>

**Comment by ngugc** [comment]
How about removing the following line in contrib\win32\openssh\config.ps1?
**_if (Test-Path $OutCRTHeader) {exit}_**

Then it will be regenerated every time.

**Comment by manojampalam** [comment]
Since 99% of all the C source files indirectly rely on this header, regenerating this every time means that all the sources will be re-compiled on every BUILD.

**Comment by ngugc** [comment]
```javascript
<Target Name="BeforeClean">
<Delete Files="$(OpenSSH-Src-Path)contrib\win32\win32compat\inc\crtheaders.h" />
</Target>
```

Why did it not work?
It works for me. The config project should be unloaded, then reloaded again.

```javascript
diff --git a/contrib/win32/openssh/config.vcxproj b/contrib/win32/openssh/config.vcxproj
index c171a31..45d6ca4 100644
--- a/contrib/win32/openssh/config.vcxproj
+++ b/contrib/win32/openssh/config.vcxproj
@@ -201,4 +201,7 @@
   <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
   <ImportGroup Label="ExtensionTargets">
   </ImportGroup>
+  <Target Name="BeforeClean">
+    <Delete Files="$(OpenSSH-Src-Path)contrib\win32\win32compat\inc\crtheaders.h" />
+  </Target>
 </Project>
```

**Comment by manojampalam** [comment]
Thanks. Not sure why it did not work when I tried earlier. Fix is in.
