### ISSUE TITLE
can't use openssh in combination with mercurial - ioctlsocket error

### ISSUE THREAD

**Issue by woutercal** [PowerShell/Win32-OpenSSH#52]
When I connect manually to the mercurial server, I don't get any errors: 

C:\home>C:\OpenSSH-Win32\ssh.exe -v -oStrictHostKeyChecking=no -oKexAlgorithms=+
diffie-hellman-group1-sha1 -oPasswordAuthentication=no -oKbdInteractiveAuthentic
ation=no -oChallengeResponseAuthentication=no -i C:\home\shellscript\puppet_id_r
sa phabricator-vcs@x.x.x.x -p2222
OpenSSH_7.1p1 Microsoft Win32 port, OpenSSL 1.0.2d 9 Jul 2015
debug1: Connecting to x.x.x [x.x.x.x] port 2222.
debug1: allocating new sfd, sfd [3] fd [3] handle [1880] type [2]
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: allocating new sfd, sfd [4] fd [4] handle [1804] type [1]
debug1: key_load_public: No such file or directory
debug1: identity file C:\home\shellscript\puppet_id_rsa type -1
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\home\shellscript\puppet_id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.1p1 Microsoft Win32 port Nov  9 2015
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.7p1 Debian-5
debug1: match: OpenSSH_6.7p1 Debian-5 pat OpenSSH* compat 0x04000000
debug1: Authenticating to rcs-serv.proxi.tools:2222 as 'phabricator-vcs'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:...
debug1: Host '[x.x.x.x]:2222' is known and matches the ECDSA host key.
debug1: Found key in C:\Documents and Settings\Administrator\.ssh\known_hosts:2
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Trying private key: C:\home\shellscript\puppet_id_rsa
debug1: allocating new sfd, sfd [4] fd [4] handle [1792] type [1]
debug1: Authentication succeeded (publickey).
Authenticated to rcs-serv.proxi.tools ([5.39.40.247]:2222).
debug1: allocating new sfd, sfd [4] fd [4] handle [15] type [4]
debug1: allocating new sfd, sfd [5] fd [5] handle [19] type [4]
debug1: allocating new sfd, sfd [6] fd [6] handle [23] type [4]
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: Remote: Forced command.
debug1: Remote: Port forwarding disabled.
debug1: Remote: X11 forwarding disabled.
debug1: Remote: Agent forwarding disabled.
debug1: Remote: Pty allocation disabled.
PTY allocation request failed on channel 0
phabricator-ssh-exec: Welcome to Phabricator.
...

When I use ssh in combination with mercurial, I get ioctlsocket errors and the connection times out:

C:\home>hg.exe clone ssh://phabricator-vcs@x.x.x.x:2222/diffusion/COMMON/common-files/ c:\home\shellscript\common --ssh "ssh -v -oStrictHostKeyChecking=no -oPasswordAuthentication=no -oKbdInteractiveAuthentication=no -oChallengeResponseAuthentication=no -i c:\home\shellscript\puppet_id_rsa"
remote: OpenSSH_7.1p1 Microsoft Win32 port, OpenSSL 1.0.2d 9 Jul 2015
remote: debug1: Connecting to x.x.x.x [x.x.x.x] port 2222.
remote: debug1: allocating new sfd, sfd [3] fd [3] handle [1860] type [2]
remote: debug1: Connection established.
remote: debug1: permanently_set_uid: 0/0
remote: debug1: allocating new sfd, sfd [4] fd [4] handle [1800] type [1]
remote: debug1: key_load_public: No such file or directory
remote: debug1: identity file c:\home\shellscript\puppet_id_rsa type -1
remote: debug1: _open() returned error, errno [2]
remote: debug1: key_load_public: No such file or directory
remote: debug1: identity file c:\home\shellscript\puppet_id_rsa-cert type -1
remote: debug1: Enabling compatibility mode for protocol 2.0
remote: debug1: Local version string SSH-2.0-OpenSSH_7.1p1 Microsoft Win32 port Nov  9 2015
remote: debug1: Remote protocol version 2.0, remote software version OpenSSH_6.7p1 Debian-5
remote: debug1: match: OpenSSH_6.7p1 Debian-5 pat OpenSSH* compat 0x04000000
remote: debug1: Authenticating to x.x.x.x:2222 as 'phabricator-vcs'
remote: debug1: SSH2_MSG_KEXINIT sent
remote: debug1: SSH2_MSG_KEXINIT received
remote: debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
remote: debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
remote: debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
remote: debug1: Server host key: ecdsa-sha2-nistp256 SHA256:...
remote: debug1: Host '[x.x.x.x]:2222' is known and matches the ECDSA host key.
remote: debug1: Found key in C:\Documents and Settings\Administrator\.ssh\known_hosts:2
remote: debug1: SSH2_MSG_NEWKEYS sent
remote: debug1: expecting SSH2_MSG_NEWKEYS
remote: debug1: SSH2_MSG_NEWKEYS received
remote: debug1: Roaming not allowed by server
remote: debug1: SSH2_MSG_SERVICE_REQUEST sent
remote: debug1: SSH2_MSG_SERVICE_ACCEPT received
remote: debug1: Authentications that can continue: publickey,keyboard-interactive
remote: debug1: Next authentication method: publickey
remote: debug1: Trying private key: c:\home\shellscript\puppet_id_rsa
remote: debug1: allocating new sfd, sfd [4] fd [4] handle [1788] type [1]
remote: debug1: Authentication succeeded (publickey).
remote: Authenticated to x.x.x.x ([x.x.x.x]:2222).
remote: debug1: allocating new sfd, sfd [4] fd [4] handle [1788] type [3]
remote: debug1: allocating new sfd, sfd [5] fd [5] handle [1784] type [3]
remote: debug1: allocating new sfd, sfd [6] fd [6] handle [1780] type [3]
remote: debug1: ioctlsocket() returned error, errno [10038]
remote: debug1: ioctlsocket() returned error, errno [10038]
remote: debug1: ioctlsocket() returned error, errno [10038]
remote: debug1: channel 0: new [client-session]
remote: debug1: Requesting no-more-sessions@openssh.com
remote: debug1: Entering interactive session.
remote: debug1: Remote: Forced command.
remote: debug1: Remote: Port forwarding disabled.
remote: debug1: Remote: X11 forwarding disabled.
remote: debug1: Remote: Agent forwarding disabled.
remote: debug1: Remote: Pty allocation disabled.
remote: debug1: Sending command: hg -R diffusion/COMMON/common-files/ serve --stdio

Any idea what could be the problem?

**Comment by manojampalam** [comment]
Hoping that #91 would fix this issue.

**Comment by manojampalam** [comment]
Try out the latest release and reopen if you still see this issue.
