### ISSUE TITLE
ssh command has many problems connecting to Ubuntu 16.04

### ISSUE THREAD

**Issue by ngugc** [PowerShell/Win32-OpenSSH#520]
Use ssh(v0.0.8.0) command to connect to Ubuntu 16.04 .
It has no color scheme, and vim is almost unusable.

**Comment by manojampalam** [comment]
What shell are you using? Try using a bash shell.

**Comment by ngugc** [comment]
I tried with Windows CMD and powershell. Haven't tried with a bash shell.
But I don't get it. Why should users get a bash shell on **_Windows_** to run ssh client?

**Comment by ngugc** [comment]
Do you mean this Ubuntu Bash on Windows?
https://msdn.microsoft.com/en-us/commandline/wsl/about

**Comment by ngugc** [comment]
Tried with Cygwin:
```javascript
$ ./bin/Win32/Debug/ssh.exe 192.168.10.201
Pseudo-terminal will not be allocated because stdin is not a terminal.
```

**Comment by bagajjal** [comment]
After login to the Ubuntu from windows cmd/powershell, 
1) issue "bash" so that you will get into the bash shell..
2) Then do the vim <yourfilepath>

Here is the snapshot of vim working (logged from windows cmd.exe to Linux server)..
![image](https://cloud.githubusercontent.com/assets/23668037/22767362/a62c036a-ee2f-11e6-9d2c-0541b3d976b0.png)

openssh right now supports only ANSI/VT100 terminal control escape sequences...

If it didn't work then issue 
"echo $TERM" -> it should xterm.

also attach the screenshot.

**Comment by ngugc** [comment]
I couldn't change $TERM to xterm, it's always dumb.
![image](https://cloud.githubusercontent.com/assets/2368031/22783684/d55feaa6-ef07-11e6-9c15-0d59b570c47c.png)

If connecting with XShell, it's "xterm" by default:
![image](https://cloud.githubusercontent.com/assets/2368031/22782633/fb175cde-ef02-11e6-8bcc-fb52eaf4cfcd.png)

**Comment by ngugc** [comment]
The output was garbled if forcely set $TERM to xterm:
![image](https://cloud.githubusercontent.com/assets/2368031/22783059/06a4eb3c-ef05-11e6-8c46-36c8794e9358.png)

**Comment by ngugc** [comment]
@bagajjal , @manojampalam, how did you make it work? Did you run ssh.exe with additional options or configurations? Thanks!

**Comment by ngugc** [comment]
Attached the ssh log.  I couldn't put the debug log in a separated file with the "-E" option.
![image](https://cloud.githubusercontent.com/assets/2368031/22858791/7c413392-f102-11e6-908b-f401ab3979f7.png)
This was the standard error output:
[log.txt](https://github.com/PowerShell/Win32-OpenSSH/files/769025/log.txt)

**Comment by bagajjal** [comment]
There are some problems while connecting from windows openssh client to unix ssh servers, we are trying to fix them.

**Comment by bagajjal** [comment]
Please checkout the march mid release.
I have captured the terminal related information here "https://github.com/PowerShell/Win32-OpenSSH/wiki/Terminal-Info"

**Comment by ngugc** [comment]
Great! It worked after following the instructions in "https://github.com/PowerShell/Win32-OpenSSH/wiki/Terminal-Info".

One more question, why is the TERM env variable in Linux server still "dumb" by default?
What's more we need to do from ssh client side to make it as "xterm" by default?

Thanks very much!

**Comment by bagajjal** [comment]
Please set the TERM to xterm before doing the ssh (step 4)...

FYI,  wiki link is moved to https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH.
