### ISSUE TITLE
sftp failed with broken pipe

### ISSUE THREAD

**Issue by laughterk** [PowerShell/Win32-OpenSSH#523]
There's a chance (6/10) sftp fails to connect to the server:

1. client: openssh on OS X 10.11(OpenSSH_6.9p1) or Ubuntu 14.04 (OpenSSH_6.6.1p1 Ubuntu-2ubuntu2).
2. server: v0.0.8.0
3. error message:
> Tunnel established.
> Tunnel closed.
> Write failed: Broken pipe
> Couldn't read packet: Connection reset by peer

Not sure if it relates to my configuration, I'm connecting to the server via `ProxyCommand` using `proxy tunnel` (the server is behind a firewall).

PS: directly ssh to the server using the same configuration works each time.

**Comment by pkt1237** [comment]
I have the same issue, although, its only from our linux servers
1. client: OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013 on Red Hat Enterprise Linux Server release 6.8 (Santiago)
2. Server: v0.0.8.0
3. error message:
Write failed: Broken pipe
Couldn't read packet: Connection reset by peer

Windows box is not behind a firewall so no need for proxy command in our setup
Other items to note, logs show that password was accepted and initial connection was established then immediately closed, also if I go from my Win7 Desktop using Filezilla, i have no problems getting in via sftp.  Only seems to break between our RHEL server and our win server.  This was previously working under v0.0.6.0.

Oh also, using ssh from the above linux version does not have an issue, only appears to be broke when wanting to use sftp.

**Comment by acpiper** [comment]
I'm experiencing the same behaviour with 64-bit versions 0.0.7.0 through 0.0.9.0 when connecting using Ubuntu Linux 14.04 LTS's latest openssh SFTP client and Paramiko SFTP client. I've not tested connecting from a Windows machine.

**Comment by manojampalam** [comment]
Please try out the latest release, open a new issue with template filled, if you still see this issue.
