### ISSUE TITLE
ssh cmd command -> output / error

### ISSUE THREAD

**Issue by jovinoblanco** [PowerShell/Win32-OpenSSH#525]
Hi,

Windows client:
W7 Professional SP1 (32 bit) with Win32-OpenSSH -> not sure which version around October 2016)

I encountered the following problem. I need (because Job-Server executor definition) to use **cmd** for every ssh command executed from jobs of our job-server. But using cmd.exe /c does not return output for some commands:

ssh CONNECT-STRING(-i, domain, username, host) cmd.exe /c ipconfig
-> no output

ssh CONNECT-STRING(-i, domain, username, host) cmd.exe /c systeminfo
-> no output

ssh CONNECT-STRING(-i, domain, username, host) cmd.exe /c driverquery
-> no output

ssh CONNECT-STRING(-i, domain, username, host) cmd.exe /c driverquery
-> no output

--------------------------------------------------------------------------------

ssh CONNECT-STRING(-i, domain, username, host) cmd.exe /c date
-> working

ssh CONNECT-STRING(-i, domain, username, host) cmd.exe /c vol
-> working

-------------------------------------------------------------------------------

I did further tests and found:
ssh CONNECT-STRING(-i, domain, username, host) cmd.exe  ipconfig or
ssh CONNECT-STRING(-i, domain, username, host) cmd.exe /k  ipconfig

returns the following error message (german):
Für diesen Befehl ist nicht genügend Speicher verfügbar

Translated:
Not enough storage is available to process this command

I believe that resolving this problem with cmd.exe | cmd.exe /k will also solve the problem with cmd /c meaning that the command will return output.

Thank you very much for your help/support. I appreciate every kind of tip in order solve this nasty problem on our side

Cheers

**Comment by manojampalam** [comment]
I just tested the latest version on Windows 10 en-us. All of the above commands seemed to work. Can you try out with the latest version on your side?

**Comment by jovinoblanco** [comment]
hi

i tried to install the newest version today.
unfortunately i wasn able to execute an kind of statement and got the error error in libcrypto.

**Comment by manojampalam** [comment]
Please share logs.

**Comment by jovinoblanco** [comment]
Hi,

thanks for your feedback.

I wasnt able to install the newest version yet. I will soon and will let you know.

Cheers

**Comment by manojampalam** [comment]
Reopen if needed
