### ISSUE TITLE
ssh.exe -E option not work

### ISSUE THREAD

**Issue by ngugc** [PowerShell/Win32-OpenSSH#526]
Almost the latest version: commit ce03c08333f19db75dce0cd17e70c2ecda4ae2fc
The ssh.exe -E option does not work.
[ssh_log.txt](https://github.com/PowerShell/Win32-OpenSSH/files/769024/ssh_log.txt)
The debug output was still in the standard error, and there was nothing in the log.txt specified by -E option.

**Comment by ngugc** [comment]
log.c

![image](https://cloud.githubusercontent.com/assets/2368031/22910321/22c4c0ca-f294-11e6-881f-585effa1d430.png)

**Comment by manojampalam** [comment]
This should work with March-end release.
