### ISSUE TITLE
Paste does not work from OSX Terminal

### ISSUE THREAD

**Issue by brandonroyal** [PowerShell/Win32-OpenSSH#527]
Paste does not work when using macOS Terminal or iTerm2 client

*Environment*
OSX El Capitan (native SSH Client)
Windows Server 2016

**Comment by friism** [comment]
Here are some other things that don't work for me from a Windows client to a open-ssh from this repo running on Windows server.

## Git-bash

```
friism@LAPTOP-G8D4BRBC MINGW64 ~
$ ssh -V
OpenSSH_7.3p1, OpenSSL 1.0.2j  26 Sep 2016

 ssh Administrator@52.37.23.57 powershell
```

 * up/down arrow doesn't cycle through command history, it moves the cursor up and down
 * ctrl+c is not sent to process run in the SSH session, it terminates the SSH session
 * ...etc

## Conemu/powershell

```
C:\code\aws-win-packer [master +5 ~2 -0 !]> ssh -V
OpenSSH_7.1p1 Microsoft_Win32_port_with_VS Nov  6 2016, OpenSSL 1.0.2d 9 Jul 2015

ssh -i "C:\Users\Michael Friis\Downloads\friism-test.pem" Administrator@52.37.23.57 powershell
```

 * up/down arrow doesn't work at all
 * ctrl+c closes SSH session

**Comment by laughterk** [comment]
> Paste does not work when using macOS Terminal or iTerm2 client

Same problem on Ubuntu 14.04 (OpenSSH_6.6.1p1 Ubuntu-2ubuntu2) too, only the first character is left.

**Comment by bagajjal** [comment]
Thanks for reporting.. This will be fixed in Feb-Mid release (Feb-15th).

**Comment by friism** [comment]
@bagajjal also the arrow-key and ctrl+c stuff that I mentioned?

**Comment by bagajjal** [comment]
@friism - arrow keys and ctrl+c are working without fail.. 
I verified these setups,
1) windows openssh client to windows openssh server
2) windows openssh client to Ubuntu server
3) from putty to windows openssh server..

I am using windows 10 OS (from cmd.exe and also powershell) and Ubuntu 16.10.

If they didn't work for you then specify the operating system version and client/server software used and open a new issue.. Please use the latest release binaries..

**Comment by friism** [comment]
@bagajjal here's a video: https://www.youtube.com/watch?v=Y2MBPOS5X7o&feature=youtu.be

This is with 0.0.8.0 on WS2016 server with MinGW SSH client

**Comment by bagajjal** [comment]
@friism , are you referring to the left over characters when you press up/down arrows because the new command is smaller than the old command? If yes, this is a known issue which we are trying to fix.. You can raise a new issue for this.

**Comment by friism** [comment]
@bagajjal the most annoying thing is in the latter part of the video when I do `ssh Administrator@<IP> powershell` you'll notice that hidding up-arrow just moves the cursor around in the terminal window.

**Comment by bagajjal** [comment]
@friism  its the issue with the MinGW SSH client.. Its unable to interpret correctly..
Please use the openssh client and report if you have any issues...

Also please open a new issue since this thread is closed..
