### ISSUE TITLE
"Exit signal received..." in all connections

### ISSUE THREAD

**Issue by nightwish47** [PowerShell/Win32-OpenSSH#530]
At an exact moment, not all but most of connection from clients is killed and in sshd.log `debug1: Exit signal received...` appears

For example: I'm running 4 clients, they're connecting to the SSH server. Then 3 of them suddenly disconnect. The 4th connection is still running fine, no problem.

sshd.log
>1752 14:54:11 173 debug1: Exit signal received...
>...
>6456 14:54:11 173 debug1: Exit signal received...
>...
>3268 14:54:11 173 debug1: Exit signal received...

**Comment by nightwish47** [comment]
the issue remains for days, any suggestion would be appreciated

**Comment by bagajjal** [comment]
Please retest manually and provide the logs for the sshd.log and ssh client..

**Comment by nightwish47** [comment]
This is server log.
[sshd.log.20170228.txt](https://github.com/PowerShell/Win32-OpenSSH/files/805550/sshd.log.20170228.txt)
I'm contacting to get client log.
Thanks

**Comment by bagajjal** [comment]
Are you still facing this issue? Is it reproducible manually?
Please provide the steps to reproduce and the logs (sshd.log and ssh client logs)

**Comment by bagajjal** [comment]
can we close this issue?

**Comment by bagajjal** [comment]
If the issue still persist then please provide the steps for repro.
