### ISSUE TITLE
How to use the -f and -n options ?

### ISSUE THREAD

**Issue by qlux** [PowerShell/Win32-OpenSSH#535]
I am trying to use the background option of ssh using the -f (which implies -n) redirecting STDIN to /dev/null. I have the following error on Windows:

`debug2: open - pathname:/dev/null, flags:0, mode:0
debug1: open - CreateFile ERROR:3
dup() in/out/err failed`

Is there a way to redirect /dev/null to NUL or to have something equivalent to the background option (sending EOF) ?

Thanks

**Comment by manojampalam** [comment]
background execution is not supported in Windows yet. See https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Scope
