### ISSUE TITLE
Disconnect after a period of time

### ISSUE THREAD

**Issue by nightwish47** [PowerShell/Win32-OpenSSH#536]
I have a client with setup as below:
Every 10 minutes, client will connect to server then send files in queue. If no file left, it will keep the connection for 2 more minutes then disconnect. 
In server, I set the following parameter but I'm not sure it's root cause or not. Server is running v0.0.7.0.
>ClientAliveInterval 60
ClientAliveCountMax 3

The situation is in most sessions, most but not all, they are disconnected after 3 minutes. If heavy file or multiple files are being transmitted, they're broken.
Please see log file. Thanks.
[sshd.log.20170211.txt](https://github.com/PowerShell/Win32-OpenSSH/files/788946/sshd.log.20170211.txt)

**Comment by bagajjal** [comment]
I have gone through the attached sshd.log file..

As you can see in the below screenshot the server is getting SIGCHLD signal (i.e., the client has terminated the connection)...

![image](https://cloud.githubusercontent.com/assets/23668037/23239104/183df892-f91a-11e6-93da-5f84d38c172f.png)

The below configuration handles the network failures where the server sends a alive_request to client for every 60 secs and client replies.. If the server didn't get the response from the client for max retries (3 i.e., 3 * 60 sec = 3 min) then the server will close the connection.. 
                    ClientAliveInterval 60
                   ClientAliveCountMax 3

Error message in sshd.log if there is a network failures i.e., connection between server and client is lost and there is no traffic...
![image](https://cloud.githubusercontent.com/assets/23668037/23239422/feb5187c-f91b-11e6-8e54-9bacc6cf2743.png)

so its clear that there is no network issue from the sshd.log file and the client is initiating the connection close.. 

Please check your scripts to make sure the client is not closing the connection.. 
Also please try manually, if you were able to reproduce then please share your sshd_config, sshd.log and steps to reproduce....

**Comment by nightwish47** [comment]
Thank you for your suggestion. I double checked and turn out it's my fault of configuration in client, it's not this software issue.
I will close the issue.
Thank you again for your time.
