### ISSUE TITLE
Missing "Diffie-Hellman Key Exchange Reply" packet during connection establishment

### ISSUE THREAD

**Issue by nightwish47** [PowerShell/Win32-OpenSSH#537]
I mentioned this issue in #522 because I think they might be related.
But to easier to follow, I create this issue.
Network monitor showed that during connection establishment, "Diffie-Hellman Key Exchange Reply" packet is missing so connection is failed.
As below:
Normal connection
![diffie-normal](https://cloud.githubusercontent.com/assets/25627306/23195230/82c68190-f8f5-11e6-97c8-0f256344bec1.PNG)

No Diffie-Hellman Key Exchange Reply
![diffie-my system](https://cloud.githubusercontent.com/assets/25627306/23195239/8c6e006a-f8f5-11e6-8a40-1f8108418759.PNG)

**Comment by bagajjal** [comment]
Can this be closed? Might be related to #536?

**Comment by nightwish47** [comment]
@bagajjal : I think that it is not related to #536 and it occur sometime until now.
Could you please continue check it?

**Comment by nightwish47** [comment]
@bagajjal :May we hear updates on this topic?

**Comment by bagajjal** [comment]
@nightwish47 - Are you running into this issue again when you are using only the openssh client? If not, can this be closed?

**Comment by manojampalam** [comment]
Please reopen with repro instructions.
