### ISSUE TITLE
A problem occurs when restarting the sshd & ssh-Agent service when the existing sshd process still remains

### ISSUE THREAD

**Issue by x9f5yjkq** [PowerShell/Win32-OpenSSH#538]
Hello.

We are using OpenSSH v0.0.9.
We restart the sshd service and the ssh-Agent service every night at 23:00.
We do not use password authentication, we use key authentication only.

A problem occurred in the following situations.
-----------------------------------------------
When a session under SFTP connection exists at the time of restarting the sshd service and ssh-Agent service at 23:00,
After restarting the sshd service and the ssh-Agent service, a new SFTP connection can not be established.
 (Key authentication NG)

As a measures, kill all the sshd processes from the Windows Task Manager and restart the sshd service and ssh - Agent service to recover.
-----------------------------------------------

<Problem 1>
The problem is that restarting sshd service and ssh - agent service will not kill the existing sshd process.

<Problem 2>
If an existing SFTP connection (sshd process) remains, if you restart the sshd service and ssh-agent service, the key authentication fails in the new SFTP connection (sshd process).

Please tell me the solution about the above two problems.

**Comment by bagajjal** [comment]
Problem 1 described above is not a bug.. it is an expected behavior... when you restart the sshd service then the existing connections will still be left alive.. 

For problem2, it is a bug in our code.. We will try to fix this in the feb-end milestone.. As a workaround, don't stop the ssh-agent service..

**Comment by x9f5yjkq** [comment]
Hello.
thank you for your answer.
For the time being, we will operate without restarting the ssh-agent service.

**Comment by bagajjal** [comment]
But as mentioned earlier even if you restart the sshd, the existing connections will still continue..
That's the base SSH behavior..

**Comment by x9f5yjkq** [comment]
Thank you.
I understood.
If we need to kill an existing process at the time of restarting the daily service, we will deal by batch processing.

**Comment by bagajjal** [comment]
The issue is related to port mismatch which is added to prevent malware executable (that has same name as ssh-agent)..

**Comment by manojampalam** [comment]
The check was removed and you shouldn't be seeing this anymore. Reopen if needed.
