### ISSUE TITLE
How to set shared directory and permissions for user?

### ISSUE THREAD

**Issue by togosh** [PowerShell/Win32-OpenSSH#539]
With FileZilla I had a GUI to perform these actions: 
[https://wiki.filezilla-project.org/wiki/images/f/f5/FZS_aliases.png](https://wiki.filezilla-project.org/wiki/images/f/f5/FZS_aliases.png)

Im totally new to OpenSSH, I have SFTP setup on a windows server, I can log in with my windows account,
I set up another windows account using:
```
net user username password /add
```
but when connecting in that user has access to everything.

Modifying sshd_config file
```
#ChrootDirectory none
```
and replacing none with a path and removing # seemed to change the default starting directory when logging in, but I could still poke around all over the system

Questions:
How do I restrict a user to only have access to a certain directory?
How do I set a users read/write permissions?

References:
https://github.com/PowerShell/Win32-OpenSSH/issues/190

https://github.com/PowerShell/Win32-OpenSSH/issues/140

https://github.com/PowerShell/Win32-OpenSSH/issues/381

https://github.com/PowerShell/Win32-OpenSSH/issues/478

https://github.com/PowerShell/Win32-OpenSSH/issues/3

**Comment by togosh** [comment]
This is what I could find:

cacls
http://superuser.com/questions/131827/limiting-ssh-user-account-only-to-access-his-home-directory

WinJail
http://www.winquota.com/wj/

https://www.experts-exchange.com/questions/27659882/Windows-Server-2008-restrict-user-to-one-folder.html

https://social.technet.microsoft.com/Forums/windowsserver/en-US/2a034514-1886-4fda-8d86-52d80cafd4cf/restrict-user-access-to-one-resource?forum=winserverDS

icacls
http://serverfault.com/questions/578129/how-to-replace-permissions-and-everything-inside-with-icacls-on-windows-server-2

**Comment by togosh** [comment]
I ended up ditching Windows and going with Ubuntu, these are the steps I followed:
http://askubuntu.com/questions/420652/how-to-setup-a-restricted-sftp-server-on-ubuntu/607898#607898

**Comment by manojampalam** [comment]
CHROOT is a UNIX feature that's not supported in Windows. 
SFTP subsystem (sftp-server.exe) on Windows ends up getting launched as your Windows user. You will need to use the standard Windows ACLing to control access to files (and other resources).

**Comment by mrPsycho** [comment]
@manojampalam and how to change disk to D in sftp browser?

**Comment by bagajjal** [comment]
@mrPsycho  use "cd d:\"

**Comment by mrPsycho** [comment]
@bagajjal thanks, captain.  
but tell it to the end users, who uses filezilla or cyberduck

**Comment by bagajjal** [comment]
If you are using third party software then you need to browse to the corresponding drive..

![image](https://cloud.githubusercontent.com/assets/23668037/25599553/e25a633e-2e91-11e7-8da8-a94c19cb0350.png)

As of now "/" ( root ) only shows the C drive.. There is already a fix, which will be pushed in the next release..

**Comment by mrPsycho** [comment]
@bagajjal thanks a lot!

**Comment by smaug9** [comment]
@bagajjal: ETA for next release?
Also, confirmed that mounting a volume in an empty folder on the C:\ drive and connecting via winscp fails.

**Comment by manojampalam** [comment]
Fix involves changes to dirent.c. Ensure changes in https://github.com/PowerShell/openssh-portable/pull/47 are also incorporated if needed.

**Comment by helplessJ** [comment]
Thud.
