### ISSUE TITLE
domain users getting access denied on windows 2003 sp2

### ISSUE THREAD

**Issue by anirban1c** [PowerShell/Win32-OpenSSH#54]
sshd running on windows 2003 sp2 in a AD domain 
login from putty or linux ssh client getting access denied
are local users only supported in this release ?

**Comment by quamrulmina** [comment]
Password login for domain users are allowed but you need to specify the domain in the client invocation using user@domain format. Two examples that will work:
ssh user@domain@hostname
ssh -l user@domain hostname

**Comment by anirban1c** [comment]
thanks let me test that

**Comment by ljhmily** [comment]
> sshd running on windows 2003 sp2 in a AD domain login from putty or linux ssh client getting access denied are local users only supported in this release ?

how to get the windows 2003 support openssh version？
