### ISSUE TITLE
Update lib

### ISSUE THREAD

**Issue by nightwish47** [PowerShell/Win32-OpenSSH#544]
Please recheck if 
[https://github.com/PowerShell/Win32-OpenSSH/blob/L1-Prod/contrib/win32/openssh/OpenSSLSDK/1.0.2d/Win32/Release/lib/libeay32.lib](url)
and
[https://github.com/PowerShell/Win32-OpenSSH/blob/L1-Prod/contrib/win32/openssh/OpenSSLSDK/1.0.2d/Win32/Release/lib/ssleay32.lib](url)
are latest version (1.0.2d)? Latest version is 1.1.0, I think.
[https://www.openssl.org/source/](url)
 
IMHO, using an outdated version might lead to less secure connection and other issues, probably.

**Comment by manojampalam** [comment]
OpenSSH does not work with OpenSSL 1.1.0 (since the API surface diverged significantly).
