### ISSUE TITLE
Location of libs after compiled

### ISSUE THREAD

**Issue by nightwish47** [PowerShell/Win32-OpenSSH#545]
Hi, I understand the 2 libs `libeay32.lib` and `ssleay32.lib` are in 
[https://github.com/PowerShell/Win32-OpenSSH/tree/L1-Prod/contrib/win32/openssh/OpenSSLSDK](url) 
but I want to do some investigations myself. 
I wonder if you guys can show me where are they located after compiled. 
Thanks

**Comment by manojampalam** [comment]
You can find OpenSSL build instructions [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Building-using-VS-2015/05b574c32d7dc4a4d3d5bebd82826819bdcf15d4)
