### ISSUE TITLE
OpenSSLSDK payload

### ISSUE THREAD

**Issue by mirathewhite** [PowerShell/Win32-OpenSSH#547]
I'm trying to build OpenSSH in VS 2015 for the first time.  @manojampalam can you clarify exactly which file(s) need to be downloaded from https://github.com/PowerShell/Win32-OpenSSH/tree/L1-Prod/contrib/win32/openssh/OpenSSLSDK to build using VS 2015?

Thank you,
Mira

**Comment by bagajjal** [comment]
@mirathewhite - download the whole folder ( https://github.com/PowerShell/Win32-OpenSSH/tree/L1-Prod/contrib/win32/openssh/OpenSSLSDK) to your repository($openssh-portable\contrib\win32\openssh\OpenSSLSDK)..

**Comment by mirathewhite** [comment]
Thank you @bagajjal .
