### ISSUE TITLE
sshd_config does not support option 'AuthorizedPrincipalsCommand'

### ISSUE THREAD

**Issue by discodance1** [PowerShell/Win32-OpenSSH#548]
When i try to use option AuthorizedPrinciaplsCommand in sshd_config to run a custom binary to authorize a user.
ssh-agent fails to start with error 1053.

**Comment by discodance1** [comment]
This is with the latest version of openssh v0.0.9.0

**Comment by manojampalam** [comment]
'AuthorizedPrincipalsCommand' and 'AuthorizedKeysCommand' are not supported yet in Windows. See project scope [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Scope)

**Comment by discodance1** [comment]
I do see in your recent commit AuthorizedPrincipalsCommand option has been synced from openssh-portable. 

I tried submitting below code change but was told that currently openssh-portable only supports cygwin paths on windows.
https://github.com/discodance1/openssh-portable/commit/0aa5eca300662093ff7d9382f4a76af274e0cd25

**Comment by discodance1** [comment]
Submitted a commit: 
https://github.com/discodance1/Win32-OpenSSH/commit/6cb1805afa4a450b0022601c45d6feac88aecd8a

**Comment by manojampalam** [comment]
Did you get 'AuthorizedPrincipalsCommand' to work. Currently its disabled in here
logit("AuthorizedPrincipalsCommand and AuthorizedKeysCommand are not supported in Windows yet");
in auth2-pubkey.c

Function subprocess() needs to be ported for Windows first.

**Comment by discodance1** [comment]
I do see your point.
When i run sshd.exe -ddd in command prompt with AuthorizedPrincipalsCommand i Get
AuthorizedPrincipalCommand C:/ProgramData/binary.exe %u
I see error "AuthorizedPrincipalsCommand must be an absolute path"
Which speaks to me that AuthorizedPrincipalsCommand is supported.

But when i check ssh-agent logs during the normal run it says AuthorizedPrincipalsCommand and AuthorizedKeysCommand are not supported in Windows yet

Do you know by when this option will be supported ?

**Comment by manojampalam** [comment]
Related to https://github.com/PowerShell/Win32-OpenSSH/issues/473
I'll see what it takes to have this enabled.

**Comment by joeyaiello** [comment]
Putting a note here: got some interest in this offline. :)

**Comment by dbroeglin** [comment]
I'm curious if there is any ETA on this subject. I was trying to setup a git server on windows using Git over SSH and this would have been just the way to go.

**Comment by manojampalam** [comment]
Setting this for Oct-Mid radar to see what can be done.

**Comment by manojampalam** [comment]
Looked into this. The underlying implementation relies on fdopen support that does not exist in Windows POSIX adapter yet. And AFAIK, its not possible to add its support without modifying POSIX semantics - this means changes to core OpenSSH code that we are not prepared to do yet. 

Sorry to inform that this cannot come until we take care of a whole bunch of other issues need for this fork to be accepted upstream.

**Comment by bagajjal** [comment]
Fixed as part of https://github.com/PowerShell/openssh-portable/pull/409
