### ISSUE TITLE
Changing Local/AD user's Home Directory does not work

### ISSUE THREAD

**Issue by mvpkenlin** [PowerShell/Win32-OpenSSH#549]
With the rest of the issues #126 #140 #190 #539 

I tried to set User's Home Directory into a network share under User's properties. However, the result is, it still logged into c:\Users\%usrname% after connected through SFTP client. 

Anyone else has tried it?

**Comment by mvpkenlin** [comment]
Ops, just found out that #154 has mentioned about this from Mar 2016.

**Comment by manojampalam** [comment]
Taking a look at this now. Can you elaborate how you modified User's properties?

**Comment by manojampalam** [comment]
dup #154 
Please add details on #154
