### ISSUE TITLE
Getting “System error 1067” when installing OpenSSH

### ISSUE THREAD

**Issue by tgefen** [PowerShell/Win32-OpenSSH#55]
I'm trying to install the package on windows Server 2008 R2. I applied all steps (except the firewall one) and all passed successfully.

When I try this command

    net start sshd

I get this error:

    The SSHD service is starting. The SSHD service could not be started.

    A system error has occurred.

    System error 1067 has occurred.

    The process terminated unexpectedly.

What could be the problem? I couldn't find any log file. The Security in Windows' Event Viewer only says:

The SSHD service terminated unexpectedly.  It has done this 2 time(s).

You can see more details on the XML below.

Note:

    I skipped the Firewall step since the firewall is not running.
    I generated the keys successfully
    There's no antivirus installed on this host
    I tried to install both 32bit and 64bit packages (same error on both).
    My machine is 64bit running on VMware.

These are the XML details from the Event Viewer:

Log Name:      System
Source:        Service Control Manager
Date:          12/25/2015 12:17:53 PM
Event ID:      7034
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WINS08-2
Description:
The SSHD service terminated unexpectedly.  It has done this 2 time(s).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
    <EventID Qualifiers="49152">7034</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2015-12-25T10:17:53.073482000Z" />
    <EventRecordID>20007</EventRecordID>
    <Correlation />
    <Execution ProcessID="468" ThreadID="4180" />
    <Channel>System</Channel>
    <Computer>WINS08-2</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="param1">SSHD</Data>
    <Data Name="param2">2</Data>
  </EventData>
</Event>

**Comment by tgefen** [comment]
I could find the problem my self.
You have to tell users to "cd" to the extracted folder before running step #3.
https://github.com/PowerShell/Win32-OpenSSH/wiki/Deploy-Win32-OpenSSH

**Comment by mikemaccana** [comment]
I'm having the same issue. 

I don't think your suggested fix related to the problem - assuming 'Step 3' is the ssh-keygen step, I cd'd into the folder before running it (I don't think it would run otherwise since it isn't in PATH).

**Comment by mikemaccana** [comment]
Actually, you're right. Not sure how I missed this the first time around.

**Comment by mikemaccana** [comment]
Fixed in https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by manojampalam** [comment]
Thanks for taking care of this.

**Comment by mikemaccana** [comment]
No probs @manojampalam thank for all your hard work! 💯

**Comment by jyhong836** [comment]
I meet the same problem when I install OpenSSH under 'D:/XXX/'. Not sure why this happens.

**Comment by bagajjal** [comment]
@jyhong836 - Try [troubleshooting steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps). I would recommend installing OpenSSH under c:\program files\.

If you couldn't resolve your problem then please open a new issue, provide sshd log (with DEBUG3 enabled).

**Comment by jyhong836** [comment]
@bagajjal Yes. Installing in 'c:\program...' will resolve the issue. Thanks.

**Comment by JukEboXAuDiO** [comment]
Getting this error with 7.7.2.0p Beta. Is installed in C:\program Files\OpenSSH on Windows Server 2016.

**Comment by egoldin** [comment]
Me too, also C:\program Files\OpenSSH on Windows Server 2016

**Comment by amakhno** [comment]
Running FixHostFilePermissions.ps1 script solved this problem for me

**Comment by i6amokk** [comment]
1

**Comment by s2zaman** [comment]
`The OpenSSH SSH Server service terminated unexpectedly`
After installing the [64bit](https://github.com/PowerShell/Win32-OpenSSH/releases/download/v8.0.0.0p1-Beta/OpenSSH-Win64.zip) version of [OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/releases), got this error while starting the service.

Resolved by installing the [32bit](https://github.com/PowerShell/Win32-OpenSSH/releases/download/v8.0.0.0p1-Beta/OpenSSH-Win32.zip) version.

**Comment by s2zaman** [comment]
The 64bit version too is working now.
I suspect it is a permissions issue with 64bit version only.

Thanks @amakhno for pointing out.

The `FixHostFilePermissions.ps1` powershell script residing at `C:\Program Files\OpenSSH-Win64\FixHostFilePermissions.ps1` resolved the error `The OpenSSH SSH Server service terminated unexpectedly`.

The **sshd** service is now starting successfully.
Can be found in services with the **OpenSSH SSH Server** as display name.

**Comment by 0xarcano** [comment]
> The 64bit version too is working now.
> I suspect it is a permissions issue with 64bit version only.
> 
> Thanks @amakhno for pointing out.
> 
> The `FixHostFilePermissions.ps1` powershell script residing at `C:\Program Files\OpenSSH-Win64\FixHostFilePermissions.ps1` resolved the error `The OpenSSH SSH Server service terminated unexpectedly`.
> 
> The **sshd** service is now starting successfully.
> Can be found in services with the **OpenSSH SSH Server** as display name.

It works for me, thanks!

**Comment by EdwinCloud101** [comment]
This video explains at 2:00 minutes

https://youtu.be/gUOEaZb0gW8
