### ISSUE TITLE
Host Key Negotiation Fails

### ISSUE THREAD

**Issue by nightwish47** [PowerShell/Win32-OpenSSH#552]
Hello guys,

We got following error sometimes and wonder why does the host key negotiation fail although using same config file?

**sshd.log reports:**

1. Error case

5468 10:22:00 356 debug2: **host key algorithms: ssh-ed25519**
5468 10:22:00 356 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
5468 10:22:00 356 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
5468 10:22:00 356 debug2: first_kex_follows 0 
5468 10:22:00 356 debug2: reserved 0 
5468 10:22:00 356 debug1: kex: algorithm: diffie-hellman-group-exchange-sha256
5468 10:22:00 356 debug1: kex: **host key algorithm: (no match)**
5468 10:22:00 356 fatal: **Unable to negotiate with xxx.xxx.xxx.xxx: no matching host key type found. Their offer: ssh-rsa,ssh-dss**

2. Success case

3064 10:21:59 675 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
3064 10:21:59 675 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
3064 10:21:59 675 debug2: first_kex_follows 0 
3064 10:21:59 675 debug2: reserved 0 
3064 10:21:59 675 debug1: kex: algorithm: diffie-hellman-group-exchange-sha256
3064 10:21:59 675 debug1: kex: **host key algorithm: ssh-rsa**
3064 10:21:59 675 debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1 compression: none

Thanks in advance

**Comment by manojampalam** [comment]
What was this list in success case?
debug2: host key algorithms: XXXXXXXXXXX

Can you dump the full logs in failure case? I suspect sshd failed to load the relevant host keys for some reason.

**Comment by nightwish47** [comment]
@manojampalam : I would like to answer as below:

> What was this list in success case?
> debug2: host key algorithms: XXXXXXXXXXX

→[host key algorithms: ssh-rsa,ssh-dss] 

> Can you dump the full logs in failure case? I suspect sshd failed to load the relevant host keys for some reason.

→Please see attached file
[Error_log.txt](https://github.com/PowerShell/Win32-OpenSSH/files/815880/Error_log.txt)

**Comment by manojampalam** [comment]
Looks like you are using a pretty old version. This was removed a while back
-> ModifyRightsToDesktop(mode = 0)...

Please update to the latest version. Reopen if needed

**Comment by nightwish47** [comment]
@manojampalam :Thanks for your answer.

> Please update to the latest version

Is it mean that update the latest version for OpenSSH on client side?

In addition, since the system is running on production, so its very hard to upgrade the latest version right now.
Are there any other methods to modify the setting of 「sshd_conifg」instead of version up?

**Comment by nightwish47** [comment]
@manojampalam : please re-open this topic.

**Comment by nightwish47** [comment]
@manojampalam : please re-open this topic and any updates on this issue?
