### ISSUE TITLE
Please modify your install instructions

### ISSUE THREAD

**Issue by discodance1** [PowerShell/Win32-OpenSSH#554]
In your install instructions you say to install openssh in 
C:\Program Files\OpenSSH but when you do so passwordless ssh ssh fails to work with unable to create token for user.
Things work as expected when openssh is installed under C:\OpenSSH. 

Either modify the doc for fix the code to reflect the install instructions.

**Comment by manojampalam** [comment]
What release? AFAIK with the latest release, it should work wherever installed.

**Comment by jschvartz** [comment]
Yes, it does work ok as specified in last documentation (tried it successfully this afternoon).
Only the link for psexec:
https://technet.microsoft.com/en-us/sysinternals/pxexec.aspx
is no longer valid and should be replaced by:
https://technet.microsoft.com/en-us/sysinternals/pstools

Thanks for everything!
Joel

**Comment by manojampalam** [comment]
Thanks @jschvartz. Updated wiki.
