### ISSUE TITLE
extraneous character on ssh output

### ISSUE THREAD

**Issue by rgl** [PowerShell/Win32-OpenSSH#555]
When I run the following command several times:

```powershell
c:/OpenSSH/ssh -i c:/vagrant/tmp/id_rsa vagrant@sshd.example.com echo native sshd hello world from %COMPUTERNAME%
```

The output is somewhat messed up, it will have an extra character after `SSHD`, as you can see in these cases:

```plain
native sshd hello world from SSHD=
native sshd hello world from SSHDA
native sshd hello world from SSHD(
```

Its seems there's a bug somewhere.

I'm using v0.0.9.0.

**Comment by manojampalam** [comment]
dup #566
