### ISSUE TITLE
Support /dev/null for Windows

### ISSUE THREAD

**Issue by mnalis** [PowerShell/Win32-OpenSSH#556]
When redirecting stdin from `/dev/null`, with for example:

    ssh -n -4 -T server whoami

it doesn't work (returns without executing commands and without showing its output) - even when commands do not require STDIN. When `-n` is removed it works correctly.

`-n -v` (problematic) output shows:
```
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending command: whoami
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 2680, received 2768 bytes, in 0.2 seconds
Bytes per second: sent 16756.8, received 17307.0
debug1: Exit status 0
```

just '-v' (ok) shows:
```
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending command: whoami
fx1\mysqlbackup
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 2664, received 2896 bytes, in 0.2 seconds
Bytes per second: sent 14317.2, received 15564.0
debug1: Exit status 0

```

**Comment by mnalis** [comment]
The bug evidently manifest itself in a way that ssh to windows sshd server works from command line, but does not work from crontab. It also fails from command line if you redirect stdin from /dev/null, like so:

    ssh  winserver whoami < /dev/null

Until this is fixed, I've had to use [this wrapper script](http://serverfault.com/a/836667/182307) on ssh client

**Comment by manojampalam** [comment]
Windows equivalent of open(dev/null) is CreateFile("NUL"). Need to add support for open(dev/null) in the POSIX layer
