### ISSUE TITLE
sshd sometimes hangs and waits for input, even for noninteractive sessions

### ISSUE THREAD

**Issue by mnalis** [PowerShell/Win32-OpenSSH#557]
I'm experiencing sporadic problems when trying to ssh to windows server.

When trying to run non-interactive commands (from Debian Jessie with OpenSSH client), sometimes (but not always, and at different intervals) remote command will stop and require pressing <kbd>ENTER</kbd> to continue.

For example:

    ssh -4 -T somehost "mysqldump --master-data --all-databases" > backup.sql &

on some windows machines it finishes ok (if the databases are small enough) but on bigger ones it will usually stop (either immediately, with `backup.sql` remaining with size 0, or after some time, with `backup.sql` having from few megabytes to few hundred megabytes) and then shell will inform me that ssh client process is waiting for input:

    [1]+  Stopped                 ssh -4 -T somehost "cat mysqldump --master-data --all-databases" > backup.sql

if I bring it to `fg` and press <kbd>ENTER</kbd>, it will continue working, even after I <kbd>CTRL</kbd>+<kbd>Z</kbd> and `bg` it. Sometimes it will finish then, other times it will stop again after some time.

strace confirms the process is waiting for TTY input (on file descriptor 4, which is RW opened `/dev/pts/2` or similar PTY of shell spawning the ssh client) and that it is why process has been stopped.

(of course there is never any problem when opensshd is running on Debian GNU/Linux or Ubuntu servers for example)

**Comment by bagajjal** [comment]
Please test with the latest release.

**Comment by manojampalam** [comment]
We have fixed some issues related to hangs reading IO streams. Please test out the latest release and reopen if you still see this.
