### ISSUE TITLE
Should SSH sessions really have %TEMP% set to C:\Users\SSHD\AppData\Local\Temp ?

### ISSUE THREAD

**Issue by charabaruk** [PowerShell/Win32-OpenSSH#559]
This seems like it could be a security issue if multiple users are connecting to the same server. Instead, wouldn't it be better to maintain the user's original TEMP directory?

**Comment by manojampalam** [comment]
Thanks for catching this. Will be fixed in next drop.

**Comment by manojampalam** [comment]
Looked into this. TEMP is set to user's TEMP directory if the user's profile exists. This is being picked up and set in setup_session_user_vars() routine in session.c as part of reading user's environment variables from user's profile in registry.

If there is a failure reading entries from user's profile, TEMP may be set to C:\Users\SSHD\AppData\Local\Temp. However, there is no security issue here. C:\Users\SSHD\AppData\Local\Temp is owned and ACLed to "SSHD" account only. Regular users wouldn't have permissions to read or write to this directory. 

Please reopen if you have further concerns.
