### ISSUE TITLE
"Could not open a connection to your authentication agent."

### ISSUE THREAD

**Issue by altano** [PowerShell/Win32-OpenSSH#560]
I ran `choco install openssh /SSHAgentFeature` and verified that the SSH Server Broker and SSH Server Proxy services were installed and running.

Unfortunately I'm not sure what to do next: every ssh command gives the error "Could not open a connection to your authentication agent." e.g.:

    PS C:\src> ssh-add C:\Users\alan\.ssh\id_rsa
    Could not open a connection to your authentication agent.

What am i doing wrong?

**Comment by manojampalam** [comment]
SSH Server Broker and SSH Server Proxy services were installed and running are a different and independent implementations of SSH (they do not support ssh-agent and its operations) see [here](https://github.com/PowerShell/Win32-OpenSSH/issues/318)


You will need to install OpenSSH bits from [here](https://github.com/PowerShell/Win32-OpenSSH/releases)

**Comment by altano** [comment]
Question 1: So `choco install openssh /SSHAgentFeature` (and the chocolately install in general) can't be used if one wants to make use of ssh-agent?

Question 2: how does one make use of ssh-agent from the OpenSSH port to have persistent authentication? E.g. Being prompted for the password to my key the first time I open my console or the first time ssh runs, but not subsequently. Are there any guides/tutorials? I have this working using Pageant and posh-git on another machine but I'd love to be able to replace those with this port.

**Comment by altano** [comment]
Oh I see from your link that those services are from enabling dev mode, not from the choco install of openssh. So my second question remains: I've installed this port using chocolately: now what? How do I use ssh-agent from this port to get the same functionality as Pageant?
