### ISSUE TITLE
Executing Powershell script on remote Windows server fails with no -TTY/PTTY

### ISSUE THREAD

**Issue by nellfr** [PowerShell/Win32-OpenSSH#561]
Hello, 

I have 1 Linux script that runs in crontab which initiate an keybased SSH login against a Windows 2012 R2 server , to invoke a Powershell script execution with some parameters. 
Basically the Linux script issues this command : 
**ssh -i ID_file  ssh_user@Windows_server_IP "powershell C:\script_path\powershell_script.ps1 param1 param2 param3"**

1. When I launch the Linux script manually from the Linux server it runs fine during 2min (expected execution duration time). 

2. When I launch it through contab the SSH command runs but the PowerShell script is not invoked at all. 

I will copy / paste the SSH server log extract in DEBUG2 mode.

**Comment by nellfr** [comment]
18176 12:17:01 482 debug2: accept io:000000FFEC2B0930
18176 12:17:01 482 debug1: socket:560, io:000000FFEC2B0930, fd:5 
18176 12:17:01 482 debug1: pipe - r-h:568,io:000000FFEC2B05C0,fd:6  w-h:552,io:000000FFEC2B0CA0,fd:7
18176 12:17:01 482 debug1: spawning "C:\\Program Files\\OpenSSH\\sshd.exe"
18176 12:17:01 483 debug1: Register child 0000000000000240 pid 4184, 0 zombies of 2
18176 12:17:01 483 debug1: close - io:000000FFEC2B0930, type:1, fd:5, table_index:5
18176 12:17:01 483 debug2: close - io:000000FFEC2B0930
18176 12:17:01 483 debug1: Forked child 4184.
18176 12:17:01 483 debug1: close - io:000000FFEC2B0CA0, type:2, fd:7, table_index:7
18176 12:17:01 483 debug2: fileclose - pio:000000FFEC2B0CA0
18176 12:17:01 484 debug2: on_select - io:000000FFEC2AEB20 type:1 rd:1
18176 12:17:01 484 debug2: on_select - io:000000FFEC2AE0B0 type:1 rd:1
18176 12:17:01 484 debug2: ReadFileEx io:000000FFEC2B05C0
4184 12:17:01 629 debug1: child socket: 560
4184 12:17:01 629 debug1: child startup_pipe: 552
4184 12:17:01 630 Connection from 10.0.168.138 port 40356 on 10.0.146.37 port 22
4184 12:17:01 630 debug1: Client protocol version 2.0; client software version OpenSSH_6.6.1
4184 12:17:01 630 debug1: match: OpenSSH_6.6.1 pat OpenSSH_6.6.1* compat 0x04000000
4184 12:17:01 630 debug1: Local version string SSH-2.0-OpenSSH_7.4
4184 12:17:01 630 debug1: Enabling compatibility mode for protocol 2.0
4184 12:17:01 630 debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
4184 12:17:01 630 debug1: SSH2_MSG_KEXINIT sent
4184 12:17:01 635 debug1: SSH2_MSG_KEXINIT received
4184 12:17:01 635 debug1: kex: algorithm: curve25519-sha256@libssh.org
4184 12:17:01 635 debug1: kex: host key algorithm: ecdsa-sha2-nistp256
4184 12:17:01 635 debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none
4184 12:17:01 635 debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none
4184 12:17:01 635 debug1: expecting SSH2_MSG_KEX_ECDH_INIT
4184 12:17:01 645 debug1: rekey after 4294967296 blocks
4184 12:17:01 645 debug1: SSH2_MSG_NEWKEYS sent
4184 12:17:01 645 debug1: expecting SSH2_MSG_NEWKEYS
4184 12:17:01 655 debug1: SSH2_MSG_NEWKEYS received
4184 12:17:01 655 debug1: rekey after 4294967296 blocks
4184 12:17:01 655 debug1: KEX done
4184 12:17:01 715 debug1: userauth-request for user ssh_user service ssh-connection method none
4184 12:17:01 715 debug1: attempt 0 failures 0
4184 12:17:01 716 Failed none for ssh_user from 10.0.168.138 port 40356 ssh2
4184 12:17:01 717 debug1: userauth-request for user ssh_user service ssh-connection method publickey
4184 12:17:01 717 debug1: attempt 1 failures 0
4184 12:17:01 717 debug1: userauth_pubkey: test whether pkalg/pkblob are acceptable for RSA SHA256:Amf1vjWBG/ngcq4/aQRpvaS2CJAel03pS0THK5SSabo
4184 12:17:01 717 Postponed publickey for ssh_user from 10.0.168.138 port 40356 ssh2
4184 12:17:01 724 debug1: userauth-request for user ssh_user service ssh-connection method publickey
4184 12:17:01 724 debug1: attempt 2 failures 0
4184 12:17:01 728 Accepted publickey for ssh_user from 10.0.168.138 port 40356 ssh2: RSA SHA256:Amf1vjWBG/ngcq4/aQRpvaS2CJAel03pS0THK5SSabo
4184 12:17:01 728 debug1: close - io:0000000B1840DF60, type:2, fd:4, table_index:4
18176 12:17:01 729 debug2: ReadCB pio:000000FFEC2B05C0, pending_state:1, error:109, received:0
18176 12:17:01 729 debug1: close - io:000000FFEC2B05C0, type:2, fd:6, table_index:6
18176 12:17:01 729 debug2: fileclose - pio:000000FFEC2B05C0
4184 12:17:01 729 debug1: Entering interactive session for SSH2.
4184 12:17:01 729 debug1: pipe - r-h:552,io:0000000B1840DF60,fd:4  w-h:396,io:0000000B18435F80,fd:6
4184 12:17:01 729 debug1: server_init_dispatch
18176 12:17:01 729 debug2: on_select - io:000000FFEC2AEB20 type:1 rd:1
18176 12:17:01 729 debug2: on_select - io:000000FFEC2AE0B0 type:1 rd:1
4184 12:17:01 730 debug1: server_input_channel_open: ctype session rchan 0 win 2097152 max 32768
4184 12:17:01 730 debug1: input_session_request
4184 12:17:01 730 debug1: channel 0: new [server-session]
4184 12:17:01 730 debug1: session_new: session 0
4184 12:17:01 730 debug1: session_open: channel 0
4184 12:17:01 730 debug1: session_open: session 0: link with channel 0
4184 12:17:01 730 debug1: server_input_channel_open: confirm session
4184 12:17:01 730 debug1: server_input_global_request: rtype no-more-sessions@openssh.com want_reply 0
4184 12:17:01 772 debug1: server_input_channel_req: channel 0 request env reply 0
4184 12:17:01 772 debug1: session_by_channel: session 0 channel 0
4184 12:17:01 772 debug1: session_input_channel_req: session 0 req env
4184 12:17:01 772 debug1: server_input_channel_req: channel 0 request exec reply 1
4184 12:17:01 772 debug1: session_by_channel: session 0 channel 0
4184 12:17:01 772 debug1: session_input_channel_req: session 0 req exec
4184 12:17:01 772 Starting session: command for ssh_user from 10.0.168.138 port 40356 id 0
4184 12:17:01 772 debug1: pipe - r-h:400,io:0000000B184371B0,fd:7  w-h:408,io:0000000B18437260,fd:8
4184 12:17:01 772 debug1: pipe - r-h:412,io:0000000B18437310,fd:9  w-h:416,io:0000000B184373C0,fd:10
4184 12:17:01 772 debug1: pipe - r-h:420,io:0000000B18437470,fd:11  w-h:424,io:0000000B18437520,fd:12
4184 12:17:01 775 debug1: Executing command: C:\\Program Files\\OpenSSH\\ssh-shellhost.exe -nopty "powershell C:\\script_path\\powershell_script.ps1 param1 param2 param3 "
4184 12:17:01 776 debug1: Register child 00000000000001C4 pid 21860, 0 zombies of 0
4184 12:17:01 776 debug1: close - io:0000000B184371B0, type:2, fd:7, table_index:7
4184 12:17:01 776 debug1: close - io:0000000B184373C0, type:2, fd:10, table_index:10
4184 12:17:01 779 debug1: close - io:0000000B18437520, type:2, fd:12, table_index:12
4184 12:17:01 781 debug1: close - io:0000000B18437260, type:2, fd:8, table_index:8
4184 12:17:01 784 debug1: close - io:0000000B18437310, type:2, fd:9, table_index:9
4184 12:17:01 784 debug1: close - io:0000000B18437470, type:2, fd:11, table_index:11
4184 12:17:01 786 debug1: zombie'ing child at index 0, 0 zombies of 1
4184 12:17:01 786 debug1: raise sig:3
4184 12:17:01 786 debug1: process_queued_signals: WARNING - A signal has interrupted and was processed
4184 12:17:01 786 debug1: Received SIGCHLD.
4184 12:17:01 786 debug1: Unregister child at index 0, 1 zombies of 1
4184 12:17:01 786 debug1: session_by_pid: pid 21860
4184 12:17:01 786 debug1: session_exit_message: session 0 channel 0 pid 21860
4184 12:17:01 786 debug1: session_exit_message: release channel 0
4184 12:17:01 788 debug1: session_by_channel: session 0 channel 0
4184 12:17:01 788 debug1: session_close_by_channel: channel 0 child 0
4184 12:17:01 788 Close session: user ssh_user from 10.0.168.138 port 40356 id 0
4184 12:17:01 788 debug1: channel 0: free: server-session, nchannels 1
4184 12:17:01 788 Received disconnect from 10.0.168.138 port 40356:11: disconnected by user
4184 12:17:01 788 Disconnected from 10.0.168.138 port 40356
4184 12:17:01 788 debug1: do_cleanup
18176 12:17:01 790 debug1: zombie'ing child at index 2, 0 zombies of 3
18176 12:17:01 790 debug1: raise sig:3
18176 12:17:01 790 debug1: Unregister child at index 2, 1 zombies of 3
18176 12:17:01 791 debug2: signal() sig:3, handler:000007F7C147C4F0
18176 12:17:01 791 debug1: process_queued_signals: WARNING - A signal has interrupted and was processed
18176 12:17:01 791 debug2: on_select - io:000000FFEC2AEB20 type:1 rd:1
18176 12:17:01 791 debug2: on_select - io:000000FFEC2AE0B0 type:1 rd:1

**Comment by mnalis** [comment]
In my case it was because windows sshd does not work when there is not STDIN attached. See #556 for workaround on the client side.

**Comment by nellfr** [comment]
Hi @mnalis thank you for feedback.
In my case the ssh command is executed by a "client wrapper" which I mentioned earlier as Linux script (scheduled in cron). 
I just tried with "-n" and the result is the same, PowerShell script residing on Windows server is not invoked at all. 
I will paste ssh client and server logs in a moment.

**Comment by mnalis** [comment]
yes, with `-n` (or `< /dev/null"`) it would fail also when run on command line (and not just when invoked from crontab). It just demonstrates what the problem is (not handling missing STDIN) and does not fix the problem. 

The workaround is using  [this perl script](http://serverfault.com/a/836667/182307)  linked from #556. It fakes STDIN with no input, so sshd on windows side continues to work normally. 

Another (worse, but simpler to try) workaround might be using `-tt` which would probably run the command, but the output would be mangled with escape sequences and line wrappings (as sshd would assume you are at 80x25 terminal)

**Comment by nellfr** [comment]
Thanks for the two suggestions.
I confirm that -tt option allow to execute the command on server. As the target implementation of the ssh command is to be run by an automation tool silently this workaround is acceptable. Indeed no human is supposed to read output. 
I hope pty allocation and STDIN handling will be fixed in future release to align Microsoft OpenSSH capabilities with OpenSSH on Linux.

**Comment by nellfr** [comment]
I have upgraded OpenSSH package from 0.0.8.0 to 0.0.12.0 but I figured out recently that above workaround (-tt) is no longer working. It results in ssh client command runs and exists immediately from client, and from server it does not execute the script which is same situation than initial issue. 
Is there any remaining workaround or plan to support it ?

**Comment by manojampalam** [comment]
We'll investigate and see what can be done for May-Mid drop.

**Comment by bagajjal** [comment]
check the may-end release
