### ISSUE TITLE
Problems when connecting Permission Denied on password authentication.

### ISSUE THREAD

**Issue by fjaenal** [PowerShell/Win32-OpenSSH#562]
Until now I have been using the Win32-openSSH version from august. Due to some security issues in the Open SSH 7.1 version, I am looking forward to move to the V 0.9.0.0 or V 0.8.0.0 but I have come up with a problem when logging, In the attached files there are the logs and the sshd_config file.

Test Data:
+ Using a port 22200
+ The account is Administrator.
+ The client is an Open SSH v7.4
+ SSHD is running as an NT SERVICE
+ And with the same port and same condition it works for the Win32-openSSH version from august.

+ Executing:
     "C:\Users\jaenf\Desktop\OpenSSH-Win32>ssh Administrator@X.Y.Z.T -p 22200"
Administrator@X.Y.Z.T's password:
**Permission denied, please try again.**
Administrator@X.Y.Z.T's password:"

In the log I can see:
**9748 12:10:09 569 debug1: auth agent did not authorize client Administrator**

I have been taking a look to logs, trying everything but can't say why its keeping telling me "Permission denied"

Is there any restriction for Administrator account? Am I missing something new in the configuration?

[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/821084/sshd_config.txt)
[sshd.log.txt](https://github.com/PowerShell/Win32-OpenSSH/files/821085/sshd.log.txt)

**Comment by manojampalam** [comment]
Authentication and token generation take place in ssh-agent. Please attach agent logs. 
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting%20Steps

**Comment by fjaenal** [comment]
Please find attach the agent-ssh log and anew sshd.log (I have test without key auth, I only need password auth):

[ssh-agent.log.txt](https://github.com/PowerShell/Win32-OpenSSH/files/823859/ssh-agent.log.txt)
[sshd.log.txt](https://github.com/PowerShell/Win32-OpenSSH/files/823877/sshd.log.txt)

Also the ssh-agent runs as a local system account (the sshd runs under NT SERVICE) and sshd has a dependency on ssh-agent.

Also due to some restrictions I have a Console installer (Can't use PS due to security policies), to create the services I run the following commands:
`sc.exe create %NAME_AGENT% binpath= %INSTALLDIR%\ssh-agent.exe DisplayName= "SSH Agent Deamon" start= auto`
`sc.exe create %NAME% binpath= %INSTALLDIR%\sshd.exe DisplayName= "SSH Deamon" start= auto depend= %NAME_AGENT%`
`sc.exe sdset %NAME_AGENT% "D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)(A;;RP;;;AU)"`
`sc.exe config %NAME% obj= "NT SERVICE\sshd"`
`ntrights.exe -u "NT SERVICE\sshd" +r SeAssignPrimaryTokenPrivilege`

Again, thanks for the help !!!
Francisco

**Comment by fjaenal** [comment]
Some more information:
Testing different versions, all 32 bits for the moment
Client and server configuration / installer remains the same for all tests
The account used is the Administrator and its a Local account.
Version 0.0.1.0 --> Works
Version 0.0.2.0 to 0.9.0.0 does not work, same error / logs as above.

Test with 64 bits same results

Also the server OS is Windows server 2008 R2

**Comment by DarwinJS** [comment]
@fjaenal - I believe this is the fault of the chocolatey package - it was not properly copying the ssh-lsa.dll on new installs.

It is fixed in version 0.0.9.20170308, which as of this moment is still in moderation.  It can be pulled before moderation is complete by specifying the version on your chocolately install or upgrade command line.

**Comment by fjaenal** [comment]
@DarwinJS  - I think I may explain myself wrong, I am not using Chocolate package, and the subsequent ps1 script to install, that's because I can't have powershell running on the server. So I have created my own installer using the CMD console. The lines I refer above are the one I use to create, configure and run the sshd and ssh-agent.

To make the installer I have follow the [https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH](url) instructions.

Also I am not using PK auth, its just password auth all the time, so I am not using the ssh-lsa.dll auth method.

Hope i am explaining myself properly or am I missing something basic?

[sshinstaller.bat.txt](https://github.com/PowerShell/Win32-OpenSSH/files/827789/sshinstaller.bat.txt)

Thanks a lot for the help !!!!!!
Francisco

**Comment by DarwinJS** [comment]
@fjaenal - No it's me that wasn't quite sure whether you were affected by this bug.

**Comment by fjaenal** [comment]
Solved the issue, it was the installer I was using, thanks for the help, this can now be closed.

Francisco
