### ISSUE TITLE
Starts cmd rather than powershell

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/Win32-OpenSSH#58]
Having to manually launch powershell after login gets tired. Suggest powershell be the default, and/or make it configurable.

**Comment by quamrulmina** [comment]
Your suggestions will be considered as we expand the feature list.

**Comment by mikemaccana** [comment]
Cheers and thanks for the quick reply! 😃

**Comment by RamblingCookieMonster** [comment]
Agreed - having to call PowerShell manually is a bit of a pain point

**Comment by manojampalam** [comment]
Closing as dup of #90
