### ISSUE TITLE
Have I come to the right place ?

### ISSUE THREAD

**Issue by Adgreen** [PowerShell/Win32-OpenSSH#581]
Have I come to the right place ?

Is this a Win 32 and Win 64 version of   openssh.com ?

I like to run a SSH Server on my Windows server 2016, 64 bit.   Should i just download this OpenSSH-Win64.zip and OpenSSH-Win64_Symbols.zip  for  v0.0.10.0   and follow instructions - And that installs a SSH server on my Winserver 2016, 64 bit ?

Or do I also need to install Cygwin first - and is this OpenSSH-Win64.zip a part of Cygwin ?

"the version of OpenSSH which is part of Cygwin"
"Setting up an SSH server in Windows typically involves installation (e.g. via installing Cygwin[13])"
From :   https://en.wikipedia.org/wiki/Secure_Shell#Usage

**Comment by Adgreen** [comment]
I have heard that MS should include SSH in Win Server 2016.
( If so, can/ how can I check if is is installed and activated on my Windows server 2016, )
Is that done - or do I need to install this - in order to connect with SSH to my Windows server 2016,

**Comment by Adgreen** [comment]
What is the difference between installing installing Open SSH from CygWin : 
https://cygwin.com/packages/package_list.html
https://cygwin.com/packages/x86_64/openssh/

Or installing from your, https://github.com/PowerShell/Win32-OpenSSH/releases
"This is a pre-release (non-production ready)"

**Comment by bagajjal** [comment]
Cygwin, putty are different SSH clients. OpenSSH windows version has both SSH Client and server functionality. You don't need to install Cygwin/putty for this. You can use cmd.exe/powershell to connect to the SSH server. OpenSSH is not yet part of the windows to end users, the work is still in progress. 

Install the latest version from here, https://github.com/PowerShell/Win32-OpenSSH/releases.

**Comment by Adgreen** [comment]
Yes ... 

I want both Client on my Win 10 machne. And also to install SSH Server on my Windows Server 2016.

But ...

What is the difference between installing Open SSH from :

Installing from your, https://github.com/PowerShell/Win32-OpenSSH/releases
"This is a pre-release (non-production ready)" ?

Or CygWin.com :
https://cygwin.com/packages/package_list.html
https://cygwin.com/packages/x86_64/openssh/

They seem to have had a production ready version of SSh for Windows 32 and 64 bit. For at least 1,5 years.
https://cygwin.com/packages/x86_64/openssh/ 

Are these two different development teams, both building Open SSH for Windows ?

**Comment by bagajjal** [comment]
Openssh we are developing is the Microsoft contribution to the openssh community to bring the openssh into the windows inbox.

Cygwin is from different company, not from Microsoft. 

openssh is a open source implementation of ssh. You can fork and customize to your needs.
