### ISSUE TITLE
running git when connected to windows server doesn't work

### ISSUE THREAD

**Issue by jrmuizel** [PowerShell/Win32-OpenSSH#583]
When ever I run a git command I get no output. e.g.
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\jeff>git --version

C:\Users\jeff>
```

**Comment by bagajjal** [comment]
Not sure what's the problem at your end, it worked for me...
![image](https://cloud.githubusercontent.com/assets/23668037/24121492/ac21f15c-0d75-11e7-96d8-b1269ccff290.png)

**Comment by manojampalam** [comment]
Please explain how this is relevant to this project?
