### ISSUE TITLE
sshfs file writing broken between v0.0.8.0 and v0.0.9.0

### ISSUE THREAD

**Issue by jcoffland** [PowerShell/Win32-OpenSSH#586]
Some change made for version v0.0.9.0 broke file writing in ``sshfs`` mounts.  I have a both 32 and 64-bit Windows 10 systems which I am connecting to over ssh using ``sshfs`` in Linux.  Everything works fine in v0.0.8.0 and earlier.  In v0.0.9.0 and newer, copying a file to an ``sshfs`` mount results in an access error and a new zero byte file on the remote system.  I can create and list directories and even remove files but cannot write anything to either existing or new files.  Note that ``scp`` still works.

Breaking commit: https://github.com/PowerShell/Win32-OpenSSH/commit/c8b8c4b82a5ab061c2e2ced36e0a3424d35792e2

Possibly related issues: https://github.com/PowerShell/Win32-OpenSSH/milestone/14?closed=1

**Comment by manojampalam** [comment]
IS it specific to key based authentication? Does it work with passwd auth?

If so, this might me due to the change mentioned in:
https://github.com/PowerShell/Win32-OpenSSH/issues/494

Can you confirm?

**Comment by jcoffland** [comment]
I'm using password auth.
