### ISSUE TITLE
Permissions denied when installing.

### ISSUE THREAD

**Issue by fjaenal** [PowerShell/Win32-OpenSSH#587]
Please answer the following

**"OpenSSH for Windows" version**

 v0.0.9.0

**OS details**
 Windows Server 208 R2 64 bits

**What is failing**
Pre-Conditions:

1. Not using the .ps1 defualt installer.
2. Using a batch file (.bat) 
3. Both installer are identical when creating the services (creates, ntrights, sdset, etc ...)

If and only if I installed using my .bat I do get a permission denied when trying to connect. In the log extract you can see that maybe its an Active Directory issue: NetUserGetInfo()

**Expected output**
Connected as Administrator using ssh

**Actual output**
Permission Denied

**Additional info**
This does not always happens sometimes it works. [See #562 ]
With the 0.0.1.0 does not happen
only happens since the ssh-agent is being use to handle the security part.

**Log extract**
Logs are the same as #562

**Comment by DarwinJS** [comment]
Can you please post your install script on gist and link it here?

**Comment by manojampalam** [comment]
Please reopen with relevant details if the issue is still relevant.
