### ISSUE TITLE
Launching powershell pauses forever and does not start powershell

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/Win32-OpenSSH#59]
From iTerm on OSX, TERM=xterm per default:

    ssh mike@192.168.1.104
    mike@192.168.1.104's password:
    Microsoft Windows [Version 10.0.10240]
    (c) 2015 Microsoft Corporation. All rights reserved.

    Windows PowerShell sers\Mike>powershell
    Copyright (C) 2015 Microsoft Corporation. All rights reserved.

(this is all - there's no prompt)

**Comment by quamrulmina** [comment]
You have to invoke powershell with "-File -" arguments as shown below.
powershell -File -
look at closed issue #16 for full description.

**Comment by mikemaccana** [comment]
FYI #16 includes a workaround, but has been closed without fixing the issue.

**Comment by manojampalam** [comment]
closing as dupe of #90
