### ISSUE TITLE
Can't communicate with sshd

### ISSUE THREAD

**Issue by tgefen** [PowerShell/Win32-OpenSSH#60]
Hello

I've just installed Win32-OpenSSH on Windows Server 2008 R2. It's up and running.

Now I'm trying to connect from another host. The connection is established but I can't send commands.

When trying with ssh.exe, I get this:
>ssh administrator@MYHOST dir
administrator@MYHOST's password:
Connection reset by MYHOST 

(password is correct)

When trying with Putty, I can login but the console is stuck after I enter a command ("dir") and pressing on ENTER. See:

login as: administrator
administrator@MYHOST's password:
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

administrator@MYHOST C:\Users\Administrator>dir

Do you know this problem?
I did not change any parameter on configuration file.

Thank you

**Comment by quamrulmina** [comment]
You need to issue the windows shell command using "cmd /c dir" format. The following will work for you from any ssh client:
ssh administrator@MYHOST "cmd /c dir"

**Comment by quamrulmina** [comment]
Since we do not know which shell one wants, shell commands should be run passing the shell and the needed parameters.
For Windows cmd shell, the format is "cmd /c dir" style. The full ssh command for the stated issue is:
ssh username@hostname "cmd /c dir"
