### ISSUE TITLE
Cannot take owner of any file when logged in via ssh key authorization

### ISSUE THREAD

**Issue by jhudsoncedaron** [PowerShell/Win32-OpenSSH#611]
Cannot take owner of any file when logged in via ssh key authorization

I keep a copy of chown.exe around since NT4 days for fixing ownership problems.

It does not work via ssh key authorization. We do not allow ssh password authorization over the internet for security reasons.

**Comment by manojampalam** [comment]
This is due to https://github.com/PowerShell/Win32-OpenSSH/issues/494

Do you have an alternative solution to dealing with security problem in #494 ?

**Comment by jhudsoncedaron** [comment]
#494 is not fixable as an admin user logging in can up and replace the sshd binary.

If you manage to block this, sc create junk binPath="c:\windows\system32\cmd /k ..." sc start junk or one of a hundred other paths can undo the change. It just makes legit use harder.

**Comment by manojampalam** [comment]
Not Right. SSH binaries will (eventually in the official package) be protected just like other OS binaries. 

Agree that a compromised client can authenticate and run a privileged task on remote target, but such actions are limited to from the compromised client. 

If a key is injected, it would allow an entry door from any remote client. 

I'm looking for more feedback on how we should proceed.

**Comment by megamorf** [comment]
@LeeHolmes What's your opinion on this?

**Comment by jhudsoncedaron** [comment]
@manojampalam: You haven't caught on yet. That privileged task can go back and replace the authorized_keys file as it will be running as system with all privileges. The protection is a speed bump not a actual fix to a debatable security issue.

In addition, replacing the sshd binary in place is not required to replace the sshd binary. Changing the path to it in services will suffice.

**Comment by manojampalam** [comment]
@jhudsoncedaron I'm hearing you and am with you. This approach would only shut down an easy back door. 

Waiting for @LeeHolmes input on this.

**Comment by manojampalam** [comment]
I've followed up on this and we are in agreement that this restriction is an over kill. I'll revert the change in April-Mid drop and create necessary documentation around securing authorized_keys.
