### ISSUE TITLE
Where the file scp to Win32-OpenSSH?

### ISSUE THREAD

**Issue by junjiemars** [PowerShell/Win32-OpenSSH#62]
I can run 
```shell
scp -v one-file username@Win32-OpenSSH-host:/c/Users/username
```
and ssh prompt the file had been copied to win32-openssh windows, but I can't find the file.

**Comment by quamrulmina** [comment]
your syntax is wrong. it should be given as:
scp -v one-file username@Win32-OpenSSH-host:c:/Users/username
or
scp -v one-file username@Win32-OpenSSH-host:c:\Users\username

Windows paths should be given in Windows style drive letter and directory format. Both backslash and forward slash are accepted by our Win32 port openssh.
A better way is leave the user's home directory on the target as that is where things are assumed to go if not specified.
scp one-file username@Win32-OpenSSH-host:

one-file will be found in c:\Users\username\one-file  in all cases.

**Comment by junjiemars** [comment]
@quamrulmina You are right, It's works, thank you.

**Comment by knocte** [comment]
This doesn't work for me, I always get this error:

```
packet_write_wait: Connection to 55.55.55.55 port 22: Broken pipe
lost connection
```

Do I need to first enable scp commands in the server somehow?
