### ISSUE TITLE
Issues with stat() implementation for Windows

### ISSUE THREAD

**Issue by manojampalam** [PowerShell/Win32-OpenSSH#648]
Tracked TODO in code:
win32\win32compat\fileio.c

int
fileio_stat(const char *path, struct _stat64 *buf)
	/*
	* If we doesn't have sufficient permissions then _wstat4() is returning "file not found"
	* Using the following to work around this. 
	* TODO - Replace the above call with GetFileAttributesEx 
	*/

**Comment by bingbing8** [comment]
the scenario is that in remote sftp session, dir should list all the file even the logon user does not have access to the file, but get should failed with access denied. The current behavior is dir does not list the file the user does not have permission, which is not expected.
