### ISSUE TITLE
Installation instructions for Windows?

### ISSUE THREAD

**Issue by LuisBosquez** [PowerShell/Win32-OpenSSH#649]
I can't find any easy to follow installation instructions for Windows. The INSTALL file seems to be written for Linux.

What should one do after downloading the zip and running the ps1 scripts?

**Comment by LuisBosquez** [comment]
The readme also doesn't provide enough guidance.

**Comment by manojampalam** [comment]
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by LuisBosquez** [comment]
Thanks!
