### ISSUE TITLE
sftp-server unresolved external symbol openbsd_compat.lib PathCanonicalize

### ISSUE THREAD

**Issue by kangjoni76** [PowerShell/Win32-OpenSSH#65]
Building lastest source producing build error unresolved external symbol pathcanonicalizeA openbsd_compatible.lib(real path.obj) using vs2015 RTM. looking at sftp-server project properties - > linker -> input -> additional dependencies shlwapi.lib already included, what's wrong with this?

**Comment by quamrulmina** [comment]
The problem has been fixed and code updated. The 32 bit build needed the header file to be added.

**Comment by quamrulmina** [comment]
Please verify the fix and then close the issue if the fix worked for you.

**Comment by kangjoni76** [comment]
OK trying it now, I'll confirm that to close issue if it succeds

**Comment by kangjoni76** [comment]
it works , and my issue #56 also working .. thanks.
Regards Joni
