### ISSUE TITLE
Please only update file version resource on ssh-lsa.dll when the code changes

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#650]
For the Chocolatey package I am having some trouble updating ssh-lsa.dll even when using Windows built-in pending file updates support (replace on reboot).  (Also described here: http://stackoverflow.com/questions/4443578/how-to-replace-locked-dll-was-inuse)

UPDATE: I am guessing that lsass.exe starts before PendingFileRenameOperations registry key is processed.  I believe this means that it will always require a double-reboot to update this file.  
**I have tested the problem on Win7 and Nano - and the file won't overwrite with one reboot using PendingFileRenameOperations.**

I have noticed that the versions on ssh-lsa.dll change even when the code does not seem to (File size stays the same).

Since this file is proving very difficult to update, it would be helpful if it only changed versions when there was code changes to ssh-lsa.dll specifically.  I can compare file sizes and only update when there is a size difference, but then it looks like the install script is not doing the correct thing because the version in the ZIP is newer.

So if version 0.0.8.0 was the last time ssh-lsa.dll actually had code changes, it would stay that version until it's code is actually updated.

I am not necessarily making the case to do this for all files - but if updating this one is always going to take two reboots - it would be helpful for the version to reflect when the update process actually needs to happen.

It would take some getting used to by users for the version to not move forward, but I'm thinking that a little confusion is preferable to taking two reboots on every machine on every release just to get the same code moved into place so that the cosmetic version change looks right.

Thanks for your consideration.

**Comment by DarwinJS** [comment]
FYI - I am working support into the package so that two runs of the package (each followed by a reboot) can accomplish the update of ssh-lsa.dll.  

However, this support
1. will require a special new switch and 
2. the package will NOT orchestrate the reboots or re-running of itself.
3. is smart enough to install fine on first time install with only one reboot (as before)

The best way for mass updating would be to do a manual run of the new version on a test machine and watch the log messages to understand IF ssh-lsa.dll is updated - if so, create the orchestration scripting required to accomplish the two reboot solution.  This manual pre-qualification step should already be common practice for anyone doing software deployment automation at scale.

If the new switch is not used, the package will continue to do as it always has - 
1. only try to update ssh-lsa.dll if the file size has changed and 
2. **FAIL** to make the update upon reboot due to the presumed ineffectiveness of PendingFileRenameOperations to work on lsass.exe locked files.

**Comment by DarwinJS** [comment]
It may also make sense for the zip file to provide a new helper script "upgrade-sshlsa.ps1" or similar which can be used to ONLY remove ssh-lsa.dll from the registry key.  Although it would be very similar to "uninstall-sshlsa.ps1", just having the script would also be a cue that there are special procedures required for updating ssh-lsa.dll.  It could also contain logic to indicate whether an upgrade is needed at all for the current "from" and "to" versions where it is run - maybe it kicks out a exit code that reveals whether a reboot is needed.  It would also be best for it to be runnable WITHOUT the folder being placed in it's final position so that automation developers can learn whether an upgrade is needed BEFORE making any changes to the target system.

**Comment by manojampalam** [comment]
Retaining version on ssh-lsa.dll might cause confusion down the line. I'm attempting to get rid of this dll altogether. Will let you know how it works out.

**Comment by manojampalam** [comment]
@DarwinJS Good news. I've managed to get rid of ssh-lsa.dll altogether. There will be no reboot restriction on setup now. 
https://github.com/PowerShell/Win32-OpenSSH/issues/657
