### ISSUE TITLE
Understanding host file setup

### ISSUE THREAD

**Issue by ZenoArrow** [PowerShell/Win32-OpenSSH#653]
Apologies up front if this is the wrong forum for the following questions, have looked for answers elsewhere, no luck so far.

I'm trying to understand the following sections from the install notes ( https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH ):

"
Setup SSH host keys (this will generate all the 'host' keys that sshd expects when its starts)

    .\ssh-keygen.exe -A

Secure SSH host keys (optional)

    Start-Service ssh-agent
    download psexec from here
    launch cmd.exe as SYSTEM - psexec.exe -i -s cmd.exe
    register host keys in above cmd.exe
    ssh-add ssh_host_dsa_key
    ssh-add ssh_host_rsa_key
    ssh-add ssh_host_ecdsa_key
    ssh-add ssh_host_ed25519_key
    host private keys are now securely stored by ssh-agent, private key files can be removed at this point.
"

Two questions:

1. I understand that .\ssh-keygen.exe -A is creating keys for sshd to use, but I don't understand how sshd uses these keys. My prior understanding was that all key-based validation in ssh happens between a public and private key pair, with the private key being stored on the client computer. I don't understand why sshd would need generic keys for the different encryption algorithms to be setup. What am I missing here? Are these keys used in addition to the public/private key pair for an additional authentication step?

2. I understand adding keys to ssh-agent, but why does this take place in cmd.exe rather than PowerShell?

Thank you in advance.

**Comment by bagajjal** [comment]
1) The keys generated will be used for the authenticating host.
search for the "host key" here
https://tools.ietf.org/html/rfc4253#page-13
![image](https://cloud.githubusercontent.com/assets/23668037/24781991/495ff59c-1af8-11e7-8aac-1a42d3ccabc8.png)

2) it doesn't matter whether we do in cmd.exe or powershell as we are invoking ssh-agent. Its not specific to cmd.exe/powershell

**Comment by ZenoArrow** [comment]
Thank you bagajjal for the link related to host keys, it gives me plenty of information to help explore further.

Just one follow up question, if I wanted to propose an alternative set of install notes, what's the best way to do that? Should I clone the repository, make the wiki changes, and submit these changes as a pull request?

Thanks.

**Comment by ZenoArrow** [comment]
To anyone reading this that was also interested in how SSH works, I'd recommend the following article, which I found very useful in understanding how the different keys used in SSH work together:
https://www.digitalocean.com/community/tutorials/understanding-the-ssh-encryption-and-connection-process

With reference to the host key question I'd asked previously...

>"When a TCP connection is made by a client, the server responds with the protocol versions it supports. If the client can match one of the acceptable protocol versions, the connection continues. The server also provides its public host key, which the client can use to check whether this was the intended host."

**Comment by bagajjal** [comment]
@ZenoArrow, wiki changes can't be done with pull request. We have the permissions to change the wiki.
Please let me know the changes so that we can evaluate and make the necessary changes.
