### ISSUE TITLE
Latest Win32-OpenSSH release page is hard to find.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/Win32-OpenSSH#654]
This is just a feedback!

I took me minutes to try to find the release page in order to get the latest version of Win32-OpenSSH
The main page should have a link to this release page for everyone to have easy access.

Currently, there's no link available and it's making hard to find the files.

I was lucky that I documented the link back in November in my blog post.

Just a suggestion!  I think it will help.

Thanks,
Max

**Comment by MaximoTrinidad** [comment]
Ok!!  I found the way to get to the "Release" page.  I'm blind!  
I see it on the top of the page.

But, it still would help to have another 'descriptive' link in the main page as you read the "README" information on OpenSSH.  I got spoiled with the PowerShell page.

Thanks,
Max

**Comment by bagajjal** [comment]
Which URL are you referring to add the descriptive link?

Is the wiki page not clear?
https://github.com/PowerShell/Win32-OpenSSH/wiki

**Comment by MaximoTrinidad** [comment]
Hi @bagajjal, 

Thank You!  I learn another link.  

But, I went the longer route and started reading the ReadMe document on the main page.  
My suggestion is to include the Wiki link in the ReadMe page. I think it would help.

Sorry! I'm still getting use to GitHub. 

Thanks for your patience,
Max

**Comment by bagajjal** [comment]
Are you referring to https://github.com/PowerShell/Win32-OpenSSH/blob/L1-Prod/README?

**Comment by MaximoTrinidad** [comment]
Yes!!  That page.  I think that including both the wiki and the release link won't hurt,
:)

**Comment by bagajjal** [comment]
Unfortunately we can't edit that because its the readme of the openssh community.
We cloned the openssh code and porting to windows operating system.

I feel the wiki link is good enough as it is right below the branch name.
![image](https://cloud.githubusercontent.com/assets/23668037/24813189/f92ddbb8-1b81-11e7-844c-64db3cf7f423.png)

You can always raise new issue for any help, we are happy to help you anytime.

**Comment by MaximoTrinidad** [comment]
No worries!  I'll be blogging more on Win32-OpenSSH when I get the other issue i posted total resolved.

I appreciate the help,
Max
