### ISSUE TITLE
Win32-OpenSSH - How to setup the AuthorizedKeys in the Windows User.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/Win32-OpenSSH#655]
Please answer the following

**"OpenSSH for Windows" version**
0.0.11.0

**OS details**
Windows 10 Pro

**What is failing**
No AuthorizationKeys found!  When executing script in Breaking Change note;
$authorizedKeyPath = "C:\Users\mtrinidad\.ssh\authorized_keys"
$acl = get-acl $authorizedKeyPath
$ar = New-Object  System.Security.AccessControl.FileSystemAccessRule("NT Service\sshd", "Read", "Allow")
$acl.SetAccessRule($ar)
Set-Acl  $authorizedKeyPath $acl

![brkchge_2017-04-07_12-29-03](https://cloud.githubusercontent.com/assets/19892435/24809608/fed15c78-1b8d-11e7-8487-7c48e0869a4f.jpg)

**Expected output**
No errors!

**Actual output**
PS C:\Program Files\PowerShell\6.0.0-alpha.18> $acl = get-acl $authorizedKeyPath
get-acl : Cannot find path 'C:\Users\mtrinidad\.ssh\authorized_keys' because it does not exist.

![brkchge_2_2017-04-07_12-29-03](https://cloud.githubusercontent.com/assets/19892435/24809907/5cbe346e-1b8e-11e7-9bef-d4070b0bc5df.jpg)

**Additional Notes**
Can't find any documentation on how to create the "authorized_keys".

**Comment by manojampalam** [comment]
authorized_keys is used as part of key based authentication

See https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples

**Comment by MaximoTrinidad** [comment]
Thanks for the explanation.  Also, I realized that the "authorized_keys" was a folder name and not a file.

So, after creating the folder, then I was able to run the PowerShell script.
:)
