### ISSUE TITLE
Win32-OpenSSH - PowerShell can't connect Linux to Windows. 

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/Win32-OpenSSH#656]
Please answer the following

**"OpenSSH for Windows" version**
0.0.11.0

**OS details**
Linux Ubuntu 16.04.2 LTS connecting to Windows 10 Pro
Both systems using PowerShell v6.0.0-alpha18

**What is failing**
Following command fails:
enter-pssession -HostName earth2 -UserName max_t 

enter-pssession : The background process reported an error with the following message: The SSH client session has 
ended with error message: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.

**Expected output**
To PowerShell Linux to Windows PowerShell v6.0.0-Alpha18

**Actual output**
enter-pssession : The background process reported an error with the following message: The SSH client session has 
ended with error message: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.
At line:1 char:1
+ enter-pssession -HostName earth2 -UserName max_t
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Enter-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.PowerSh 
   ell.Commands.EnterPSSessionCommand

**Additional Comment**
I was able to connect using older version of Win32-OpenSSH and before PowerShell v6.0.0-Alpha18.

![poshlinux2windows 2017-04-07 23-59-16](https://cloud.githubusercontent.com/assets/19892435/24825588/3579d60e-1bef-11e7-9503-087afb13271d.png)

**Comment by manojampalam** [comment]
Please add a reference to the instructions used to setup Powershell over ssh in Linux. 
Was an explicit subsystem added for Powershell?

**Comment by MaximoTrinidad** [comment]
Yes! 

Subsystem	powershell	C:/Program Files/PowerShell/6.0.0.18/powershell.exe -sshs -NoLogo -NoProfile

:)

**Comment by MaximoTrinidad** [comment]
Sorry!

In Windows:
Subsystem powershell C:/Program Files/PowerShell/6.0.0.18/powershell.exe -sshs -NoLogo -NoProfile

In Linux:
Subsystem powershell powershell -sshs -NoLogo -NoProfile

:)

**Comment by MaximoTrinidad** [comment]
It work Windows to Linux but not the other way.

**Comment by DarwinJS** [comment]
Although it does not list on the public website due to being a pre-release, I maintain a chocolatey package for powershell-core for windows here: https://chocolatey.org/packages/powershell-core

**Comment by MaximoTrinidad** [comment]
Hi @DarwinJS,

Aah! I can't get the link to open.  I tried everything to get this to work.  I'm presenting in the next hour and I was trying to demo PowerShell Enter-PSSession command connecting Linux to Windows.

No Worries! At least I got the Windows to Linux connection working,  Is interesting how one update can break what was working.

:)

**Comment by DarwinJS** [comment]
@MaximoTrinidad 

This should install chocolatey:
```
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
```
Other methods are here if that does not work: https://chocolatey.org/install

Then start a fresh prompt and run this to install powershell-core v18:
```
choco install powershell-core -confirm
```

**Comment by MaximoTrinidad** [comment]
I tried using the choco install powershell-code -confirm and I'm getting an error:
"powershell-core not installed. The package was not found with the source(s) listed."

This is interesting because I already have PowerShell v6.0.0-alpha18 installed.

Should I uninstall and try again.

:)

**Comment by DarwinJS** [comment]
Oh I didn't know you had it already.  Add '-pre' to try, but it will just
tell you it is installed by another means.

**Comment by PaulHigin** [comment]
@MaximoTrinidad This looks like SSH host key revocation error.  PowerShell includes the SSH error message text in its error but it looks like it is not including the entire SSH error message and is likely a bug in PowerShell SSH remoting (I'll create an issue on PowerShell github).

This happens to me anytime I install a new version of Win32-OpenSSH on my host machine, and generate new host keys.  You can repro it by deleting your existing host keys and creating new ones (ssh-keygen.exe -A).

To fix this you need to edit the known_hosts file (I just delete mine) to remove the old host key on your client machine (c:\Users\<UserName>\.ssh\known_hosts).  After you do this SSH will ask you to re-verify the host identity using the ECDSA key fingerprint.

**Comment by PaulHigin** [comment]
FYI the entire error message should look like this
```powershell
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:Etb4yw1QyVJnP4eGKdvOG/xPy9F5rKEw+Xk02wXmJGU.
Please contact your system administrator.
Add correct host key in C:\\Users\\UserName/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in C:\\Users\\UserName/.ssh/known_hosts:1
ECDSA host key for LocalComputerName has changed and you have requested strict checking.
Host key verification failed.
```

**Comment by MaximoTrinidad** [comment]
Thanks @PaulHigin!  I will try it during the weekend. I've been so busy lately that's not funny. 
:)

**Comment by MaximoTrinidad** [comment]
So,  @PaulHigin, Windows to Linux is fine. The issue is from Linux to Windows is not working,  I wonder what I need to do in Linux to correct the issue.
:)
```
PS /home/maxt> enter-pssession -HostName earth2 -UserName max_t                                                         
enter-pssession : The background process reported an error with the following message: The SSH client session has 
ended with error message: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.
At line:1 char:1
+ enter-pssession -HostName earth2 -UserName max_t
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Enter-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.PowerSh 
   ell.Commands.EnterPSSessionCommand

```

**Comment by PaulHigin** [comment]
Hi @MaximoTrinidad, it doesn't matter which direction the connection is made.  This error message (of which only part is reported by PowerShell remoting) means that the SSH host keys no longer work and that you need to update the known_hosts file on the client appropriately.  For a Linux client you should be able to find the file at /home/max_t/.ssh/.

**Comment by MaximoTrinidad** [comment]
Got it @PaulHigin!  I will try again later.

**Comment by MaximoTrinidad** [comment]
@DarwinJS , @PaulHigin 

Whaoo!!  I finally caught up with this after so much reinstalling and trying trial-error.

Well, did reinstall both the Win32-OpenSSH and openssh-server.  Just to find out the following which I didn't experience before upgrading these packages.

I got my hosts files set to resolve my machine names to a specific IP Address, as I'm using workgroup environment.

So, whole issue was due to Linux OpenSSH, or maybe PowerShell, is not resolving my IP Address to its hostname.

If I use only the IP-Address in Enter-PSSession in the '-hostname' paramater then I'm fine.
(see images)

Is this a bug somewhere?  Again, I'm fine using hostname Windows-to-Linux.

![linux_openssh_01](https://cloud.githubusercontent.com/assets/19892435/25071683/96fdfc0a-228b-11e7-813e-a9493a897404.png)

![linux_openssh_02](https://cloud.githubusercontent.com/assets/19892435/25071684/9c7fe67a-228b-11e7-88bd-24607168102d.png)

![linux_openssh_03](https://cloud.githubusercontent.com/assets/19892435/25071687/a1bab5ac-228b-11e7-82fb-8d85c81a3e0a.png)

**Comment by MaximoTrinidad** [comment]
Yeap!  In my blog post back in December 2016, I could use hostname as well as the IP-Address in Enter-PSSession to connect from Linux-to-Windows machine.
http://www.maxtblog.com/2016/12/powershell-open-source-windows-psremoting-to-linux-with-openssh/ 
:)

**Comment by PaulHigin** [comment]
You can still use either host name or IP address for establishing an SSH connection.  The problem above is that "earth2" host name is recorded in the known_hosts file and is using older non-matching host keys.  When you use the IP address SSH creates a *new* entry in the known_hosts file with the correct host keys.  In order to get "earth2" host name working again you need to delete that entry out of the known_hosts file (or just delete the known_hosts file) and let SSH re-verify that the host name and fingerprint is correct for earth2 host name.

Note that this is SSH and not PowerShell.  PowerShell is using SSH to establish the connection and as a transport for remoting, and this is standard SSH behavior.

**Comment by MaximoTrinidad** [comment]
Thanks @PaulHigin for your patience!!  I will look into it tonight and see if I can get it cleared this time.
:)

**Comment by MaximoTrinidad** [comment]
Hum! It didn't work for me.  I removed the entry from the unknown_hosts file and even deleted the file from my windows .ssh folder.  I can't make it work using the hostname.  I can only use the IP-Address.
After my monthly online user group tomorrow, I'm going to revert back to an older OpenSSH and try again just to isolate the issue I'm having now.  Again, back in December I got it working.

I'm just using the "Enter-PSSession" cmdlet, and I haven't try any other way.

![pssessionerrorhostname_ 2017-04-18 21-29-54](https://cloud.githubusercontent.com/assets/19892435/25159683/84fd56b8-247f-11e7-896b-b4ef28ab0339.png)

**Comment by PaulHigin** [comment]
I am sorry you are having so much trouble with this.  The whole SSH error message includes the actual location of the known_hosts file affected, and it may be that you are modifying or removing the wrong file.  A good reason why we need to get this fixed in PowerShell.  But a workaround is to attempt the connection with SSH, so that you get the complete error message:
```powershell
PS > ssh max_t@earth2
```
This is equivalent to what PowerShell does when establishing the SSH connection and should return the same error but with the *complete* error message, and identify the host key and file affected by the error.

**Comment by MaximoTrinidad** [comment]
@PaulHigin 
Awesome!! Sorry for the long delay!! 

I did upgrade the OpenSSH to the latest and then execute the command you gave me "ssh max_t@earth2".  This provided me with some information and I was able to clean up the issue on my Linux machine.

Is working now!!

![ssh_result_ 2017-05-04 15-43-29](https://cloud.githubusercontent.com/assets/19892435/25723376/c648b8e8-30e5-11e7-8412-c09f1d92f788.png)

![screenshot from 2017-05-04 16-17-03](https://cloud.githubusercontent.com/assets/19892435/25723412/e2322e68-30e5-11e7-90e4-5eb2da697ed4.png)


Thanks a lot,
Max
