### ISSUE TITLE
Not Login with SSH Keys

### ISSUE THREAD

**Issue by rpereda** [PowerShell/Win32-OpenSSH#660]
Please answer the following

**"OpenSSH for Windows" version**
0.0.11.0

**OS details**
Windows Server 2012 R2 Standard

**What is failing**

I'm not able able to login using my ssh keys

**Expected output**

Login using my ssh keys

**Actual output**

It is asking me for the user password instead of using my keys for validation.
* I've followed this guide without any issue https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples

* It seems the service is not able to read the folder authorized_keys, I've tried using the admin user as logon in the service and no luck, please your support-

Below some logs:

From the server:

3048 03:38:09 645 debug1: attempt 1 failures 0
3048 03:38:09 645 debug1: userauth_pubkey: test whether pkalg/pkblob are acceptable for RSA SHA256:ueiywq2iC7n71dmluCAZqixYO9/Rga38WZXdg9IxXGQ
3048 03:38:09 645 debug1: trying public key file C:\\Users\\Administrator/.ssh/authorized_keys
3048 03:38:09 645 debug1: Could not open authorized keys 'C:\\Users\\Administrator/.ssh/authorized_keys': Permission denied

**Comment by manojampalam** [comment]
Did you note this from https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.11.0

**NOTE - Breaking Change**
  - Due to a security issue that got fixed in this release, SSHD account now needs read access to "authorized_keys. Otherwise pubkey authentication will fail. Do the following:
 ```
    $authorizedKeyPath = "c:\users\user\.ssh\authorized_keys"
    $acl = get-acl $authorizedKeyPath
    $ar = New-Object  System.Security.AccessControl.FileSystemAccessRule("NT Service\sshd", "Read", "Allow")
    $acl.SetAccessRule($ar)
    Set-Acl  $authorizedKeyPath $acl
```

**Comment by rpereda** [comment]
Hi manojampalam ,

Thanks for your reply however this is not the case since I already did those steps, and I can validate that the permissions has been granted.

<img width="917" alt="screen shot 2017-04-12 at 11 53 45 am" src="https://cloud.githubusercontent.com/assets/3868410/24969643/07fd8e38-1f77-11e7-868b-068c69326038.png">
