### ISSUE TITLE
Cannot contribute to Wiki

### ISSUE THREAD

**Issue by ChristophB125** [PowerShell/Win32-OpenSSH#661]
I found some mistakes in the Wiki that I wanted to fix.

I followed the instructions [here](https://gist.github.com/larrybotha/10650410) but I cannot contribute becausewhen I fork the Win32-OpenSSH repository, the Wiki does not get forked as well (this seems to be a GitHub issue by looking at the comments [here](http://stackoverflow.com/a/36321244/1810304).
I can of course clone the wiki of the master branch but then I do not have push rights to it

Should I otherwise just open an issue and tell you the proposed corrections in the documentation?

**Comment by bagajjal** [comment]
Yes, WIKI can't be cloned / pushed by a change.
Please open an issue and propose the necessary changes, we will evaluate and make the necessary changes
