### ISSUE TITLE
authorized_keys when created with NotePad fails

### ISSUE THREAD

**Issue by ThomasMConnors** [PowerShell/Win32-OpenSSH#662]
**"OpenSSH for Windows" version**
0.0.11.0

**OS details**
Windows Server 2012 R2 Standard

authorized_keys when created with NotePad fails. Default w/notepad is Unicode and not ASCII.  This drove me crazy for a half a day.

**Expected output**
Should would with both ASCII & Unicode. (or at least documented in the install notes for now.

**Actual output**
N/A

**Comment by manojampalam** [comment]
It should work with UTF-8. Try saving the file in that format.
