### ISSUE TITLE
Local server account fails w/Key Auth

### ISSUE THREAD

**Issue by ThomasMConnors** [PowerShell/Win32-OpenSSH#663]
"OpenSSH for Windows" version
 0.0.11.0

OS details
 Windows Server 2012 R2 Standard

I can SSH/SFTP to a my OpenSSH server using a domain account on the server. With a Windows server local account it works for password auth but not public/private keys

5664 21:51:22 347 client pid 4308 connected
5664 21:51:22 347 debug1: spawned worker 3756 for agent client pid 4308
3756 21:51:22 393 agent_start pid:3756, dbg:0, child:1, pipe:408
3756 21:51:22 393 debug3: connection io 000000E5CBE34010 #bytes:0 state:0
3756 21:51:24 956 debug3: connection io 000000E5CBE34010 #bytes:4 state:1
3756 21:51:24 956 debug3: connection io 000000E5CBE34010 #bytes:952 state:2
3756 21:51:24 956 debug2: client type: 3
3756 21:51:24 956 debug1: process agent request type 200
3756 21:51:24 956 debug1: unable to generate token for user tomc
3756 21:51:24 956 debug3: connection io 000000E5CBE34010 #bytes:5 state:3
3756 21:51:26 800 debug1: iocp error: 109 on 000000E5CBE34010 \n
3756 21:51:26 800 debug1: connection 000000E5CBE34010 clean up
3756 21:51:26 800 debug1: iocp error: 6 on 0000000000000000 \n

3904 21:51:22 253 debug3: socket:552, io:00000074026EF6B0, fd:5 
3904 21:51:22 253 debug3: fd 5 is not O_NONBLOCK
3904 21:51:22 253 debug3: pipe - r-h:520,io:00000074026A1FD0,fd:6  w-h:448,io:00000074026C8430,fd:7
3904 21:51:22 253 debug3: spawning "C:\\Program Files\\OpenSSH-Win64\\sshd.exe"
3904 21:51:22 253 debug3: Register child 000000000000020C pid 4308, 0 zombies of 0
3904 21:51:22 253 debug3: close - io:00000074026EF6B0, type:1, fd:5, table_index:5
3904 21:51:22 253 debug1: Forked child 4308.
3904 21:51:22 253 debug3: close - io:00000074026C8430, type:2, fd:7, table_index:7
4308 21:51:22 347 debug1: child socket: 552
4308 21:51:22 347 debug1: child startup_pipe: 448
4308 21:51:22 347 Connection from 10.1.4.40 port 17779 on 10.45.33.49 port 22
4308 21:51:22 347 debug1: Client protocol version 2.0; client software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
4308 21:51:22 347 debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8 pat OpenSSH_6.6.1* compat 0x04000000
4308 21:51:22 347 debug1: Local version string SSH-2.0-OpenSSH_7.5
4308 21:51:22 347 debug1: Enabling compatibility mode for protocol 2.0
4308 21:51:22 347 debug2: fd 3 setting O_NONBLOCK
4308 21:51:22 347 debug3: socket:0, socktype:1, io:00000078D3C96DA0, fd:5 
4308 21:51:22 347 debug3: list_hostkey_types: ssh-dss key not permitted by HostkeyAlgorithms
4308 21:51:22 347 debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
4308 21:51:22 347 debug3: send packet: type 20
4308 21:51:22 347 debug1: SSH2_MSG_KEXINIT sent
4308 21:51:22 706 debug3: receive packet: type 20
4308 21:51:22 706 debug1: SSH2_MSG_KEXINIT received
4308 21:51:22 706 debug2: local server KEXINIT proposal
4308 21:51:22 706 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
4308 21:51:22 706 debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
4308 21:51:22 706 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
4308 21:51:22 706 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
4308 21:51:22 706 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
4308 21:51:22 706 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
4308 21:51:22 706 debug2: compression ctos: none
4308 21:51:22 706 debug2: compression stoc: none
4308 21:51:22 706 debug2: languages ctos: 
4308 21:51:22 706 debug2: languages stoc: 
4308 21:51:22 706 debug2: first_kex_follows 0 
4308 21:51:22 706 debug2: reserved 0 
4308 21:51:22 706 debug2: peer client KEXINIT proposal
4308 21:51:22 706 debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
4308 21:51:22 706 debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-ed25519,ssh-rsa,ssh-dss
4308 21:51:22 706 debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
4308 21:51:22 706 debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
4308 21:51:22 706 debug2: MACs ctos: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
4308 21:51:22 706 debug2: MACs stoc: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
4308 21:51:22 706 debug2: compression ctos: none,zlib@openssh.com,zlib
4308 21:51:22 706 debug2: compression stoc: none,zlib@openssh.com,zlib
4308 21:51:22 706 debug2: languages ctos: 
4308 21:51:22 706 debug2: languages stoc: 
4308 21:51:22 706 debug2: first_kex_follows 0 
4308 21:51:22 706 debug2: reserved 0 
4308 21:51:22 706 debug1: kex: algorithm: curve25519-sha256@libssh.org
4308 21:51:22 706 debug1: kex: host key algorithm: ecdsa-sha2-nistp256
4308 21:51:22 706 debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none
4308 21:51:22 706 debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none
4308 21:51:22 706 debug1: expecting SSH2_MSG_KEX_ECDH_INIT
4308 21:51:23 112 debug3: receive packet: type 30
4308 21:51:23 112 debug3: send packet: type 31
4308 21:51:23 112 debug3: send packet: type 21
4308 21:51:23 112 debug2: set_newkeys: mode 1
4308 21:51:23 112 debug1: rekey after 4294967296 blocks
4308 21:51:23 112 debug1: SSH2_MSG_NEWKEYS sent
4308 21:51:23 112 debug1: expecting SSH2_MSG_NEWKEYS
4308 21:51:23 472 debug3: receive packet: type 21
4308 21:51:23 472 debug1: SSH2_MSG_NEWKEYS received
4308 21:51:23 472 debug2: set_newkeys: mode 0
4308 21:51:23 472 debug1: rekey after 4294967296 blocks
4308 21:51:23 472 debug1: KEX done
4308 21:51:23 893 debug3: receive packet: type 5
4308 21:51:23 893 debug3: send packet: type 6
4308 21:51:24 237 debug3: receive packet: type 50
4308 21:51:24 237 debug1: userauth-request for user tomc service ssh-connection method none
4308 21:51:24 237 debug1: attempt 0 failures 0
4308 21:51:24 237 debug2: parse_server_config: config reprocess config len 242
4308 21:51:24 237 debug2: input_userauth_request: setting up authctxt for tomc
4308 21:51:24 237 debug2: input_userauth_request: try method none
4308 21:51:24 237 Failed none for tomc from 10.1.4.40 port 17779 ssh2
4308 21:51:24 237 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"
4308 21:51:24 237 debug3: send packet: type 51
4308 21:51:24 597 debug3: receive packet: type 50
4308 21:51:24 597 debug1: userauth-request for user tomc service ssh-connection method publickey
4308 21:51:24 597 debug1: attempt 1 failures 0
4308 21:51:24 597 debug2: input_userauth_request: try method publickey
4308 21:51:24 597 debug1: userauth_pubkey: test whether pkalg/pkblob are acceptable for RSA SHA256:2lCcCbp9Rgtg8XFwsfp1MWxo94KIcHd+JIeLmFNAkaI
4308 21:51:24 597 debug1: trying public key file C:\\Users\\tomc/.ssh/authorized_keys
4308 21:51:24 597 debug1: matching key found: file C:\\Users\\tomc/.ssh/authorized_keys, line 2 RSA SHA256:2lCcCbp9Rgtg8XFwsfp1MWxo94KIcHd+JIeLmFNAkaI
4308 21:51:24 597 debug3: send packet: type 60
4308 21:51:24 597 debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa
4308 21:51:24 597 Postponed publickey for tomc from 10.1.4.40 port 17779 ssh2
4308 21:51:24 956 debug3: receive packet: type 50
4308 21:51:24 956 debug1: userauth-request for user tomc service ssh-connection method publickey
4308 21:51:24 956 debug1: attempt 2 failures 0
4308 21:51:24 956 debug2: input_userauth_request: try method publickey
4308 21:51:24 956 debug3: userauth_pubkey: have signature for RSA SHA256:2lCcCbp9Rgtg8XFwsfp1MWxo94KIcHd+JIeLmFNAkaI
4308 21:51:24 956 debug1: auth agent did not authorize client tomc
4308 21:51:24 956 debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa
4308 21:51:24 956 Failed publickey for tomc from 10.1.4.40 port 17779 ssh2: RSA SHA256:2lCcCbp9Rgtg8XFwsfp1MWxo94KIcHd+JIeLmFNAkaI
4308 21:51:24 956 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"
4308 21:51:24 956 debug3: send packet: type 51
4308 21:51:25 300 debug3: receive packet: type 50
4308 21:51:25 300 debug1: userauth-request for user tomc service ssh-connection method keyboard-interactive
4308 21:51:25 300 debug1: attempt 3 failures 1
4308 21:51:25 300 debug2: input_userauth_request: try method keyboard-interactive
4308 21:51:25 300 debug1: keyboard-interactive devs 
4308 21:51:25 300 debug1: auth2_challenge: user=tomc devs=
4308 21:51:25 300 debug1: kbdint_alloc: devices ''
4308 21:51:25 300 debug2: auth2_challenge_start: devices 
4308 21:51:25 300 Failed keyboard-interactive for tomc from 10.1.4.40 port 17779 ssh2
4308 21:51:25 300 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"
4308 21:51:25 300 debug3: send packet: type 51
4308 21:51:26 800 Connection closed by authenticating user tomc 10.1.4.40 port 17779
4308 21:51:26 800 debug1: do_cleanup
3904 21:51:26 800 debug3: close - io:00000074026A1FD0, type:2, fd:6, table_index:6
3904 21:51:26 800 debug3: zombie'ing child at index 0, 0 zombies of 1
3904 21:51:26 800 debug3: raise sig:3
3904 21:51:26 800 debug3: Unregister child at index 0, 1 zombies of 1
3904 21:51:26 800 debug3: process_queued_signals: WARNING - A signal has interrupted and was processed
3904 22:14:02 238 debug3: socket:448, io:00000074026EF6B0, fd:5 
3904 22:14:02 238 debug3: fd 5 is not O_NONBLOCK
3904 22:14:02 238 debug3: pipe - r-h:520,io:00000074026A1FD0,fd:6  w-h:596,io:00000074026C3390,fd:7
3904 22:14:02 238 debug3: spawning "C:\\Program Files\\OpenSSH-Win64\\sshd.exe"
3904 22:14:02 238 debug3: Register child 00000000000001C8 pid 6232, 0 zombies of 0
3904 22:14:02 238 debug3: close - io:00000074026EF6B0, type:1, fd:5, table_index:5
3904 22:14:02 238 debug1: Forked child 6232.
3904 22:14:02 238 debug3: close - io:00000074026C3390, type:2, fd:7, table_index:7
6232 22:14:02 332 debug1: child socket: 448
6232 22:14:02 332 debug1: child startup_pipe: 596
6232 22:14:02 332 Connection from 10.1.4.40 port 18114 on 10.45.33.49 port 22
6232 22:14:02 332 debug1: Client protocol version 2.0; client software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
6232 22:14:02 332 debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8 pat OpenSSH_6.6.1* compat 0x04000000
6232 22:14:02 332 debug1: Local version string SSH-2.0-OpenSSH_7.5
6232 22:14:02 332 debug1: Enabling compatibility mode for protocol 2.0
6232 22:14:02 332 debug2: fd 3 setting O_NONBLOCK
6232 22:14:02 332 debug3: socket:0, socktype:1, io:000000F5A8066DA0, fd:5 
6232 22:14:02 332 debug3: list_hostkey_types: ssh-dss key not permitted by HostkeyAlgorithms
6232 22:14:02 332 debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
6232 22:14:02 332 debug3: send packet: type 20
6232 22:14:02 332 debug1: SSH2_MSG_KEXINIT sent
6232 22:14:02 691 debug3: receive packet: type 20
6232 22:14:02 691 debug1: SSH2_MSG_KEXINIT received
6232 22:14:02 691 debug2: local server KEXINIT proposal
6232 22:14:02 691 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
6232 22:14:02 691 debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
6232 22:14:02 691 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
6232 22:14:02 691 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
6232 22:14:02 691 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
6232 22:14:02 691 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
6232 22:14:02 691 debug2: compression ctos: none
6232 22:14:02 691 debug2: compression stoc: none
6232 22:14:02 691 debug2: languages ctos: 
6232 22:14:02 691 debug2: languages stoc: 
6232 22:14:02 691 debug2: first_kex_follows 0 
6232 22:14:02 691 debug2: reserved 0 
6232 22:14:02 691 debug2: peer client KEXINIT proposal
6232 22:14:02 691 debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
6232 22:14:02 691 debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-ed25519,ssh-rsa,ssh-dss
6232 22:14:02 691 debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
6232 22:14:02 691 debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
6232 22:14:02 691 debug2: MACs ctos: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
6232 22:14:02 691 debug2: MACs stoc: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
6232 22:14:02 691 debug2: compression ctos: none,zlib@openssh.com,zlib
6232 22:14:02 691 debug2: compression stoc: none,zlib@openssh.com,zlib
6232 22:14:02 691 debug2: languages ctos: 
6232 22:14:02 691 debug2: languages stoc: 
6232 22:14:02 691 debug2: first_kex_follows 0 
6232 22:14:02 691 debug2: reserved 0 
6232 22:14:02 691 debug1: kex: algorithm: curve25519-sha256@libssh.org
6232 22:14:02 691 debug1: kex: host key algorithm: ecdsa-sha2-nistp256
6232 22:14:02 691 debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none
6232 22:14:02 691 debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none
6232 22:14:02 691 debug1: expecting SSH2_MSG_KEX_ECDH_INIT
6232 22:14:03 097 debug3: receive packet: type 30
6232 22:14:03 097 debug3: send packet: type 31
6232 22:14:03 097 debug3: send packet: type 21
6232 22:14:03 097 debug2: set_newkeys: mode 1
6232 22:14:03 097 debug1: rekey after 4294967296 blocks
6232 22:14:03 097 debug1: SSH2_MSG_NEWKEYS sent
6232 22:14:03 097 debug1: expecting SSH2_MSG_NEWKEYS
6232 22:14:03 472 debug3: receive packet: type 21
6232 22:14:03 472 debug1: SSH2_MSG_NEWKEYS received
6232 22:14:03 472 debug2: set_newkeys: mode 0
6232 22:14:03 472 debug1: rekey after 4294967296 blocks
6232 22:14:03 472 debug1: KEX done
6232 22:14:03 863 debug3: receive packet: type 5
6232 22:14:03 863 debug3: send packet: type 6
6232 22:14:04 222 debug3: receive packet: type 50
6232 22:14:04 222 debug1: userauth-request for user tomc service ssh-connection method none
6232 22:14:04 222 debug1: attempt 0 failures 0
6232 22:14:04 222 debug2: parse_server_config: config reprocess config len 242
6232 22:14:04 222 debug2: input_userauth_request: setting up authctxt for tomc
6232 22:14:04 222 debug2: input_userauth_request: try method none
6232 22:14:04 222 Failed none for tomc from 10.1.4.40 port 18114 ssh2
6232 22:14:04 222 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"
6232 22:14:04 222 debug3: send packet: type 51
6232 22:14:04 582 debug3: receive packet: type 50
6232 22:14:04 582 debug1: userauth-request for user tomc service ssh-connection method publickey
6232 22:14:04 582 debug1: attempt 1 failures 0
6232 22:14:04 582 debug2: input_userauth_request: try method publickey
6232 22:14:04 582 debug1: userauth_pubkey: test whether pkalg/pkblob are acceptable for RSA SHA256:2lCcCbp9Rgtg8XFwsfp1MWxo94KIcHd+JIeLmFNAkaI
6232 22:14:04 582 debug1: trying public key file C:\\Users\\tomc/.ssh/authorized_keys
6232 22:14:04 582 debug1: matching key found: file C:\\Users\\tomc/.ssh/authorized_keys, line 2 RSA SHA256:2lCcCbp9Rgtg8XFwsfp1MWxo94KIcHd+JIeLmFNAkaI
6232 22:14:04 582 debug3: send packet: type 60
6232 22:14:04 582 debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa
6232 22:14:04 582 Postponed publickey for tomc from 10.1.4.40 port 18114 ssh2
6232 22:14:04 941 debug3: receive packet: type 50
6232 22:14:04 941 debug1: userauth-request for user tomc service ssh-connection method publickey
6232 22:14:04 941 debug1: attempt 2 failures 0
6232 22:14:04 941 debug2: input_userauth_request: try method publickey
6232 22:14:04 941 debug3: userauth_pubkey: have signature for RSA SHA256:2lCcCbp9Rgtg8XFwsfp1MWxo94KIcHd+JIeLmFNAkaI
6232 22:14:04 941 debug1: auth agent did not authorize client tomc
6232 22:14:04 941 debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa
6232 22:14:04 941 Failed publickey for tomc from 10.1.4.40 port 18114 ssh2: RSA SHA256:2lCcCbp9Rgtg8XFwsfp1MWxo94KIcHd+JIeLmFNAkaI
6232 22:14:04 941 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"
6232 22:14:04 941 debug3: send packet: type 51
6232 22:14:05 300 debug3: receive packet: type 50
6232 22:14:05 300 debug1: userauth-request for user tomc service ssh-connection method keyboard-interactive
6232 22:14:05 300 debug1: attempt 3 failures 1
6232 22:14:05 300 debug2: input_userauth_request: try method keyboard-interactive
6232 22:14:05 300 debug1: keyboard-interactive devs 
6232 22:14:05 300 debug1: auth2_challenge: user=tomc devs=
6232 22:14:05 300 debug1: kbdint_alloc: devices ''
6232 22:14:05 300 debug2: auth2_challenge_start: devices 
6232 22:14:05 300 Failed keyboard-interactive for tomc from 10.1.4.40 port 18114 ssh2
6232 22:14:05 300 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"
6232 22:14:05 300 debug3: send packet: type 51
6232 22:14:07 504 Connection closed by authenticating user tomc 10.1.4.40 port 18114
6232 22:14:07 504 debug1: do_cleanup
3904 22:14:07 504 debug3: close - io:00000074026A1FD0, type:2, fd:6, table_index:6
3904 22:14:07 504 debug3: zombie'ing child at index 0, 0 zombies of 1
3904 22:14:07 504 debug3: raise sig:3
3904 22:14:07 504 debug3: Unregister child at index 0, 1 zombies of 1
3904 22:14:07 504 debug3: process_queued_signals: WARNING - A signal has interrupted and was processed

**Comment by manojampalam** [comment]
For workgroup/local accounts, you currently need to install ssh-lsa.dll. This restriction (and ssh-lsa.dll) will go away in the next release.

**Comment by ThomasMConnors** [comment]
Manoj, looks like the config was right but a reboot was pending. Thanks! It works now.


[cid:image001.png@01D2B395.A7C94450]


[cid:image002.png@01D2B395.A7C94450]
