### ISSUE TITLE
Login with SSH Keys not working

### ISSUE THREAD

**Issue by rpereda** [PowerShell/Win32-OpenSSH#664]
Please answer the following

**"OpenSSH for Windows" version**
 0.0.11.0

**OS details**
 Windows Server 2012 R2 Standard

**What is failing**

SSH is not able to read the authorized_keys folder, therefore a login with ssh keys is not possible, below some logs

4000 17:41:37 125 debug1: userauth_pubkey: test whether pkalg/pkblob are acceptable for RSA SHA256:ueiywq2iC7n71dmluCAZqixYO9/Rga38WZXdg9IxXGQ
4000 17:41:37 125 debug1: trying public key file **C:\\Users\\Administrator/.ssh/authorized_keys**
4000 17:41:37 125 debug1: Could not open authorized keys 'C:\\Users\\Administrator/.ssh/authorized_keys': Permission denied
4000 17:41:37 125 debug1: trying public key file **C:\\Users\\Administrator/.ssh/authorized_keys2**
4000 17:41:37 125 debug1: Could not open authorized keys 'C:\\Users\\Administrator/.ssh/authorized_keys2': Permission denied
4000 17:41:37 125 Failed publickey for Administrator from 96.253.71.234 port 60953 ssh2

I followed the installation guide from here (https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH) and also executed the script to grant the read access which is mentioned here (https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.11.0), I've validated the access in my machine. I tried creating the default second folder authorized_keys2 authorized_keys2 without luck, also I was thinking that it was something related to the path so I've tried several combinations at the end I commented out the path so it can look for the default but still not working, any help will be appreciated.

thanks!

below part of my config:
`#` Logging
`#` obsoletes QuietMode and FascistLogging
`#`SyslogFacility AUTH

LogLevel DEBUG

`#` Authentication:

`#`LoginGraceTime 2m
`#`PermitRootLogin yes
`#`StrictModes yes
`#`MaxAuthTries 6
`#`MaxSessions 10

RSAAuthentication yes
PubkeyAuthentication yes

`# `The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
`#` but this is overridden so installations will only check .ssh/authorized_keys
`#`AuthorizedKeysFile	.ssh/authorized_keys
`#`AuthorizedKeysFile	\.ssh\authorized_keys

**Expected output**
Be able to login using ssh keys.

**Actual output**
ssh is bypassing the ssh validation and asking for password.

<img width="917" alt="screen shot 2017-04-12 at 11 53 45 am" src="https://cloud.githubusercontent.com/assets/3868410/24971823/e64f7bea-1f7e-11e7-9fbb-ca0fbacc9ad3.png">
<img width="1070" alt="screen shot 2017-04-12 at 12 44 00 pm" src="https://cloud.githubusercontent.com/assets/3868410/24971827/e8fe20da-1f7e-11e7-9991-cf74209b22aa.png">

**Comment by DarwinJS** [comment]
@rpereda - I believe you have referred to authorized_keys as a folder in multiple issues?

It is not a folder, but a file containing a list of keys.

**Comment by manojampalam** [comment]
Reopen if needed.

**Comment by mrPsycho** [comment]
what should be correct path in `sshd_config` for `AuthorizedKeysFile`?

if something like `./authorized_keys` - point to directory where `sshd.exe` is placed.
