### ISSUE TITLE
ssh-add not connecting to SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by gpoul** [PowerShell/Win32-OpenSSH#669]
**"OpenSSH for Windows" version**
0.0.11.0

**OS details**
Windows 10 Pro

**What is failing**

ssh-add doesn't appear to be able to connect to the agent; I'm trying to use gpg-agent, but the error already happens with ssh-add not being able to connect at all, so I think this is related to ssh-add, not gpg-agent.

**Expected output**

I would expect ssh-add to be able to connect to the agent

**Actual output**

C:\Users\GerhardPoul>ssh-add -L
Error connecting to agent: No such file or directory

C:\Users\GerhardPoul>set SSH_AUTH_SOCK=C:\Users\GerhardPoul\AppData\Roaming\gnupg\S.gpg-agent.ssh

C:\Users\GerhardPoul>type %SSH_AUTH_SOCK%
52453
Γ]ÄH╪Iz5æ[╙Wî└
C:\Users\GerhardPoul>ssh-add -L
_Error connecting to agent: No such file or directory_

C:\Users\GerhardPoul>

**Comment by manojampalam** [comment]
IPC for Windows port happens over Named pipes (compared to Unix domain sockets on Unix). SSH agents for Windows need to expose their end points over named pipes. 

Say if the agent is exposed over \\.\pipe\AGENTPIPENAME 
SSH_AUTH_SOCK should be set to AGENTPIPENAME
