### ISSUE TITLE
Using WSL via Win32-OpenSSH breaks console

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#670]
Please answer the following

**"OpenSSH for Windows" version**
 `0.0.11.0`

**OS details**
 `Windows 10 Pro 1607`

**What is failing**
Logging into cmd works, but going into WSL via bash seems to break everything - backspace causes control characters to be printed to the screen (`[K`), and trying to use tmux results in more garbage being printed 

**Expected output**
A "normal" session, including being able to run tmux

**Actual output**
![image](https://cloud.githubusercontent.com/assets/159567/25071424/e25e6dd8-22f9-11e7-9720-7becbcfc2fdd.png)

**Comment by bagajjal** [comment]
Can you elaborate what do you mean by "Logging into cmd works"?

Without WSL, were you able to login to unix machine properly and the terminal behaves correctly.

Try setting the SSH_TERM_CONHOST_PARSER to 0 in cmd.exe using (set SSH_TERM_CONHOST_PARSER=0) and then do ssh. Let us know if this works well.

**Comment by bagajjal** [comment]
Did you try the workaround (set SSH_TERM_CONHOST_PARSER=0) ?

**Comment by bagajjal** [comment]
Reopen with requested information..

**Comment by ghost** [comment]
Can't reproduce on current build, will open a new issue with the current error.
