### ISSUE TITLE
sshd service cannot be started; access is denied

### ISSUE THREAD

**Issue by Scrxtchy** [PowerShell/Win32-OpenSSH#672]
**"OpenSSH for Windows" version**
0.0.11.0

**OS details**
Windows Server 2016 Standard

**What is failing**
sshd service being started returns an access is denied error

**Expected output**
sshd service should start and be left running in the background as a service

**Actual output**
```
---------------------------
Services
---------------------------
Windows could not start the sshd service on Local Computer.



Error 5: Access is denied.


---------------------------
OK   
---------------------------
```

sshd's service properties imply that it is logging in as `NT SERVICE\SSHD`
Otherwise, the deamon runs fine when executing it from it's executable from my terminal (returns a broken pipe error when I log in though)

**Comment by manojampalam** [comment]
Cross checking - are you starting the service as an admin (in an elevated console) ?

**Comment by Scrxtchy** [comment]
I am running it from the Administrative account, however I'm using the Service management utilities instead of a command line

**Comment by manojampalam** [comment]
Can you try using "net start sshd"

Also, can you dump the cmdline you are using (from Service management utitlities)?

**Comment by Scrxtchy** [comment]
Fixed it;
I noticed I was running these application files from a user directory, instead of say Program Files that are accessible from the sshd service user

**Comment by pmontrasio** [comment]
I cd into Program Files but I keep getting the same error.

I was already logged in ad Administrator but to be sure that I'm running cmd as Administrator: went to c:\windows\system32, right click on cmd.exe, run as administrator. Same error.

sshd.exe -ddd starts and displays Server listening on 0.0.0.0 port 22 but I can't connect from the outside. I configured the firewall according to the instructions and got Status: The Rule was parsed successfully from the store. (65536).

Is it possible that the access denies error and the connection problem are linked?
