### ISSUE TITLE
STDOUT doesn't wrap the buffer when running in SecureCRT

### ISSUE THREAD

**Issue by DHammarberg** [PowerShell/Win32-OpenSSH#673]
Please answer the following

**"OpenSSH for Windows" version**
v0.0.12.0

**OS details**
Windows 7 Ultimate

**What is failing**
STDOUT doesn't wrap the buffer when I run a terminal through SecureCRT. If I fill up the buffer with command output from "dir" or similar, eventually it gets to the bottom row. But unlike when I log onto Linux machines, it doesn't wrap the remaining lines back - only the last 2-3 ones. So I have to clear the screen with "cls" to be able to see new output.

After more troubleshooting, I've discovered it appears to be when I've gotten too many lines into the buffer. When it passes like 150, it stops wrapping. So if I'm in a directory with 100 files, I can run dir twice - but the third time, it doesn't add anything at all.

**Comment by manojampalam** [comment]
As a work around, set your buffer rows to a big number (9999).

**Comment by bagajjal** [comment]
I am not able to recreate this issue on windows 10. It should be the same behavior on the windows 7 as well.

After SSH does your previous cmd.exe content (before doing ssh) is still there or the whole screen got cleared? please share the recording.
 
Are you using the legacy console?
Please share your cmd.exe properties, "console screen buffer size - width / height" and  windows size.

Go through this URL and set the cmd.exe settings correctly,
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

**Comment by DHammarberg** [comment]
My cmd.exe has version 6.1.7601.17514.
conhost.exe has version 6.1.7601.23714.
conhost.exe is run with this command line: C:\Windows\system32\conhost.exe "-532765958-1897637209-556521010-811327810-9583264939507278038647003711698927287
Logical rows and columns in SecureCRT are 24 and 80.
This is how it looks for me: https://www.dropbox.com/s/nl0gqrpnjgloebe/securecrt_ssh_console.mp4
After having padded the buffer a bit, it just keeps overwriting that last line, it seems.

**Comment by DHammarberg** [comment]
When I try it in Putty, I find it works the way it should there. But inside SecureCRT, something goes wrong, whether I log directly into Windows, or do it from another machine. I'm using the same settings for this session that I use in any other, so maybe some terminal communication problem, I don't know.

**Comment by DHammarberg** [comment]
I've tried a little more now. It seems the problem is present when connecting with mRemoteNG too. Just to make sure, I updated to the latest SecureCRT version as well, and it didn't change it. 

What works for me:

Putty
Connecting from xterm running on Linux machine

What doesn't:

SecureCRT
mRemoteNG

I tried different terminal settings in SecureCRT too, but none worked.

**Comment by bagajjal** [comment]
Please provide this information,
1) are you using the non-legacy console mode in the cmd.exe console properties,   
   Make sure you **uncheck** the "use legacy console"   
![image](https://cloud.githubusercontent.com/assets/23668037/23882278/cc062726-081c-11e7-8e4c-792da6af23b9.png) 

2) after doing ssh, does your whole console gets cleared (or) were you able to see the commands that were executed before the ssh?

3) share the screenshot of your cmd.exe properties, "console screen buffer size - width / height" and windows size.
![image](https://cloud.githubusercontent.com/assets/23668037/23882328/11ed4116-081d-11e7-87e0-757680ea3a74.png)

4) try this workaround and let us know if it works.
before doing ssh, in cmd.exe execute "set SSH_TERM_CONHOST_PARSER=0" and then login to the ssh server.

5) Why are you running the conhost manually? I think it should be started when you login to your machine? what are these different options provided to the conhost
 C:\Windows\system32\conhost.exe "-532765958-1897637209-556521010-811327810-9583264939507278038647003711698927287

**Comment by bagajjal** [comment]
@DHammarberg  - could you please provide the requested information.

**Comment by bagajjal** [comment]
If the issue still persists then please reopen with the requested information.
