### ISSUE TITLE
Version without ssh-lsa does not work with ssh keys on docker for Windows

### ISSUE THREAD

**Issue by vcarluer** [PowerShell/Win32-OpenSSH#677]
Please answer the following

**"OpenSSH for Windows" version**
0.0.12.0

**OS details**
Microsoft Windows Server Core 2016 Docker container hosted by Microsoft Windows 2016.

**What is failing**
ssh key authentication

**Expected output**
Logon with public key

**Actual output**
Password prompt

Deployed with chocolatey.org package https://chocolatey.org/packages/openssh
Fallback to 0.0.10.0 works well

**Comment by bgelens** [comment]
Got this with PowerShell 6 ```New-PSSession``` as well. Reverted to 0.0.11.0 and working again. In my case I installed from GH releases.

**Comment by Flamez97** [comment]
@vcarluer  Please do you know a link to download the version with ssh-sla?

**Comment by vcarluer** [comment]
The version 0.0.10.0 available here have it (maybe the 0.0.11.0 too, didn't test)
https://github.com/PowerShell/Win32-OpenSSH/releases
I have installed it with chocolatey, so I didn't have test direct install from here but it should be the same.

**Comment by DarwinJS** [comment]
v0.0.11.0 has ssh-lsa.dll as well.

On line 10 of the below linked dockerfile, add '-MaximumVersion 0.0.11.0' to keep your docker builds at 11 until this is fixed.

https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/Dockerfile

**Comment by manojampalam** [comment]
I'm looking into this.

**Comment by Flamez97** [comment]
Thanks @vcarluer

**Comment by manojampalam** [comment]
Found the issue. On the nanoserver docker image, SHGetKnownFolderPath(&FOLDERID_Profile) using the token generated by S4U for NTLM, is returning the system profile path
- C:\\Windows\\system32\\config\\systemprofile

I'll fix this in the next drop by avoiding this call and retrieving the user profile path from registry directly.

This is my dockerfile
```
FROM microsoft/nanoserver:latest

ADD OpenSSH-Win64 c:/openssh
RUN powershell -executionpolicy bypass -file c:\openssh\install-sshd.ps1
RUN powershell -c {cd c:\openssh; .\ssh-keygen -A;}
EXPOSE 22/tcp
RUN net user admin a /add
ENTRYPOINT net start sshd

#docker build . -t m1
```

**Comment by manojampalam** [comment]
We found some reliability issues with recent changes and will need time to do stabilization. This issue has been fixed but a drop wont be available till Mid May. Thanks for your patience.
