### ISSUE TITLE
Wiki Documentation: Minor mistakes and improvement suggestions

### ISSUE THREAD

**Issue by ChristophB125** [PowerShell/Win32-OpenSSH#678]
As a result of #661:
In the Wiki page [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples), the following command syntax is incorrect and would give an error:
`Set-Acl  $authorizedKeyPath $acl`
The correct syntax using named parameters is:
`Set-Acl -Path $authorizedKeyPath -AclObject $acl`

On the same Wiki [page](https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples), I would suggest adding a comment that the user account under which the shh-keygen and ssh-add commands are run have to match the credentials under which PowerShell remoting commands will be run on the client side.

In another Wiki page [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH), Under the bullet points of 'Secure SSH host keys': one needs to add the step `cd 'C:\Program Files\OpenSSH'` if one has not added the OpenSSH directory to the path variable. Maybe it would be useful to add this as a step to the instructions as well (either the cd command or the adding to the environment variable)

In general, I would suggest to split the instructions for client/host separately for further improvement. I found it also difficult to bring all the pieces of information from this and the PowerShell repo together to be able to configure remoting.

**Comment by bagajjal** [comment]
Thanks for your feedback.

1) Not sure why you are getting an error for (Set-Acl $authorizedKeyPath $acl).
It works for me.. here is the snapshot,
![image](https://cloud.githubusercontent.com/assets/23668037/25207150/70b36466-2521-11e7-8ebf-1ba05f668018.png)
![image](https://cloud.githubusercontent.com/assets/23668037/25207156/7e31c1f0-2521-11e7-90d8-71552bdf43c6.png)

As per the msdn -Path, -AclObject are optional so you shouldn't get any error...
![image](https://cloud.githubusercontent.com/assets/23668037/25207205/ced6105c-2521-11e7-8542-75da81d1c02f.png)

2) Adding comment for the ssh-keygen, ssh-add.. It is very clear as the keys are specific to a given user so they can be used for the same user so ignoring this comment.

3) This Wiki page [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH), already has this information to do a "cd 'C:\Program Files\OpenSSH'"?
![image](https://cloud.githubusercontent.com/assets/23668037/25207260/112056a2-2522-11e7-8dbd-88d46131d30a.png)

4) I have separated the client and server cmds in this wiki [page
](https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples) 

Let me know if you have more suggestions. If not then lets close this issue.
