### ISSUE TITLE
SSH Login shell has elevated privileges?

### ISSUE THREAD

**Issue by mayo** [PowerShell/Win32-OpenSSH#679]
When I log in over ssh, the given shell seems to be running with elevated privileges. The user I'm logging in as, is in the admin group and the shell seems to be running in admin mode. I need to run the shell in unprivileged mode. Is there any way to achieve this?

(This might be related or similar to issue #157)

**Comment by manojampalam** [comment]
If the user you are logging in as, is part of Administrators group, then yes, you will be an admin with elevated privileges. 

You would need to create a restricted user and login as that user instead.

**Comment by manojampalam** [comment]
Please reopen if you have follow up questions.
