### ISSUE TITLE
Suggestion: Package with chocolatey

### ISSUE THREAD

**Issue by willpriceb** [PowerShell/Win32-OpenSSH#68]
Hi,

Thanks for your awesome work, this is a great addition to the windows ecosystem.

It'd be really nice to be able to install openssh via https://chocolatey.org/

**Comment by nachfuellbar** [comment]
https://github.com/PowerShell/Win32-OpenSSH/issues/42

**Comment by willpriceb** [comment]
Thanks @nachfuellbar 
Closing as dupe.
