### ISSUE TITLE
Passing password through Powershell using ssh

### ISSUE THREAD

**Issue by greavette** [PowerShell/Win32-OpenSSH#687]
Hello,

**"OpenSSH for Windows" version**
0.0.11.0

**OS details**
Windows Server 2012 R2 Datacenter

Connecting from Windows Server 2012 to Red Hat Linux 7 using password.  Connection using ssh is successful from Windoes Server to Linux Server.  Looking for direction on how I can pass through my password in powershell when logging in to Linux server so I won't have to type in the password.

Thank you.

**Comment by bagajjal** [comment]
Use the key based authentication..
This wiki has the steps,
https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples
