### ISSUE TITLE
sftp batch file does not work for private keys with passwords

### ISSUE THREAD

**Issue by JefStat** [PowerShell/Win32-OpenSSH#69]
Trying to copy a few files using sftp batch mode with is not working. 
My error
```
Permission denied (publickey,password,keyboard-interactive).
Couldn't read packet: An existing connection was forcibly closed by the remote host.
```
My command is `& 'C:\Program Files\OpenSSH-Win32\sftp.exe' -F C:\Users\user\.ssh\config -b .\s
ftp_batch.txt admin@192.168.1.2`

My ssh key has a password on it which I believe is the problem. From what I can tell I would need to use ssh-agent to cache my private-key login.

**Comment by manojampalam** [comment]
Tracked as #35
