### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by grego1981** [PowerShell/Win32-OpenSSH#691]
Please answer the following

**"OpenSSH for Windows" version**
0.0.10.0

**OS details**
 Windows 7 Pro x64 SP1

**What is failing**
Getting access denied from VBscript even logged in as domain administator
**Expected output**
It's a windows update vbscript it runs fetches the updates and installs them afterwards. It works when using psexec with the same credentials.
**Actual output**
Permission denied when installing.

**Comment by manojampalam** [comment]
Key based auth or password?

**Comment by grego1981** [comment]
I'm using password authentication.

**Comment by manojampalam** [comment]
I'm guessing this has something to do with what your script is doing. Remote ssh session are Network Logons. So, if your script is trying to access something that has explicitly denied access to "Network", you would be seeing this. 

A quick test would be to do the same via a remote PS session (that runs on Network logons too).

**Comment by manojampalam** [comment]
Reopen if needed.
