### ISSUE TITLE
Response to fingerpring verification prompt does not echo

### ISSUE THREAD

**Issue by martinprikryl** [PowerShell/Win32-OpenSSH#692]
**"OpenSSH for Windows" version**
0.0.12.0

**OS details**
Windows 10 Pro

**What is failing**
When connecting to new host with `ssh.exe`, I get a usual prompt:
> The authenticity of host '...' can't be established. ...
> Are you sure you want to continue connecting (yes/no)?

When typing a response, contrary to a common *nix build of `ssh`, the response cannot be seen (like if I were typing a password). If I blindly type `yes` and press <kbd>Enter</kbd>, the connection proceeds. So the prompt is working, it just does not echo the response.

I have actually tested this based on this post on Super User:
https://superuser.com/q/1203841/213663#comment1753177_1203856
So it's not only me, who has the problem.

**Comment by lodo1995** [comment]
I had that problem too (I'm the one that wrote about it on Super User).

It's really a weird bug, and quite problematic, because when you don't see anything you hardly think that maybe the input is working in "password mode", so you probably just give up.

**Comment by bagajjal** [comment]
Please check the june mid release
