### ISSUE TITLE
Windows 7 - Network error: Software caused connection abort

### ISSUE THREAD

**Issue by Nico83500** [PowerShell/Win32-OpenSSH#694]
Hi,

When I try to connect to SFTP (or PuTTY) on this host, I get a message "Network error: Software caused connection abort". No problem with my other computer with Windows 10 Profesionnal x64.

Details :

OpenSSH for Windows 0.0.12.0

OS details : Windows 7 Professional SP1 x64

Thank you for your help !

**Comment by Nico83500** [comment]
I've updated my system (include Powershell 5.1) and launched a new installation. Problem solved.

**Comment by moribellamy** [comment]
+1, same error with a clean install on windows7, per https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by manojampalam** [comment]
@moribellamy please open a new issue with details.
