### ISSUE TITLE
scp -r ignored from PS server to linux client

### ISSUE THREAD

**Issue by blaggacao** [PowerShell/Win32-OpenSSH#70]
The recursive copy from a PS server to a linux client is simply ignored. It copys an empty directory insted.

```
scp -r USER@hostname:c:\\Users\\USER\\folder /home
```

**Comment by rgl** [comment]
this still does not work in v0.0.5.0

**Comment by bingbing8** [comment]
directory copy is fixed on latest. Please check on the next drop when it is available.
