### ISSUE TITLE
Long-pressing arrow-keys prints control sequences instead of advancing cursor (Linux client)

### ISSUE THREAD

**Issue by Rondom** [PowerShell/Win32-OpenSSH#701]
**"OpenSSH for Windows" version**
 `0.0.12.0`

**OS details**
 `Windows Server 2016 Datacenter`

**Client**
`OpenSSH_7.4p1 Debian-10, OpenSSL 1.0.2k  26 Jan 2017`

**What is failing**
1. Log in to windows machine via ssh from a Linux machine (in my case Debian stretch/testing)
2. Type a longer line such as "asdf asdf asd fasd fasd fas dfa sdfa sd fasd fas dfas dasdf"
3. Press Left-Arrow multiple times to move the cursor but don't hold the key down
4. Hold Left-Arrow down to move the cursor

**Expected output**
Cursor moves further to the left no matter if holding the key down or pressing it just once multiple times

    asdf asdf asdf asd fasd fasd fa sdf asd fa sdf asd fa sdf asd fas dfadfasd
                  ^ (cursor)

**Actual output**
Control sequences are printed when holding down one of the arrow-keys.

    asdf asdf asdf asd fasd fasd fa sdf asd fa sdf as^[[D^[[D^[[D^[[Dd fa sdf asd fas dfadfasd   
                                                               ^ (cursor)

**Comment by bagajjal** [comment]
This is a Linux client terminal issue.. 
Client has to interpret the VT sequences sent by the server..

Before doing ssh, on the Linux client..  use the bash and set the term to xterm..
please try this and let me know if you still have issues...

fyi, this is working from long time.. we have tested Ubuntu client to windows ssh server.

**Comment by manojampalam** [comment]
@Rondom what's your TERM set to?

**Comment by Rondom** [comment]
I have reproduced this with GNOME Terminal and terminator (`TERM=xterm-256color`). I also tried setting the `TERM=xterm`. Also I tried logging in outside X via a Linux-VT (`TERM=linux`) and I got the same behaviour.

**Comment by bagajjal** [comment]
I couldn't download GNOME terminal but I have tried it in the putty terminal..
I used putty to login to Ubuntu machine from my windows... Then from Ubuntu machine, I logged into the windows server. I tried but couldn't reproduce this issue by long-pressing the left and right arrows...

Please check this video,
https://www.screencast.com/t/c0WBwYyzoEH

Please try using Ubuntu and let me know your findings...

**Comment by Rondom** [comment]
As I said, I tried different terminals and I found it highly unlikely that the client is the culprit, so I investigated it a bit further.
The issue only occurs at higher latencies. Could it be that your Ubuntu environment is on the same physical machine / datacenter? I was accessing my Windows-VM using WiFi and an SSH-tunnel to the KVM-host it was running on. That was enough to trigger it. I could not reproduce it when logging in directly from the KVM-host to the Windows-guest.

So in order to reproduce it, you need a higher latency link. You can use `tc` to simulate latency (replace virbr0 with the interface in question). 500ms ± 100ms is ample to trigger the behaviour:

    tc qdisc add dev virbr0 root netem delay 500ms 100ms

**Comment by bagajjal** [comment]
The fix is available in june-mid release..
