### ISSUE TITLE
fatal: percent_expand: unknown key %s

### ISSUE THREAD

**Issue by mrPsycho** [PowerShell/Win32-OpenSSH#702]
**"OpenSSH for Windows" version**

    PS C:\Program Files\OpenSSH> ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
    Get-Command : The term 'sshd' is not recognized as the name of a cmdlet, function, script file, or operable program.
    Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    At line:1 char:13
    + ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
    +             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (sshd:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

    Get-Item : Cannot bind argument to parameter 'Path' because it is null.
    At line:1 char:12
    + ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
    +            ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Item], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetItemComm and

    PS C:\Program Files\OpenSSH> .\sshd.exe -v
    unknown option -- v
    OpenSSH_7.5p1, OpenSSL 1.0.2d 9 Jul 2015

**OS details**
Windows Server 2016 Datacenter

**What is failing**
it is not possible to use `~/path/to/file` in `sshd_config`.
For example, to use special `authorized_keys` file.

**Expected output**
it works without errors.

**Actual output**
can't log in and error in log:

`fatal: percent_expand: unknown key %s`

**Comment by manojampalam** [comment]
What's the exact entry in sshd_config? did it have a "%s"? As per https://linux.die.net/man/5/sshd_config, %s has no meaning. 
Only the following are defined:
%% is replaced by a literal '%', %h is replaced by the home directory of the user being authenticated, and %u is replaced by the username of that user

**Comment by manojampalam** [comment]
Reopen if needed.

**Comment by corygabrielsen** [comment]
If anyone finds this issue, my primary issue was taking online instructions too literally and using the string `IdentityFile %USERPROFILE%\.ssh\id_rsa` instead of `IdentityFile C:/Users/myname/.ssh/id_rsa`.

This causes OpenSSL to fail with an opaque error string:
```
percent_expand: unknown key %U
```

To fix this, I replaced:
```
Host example
    HostName example.com
    User user
    IdentityFile %USERPROFILE%\.ssh\id_rsa
```
with
```
Host example
    HostName example.com
    User user
    IdentityFile C:\Users\myname\.ssh\id_rsa
```
in my `.ssh/config`, and then subsequently facepalmed when it worked.

You can use the following script to help debug. Your specific issue may need a bit of tweaking, but this helped me solve an issue I had been facing for longer than I'm willing to admit publicly.
```bat
@echo off
REM Author: Cory Gabrielsen
REM Date: 2023-01-10
REM Description: This script will help you debug ssh issues by displaying the ssh config file
REM and the contents of the IdentityFile.  It will also run ssh -G test and display the results.
REM This script is intended to be run on a Windows machine.
REM

REM display the contents of the ssh config file located in the .ssh directory under
REM the user's profile.

REM Must pass the hostname as the first argument to this script
if "%1"=="" goto :usage

echo ^>        USERPROFILE: %USERPROFILE%
echo ^>        Running ssh -G %1...
ssh -G "%1" 2>&1 > ssh_G.txt
echo ^>        Result written to ssh_G.txt
echo ^>        ssh_G.txt contents:
set /p first_line=<ssh_G.txt
echo %first_line%
echo ....


echo ^>       Finding IdentityFile from ssh_G.txt...
set found=
rem search through the ssh_G.txt file for the IdentityFile line
for /f "tokens=2 delims= " %%i in ('findstr /i "identityfile" ssh_G.txt') do set found=%%i
for /f "tokens=2 delims= " %%i in ('findstr /i "identityfile" ssh_G.txt') do echo identityfile %%i
echo ^>       identityfile %found%

echo Connecting to host: %1...
ssh "%1"

rem usage instructions
:usage
echo.
echo Usage: debug_ssh.bat hostname
echo Example: debug_ssh.bat test.example.com
echo.
echo This script will help you debug ssh issues by displaying the ssh config file
echo and the contents of the IdentityFile.  It will also run ssh -G test and display the results.
echo This script is intended to be run on a Windows machine.
echo.
```

I think many people probably spent 10 seconds on this and used the correct string, but sometimes you just get the wrong idea of how to do something in your head and get stuck. I hope this can help anyone who deals with the `percent_expand` error coming from OpenSSL on Windows.

This also causes a hard crash in VS Code when using the Remote-SSH extension.
