### ISSUE TITLE
About memory load by Openssh

### ISSUE THREAD

**Issue by nightwish47** [PowerShell/Win32-OpenSSH#703]
"OpenSSH for Windows" version
  OpenSSH_ 7.1 p 1 Microsoft_Win 32 _ port_with_VS, OpenSSL 1.0.2 d 9 Jul 2015

OS details
  Windows Server 2012 R2 DataCenter

What is failing
The physical memory of Windows Server is increasing every day.
Is there a high load on memory by using OpenSSH?
Access frequency is once every 10 minutes from 10 clients every day.

Expected output
The high memory load is eliminated

**Comment by nightwish47** [comment]
I made a mistake in writing.

Access frequency is once every 10 minutes from 10 clients every day.　⇒×
Access frequency is once every minute from 10 clients every day.　⇒○

**Comment by manojampalam** [comment]
Looks like you are using a pretty old version. Can you try out the latest drop?

**Comment by nightwish47** [comment]
Currently running on production, it is difficult to try with the new version.
In the development environment, the same version of OpenSSH is used, but the physical memory remains low.

Is there a possibility that physical memory load will be high if OpenSSH version is old?

**Comment by manojampalam** [comment]
Very likely. A lot of effort went into fixing bug fixes and cleaning up code. Please install the latest version and reopen if you still see the perf issue.

**Comment by nightwish47** [comment]
Upgrading is difficult.
Since the event occurs when the access frequency is high, is there any way to improve by sshd_config or other parameters?

**Comment by nightwish47** [comment]
please re-open this topic.

**Comment by megamorf** [comment]
@nightwish47 just update the software, you're using an ancient version.

**Comment by nightwish47** [comment]
We are try to investigating the cause and found that process [CMCa] & [CM10] is already increased in Windows Kernel profile memory.
Could you help to confirm that process [CMCa] and [Cm10] is root cause or not?

In addition, are there any similar issue in the past?

**Comment by megamorf** [comment]
Please tell us why they should put effort into debugging a 2 year old version of a software that isn't yet considered production-ready? @nightwish47
