### ISSUE TITLE
SSHD on Active Directory Domain Controllers

### ISSUE THREAD

**Issue by aduzsardi** [PowerShell/Win32-OpenSSH#704]
Please answer the following
**"OpenSSH for Windows" version**
0.0.12.0
Windows Server 2016 Standard - domain controller

$sshdAccount = "NT SERVICE\SSHD" , does not get created on domain controllers so the service will fail with  `3368 10:05:01 859 error: Couldn't create pid file "./sshd.pid": Permission denied`
what would be the work around for this situation ?
creating an Active Directory account for the sshd service and run the service as that account or just use Local System ?

**Comment by manojampalam** [comment]
3368 10:05:01 859 error: Couldn't create pid file "./sshd.pid": Permission denied
this is an unrelated issue and does not mean that SSHD account doesn't get created.

What context is SSHD running as on your box?

**Comment by aduzsardi** [comment]
Not sure what you mean by 'context'
What i can tell you is that , it's a Windows 2016 Server (core) and it is a domain controller, installed OpenSSH , no issues there , checked the service and it was running with  NT SERVICE\SSHD  user account account , and seems like there's no such user and it doesn't have permissions to write in the OpenSSH folder , so i switched sshd service to run as Local System

**Comment by manojampalam** [comment]
What I meant is the user context the server is running as. You answer it - its NT Service\SSHD.

Is the service otherwise working fine (as NT Service\SSHD)?

Is the following log entry only concern you have?
error: Couldn't create pid file "./sshd.pid": Permission denied

**Comment by aduzsardi** [comment]
No it was not working until i changed the service to run as Local System.
While it was running as NT Service\SSHD , got `connection reset by server` on the client side , and `error: Couldn't create pid file "./sshd.pid": Permission denied` on server side
This only happens on Domain Controllers , so i guess we can live with that

**Comment by manojampalam** [comment]
Running SSHD as System is scary. We need to root cause this. Can you share you full client and server side logs?

**Comment by manojampalam** [comment]
@aduzsardi Please reopen this once you have the logs ready. As I said, running SSHD as system is a huge security compromise.

**Comment by aduzsardi** [comment]
so i run the installer script again , and now it seems to be working , i don't know how and why ... maybe i did something wrong the first time , although i have no idea what could have i done
but the ssh-agent service still runes as Local System

**Comment by abmoham** [comment]
Typically, Domain Controllers are special case systems re:software installation rights. More so when it requires a service and/or service account to run said service. Similar cases require creation of a domain user (can be the same name or your choosing) and be added into Builtin/Server Operator group in AD. Also may need to add the same user to 'Allow logon as a service' to Domain Controllers group policy rights. As described, this may provide server level access (withouut any AD domain rights) to complete the setup. Worth a try?
