### ISSUE TITLE
Environment variables in Windows SSH session

### ISSUE THREAD

**Issue by gazoakley** [PowerShell/Win32-OpenSSH#71]
Commands that rely on variables such as APPDATA and LOCALAPPDATA are failing since they are not being reset for the spawned cmd process - they stay pointing at C:\Windows\system32\config\systemprofile\AppData - and most users don't have permissions to write to that location. USERPROFILE is set correctly, so I can workaround by just:

set APPDATA=%USERPROFILE%\AppData\Roaming
set LOCALAPPDATA=%USERPROFILE%\AppData\Local

But it feels like this should be set automatically.

**Comment by nachfuellbar** [comment]
Correct me if i'm wrong (i'm currently on my linux notebook)
Shouldn't APPDATA refer to %USERPROFILE%\AppData\Roaming?

**Comment by gazoakley** [comment]
You're right - will update original post

**Comment by quamrulmina** [comment]
APPDATA, LOCALAPPDATA are set correctly and HOMEDRIVE, HOMEPATH are also set user's home directory drive letter and directory path as in Windows interactive shell

**Comment by gazoakley** [comment]
Thanks :+1:

**Comment by RamblingCookieMonster** [comment]
On a related note:

It might be intentional, but USERDNSDOMAIN is a handy variable I use as a default variable value for some domain related functions, doesn't appear to be available in these sessions.

Thanks!

**Comment by quamrulmina** [comment]
Good find & suggestions. In future, it and any other missing environment variables can be added in the sessions.

**Comment by epoctic** [comment]
why is this closed
