### ISSUE TITLE
Entering character ö prints two characters

### ISSUE THREAD

**Issue by Rondom** [PowerShell/Win32-OpenSSH#711]
**"OpenSSH for Windows" version**
 `0.0.12.0`

**OS details**
 `Windows Server 2016 Datacenter`

**What is failing** 
1. `ssh localhost`
2. Type the character `ö` (or paste it from clipboard, if it is hard to enter for you)

**Expected output**
Character `ö` is printed

**Actual output**
Two characters ` ┬ö` are printed.

**Comment by bagajjal** [comment]
The fix is available in june-mid release..

**Comment by Rondom** [comment]
Is the "june-mid-release" 0.0.15.0? If so, the issue is not fixed for me (and neither is #701)..
The behaviour is still the same with the above setup after upgrading. I have even done a reboot, it has not helped.

**Comment by bagajjal** [comment]
No its 0.0.16.0

**Comment by bagajjal** [comment]
Yet to be released

**Comment by Rondom** [comment]
0.0.16.0 works now when accessing a Windows-box from Linux.
Unfortunately with the above setup and steps, now pressing `ö` yields `` for the `ssh localhost` case.

**Comment by bagajjal** [comment]
Can you check the chcp setting on the cmd.exe..

It works perfectly fine on the localhost
![image](https://user-images.githubusercontent.com/23668037/27245945-28582b5c-52a3-11e7-84de-70d37685aea1.png)

**Comment by Rondom** [comment]
```
C:\Users\admin>echo ö
ö

C:\Users\admin>chcp
Active code page: 437

C:\Users\admin>ssh localhost
admin@WIN-U2UORB1LT7K@localhost's password:
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

admin@WIN-U2UORB1LT7K@WIN-U2UORB1LT7K C:\Users\admin>echo      


admin@WIN-U2UORB1LT7K@WIN-U2UORB1LT7K C:\Users\admin>chcp         
Active code page: 437

```

**Comment by bagajjal** [comment]
I copied "ö" and pasted in the ssh window and it worked.. can you try this and see if it works...

**Comment by Rondom** [comment]
Same behaviour when pasting :-(

**Comment by bagajjal** [comment]
1) can you try setting the chcp to 65001
![image](https://user-images.githubusercontent.com/23668037/27246605-8396ef7c-52a7-11e7-8830-ddb5fb9230df.png)

2) If it didn't work then try another terminal like putty/Cygwin.
Linux client to windows server works fine but openssh windows client to openssh windows server doesn't work so mostly its something to windows client..

As far as I know, openssh windows client doesn't do any modification..

**Comment by Rondom** [comment]
Once I do that, ö works still works locally, but when ssh-ing to localhost, it prints nothing!

**Comment by bagajjal** [comment]
Did you try other ssh clients (putty /Cygwin) on the same machine..

**Comment by Rondom** [comment]
Just downloaded Putty, works fine.

**Comment by bagajjal** [comment]
Please share your client OS details, I will try to reproduce at my end

**Comment by Rondom** [comment]
It's the same as in the initial issue description: Win 2016 (10.0.14393)
