### ISSUE TITLE
Keyboard does not work as expected.

### ISSUE THREAD

**Issue by laughterk** [PowerShell/Win32-OpenSSH#713]
Please answer the following

**"OpenSSH for Windows" version**
v0.0.12.0

**OS details**
Windows 7 Professional

**What is failing**
When connected from Linux (Ubuntu 14.04):
1. When pressing "Shift + Tab", it shows "^[[Z" instead of doing auto-complete.
2. Pressing 'Home', it shows "^[OH" instead of moving cursor.
3. Pressing 'End', it shows "^[OF]"
4. Type some characters and pressing "Ctrl + C", nothing happens instead of starting a new command.

**Comment by manojampalam** [comment]
Please see if https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH can provide any clues and let @bagajjal know if it needs any updates/clarifications.

**Comment by remittor** [comment]
Bugfix: https://github.com/PowerShell/openssh-portable/pull/137
Diff: https://github.com/PowerShell/openssh-portable/pull/137/commits/a07f7cb4d048795a27d5a1e9f9e22f650b0e7273

**Comment by Rondom** [comment]
I would like to add Ctrl+Arrowkey (i.e. up,down,left,right) to the list.

**Comment by bagajjal** [comment]
@remittor - Could you please send a new PR that include your changes till the commitID - 63ff39259d7a26b33fcdaa3d42cfdf1441d8828a..

We can work on fixing the xterm related changes later.

**Comment by bagajjal** [comment]
@remittor - Could you please do the needful so that we can pick up your changes to june end release.
If you are busy then can I pick your changes and submit to june end release?
Please do reply.

**Comment by remittor** [comment]
> If you are busy then can I pick your changes and submit to june end release?

Please do this.

**Comment by bagajjal** [comment]
@laughterk - 
1) control+c is been sent to the console but looks like its not honoring.. if you would like to check then do a "ping 127.0.0.1" and press control+c.. Its an issue from the console side not from openssh code.
2) autocompletion is tab.

@remittor - I have merged only the keystroke mapping for now as there are too many merge issues and I need to retest the merged part. The rest of the changes will be submitted to next release.. Thanks for you continuous support. Appreciate your efforts to make our product better.
