### ISSUE TITLE
Can not access public key file

### ISSUE THREAD

**Issue by jgr208** [PowerShell/Win32-OpenSSH#716]
Please answer the following

**"OpenSSH for Windows" version**
v0.0.12.0

**OS details**
Windows 2008 R2 with STIG applied

**What is failing**
Getting access denied to the public key trying to be used for public key authentication even while using the administrator account.

**Expected output**
Public key accepted and log in with key completed.

**Actual output**

> 2348 12:16:14 462 debug1: trying public key file C:\\Users\\Administrator/.ssh/authorized_keys
2348 12:16:14 462 debug1: Could not open authorized keys 
'C:\\Users\\Administrator/.ssh/authorized_keys': Permission denied
2348 12:16:14 462 debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa
2348 12:16:14 462 Failed publickey for administrator from 192.168.50.153 port 38828 ssh2
2348 12:16:14 462 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"
2348 12:16:14 462 debug3: send packet: type 51
2348 12:16:14 462 debug3: receive packet: type 50
2348 12:16:14 462 debug1: userauth-request for user administrator service ssh-connection method keyboard-interactive
2348 12:16:14 462 debug1: attempt 2 failures 1
2348 12:16:14 462 debug2: input_userauth_request: try method keyboard-interactive
2348 12:16:14 462 debug1: keyboard-interactive devs 
2348 12:16:14 462 debug1: auth2_challenge: user=administrator devs=
2348 12:16:14 462 debug1: kbdint_alloc: devices ''
2348 12:16:14 462 debug2: auth2_challenge_start: devices 
2348 12:16:14 462 Failed keyboard-interactive for administrator from 192.168.50.153 port 38828 ssh2
2348 12:16:14 462 debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"
2348 12:16:14 462 debug3: send packet: type 51

**Comment by manojampalam** [comment]
Ensure, sshd has read access to authorized keys. See wiki - https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples. 

Reopen if needed.

**Comment by jgr208** [comment]
Tried and is still happening.
