### ISSUE TITLE
Regarding to 「UseRoaming no」parameter of OpenSSH 7.1 p1

### ISSUE THREAD

**Issue by nightwish47** [PowerShell/Win32-OpenSSH#717]
**"OpenSSH for Windows" version**
OpenSSH_ 7.1 p 1 Microsoft_Win 32 _ port_with_VS, OpenSSL 1.0.2 d 9 Jul 2015

**OS details**
Windows Server 2012 R2 DataCenter

**What is failing**
We are try to setting [UseRoaming no] parameter in ssh_config as below note.
But when restart Windows service, we found error for SFTP connection.

Note Link:
http://www.openssh.com/txt/release-7.1p2

**Expected output**
Using [UseRoaming no] parameter
Can we use [UseRoaming no] parameter for the version in windows?

**Actual output**
Found SFTP connection error

**Comment by manojampalam** [comment]
You are using a pretty old version. Any reason for not upgrading to the latest?

**Comment by megamorf** [comment]
See #703

**Comment by nightwish47** [comment]
Microsoft official "OpenSSH" was released when looking for the Windows version of the commonly used SSH tool, so I use it as a production run.
Is there an Opne SSH version that is stable in the Windows environment?
When will it stabilize again?

**Comment by megamorf** [comment]
@nightwish47 No, but you can follow the releases page to check for a production-ready version of the Windows OpenSSH build: https://github.com/PowerShell/Win32-OpenSSH/releases

**Comment by bagajjal** [comment]
@nightwish47 - Looks like this option (useroaming) is deprecated...

![image](https://user-images.githubusercontent.com/23668037/27205094-95cc15d8-51e3-11e7-8bc6-202bbd25ca5f.png)
