### ISSUE TITLE
0.0.13.0 simply does not work

### ISSUE THREAD

**Issue by kai-uwe-rommel** [PowerShell/Win32-OpenSSH#720]
I followed the installation instructions. But I still get:

5884 23:05:59 356 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
5884 23:05:59 357 error: @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
5884 23:05:59 357 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
5884 23:05:59 357 error: Permissions for './ssh_host_rsa_key' are too open.
5884 23:05:59 357 error: It is required that your private key files are NOT accessible by others.
5884 23:05:59 357 error: This private key will be ignored.
5884 23:05:59 357 error: key_load_private: bad permissions

I can't see what is wrong. The permissions are like they should be according to the instructions.

**Comment by bingbing8** [comment]
Did you follow the [release notes](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.13.0) to re-ACL your key files?
**This version implements a breaking change that enforces more secure ACLs on various keys and configuration files.**
**Please make sure to read [this wiki topic on the secure protection of various files][Secure file] before using this latest version.**

- If you're updating from a previous version of Win32-OpenSSH, you will have to re-ACL files on both the server and client side.
- If this is your first time using Win32-OpenSSH, `ssh-keygen.exe` will do its best to ACL newly generated keys appropriately.
However, you will have to re-ACL all host keys, `authorized_keys`, and your user `ssh_config` (if you have one).

The [installation instruction](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH) also has been updated for this changes

You got that message because your private host allows other disallowed account to access. Can you check the aces of your file to make sure the file follow the requirement at [secure protection of various files][Secure file]? 

```powershell
(get-acl .\ssh_host_rsa_key).Access
```
This is the host key for sshd, right?

[Secure file]: https://github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-win32-openssh

**Comment by kai-uwe-rommel** [comment]
Yanbing <notifications@github.com> wrote on 14.05.2017 01:52:52:
>
> can you check the aces of your file:
> (get-acl .\ssh_host_rsa_key).Access

PS C:\Program Files\OpenSSH> (get-acl .\ssh_host_rsa_key).Access

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : ARS\A-Rommel
IsInherited       : False
InheritanceFlags  : None
PropagationFlags  : None

FileSystemRights  : Read, Synchronize
AccessControlType : Allow
IdentityReference : NT SERVICE\sshd
IsInherited       : False
InheritanceFlags  : None
PropagationFlags  : None

The ARS\A-Rommel is my admin account with which I am logged in when
I try to install/configure. It is a member of the domain's "Domain Admins"
group which in turn is a member of the local "Administrators" group.
So this is the minimum access I need ... some admin account must be
able to have access rights to the files. And SYSTEM should be, too,
for the backup software.

> Which cmds are your run? ssh, ssh-add, or scp?

I am trying to start the sshd service. But sshd complains:

5884 23:05:59 356 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
5884 23:05:59 357 error: @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
5884 23:05:59 357 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
5884 23:05:59 357 error: Permissions for './ssh_host_rsa_key' are too open.
5884 23:05:59 357 error: It is required that your private key files are NOT accessible by others.
5884 23:05:59 357 error: This private key will be ignored.
5884 23:05:59 357 error: key_load_private: bad permissions
5884 23:05:59 359 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
5884 23:05:59 359 error: @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
5884 23:05:59 359 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
5884 23:05:59 359 error: Permissions for './ssh_host_dsa_key' are too open.
5884 23:05:59 359 error: It is required that your private key files are NOT accessible by others.
5884 23:05:59 359 error: This private key will be ignored.
5884 23:05:59 359 error: key_load_private: bad permissions
5884 23:05:59 361 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
5884 23:05:59 361 error: @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
5884 23:05:59 361 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
5884 23:05:59 361 error: Permissions for './ssh_host_ecdsa_key' are too open.
5884 23:05:59 361 error: It is required that your private key files are NOT accessible by others.
5884 23:05:59 361 error: This private key will be ignored.
5884 23:05:59 361 error: key_load_private: bad permissions
5884 23:05:59 365 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
5884 23:05:59 365 error: @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
5884 23:05:59 365 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
5884 23:05:59 365 error: Permissions for './ssh_host_ed25519_key' are too open.
5884 23:05:59 365 error: It is required that your private key files are NOT accessible by others.
5884 23:05:59 365 error: This private key will be ignored.
5884 23:05:59 365 error: key_load_private: bad permissions
5884 23:05:59 366 Server listening on :: port 22.
5884 23:05:59 366 Server listening on 0.0.0.0 port 22.
5884 23:05:59 366 error: Couldn't create pid file "./sshd.pid": Permission denied

(Should I be worried about the ./sshd.pid error, too? I guess rather not, I don't
care about the pid file.)

**Comment by bingbing8** [comment]
@kai-uwe-rommel. is these private keys are new generated by ssh-keygen.exe or they are existing keys before this build? I assume ARS\A-Rommel is the file owner of the private key files, right?
Can you please update the  LogLevel to "LogLevel DEBUG3" in sshd_config so more details info is logged to tell you which sid is bad user? can you check if the bad user is your login user. We saw once the same user has two different sids, which cause the sid listed in ACL are different from the login sid and reported as bad user. not sure you are seeing the same issue.

**Comment by kai-uwe-rommel** [comment]
Unfortunately, with DEBUG3 it does not show user info (SID):

780 10:39:31 376 debug1: sshd version OpenSSH_7.5, OpenSSL 1.0.2d 9 Jul 2015
780 10:39:31 376 debug3: open - handle:00000000000003CC, io:00000021ADE282D0, fd:3
780 10:39:31 380 debug3: Bad owner on ./ssh_host_rsa_key
780 10:39:31 380 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
780 10:39:31 380 error: @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
780 10:39:31 380 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
780 10:39:31 380 error: Permissions for './ssh_host_rsa_key' are too open.
780 10:39:31 380 error: It is required that your private key files are NOT accessible by others.
780 10:39:31 380 error: This private key will be ignored.
780 10:39:31 380 debug3: close - io:00000021ADE282D0, type:2, fd:3, table_index:3
780 10:39:31 380 error: key_load_private: bad permissions

**Comment by kai-uwe-rommel** [comment]
As a test, I removed the ACL entry for my ID from one of the files and added full rights for a local admin ID (mine is a domain account) but it did not change things.

I have then removed the extra admin ACL entry completely, so now it looks that way:

C:\Program Files\OpenSSH>cacls ssh_host_dsa_key
C:\Program Files\OpenSSH\ssh_host_dsa_key NT SERVICE\sshd:(special access:)
                                                          READ_CONTROL
                                                          SYNCHRONIZE
                                                          FILE_GENERIC_READ
                                                          FILE_READ_DATA
                                                          FILE_READ_EA
                                                          FILE_READ_ATTRIBUTES

So ONLY the sshd account left on the file (which is bad, but for a test ...).
However, STILL the same error message for that file:
7972 10:46:15 376 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
7972 10:46:15 376 error: @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
7972 10:46:15 376 error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
7972 10:46:15 376 error: Permissions for './ssh_host_dsa_key' are too open.
7972 10:46:15 376 error: It is required that your private key files are NOT accessible by others.
7972 10:46:15 376 error: This private key will be ignored.
7972 10:46:15 376 error: key_load_private: bad permissions

So there must be a bug, I think, because this is simply wrong.

**Comment by bingbing8** [comment]
@kai-uwe-rommel with debug3, it show the file has bad owner. Can you check the owner of the file(```(Get-Acl .\sshtest_hostkey_ecdsa.pub).Owner```)? Can you change the owner of the file to one of the allowed account types followed by [secure protection of various files](https://github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-win32-openssh)?

**Comment by kai-uwe-rommel** [comment]
The owner was my own account. I don't understand what should be wrong with it. It happens to be a domain account. The problem went away when I made the local Administrators group the owner. IMO, this is overly restrictive and complicated and the setup script/instructions are not detailed enough.

However, for other reasons I now switched (back) to Cygwin SSHD anyway.

**Comment by bingbing8** [comment]
Domain account should be fine as owner of the private key file. It is ARS\A-Rommel, which is account you logged in, right? We are investigating why this is not okay on your machine. If you have more info why this account is special, please share with us. as I said before, we saw there is once where the user moved from a domain to another, the same domain account has two sids which cause the sid comparison failed. Not sure that is the case here though.

**Comment by kai-uwe-rommel** [comment]
Yes, the owner account was mine, ARS\A-Rommel. 
There is nothing special about this account. Just an ordinary domain admin account.
I'm sorry but I have to move on now, getting work done ... 
No more time to experiment with this sshd.
I'll perhaps come back and try it again in a year or so ...

**Comment by manojampalam** [comment]
@kai-uwe-rommel we have relaxed the file permission checks on Windows for the time being. Feel free to use [0.0.12.0](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.12.0) (that should not have the problem you are seeing).

**Comment by bingbing8** [comment]
v13 is pulled down.
