### ISSUE TITLE
Just 'openssh' rather than 'Microsoft openSSH' in terminal title

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/Win32-OpenSSH#722]
The current terminal title is 'Microsoft openSSH'.

![screenshot_1](https://cloud.githubusercontent.com/assets/172594/26054218/b08c24a0-3963-11e7-827d-4ee722ee8eec.png)

 - This is too long to fit in the terminal title 
 - The vendor name isn't necessary
 - Although this fork is maintained by Microsoft, openssh isn't a Microsoft product.
 - The capitalisation is odd

It would be simpler to just use 'openssh'.

**Comment by manojampalam** [comment]
Thanks for catching it. Agree that the title is odd and not appropriate. It creeped in from initial terminal prototyping work. 

I'll rename it to "OpenSSH SSH client", consistent with what [this](https://linux.die.net/man/1/ssh) says.

**Comment by mikemaccana** [comment]
Just saw this now. Thanks @bingbing8 ! 😊
