### ISSUE TITLE
Strange behaviour with domain authentication with keys

### ISSUE THREAD

**Issue by redfish0** [PowerShell/Win32-OpenSSH#723]
**"OpenSSH for Windows" version**
0.0.12.0
 
**Server OperatingSystem**
Windows Server 2012 Standard

**Client OperatingSystem**
Ubuntu 16.04

I generated the keys and the public key is in the authorized_keys file, the authentication works when I open the session with "ssh -i .ssh/id_rsa  -l rexecdev1@mydomain.com -T server1.mydomain.com" from Ubuntu but even if "whoami /user" returns the correct domain user I get "Access denied" when I try to reach a domain ressource like SYSVOL.
If I authenticate with ""ssh -i .ssh/id_rsa  -l rexecdev1 -T server1.mydomain.com" (without the domain suffix to the username" I get prompted for the username and after successfull logon I have access to domain ressources (whoami /user returns the same ID).

In this second variant ssh-agent.log shows : 
6240 12:11:26 036 debug1: matching key found: file C:\\Users\\rexecdev1/.ssh/authorized_keys, line 1 RSA SHA256:ZQ05YimDlCK8NokhKHLw0FUcqJI6d0sT3SZoEslPAgA
....
9052 12:20:35 610 debug1: LsaLogonUser failed NTSTATUS: 1

And the event viewer : 
``
Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          16.05.2017 12:20:35
Event ID:      4625
Task Category: Logon
Level:         Information
Keywords:      Audit Failure
User:          N/A
Computer:      Server1.mydomain.com
Description:
An account failed to log on.

Subject:
	Security ID:		SYSTEM
	Account Name:		SERVER1$
	Account Domain:		MYDOMAIN
	Logon ID:		0x3E7

Logon Type:			3

Account For Which Logon Failed:
	Security ID:		NULL SID
	Account Name:		
	Account Domain:		SERVER1

Failure Information:
	Failure Reason:		Unknown user name or bad password.
	Status:			0xC000006D
	Sub Status:		0xC0000064

Process Information:
	Caller Process ID:	0x235c
	Caller Process Name:	C:\Program Files\OpenSSH\ssh-agent.exe

Network Information:
	Workstation Name:	-
	Source Network Address:	-
	Source Port:		-

Detailed Authentication Information:
	Logon Process:		sshagent
	Authentication Package:	MICROSOFT_AUTHENTICATION_PACKAGE_V1_0
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0
``
Any idea what I'm doing wrong ?

Thanks

**Comment by manojampalam** [comment]
See [this](https://github.com/PowerShell/Win32-OpenSSH/wiki/SSH-remote-sessions-on-Windows)
