### ISSUE TITLE
"latest" URL for download of binary?

### ISSUE THREAD

**Issue by yooakim** [PowerShell/Win32-OpenSSH#73]
Would it be possible to setup the build process so that the latest version has a URL of the format:

```
https://github.com/PowerShell/Win32-OpenSSH/releases/latest/OpenSSH-Win32.zip
```

In order to write simple instructions and scripts to install it is a lot easier if there is a dedicated URL that always points to the most current version.

**Comment by manojampalam** [comment]
Yes. Daily automated builds (and links to stable and latest builds) will come online end of February.

**Comment by RamblingCookieMonster** [comment]
Looking forward to it, this would be very helpful until things stabilize.

**Comment by manojampalam** [comment]
Try https://github.com/PowerShell/Win32-OpenSSH/releases/download/latest/OpenSSH-Win64.zip
and
https://github.com/PowerShell/Win32-OpenSSH/releases/download/latest/OpenSSH-Win32.zip

I'll publish a new build from latest sources in couple of days.

**Comment by manojampalam** [comment]
See steps in Wiki on how to get automatic links to latest release packages
