### ISSUE TITLE
PowerShell on Linux hangs in SSH session from Windows 

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/Win32-OpenSSH#733]
Please answer the following

**"OpenSSH for Windows" version**
0.0.14.0
 
**Server OperatingSystem**
Linux jaiello-centos 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Client OperatingSystem**
Microsoft Windows 10.0.16199

**What is failing**
After starting PowerShell on the Linux side, I can't input characters at all. The only way to get out of that hung state is to use `Ctrl+Break` which pops me completely out of the SSH session. `Ctrl+C` does nothing. 

**Expected output**
I can use PowerShell normally in that remote SSH session on Linux. 

**Actual output**
Nothing.

Note: @bagajjal isn't getting a clean repro on this, so the onus is on me to try this on a non-Insider build so we can narrow this down to a conhost problem or something else.

**Comment by MaximoTrinidad** [comment]
FYI

When connected from Windows 10 Insider Build 16199 to Ubuntu 16.04, is getting hung after starting PowerShell under ssh.  Pressing Ctrl-C doesn't work to get out of the session. 

In Windows, under PowerShell Core 6.0.0-beta.1, using OpenSSH ver 0.0.13.0:
c:> ssh user@linuxSystem

![linuxwnssh_01_2017-05-22_19-08-56](https://cloud.githubusercontent.com/assets/19892435/26416592/71a9bda6-4084-11e7-8620-120899e80063.jpg)

:)

**Comment by SteveL-MSFT** [comment]
This repros for me on 16197.  Using Ubuntu16.04 OpenSSH client works fine.

**Comment by manojampalam** [comment]
@joeyaiello can you please try it out with the latest release?

**Comment by MaximoTrinidad** [comment]
It's working in Ubuntu 17.10 with PSCore 6.0.1 OpenSSH both ways.

**Comment by manojampalam** [comment]
Thanks for validating
