### ISSUE TITLE
SSH_ORIGINAL_COMMAND missing in environment

### ISSUE THREAD

**Issue by mayo** [PowerShell/Win32-OpenSSH#737]
Please answer the following

**"OpenSSH for Windows" version:**
0.0.14.0
 
**Server OperatingSystem**
Windows Server 2012 R2 Standard

**Client OperatingSystem**
CentOS 7

**What is failing**
With the following in sshd_config, the `SSH_ORIGINAL_COMMAND` environment variable is missing after login is complete.
```
Match User *
    ForceCommand cmd.exe
```

**Expected output**
There should be `SSH_ORIGINAL_COMMAND` variable set

**Actual output**
The only SSH env variables are:
```
SSH_ASYNC_STDERR=1                                                              
SSH_ASYNC_STDIN=1                                                               
SSH_ASYNC_STDOUT=1                                                              
SSH_AUTH_SOCK=ssh-agent                                                         
SSH_CLIENT=10.10.10.10 52140 22                                                 
SSH_CONNECTION=10.10.10.10 52140 10.10.10.20 22 
```

**Comment by bagajjal** [comment]
@mayo -it turns out to be the unix openssh issue.. could you please test on the unix machine and see if it works fine..

In the below code snippet, original_command is always set to command (which is NULL).. this is causing the issue... 

![image](https://cloud.githubusercontent.com/assets/23668037/26741912/3b832948-4790-11e7-8c28-71de5c517072.png)

**Comment by bagajjal** [comment]
Tested on the Ubuntu machine.. Its base unix code issue
![image](https://cloud.githubusercontent.com/assets/23668037/26804607/636bafe2-49fd-11e7-8862-074216cf9913.png)

**Comment by bagajjal** [comment]
@mayo - The code works fine with no issues..
My initial understanding is wrong.. 

SSH_ORIGINAL_COMMAND will have the command specified by the client..

When you are doing "ssh user@ip hostname", in this case the SSH_ORIGINAL_COMMAND will be set to hostname... Here "hostname" is the command specified by the client.

If you are doing normal ssh with no command "ssh  user@ip" then the SSH_ORIGINAL_COMMAND will not be set...
