### ISSUE TITLE
Docker machine fails when using OpenSSH-Win32

### ISSUE THREAD

**Issue by gbraad** [PowerShell/Win32-OpenSSH#738]
**"OpenSSH for Windows" version**
0.0.12.0
 
**Server OperatingSystem**
Windows 10 Pro, 1703 (15063.296)

**Client OperatingSystem**
  * https://github.com/minishift/minishift-b2d-iso (tinycore)
  * https://github.com/minishift/minishift-centos-iso (centos7)

**What is failing**
During the startup using Docker machine, when openssh-win32 is on the path, it is not possible to establish a connection to provision the virtual machine.

**Expected output**
exit status 255

**Actual output**
exit status 0

**More information**
  * https://github.com/minishift/minishift/issues/957
  * https://github.com/docker/machine/issues/3104

```powershell
PS> $env:PATH += "path to openssh-win32"
PS> $env:HYPERV_VIRTUAL_SWITCH="Wireless"
PS> minishift.exe start --show-libmachine-logs -v 5
```

**Comment by gbraad** [comment]
The same problem exists for `minikube`:

```powershell
PS> $env:PATH += "path to openssh-win32"
PS> .\minikube-windows-amd64.exe start --vm-driver hyperv --hyperv-virtual-switch "Wireless" -v 9
```
	Starting local Kubernetes v1.6.0 cluster...
	Starting VM...
	Found binary path at C:\Users\gbraad\Downloads\minikube-windows-amd64.exe
	Launching plugin server for driver hyperv
	Plugin server listening at address 127.0.0.1:65380
	() Calling .GetVersion
	Using API Version  1
	() Calling .SetConfigRaw
	() Calling .GetMachineName
	(minikube) Calling .GetState
	(minikube) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive
	( Get-VM minikube ).state
	(minikube) DBG | [stdout =====>] : Running
	Waiting for SSH to be available...
	(minikube) DBG |
	(minikube) DBG | [stderr =====>] :
	Getting to WaitForSSH function...
	(minikube) Calling .GetSSHHostname
	(minikube) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive
	( Get-VM minikube ).state
	(minikube) DBG | [stdout =====>] : Running
	(minikube) DBG |
	(minikube) DBG | [stderr =====>] :
	(minikube) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive
	(( Get-VM minikube ).networkadapters[0]).ipaddresses[0]
	(minikube) DBG | [stdout =====>] : 10.0.21.123
	(minikube) DBG |
	(minikube) DBG | [stderr =====>] :
	(minikube) Calling .GetSSHPort
	(minikube) Calling .GetSSHKeyPath
	(minikube) Calling .GetSSHKeyPath
	(minikube) Calling .GetSSHUsername
	Using SSH client type: external
	&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@10.0.21.123 -o IdentitiesOnly=yes -i C:\Users\gbraad\.minikube\machines\minikube\id_rsa -p 22] C:\Users\gbraad\Downloads\OpenSSH-Win64\ssh.exe <nil>}
	About to run SSH command:
	exit 0
	SSH cmd err, output: exit status 255:
	Error getting ssh command 'exit 0' : ssh command error:
	command : exit 0
	err     : exit status 255
	output  :
	Getting to WaitForSSH function...
	(minikube) Calling .GetSSHHostname
	(minikube) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive
	( Get-VM minikube ).state
	(minikube) DBG | [stdout =====>] : Running
	(minikube) DBG |
	(minikube) DBG | [stderr =====>] :
	(minikube) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive
	(( Get-VM minikube ).networkadapters[0]).ipaddresses[0]
	(minikube) DBG | [stdout =====>] : 10.0.21.123
	(minikube) DBG |
	(minikube) DBG | [stderr =====>] :
	(minikube) Calling .GetSSHPort
	(minikube) Calling .GetSSHKeyPath
	(minikube) Calling .GetSSHKeyPath
	(minikube) Calling .GetSSHUsername
	Using SSH client type: external
	&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@10.0.21.123 -o IdentitiesOnly=yes -i C:\Users\gbraad\.minikube\machines\minikube\id_rsa -p 22] C:\Users\gbraad\Downloads\OpenSSH-Win64\ssh.exe <nil>}
	About to run SSH command:
	exit 0
	SSH cmd err, output: exit status 255:
	Error getting ssh command 'exit 0' : ssh command error:
	command : exit 0
	err     : exit status 255
	output  :

**Comment by manojampalam** [comment]
dup #666 
check https://github.com/PowerShell/Win32-OpenSSH/issues/666 and reopen if needed.
