### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by ylluminate** [PowerShell/Win32-OpenSSH#739]
First, is this project the `sshd` that ships default in Windows 10 now?  

If so, I'm having some trouble here hunting down the config file or reg key(s) in order to configure this more fully. At present this is not working too well with PowerShell interoperability:
https://github.com/lukesampson/scoop/issues/1525

**Comment by manojampalam** [comment]
No. Take a look at https://github.com/PowerShell/Win32-OpenSSH/issues/318

**Comment by ylluminate** [comment]
That's very nice to know. Appreciate your pointing over to that issue. Definitely need to know the "right" way to do this now with the imminent integration en route.
