### ISSUE TITLE
packet_write_wait: Broken pipe

### ISSUE THREAD

**Issue by keza** [PowerShell/Win32-OpenSSH#741]
Error when i try to connect mac to win 7 pc

debug1: Authentication succeeded (password).
Authenticated to 10.6.130.33 ([10.6.130.33]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
packet_write_wait: Connection to 10.6.130.33 port 22: Broken pipe

**Comment by manojampalam** [comment]
shared detailed server side logs - https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Comment by manojampalam** [comment]
Reopen with relevant details.
