### ISSUE TITLE
After install script "Windows has encountered a critical problem and will restart automatically"

### ISSUE THREAD

**Issue by dariusj18** [PowerShell/Win32-OpenSSH#743]
**"OpenSSH for Windows" version**
v0.0.14.0
 
**Server OperatingSystem**
Windows Server 2008 R2 Datacenter

**What is failing**
After running the install script I get the message 

> Windows has encountered a critical problem and will restart automatically in one minute. Please save your work now.

Then the server restarted

**Comment by manojampalam** [comment]
This is strange. Do you have any anti-virus programs installed on your computer that might flag ssh binaries as malicious?

**Comment by dariusj18** [comment]
Symantec Endpoint Protection is installed

**Comment by bagajjal** [comment]
This can be closed?
