### ISSUE TITLE
OpenSSHUtils.psm1 Uses Unapproved Verbs

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#745]
When loading OpenSSHUtils.psm1 the following warning is issued:

WARNING: The names of some imported commands from the module 'OpenSSHUtils' include unapproved
verbs that might make them less discoverable. To find the commands with unapproved verbs, run the
Import-Module command again with the Verbose parameter. For a list of approved verbs, type
Get-Verb.

I think a more appropriate verb choice than "Fix" would be "Reset".

I know this isn't a critical error - but the usability semantics of PowerShell are one of it's hallmark features for some good reasons :)

**Comment by bingbing8** [comment]
@DarwinJS good catch.  We will go with:
Repair-SshdConfigPermission

**Comment by bingbing8** [comment]
@DarwinJS , I added a commit to the fix of this issue. Since we are discussing how to handle the future breaking changes and release of scripts, I can't submit the changes soon. Below include multiple fixes if you are interested:
1. use valid verb, 
2. psd1 file to specify version, 
3. -confirm support, 
4. workaround the error "the security identifier is not allowed to be the owner of this object" on downlevel machine.

**Comment by DarwinJS** [comment]
Wow you can refactor code at lightning speed!  Thanks for diving into this.

I tested the updated module code from the branch you noted.

I can no longer control the prompting behavior.  

The -quiet switch is no longer available and the -confirm switch does not suppress the 30 second time-out confirmation prompt - so we are back to extending an automated install of a basic sshd server to 18 minutes even when there are only a few user files to process.  In addition, the onscreen logging is quite a bit longer with all the prompts.

When I requested that -confirm be used instead of -quiet I also meant that the 30 second timeout on each permission command should be suppressed as I have pre-confirmed my desire to make that happen by using "-confirm".  In fact, I wasn't as concerned about properly implemented "ShouldProcess" support as I was about using a more conventional switch to suppress any confirmation prompt behavior.  It is cool that full shouldprocess has been implemented - but I think that the confirm switch should also control this prompting behavior or the -quiet switch should be reinstated.


I am also still getting errors on setting the permissions on individual user files - I thought that might have been in scope to fix when you were transitioning the code to only write the access control list and not the entire permissions object when only removing ACLs?

Thanks so much for all your work on this and I apologize if my requests have been unclear and/or too divided across different Github issues!

![image](https://user-images.githubusercontent.com/11597190/27002632-6dae8cd0-4db4-11e7-8198-57ed2ea6fab1.png)

**Comment by bingbing8** [comment]
@DarwinJS  to Suppress the prompt, you can user -confirm:$false when you call the cmdlet. It is equivalent to -quiet

**Comment by bingbing8** [comment]
@DarwinJS Sorry for the inconvenience.
1. The equivalent of "-quiet" when use the new utility scripts is "-confirm:$false" to Suppress the prompt. Could you please try?
2. I see your request not use shouldprocess, but where is the promp "Respond within 30 seconds or the default selection will be chosen" come from? If you directly run the utility scripts, you won't see the timeout. Is it from your chocolatey scripts?

3. One challenge for me is that I can't repro the error you see about setting the permission on individual user profiles on my win 7 machine even I put multiple authorized_keys files at other standard user profile path.  The only way I can work is to send you the fix and test on your machine, which slow down your package. sorry for that.
Anyway, 
I fixed the "the security identifier is not allowed to be the owner of this object" by p/invoke .net to adjust the privilege now.  I also tested on my win7 and Nano server. Please check out https://github.com/PowerShell/openssh-portable/pull/164 and let me know if you still see the error.
