### ISSUE TITLE
Would Be Nice to Have More Verbose Logging in Fix*.ps1

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#751]
It would be very helpful if these utility scripts emitted console output as to exactly which files they are changing (which reveals the list of files they have found) and what the changes are.

For example, in these two loops: https://github.com/PowerShell/Win32-OpenSSH/blob/2c3a1a95d0b36697be3da814a7fc08bdfb7db0cb/contrib/win32/openssh/FixUserFilePermissions.ps1#L4-L11

If console message suppression is desirable for some scenarios, please provide a switch to suppress messages that does not also suppress confirmation prompts.  (related to #749)

I can submit a PR for this request if that is acceptable.

**Comment by manojampalam** [comment]
Yes please.

**Comment by bingbing8** [comment]
@DarwinJS  the scripts currently already print all the files they are changing and what actions are done to each file to the console.  Please checkout here: 
file path printout: https://github.com/PowerShell/Win32-OpenSSH/blob/2c3a1a95d0b36697be3da814a7fc08bdfb7db0cb/contrib/win32/openssh/OpenSSHUtils.psm1#L147
sample action printout: https://github.com/PowerShell/Win32-OpenSSH/blob/2c3a1a95d0b36697be3da814a7fc08bdfb7db0cb/contrib/win32/openssh/OpenSSHUtils.psm1#L201
What else do you want to emit to console? Can you give an example?
![microsoftteams-image](https://user-images.githubusercontent.com/12284203/26904558-54222f7a-4b97-11e7-8de5-e15afc14064c.png)

**Comment by DarwinJS** [comment]
That works fine @bingbing8!
