### ISSUE TITLE
fatal: sshd_hostkey_sign: ssh_agent_sign failed: agent refused operation

### ISSUE THREAD

**Issue by dariusj18** [PowerShell/Win32-OpenSSH#753]
**Server OperatingSystem**
Windows Server 2012 R2 Datacenter

**Release**
0.0.15.0

I think I ran everything correctly however when I run the service under the NT SERVICE\SSHD user i get this

> fatal: sshd_hostkey_sign: ssh_agent_sign failed: agent refused operation/

in the logs, and a "Connection reset" from my client.

When I run sshd.exe as Administrator it works

I figure there has to be some kind of permissions I am missing, howver I ran the FixHostFilePermissions.ps1 script and the FixUserFilePermissions.ps1 script just in case.

**Comment by manojampalam** [comment]
FixHostfilePermissions.ps1 should have set the right permissions. 
Can you dump the permissions on each of your host private keys?
icacls .\ssh_host_rsa_key
icacls .\ssh_host_dsa_key
icacls .\ssh_host_ecdsa_key
icacls .\ssh_host_ed25519_key

**Comment by dariusj18** [comment]
Those commands return 

BUILTIN\Administrators:(F)
NT AUTHORITY\SYSTEM:(F)
SERVERNAME\Administrator:(R,W)

**Comment by manojampalam** [comment]
Can you try running FixHostFilePermissions.ps1 again ? It should have added read permissions (R) to sshd account and should have removed entry for SERVERNAME\Administrator.

you should see output like this:
NT AUTHORITY\SYSTEM:(F)
BUILTIN\Administrators:(F)
NT SERVICE\SSHD:(R)

**Comment by dariusj18** [comment]
I didn't see this before, however I think I see the problem, I have Powershell 4.0, so I get errors when running the script

Get-ItemPropertyValue : The term 'Get-ItemPropertyValue' is not recognized as the name of a cmdlet,

and more

**Comment by dariusj18** [comment]
I manually change the permissions and now i see them as 

> NT AUTHORITY\SYSTEM:(F)
> BUILTIN\Administrators:(F)
> NT SERVICE\sshd:(R)
> 

However in the log I now see 

> @@@@@@@@@@@@ ...
> WARNING: UNPROTECTED PRIVATE KEY FILE!          @
> @@@@@@@@@@@@@ ...
> Permissions for './ssh_host_rsa_key' are too open.
> It is required that your private key files are NOT accessible by others.

for each of the private key files

**Comment by manojampalam** [comment]
you'll need to change the owner too (for each of the private keys):
icacls .\ssh_host_dsa_key /setowner system

on top of what you already did:
icacls .\ssh_host_dsa_key /remove SERVERNAME\Administrator
icacls .\ssh_host_dsa_key /grant "NT SERVICE\SSHD":(R)

**Comment by dariusj18** [comment]
That worked, thank you.

**Comment by DarwinJS** [comment]
@dariusj18 - you said:

> I didn't see this before, however I think I see the problem, I have Powershell 4.0, so I get errors when running the script
> Get-ItemPropertyValue : The term 'Get-ItemPropertyValue' is not recognized as the name of a cmdlet, and more

Can you please tell which script(s) generated these?

**Comment by dariusj18** [comment]
It was FixHostfilePermissions.ps1

**Comment by duanyao** [comment]
I saw "Get-ItemPropertyValue" error from FixHostfilePermissions.ps1 too. It's a Win7 64bit and I installed WMF 4.0. Does this script only run in powershell 3.0? However even if I start powershell with `-version 3.0` the errors persist.
