### ISSUE TITLE
Build 0.0.14.0 can't configure multiple TCP ports to listen

### ISSUE THREAD

**Issue by schall8** [PowerShell/Win32-OpenSSH#754]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 0.0.14.0

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows Server 2012 Datacenter

**Client OperatingSystem**
N/A
**What is failing**
updating the sshd_config file to include the following lines:
Port 22
Port 12345
Port 12346

netstat -a shows only port 22 listening.  On linux this configuration works just fine.  How can i add additional ports to openssh daemon on windows?

**Expected output**
portqry -n <servername> -e 12345 returns listening
or 
portqry -n <servername> -e 12346 returns lisstening

**Actual output**
NOT Listening

**Comment by manojampalam** [comment]
Seems to work for me. Can you try running sshd in debug mode (sshd -d) and see if there are any issues/failures binding to other ports ?

**Comment by schall8** [comment]
C:\Program Files\OpenSSH>sshd -d
debug1: Bind to port 22 on ::.
Server listening on :: port 22.
debug1: Bind to port 22 on 0.0.0.0.
Server listening on 0.0.0.0 port 22.

Thank you for pointing me to the interactive debug made me double check and notepad saved the config with the .txt extension.  it is binding now properly, thank you for your time.

C:\Program Files\OpenSSH>sshd -d
debug1: Bind to port 12346 on ::.
Server listening on :: port 12346.
debug1: Bind to port 12346 on 0.0.0.0.
Server listening on 0.0.0.0 port 12346.
debug1: Bind to port 12345 on ::.
Server listening on :: port 12345.
debug1: Bind to port 12345 on 0.0.0.0.
Server listening on 0.0.0.0 port 12345.
debug1: Bind to port 22 on ::.
Server listening on :: port 22.
debug1: Bind to port 22 on 0.0.0.0.
Server listening on 0.0.0.0 port 22.
