### ISSUE TITLE
Please remove 30 second timeout when -quiet is not used or provide pass through parameter on Fix*.ps1 helpers

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#759]
FixHostFilePermissions.ps1 and FixUserFilePermissions.ps1 do not make their calls using the -quiet parameter.

On a very simple installation with only one SSH user the 30 second delay occured 36 times or 18 minutes worth.

Given that openssh v0.0.15.0 will not function without these permissions changes, I think the prompting and the delay are a little overcautious.  Especially since by the time the FixHostFilePermissions.ps1 script is run, the new files are already on the system - answering "no" will result in a broken setup.

Could the prompt / delay either be:

- removed
- reduced in default time length
- or a pass through parameter "-quiet" added to FixHostFilePermissions.ps1 and FixUserFilePermissions.ps1

If these changes can be made and a pull request created - I will grab the code from the pull request and include it in the chocolatey package for 0.0.15.0 as an override of the files in the zip archives.

**Comment by bingbing8** [comment]
@DarwinJS 
1. I don't have timeout set in any of these 3 scripts. Which timeout do you refer to?
2. both FixHostFilePermissions.ps1 and FixUserFilePermissions.ps1 support -quiet mode. Did you try ```FixHostFilePermissions.ps1 -quiet```?

**Comment by DarwinJS** [comment]
I have tried -quiet and it does pass through - sorry my bad! 
There is a 30 second timeout on each attempt to set permissions when -quiet is not used.
It would still be nice to have "-confirm" functionality separated from "-quiet" (no logging messages) functionality as per #749

**Comment by bingbing8** [comment]
@DarwinJS we will change to -confirm.
