### ISSUE TITLE
Error Setting Permissions For Clean Removal

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#764]
To prepare for a clean removal, the chocolateyuninstall.ps1 script must take ownership of key and config files.

However, when I call "Repair-File Permission" with no parameters (to only set the owner to the current user), I get the below error.

For the time being I am setting $ErrorActionPreference = 'SilentlyContinue' right before the call.

Is there a way to make the default behavior simply give the current user ownership if none of the other parameters are specified?

![image](https://user-images.githubusercontent.com/11597190/27016484-63d78776-4eee-11e7-9ef2-25777c2f05b9.png)

**Comment by DarwinJS** [comment]
$ErrorActionPreference did not end up working when embedded in the uninstall.

Neither did the following code when used in "ChocolateyUninstall.ps1" (was trying to make sure the parameters were populated so the permissions run could complete successfully):

````
    Import-Module "$toolsdir\OpenSSHUtils"
    $RunningUser = New-Object System.Security.Principal.NTAccount($($env:USERDOMAIN), $($env:USERNAME))
    dir "$TargetFolder\*" | % {repair-filepermission -FilePath $_.fullname -Owners $RunningUser -ReadAccessOK $RunningUser -AnyAccessOK $RunningUser -confirm:$false}

    If (Test-Path $TargetFolder) {Remove-Item "$TargetFolder" -Recurse -Force}
````

I think I will publish the chocolatey package and just mention that the chocolatey **uninstall** switch /DeleteConfigAndServerKeys does not work yet until I can find a fix.  

Although I think this switch is needed for a complete solution - I'm not sure how much use it actually gets at this early stage in the life of win32-openssh.

An uninstall without this switch works fine as it does not attempt to delete the config nor key files.

Let me know if there is a way for me to call the current version of Repair-FilePermission that would fix this error.  Thanks!

**Comment by bingbing8** [comment]
@DarwinJS  it is a bug missing a pair of parenthesis in the script. I added a fix (https://github.com/PowerShell/openssh-portable/pull/165). Below line can workaround it if you don't want to update the scripts in the package. 
 ```Repair-FilePermission .\ssh_host_dsa_key -ReadAccessNeeded "NT SERVICE\sshd"```

We are curious the reason that chocolateyuninstall.ps1 script need to take ownership of key and config files. Administrators group should have full control on those files. If the user is member of the admin group, he/she should be able to delete those files.

**Comment by DarwinJS** [comment]
@bingbing8 - I don't know the answer to "why" - but I do know that without doing this, the key files are not removed on Windows 10.  Win7 seems to work.

**Comment by DarwinJS** [comment]
I updated to the latest module and still get the error if I don't provide -ReadAccessNeeded - but the workaround does work.  Thanks.

**Comment by bingbing8** [comment]
@DarwinJS did you import the module with -force parameter. after this fix, i can do ```Repair-FilePermission .\ssh_host_dsa_key``` successfully on win7 and win10 including Nano. can you post the screenshot again if you still repro? Thanks! Here is my screenshot before and after:
![before](https://user-images.githubusercontent.com/12284203/27153592-e697e61e-5106-11e7-82ce-23fccb588b15.png)
![repair](https://user-images.githubusercontent.com/12284203/27153597-ecb47bca-5106-11e7-9886-7dadfc26ecdd.png)
![after](https://user-images.githubusercontent.com/12284203/27153603-f2350a2e-5106-11e7-8739-f897b2631fe3.png)

**Comment by bingbing8** [comment]
move to Jun-End until get response from @DarwinJS

**Comment by DarwinJS** [comment]
The -force parameter does indeed work!
Now using this approach in chocolatey package 0.0.16.0
