### ISSUE TITLE
Chocolatey Package for 0.0.15.0 Released

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#765]
Big thanks to @bingbing8 for quick response in refactoring the new opensshutils.psm1 module to work with needs that were discovered when creating the chocolatey package.

**Comment by gbraad** [comment]
This closes: https://github.com/DarwinJS/ChocoPackages/issues/34 and https://github.com/PowerShell/Win32-OpenSSH/issues/666 Thanks!

**Comment by bingbing8** [comment]
Great to know it works now. Thanks!
