### ISSUE TITLE
SSHD service fails to start on Windows 7

### ISSUE THREAD

**Issue by bingbing8** [PowerShell/Win32-OpenSSH#770]
Please answer the following

**"OpenSSH for Windows" version**
0.0.16.0
 
**Server OperatingSystem**
win7

**Client OperatingSystem**

**What is failing**
Service failed to start with error:
A privilege that the service requires to function properly does not exist in the service account configuration.
You may use the Services Microsoft Management Console (MMC) snap-in (services.msc) and the Local Security Settings MMC snap-in (secpol.msc) to view the service configuration and the account configuration.
**Expected output**
sshd service should be able to start.

**Actual output**

**Comment by manojampalam** [comment]
Issue: Install script on Win7 fails to assign SeAssignPrimaryTokenPrivilege privilege  to sshd account 

Work around: 
- Open control panel and navigate to
  - Administrative Tools >  Local Security Policy > Local Policies > User Rights Assignment.
- Double click **Replace a Process Level Token**
- Add **NT Service\SSHD**

**Comment by mbtts** [comment]
The location "_From this location_" needs to be your machine name (which may not be the default).

**Comment by NiQ1** [comment]
For me it still doesn't work (same error) even with that permission granted.

**Comment by bingbing8** [comment]
@NiQ1, which version of openssh do you run? sshd is now run under local system now.

**Comment by stevenbrix** [comment]
I'm on a recent insiders build (18281) and am still seeing this issue. Doing the above workaround didn't work.

**Comment by bingbing8** [comment]
@stevenbrix, the behavior you see may be different from the issue aboe. Could you post the output of ```sshd -ddd```?
Also, did you follow the [Install Win32 OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH), especially this sentence: Make sure binary location has the Write permissions to just to SYSTEM, Administrator groups. Authenticated users should and only have Read and Execute? could you please post the output of ```(Get-ACL sshd.exe).Access```?

**Comment by stevenbrix** [comment]
Thanks @bingbing8, I've been following the instructions I found online [here](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/). Are these no longer relevant?

Here's the output from _ssshd -ddd_
PS C:\WINDOWS\system32> sshd -ddd
debug2: load_server_config: filename __PROGRAMDATA__\\ssh/sshd_config
debug3: Failed to open file:C:\\ProgramData\\ssh/sshd_config error:2
__PROGRAMDATA__\ssh/sshd_config: No such file or directory
PS C:\WINDOWS\system32>

**Comment by bingbing8** [comment]
@stevenbrix, this is a completely different issue from the original one on win7
looks like you are using inbox binaries. For the log you post, looks like you never try to start the service yet. If you ever try to start sshd service, the first thing it try to do is to create %PROGRAMDATA%\ssh folder and create keys and copy sshd_config under that folder.
What error do you get when you ```net start sshd```?

**Comment by stevenbrix** [comment]
Yeah, I didn't realize I had to do `net start sshd`. It works once I do that, however 
`./ssh-keygen.exe -A` doesn't seem to do anything.

**Comment by bingbing8** [comment]
@stevenbrix ,```./ssh-keygen.exe -A ``` only generates keys under %PROGRAMDATA%\ssh. but since ```net start sshd``` already generate the keys, ```./ssh-keygen.exe -A ``` will do nothing after that.
