### ISSUE TITLE
OpenSSH-Win32.zip

### ISSUE THREAD

**Issue by cashcat** [PowerShell/Win32-OpenSSH#773]
OpenSSH-Win32.zip can't download...please check...
OpenSSH-Win64.zip can't download...please check...

Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**

**What is failing**

**Expected output**

**Actual output**

**Comment by bingbing8** [comment]
@cashcat I tried, both zip package download fine. Is there anything wrong on your machine or network?

**Comment by manojampalam** [comment]
Reopen with details if this issue still persists.
