### ISSUE TITLE
ssh-agent cannot be started

### ISSUE THREAD

**Issue by TomJampen** [PowerShell/Win32-OpenSSH#775]
Hi

**"OpenSSH for Windows" version**
0.0.16.0
 
**Server OperatingSystem**
Windows Server 2008 R2 Enterprise

**Client OperatingSystem**
Debian Stretch

**What is failing**
Starting the ssh-agent service with "Start-Service ssh-agent" does not work:

    Start-Service : Der Dienst "ssh-agent (ssh-agent)" kann aufgrund des folgenden Fehlers nicht gestartet werden: Der Dienst ssh-agent kann nicht auf dem Computer . gestartet werden.
    Bei Zeile:1 Zeichen:14
    + Start-Service <<<<  ssh-agent
        + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
        + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

I've followed the installation guide, installed the server, generated keys, fixed the permissions. I've even followed the wordaround for #770, but ssh-agent cannot be started.

Thanks for your help,
Tom

**Comment by bagajjal** [comment]
Looks like ssh-agent.exe can't be opened (OpenError: (System.ServiceProcess.ServiceController:ServiceController).. 

Please check the access permissions
1) cd to folder where ssh-agent.exe is present
2) (Get-Item .\ssh-agent.exe).GetAccessControl('ACCESS').Access

**Comment by TomJampen** [comment]
Thanks for your fast reply. ssh-agent.exe is present and the permissions are the following:

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : NT-AUTORITÄT\SYSTEM
IsInherited       : True
InheritanceFlags  : None
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : VORDEFINIERT\Administratoren
IsInherited       : True
InheritanceFlags  : None
PropagationFlags  : None

FileSystemRights  : ReadAndExecute, Synchronize
AccessControlType : Allow
IdentityReference : VORDEFINIERT\Benutzer
IsInherited       : True
InheritanceFlags  : None
PropagationFlags  : None

**Comment by manojampalam** [comment]
Try doing the following in an interactive and elevated cmd.exe
ssh-agent.exe -ddd

**Comment by TomJampen** [comment]
I tried exactly as you told me (in an elevated cmd.exe) and got the followin error message:
C:\Program Files\OpenSSH-Win64/sshd_config: Permission denied

That's weird, because I set the permissions using the FixHostFilePermissions.ps1.

I've just run it again, now and the output is strange. It looks like a language issue:

Mostly the output is:

Current owner: ''. 'NT AUTHORITY\SYSTEM' should own 'C:\Program Files\OpenSSH-Win64\sshd_config'.

But for a few files:

Current owner: 'NT-AUTORITÄT\SYSTEM'. 'NT AUTHORITY\SYSTEM' should own 'C:\Program Files\OpenSSH-Win64\ssh_host_dsa_key.pub'.

**Comment by manojampalam** [comment]
Thanks. This is indeed a localization issue. We'll have it fixed in the next drop. Please use 0.0.14.0 for now (this release does not have the permissions restrictions yet)

**Comment by bingbing8** [comment]
@TomJampen this is due to the same as #771. The fix has been checked in and will be available in next drop. Or please follow [Security protection wiki](https://github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-Win32-OpenSSH) to manually fix the file permissions if you run on non-English build.

**Comment by manojampalam** [comment]
dup #771

**Comment by mohamedalbyoumi** [comment]
agent_start pid:21744, dbg:1
cannot create agent root reg key, ERROR:5
