### ISSUE TITLE
AllowGroups appears to no longer function in sshd_config

### ISSUE THREAD

**Issue by glydeen** [PowerShell/Win32-OpenSSH#777]
**OpenSSH for Windows**
0.0.16.0
 
**Server OperatingSystem**
 Windows Server 2016 Standard

**Client OperatingSystem**
Using OS X 10.12.5 Terminal (SFTP)

**What is failing**
Unable to authenticate when using "AllowGroups" in the sshd_config

AllowGroups	"SFTP-Users" (Group does exist in AD)

**Expected output**
Successful login

**Actual output**
Permission denied, please try again.

**Log shows**

9664 19:09:43:762 error: NetUserGetLocalGroups() failed with error: 2221
9664 19:09:43:762 User John.doe from X.X.X.X not allowed because not in any group
9664 19:09:43:762 Failed keyboard-interactive for invalid user John.doe from X.X.X.X port 53724 ssh2
9664 19:09:43:794 Failed password for invalid user John.doe from X.X.X.X port 53724 ssh2
9664 19:09:43:809 Failed keyboard-interactive for invalid user John.doe from X.X.X.X port 53724 ssh2
9664 19:09:45:262 Failed keyboard-interactive for invalid user John.doe from X.X.X.X port 53724 ssh2
9664 19:09:45:294 Failed password for invalid user John.doe from X.X.X.X port 53724 ssh2
9664 19:09:45:309 Failed keyboard-interactive for invalid user John.doe from X.X.X.X port 53724 ssh2
9664 19:09:45:309 error: maximum authentication attempts exceeded for invalid user John.doe from X.X.X.X port 53724 ssh2
9664 19:09:45:309 Disconnecting invalid user John.doe X.X.X.X port 53724: Too many authentication failures

**Comment by manojampalam** [comment]
Is John.doe a domain account? If so can you try specifying in a format detailed at https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples

Domain users: Domain needs to be explicitly specified. Any of the following formats work 
ssh -l user@domain host
ssh domain\user@host
ssh user@domain@host

Also, would you know how these 2 user Ids are associated - gary.lydeen and John.doe ?
