### ISSUE TITLE
win7: run powershell on remote ssh session does not return until ENTER is click

### ISSUE THREAD

**Issue by bingbing8** [PowerShell/Win32-OpenSSH#780]
Please answer the following
**"OpenSSH for Windows" version**
0.0.16.0
 
**Server OperatingSystem**
Windows 7 Professional

**Client OperatingSystem**
Windows 7 Professional

**What is failing**
```ssh username@localhost powershell get-process ``` does not return

**Expected output**
the command should return

**Actual output**
the command hangs

**Comment by HSSupport** [comment]
can confirm this issue with 0.16 too
this issue REMAINS even if you remove open-ssh and reinstall version 0.15 (no idea if remains post-reboot though, cant reboot yet)

**Comment by HSSupport** [comment]
Hi

i have tested this on version 0.17, on windows server 2008 (SBS 2011) with powershell v2.
works on server 2012 and 2016, which have higher native versions of powershell - could this be the cause?

if you create a powershell script and call it via 'ssh "domain\user"@"host" "powershell -file FILE"' it will correctly process the file but then hang waiting for an enter.
once enter is pressed it finally correctly exits

this seems to occur on any script, my test is "write-host hello" and it hangs. even with "exit" at the end of the file

**Comment by sr-verde** [comment]
Try something like this (replacing `dir` by your command):

`$ ssh win7@10.10.10.10 'powershell.exe  "& {dir; Stop-Process -Force -Processname PowerShell}"'`

It’s not very … pretty, but should work.

**Comment by HSSupport** [comment]
Version 7.6.1.0p1
This issue seems to have come back when openssh is installed and running on a Server 2008 R2 (SBS 2011) machine. the Stop-Process workaround works fine, pressing enter works fine, but otherwise it doesnt actually finish.

i do wonder if this is because its running powershell v2.0. Server 2012 and Server 2016 dont have this issue.

thanks

**Comment by cryptid11** [comment]
AHAHAHAHAH "Resolution - Won't Fix" windows is just crap
another internal combustion engine/oil paradigm, total bullshit but still huge market power and very slow to get rid of
funny planet

**Comment by koldev** [comment]
The process killer workaround by sr-verde worked for me, but the real solution was to upgrade Powershell 2 to 5.1.
