### ISSUE TITLE
ConnectTimeout Option in config

### ISSUE THREAD

**Issue by syswipe** [PowerShell/Win32-OpenSSH#79]
Hi!
Please, explain me strange issue...
I've tried to move my personal config for ssh client from Linux to Windows 10 laptop. After that i've tried to connect to some host and have recieved an error:

> ssh syswipe.tk
ssh: connect to host syswipe.tk port 22: A non-blocking socket operation could not be completed immediately.

After commenting "ConnectTimeout" option in config, all works fine. Is this option implemented in Win version of OpenSSH? Or it isn't compatible with Windows network subsystem, or something else?

**Comment by quamrulmina** [comment]
"ConnectTimeout" option is not implemented in current Windows port of OpenSSH and should be avoided or commented out in ssh client "config" file .

**Comment by manojampalam** [comment]
This is now supported
