### ISSUE TITLE
Only AllowTcpForwarding without SFTP and without shell access

### ISSUE THREAD

**Issue by comsyspro** [PowerShell/Win32-OpenSSH#790]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
0.0.17.0
 
**Client OperatingSystem**
Windows 7

**What is failing**
Is it possible to configure in the sshd_config only functioning for "AllowTcpForwarding yes" but without SFTP and without shell access. What I tried so far:

uncommented subsystem to disable sftp:
`#Subsystem	sftp	sftp-server.exe`

added ForceCommand, but here the cmd shell is executed. On linux you could disable the shell by /bin/false, but here I didn't know what to do:
```
Match User sshuser
	AllowTcpForwarding yes
	X11Forwarding no
	PermitTunnel no
	GatewayPorts no
	AllowAgentForwarding no
	ForceCommand cmd.exe /K echo no shell access
```

So how you could resolve this correctly to use only AllowTcpForwarding without SFTP and without shell access?

**Expected output**

**Actual output**

**Comment by bagajjal** [comment]
Use

ForceCommand cmd.exe /C echo no shell access

Incase if you want to display the custom message ("no shell access") at the client side then add this line to sshd_config.
"PermitTTY no"

**Comment by comsyspro** [comment]
Thanks for your tip, but I solved it now with following code line:

```
Match User sshuser
	AllowTcpForwarding yes
        PermitTTY no
	ForceCommand cmd.exe /C echo noshell & pause
```
It is important to add `& pause` behind the echo command because it would otherwise exit the echo command directly after execution and the ssh connection will be interrupted. With the `& pause` command the connection stays open until you press the 'enter' key.

```
Match User sshuser
	AllowTcpForwarding yes
        PermitTTY no
        ForceCommand cmd.exe /C echo noshell & echo to exit the ssh connection press the 'enter' key & pause
```
But one problem exists in this case: The sftp server is not working now. So please tell if there is a workaround. At the moment my only idea were to install filezilla ftp server and tunnel the ftp traffic on port 21 through the exitsing ssh connection, but it would be easier to be able to also use the sftp-server.exe when using the ForceCommand parameter. 

Finally I got it work too by changing the following code line:
`ForceCommand sftp-server.exe`

So the complete config is now:

```
Match User sshuser
	AllowTcpForwarding yes
        PermitTTY no
        ForceCommand sftp-server.exe
```
With that a connecting ssh user can use TcpForwarding and can have a SFTP connection without a shell access.
