### ISSUE TITLE
Latest OpenSSHUtils.psm1 Not Compatible with Nano

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#794]
Opening new issue, rather than reopening #771 

The changes to OpenSSHUtils.psm1 do not work with Nano because they assume the ACL is returning user ids when Nano returns SIDs.

![image](https://user-images.githubusercontent.com/11597190/27830045-8c9ed06e-6092-11e7-81fe-5a16c894c5ee.png)

**Comment by DarwinJS** [comment]
FYI - The fix in the pull request is in the Chocolatey package for 0.0.17.0

**Comment by bingbing8** [comment]
@DarwinJS Thanks for the PR. I checked on my Nano server, all of the IdentityReference are of user ids. I think is this is not specific to Nano server. It could happen on other platforms too. I see in some cases where those virtual accounts are invalid on the machine, the identityReference is not translatable, then the identityReference are with sid string. for example, when openssh is uninstalled from the machine, but the file still has an ace to "nt service\sshd", in this case, its IdentityReference is in sid string type. not sure if those sid strings on your sshd_config are in this case though. 
I added comments on the PR. Thanks!

**Comment by DarwinJS** [comment]
@bingbing8 - I was indeed testing this on an "upgrade" - but I believe I was upgrading Win 7 as well and didn't see it.  Hopefully that code will help with whatever the conditions are where there occurs and it's good to know it is not Nano specific.
