### ISSUE TITLE
sshd service can not start on Windows 7

### ISSUE THREAD

**Issue by wim-h** [PowerShell/Win32-OpenSSH#795]
Please answer the following

**"OpenSSH for Windows" version**
0.0.17.0
 
**Server OperatingSystem**
Windows 7 Professional 32bit
Including the fix as per #770

**What is failing**
The sshd service fails to start

**Expected output**
A running sshd service.

**Actual output**
Starting the service yields the following error message:

Windows can not start the sshd service on Local Computer.

Error 2: The system cannot find the file specified.

After modifying the service configuration, changing ImagePath from:
  C:\Program Files\OpenSSH\sshd.exe
to:
  "C:\Program Files\OpenSSH\sshd.exe"

I am getting the following error:

  Windows could not start the sshd service on Local Computer.
Error 5: Access is denied

I did ran .\FixHostFilePermissions.ps1 -Confirm:$false
All files are looking good.

**Comment by bagajjal** [comment]
Are you starting the sshd from a cmd that's opened in administrative mode?

If this doesn't work then execute in debug mode (sshd.exe -ddd) to investigate further.

**Comment by manojampalam** [comment]
We may have missed testing 32-bit drop on Win7.  Can you check if you see the same issue with 0.0.16.0 too?

**Comment by wim-h** [comment]
Starting from an administrative command prompt works, it waits for incoming connections.
But executing an ssh command yields a forced close of sshd.exe:

The program has stopped working. Windows can check online for a solution to the problem.
. Check online. ...
. Close the program

Output of sshd.exe -ddd ( I've skipped the initial setup and key exchange parts, as that seems to work):
debug1: Entering interactive session for SSH2.
debug3: pipe - r-h:316,io:00435EE0,fd:4  w-h:312,io:00435F60,fd:6
debug2: fd 4 setting O_NONBLOCK
debug2: fd 6 setting O_NONBLOCK
debug1: server_init_dispatch
debug3: receive packet: type 90
debug1: server_input_channel_open: ctype session rchan 0 win 2097152 max 32768
debug1: input_session_request
debug1: channel 0: new [server-session]
debug2: session_new: allocate (allocated 0 max 10)
debug3: session_unused: session id 0 unused
debug1: session_new: session 0
debug1: session_open: channel 0
debug1: session_open: session 0: link with channel 0
debug1: server_input_channel_open: confirm session
debug3: send packet: type 91
debug3: receive packet: type 80
debug1: server_input_global_request: rtype no-more-sessions@openssh.com want_rep
ly 0
debug3: receive packet: type 98
debug1: server_input_channel_req: channel 0 request exec reply 1
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req exec
Starting session: command for rexusr from 172.17.1.5 port 30250 id 0
debug3: pipe - r-h:324,io:00435FE0,fd:7  w-h:320,io:00436060,fd:8
debug3: pipe - r-h:332,io:004360E0,fd:9  w-h:328,io:00436160,fd:10
debug3: pipe - r-h:340,io:004361E0,fd:11  w-h:336,io:00436260,fd:12
debug2: fd 7 setting O_NONBLOCK
debug2: fd 8 setting O_NONBLOCK
debug2: fd 9 setting O_NONBLOCK
debug2: fd 10 setting O_NONBLOCK
debug2: fd 11 setting O_NONBLOCK
debug2: fd 12 setting O_NONBLOCK
debug3: socket:0, socktype:1, io:004362E0, fd:13
debug1: Executing command: C:\\Program Files\\OpenSSH\\ssh-shellhost.exe -nopty
Y21kIC9jICJkaXIi
debug3: Register child 00000160 pid 1416, 0 zombies of 0
debug2: fd 5 setting TCP_NODELAY
debug3: close - io:00435FE0, type:2, fd:7, table_index:7
debug3: close - io:00436160, type:2, fd:10, table_index:10
debug3: close - io:00436260, type:2, fd:12, table_index:12
debug3: fd 9 is O_NONBLOCK
debug3: fd 8 is O_NONBLOCK
debug3: fd 11 is O_NONBLOCK
debug3: send packet: type 99
debug2: channel 0: read<=0 rfd 9 len 0
debug2: channel 0: read failed
debug3: zombie'ing child at index 0, 0 zombies of 1
debug3: zombie'ing child at index 0, 0 zombies of 1

**Comment by wim-h** [comment]
Downloaded and tested v0.0.16.0:
Starting sshd service using Services Control Panel: Same error as 0.0.17.

Starting sshd -ddd on command line: same behaviour as 0.0.16

**Comment by wim-h** [comment]
> We may have missed testing 32-bit drop on Win7

Both 0.0.17 and 0.0.16?
Do you know if 64 bit testing has been done?

**Comment by wim-h** [comment]
Unable to start sshd service from services control panel using 0.0.17.0 on Win7 64 bit.
Same behaviour as on Win7 32bit.

Running sshd -ddd from Administrative command prompt also behaves as Win7 32 bit.

**Comment by bingbing8** [comment]
@wim-h this is a known issue on win7. please refer to #770

**Comment by bagajjal** [comment]
Looks like ssh client is closing the connection.. can you please share the ssh client logs as well (ssh.exe -vvv user@ip)

**Comment by bagajjal** [comment]
reopen this if required with requested information.

**Comment by pavan89** [comment]
I have also facing from this issue : sshd service not enable to start service, Gives below error.
Please suggest.
C:\>ssh localhost
**ssh: connect to host localhost port 22: Connection refused**
