### ISSUE TITLE
Does OpenSSH Automatically Obey Disabled Ciphers in the SCHANNEL Registry Key?

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#797]
Pardon my ignorance of the implementation of OpenSSH on Windows :)

At my company we disable any SSL cipher or key exchange algorithm advised by CIS.

If we are configuring the SCHANNEL registry keys as described in the below articles, are we automatically covered for disabling openssh usage of the same ciphers and algorithms?

These are not necessarily exhaustive:
https://support.microsoft.com/en-us/help/245030/how-to-restrict-the-use-of-certain-cryptographic-algorithms-and-protoc
https://technet.microsoft.com/en-us/library/security/ms15-055.aspx

**Comment by bagajjal** [comment]
Thanks for bringing this up.
As of now we don't do this, I think it is good to have this.

**Comment by manojampalam** [comment]
I don't see a compelling reason for OpenSSH to respect schannel config - it will end up resulting in unnecessary confusion, given that there is a well known and documented way to add restrictions using sshd_config.

**Comment by DarwinJS** [comment]
Copying @SteveL-MSFT and @joeyaiello 

To me the reasons are both compelling and significant:
- This location is well documented so it is easier to learn that it should be addressed.
- This location addressed by many existing security standards and tools.
- This location is directly configurable by group policy (local and AD configured)
- This location can be pre-populated before sshd or ssh are installed on a machine.
- This location could be made to disable ciphers for both client and server. (rather than possibly having to do both server config files and config files for *each* existing user and *new* user)
- This location is likely perceived as "one stop shopping" on disabling these ciphers on Windows.

With the importance of security, I feel these benefits outweigh the generally good design principle of having one place to configure things.  It would be easy enough to show in logs that these ciphers are disabled by this registry key.  Could also be surface in error messages ("The client attempted to negotiate the cipher Triple DES 168 which is disabled on this system in HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders")

I think doing this would help people "fall into the pit of success" rather than provide another opportunity to learn that they are unprotected and then have to write regex's over config files and run on that on all their machines - and run it repeatedly to catch new installs of ssh or new user profiles (while being unprotected until the maintenance process runs again).

P.S. While I both love open source and have a distain for the USER half of the registry - having a standardized configuration store has created some significant advantages for Windows as this demonstrates.

In fact, if openssh supported a redirection of it's config file to the registry (that was made very clear in all logs and startup messages) all of the above benefits would be available to configuring all aspects of it - including local gpo enforcement.

**Comment by rgl** [comment]
OpenSSH does not uses the SChannel library, it uses LibreSSL. Having it poking at the schannel settings would be pretty unexpected.
