### ISSUE TITLE
SSH sessions continue to be alive after deamon is stopped

### ISSUE THREAD

**Issue by manojampalam** [PowerShell/Win32-OpenSSH#8]
- sshd.exe -r
- Start a remote session
- Ctrl+C deamon
- Remote session is still active (as the forked child sshd.exe is not terminated)

**Comment by KrzysztofKaspruk** [comment]
Maybe it should be that way?

On Linuxes established incoming ssh sessions were never ended with stopping ssh daemon.

**Comment by ariscop** [comment]
This is intended, at least on unix, so the daemon can be restarted without killing active sessions

**Comment by nachfuellbar** [comment]
I think forked children should continue to run
i.e. if you change sshd configuration and you want to restart the daemon to apply settings

**Comment by ariscop** [comment]
Could do something like a service stop kills active sessions, but restart does not? i'm not familiar enough with windows services to know if thats possible

**Comment by nachfuellbar** [comment]
Maybe this is possible

Just want to know:
Is stopping connections on stopping of server needed (or really wanted)?
On linux i kill all ssh processes if i need to (doesn't happen too often)
Mostly i kill specific sessions; till now i've never needed all open connections to be closed on sshd restart or stop

**Comment by manojampalam** [comment]
Differentiating between stop service and restart service is not possible. I'll close this given similar functionality in Linux.
