### ISSUE TITLE
esxtop doesn't work like top

### ISSUE THREAD

**Issue by nachfuellbar** [PowerShell/Win32-OpenSSH#80]
I'm trying to use esxtop on esxi 5.5.0u1 and update 3
on both versions esxtop hangs up after short time
while esxtop is "working", the output is an ongoing csv like stream
this happens on cmd and powershell

`"(PDH-CSV 4.0) (UTC)(0)","\\Test-ESXi\Memory\Memory Overcommit (1 Minute Avg)","\\Test-ESXi\Memory\Memory Overcommit (5 Minute Avg)",`

**Comment by manojampalam** [comment]
According to http://www.punchingclouds.com/2013/01/30/esxtop-data-display-issues-with-osx-terminal-application/, it looks like we need Xterm support in ssh.exe (correct me if I'm wrong). If so, tagging this as a feature request.

**Comment by maertendMSFT** [comment]
@nachfuellbar, we believe this has been fixed in the latest version.  Does it repro now?
