### ISSUE TITLE
Configure PowerShell as default shell

### ISSUE THREAD

**Issue by devonfury** [PowerShell/Win32-OpenSSH#800]
Please answer the following

**"OpenSSH for Windows" version**
0.0.16.0
 
**Server OperatingSystem**
 Windows Server 2012 R2 Standard

**What is failing**
Unable to change the default shell from cmd to PowerShell

**Comment by bagajjal** [comment]
Try adding this in sshd_config...

Match User *
       ForceCommand C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

Please change the path of the powershell based on your system configuration.

**Comment by devonfury** [comment]
That worked.

Thanks

**Comment by hsson** [comment]
Unfortunately this solutions breaks so many things -- I was hoping there would be a more reliable and stable one. First of all, it breaks use cases where you just want to execute a single command, such as `ssh Administrator@<ip address> "echo hello"`. If using the ForceCommand solution this will completely ignore the original ssh command and just start powershell.

Another thing that completely breaks because of this is sFTP, which is kind of important.

**Comment by hamedsbt** [comment]
after set force command to:  C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe or powershell.exe
I got error:
Cloning into 'testgit2'...
fatal: protocol error: bad line length character: Wind

sshd log (powershell.exe):
7052 23:47:13:550 Starting session: forced-command (config) 'powershell.exe' for hamedsbt from 127.0.0.1 port 6939 id 0
7052 23:47:13:550 debug2: fd 8 setting O_NONBLOCK
7052 23:47:13:550 debug2: fd 9 setting O_NONBLOCK
7052 23:47:13:550 debug2: fd 10 setting O_NONBLOCK
7052 23:47:13:550 debug2: fd 11 setting O_NONBLOCK
7052 23:47:13:550 debug2: fd 12 setting O_NONBLOCK
7052 23:47:13:550 debug2: fd 13 setting O_NONBLOCK
7052 23:47:13:602 debug1: Executing command: D:\\sft\\OpenSSH-Win64\\ssh-shellhost.exe -nopty cG93ZXJzaGVsbC5leGU=
7052 23:47:13:627 debug2: fd 3 setting TCP_NODELAY
7052 23:47:13:627 debug3: fd 10 is O_NONBLOCK
7052 23:47:13:627 debug3: fd 9 is O_NONBLOCK
7052 23:47:13:627 debug3: fd 12 is O_NONBLOCK
7052 23:47:13:627 debug3: send packet: type 99
7052 23:47:14:024 debug3: receive packet: type 96
7052 23:47:14:024 debug2: channel 0: rcvd eof
7052 23:47:14:024 debug2: channel 0: output open -> drain
7052 23:47:14:024 debug2: channel 0: obuf empty

It seem the clone command does not pass correctly (b64: cG93ZXJzaGVsbC5leGU=) mean powershell.exe only!

**Comment by bagajjal** [comment]
Follow step 13 in this link to configure default shell
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by hamedsbt** [comment]
thank you for reply, but did not work:
$ git clone hamedsbt@127.0.0.1:"D:/TMP/git_projects/test_remote" test
Cloning into 'test'...
fatal: protocol error: bad line length character: Wind
sshd log:
8256 20:23:04:262 Starting session: forced-command (config) 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe' for hamedsbt from 127.0.0.1 port 8202 id 0
8256 20:23:04:262 debug2: fd 8 setting O_NONBLOCK
8256 20:23:04:262 debug2: fd 9 setting O_NONBLOCK
8256 20:23:04:262 debug2: fd 10 setting O_NONBLOCK
8256 20:23:04:262 debug2: fd 11 setting O_NONBLOCK
8256 20:23:04:262 debug2: fd 12 setting O_NONBLOCK
8256 20:23:04:262 debug2: fd 13 setting O_NONBLOCK
8256 20:23:04:310 debug1: Executing command: D:\\sft\\OpenSSH-Win64\\ssh-shellhost.exe -nopty QzpcV2luZG93c1xTeXN0ZW0zMlxXaW5kb3dzUG93ZXJTaGVsbFx2MS4wXHBvd2Vyc2hlbGwuZXhl
8256 20:23:04:336 debug2: fd 3 setting TCP_NODELAY
8256 20:23:04:336 debug3: fd 10 is O_NONBLOCK
8256 20:23:04:336 debug3: fd 9 is O_NONBLOCK
8256 20:23:04:336 debug3: fd 12 is O_NONBLOCK
8256 20:23:04:336 debug3: send packet: type 99
8256 20:23:04:552 debug3: receive packet: type 96
8256 20:23:04:552 debug2: channel 0: rcvd eof
8256 20:23:04:552 debug2: channel 0: output open -> drain
8256 20:23:04:552 debug2: channel 0: obuf empty
8256 20:23:04:552 debug2: channel 0: close_write
8256 20:23:04:552 debug2: channel 0: output drain -> closed
8256 20:23:04:901 debug3: receive packet: type 98
8256 20:23:04:901 debug1: server_input_channel_req: channel 0 request eow@openssh.com reply 0
8256 20:23:04:901 debug2: channel 0: rcvd eow
8256 20:23:04:901 debug2: channel 0: close_read
8256 20:23:04:901 debug2: channel 0: input open -> closed

**Comment by DarwinJS** [comment]
@bagajjal - I just noticed that the instructions say ""Full path (case sensitive) of the shell executable." - but then in the screenshot it shows the Windows folder with a lowercase like this "c:\windows\..."  If you do a dir "c:\" - the windows folder shows as "c:\Windows".

Is it actually case sensitive in that path?

Interestingly, (never noticed this before) if you do "dir c:\windows\system32" the windows folder displays in the output as "c:\windows".

**Comment by hamedsbt** [comment]
@DarwinJS - basically the windows is not case sensitive nor on dir-name, file-name, path address and so on...
