### ISSUE TITLE
Auth: "failed none for"

### ISSUE THREAD

**Issue by hdatma** [PowerShell/Win32-OpenSSH#801]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 0.0.17.0
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
MacOS 10.12.5 with custom OpenSSH 7.5p1

**What is failing**
All is well, except for the following. The server log on Windows says ...

"7524 19:10:32:592 Connection from 192.168.1.8 port 61249 on 192.168.1.23 port 22
7524 19:10:32:715 Failed none for me from 192.168.1.8 port 61249 ssh2
...............................^^^^^^^^^^^^^^^
7524 19:10:32:720 Postponed publickey for me from 192.168.1.8 port 61249 ssh2
7524 19:10:32:762 Accepted publickey for me from 192.168.1.8 port 61249 ssh2: ED25519 SHA256:bDoTLqO8gR9i4Y/Hn6oQPFL7hEHVurG0bG/NPHT/6KE
7524 19:10:32:771 Starting session: shell on console for me from 192.168.1.8 port 61249 id 0
7524 19:10:34:975 Close session: user me from 192.168.1.8 port 61249 id 0
7524 19:11:05:008 Received disconnect from 192.168.1.8 port 61249:11: disconnected by user
7524 19:11:05:008 Disconnected from user me 192.168.1.8 port 61249"

where sshd_config includes the following

"PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no 
KbdInteractiveAuthentication no
PermitRootLogin no 
RhostsRSAAuthentication no
HostbasedAuthentication no
IgnoreRhosts yes
UsePAM no
AllowAgentForwarding no 
AllowTcpForwarding no
MaxAuthTries 3"

**Expected output**
I do not expect the above "failed none for", and want it to stop. 

**Actual output**
Huh?

**Comment by manojampalam** [comment]
Looks like the trace message is being logged from core OpenSSH code. IF so, you would see a similar event in auth logs on Unix. Can you please confirm this and open up a bug in OpenSSH main project if this indeed is the case?

Otherwise, please reopen.
