### ISSUE TITLE
emacs terminal problem

### ISSUE THREAD

**Issue by icf3** [PowerShell/Win32-OpenSSH#802]
This is a terminal issue and Windows SSH client to Linux/Unix/macOS (*nix) SSH server CASE.
vi is work. but emacs is not work.

OpenSSH for Windows version : 0.0.17.0
Server Linux / Debian / armbian.
Client Windows10

Expected output
![ssh3](https://user-images.githubusercontent.com/30029117/27998549-29903468-654c-11e7-85d7-86005e343929.png)

Actual output
![ssh1](https://user-images.githubusercontent.com/30029117/27998553-3bfc701c-654c-11e7-862f-14747ffd6874.png)

![ssh2](https://user-images.githubusercontent.com/30029117/27998554-3fa2dab2-654c-11e7-8325-7eebbca2beeb.png)

I tried to fix it.
Win32-OpenSSH-0.0.17.0\Win32-OpenSSH-0.0.17.0\contrib\win32\win32compat
console.c

`dwAttributes |= (DWORD)ENABLE_VIRTUAL_TERMINAL_PROCESSING | 0x0008;`

0x0008 is #define (DISABLE_NEWLINE_AUTO_RETURN)

I don't know if this fix is right.
My fix may work after Anniversary Update for Windows 10.

**Comment by bagajjal** [comment]
Fix is available in july mid  release (v0.0.18.0)

**Comment by icf3** [comment]
0.0.18.0 does not work like 0.0.17.0.
Would you see it once again?

My TERM is "xterm" or "vt100"

export TERM=xterm
or
export TERM=vt100

**Comment by bagajjal** [comment]
I can think of two code changes that might have an interaction with it..
1) ssh-shellhost now supports dealing the control sequences (#799, code changes in ProcessCtrlSequence() in ssh-shellhost.exe).

2) Addition of DISABLE_NEWLINE_AUTO_RETURN.

Can you try to remove DISABLE_NEWLINE_AUTO_RETURN and see if it works as expected?
If not, please provide what is not working and reproduction steps..

**Comment by bagajjal** [comment]
Reopening to track the regression caused.

**Comment by icf3** [comment]
Sorry, I can't remove DISABLE_NEWLINE_AUTO_RETURN.
If it is possible, you try it.
If not, I hope Adding temporary special option of DISABLE_NEWLINE_AUTO_RETURN.
So, I'm happy. But,you do not need to do it.

ex)   ssh.exe --disable-newline-auto-return icf3@192.168.1.1

**Comment by bagajjal** [comment]
I have made the code changes to remove the DISABLE_NEWLINE_AUTO_RETURN. This zip contains ssh.exe build in debug, x64 binary.
[Emacs-TerminalIssue.zip](https://github.com/PowerShell/Win32-OpenSSH/files/1164161/Emacs-TerminalIssue.zip). 

Please try this and if it doesn't help, please provide the reproduction steps and what is not working so that I can reproduce and debug at my end.

**Comment by icf3** [comment]
OK : Emacs-TerminalIssue.zip ,  0.0.18.0 binary
NG : 0.0.17.0 , 0.0.18.0 source

In 0.0.18.0 binary and 0.0.18.0 source, why are results different?
Can I test Emacs-TerminalIssue souce code?

The reproduction is easy.
You just type "Expected output image".

#include <stdio.h>

int main() {
    printf("Hello World\n");
    return 0;
}

**Comment by fpqc** [comment]
@bagajjal You should encourage testing from the latest insider builds and also maybe keep in touch with @zadjii-msft , who has been implementing a lot of the control sequences.  The console processing of control sequences is not yet perfect, and you're probably better off making sure if it's your bug or their bug before fixing or introducing a workaround.  If I remember correctly, this disable newline autoreturn thing was mentioned on the console/WSL github.

Edit: Here's the issue I was remembering:

https://github.com/Microsoft/BashOnWindows/issues/1273

**Comment by bagajjal** [comment]
@icf3 - 
1) what do you mean by 0.0.18.0 binary and 0.0.18.0 source?
2) Can you please confirm whether Emacs-TerminalIssue.zip fixed the regression?
3) I tried both the v0.0.17.0 and v0.0.18.0 but couldn't find big difference. only the difference is the indentation is happening little late. Can you please provide your observations?

As mentioned, the Emacs-TerminalIssue.zip doesn't set the "DISABLE_NEWLINE_AUTO_RETURN" on the stdout handler.

If the windows SSH client is using win10+ then the control sequences received from the SSH server will be directly given to the conhost.exe process. Not sure if the conhost.exe is behaving incorrectly when this flag is set.

**Comment by icf3** [comment]
@bagajjal  -

> 1. what do you mean by 0.0.18.0 binary and 0.0.18.0 source?

They are file that is enable to download in this site.

> 2. Can you please confirm whether Emacs-TerminalIssue.zip fixed the regression?

Yes. But it may be only fix this emacs problem. And it is only binary.

> 3. I tried - - - Can you please provide your observations?

v0.0.18.0 is same as v0.0.17.0 at source level. That's while still having a emacs problem.

Even if Emacs-TerminalIssue.zip doesn't set the "DISABLE_NEWLINE_AUTO_RETURN",
this may be version of only fix this emacs problem.
It could not help me. Because I wish for source cord.

> If the windows SSH client is using win10+ then the control sequences received from the SSH server will be directly given to the conhost.exe process. Not sure if the conhost.exe is behaving incorrectly when this flag is set.

It is easy.
If you add temporary special option for this emacs problem, I'm happy.
ex) ssh.exe --disable-newline-auto-return icf3@192.168.1.1

**Comment by icf3** [comment]
This bug is fixed by Ver 0.0.19.0 (source code).
I confirmed that my patch is included.
Thanks!
