### ISSUE TITLE
KexAlgorithms curve25519-sha256@libssh.org on Windows

### ISSUE THREAD

**Issue by hdatma** [PowerShell/Win32-OpenSSH#803]
**"OpenSSH for Windows" version**
0.0.17.0

**Server OperatingSystem**
Windows 10 Pro
Windows Server 2012 Foundation

**Client OperatingSystem**
MacOS 10.12.5 with custom OpenSSH 7.5p1

**What is failing**

Two SSH servers, with exactly the same OpenSSH software version and sshd_conf. 

On Windows Server: no matching key exchange method found
On Windows 10: all is well. 

This is the log on Windows Server:

"3540 15:41:03:562 Connection from <remote-ip> port 55883 on 192.168.1.15 port 22
3540 15:41:04:000 Unable to negotiate with <remote-ip> port 55883: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1"

**Comment by bagajjal** [comment]
Kex negotiation will be initiated by both client and server.. In client it picks either from ssh_config or through command line arguments.. In sshd it picks from sshd_config or command line arguments if you start as non-service process or default kex algorithms.. Could you please check this configuration in both the systems and compare both the ssh logs (ssh.exe -vvv user@ip) and sshd log with debug3 enabled.. If you still have questions then please share both ssh and sshd logs and configuration..

**Comment by manojampalam** [comment]
Reopen once you have the logs ready.

**Comment by hdatma** [comment]
1. I see errors from sshd at start-up. 

2. I usually write own keys using "ssh-keygen -t ed25519 -o -a 100". 
The command works on Windows 10 Pro, but fails on Windows Server 2012 Foundation.  


`--->  starting sshd...

6472 20:21:52:909 debug1: sshd version OpenSSH_7.5, LibreSSL 2.5.3
6472 20:21:52:909 debug3: socket:0, socktype:1, io:000000F3159D0860, fd:3 
6472 20:21:52:909 debug3: close - io:000000F3159D0860, type:2, fd:3, table_index:3
6472 20:21:52:909 debug3: open - handle:00000000000000F4, io:000000F3159D0BE0, fd:3
6472 20:21:52:909 debug3: ReadFileEx() ERROR:38, io:000000F3159D0BE0
6472 20:21:52:909 debug3: read - no more data, io:000000F3159D0BE0
6472 20:21:52:909 debug3: ReadFileEx() ERROR:38, io:000000F3159D0BE0
6472 20:21:52:909 debug3: read - no more data, io:000000F3159D0BE0
6472 20:21:52:909 debug3: close - io:000000F3159D0BE0, type:2, fd:3, table_index:3
6472 20:21:52:909 debug1: private host key #0: ssh-rsa SHA256:bCCuyJvd6le8bfIoZh9xudAWQ7ga36nmJLjtY6zXUqk
6472 20:21:52:909 debug3: open - handle:00000000000000F4, io:000000F3159D0BE0, fd:3
6472 20:21:52:909 debug3: ReadFileEx() ERROR:38, io:000000F3159D0BE0
6472 20:21:52:909 debug3: read - no more data, io:000000F3159D0BE0
6472 20:21:52:909 debug3: ReadFileEx() ERROR:38, io:000000F3159D0BE0
6472 20:21:52:909 debug3: read - no more data, io:000000F3159D0BE0
6472 20:21:52:909 debug3: close - io:000000F3159D0BE0, type:2, fd:3, table_index:3
6472 20:21:52:909 debug1: private host key #1: ssh-dss SHA256:NYTII3zVccEcEGaG0JEtGbqko/z57PzHB1MuEbXdK4U
6472 20:21:52:909 debug3: open - handle:00000000000000F4, io:000000F3159D0BE0, fd:3
6472 20:21:52:909 debug3: ReadFileEx() ERROR:38, io:000000F3159D0BE0
6472 20:21:52:909 debug3: read - no more data, io:000000F3159D0BE0
6472 20:21:52:909 debug3: ReadFileEx() ERROR:38, io:000000F3159D0BE0
6472 20:21:52:909 debug3: read - no more data, io:000000F3159D0BE0
6472 20:21:52:909 debug3: close - io:000000F3159D0BE0, type:2, fd:3, table_index:3
6472 20:21:52:909 debug1: private host key #2: ecdsa-sha2-nistp256 SHA256:Ak0Do+Pu82XFj0kHf+9IcX3wLIbGeeybSYwx7xAEtFI
6472 20:21:52:909 debug3: open - handle:00000000000000F4, io:000000F3159D0BE0, fd:3
6472 20:21:52:909 debug3: ReadFileEx() ERROR:38, io:000000F3159D0BE0
6472 20:21:52:909 debug3: read - no more data, io:000000F3159D0BE0
6472 20:21:52:909 debug3: ReadFileEx() ERROR:38, io:000000F3159D0BE0
6472 20:21:52:909 debug3: read - no more data, io:000000F3159D0BE0
6472 20:21:52:909 debug3: close - io:000000F3159D0BE0, type:2, fd:3, table_index:3
6472 20:21:52:909 debug1: private host key #3: ssh-ed25519 SHA256:BhQkyRplazLCfbGeh0EoKOhSYLL+AcL6GNm53lfkgDA
6472 20:21:52:909 debug3: socket:228, socktype:1, io:000000F3159D0BE0, fd:3 
6472 20:21:52:909 debug2: fd 3 setting O_NONBLOCK
6472 20:21:52:909 debug3: sock_set_v6only: set socket 3 IPV6_V6ONLY
6472 20:21:52:909 debug1: Bind to port 22 on ::.
6472 20:21:52:909 Server listening on :: port 22.
6472 20:21:52:909 debug3: socket:300, socktype:1, io:000000F3159D0E20, fd:4 
6472 20:21:52:909 debug2: fd 4 setting O_NONBLOCK
6472 20:21:52:909 debug1: Bind to port 22 on 0.0.0.0.
6472 20:21:52:909 Server listening on 0.0.0.0 port 22.
