### ISSUE TITLE
Invoking remote commands into WSL (bash) fails

### ISSUE THREAD

**Issue by darkverbito** [PowerShell/Win32-OpenSSH#808]
Open SSH 0.0.17.0
Windows 10 Enterprise N
Any SSH client (Mac OS SSH, PLINK) 

I'm having success using SSH as follows:

bobby {~/code/ssh}  ➩ ssh -i sshkey bobby@40.116.167.230
Microsoft Windows [Version 10.0.14393]                                                                                  
(c) 2016 Microsoft Corporation. All rights reserved.                                                                    

bobby@WINDOWS-TST C:\Users\bobby>
bobby@WINDOWS-TST C:\Users>ls -l                                                                                          
total 37                                                                                                                
lrwxrwxrwx 1 bobby 197121  14 Jul 16  2016 'All Users' -> /c/ProgramData                                              
drwxr-xr-x 1 bobby 197121   0 Aug 22  2016  Default                                                                   
lrwxrwxrwx 1 bobby 197121  16 Jul 16  2016 'Default User' -> /c/Users/Default                                         
drwxr-xr-x 1 bobby 197121   0 Aug 22  2016  Public                                                                    
drwxr-xr-x 1 bobby 197121   0 Jun 12 20:49  SSHD                                                                      
drwxr-xr-x 1 bobby 197121   0 Aug 22  2016  defaultuser0                                                              
-rw-r--r-- 1 bobby 197121 174 Jul 16  2016  desktop.ini                                                               
drwxr-xr-x 1 bobby 197121   0 Jul 12 18:14  bobby

And I can execute remote commands:
                                                     
bobby {~/code/ssh}  ➩ ssh -i sshkey bobby@40.116.167.230 "cd .. & ls -l"
total 37
lrwxrwxrwx 1 bobby 197121  14 Jul 16  2016 All Users -> /c/ProgramData
drwxr-xr-x 1 bobby 197121   0 Aug 22  2016 Default
lrwxrwxrwx 1 bobby 197121  16 Jul 16  2016 Default User -> /c/Users/Default
drwxr-xr-x 1 bobby 197121   0 Aug 22  2016 Public
drwxr-xr-x 1 bobby 197121   0 Jun 12 20:49 SSHD
drwxr-xr-x 1 bobby 197121   0 Aug 22  2016 defaultuser0
-rw-r--r-- 1 bobby 197121 174 Jul 16  2016 desktop.ini
drwxr-xr-x 1 bobby 197121   0 Jul 12 18:14 bobby

However when I try to execute things in bash I get an error:

bobby {~/code/ssh}  ➩ ssh -i sshkey bobby@40.116.167.230 "bash -c 'eval echo hi mom'"
Error: 0x80070057

But that does work if I execute it interactively:

bobby {~/code/ssh}  ➩ ssh -i sshkey bobby@40.116.167.230
Microsoft Windows [Version 10.0.14393]                                                                                  
(c) 2016 Microsoft Corporation. All rights reserved.                                                                    

bobby@WINDOWS-TST C:\Users\bobby>bash -c 'eval echo hi mom'                                                             
hi mom  

I had to set Local Launch and Activation permissions for my user by taking control of the registry keys:

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\AppID\{F72671A9-012C-4725-9D2F-2A4D32D65169}
HKEY_CLASSES_ROOT\CLSID\{4f476546-b412-4579-b64c-123df331e3d6}

Then adjusting the permissions in DCOM component services for AppId F72671A9-012C-4725-9D2F-2A4D32D65169. Before doing that I was getting an error 0x80070005 any time I would try to invoke bash over OpenSSH-Win64

**Comment by bagajjal** [comment]
duplicate of https://github.com/PowerShell/Win32-OpenSSH/issues/289

bash.exe is not allowed for the network logons.. Its the limitation from the bash.exe..

**Comment by darkverbito** [comment]
That makes no sense. Look it is working interactively.

**Comment by darkverbito** [comment]
Also note that the error for 289 is resolved if you adjust the DCOM as I indicated.

**Comment by darkverbito** [comment]
Please re-open this. It should not be closed.

@manojampalam @quamrulmina @dkulwin @arif-pragmasys

**Comment by bagajjal** [comment]
Please talk to the WSL team. 
As per our earlier communication with the WSL team, changing the registry can lead to a potential security issue. WSL team doesn't recommend this approach. WSL team is still making decision whether to allow the network logons or not.

We will cross-check if it is related to win32-openssh so reopening the issue.

**Comment by bagajjal** [comment]
@darkverbito - Can you please provide what fields has to be changed in the registry so that we can reproduce this issue at our end.

Here is the current snapshot of my registry,
![image](https://user-images.githubusercontent.com/23668037/28138506-de8c16c4-6705-11e7-9fda-f10aa1bacfca.png)
![image](https://user-images.githubusercontent.com/23668037/28138598-40380554-6706-11e7-9c8b-021ba2ddf520.png)

**Comment by darkverbito** [comment]
You have to take control of those keys: right click, permissions, advanced, owner (change). Then add that owner with full control. Do this for both keys.

**Comment by bagajjal** [comment]
@darkverbito - I have added the permissions as mentioned but it still gives me "Error: 0x80070057". You also mentioned something about "set Local Launch", where do we need to set this?

**Comment by darkverbito** [comment]
That is the underlying problem I was documenting.

**Comment by bagajjal** [comment]
@darkverbito -For me the interactive ssh fails to launch the bash, it gives "Error: 0x80070057".

I have added the permissions as mentioned but it didn't work.

**Comment by manojampalam** [comment]
Issue is in WSL and being tracked under https://github.com/Microsoft/BashOnWindows/issues/2322.
