### ISSUE TITLE
File not found error when running "key-based authentication" script

### ISSUE THREAD

**Issue by eneunaber** [PowerShell/Win32-OpenSSH#81]
Following the instructions for installation, when executing step 6 the following error occurs.

**Error:**
```
C:\Program Files\OpenSSH-Win32>copy C:\Program Files\OpenSSH-Win32\x64\ssh-lsa.dll C:\Windows\system32\
The system cannot find the file specified.
```

Inside **setup-ssh-lsa.cmd** if you wrap the copy statement in quotes, it appears to fix the problem.

**Original:**
```copy %lsadll% %windir%\system32\```

**Altered:**
```copy "%lsadll%" "%windir%\system32\"```

**Fixed:**
```
C:\Program Files\OpenSSH-Win32>copy "C:\Program Files\OpenSSH-Win32\x64\ssh-lsa.dll" "C:\Windows\system32\"
        1 file(s) copied.
```

**Comment by RamblingCookieMonster** [comment]
Same here, you might consider submitting a pull request : )

**Comment by StefanScherer** [comment]
Tried to create a pull request, but I can't find the script `setup-ssh-lsa.cmd` in this repo.
Any hints?

**Comment by manojampalam** [comment]
script is part of build release and is not present in repo. Will not this while releasing next drop.
