### ISSUE TITLE
Is there an order using multiple hostkeys in sshd_config?

### ISSUE THREAD

**Issue by comsyspro** [PowerShell/Win32-OpenSSH#811]
Configuring sshd_config with multiple entries for hostkeys the ed25519 hostkey is preffered when connecting with a ssh client.

```
HostKey ssh_host_rsa_key
HostKey ssh_host_dsa_key
HostKey ssh_host_ecdsa_key
HostKey ssh_host_ed25519_key
```

So if I want to use the ecdsa hostkey with the ssh client there is no chance to connect to the ssh server. Consequently I had to remove the entry `HostKey ssh_host_ed25519_key` so the server accept now the ecdsa fingerprint.

```
HostKey ssh_host_rsa_key
HostKey ssh_host_dsa_key
HostKey ssh_host_ecdsa_key
```

So my question is if there is a possibility to define the order or the priority of the used server hostkeys so that the client can choose different ones and can successfully connect to the ssh server.

Thanks for your reply.

**Comment by diogocp** [comment]
Use the `HostKeyAlgorithms` option on the client.
https://superuser.com/a/1142569/260305

**Comment by manojampalam** [comment]
If there is one, it would be detailed in https://linux.die.net/man/5/sshd_config.

**Comment by maertendMSFT** [comment]
This is not Windows specific
