### ISSUE TITLE
Issues with public key authentication

### ISSUE THREAD

**Issue by WesR** [PowerShell/Win32-OpenSSH#815]
**"OpenSSH for Windows" version**
v 0.0.17.0
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Ubuntu 16.04

**What is failing**
Key based authentication

**Expected output**
User connects to windows server

**Actual output**
`wes@mehPC:/$ ssh dustin@192.168.1.19
Permission denied (publickey,keyboard-interactive).`

I am having an issue using key based authentication. I know that there is not an issue with my key generation, as loading my public key into the cygwin's version of openSSH allows for key auth. My only thought is that there is something with the way that I have everything configured. If there is anything else I can provide I am more then happy. Thank you for your help.

[sshd.log.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1157460/sshd.log.txt)
[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1157461/sshd_config.txt)

#authorized_keys file:
`ssh-rsa AAAAB3N.......cI8+pZ7ErmEdP wes@mehPC`
Note: I have given SSHD read perms

**Comment by bagajjal** [comment]
Please provide sshd.log with DEBUG3 enabled..  
LogLevel DEBUG3 (In sshd_config)

Also the ssh client logs (ssh.exe user@ip -vvv)

**Comment by WesR** [comment]
[clientRunning.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1157521/clientRunning.txt)
[sshd.log.3.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1157522/sshd.log.3.txt)

I noticed 
`3324 15:55:54:398 debug1: trying public key file C:/Users/dustin/.ssh/authorized_keys
3324 15:55:54:413 debug3: Bad permission. N can only read access to C:/Users/dustin/.ssh/authorized_keys
3324 15:55:54:413 Authentication refused.`
So I ran it again giving it full permission to the location and got this:

[sshd.log.32.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1157528/sshd.log.32.txt)
[clientRunning2.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1157529/clientRunning2.txt)

But was still getting the BadPermission flag, so I moved it to C:/ and gave every user full access to it and got:
(Config now has `AuthorizedKeysFile	C:/authorized_keys`)

[clientRunning3.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1157536/clientRunning3.txt)
[sshd.log.33.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1157537/sshd.log.33.txt)

**Comment by bagajjal** [comment]
You should have restricted access to authorized_keys file. System(FullControl), SSHD(Read only), Administrators group (can be anything).

Your security settings should look like this
![image](https://user-images.githubusercontent.com/23668037/28344039-f117e942-6bd5-11e7-9c25-2e6b99766a53.png)

From sshd.log,
2156 16:05:30:334 debug1: trying public key file C:/authorized_keys
2156 16:05:30:334 debug3: LookupAccountSidLocalW() failed with error: 122. 
2156 16:05:30:334 debug3: Bad permissions. Try removing permissions for user: S-1-5-11 on file C:/authorized_keys.
2156 16:05:30:334 Authentication refused.

**Comment by WesR** [comment]
I did it again in user [dustin]'s account and it failed (matching your permissions fully). I moved it over to C:\Users\SSHD\\.ssh and removed all other users except the three you have listed and it worked.

Thank you so much for the help, I really appreciate it.

**Comment by WesR** [comment]
For anyone in the future, my config has these things changed:
`PubkeyAuthentication yes`
`AuthorizedKeysFile	C:/Users/SSHD/.ssh/authorized_keys`
`PasswordAuthentication no`

**Comment by bagajjal** [comment]
fyi, the location really doesn't matter as long as you have the right permissions and sshd_config referring to the right location.

**Comment by milanbojovic** [comment]
Hello, after few days of struggle I have solved my problem with help of your comments.

**Steps:** I am using Administrator user for remote machine in question, and I have commented sshd_config line #AuthorizedKeysFile...  (this line is used for setting location of authorized_keys file)  --> and from logs I have noticed that sshd service is searching for authorized_keys in C:\Users\Administrator\.ssh directory, then I have moved my authorized_keys file from C:\Program Files\OpenSSH\.ssh\ to mentioned location and I have applied same restrictions for authorized_keys file like @bagajjal mentioned in his comment above.
I have also tried to configure this location C:\Users\SSHD\.ssh but probably I did something wrong there.

**Comment by asterikx** [comment]
@bagajjal's permission settings did the trick!
I'd like to emphasize that the `authorized_keys` file's owner has to be `Administrators`. Setting it to `Service NT\sshd` (as for the`ssh_host_ed25519_key` private key file) the will result in a `Bad owner` error.

**Comment by gtestault** [comment]
The only fix that worked for me was to remove ```Authenticated Users``` group from the ```C:/Users/ProgramData/ssh``` directory. For some reason the group can access the directory by default but the ssh server won't accept public key authentication if it is there...

![image](https://user-images.githubusercontent.com/22593117/129913504-9726cecc-7553-4e78-adaa-11003946e28b.png)
![image](https://user-images.githubusercontent.com/22593117/129913549-db296843-fcca-4262-be78-3d6b5d724228.png)

With the S-1-5-11 group (Authenticated Users) it doesn't accept public key

**Comment by Cuberick-Orion** [comment]
> The only fix that worked for me was to remove `Authenticated Users` group from the `C:/Users/ProgramData/ssh` directory. For some reason the group can access the directory by default but the ssh server won't accept public key authentication if it is there...
> 
> ![image](https://user-images.githubusercontent.com/22593117/129913504-9726cecc-7553-4e78-adaa-11003946e28b.png) ![image](https://user-images.githubusercontent.com/22593117/129913549-db296843-fcca-4262-be78-3d6b5d724228.png)
> 
> With the S-1-5-11 group (Authenticated Users) it doesn't accept public key

Thanks for the solution, it works on my case (I reinstalled Windows and simply copied the old `.ssh` folder into the new OS, thus having an authentication problem).

**Comment by spevdev** [comment]
Last step:
You must run CMD or the Terminal as an admi if it says "Permission denied".
Right click on the icon and choose "Run as Administrator".

**Comment by rohitpreddyJ** [comment]
I'm facing the same issue. I've been debugging for hours but not sure what to do anymore. Please help.

```Bad permissions. Try removing permissions for user: \\Everyone (S-1-1-0) on file C:/Users/----/.ssh/id_rsa.pub.
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> Permissions for 'C:\\Users\\----\\.ssh\\id_rsa.pub' are too open.
> It is required that your private key files are NOT accessible by others.
> This private key will be ignored.
> Load key "C:\\Users\\----\\.ssh\\id_rsa.pub": bad permissions
> ubuntu@--------: Permission denied (publickey). 
```
Here are my permissions 

<img width="569" alt="Screenshot 2024-07-17 190105" src="https://github.com/user-attachments/assets/cda29738-9f7e-4d80-9bb7-f11f6bbb1d42">

**Comment by NoMoreFood** [comment]
Do `icacls %USERPROFILE%\.ssh\id_rsa.pub` and provide the results.

**Comment by rohitpreddyJ** [comment]
```
\Users\User_Profile\.ssh\id_rsa.pub BUILTIN\Administrators:(F)
                             NT AUTHORITY\SYSTEM:(F)
                             USERPROFILE:(M)
                             Everyone:(RX)
```

**Comment by NoMoreFood** [comment]
@rohitpreddyJ  Yeah so it looks like some of the files in there (like id_rsa.pub) are too open.  Go to the properties on them specifically and remove 'Everyone'.

**Comment by rohitpreddyJ** [comment]
> @rohitpreddyJ Yeah so it looks like some of the files in there (like id_rsa.pub) are too open. Go to the properties on them specifically and remove 'Everyone'.

Thank you! It worked out for me.
