### ISSUE TITLE
Symantec blocks the download, nukes all the .exe files.

### ISSUE THREAD

**Issue by Eric-ITaaS** [PowerShell/Win32-OpenSSH#819]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**

**What is failing**

**Expected output**

**Actual output**

**Comment by bagajjal** [comment]
Please provide detailed problem description.

**Comment by gravcat** [comment]
@gatornation11 if it's a Symantec false positive issue, you'll need to exclude your OpenSSH-WIn32/OpenSSH-Win64 directory and it's contents.

**Comment by bagajjal** [comment]
How is it OpenSSH issue?

**Comment by Eric-ITaaS** [comment]
It's related because people will give up on your software if it blows up every AV engine on the market.



________________________________

**Comment by gravcat** [comment]
Not really OpenSSH-Win64's problem to police Symantec's historically crappy false positive rate. Every software company I've ever worked with at one point or another has pain attached to the word "Symantec". Submit it to Symantec and they should help you resolve the false positive, at which point you'll help any other users that unfortunately also use Symantec.

**Comment by bagajjal** [comment]
@gatornation11 - didn't understand what you are expecting from the openssh project to do for this issue.  It is out of our scope. If you have different opinion then please describe so that we can think about it
