### ISSUE TITLE
Using an environment variable to change the SFTPROOT

### ISSUE THREAD

**Issue by gitfvb** [PowerShell/Win32-OpenSSH#82]
Hi, it would be very useful if the user could be jailed into a directory.
As a starter, which should be easily done in the code: Can you put in a if to grab a env variable like "FTPROOT" which could lead to a custom path? If this variable is not existent you could still use USERPROFILE.
I would contribute to this but I cannot get the compiler working everything through.

**Comment by shooshoomo** [comment]
I think ChrootDirectory is what you're looking for. Unfortunately I can't get it to work.

Shoo

**Comment by gitfvb** [comment]
Yes, that would be the equivalent I am looking for, but it does not work on my installation too.

**Comment by ZakThePotter** [comment]
I need it too

**Comment by maertendMSFT** [comment]
This should be configured in sshd_config
