### ISSUE TITLE
Ctrl+C sent from Linux to Windows does not work

### ISSUE THREAD

**Issue by GoodMirek** [PowerShell/Win32-OpenSSH#821]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**
- Read and complied.

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 ```
PS C:\Windows\system32> ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
Get-Command : The term 'sshd' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:13
+ ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (sshd:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

Get-Item : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:12
+ ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
+            ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Item], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetItemCommand
```
Version of OpenSSH as displayed by choco:
```
choco search -l openssh
Chocolatey v0.10.7
openssh 0.0.18.0
1 packages installed.
```

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
`Windows Server 2016 Datacenter`

**Client OperatingSystem**
Fedora 26, x86_64, up to date

**What is failing**
Ctrl+C does nothing while pressed via SSH session.

**Expected output**
Ctrl+C will abort run of current Powershell command while waiting for user input, like it does via RDP.

**Actual output**
Ctrl+C does nothing while pressed via SSH session.

**Comment by fpqc** [comment]
In this case, the server's powershell version and actual Windows version might matter beyond just the SKU. Large cross-SKU changes have been made to the console subsystem since the first version of Server 2016 that could potentially affect this.

**Comment by bagajjal** [comment]
Couldn't reproduce this.
Ctrl+C is being sent.. You can try initiating "ping 127.0.0.1" and then press Ctrl+C , this should stop ping.
I tried the below powershell script, Ctrl+C works fine from the ssh client (tried from Ubuntu).

$t=Get-Date -format "dd-MMM-yyyy HH:mm"
echo $t
Start-Sleep -s 60
$t=Get-Date -format "dd-MMM-yyyy HH:mm"
echo $t

**Comment by bagajjal** [comment]
@GoodMirek - Any update on this?

**Comment by GoodMirek** [comment]
@bagajjal I appreciate that you tried and cannot reproduce the issue. However, the issue persists on my side. What other info or help can I provide?

**Comment by bagajjal** [comment]
@GoodMirek - Have you tried ping or the sample powershell script that was mentioned? 
If it works then it is certain that the Ctrl+C is been issued from the ssh-shellhost.exe.
To debug further, we need to look into your powershell script and analyze which commands are not responding to the Ctrl+C.

If ping / sample powershell script doesn't  work then we have a problem in our ssh-shellhost.exe.

**Comment by GoodMirek** [comment]
@bagajjal Yes, I have tried to interrupt ping with Ctrl+C. I have also tried to interrupt others commands and also some powershell scripts, though not your example.
If I login from the same terminal to Linux machines, it works without problem.

**Comment by bagajjal** [comment]
@GoodMirek - When you are connected to windows ssh server, interrupting the ping with Ctrl+C works for you?

**Comment by GoodMirek** [comment]
@bagajjal Sorry for not being clear in my previous post. Interrupting of ping nor anything else with Ctrl+C never works when I am connected to the windows ssh server.

**Comment by bagajjal** [comment]
@GoodMirek - Need your help in analyzing the root cause. Please follow the below steps,

on your windows machine acting as ssh server,
1) Please copy your existing ssh-shellhost.exe as ssh-shellhost.exe.bkup
2) Use the ssh-shellhost.exe from this link and replace with your ssh-shellhost.exe
[shellhost-ctrl-c-issue.zip](https://github.com/PowerShell/Win32-OpenSSH/files/1195475/shellhost-ctrl-c-issue.zip)

On your ssh client machine,
1) set your TERM to xterm.
2) Now connect from your ssh client to ssh server.
3) After you login, press "ctrl+c" and enter
4) type "exit" to exit the session.
5) Now you will see some log messages on your ssh client.. please share the logs with me.
It looks like this,
![image](https://user-images.githubusercontent.com/23668037/28898326-38d522a2-779a-11e7-94c7-7e98d687b154.png)

on your windows machine acting as ssh server,
1) Revert back ssh-shellhost.exe.bkup to ssh-shellhost.exe to remove my private changes.

FYI, I am also attaching the working ctrl+c behavior, ssh from Ubuntu machine (acting as ssh client ) to windows 10 (acting as ssh server)
![image](https://user-images.githubusercontent.com/23668037/28898363-685dfda0-779a-11e7-990c-43d23b5c6ff2.png)

**Comment by GoodMirek** [comment]
@bagajjal I do not have the affected machine available any longer. I have tried hard to reproduce on other machines, no luck - it works. Thank you for your time and effort, I am sorry I cannot uncover this mystery.

**Comment by marcosnils** [comment]
@GoodMirek @bagajjal one thing that I've noticed is that even though CTRL+C works to interrupt commands (like the ping example you mentioned), if you press it while in the prompt, it doesn't cancel the current command  like it does in the real windows shell. Is there something that can be done for this?

**Comment by bagajjal** [comment]
@marcosnils - ctrl+c is issued from the ssh-shellhost but the console is not honoring.. It's a bug in the console code.. Out of our scope

**Comment by marcosnils** [comment]
@bagajjal that's what I supposed. Too bad that's console specific and that powershell / cmd doesn't react. Any ideas about it would be possible to overcome?
