### ISSUE TITLE
SSH session hangs when left idle for too long (~5 minutes) without any activity

### ISSUE THREAD

**Issue by gravcat** [PowerShell/Win32-OpenSSH#823]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**
I did not find anything super relevant in the wiki but feel free to correct me on this if I am wrong.

**"OpenSSH for Windows" version**
 `OpenSSH-Win64 0.0.14`
 
**Server OperatingSystem**
 `Windows 10 Enterprise N (Azure Marketplace)`

**Client OperatingSystem**
MacOS, PuTTY, any others

**What is failing**
After a certain period of inactivity where no fresh data is being sent back or forth, the connection will hang. It doesn't advise the client of a disconnect, but rather the terminal is completely unresponsive and cannot be CTRL-C'd from and the like.

This causes trouble because I can't determine the outcome of certain long running operations. Not to mention it's simply really frustrating to develop on when you have to force-kill the terminal process and restart anew, losing buffer and history.

**Expected output**
A session that is idle (but connected) should never hang, and be just as responsive as when it was first connected like on any UNIX or UNIX-like system.

**Actual output**
A session hangs mysteriously when left alone for a short period of less than 10 minutes.

**Comment by gravcat** [comment]
I am going to try to set my log level to `VERBOSE` and post results/logs of an isolated occurrence. Standby.

Also please bear with me, I did do my best to research the issue and review the issue tracker for historical occurrences for which I could find none.

**Comment by gravcat** [comment]
Client log provided by `-v` switch. Nothing of interest though there may be deeper levels to inspect?

```username@192.168.1.100's password: 
debug1: Authentication succeeded (password).
Authenticated to 192.168.1.100 ([192.168.1.100]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8```

**Comment by gravcat** [comment]
Video demonstrating the problem: https://www.youtube.com/watch?v=gt0NWxe4gAc

**Comment by bagajjal** [comment]
Thanks for the detailed post. We'll take a look.

**Comment by bagajjal** [comment]
I couldn't reproduce this issue.
Please share your sshd_config and sshd.log (DEBUG3).

**Comment by lejello** [comment]
Since you are specifying "Azure Marketplace" in your OS name, I'm guessing you are using an Azure VM.

Azure SNAT and load balancers applies a 4 minutes default idle timeout to all inbound and outbound tcp connections. See https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-idle-timeout and https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections

**Comment by gravcat** [comment]
@bagajjal I will test out @lejello's suggestions first and report back. If that doesn't resolve, I'll upload my (very stock) `sshd_config` and `sshd.log`. Thanks!

**Comment by bagajjal** [comment]
@gravcat - Any update on this?

**Comment by bagajjal** [comment]
reopen this if required with required information.
