### ISSUE TITLE
SSHD service access

### ISSUE THREAD

**Issue by kviktor** [PowerShell/Win32-OpenSSH#824]
I'm trying to call `signtool.exe` via ssh but it gives me this (it basically translates to access denied)
```
SignTool Error: An unexpected internal error has occurred.
C:\Users\xy\xy.exe
Error information: "Error: Store::ImportCertObject() failed." (-2146893808/0x80090010)
```

- If I use the same command via the command line from the Windows machine things works so the issue is somewhere doing it via SSH
- If I set `Local system account` in Services / sshd / Log On everything works except the auth using private key and it asks for password.

What would be the best way to solve this issue? Is it possible to find Local system account's home direcotry and put a key there or somehow grant access to NT Service\sshd?

**"OpenSSH for Windows" version**
v0.0.18.0
 
**Server OperatingSystem**
Windows 7 prof 32 bit

edit.: looks like it's possible to workaround the issue using `sshpass` and password but would be good if it worked with public key auth too.

**Comment by manojampalam** [comment]
From a security standpoint, remote SSH sessions run under the context of the authenticated user (irrespective of sshd running as LocalSystem or not). 

What is the user account you are using to login via ssh?

**Comment by manojampalam** [comment]
Reopen if needed.

**Comment by kviktor** [comment]
It was an administrator user, the Windows machine runs in a trusted environment so I just used `sshpass` in my script, not nice but works.
