### ISSUE TITLE
ChrootRoot +sftp only on Windows Server 2008R2 standard 64bit not working

### ISSUE THREAD

**Issue by stwongst** [PowerShell/Win32-OpenSSH#825]
Hi,

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
>> Get-Command sshd failed with 'sshd' not recognized.
>> It's latest build ( https://github.com/PowerShell/Win32-OpenSSH/releases/download/v0.0.18.0/OpenSSH-Win64.zip).
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

>> Windows Server 2008 R2 Standard

**What is failing**

Chroot in sftp only setup not working.  Configuration file follows:

---------
Subsystem          sftp        internal-sftp                       
                                
Match User usera                                
                ChrootDirectory c/Users/usera           
                PermitTunnel no
                AllowAgentForwarding no
                AllowTcpForwarding no
                X11Forwarding no
                ForceCommand internal-sftp                     
---------

**Expected output**

User cannot CD out of ChrootDirectory.

**Actual output**

User can CD out of ChrootDirectory. 
Can CD to \Users but can't list files in subfolders
Can CD to system folders like  \Windows, \Program Files and list the files there.

Please help.

Thanks a lot.

**Comment by Aevis** [comment]
This is a feature yet to be implemented, see [#190](https://github.com/PowerShell/Win32-OpenSSH/issues/190)

The only workaround seems to be restricting the user's access by setting your file system permissions accordingly.

**Comment by stwongst** [comment]
Got it.  Thanks a lot.
