### ISSUE TITLE
Typo on Wiki - Install-Win32-OpenSSH

### ISSUE THREAD

**Issue by B-z-F** [PowerShell/Win32-OpenSSH#829]
There are single quotes at:
`netsh advfirewall firewall add rule name='SSH Port' dir=in action=allow protocol=TCP localport=22`
but should be double:
`netsh advfirewall firewall add rule name="SSH Port" dir=in action=allow protocol=TCP localport=22`

**Comment by manojampalam** [comment]
Thanks. The above works in Powershell and the below one in cmd.exe. I'll remove the space to keep it simple.
