### ISSUE TITLE
Port forwarding not works

### ISSUE THREAD

**Issue by regomne** [PowerShell/Win32-OpenSSH#83]
I open a server in my pc and use this command to open a port forwarding in the same machine:
ssh -N -p 30226 -R 12341:localhost:8087 myusername@localhost

and then
telnet localhost 12341

telnet open a connection succesfully, and netstat show it has open:
TCP    [::1]:2780             [::1]:12341            ESTABLISHED

However, I can't find any connection connected to [::1]:8087. And I can't receive any response from the  telnet to 12341 (the 8087 port should response an error if I input something)

**Comment by quamrulmina** [comment]
We tested similar commands and it works. Please make sure that your 8087 app is running. Also use our latest build.

**Comment by quamrulmina** [comment]
Tested this scenario to work with a Windows telnet server and a telnet client. The user must make sure their app on port 8087 is running and listening. Closing the issue as test scenario in our lab testing worked.
