### ISSUE TITLE
installation was ok as per the instructions. tried starting the daemon. it returned sshd terminated unexpectedly

### ISSUE THREAD

**Issue by cyfrost** [PowerShell/Win32-OpenSSH#830]
So i just installed the latest release [v0.0.18.0](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.18.0). installation was successful. it turns out the daemon isn't working because when i tried starting the `sshd` service from Services control panel it returns "(Error 1067) The process terminated unexpectedly". it is interesting to note that when i do a "net start sshd" from elevated command prompt it says "sshd service started successfully", when i check back in Services it's not running. it must have terminated unexpectedly as stated earlier. is anyone else facing this issue? what can be the possible fix?

**Comment by bagajjal** [comment]
Run the sshd in debug mode (./sshd.exe -ddd) to see what's going wrong

**Comment by manojampalam** [comment]
Reopen if you still have an issue (refer https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps for troubleshooting steps)
