### ISSUE TITLE
Typo in misc.c

### ISSUE THREAD

**Issue by Wazner** [PowerShell/Win32-OpenSSH#832]
Hello,

I found a typo in misc.c while reading through the source code in the procedure `sanitized_path`.
https://github.com/PowerShell/Win32-OpenSSH/blob/993c15663a8fffdf2729a557a04061e8632cd65a/contrib/win32/win32compat/misc.c#L894

I believe it should be `sizeof(newPath)` instead of `sizeof(PATH_MAX)`. Incidentally it's not a bug because the string will always be 3 characters long (+ \0 byte) and the sizeof PATH_MAX (an int) is 4.

**Comment by bagajjal** [comment]
Thanks for reporting, we will fix it

**Comment by bagajjal** [comment]
Please check the aug-mid release..
