### ISSUE TITLE
SFTP-Server does not log when using a non-admin account

### ISSUE THREAD

**Issue by thezim** [PowerShell/Win32-OpenSSH#834]
I didn't see and obvious answer as to how to do this without syslog. It there any way other way? For security audits I need to know the users activity not just logins and session info.

**Comment by bagajjal** [comment]
Go to the sftp-server.exe directory, you can see the logs folder (if not then please create the logs folder).

In the sshd_config, specify the loglevel
Subsystem       sftp    sftp-server -l DEBUG3

The logs will be written to sftp-server.log file.

**Comment by thezim** [comment]
Log file is not being created in the logs folder after the config modification and service restart. Below is the my sftp config line.
```
# override default of no subsystems
Subsystem	sftp	sftp-server.exe -l DEBUG3
```

**Comment by manojampalam** [comment]
We have a limitation with Windows implementation. For sftp-server traces, you'll either need to login (via ssh) as an admin account or give that specific user permissions to write to Logs folder.

**Comment by thezim** [comment]
@manojampalam does it have to be write permission to the entire folder or can it be for sftp-server.log only assuming I create the file myself first?

**Comment by bagajjal** [comment]
@thezim - Did it work for you, with right permissions to sftp-server.log?

sftp-server.exe runs in the user context so we need to provide the write access for that user to write to the sftp-server.log file.

**Comment by bagajjal** [comment]
@thezim - Can this be closed?

FYI, The long term solution (backlog item) is to use the windows logging mechanism instead of writing to sftp-server.log.

**Comment by thezim** [comment]
@bmanikm Yes. Will there still be an option to log to sftp-server.log in the future? Parsing and archiving logs for security audits is much easier with a log file.

**Comment by bagajjal** [comment]
@thezim - Its too early to comment on the future implementation but we will certainly keep this information (writing to a log file so the parsing,archiving is easy) during our implementation.
