### ISSUE TITLE
Enter the windows interactive session via "ssh"

### ISSUE THREAD

**Issue by psmolkin** [PowerShell/Win32-OpenSSH#837]
**"OpenSSH for Windows" version**
0.0.18.0
 
**Server OperatingSystem**
 win10  v15063

**Client OperatingSystem**
Debian 8.9 
openssh-client_6.7

**What's wrong**
When I run this command in bash
`powershell -c "Invoke-Command  -HostName Hostname -UserName User@Domain -ScriptBlock {[Environment]::UserInteractive }"`   
I receive  `True`

but 
`ssh User@Domain@Dostname powershell -c "[Environment]::UserInteractive"`
gives `False`

Any idea how to enter an interactive session via "ssh"?

**Comment by bagajjal** [comment]
This will launch the interactive powershell ssh session.

ssh -t User@Domain@Dostname powershell

**Comment by bagajjal** [comment]
Did it work for you? can this be closed?

**Comment by psmolkin** [comment]
Unfortunately it didn't help me. So I modified that service which I tried to start remotely as console app.
And yes, this issue can be closed. Thanks.

**Comment by masaeedu** [comment]
@bagajjal Could this please be reopened? I don't have the ability to rewrite the service as a console application to work around the issue.

**Comment by romanad** [comment]
I need an answer too, I'm trying to turn off monitor in Windows 10 via SSH but can't find a way.
I suppose I have to run the script as an interactive user.

**Comment by maertendMSFT** [comment]
This should work using PowerShell remoting over SSH.

**Comment by ivandeex** [comment]
@maertendMSFT 
> This should work using PowerShell remoting over SSH.

This issue is not "answered".
Please provide an example or proof-link.

**Comment by ChristoWolf** [comment]
I am experiencing the same behavior.
Despite following various related MSDN articles ([1](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7.1#set-up-on-a-windows-computer), [2](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration) and of course [3](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)) using PowerShell 5.1 at first and then PowerShell 7.1 on both the client and server machines, no remote PS session was interactive.
Works fine with WinRM though.
Of course, I tried it also explicitly using the [`-t`](https://man.openbsd.org/ssh#t) OpenSSH flag as suggested above, still no interactive session.
The same applies to [`Enter-PSSession`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/enter-pssession?view=powershell-7.1#notes).

**Comment by jathri** [comment]
To turn off monitor or run anything detached from the current session, see: https://github.com/PowerShell/Win32-OpenSSH/issues/913#issuecomment-2645379135
