### ISSUE TITLE
ssh-keygen.exe returns invalid format when passphrase is not empty on -noOpenSSL build

### ISSUE THREAD

**Issue by bingbing8** [PowerShell/Win32-OpenSSH#838]
**"OpenSSH for Windows" version**
0.0.18.0
 
**Server OperatingSystem**
Windows 10

**Client OperatingSystem**
Windows 10

**What is failing**
```
ssh-keygen.exe -t ed25519 -P Bull -f C:\mspctl\openssh\id_ED25519
Generating public/private ed25519 key pair.
Saving key "C:\\mspctl\\openssh\\id_ED25519" failed: invalid argument
```
**Expected output**
key is generated.

**Actual output**
error is returned

**Comment by bingbing8** [comment]
[bug 2754](https://bugzilla.mindrot.org/show_bug.cgi?id=2754) is filed on openssh/openssh-portable

**Comment by ScottRFrost** [comment]
I just spent an hour trying to figure out what was wrong.  

In addition to ssh-keygen not working, if you try to copy over a key with a password from WSL or an actual Linux machine, it tells you:
`Load key "C:\\Users\\XXXXXXX/.ssh/id_ed25519": invalid format`

**Comment by jonathanpmartins** [comment]
Same problem here:

Load key "mykey.pem": invalid format

Similar thing happens when I try to use the Windows bash or native ssh on command prompt.

**Comment by ghost** [comment]
Still have this problem on Windows 10 using the beta from "Additional Features". Is there any way to create a key that is usable?

**Comment by timoabend** [comment]
Hi!

Same problem here when I enter a passphrase. It works, if I leave it blank.

Greetings
  Timo

**Comment by byronigoe** [comment]
Same problem here. So, the bug was fixed on 2017-08-15, but the new build hasn't made it into the Windows OpenSSH beta?

**Comment by bagajjal** [comment]
Please wait for the new Windows update..
FYI, meanwhile you can try our github version that has the latest and greatest changes..

**Comment by chunliu** [comment]
@bagajjal the issue seems still there in v1.0.0.0-beta.

**Comment by chunliu** [comment]
This issue doesn't happen in v1.0.0.0-beta anymore.

**Comment by mattjanssen** [comment]
For future reference, I got the "Load key "/c/Users/matt/.ssh/id_ed25519": invalid format" error after I had created the key file using Notepad. Instead, by copying it from with WSL I fixed the problem.
