### ISSUE TITLE
Page-UP / Page-DOWN keys send only NUL characters 

### ISSUE THREAD

**Issue by rivy** [PowerShell/Win32-OpenSSH#842]
The <kbd>Page-UP</kbd> and <kbd>Page-DOWN</kbd> keys send incorrect sequences when using the `ssh.exe`  client to connect to a Linux host.

By using `od -c` on the Linux host, it can be seen that a <kbd>Page-UP</kbd> or <kbd>Page-DOWN</kbd> keypress sends only a NUL character (aka, <kbd>CTRL-@</kbd>) to the host.

**"OpenSSH for Windows" version**
0.0.18.0
 
**Server OperatingSystem**
Ubuntu 16.04

**Client OperatingSystem**
Windows 10 Pro

**Comment by bagajjal** [comment]
@rivy - these are working on my machine.. Can you please help me with the associated VT sequence for page up / down..

**Comment by bagajjal** [comment]
@rivy - Will fix it for the aug-mid release

**Comment by bagajjal** [comment]
Please check the aug-mid release on 8/18
