### ISSUE TITLE
Alt does not act as the Meta key

### ISSUE THREAD

**Issue by thecliguy** [PowerShell/Win32-OpenSSH#845]
**"OpenSSH for Windows" version**
0.0.18.0
 
**Client OperatingSystem**
Windows 10 (Version: 1703 Build: 10.0.15063.540)

**What is failing**
A modifier key is a key that modifies the action of another key when the two are pressed together.
The Meta key is an example of a modifier key. In the absence of a physical meta key, the Alt key is commonly used to act as such.

In Weechat (an IRC client), navigating between buffers is achieved by:
  * Pressing an holding the meta key, followed by a number key (1-9).
  * Pressing an holding the meta key, followed by an arrow key.

**Expected behaviour**
The Alt key should act as the meta key.

The Alt key behaves as expected when using the OpenSSH client on the Windows Subsystem for Linux (aka Bash on Windows):

&nbsp;&nbsp;&nbsp;&nbsp;SOURCE COMPUTER: Windows 10 (Version: 1703 Build: 10.0.15063.540) using the OpenSSH client on the Windows Subsystem for Linux

&nbsp;&nbsp;&nbsp;&nbsp;TARGET SERVER: Ubuntu 16.04.3 LTS server

&nbsp;&nbsp;&nbsp;&nbsp;OUTCOME:  The Alt key behaves as expected when used in Weechat.

&nbsp;&nbsp;&nbsp;&nbsp;ADDITIONAL INFO:
&nbsp;&nbsp;&nbsp;&nbsp;```sudo showkey```
&nbsp;&nbsp;&nbsp;&nbsp;The Alt key emits no output unless used in conjunction with another key, which is the expected behaviour of a modifier.

**Actual behaviour**
&nbsp;&nbsp;&nbsp;&nbsp;SOURCE COMPUTER: Windows 10 (Version: 1703 Build: 10.0.15063.540) using the Win32-OpenSSH SSH client (0.0.18.0).

&nbsp;&nbsp;&nbsp;&nbsp;TARGET: Ubuntu 16.04.3 LTS server

&nbsp;&nbsp;&nbsp;&nbsp;OUTCOME: The Alt key has no effect when used in Weechat.

&nbsp;&nbsp;&nbsp;&nbsp; ADDITIONAL INFO:
&nbsp;&nbsp;&nbsp;&nbsp;```sudo showkey```
&nbsp;&nbsp;&nbsp;&nbsp;The Alt key immediately emits ```^@```. This suggests that the key is not acting as a modifier.

**Comment by bagajjal** [comment]
@thecliguy  - I have fixed this. Could you please test these private changes and let me know if everything looks good..
[ssh_alt_meta_fix.zip](https://github.com/PowerShell/Win32-OpenSSH/files/1294504/ssh_alt_meta_fix.zip)

**Comment by thecliguy** [comment]
@bagajjal - Excellent. I will conduct some tests tonight and let you know the outcome.

**Comment by thecliguy** [comment]
@bagajjal Apologies for the delay. I have conducted some tests using the version you supplied in 'ssh_alt_meta_fix.zip'. 

As mentioned in my initial post, in Weechat (an IRC client), navigating between buffers is achieved by:
1. Pressing and holding the meta key, followed by a number key (1-9).
1. Pressing and holding the meta key, followed by an arrow key.

Previously, neither of these navigation methods worked. In _ssh_alt_meta_fix.zip_, method 1 now works but method 2 still doesn't work.

_(In my initial post, I used ```sudo showkey``` to output key presses. I have since learnt that the same thing can be achieved using ```cat -v```)_

Using the OpenSSH client on the Windows Subsystem for Linux, ```cat -v``` produces the following output when <kbd>alt</kbd> and <kbd>&downarrow;</kbd> are pressed together: ```^[[1;3B```.

Using Win32-OpenSSH client with your fix _(ssh_alt_meta_fix.zip)_, ```cat -v``` produces the following output when <kbd>alt</kbd> and <kbd>&downarrow;</kbd> are pressed together: ```^[[B```.

So why does  pressing the meta key in combination with an arrow key behave differently in Win32-OpenSSH?

**Comment by bagajjal** [comment]
@thecliguy - Thanks for trying the private changes.
I couldn't test the curosor keys (alt+up/down/etc).. I have fixed this issue and tested.
Please test this latest private binary. 
[ssh_fixAlt_issue.zip](https://github.com/PowerShell/Win32-OpenSSH/files/1312566/ssh_fixAlt_issue.zip)

**Comment by thecliguy** [comment]
@bagajjal - I have tested the latest private release you provided and cursor keys (alt+up/down/etc) now work as expected. 

So this issue is now resolved, thank you for addressing it so quickly!

I hope this fix will be in the next release?

**Comment by bagajjal** [comment]
This is fixed and code changes are submitted.
Please check the September end release.
