### ISSUE TITLE
SSH for .NET

### ISSUE THREAD

**Issue by leoniDEV** [PowerShell/Win32-OpenSSH#85]
Do you plan to release also an "_official_" SSH library for .NET?

**Comment by manojampalam** [comment]
Currently not in plan. Will keep this open as a feature request.

**Comment by xied75** [comment]
Probably better to support this https://github.com/sshnet/SSH.NET

**Comment by leoniDEV** [comment]
I know that project, but seemed no more in development.
But i've seen that the developer has done some commits in the recent days after a long period of inactivity

**Comment by TehWardy** [comment]
I'd be interested in this too :)

**Comment by maertendMSFT** [comment]
There are no plans for this in the future.  We recommend looking at a third part solution.
