### ISSUE TITLE
ssh-agent fails with "unable to open service handle"

### ISSUE THREAD

**Issue by cowlinator** [PowerShell/Win32-OpenSSH#851]
**"OpenSSH for Windows" version**
0.0.18.0

**Server OperatingSystem**
No server
 
**Client OperatingSystem**
Microsoft Windows [Version 10.0.14393]

**What is failing**
I am trying to run ssh-agent on windows, but it fails to run.

```
choco install -y openssh
refreshenv
ssh-agent
```

**Expected output**
```
Agent pid {XYZ}
```

**Actual output**
```
unable to open service handle
```

**Comment by cowlinator** [comment]
(Also, I do not have posh-git installed.)

**Comment by bagajjal** [comment]
@cowlinator - Could you please try these steps,
1) verify if the ssh-agent is registered as service.. (check in the taskmanager, services tab)
2) From an elevated cmd.exe, run "net start ssh-agent" -> This should start the ssh-agent

If you still have issues then please use the attached ssh-agent x64 binary that will capture the error code returned by windows, 
[ssh-agent.zip](https://github.com/PowerShell/Win32-OpenSSH/files/1285930/ssh-agent.zip)

**Comment by manojampalam** [comment]
ssh-agent for Windows is implemented as a service. You'll need to run install-sshd.ps1 to install ssh-agent service. 
Reopen if you have any questions.

**Comment by cowlinator** [comment]
Thank you manojampalam.  You were correct.
I was able to resolve this by running 
powershell -ExecutionPolicy Bypass -File "%ProgramFiles%\OpenSSH-Win64\install-sshd.ps1"

**Comment by DarwinJS** [comment]
**Avoiding this Error with the Chocolatey Package:**
When you are installing only the client tools, the ssh-agent feature is optional and must be specified like this:

`choco install -y openssh -params '"/SSHAgentFeature"'`

This facilitates install scenarios where the ssh.exe binaries are needed for reasons other than supporting ssh on an interactive user machine. (e.g. as a automation prerequisite to be able to connect to another system).

FYI - whenever the /SSHServerFeature is used, the package automatically flips on the /SSHAgentFeature as well - so you may be used to that scenario auto installing the agent.

**Comment by DarwinJS** [comment]
**Avoiding this Error with the Chocolatey Package:**
When you are installing only the client tools, the ssh-agent feature is optional and must be specified like this:

`choco install -y openssh -params '"/SSHAgentFeature"'`

This facilitates install scenarios where the ssh.exe binaries are needed for reasons other than supporting ssh on an interactive user machine. (e.g. as a automation prerequisite to be able to connect to another system).

FYI - whenever the /SSHServerFeature is used, the package automatically flips on the /SSHAgentFeature as well - so you may be used to that scenario auto installing the agent.
 /cc @manojampalam @bagajjal
