### ISSUE TITLE
scp

### ISSUE THREAD

**Issue by hdatma** [PowerShell/Win32-OpenSSH#857]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`

0.0.18.0
 
sshd_config includes the following (and it works):
ForceCommand C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

Windows 10 Pro

**Client OperatingSystem**

unix

**What is failing**

scp

**Expected output**

**Actual output**

[sshd_log.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1248607/sshd_log.txt)
[scp_log.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1248608/scp_log.txt)

**Comment by bagajjal** [comment]
This is expected behaviour... When force command is there in sshd_config, sftp or scp will not work

**Comment by manojampalam** [comment]
Please reopen of needed
