### ISSUE TITLE
Answerback not working

### ISSUE THREAD

**Issue by bgrossman** [PowerShell/Win32-OpenSSH#859]
**"OpenSSH for Windows" version**
0.0.18.0
 
**Server OperatingSystem**
Windows Server 2012 R2 Standard

**Client OperatingSystem**
Windows 10

**What is failing**
My application uses answerback to have the client send back a message in response to the enquiry character. When using OpenSSH server, it looks as if the character is translated and so the client never receives it. 

**Expected output**
For example, using PuTTY, by default it sends back the string "PuTTY" in response to enquiry character. If I have the console output the enquiry character, "PuTTY" should be displayed as if I typed it. 

**Actual output**
The character displayed is ♣. PuTTY does not display "PuTTY". 

Testing with Microsoft Telnet Server and freeSSHd on the same server using the same PuTTY client settings, no character is displayed in place of the enquiry character and "PuTTY" is displayed as expected.

**Comment by bagajjal** [comment]
Please provide the reproduction steps..

**Comment by bagajjal** [comment]
Please reopen with the reproduction steps...
