### ISSUE TITLE
setup-ssh-lsa.cmd: copy ssh-lsa.dll fails

### ISSUE THREAD

**Issue by kanantha** [PowerShell/Win32-OpenSSH#86]
The copy command fails with a "system cannot find the file specified" error probably because of missing quotes.

Following is the output from setup-ssh-lsa.cmd:

    PS C:\Program Files\OpenSSH-Win32> cmd /c setup-ssh-lsa.cmd
    
    C:\Program Files\OpenSSH-Win32>if AMD64 == x86 (set lsadll=C:\Program Files\OpenSSH-Win32\x86\ssh-lsa.dll )
    
    C:\Program Files\OpenSSH-Win32>if AMD64 == AMD64 (set lsadll=C:\Program Files\OpenSSH-Win32\x64\ssh-lsa.dll )
    
    C:\Program Files\OpenSSH-Win32>copy C:\Program Files\OpenSSH-Win32\x64\ssh-lsa.dll C:\Windows\system32\
    The system cannot find the file specified.
    
    C:\Program Files\OpenSSH-Win32>reg add HKLM\System\CurrentControlSet\Control\Lsa /v "Authentication Packages" /t REG_MUL
    TI_SZ  /d  msv1_0\0ssh-lsa.dll -f
    The operation completed successfully.

**Comment by nachfuellbar** [comment]
https://github.com/PowerShell/Win32-OpenSSH/issues/81

**Comment by manojampalam** [comment]
script is part of the release package. Will fix it as part of next release

**Comment by manojampalam** [comment]
replace script in latest release
