### ISSUE TITLE
 Can not convert System.string

### ISSUE THREAD

**Issue by Ben-oDesign** [PowerShell/Win32-OpenSSH#860]
Hello,

I have the Foolowing problem 

**"OpenSSH for Windows" version**
 v0.0.19.0
 
**Server OperatingSystem**
Windows 7 64 bits

**Client OperatingSystem**
Windows XP, Windows 7 Windows 10

**What is failing**
I follow this tutorial : https://winscp.net/eng/docs/guide_windows_openssh_server
When I need to enter the following command  : `powershell.exe -ExecutionPolicy Bypass -File .\FixHostFilePermissions.ps1 -Confirm:$false`
It failed

**Expected output**
https://image.noelshack.com/fichiers/2017/34/5/1503652137-erreur-openssh.jpg

Thank you for help :)

**Comment by megamorf** [comment]
Your confirm switch is missing a dollar sign

**Comment by bagajjal** [comment]
closing this issue as it is because of the typo in the command..

**Comment by tvsuhail** [comment]
It works on Windows XP SP3?
