### ISSUE TITLE
Unable to use nano on remote linux hosts

### ISSUE THREAD

**Issue by marekr** [PowerShell/Win32-OpenSSH#861]
Please answer the following

**"OpenSSH for Windows" version**
0.0.19.0
 
**Server OperatingSystem**
Debian 8

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
If I use "nano" on a Linux system to create a new file, when it prompts for the filename I can type it in. When I hit "Enter" its supposed to go ahead and save the file but instead does nothing.

Screen cap of the steps in cmd.exe:
http://i.imgur.com/f8Q2V2V.gifv

Using cmd.exe or powershell, you get a bell sound everytime you press enter and nothing happens.
Using CMDER its just silent :/

Nano on the remote server works fine in a CYGWIN ssh copy instead of the native.

It used to work, I think the last working build I think was v0.0.17.0 though I'm not sure. 18 and 19 are both broken.

I'm guessing ssh.exe is eating the enter key somehow. It works outside nano just fine in the plain shell though (making new shell lines)

**Expected output**
The save file screen accepts the Enter key

**Actual output**
Bell sound plays in Windows instead

**Comment by SilentSpud** [comment]
If you try to use the enter key while editing text, it tries to justify the text instead

**Comment by bagajjal** [comment]
please check the latest release 0.0.20.0

**Comment by marekr** [comment]
Works now, thanks.
