### ISSUE TITLE
authorized_keys line 1 exceeds size limit

### ISSUE THREAD

**Issue by lucastheisen** [PowerShell/Win32-OpenSSH#862]
**"OpenSSH for Windows" version**
```
PS C:\Users\ltheisen> ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
0.0.19.0
```
 
**Server OperatingSystem**
 ```
PS C:\Users\ltheisen> ((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).Produc
tName)
Windows 10 Pro
```

**Client OperatingSystem**
```
PS C:\Users\ltheisen> ((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).Produc
tName)
Windows 10 Pro
```

**What is failing**
Authorized key authentication

**Expected output**
Successful login

**Actual output**
In the server log (`sshd -ddd`):
```
debug1: attempt 1 failures 0
debug2: input_userauth_request: try method publickey
debug1: userauth_pubkey: test whether pkalg/pkblob are acceptable for RSA SHA256:733ceEP/KG0kKBZVDqX8w3hXHetEoYNVUt9cZE24+6Y
debug1: trying public key file C:\\Users\\ltheisen\\.ssh/authorized_keys
debug1: read_keyfile_line: C:\\Users\\ltheisen\\.ssh/authorized_keys line 1 exceeds size limit
debug2: key not found
debug2: userauth_pubkey: authenticated 0 pkalg rsa-sha2-512
Failed publickey for ltheisen from ::1 port 59484 ssh2
debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive"
debug3: send packet: type 51
debug3: receive packet: type 50
debug1: userauth-request for user ltheisen service ssh-connection method keyboard-interactive
```

In the client console (`ssh -vvv localhost`):
```
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug3: start over, passed a different list publickey,password,keyboard-interactive
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:733ceEP/KG0kKBZVDqX8w3hXHetEoYNVUt9cZE24+6Y C:\\Users\\ltheisen/.ssh/id_rsa
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Trying private key: C:\\Users\\ltheisen/.ssh/id_dsa
debug3: GetFileAttributesExW with last error 2
debug3: no such identity: C:\\Users\\ltheisen/.ssh/id_dsa: No such file or directory
debug1: Trying private key: C:\\Users\\ltheisen/.ssh/id_ecdsa
debug3: GetFileAttributesExW with last error 2
debug3: no such identity: C:\\Users\\ltheisen/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: C:\\Users\\ltheisen/.ssh/id_ed25519
debug3: GetFileAttributesExW with last error 2
debug3: no such identity: C:\\Users\\ltheisen/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup keyboard-interactive
debug3: remaining preferred: password
```

And here is the entry in the `authorized_keys` (generated by `ssh-keygen -t rsa -b 4096`):
```
PS C:\Users\ltheisen> get-content .\.ssh\authorized_keys | select -First 1
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDsgFU14LPgFvNlfUokLLAtNX3Idl+s+zHG9MqS+Fa/XNsqrYoZSD+B4vnXGPoew/I04+r7d5QYpW+H75+uQwNW3PsEVe0Anp+J585/pdC/M3E3YqecWVhMBHD5SZ4j9sZYCOViXguJUSSM6r+fIUv7gFpotPoMTmJC6QEhzVC5jz3d93+/9zGYGaMu9st7UVqvLNIwwEFClM87fGycf4bf1Zrqp1Kakr4VzCUQhpkxVOpItKTueyILd6eolUqL1YG+14TTnVqqc2+o/UihnATgrCFCvV5UcjnjHRUbKZMvn/DiTv6askffHoQ7BYWHLstidR4NTLSqJXuxvLcwdWEzP2thba2QNhEm/o4MvyJlPcqLXhWLcXqvnMp/P36dcPiwiElGUOjM/VV29/KJpG3ZQf3xjnCbjoHSbVcaljNsymO9ejEXLw7h1yBAjGLXc/u5qRSsI18JRyfAd+kRzdzM2wYlZNc9nW4hWLTX/CpUj8KyDybgM/iqBDuSX4rUZt9SIHGJxm9vbC05Ed99rvz6ckdGKgmNHx8d4o0vXLqsPbn5fNZf6ovTNWKAo0c/guD01xsxo/oaplpHX6k4n+ujPYc0+6shSD8+UiQ2q46LqJD+jokVHEe/iA0YyvgYG5EGUUOgIPcPqBOFU+dCROcA+B+fh8C8OT8hAcfUye1+Mw== ltheisen@ljt530
```
Also, it might be worth stating that I went through all of the [file permission setup](https://github.com/PowerShell/Win32-OpenSSH/wiki/OpenSSH-utility-scripts-to-fix-file-permissions) as well

**Comment by mivale** [comment]
Same here. Same versions, followed all instructions to the letter. 20+ yrs experience with setting up openssh servers on linux, so no lack of general knowledge.

When I run this command from my home folder:

`ssh -i .ssh\id_rsa Administrator@localhost`

I get the error

`Warning: Identity file .ssh\id_rsa not accessible: No such process.`

Maybe this has something to do with this line in the config?

`hostkeyagent \\.\pipe\openssh-ssh-agent`

Might be related?

**Comment by manojampalam** [comment]
Just tried with the exact public key contents and this is what I see in logs. Can you check detailed logs on whats exactly being read from authorized_keys (perhaps multiple keys are being read at once - that may indicate a CR CR/LF issue)


debug1: trying public key file C:\\Users\\nonadmin\\.ssh/authorized_keys
debug2: user_key_allowed: check options: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDsgFU14LPgFvNlfUokLLAtNX3Idl+s+zHG9MqS+Fa/XNsqrYoZSD+B4vnXGPoew/I04+r7d5QYpW+H75+uQwNW3PsEVe0Anp+J585/pdC/M3E3YqecWVhMBHD5SZ4j9sZYC
OViXguJUSSM6r+fIUv7gFpotPoMTmJC6QEhzVC5jz3d93+/9zGYGaMu9st7UVqvLNIwwEFClM87fGycf4bf1Zrqp1Kakr4VzCUQhpkxVOpItKTueyILd6eolUqL1YG+14TTnVqqc2+o/UihnATgrCFCvV5UcjnjHRUbKZMvn/DiTv6askffHoQ7BYWHLstidR4NTLSqJXuxvLcwdWEz
P2thba2QNhEm/o4MvyJlPcqLXhWLcXqvnMp/P36dcPiwiElGUOjM/VV29/KJpG3ZQf3xjnCbjoHSbVcaljNsymO9ejEXLw7h1yBAjGLXc/u5qRSsI18JRyfAd+kRzdzM2wYlZNc9nW4hWLTX/CpUj8KyDybgM/iqBDuSX4rUZt9SIHGJxm9vbC05Ed99rvz6ckdGKgmNHx8d4o0vXLq
sPbn5fNZf6ovTNWKAo0c/guD01xsxo/oaplpHX6k4n+ujPYc0+6shSD8+UiQ2q46LqJD+jokVHEe/iA0YyvgYG5EGUUOgIPcPqBOFU+dCROcA+B+fh8C8OT8hAcfUye1+Mw== ltheisen@ljt530
'
debug2: user_key_allowed: advance: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQDsgFU14LPgFvNlfUokLLAtNX3Idl+s+zHG9MqS+Fa/XNsqrYoZSD+B4vnXGPoew/I04+r7d5QYpW+H75+uQwNW3PsEVe0Anp+J585/pdC/M3E3YqecWVhMBHD5SZ4j9sZYCOViXguJUSSM6r+
fIUv7gFpotPoMTmJC6QEhzVC5jz3d93+/9zGYGaMu9st7UVqvLNIwwEFClM87fGycf4bf1Zrqp1Kakr4VzCUQhpkxVOpItKTueyILd6eolUqL1YG+14TTnVqqc2+o/UihnATgrCFCvV5UcjnjHRUbKZMvn/DiTv6askffHoQ7BYWHLstidR4NTLSqJXuxvLcwdWEzP2thba2QNhEm/o
4MvyJlPcqLXhWLcXqvnMp/P36dcPiwiElGUOjM/VV29/KJpG3ZQf3xjnCbjoHSbVcaljNsymO9ejEXLw7h1yBAjGLXc/u5qRSsI18JRyfAd+kRzdzM2wYlZNc9nW4hWLTX/CpUj8KyDybgM/iqBDuSX4rUZt9SIHGJxm9vbC05Ed99rvz6ckdGKgmNHx8d4o0vXLqsPbn5fNZf6ovTN
WKAo0c/guD01xsxo/oaplpHX6k4n+ujPYc0+6shSD8+UiQ2q46LqJD+jokVHEe/iA0YyvgYG5EGUUOgIPcPqBOFU+dCROcA+B+fh8C8OT8hAcfUye1+Mw== ltheisen@ljt530
'

**Comment by mivale** [comment]
I've found something that might be of importance:

I created the authorized_keys file on Windows using Notepad++.

When editing I noticed that the encoding for the file (as show at the right-bottom of the window) was shown as UCS-2 LE BOM

When I changed this to UTF-8 (using the Encoding menu) it suddenly started working!

Before, i tried to edit the file in notepad, but that obviously didn't change the BOM.

Old setting

![image](https://user-images.githubusercontent.com/197782/29963933-cd96fa02-8f08-11e7-9b0e-ad4fddcbe0c4.png)

New setting

![image](https://user-images.githubusercontent.com/197782/29963957-dda448c8-8f08-11e7-83c5-4930e9611f0a.png)

**Comment by manojampalam** [comment]
@mivale Thanks. You found the issue. OpenSSH code (since its based on Unix) expects the file contents in UTF-8. 
Added this limitation here - https://github.com/PowerShell/Win32-OpenSSH/wiki/Various-Considerations

**Comment by lucastheisen** [comment]
Excellent!  Thank you, conversion to utf-8 fixed it:
```
Get-Content ~\.ssh\authorized_keys | Set-Content -Encoding utf8 ~\.ssh\authorized_keys-utf8
Move-Item ~\.ssh\authorized_keys-utf8 ~\.ssh\authorized_keys
Import-Module 'C:\Program Files\OpenSSH-Win64\OpenSSHUtils.psd1' -Force
Repair-AuthorizedKeyPermission -FilePath ~\.ssh\authorized_keys
```

**Comment by wcc-neal** [comment]
Thanks - the conversion to utf-8 fixed it for me as well

**Comment by benh57** [comment]
This saved me as well. Thanks!

**Comment by levanidev** [comment]
Wow, after 2 years, i came across this and it solved my issue. Why the hell did windows save files in that weird encoding and not UTF-8... seriously
