### ISSUE TITLE
[Alt] sends \0 instead of ESC

### ISSUE THREAD

**Issue by DHowett** [PowerShell/Win32-OpenSSH#865]
**"OpenSSH for Windows" version**
0.0.19.0 *and* the build provided by @bagajjal in issue #858.
 
**Server OperatingSystem**
```
Linux antares 4.12.0-1-amd64 #1 SMP Debian 4.12.6-1 (2017-08-12) x86_64 GNU/Linux
> OpenSSH_7.5p1 Debian-7, OpenSSL 1.0.2l  25 May 2017
```

```
Linux delfino 2.6.22.19 #31 Mon Jan 19 20:56:00 PST 2015 mips GNU/Linux
> Dropbear v2014.66
```

```
Linux ultraviolet.howett.net 3.2.0-24-generic #39-Ubuntu SMP Mon May 21 16:52:17 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
> OpenSSH_5.9p1 Debian-5ubuntu1.10, OpenSSL 1.0.1 14 Mar 2012
```

**Client OperatingSystem**
Windows 10 Enterprise Insider Preview

**What is failing**
The Alt key (Standard US-104 layout) sends `\0`. This breaks almost everything that relies on meta key sequences.

As an example,

```
$ xxd
(press Alt-Y) (control-D)
```

**Expected output**

```
00000000: 1b79                                     .y
```

(alt-y is sent as esc-y)

**Actual output**

```
00000000: 0079                                     .y
```

(alt-y is sent as `\0` `y`)

**Comment by DHowett** [comment]
This is a possible duplicate of #845, with a different repro.

**Comment by DHowett-MSFT** [comment]
@bagajjal Alt sending `\0` when you press it is almost definitely a bug, right? It doesn't even matter if you press it with another key -- just hitting alt, alt, alt will send `\0` `\0` `\0`.

**Comment by bagajjal** [comment]
@DHowett - We are not supporting alt meta keys as of now.. 
anything that is not supported will send \0, this is not specific to alt meta key word..
That's the reason I have marked it as Issue-Enhancement, hope this clarifies.

**Comment by DHowett-MSFT** [comment]
That makes sense; however: even pressing Alt-Tab -- which should not go to the session at all (!) -- sends a `\0`. It seems bad that any modifier press is being "sent" when it could wait for a fully-baked key+modifier combo before it sends `\0`.

**Comment by bagajjal** [comment]
This is fixed and code changes are submitted.
Please check the September end release.
