### ISSUE TITLE
Can't rerun commands using the command line viewer in Vim

### ISSUE THREAD

**Issue by dgc** [PowerShell/Win32-OpenSSH#866]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

* "Use legacy console (requires relaunch)" is unchecked:
* Width is set to 120 characters
* $env:TERM is set to "xterm"

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
0.0.19.0

**Server OperatingSystem**
`$ cat /etc/redhat-release`

CentOS Linux release 7.3.1611 (Core)

**Client OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

Windows 10 Pro

**What is failing**

I am getting unexpected behaviour in Vim when trying to rerun items from the command line viewer.

Reproduction steps:

1. Type "powershell" into the Start menu to get a powershell window
1. Type "ssh _remote-address_" to log into the remote machine
1. Type "vim" to start Vim
1. Type ":version" and press Enter to see Vim's version information. On my test, I see around 30 lines of text with the first line showing `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 21 2016 17:00:20)`.
1. Press Enter to return to the editor
1. Type "q:" to open the command line viewer
1. Type "k" to move the cursor up to the "version" command we just ran
1. Press Enter to rerun the version command.

**Expected output**

I expected to see Vim's version information a second time.

**Actual output**

The cursor moves to the line below.

**Comment by dgc** [comment]
You could almost dismiss this as a Vim issue but this works correctly via PuTTY.

**Comment by bagajjal** [comment]
@dgc - Can you try latest release 0.0.20.0
FYI, it works at my end
![vim-cmd-norepro](https://user-images.githubusercontent.com/23668037/30129257-33b4dd5a-92fa-11e7-9d80-c92af6b8b280.gif)

**Comment by dgc** [comment]
@bagajjal It's fixed for me in 0.0.20.0

Thanks!
