### ISSUE TITLE
Could not create directory '%systemroot%\\system32\\config\\systemprofile/.ssh'.

### ISSUE THREAD

**Issue by rickmoua** [PowerShell/Win32-OpenSSH#867]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**  -Windows 7

**What is failing**

**Expected output**

**Actual output**
C:\Program Files\OpenSSH>ssh -i .\id_rsa jsmith@172.24.212.210
Could not create directory '%systemroot%\\system32\\config\\systemprofile/.ssh'.

The authenticity of host '172.24.212.210 (172.24.212.210)' can't be established.

ECDSA key fingerprint is SHA256:qBiOdTlHD+pKc0j5i/jlU1bBCR1iwKClZlsb5+C6+WU.
Are you sure you want to continue connecting (yes/no)? yes
Failed to add the host to the list of known hosts (%systemroot%\\system32\\confi
g\\systemprofile/.ssh/known_hosts).
jsmith@172.24.212.210's password:

**Comment by manojampalam** [comment]
This might result when your user profile is not loaded. '%systemroot%\system32\config\systemprofile is the default profile (that gets pointed to when user profile is not loaded)

**Comment by manojampalam** [comment]
Reopen if needed.
