### ISSUE TITLE
Scp:  path quoting

### ISSUE THREAD

**Issue by drieseng** [PowerShell/Win32-OpenSSH#868]
Can you confirm that - for the scp protocol (on Windows) - a path should be enclosed in quotes to avoid metacharacters from being interpreted?

* Should quotes that are embedded in the path be escaped with a backslash?

  If I escape an embedded quote, then I get a "Protocol not available" error.

  **For example:**
  When I send an exec request with the following command:
  > scp -t "malicious\\"argument"

  I get the following error:
  > scp: malicious"argument: Protocol not available

* Do you need to escape backslashes in a path that is enclosed in quotes?

  **For example:**
  When I send an exec request with the following command:
  > scp -t "malicious\\\\argument"

  I get the following error:
  > scp: malicious//argument: No such process

  If I do not escape the backslash, then I get the same error.

  **For example:**
  When I send an exec request with the following command:
  > scp -t "malicious\\argument"

  I get the following error:
  > scp: malicious/argument: No such process

**Comment by manojampalam** [comment]
Based on this observation, try escaping it with " itself

E:\openssh\openssh-portable\bin\x64\Release>ssh localhost echo "dq"
dq

E:\openssh\openssh-portable\bin\x64\Release>ssh localhost echo "d""q"
d"q
