### ISSUE TITLE
can't find default public key in .ssh/authorized_keys

### ISSUE THREAD

**Issue by actg** [PowerShell/Win32-OpenSSH#870]
Version:
         win32-openssh 7.5 P1
windows platform version:
         windows 10 Ultimate

1. sshd_config configure default authorized_keys file in .ssh/ folder
AuthorizedKeysFile    .ssh/authorized_keys

2. When client ssh login to server,but the server Permission denied, and sshd.log file present following logs:

8708 14:23:49:580 debug1: trying public key file C:\\WINDOWS\\.ssh/authorized_keys
8708 14:23:49:580 Authentication refused.

3. Why don't load default authorized_keys in C:\Users\user\\.ssh folder? I have been perform FixHostFilePermissions.ps1 in powershell dialog as Administrator.What's wrong with me?

**Comment by bagajjal** [comment]
@248668342 - 
authorized_keys is a file (not a folder). 
When sshd_config has an explicity AuthorizedKeysFile specified, sshd process will never look into C:\Users\user/.ssh folder.
FixHostFilePermissions.ps1 - This will not fix you AuthorizedKeysFile specified in the sshd_config. Please do this manually... Follow these steps,
a) right click authorized_keys file.
b) security tab
c) Advanced button
d) permissions tab
e) Make sure Owner field is set to "system" or "administrators group"
f) Permission entries has "system", "administrators group" and sshd (Read only) permission.
 
finally your authorized_keys advanced security settings should look like this, it could be owner by the user, SYSTEM or Administrators group

![image](https://user-images.githubusercontent.com/23668037/29851766-e5ad02aa-8cea-11e7-899c-6f0a688cee22.png)

**Comment by JW0914** [comment]
authorized_keys should only be accessible by the user and sshd.
 - **_%USERPROFILE%\\.ssh\\authorized_keys_**
     - ```
       NT SERVICE\sshd:(R)
       WRT\JW0914:(F)
       ```
        - ```icacls %USERPROFILE%\.ssh\authorized_keys /grant `"NT SERVICE\sshd`":`(R`)```
```icacls %USERPROFILE%\.ssh\authorized_keys /grant `"WRT\JW0914`":`(F`)```

**Comment by JW0914** [comment]
@248668342 @bagajjal  authorized_keys should only be accessible by the _user_ and _sshd_, and should be owned by the user, **_not_** NT AUTHORITY/SYSTEM or BUILTIN\Administrators.
 - **_%USERPROFILE%\\.ssh\\authorized_keys_**
   ```
   NT SERVICE\sshd:(R)
   WRT\JW0914:(F)
   ```
   - Remove all inheritance for .ssh and all files contained within _(Properties -> Security -> Advanced)_
      - Remove all users but the signed in user, then: 
        - ```icacls %USERPROFILE%\.ssh\authorized_keys /grant `"NT SERVICE\sshd`":`(R`)```
```icacls %USERPROFILE%\.ssh\authorized_keys /grant `"WRT\JW0914`":`(F`)```
          - Where _WRT\JW0914_ is the user

### Correct Permissions structure for files/directories within _%UserProfile%\\.ssh_:

- **NOTE:**
   - **%UserProfile%\\.ssh**, and all files/directories within, should _**not**_ have inherited permissions.
      - Unless the user is the only one being passed for inheritance
      - User should be the owner of _%UserProfile%\\.ssh_ and all files/directories within
   - **%ProgramFiles%\\OpenSSH\\ssh_host_*_key**
      - [`PsExe`](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec) should be utilized to register the server keys as _NT AUTHORITY\SYSTEM_ (_[halfway down](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH)_)
     - [`sdelete`](https://docs.microsoft.com/en-us/sysinternals/downloads/sdelete) should be used to securely erase them _(5 pass minimum)_ once registered
- **_%ProgramFiles%\\OpenSSH\\ssh_config_**
       ```
       NT AUTHORITY\SYSTEM:(F) |
       BUILTIN\Administrators:(F) |
       NT SERVICE\sshd:(R)
       ```
     - ```icacls %ProgramFiles%\OpenSSH\sshd_config /grant `"NT AUTHORITY\SYSTEM`":`(F`)```
```icacls %ProgramFiles%\OpenSSH\sshd_config /grant `"BUILTIN\Administrators`":`(F`)```
```icacls %ProgramFiles%\OpenSSH\sshd_config /grant `"NT SERVICE\sshd`":`(R`)```
- **_%ProgramFiles%\\OpenSSH\\sshd_config_**
       ```
       NT AUTHORITY\SYSTEM:(F) |
       BUILTIN\Administrators:(F) |
       NT SERVICE\sshd:(R)
       ```
     - ```icacls %ProgramFiles%\OpenSSH\sshd_config /grant `"NT AUTHORITY\SYSTEM`":`(F`)```
```icacls %ProgramFiles%\OpenSSH\sshd_config /grant `"BUILTIN\Administrators`":`(F`)```
```icacls %ProgramFiles%\OpenSSH\sshd_config /grant `"NT SERVICE\sshd`":`(R`)```
- **_%UserProfile%\\.ssh_**
       ```
       WRT\JW0914:(F)
       ```
     - ```icacls %UserProfile%\.ssh /grant `"WRT\JW0914`":`(F`)```
- **_%UserProfile%\\.ssh\\authorized_keys_**
       ```
       NT SERVICE\sshd:(R) |
       WRT\JW0914:(F)
       ```
     - ```icacls %UserProfile%\.ssh\authorized_keys /grant `"NT SERVICE\sshd`":`(R`)```
```icacls %UserProfile%\.ssh\authorized_keys /grant `"WRT\JW0914`":`(F`)```
- **_%UserProfile%\\.ssh\\config_**
       ```
       WRT\JW0914:(F)
       ```
     - ```icacls %UserProfile%\.ssh\config /grant `"WRT\JW0914`":`(F`)```
- **_%UserProfile%\\.ssh\\known_hosts_**
       ```
       WRT\JW0914:(F)
       ```
     - ```icacls %UserProfile%\.ssh\known_hosts /grant `"WRT\JW0914`":`(F`)```
- **_~/.ssh_**
   ```
   [root@LEDE] /home/jw # ls -lsa .ssh
       0 drwx------    1 jw       jw             368 Sep 10  2017 .
       4 -rw-------    1 jw       jw            2254 Sep 10  2017 authorized_keys
       8 -rw-------    1 jw       jw            6699 Sep 10  2017 config
       0 -rw-------    1 jw       jw               0 Sep 10  2017 known_hosts
   ```

**Comment by manojampalam** [comment]
8708 14:23:49:580 debug1: trying public key file C:\WINDOWS\.ssh/authorized_keys
8708 14:23:49:580 Authentication refused.

This implies that loading of user profile might have failed (OpenSSH defaults to c:\windows if user profile cannot be loaded). Can you check ssh-agent logs ?

**Comment by manojampalam** [comment]
Reopen if needed.

**Comment by dermeister0** [comment]
@JW0914 
The sshd service created by install-sshd.ps1 runs under Local System account. Possibly the sshd user is not used.

That's why we need to grant permissions to `Administrators` group.

```
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.4
```

**Comment by JW0914** [comment]
With current version and going forward, there should only be two users with access permissions to `%UserProfile%\.ssh\authorized_keys`: 
* The owning user
* NT SYSTEM

![screenshot](https://user-images.githubusercontent.com/8009181/48713635-7a2b8000-ebd6-11e8-91d0-3bbfac7c0c62.png)
