### ISSUE TITLE
Possibility to disable VT-100 sequences coming from server

### ISSUE THREAD

**Issue by lumean** [PowerShell/Win32-OpenSSH#871]
Hi 

I'm running the SSH server version `0.0.19.0` on Windows 10 Professional and I'm looking for a way to disable the VT-100/xTerm control Sequences in the stdout which I get from the server.

I'm using a ruby ssh client to automate some interactive cli commands in an "expect" way.
e.g. when I want to execute the `dir` command I get an output as follows:
****
``` 
c:\>                                                                                           [9;38H[9;38H[9;38Hd                                                                                          [9;39H[9;39Hi                                                                                         [9;40H[9;40Hr                                                                                        [9;41H[9;41H

```

Whereas I would expect something like
```
c:\>dir
```

**Comment by manojampalam** [comment]
you can disable server side PTY by using -T flag.
ssh -T

**Comment by lumean** [comment]
Thanks, worked perfectly
