### ISSUE TITLE
fg command fails for nano

### ISSUE THREAD

**Issue by SilentSpud** [PowerShell/Win32-OpenSSH#875]
**"OpenSSH for Windows" version**
Version 0.0.20.0
 
**Server Operating System**
Ubuntu Server 17.04 x64

**Client Operating System**
Windows 10 Pro x64

**What is failing**
Using the `fg` command to bring a background `nano` process back to foreground.

**Expected output**
The editor reopens.

**Actual output**
The console flickers between nano and a blank screen

**Comment by bagajjal** [comment]
@reap3r119 - I couldn't repro this issue.. is it working with other ssh clients like putty/Cygwin?
FYI, please see the recording.. I tried three times, it works perfectly 
![nano-fg-norepro](https://user-images.githubusercontent.com/23668037/30129396-a279e776-92fa-11e7-88e0-fc5f76e1727b.gif)

**Comment by SilentSpud** [comment]
It only happens when using ConEmu with its hooks enabled. Trying this in Command Prompt works fine, as does ConEmu with the hooks disabled

**Comment by bagajjal** [comment]
@reap3r119 - Please provide the reproduction steps...
Also did you try this from other ssh clients like putty/Cygwin? if yes, does it behaves correctly?

**Comment by SilentSpud** [comment]
Enable `Inject ConEmuHk` under Features in ConEmu's settings, open a new console and connect to the ssh server, run `nano somefile`, stop it with `Ctrl+Z`, then use `fg` to bring it back to the foreground.

I've tried it with putty, kitty and cygwin, and it works just fine in all of them. I also tried it on a 32-bit Win10 machine, and it does the same thing.

**Comment by bagajjal** [comment]
@reap3r119 - I tried as you said but couldn't repro this issue..
please have a look at this,
![nano-issue1](https://user-images.githubusercontent.com/23668037/30181225-6c577b18-93c7-11e7-8816-772d445d7002.gif)


Let me know if I miss something.

**Comment by bagajjal** [comment]
@reap3r119 - Any update on this? Can you try on a different machine?

**Comment by SilentSpud** [comment]
I tested it with a fresh install of ubuntu server, and I'm not encountering the same issue any more. I'll look more into what's different when I get back

**Comment by bagajjal** [comment]
Thank you.. I'm closing this issue.
