### ISSUE TITLE
Window server 2016 can't start ssh-agent service

### ISSUE THREAD

**Issue by liurui39660** [PowerShell/Win32-OpenSSH#877]
**"OpenSSH for Windows" version**
0.0.20.0
 
**Server OperatingSystem**
Windows Server 2016 Datacenter

**Client OperatingSystem**
None

**What is failing**
Failed to start `ssh-agent `service

**Expected output**
The `ssh-agent` service starts successfully, thus `sshd` can start

**Actual output**
An error when starting `ssh-agent` service
>Error 1053: The service didn't respond to the start or control request in a timely fashion.

Therefore, `sshd` can't start

**Comment by bagajjal** [comment]
Please share the ssh-agent DEBUG3 logs

**Comment by liurui39660** [comment]
Only one line
>agent_start pid:9000, dbg:1

Then, nothing happened, ssh-agent didn't exit but keep running. 
However, while it is running, `sshd` service is still unavailable, it returns the same error as before:
>Error 1068: The dependency service or group failed to start.

**Comment by manojampalam** [comment]
Try doing this interactively - 
ssh-agent -d

**Comment by liurui39660** [comment]
There is something strange: after doing some `ssh-agent -d` , `ssh-agent -ddd` and some `Ctrl+C`, the `ssh-agent` service is able to start, `sshd` is also available.

The only thing I did after last post is trying to install `freeSSHd` and `freeFTPd`, both of them are setup successfully, the former occupied port 22, and the latter occupied port 20 (I assigned it). I shut them down before I tried `ssh-agent -d`.

What I did:
- Try to install `freeSSHd` and `freeFTPd`
- Idle for 4 or 5 hours (the server is under testing, so no one use it except me)
- Open a new Powershell session
- `ssh-agent -d`, it returned
>agent_start pid:9656, dbg:1

and keep running, nothing happened
- `Ctrl+C`, it stopped and returned
>debug1: shutting down

- `ssh-agent -ddd`, returned
>agent_start pid:4820, dbg:1

it is also OK, nothing happened
- `Ctrl+C`, returned
>debug3: Ctrl+C received

then it stuck, it didn't show `PS C:\Users\Administrator>` as usual

- Click the `X` to close the session forcely
- Open a new Powershell session
- `ssh-agent`, seemed successful, and showed `PS C:\Users\Administrator>`, but in the past, it returns an error (1053) instead
- Open `serices.msc`, tried to start `ssh-agent` service, succeeded
- Start `sshd`, succeeded

I have no idea what happened on it, since I can't reboot the server, I can't reproduce the problem again. May be I should temporarily close the issue until next it goes wrong.
