### ISSUE TITLE
Diff between Win10 IoT SSH and this project

### ISSUE THREAD

**Issue by shooshoomo** [PowerShell/Win32-OpenSSH#88]
Stumbled upon this the other day. https://ms-iot.github.io/content/en-US/win10/samples/SSH.htm 

Does anyone know the difference between these and the implications to this project if SSH is already shipping with Win 10 IoT core?

**Comment by manojampalam** [comment]
The one in IoT core is a version implemented by Microsoft specifically to fill in certain immediate gaps in Developer experience scenarios. Long term goal is to replace it with OpenSSH version.
