### ISSUE TITLE
PSReadline misaligned output

### ISSUE THREAD

**Issue by nkrepo** [PowerShell/Win32-OpenSSH#881]
**"OpenSSH for Windows" version**
0.0.20.0

**OS details**
Microsoft Windows 10 Pro 64-bit 10.0.15063 (Creators Update)

**What is failing**
When tab is pressed to provide autocomplete for the cmdlet's parameters, the output is misaligned. 

**Expected output**
For example when PSReadline module is loaded and tab is pressed after "ls -":
![image](https://user-images.githubusercontent.com/8989693/30310801-fcf617f2-979a-11e7-91a9-9e293c8c9158.png)

**Actual output**
Started powershell's terminal connected to localhost via sshd and started powershell at the command prompt.
The output when tab is pressed after "ls -" is:
![image](https://user-images.githubusercontent.com/8989693/30310837-2a145e10-979b-11e7-8fa1-a3eb6af2d7f5.png)
The "Screen buffer Size Width" was set equal to "Window Size Width" before connecting though ssh to localhost.

**Comment by gravcat** [comment]
Dropping this here in case your issue is more relevant there

https://github.com/PowerShell/PSReadLine

**Comment by bagajjal** [comment]
@gravcat - This is because of "https://github.com/PowerShell/Win32-OpenSSH/issues/590".
I am closing this issue as duplicate.

You can verify this by starting the sshd in the debug mode 
a) net stop sshd
b) .\sshd.exe -ddd

Now start a ssh session...

**Comment by gravcat** [comment]
@bagajjal not my issue just trying to help out! @nkrepo see above.
