### ISSUE TITLE
libssh2 SFTP Upload Failure

### ISSUE THREAD

**Issue by necouchman** [PowerShell/Win32-OpenSSH#883]
**"OpenSSH for Windows" version**
0.0.20.0
 
**Server OperatingSystem**
Windows 10 Enterprise

**Client OperatingSystem**
Guacamole/libssh2/Linux

**What is failing**
File uploads

**Actual output**
Unable to open file <filename>

**Description**
The application we are using leverages the libssh2 library for SSH and SFTP connections.  It works fine against other UNIX-based SSH servers for uploading files (Linux, FreeBSD, AIX, Solaris), and works fine if I download and install the SolarWindows SFTP/SCP server, but fails against the Microsoft OpenSSH implementation.  A user on the mailing list traced it to this line of code:

https://github.com/libssh2/libssh2/blob/819ef4f2037490b6aa2e870aea851b6364184090/src/sftp.c#L1060

Changing this from:

`attrs.permissions = mode |
            (open_file ? LIBSSH2_SFTP_ATTR_PFILETYPE_FILE :
             LIBSSH2_SFTP_ATTR_PFILETYPE_DIR);`

to:

`attrs.permissions = mode`

Allows the file to upload successfully, so it seems to be something about trying to open the file as a file vs. directory and the ability of the sftp-server subsystem to handle it on Windows.

Here are the log entries from the sftp-server.log file:

`
14272 11:42:48:925 debug3: request 25: open flags 26
14272 11:42:48:925 open "/C:/Users/Administrator/Desktop/brainpinky.png" flags WRITE,CREATE,TRUNCATE mode 0100600
14272 11:42:48:925 debug3: open - ERROR: unsupported mode: 33152
14272 11:42:48:925 debug3: createFile_flags_setup() failed.
14272 11:42:48:925 debug3: request 25: sent status 4
14272 11:42:48:925 sent status Failure
`

Please let me know if I can provide any further information.

**Comment by gassman** [comment]
Looking into this a bit, the Linux open() function supports a number of mode bit including:

File Permissions
```
S_IRWXU  00700 user (file owner) has read, write, and execute permission
S_IRUSR  00400 user has read permission
S_IWUSR  00200 user has write permission
S_IXUSR  00100 user has execute permission
S_IRWXG  00070 group has read, write, and execute permission
S_IRGRP  00040 group has read permission
S_IWGRP  00020 group has write permission
S_IXGRP  00010 group has execute permission
S_IRWXO  00007 others have read, write, and execute permission
S_IROTH  00004 others have read permission
S_IWOTH  00002 others have write permission
S_IXOTH  00001 others have execute permission
```

File Type
```
/* File types.  */
#define __S_IFDIR       0040000 /* Directory.  */
#define __S_IFCHR       0020000 /* Character device.  */
#define __S_IFBLK       0060000 /* Block device.  */
#define __S_IFREG       0100000 /* Regular file.  */
#define __S_IFIFO       0010000 /* FIFO.  */
#define __S_IFLNK       0120000 /* Symbolic link.  */
#define __S_IFSOCK      0140000 /* Socket.  */
```
The file type maps to the libssh2 SFTP constants for:
```
/* S_IFREG */
#define LIBSSH2_SFTP_ATTR_PFILETYPE_FILE        0100000
/* S_IFDIR */
#define LIBSSH2_SFTP_ATTR_PFILETYPE_DIR         0040000
```
So I am wondering if the open() library function used by OpenSSH here is honouring these file types.

**Comment by manojampalam** [comment]
We'll fix this for Oct-Mid drop.
