### ISSUE TITLE
Uploaded files have no delete permission

### ISSUE THREAD

**Issue by Valdaun** [PowerShell/Win32-OpenSSH#884]
**"OpenSSH for Windows version**

Brand new latest version using the Choco installer method 1b (super slick btw, install worked 100% perfectly as a single copy/paste line):

Progress: Downloading openssh **0.0.20.20170913**... 100%

openssh v0.0.20.20170913 [Approved]
openssh package files install completed. Performing other installation steps.
Running on: Windows Server 2012 R2 Standard, (ServerStandard)
Windows Version: 6.3.9600

**Client OperatingSystem**

Windows 10 - FileZilla, WinSCP

**What is failing**

I previously updated a closed ticket (#876) as this is similar to what that person was experiencing, but not sure what the guidelines are on responding to closed tickets so I thought I would make a new issue more specific to the exact thing causing this otherwise awesome software to not be workable in my environment.

The gist is that files uploaded, no matter from what client seemingly, are only granted baseline read/write permissions under windows and do not include execute nor most importantly, delete:

![image](https://user-images.githubusercontent.com/8713530/30496147-8a3ed56c-9a1c-11e7-81d3-188009cf1d0e.png)

This means even right after uploading a file, clients are unable to delete them:

![image](https://user-images.githubusercontent.com/8713530/30496197-ab9a4688-9a1c-11e7-8ff8-1d706d7d5896.png)

Nor can they rename them:

![image](https://user-images.githubusercontent.com/8713530/30496225-bf58659c-9a1c-11e7-8bad-12e49c2e5cdd.png)

**Expected output**

I would expect any file a user can upload should have all permissions except for Full Control so that clients can fully utilize any of the SCP or SFTP software to manage files on the target system.   It would be acceptable to rely on inheritance as well.  Creating sub directories does inherit permissions, however uploading files or creating them from the client runs into this permission problem.

Here is a screenshot of a file that was created from FileZilla by right clicking in the target folder and choosing to create a new file:

![image](https://user-images.githubusercontent.com/8713530/30496424-568143f8-9a1d-11e7-9ee3-7ea5ea407223.png)

**Comment by Valdaun** [comment]
One other thing I thought to try right after was to see if using an SSH client alone and creating files once logged in would have any issues.   I connected using PuTTY as the same test user, and ran the following to create a directory and then a single text file:

![image](https://user-images.githubusercontent.com/8713530/30496796-8fc10184-9a1e-11e7-9c0e-72fe8e04c1b4.png)

Both the folder and the file in this case have expected permissions, that being that they keep the inheritance from whatever folder they were created inside of:

![image](https://user-images.githubusercontent.com/8713530/30496842-b02f36ac-9a1e-11e7-8226-45ed77f59b33.png)

So this issue does seem specific to the SFTP handling side of things.

**Comment by Valdaun** [comment]
One last update ... I was able to implement a workaround by granting that local account "cisco" membership in the local "Administrators" group (which gets assigned full control permission).   This is not ideal, as it violates the concept of least privilege but it did allow me to proceed and use this for now which I'm happy about.  Hopefully the underlying issue can be resolved at some point, however.

Thanks!

**Comment by bagajjal** [comment]
@Valdaun - Thanks for reporting the issue. We will target the fix for the next release.
