### ISSUE TITLE
sshd doesn't support meta keys

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/Win32-OpenSSH#886]
sshd doesn't support meta keys like alt+a, alt+shift+a, ctrl+alt+shift+a, etc.

**Comment by nkrepo** [comment]
Hi bagajjal,  will the "ctrl+space" be also supported? It is related to PsRealine #686.

**Comment by bagajjal** [comment]
There is no control sequence for sending "ctrl + space" from client to server 
You can change powershell keyboard shortcut 
Set-PSReadlineKeyHandler -Key Tab -Function Complete
https://github.com/lzybkr/PSReadLine

**Comment by bagajjal** [comment]
This is fixed and code changes are submitted.
Please check the September end release.
