### ISSUE TITLE
Incompatible SSH 

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#887]
Tried the latest build of SSH-Win64 connecting to a remote device
ssh UserName@xxx.xxx.xxx.xxx

And get the following error:
Unable to negotiate with xxx.xxx.xxx.xxx port 22: no matching cipher found. Their offer: aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc

While running ssh using putty worked well.

**Comment by bagajjal** [comment]
Please share the ssh logs (ssh.exe -vvv user@ip)

**Comment by ghost** [comment]
OpenSSH_7.5p1, LibreSSL 2.5.3
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/config error:2
debug3: Failed to open file:./ssh_config error:2
debug2: resolving "11.170.208.41" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 11.170.208.41 [11.170.208.41] port 22.
debug3: socket:352, socktype:1, io:0000015929F7A4F0, fd:3
debug1: Connection established.
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_rsa error:2
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_rsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\currentWinUser/.ssh/id_rsa type -1
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_rsa-cert error:2
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_rsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\currentWinUser/.ssh/id_rsa-cert type -1
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_dsa error:2
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_dsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\currentWinUser/.ssh/id_dsa type -1
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_dsa-cert error:2
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_dsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\currentWinUser/.ssh/id_dsa-cert type -1
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_ecdsa error:2
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_ecdsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\currentWinUser/.ssh/id_ecdsa type -1
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_ecdsa-cert error:2
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_ecdsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\currentWinUser/.ssh/id_ecdsa-cert type -1
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_ed25519 error:2
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_ed25519.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\currentWinUser/.ssh/id_ed25519 type -1
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_ed25519-cert error:2
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/id_ed25519-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\currentWinUser/.ssh/id_ed25519-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.5
debug1: Remote protocol version 2.0, remote software version SSH_2.0
debug1: no match: SSH_2.0
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 11.170.208.41:22 as 'remoteSSHUser'
debug3: hostkeys_foreach: reading file "C:\\Users\\currentWinUser/.ssh/known_hosts"
debug3: Failed to open file:C:\\Users\\currentWinUser/.ssh/known_hosts2 error:2
debug3: Failed to open file:./ssh_known_hosts error:2
debug3: Failed to open file:./ssh_known_hosts2 error:2
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: ssh-dss,ssh-rsa
debug2: ciphers ctos: aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: hmac-sha1,hmac-md5
debug2: MACs stoc: hmac-sha1,hmac-md5
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: diffie-hellman-group-exchange-sha1
debug1: kex: host key algorithm: ssh-rsa
Unable to negotiate with 11.170.208.41 port 22: no matching cipher found. Their offer: aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc

**Comment by manojampalam** [comment]
Client supported
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr

and server supported
debug2: ciphers ctos: aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc

Negotiation fails because there isn't a matching cipher. 

You either need to enable cbc ciphers on client 
      ex. ssh -c aes256-cbc
or ctr ciphers on your target (check sshd_config man page)
