### ISSUE TITLE
Support ssh-copy-id script

### ISSUE THREAD

**Issue by StefanScherer** [PowerShell/Win32-OpenSSH#89]
I recently tried OpenSSH-Win64 on a Win2016TP4 at Azure and thought I can use the `ssh-copy-id` scripts from a Linux/Mac machine to insert my SSH public key.

```
$ ssh-copy-id docker@docker-tp4.northeurope.cloudapp.azure.com
/usr/local/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/local/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
docker@docker-tp4.northeurope.cloudapp.azure.com's password: 
packet_write_wait: Connection to 1.2.3.4: Broken pipe
```

Any chance to get this working? Would be really great to work between different OS'es.

( http://www.lindonslog.com/linux-unix/ssh-keygen-keys/ )

**Comment by manojampalam** [comment]
Stefan, that would be a question to ssh-copy-id owners :). It would need to have conditional logic to differentiate target OS and have the equivalent batch commands to do the id transfer.

**Comment by Rondom** [comment]
While it is in the contrib-directory, the script is strictly speaking still part of the OpenSSH-codebase and it would be nice if the script
* could support copying keys to windows hosts
* was shipped with OpenSSH for Windows

EDIT: Ok, I see it is implemented in Shell, so not easy to ship. I also found the discussion #341 which tracks this issue and your reasoning behind not supporting it.
