### ISSUE TITLE
fatal: ERROR. Cannot create process (2).\n

### ISSUE THREAD

**Issue by itsupport-iattc** [PowerShell/Win32-OpenSSH#890]
Please answer the following

**"OpenSSH for Windows" version**
 Cannot get `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)` to work. File version from sshd.exe is 0.0.20.0
 
**Server OperatingSystem**
Cannot get this command to work, either `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`  Using Windows Server 2012 R2

**Client OperatingSystem**
Windows 10

**What is failing**
The client (Filezilla) fails as follows:
Status:	Connecting to <server FQDN>...
Response:	fzSftp started, protocol_version=8
Command:	open "<username>" 22
Command:	Pass: ******************
Error:	Network error: Software caused connection abort
Error:	Could not connect to server

The log on the server reads:
1416 14:16:39:499 Server listening on :: port 22.
1416 14:16:39:499 Server listening on 0.0.0.0 port 22.
5984 14:16:48:711 Accepted password for <username><client IP address> port 7167 ssh2
5984 14:16:48:851 fatal: ERROR. Cannot create process (2).\n

**Expected output**
Would like connections to work.

**Actual output**
See above.

Already tried:
- Fixing host file permissions.
- Verified NT SERVICE\SSHD virtual account has Log on as service and Replace a process level token rights.

Thanks in advance.

[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1323052/sshd_config.txt)

**Comment by bagajjal** [comment]
Please share 
1) sshd.log with DEBUG3 logs (add LOGLEVEL DEBUG3 in sshd_config).
2) output of the powershell command
icacls C:\OpenSSH-Win\sftp-server.exe

**Comment by itsupport-iattc** [comment]
Here you go:

PS C:\OpenSSH-Win64> icacls .\sftp-server.exe
.\sftp-server.exe NT AUTHORITY\SYSTEM:(I)(F)
                  BUILTIN\Administrators:(I)(F)
                  IATTC01\mlopez:(I)(F)
                  NT SERVICE\sshd:(I)(M)
[sshd.log.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1325177/sshd.log.txt)


Successfully processed 1 files; Failed processing 0 files

**Comment by bagajjal** [comment]
Sftp-server runs in the user space...

FTPUser1 doesn't have the permissions to read & execute Sftp-server..

Provide the access (read & execute) to everyone

**Comment by manojampalam** [comment]
Cannot create process (2).

(2) indicates  - FILE NOT FOUND. 
Can you double check that both sshd and sftp-server.exe are located in the same directory?


I see 2 different directories in discussion above: C:\OpenSSH-Win64 and C:\OpenSSH-Win

**Comment by itsupport-iattc** [comment]
Bingo. Had to update the Subsystem path for sfttp to C:\OpenSSH-Win64 . I think the reason for this is that installed the 32 bit version first, then uninstalled it and installed the 64 bit version. Seems the uninstall script doesn't clean everything up.

Thanks,

M.
