### ISSUE TITLE
Firewall Rules for OpenSSH

### ISSUE THREAD

**Issue by tarmizee** [PowerShell/Win32-OpenSSH#900]
Dear Expert,

Thanks for develop the OpenSSH tools. Seeking your advice for the firewall rules. I understand that ssh will require port 22. I noticed that when the source system trying to establish ssh connection to target system, additional port is required which generated dynamically. Below is the error that I received:

4076 10:10:49:923 Could not write ident string to 127.0.0.1 port 64857
840 10:12:34:671 error: Couldn't create pid file "./sshd.pid": Permission denied
840 10:12:34:671 WARNING: could not open ./moduli (No such file or directory), using fixed modulus
840 10:12:38:820 Connection closed by 192.168.41.112 port 64880
3876 10:13:50:398 Received signal 8; terminating.
1304 10:14:11:635 Server listening on :: port 22.
1304 10:14:11:635 Server listening on 0.0.0.0 port 22.
1304 10:14:11:635 error: Couldn't create pid file "./sshd.pid": Permission denied

What is the correct firewall rules that we should implement in order to ensure the ssh is working ?

Thanks in advance for the advice.
Tarmizee

**Comment by manojampalam** [comment]
As per https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH in wiki
`netsh advfirewall firewall add rule name=SSHPort dir=in action=allow protocol=TCP localport=22`
