### ISSUE TITLE
How to add an SSH only user on Windows?

### ISSUE THREAD

**Issue by codearoo** [PowerShell/Win32-OpenSSH#901]
I just installed openssh 0.0.21.0 via Chocolatey on Win2012 and configured it. I tested it out with an Admin account and it works fine. But I wanted to create a user so that I can connect in SSH and open some tunnels. But when trying to SSH with that user, I get "Access denied".
Since I created the user, there is no c:\users\xxx folder for that user yet. I imagine I would have to actually log in as that user (but this is a remote VM so I'd have to allow that permission first).. but just wondering if there is a more systematic way to do this.. if indeed that is the problem. Because it wouldn't be able to find or create any  .ssh folder for the user.

**Comment by manojampalam** [comment]
related to https://github.com/PowerShell/Win32-OpenSSH/issues/478
you can login using that user's password over SSH (this will automatically create user's profile).

**Comment by codearoo** [comment]
I can't. That's why I made this ticket. When I try to log in with that user over SSH, I get "Permission denied, please try again."  (this time tested from the local server itself.)

**Comment by codearoo** [comment]
oh crap! It was a typo in the darn password!!
<smack in the face>  Sorry.
