### ISSUE TITLE
shell-host.c sometimes attempts to emulate interactive features in non-PTY mode

### ISSUE THREAD

**Issue by djsweet** [PowerShell/Win32-OpenSSH#903]
**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

This is not a terminal issue, but rather non-pty channels attempting to emulate a pty.

**"OpenSSH for Windows" version**
Build 0.0.21.0 (as recent as 727329abd4e471fc795331c801b65738a0cb849b)

 **Server OperatingSystem**
Server on Windows 10 Pro and Windows 7 Professional

**Client OperatingSystem**
Seen on macOS 10.12 SSH client, [Paramiko 2.x](http://www.paramiko.org) on macOS and Linux, and the SSH client as part of Win32-OpenSSH

**What is failing**
Given the command (in PowerShell)

```
echo "echo `"Hello, World!`"" | ssh $TARGET cd `%SYSTEMROOT`% `&`& powershell -Command -
```

**Expected output**
```
Hello, World!
```

**Actual output**
```
echo "Hello, World!"
Hello, World!
```

which is a result of `shell-host.c` sending the input buffer back over `stdout` when encountering a newline. Additionally, `shell-host.c` tries to emulate backspace and tab behavior when transferring remote `stdin` input to the target process: This may be the root cause of #893.

See [openssh-portable PR 218](https://github.com/PowerShell/openssh-portable/pull/218) for a potential patch, which removes all attempts to emulate interactive features in a non-pty channel.

**Comment by manojampalam** [comment]
Non-PTY logic is now completed removed from shellhost.
