### ISSUE TITLE
SCP windows source path with wildcard * does not work after version 0.0.2.0

### ISSUE THREAD

**Issue by vcarluer** [PowerShell/Win32-OpenSSH#904]
Please answer the following

**"OpenSSH for Windows" version**
 0.0.3.0 => 0.0.21.0
 
**Server OperatingSystem**
CentOS release 6.8 (Final)

**Client OperatingSystem**
  Docker container: Windows Server 2016 Datacenter

**What is failing**
scp with windows source path containing wildcard *
ex: scp .\tmp\* sharefs:~

**Expected output**
Copy all files to server without directory tmp
Version 0.0.2.0:
debug1: Entering interactive session.
debug1: Sending command: scp -v -r -t ~/unc
**Sink: C0644 16 test
test                      |          0 KB |     0.0 kB/s | 00:00:000 | 100%**
debug1: close - io:00000299973BD7F0, type:2, fd:4, table_index:4
debug1: close - io:00000299973BD270, type:2, fd:5, table_index:5
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
debug1: close - io:00000299973E8870, type:2, fd:6, table_index:6
Transferred: sent 3496, received 2944 bytes, in 0.2 seconds
Bytes per second: sent 16489.4, received 13885.8
debug1: Exit status 0

**Actual output**
...
Version 0.0.21.0:
debug1: Entering interactive session.
debug1: pledge: network
debug1: Sending command: scp -v -r -t ~/unc
**./tmp/*: Protocol not available**
Sink: ╔scp: ./tmp/*: Protocol not available
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 3040, received 2912 bytes, in -7.0 seconds
debug1: Exit status 1
...

Version 0.0.3.0: 
...
debug1: Entering interactive session.
debug1: Sending command: scp -v -r -t ~/unc
**.\tmp\*: Unknown error**
debug1: close - io:00000201E756E510, type:2, fd:4, table_index:4
debug1: close - io:00000201E7596D10, type:2, fd:5, table_index:5
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
debug1: close - io:00000201E7596DC0, type:2, fd:6, table_index:6
Transferred: sent 3384, received 2832 bytes, in 0.2 seconds
Bytes per second: sent 16668.7, received 13949.7
debug1: Exit status 0
...

**Comment by doggy8088** [comment]
@manojampalam Is there any workaround for this bug at this time?

**Comment by manojampalam** [comment]
@bingbing8 is this expected to work?

**Comment by doggy8088** [comment]
@manojampalam I can use wildcard ( * ) in the WSL or in the Linux shell.   Such as `scp * user@myhost:`.

**Comment by jasonblewis** [comment]
does this merge fix the issue? and if so, any chance of a release?

**Comment by manojampalam** [comment]
We should have one end of this week. If you'd like to test a private, let us know.

**Comment by bingbing8** [comment]
@jasonblewis, please try this private scp binary.
[scpx64.zip](https://github.com/PowerShell/Win32-OpenSSH/files/1849361/scpx64.zip)
