### ISSUE TITLE
key based auth does not after merge from upstream

### ISSUE THREAD

**Issue by bingbing8** [PowerShell/Win32-OpenSSH#905]
Please answer the following
**"OpenSSH for Windows" version**
 0.0.21.0
 
**Server OperatingSystem**
 Win10

**Client OperatingSystem**
 Win10
**What is failing**
key auth does not after merge from upstream

**Expected output**
key auth works

**Actual output**
key auth fail and fall back to pass auth

**Comment by bingbing8** [comment]
this should be fixed in upstream. [issue 2790](https://bugzilla.mindrot.org/show_bug.cgi?id=2790) to track it.

**Comment by manojampalam** [comment]
Reverted original change as authentication logic is moved to sshd and this check is no longer relevant
