### ISSUE TITLE
Service 'sshd (sshd)' cannot be started but sshd.exe runs from command line

### ISSUE THREAD

**Issue by dheater** [PowerShell/Win32-OpenSSH#907]
Please answer the following

**"OpenSSH for Windows" version**

0.0.21.0

**Server OperatingSystem**

Windows Server 2016 Standard

ProductName  : Windows Server 2016 Standard
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows nt\CurrentVersion\
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows nt
PSChildName  : CurrentVersion
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry

**What is failing**

sshd service fails to start

**Actual output**

PS C:\Users\dheater\Documents\OpenSSH-Win64\OpenSSH-Win64> Start-Service sshd
Start-Service : Service 'sshd (sshd)' cannot be started due to the following error: Cannot start service sshd on
computer '.'.
At line:1 char:1
+ Start-Service sshd
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

** Further details **

I can run `sshd.exe` by itself and successfully launch and ssh session from another machine. Its only starting the server that fails.

First time I installed, I was not admin.

I've uninstalled and rebooted, then reinstalled as admin. I see the `sshd` service in the service manager, but I cannot start it from Powershell (see above) or from the service manager

![image](https://user-images.githubusercontent.com/1173374/31308019-b404f268-ab34-11e7-8242-6bcf21f5e1c4.png)

Installed with instructions from here: 
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH
I did skip the optional step of securing the SSH host keys for now.

**Comment by bagajjal** [comment]
Verify the output of 
icacls sshd.exe 

Sshd service runs as "Nt service/sshd" so it should have read &execute  permissions

**Comment by dheater** [comment]
PS C:\Users\dheater\Documents\OpenSSH-Win64\OpenSSH-Win64> icacls sshd.exe
sshd.exe NT AUTHORITY\SYSTEM:(F)
         BUILTIN\Administrators:(F)
         PERF-WIN2016\dheater:(F)

Successfully processed 1 files; Failed processing 0 files

**Comment by bagajjal** [comment]
Please provide read, execute permissions  to  "authenticated users".

**Comment by dheater** [comment]
I tried piecing together how to set permissions on a service for "authenticated users".
Below is what I came up with combining information from several websites, mainly this one: https://michlstechblog.info/blog/windows-set-permissions-on-a-service/

Apparently I didn't get it right b/c its still not working.

Can you provide the command foo for setting permissions?


```
PS C:\Program Files (x86)\Windows Resource Kits\Tools> .\subinacl.exe /service sshd /grant=S-1-5-11=QSTOP
sshd : new ace for authenticated users
sshd : 1 change(s)


Elapsed Time: 00 00:00:00
Done:        1, Modified        1, Failed        0, Syntax errors        0
Last Done  : sshd
PS C:\Program Files (x86)\Windows Resource Kits\Tools> Start-Service sshd
Start-Service : Service 'sshd (sshd)' cannot be started due to the following error: Cannot start service sshd on
computer '.'.
At line:1 char:1
+ Start-Service sshd
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
```

**Comment by bagajjal** [comment]
Get the properties of sshd.exe and in the security tab add the permissions..

**Comment by dheater** [comment]
Granted "Full control" to all authenticated users

![image](https://user-images.githubusercontent.com/1173374/31316416-683ebb5c-abf2-11e7-965d-bf6114c916ba.png)



Still had the same problem so I uninstalled and reinstalled. Still had the same problem.

**Comment by dheater** [comment]
I changed the `sshd` service "Log On" From:

![image](https://user-images.githubusercontent.com/1173374/31316402-29804dcc-abf2-11e7-9cd0-ad980711cbc7.png)

To:

![image](https://user-images.githubusercontent.com/1173374/31316474-d3efb9d6-abf3-11e7-97f8-8d7886767203.png)

and know I'm able to start the service.

**Comment by dheater** [comment]
Root cause was that I extracted to the wrong directory.

Be sure to extract the `.zip` file to `c:\Program Files\OpenSSH` and it should work out of the box.

**Comment by dheater** [comment]
BTW, if you don't extract to the correct directory, even if you getting it working, ssh keys don't work correctly.

**Comment by DarwinJS** [comment]
I would love to know if you have any similar problems with the universal installer on that machine?

This oneliner should do it (installs chocolatey as well):

```set-executionpolicy RemoteSigned -Force -EA 'SilentlyContinue';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/DarwinJS/ChocoPackages/master/openssh/InstallChoco_and_openssh_with_server.ps1'))```

If you have PowerShell 5, this oneliner does it without chocolatey:
```set-executionpolicy RemoteSigned -Force -EA 'SilentlyContinue';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/DarwinJS/ChocoPackages/master/openssh/InstallChoco_and_win32-openssh_with_serverPS5.ps1'))```

Full instructions for all install methods (including offline and docker installs) are here: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/readme.md

**Comment by rebelholic** [comment]
@dheater  Already tried with your solution but still not luck for Win Server 2016. Could anyone to help me to fix this problem?

**Comment by penguinpages** [comment]
Update.. 

I will have to amend my post and document request.  I did an entire cycle of deploy on server 2022, 2019. GUI and Powershell.

Results are all the same.  Install works fine.. Documentation on install IS CORRECT... but...


Failure to start service (GUI or Powershell) fails due to ??

But.. if post install you reboot (ugh.. this is bad).. service starts fine.


As such my request would be  what service or resource needs to be touched or restarted to avoid a reboot.  These are production systems and this is not acceptable.

Adding that set of steps to documentation is now the request.



###############
means to install and start OpenSSH also has same result. So not sure total root cause but something is not deploying correct.

Error is on start of service
![image](https://github.com/PowerShell/Win32-OpenSSH/assets/17153876/4e10170b-3fcd-426a-848e-5393ae4ed6c2)


I tested on Windows 2022 and Windows 2019.   

I did  GUI un-install before re-installing via the apps and features path

![image](https://github.com/PowerShell/Win32-OpenSSH/assets/17153876/73db4937-c37f-411f-b295-fe3db4b8a414)
