### ISSUE TITLE
sshd.log rotation or size limitation

### ISSUE THREAD

**Issue by yasu1013** [PowerShell/Win32-OpenSSH#911]
**"OpenSSH for Windows" version**
0.0.21.0
 
**Server OperatingSystem**
Windows Server 2012 R2

I installed OpenSSH and it works correctly, but it seems that sshd.log monotonically increases (i.e. there is no size limit, and sshd.log is not rotated). I think this is normal operation, but I would like to avoid to impact disk space.

So, I have 2 questions:
Q1. Are there any problems by rotating (copy and clear) sshd.log without stopping sshd.exe ?
Q2. Is there a parameter in sshd_config  which limits size of sshd.log (without changing loglevel)?

thank you

**Comment by manojampalam** [comment]
Currently there is no mechanism to limit size of sshd.log. 

That said, you may wipe sshd.log clean any time (without stopping sshd service)
Powershell
`$null | Set-Content .\logs\sshd.log`
Cmdline
`: > logs\sshd.log`

**Comment by yasu1013** [comment]
@manojampalam Thank you for your reply. 
Is that same about ssh-agent.log ? (no mechanism to limit size, any time cleaning)

**Comment by bagajjal** [comment]
Yes, it is same for ssh-agent.log.

**Comment by yasu1013** [comment]
@bagajjal Thank you for quick response. I close this issue.
