### ISSUE TITLE
Open ssh service sshd starts then stops in windows server 2012 and it could not start manually

### ISSUE THREAD

**Issue by naodagere** [PowerShell/Win32-OpenSSH#912]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**

**What is failing**

**Expected output**

**Actual output**

**Comment by bagajjal** [comment]
Share the sshd.log with debug 3 logs

**Comment by manojampalam** [comment]
For more trouble shooting info - https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Comment by manojampalam** [comment]
Reopen with relevant info.
