### ISSUE TITLE
starting powershell in interactive session over shh

### ISSUE THREAD

**Issue by minodudd** [PowerShell/Win32-OpenSSH#913]
**"OpenSSH for Windows" version**
v0.0.21.0
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
raspbian 7.2

**What is failing**
Based on suggestion in https://github.com/PowerShell/Win32-OpenSSH/issues/837 I've tried starting the ssh session using either :
`ssh -t user@domain@hostname powershell` or `ssh -t user@hostname powershell`
and running
`[Environment]::UserInteractive`
to which I get the response
`False`

My actual goal is to turn my monitors off on command from the linux box. I originally tried doing that by running nircmd from the command prompt of the ssh session but that has failed as well.

**Expected output**
`True`

**Actual output**
`False`

**Comment by ariscop** [comment]
As a workaround you could use `psexec -i` to interact with a specific session, from [sysinternals](https://docs.microsoft.com/en-au/sysinternals/downloads/sysinternals-suite)

**Comment by minodudd** [comment]
I'm afraid it didn't do the trick. 
I'm still getting False for that script as well as trying to to run `nircmd.exe monitor async_off`. 
The command works locally but not over ssh even when wrapped with `psexec -i`.

Specifically I've tried it with psexec64.exe, but I doubt that's the issue.

**Comment by manojampalam** [comment]
@PaulHigin how can we launch powershell.exe without an actual terminal but still in interactive mode?

**Comment by PaulHigin** [comment]
I don't think this is PowerShell but Open-SSH starting the powershell.exe in session 0 (non-interactive session).  I am not sure how to do this via Windows API, and may not be possible for security reasons since ssh is hosting a remote connection.

**Comment by manojampalam** [comment]
ssh -t user@domain@hostname 
Above will create a remote session with IO redirected over stdin and stdout. How can we make powershell.exe operate over stdin and stdout (without a console)?

**Comment by PaulHigin** [comment]
You can make powershell.exe read from stdin by starting it with: "powershell.exe -"

**Comment by ivandeex** [comment]
@maertendMSFT There is no answer. There is no even link to answer. This issue is closed by mistake!

**Comment by ChristoWolf** [comment]
Copied from #837 for visibility:
I am experiencing the same behavior.
Despite following various related MSDN articles ([1](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7.1#set-up-on-a-windows-computer), [2](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration) and of course [3](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)) using PowerShell 5.1 at first and then PowerShell 7.1 on both the client and server machines, no remote PS session was interactive.
Works fine with WinRM though.
Of course, I tried it also explicitly using the [`-t`](https://man.openbsd.org/ssh#t) OpenSSH flag as suggested above, still no interactive session.
The same applies to [`Enter-PSSession`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/enter-pssession?view=powershell-7.1#notes).

**Comment by jathri** [comment]
Use schtasks /run /TN <task_name> from remote ssh cli to run nircmd (or anything detached from the current session) as on-demand scheduled task. Works for me :)
