### ISSUE TITLE
Improve Documentation of DefaultShellCommandOption

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#917]
The documentation at https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH and screenshot https://user-images.githubusercontent.com/23668037/31640389-f133818a-b292-11e7-8522-c2bb744eb67c.png do not give sufficient information to understand when to use DefaultShellCommandOption.

The documentation only says "option to execute non-interactive commmands." and "If you are configuring the powershell.exe/cmd.exe/bash.exe as default ssh shell then you can ignore DefaultShellCommandOption" and the screen shot shows "/c" with powershell.exe, but that seems like a cmd.exe option.

Without further information, it seems like DefaultShellCommandOption is never relevant.

Could someone please update the documentation with:
- the use cases where this configuration option would be valid 
- whether it puts a persistent limitation on what types of commands or responses give by the shell
- valid examples of current known use cases for DefaultShellCommandOption (including if they would ever be used cmd.exe and powershell.exe)  For example, is it /c for cmd.exe and -noninteractive for powershell.exe ?

**Comment by bagajjal** [comment]
DefaultShellCommandOption - This is the command option associated with the default shell.

For cmd.exe / powershell.exe it is /c. For bash.exe (WSL) it is -c.

![1](https://user-images.githubusercontent.com/23668037/31741118-1e9f83e6-b408-11e7-8127-4ed53105e98e.png)

DefaultShellCommandOption is used when user want to execute remote commands. Ex - ssh user@ip hostname.

![image](https://user-images.githubusercontent.com/23668037/31741212-53dbb534-b408-11e7-90b8-e96385c2c48c.png)

I have updated the wiki,  https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH.
Please let me know if I need to add more text.

**Comment by DarwinJS** [comment]
It is a little better - but the registry screenshot (https://user-images.githubusercontent.com/23668037/31640389-f133818a-b292-11e7-8522-c2bb744eb67c.png) is still showing a combination that:

1. you mention is unnecessary (powershell.exe with the option specified)
2. that is not the common way it is documented everywhere for powershell  (although powershell.exe does take /c as an option, everywhere on the plant it is documented as taking a dash and the full name like this "-command")

It would be nice if
1. The documentation cited an actual example of usage of this switch where it would actually be needed (aside from ones listed that don't really need it)
2. The registry screenshot matched an example of usage of this switch where it would actually be needed

If the whole registry key is a leftover from when the code didn't previously handle the defaults for powershell.exe / cmd.exe / bash.exe - then in the spirit of lean engineering, I would just remove it from the documentation and the code.  

Otherwise a known use case where it is absolutely needed would make the best example :)

If the screenshot must use an example that doesn't really need the configuration, I would change it to "cmd.exe" and "/c" or "powershell.exe" and "-command" so that it makes more sense to everyone's defacto expectations.

I would also probably change this text "- command option for the default shell."

To something like "- the switch that the configured default shell requires to execute a command and immediately exit and return to the calling process."

**Comment by ryan-r-russo** [comment]
I too find the wording confusing.  I am attempting to use Cygwin's bash.exe and going around in circles adding various options to both DefaultShell and DefaultShellCommandOption in possibly futile attempt to get my Cygwin Bash user resource files to get sourced in.   As it stands now I have no path to Cygwin's bin dir.   Based on the discussion here it seems that DefaultShellCommandOption is meant for one-time command which does not require interactive shell?

Also, if my conclusion is true, does DefaultShell allow for options following the path?
Here's a few I tried for DefaultShell:
C:\cygwin64\bin\bash.exe -i
C:\cygwin64\bin\bash.exe -
C:\cygwin64\bin\bash.exe --login

None read my Bash resources files in C:\Users\\$MYUSER
I have each type in that location that Bash normally uses as a login shell  (.basrc, .profile, .bash_profile)

**Comment by bagajjal** [comment]
DefaultShellCommandOption for cygwin is -c. DefaultShellCommandOption will take a command, executes that command and exits the shell, i.e., it is used for executing a command without opening an interactive shell.

please see the attached screenshot.
![defaultshell-cygwin](https://user-images.githubusercontent.com/23668037/32012929-54ba9626-b96e-11e7-9641-bb5c38b89ab1.png)

Your registry changes should look like,
![image](https://user-images.githubusercontent.com/23668037/32013012-91565e26-b96e-11e7-96d8-4b4dbb5bd32c.png)

Once you have those registry settings.. you will be able to login to the cygwin-bash as default shell.
![image](https://user-images.githubusercontent.com/23668037/32013106-db6eaa04-b96e-11e7-897d-010ffe99f101.png)

DefaultShellCommandOption  is used for executing remote ssh commands like hostname,
![image](https://user-images.githubusercontent.com/23668037/32013197-13b8c606-b96f-11e7-9867-0ec9e5358d9b.png)

**Comment by ryan-r-russo** [comment]
Right. I get it now.  The wording led me to believe the the separate key was for options to DefaultShell.  

I get the behavior I want with Default Shell value = C:\cygwin64\bin\bash.exe --login
and DefaultShellCommandOption unset

I was trying both but, must not have restarted after one of those attempts.

Login now sources my Cygwin user's .bashrc as expected.

As the docu. reads it sounds like you cannot have both.

Also, without DefaultShellCommandOption command **unset** I can still run remote commands like hostname  and log in interactively.

This is latest version (0.0.22.0) on Win 7 64

**Comment by bagajjal** [comment]
@DarwinJS , @ryan-r-russo - I have modified the wiki instructions (step -12). Feel free to reach out to me if it requires more readable text.

https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH
