### ISSUE TITLE
Resolve SYSTEM environment variables in "default shell path"

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#918]
I am thinking of setting a "latest version of PowerShell Core" environment variable in the PowerShell Core for Windows Chocolatey package.  Hoping that could be used in this parameter to allow SSH to simply use the latest version of PowerShell Core that was installed for this value.

**Comment by manojampalam** [comment]
This goes back to the discussion with having Environment Variables to decide on default shell. Security concerns we had with that approach would apply to this proposal too.

**Comment by parkovski** [comment]
What about generating a private key hash of the program the user designates as the default shell, and falling back to cmd.exe if the hash doesn't match? It seems like that would provide maximum flexibility but avoid the "malware changes the envvar or exe" security issue.

**Comment by manojampalam** [comment]
@parkovski can you enlighten a bit more on how your proposal would work? Are you saying that the binary need to be signed?

**Comment by DarwinJS** [comment]
I think it would make more sense to simply allow it to point to another hklm reg key that openssh could populate.  This way the value is still retrievable by defacto windows config methods but protected from a user level override.  It would not be necessary to lock what key it can point to, but if being set by any authorized setup program - the program should only allow hklm.

**Comment by DarwinJS** [comment]
Should also mention that this allows the flexibility for the openssh key to be decided later - or not at all - deployment automation specialists who setup openssh could elect to establish a location if openssh project does not want to.

**Comment by parkovski** [comment]
@manojampalam It's along those lines but the signing data would be separate from the executable and managed by `ssh-agent`. Essentially you'd store a list of authorized shells and a command to add to the list (or an option on `ssh-add`) that requires admin privileges - this would generate a new key pair with the private key only readable by the system and hash the shell exe. You could store these hashes somewhere like `~/.ssh/authorized_shells` - security doesn't matter for that file because only the system can generate a correct hash. Then it would be safe to read the shell from an environment variable and run it as long as its hash validates. This is useful if you want to set a default shell to something not published by MS, or if you're developing one yourself. The downside for shell developers is they have to update this for every new build.

Now that I think about it though, this seems more complicated than it needs to be. Just a quick note about using a reg key though - unless you enforce admin write permissions on the path it points to, there's still a potential security hole if I set my shell to something like "~/Documents/my-custom-shell.exe". I think this approach is easier and still secure:
- Only launch shells that require elevated write permissions.
- Create an `authorized_shells` list - whether this is in the install directory or the user's `.ssh` directory doesn't matter as long as it also requires elevated write permissions.
  - An unresolved question is whether this should allow directories. It would be nice to list `C:\Program Files\PowerShell\**` and have any PSCore update work automatically, but `C:\**` probably should not allow any admin writable path.
  - Maybe you have to list the exe name, or can use wildcards but not a blanket "any subpath".
- Whitelist the system path and/or signed exes. This way nothing special has to be done to switch between `cmd` and `PowerShell`.
- Read the shell from an environment var, but validate the ACLs and against the `authorized_shells` list, otherwise fall back to the default.
  - As a side note, it'd be nice to have the default be based on the start menu (Win+X) shortcut option.

**Comment by DarwinJS** [comment]
@parkovski - traditionally windows has handled the "admin write permissions" by simply requiring that the target be in either of the program files folders or either system32 folder.  If for some reason the permissions on these locations are non-standard, then the system is probably in trouble anyway.

This is effectively the built-in windows "whitelisting" for "only an admin can change / update stuff in these locations".

For instance, when many accessibility programs were disabled by changes in Windows 7, Microsoft made a way for them to work, but they had to add themselves to an HKLM registry key and then be on one of the previously mentioned paths.

One advantage to using this method is you don't actually have to check permissions and you don't have to limit permissions - any changes from standard permissions in these areas were done by an admin anyway.  Also, OpenSSH's internal way of checking permissions does not check "effective" permissions which would be required for Windows PowerShell and cmd.exe as you can't limit permissions to these files to an exactly specified ACL (like OpenSSH expects of key files) and not have bad things happen.

Different tangent - my plan for the openssh installer was to allow you to specify a set of paths to probe and it would find the latest shell on that path and populate this key.

It could use get-command and grab the version number and take the latest.

It could even allow crossing between shell types and stipulating exactly one full path (for example to windows powershell).  It would only proceed to new file specs if nothing was found with the previous.  It would also allow you to stipulate a version of core if you only wanted a specific one.

If it finds nothing in your search specs, don't populate the key, which results in default behavior.

Examples:
```
#PowerShell for Windows with the bitness that matches the platform:
-PathSpecsToProbeForShellEXE 'c:\windows\system32\windowspowershell\v1.0\powershell.exe"

#The latest version of powershell core (including favoring the new EXE name), if none, windows powershell
-PathSpecsToProbeForShellEXE "c:\Program Files\PowerShell\*\pwsh.exe","c:\Program Files\PowerShell\*\Powershell.exe","c:\windows\system32\windowspowershell\v1.0\powershell.exe"

#The latest version of core, if none, cmd.exe
-PathSpecsToProbeForShellEXE "c:\Program Files\PowerShell\*\Powershell.exe","c:\windows\system32\cmd.exe"

#Specific version of core, if none, windows powershell
-PathSpecsToProbeForShellEXE "c:\Program Files\PowerShell\6.0.0-beta.6\Powershell.exe","c:\windows\system32\windowspowershell\v1.0\powershell.exe"

```
The challenge I ran into is that the version information is not in the PE header of powershell.exe. 

I submitted this issue which also discusses a work around using the powershell core folder level (and limitations of that):  https://github.com/PowerShell/PowerShell/issues/5166

**Comment by DarwinJS** [comment]
Hmmm after this discussion maybe I'll scan the results and skip any paths outside of the four I mentioned unless the installer receives the switch -AllowInsecureShellEXE.  Then admins are empowered, but also warned.

**Comment by DarwinJS** [comment]
I have the logic described above working for /PathSpecsToProbeForShellEXE and an additional switch /AllowInsecureShellEXE (which gives warning ending in "Very unwise!!")

Tested and working on Win7, Win10 and Nano.

Even with the probing built, the idea that opened this issue is still relevant.  Allowing this registry key to point to another "Admin only updatable" location where PowerShell Core's "version to use" could be found.  This is because this probing mechanism cannot update the OpenSSH key when a newer version of PowerShell core is installed.

**Comment by diogocp** [comment]
I'm seeing some weird behavior when using environment variables in DefaultShell.

If DefaultShell is not set, I get the cmd shell as expected.

If I set it to `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`, I get powershell, again as expected.

However, if I set it to `%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe`, I get a powershell when I login interactively, but if instead I pass a command to be executed to ssh (e.g. `ssh localhost rm test.txt`) nothing happens. It returns with exit code 0 but nothing is executed on the server.

**Comment by DarwinJS** [comment]
@diogocp - the reason is that malware could theoretically 

1. read this registry key 
2. insert a user level %SystemRoot% environment variable which redirects the shell to a exe that pretends to be a shell like powershell - but monitors everything that goes on.

By requiring a literal path - no such attack is possible.

Which raises this idea for addressing this problem @manojampalam - what if the code that reads this registry key:

1. Reads ONLY System level environment variables.

This way it protects the "system" domain by only using environment variables that can be set by an administrator.

This would solve two problems:
- setting this variable across a set of machines that vary in where the %windir% is (e.g. windows installed on C: or D: across a set of machines)
- setting it to custom environment variables - it would still only read and use them from the Machine environment variables.

The call to get only machine variables in PowerShell / .NET is: 

```
[environment]::GetEnvironmentVariables("Machine")
```

More info: https://msdn.microsoft.com/en-us/library/system.environment_methods(v=vs.110).aspx

**Comment by diogocp** [comment]
@DarwinJS, I haven't looked into this recently, but the behavior I observed was that the variable **was read**, but only on interactive logins:

> if I set it to %SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe, I get a powershell when I login interactively

**Comment by manojampalam** [comment]
Thanks @DarwinJS. I'll check if there is a straight forward way to resolve a SYSTEM only environment variable. My guess is Powershell is probably populating that list directly from registry (this we can do certainly, just that the code would be more complex). 

Setting it to backlog. Will get back with an update by next milestone.

**Comment by parkovski** [comment]
Looking at [this MSDN page](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682653(v=vs.85).aspx), seems like you'd read from `HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment` to check just for system environment variables. Looks like `GetEnvironmentVariable` and `GetEnvironmentStrings` just look at the calling process' environment block.

**Comment by DarwinJS** [comment]
@parkovski - yes, but in the registry they are unexpanded - meaning they could contain embedded environment variables.  So they would need to be retrieved ONLY from the System context, and any expansions should technically only be done if they reference system context as well.
