### ISSUE TITLE
Session.connect: java.net.SocketException: Connection reset SFTP

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#920]
We are facing this issue not all time but couple of times a day ,
we are putting our files into a SFTP location where we are asked to put the same file into two different locations,
we are able to do that but some times when we completed placing files into first location  from our application and trying to put file into Second location we are seeingSession.connect: java.net.SocketException: Connection reset SFTP
can any one help to understand what was the issue
application :IBM Integration bus 
note :we are not doing any socket operation in the code

**Comment by bagajjal** [comment]
Please share the sftp-server.log with DEBUG3 enabled in that time period.

**Comment by thezim** [comment]
If you need help getting SFTP logging working see #834.

**Comment by manojampalam** [comment]
Please reopen with relevant info.
