### ISSUE TITLE
OpenSSH-Win32\sftp-server.exe --> Trojan:Win32/Fuerboos.B!cl  

### ISSUE THREAD

**Issue by brwilkinson** [PowerShell/Win32-OpenSSH#922]
Windows 10 Enterprise

Not sure if this is expected.

I had to create AV exclusions in order to use openssh-win32.

The first file that was flagged was sftp-server.exe, however I had to exclude the whole directory.

**Comment by bagajjal** [comment]
I am assuming this is a question to AV?
We need to understand why AV considers as virus.
From win32-openssh, I don't think we can do much here.

**Comment by AlFeersum** [comment]
Wouldn't it also be dependent on the AV?  Sophos Enterprise doesn't flag it.

**Comment by danielchalmers** [comment]
I got this on Windows Defender definition version 1.257.121.0 with [one of my programs](https://github.com/danielchalmers/Network-Monitor/releases/latest).  
After updating to 1.257.132.0 it doesn't seem to happen anymore.
