### ISSUE TITLE
unable to set Defaults:<myuser> !requiretty 

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#928]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
recent
 
**Server OperatingSystem**
Windows Server 2012 R2 Standard

**Client OperatingSystem**
any Linux
**What is failing**
can't set Defaults:<myuser> !requiretty due to missing /etc/sudoers.d/<myuser>

**Comment by manojampalam** [comment]
What defaults are you trying to set? It helps if you can give the exact cmdline you are trying to execute.
Reopen with required info.
