### ISSUE TITLE
ssh client freezes with output redirection to stdin of Linux server....

### ISSUE THREAD

**Issue by naatje80** [PowerShell/Win32-OpenSSH#929]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
v0.0.22.0
 
**Server OperatingSystem**
Scientific Linux 6.9

**Client OperatingSystem**
Windows 10 Enterprise

**What is failing**
When forwarding text to stdin to Linux server running ssh-daemon, the ssh client on windows freezes. I've both tried following command both in the powershell and the Windows command line, but the results are the same:
Powershell: 
echo "Hello World"|./ssh user@server "cat -"

**Expected output**
Hello World
Return to command line.

**Actual output**
Hello World
Client freezes.

**Comment by naatje80** [comment]
Forgot to mention i could stop the client by typing Control+C.

**Comment by manojampalam** [comment]
Can you check if the session process (sshd) is still running on your Linux target? It looks like the client is hanging as the channel from target is still open.

**Comment by naatje80** [comment]
Dear manojampalam,

Thank you for your reply. The session process is indeed still running on the Linux target. When break the client session by pressing Control+C it is also closed.

**Comment by manojampalam** [comment]
@naatje80 can you also confirm that the shell process (that is executing cat -) is still running?

If so, that would be the root cause why ssh.exe isn't exiting. You can expect the following to be sent to your shell process - \"Hello World\"\r\n
Do you expect the shell process to continue running with that input?

**Comment by naatje80** [comment]
The cat process is indeed still running on the server. 

What I actually wanted to achieve is copying the public ssh key added to the authorized keys of a file using ssh. But because the client freezes, I tried just the basic: only redirecting some text to the remote server. 

What I see is that if I send output to the stdin using ssh, the file is created but the content is not added until I press Control+C. I also tried the redirection using dd:
`
echo "Hello World"\r\n | ssh userid@server  "dd of=some_file oflag=append conv=notrunc"
`
I see the same issue: dd is not closing on the server side until I press Control+C in the client. Also the file is created but the content is not added until Control+C is pressed in the ssh client on the Windows side.

I already tried various carriage return ending for the echo line, because I also expected that it was waiting a return. But none seem to help.

Hopefully this additional information is helpfull.....

**Comment by manojampalam** [comment]
OK Thanks. Found the issue. Will fix it for next release.

**Comment by manojampalam** [comment]
Try the attached private. 
[ssh.zip](https://github.com/PowerShell/Win32-OpenSSH/files/1440151/ssh.zip)

**Comment by naatje80** [comment]
Great, thank you! The issue is indeed now solved. There was only one issue with the ssh.exe you've supplied, It had a dependency for libcrypto.dll but the pre-compiled version of the full package contained a file called libcrypto-41.dll (Only had to copy and rename that file to use the ssh.exe). But this is most likely due to the way you've compiled the pacakge.....

**Comment by bagajjal** [comment]
@naatje80 - We are renaming the dll to exclude the version number so the new release (yet to be released) will have libcryto.dll instead of libcrypto-41.dll.

**Comment by naatje80** [comment]
@bagajjal Ok thank you for your clarification. I understand! For me the issue is solved.
