### ISSUE TITLE
Install-sshd.ps1 should set correct user directory/file permissions 

### ISSUE THREAD

**Issue by JW0914** [PowerShell/Win32-OpenSSH#930]
**"OpenSSH for Windows" version**
All

**Client OperatingSystem**
All

**What is failing**
Repeated issues being opened by users as a result of incorrect permissions, of which can be easily corrected by having `install-sshd.ps1` create the proper permissions from the get-go.

- _Users should not be required to manually set permissions on something as sensitive as an SSH server due to the severe security implications of incorrect permissions being set._

It also appears even some Collaborators do not understand what the proper permissions should and should not be, as Collaborators are informing other users to incorrectly set permissions on files and directories contained within _%UserProfile%\\.ssh_

---

##

- **NOTE:**
   - **%UserProfile%\\.ssh**
      - This, and all files/directories within, should _**not**_ have inherited permissions.
         - _Unless user is only one being passed for inheritance_
      - User should be the owner of _%UserProfile%\\.ssh_ and all files/directories within
   - **%ProgramFiles%\\OpenSSH\\ssh_host_*_key**
      - [`PsExe`](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec) should be utilized to register the server keys as _NT AUTHORITY\SYSTEM_ (_[halfway down](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH)_)
     - [`sdelete`](https://docs.microsoft.com/en-us/sysinternals/downloads/sdelete) should be used to securely erase them _(5 pass minimum)_ once registered
##

- **_%ProgramFiles%\\OpenSSH\\ssh_config_**
       ```
       NT AUTHORITY\SYSTEM:(F) |
       BUILTIN\Administrators:(F) |
       NT SERVICE\sshd:(R)
       ```
     - ```icacls %ProgramFiles%\OpenSSH\sshd_config /grant `"NT AUTHORITY\SYSTEM`":`(F`)```
```icacls %ProgramFiles%\OpenSSH\sshd_config /grant `"BUILTIN\Administrators`":`(F`)```
```icacls %ProgramFiles%\OpenSSH\sshd_config /grant `"NT SERVICE\sshd`":`(R`)```
- **_%ProgramFiles%\\OpenSSH\\sshd_config_**
       ```
       NT AUTHORITY\SYSTEM:(F) |
       BUILTIN\Administrators:(F) |
       NT SERVICE\sshd:(R)
       ```
     - ```icacls %ProgramFiles%\OpenSSH\sshd_config /grant `"NT AUTHORITY\SYSTEM`":`(F`)```
```icacls %ProgramFiles%\OpenSSH\sshd_config /grant `"BUILTIN\Administrators`":`(F`)```
```icacls %ProgramFiles%\OpenSSH\sshd_config /grant `"NT SERVICE\sshd`":`(R`)```
##

- **_%UserProfile%\\.ssh_**
       ```
       <HostName>\%UserName%:(OI)(CI)(F)
       ```
     - ```takeown /r /f %UserProfile%\.ssh```
     - ```icacls %UserProfile%\.ssh /grant `"<HostName>\%UserName%`":`(F`)```
- **_%UserProfile%\\.ssh\\authorized_keys_**
       ```
       NT SERVICE\sshd:(R) |
       <HostName>\%UserName%:(OI)(CI)(F)
       ```
     - ```icacls %UserProfile%\.ssh\authorized_keys /grant `"NT SERVICE\sshd`":`(R`)```
```icacls %UserProfile%\.ssh\authorized_keys /grant `"<HostName>\%UserName%`":`(F`)```
- **_%UserProfile%\\.ssh\\config_**
       ```
       <HostName>\%UserName%:(OI)(CI)(F)
       ```
     - ```icacls %UserProfile%\.ssh\config /grant `"<HostName>\%UserName%`":`(F`)```
- **_%UserProfile%\\.ssh\\known_hosts_**
       ```
       <HostName>\%UserName%:(OI)(CI)(F)
       ```
     - ```icacls %UserProfile%\.ssh\known_hosts /grant `"<HostName>\%UserName%`":`(F`)```
##

- **_~/.ssh_**
   ```
   [root@LEDE] /home/jw # ls -lsa .ssh
       0 drwx------    1 jw       jw             368 Sep 10  2017 .
       4 -rw-------    1 jw       jw            2254 Sep 10  2017 authorized_keys
       8 -rw-------    1 jw       jw            6699 Sep 10  2017 config
       0 -rw-------    1 jw       jw               0 Sep 10  2017 known_hosts
   ```

**Comment by manojampalam** [comment]
Utilities included in package are meant to do exactly this. Utility usage details are at https://github.com/PowerShell/Win32-OpenSSH/wiki/OpenSSH-utility-scripts-to-fix-file-permissions

Please point out instances where -
_Collaborators are informing other users to incorrectly set permissions on files and directories contained within %UserProfile%\.ssh_

Added sdelete suggestion on Wiki. Thanks.

**Comment by JW0914** [comment]
If you can provide a private way to communicate with you, I'll provide the name of the collaborator, as well as the post detailing the above, however it's not appropriate to call them out publicly _(which is why the Collaborator was not named and post not linked to)_.

##
`FixHostFilePermissions.ps1` and `FixUserFilePermissions.ps1` do not set the correct permissions for _%UserProfile%\\.ssh\\*_

- _%UserProfile%\\.ssh_ **should not** have inherited permissions, unless the owning user is the **only** user being passed for inheritance.
   - This means _NT AUTHORITY\\SYSTEM_ and _Administrators_, or any other user/group, **should not** have access
     - Depending on how Windows was installed or upgraded, more often times than not, the user is not the owner of their user folder; usually _NT AUTHORITY\\SYSTEM_ or _Administrators_ is, and since permissions are inherited from _%UserProfile%_, _NT AUTHORITY\\SYSTEM_ and _Administrators_ have full access when they should have **no** access.
- All one needs to do is issue `icacls %UserProfile%\.ssh`  & `icacls %UserProfile%\.ssh\*` to show improper permissions.  
   - The permissions I laid out in the main post above are the proper permissions; these are not the permissions one sees after installing OpenSSH and running `FixHostFilePermissions.ps1` & `FixUserFilePermissions.ps1`

##
### FixHostFilePermissions.ps1

```
PS C:\Program Files\OpenSSH> .\FixHostFilePermissions.ps1
  [*] C:\Program Files\OpenSSH\sshd_config
      looks good

  [*] C:\Users\JW0914\.ssh\authorized_keys
      'NT SERVICE\sshd' now has Read access to 'C:\Users\JW0914\.ssh\authorized_keys'.
      Repaired permissions

   Done.


PS C:\Program Files\OpenSSH> icacls C:\Users\JW0914\.ssh
C:\Users\JW0914\.ssh
                    NT AUTHORITY\SYSTEM:(OI)(CI)(F)
                    BUILTIN\Administrators:(OI)(CI)(F)
                    Win10Pro\JW0914:(OI)(CI)(F)

Successfully processed 1 files; Failed processing 0 files


PS C:\Program Files\OpenSSH> icacls C:\Users\JW0914\.ssh\*
C:\Users\JW0914\.ssh\authorized_keys 
                                    NT SERVICE\sshd:(R)
                                    NT AUTHORITY\SYSTEM:(I)(F)
                                    BUILTIN\Administrators:(I)(F)
                                    Win10Pro\JW0914:(I)(F)

C:\Users\JW0914\.ssh\config 
                           NT AUTHORITY\SYSTEM:(F)
                           BUILTIN\Administrators:(F)
                           Win10Pro\JW0914:(F)

C:\Users\JW0914\.ssh\known_hosts 
                                NT AUTHORITY\SYSTEM:(F)
                                BUILTIN\Administrators:(F)
                                Win10Pro\JW0914:(F)

Successfully processed 3 files; Failed processing 0 files
```

##
### FixUserFilePermissions.ps1

```
PS C:\Program Files\OpenSSH> .\FixUserFilePermissions.ps1
  [*] ~\.ssh\config
      looks good

   Done.


PS C:\Program Files\OpenSSH> icacls C:\Users\JW0914\.ssh\*
C:\Users\JW0914\.ssh\authorized_keys
                                    NT SERVICE\sshd:(R)
                                    NT AUTHORITY\SYSTEM:(I)(F)
                                    BUILTIN\Administrators:(I)(F)
                                    Win10Pro\JW0914:(I)(F)

C:\Users\JW0914\.ssh\config
                           NT AUTHORITY\SYSTEM:(F)
                           BUILTIN\Administrators:(F)
                           Win10Pro\JW0914:(F)

C:\Users\JW0914\.ssh\known_hosts
                                NT AUTHORITY\SYSTEM:(F)
                                BUILTIN\Administrators:(F)
                                Win10Pro\JW0914:(F)

Successfully processed 3 files; Failed processing 0 files
```

**Comment by manojampalam** [comment]
Its alright. Mistakes do happen we all are learning from each other. You could simply reply on the original issue thread and point out the inconsistency. 

As for ownership of %userprofile%\.ssh, SYSTEM and ADMINISTRATORS can take ownership of any resource in Windows no matter what (even if they are explicitly denied). See takeown usage. Hence any such restrictions would only be superficial. Or am I missing something?

**Comment by JW0914** [comment]
I replied with something similar to the original post above, however this current issue wasn't opened solely because of that thread, but instead because I've come across several issue threads regarding _%UserProfile\.ssh\*_ permissions issues.

- _%UserProfile\.ssh\*_ permissions should echo BSD/Linux permissions, and root, nor sudo, have access to an individual user's .ssh folder on a multi-user system
   - It's imperative no one but the user has access to _%UserProfile%\.ssh\authorizedkeys_ and _%UserProfile%\.ssh\config_, as it's a major security risk for either to be accessible by anyone but the user they belong to.

**Comment by JW0914** [comment]
I replied with something similar to the original post above, however this current issue wasn't opened solely because of that thread, but instead because I've come across several issue threads regarding _%UserProfile%\\.ssh\\*_ permissions issues.

- _%UserProfile%\\.ssh\\*_ permissions should echo BSD/Linux permissions, and root, nor sudo, have access to an individual user's _.ssh_ folder on a multi-user system
   - It's imperative no one but the user has access to _%UserProfile%\\.ssh\\authorizedkeys_ and _%UserProfile%\\.ssh\\config_, as it's a major security risk for either to be accessible by anyone but the user they belong to.

**Comment by JW0914** [comment]
root can do the same on a multi-user BSD/Linux system, so clearly there's a reason why only the owning user should have access.  I don't know what that reasoning is, but considering this has always been the permission structure for OpenSSH, I'd recommend sticking with the way the software and it's permission structure is intended to work, and not modify it unless one understands the reasoning of the BSD authors.  

- _Unless one can provide a logical and rational reasoning for changing the permission structure to something other than it was intended to be, then it should be left well alone._

takeown would have to be utilized by an administrator to take ownership of a folder/file which is owned by another local user or a system level user/group, so yes, there are good enough reasons to ensure _NT AUTHORITY\\SYSTEM_ & _Administrators_ do not have access to _%UserProfile%\\.ssh\*_.  

- _Unless Microsoft has received guidance from OpenSSH authors/maintainers as to why Windows should not follow the same permissions structure as BSD/Linux, then the permissions should remain as they were intended to be by OpenSSH._

**Comment by manojampalam** [comment]
Thanks for your follow up. We did think through this while designing permissions for Windows. 
The equivalent of "root" in windows, for all practical purposes, is SYSTEM or Administrators.

I understand the permissions structure in Unix, but our thinking process here is to "not superficially restrict any access without any security benefit". As I said, SYSTEM or Administrators can take over ownership and modify permissions of any file or folder at their will (irrespective of ACLs). So what's the point in blocking them. 

We will double check with OpenSSH authors/maintainers.

**Comment by JW0914** [comment]
Fair enough, thank you.
