### ISSUE TITLE
ssh-agent returns empty

### ISSUE THREAD

**Issue by jdnichollsc** [PowerShell/Win32-OpenSSH#931]
**"OpenSSH for Windows" version**
 `v0.0.22.0`
 
**OperatingSystem**
 `Windows Server 2012`

**What is failing**
**ssh-agent** returns empty from the command line prompt.

**Expected output**
Say anything!

**Actual output**
Nothing...

Thanks in advance

**Comment by manojampalam** [comment]
This is expected. ssh-agent is implemented as a service in Windows. Running ssh-agent.exe simply starts the service.

**Comment by jdnichollsc** [comment]
ohh thanks for response, I'm going to use the **ssh-agent** of Git 👍
