### ISSUE TITLE
A huge log file

### ISSUE THREAD

**Issue by kice** [PowerShell/Win32-OpenSSH#935]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
0.0.10.0 

---

`
2017/10/30  20:38   217,504,821,628 C:\Program Files\OpenSSH-Win64\logs\sshd.log
`
This file is over 200G and how can I do with it?

**Comment by bagajjal** [comment]
You can delete the file.. It will not have any impact..

**Comment by kice** [comment]
I knew that and is it there any config effect on this issue? like limiting the file size or only log last 7days.

**Comment by DarwinJS** [comment]
@kice - are you really running version 0.0.10.0 ?  If so you should update to 0.0.22.0.

**Comment by bagajjal** [comment]
We don't have log throttling implemented because our long term goal is to move away from the log files.. 

Enable minimal logging so that the file will not grow fast. Have a periodic powershell scripts to backup and delete the log files.

**Comment by manojampalam** [comment]
You may use this workaround until we find a solution

create a task scheduler task that would run the following PowerShell script (edit as needed) at intervals. It empties contents of sshd.log into a backup file once sshd.log breaches 25MB

if ((Get-ChildItem .\logs\sshd.log).Length -gt 25*1024*1024) 
{
   copy-item .\logs\sshd.log .\logs\sshd.log.prev
   $null | Set-Content .\logs\sshd.log
}

**Comment by maertendMSFT** [comment]
The logs are now published to ETW
