### ISSUE TITLE
DefaultShell not working from macOS

### ISSUE THREAD

**Issue by brandonroyal** [PowerShell/Win32-OpenSSH#936]
When setting the `DefaultShell` option in the registry, SSH does not appear to respect that setting

**Reproduction Steps**
1. Install per instructions: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH#install-win32-openssh-test-release

1. Setup `DefaultShell` using [this screenshot](https://user-images.githubusercontent.com/23668037/32013581-67206dca-b970-11e7-8820-fde658d302c1.png) as a reference point
```powershell
#set registry entry
PS> reg add "HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH" /v DefaultShell /t REG_SZ /d "C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" /f

#validate that registry entry is set
PS> reg query "HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH" /v DefaultShell

HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH
    DefaultShell    REG_SZ    C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe

#restart machine (probably overkill I know)
PS> Restart-Computer -Force
```

1. Run ssh command
```
$ ssh -p 2222 vagrant@localhost Get-Service
```

**Expected Result**
```
$ ssh -p 2222 vagrant@localhost Get-Service
```
This command should return list of Windows Services like a normal PS command

**Actual Result**
```bash
$ ssh -p 2222 vagrant@localhost Get-Service

'Get-Service' is not recognized as an internal or external command,
operable program or batch file.
```

**"OpenSSH for Windows" version**
0.0.22.0
 
**Server OperatingSystem**
Windows Server 2016 Standard Evaluation

**Client OperatingSystem**
macOS 10.12.6

**Comment by bagajjal** [comment]
@BrandonRoyal - When you launch an interactive ssh session (ssh -p 2222 vagrant@localhost), are you getting powershell as default shell?

**Comment by brandonroyal** [comment]
@bagajjal no. I'm not.

When attempting interactive SSH...
```bash
$ ssh -p 2222 vagrant@localhost
```

Command screen looks like this:
```cmd
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

vagrant@VAGRANT-2016 C:\Users\vagrant>
```

Confirming this is not PowerShell by requesting PS version:
```cmd
C:\Users\vagrant>$PSVersionTable.PSVersion
'$PSVersionTable.PSVersion' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by brandonroyal** [comment]
@bagajjal Any update on this?

**Comment by bagajjal** [comment]
@BrandonRoyal - Sorry for the late reply..
I have created the private [ssh-shellhost binary](https://github.com/PowerShell/Win32-OpenSSH/files/1537389/ssh-shellhost-DefaultShell-Issue.zip). Please use this binary (replace existing ssh-shellhost.exe with my private ssh-shellhost.exe), it will show error message and the configured default shell..
1) Use "Get-DefaultShell" command display the default shell. Please note that this is a private command and not a powershell command.
2) Over the ssh client, just to make sure please issue "reg query "HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH" /v DefaultShell" command that shows the registry value.

Here is how it looks,
![image](https://user-images.githubusercontent.com/23668037/33692901-8f6deb2c-daa4-11e7-8361-d2d4699a8fa7.png)

**Comment by bagajjal** [comment]
Any update on this?

**Comment by bagajjal** [comment]
@BrandonRoyal - Could you please try the steps I mentioned and provide the information.

**Comment by bagajjal** [comment]
please reopen with required information.

**Comment by woegjiub** [comment]
<img width="675" alt="screen shot 2018-03-01 at 13 22 05" src="https://user-images.githubusercontent.com/2138067/36823909-a73ec5ea-1d53-11e8-84b5-993c776ea3ad.png">
I can confirm that this issue still exists.

SSHing into virtualbox from macOS produces the above results.

Both Windows and macOS are on the most recent versions.

**Comment by bagajjal** [comment]
@woegjiub - can you try steps mentioned above dated "Dec 6 017"

**Comment by woegjiub** [comment]
Even as administrator, I am unable to modify that file.
I've installed OpenSSH from add/remove windows features, not from here

**Comment by woegjiub** [comment]
Given the registry entry shows that powershell is the default, how does this binary help?

If it's necessary to override that, could you please advice on how this can be achieved (I'm a Linux/macOS user, and don't know much about windows)
