### ISSUE TITLE
Unable to set Defaults:myuser !requiretty 

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#937]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
recent
 
**Server OperatingSystem**
Windows Server 2012 R2 Standard

**Client OperatingSystem**
Any Linux

**What is failing**
calling system doesnt get a tty

I need to set a Defaults:<connecting user> !requiretty. On Linux systems, this is set in the /etc/sudoers.d file. As there is no sudoers file in a Windows environment, theres no way to set this parameter.
I was asked to reopen this issue with the exact cmdline I'm trying execute (https://github.com/PowerShell/Win32-OpenSSH/issues/928). There is no cmdline to set this parameter / setting.

**Comment by manojampalam** [comment]
Can you please explain what setting this does and its use case scenarios? We need to first evaluate if the use case scenarios apply to Windows at all.

**Comment by ghost** [comment]
This setting acquires a tty on the target system (in this case on a windows machine). 
Use case: A script, containing the ssh command, is triggered on a system which does not have a tty itself (for example from a scheduler [in our case SAP Solution Manager or Icinga]). 
We counter checked this with a linux system as ssh target with the mentioned setting set in /etc/sudoers.d

**Comment by maertendMSFT** [comment]
Can you provide more information?
