### ISSUE TITLE
test suite update

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/Win32-OpenSSH#940]
Automated test suite update,
Make the libressl enabled by default, add a new switch to disable using libressl.

**Comment by DarwinJS** [comment]
Although I don't know what "WindowsInbox" is, just want to lobby that any "global behavior" switches that affect behaviors beyond jus testing, they should be configurable by installation technology.  e.g. In sshd_conf or registry.

Also to avoid dumb comments like this one I'm making, it would be helpful to articulate the meaning of jargon like "WindowsInbox" in the issue itself ;)

**Comment by bagajjal** [comment]
This issue is purely from a automated test coverage perspective.

We are shipped "openssh" into windows10 as "feature on demand".
The shipped windows 10 openssh binaries only support default crypto algorithm (ed25519).
We are now making changes to support all crypto algorithms like rsa, dsa, etc.
As part of this change we need to update our test scripts to test all crypto algorithms.
