### ISSUE TITLE
[Question about install]

### ISSUE THREAD

**Issue by fjaenal** [PowerShell/Win32-OpenSSH#942]
Hello:
   This is just a question, not an issue per se. I have running on a windows Server 2012 the Win32-OpenSSH, in order to install we can not use Powershell nor Chocolatey. We have to relay only on the Old good Windows Command. For the version we are running I have a batch script (I can attach it if necessary), with that script, which is very basic, I can install the version v0.0.9.0.

The question is; Can I use the Windows Command to install the Win32-OpenSSH in the newer versions of Win32-OpenSSH? or is powershell / chocolatey mandatory. Also it has to be automated.

Frank

**Comment by bagajjal** [comment]
@fjaenal - Powershell/chocolatey automates the installation process. If you can do the same thing manually or using batch script then you are good.

**Comment by DarwinJS** [comment]
@fjaenal - in theory you could use cmd.  Backporting everything required could be significant effort both to do the first time and then to maintain when installation information is updated in newer releases.

Things like the complex permissions setting in things like: https://github.com/PowerShell/Win32-OpenSSH/blob/L1-Prod/contrib/win32/openssh/OpenSSHUtils.psm1 it could quite be difficult.

Also adding special permissions to the user running sshd can be challenging.

**Comment by fjaenal** [comment]
Then the next question, maybe is too basic, is: Are mandatory the set of all those permission settings on the server? Can it be installed and run as an administrator on the server without giving those permissions?

**Comment by bagajjal** [comment]
nope. Those permissions are mandatory. You can configure the permissions manually as well but it is time taking process.

**Comment by fjaenal** [comment]
First of all thanks a lot for the help. 
Do we only need PS / Chocolatey for the installation (can be disable afterwards?) or must it be enable at any time?
Also the installation requires restart? I can't see any reference on the "Install Win32 OpenSSH" wiki page to restart.

**Comment by DarwinJS** [comment]
@fjaenal - I maintain the Universal Installer.  Although it is housed in a Chocolatey package, it is designed to be used without Chocolatey as well.  In fact, you don't even need internet access after you've downloaded the package once into your organization.  You can also extract the package to a shared location and run installs from there.

You can follow these instructions: https://github.com/DarwinJS/ChocoPackages/tree/master/openssh#install-scenario-4-complete-offline-install--network-based-install--sccm-or-other-esd-install-wout-chocolatey-wout-wow64-wout-powershell-5-wout-internet

This installation method will also work for easy upgrades to newer versions as the install script is designed to do an upgrade as well.

You don't need chocolatey or powershell to be running after install.

The OpenSSH installation no longer requires a reboot under normal circumstances.

**Comment by DarwinJS** [comment]
FYI I just updated the instructions to be clearer for your deployment scenario: https://github.com/DarwinJS/ChocoPackages/tree/master/openssh#install-scenario-4-complete-offline-install--network-based-install--sccm-or-other-esd-install-wout-chocolatey-wout-wow64-wout-powershell-5-wout-internet

Also the heading says without "PowerShell 5" - it means you don't need version 5 (which contains PackageManagement), not that you don't need PowerShell at all.

**Comment by fjaenal** [comment]
thanks a lot !!!!! Really helpful as always !
