### ISSUE TITLE
Cannot open include file: 'openssl/opensslv.h': No such file or directory

### ISSUE THREAD

**Issue by DaburLal** [PowerShell/Win32-OpenSSH#943]
Referring to https://github.com/PowerShell/Win32-OpenSSH/wiki/Building-using-VS-2015 

When i try building according to above mentioned steps, it gives the following error : Cannot open include file: 'openssl/opensslv.h': No such file or directory

**Comment by manojampalam** [comment]
Updated instructions. Try now and reopen if you still see issues.

**Comment by saurabhverma999** [comment]
I am able to run sftp and scp but when i try running ssh and sshd it stops in between giving the following error

'sshd.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'sshd.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'sshd.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
The program '[8980] sshd.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.

**Comment by DaburLal** [comment]
Now i am able to run scp and sftp but when i try running sshd i get the following error 

'sshd.exe' (Win32): Loaded 'C:\Users\w21821\Desktop\openssh-portable-latestw_all\bin\x64\Debug\sshd.exe'. Symbols loaded.
'sshd.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'sshd.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'sshd.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'sshd.exe' (Win32): Loaded 'C:\Users\w21821\Desktop\openssh-portable-latestw_all\contrib\win32\openssh\LibreSSLSDK\x64\libcrypto.dll'. Symbols loaded.
'sshd.exe' (Win32): Loaded 'C:\Program Files\PowerShell\6.0.0-beta.9\api-ms-win-core-localization-l1-2-1.dll'. Cannot find or open the PDB file.
Exception thrown at 0x0000000076FE8078 (ntdll.dll) in sshd.exe: 0xC0000139: Entry Point Not Found.
The program '[6016] sshd.exe' has exited with code -1073741511 (0xc0000139) 'Entry Point Not Found'.
