### ISSUE TITLE
Doesn't work well with SSH2.js

### ISSUE THREAD

**Issue by guiguan** [PowerShell/Win32-OpenSSH#944]
**"OpenSSH for Windows" version**
v0.0.22.0
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
macOS 10.13.1 and `ssh2` library

**What is failing**, **Expected output** & **Actual output**
When using `ssh2` shell method to get output from a remote ssh command, the openssh server (installed following this https://winscp.net/eng/docs/guide_windows_openssh_server) terminated the connection unexpectedly and didn't return any output related to the remote command. Other ssh servers worked fine on the same windows, including Bitvise SSH Server and Windows 10 developer extension ssh server https://www.danielsellers.com/blog/2017/2/10/microsoft-ssh-server-for-windows.

You can use my demo code to test and debug: https://github.com/guiguan/ssh2-test

**Comment by saurabhverma999** [comment]
I am able to run sftp and scp but when i try running ssh and sshd it stops in between giving the following error

'sshd.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'sshd.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'sshd.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
The program '[8980] sshd.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.

**Comment by manojampalam** [comment]
Get server side logs using steps at https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Comment by manojampalam** [comment]
Reopen with logs.
