### ISSUE TITLE
libcrypto.dll can't load on Windows 7 due to Windows 10-specific DLL imports

### ISSUE THREAD

**Issue by djsweet** [PowerShell/Win32-OpenSSH#946]
**"OpenSSH for Windows" version**
0.0.23.0
 
**Server OperatingSystem**
 Windows 7 Professional

**Client OperatingSystem**
Not applicable, `sshd` server fails to start

**What is failing**
All programs with a dependency on libcrypto, esp. `ssh.exe`, `sshd.exe`, and `ssh-keygen.exe` fail to start on Windows 7. Attempting to run these programs through Windows Explorer provides the following error message:

"The program can't start because api-ms-win-core-localization-l1-2-1.dll is missing from your computer. Try reinstalling the program to fix this problem".

Building LibreSSL 2.6.3 against SDK v8.1, then re-building OpenSSH against this custom LibreSSL `crypto-42.dll` solves this issue.

**Comment by bingbing8** [comment]
yes, please use the libcryto.dll from [Release v0.0.23.0](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.23.0). We will revert the libcryto.dll back to that build with sdk 8.1

**Comment by bagajjal** [comment]
Reopening this issue to fix properly.

**Comment by bagajjal** [comment]
update the binaries.
