### ISSUE TITLE
Any OpenSSH version for Windows XP SP3?

### ISSUE THREAD

**Issue by tvsuhail** [PowerShell/Win32-OpenSSH#948]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**

**What is failing**

**Expected output**

**Actual output**

**Comment by bagajjal** [comment]
We tested windows 7 and above. As per [windows lifecycle fact sheet](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet), Microsoft doesn't support Windows XP SP3.

Having said that, you can try the latest release. If it didn't work then we may not be able to support windows XP SP3.

**Comment by tvsuhail** [comment]
I tried, but receiving error while executing install script for service start and user creation.  And when running ssh-keygen, receiving not a valid win32 application.

**Comment by makefu** [comment]
@tvsuhail Hey, i am getting the same error. have you made any progress or how have you solved the issue?

**Comment by bagajjal** [comment]
As stated earlier we support windows 7 and above. 
Windows XP SP3 is not supported.

**Comment by makefu** [comment]
@bagajjal yep i understood that, however i cannot (currently) change the underlying Operating System, unfortunately.
Our solution right now is to use FreeSSHd with a lot of hardening and configuration measures to protect the service as good as possible.

cygwin is also not running on windowsXP, unfortunately. Otherwise this would have been my favorite solution right after win32-OpenSSH.

**Comment by tvsuhail** [comment]
> @bagajjal yep i understood that, however i cannot (currently) change the underlying Operating System, unfortunately.
> Our solution right now is to use FreeSSHd with a lot of hardening and configuration measures to protect the service as good as possible.
> 
> cygwin is also not running on windowsXP, unfortunately. Otherwise this would have been my favorite solution right after win32-OpenSSH.

@makefu I couldn't find any solution during that time, then i had used Bitwise SSH.

**Comment by makefu** [comment]
@tvsuhail thanks for the heads-up!
