### ISSUE TITLE
Unable to run ssh and sshd

### ISSUE THREAD

**Issue by DaburLal** [PowerShell/Win32-OpenSSH#949]
While trying to run ssh and sshd from Visual Studio 2015, build gets completed with zero failures but while debugging it gives the following error - 

The program '[8740] ssh.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.

It could not able to access libcrypto.dll

It says to reinstall the program to fix the problem.

**Comment by bagajjal** [comment]
Your environment path variable should have the libcrypto.dll ("$openssh-portable\contrib\win32\openssh\LibreSSLSDK\<platform>\libcrypto-41.dll").

**Comment by DaburLal** [comment]
Still the same error occurring!

**Comment by DaburLal** [comment]
Could you kindly give me a detailed explanation for the same ?? Thanks in advance.

**Comment by bagajjal** [comment]
please copy the "$openssh-portable\contrib\win32\openssh\LibreSSLSDK\<platform>\libcrypto-41.dll to "c:\windows\system32" folder so that it will always be part of environment path variable.
