### ISSUE TITLE
Update Chocolatey Instructions in Wiki

### ISSUE THREAD

**Issue by madisonrickert** [PowerShell/Win32-OpenSSH#950]
On the [chocolatey install instructions page](https://github.com/PowerShell/Win32-OpenSSH/wiki/Win32-OpenSSH-Automated-Install-and-Upgrade-using-Chocolatey) I noticed a couple errors:

1. `win32-openssh` package name has been deprecated in the chocolatey repository, should be changed to just `openssh`.
2. In the section "Chocolatey Package Usage Scenarios" the uninstall commands are incorrect.

**Comment by manojampalam** [comment]
@DarwinJS FYI

**Comment by DarwinJS** [comment]
@manojampalam - is it possible for that page to just contain a forward link to: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/readme.md

**Comment by manojampalam** [comment]
Redirected link in wiki main page.
