### ISSUE TITLE
unable to use get-ad* with pubkey auth

### ISSUE THREAD

**Issue by n3roGit** [PowerShell/Win32-OpenSSH#951]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
#	$OpenBSD: sshd_config,v 1.84 2011/05/23 03:30:07 djm Exp $
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Server 2016

**Client OperatingSystem**
WIndows 10 Pro

**What is failing**
Get-ADUser TestUser
Get-ADUser : Unable to contact the server. This may be because this server does not exist, it is
currently down, or it does not have the Active Directory Web Services running.
At line:1 char:1
+ Get-ADUser TestUser
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (kdall:ADUser) [Get-ADUser], ADServerDownExcept
   ion
    + FullyQualifiedErrorId : ActiveDirectoryServer:0,Microsoft.ActiveDirectory.Management.Command
   s.GetADUser

when using public key authentication

**Expected output**

**Actual output**

**Comment by n3roGit** [comment]
I have a hunch what it could be. apparently only a local copy of the user is used when using a key, which has no access to the AD.

If you additionally authenticate yourself in the console, you can retrieve the ad stuff.


$pass="YourPassword"|ConvertTo-SecureString -AsPlainText -Force
$Cred = New-Object   System.Management.Automation.PsCredential('Username@Domain',$pass)
Get-ADUser TestUser -Credential $cred

**Comment by manojampalam** [comment]
It might be related to the fact that the session that gets created using pubkey auth has no outbound auth capabilities. If your scenarios works with password auth and not pubkey auth - this is definitely the underlying reason.
