### ISSUE TITLE
Trying to connect with Putty (ssh client)

### ISSUE THREAD

**Issue by DaburLal** [PowerShell/Win32-OpenSSH#952]
This is more of a guidance i am seeking from people working on the same project.
I am trying to secure VNC server and client using Secure shell.
For that i have installed source codes for secure shell client (putty) and secure shell server (OpenSSH) on the respective platforms.

Now as i have to move forward with the process of connecting these two, i am seeking for experience from people who have done the same or know any reference which i can follow to establish a connection between the two.

Thank You!

**Comment by manojampalam** [comment]
I would recommend asking this on openssh general DL
