### ISSUE TITLE
ssh-agent communication failed when DC unreachable during start

### ISSUE THREAD

**Issue by jochemd** [PowerShell/Win32-OpenSSH#953]
**"OpenSSH for Windows" version**
0.0.22.0
 
**Server OperatingSystem**
n/a

**Client OperatingSystem**
Windows 10 build 16299.19

**What is failing**
ssh-agent in general, and the command "ssh-add -l" is a good example

**Expected output**
4096 SHA256:******************************************** jochem@********** (RSA)

**Actual output**
error fetching identities: communication with agent failed

My laptop is part of a domain. If I am in the office or connected through a VPN to the office the moment my ssh-agent starts, ssh-add works correctly. If I am not connected to a domain controller when ssh-agent starts, it fails with the following message in ssh-agent.log:

> 13228 18:38:24:312 error: LookupAccountNameW on SSHD account failed with 1789
> 13228 18:38:24:312 fatal: failed to retrieve client details
> 1508 18:38:46:464 error: LookupAccountNameW on SSHD account failed with 1789
> 1508 18:38:46:464 fatal: failed to retrieve client details
> 2012 18:39:16:678 error: LookupAccountNameW on SSHD account failed with 1789
> 2012 18:39:16:680 fatal: failed to retrieve client details
> 9240 18:39:28:542 error: LookupAccountNameW on SSHD account failed with 1789
> 9240 18:39:28:542 fatal: failed to retrieve client details
> 8304 18:41:02:828 error: LookupAccountNameW on SSHD account failed with 1789
> 8304 18:41:02:828 fatal: failed to retrieve client details
> 3196 18:41:11:463 error: LookupAccountNameW on SSHD account failed with 1789
> 3196 18:41:11:463 fatal: failed to retrieve client details
> 10076 18:41:15:724 error: LookupAccountNameW on SSHD account failed with 1789
> 10076 18:41:15:724 fatal: failed to retrieve client details
> 3100 18:45:05:663 error: LookupAccountNameW on SSHD account failed with 1789
> 3100 18:45:05:664 fatal: failed to retrieve client details
> 8092 18:57:06:595 error: LookupAccountNameW on SSHD account failed with 1789
> 8092 18:57:06:595 fatal: failed to retrieve client details

Failure is easy to resolve by connecting to the VPN and restarting ssh-agent, but it is an inconvenience.

**Comment by jochemd** [comment]
I forgot to mention: I just installed the Fall Creators Update and I can't quite determine whether this was a problem before or not.

**Comment by bagajjal** [comment]
error 1789 - ERROR_TRUSTED_RELATIONSHIP_FAILURE

Can you try the below URLs and see if it works?
https://community.spiceworks.com/how_to/108912-fix-the-trust-relationship-between-this-workstation-and-the-primary-domain-failed
https://support.microsoft.com/en-us/help/2771040/-the-trust-relationship-between-this-workstation-and-the-primary-domai

**Comment by jochemd** [comment]
Tried them, but didn't make a difference.

**Comment by jochemd** [comment]
I did a full uninstall, then installed 0.0.23.0 and now I am not experiencing the problem anymore.
