### ISSUE TITLE
SSH : Could not resolve hostname -: Name or service not known

### ISSUE THREAD

**Issue by DaburLal** [PowerShell/Win32-OpenSSH#954]
**Server OperatingSystem**
 `Windows 7

**Client OperatingSystem**
Windows 7 using Putty as secure shell client

After installing the OpenSSH, using automated installation steps for powershell, SSHD starts succesfully.

But as i enter any of the available commands, i get the following error:

ssh : Could not resolve hostname - : Name or service not known.

I am trying to connect to secure shell server(SSHD) using secure shell client (Putty)

Kindly guide me.

Thanks!

**Comment by manojampalam** [comment]
This is a client side issue. Refer Putty troubleshooting guidelines to take this further.

**Comment by bagajjal** [comment]
Enable the putty logs and debug further. 
In case if you are using domain user account then try like this,

ssh -l user@domain host (or)
ssh domain\user@host (or)
ssh user@domain@host

**Comment by DaburLal** [comment]
Once i run sshd , and then give ssh - l command on the same system, i still get the same error
