### ISSUE TITLE
Does ForceCommand really works for OpenSSH-Windows?

### ISSUE THREAD

**Issue by Lyova5** [PowerShell/Win32-OpenSSH#956]
**"OpenSSH for Windows" version**
0.0.23
 
**Server OperatingSystem**
Windows Server 2012 R2

**Client OperatingSystem**
Windows 8.1

**What is failing**
I'm trying to setup ForceCommand, but any command in ForceCommand forces client to hang.
Match User testuser
	ForceCommand dir

**Expected output**
I expect to see dir output.

**Actual output**
Client hangs to black windows without cmd greetings. If I comment ForceCommand with #, all is ok.

**Comment by manojampalam** [comment]
It should work. Try 
ForceCommand cmd /c dir

**Comment by Lyova5** [comment]
Ouch! Sorry, i thought that cmd is executed already.
