### ISSUE TITLE
Little failure in Wiki file Install-Win32-OpenSSH.md

### ISSUE THREAD

**Issue by xinrag** [PowerShell/Win32-OpenSSH#959]
Hello!

Don't know how to edit/contribute the wiki... so the issue here:

At point the point "Generate SSH host key" in Install-Win32-OpenSSH.md you should run the powershell script FixHostFilePermissions.ps1 with ...-ExecutionPolicy Bypass..., too. See the few lines above where we install and execude install-sshd.ps1.

Very little update... I know... (:

Regards, Stephan

PS: What is the best way to report thins and contribute to the wiki?

**Comment by manojampalam** [comment]
Thanks. Fixed.
