### ISSUE TITLE
Support Windows network authentication (Negotiate, NTLM, Kerberos)

### ISSUE THREAD

**Issue by manojampalam** [PowerShell/Win32-OpenSSH#96]

**Comment by dealboy** [comment]
+1

**Comment by hawicz** [comment]
Including Kerberos support would make this far more useful.

**Comment by mnaiman** [comment]
NTLM is good for non domain enviroment I guess

**Comment by mattpwhite** [comment]
Support for [GSS-API key exchange](https://www.ietf.org/rfc/rfc4462.txt) is critical for our shop to make any practical use of this fork.  OpenSSH supports this on *nix platforms, as do many commercial Windows SSH implementations and some PuTTY forks.  After you put in the (admittedly non-trivial) work to build a functioning cross platform Kerberos environment, it basically *just works*.  No one that has ever seen a setup like this would ever consider going back to explicit distribution (and hopefully rotation/revocation) of SSH keys across a large environment.

NTLM is not a viable alternative.  It potentially provides SSO, but not server authentication or credential delegation and is significantly less secure than Kerberos in general.

**Comment by KeithGlidewell** [comment]
Is there any timeline for when we might see GSSAPI/Kerb support?  Thanks.

**Comment by manojampalam** [comment]
Its not there yet in the horizon. What would be your client/server side GSSAPI providers?

**Comment by DomDupuis** [comment]
+1  (Kerberos is a must)

**Comment by mgkuhn** [comment]
Kerberos/GSSAPI authentication and ticket delegation is now working well with release [v7.9.0.0p1-Beta](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.9.0.0p1-Beta).

With that in place, does anyone actually really still need NTLM authentication, given how vulnerable that entire technology is in comparison to Kerberos? I can't think of a scenario where in addition to the existing three authentication methods (password, pubkey, Kerberos) NTLM still would add something useful nowadays.

**Comment by mnaiman** [comment]
As I wrote before, NTLM is good for non domain enviroment

**Comment by mnaiman** [comment]
WinRM supports NTLM too - allowed hosts solves problem of server authentication

**Comment by NoMoreFood** [comment]
All I can say is that I'm not interested in adding this myself.

**Comment by mattpwhite** [comment]
NTLM is actively harmful in most contexts in a domain environment (silent downgrades to an insecure protocol when Kerberos is not configured correctly) and, for ssh, doesn’t seem to make anything easier or more secure outside of one.  If someone does decide to implement it anyway, I would hope that it would default off and be governed by totally separate configuration knobs than the recently added Kerberos support.

**Comment by mgkuhn** [comment]
All the non-domain environments that I'm familiar with are so tiny that ssh public-key authentication is perfectly practical to manage. And as soon as your environment is not tiny enough any more to manually manage authorized_keys, I generally think that's when it is time to set up a Kerberos KDC (Active Directory, SAMBA, MIT Kerberos, Heimdahl, etc.), rather than try anything involving NTLM. Active Directory would become a vastly less dangerous and tricky-to-configure-correctly tool if Microsoft finally switched off NTLM in it.

**Comment by maertendMSFT** [comment]
Latest release supports Kerberos, we do not recommend NTLM.
