### ISSUE TITLE
sshd service cannot start, access is denied

### ISSUE THREAD

**Issue by mauro-miatello** [PowerShell/Win32-OpenSSH#960]
windows 2008 r2 std 64bit
openssh v0.0.23.0

i try to launch the service but i've Error 5: Access is denied like #672
i've tried from gui and from console
i've tried to add full access to sshd

noway

if I run sshd.exe -ddd from console it works

**Comment by mauro-miatello** [comment]
PS C:\OpenSSH> .\FixHostFilePermissions.ps1
  [*] C:\OpenSSH\sshd_config
      looks good

  [*] C:\OpenSSH\ssh_host_dsa_key
      looks good

  [*] C:\OpenSSH\ssh_host_dsa_key.pub
      looks good

  [*] C:\OpenSSH\ssh_host_ecdsa_key
      looks good

  [*] C:\OpenSSH\ssh_host_ecdsa_key.pub
      looks good

  [*] C:\OpenSSH\ssh_host_ed25519_key
      looks good

  [*] C:\OpenSSH\ssh_host_ed25519_key.pub
      looks good

  [*] C:\OpenSSH\ssh_host_rsa_key
      looks good

  [*] C:\OpenSSH\ssh_host_rsa_key.pub
      looks good

  [*] C:\Users\root\.ssh\authorized_keys
      looks good

   Done.

PS C:\OpenSSH> net start sshd
Errore di sistema 5.

Accesso negato.

**Comment by mauro-miatello** [comment]
solved
changed owner of the service with root (local administrator i've create) instead of sshd
give root accesso to secpol.msc > local policies > User Rights Assignment > Replace a process level token

**Comment by pmontrasio** [comment]
I had to do the same thing, thanks for posting the workaround. However it looks like a bug somewhere in the installation process.

**Comment by mauro-miatello** [comment]
this workaround works no more
and version 7.9 doesnt let me connect

**Comment by mauro-miatello** [comment]
i removed 7.9, installed 0.24
cleaned all, restored file permissions
service agent installed as system  service sshd as root
it works
