### ISSUE TITLE
How to login in ssh with elevated privileges

### ISSUE THREAD

**Issue by benvindo** [PowerShell/Win32-OpenSSH#962]
When I login in my server, he open a terminal cmd, I a need execute scripts but theses scripts needs that my user execute a cmd or powershell with elevated privileges. I tried used RunAs for execute script in cmd and powershell but he stay in processing all the time, I guess the command stay waiting accept a windows' confirmation for run privileges but de window don't show me because I'm use ssh to connect other my server. 
Anyone knows how can execute a file or login in ssh with elevated privileges?

**Comment by manojampalam** [comment]
IF you are using an admin account, you should have an elevated session. 

Make sure you set the registry entry specified here
https://support.microsoft.com/en-us/help/942817/how-to-change-the-remote-uac-localaccounttokenfilterpolicy-registry-se

**Comment by DarwinJS** [comment]
@manojampalam - is this registry setting in the setup instructions.  I don't remember seeing it anywhere?  I think the universal installer might be handling this by giving SSHD service user the user right to change tokens.

I also thought that SSHD always requested "HighestAvailable" in regard to elevation so if the user is admin they would automatically have an elevated setting?

Can you clarify because it seems like this setting is making a global system change that affects more than just SSHD.

If this reg change is required for certain conditions I would probably make it an option in the universal installer - but I've never seen it surface before.

Thanks,
D.

**Comment by manojampalam** [comment]
@DarwinJS let me follow up for the right guidance. I assumed its a known fact that remote administration using workgroup administrator accounts requires the above registry setting.

**Comment by SwooshyCueb** [comment]
As far as I can tell, this registry key isn't mentioned anywhere in the documentation: https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_overview

**Comment by keithzg** [comment]
As is unfortunately a habit with Microsoft documentation, the support.microsoft.com link above, https://support.microsoft.com/en-us/help/942817/how-to-change-the-remote-uac-localaccounttokenfilterpolicy-registry-se, no longer appears to be valid and merely returns a 404 (Microsoft's web admins seem allergic to leaving redirects behind so I have no idea if this means the documentation is gone or just moved).

**Comment by RomainFallet** [comment]
My solution to this was to set the key ConsentPromptBehaviorAdmin to 0:
![Capture](https://user-images.githubusercontent.com/6952638/78294831-52b72800-752b-11ea-82d1-6a22787bf90f.PNG)

**Comment by jdrch** [comment]
> As is unfortunately a habit with Microsoft documentation, the support.microsoft.com link above, https://support.microsoft.com/en-us/help/942817/how-to-change-the-remote-uac-localaccounttokenfilterpolicy-registry-se, no longer appears to be valid and merely returns a 404 (Microsoft's web admins seem allergic to leaving redirects behind so I have no idea if this means the documentation is gone or just moved).

I was able to find instructions by Googling the last part of that URL, `how-to-change-the-remote-uac-localaccounttokenfilterpolicy-registry-se`, which brought me [here](https://docs.oracle.com/en//database/oracle/oracle-database/21/cwwin/verifying-user-privileges-to-update-remote-nodes.html#GUID-01436EC2-8470-40C2-AABB-5FA99C71EF0E). Mad props to Oracle for the impeccable documentation. Following Step 1 worked for me.
