### ISSUE TITLE
Permission denied when trying to connect to SSHD using password method

### ISSUE THREAD

**Issue by leotxcosta** [PowerShell/Win32-OpenSSH#965]
**OpenSSH for Windows" version**
0.0.23.0

**Server OperatingSystem**
Windows Server 2008 Standard

**What is failing**
When I try to connect to the server using ssh or WinSCP I get a permission denied error.
I got this error running the service under my account and LocalSystem account. Currently I'm not able to run the service using NT SERVICE/SSHD account.

**Expected output**
Connect to SSHD successfully.

**Actual output**
That's the server output when I run it in debug mode.

PS. I replaced my actual username and domain with "myusername" and "mydomain"

debug1: Server will not fork when running in debugging mode.
Connection from ::1 port 57020 on ::1 port 22
debug1: Client protocol version 2.0; client software version OpenSSH_7.6
debug1: match: OpenSSH_7.6 pat OpenSSH* compat 0x04000000
debug1: Local version string SSH-2.0-OpenSSH_7.6
debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_INIT
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: KEX done
debug1: userauth-request for user myusername@mydomain service ssh-connection method none
debug1: attempt 0 failures 0
Failed none for myusername@mydomain from ::1 port 57020 ssh2
debug1: userauth-request for user myusername@mydomain service ssh-connection method keyboard-interactive
debug1: attempt 1 failures 0
debug1: keyboard-interactive devs
debug1: auth2_challenge: user=myusername@mydomain devs=
debug1: kbdint_alloc: devices ''
Failed keyboard-interactive for myusername@mydomain from ::1 port 57020 ssh2
debug1: userauth-request for user myusername@mydomain service ssh-connection method password
debug1: attempt 2 failures 1
debug1: failed to logon user: myusername domain: mydomain error:126
Failed password for myusername@mydomain from ::1 port 57020 ssh2
debug1: userauth-request for user myusername@mydomain service ssh-connection method password
debug1: attempt 3 failures 2
debug1: failed to logon user: myusername domain: mydomain error:126
Failed password for myusername@mydomain from ::1 port 57020 ssh2

**Comment by manojampalam** [comment]
@bingbing8 this seems to be related to the recent LogonUser changes. 

@leotxcosta please use the previous version for now.

**Comment by leotxcosta** [comment]
Thanks guys! Testing with the previous version it worked!

**Comment by DaburLal** [comment]
Hello, From where did you download previous version?? Thanks !!

**Comment by leotxcosta** [comment]
You can find it here: https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.22.0

**Comment by bingbing8** [comment]
@saurabhverma999 and @leotxcosta, are you running windows server 2008? Can you check if this file ("%windir%\system32\sspicli.dll") presents on your machine? Windows server 2008 is equivalent to Vista SP1.  Note that vista and below is out of scope for our project.

**Comment by DaburLal** [comment]
@bingbing8 , i am running it on Windows 7 and the file you mentioned is also present.

**Comment by leotxcosta** [comment]
@bingbing8 in fact sspicli.dll is not present in our server. I'm going to try running it in a Win 2012 R2 server to check if it works.

**Comment by leotxcosta** [comment]
Testing in Win Server 2012 R2 it worked successfully!

**Comment by bingbing8** [comment]
@saurabhverma999, I can't see the password auth issue on win7. Can you provide your trace?
@leotxcosta, win server 2008 is out of scope, but I fixed the password auth issue. but I think you will still see the service can't started on win server 2008.

**Comment by leotxcosta** [comment]
@bingbing8 no problem. As it worked in Win 2012 server, We decided to install it in our Win 2012 server. But thanks a lot for your help anyway.

**Comment by bingbing8** [comment]
@saurabhverma999,  close this issue since this is on windows 2008 and also the issue by loading sspicli.dll has been fixed. Please open a different issue if you still see it repro on win 7.
