### ISSUE TITLE
SSH fail to build with platform toolset "Visual Studio 2015 - Windows XP (v140_xp)"

### ISSUE THREAD

**Issue by ngugc** [PowerShell/Win32-OpenSSH#967]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**
Windows XP

**What is failing**
Fail to build with platform toolset "Visual Studio 2015 - Windows XP (v140_xp)"

**Expected output**
Be built successfully.

**Actual output**
2>------ Build started: Project: ssh, Configuration: Release Win32 ------
2>clientloop.c
2>C:\apps\openssh-portable\contrib\win32\win32compat\inc\sys/socket.h(8): fatal error C1083: Cannot open include file: 'WinSock2.h': No such file or directory
2>readconf.c
2>C:\apps\openssh-portable\contrib\win32\win32compat\inc\sys/socket.h(8): fatal error C1083: Cannot open include file: 'WinSock2.h': No such file or directory
2>ssh.c
2>C:\apps\openssh-portable\contrib\win32\win32compat\inc\sys/socket.h(8): fatal error C1083: Cannot open include file: 'WinSock2.h': No such file or directory
2>sshconnect.c
2>C:\apps\openssh-portable\contrib\win32\win32compat\inc\sys/socket.h(8): fatal error C1083: Cannot open include file: 'WinSock2.h': No such file or directory
2>sshconnect2.c
2>C:\apps\openssh-portable\contrib\win32\win32compat\inc\sys/socket.h(8): fatal error C1083: Cannot open include file: 'WinSock2.h': No such file or directory
2>wmain_common.c
2>C:\apps\openssh-portable\contrib\win32\openssh\..\..\..\contrib\win32\win32compat\wmain_common.c(33): fatal error C1083: Cannot open include file: 'Windows.h': No such file or directory
2>win32_sshtty.c
2>C:\apps\openssh-portable\contrib\win32\openssh\..\..\..\contrib\win32\win32compat\win32_sshtty.c(5): fatal error C1083: Cannot open include file: 'Windows.h': No such file or directory
2>win32-utf8.c
2>C:\apps\openssh-portable\contrib\win32\openssh\..\..\..\contrib\win32\win32compat\win32-utf8.c(6): fatal error C1083: Cannot open include file: 'Windows.h': No such file or directory

**Comment by manojampalam** [comment]
Sorry. XP support is out of scope for this project.
