### ISSUE TITLE
Disappearance of Repair-FilePermission and Dependability of OpenSSHUtils.psm1

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#968]
It looks like the function Repair-FilePermission is missing from the latest version of OpenSSHUtils.psm1.

I have a dependency on it in the universal installer.

This was an exported function - so publicly available for dependency.

In addition to breaking uninstall, this change leaves me wondering which of the current Repair-* functions are equivalent to the previously existing Repair-FilePermissions?

I would like to suggest the following:
- That going forward, exported functions from OpenSSHUtils.psm1 be treated similar to exposed APIs in any software - that they always be managed with backward compatibility in mind.  This is the only way that other automation will be able to take dependencies on it with peace of mind.
- In this specific case I think that function should have stayed for compatibility and have it call the combination of new, more granular functions that are functionally equivalent to the historical Repair-FilePermissions function + any quality or scope improvements that have been implemented by the new functions.

Thanks for providing OpenSSHUtils.psm1 and all the hard work that goes into maintaining it!

**Comment by DarwinJS** [comment]
@bingbing8 - or anyone familiar with the recent changes to OpenSSHUtils.psm1 - could someone let me know what functions I would call in the current code to get the equivalent functionality of the previous Repair-FilePermissions ?

Thanks.

**Comment by bingbing8** [comment]
@DarwinJS, Can you check where you get OpenSSHUtils.*? These two files have not been update since v0.0.21.0. Function Repair-FilePermission is still under exported. note that the function name is Repair-FilePermission instead of Repair-FilePermission**s**.

**Comment by joeyaiello** [comment]
Hey @DarwinJS, just finished talking offline with @bingbing8. I should start by saying that it's still not expected that Repair-FilePermission is gone. I have an open PR that actually does that at PowerShell/openssh-portable#242, but it's not in a mergeable state. 

Now, let's talk about what's desired from our end. We need a "MS-supported" way for people to both *install* and *configure* OpenSSH. 

I am 100% supportive of the work you do to make OpenSSH installable for Chocolatey, and I want to make sure that we work with you to avoid breaking Chocolatey users. Unfortunately (or fortunately, I guess), you've been so awesome about getting this Chocolatey package off the ground, that you've taken a dependency on a module that we really didn't deem "finished". To that end, we're going to have to break a few things before reaching the aspirational 1.x SemVer state that you allude to in your first bullet above. 

So, for installation, "MS-supported" means we'll have inbox mechanisms for future versions of Windows (specifically "features-on-demand") and (probably) an MSI for downlevel OS's (a la how PowerShell Core currently works). 

Now my current issue is that even for the shipping beta inbox FOD of the OpenSSH server, it's really hard to configure it and get it to work. To that end, we want to ship `OpenSSHUtils` as a signed, supported module on the Gallery for people to easily install.

In said module, I want to expose less of the helper functions that we currently export in OpenSSHUtils (my understanding is that everything was exported as a convenient way to get off the ground), as many of them are not properly prefixed. 

So now my questions to you:
* How are you using Repair-FilePermission today? 
* Is there some kind of helper function(s) that we could expose which accomplishes the same task without needing to call Repair-FilePermission directly?
* If not, could you help me come up with a name that isn't so generic? As it currently stands, the cmdlet sounds like something for repairing broken ACLs. 
* Are there any other "internal" functions you're calling that we might need to rename? I.e. Other than Repair-FilePermission, what do you need that's [not in this FunctionsToExport](https://github.com/PowerShell/openssh-portable/pull/242/files#diff-a39d028b6283cae93036077e5db340a0R9)?

Hopefully that all makes sense. If it doesn't, I'm more than happy to adjust or clarify.

**Comment by DarwinJS** [comment]
@joeyaiello - thanks for looking into this.

I must apologize!  I did a cursory glance at the code and thought I could not find the function.

After doing more testing I have found that the uninstall I wrote does not search for the module in the correct place.

So apologies to @bingbing8 and your team!

Your questions to me are still relevant, so here are some thoughts.

FYI - An eons-long theme in software deployment automation is: **Getting "install" tested under real-world condition is hard.  Getting "upgrade" and "uninstall" tested under real-world conditions is even harder.**  To add hardship to that they are a typical **Murphy-Pattern** (i.e. the hardest part of install to get right).  You will see this in the below in my response to "Why do you need to call Repair-FilePermission directly?"  Way too much install / upgrade / uninstall testing is done under conditions that do not emulate actual installs - for example, many software distribution systems use the "SYSTEM" account for installation and do it under a Service - both of which can cause edge case issues - but they are rarely tested as part of regular development.

- In the installation I call https://github.com/PowerShell/Win32-OpenSSH/blob/L1-Prod/contrib/win32/openssh/FixHostFilePermissions.ps1 - because it seems like the "official" way for interfacing with OpenSSHUtils to ask it to do all the fixups.  It depends on OpenSSHUtils module.  
- Along that line if you are going to bundle this up, then I would suggest that the meta-functionality in FixHostFilePermissions.ps1 and FixUserFilePermissions.ps1 needs to become exposed functions in OpenSSHUtils rather than separate scripts.  (Backwards compatibility could be maintained by making these simply load the module and call the right function.)  To be clear these are two helper scripts that ship with OpenSSH along side OpenSSHUtils.psm1
- Tangent: FYI - the permissions set by FixUserFilePermissions.ps1 should be tested with a few OTHER windows SSH clients - to understand compatibility - and if it is incompatible - why?  Git's built-in ssh would be a huge one, but there are also other common user oriented openssh clients.
- For Repair-FilePermission usage - in the uninstallation I can't assume that the Uninstalling user id has permissions to the properly secured key files because I don't know who they are.  I do assume they are admin.  I also didn't want to assume permissions hadn't been adjusted by custom scripts - so they might pass sshd.exe's checks, but be stricter than what opensshutils module sets - either by accident or on purpose by custom scripts.  So I directly use Repair-FilePermissions because it is the only way I can force permissions to these files with **the current user id doing the uninstall - regardless of what that user id is - so a completely clean uninstall is possible.  So I believe there is a special need during uninstall to need to "undo" the proper permissions and this is how I accomplished it - it would be awesome if this need was directly or indirectly accounted for in opensshutils.**
- For CMDLet naming for all the opensshutils functions that have to do with correcting permissions, I would probably tack toward "Ensure-SSH*" - so "Ensure-SSHSecuredHostkeyPermissions", etc.  This is because "Repair" implies I know they are broken, "Ensure" implies "I don't care their current state - just fix it if it's wrong"  Using SSH next seems to indicate the scope of the CMDLets.

Some other items to consider in this library - these are helpers I've written to be sure OpenSSH can install in all scenarios from Win7+PSH2 through Nano Server - the two extremes in which it always seems require special adaptation:
- Setting user rights for SeServiceLogonRight and SeAssignPrimaryTokenPrivilege in a way that is *compatible across all supported distros*.  I believe that there are scenarios where this is required - I think Windows 7 and/or Nano seemed to require the logon as a service right, even though "NT SERVICE\sshd" should implicitly have it on most targets.  I do this in https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/tools/AddAccountToAssignPrimaryToken.ps1 and https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/tools/AddAccountToAssignPrimaryToken.ps1 - **but I hear rumblings that my code may not be reliable**.  I tried to adapt the DSC code for local policy that your team developed (which is known to work in Nano) - but I ran into errors.  That code is here: https://github.com/PowerShell/SecurityPolicyDsc/tree/master/DSCResources/MSFT_UserRightsAssignment
- I coded up an externally callable function that let's one search for a suitable shell executable to set as the default shell for OpenSSH. I purposely made it a separate file so it could be called after upgrading PowerShell Core - but it can also be used by any automation that upgrades any exe being used as the default shell.  By having this as a part of opensshutils you can apply some guidance.  For instance, my function requires a "yes I don't care about security" confirmation switch if setting the shell exe to something outside of Windows built-in "admin whitelisting" permissions (ie anything not in a Program Files folder or a system32 folder).  Although my implementation is not *simple* I think it encompasses how I might need to perform this task in real-world scenarios.  Here is the code with comment based help: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/tools/Set-SSHDefaultShell.ps1
- I use this helper to detect anything listening on port 22 (and check whether it is presumably a previous version of win32-openssh) - I had to find code and customize it myself for 100% compatibility for Win7 through Nano: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/tools/Get-NetStat.ps1
- Ensure that NONE of the syntax in OpenSSHUtils is post-PowerShell 2.  I have applied a lot of fixes that are simply regressions to PSH 2.0 "style" syntax that then work fine through PowerShell 5.1.

**Comment by bingbing8** [comment]
@DarwinJS, looks like you are using `secedit.exe` and cim instance in your [script](https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/tools/AddAccountToAssignPrimaryToken.ps1) and [script](https://github.com/PowerShell/SecurityPolicyDsc/tree/master/DSCResources/MSFT_UserRightsAssignment), but `secedit.exe` is not available on latest Nano server. cim instance cmdlet is not available on all OS either, for ex, win7+psh2. Please see how I set user rights for  for SeServiceLogonRight and SeAssignPrimaryTokenPrivilege [here](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/openssh/install-sshd.ps1). it works both on win7 and Nano server.

**Comment by DarwinJS** [comment]
@bingbing8 - thanks for the information on secedit and the code reference.  I will work it into my code.

Your code and the Add-Privilege function would be great additions to OpenSSHUtils!

Even though code samples for setting User Privileges is common, I think this bit would be a great addition to OpenSSHUtils because the effort to ensure that the code works across all OpenSSH targets is a core value of OpenSSHUtils !

**Comment by DarwinJS** [comment]
FYI - Get-UserSID from https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/openssh/OpenSSHUtils.psm1 is also very valuable as an export.

**Comment by joeyaiello** [comment]
@DarwinJS sorry for the lack of an update. We had some conflicting internal requirements here that I had to work through. 

I know this point really stinks, but I do want to make it again for clarity: we're prepared to make breaking changes and rework the module in order to "do the right thing" from a PowerShell design perspective. (And thanks to you, I've got a ton of suggestion above for how we should do this! Some of your design ideas are great, we should get an issue going to ) I'd like to limit the impact to you and the Chocolatey installer, but I also can't optimize for your specific use case (at least, not in the short term, I'll explain below).

We agree those are useful helper functions, but we can't justify "shipping" an OpenSSHUtils module to the Gallery that exposes them given their generality and "one-off-ness". That being said, we need the module published to the PowerShell Gallery so that MSFT customers have an official way to configure the Beta FOD. **Therefore, we plan on publishing the OpenSSHUtils module as a 0.1 release to the Gallery with a limited set of exported functions** (see PowerShell/openssh-portable#251).

For the time being, we're holding off the merge on that PR in order to avoid breaking you in an upcoming release. But if it's possible, we'd really appreciate that you move to the syntax we use to call these internal functions from [within our tests](https://github.com/PowerShell/openssh-portable/pull/251/commits/4b84ffff7f1d47f9e1f006bb29afeaadab54dd55#diff-2e5f680f249e1ca92315ea58cb45b0f9R49):

```powershell
$m = Get-Module OpenSSHUtils
& ($m) Get-UserSID ...
```

If you could let us know when it's okay to merge (implying it will be in the next release on Win32-OpenSSH), please let us know. Better yet, if you could decouple and pick up the Gallery version that would be best. 

More notes about configurability:

In a future release (not sure how soon via GitHub builds, but certainly by the next release of Windows), we are planning to implement functionality that will auto-generate host keys at server start time if they don't exist. This should eliminate the need for bootstrapping host keys, but we're not totally closed on how it should work.

In the fullness of time, we also want to do an MSI-based installer for downlevel platforms. This should handle as much of the bootstrapping logic as possible. I'd expect that wrapping a well-built MSI is significantly easier than maintaining the logic you currently have in the Chocolatey package. Is that accurate, or am I misguided there? 
(Side note: thank you for all the pointers to your more intelligent logic. As we discussed a million years ago, I still would love to work with you in making sure that it finds its way into our MSI logic.)

However, neither of those points will solve the authorized_keys ACLing problem, which we'll have to continue to address via the OpenSSHUtils (which I'd also expect to find its way inbox at some point).

I'm hoping that the plan we landed on works for you okay. Please give me any info for what of this doesn't work for you.

**Comment by DarwinJS** [comment]
@joeyaiello - thanks for the consideration - very appreciated!

Some thoughts...
- I will work to be compatible very quickly - in order to use the exact code as provided through github I will likely just lag a little in the provision of the package when it occurs.

"**Better yet, if you could decouple and pick up the Gallery version that would be best.**"
- I'd like to stick with what's in the package to always be on the same update cycle.  Additionally, in order to serve clients who can't download from the gallery (all non-PSH5), the code will need to continue to ship with the product for a long time, correct?

**"This should eliminate the need for bootstrapping host keys, but we're not totally closed on how it should work."**
- if you do this you would either need to take a dependency from the sshd.exe to the opensshutils.psm1 to make the permissions changes OR integrate the permissions code into sshd.exe.  If you do the second I would really like to see ALL file permissions code and possible all special permissions code inside one of the openssh EXEs so there is not two code bases doing the same thing differently.

**"I'd expect that wrapping a well-built MSI is significantly easier than maintaining the logic you currently have in the Chocolatey package. Is that accurate, or am I misguided there?"**
Unfortunately, I would have to say I feel it is misguided - as I did in the previous conversation you are referencing.
Here is a summary of why
- MSI does not run on all targets - most notably nano.
- at a minimum, your permissions settings requirements are going to require custom actions.  Managed code custom actions and powershell custom actions are hackable, but not officially supported.  So you'd be into C++ or an EXE.  
    - Design baed counter argument to this *specific part* of the concern is if you do code the permissions code into one or more of the openssh binaries you would be able to call it as a custom action during install.  In this case I would advise an EXE or a DLL that is ALSO callable by RunDLL - so that your customers can use these routines as well to re-assert permissions.   Hmmm - wonder if runddl is on nano?  Reminder - EXE custom actions are "out of process" while DLLS are "in process" - so DLL custom actions are more wired up during an MSI install to be able to bubble up better error messages without instrumenting a slew of exit codes - the downside to DLL again being less ability for customers to use this code.
- also you will need custom action code to do things like "scan if port 22 is currently in use" - and many other things that you can see in the universal installer code.
- proper leveraging of MSI upgrade over and patching scenarios requires MUCH MORE METICULOUS **LONG TERM** management of the GUIDs assigned to each code component (msi 'component').
- beyond components there are also many other ways to 'go wrong' when building an MSI package - openssh is so simple, you shouldn't hit too many.
- From a deployment perspective (openssh users), the most reliable MSI upgrades are to, via script, uninstall the previous version and install the next.  Many organizations do this as a matter of course because so many vendor's MSIs can't manage to do the previous bullet (meticulous release-to-release msi component management) well for the long term.  This is a hassle (that is killing me right this month on a enterprise package I support for DevOps server automation for a package we install on EVERY server).
- From a deployment perspective if you do attempt to support official MSI "minor upgrades" and "major upgrades" - they require different command lines at deployment time - so I have to know BEFORE calling the installer if the current system has a previosly installed copy and call /f for a minor upgrade and /i for a major.  Another reason many shops simply uninstall and reinstall.
- in my experience with packaging it, openssh "install over" requirements are very simple, but you still inherit the above challenges if you want to do your simple requirements via MSI.
- you will need a package per bitness (or hack the 32-bit package to notice a 64-bit and install the right binaries - since openssh does not do COM and very little registry stuff, this might be doable) - but I think you're all ready doing that.
- by the time you take measures to offset MSI's downsides, it will be functioning as mainly as a .zip - kind of like the PowerShell Core now.  At that point I don't understand the point of choosing MSI - the future is moving to ZIP archives - App-V 5, NuGet, .appx,
 .docx (OPC - Open Packaging Container - I know OPC didn't take a strong hold - but still much more transparent than .MSI)
- you lose community support on the installer - even if you store the source in SCM compatible wix format - few have the desire to learn this old technology - but especially if they have to learn wix's specific source implementation on top.
- quite frankly MSI is very non-DevOp-ish - and for as much as the team is wary about putting in Windows specific features (e.g. - having some registry based config overrides so that GPO can hook up and push policy BEFORE sshd.exe is installed, rather than having to be constantly scheduled to come in after) - this seems like a notable departure towards one of the most legacy and increasingly challenging technologies to package in.

For an installer I would suggest something similar to how I am doing the universal installer
- make / keep the installer logical code as PowerShell that runs on all target platforms.
- package it in nuget .nupkg (which is just a zip)
- place the installation script inside
- nuget cannot run an internal script - but you could put a wrapper around it to call the PowerShell based installer.
- for non gallery installs the .nupkg can be further bundled with nuget.exe - but it can also just be "unzipped" directly
- I know this might make windows normal servicing channels a little more challenging - but personally I would rather take an innovative look at how I might unzip a package and run a powershell under Windows Update than hamstring the other deployment channels with an MSI.
- it is more infrastructure as code compatible because everyone can inspect the installation code
- you will get more community involvement for fixing installer bugs

I have built MSI packages and taught it to admins for over 15 years - I think its time is long done on the server / DevOps side of the house ;)

PS - Unaccounted for in the universal installer:
- for any installer you will have some tech debt if you stay with "C:\Program Files\OpenSSH" due to the possibility of someone else being there.  I have avoided this by staying with the original "C:\Program Files\OpenSSH-Win<BITNESS>" in the universal installer.
- properly splicing in defaults for new configuration items if and when necessary - without disturbing existing config.

**Comment by DarwinJS** [comment]
It seems PowerShell/openssh-portable#251 is not merged for 1.0.0.0 - does that mean that I should not use the updated module reference syntax in packaging 1.0.0.0 ?

There are a lot of changes for 1.0.0.0 - so still figuring out what it all means for the packaging.

**Comment by manojampalam** [comment]
my two cents.. we've gotten the new privilege separation model earlier than we thought. This makes the file permissions on Windows very much inline with how they are on Unix. One would not find any use from this utility in the default 99% of the cases. 
- Host keys are now automatically generated (if they dont already exist), with the right permissions. 
- User keys and authorized_keys have always been generated with the right permissions.

Starting from version 1.0.0.0, there would be no need for any configuration migration, since the service config now sits separate and isolate in a different folder, and is untouched during OpenSSH version updates. The would also be no changes to how file permissions are enforced, going forward.

Given this, should we modify/rename this utility and make its use case to just - migrate config from 0.0.* versions to 1.0.* versions

**Comment by DarwinJS** [comment]
@manojampalam - if I am understanding you correctly, then I have a possible consideration.

Although permissions on keys are set during the new creation routine - how do they get corrected if someone messes them up or if I have to restore them from backup?

In some cases (like the massive GitLab instance I help manage) having host keys change would be a big pain.

I would say the ability to reassert permissions on an **existing** key set is important in the full lifecycle of managing SSH at a large scale.

Is it possible to have the key generation processes to be triggered to simply correct permissions on existing keys?  Obviously it should require admin permissions and a switch so that it does not happen automatically against keys that have been tampered with or replaced.

The ability to reassert something like this and do only the required fixups is very much a part of DevOps.

**Comment by manojampalam** [comment]
Agreed. But at this point, we are not different than Unix (in terms of file permissions). I haven't come across a utility on Unix that does complete file permission tuning. Perhaps its simple to fix up file permissions (chmod), compared to multiple/confusing icacls on Windows?

**Comment by DarwinJS** [comment]
@manojampalam - yes it is a simple chmod.  However, the tough part of this is that it is not easy to find information on the equivalent Windows file permissions that would satisfy the chmod statement (I have tried using google).

**Comment by maertendMSFT** [comment]
This is no longer need, the permissions are set correctly
