### ISSUE TITLE
CreateService failed 1073

### ISSUE THREAD

**Issue by chmac** [PowerShell/Win32-OpenSSH#97]
When I reach the `.\sshd.exe install` step I see this error:

    CreateService failed 1073

Not sure what the cause is, or how to fix. I'm running this in an "administrator" power shell...

**Comment by manojampalam** [comment]
Did you have a prior install already? Try doing a sshd.exe uninstall first.

**Comment by chmac** [comment]
We probably did, I think it was installed by cygwin, guessing the error was on my side...
