### ISSUE TITLE
Connection Reset error when connecting to SSHD - Cannot create process (1349)

### ISSUE THREAD

**Issue by leotxcosta** [PowerShell/Win32-OpenSSH#970]
**OpenSSH for Windows" version**
0.0.22.0

**Server OperatingSystem**
Windows Server 2008 Standard

**What is failing**
I get a "connection reset" error when I try to connect to SSHD running as service (even in debug mode - DEBUG3) or via command line. However, If I run it via command line in debug mode (sshd -d), I can establish the connection successfully.

Looking at debug logs, I found the following error:
21312 19:38:49:116 debug1: Executing command: C:\\Program Files\\OpenSSH\\sftp-server.exe
21312 19:38:49:116 fatal: ERROR. Cannot create process (1349).\n

[sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/1507757/sshd.log)

I don't know if it makes sense but checking the session.c file, it looks like it may have some issue related to the code below:

if (debug_flag)
			create_process_ret_val = CreateProcessW(NULL, exec_command_w, NULL, NULL, TRUE,
				DETACHED_PROCESS, NULL, pw_dir_w,
				&si, &pi);
		else /* launch as client user context */
			**create_process_ret_val = CreateProcessAsUserW(hToken, NULL, exec_command_w, NULL, NULL, TRUE,
				DETACHED_PROCESS , NULL, pw_dir_w,
				&si, &pi);**

I've already tried v0.0.23, but I'm getting permission denied error when trying to connect to SSHD.

**Comment by manojampalam** [comment]
What context are you running sshd as ?
1349 implies that the account, that sshd is running as, does not have the privileges to launch a session process as the user.
Installation scripts should assign this privilege to sshd account. 

Try the following steps to manually assign:
- Open control panel and navigate to
  - Administrative Tools >  Local Security Policy > Local Policies > User Rights Assignment.
- Double click **Replace a Process Level Token**
- Add **NT Service\SSHD**  

Reopen if you still see this issue.
