### ISSUE TITLE
Terminal issue in Windows Cygwin if the output of a command would otherwise scroll past the bottom of the terminal Window, the output overwrites itself on the last line.  If the output would also exceed the width of the terminal when this happens, the output echoes every character change on a new line instead of wrapping.

### ISSUE THREAD

**Issue by surendrasake** [PowerShell/Win32-OpenSSH#971]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**

**What is failing**

**Expected output**

**Actual output**

**Comment by surendrasake** [comment]
[4;53H
[5;1H                           [5;53H
[6;1H                            [6;53H
[7;1H                            [7;53H[7;53Hpowershell Set-ExecutionPoli[7;54Howershell Set-ExecutionPoli[7;55Hwershell Set-ExecutionPoli[7;56Hershell Set-ExecutionPoli[7;57Hrshell Set-ExecutionPoli[7;58Hshell Set-ExecutionPoli[7;59Hhell Set-ExecutionPoli[7;60Hell Set-ExecutionPoli[7;61Hll Set-ExecutionPoli[7;62Hl Set-ExecutionPoli[7;63H Set-ExecutionPoli[7;64HSet-ExecutionPoli[7;65Het-ExecutionPoli[7;66Ht-ExecutionPoli[7;67H-ExecutionPoli[7;68HExecutionPoli[7;69HxecutionPoli[7;70HecutionPoli[7;71HcutionPoli[7;72HutionPoli[7;73HtionPoli[7;74HionPoli[7;75HonPoli[7;76HnPoli[7;77HPoli[7;78Holi[7;79Hli[7;80Hi
[8;1H                                                        [8;2Hy Unrestricted -Force                                                          [8;3H Unrestricted -Force                                                          [8;4HUnrestricted -Force                                                          [8;5Hnrestricted -Force                                                          [8;6Hrestricted -Force                                                          [8;7Hestricted -Force                                                          [8;8Hstricted -Force                                                          [8;9Htricted -Force                                                          [8;10Hricted -Force                                                          [8;11Hicted -Force                                                          [8;12Hcted -Force                                                          [8;13Hted -Force                                                          [8;14Hed -Force                                                          [8;15Hd -Force                                                          [8;16H -Force                                                          [8;17H-Force                                                          [8;18HForce                                                          [8;19Horce                                                          [8;20Hrce                                                          [8;21Hce                                                          [8;22He                                                          
[9;1H
[10;1H                           [10;53H
[11;1Hadministrator@CONFIG3BAY1DEV C:\Users\Administrator>                            [11;53H[11;53Hpowershell Get-ExecutionPoli[11;54Howershell Get-ExecutionPoli[11;55Hwershell Get-ExecutionPoli[11;56Hershell Get-ExecutionPoli[11;57Hrshell Get-ExecutionPoli[11;58Hshell Get-ExecutionPoli[11;59Hhell Get-ExecutionPoli[11;60Hell Get-ExecutionPoli[11;61Hll Get-ExecutionPoli[11;62Hl Get-ExecutionPoli[11;63H Get-ExecutionPoli[11;64HGet-ExecutionPoli[11;65Het-ExecutionPoli[11;66Ht-ExecutionPoli[11;67H-ExecutionPoli[11;68HExecutionPoli[11;69HxecutionPoli[11;70HecutionPoli[11;71HcutionPoli[11;72HutionPoli[11;73HtionPoli[11;74HionPoli[11;75HonPoli[11;76HnPoli[11;77HPoli[11;78Holi[11;79Hli[11;80Hi
[12;1Hcy                                                                              [12;2Hy                                                                              
[13;1H[13;1HUnrestricted

**Comment by surendrasake** [comment]
like this Junk and escape sequences are coming and output is wrapping up in logfile.


                        [4;53H
[5;1H                           [5;53H
[6;1H                            [6;53H
[7;1H                            [7;53H[7;53Hpowershell Set-ExecutionPoli[7;54Howershell Set-ExecutionPoli[7;55Hwershell Set-ExecutionPoli[7;56Hershell Set-ExecutionPoli[7;57Hrshell Set-ExecutionPoli[7;58Hshell Set-ExecutionPoli[7;59Hhell Set-ExecutionPoli[7;60Hell Set-ExecutionPoli[7;61Hll Set-ExecutionPoli[7;62Hl Set-ExecutionPoli[7;63H Set-ExecutionPoli[7;64HSet-ExecutionPoli[7;65Het-ExecutionPoli[7;66Ht-ExecutionPoli[7;67H-ExecutionPoli[7;68HExecutionPoli[7;69HxecutionPoli[7;70HecutionPoli[7;71HcutionPoli[7;72HutionPoli[7;73HtionPoli[7;74HionPoli[7;75HonPoli[7;76HnPoli[7;77HPoli[7;78Holi[7;79Hli[7;80Hi
[8;1H                                                        [8;2Hy Unrestricted -Force                                                          [8;3H Unrestricted -Force                                                          [8;4HUnrestricted -Force                                                          [8;5Hnrestricted -Force                                                          [8;6Hrestricted -Force                                                          [8;7Hestricted -Force                                                          [8;8Hstricted -Force                                                          [8;9Htricted -Force                                                          [8;10Hricted -Force                                                          [8;11Hicted -Force                                                          [8;12Hcted -Force                                                          [8;13Hted -Force                                                          [8;14Hed -Force                                                          [8;15Hd -Force                                                          [8;16H -Force                                                          [8;17H-Force                                                          [8;18HForce                                                          [8;19Horce                                                          [8;20Hrce                                                          [8;21Hce                                                          [8;22He                                                          
[9;1H
[10;1H                           [10;53H
[11;1Hadministrator@CONFIG3BAY1DEV C:\Users\Administrator>                            [11;53H[11;53Hpowershell Get-ExecutionPoli[11;54Howershell Get-ExecutionPoli[11;55Hwershell Get-ExecutionPoli[11;56Hershell Get-ExecutionPoli[11;57Hrshell Get-ExecutionPoli[11;58Hshell Get-ExecutionPoli[11;59Hhell Get-ExecutionPoli[11;60Hell Get-ExecutionPoli[11;61Hll Get-ExecutionPoli[11;62Hl Get-ExecutionPoli[11;63H Get-ExecutionPoli[11;64HGet-ExecutionPoli[11;65Het-ExecutionPoli[11;66Ht-ExecutionPoli[11;67H-ExecutionPoli[11;68HExecutionPoli[11;69HxecutionPoli[11;70HecutionPoli[11;71HcutionPoli[11;72HutionPoli[11;73HtionPoli[11;74HionPoli[11;75HonPoli[11;76HnPoli[11;77HPoli[11;78Holi[11;79Hli[11;80Hi
[12;1Hcy                                                                              [12;2Hy                                                                              
[13;1H[13;1HUnrestricted

**Comment by bagajjal** [comment]
@surendrasake - 
Please provide the steps to reproduce. 
Are you using the ssh provided by the Cygwin?

**Comment by bagajjal** [comment]
Any update on this?

**Comment by manojampalam** [comment]
Please reopen with requested information.
