### ISSUE TITLE
Few More Wiki Fixes

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#972]
On this page: https://github.com/PowerShell/Win32-OpenSSH/wiki the link to "Alternative installation using Chocolatey" in the right hand navigation bar is CORRECT, while the link under the same text in the main body is incorrect.

Could we also change the text to "Alternative installation using the universal installer"

Then, on this page: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

In step 2, the chocolatey package is referenced and then immediately after "For compatibility issues on Nano see issues on Nano.".  This has the effect of appearing to link the Universal Installer ("Chocolatey Package") to compatibility issues with Nano, when in fact one of the benefits of using the Universal installer is that these issues are all handled correctly.

Also Step 2 references "If you're interested in a PowerShell script to automate installation and configuration check out this issue.".  The Universal installer provides the same functionality (installation with pure powershell) - but is maintained and debugged for Win7+PSH2 through Nano.  So it seems it might be better to use the Universal installer.  

How about replacing the text for #2 with:

"2. Download the latest build of OpenSSH."

If you still want to draw attention to the alternative install on this page, maybe a preface comment to the entire list list like:

Note: A community maintained universal installer is available to perform these steps - it is tested on Windows 7 with PSH 2 through Nano Server. [See instructions here](https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/readme.md).

**Comment by manojampalam** [comment]
Thanks. Updated titles and wiki.

**Comment by DarwinJS** [comment]
@manojampalam - thanks.  I think the previous reference to the universal installer as a note at the top of the install page (right before the install steps) was very helpful so that someone does not start down the long road of automating it themselves before they realize there is an automated install available.

Here is the page I mean: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH
