### ISSUE TITLE
SSH Client fails to use existing id_rsa key

### ISSUE THREAD

**Issue by dac514** [PowerShell/Win32-OpenSSH#973]
**"OpenSSH for Windows" version**
Client: 0.0.18.0
 
**Client OperatingSystem**
Windows 10 Pro

**What is failing**
I installed the client, ***not the server***, [following these steps](https://www.thomasmaurer.ch/2017/11/install-ssh-on-windows-10-as-optional-feature/). 
Previously, I am a Git for Windows user and I already have an id_rsa key in ~/.ssh. It is paraphrase protected. 

**Expected output**
The client should ask me for my paraphrase. Ie.
> Enter passphrase for /c/Users/ME/.ssh/id_rsa:
> Identity added: /c/Users/ME/.ssh/id_rsa (/c/Users/ME/.ssh/id_rsa)

**Actual output**
key_load_public: invalid format
Unable to negotiate with x.x.x.x port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256

**Comment by manojampalam** [comment]
Windows inbox Beta version currently supports one key type (ed25519). 
Please stay tuned for more info from @joeyaiello 

Also, as @drichardson found below, there is an issue with passphrase protected private keys. As a work around, create passphrase-less private keys and register them with ssh-agent (this will encrypt and persistently store the private keys, so you don't have to register them again). Once the private key is registered, it could be deleted or moved to a safer location.

**Comment by drichardson** [comment]
I have the same problem with RSA and ed25519 keys that have passphrases on them. It seems that the beta version only supports keys without passphrases.

**Comment by bagajjal** [comment]
@drichardson - Are you using windows inbox openssh (or) you downloaded from our GitHub page?

**Comment by drichardson** [comment]
I installed _OpenSSH Client (Beta)_ from _Apps & features > Manage optional features_ on Window 10. I assumed this github project is the source for that, but perhaps I'm mistaken.

```
PS> Get-Command ssh

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ssh.exe                                            0.0.18.0   C:\WINDOWS\System32\OpenSSH\ssh.exe

PS> C:\WINDOWS\System32\OpenSSH\ssh.exe -V
OpenSSH_7.5p1, without OpenSSL
```

**Comment by DrPizza** [comment]
It's failing to work with either my RSA key or my ed25519 key.

```

C:\Users\DrPizza\.ssh>dir
 Volume in drive C has no label.
 Volume Serial Number is 200D-0382

 Directory of C:\Users\DrPizza\.ssh

14/12/2017  12:00    <DIR>          .
14/12/2017  12:00    <DIR>          ..
14/12/2017  12:01               420 id_ed25519
14/12/2017  12:00             3,239 id_rsa
14/12/2017  11:33               126 known_hosts
               3 File(s)          3,785 bytes
               2 Dir(s)  2,573,890,686,976 bytes free

C:\Users\DrPizza\.ssh>ssh -v user@lunix.quiscalusmexicanus.org
OpenSSH_7.5p1, without OpenSSL
debug1: Connecting to lunix.quiscalusmexicanus.org [137.135.108.74] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\DrPizza/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\DrPizza/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\DrPizza/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\DrPizza/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\DrPizza/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\DrPizza/.ssh/id_ed25519-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.5
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.2 pat OpenSSH* compat 0x04000000
debug1: Authenticating to lunix.quiscalusmexicanus.org:22 as 'user'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-ed25519 SHA256:58qRN+qo2e6TjHcYFfwy4F6+cl1ec4MCZoorWuuF+G0
debug1: Host 'lunix.quiscalusmexicanus.org' is known and matches the ED25519 host key.
debug1: Found key in C:\\Users\\DrPizza/.ssh/known_hosts:1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: pubkey_prepare: ssh_fetch_identitylist: communication with agent failed
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: C:\\Users\\DrPizza/.ssh/id_rsa
Load key "C:\\Users\\DrPizza/.ssh/id_rsa": invalid format
debug1: Trying private key: C:\\Users\\DrPizza/.ssh/id_dsa
debug1: Trying private key: C:\\Users\\DrPizza/.ssh/id_ed25519
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
user@lunix.quiscalusmexicanus.org: Permission denied (publickey).
```

Both keys (in putty format) work fine in PuTTY.

**Comment by robertpeteuil** [comment]
This may only be an issue with the debug output, but the key-value displayed shows two different delimiting character schemes (1/2 windows + 1/2 POSIX):

```
debug1: Trying private key: C:\\Users\\DrPizza/.ssh/id_dsa
```

- The first half (User Home Directory) is correctly using windows path delimiting characters `\\`
  - this is likely populated by a function/API that checks or is platform specific
- The second half (`.ssh` and `id_rsa`) is using POSIX path delimiting characters  `/`
  - this is may be hard-coded somewhere (from the original BSD version)

**Comment by bagajjal** [comment]
@robertpeteuil - Different delimiters is a display issue but not a functionality issue.
As @manojampalam  mentioned, Windows inbox Beta version currently supports one key type (ed25519).

One key thing to focus is we support only utf-8 encoding file format .

**Comment by robertpeteuil** [comment]
@bagajjal - thanks for the clarification.   I'm guessing you saw my post via email notification? 

I deleted it almost immediately as I realized the key was sucesfully read earlier in the log.

**Comment by bagajjal** [comment]
@DrPizza - As per logs ed25519 is not found.
debug1: identity file C:\\Users\\DrPizza/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory

**Comment by DrPizza** [comment]
@bagajjal Yes, that's why I included the directory listing before the log. Why is the file not found? It's there, as the directory listing shows.

**Comment by bagajjal** [comment]
@DrPizza  - ah, missed that (directory listing)..
can you please share DEBUG3 (-vvv) enabled ssh logs
"ssh -vvv user@lunix.quiscalusmexicanus.org"

**Comment by DrPizza** [comment]
I'm not sure I can. It's now connecting without issue, using the ed25519 key. I haven't knowingly changed anything since yesterday, so I'm not sure what's making it work now.

**Comment by bagajjal** [comment]
@DrPizza - Good to know that its working now.. It would be great if you can update your [blog](https://arstechnica.com/gadgets/2017/12/microsoft-quietly-snuck-an-ssh-client-and-server-into-the-latest-windows-10/) so that people will not be missguided.

**Comment by joeyaiello** [comment]
Got the blog published: https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/

**Comment by Cambridgeport90** [comment]
Love this one? I can’t believe it’s coming together nicely. Thank God.

**Comment by massimonewsuk** [comment]
Is there any update on when RSA keys will be supported? So for example the standard ones that AWS generates for you.

**Comment by manojampalam** [comment]
GitHub releases have full support for all key types. RSA keys are supported too.

**Comment by cdhunt** [comment]
I'm not sure if this is related, but I cannot add any keys to ssh-agent.

v1.0.0.0-Beta

```
Could not add identity "C:\Users\Chris.Hunt/.ssh/id_rsa": communication with agent failed
Could not add identity "C:\Users\Chris.Hunt/.ssh/id_ed25519": communication with agent failed
```

```
Status   Name               DisplayName
------   ----               -----------
Running  ssh-agent          ssh-agent
```

**Comment by Cambridgeport90** [comment]
I’ll run a test for you guys of this when I get home in a bit as well.

**Comment by Suncatcher** [comment]
@bagajjal 
> Windows inbox Beta version currently supports one key type (ed25519)

Can one convert existing RSA key (generated by Ubuntu) to ed25519? Or it is required to generate ed25519 only in Windows?

@manojampalam 
> GitHub releases have full support for all key types. RSA keys are supported too.

You mean OpenSSH installed from this GIT repo and installed from Windows Settings are different?

**Comment by manojampalam** [comment]
You cannot convert keys from one type to another. 

OpenSSH installed from Windows settings is a limited version (supports only one key type and a limited set of crypto algorithms) of the more comprehensive version released on GitHub

**Comment by Suncatcher** [comment]
Thx for info. Should I delete built-in Windows client prior to installing Git version?

**Comment by manojampalam** [comment]
They can work side by side but may be end up causing confusion. If you don't need the built-in client, recommend uninstalling it.

**Comment by Suncatcher** [comment]
> of the more comprehensive version released on GitHub

@manojampalam, okay, I read [this stuff](https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Status) and they say:

> Win32-OpenSSH will be deprecated once changes in PowerShell/openssh-portable are integrated back into openssh/openssh-portable

So I wanna ask, should I install the client from [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH) or better use [openssh-portable](https://github.com/PowerShell/openssh-portable)? Do they differ in features?

**Comment by manojampalam** [comment]
Win32-OpenSSH and PowerShell/openssh-portable are the same. We do development in PowerShell/openssh-portable and maintain issues, do releases in Win32-OpenSSH (we are stuck this way for legacy reasons).

**Comment by CMCDragonkai** [comment]
I just tried the most recent openssh from chocolatey. Which installed the version 8. It still failed on my RSA key that is password protected.

**Comment by bagajjal** [comment]
This should be fixed by now.
Please create new issue if you still have issues.

**Comment by cdhunt** [comment]
@bagajjal What release is this fixed in?

**Comment by bagajjal** [comment]
@cdhunt - This thread has two issues.
1) rsa key is not working 
The initial version of openssh into windows (like 2 years back) support only ed25519. We added crypto library support using libressl in the next windows release. 
This is expected and we provided a feature update to support different crypto keys.

2) rsa key with passphrase is not working.
We never have this problem.
