### ISSUE TITLE
Passwordless ssh failing between AIX and Windows 2012 R2

### ISSUE THREAD

**Issue by r-madhumitha** [PowerShell/Win32-OpenSSH#974]
**"OpenSSH for Windows" version 0.0.22.0
**Server OperatingSystem** Windows 2012 R2
 **Client OperatingSystem** AIX 7.1

sftp through Passwordless ssh connection is failing. SFTP is successful using password.

**Expected output**
After the ssh key exchange, the sftp command from AIX must not prompt for a password.
**Actual output**
Even though in sshd logs I see that the RSA key is found, passwordless authentication is failing and prompting for a password.
Attached sshd, ssh-agent and sshd_config files.

[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1523174/sshd_config.txt)
[ssh-agent.log](https://github.com/PowerShell/Win32-OpenSSH/files/1523166/ssh-agent.log)
[sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/1523167/sshd.log)

**Comment by bagajjal** [comment]
Looks like sshd is not running under the context of "NTService\sshd".. 

For this reason sshd, ssh-agent were not able to communicate.

From ssh-agent log,
5292 14:21:39:385 error: cannot process request: client process is not admin or sshd
5292 14:21:39:385 debug1: connection 000000C30CA1D6E0 clean up


From sshd.log,
5548 14:21:39:354 debug1: matching key found: file C:\\Users\\user1\\.ssh/authorized_keys, line 1 RSA SHA256:TJOtdjyFmlFiQZQfgtx8xlylS6R6+Wwy4C9/flwx4to
5548 14:21:39:385 debug1: unable to send pubkeyauth request
5548 14:21:39:385 debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa
5548 14:21:39:385 Failed publickey for ACCOUNTS\\user1 from 10.123.543.12 port 59802 ssh2: RSA SHA256:TJOtdjyFmlFiQZQfgtx8xlylS6R6+Wwy4C9/flwx4to

**Comment by r-madhumitha** [comment]
Yes. sshd and ssh-agent are running as local system. I was not able to start the sshd service as NTSERVICE\sshd. Is there a way to fix this?

**Comment by bagajjal** [comment]
I would suggest you fix the issue why the sshd service is not running as NTService\sshd.

Please follow the install instructions.. 
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH
(or)
install using chocolatey
https://chocolatey.org/packages/openssh
