### ISSUE TITLE
[Not Urgent] Can someone explain this paragraph of the wiki?

### ISSUE THREAD

**Issue by changemenemo** [PowerShell/Win32-OpenSSH#977]
The sshd have been installed under server 2016.
I would like to put powershell as default shell but I didn't quite understand this paragraph. 

> If you are configuring the powershell.exe/cmd.exe/WSL-bash.exe as default ssh shell then you can ignore Computer\HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH\DefaultShellCommandOption. Your registry should look like this.

because on the image there was just powershell.exe and not the rest. So should I put the entire :  `powershell.exe/cmd.exe/WSL-bash.exe` ? And what about the key mentioned in this paragraph?  Sorry  it is certainly stupid questions but I would like to have some clarification. Thanks

**Comment by bagajjal** [comment]
Populate the powershell full path as shown in the picture 

https://user-images.githubusercontent.com/23668037/32013581-67206dca-b970-11e7-8820-fde658d302c1.png

**Comment by bagajjal** [comment]
please reopen if you have issues..
