### ISSUE TITLE
SSH Logs interpretation of date/ time

### ISSUE THREAD

**Issue by goncalogracamelo** [PowerShell/Win32-OpenSSH#978]
This must be a very basic question but I have been searchin for some some time and havent figured out.

In the logs, whats the meaning of the first number:"13720", should this be the date?

For example:
13720 18:29:00:557 debug1: Bind to port 22 on ::.
13720 18:29:00:557 Server listening on :: port 22.

Can some help.
Thanks

**Comment by manojampalam** [comment]
ProcessID

**Comment by goncalogracamelo** [comment]
Thank you for the very quick response.

How, can we add the date like "2017-01-01" to the time value that is being written?
Thanks again.
