### ISSUE TITLE
VNC session not going through OpenSSH - PuTTY tunnel

### ISSUE THREAD

**Issue by DaburLal** [PowerShell/Win32-OpenSSH#980]
**Server OperatingSystem**
 `Windows 7 - sshd

**Client OperatingSystem**

Wndows 7 - PuTTY

**What is failing**

VNC session not going through OpenSSH - PuTTY tunnel

**Expected output**

VNC session should go through the established tunnel

I am trying to secure my VNC session using OpenSSH(ssshd) and Putty(client)(everything is on windows)

First I establish a tunnel using putty and then log into my server PC using username and password

Second, I turn on my VNC client and server on the respective sides.

The problem i am facing is that my vnc session is not going through the tunnel.

1 - Following is the command which i am using to establish the tunnel putty.exe -ssh w21821@10.31.128.23 -L 5900:10.31.128.23:5900
2 - Following is my SSHD_config file , 
[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1531622/sshd_config.txt)

When I give this command ond on the client side, netstat -aon | find ":5900" I get this
![unbenannt](https://user-images.githubusercontent.com/32668117/33613845-f76e656e-d9d5-11e7-929f-5776675bc2f7.PNG)

In this picture, first is the example of vnc session through the tunnel, whereas the others are not going through the tunnel.

I got the 1st output only once, since then the same output appears again and again.

Can someone guide me on this??

Thanks in advance!!

**Comment by manojampalam** [comment]
Did you try doing this with ssh.exe client? Is it local port forwarding or remote port forwarding?

**Comment by manojampalam** [comment]
dup #979
