### ISSUE TITLE
Bad tun device 

### ISSUE THREAD

**Issue by DaburLal** [PowerShell/Win32-OpenSSH#981]
Using ssh to establish a tunnel , it says bad tun device.

Here is what is obtained after ssh -vvv w21821@10.31.128.23

PS C:\Windows\system32> ssh -vvv w21821@10.31.128.23
OpenSSH_7.6p1, LibreSSL 2.5.3
debug3: Failed to open file:C:\\Users\\w21821/.ssh/config error:2
debug3: Failed to open file:./ssh_config error:2
debug2: resolving "10.31.128.23" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 10.31.128.23 [10.31.128.23] port 22.
debug1: Connection established.
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_rsa error:2
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_rsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\w21821/.ssh/id_rsa type -1
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_rsa-cert error:2
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_rsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\w21821/.ssh/id_rsa-cert type -1
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_dsa error:2
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_dsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\w21821/.ssh/id_dsa type -1
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_dsa-cert error:2
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_dsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\w21821/.ssh/id_dsa-cert type -1
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_ecdsa error:2
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_ecdsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\w21821/.ssh/id_ecdsa type -1
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_ecdsa-cert error:2
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_ecdsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\w21821/.ssh/id_ecdsa-cert type -1
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_ed25519 error:2
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_ed25519.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\w21821/.ssh/id_ed25519 type -1
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_ed25519-cert error:2
debug3: Failed to open file:C:\\Users\\w21821/.ssh/id_ed25519-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\w21821/.ssh/id_ed25519-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.6
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6
debug1: match: OpenSSH_7.6 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 10.31.128.23:22 as 'w21821'
debug3: hostkeys_foreach: reading file "C:\\Users\\w21821/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file C:\\Users\\w21821/.ssh/know
n_hosts:1
debug3: load_hostkeys: loaded 1 keys from 10.31.128.23
debug3: Failed to open file:C:\\Users\\w21821/.ssh/known_hosts2 error:2
debug3: Failed to open file:./ssh_known_hosts error:2
debug3: Failed to open file:./ssh_known_hosts2 error:2
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@open
ssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@op
enssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2
-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sh
a256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-
group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ex
t-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2
-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sh
a2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh
.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256
-ctr
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256
-ctr
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-25
6-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-6
4@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-25
6-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-6
4@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2
-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sh
a256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-
group14-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp2
56,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256
-ctr
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256
-ctr
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-25
6-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-6
4@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-25
6-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-6
4@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit
> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit
> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:cpynmDiQP5TzjW20iPwPdUHQ01GN
SB0g7VIVRus24hg
debug3: hostkeys_foreach: reading file "C:\\Users\\w21821/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file C:\\Users\\w21821/.ssh/know
n_hosts:1
debug3: load_hostkeys: loaded 1 keys from 10.31.128.23
debug3: Failed to open file:C:\\Users\\w21821/.ssh/known_hosts2 error:2
debug3: Failed to open file:./ssh_known_hosts error:2
debug3: Failed to open file:./ssh_known_hosts2 error:2
debug1: Host '10.31.128.23' is known and matches the ECDSA host key.
debug1: Found key in C:\\Users\\w21821/.ssh/known_hosts:1
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug2: key: id_rsa (000000000048AF30), agent
debug2: key: id_rsa (000000000048AF80), agent
debug2: key: C:\\Users\\w21821/.ssh/id_rsa (0000000000000000)
debug2: key: C:\\Users\\w21821/.ssh/id_dsa (0000000000000000)
debug2: key: C:\\Users\\w21821/.ssh/id_ecdsa (0000000000000000)
debug2: key: C:\\Users\\w21821/.ssh/id_ed25519 (0000000000000000)
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rs
a-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password,keyboard-interacti
ve
debug3: start over, passed a different list publickey,password,keyboard-interact
ive
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:H+JOH6I1uoKbl+4w8F4iZ9VoX+jR2cFwWH7kqfsm
UHg id_rsa
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password,keyboard-interacti
ve
debug1: Offering public key: RSA SHA256:KSXthUnfaxVRlK2eXm0h175OFNXuGFlfkK/IAOp1
D/I id_rsa
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password,keyboard-interacti
ve
debug1: Trying private key: C:\\Users\\w21821/.ssh/id_rsa
debug3: GetFileAttributesExW with last error 2
debug3: no such identity: C:\\Users\\w21821/.ssh/id_rsa: No such file or directo
ry
debug1: Trying private key: C:\\Users\\w21821/.ssh/id_dsa
debug3: GetFileAttributesExW with last error 2
debug3: no such identity: C:\\Users\\w21821/.ssh/id_dsa: No such file or directo
ry
debug1: Trying private key: C:\\Users\\w21821/.ssh/id_ecdsa
debug3: GetFileAttributesExW with last error 2
debug3: no such identity: C:\\Users\\w21821/.ssh/id_ecdsa: No such file or direc
tory
debug1: Trying private key: C:\\Users\\w21821/.ssh/id_ed25519
debug3: GetFileAttributesExW with last error 2
debug3: no such identity: C:\\Users\\w21821/.ssh/id_ed25519: No such file or dir
ectory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup keyboard-interactive
debug3: remaining preferred: password
debug3: authmethod_is_enabled keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug2: userauth_kbdint
debug3: send packet: type 50
debug2: we sent a keyboard-interactive packet, wait for reply
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password,keyboard-interacti
ve
debug3: userauth_kbdint: disable: no info_req_seen
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred:
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
debug3: failed to open file:/dev/tty error:3
debug1: read_passphrase: can't open /dev/tty: No such file or directory
w21821@10.31.128.23's password:

**Comment by Cambridgeport90** [comment]
I don’t think it’s the client.

**Comment by DaburLal** [comment]
@Cambridgeport90 , I was able to establish tunnel using ssh
