### ISSUE TITLE
I am getting the error below after installing OpenSSH Win64 0.0.22.0 on Windows 2016 machine in Azure.  Couldn't Create pid file "./sshd.pid": Permission Denied

### ISSUE THREAD

**Issue by Leon-Straathof** [PowerShell/Win32-OpenSSH#982]
I am getting the error below in the logfile "C:\Program Files\OpenSSH\logs\sshd.log" after installing OpenSSH Win64 0.0.22.0 on Windows 2016 machine in Azure.  

Couldn't Create pid file "./sshd.pid": Permission Denied

Self investigation into the problem:

Permissions are not set on folder "C:\Program Files\OpenSSH\logs\" but only on file "C:\Program Files\OpenSSH\logs\sshd.log".

Default (no PidFile setting in sshd_config) SSHD tries to write file "sshd.pid" to folder "C:\Program Files\OpenSSH\".

Self made work around (needed until fixed):
Give account "NT SERVICE\SSHD" R/W permissions on folder "C:\Program Files\OpenSSH\logs\".
Set "PidFile ./logs/sshd.pid" in settings file "C:\Program Files\OpenSSH\sshd_config".

Actualy writing logs and other files under "C:\Program Files" in itself is a windows security violation. For something that possibly gives connetion to the big bad world outside the location for a service or any other piece of software should be under "C:\Programdata" if the data in the written files are machine bound like the files of SSHD. Or in a user profile if the data is user bound.

**Comment by manojampalam** [comment]
This will be fixed in next drop. this file will be logged under %PROGRAMDATA%\ssh
