### ISSUE TITLE
$SSH_AUTH_SOCK fails to work with Gpg4win's gpg-agent

### ISSUE THREAD

**Issue by charabaruk** [PowerShell/Win32-OpenSSH#985]
**"OpenSSH for Windows" version**
 0.0.23.0
 
**Server OperatingSystem**
 N/A

**Client OperatingSystem**
 Windows 10 Pro Insider Preview

**What is failing**
`ssh` and `ssh-add -L` fail to retrieve keys from `gpg-agent` supplied with Gpg4win package when `$SSH_AUTH_SOCK` is set up instead of the `ssh-agent` service.

**Expected output**
```
$ ssh-add -L
ssh-rsa ... ...
```

**Actual output**
```
$ ssh-add -L
error fetching identities: invalid format
```

**Additional notes**

By comparing log output from a good session using `ssh-agent` to a session using a sock from `gpg-agent` the difference I see leading up to a connection is `debug2: key: [IDENTITYNAME] ([FINGERPRINT]), agent` when things are successful, versus `debug1: pubkey_prepare: ssh_fetch_identitylist: invalid format` when they aren't.

**Comment by charabaruk** [comment]
I just noticed that issue #827 already exists to cover this situation. Oops.

**Comment by vovcacik** [comment]
Yeah looks like #827, but [notice that I used official gpg build for Windows][1] and not Gpg4Win. But it should be about the same.

[1]: https://github.com/PowerShell/Win32-OpenSSH/issues/827#issuecomment-321972634

**Comment by charabaruk** [comment]
@vovcacik You might not be aware of this but Gpg4win packages the official GPG installer and runs that internally. Latest Gpg4win includes gnupg 2.2.3 build 20171120. There's nothing "unofficial" about the GPG build included in Gpg4win.

**Comment by vovcacik** [comment]
@coldacid Ah, good to know. Last time I installed gpg4win I think it had outdated version of gpg, which seems not to be true anymore. Then I found lighter build on gpg's ftp server that was better fit for me.
