### ISSUE TITLE
New connections hang after a client sends ^C

### ISSUE THREAD

**Issue by paulmcenaney** [PowerShell/Win32-OpenSSH#986]
**"OpenSSH for Windows" version**
0.0.24.0
Installed from chocolatey repo.
 
**Server OperatingSystem**
Windows 10; Version 1709 (OS build 16299.64)

**Client OperatingSystem**
Windows 10; Version 1709 (OS build 16299.64)
(Same as server; connecting to itself from Ubuntu for Windows)

**What is failing**
After a client sends ^C (Ctrl+C, if you prefer the Windowsy way of writing it) to interrupt a command, openSSH-Win64\sshd.EXE no longer accepts new connections.
New connections aren't rejected, and don't receive a tcp reset; they just hang, prior to the password prompt.

The existing connection doesn't appear to be affected.

**Comment by paulmcenaney** [comment]
Here's ssh -vvv for one of the borked connections.
User, host, and domain have been replaced with "foo", "bar", and "baz", respectively.

```
foo@bar:~$ ssh -vvv -l foo@baz.test bar
OpenSSH_7.2p2 Ubuntu-4ubuntu2.2, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "bar" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to bar [127.0.1.1] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /home/foo/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/foo/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/foo/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/foo/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/foo/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/foo/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/foo/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/foo/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
```

It appears to fail before successfully getting the remote protocol version. (Compare against -vvv from any normal connection. I can include that if necessary.)

**Comment by manojampalam** [comment]
Can you try out the latest release and share sshd logs?

**Comment by paulmcenaney** [comment]
No change in behavior on 1.0.0.20180201. (Again, installed through NuGet/Chocolatey... _Shouldn't_ matter.)

^C (Ctrl+C) is still not processed as an interrupt in the remote CMD/console session.
Second SSH process still not able to connect after the ^C is sent by the first session.

Happy to attach the sshd log if someone can tell me where to find it. I've searched the sshd binary directory, ProgramData, AppData, and a few other suspect locations to no avail, thus far. This (https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps) appears to indicate it should be in the install directory, alongside ssh-agent.log... but not luck, there. (Even with LogLevel set to DEBUG.) ssh-agent.log does seem to be updated, though...

Running the server directly from the commandline with the -d option does print debug info... but I'm not able to connect the client, with this method. Client dies with "Broken Pipe" messages, and the server prints:

Starting session: shell on console for epic\pmcenane from 2620:72:0:f45:: port 59754
debug1: pipe - read end: handle:00000000000001C4, io:000001DD2167A420, fd:7
debug1: pipe - write end: handle:00000000000001C8, io:000001DD216791A0, fd:8
debug1: pipe - read end: handle:00000000000001CC, io:000001DD216549F0, fd:9
debug1: pipe - write end: handle:00000000000001D0, io:000001DD21654AA0, fd:10
debug1: pipe - read end: handle:00000000000001D4, io:000001DD21654B50, fd:11
debug1: pipe - write end: handle:00000000000001D8, io:000001DD21654C00, fd:12
debug1: <- GetHomeDirFromToken()...
debug1: socketio_getsockname - ERROR:14
getsockname failed: Bad address
debug1: socketio_getsockname - ERROR:14
debug1: socketio_getsockname - ERROR:14
getsockname failed: Bad address
debug1: Executing command: ssh-shellhost.exe
debug1: ERROR. Cannot create process as new user (1314).


Let me know how I can get you a server log, and I'll test again.

**Comment by manojampalam** [comment]
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

Get sshd server logs (not sshd in debug mode that accepts only one connection).

**Comment by paulmcenaney** [comment]
That link does not appear to contain correct information regarding the logs directory.
> Delete sshd.log and ssh-agent.log (in the logs directory of your installation path)

The installation path is c:\ProgramFiles\OpenSSH-Win64\.
ssh-agent.log is in the install location itself; not a logs subdirectory. Neither the logs subdirectory, nor the sshd.log exist in that directory tree. To be clear: there are NO subdirectories in the install location.

**Comment by manojampalam** [comment]
Thanks. Its now fixed. It should be %programdata%\ssh\logs

**Comment by paulmcenaney** [comment]
Does the fix require a new build of the server, or was it merely an update to the wiki entry..?
%programdata%\ssh\ does not exist on my system, running sshd 1.0.0.20180201.

Looks like Chocolatey may install sshd with LogLevel QUIET by default.
I've previously edited sshd_config to include the following line, without success.
LogLevel DEBUG

Does the log path need to be added to sshd_config, somehow? (Doesn't seem to be a standard option in the *NIX sshd_config, since it uses syslog facilities...)

**Comment by manojampalam** [comment]
No. Its just a wiki entry fix. 

Logs dir should have been created as part of installation. 
%programdata%\ssh\ also should exist on your system. (host keys would be read from this folder). Double check please. 

As for log files, yes, this is something specific to Windows.

**Comment by bagajjal** [comment]
Any update?

**Comment by paulmcenaney** [comment]
Finally had time to sit down with ProcMon and figure out what, exactly, is going on, here.

First, the log file is NOT created in %programdata%\ssh\. It's created in %programfiles%\OpenSSH-Win64\, along with everything else.
Second, the sshd.exe process receives an "ACCESS DENIED" result on the CreateFile operation on sshd.log.

Here's the block of file operations of interest. 

```
10:31:11.9825338 AM	sshd.exe	18856	CreateFile	C:\Program Files\OpenSSH-Win64\sshd.log	ACCESS DENIED	Desired Access: Generic Write, Read Attributes, Disposition: OpenIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0
10:31:11.9851645 AM	sshd.exe	18856	CreateFile	C:\Program Files\OpenSSH-Win64\sshd.log	ACCESS DENIED	Desired Access: Generic Write, Read Attributes, Disposition: OpenIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0
10:31:11.9904597 AM	sshd.exe	18856	CreateFile	C:\Program Files\OpenSSH-Win64\sshd.log	ACCESS DENIED	Desired Access: Generic Write, Read Attributes, Disposition: OpenIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0
10:31:11.9940783 AM	sshd.exe	18856	CreateFile	C:\Program Files\OpenSSH-Win64\sshd.log	ACCESS DENIED	Desired Access: Generic Write, Read Attributes, Disposition: OpenIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0
10:31:11.9981289 AM	sshd.exe	18856	CreateFile	C:\Program Files\OpenSSH-Win64\sshd.log	ACCESS DENIED	Desired Access: Generic Write, Read Attributes, Disposition: OpenIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0
10:31:12.0017993 AM	sshd.exe	18856	CreateFile	C:\Program Files\OpenSSH-Win64\sshd.log	ACCESS DENIED	Desired Access: Generic Write, Read Attributes, Disposition: OpenIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0
10:31:12.0056954 AM	sshd.exe	18856	CreateFile	C:\Program Files\OpenSSH-Win64\sshd.log	ACCESS DENIED	Desired Access: Generic Write, Read Attributes, Disposition: OpenIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0
10:31:12.0096305 AM	sshd.exe	18856	CreateFile	C:\Program Files\OpenSSH-Win64\sshd.log	ACCESS DENIED	Desired Access: Generic Write, Read Attributes, Disposition: OpenIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0
10:31:12.0171029 AM	sshd.exe	18856	CreateFile	C:\Program Files\OpenSSH-Win64\sshd.log	ACCESS DENIED	Desired Access: Generic Write, Read Attributes, Disposition: OpenIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0
```


Adding the "NT SERVICE\sshd" user principle to the ACL list on %programfiles%\OpenSSH-Win64 allowed both the sshd.log and sshd.pid files to be created; neither had previously existed.

***************************************************************
Now that THAT's resolved, here's the timing for the test and attached log. Spread them out a bit, so it's easy to pick apart what goes together in the log.

10:55 - start SSHD service
10:56 - first connection from my Linux box; run some commands
10:57 - ^C sent
10:58 - Run a few more commands from the original Linux connection
10:59 - Attempt second connection
10:59:51 - Disconnect original session
11:00 - Stop SSHD service
***************************************************************

The resulting log is attached.
[sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/1741073/sshd.log)

**Comment by manojampalam** [comment]
Looked at the traces. Looks like your Ctrl+C somehow made it to the main service process. This shouldn't happen. Can you get debug3 traces to take this further?
