### ISSUE TITLE
scp - file name wildcards error - Protocol not available

### ISSUE THREAD

**Issue by robehub** [PowerShell/Win32-OpenSSH#988]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
0.0.24.0 32/64bit
 
**Server OperatingSystem**
Solaris 10

**Client OperatingSystem**
Windows 7

**What is failing**
scp.exe -F .\ssh_config test*.txt user@host:/home/user/

**Expected output**
"test1.txt                                     100%   10     0.0KB/s   00:00"

**Actual output**
"test*.txt: Protocol not available"

**Comment by bingbing8** [comment]
It has been fixed by PR  https://github.com/PowerShell/openssh-portable/pull/283

**Comment by Fuseteam** [comment]
this seems to be an issue when using it in the form of `folder/*` from the windows side

**Comment by dzmitry-lahoda** [comment]
it happened on one of our servers... @Churs, what our version of windows and ssh-scp?

On my Windows `scp -rp *.ps1 $user@${computer}:$root` works fine. On Jenkins server we get `Protocol not available `


On bad server
```
Microsoft Windows [Version 10.0.17134.706]

scp 7.6.0.0
```

Old version.
