### ISSUE TITLE
Failed connecting to legacy devices

### ISSUE THREAD

**Issue by ghost** [PowerShell/Win32-OpenSSH#989]
I have a group of legacy UPS devices, while connecting  with putty are successful, connections using Win32-OpenSSH always fails (all versions). 

C:\WINDOWS\system32>ssh -c aes256-cbc RemoteUsername@11.170.184.40 -vvv
OpenSSH_7.6p1, LibreSSL 2.5.3
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/config error:2
debug3: Failed to open file:./ssh_config error:2
debug2: resolving "11.170.184.40" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 11.170.184.40 [11.170.184.40] port 22.
debug1: Connection established.
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_rsa error:2
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_rsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\UserMyself/.ssh/id_rsa type -1
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_rsa-cert error:2
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_rsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\UserMyself/.ssh/id_rsa-cert type -1
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_dsa error:2
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_dsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\UserMyself/.ssh/id_dsa type -1
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_dsa-cert error:2
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_dsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\UserMyself/.ssh/id_dsa-cert type -1
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_ecdsa error:2
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_ecdsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\UserMyself/.ssh/id_ecdsa type -1
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_ecdsa-cert error:2
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_ecdsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\UserMyself/.ssh/id_ecdsa-cert type -1
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_ed25519 error:2
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_ed25519.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\UserMyself/.ssh/id_ed25519 type -1
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_ed25519-cert error:2
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/id_ed25519-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\UserMyself/.ssh/id_ed25519-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.6
debug1: Remote protocol version 2.0, remote software version SSH_2.0
debug1: no match: SSH_2.0
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 11.170.184.40:22 as 'RemoteUsername'
debug3: hostkeys_foreach: reading file "C:\\Users\\UserMyself/.ssh/known_hosts"
debug3: Failed to open file:C:\\Users\\UserMyself/.ssh/known_hosts2 error:2
debug3: Failed to open file:./ssh_known_hosts error:2
debug3: Failed to open file:./ssh_known_hosts2 error:2
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellm
an-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecd
sa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: aes256-cbc
debug2: ciphers stoc: aes256-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: ssh-dss,ssh-rsa
debug2: ciphers ctos: aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: hmac-sha1,hmac-md5
debug2: MACs stoc: hmac-sha1,hmac-md5
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: diffie-hellman-group-exchange-sha1
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes256-cbc MAC: hmac-sha1 compression: none
debug1: kex: client->server cipher: aes256-cbc MAC: hmac-sha1 compression: none
debug3: send packet: type 34
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(2048<8192<8192) sent
debug3: receive packet: type 1
Received disconnect from 11.170.184.40 port 22:2: protocol error
Disconnected from 11.170.184.40 port 22

**Comment by bagajjal** [comment]
please share us the sshd.log (DEBUG3 enabled)...

from the ssh client logs its unclear why the sshd server is sending protocol error.
Received disconnect from 11.170.184.40 port 22:2: protocol error

**Comment by bagajjal** [comment]
please reopen if required with requested information.
