### ISSUE TITLE
Short username support in ssh client

### ISSUE THREAD

**Issue by adaugherity** [PowerShell/Win32-OpenSSH#991]
When you don't specify a username, the ssh client apparently uses `user@domain` rather than just `user` as I would expect.  Apologies if this is expected behavior and documented somewhere, but I could not find any such documentation. 

I realize defaulting to user@domain may make sense in the Windows world, but to me, a longtime *NIX user, it does not match what I expect from ssh.

**"OpenSSH for Windows" version**
 `0.0.18.0` (installed OpenSSH client via Windows 10 v1709 optional features; same behavior in 0.0.24.0 tarball download)
 
**Server OperatingSystem**
 any UNIX

**Client OperatingSystem**
Windows 10 v1709 (also 8.1 and anything else win32-openssh runs on)

**What is failing**
`ssh servername` (without specifying a username) fails. 

This is because it is attempting to login to the server as `user@domain` (on a domain member) or `user@machine_name` (name of client machine if not a domain member), rather than just `username`, which is what the server expects.  Perhaps it's combining the Windows environment variables `%USERNAME%@%USERDOMAIN`?

**Expected output**
Login is attempted as `%USERNAME%` which succeeds.

Server's system log:
`sshd[25343]: Accepted keyboard-interactive/pam for adaugherity from a.b.c.d port 49699 ssh2`

**Actual output**
Login is attempted with the `@domain` part appended, with no indication given on the client.   I discovered the issue by checking the server's log:
```
sshd[25328]: Invalid user adaugherity@AD-W10VM from a.b.c.d
sshd[25328]: input_userauth_request: invalid user adaugherity@AD-W10VM [preauth]
```

**Comment by FranklinYu** [comment]
Currently my work-around is to specify it in `%USERPROFILE%\.ssh\config`, but it would be greatly appreciated if it can default to short name when I'm using the client.

**Comment by manojampalam** [comment]
Thanks for the feedback. I believe we can resolve it to just "user" if its a local account and "user@domain" for a domain account.

**Comment by yecril71pl** [comment]
No, you cannot.  "user@domain" makes sense only if the host is Windows, which is not the case in a mixed environment.  Use "_@domain" only if you can detect that the host expects it.
