### ISSUE TITLE
ssh-keygen doubling up hostname in .pub

### ISSUE THREAD

**Issue by ThomasEBoland** [PowerShell/Win32-OpenSSH#993]
**"OpenSSH for Windows" version**
0.0.18.0

Loaded from *Optional Features* (the standard way) on 2017-12-14.
 
**Client OperatingSystem**
Windows 10 Pro 64-bit

**What is failing**
ssh-keygen.exe

Simple beta problem. The user@host comment at the end of the .pub is doubling up the hostname.
Happened on both my computers at home. 
_No_ impact on operations, It's just a comment and can be edited down to user@host by user. Not a killer in any way, but shows a lack of polish for a release version. For beta, this is fine. It's what we're supposed to find. 

Edit: There may be use-cases where that comment is actually used or verified. Therefore, it *could* have impact, but under interesting circumstances. As user@host@host is certainly not expected, it could drive someone out-of-their-mind-nuts trying to find this problem.

**Expected output**
user@host

**Actual output**
user@host@host

**Comment by bagajjal** [comment]
it will be in user@domain@machinename format.
is domain& machinename same in your case?
This is just a comment so it will not do any harm.

**Comment by ThomasEBoland** [comment]
That explains it. Good enough. Close it.

I don't use an identified domain on these computers. Also, different from the Linux machines I have seen, which were all user@host.
