### ISSUE TITLE
Cannot invoke remote commands using bash -c

### ISSUE THREAD

**Issue by k-y** [PowerShell/Win32-OpenSSH#994]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
0.0.24
 
**Server OperatingSystem**
Windows Server 2016 Datacenter

**Client OperatingSystem**
CentOS 7.1.1503

**What is failing**
DefaultShell = C:\cygwin64\bin\bash.exe

We cannot execute scripts remotely using 'bash -c'.
Remote commands such as 'hostname' work as expected but when testing:
ssh -i sshkey user@host 'bash -c "cd /cygdrive/c/Temp && ls"'
We get an interactive shell instead of a remote script invocation.

**Expected output**
(Contents of /cygdrive/c/Temp)

**Actual output**
(Interactive bash shell)

**Comment by bagajjal** [comment]
on the ssh server side, did you configure Defaultshell  in the windows registry(HKLM\SOFTWARE\OpenSSH\DefaultShell)? If yes then there is no need to mention bash -c.

**Comment by bagajjal** [comment]
Any update on this?

**Comment by bagajjal** [comment]
please reopen if required.
