### ISSUE TITLE
Error: Accept: Connection Reset

### ISSUE THREAD

**Issue by jems99** [PowerShell/Win32-OpenSSH#997]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`

Latest build
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Server 2008 R2

**Client OperatingSystem**

**What is failing**
After about 10 minutes we get this error "Error: Accept: Connection Reset". This causes SFTP to stop working completely and the log file to grow exponentially. 

**Expected output**

**Actual output**

**Comment by cxhercules** [comment]
I started getting this all weekend, several times per second after about 10 hours possibly and disk space was filled by a sshd.log of 16 gigs. 

"OpenSSH for Windows" version: v0.0.22.0

Server OperatingSystem: 2012r2 build 9600

Client OperatingSystem

What is failing:
We are getting constant error message "Error: Accept: Connection Reset" and this has filled disk space.

**Comment by bagajjal** [comment]
Can you provide the sshd.log with DEBUG3 enabled..
Are you seeing this issue all the time?
Also have you tried restarting sshd deamon process (net stop sshd; net start sshd)? Did it help?

Unfortunately we don't have log throttling mechanism as our long term goal is to move away from log file to windows logging..

As a workaround to throttle the sshd log,
create a task scheduler task that would run the following PowerShell script (edit as needed) at intervals. It empties contents of sshd.log into a backup file once sshd.log breaches 25MB
```
if ((Get-ChildItem .\logs\sshd.log).Length -gt 2510241024)
{
copy-item .\logs\sshd.log .\logs\sshd.log.prev
$null | Set-Content .\logs\sshd.log
}

```

**Comment by jems99** [comment]
For me the log is this message over and over: Error: Accept: Connection Reset

When the application gets into this state no connections can be established. Restarts both services fixes the issue for about 10 minutes and then it happens again. Right now we can't use SFTP because of this.

**Comment by jems99** [comment]
I can run in DEBUG3 and provide shortly.

**Comment by cxhercules** [comment]
Yes seems related to issue https://github.com/PowerShell/Win32-OpenSSH/issues/935 and will see if I can set to debug3 and set this task in place as well. 

Thanks

**Comment by bagajjal** [comment]
it would be great if you can repro the issue and provide the complete log file that covers service restart, working for 10 minutes and start seeing the issue again..

issue #935 is about log throttling but not related to this.

**Comment by cxhercules** [comment]
This morning came in and everything was down because all disk were full on ssh enabled windows systems so had to quickly get them back up and running, but did investigate on one system and that is how I found the log file. I will add more info as I gather it, thanks.

**Comment by cxhercules** [comment]
Well it relates to this in that it filled the disk space or create huge log file, but understood. I thought maybe they just did not show the error message that filled the log. Seemed to me it could have been same error.

**Comment by bagajjal** [comment]
If you have a close look at the #935 description, they are using 0.0.10.0 (might be a year old).. The current version is 0.0.24.0..

**Comment by cxhercules** [comment]
I did see that, and thank you.

**Comment by cxhercules** [comment]
@bagajjal by the way I tested your script and works, but 25MB should be represented as 26214400.

**Comment by bagajjal** [comment]
This might be related to #787

fyi, we couldn't reproduce #787 as well and we don't have proper logs (DEBUG3 enabled)..
It would be great if you can provide sshd.log with DEBUG3 enabled so that we can analyze from log file.

**Comment by cxhercules** [comment]
Thank you I will check with team to find out if these systems are in fact being scanned. I will set some systems to debug3 in effort to resolve this issue.

**Comment by bagajjal** [comment]
Any update on this

**Comment by manojampalam** [comment]
We had a recent fix in transport that might potentially resolve this. Try out the latest release 1.0.0.0, reopen if you still see this.
